// 고린도후서 10장 · 2Corinthians 10
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Corinthians",10,18);
BibleDB.add([
  {Bible:"2Corinthians", Chapter:10, Verse:1, Page:1, Kor:"<바울이 자기의 사도직을 변호하다> 나 바울은 그리스도의 온유하심과 관대하심을 힘입어서 여러분을 권면합니다. 내가 얼굴을 마주 대하고 있을 때에는 여러분에게 유순하나, 떠나 있을 때에는 여러분에게 강경하다고들 합니다.", Chn:"", Eng:"By the meekness and gentleness of Christ, I appeal to you--I, Paul, who am \"timid\" when face to face with you, but \"bold\" when away!", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:2, Page:1, Kor:"내가 여러분에게 청하는 것은, 내가 가서 여러분을 대할 때에 강경하게 대해야 할 일이 없게 해 달라는 것입니다. 그러나 우리가 육정을 따라서 처신한다고 여기는 사람들에게는 나는 확신을 가지고 담대하게 대하려고 생각합니다.", Chn:"", Eng:"I beg you that when I come I may not have to be as bold as I expect to be toward some people who think that we live by the standards of this world.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:3, Page:1, Kor:"우리가 육신을 입고 살고 있습니다마는, 육정을 따라서 싸우는 것은 아닙니다.", Chn:"", Eng:"For though we live in the world, we do not wage war as the world does.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:4, Page:1, Kor:"싸움에 쓰는 우리의 무기는, 육체의 무기가 아니라, 하나님 앞에서 견고한 요새라도 무너뜨리는 강력한 무기입니다. 우리는 궤변을 무찌르고,", Chn:"", Eng:"The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:5, Page:1, Kor:"하나님을 아는 지식을 가로막는 모든 교만을 쳐부수고, 모든 생각을 사로잡아서, 그리스도께 복종시킵니다.", Chn:"", Eng:"We demolish arguments and every pretension that sets itself up against the knowledge of God, and we take captive every thought to make it obedient to Christ.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:6, Page:1, Kor:"그리고 여러분이 온전히 순종하게 될 때에는, 우리는 모든 복종하지 않는 자를 처벌할 준비가 되어 있을 것입니다.", Chn:"", Eng:"And we will be ready to punish every act of disobedience, once your obedience is complete.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:7, Page:1, Kor:"○여러분은 겉모양만 봅니다. 누구든지 자기가 그리스도께 속한 사람이라고 확신한다면, 자기가 그리스도께 속한 사람인 것과 같이, 우리도 그리스도께 속한 사람이라는 것을 다시 한 번 스스로 명심해야 할 것입니다.", Chn:"", Eng:"You are looking only on the surface of things. If anyone is confident that he belongs to Christ, he should consider again that we belong to Christ just as much as he.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:8, Page:1, Kor:"주님께서 우리에게 주신 권위를 내가 좀 지나치게 자랑했다고 하더라도, 그 권위는 주님께서 여러분을 넘어뜨리라고 주신 것이 아니라, 세우라고 주신 것이므로, 나는 부끄러울 것이 없습니다.", Chn:"", Eng:"For even if I boast somewhat freely about the authority the Lord gave us for building you up rather than pulling you down, I will not be ashamed of it.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:9, Page:1, Kor:"나는 편지로 여러분에게 겁을 주려고 하는 것처럼 보이고 싶지는 않습니다.", Chn:"", Eng:"I do not want to seem to be trying to frighten you with my letters.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:10, Page:1, Kor:"\"바울의 편지는 무게가 있고, 힘이 있지만, 직접 대할 때에는, 그는 약하고, 말주변도 변변치 못하다\" 하고 말하는 사람들이 있습니다.", Chn:"", Eng:"For some say, \"His letters are weighty and forceful, but in person he is unimpressive and his speaking amounts to nothing.\"", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:11, Page:1, Kor:"이런 사람들은, 우리가 떠나 있을 때에 편지로 쓰는 말과, 함께 있을 때에 행하는 일 사이에는, 아무런 차이가 없다는 것을 알아야 합니다.", Chn:"", Eng:"Such people should realize that what we are in our letters when we are absent, we will be in our actions when we are present.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:12, Page:1, Kor:"○우리는 자기를 내세우는 사람들과 같은 부류가 되려고 하거나, 그들과 견주어 보려고 하지 않습니다. 그러나 그들은 자기를 척도로 하여 자기를 재고, 자기를 기준으로 하여 자기를 견주어 보고 있으니, 어리석기 짝이 없습니다.", Chn:"", Eng:"We do not dare to classify or compare ourselves with some who commend themselves. When they measure themselves by themselves and compare themselves with themselves, they are not wise.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:13, Page:1, Kor:"우리는 마땅한 정도 이상으로 자랑을 하려고 하지 않습니다. 우리가 여러분에게까지 다다른 것도, 하나님께서 우리에게 정하여 주신 한계 안에서 된 일입니다.", Chn:"", Eng:"We, however, will not boast beyond proper limits, but will confine our boasting to the field God has assigned to us, a field that reaches even to you.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:14, Page:1, Kor:"그러므로 우리는 여러분에게로 가지 못할 사람이 아닙니다. 우리가 여러분에게까지 가서 그리스도의 복음을 전한 것은, 한계를 벗어나서 행동한 것이 아닙니다.", Chn:"", Eng:"We are not going too far in our boasting, as would be the case if we had not come to you, for we did get as far as you with the gospel of Christ.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:15, Page:1, Kor:"우리는 주제 넘게 다른 사람들이 수고한 일을 가지고 자랑하려는 것이 아닙니다. 다만 바라는 것은 여러분의 믿음이 자람에 따라 우리의 활동 범위가 여러분 가운데서 더 넓게 확장되는 것입니다.", Chn:"", Eng:"Neither do we go beyond our limits by boasting of work done by others. Our hope is that, as your faith continues to grow, our area of activity among you will greatly expand,", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:16, Page:1, Kor:"우리는 여러분의 지역을 넘어서 a복음을 전하려는 것이요, 남들이 자기네 지역에서 이미 이루어 놓은 일을 가지고 자랑하려는 것이 아닙니다.(a 또는 '기쁜 소식')", Chn:"", Eng:"so that we can preach the gospel in the regions beyond you. For we do not want to boast about work already done in another man's territory.", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:17, Page:1, Kor:"b\"자랑하려는 사람은 주님 안에서 자랑해야 합니다.\"(b 렘 9:24)", Chn:"", Eng:"But, \"Let him who boasts boast in the Lord.\"", Ind:""},
  {Bible:"2Corinthians", Chapter:10, Verse:18, Page:1, Kor:"참으로 인정을 받는 사람은 스스로 자기를 내세우는 사람이 아니라, 주님께서 내세워 주시는 사람입니다.", Chn:"", Eng:"For it is not the one who commends himself who is approved, but the one whom the Lord commends.", Ind:""},
]);
