// 고린도후서 13장 · 2Corinthians 13
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Corinthians",13,13);
BibleDB.add([
  {Bible:"2Corinthians", Chapter:13, Verse:1, Page:1, Kor:"<마지막 경고와 인사> 나는 지금 세 번째로 여러분을 방문하려고 합니다. a\"모든 소송 사건은 두세 증인의 말을 근거로 하여 결정지어야 합니다.\"(a 신 19:15)", Chn:"", Eng:"This will be my third visit to you. \"Every matter must be established by the testimony of two or three witnesses.\"", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:2, Page:1, Kor:"내가 두 번째로 여러분을 방문하였을 때에, 전에 범죄한 사람들과 또 그 밖에 모든 사람에게 이미 말한 바와 같이, 지금 떨어져 있으면서도 다시 말하여 둡니다. 내가 이번에 다시 가면, 그러한 사람들을 그냥 두지 않겠습니다.", Chn:"", Eng:"I already gave you a warning when I was with you the second time. I now repeat it while absent: On my return I will not spare those who sinned earlier or any of the others,", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:3, Page:1, Kor:"여러분은 그리스도께서 내 안에서 말씀하고 계시다는 증거를 구하고 있으니 말입니다. 그리스도는 여러분에게 약하신 분이 아닙니다. 그는 여러분 가운데서 능력을 떨치시는 분입니다.", Chn:"", Eng:"since you are demanding proof that Christ is speaking through me. He is not weak in dealing with you, but is powerful among you.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:4, Page:1, Kor:"그분은 약하셔서 십자가에 못박혀 죽으셨지만, 하나님의 능력으로 살아 계십니다. 우리도 b그분 안에서 약합니다마는, 하나님의 능력으로 그분과 함께 살아나서, 여러분을 대할 것입니다.(b 다른 고대 사본들에는 '그와 함께 약하지만')", Chn:"", Eng:"For to be sure, he was crucified in weakness, yet he lives by God's power. Likewise, we are weak in him, yet by God's power we will live with him to serve you.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:5, Page:1, Kor:"○여러분은 자기가 믿음 안에 있는지를 스스로 시험해 보고, 스스로 검증해 보십시오. 여러분은 예수 그리스도께서 여러분 안에 계시다는 것을 알지 못합니까? 모른다면, 여러분은 실격자입니다.", Chn:"", Eng:"Examine yourselves to see whether you are in the faith; test yourselves. Do you not realize that Christ Jesus is in you--unless, of course, you fail the test?", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:6, Page:1, Kor:"그러나 나는 우리가 실격자가 아니라는 것을 여러분이 알게 되기를 바랍니다.", Chn:"", Eng:"And I trust that you will discover that we have not failed the test.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:7, Page:1, Kor:"우리는 여러분이 악을 저지르지 않게 되기를 하나님께 기도합니다. 그것은 우리가 합격자임을 드러내려는 것이 아니라, 우리는 실격자인 것처럼 보일지라도, 여러분만은 옳은 일을 하게 하려고 하는 것입니다.", Chn:"", Eng:"Now we pray to God that you will not do anything wrong. Not that people will see that we have stood the test but that you will do what is right even though we may seem to have failed.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:8, Page:1, Kor:"우리는 진리를 거슬러서는 아무것도 할 수 없고, 오직 진리를 위해서만 무언가 할 수 있습니다.", Chn:"", Eng:"For we cannot do anything against the truth, but only for the truth.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:9, Page:1, Kor:"우리는 약하더라도, 여러분이 강하면, 그것으로 우리는 기뻐합니다. 우리는 여러분이 완전하게 되기를 기도합니다.", Chn:"", Eng:"We are glad whenever we are weak but you are strong; and our prayer is for your perfection.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:10, Page:1, Kor:"내가 떠나 있는 동안에 이렇게 편지를 하는 것은, 내가 가서, 주님께서 주신 권한을 가지고 사건들을 처리할 때에, 너무 엄하게 대할 필요가 없게 하려는 것입니다. 이 권위는 여러분을 넘어뜨리라고 주신 것이 아니라 세우라고 주신 것입니다.", Chn:"", Eng:"This is why I write these things when I am absent, that when I come I may not have to be harsh in my use of authority--the authority the Lord gave me for building you up, not for tearing you down.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:11, Page:1, Kor:"○끝으로 말합니다. c형제자매 여러분, d기뻐하십시오. 온전하게 되기를 힘쓰십시오. e서로 격려하십시오. 같은 마음을 품으십시오. 화평하게 지내십시오. 그리하면 사랑과 평화의 하나님께서 여러분과 함께 하실 것입니다.(c 그, '형제들' d 또는 '안녕히 계십시오' e 또는 '내 호소에 귀를 기울여 주십시오')", Chn:"", Eng:"Finally, brothers, good-by. Aim for perfection, listen to my appeal, be of one mind, live in peace. And the God of love and peace will be with you.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:12, Page:1, Kor:"거룩한 입맞춤으로 서로 인사하십시오. 모든 성도가 여러분에게 문안합니다.", Chn:"", Eng:"Greet one another with a holy kiss.", Ind:""},
  {Bible:"2Corinthians", Chapter:13, Verse:13, Page:1, Kor:"○주 예수 그리스도의 은혜와 하나님의 사랑과 성령의 사귐이 여러분 모두와 함께 하기를 빕니다.", Chn:"", Eng:"All the saints send their greetings.", Ind:""},
]);
