// 예레미야애가 3장 · Lamentations 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Lamentations",3,66);
BibleDB.add([
  {Bible:"Lamentations", Chapter:3, Verse:1, Page:1, Kor:"a나는 하나님의 진노의 몽둥이에 얻어맞고, 고난당하는 자다. (a 각 연의 첫 글자가 같은 히브리어 알파벳으로 시작되는 시 119편과 같은 종류의 알파벳 시)", Chn:"", Eng:"I am the man who has seen affliction by the rod of his wrath.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:2, Page:1, Kor:"주님께서 나를 이끄시어, 빛도 없는 캄캄한 곳에서 헤매게 하시고,", Chn:"", Eng:"He has driven me away and made me walk in darkness rather than light;", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:3, Page:1, Kor:"온종일 손을 들어서 치고 또 치시는구나.", Chn:"", Eng:"indeed, he has turned his hand against me again and again, all day long.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:4, Page:1, Kor:"주님께서 내 살갗을 약하게 하시며, 내 뼈를 꺾으시며,", Chn:"", Eng:"He has made my skin and my flesh grow old and has broken my bones.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:5, Page:1, Kor:"가난과 고생으로 나를 에우시며,", Chn:"", Eng:"He has besieged me and surrounded me with bitterness and hardship.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:6, Page:1, Kor:"죽은 지 오래 된 사람처럼 흑암 속에서 살게 하신다.", Chn:"", Eng:"He has made me dwell in darkness like those long dead.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:7, Page:1, Kor:"내가 도망갈 수 없도록 담을 쌓아 가두시고, 무거운 족쇄를 채우시며,", Chn:"", Eng:"He has walled me in so I cannot escape; he has weighed me down with chains.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:8, Page:1, Kor:"살려 달라고 소리를 높여 부르짖어도 내 기도를 듣지 않으시며,", Chn:"", Eng:"Even when I call out or cry for help, he shuts out my prayer.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:9, Page:1, Kor:"다듬은 돌로 담을 쌓아서 내 앞길을 가로막아, 길을 가는 나를 괴롭히신다.", Chn:"", Eng:"He has barred my way with blocks of stone; he has made my paths crooked.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:10, Page:1, Kor:"주님께서는, 엎드려서 나를 노리는 곰과 같고, 몰래 숨어서 나를 노리는 사자와 같으시다.", Chn:"", Eng:"Like a bear lying in wait, like a lion in hiding,", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:11, Page:1, Kor:"길을 잘못 들게 하시며, 내 몸을 찢으시며, 나를 외롭게 하신다.", Chn:"", Eng:"he dragged me from the path and mangled me and left me without help.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:12, Page:1, Kor:"주님께서 나를 과녁으로 삼아서, 활을 당기신다.", Chn:"", Eng:"He drew his bow and made me the target for his arrows.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:13, Page:1, Kor:"주님께서 화살통에서 뽑은 화살로 내 심장을 뚫으시니,", Chn:"", Eng:"He pierced my heart with arrows from his quiver.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:14, Page:1, Kor:"내 백성이 모두 나를 조롱하고, 온종일 놀려댄다.", Chn:"", Eng:"I became the laughingstock of all my people; they mock me in song all day long.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:15, Page:1, Kor:"쓸개즙으로 나를 배불리시고, 쓴 쑥으로 내 배를 채우신다.", Chn:"", Eng:"He has filled me with bitter herbs and sated me with gall.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:16, Page:1, Kor:"돌로 내 이를 바수시고, 나의 얼굴을 땅에 비비신다.", Chn:"", Eng:"He has broken my teeth with gravel; he has trampled me in the dust.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:17, Page:1, Kor:"내게서 평안을 빼앗으시니, 나는 행복을 잊고 말았다.", Chn:"", Eng:"I have been deprived of peace; I have forgotten what prosperity is.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:18, Page:1, Kor:"나오느니 탄식뿐이다. 이제 내게서는 찬란함도 사라지고, 주님께 두었던 마지막 희망마저 사라졌다.", Chn:"", Eng:"So I say, \"My splendor is gone and all that I had hoped from the LORD.\"", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:19, Page:1, Kor:"내가 겪은 그 고통, 쓴 쑥과 쓸개즙 같은 그 고난을 잊지 못한다.", Chn:"", Eng:"I remember my affliction and my wandering, the bitterness and the gall.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:20, Page:1, Kor:"잠시도 잊을 수 없으므로, 울적한 마음을 가눌 길이 없다.", Chn:"", Eng:"I well remember them, and my soul is downcast within me.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:21, Page:1, Kor:"그러나 마음 속으로 곰곰이 생각하며 오히려 희망을 가지는 것은,", Chn:"", Eng:"Yet this I call to mind and therefore I have hope:", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:22, Page:1, Kor:"b주님의 한결같은 사랑이 다함이 없고 그 긍휼이 끝이 없기 때문이다. (b 시리아어역과 타르굼을 따름. 히, '우리는 끊어지지 않았고')", Chn:"", Eng:"Because of the LORD'S great love we are not consumed, for his compassions never fail.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:23, Page:1, Kor:"\"주님의 사랑과 긍휼이 아침마다 새롭고, 주님의 신실이 큽니다.\"", Chn:"", Eng:"They are new every morning; great is your faithfulness.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:24, Page:1, Kor:"나는 늘 말하였다. \"주님은 내가 가진 모든 것, 주님은 나의 희망!\"", Chn:"", Eng:"I say to myself, \"The LORD is my portion; therefore I will wait for him.\"", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:25, Page:1, Kor:"주님께서는, 주님을 기다리는 사람이나 주님을 찾는 사람에게 복을 주신다.", Chn:"", Eng:"The LORD is good to those whose hope is in him, to the one who seeks him;", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:26, Page:1, Kor:"주님께서 구원하여 주시기를 참고 기다리는 것이 좋다.", Chn:"", Eng:"it is good to wait quietly for the salvation of the LORD.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:27, Page:1, Kor:"젊은 시절에 이런 멍에를 짊어지는 것이 좋고,", Chn:"", Eng:"It is good for a man to bear the yoke while he is young.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:28, Page:1, Kor:"짊어진 멍에가 무거울 때에는 잠자코 있는 것이 좋고,", Chn:"", Eng:"Let him sit alone in silence, for the LORD has laid it on him.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:29, Page:1, Kor:"어쩌면 희망이 있을지도 모르니 c겸손하게 사는 것이 좋다. (c 히, '먼지에 입을 대는 것이')", Chn:"", Eng:"Let him bury his face in the dust--there may yet be hope.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:30, Page:1, Kor:"때리려는 사람에게 뺨을 대주고, d욕을 하거든 기꺼이 들어라. (d 히, '굴욕으로 배를 채워라')", Chn:"", Eng:"Let him offer his cheek to one who would strike him, and let him be filled with disgrace.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:31, Page:1, Kor:"주님께서는 우리를 언제까지나 버려 두지는 않으신다.", Chn:"", Eng:"For men are not cast off by the Lord forever.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:32, Page:1, Kor:"주님께서 우리를 근심하게 하셔도, 그 크신 사랑으로 우리를 불쌍히 여기신다.", Chn:"", Eng:"Though he brings grief, he will show compassion, so great is his unfailing love.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:33, Page:1, Kor:"우리를 괴롭히거나 근심하게 하는 것은, 그분의 본심이 아니다.", Chn:"", Eng:"For he does not willingly bring affliction or grief to the children of men.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:34, Page:1, Kor:"세상에서 옥에 갇힌 모든 사람이 발 아래 짓밟히는 일,", Chn:"", Eng:"To crush underfoot all prisoners in the land,", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:35, Page:1, Kor:"가장 높으신 주님 앞에서 인권이 유린되는 일,", Chn:"", Eng:"to deny a man his rights before the Most High,", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:36, Page:1, Kor:"재판에서 사람이 억울한 판결을 받는 일, 이러한 모든 일을 주님께서 못 보실 줄 아느냐?", Chn:"", Eng:"to deprive a man of justice--would not the Lord see such things?", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:37, Page:1, Kor:"말씀으로 명령하시고 그것을 이루시는 분이 누구냐? 주님이 아니시더냐?", Chn:"", Eng:"Who can speak and have it happen if the Lord has not decreed it?", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:38, Page:1, Kor:"궂은 일도 좋은 일도, 가장 높으신 주님께서 말씀하셔서 일어나는 것이 아니냐?", Chn:"", Eng:"Is it not from the mouth of the Most High that both calamities and good things come?", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:39, Page:1, Kor:"어찌하여 살아 있는 사람이, 자기 죄값으로 치르는 벌을 불평하느냐?", Chn:"", Eng:"Why should any living man complain when punished for his sins?", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:40, Page:1, Kor:"지나온 길을 돌이켜 살펴보고, 우리 모두 주님께로 돌아가자.", Chn:"", Eng:"Let us examine our ways and test them, and let us return to the LORD.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:41, Page:1, Kor:"하늘에 계신 하나님께 우리의 마음을 열고, 손을 들어서 기도하자.", Chn:"", Eng:"Let us lift up our hearts and our hands to God in heaven, and say:", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:42, Page:1, Kor:"\"우리가 주님을 거슬러 죄를 지었고, 주님께서는 우리를 용서하지 않으셨습니다.", Chn:"", Eng:"\"We have sinned and rebelled and you have not forgiven.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:43, Page:1, Kor:"주님께서 몹시 노하셔서, 우리를 쫓으시고, 사정없이 죽이셨습니다.", Chn:"", Eng:"\"You have covered yourself with anger and pursued us; you have slain without pity.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:44, Page:1, Kor:"주님께서 구름을 두르셔서, 우리의 기도가 주님께 이르지 못하게 하셨습니다.", Chn:"", Eng:"You have covered yourself with a cloud so that no prayer can get through.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:45, Page:1, Kor:"주님께서 우리를 뭇 민족 가운데서 쓰레기와 오물 더미로 만드셨으므로,", Chn:"", Eng:"You have made us scum and refuse among the nations.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:46, Page:1, Kor:"우리의 모든 대적이 우리를 보고서 입을 열어 놀려댔습니다.", Chn:"", Eng:"\"All our enemies have opened their mouths wi`e against us.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:47, Page:1, Kor:"우리에게 남은 것이라고는 두려움과 함정과 파멸과 폐허뿐입니다.", Chn:"", Eng:"We have suffered terror and pitfalls, ruin and destruction.\"", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:48, Page:1, Kor:"내 백성의 도성이 파멸되니, 나의 눈에서 눈물이 냇물처럼 흐릅니다.", Chn:"", Eng:"Streams of tears flow from my eyes because my people are destroyed.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:49, Page:1, Kor:"눈물이 걷잡을 수 없이 쉬지 않고 쏟아집니다.", Chn:"", Eng:"My eyes will flow unceasingly, without relief,", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:50, Page:1, Kor:"주님께서 하늘에서 살피시고, 돌아보시기를 기다립니다.", Chn:"", Eng:"until the LORD looks down from heaven and sees.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:51, Page:1, Kor:"도성에 사는 모든 여자가 겪은 일을 보니, 내 마음은 슬픔을 달랠 길이 없습니다.", Chn:"", Eng:"What I see brings grief to my soul because of all the women of my city.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:52, Page:1, Kor:"까닭없이 내 대적이 된 자들이 새를 사냥하듯 나를 쫓습니다.", Chn:"", Eng:"Those who were my enemies without cause hunted me like a bird.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:53, Page:1, Kor:"그들이 나를 산 채로 구덩이에 처넣고, 돌로 막아서 못 나오게 하였습니다.", Chn:"", Eng:"They tried to end my life in a pit and threw stones at me;", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:54, Page:1, Kor:"물이 내 머리 위로 넘쳤으므로, '나는 이제 죽었구나' 하고 생각하였습니다.", Chn:"", Eng:"the waters closed over my head, and I thought I was about to be cut off.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:55, Page:1, Kor:"주님, 그 깊디 깊은 구덩이 밑바닥에서 주님의 이름을 불렀습니다.", Chn:"", Eng:"I called on your name, O LORD, from the depths of the pit.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:56, Page:1, Kor:"'살려 주십시오. 못들은 체 하지 마시고, 건져 주십시오' 하고 울부짖을 때에, 주님께서 내 간구를 들어 주셨습니다.", Chn:"", Eng:"You heard my plea: \"Do not close your ears to my cry for relief.\"", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:57, Page:1, Kor:"내가 주님께 부르짖을 때에, 주님께서 내게 가까이 오셔서 두려워하지 말라고 격려하셨습니다.", Chn:"", Eng:"You came near when I called you, and you said, \"Do not fear.\"", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:58, Page:1, Kor:"주님, 주님께서 내 원한을 풀어 주시고, 내 목숨을 건져 주셨습니다.", Chn:"", Eng:"O Lord, you took up my case; you redeemed my life.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:59, Page:1, Kor:"주님, 주님께서 내가 당한 억울한 일을 보셨으니, 내게 바른 판결을 내려 주십시오.", Chn:"", Eng:"You have seen, O LORD, the wrong done to me. Uphold my cause!", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:60, Page:1, Kor:"주님께서는 나를 치려는 그들의 적개심과 음모를 아십니다.", Chn:"", Eng:"You have seen the depth of their vengeance, all their plots against me.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:61, Page:1, Kor:"주님, 주님께서는, 그들이 나를 두고 하는 모든 야유와 음모를 들으셨습니다.", Chn:"", Eng:"O LORD, you have heard their insults, all their plots against me--", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:62, Page:1, Kor:"내 원수들이 온종일 나를 헐뜯고 모함합니다.", Chn:"", Eng:"what my enemies whisper and mutter against me all day long.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:63, Page:1, Kor:"그들은 앉으나 서나, 늘 나를 비난합니다.", Chn:"", Eng:"Look at them! Sitting or standing, they mock me in their songs.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:64, Page:1, Kor:"주님, 그들이 저지른 일을 그대로 갚아 주십시오.", Chn:"", Eng:"Pay them back what they deserve, O LORD, for what their hands have done.", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:65, Page:1, Kor:"그들의 마음을 돌같이 하시고, 저주를 내려 주십시오.", Chn:"", Eng:"Put a veil over their hearts, and may your curse be on them!", Ind:""},
  {Bible:"Lamentations", Chapter:3, Verse:66, Page:1, Kor:"진노로 그들을 뒤쫓아, 주님의 하늘 아래에서 살 수 없게 하여 주십시오.\"", Chn:"", Eng:"Pursue them in anger and destroy them from under the heavens of the LORD.", Ind:""},
]);
