// 에스더 9장 · Esther 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Esther",9,32);
BibleDB.add([
  {Bible:"Esther", Chapter:9, Verse:1, Page:1,
    Kor:"<유다 사람이 원수들을 죽이다> 열두째 달인 아달월 십삼일, 드디어 왕이 내린 명령과 조서대로 시행하는 날이 되었다. 이 날은, 본래 유다 사람의 원수들이 유다 사람을 없애려고 한 날인데, 오히려 유다 사람이 자기들을 미워하는 자들을 없애는 날로 바뀌었다.",
    Chn:"十二月，乃亚达月十三日，王的谕旨将要举行，就是犹大人的仇敌盼望辖制他们的日子，犹大人反倒辖制恨他们的人。",
    Eng:"On the thirteenth day of the twelfth month, the month of Adar, the edict commanded by the king was to be carried out. On this day the enemies of the Jews had hoped to overpower them, but now the tables were turned and the Jews got the upper hand over those who hated them.",
    Ind:"Dalam bulan yang kedua belas--yakni bulan Adar--,pada hari yang ketiga belas, ketika titah serta undang-undang raja akan dilaksanakan, pada hari musuh-musuh orang Yahudi berharap mengalahkan orang Yahudi, terjadilah yang sebaliknya: orang Yahudi mengalahkan pembenci-pembenci mereka."
  },
  {Bible:"Esther", Chapter:9, Verse:2, Page:1,
    Kor:"아하수에로 왕이 다스리는 모든 지방의 각 성읍에 사는 유다 사람들은, 성읍별로 모여서, 자기들을 해치려고 한 자들을 공격하였다. 모든 민족이 그들을 두려워하였으므로, 아무도 막을 수 없었다.",
    Chn:"犹大人在亚哈随鲁王各省的城里聚集，下手击杀那要害他们的人。无人能敌挡他们，因为各族都惧怕他们。",
    Eng:"The Jews assembled in their cities in all the provinces of King Xerxes to attack those seeking their destruction. No one could stand against them, because the people of all the other nationalities were afraid of them.",
    Ind:"Maka berkumpullah orang Yahudi di dalam kota-kotanya di seluruh daerah raja Ahasyweros, untuk membunuh orang-orang yang berikhtiar mencelakakan mereka, dan tiada seorangpun tahan menghadapi mereka, karena ketakutan kepada orang Yahudi telah menimpa segala bangsa itu."
  },
  {Bible:"Esther", Chapter:9, Verse:3, Page:1,
    Kor:"각 지방의 대신들과 제후들과 총독들과 왕의 행정관리들은, 모르드개가 무서워서도 유다 사람들을 도왔다.",
    Chn:"各省的首领、总督、省长，和办理王事的人，因惧怕末底改，就都帮助犹大人。",
    Eng:"And all the nobles of the provinces, the satraps, the governors and the king's administrators helped the Jews, because fear of Mordecai had seized them.",
    Ind:"Dan semua pembesar daerah dan wakil pemerintahan dan bupati serta pejabat kerajaan menyokong orang Yahudi, karena ketakutan kepada Mordekhai telah menimpa mereka."
  },
  {Bible:"Esther", Chapter:9, Verse:4, Page:1,
    Kor:"당시 모르드개는, 왕궁에서 실권을 잡고 있었고, 그의 세력은 날로 더하여 갔으며, 그의 명성은 전국 방방곡곡에 퍼졌다.",
    Chn:"末底改在朝中为大，名声传遍各省，日渐昌盛。",
    Eng:"Mordecai was prominent in the palace; his reputation spread throughout the provinces, and he became more and more powerful.",
    Ind:"Sebab Mordekhai besar kekuasaannya di dalam istana raja dan tersiarlah berita tentang dia ke segenap daerah, karena Mordekhai itu bertambah-tambah besar kekuasaannya."
  },
  {Bible:"Esther", Chapter:9, Verse:5, Page:1,
    Kor:"○유다 사람들은 그들의 원수를 다 칼로 쳐 죽여 없앴으며, 자기들을 미워하는 자들에게, 하고 싶은 대로 다 하였다.",
    Chn:"犹大人用刀击杀一切仇敌，任意杀灭恨他们的人。",
    Eng:"The Jews struck down all their enemies with the sword, killing and destroying them, and they did what they pleased to those who hated them.",
    Ind:"Maka orang Yahudi mengalahkan semua musuhnya: mereka memukulnya dengan pedang, membunuh dan membinasakannya; mereka berbuat sekehendak hatinya terhadap pembenci-pembenci mereka."
  },
  {Bible:"Esther", Chapter:9, Verse:6, Page:1,
    Kor:"유다 사람들은 도성 수산에서만도 그런 자들을 오백 명이나 처형하였다.",
    Chn:"在书珊城，犹大人杀灭了五百人；",
    Eng:"In the citadel of Susa, the Jews killed and destroyed five hundred men.",
    Ind:"Di dalam benteng Susan saja orang Yahudi membunuh dan membinasakan lima ratus orang."
  },
  {Bible:"Esther", Chapter:9, Verse:7, Page:1,
    Kor:"바산다다와 달본과 아스바다와",
    Chn:"又杀巴珊大他、达分、亚斯帕他、",
    Eng:"They also killed Parshandatha, Dalphon, Aspatha,",
    Ind:"Juga Parsandata, Dalfon, Aspata,"
  },
  {Bible:"Esther", Chapter:9, Verse:8, Page:1,
    Kor:"보라다와 아달리야와 아리다다와",
    Chn:"破拉他、亚大利雅、亚利大他、",
    Eng:"Poratha, Adalia, Aridatha,",
    Ind:"Porata, Adalya, Aridata,"
  },
  {Bible:"Esther", Chapter:9, Verse:9, Page:1,
    Kor:"바마스다와 아리새와 아리대와 왜사다와",
    Chn:"帕玛斯他、亚利赛、亚利代、瓦耶撒他；",
    Eng:"Parmashta, Arisai, Aridai and Vaizatha,",
    Ind:"Parmasta, Arisai, Aridai dan Waizata,"
  },
  {Bible:"Esther", Chapter:9, Verse:10, Page:1,
    Kor:"유다 사람의 원수요 함므다다의 아들인 하만의 열 아들도 죽였다. 유다 사람들은 그들을 죽이기는 하였지만, 그들의 재산은 빼앗지 않았다.",
    Chn:"这十人都是哈米大他的孙子、犹大人仇敌哈曼的儿子。犹大人却没有下手夺取财物。",
    Eng:"the ten sons of Haman son of Hammedatha, the enemy of the Jews. But they did not lay their hands on the plunder.",
    Ind:"kesepuluh anak laki-laki Haman bin Hamedata, seteru orang Yahudi, dibunuh oleh mereka, tetapi kepada barang rampasan tidaklah mereka mengulurkan tangan."
  },
  {Bible:"Esther", Chapter:9, Verse:11, Page:1,
    Kor:"○도성 수산에서 죽은 사람의 수는 그 날로 왕에게 보고되었다.",
    Chn:"当日，将书珊城被杀的人数呈在王前。",
    Eng:"The number of those slain in the citadel of Susa was reported to the king that same day.",
    Ind:"Pada hari itu juga jumlah orang-orang yang terbunuh di dalam benteng Susan disampaikan ke hadapan raja."
  },
  {Bible:"Esther", Chapter:9, Verse:12, Page:1,
    Kor:"왕이 에스더 왕후에게 말하였다. \"유다 사람들은 도성 수산에서만도 그들의 원수를 오백 명이나 죽였고, 하만의 열 아들도 다 죽였소. 그러니 나머지 다른 지방에서야 오죽하였겠소? 이제 당신의 남은 소청이 무엇이오? 내가 그대로 들어주리다. 당신의 요구가 또 무엇이오? 당신이 바라는 대로 하여 주겠소.\"",
    Chn:"王对王后以斯帖说：「犹大人在书珊城杀灭了五百人，又杀了哈曼的十个儿子，在王的各省不知如何呢？现在你要什么，我必赐给你；你还求什么，也必为你成就。」",
    Eng:"The king said to Queen Esther, \"The Jews have killed and destroyed five hundred men and the ten sons of Haman in the citadel of Susa. What have they done in the rest of the king's provinces? Now what is your petition? It will be given you. What is your request? It will also be granted.\"",
    Ind:"Lalu titah raja kepada Ester, sang ratu: \"Di dalam benteng Susan saja orang Yahudi telah membunuh dan membinasakan lima ratus orang beserta kesepuluh anak Haman. Di daerah-daerah kerajaan yang lain, entahlah apa yang diperbuat mereka. Dan apakah permintaanmu sekarang? Niscaya akan dikabulkan. Dan apakah keinginanmu lagi? Niscaya dipenuhi.\""
  },
  {Bible:"Esther", Chapter:9, Verse:13, Page:1,
    Kor:"에스더가 대답하였다. \"임금님께서만 좋으시다면, 수산에 있는 유다 사람들이 내일도 오늘처럼 이 조서대로 시행하도록 하여 주십시오. 그리고 하만의 열 아들의 주검은 장대에 매달아 주십시오.\"",
    Chn:"以斯帖说：「王若以为美，求你准书珊的犹大人，明日也照今日的旨意行，并将哈曼十个儿子的尸首挂在木架上。」",
    Eng:"\"If it pleases the king,\" Esther answered, \"give the Jews in Susa permission to carry out this day's edict tomorrow also, and let Haman's ten sons be hanged on gallows.\"",
    Ind:"Lalu jawab Ester: \"Jikalau baik pada pemandangan raja, diizinkanlah kiranya kepada orang Yahudi yang di Susan untuk berbuat besokpun sesuai dengan undang-undang untuk hari ini, dan kesepuluh anak Haman itu hendaklah disulakan pada tiang.\""
  },
  {Bible:"Esther", Chapter:9, Verse:14, Page:1,
    Kor:"왕은 그렇게 하라고 명령을 내렸다. 수산에는 조서가 내렸고, 하만의 열 아들의 주검은 장대에 매달렸다.",
    Chn:"王便允准如此行。旨意传在书珊，人就把哈曼十个儿子的尸首挂起来了。",
    Eng:"So the king commanded that this be done. An edict was issued in Susa, and they hanged the ten sons of Haman.",
    Ind:"Rajapun menitahkan berbuat demikian; maka undang-undang itu dikeluarkan di Susan dan kesepuluh anak Haman disulakan orang."
  },
  {Bible:"Esther", Chapter:9, Verse:15, Page:1,
    Kor:"수산의 유다 사람들은 아달월 십사일에 한 곳에 모여서, 수산에서만도 삼백 명을 죽였으나, 역시 재산은 빼앗지 않았다.",
    Chn:"亚达月十四日，书珊的犹大人又聚集在书珊，杀了三百人，却没有下手夺取财物。",
    Eng:"The Jews in Susa came together on the fourteenth day of the month of Adar, and they put to death in Susa three hundred men, but they did not lay their hands on the plunder.",
    Ind:"Jadi berkumpullah orang Yahudi yang di Susan pada hari yang keempat belas bulan Adar juga dan dibunuhnyalah di Susan tiga ratus orang, tetapi kepada barang rampasan tidaklah mereka mengulurkan tangan."
  },
  {Bible:"Esther", Chapter:9, Verse:16, Page:1,
    Kor:"○그러는 동안에, 왕이 다스리는 각 지방에 있는 나머지 유다 사람들도, 지방별로 함께 모여서 조직을 정비하고, 자체 방어에 들어갔다. 그들은 원수들을 무려 칠만 오천 명이나 죽였으나, 역시 재산은 빼앗지 않았다.",
    Chn:"在王各省其余的犹大人也都聚集保护性命，杀了恨他们的人七万五千，却没有下手夺取财物。这样，就脱离仇敌，得享平安。",
    Eng:"Meanwhile, the remainder of the Jews who were in the king's provinces also assembled to protect themselves and get relief from their enemies. They killed seventy-five thousand of them but did not lay their hands on the plunder.",
    Ind:"Orang Yahudi yang lain, yang ada di dalam daerah kerajaan, berkumpul dan mempertahankan nyawanya serta mendapat keamanan terhadap musuhnya; mereka membunuh tujuh puluh lima ribu orang di antara pembenci-pembenci mereka, tetapi kepada barang rampasan tidaklah mereka mengulurkan tangan."
  },
  {Bible:"Esther", Chapter:9, Verse:17, Page:1,
    Kor:"이 일이 일어난 것은 아달월 십삼일이었다. 십사일에는 쉬면서, 그 날을, 잔치를 하면서 기뻐하는 날로 삼았다.",
    Chn:"亚达月十三日，行了这事；十四日安息，以这日为设筵欢乐的日子。",
    Eng:"This happened on the thirteenth day of the month of Adar, and on the fourteenth they rested and made it a day of feasting and joy.",
    Ind:"Hal itu terjadi pada hari yang ketiga belas dalam bulan Adar. Pada hari yang keempat belas berhentilah mereka dan hari itu dijadikan mereka hari perjamuan dan sukacita."
  },
  {Bible:"Esther", Chapter:9, Verse:18, Page:1,
    Kor:"그러나 수산에 사는 유다 사람들은, 십삼일과 십사일에 모여 일을 벌였으므로, 십오일에는 쉬면서, 그 날을 잔치를 하면서 기뻐하는 날로 삼았다.",
    Chn:"但书珊的犹大人，这十三日、十四日聚集杀戮仇敌；十五日安息，以这日为设筵欢乐的日子。",
    Eng:"The Jews in Susa, however, had assembled on the thirteenth and fourteenth, and then on the fifteenth they rested and made it a day of feasting and joy.",
    Ind:"Akan tetapi orang Yahudi yang di Susan berkumpul, baik pada hari yang ketiga belas, baik pada hari yang keempat belas dalam bulan itu. Lalu berhentilah mereka pada hari yang kelima belas dan hari itu dijadikan mereka hari perjamuan dan sukacita."
  },
  {Bible:"Esther", Chapter:9, Verse:19, Page:1,
    Kor:"성벽이 없는 여러 마을에 사는 유다 사람들이 아달월 십사일을 명절로 정하고, 즐겁게 잔치를 벌이면서, 서로 음식을 나누어 먹은 까닭도 바로 이것이다.",
    Chn:"所以住无城墙乡村的犹大人，如今都以亚达月十四日为设筵欢乐的吉日，彼此馈送礼物。",
    Eng:"That is why rural Jews--those living in villages--observe the fourteenth of the month of Adar as a day of joy and feasting, a day for giving presents to each other.",
    Ind:"Oleh sebab itu orang Yahudi yang di pedusunan, yakni yang diam di perkampungan merayakan hari yang keempat belas bulan Adar itu sebagai hari sukacita dan hari perjamuan, dan sebagai hari gembira untuk antar-mengantar makanan."
  },
  {Bible:"Esther", Chapter:9, Verse:20, Page:1,
    Kor:"<부림절> ○모르드개는 이 모든 사건을 다 기록하여 두었다. 그는 또, 멀든지 가깝든지, 아하수에로 왕이 다스리는 모든 지방에 사는 유다 사람들에게 글을 보내서,",
    Chn:"末底改记录这事，写信与亚哈随鲁王各省远近所有的犹大人，",
    Eng:"Mordecai recorded these events, and he sent letters to all the Jews throughout the provinces of King Xerxes, near and far,",
    Ind:"Maka Mordekhai menuliskan peristiwa itu, lalu mengirimkan surat-surat kepada semua orang Yahudi di seluruh daerah raja Ahasyweros, baik yang dekat baik yang jauh,"
  },
  {Bible:"Esther", Chapter:9, Verse:21, Page:1,
    Kor:"해마다 아달월 십사일과 십오일을 명절로 지키도록 지시하였다.",
    Chn:"嘱咐他们每年守亚达月十四、十五两日，",
    Eng:"to have them celebrate annually the fourteenth and fifteenth days of the month of Adar",
    Ind:"untuk mewajibkan mereka, supaya tiap-tiap tahun merayakan hari yang keempat belas dan yang kelima belas bulan Adar,"
  },
  {Bible:"Esther", Chapter:9, Verse:22, Page:1,
    Kor:"그 날에 유다 사람이 원수들의 손에서 벗어났으며, 그 날에 유다 사람의 슬픔이 기쁨으로 바뀌었고, 초상날이 잔칫날로 바뀌었으므로, 모르드개는 그 이틀 동안을, 잔치를 벌이면서 기뻐하는 명절로 정하고, 서로 음식을 나누어 먹고, 가난한 사람들에게 선물을 주는 날로 지키도록 지시하였다.",
    Chn:"以这月的两日为犹大人脱离仇敌得平安、转忧为喜、转悲为乐的吉日。在这两日设筵欢乐，彼此馈送礼物，周济穷人。",
    Eng:"as the time when the Jews got relief from their enemies, and as the month when their sorrow was turned into joy and their mourning into a day of celebration. He wrote them to observe the days as days of feasting and joy and giving presents of food to one another and gifts to the poor.",
    Ind:"karena pada hari-hari itulah orang Yahudi mendapat keamanan terhadap musuhnya dan dalam bulan itulah dukacita mereka berubah menjadi sukacita dan hari perkabungan menjadi hari gembira, dan supaya menjadikan hari-hari itu hari perjamuan dan sukacita dan hari untuk antar-mengantar makanan dan untuk bersedekah kepada orang-orang miskin."
  },
  {Bible:"Esther", Chapter:9, Verse:23, Page:1,
    Kor:"그래서 유다 사람들은, 모르드개가 그들에게 글로 써서 지시한 대로, 자기들이 시작한 그 명절을 해마다 지켰다.",
    Chn:"于是，犹大人按着末底改所写与他们的信，应承照初次所守的守为永例；",
    Eng:"So the Jews agreed to continue the celebration they had begun, doing what Mordecai had written to them.",
    Ind:"Maka orang Yahudi menerima sebagai ketetapan apa yang sudah dimulai mereka melakukannya dan apa yang ditulis Mordekhai kepada mereka."
  },
  {Bible:"Esther", Chapter:9, Verse:24, Page:1,
    Kor:"○유다 사람의 원수 아각의 자손 함므다다의 아들 하만은, 유다 사람들을 죽여 없애려고, 주사위의 일종인 부르를 던져서, 유다 사람들을 다 없앨 날을 받았으나,",
    Chn:"是因犹大人的仇敌亚甲族哈米大他的儿子哈曼设谋杀害犹大人，掣普珥，就是掣签，为要杀尽灭绝他们；",
    Eng:"For Haman son of Hammedatha, the Agagite, the enemy of all the Jews, had plotted against the Jews to destroy them and had cast the pur (that is, the lot) for their ruin and destruction.",
    Ind:"Sesungguhnya Haman bin Hamedata, orang Agag, seteru semua orang Yahudi itu, telah merancangkan hendak membinasakan orang Yahudi dan diapun telah membuang pur--yakni undi--untuk menghancurkan dan membinasakan mereka,"
  },
  {Bible:"Esther", Chapter:9, Verse:25, Page:1,
    Kor:"에스더가 그 음모를 왕 앞에 말하니, 왕은 하만이 유다 사람을 해치려고 꾸민 악한 흉계가 하만 자신에게 돌아가도록 하고, 하만뿐만 아니라 그의 모든 아들까지도 장대에 매달도록, 글로 써서 조서를 내렸다.",
    Chn:"这事报告于王，王便降旨使哈曼谋害犹大人的恶事归到他自己的头上，并吩咐把他和他的众子都挂在木架上。",
    Eng:"But when the plot came to the king's attention, he issued written orders that the evil scheme Haman had devised against the Jews should come back onto his own head, and that he and his sons should be hanged on the gallows.",
    Ind:"akan tetapi ketika hal itu disampaikan ke hadapan raja, maka dititahkannyalah dengan surat, supaya rancangan jahat yang dibuat Haman terhadap orang Yahudi itu dibalikkan ke atas kepalanya. Maka Haman beserta anak-anaknya disulakan pada tiang."
  },
  {Bible:"Esther", Chapter:9, Verse:26, Page:1,
    Kor:"그래서 주사위의 일종인 부르라는 말을 따라, 이 두 날을 불러서 부림이라고 하였다. 이 모든 사건은, 유다 사람 스스로가 직접 보고 겪은 것이며, 모르드개의 글에도 적혀 있는 것이다.",
    Chn:"照着普珥的名字，犹大人就称这两日为「普珥日」。他们因这信上的话，又因所看见所遇见的事，",
    Eng:"(Therefore these days were called Purim, from the word pur.) Because of everything written in this letter and because of what they had seen and what had happened to them,",
    Ind:"Oleh sebab itulah hari-hari itu disebut Purim, menurut kata pur. Oleh sebab itu jugalah, yakni karena seluruh isi surat itu dan karena apa yang dilihat mereka mengenai hal itu dan apa yang dialami mereka,"
  },
  {Bible:"Esther", Chapter:9, Verse:27, Page:1,
    Kor:"그래서 그들은 이 두 날을, 그들과 자손과 그들에게 귀화하는 모든 사람이, 해마다 정해진 때에, 글에 적혀 있는 대로, 반드시 지켜야 하는 명절로 삼았다.",
    Chn:"就应承自己与后裔，并归附他们的人，每年按时必守这两日，永远不废。",
    Eng:"the Jews took it upon themselves to establish the custom that they and their descendants and all who join them should without fail observe these two days every year, in the way prescribed and at the time appointed.",
    Ind:"orang Yahudi menerima sebagai kewajiban dan sebagai ketetapan bagi dirinya sendiri dan keturunannya dan bagi sekalian orang yang akan bergabung dengan mereka, bahwa mereka tidak akan melampaui merayakan kedua hari itu tiap-tiap tahun, menurut yang dituliskan tentang itu dan pada waktu yang ditentukan,"
  },
  {Bible:"Esther", Chapter:9, Verse:28, Page:1,
    Kor:"이 두 날은, 유다 사람이면, 어느 지방 어느 성읍에 살든지, 모든 집안마다 대대로 기억하고 지켜야 하는 날이다. 이틀 동안 계속되는 부림절은 유다 사람들로서는 거를 수 없는 명절이 되고, 자손에게도 잊어서는 안 되는 날이 되었다.",
    Chn:"各省各城、家家户户、世世代代纪念遵守这两日，使这「普珥日」在犹大人中不可废掉，在他们后裔中也不可忘记。",
    Eng:"These days should be remembered and observed in every generation by every family, and in every province and in every city. And these days of Purim should never cease to be celebrated by the Jews, nor should the memory of them die out among their descendants.",
    Ind:"dan bahwa hari-hari itu akan diperingati dan dirayakan di dalam tiap-tiap angkatan, di dalam tiap-tiap kaum, di tiap-tiap daerah, di tiap-tiap kota, sehingga hari-hari Purim itu tidak akan lenyap dari tengah-tengah orang Yahudi dan peringatannya tidak akan berakhir dari antara keturunan mereka."
  },
  {Bible:"Esther", Chapter:9, Verse:29, Page:1,
    Kor:"○아비하일의 딸 에스더 왕후는, 유다 사람 모르드개와 함께, 전권을 가지고 두 번째로 편지를 써서, 부림절을 확정하였다.",
    Chn:"亚比孩的女儿—王后以斯帖和犹大人末底改以全权写第二封信，坚嘱犹大人守这「普珥日」，",
    Eng:"So Queen Esther, daughter of Abihail, along with Mordecai the Jew, wrote with full authority to confirm this second letter concerning Purim.",
    Ind:"Lalu Ester, sang ratu, anak Abihail, menulis surat, bersama-sama dengan Mordekhai, orang Yahudi itu; surat yang kedua tentang hari raya Purim ini dituliskannya dengan segala ketegasan untuk menguatkannya."
  },
  {Bible:"Esther", Chapter:9, Verse:30, Page:1,
    Kor:"위로와 격려의 말이 담긴 그 편지는, 아하수에로 왕국 백스물일곱 지방에 사는 모든 유다 사람들에게 발송되었다.",
    Chn:"用和平诚实话写信给亚哈随鲁王国中一百二十七省所有的犹大人，",
    Eng:"And Mordecai sent letters to all the Jews in the 127 provinces of the kingdom of Xerxes--words of goodwill and assurance--",
    Ind:"Lalu dikirimkanlah surat-surat kepada semua orang Yahudi di dalam keseratus dua puluh tujuh daerah kerajaan Ahasyweros, dengan kata-kata salam dan setia,"
  },
  {Bible:"Esther", Chapter:9, Verse:31, Page:1,
    Kor:"이 편지는 이틀 동안 계속되는 부림절을 확정짓는 것이다. 이것은 유다 사람 모르드개와 에스더 왕후가 지시한 것일 뿐만 아니라, 유다 사람들 스스로도 기꺼이 부림절을 명절로 확정하고, 그 자손들도 그 때가 되면, 금식하며, 슬피 울면서 지키도록 하였다.",
    Chn:"劝他们按时守这「普珥日」，禁食呼求，是照犹大人末底改和王后以斯帖所嘱咐的，也照犹大人为自己与后裔所应承的。",
    Eng:"to establish these days of Purim at their designated times, as Mordecai the Jew and Queen Esther had decreed for them, and as they had established for themselves and their descendants in regard to their times of fasting and lamentation.",
    Ind:"supaya hari-hari Purim itu dirayakan pada waktu yang ditentukan, seperti yang diwajibkan kepada mereka oleh Mordekhai, orang Yahudi itu, dan oleh Ester, sang ratu, dan seperti yang diwajibkan mereka kepada dirinya sendiri serta keturunan mereka, mengenai hal berpuasa dan meratap-ratap."
  },
  {Bible:"Esther", Chapter:9, Verse:32, Page:1,
    Kor:"부림절에 관한 규정은, 에스더의 명령으로 이렇게 확정되고, 그것은 글로 기록되었다.",
    Chn:"以斯帖命定守「普珥日」，这事也记录在书上。",
    Eng:"Esther's decree confirmed these regulations about Purim, and it was written down in the records.",
    Ind:"Demikianlah perintah Ester menetapkan perihal Purim itu, kemudian dituliskan di dalam kitab."
  },
]);
