// 에스더 7장 · Esther 7
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Esther",7,10);
BibleDB.add([
  {Bible:"Esther", Chapter:7, Verse:1, Page:1, Kor:"왕과 하만은 에스더 왕후가 차린 잔치에 함께 갔다.", Chn:"", Eng:"So the king and Haman went to dine with Queen Esther,", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:2, Page:1, Kor:"둘째 날에도 술을 마시면서 왕이 물었다. \"에스더 왕후, 당신의 간청이 무엇이오? 내가 다 들어주겠소. 당신의 소청이 무엇이오? 나라의 절반이라도 떼어 주겠소.\"", Chn:"", Eng:"and as they were drinking wine on that second day, the king again asked, \"Queen Esther, what is your petition? It will be given you. What is your request? Even up to half the kingdom, it will be granted.\"", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:3, Page:1, Kor:"에스더 왕후가 대답하였다. \"임금님, 내가 임금님께 은혜를 입었고, 임금님께서 나를 어여삐 여기시면, 나의 목숨을 살려 주십시오. 이것이 나의 간청입니다. 나의 겨레를 살려 주십시오. 이것이 나의 소청입니다.", Chn:"", Eng:"Then Queen Esther answered, \"If I have found favor with you, O king, and if it pleases your majesty, grant me my life--this is my petition. And spare my people--this is my request.", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:4, Page:1, Kor:"나와 내 겨레가 팔려서, 망하게 되었습니다. 살육당하게 되었습니다. 다 죽게 되었습니다. 우리가 남종이나 여종으로 팔려 가기만 하여도, 내가 이런 말씀을 드리지 않을 것입니다. 그만한 일로 임금님께 걱정을 끼쳐 드리지는 않을 것입니다.\"", Chn:"", Eng:"For I and my people have been sold for destruction and slaughter and annihilation. If we had merely been sold as male and female slaves, I would have kept quiet, because no such distress would justify disturbing the king.\"", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:5, Page:1, Kor:"아하수에로 왕이 에스더 왕후에게 물었다. \"그자가 누구요? 감히 그런 일을 하려고 마음을 먹고 있는 자가 어디에 있는 누구인지 밝히시오.\"", Chn:"", Eng:"King Xerxes asked Queen Esther, \"Who is he? Where is the man who has dared to do such a thing?\"", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:6, Page:1, Kor:"에스더가 대답하였다. \"그 대적, 그 원수는 바로 이 흉악한 하만입니다.\" 에스더의 대답이 떨어지자마자, 하만은 왕과 왕후 앞에서 사색이 되었다.", Chn:"", Eng:"Esther said, \"The adversary and enemy is this vile Haman.\" Then Haman was terrified before the king and queen.", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:7, Page:1, Kor:"화가 머리 끝까지 오른 왕은 술잔을 내려놓고서, 자리에서 일어나 왕궁 안뜰로 나갔다. 하만은 왕이 자기에게 벌을 내리기로 마음 먹은 것을 알고서, 그 자리에 남아서, 에스더 왕후에게 목숨만 살려 달라고 애걸하였다.", Chn:"", Eng:"The king got up in a rage, left his wine and went out into the palace garden. But Haman, realizing that the king had already decided his fate, stayed behind to beg Queen Esther for his life.", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:8, Page:1, Kor:"왕이 안뜰에서 술자리로 돌아와 보니, 하만이 에스더가 눕는 침상에 엎드려 있었다. 이것을 본 왕은 \"내가 집안에 왕후와 함께 있는데도, 저 놈이 왕후를 범하려고 하는구나!\" 하고 소리 쳤다. 왕의 입에서 이 말이 떨어지자마자, 내시들이 달려들어서, 하만의 얼굴을 가렸다.", Chn:"", Eng:"Just as the king returned from the palace garden to the banquet hall, Haman was falling on the couch where Esther was reclining. The king exclaimed, \"Will he even molest the queen while she is with me in the house?\" As soon as the word left the king's mouth, they covered Haman's face.", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:9, Page:1, Kor:"그 때에 왕을 모시는 내시들 가운데 한 사람인 하르보나가 말하였다. \"하만이 자기 집에 높이 쉰 자짜리 장대를 세워 놓았습니다. 그것은 임금님을 해치려는 자들을 제때에 고발한 모르드개를 매달아 죽이려고 세운 것입니다.\" 그 때에 왕이 명령을 내렸다. \"하만을 거기에 매달아라!\"", Chn:"", Eng:"Then Harbona, one of the eunuchs attending the king, said, \"A gallows seventy-five feet high stands by Haman's house. He had it made for Mordecai, who spoke up to help the king.\" The king said, \"Hang him on it!\"", Ind:""},
  {Bible:"Esther", Chapter:7, Verse:10, Page:1, Kor:"사람들은, 하만이 모르드개를 매달려고 세운 바로 그 장대에 하만을 매달았다. 그런 다음에야, 비로소 왕의 분노가 가라앉았다.", Chn:"", Eng:"So they hanged Haman on the gallows he had prepared for Mordecai. Then the king's fury subsided.", Ind:""},
]);
