// 마태복음 28장 · Matthew 28
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Matthew",28,20);
BibleDB.add([
  {Bible:"Matthew", Chapter:28, Verse:1, Page:1, Kor:"<예수께서 부활하시다(막 16:1-8; 눅 24:1-12; 요 20:1-10)> 안식일이 지나고, 이레의 첫 날 동틀 무렵에, 막달라 마리아와 다른 마리아가 무덤을 보러 갔다.", Chn:"", Eng:"After the Sabbath, at dawn on the first day of the week, Mary Magdalene and the other Mary went to look at the tomb.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:2, Page:1, Kor:"그런데 갑자기 큰 지진이 일어났다. 주님의 한 천사가 하늘에서 내려와 무덤에 다가와서, 그 돌을 굴려 내고, 그 돌 위에 앉았다.", Chn:"", Eng:"There was a violent earthquake, for an angel of the Lord came down from heaven and, going to the tomb, rolled back the stone and sat on it.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:3, Page:1, Kor:"그 천사의 모습은 번개와 같았고, 그의 옷은 눈과 같이 희었다.", Chn:"", Eng:"His appearance was like lightning, and his clothes were white as snow.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:4, Page:1, Kor:"지키던 사람들은 천사를 보고 두려워서 떨었고, 죽은 사람처럼 되었다.", Chn:"", Eng:"The guards were so afraid of him that they shook and became like dead men.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:5, Page:1, Kor:"천사가 여자들에게 말하였다. \"두려워하지 말아라. 나는, 너희가 십자가에 달리신 예수를 찾는 줄 안다.", Chn:"", Eng:"The angel said to the women, \"Do not be afraid, for I know that you are looking for Jesus, who was crucified.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:6, Page:1, Kor:"그는 여기에 계시지 않다. 그가 말씀하신 대로, 그는 살아나셨다. 와서 a그가 누워 계시던 곳을 보아라.(a 다른 고대 사본들에는 '주님께서')", Chn:"", Eng:"He is not here; he has risen, just as he said. Come and see the place where he lay.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:7, Page:1, Kor:"그리고 빨리 가서 제자들에게 전하기를, 그는 b죽은 사람들 가운데서 살아 나셔서, 그들보다 먼저 갈릴리로 가시니, 그들은 거기서 그를 뵙게 될 것이라고", Chn:"", Eng:"Then go quickly and tell his disciples: 'He has risen from the dead and is going ahead of you into Galilee. There you will see him.' Now I have told you.\"", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:8, Page:1, Kor:"여자들은 무서움과 큰 기쁨이 엇갈려서, 급히 무덤을 떠나, 이 소식을 그의 제자들에게 전하려고 달려갔다.", Chn:"", Eng:"So the women hurried away from the tomb, afraid yet filled with joy, and ran to tell his disciples.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:9, Page:1, Kor:"그런데 갑자기 예수께서 여자들과 마주쳐서 \"평안하냐?\" 하고 말씀하셨다. 여자들은 다가가서, 그의 발을 붙잡고, 그에게 절을 하였다.", Chn:"", Eng:"Suddenly Jesus met them. \"Greetings,\" he said. They came to him, clasped his feet and worshiped him.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:10, Page:1, Kor:"그 때에 예수께서 그 여자들에게 말씀하셨다. \"무서워하지 말아라. 가서, 나의 형제들에게 갈릴리로 가라고 전하여라. 그러면, 거기에서 그들이 나를 만날 것이다.\"", Chn:"", Eng:"Then Jesus said to them, \"Do not be afraid. Go and tell my brothers to go to Galilee; there they will see me.\"", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:11, Page:1, Kor:"<경비병의 보고> ○여자들이 가는데, 경비병 가운데 몇 사람이 성 안으로 들어가서, 일어난 일을 모두 대제사장들에게 보고하였다.", Chn:"", Eng:"While the women were on their way, some of the guards went into the city and reported to the chief priests everything that had happened.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:12, Page:1, Kor:"대제사장들은 장로들과 함께 모여 의논한 끝에, 병사들에게 은돈을 많이 집어 주고", Chn:"", Eng:"When the chief priests had met with the elders and devised a plan, they gave the soldiers a large sum of money,", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:13, Page:1, Kor:"말하였다. \"'예수의 제자들이 밤중에 와서, 우리가 잠든 사이에 시체를 훔쳐갔다' 하고 말하여라.", Chn:"", Eng:"telling them, \"You are to say, 'His disciples came during the night and stole him away while we were asleep.'", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:14, Page:1, Kor:"이 소문이 총독의 귀에 들어가게 되더라도, 우리가 잘 말해서, 너희에게 아무 해가 미치지 않게 해주겠다.\"", Chn:"", Eng:"If this report gets to the governor, we will satisfy him and keep you out of trouble.\"", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:15, Page:1, Kor:"그들은 돈을 받고서, 시키는 대로 하였다. 그리고 이 말이 오늘날까지 유대인들 사이에 널리 퍼져 있다.", Chn:"", Eng:"So the soldiers took the money and did as they were instructed. And this story has been widely circulated among the Jews to this very day.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:16, Page:1, Kor:"<제자들의 사명(막 16:14-18; 눅 24:36-49; 요 20:19-23; 행 1:6-8)> ○열한 제자가 갈릴리로 가서, 예수께서 일러주신 산에 이르렀다.", Chn:"", Eng:"Then the eleven disciples went to Galilee, to the mountain where Jesus had told them to go.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:17, Page:1, Kor:"그들은 예수를 뵙고, 절을 하였다. 그러나 의심하는 사람들도 있었다.", Chn:"", Eng:"When they saw him, they worshiped him; but some doubted.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:18, Page:1, Kor:"예수께서 다가와서, 그들에게 말씀하셨다. \"나는 하늘과 땅의 모든 권세를 받았다.", Chn:"", Eng:"Then Jesus came to them and said, \"All authority in heaven and on earth has been given to me.", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:19, Page:1, Kor:"그러므로 너희는 가서, 모든 민족을 제자로 삼아서, 아버지와 아들과 성령의 이름으로 c세례를 주고,(c 또는 '침례')", Chn:"", Eng:"Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit,", Ind:""},
  {Bible:"Matthew", Chapter:28, Verse:20, Page:1, Kor:"내가 너희에게 명령한 모든 것을 그들에게 가르쳐 지키게 하여라. 보아라, 내가 세상 끝 날까지 항상 너희와 함께 있을 것이다.\"d(d 다른 고대 사본들은 절 끝에 '아멘'이 있음)", Chn:"", Eng:"", Ind:""},
]);
