// 마태복음 25장 · Matthew 25
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Matthew",25,46);
BibleDB.add([
  {Bible:"Matthew", Chapter:25, Verse:1, Page:1, Kor:"", Chn:"", Eng:""At that time the kingdom of heaven will be like ten virgins who took their lamps and went out to meet the bridegroom.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:2, Page:1, Kor:"", Chn:"", Eng:"Five of them were foolish and five were wise.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:3, Page:1, Kor:"", Chn:"", Eng:"The foolish ones took their lamps but did not take any oil with them.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:4, Page:1, Kor:"", Chn:"", Eng:"The wise, however, took oil in jars along with their lamps.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:5, Page:1, Kor:"", Chn:"", Eng:"The bridegroom was a long time in coming, and they all became drowsy and fell asleep.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:6, Page:1, Kor:"", Chn:"", Eng:""At midnight the cry rang out: 'Here's the bridegroom! Come out to meet him!'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:7, Page:1, Kor:"", Chn:"", Eng:""Then all the virgins woke up and trimmed their lamps.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:8, Page:1, Kor:"", Chn:"", Eng:"The foolish ones said to the wise, 'Give us some of your oil; our lamps are going out.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:9, Page:1, Kor:"", Chn:"", Eng:""'No,' they replied, 'there may not be enough for both us and you. Instead, go to those who sell oil and buy some for yourselves.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:10, Page:1, Kor:"", Chn:"", Eng:""But while they were on their way to buy the oil, the bridegroom arrived. The virgins who were ready went in with him to the wedding banquet. And the door was shut.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:11, Page:1, Kor:"", Chn:"", Eng:""Later the others also came. 'Sir! Sir!' they said. 'Open the door for us!'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:12, Page:1, Kor:"", Chn:"", Eng:""But he replied, 'I tell you the truth, I don't know you.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:13, Page:1, Kor:"", Chn:"", Eng:""Therefore keep watch, because you do not know the day or the hour.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:14, Page:1, Kor:"", Chn:"", Eng:""Again, it will be like a man going on a journey, who called his servants and entrusted his property to them.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:15, Page:1, Kor:"", Chn:"", Eng:"To one he gave five talents of money, to another two talents, and to another one talent, each according to his ability. Then he went on his journey.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:16, Page:1, Kor:"", Chn:"", Eng:"The man who had received the five talents went at once and put his money to work and gained five more.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:17, Page:1, Kor:"", Chn:"", Eng:"So also, the one with the two talents gained two more.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:18, Page:1, Kor:"", Chn:"", Eng:"But the man who had received the one talent went off, dug a hole in the ground and hid his master's money.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:19, Page:1, Kor:"", Chn:"", Eng:""After a long time the master of those servants returned and settled accounts with them.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:20, Page:1, Kor:"", Chn:"", Eng:"The man who had received the five talents brought the other five. 'Master,' he said, 'you entrusted me with five talents. See, I have gained five more.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:21, Page:1, Kor:"", Chn:"", Eng:""His master replied, 'Well done, good and faithful servant! You have been faithful with a few things; I will put you in charge of many things. Come and share your master's happiness!'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:22, Page:1, Kor:"", Chn:"", Eng:""The man with the two talents also came. 'Master,' he said, 'you entrusted me with two talents; see, I have gained two more.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:23, Page:1, Kor:"", Chn:"", Eng:""His master replied, 'Well done, good and faithful servant! You have been faithful with a few things; I will put you in charge of many things. Come and share your master's happiness!'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:24, Page:1, Kor:"", Chn:"", Eng:""Then the man who had received the one talent came. 'Master,' he said, 'I knew that you are a hard man, harvesting where you have not sown and gathering where you have not scattered seed.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:25, Page:1, Kor:"", Chn:"", Eng:"So I was afraid and went out and hid your talent in the ground. See, here is what belongs to you.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:26, Page:1, Kor:"", Chn:"", Eng:""His master replied, 'You wicked, lazy servant! So you knew that I harvest where I have not sown and gather where I have not scattered seed?", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Well then, you should have put my money on deposit with the bankers, so that when I returned I would have received it back with interest.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:28, Page:1, Kor:"", Chn:"", Eng:""'Take the talent from him and give it to the one who has the ten talents.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:29, Page:1, Kor:"", Chn:"", Eng:"For everyone who has will be given more, and he will have an abundance. Whoever does not have, even what he has will be taken from him.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:30, Page:1, Kor:"", Chn:"", Eng:"And throw that worthless servant outside, into the darkness, where there will be weeping and gnashing of teeth.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:31, Page:1, Kor:"", Chn:"", Eng:""When the Son of Man comes in his glory, and all the angels with him, he will sit on his throne in heavenly glory.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:32, Page:1, Kor:"", Chn:"", Eng:"All the nations will be gathered before him, and he will separate the people one from another as a shepherd separates the sheep from the goats.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:33, Page:1, Kor:"", Chn:"", Eng:"He will put the sheep on his right and the goats on his left.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:34, Page:1, Kor:"", Chn:"", Eng:""Then the King will say to those on his right, 'Come, you who are blessed by my Father; take your inheritance, the kingdom prepared for you since the creation of the world.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:35, Page:1, Kor:"", Chn:"", Eng:"For I was hungry and you gave me something to eat, I was thirsty and you gave me something to drink, I was a stranger and you invited me in,", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:36, Page:1, Kor:"", Chn:"", Eng:"I needed clothes and you clothed me, I was sick and you looked after me, I was in prison and you came to visit me.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:37, Page:1, Kor:"", Chn:"", Eng:""Then the righteous will answer him, 'Lord, when did we see you hungry and feed you, or thirsty and give you something to drink?", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:38, Page:1, Kor:"", Chn:"", Eng:"When did we see you a stranger and invite you in, or needing clothes and clothe you?", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:39, Page:1, Kor:"", Chn:"", Eng:"When did we see you sick or in prison and go to visit you?'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:40, Page:1, Kor:"", Chn:"", Eng:""The King will reply, 'I tell you the truth, whatever you did for one of the least of these brothers of mine, you did for me.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:41, Page:1, Kor:"", Chn:"", Eng:""Then he will say to those on his left, 'Depart from me, you who are cursed, into the eternal fire prepared for the devil and his angels.", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:42, Page:1, Kor:"", Chn:"", Eng:"For I was hungry and you gave me nothing to eat, I was thirsty and you gave me nothing to drink,", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:43, Page:1, Kor:"", Chn:"", Eng:"I was a stranger and you did not invite me in, I needed clothes and you did not clothe me, I was sick and in prison and you did not look after me.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:44, Page:1, Kor:"", Chn:"", Eng:""They also will answer, 'Lord, when did we see you hungry or thirsty or a stranger or needing clothes or sick or in prison, and did not help you?'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:45, Page:1, Kor:"", Chn:"", Eng:""He will reply, 'I tell you the truth, whatever you did not do for one of the least of these, you did not do for me.'", Ind:""},
  {Bible:"Matthew", Chapter:25, Verse:46, Page:1, Kor:"", Chn:"", Eng:""Then they will go away to eternal punishment, but the righteous to eternal life."", Ind:""},
]);
