// 마태복음 16장 · Matthew 16
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Matthew",16,28);
BibleDB.add([
  {Bible:"Matthew", Chapter:16, Verse:1, Page:1,
    Kor:"<표징 문제(막 8:11-13; 눅 12:54-56)> 바리새파 사람들과 사두개파 사람들이 와서, 예수를 시험하느라고, 하늘로부터 내리는 a표징을 자기들에게 보여 달라고 요청하였다.(a 12:38, 39의 '표징'은 예수의 신성을 보여주기 위한 상징으로서의 기적)",
    Chn:"法利赛人和撒都该人来试探耶稣，请他从天上显个神迹给他们看。",
    Eng:"The Pharisees and Sadducees came to Jesus and tested him by asking him to show them a sign from heaven.",
    Ind:"Kemudian datanglah orang-orang Farisi dan Saduki hendak mencobai Yesus. Mereka meminta supaya Ia memperlihatkan suatu tanda dari sorga kepada mereka."
  },
  {Bible:"Matthew", Chapter:16, Verse:2, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. <\"너희는 저녁 때에는 '하늘이 붉은 것을 보니 내일은 날씨가 맑겠구나' 하고,",
    Chn:"耶稣回答说：「晚上天发红，你们就说：『天必要晴。』",
    Eng:"He replied, \"When evening comes, you say, 'It will be fair weather, for the sky is red,'",
    Ind:"Tetapi jawab Yesus: \"Pada petang hari karena langit merah, kamu berkata: Hari akan cerah,"
  },
  {Bible:"Matthew", Chapter:16, Verse:3, Page:1,
    Kor:"아침에는 '하늘이 붉고 흐린 것을 보니 오늘은 날씨가 궂겠구나' 한다. 너희는 하늘의 징조는 분별할 줄 알면서, 시대의 b징조들은 분별하지 못하느냐?>(b 또는 '표징'. 그, '세메이온')",
    Chn:"早晨天发红，又发黑，你们就说：『今日必有风雨。』你们知道分辨天上的气色，倒不能分辨这时候的神迹。",
    Eng:"and in the morning, 'Today it will be stormy, for the sky is red and overcast.' You know how to interpret the appearance of the sky, but you cannot interpret the signs of the times.",
    Ind:"dan pada pagi hari, karena langit merah dan redup, kamu berkata: Hari buruk. Rupa langit kamu tahu membedakannya tetapi tanda-tanda zaman tidak."
  },
  {Bible:"Matthew", Chapter:16, Verse:4, Page:1,
    Kor:"악하고 음란한 세대가 표징을 요구하지만, 이 세대는, 요나의 표징 밖에는, 아무 표징도 받지 못할 것이다.\" 그리고 나서 예수께서는 그들을 남겨 두고 떠나가셨다.",
    Chn:"一个邪恶淫乱的世代求神迹，除了约拿的神迹以外，再没有神迹给他看。」耶稣就离开他们去了。",
    Eng:"A wicked and adulterous generation looks for a miraculous sign, but none will be given it except the sign of Jonah.\" Jesus then left them and went away.",
    Ind:"Angkatan yang jahat dan tidak setia ini menuntut suatu tanda. Tetapi kepada mereka tidak akan diberikan tanda selain tanda nabi Yunus.\" Lalu Yesus meninggalkan mereka dan pergi."
  },
  {Bible:"Matthew", Chapter:16, Verse:5, Page:1,
    Kor:"<바리새파 사람들과 사두개파 사람들의 누룩(막 8:14-21)> ○제자들이 건너편에 이르렀는데, 그들은 빵을 가져 오는 것을 잊었다.",
    Chn:"门徒渡到那边去，忘了带饼。",
    Eng:"When they went across the lake, the disciples forgot to take bread.",
    Ind:"Pada waktu murid-murid Yesus menyeberang danau, mereka lupa membawa roti."
  },
  {Bible:"Matthew", Chapter:16, Verse:6, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"너희는 바리새파 사람들과 사두개파 사람들의 누룩을 주의하고 경계하여라.\"",
    Chn:"耶稣对他们说：「你们要谨慎，防备法利赛人和撒都该人的酵。」",
    Eng:"\"Be careful,\" Jesus said to them. \"Be on your guard against the yeast of the Pharisees and Sadducees.\"",
    Ind:"Yesus berkata kepada mereka: \"Berjaga-jagalah dan waspadalah terhadap ragi orang Farisi dan Saduki.\""
  },
  {Bible:"Matthew", Chapter:16, Verse:7, Page:1,
    Kor:"그들은 서로 수군거리며 말하였다. \"우리가 빵을 가져오지 않았구나!\"",
    Chn:"门徒彼此议论说：「这是因为我们没有带饼吧。」",
    Eng:"They discussed this among themselves and said, \"It is because we didn't bring any bread.\"",
    Ind:"Maka mereka berpikir-pikir dan seorang berkata kepada yang lain: \"Itu dikatakan-Nya karena kita tidak membawa roti.\""
  },
  {Bible:"Matthew", Chapter:16, Verse:8, Page:1,
    Kor:"예수께서 이것을 아시고 말씀하셨다. \"믿음이 적은 사람들아, 어찌하여 너희는 빵이 없다는 것을 두고 서로 수군거리느냐?",
    Chn:"耶稣看出来，就说：「你们这小信的人，为什么因为没有饼彼此议论呢？",
    Eng:"Aware of their discussion, Jesus asked, \"You of little faith, why are you talking among yourselves about having no bread?",
    Ind:"Dan ketika Yesus mengetahui apa yang mereka perbincangkan, Ia berkata: \"Mengapa kamu memperbincangkan soal tidak ada roti? Hai orang-orang yang kurang percaya!"
  },
  {Bible:"Matthew", Chapter:16, Verse:9, Page:1,
    Kor:"너희는 아직도 깨닫지 못하느냐? 오천 명이 먹은 그 빵 다섯 개를 기억하지 못하느냐? 부스러기를 몇 광주리나 거두었더냐?",
    Chn:"你们还不明白吗？不记得那五个饼分给五千人、又收拾了多少篮子的零碎吗？",
    Eng:"Do you still not understand? Don't you remember the five loaves for the five thousand, and how many basketfuls you gathered?",
    Ind:"Belum juga kamu mengerti? Tidak kamu ingat lagi akan lima roti untuk lima ribu orang itu dan berapa bakul roti kamu kumpulkan kemudian?"
  },
  {Bible:"Matthew", Chapter:16, Verse:10, Page:1,
    Kor:"또한 사천 명이 먹은 그 빵 일곱 개를 기억하지 못하느냐? 부스러기를 몇 광주리나 거두었더냐?",
    Chn:"也不记得那七个饼分给四千人、又收拾了多少筐子的零碎吗？",
    Eng:"Or the seven loaves for the four thousand, and how many basketfuls you gathered?",
    Ind:"Ataupun akan tujuh roti untuk empat ribu orang itu dan berapa bakul kamu kumpulkan kemudian?"
  },
  {Bible:"Matthew", Chapter:16, Verse:11, Page:1,
    Kor:"내가 빵을 두고 너희에게 말한 것이 아님을, 너희는 어찌하여 깨닫지 못하느냐? 바리새파 사람들과 사두개파 사람들의 누룩을 경계하여라.\"",
    Chn:"我对你们说：『要防备法利赛人和撒都该人的酵』，这话不是指着饼说的，你们怎么不明白呢？」",
    Eng:"How is it you don't understand that I was not talking to you about bread? But be on your guard against the yeast of the Pharisees and Sadducees.\"",
    Ind:"Bagaimana mungkin kamu tidak mengerti bahwa bukan roti yang Kumaksudkan. Aku berkata kepadamu: Waspadalah terhadap ragi orang Farisi dan Saduki.\""
  },
  {Bible:"Matthew", Chapter:16, Verse:12, Page:1,
    Kor:"그제서야 그들은, 빵의 누룩이 아니라, 바리새파 사람들과 사두개파 사람들의 가르침을 경계하라고 하시는 말씀인 줄을 깨달았다.",
    Chn:"门徒这才晓得他说的不是叫他们防备饼的酵，乃是防备法利赛人和撒都该人的教训。",
    Eng:"Then they understood that he was not telling them to guard against the yeast used in bread, but against the teaching of the Pharisees and Sadducees.",
    Ind:"Ketika itu barulah mereka mengerti bahwa bukan maksud-Nya supaya mereka waspada terhadap ragi roti, melainkan terhadap ajaran orang Farisi dan Saduki."
  },
  {Bible:"Matthew", Chapter:16, Verse:13, Page:1,
    Kor:"<베드로의 고백(막 8:27-30; 눅 9:18-21)> ○예수께서 빌립보의 가이사랴 지방에 이르러서, 제자들에게 물으셨다. \"사람들이 인자를 누구라고 하느냐?\"",
    Chn:"耶稣到了凯撒利亚·腓立比的境内，就问门徒说：「人说我—人子是谁？」",
    Eng:"When Jesus came to the region of Caesarea Philippi, he asked his disciples, \"Who do people say the Son of Man is?\"",
    Ind:"Setelah Yesus tiba di daerah Kaisarea Filipi, Ia bertanya kepada murid-murid-Nya: \"Kata orang, siapakah Anak Manusia itu?\""
  },
  {Bible:"Matthew", Chapter:16, Verse:14, Page:1,
    Kor:"제자들이 대답하였다. \"c세례자 요한이라고 하는 사람들도 있고, 엘리야라고 하는 사람들도 있고, 예레미야나 예언자들 가운데에 한 분이라고 하는 사람들도 있습니다.\"(c 또는 '침례자')",
    Chn:"他们说：「有人说是施洗的约翰；有人说是以利亚；又有人说是耶利米或是先知里的一位。」",
    Eng:"They replied, \"Some say John the Baptist; others say Elijah; and still others, Jeremiah or one of the prophets.\"",
    Ind:"Jawab mereka: \"Ada yang mengatakan: Yohanes Pembaptis, ada juga yang mengatakan: Elia dan ada pula yang mengatakan: Yeremia atau salah seorang dari para nabi.\""
  },
  {Bible:"Matthew", Chapter:16, Verse:15, Page:1,
    Kor:"예수께서 그들에게 물으셨다. \"그러면 너희는 나를 누구라고 하느냐?\"",
    Chn:"耶稣说：「你们说我是谁？」",
    Eng:"\"But what about you?\" he asked. \"Who do you say I am?\"",
    Ind:"Lalu Yesus bertanya kepada mereka: \"Tetapi apa katamu, siapakah Aku ini?\""
  },
  {Bible:"Matthew", Chapter:16, Verse:16, Page:1,
    Kor:"시몬 베드로가 대답하였다. \"선생님은 살아 계신 하나님의 아들 d그리스도십니다.\"(d 또는 '메시아'. 그리스도는 그리스어이고 메시아는 히브리어임. 둘 다 '기름부음 받은 사람'을 뜻함)",
    Chn:"西门·彼得回答说：「你是基督，是永生　神的儿子。」",
    Eng:"Simon Peter answered, \"You are the Christ, the Son of the living God.\"",
    Ind:"Maka jawab Simon Petrus: \"Engkau adalah Mesias, Anak Allah yang hidup!\""
  },
  {Bible:"Matthew", Chapter:16, Verse:17, Page:1,
    Kor:"예수께서 그에게 말씀하셨다. \"시몬 바요나야, 너는 복이 있다. 너에게 이것을 알려 주신 분은, 사람이 아니라, 하늘에 계신 나의 아버지시다.",
    Chn:"耶稣对他说：「西门·巴·约拿，你是有福的！因为这不是属血肉的指示你的，乃是我在天上的父指示的。",
    Eng:"Jesus replied, \"Blessed are you, Simon son of Jonah, for this was not revealed to you by man, but by my Father in heaven.",
    Ind:"Kata Yesus kepadanya: \"Berbahagialah engkau Simon bin Yunus sebab bukan manusia yang menyatakan itu kepadamu, melainkan Bapa-Ku yang di sorga."
  },
  {Bible:"Matthew", Chapter:16, Verse:18, Page:1,
    Kor:"나도 너에게 말한다. 너는 e베드로다. 나는 이 f반석 위에다가 내 교회를 세우겠다. g죽음의 h문들이 그것을 이기지 못할 것이다.(e 그, '페트로스' f 그, '페트라' g 그, '하데스의', 곧 '죽은 자들이 모여 있는 세계의' h 또는 '세력이')",
    Chn:"我还告诉你，你是彼得，我要把我的教会建造在这磐石上；阴间的权柄不能胜过他。",
    Eng:"And I tell you that you are Peter, and on this rock I will build my church, and the gates of Hades will not overcome it.",
    Ind:"Dan Akupun berkata kepadamu: Engkau adalah Petrus dan di atas batu karang ini Aku akan mendirikan jemaat-Ku dan alam maut tidak akan menguasainya."
  },
  {Bible:"Matthew", Chapter:16, Verse:19, Page:1,
    Kor:"내가 너에게 하늘 나라의 열쇠를 주겠다. 네가 무엇이든지 땅에서 매면 하늘에서도 매일 것이요, 땅에서 풀면 하늘에서도 풀릴 것이다.\"",
    Chn:"我要把天国的钥匙给你，凡你在地上所捆绑的，在天上也要捆绑；凡你在地上所释放的，在天上也要释放。」",
    Eng:"I will give you the keys of the kingdom of heaven; whatever you bind on earth will be bound in heaven, and whatever you loose on earth will be loosed in heaven.\"",
    Ind:"Kepadamu akan Kuberikan kunci Kerajaan Sorga. Apa yang kauikat di dunia ini akan terikat di sorga dan apa yang kaulepaskan di dunia ini akan terlepas di sorga.\""
  },
  {Bible:"Matthew", Chapter:16, Verse:20, Page:1,
    Kor:"그 때에 예수께서 제자들에게 엄명하시기를, 자기가 d그리스도라는 것을 아무에게도 말하지 말라고 하셨다.(d 또는 '메시아'. 그리스도는 그리스어이고 메시아는 히브리어임. 둘 다 '기름부음 받은 사람'을 뜻함)",
    Chn:"当下，耶稣嘱咐门徒，不可对人说他是基督。",
    Eng:"Then he warned his disciples not to tell anyone that he was the Christ.",
    Ind:"Lalu Yesus melarang murid-murid-Nya supaya jangan memberitahukan kepada siapapun bahwa Ia Mesias."
  },
  {Bible:"Matthew", Chapter:16, Verse:21, Page:1,
    Kor:"<죽음과 부활을 처음으로 예고하시다(막 8:31-9:1; 눅 9:22-27)> ○그 때부터 예수께서는, 자기가 반드시 예루살렘에 올라가야 하며, 장로들과 대제사장들과 율법학자들에게 많은 고난을 받고 죽임을 당해야 하며, 사흘째 되는 날에 살아나야 한다는 것을, 제자들에게 밝히기 시작하셨다.",
    Chn:"从此，耶稣才指示门徒，他必须上耶路撒冷去，受长老、祭司长、文士许多的苦，并且被杀，第三日复活。",
    Eng:"From that time on Jesus began to explain to his disciples that he must go to Jerusalem and suffer many things at the hands of the elders, chief priests and teachers of the law, and that he must be killed and on the third day be raised to life.",
    Ind:"Sejak waktu itu Yesus mulai menyatakan kepada murid-murid-Nya bahwa Ia harus pergi ke Yerusalem dan menanggung banyak penderitaan dari pihak tua-tua, imam-imam kepala dan ahli-ahli Taurat, lalu dibunuh dan dibangkitkan pada hari ketiga."
  },
  {Bible:"Matthew", Chapter:16, Verse:22, Page:1,
    Kor:"이에 베드로가 예수를 따로 붙들고 \"주님, 안됩니다. 절대로 이런 일이 주님께 일어나서는 안됩니다\" 하고 말하면서 예수께 대들었다.",
    Chn:"彼得就拉着他，劝他说：「主啊，万不可如此！这事必不临到你身上。」",
    Eng:"Peter took him aside and began to rebuke him. \"Never, Lord!\" he said. \"This shall never happen to you!\"",
    Ind:"Tetapi Petrus menarik Yesus ke samping dan menegor Dia, katanya: \"Tuhan, kiranya Allah menjauhkan hal itu! Hal itu sekali-kali takkan menimpa Engkau.\""
  },
  {Bible:"Matthew", Chapter:16, Verse:23, Page:1,
    Kor:"그러나 예수께서는 돌아서서, 베드로에게 말씀하셨다. \"사탄아, 내 뒤로 물러가라. 너는 나에게 걸림돌이다. 너는 하나님의 일을 생각하지 않고, 사람의 일만 생각하는구나!\"",
    Chn:"耶稣转过来，对彼得说：「撒但，退我后边去吧！你是绊我脚的；因为你不体贴　神的意思，只体贴人的意思。」",
    Eng:"Jesus turned and said to Peter, \"Get behind me, Satan! You are a stumbling block to me; you do not have in mind the things of God, but the things of men.\"",
    Ind:"Maka Yesus berpaling dan berkata kepada Petrus: \"Enyahlah Iblis. Engkau suatu batu sandungan bagi-Ku, sebab engkau bukan memikirkan apa yang dipikirkan Allah, melainkan apa yang dipikirkan manusia.\""
  },
  {Bible:"Matthew", Chapter:16, Verse:24, Page:1,
    Kor:"○그 때에 예수께서는 제자들에게 말씀하셨다. \"누구든지 나를 따라오려거든, 자기를 부인하고, 제 십자가를 지고, 나를 따라 오너라.",
    Chn:"于是耶稣对门徒说：「若有人要跟从我，就当舍己，背起他的十字架来跟从我。",
    Eng:"Then Jesus said to his disciples, \"If anyone would come after me, he must deny himself and take up his cross and follow me.",
    Ind:"Lalu Yesus berkata kepada murid-murid-Nya: \"Setiap orang yang mau mengikut Aku, ia harus menyangkal dirinya, memikul salibnya dan mengikut Aku."
  },
  {Bible:"Matthew", Chapter:16, Verse:25, Page:1,
    Kor:"누구든지 자기 목숨을 구하고자 하는 사람은 잃을 것이요, 나 때문에 자기 목숨을 잃는 사람은 찾을 것이다.",
    Chn:"因为，凡要救自己生命的，必丧掉生命；凡为我丧掉生命的，必得着生命。",
    Eng:"For whoever wants to save his life will lose it, but whoever loses his life for me will find it.",
    Ind:"Karena barangsiapa mau menyelamatkan nyawanya, ia akan kehilangan nyawanya; tetapi barangsiapa kehilangan nyawanya karena Aku, ia akan memperolehnya."
  },
  {Bible:"Matthew", Chapter:16, Verse:26, Page:1,
    Kor:"사람이 온 세상을 얻고도 제 목숨을 잃으면, 무슨 이득이 있겠느냐? 또 사람이 제 목숨을 되찾는 대가로 무엇을 내놓겠느냐?",
    Chn:"人若赚得全世界，赔上自己的生命，有什么益处呢？人还能拿什么换生命呢？",
    Eng:"What good will it be for a man if he gains the whole world, yet forfeits his soul? Or what can a man give in exchange for his soul?",
    Ind:"Apa gunanya seorang memperoleh seluruh dunia tetapi kehilangan nyawanya? Dan apakah yang dapat diberikannya sebagai ganti nyawanya?"
  },
  {Bible:"Matthew", Chapter:16, Verse:27, Page:1,
    Kor:"인자가 자기 아버지의 영광에 싸여, 자기 천사들을 거느리고 올 터인데, 그 때에 그는 각 사람에게, 그 행실대로 갚아 줄 것이다.",
    Chn:"人子要在他父的荣耀里，同着众使者降临；那时候，他要照各人的行为报应各人。",
    Eng:"For the Son of Man is going to come in his Father's glory with his angels, and then he will reward each person according to what he has done.",
    Ind:"Sebab Anak Manusia akan datang dalam kemuliaan Bapa-Nya diiringi malaikat-malaikat-Nya; pada waktu itu Ia akan membalas setiap orang menurut perbuatannya."
  },
  {Bible:"Matthew", Chapter:16, Verse:28, Page:1,
    Kor:"내가 진정으로 너희에게 말한다. 여기에 서 있는 사람들 가운데는, 죽음을 맛보지 않고 살아서, 인자가 자기 왕권을 차지하고 오는 것을 볼 사람들도 있다.\"",
    Chn:"我实在告诉你们，站在这里的，有人在没尝死味以前必看见人子降临在他的国里。」",
    Eng:"I tell you the truth, some who are standing here will not taste death before they see the Son of Man coming in his kingdom.\"",
    Ind:"Aku berkata kepadamu: Sesungguhnya di antara orang yang hadir di sini ada yang tidak akan mati sebelum mereka melihat Anak Manusia datang sebagai Raja dalam Kerajaan-Nya.\""
  },
]);
