// 마태복음 9장 · Matthew 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Matthew",9,38);
BibleDB.add([
  {Bible:"Matthew", Chapter:9, Verse:1, Page:1, Kor:"", Chn:"", Eng:"Jesus stepped into a boat, crossed over and came to his own town.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:2, Page:1, Kor:"", Chn:"", Eng:"Some men brought to him a paralytic, lying on a mat. When Jesus saw their faith, he said to the paralytic, "Take heart, son; your sins are forgiven."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:3, Page:1, Kor:"", Chn:"", Eng:"At this, some of the teachers of the law said to themselves, "This fellow is blaspheming!"", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Knowing their thoughts, Jesus said, "Why do you entertain evil thoughts in your hearts?", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Which is easier: to say, 'Your sins are forgiven,' or to say, 'Get up and walk'?", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:6, Page:1, Kor:"", Chn:"", Eng:"But so that you may know that the Son of Man has authority on earth to forgive sins...." Then he said to the paralytic, "Get up, take your mat and go home."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:7, Page:1, Kor:"", Chn:"", Eng:"And the man got up and went home.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:8, Page:1, Kor:"", Chn:"", Eng:"When the crowd saw this, they were filled with awe; and they praised God, who had given such authority to men.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:9, Page:1, Kor:"", Chn:"", Eng:"As Jesus went on from there, he saw a man named Matthew sitting at the tax collector's booth. "Follow me," he told him, and Matthew got up and followed him.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:10, Page:1, Kor:"", Chn:"", Eng:"While Jesus was having dinner at Matthew's house, many tax collectors and "sinners" came and ate with him and his disciples.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:11, Page:1, Kor:"", Chn:"", Eng:"When the Pharisees saw this, they asked his disciples, "Why does your teacher eat with tax collectors and 'sinners'?"", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:12, Page:1, Kor:"", Chn:"", Eng:"On hearing this, Jesus said, "It is not the healthy who need a doctor, but the sick.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:13, Page:1, Kor:"", Chn:"", Eng:"But go and learn what this means: 'I desire mercy, not sacrifice.' For I have not come to call the righteous, but sinners."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Then John's disciples came and asked him, "How is it that we and the Pharisees fast, but your disciples do not fast?"", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:15, Page:1, Kor:"", Chn:"", Eng:"Jesus answered, "How can the guests of the bridegroom mourn while he is with them? The time will come when the bridegroom will be taken from them; then they will fast.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:16, Page:1, Kor:"", Chn:"", Eng:""No one sews a patch of unshrunk cloth on an old garment, for the patch will pull away from the garment, making the tear worse.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Neither do men pour new wine into old wineskins. If they do, the skins will burst, the wine will run out and the wineskins will be ruined. No, they pour new wine into new wineskins, and both are preserved."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:18, Page:1, Kor:"", Chn:"", Eng:"While he was saying this, a ruler came and knelt before him and said, "My daughter has just died. But come and put your hand on her, and she will live."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Jesus got up and went with him, and so did his disciples.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Just then a woman who had been subject to bleeding for twelve years came up behind him and touched the edge of his cloak.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:21, Page:1, Kor:"", Chn:"", Eng:"She said to herself, "If I only touch his cloak, I will be healed."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:22, Page:1, Kor:"", Chn:"", Eng:"Jesus turned and saw her. "Take heart, daughter," he said, "your faith has healed you." And the woman was healed from that moment.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:23, Page:1, Kor:"", Chn:"", Eng:"When Jesus entered the ruler's house and saw the flute players and the noisy crowd,", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:24, Page:1, Kor:"", Chn:"", Eng:"he said, "Go away. The girl is not dead but asleep." But they laughed at him.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:25, Page:1, Kor:"", Chn:"", Eng:"After the crowd had been put outside, he went in and took the girl by the hand, and she got up.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:26, Page:1, Kor:"", Chn:"", Eng:"News of this spread through all that region.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:27, Page:1, Kor:"", Chn:"", Eng:"As Jesus went on from there, two blind men followed him, calling out, "Have mercy on us, Son of David!"", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:28, Page:1, Kor:"", Chn:"", Eng:"When he had gone indoors, the blind men came to him, and he asked them, "Do you believe that I am able to do this?" "Yes, Lord," they replied.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Then he touched their eyes and said, "According to your faith will it be done to you";", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:30, Page:1, Kor:"", Chn:"", Eng:"and their sight was restored. Jesus warned them sternly, "See that no one knows about this."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:31, Page:1, Kor:"", Chn:"", Eng:"But they went out and spread the news about him all over that region.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:32, Page:1, Kor:"", Chn:"", Eng:"While they were going out, a man who was demon-possessed and could not talk was brought to Jesus.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:33, Page:1, Kor:"", Chn:"", Eng:"And when the demon was driven out, the man who had been mute spoke. The crowd was amazed and said, "Nothing like this has ever been seen in Israel."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:34, Page:1, Kor:"", Chn:"", Eng:"But the Pharisees said, "It is by the prince of demons that he drives out demons."", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:35, Page:1, Kor:"", Chn:"", Eng:"Jesus went through all the towns and villages, teaching in their synagogues, preaching the good news of the kingdom and healing every disease and sickness.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:36, Page:1, Kor:"", Chn:"", Eng:"When he saw the crowds, he had compassion on them, because they were harassed and helpless, like sheep without a shepherd.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:37, Page:1, Kor:"", Chn:"", Eng:"Then he said to his disciples, "The harvest is plentiful but the workers are few.", Ind:""},
  {Bible:"Matthew", Chapter:9, Verse:38, Page:1, Kor:"", Chn:"", Eng:"Ask the Lord of the harvest, therefore, to send out workers into his harvest field."", Ind:""},
]);
