// 신명기 18장 · Deuteronomy 18
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Deuteronomy",18,22);
BibleDB.add([
  {Bible:"Deuteronomy", Chapter:18, Verse:1, Page:1, Kor:"<제사장과 레위 사람의 몫> \"레위 사람 제사장과 모든 레위 지파 사람은 이스라엘 가운데서 몫이나 유산으로 받은 땅이 없으므로, 주님께 불살라 바친 제물과 주님께 바친 예물을 유산으로 받아, 먹고 살 것입니다.", Chn:"", Eng:"The priests, who are Levites--indeed the whole tribe of Levi--are to have no allotment or inheritance with Israel. They shall live on the offerings made to the LORD by fire, for that is their inheritance.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:2, Page:1, Kor:"그들이 그 겨레 가운데서 차지할 유산이 없다는 것은, 주님께서 그들에게 말씀하신 대로, 주님께서 친히 그들의 유산이기 때문입니다.", Chn:"", Eng:"They shall have no inheritance among their brothers; the LORD is their inheritance, as he promised them.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:3, Page:1, Kor:"○백성이 소나 양을 제물로 바칠 때에, 제사장이 그들에게서 받을 몫이 있는데, 앞다리와 턱과 위는 제사장에게 주어야 합니다.", Chn:"", Eng:"This is the share due the priests from the people who sacrifice a bull or a sheep: the shoulder, the jowls and the inner parts.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:4, Page:1, Kor:"또 처음 거둔 곡식과 포도주와 기름과 처음 깎은 양털도 제사장에게 주어야 합니다.", Chn:"", Eng:"You are to give them the firstfruits of your grain, new wine and oil, and the first wool from the shearing of your sheep,", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:5, Page:1, Kor:"이것은 주 당신들의 하나님이 모든 지파 가운데서 그를 택하여 세우셔서, 그와 그의 자손이 대대로 주님의 이름으로 섬기는 일을 하게 하셨기 때문입니다.", Chn:"", Eng:"for the LORD your God has chosen them and their descendants out of all your tribes to stand and minister in the LORD'S name always.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:6, Page:1, Kor:"○레위 사람은 이스라엘의 온 땅 어느 성읍에 살든지, 그에게 간절한 소원이 있어서 살던 곳을 떠난다 하더라도, 그가 주님께서 택하신 곳에 이르면, 그 곳이 어디든지,", Chn:"", Eng:"If a Levite moves from one of your towns anywhere in Israel where he is living, and comes in all earnestness to the place the LORD will choose,", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:7, Page:1, Kor:"하나님 앞에 서서 섬기는 다른 모든 레위 사람 형제와 다름없이, 주 하나님의 이름으로 직무를 수행할 수 있습니다.", Chn:"", Eng:"he may minister in the name of the LORD his God like all his fellow Levites who serve there in the presence of the LORD.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:8, Page:1, Kor:"그는 조상에게서 물려받은 것을 팔아서 얻는 수입이 있다고 하더라도, 다른 제사장과 같이 몫을 나누어 받아야 합니다.\"", Chn:"", Eng:"He is to share equally in their benefits, even though he has received money from the sale of family possessions.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:9, Page:1, Kor:"<이교 풍속에 관한 경고> ○\"당신들은 주 당신들의 하나님이 당신들에게 주시는 땅에 들어가거든, 그 곳에 사는 민족들이 하는 역겨운 일들을 본받지 마십시오.", Chn:"", Eng:"When you enter the land the LORD your God is giving you, do not learn to imitate the detestable ways of the nations there.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:10, Page:1, Kor:"당신들 가운데서 자기 아들이나 딸을 a불 가운데로 지나가게 하는 사람과 점쟁이와 복술가와 요술객과 무당과(a 또는 '불살라 제물로 바치는 사람과')", Chn:"", Eng:"Let no one be found among you who sacrifices his son or daughter in the fire, who practices divination or sorcery, interprets omens, engages in witchcraft,", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:11, Page:1, Kor:"주문을 외우는 사람과 귀신을 불러 물어 보는 사람과 박수와 혼백에게 물어 보는 사람이 있어서는 안 됩니다.", Chn:"", Eng:"or casts spells, or who is a medium or spiritist or who consults the dead.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:12, Page:1, Kor:"이런 일을 하는 사람은 모두 주님께서 미워하십니다. 주 당신들의 하나님은 이런 역겨운 일 때문에 당신들 앞에서 그들을 몰아내시는 것입니다.", Chn:"", Eng:"Anyone who does these things is detestable to the LORD, and because of these detestable practices the LORD your God will drive out those nations before you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:13, Page:1, Kor:"당신들은 주 당신들의 하나님 앞에서 완전해야 합니다.\"", Chn:"", Eng:"You must be blameless before the LORD your God.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:14, Page:1, Kor:"<예언자를 보낼 약속> ○\"당신들이 쫓아낼 민족들은 점쟁이나 복술가들의 이야기를 듣지만, 주 당신들의 하나님은 당신들에게 그런 것을 용납하지 않으십니다.", Chn:"", Eng:"The nations you will dispossess listen to those who practice sorcery or divination. But as for you, the LORD your God has not permitted you to do so.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:15, Page:1, Kor:"주 당신들의 하나님은 당신들의 동족 가운데서 나와 같은 예언자 한 사람을 일으켜 세워 주실 것이니, 당신들은 그의 말을 들어야 합니다.", Chn:"", Eng:"The LORD your God will raise up for you a prophet like me from among your own brothers. You must listen to him.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:16, Page:1, Kor:"○이것은 당신들이 호렙 산에서 총회를 가진 날에 주 당신들의 하나님께 청한 일입니다. 그 때에 당신들이 말하기를 '주 우리 하나님의 소리를 다시는 듣지 않게 하여 주시며, 무서운 큰 불도 보지 않게 하여 주십시오. 우리가 죽을까 두렵습니다' 하였습니다.", Chn:"", Eng:"For this is what you asked of the LORD your God at Horeb on the day of the assembly when you said, \"Let us not hear the voice of the LORD our God nor see this great fire anymore, or we will die.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:17, Page:1, Kor:"그 때에 주님께서 내게 말씀하시기를 '그들이 한 말이 옳다.", Chn:"", Eng:"The LORD said to me: \"What they say is good.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:18, Page:1, Kor:"나는 그들의 동족 가운데서 너와 같은 예언자 한 사람을 일으켜 세워, 나의 말을 그의 입에 담아 줄 것이다. 그는, 내가 명한 모든 것을 그들에게 다 일러줄 것이다.", Chn:"", Eng:"I will raise up for them a prophet like you from among their brothers; I will put my words in his mouth, and he will tell them everything I command him.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:19, Page:1, Kor:"그가 내 이름으로 말할 때에, 내 말을 듣지 않는 사람은, 내가 벌을 줄 것이다.", Chn:"", Eng:"If anyone does not listen to my words that the prophet speaks in my name, I myself will call him to account.", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:20, Page:1, Kor:"또 내가 말하라고 하지 않은 것을, 제 마음대로 내 이름으로 말하거나 다른 신들의 이름으로 말하는 예언자는, 죽임을 당할 것이다' 하셨습니다.", Chn:"", Eng:"But a prophet who presumes to speak in my name anything I have not commanded him to say, or a prophet who speaks in the name of other gods, must be put to death.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:21, Page:1, Kor:"○그런데 당신들이 마음 속으로, 그것이 주님께서 하신 말씀인지 아닌지를 어떻게 알겠느냐고 말하겠지만,", Chn:"", Eng:"You may say to yourselves, \"How can we know when a message has not been spoken by the LORD?\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:18, Verse:22, Page:1, Kor:"예언자가 주님의 이름으로 말한 것이 그대로 이루어지지 않으면, 그 말은 주님께서 하신 말씀이 아닙니다. 그러니 당신들은 제멋대로 말하는 그런 예언자를 두려워하지 마십시오.\"", Chn:"", Eng:"If what a prophet proclaims in the name of the LORD does not take place or come true, that is a message the LORD has not spoken. That prophet has spoken presumptuously. Do not be afraid of him.", Ind:""},
]);
