// 신명기 17장 · Deuteronomy 17
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Deuteronomy",17,20);
BibleDB.add([
  {Bible:"Deuteronomy", Chapter:17, Verse:1, Page:1, Kor:"당신들은 흠이 있거나 악질이 있는 소나 양을 주 당신들의 하나님께 제물로 바쳐서는 안 됩니다. 그런 것은 주 당신들의 하나님이 역겨워하시는 것입니다.", Chn:"", Eng:"Do not sacrifice to the LORD your God an ox or a sheep that has any defect or flaw in it, for that would be detestable to him.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:2, Page:1, Kor:"○주 당신들의 하나님이 당신들에게 주시는 성읍 안에서나 당신들 가운데서, 남자이든 여자이든, 주 당신들의 하나님의 눈에 거슬리는 악한 일을 하여, 그의 언약을 깨뜨리고,", Chn:"", Eng:"If a man or woman living among you in one of the towns the LORD gives you is found doing evil in the eyes of the LORD your God in violation of his covenant,", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:3, Page:1, Kor:"다른 신들을 찾아가서 섬기며, 내가 명하지 않은 해나 달이나 하늘의 모든 천체에 엎드려 절하는 사람이 생길 것입니다.", Chn:"", Eng:"and contrary to my command has worshiped other gods, bowing down to them or to the sun or the moon or the stars of the sky,", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:4, Page:1, Kor:"이런 일이 당신들에게 보고되어 당신들이 알게 되거든, 당신들은 이것을 잘 조사해 보아야 합니다. 그래서 이스라엘 안에서 이런 역겨운 일을 한 것이 사실로 드러나면,", Chn:"", Eng:"and this has been brought to your attention, then you must investigate it thoroughly. If it is true and it has been proved that this detestable thing has been done in Israel,", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:5, Page:1, Kor:"당신들은, 남자이든 여자이든, 이런 악한 일을 한 사람을 당신들 성문 바깥으로 끌어내어 돌로 쳐서 죽여야 합니다.", Chn:"", Eng:"take the man or woman who has done this evil deed to your city gate and stone that person to death.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:6, Page:1, Kor:"그런데 사람을 죽일 때에는 한 사람의 증언만으로는 죽일 수 없으며, 두세 사람의 증언이 있어야 합니다.", Chn:"", Eng:"On the testimony of two or three witnesses a man shall be put to death, but no one shall be put to death on the testimony of only one witness.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:7, Page:1, Kor:"죽일 때에는 증인이 맨 먼저 돌로 쳐야 하고, 그 다음에 모든 백성이 뒤따라서 돌로 쳐야 합니다. 그렇게 하여, 이런 악한 일을 당신들 가운데서 뿌리를 뽑아야 합니다.", Chn:"", Eng:"The hands of the witnesses must be the first in putting him to death, and then the hands of all the people. You must purge the evil from among you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:8, Page:1, Kor:"○당신들이 사는 성 안에서, a피 흘리는 싸움이나, 서로 다투는 일이나, 폭행하는 일로 당신들에게 판결하기 어려운 분쟁이 생기거든, 주 당신들의 하나님이 택하신 곳으로 그 사건을 가지고 올라가서,(a 또는 '살인 사건이나, 민사 사건이나, 구타 사건으로')", Chn:"", Eng:"If cases come before your courts that are too difficult for you to judge--whether bloodshed, lawsuits or assaults--take them to the place the LORD your God will choose.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:9, Page:1, Kor:"제사장인 레위 사람과 그 때에 직무를 맡고 있는 재판관에게 가서 재판을 요청하면, 그들이 당신들에게 그것에 대한 판결을 내려 줄 것입니다.", Chn:"", Eng:"Go to the priests, who are Levites, and to the judge who is in office at that time. Inquire of them and they will give you the verdict.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:10, Page:1, Kor:"당신들은 주님께서 택하신 곳에서 그들이 당신들에게 내려 준 판결에 복종해야 하고, 당신들에게 일러준 대로 지켜야 합니다.", Chn:"", Eng:"You must act according to the decisions they give you at the place the LORD will choose. Be careful to do everything they direct you to do.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:11, Page:1, Kor:"그들이 당신들에게 내리는 지시와 판결은 그대로 받아들여서 지켜야 합니다. 그들이 당신들에게 내려 준 판결을 어겨서, 좌로나 우로나 벗어나면 안 됩니다.", Chn:"", Eng:"Act according to the law they teach you and the decisions they give you. Do not turn aside from what they tell you, to the right or to the left.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:12, Page:1, Kor:"주 당신들의 하나님을 섬기는 제사장이나 재판관의 말을 듣지 않고 거역하는 사람이 있으면, 죽여야 합니다. 그렇게 하여서 이스라엘에서 그런 악한 일은 뿌리를 뽑아야 합니다.", Chn:"", Eng:"The man who shows contempt for the judge or for the priest who stands ministering there to the LORD your God must be put to death. You must purge the evil from Israel.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:13, Page:1, Kor:"그러면 온 이스라엘 백성이 듣고 두려워하며, 다시는 아무도 재판 결과를 하찮게 여기지 않을 것입니다.\"", Chn:"", Eng:"All the people will hear and be afraid, and will not be contemptuous again.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:14, Page:1, Kor:"<이스라엘의 왕도> ○\"주 당신들의 하나님이 주시는 그 땅에 들어가서 그 땅을 차지하고 살 때에, 주위의 다른 모든 민족같이 당신들도 왕을 세우고 싶다는 생각이 들거든,", Chn:"", Eng:"When you enter the land the LORD your God is giving you and have taken possession of it and settled in it, and you say, \"Let us set a king over us like all the nations around us,\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:15, Page:1, Kor:"당신들은 반드시 주 당신들의 하나님이 택하신 사람을 당신들 위에 왕으로 세워야 합니다. 당신들은 겨레 가운데서 한 사람을 왕으로 세우고, 같은 겨레가 아닌 외국 사람을 당신들의 왕으로 세워서는 안 됩니다.", Chn:"", Eng:"be sure to appoint over you the king the LORD your God chooses. He must be from among your own brothers. Do not place a foreigner over you, one who is not a brother Israelite.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:16, Page:1, Kor:"왕이라 해도 군마를 많이 가지려고 해서는 안 되며, 군마를 많이 얻으려고 그 백성을 이집트로 보내서도 안 됩니다. 이는 주님께서 다시는 당신들이 그 길로 되돌아가지 못한다고 말씀하셨기 때문입니다.", Chn:"", Eng:"The king, moreover, must not acquire great numbers of horses for himself or make the people return to Egypt to get more of them, for the LORD has told you, \"You are not to go back that way again.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:17, Page:1, Kor:"왕은 또 많은 아내를 둠으로써 그의 마음이 다른 데로 쏠리게 하는 일이 없어야 하며, 자기 것으로 은과 금을 너무 많이 모아서도 안 됩니다.", Chn:"", Eng:"He must not take many wives, or his heart will be led astray. He must not accumulate large amounts of silver and gold.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:18, Page:1, Kor:"왕위에 오른 사람은 레위 사람 제사장 앞에 보관되어 있는 b이 율법책을 두루마리에 옮겨 적어,(b '이 율법책의 복사본'을 칠십인역이 그리스어로 '듀테로노미온'이라고 번역하였고, 여기에서 '신명기'라는 책 이름이 나옴)", Chn:"", Eng:"When he takes the throne of his kingdom, he is to write for himself on a scroll a copy of this law, taken from that of the priests, who are Levites.", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:19, Page:1, Kor:"평생 자기 옆에 두고 읽으면서, 자기를 택하신 주 하나님 경외하기를 배우며, 이 율법의 모든 말씀과 규례를 성심껏 어김없이 지켜야 합니다.", Chn:"", Eng:"It is to be with him, and he is to read it all the days of his life so that he may learn to revere the LORD his God and follow carefully all the words of this law and these decrees", Ind:""},
  {Bible:"Deuteronomy", Chapter:17, Verse:20, Page:1, Kor:"마음이 교만해져서 자기 겨레를 업신여기는 일도 없고, 그 계명을 떠나서 좌로나 우로나 치우치지도 않으면, 그와 그의 자손이 오래도록 이스라엘의 왕위에 앉게 될 것입니다.\"", Chn:"", Eng:"and not consider himself better than his brothers and turn from the law to the right or to the left. Then he and his descendants will reign a long time over his kingdom in Israel.", Ind:""},
]);
