// 신명기 16장 · Deuteronomy 16
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Deuteronomy",16,22);
BibleDB.add([
  {Bible:"Deuteronomy", Chapter:16, Verse:1, Page:1, Kor:"<유월절(출 12:1-20)> \"당신들은 a아빕월을 지켜 주 당신들의 하나님께 유월절 제사를 드려야 합니다. 이는 아빕월 어느 날 밤에, 주 당신들의 하나님이 당신들을 이집트에서 건져 내셨기 때문입니다.(a 유다인의 정월. 후에 닛산이라고 부름. 양력 삼월 중순 이후)", Chn:"", Eng:"Observe the month of Abib and celebrate the Passover of the LORD your God, because in the month of Abib he brought you out of Egypt by night.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:2, Page:1, Kor:"당신들은 주님께서 자기의 이름을 두려고 택하신 그 곳에서 양과 소를 잡아, 주 당신들의 하나님께 유월절 제물로 바쳐야 합니다.", Chn:"", Eng:"Sacrifice as the Passover to the LORD your God an animal from your flock or herd at the place the LORD will choose as a dwelling for his Name.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:3, Page:1, Kor:"누룩을 넣은 빵을 이 제물과 함께 먹으면 안 됩니다. 이레 동안은 누룩을 넣지 않은 빵 곧 고난의 빵을 먹어야 합니다. 이는 당신들이 이집트 땅에서 나올 때에 급히 나왔으므로, 이집트 땅에서 나올 때의 일을 당신들이 평생토록 기억하게 하려 함입니다.", Chn:"", Eng:"Do not eat it with bread made with yeast, but for seven days eat unleavened bread, the bread of affliction, because you left Egypt in haste--so that all the days of your life you may remember the time of your departure from Egypt.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:4, Page:1, Kor:"이레 동안은 당신들의 땅의 경계 안 어디에서도 누룩이 눈에 띄어서도 안 되고, 첫날 저녁에 잡은 제물 고기를 다음날 아침까지 남겨 두어서도 안 됩니다.", Chn:"", Eng:"Let no yeast be found in your possession in all your land for seven days. Do not let any of the meat you sacrifice on the evening of the first day remain until morning.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:5, Page:1, Kor:"○유월절 제사는, 주 당신들의 하나님이 당신들에게 주시는 성읍이라 해서, 아무데서나 다 드릴 수 있는 것은 아닙니다.", Chn:"", Eng:"You must not sacrifice the Passover in any town the LORD your God gives you", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:6, Page:1, Kor:"유월절 제물로 드릴 것은, 당신들의 주 하나님께서 자기의 이름을 두려고 택하신 곳에서만 잡을 수 있으며, 잡는 때는 당신들이 이집트를 떠난 바로 그 시각 곧 초저녁 해가 질 무렵입니다.", Chn:"", Eng:"except in the place he will choose as a dwelling for his Name. There you must sacrifice the Passover in the evening, when the sun goes down, on the anniversary of your departure from Egypt.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:7, Page:1, Kor:"주 당신들의 하나님이 택하신 곳에서 고기를 구워서 먹고, 아침이 되면 당신들의 장막으로 돌아가십시오.", Chn:"", Eng:"Roast it and eat it at the place the LORD your God will choose. Then in the morning return to your tents.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:8, Page:1, Kor:"엿새 동안은 누룩을 넣지 않은 빵을 먹고, 이렛날은 주 당신들의 하나님 앞에서 성회로 모이십시오. 당신들은 어떤 일도 해서는 안 됩니다.\"", Chn:"", Eng:"For six days eat unleavened bread and on the seventh day hold an assembly to the LORD your God and do no work.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:9, Page:1, Kor:"○<칠칠절(출 34:22; 레 23:15-21)> \"그로부터 일곱 이레를 세는데, 밭에 있는 곡식에 낫을 대는 첫날부터 시작하여 일곱 이레를 세십시오.", Chn:"", Eng:"Count off seven weeks from the time you begin to put the sickle to the standing grain.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:10, Page:1, Kor:"그리고 주 당신들의 하나님이 당신들에게 주신 복을 따라, 마음에서 우러나오는 예물을 가지고 와서, 주 당신들의 하나님께 칠칠절을 지키십시오.", Chn:"", Eng:"Then celebrate the Feast of Weeks to the LORD your God by giving a freewill offering in proportion to the blessings the LORD your God has given you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:11, Page:1, Kor:"당신들은 주 당신들의 하나님이 그의 이름을 두려고 택하신 그 곳에서, 당신들과 당신들의 아들과 딸과 남종과 여종과, 성 안에서 같이 사는 레위 사람과 떠돌이와 고아와 과부까지도 함께 주 당신들의 하나님 앞에서 즐거워해야 합니다.", Chn:"", Eng:"And rejoice before the LORD your God at the place he will choose as a dwelling for his Name--you, your sons and daughters, your menservants and maidservants, the Levites in your towns, and the aliens, the fatherless and the widows living among you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:12, Page:1, Kor:"당신들은 이집트에서 종살이하던 것을 기억하고, 이 모든 규례를 어김없이 잘 지키십시오.\"", Chn:"", Eng:"Remember that you were slaves in Egypt, and follow carefully these decrees.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:13, Page:1, Kor:"<초막절(레 23:33-43)> ○\"당신들은 타작 마당과 포도주 틀에서 소출을 거두어들일 때에, 이레 동안 초막절을 지켜야 합니다.", Chn:"", Eng:"Celebrate the Feast of Tabernacles for seven days after you have gathered the produce of your threshing floor and your winepress.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:14, Page:1, Kor:"당신들은 이 절기에 당신들과 당신들의 아들과 딸과 남종과 여종과 성 안에서 같이 사는 레위 사람과 떠돌이와 고아와 과부까지도 함께 즐거워해야 합니다.", Chn:"", Eng:"Be joyful at your Feast--you, your sons and daughters, your menservants and maidservants, and the Levites, the aliens, the fatherless and the widows who live in your towns.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:15, Page:1, Kor:"당신들은 주 당신들의 하나님이 택하신 곳에서 이레 동안 초막절을 지켜야 합니다. 당신들은, 주 당신들의 하나님이 당신들의 모든 소출과 당신들이 손을 댄 모든 일에 복을 주셨기 때문에 즐거워하는 것입니다.", Chn:"", Eng:"For seven days celebrate the Feast to the LORD your God at the place the LORD will choose. For the LORD your God will bless you in all your harvest and in all the work of your hands, and your joy will be complete.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:16, Page:1, Kor:"○모든 남자는 한 해에 세 번, 무교절과 칠칠절과 초막절에, 주 당신들의 하나님이 택하신 곳으로 가서 주님을 뵈어야 합니다. 그러나 빈 손으로 주님을 뵈러 가서는 안 됩니다.", Chn:"", Eng:"Three times a year all your men must appear before the LORD your God at the place he will choose: at the Feast of Unleavened Bread, the Feast of Weeks and the Feast of Tabernacles. No man should appear before the LORD empty-handed:", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:17, Page:1, Kor:"저마다 주 당신들의 하나님으로부터 받은 복에 따라서 그 힘대로 예물을 가지고 나아가야 합니다.\"", Chn:"", Eng:"Each of you must bring a gift in proportion to the way the LORD your God has blessed you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:18, Page:1, Kor:"<공정한 재판> ○\"당신들은 주 당신들의 하나님이 각 지파에게 주시는 모든 성읍에 재판관과 지도자를 두어, 백성에게 공정한 재판을 하도록 하십시오.", Chn:"", Eng:"Appoint judges and officials for each of your tribes in every town the LORD your God is giving you, and they shall judge the people fairly.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:19, Page:1, Kor:"당신들은 재판에서 공정성을 잃어서도 안 되고, 사람의 얼굴을 보아주어서도 안 되며, 재판관이 뇌물을 받아서도 안 됩니다. 뇌물은 지혜 있는 사람의 눈을 어둡게 하고, 죄 없는 사람을 죄인으로 만듭니다.", Chn:"", Eng:"Do not pervert justice or show partiality. Do not accept a bribe, for a bribe blinds the eyes of the wise and twists the words of the righteous.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:20, Page:1, Kor:"당신들은 오직 정의만을 따라야 합니다. 그래야만 당신들이 살고, 주 당신들의 하나님이 당신들에게 주시는 땅을 당신들이 차지할 것입니다.", Chn:"", Eng:"Follow justice and justice alone, so that you may live and possess the land the LORD your God is giving you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:21, Page:1, Kor:"○당신들은, 당신들이 만든 주 당신들의 하나님의 제단 옆에, 어떤 나무로라도 아세라 목상을 만들어 세워서는 안 됩니다.", Chn:"", Eng:"Do not set up any wooden Asherah pole beside the altar you build to the LORD your God,", Ind:""},
  {Bible:"Deuteronomy", Chapter:16, Verse:22, Page:1, Kor:"그리고 주 당신들의 하나님이 미워하시는 석상을 만들어 세워서도 안 됩니다.", Chn:"", Eng:"and do not erect a sacred stone, for these the LORD your God hates.", Ind:""},
]);
