// 신명기 15장 · Deuteronomy 15
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Deuteronomy",15,23);
BibleDB.add([
  {Bible:"Deuteronomy", Chapter:15, Verse:1, Page:1, Kor:"<빚을 면제해 주는 해(레 25:1-7)> \"매 칠 년 끝에는 빚을 면제하여 주십시오.", Chn:"", Eng:"At the end of every seven years you must cancel debts.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:2, Page:1, Kor:"면제 규례는 이러합니다. 누구든지 이웃에게 돈을 꾸어 준 사람은 그 빚을 면제하여 주십시오. a주님께서 면제를 선포하였기 때문에 이웃이나 동족에게 빚을 갚으라고 다그쳐서는 안 됩니다.(a 또는 '주님의 면제년이 선포되었기 때문에')", Chn:"", Eng:"This is how it is to be done: Every creditor shall cancel the loan he has made to his fellow Israelite. He shall not require payment from his fellow Israelite or brother, because the LORD'S time for canceling debts has been proclaimed.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:3, Page:1, Kor:"이방 사람에게 준 빚은 갚으라고 할 수 있으나, 당신들의 동족에게 준 빚은 면제해 주어야 합니다.", Chn:"", Eng:"You may require payment from a foreigner, but you must cancel any debt your brother owes you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:4, Page:1, Kor:"○당신들 가운데 가난한 사람이 없게 하십시오. 그러면 주 당신들의 하나님이 당신들에게 유산으로 주어 차지하게 하시는 땅에서 당신들이 참으로 복을 받을 것입니다.", Chn:"", Eng:"However, there should be no poor among you, for in the land the LORD your God is giving you to possess as your inheritance, he will richly bless you,", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:5, Page:1, Kor:"주 당신들의 하나님의 말씀을 잘 듣고, 오늘 내가 당신들에게 명한 이 모든 명령을 다 지키면,", Chn:"", Eng:"if only you fully obey the LORD your God and are careful to follow all these commands I am giving you today.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:6, Page:1, Kor:"주 당신들의 하나님이 당신들에게 말씀하신 대로 복을 내려 주실 것입니다. 당신들이 많은 민족에게 돈을 꾸어 주기는 하겠지만 꾸지는 않겠고, 또 당신들이 많은 민족을 다스리기는 하겠지만 다스림을 받지는 않을 것입니다.", Chn:"", Eng:"For the LORD your God will bless you as he has promised, and you will lend to many nations but will borrow from none. You will rule over many nations but none will rule over you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:7, Page:1, Kor:"○주 당신들의 하나님이 당신들에게 주시는 땅의 어느 한 성읍 가운데에 가난한 동족이 살고 있거든, 당신들은 그를 인색한 마음으로 대하지 마십시오. 그 가난한 동족에게 베풀지 않으려고 당신들의 손을 움켜 쥐지 마십시오.", Chn:"", Eng:"If there is a poor man among your brothers in any of the towns of the land that the LORD your God is giving you, do not be hardhearted or tightfisted toward your poor brother.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:8, Page:1, Kor:"반드시 당신들의 손을 그에게 펴서, 그가 필요한 만큼 넉넉하게 꾸어 주십시오.", Chn:"", Eng:"Rather be openhanded and freely lend him whatever he needs.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:9, Page:1, Kor:"당신들은 삼가서 마음에 악한 생각을 품지 마십시오. 빚을 면제하여 주는 해인 일곱째 해가 가까이 왔다고 해서, b인색한 마음으로 가난한 동족을 냉대하며, 아무것도 꾸어 주지 않아서는 안 됩니다. 그가 당신들을 걸어 주님께 호소하면, 당신들이 죄인이 될 것입니다.(b 히, '궁핍한 형제에게 악한 눈을 들며')", Chn:"", Eng:"Be careful not to harbor this wicked thought: \"The seventh year, the year for canceling debts, is near,\" so that you do not show ill will toward your needy brother and give him nothing. He may then appeal to the LORD against you, and you will be found guilty of sin.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:10, Page:1, Kor:"당신들은 반드시 그에게 꾸어 주고, 줄 때에는 아깝다는 생각을 하지 마십시오. 그러면 주 당신들의 하나님이 당신들이 하는 모든 일과 당신들이 손을 대는 모든 일에 복을 내려 주실 것입니다.", Chn:"", Eng:"Give generously to him and do so without a grudging heart; then because of this the LORD your God will bless you in all your work and in everything you put your hand to.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:11, Page:1, Kor:"당신들은 반드시 손을 뻗어, 당신들의 땅에서 사는 가난하고 궁핍한 동족을 도와주십시오. 그렇다고 하여, 당신들이 사는 땅에서 가난한 사람이 없어지지는 않겠지만, 이것은 내가 당신들에게 내리는 명령입니다.\"", Chn:"", Eng:"There will always be poor people in the land. Therefore I command you to be openhanded toward your brothers and toward the poor and needy in your land.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:12, Page:1, Kor:"<종을 대우하는 법(출 21:1-11)> ○\"당신들 동족 히브리 사람이 남자든지 여자든지, 당신들에게 팔려 와서 여섯 해 동안 당신들을 섬겼거든, 일곱째 해에는 그에게 자유를 주어서 내보내십시오.", Chn:"", Eng:"If a fellow Hebrew, a man or a woman, sells himself to you and serves you six years, in the seventh year you must let him go free.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:13, Page:1, Kor:"자유를 주어서 내보낼 때에, 빈 손으로 내보내서는 안 됩니다.", Chn:"", Eng:"And when you release him, do not send him away empty-handed.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:14, Page:1, Kor:"당신들은 주 당신들의 하나님으로부터 복을 받은 대로, 당신들의 양 떼와 타작 마당에서 거둔 것과 포도주 틀에서 짜낸 것을 그에게 넉넉하게 주어서 내보내야 합니다.", Chn:"", Eng:"Supply him liberally from your flock, your threshing floor and your winepress. Give to him as the LORD your God has blessed you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:15, Page:1, Kor:"당신들이 이집트 땅에서 종살이한 것과 주 당신들의 하나님이 당신들을 거기에서 구속하여 주신 것을 생각하십시오. 그러므로 내가 오늘 이러한 것을 당신들에게 명하는 것입니다.", Chn:"", Eng:"Remember that you were slaves in Egypt and the LORD your God redeemed you. That is why I give you this command today.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:16, Page:1, Kor:"○그러나 그 종이 당신들과 당신들의 가족을 사랑하고, 당신들과 함께 있는 것을 좋아하여 '나는 이 집을 떠나가지 않겠습니다' 하고 당신들에게 말하거든,", Chn:"", Eng:"But if your servant says to you, \"I do not want to leave you,\" because he loves you and your family and is well off with you,", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:17, Page:1, Kor:"당신들은 그의 귀를 문에 대고 송곳으로 그 귓불을 뚫으십시오. 그러면 그는 영원히 당신들의 종이 될 것입니다. ○여종도 그렇게 하십시오.", Chn:"", Eng:"then take an awl and push it through his ear lobe into the door, and he will become your servant for life. Do the same for your maidservant.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:18, Page:1, Kor:"○남녀 종에게 자유를 주어서 내보내는 것을 언짢게 생각하지 마십시오. 그들은 여섯 해 동안 품팔이꾼이 받을 품삯의 두 배는 될 만큼 당신들을 섬겼습니다. 그렇게 내보내야만 주 당신들의 하나님이 당신들이 하는 모든 일에 복을 내려 주실 것입니다.\"", Chn:"", Eng:"Do not consider it a hardship to set your servant free, because his service to you these six years has been worth twice as much as that of a hired hand. And the LORD your God will bless you in everything you do.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:19, Page:1, Kor:"<처음 난 소와 양의 새끼> ○\"당신들은 소나 양의 처음 난 수컷은 구별하여 주 당신들의 하나님께 바쳐야 합니다. 처음 난 황소는 부리지 말아야 하고, 처음 난 양은 털을 깎지 말아야 합니다.", Chn:"", Eng:"Set apart for the LORD your God every firstborn male of your herds and flocks. Do not put the firstborn of your oxen to work, and do not shear the firstborn of your sheep.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:20, Page:1, Kor:"해마다 당신들과 당신들의 가족은 주 당신들의 하나님 앞 곧 주님께서 택하신 곳에서 그것을 먹어야 합니다.", Chn:"", Eng:"Each year you and your family are to eat them in the presence of the LORD your God at the place he will choose.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:21, Page:1, Kor:"그 짐승에 흠이 있어서, 다리를 절거나, 눈을 못 보거나, 그 밖에 무슨 흠이 있으면, 그것은 주 당신들의 하나님께 잡아 바치지 못합니다.", Chn:"", Eng:"If an animal has a defect, is lame or blind, or has any serious flaw, you must not sacrifice it to the LORD your God.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:22, Page:1, Kor:"그런 경우에는, 노루나 사슴을 잡아먹듯이, 정한 사람이든지 부정한 사람이든지 모두 성 안에서 그것들을 잡아먹을 수 있습니다.", Chn:"", Eng:"You are to eat it in your own towns. Both the ceremonially unclean and the clean may eat it, as if it were gazelle or deer.", Ind:""},
  {Bible:"Deuteronomy", Chapter:15, Verse:23, Page:1, Kor:"그러나 피는 먹지 말고, 물처럼 땅에 쏟아 버려야 합니다.\"", Chn:"", Eng:"But you must not eat the blood; pour it out on the ground like water.", Ind:""},
]);
