// 신명기 1장 · Deuteronomy 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Deuteronomy",1,46);
BibleDB.add([
  {Bible:"Deuteronomy", Chapter:1, Verse:1, Page:1, Kor:"", Chn:"", Eng:"These are the words Moses spoke to all Israel in the desert east of the Jordan--that is, in the Arabah--opposite Suph, between Paran and Tophel, Laban, Hazeroth and Dizahab.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:2, Page:1, Kor:"", Chn:"", Eng:"(It takes eleven days to go from Horeb to Kadesh Barnea by the Mount Seir road.)", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:3, Page:1, Kor:"", Chn:"", Eng:"In the fortieth year, on the first day of the eleventh month, Moses proclaimed to the Israelites all that the LORD had commanded him concerning them.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:4, Page:1, Kor:"", Chn:"", Eng:"This was after he had defeated Sihon king of the Amorites, who reigned in Heshbon, and at Edrei had defeated Og king of Bashan, who reigned in Ashtaroth.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:5, Page:1, Kor:"", Chn:"", Eng:"East of the Jordan in the territory of Moab, Moses began to expound this law, saying:", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:6, Page:1, Kor:"", Chn:"", Eng:"The LORD our God said to us at Horeb, \"You have stayed long enough at this mountain.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Break camp and advance into the hill country of the Amorites; go to all the neighboring peoples in the Arabah, in the mountains, in the western foothills, in the Negev and along the coast, to the land of the Canaanites and to Lebanon, as far as the great river, the Euphrates.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:8, Page:1, Kor:"", Chn:"", Eng:"See, I have given you this land. Go in and take possession of the land that the LORD swore he would give to your fathers--to Abraham, Isaac and Jacob--and to their descendants after them.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:9, Page:1, Kor:"", Chn:"", Eng:"At that time I said to you, \"You are too heavy a burden for me to carry alone.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:10, Page:1, Kor:"", Chn:"", Eng:"The LORD your God has increased your numbers so that today you are as many as the stars in the sky.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:11, Page:1, Kor:"", Chn:"", Eng:"May the LORD, the God of your fathers, increase you a thousand times and bless you as he has promised!", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:12, Page:1, Kor:"", Chn:"", Eng:"But how can I bear your problems and your burdens and your disputes all by myself?", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Choose some wise, understanding and respected men from each of your tribes, and I will set them over you.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:14, Page:1, Kor:"", Chn:"", Eng:"You answered me, \"What you propose to do is good.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:15, Page:1, Kor:"", Chn:"", Eng:"So I took the leading men of your tribes, wise and respected men, and appointed them to have authority over you--as commanders of thousands, of hundreds, of fifties and of tens and as tribal officials.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:16, Page:1, Kor:"", Chn:"", Eng:"And I charged your judges at that time: Hear the disputes between your brothers and judge fairly, whether the case is between brother Israelites or between one of them and an alien.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Do not show partiality in judging; hear both small and great alike. Do not be afraid of any man, for judgment belongs to God. Bring me any case too hard for you, and I will hear it.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:18, Page:1, Kor:"", Chn:"", Eng:"And at that time I told you everything you were to do.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Then, as the LORD our God commanded us, we set out from Horeb and went toward the hill country of the Amorites through all that vast and dreadful desert that you have seen, and so we reached Kadesh Barnea.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Then I said to you, \"You have reached the hill country of the Amorites, which the LORD our God is giving us.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:21, Page:1, Kor:"", Chn:"", Eng:"See, the LORD your God has given you the land. Go up and take possession of it as the LORD, the God of your fathers, told you. Do not be afraid; do not be discouraged.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:22, Page:1, Kor:"", Chn:"", Eng:"Then all of you came to me and said, \"Let us send men ahead to spy out the land for us and bring back a report about the route we are to take and the towns we will come to.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:23, Page:1, Kor:"", Chn:"", Eng:"The idea seemed good to me; so I selected twelve of you, one man from each tribe.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:24, Page:1, Kor:"", Chn:"", Eng:"They left and went up into the hill country, and came to the Valley of Eshcol and explored it.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Taking with them some of the fruit of the land, they brought it down to us and reported, \"It is a good land that the LORD our God is giving us.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:26, Page:1, Kor:"", Chn:"", Eng:"But you were unwilling to go up; you rebelled against the command of the LORD your God.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:27, Page:1, Kor:"", Chn:"", Eng:"You grumbled in your tents and said, \"The LORD hates us; so he brought us out of Egypt to deliver us into the hands of the Amorites to destroy us.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Where can we go? Our brothers have made us lose heart. They say, 'The people are stronger and taller than we are; the cities are large, with walls up to the sky. We even saw the Anakites there.'\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Then I said to you, \"Do not be terrified; do not be afraid of them.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:30, Page:1, Kor:"", Chn:"", Eng:"The LORD your God, who is going before you, will fight for you, as he did for you in Egypt, before your very eyes,", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:31, Page:1, Kor:"", Chn:"", Eng:"and in the desert. There you saw how the LORD your God carried you, as a father carries his son, all the way you went until you reached this place.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:32, Page:1, Kor:"", Chn:"", Eng:"In spite of this, you did not trust in the LORD your God,", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:33, Page:1, Kor:"", Chn:"", Eng:"who went ahead of you on your journey, in fire by night and in a cloud by day, to search out places for you to camp and to show you the way you should go.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:34, Page:1, Kor:"", Chn:"", Eng:"When the LORD heard what you said, he was angry and solemnly swore:", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:35, Page:1, Kor:"", Chn:"", Eng:"\"Not a man of this evil generation shall see the good land I swore to give your forefathers,", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:36, Page:1, Kor:"", Chn:"", Eng:"except Caleb son of Jephunneh. He will see it, and I will give him and his descendants the land he set his feet on, because he followed the LORD wholeheartedly.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:37, Page:1, Kor:"", Chn:"", Eng:"Because of you the LORD became angry with me also and said, \"You shall not enter it, either.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:38, Page:1, Kor:"", Chn:"", Eng:"But your assistant, Joshua son of Nun, will enter it. Encourage him, because he will lead Israel to inherit it.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:39, Page:1, Kor:"", Chn:"", Eng:"And the little ones that you said would be taken captive, your children who do not yet know good from bad--they will enter the land. I will give it to them and they will take possession of it.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:40, Page:1, Kor:"", Chn:"", Eng:"But as for you, turn around and set out toward the desert along the route to the Red Sea.\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:41, Page:1, Kor:"", Chn:"", Eng:"Then you replied, \"We have sinned against the LORD. We will go up and fight, as the LORD our God commanded us.\" So every one of you put on his weapons, thinking it easy to go up into the hill country.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:42, Page:1, Kor:"", Chn:"", Eng:"But the LORD said to me, \"Tell them, 'Do not go up and fight, because I will not be with you. You will be defeated by your enemies.'\"", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:43, Page:1, Kor:"", Chn:"", Eng:"So I told you, but you would not listen. You rebelled against the LORD'S command and in your arrogance you marched up into the hill country.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:44, Page:1, Kor:"", Chn:"", Eng:"The Amorites who lived in those hills came out against you; they chased you like a swarm of bees and beat you down from Seir all the way to Hormah.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:45, Page:1, Kor:"", Chn:"", Eng:"You came back and wept before the LORD, but he paid no attention to your weeping and turned a deaf ear to you.", Ind:""},
  {Bible:"Deuteronomy", Chapter:1, Verse:46, Page:1, Kor:"", Chn:"", Eng:"And so you stayed in Kadesh many days--all the time you spent there.", Ind:""},
]);
