// 신명기 3장 · Deuteronomy 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Deuteronomy",3,29);
BibleDB.add([
  {Bible:"Deuteronomy", Chapter:3, Verse:1, Page:1,
    Kor:"<이스라엘이 바산 왕 옥을 쳐부수다(민 21:31-35)> \"그 다음에 우리는 방향을 바꾸어서 바산 길로 올라갔습니다. 그러나 바산 왕 옥이 우리를 맞아 싸우려고, 자기의 군대를 모두 거느리고 에드레이로 나왔습니다.",
    Chn:"「以后，我们转回，向巴珊去。巴珊王噩和他的众民都出来，在以得来与我们交战。",
    Eng:"Next we turned and went up along the road toward Bashan, and Og king of Bashan with his whole army marched out to meet us in battle at Edrei.",
    Ind:"\"Kemudian beloklah kita dan maju ke arah Basan. Dan Og, raja Basan, dengan seluruh tentaranya maju mendatangi kita, untuk berperang di Edrei."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:2, Page:1,
    Kor:"그 때에 주님께서 나에게 말씀하시기를 '그를 두려워하지 말아라. 내가 그와 그의 온 군대와 그의 땅을 너의 손에 넘겼으니, 전에 헤스본에 사는 아모리 왕 시혼을 무찌른 것처럼 그를 무찔러라' 하셨습니다.",
    Chn:"耶和华对我说：『不要怕他！因我已将他和他的众民，并他的地，都交在你手中；你要待他像从前待住希实本的亚摩利王西宏一样。』",
    Eng:"The LORD said to me, \"Do not be afraid of him, for I have handed him over to you with his whole army and his land. Do to him what you did to Sihon king of the Amorites, who reigned in Heshbon.\"",
    Ind:"Tetapi TUHAN berfirman kepadaku: Janganlah takut kepadanya, sebab Aku menyerahkan dia ke dalam tanganmu beserta seluruh tentaranya dan negerinya, dan perlakukanlah dia seperti yang kaulakukan terhadap Sihon, raja orang Amori, yang diam di Hesybon."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:3, Page:1,
    Kor:"○주 우리의 하나님은 바산 왕 옥과 그의 백성을 모두 우리 손에 넘겨 주셨으므로, 우리는 그들을 한 사람도 남김없이 쳐죽였습니다.",
    Chn:"于是耶和华—我们的　神也将巴珊王噩和他的众民都交在我们手中；我们杀了他们，没有留下一个。",
    Eng:"So the LORD our God also gave into our hands Og king of Bashan and all his army. We struck them down, leaving no survivors.",
    Ind:"Dan TUHAN, Allah kita, menyerahkan juga Og, raja Basan, beserta seluruh tentaranya ke dalam tangan kita dan kita mengalahkan dia, sehingga tidak seorangpun luput."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:4, Page:1,
    Kor:"그 때에 우리는 그의 성읍을 하나도 남김없이 다 점령하였는데, 바산 왕국의 옥이 다스린 아르곱 전 지역의 성읍은 예순 개나 되었습니다.",
    Chn:"那时，我们夺了他所有的城，共有六十座，没有一座城不被我们所夺。这为亚珥歌伯的全境，就是巴珊地噩王的国。",
    Eng:"At that time we took all his cities. There was not one of the sixty cities that we did not take from them--the whole region of Argob, Og's kingdom in Bashan.",
    Ind:"Pada waktu itu kita merebut segala kotanya; tidak ada kota yang tidak kita rampas dari pada mereka: enam puluh kota, seluruh wilayah Argob, kerajaan Og di Basan."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:5, Page:1,
    Kor:"이 성읍은 모두 높은 성벽과 성문과 빗장으로 방비되어 있었습니다. 그리고 그 밖에 성벽이 없는 마을들도 많았습니다.",
    Chn:"这些城都有坚固的高墙，有门有闩。此外还有许多无城墙的乡村。",
    Eng:"All these cities were fortified with high walls and with gates and bars, and there were also a great many unwalled villages.",
    Ind:"Semuanya itu adalah kota berkubu, dengan tembok yang tinggi-tinggi, dengan pintu-pintu gerbang dan palang-palangnya; lain dari pada itu sangat banyak kota yang tidak berkubu."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:6, Page:1,
    Kor:"우리는 헤스본 왕 시혼에게 한 것처럼 그들을 전멸시키고, 모든 성읍에서 남자 여자 어린 아이 할 것 없이 전멸시켰습니다.",
    Chn:"我们将这些都毁灭了，像从前待希实本王西宏一样，把有人烟的各城，连女人带孩子，尽都毁灭；",
    Eng:"We completely destroyed them, as we had done with Sihon king of Heshbon, destroying every city--men, women and children.",
    Ind:"Kita menumpas seluruh penduduknya, seperti yang kita lakukan terhadap Sihon, raja Hesybon, dengan menumpas penduduk setiap kota: laki-laki, perempuan dan anak-anak."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:7, Page:1,
    Kor:"그러나 성읍에서 노획한 모든 집짐승과 물건들은 우리의 전리품으로 삼았습니다.",
    Chn:"惟有一切牲畜和城中的财物都取为自己的掠物。",
    Eng:"But all the livestock and the plunder from their cities we carried off for ourselves.",
    Ind:"Tetapi segala hewan dan jarahan dari kota-kota itu kita rampas bagi kita sendiri."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:8, Page:1,
    Kor:"○그 때에 우리는, 요단 강 동쪽 아르논 개울 가에서 헤르몬 산까지의 땅을, 두 아모리 왕의 손에서 빼앗았습니다.",
    Chn:"那时，我们从约旦河东两个亚摩利王的手将亚嫩谷直到黑门山之地夺过来（",
    Eng:"So at that time we took from these two kings of the Amorites the territory east of the Jordan, from the Arnon Gorge as far as Mount Hermon.",
    Ind:"Jadi pada waktu itu dari tangan kedua raja orang Amori itu kita merampas negeri yang di seberang sungai Yordan, mulai dari sungai Arnon sampai gunung Hermon"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:9, Page:1,
    Kor:"(시돈 사람들은 헤르몬을 시룐이라 하였고, 아모리 사람들은 스닐이라고 하였다.)",
    Chn:"这黑门山，西顿人称为西连，亚摩利人称为示尼珥），",
    Eng:"(Hermon is called Sirion by the Sidonians; the Amorites call it Senir.)",
    Ind:"--orang Sidon menyebut Hermon itu Siryon dan orang Amori menyebutnya Senir--,"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:10, Page:1,
    Kor:"우리가 빼앗은 땅은, 고원지대의 모든 성읍과, 온 길르앗과 바산의 온 땅, 곧 바산 왕 옥이 다스리는 성읍인 살르가와 에드레이까지입니다.\"",
    Chn:"就是夺了平原的各城、基列全地、巴珊全地，直到撒迦和以得来，都是巴珊王噩国内的城邑。（",
    Eng:"We took all the towns on the plateau, and all Gilead, and all Bashan as far as Salecah and Edrei, towns of Og's kingdom in Bashan.",
    Ind:"segala kota di dataran tinggi, seluruh Gilead dan seluruh Basan sampai Salkha dan Edrei, kota-kota kerajaan Og di Basan."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:11, Page:1,
    Kor:"○(르바임 족속 가운데서 살아 남은 사람은 오직 바산 왕 옥뿐이었다. 쇠로 만든 그의 a침대는, 지금도 암몬 자손이 사는 랍바에 있다. 그것은, b보통 자로 재어서, 길이가 아홉 자요 너비가 넉 자나 된다.)(a 또는 '관' b 히, '사람의 자로 재어서')",
    Chn:"利乏音人所剩下的只有巴珊王噩。他的床是铁的，长九肘，宽四肘，都是以人肘为度。现今岂不是在亚扪人的拉巴吗？）」",
    Eng:"(Only Og king of Bashan was left of the remnant of the Rephaites. His bed was made of iron and was more than thirteen feet long and six feet wide. It is still in Rabbah of the Ammonites.)",
    Ind:"Hanya Og, raja Basan, yang tinggal hidup dari sisa-sisa orang Refaim. Sesungguhnya, ranjangnya adalah ranjang dari besi; bukankah itu masih ada di kota Raba bani Amon? Sembilan hasta panjangnya dan empat hasta lebarnya, menurut hasta biasa.\""
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:12, Page:1,
    Kor:"<요단 강 동쪽에 자리잡은 지파들(민 32:1-42)> ○\"우리가 그 땅을 차지하였을 때에, 나는 르우벤 자손과 갓 자손에게 아르논 골짜기 곁에 있는 아로엘에서부터 길르앗 산지의 반쪽과 거기에 있는 성읍들을 주었습니다.",
    Chn:"「那时，我们得了这地。从亚嫩谷边的亚罗珥起，我将基列山地的一半，并其中的城邑，都给了吕便人和迦得人。",
    Eng:"Of the land that we took over at that time, I gave the Reubenites and the Gadites the territory north of Aroer by the Arnon Gorge, including half the hill country of Gilead, together with its towns.",
    Ind:"\"Adapun negeri itu telah kita duduki pada waktu itu; mulai dari Aroer yang di tepi sungai Arnon, beserta setengah dari pegunungan Gilead dengan kota-kotanya aku berikan kepada orang Ruben dan orang Gad;"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:13, Page:1,
    Kor:"므낫세 반쪽 지파에게는, 길르앗의 남은 땅과 옥의 나라인 온 바산 지역을 주었습니다.\" (아르곱의 모든 지역 곧 바산을 옛적에는 르바임의 땅이라고 하였다.",
    Chn:"其余的基列地和巴珊全地，就是噩王的国，我给了玛拿西半支派。亚珥歌伯全地乃是巴珊全地；这叫做利乏音人之地。",
    Eng:"The rest of Gilead and also all of Bashan, the kingdom of Og, I gave to the half tribe of Manasseh. (The whole region of Argob in Bashan used to be known as a land of the Rephaites.",
    Ind:"dan yang masih tinggal dari Gilead beserta seluruh Basan, kerajaan Og, yakni seluruh wilayah Argob, aku berikan kepada suku Manasye yang setengah itu. --Seluruh Basan ini disebut negeri orang Refaim. --"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:14, Page:1,
    Kor:"므낫세의 아들 야일은 그술 족속과 마아갓 족속 경계까지 이르는 아르곱 땅을 모두 차지하였다. 그래서 오늘날까지 그의 이름을 따라, 이 바산 지역을 c하봇야일이라고 한다.)(c '야일의 촌락')",
    Chn:"玛拿西的子孙睚珥占了亚珥歌伯全境，直到基述人和玛迦人的交界，就按自己的名称这巴珊地为哈倭特·睚珥，直到今日。",
    Eng:"Jair, a descendant of Manasseh, took the whole region of Argob as far as the border of the Geshurites and the Maacathites; it was named after him, so that to this day Bashan is called Havvoth Jair.)",
    Ind:"Yair, anak Manasye, mengambil seluruh wilayah Argob sampai daerah orang Gesur dan orang Maakha, dan menamai daerah itu, yakni Basan, menurut namanya sendiri: Hawot-Yair, sampai sekarang."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:15, Page:1,
    Kor:"○\"므낫세 지파의 한 가문인 마길에게는 길르앗을 주었습니다.",
    Chn:"我又将基列给了玛吉。",
    Eng:"And I gave Gilead to Makir.",
    Ind:"Kepada Makhir kuberikan Gilead."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:16, Page:1,
    Kor:"그리고 르우벤 자손과 갓 자손에게는, 길르앗에서 계곡 중앙을 경계로 한 아르논 계곡까지와 암몬 자손의 경계인 얍복 강까지를 주었습니다.",
    Chn:"从基列到亚嫩谷，以谷中为界，直到亚扪人交界的雅博河，我给了吕便人和迦得人，",
    Eng:"But to the Reubenites and the Gadites I gave the territory extending from Gilead down to the Arnon Gorge (the middle of the gorge being the border) and out to the Jabbok River, which is the border of the Ammonites.",
    Ind:"Kepada orang Ruben dan kepada orang Gad kuberikan sebagian dari Gilead, sebelah sini sampai sungai Arnon, yakni setengah dari sungai itu dengan daerah pinggirnya, dan sebelah sana sampai sungai Yabok, batas daerah bani Amon;"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:17, Page:1,
    Kor:"그들이 차지한 지역은 서쪽으로는 요단 강까지 이르고, 북쪽으로는 긴네렛 호수까지 이르고, 남쪽으로는 사해까지 이르고, 동쪽으로는 비스가 산 기슭까지 이릅니다.",
    Chn:"又将亚拉巴和靠近约旦河之地，从基尼烈直到亚拉巴海，就是盐海，并毗斯迦山根东边之地，都给了他们。",
    Eng:"Its western border was the Jordan in the Arabah, from Kinnereth to the Sea of the Arabah (the Salt Sea), below the slopes of Pisgah.",
    Ind:"selanjutnya Araba-Yordan dan sungai Yordan dengan daerah pinggirnya, mulai dari Kineret sampai ke Laut Araba, yakni Laut Asin di kaki lereng gunung Pisga ke arah timur."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:18, Page:1,
    Kor:"○그 때에 내가 당신들에게 명령하였습니다. '주 당신들의 하나님은 당신들에게 요단 강 동쪽에 있는 이 땅을 주셔서 차지하게 하셨습니다. 그러므로 당신들은, 당신들의 동기인 이스라엘의 다른 지파들도 땅을 차지할 수 있도록 도와주어야 합니다. 당신들의 용사들은 무장을 하고 이스라엘의 다른 05 3:지파들보다 앞서서 요단 강을 건너가십시오.",
    Chn:"「那时，我吩咐你们说：『耶和华—你们的　神已将这地赐给你们为业；你们所有的勇士都要带着兵器，在你们的弟兄以色列人前面过去。",
    Eng:"I commanded you at that time: \"The LORD your God has given you this land to take possession of it. But all your able-bodied men, armed for battle, must cross over ahead of your brother Israelites.",
    Ind:"Pada waktu itu aku memerintahkan kepadamu, demikian: TUHAN, Allahmu, telah memberikan negeri ini kepadamu untuk dimiliki; namun kamu, yakni semua orang yang gagah perkasa, harus menyeberang dengan bersenjata di depan saudara-saudaramu, orang Israel."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:19, Page:1,
    Kor:"다만 당신들의 아내와 어린 아이들은 여기에 남아 있게 하십시오. 그리고 당신들에게 집짐승이 많다는 것은 내가 알고 있으니, 그 집짐승도 당신들의 가족과 함께, 내가 당신들에게 나누어 준 성읍에 머물러 있게 하십시오.",
    Chn:"但你们的妻子、孩子、牲畜（我知道你们有许多的牲畜）可以住在我所赐给你们的各城里。",
    Eng:"However, your wives, your children and your livestock (I know you have much livestock) may stay in the towns I have given you,",
    Ind:"Hanya isteri dan anak-anakmu serta ternak-ternakmu--aku tahu ada banyak ternak padamu--boleh tinggal di kota-kota yang telah kuberikan kepadamu,"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:20, Page:1,
    Kor:"주님께서는 당신들과 마찬가지로 당신들의 동기들에게도 편히 쉴 곳을 주실 것이니, 그들이 주 당신들의 하나님이 요단 강 서쪽에 마련하여 주신 땅을 차지한 다음에라야, 당신들은 제각기 내가 당신들에게 준 이 땅으로 돌아올 수 있습니다.'",
    Chn:"等到你们弟兄在约旦河那边，也得耶和华—你们　神所赐给他们的地，又使他们得享平安，与你们一样，你们才可以回到我所赐给你们为业之地。』",
    Eng:"until the LORD gives rest to your brothers as he has to you, and they too have taken over the land that the LORD your God is giving them, across the Jordan. After that, each of you may go back to the possession I have given you.\"",
    Ind:"sampai TUHAN mengaruniakan keamanan kepada saudara-saudaramu seperti kepadamu, dan merekapun memiliki negeri, yang diberikan TUHAN, Allahmu, kepada mereka di seberang sungai Yordan. Sesudah itu bolehlah kamu pulang, masing-masing ke tanah miliknya yang telah kuberikan kepadamu."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:21, Page:1,
    Kor:"○그 때에 내가 여호수아에게 말하였습니다. '너는, 주 d우리의 하나님이 이 두 아모리 왕에게 어떻게 하였는가를, 두 눈으로 똑똑히 보았다. 주님께서는, 네가 지나가는 모든 나라에서도 이와 같이 하실 것이다.",
    Chn:"那时我吩咐约书亚说：『你亲眼看见了耶和华—你　神向这二王所行的；耶和华也必向你所要去的各国照样行。",
    Eng:"At that time I commanded Joshua: \"You have seen with your own eyes all that the LORD your God has done to these two kings. The LORD will do the same to all the kingdoms over there where you are going.",
    Ind:"Dan kepada Yosua kuperintahkan pada waktu itu, demikian: Matamu sendirilah yang melihat segala yang dilakukan TUHAN, Allahmu, terhadap kedua raja itu. Demikianlah akan dilakukan TUHAN terhadap segala kerajaan, ke mana engkau pergi."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:22, Page:1,
    Kor:"그들을 두려워하지 말아라. 주 d우리의 하나님이 너를 대신하여 싸우실 것이다.'\"(d 히, '당신들의 하나님')",
    Chn:"你不要怕他们，因那为你争战的是耶和华—你的　神。』」",
    Eng:"Do not be afraid of them; the LORD your God himself will fight for you.\"",
    Ind:"Janganlah takut kepada mereka, sebab TUHAN, Allahmu, Dialah yang berperang untukmu.\""
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:23, Page:1,
    Kor:"<모세가 가나안 진입을 허락받지 못하다> ○\"그 때에 내가 주님께 간구하였습니다.",
    Chn:"「那时，我恳求耶和华说：",
    Eng:"At that time I pleaded with the LORD:",
    Ind:"\"Juga pada waktu itu aku mohon kasih karunia dari pada TUHAN, demikian:"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:24, Page:1,
    Kor:"'주 하나님, 주님께서는 주님의 크심과 권능을 주님의 종에게 나타내 보이셨습니다. 하늘과 땅 사이에 어떤 신이 주님께서 권능으로 하신 것과 같은 일을 할 수 있겠습니까?",
    Chn:"『主耶和华啊，你已将你的大力大能显给仆人看。在天上，在地下，有什么神能像你行事、像你有大能的作为呢？",
    Eng:"\"O Sovereign LORD, you have begun to show to your servant your greatness and your strong hand. For what god is there in heaven or on earth who can do the deeds and mighty works you do?",
    Ind:"Ya, Tuhan ALLAH, Engkau telah mulai memperlihatkan kepada hamba-Mu ini kebesaran-Mu dan tangan-Mu yang kuat; sebab allah manakah di langit dan di bumi, yang dapat melakukan perbuatan perkasa seperti Engkau?"
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:25, Page:1,
    Kor:"부디 저를 건너가게 하여 주십시오. 그래서 요단 저쪽 아름다운 땅과 아름다운 산과 레바논을 보게 하여 주십시오.'",
    Chn:"求你容我过去，看约旦河那边的美地，就是那佳美的山地和黎巴嫩。』",
    Eng:"Let me go over and see the good land beyond the Jordan--that fine hill country and Lebanon.\"",
    Ind:"Biarlah aku menyeberang dan melihat negeri yang baik yang di seberang sungai Yordan, tanah pegunungan yang baik itu, dan gunung Libanon."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:26, Page:1,
    Kor:"○그러나 주님께서는, 당신들 때문에 나에게 진노하셔서, 나의 간구를 들어 주지 않으셨습니다. 주님께서 나에게 말씀하셨습니다. '이것으로 네게 족하니, 이 일 때문에 더 이상 나에게 말하지 말아라.",
    Chn:"但耶和华因你们的缘故向我发怒，不应允我，对我说：『罢了！你不要向我再提这事。",
    Eng:"But because of you the LORD was angry with me and would not listen to me. \"That is enough,\" the LORD said. \"Do not speak to me anymore about this matter.",
    Ind:"Tetapi TUHAN murka terhadap aku oleh karena kamu dan tidaklah mendengarkan permohonanku. TUHAN berfirman kepadaku: Cukup! Jangan lagi bicarakan perkara itu dengan Aku."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:27, Page:1,
    Kor:"너는 이 요단 강을 건너가지 못할 것이니, 저 비스가 산 꼭대기에 올라가서, 너의 눈을 들어, 동서남북 사방을 바라보아라.",
    Chn:"你且上毗斯迦山顶去，向东、西、南、北举目观望，因为你必不能过这约旦河。",
    Eng:"Go up to the top of Pisgah and look west and north and south and east. Look at the land with your own eyes, since you are not going to cross this Jordan.",
    Ind:"Naiklah ke puncak gunung Pisga dan layangkanlah pandangmu ke barat, ke utara, ke selatan dan ke timur dan lihatlah baik-baik, sebab sungai Yordan ini tidak akan kauseberangi."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:28, Page:1,
    Kor:"너는 여호수아에게 너의 직분을 맡겨서, 그를 격려하고, 그에게 용기를 주어라. 그는 이 백성을 이끌고 건너갈 사람이며, 네가 보는 땅을 그들에게 유산으로 나누어 줄 사람이다.'",
    Chn:"你却要嘱咐约书亚，勉励他，使他胆壮；因为他必在这百姓前面过去，使他们承受你所要观看之地。』",
    Eng:"But commission Joshua, and encourage and strengthen him, for he will lead this people across and will cause them to inherit the land that you will see.\"",
    Ind:"Dan berilah perintah kepada Yosua, kuatkan dan teguhkanlah hatinya, sebab dialah yang akan menyeberang di depan bangsa ini dan dialah yang akan memimpin mereka sampai mereka memiliki negeri yang akan kaulihat itu."
  },
  {Bible:"Deuteronomy", Chapter:3, Verse:29, Page:1,
    Kor:"○그 때에 우리는 벳브올 맞은쪽 골짜기에 머물러 있었습니다.\"",
    Chn:"于是我们住在伯·毗珥对面的谷中。」",
    Eng:"So we stayed in the valley near Beth Peor.",
    Ind:"Demikianlah kita tinggal di lembah di tentangan Bet-Peor.\""
  },
]);
