// 신명기 23장 · Deuteronomy 23
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Deuteronomy",23,25);
BibleDB.add([
  {Bible:"Deuteronomy", Chapter:23, Verse:1, Page:1,
    Kor:"<주님의 총회 회원이 될 수 없는 사람들> \"고환이 터졌거나 음경이 잘린 사람은, 주님의 총회 회원이 되지 못합니다.",
    Chn:"「凡外肾受伤的，或被阉割的，不可入耶和华的会。",
    Eng:"No one who has been emasculated by crushing or cutting may enter the assembly of the LORD.",
    Ind:"\"Orang yang hancur buah pelirnya atau yang terpotong kemaluannya, janganlah masuk jemaah TUHAN."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:2, Page:1,
    Kor:"○사생아도 주님의 총회 회원이 되지 못하고, 그 자손은 십 대에 이르기까지 주님의 총회 회원이 되지 못합니다.",
    Chn:"「私生子不可入耶和华的会；他的子孙，直到十代，也不可入耶和华的会。",
    Eng:"No one born of a forbidden marriage nor any of his descendants may enter the assembly of the LORD, even down to the tenth generation.",
    Ind:"Seorang anak haram janganlah masuk jemaah TUHAN, bahkan keturunannya yang kesepuluhpun tidak boleh masuk jemaah TUHAN."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:3, Page:1,
    Kor:"○암몬 사람과 모압 사람은 주님의 총회 회원이 되지 못합니다. 그 자손은 십 대가 아니라, 영원히 주님의 총회 회원이 되지 못합니다.",
    Chn:"「亚扪人或是摩押人不可入耶和华的会；他们的子孙，虽过十代，也永不可入耶和华的会。",
    Eng:"No Ammonite or Moabite or any of his descendants may enter the assembly of the LORD, even down to the tenth generation.",
    Ind:"Seorang Amon atau seorang Moab janganlah masuk jemaah TUHAN, bahkan keturunannya yang kesepuluhpun tidak boleh masuk jemaah TUHAN sampai selama-lamanya,"
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:4, Page:1,
    Kor:"그들은 당신들이 이집트에서 나올 때에, 먹을 것과 마실 것을 가지고 와서 당신들을 맞아들이기는커녕, 당신들을 저주하려고 브올의 아들 발람에게 뇌물을 주어 메소포타미아 지방의 브돌에서 그를 불러온 사람들입니다.",
    Chn:"因为你们出埃及的时候，他们没有拿食物和水在路上迎接你们，又因他们雇了美索不达米亚的毗夺人比珥的儿子巴兰来咒诅你们。",
    Eng:"For they did not come to meet you with bread and water on your way when you came out of Egypt, and they hired Balaam son of Beor from Pethor in Aram Naharaim to pronounce a curse on you.",
    Ind:"karena mereka tidak menyongsong kamu dengan roti dan air pada waktu perjalananmu keluar dari Mesir, dan karena mereka mengupah Bileam bin Beor dari Petor di Aram-Mesopotamia melawan engkau, supaya dikutukinya engkau."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:5, Page:1,
    Kor:"그러나 주 당신들의 하나님이 당신들을 사랑하시기 때문에, 주님께서 발람의 말을 듣지 않으시고, 오히려 그 저주를 복으로 바꾸셨습니다.",
    Chn:"然而耶和华—你的　神不肯听从巴兰，却使那咒诅的言语变为祝福的话，因为耶和华—你的　神爱你。",
    Eng:"However, the LORD your God would not listen to Balaam but turned the curse into a blessing for you, because the LORD your God loves you.",
    Ind:"Tetapi TUHAN, Allahmu, tidak mau mendengarkan Bileam dan TUHAN, Allahmu, telah mengubah kutuk itu menjadi berkat bagimu, karena TUHAN, Allahmu, mengasihi engkau."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:6, Page:1,
    Kor:"당신들은 당신들의 평생에 그들이 조금이라도 번영하거나 성공할 틈을 주어서는 안 됩니다.",
    Chn:"你一生一世永不可求他们的平安和他们的利益。",
    Eng:"Do not seek a treaty of friendship with them as long as you live.",
    Ind:"Selama engkau hidup, janganlah engkau mengikhtiarkan kesejahteraan dan kebahagiaan mereka sampai selama-lamanya."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:7, Page:1,
    Kor:"○당신들은 에돔 사람을 미워해서는 안 됩니다. 그들은 당신들의 친족입니다. 이집트 사람을 미워해서도 안 됩니다. 당신들이 그들의 땅에서 나그네로 살았기 때문입니다.",
    Chn:"「不可憎恶以东人，因为他是你的弟兄。不可憎恶埃及人，因为你在他的地上作过寄居的。",
    Eng:"Do not abhor an Edomite, for he is your brother. Do not abhor an Egyptian, because you lived as an alien in his country.",
    Ind:"Janganlah engkau menganggap keji orang Edom, sebab dia saudaramu. Janganlah engkau menganggap keji orang Mesir, sebab engkaupun dahulu adalah orang asing di negerinya."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:8, Page:1,
    Kor:"그들에게서 태어난 삼 대 자손들은 주님의 총회 회원이 될 수 있습니다.\"",
    Chn:"他们第三代子孙可以入耶和华的会。」",
    Eng:"The third generation of children born to them may enter the assembly of the LORD.",
    Ind:"Anak-anak yang lahir bagi mereka dalam keturunan yang ketiga, boleh masuk jemaah TUHAN.\""
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:9, Page:1,
    Kor:"<진을 깨끗하게 하는 법> ○\"당신들이 진을 치고 적과 맞서고 있는 동안에는, 어떤 악한 일도 스스로 삼가야 합니다.",
    Chn:"「你出兵攻打仇敌，就要远避诸恶。",
    Eng:"When you are encamped against your enemies, keep away from everything impure.",
    Ind:"\"Apabila engkau maju dengan tentaramu melawan musuhmu, maka haruslah engkau menjaga diri terhadap segala yang jahat."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:10, Page:1,
    Kor:"당신들 가운데 누가 밤에 몽설하여 부정을 탔을 때에, 그 사람은 진 밖으로 나가서 머물러 있어야 합니다.",
    Chn:"「你们中间，若有人夜间偶然梦遗，不洁净，就要出到营外，不可入营；",
    Eng:"If one of your men is unclean because of a nocturnal emission, he is to go outside the camp and stay there.",
    Ind:"Apabila ada di antaramu seorang laki-laki yang tidak tahir disebabkan oleh sesuatu yang terjadi atasnya pada malam hari, maka haruslah ia pergi ke luar perkemahan, janganlah ia masuk ke dalam perkemahan."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:11, Page:1,
    Kor:"해가 질 무렵에 목욕을 하고, 해가 진 다음에 진으로 들어올 수 있습니다.",
    Chn:"到傍晚的时候，他要用水洗澡，及至日落了才可以入营。",
    Eng:"But as evening approaches he is to wash himself, and at sunset he may return to the camp.",
    Ind:"Kemudian menjelang senja haruslah ia mandi dengan air, dan pada waktu matahari terbenam, ia boleh masuk kembali ke dalam perkemahan."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:12, Page:1,
    Kor:"○당신들은 진 바깥의 한 곳에 변소를 만들어 놓고, 그 곳에 갈 때에는,",
    Chn:"「你在营外也该定出一个地方作为便所。",
    Eng:"Designate a place outside the camp where you can go to relieve yourself.",
    Ind:"Di luar perkemahan itu haruslah ada bagimu suatu tempat ke mana engkau pergi untuk kada hajat."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:13, Page:1,
    Kor:"당신들의 연장 가운데서 삽을 가지고 가야 합니다. 용변을 볼 때에는 그것으로 땅을 파고, 돌아설 때에는 배설물을 덮으십시오.",
    Chn:"在你器械之中当预备一把锹，你出营外便溺以后，用以铲土，转身掩盖。",
    Eng:"As part of your equipment have something to dig with, and when you relieve yourself, dig a hole and cover up your excrement.",
    Ind:"Di antara perlengkapanmu haruslah ada padamu sekop kecil dan apabila engkau jongkok kada hajat, haruslah engkau menggali lobang dengan itu dan menimbuni kotoranmu."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:14, Page:1,
    Kor:"주 당신들의 하나님은 당신들을 구원하시고 당신들의 대적들을 당신들에게 넘겨 주시려고, 당신들의 진 안을 두루 다니시기 때문에, 당신들의 진은 깨끗하게 유지되어야 합니다. 주님께서 당신들 가운데로 다니시다가 더러운 것을 보시면 당신들에게서 떠나시고 말 것이니, 그런 일이 일어나지 않도록 당신들의 진을 성결하게 하십시오.\"",
    Chn:"因为耶和华—你的　神常在你营中行走，要救护你，将仇敌交给你，所以你的营理当圣洁，免得他见你那里有污秽，就离开你。」",
    Eng:"For the LORD your God moves about in your camp to protect you and to deliver your enemies to you. Your camp must be holy, so that he will not see among you anything indecent and turn away from you.",
    Ind:"Sebab TUHAN, Allahmu, berjalan dari tengah-tengah perkemahanmu untuk melepaskan engkau dan menyerahkan musuhmu kepadamu; sebab itu haruslah perkemahanmu itu kudus, supaya jangan Ia melihat sesuatu yang tidak senonoh di antaramu, lalu berbalik dari padamu.\""
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:15, Page:1,
    Kor:"<기타 규정> ○\"어떤 종이 그의 주인을 피하여 당신들에게로 도망하여 오거든, 당신들은 그를 주인에게 돌려보내서는 안 됩니다.",
    Chn:"「若有奴仆脱了主人的手，逃到你那里，你不可将他交付他的主人。",
    Eng:"If a slave has taken refuge with you, do not hand him over to his master.",
    Ind:"\"Janganlah kauserahkan kepada tuannya seorang budak yang melarikan diri dari tuannya kepadamu."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:16, Page:1,
    Kor:"성 안에서 그가 좋아하는 곳을 택하게 하여, 당신들과 함께 당신들 가운데서 살게 하여 주고, 그를 압제하지 않도록 하십시오.",
    Chn:"他必在你那里与你同住，在你的城邑中，要由他选择一个所喜悦的地方居住；你不可欺负他。",
    Eng:"Let him live among you wherever he likes and in whatever town he chooses. Do not oppress him.",
    Ind:"Bersama-sama engkau ia boleh tinggal, di tengah-tengahmu, di tempat yang dipilihnya di salah satu tempatmu, yang dirasanya baik; janganlah engkau menindas dia.\""
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:17, Page:1,
    Kor:"○이스라엘의 딸은 창녀가 될 수 없습니다. 또 이스라엘의 아들들도 a남창이 될 수 없습니다.(a 가나안의 풍요 종교에는 신전 창녀와 신전 남창이 있어서 풍요의 신을 숭배하였음)",
    Chn:"「以色列的女子中不可有妓女；以色列的男子中不可有娈童。",
    Eng:"No Israelite man or woman is to become a shrine prostitute.",
    Ind:"\"Di antara anak-anak perempuan Israel janganlah ada pelacur bakti, dan di antara anak-anak lelaki Israel janganlah ada semburit bakti."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:18, Page:1,
    Kor:"창녀가 번 돈이나 b남창이 번 돈은, 주 당신들의 하나님의 성전에 서원을 갚는 헌금으로 드릴 수 없습니다. 이 두 가지가 다 주 당신들의 하나님이 미워하시는 것입니다.(b 히, '개의 소득')",
    Chn:"娼妓所得的钱，或娈童所得的价，你不可带入耶和华—你　神的殿还愿，因为这两样都是耶和华—你　神所憎恶的。",
    Eng:"You must not bring the earnings of a female prostitute or of a male prostitute into the house of the LORD your God to pay any vow, because the LORD your God detests them both.",
    Ind:"Janganlah kaubawa upah sundal atau uang semburit ke dalam rumah TUHAN, Allahmu, untuk menepati salah satu nazar, sebab keduanya itu adalah kekejian bagi TUHAN, Allahmu.\""
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:19, Page:1,
    Kor:"○당신들은 동족에게 꾸어 주었거든 이자는 받지 마십시오. 돈이든지 곡식이든지, 이자가 나올 수 있는 어떤 것이라도 이자를 받아서는 안 됩니다.",
    Chn:"「你借给你弟兄的，或是钱财或是粮食，无论什么可生利的物，都不可取利。",
    Eng:"Do not charge your brother interest, whether on money or food or anything else that may earn interest.",
    Ind:"\"Janganlah engkau membungakan kepada saudaramu, baik uang maupun bahan makanan atau apapun yang dapat dibungakan."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:20, Page:1,
    Kor:"외국 사람에게는 꾸어 주고서 이자를 받아도 좋습니다. 그러나 동족에게서는 이자를 받지 못합니다. 그래야만 당신들이 들어가 차지할 땅에서 당신들이 하는 모든 일에, 주 당신들의 하나님이 복을 주실 것입니다.",
    Chn:"借给外邦人可以取利，只是借给你弟兄不可取利。这样，耶和华—你　神必在你所去得为业的地上和你手里所办的一切事上赐福与你。",
    Eng:"You may charge a foreigner interest, but not a brother Israelite, so that the LORD your God may bless you in everything you put your hand to in the land you are entering to possess.",
    Ind:"Dari orang asing boleh engkau memungut bunga, tetapi dari saudaramu janganlah engkau memungut bunga--supaya TUHAN, Allahmu, memberkati engkau dalam segala usahamu di negeri yang engkau masuki untuk mendudukinya.\""
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:21, Page:1,
    Kor:"○주 당신들의 하나님께 맹세하여서 서원한 것은 미루지 말고 지켜야 합니다. 주 당신들의 하나님은 반드시 그것을 당신들에게 요구하실 것입니다. 그러니 미루는 것은 당신들에게 죄가 됩니다.",
    Chn:"「你向耶和华—你的　神许愿，偿还不可迟延；因为耶和华—你的　神必定向你追讨，你不偿还就有罪。",
    Eng:"If you make a vow to the LORD your God, do not be slow to pay it, for the LORD your God will certainly demand it of you and you will be guilty of sin.",
    Ind:"\"Apabila engkau bernazar kepada TUHAN, Allahmu, janganlah engkau menunda-nunda memenuhinya, sebab tentulah TUHAN, Allahmu, akan menuntutnya dari padamu, sehingga hal itu menjadi dosa bagimu."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:22, Page:1,
    Kor:"맹세하지 않은 것은 당신들에게 죄가 되지 않습니다.",
    Chn:"你若不许愿，倒无罪。",
    Eng:"But if you refrain from making a vow, you will not be guilty.",
    Ind:"Tetapi apabila engkau tidak bernazar, maka hal itu bukan menjadi dosa bagimu."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:23, Page:1,
    Kor:"그러나 한 번 당신들의 입으로 맹세한 것은 반드시 지켜야 합니다. 당신들이 주 당신들의 하나님께 입으로 스스로 약속한 것은 서원한 대로 하여야 합니다.",
    Chn:"你嘴里所出的，就是你口中应许甘心所献的，要照你向耶和华—你　神所许的愿谨守遵行。",
    Eng:"Whatever your lips utter you must be sure to do, because you made your vow freely to the LORD your God with your own mouth.",
    Ind:"Apa yang keluar dari bibirmu haruslah kaulakukan dengan setia, sebab dengan sukarela kaunazarkan kepada TUHAN, Allahmu, sesuatu yang kaukatakan dengan mulutmu sendiri.\""
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:24, Page:1,
    Kor:"○당신들이 이웃 사람의 포도원에 들어가서 먹을 만큼 실컷 따먹는 것은 괜찮지만, 그릇에 담아가면 안 됩니다.",
    Chn:"「你进了邻舍的葡萄园，可以随意吃饱了葡萄，只是不可装在器皿中。",
    Eng:"If you enter your neighbor's vineyard, you may eat all the grapes you want, but do not put any in your basket.",
    Ind:"\"Apabila engkau melalui kebun anggur sesamamu, engkau boleh makan buah anggur sepuas-puas hatimu, tetapi tidak boleh kaumasukkan ke dalam bungkusanmu."
  },
  {Bible:"Deuteronomy", Chapter:23, Verse:25, Page:1,
    Kor:"○당신들이 이웃 사람의 곡식밭에 들어가 이삭을 손으로 잘라서 먹는 것은 괜찮지만, 이웃의 c곡식에 낫을 대면 안 됩니다.\"(c 히, '곡식 밭에')",
    Chn:"你进了邻舍站着的禾稼，可以用手摘穗子，只是不可用镰刀割取禾稼。」",
    Eng:"If you enter your neighbor's grainfield, you may pick kernels with your hands, but you must not put a sickle to his standing grain.",
    Ind:"Apabila engkau melalui ladang gandum sesamamu yang belum dituai, engkau boleh memetik bulir-bulirnya dengan tanganmu, tetapi sabit tidak boleh kauayunkan kepada gandum sesamamu itu.\""
  },
]);
