// 갈라디아서 6장 · Galatians 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Galatians",6,18);
BibleDB.add([
  {Bible:"Galatians", Chapter:6, Verse:1, Page:1, Kor:"<서로 짐을 져 줍시다> a형제자매 여러분, 어떤 사람이 어떤 죄에 빠진 일이 드러나면, b성령의 인도하심을 따라 사는 사람인 여러분은 온유한 마음으로 그런 사람을 바로잡아 주고, 자기 스스로를 살펴서, 유혹에 빠지지 않도록 조심하십시오.(a 그, '형제들' b 또는 '신령한 사람인 여러분은')", Chn:"", Eng:"Brothers, if someone is caught in a sin, you who are spiritual should restore him gently. But watch yourself, or you also may be tempted.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:2, Page:1, Kor:"여러분은 서로 남의 짐을 져 주십시오. 그렇게 하면 여러분이 그리스도의 법을 c성취하실 것입니다.(c 다른 고대 사본에는 '성취하십시오')", Chn:"", Eng:"Carry each other's burdens, and in this way you will fulfill the law of Christ.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:3, Page:1, Kor:"어떤 사람이 아무것도 아니면서 무엇이 된 것처럼 생각하면, 그는 자기를 속이는 것입니다.", Chn:"", Eng:"If anyone thinks he is something when he is nothing, he deceives himself.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:4, Page:1, Kor:"각 사람은 자기 일을 살펴보십시오. 그러면 자기에게는 자랑거리가 있더라도, 남에게까지 자랑할 것은 없을 것입니다.", Chn:"", Eng:"Each one should test his own actions. Then he can take pride in himself, without comparing himself to somebody else,", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:5, Page:1, Kor:"사람은 각각 자기 몫의 짐을 져야 합니다.", Chn:"", Eng:"for each one should carry his own load.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:6, Page:1, Kor:"말씀을 배우는 사람은 가르치는 사람과 모든 좋은 것을 함께 나누어야 합니다.", Chn:"", Eng:"Anyone who receives instruction in the word must share all good things with his instructor.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:7, Page:1, Kor:"자기를 속이지 마십시오. 하나님은 조롱을 받으실 분이 아니십니다. 사람은 무엇을 심든지, 심은 대로 거둘 것입니다.", Chn:"", Eng:"Do not be deceived: God cannot be mocked. A man reaps what he sows.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:8, Page:1, Kor:"자기 육체에다 심는 사람은 육체에서 썩을 것을 거두고, 성령에다 심는 사람은 성령에게서 영생을 거둘 것입니다.", Chn:"", Eng:"The one who sows to please his sinful nature, from that nature will reap destruction; the one who sows to please the Spirit, from the Spirit will reap eternal life.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:9, Page:1, Kor:"선한 일을 하다가, 낙심하지 맙시다. 지쳐서 넘어지지 아니하면, 때가 이를 때에 거두게 될 것입니다.", Chn:"", Eng:"Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:10, Page:1, Kor:"그러므로 기회가 있는 동안에, 모든 사람에게 선한 일을 합시다. 특히 믿음의 식구들에게는 더욱 그렇게 합시다.", Chn:"", Eng:"Therefore, as we have opportunity, let us do good to all people, especially to those who belong to the family of believers.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:11, Page:1, Kor:"<마지막으로 하는 경고와 축복> ○보십시오, 내가 여러분에게 직접 이렇게 큰 글자로 적습니다.", Chn:"", Eng:"See what large letters I use as I write to you with my own hand!", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:12, Page:1, Kor:"육체의 겉모양을 꾸미기를 좋아하는 사람은, 여러분에게 할례를 받으라고 강요합니다. 그것은 그들이 그리스도의 십자가 때문에 받는 박해를 면하고자 하는 것입니다.", Chn:"", Eng:"Those who want to make a good impression outwardly are trying to compel you to be circumcised. The only reason they do this is to avoid being persecuted for the cross of Christ.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:13, Page:1, Kor:"할례를 받는 사람들 스스로도 율법을 지키지 않으면서 여러분에게 할례를 받게 하려는 것은, 여러분의 육체를 이용하여 자랑하려는 것입니다.", Chn:"", Eng:"Not even those who are circumcised obey the law, yet they want you to be circumcised that they may boast about your flesh.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:14, Page:1, Kor:"그런데 내게는 우리 주 예수 그리스도의 십자가 밖에는, 자랑할 것이 아무것도 없습니다. 그리스도로 말미암아, 내 쪽에서 보면 세상이 죽었고, 세상 쪽에서 보면 내가 죽었습니다.", Chn:"", Eng:"May I never boast except in the cross of our Lord Jesus Christ, through which the world has been crucified to me, and I to the world.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:15, Page:1, Kor:"d할례를 받거나 안 받는 것이 중요한 것이 아니라, 새롭게 창조되는 것이 중요합니다.(d 다른 고대 사본들에는 절 머리에 '그리스도 예수 안에서는'이 첨가되어 있음)", Chn:"", Eng:"Neither circumcision nor uncircumcision means anything; what counts is a new creation.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:16, Page:1, Kor:"이 표준을 따라 사는 사람들에게와 하나님의 백성 이스라엘에게 평화와 자비가 있기를 빕니다.", Chn:"", Eng:"Peace and mercy to all who follow this rule, even to the Israel of God.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:17, Page:1, Kor:"○이제부터는 아무도 나를 괴롭히지 마십시오. 나는 내 몸에 e예수의 상처 자국을 지고 다닙니다.(e 예수를 위하여 받은 박해로 생긴 상처 자국을 뜻함)", Chn:"", Eng:"Finally, let no one cause me trouble, for I bear on my body the marks of Jesus.", Ind:""},
  {Bible:"Galatians", Chapter:6, Verse:18, Page:1, Kor:"○a형제자매 여러분, 우리 주 예수 그리스도의 은혜가 여러분의 심령에 있기를 빕니다. 아멘.(a 그, '형제들')", Chn:"", Eng:"", Ind:""},
]);
