// 잠언 3장 · Proverbs 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Proverbs",3,35);
BibleDB.add([
  {Bible:"Proverbs", Chapter:3, Verse:1, Page:1, Kor:"", Chn:"", Eng:"My son, do not forget my teaching, but keep my commands in your heart,", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:2, Page:1, Kor:"", Chn:"", Eng:"for they will prolong your life many years and bring you prosperity.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:3, Page:1, Kor:"", Chn:"", Eng:"Let love and faithfulness never leave you; bind them around your neck, write them on the tablet of your heart.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Then you will win favor and a good name in the sight of God and man.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Trust in the LORD with all your heart and lean not on your own understanding;", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:6, Page:1, Kor:"", Chn:"", Eng:"in all your ways acknowledge him, and he will make your paths straight.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Do not be wise in your own eyes; fear the LORD and shun evil.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:8, Page:1, Kor:"", Chn:"", Eng:"This will bring health to your body and nourishment to your bones.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Honor the LORD with your wealth, with the firstfruits of all your crops;", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:10, Page:1, Kor:"", Chn:"", Eng:"then your barns will be filled to overflowing, and your vats will brim over with new wine.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:11, Page:1, Kor:"", Chn:"", Eng:"My son, do not despise the LORD'S discipline and do not resent his rebuke,", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:12, Page:1, Kor:"", Chn:"", Eng:"because the LORD disciplines those he loves, as a father the son he delights in.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Blessed is the man who finds wisdom, the man who gains understanding,", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:14, Page:1, Kor:"", Chn:"", Eng:"for she is more profitable than silver and yields better returns than gold.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:15, Page:1, Kor:"", Chn:"", Eng:"She is more precious than rubies; nothing you desire can compare with her.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:16, Page:1, Kor:"", Chn:"", Eng:"Long life is in her right hand; in her left hand are riches and honor.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Her ways are pleasant ways, and all her paths are peace.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:18, Page:1, Kor:"", Chn:"", Eng:"She is a tree of life to those who embrace her; those who lay hold of her will be blessed.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:19, Page:1, Kor:"", Chn:"", Eng:"By wisdom the LORD laid the earth's foundations, by understanding he set the heavens in place;", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:20, Page:1, Kor:"", Chn:"", Eng:"by his knowledge the deeps were divided, and the clouds let drop the dew.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:21, Page:1, Kor:"", Chn:"", Eng:"My son, preserve sound judgment and discernment, do not let them out of your sight;", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:22, Page:1, Kor:"", Chn:"", Eng:"they will be life for you, an ornament to grace your neck.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:23, Page:1, Kor:"", Chn:"", Eng:"Then you will go on your way in safety, and your foot will not stumble;", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:24, Page:1, Kor:"", Chn:"", Eng:"when you lie down, you will not be afraid; when you lie down, your sleep will be sweet.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Have no fear of sudden disaster or of the ruin that overtakes the wicked,", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:26, Page:1, Kor:"", Chn:"", Eng:"for the LORD will be your confidence and will keep your foot from being snared.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Do not withhold good from those who deserve it, when it is in your power to act.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Do not say to your neighbor, \"Come back later; I'll give it tomorrow\"--when you now have it with you.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Do not plot harm against your neighbor, who lives trustfully near you.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:30, Page:1, Kor:"", Chn:"", Eng:"Do not accuse a man for no reason--when he has done you no harm.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:31, Page:1, Kor:"", Chn:"", Eng:"Do not envy a violent man or choose any of his ways,", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:32, Page:1, Kor:"", Chn:"", Eng:"for the LORD detests a perverse man but takes the upright into his confidence.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:33, Page:1, Kor:"", Chn:"", Eng:"The LORD'S curse is on the house of the wicked, but he blesses the home of the righteous.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:34, Page:1, Kor:"", Chn:"", Eng:"He mocks proud mockers but gives grace to the humble.", Ind:""},
  {Bible:"Proverbs", Chapter:3, Verse:35, Page:1, Kor:"", Chn:"", Eng:"The wise inherit honor, but fools he holds up to shame.", Ind:""},
]);
