// 잠언 28장 · Proverbs 28
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Proverbs",28,28);
BibleDB.add([
  {Bible:"Proverbs", Chapter:28, Verse:1, Page:1,
    Kor:"<율법이 주는 유익> 악인은 뒤쫓는 사람이 없어도 달아나지만, 의인은 사자처럼 담대하다.",
    Chn:"恶人虽无人追赶也逃跑； 义人却胆壮像狮子。",
    Eng:"The wicked man flees though no one pursues, but the righteous are as bold as a lion.",
    Ind:"Orang fasik lari, walaupun tidak ada yang mengejarnya, tetapi orang benar merasa aman seperti singa muda."
  },
  {Bible:"Proverbs", Chapter:28, Verse:2, Page:1,
    Kor:"나라에 반역이 일면, 통치자가 자주 바뀌지만, 슬기와 지식이 있는 사람이 다스리면, 그 나라가 오래간다.",
    Chn:"邦国因有罪过，君王就多更换； 因有聪明知识的人，国必长存。",
    Eng:"When a country is rebellious, it has many rulers, but a man of understanding and knowledge maintains order.",
    Ind:"Karena pemberontakan negeri banyaklah penguasa-penguasanya, tetapi karena orang yang berpengertian dan berpengetahuan tetaplah hukum."
  },
  {Bible:"Proverbs", Chapter:28, Verse:3, Page:1,
    Kor:"가난한 사람을 억압하는 가난한 사람은 먹거리를 남김없이 쓸어 버리는 폭우와 같다.",
    Chn:"穷人欺压贫民， 好像暴雨冲没粮食。",
    Eng:"A ruler who oppresses the poor is like a driving rain that leaves no crops.",
    Ind:"Orang miskin yang menindas orang-orang yang lemah adalah seperti hujan deras, tetapi tidak memberi makanan."
  },
  {Bible:"Proverbs", Chapter:28, Verse:4, Page:1,
    Kor:"율법을 버린 사람은 악인을 찬양하지만, 율법을 지키는 사람은 악인에게 대항한다.",
    Chn:"违弃律法的，夸奖恶人； 遵守律法的，却与恶人相争。",
    Eng:"Those who forsake the law praise the wicked, but those who keep the law resist them.",
    Ind:"Orang yang mengabaikan hukum memuji orang fasik, tetapi orang yang berpegang pada hukum menentangnya."
  },
  {Bible:"Proverbs", Chapter:28, Verse:5, Page:1,
    Kor:"악한 사람은 공의를 깨닫지 못하나, 주님을 찾는 사람은 모든 것을 깨닫는다.",
    Chn:"坏人不明白公义； 惟有寻求耶和华的，无不明白。",
    Eng:"Evil men do not understand justice, but those who seek the LORD understand it fully.",
    Ind:"Orang yang jahat tidak mengerti keadilan, tetapi orang yang mencari TUHAN mengerti segala sesuatu."
  },
  {Bible:"Proverbs", Chapter:28, Verse:6, Page:1,
    Kor:"부유하나 구부러진 길을 가는 사람보다는 가난해도 흠 없이 사는 사람이 낫다.",
    Chn:"行为纯正的穷乏人 胜过行事乖僻的富足人。",
    Eng:"Better a poor man whose walk is blameless than a rich man whose ways are perverse.",
    Ind:"Lebih baik orang miskin yang bersih kelakuannya dari pada orang yang berliku-liku jalannya, sekalipun ia kaya."
  },
  {Bible:"Proverbs", Chapter:28, Verse:7, Page:1,
    Kor:"슬기로운 아들은 율법을 지키지만, 먹기를 탐하는 사람들과 어울리는 아들은 아버지에게 욕을 돌린다.",
    Chn:"谨守律法的，是智慧之子； 与贪食人作伴的，却羞辱其父。",
    Eng:"He who keeps the law is a discerning son, but a companion of gluttons disgraces his father.",
    Ind:"Orang yang memelihara hukum adalah anak yang berpengertian, tetapi orang yang bergaul dengan pelahap mempermalukan ayahnya."
  },
  {Bible:"Proverbs", Chapter:28, Verse:8, Page:1,
    Kor:"높은 이자로 재산을 늘리는 것은, 마침내, 가난한 사람들에게 은혜로 베풀어질 재산을 쌓아 두는 것이다.",
    Chn:"人以厚利加增财物， 是给那怜悯穷人者积蓄的。",
    Eng:"He who increases his wealth by exorbitant interest amasses it for another, who will be kind to the poor.",
    Ind:"Orang yang memperbanyak hartanya dengan riba dan bunga uang, mengumpulkan itu untuk orang-orang yang mempunyai belas kasihan kepada orang-orang lemah."
  },
  {Bible:"Proverbs", Chapter:28, Verse:9, Page:1,
    Kor:"귀를 돌리고 율법을 듣지 않으면, 그의 기도마저도 역겹게 된다.",
    Chn:"转耳不听律法的， 他的祈祷也为可憎。",
    Eng:"If anyone turns a deaf ear to the law, even his prayers are detestable.",
    Ind:"Siapa memalingkan telinganya untuk tidak mendengarkan hukum, juga doanya adalah kekejian."
  },
  {Bible:"Proverbs", Chapter:28, Verse:10, Page:1,
    Kor:"정직한 사람을 나쁜 길로 유인하는 사람은 자기가 판 함정에 빠지지만, 흠 없이 사는 사람은 복을 받는다.",
    Chn:"诱惑正直人行恶道的，必掉在自己的坑里； 惟有完全人必承受福分。",
    Eng:"He who leads the upright along an evil path will fall into his own trap, but the blameless will receive a good inheritance.",
    Ind:"Siapa menyesatkan orang jujur ke jalan yang jahat akan jatuh ke dalam lobangnya sendiri, tetapi orang-orang yang tak bercela akan mewarisi kebahagiaan."
  },
  {Bible:"Proverbs", Chapter:28, Verse:11, Page:1,
    Kor:"부자가 자기 보기에는 지혜롭지만, 가난하나 슬기로운 사람은 그 사람의 속을 꿰뚫어 본다.",
    Chn:"富足人自以为有智慧， 但聪明的贫穷人能将他查透。",
    Eng:"A rich man may be wise in his own eyes, but a poor man who has discernment sees through him.",
    Ind:"Orang kaya menganggap dirinya bijak, tetapi orang miskin yang berpengertian mengenal dia."
  },
  {Bible:"Proverbs", Chapter:28, Verse:12, Page:1,
    Kor:"정직한 사람이 이기면 많은 사람이 축하하지만, 악인이 일어나면 사람들이 숨는다.",
    Chn:"义人得志，有大荣耀； 恶人兴起，人就躲藏。",
    Eng:"When the righteous triumph, there is great elation; but when the wicked rise to power, men go into hiding.",
    Ind:"Jika orang benar menang, banyaklah pujian orang, tetapi jika orang fasik mendapat kekuasaan, orang menyembunyikan diri."
  },
  {Bible:"Proverbs", Chapter:28, Verse:13, Page:1,
    Kor:"자기의 죄를 숨기는 사람은 잘 되지 못하지만, 죄를 자백하고 그것을 끊어 버리는 사람은 불쌍히 여김을 받는다.",
    Chn:"遮掩自己罪过的，必不亨通； 承认离弃罪过的，必蒙怜恤。",
    Eng:"He who conceals his sins does not prosper, but whoever confesses and renounces them finds mercy.",
    Ind:"Siapa menyembunyikan pelanggarannya tidak akan beruntung, tetapi siapa mengakuinya dan meninggalkannya akan disayangi."
  },
  {Bible:"Proverbs", Chapter:28, Verse:14, Page:1,
    Kor:"늘 두려워하는 마음으로 사는 사람은 복을 받지만, 마음이 완고한 사람은 재앙에 빠진다.",
    Chn:"常存敬畏的，便为有福； 心存刚硬的，必陷在祸患里。",
    Eng:"Blessed is the man who always fears the LORD, but he who hardens his heart falls into trouble.",
    Ind:"Berbahagialah orang yang senantiasa takut akan TUHAN, tetapi orang yang mengeraskan hatinya akan jatuh ke dalam malapetaka."
  },
  {Bible:"Proverbs", Chapter:28, Verse:15, Page:1,
    Kor:"가난한 백성을 억누르는 악한 통치자는, 울부짖는 사자요, 굶주린 곰이다.",
    Chn:"暴虐的君王辖制贫民， 好像吼叫的狮子、觅食的熊。",
    Eng:"Like a roaring lion or a charging bear is a wicked man ruling over a helpless people.",
    Ind:"Seperti singa yang meraung atau beruang yang menyerbu, demikianlah orang fasik yang memerintah rakyat yang lemah."
  },
  {Bible:"Proverbs", Chapter:28, Verse:16, Page:1,
    Kor:"슬기가 모자라는 통치자는 억압만을 일삼지만, 부정한 이득을 미워하는 통치자는 오래도록 살 것이다.",
    Chn:"无知的君多行暴虐； 以贪财为可恨的，必年长日久。",
    Eng:"A tyrannical ruler lacks judgment, but he who hates ill-gotten gain will enjoy a long life.",
    Ind:"Seorang pemimpin yang tidak mempunyai pengertian keras penindasannya, tetapi orang yang membenci laba yang tidak halal, memperpanjang umurnya."
  },
  {Bible:"Proverbs", Chapter:28, Verse:17, Page:1,
    Kor:"사람을 죽인 사람은 함정으로 달려가는 것이니, 아무도 그를 막지 말아야 한다.",
    Chn:"背负流人血之罪的，必往坑里奔跑， 谁也不可拦阻他。",
    Eng:"A man tormented by the guilt of murder will be a fugitive till death; let no one support him.",
    Ind:"Orang yang menanggung darah orang lain akan lari sampai ke liang kubur. Janganlah engkau menahannya!"
  },
  {Bible:"Proverbs", Chapter:28, Verse:18, Page:1,
    Kor:"흠 없이 사는 사람은 구원을 받을 것이지만, 그릇된 길을 따라가는 사람은 언젠가는 한 번 넘어지고야 만다.",
    Chn:"行动正直的，必蒙拯救； 行事弯曲的，立时跌倒。",
    Eng:"He whose walk is blameless is kept safe, but he whose ways are perverse will suddenly fall.",
    Ind:"Siapa berlaku tidak bercela akan diselamatkan, tetapi siapa berliku-liku jalannya akan jatuh ke dalam lobang."
  },
  {Bible:"Proverbs", Chapter:28, Verse:19, Page:1,
    Kor:"밭을 가는 사람은 먹을 것이 넉넉하지만, 헛된 것을 꿈꾸는 사람은 찌들게 가난하다.",
    Chn:"耕种自己田地的，必得饱食； 追随虚浮的，足受穷乏。",
    Eng:"He who works his land will have abundant food, but the one who chases fantasies will have his fill of poverty.",
    Ind:"Siapa mengerjakan tanahnya akan kenyang dengan makanan, tetapi siapa mengejar barang yang sia-sia akan kenyang dengan kemiskinan."
  },
  {Bible:"Proverbs", Chapter:28, Verse:20, Page:1,
    Kor:"신실한 사람은 많은 복을 받지만, 속히 부자가 되려는 사람은 벌을 면하지 못한다.",
    Chn:"诚实人必多得福； 想要急速发财的，不免受罚。",
    Eng:"A faithful man will be richly blessed, but one eager to get rich will not go unpunished.",
    Ind:"Orang yang dapat dipercaya mendapat banyak berkat, tetapi orang yang ingin cepat menjadi kaya, tidak akan luput dari hukuman."
  },
  {Bible:"Proverbs", Chapter:28, Verse:21, Page:1,
    Kor:"사람의 얼굴을 보고 재판하는 것은 옳지 않다. 사람은 빵 한 조각 때문에 그런 죄를 지을 수도 있다.",
    Chn:"看人的情面乃为不好； 人因一块饼枉法也为不好。",
    Eng:"To show partiality is not good--yet a man will do wrong for a piece of bread.",
    Ind:"Memandang bulu tidaklah baik, tetapi untuk sekerat roti orang membuat pelanggaran."
  },
  {Bible:"Proverbs", Chapter:28, Verse:22, Page:1,
    Kor:"죄악에 눈이 어두운 사람은 부자가 되는 데에만 바빠서, 언제 궁핍이 자기에게 들이닥칠지를 알지 못한다.",
    Chn:"人有恶眼想要急速发财， 却不知穷乏必临到他身。",
    Eng:"A stingy man is eager to get rich and is unaware that poverty awaits him.",
    Ind:"Orang yang kikir tergesa-gesa mengejar harta, dan tidak mengetahui bahwa ia akan mengalami kekurangan."
  },
  {Bible:"Proverbs", Chapter:28, Verse:23, Page:1,
    Kor:"아첨하는 사람보다는 바르게 꾸짖는 사람이, 나중에 고맙다는 말을 듣는다.",
    Chn:"责备人的，后来蒙人喜悦， 多于那用舌头谄媚人的。",
    Eng:"He who rebukes a man will in the end gain more favor than he who has a flattering tongue.",
    Ind:"Siapa menegur orang akan kemudian lebih disayangi dari pada orang yang menjilat."
  },
  {Bible:"Proverbs", Chapter:28, Verse:24, Page:1,
    Kor:"자기 부모의 것을 빼앗고도 그것이 죄가 아니라고 하는 사람은 살인자와 한패이다.",
    Chn:"偷窃父母的，说：这不是罪， 此人就是与强盗同类。",
    Eng:"He who robs his father or mother and says, \"It's not wrong\"--he is partner to him who destroys.",
    Ind:"Siapa merampasi ayah dan ibunya dan menyangka bahwa itu bukan suatu pelanggaran, ia sendiri adalah kawan si perusak."
  },
  {Bible:"Proverbs", Chapter:28, Verse:25, Page:1,
    Kor:"욕심이 많은 사람은 다툼을 일으키지만, 주님을 의뢰하는 사람은 풍성함을 누린다.",
    Chn:"心中贪婪的，挑起争端； 倚靠耶和华的，必得丰裕。",
    Eng:"A greedy man stirs up dissension, but he who trusts in the LORD will prosper.",
    Ind:"Orang yang loba, menimbulkan pertengkaran, tetapi siapa percaya kepada TUHAN, diberi kelimpahan."
  },
  {Bible:"Proverbs", Chapter:28, Verse:26, Page:1,
    Kor:"자기의 생각만을 신뢰하는 사람은 미련한 사람이지만, 지혜롭게 사는 사람은 구원을 받는다.",
    Chn:"心中自是的，便是愚昧人； 凭智慧行事的，必蒙拯救。",
    Eng:"He who trusts in himself is a fool, but he who walks in wisdom is kept safe.",
    Ind:"Siapa percaya kepada hatinya sendiri adalah orang bebal, tetapi siapa berlaku dengan bijak akan selamat."
  },
  {Bible:"Proverbs", Chapter:28, Verse:27, Page:1,
    Kor:"가난한 사람을 도와주는 사람은 모자라는 것이 없지만, 그를 못 본 체하는 사람은 많은 저주를 받는다.",
    Chn:"周济贫穷的，不致缺乏； 佯为不见的，必多受咒诅。",
    Eng:"He who gives to the poor will lack nothing, but he who closes his eyes to them receives many curses.",
    Ind:"Siapa memberi kepada orang miskin tak akan berkekurangan, tetapi orang yang menutup matanya akan sangat dikutuki."
  },
  {Bible:"Proverbs", Chapter:28, Verse:28, Page:1,
    Kor:"악인이 일어나면 사람들은 숨어 버리지만, 그가 망하면 의인이 많이 나타난다.",
    Chn:"恶人兴起，人就躲藏； 恶人败亡，义人增多。",
    Eng:"When the wicked rise to power, people go into hiding; but when the wicked perish, the righteous thrive.",
    Ind:"Jika orang fasik mendapat kekuasaan, orang menyembunyikan diri, tetapi jika mereka binasa, bertambahlah jumlah orang benar."
  },
]);
