// 잠언 25장 · Proverbs 25
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Proverbs",25,28);
BibleDB.add([
  {Bible:"Proverbs", Chapter:25, Verse:1, Page:1,
    Kor:"<솔로몬의 잠언 추가> 이것도 솔로몬의 잠언으로, 유다 왕 히스기야의 신하들이 편집한 것이다.",
    Chn:"以下也是所罗门的箴言，是犹大王希西家的人所誊录的。",
    Eng:"These are more proverbs of Solomon, copied by the men of Hezekiah king of Judah:",
    Ind:"Juga ini adalah amsal-amsal Salomo yang dikumpulkan pegawai-pegawai Hizkia, raja Yehuda."
  },
  {Bible:"Proverbs", Chapter:25, Verse:2, Page:1,
    Kor:"일을 숨기는 것은 하나님의 영광이요, 일을 밝히 드러내는 것은 왕의 영광이다.",
    Chn:"将事隐秘乃　神的荣耀； 将事察清乃君王的荣耀。",
    Eng:"It is the glory of God to conceal a matter; to search out a matter is the glory of kings.",
    Ind:"Kemuliaan Allah ialah merahasiakan sesuatu, tetapi kemuliaan raja-raja ialah menyelidiki sesuatu."
  },
  {Bible:"Proverbs", Chapter:25, Verse:3, Page:1,
    Kor:"하늘이 높고 땅이 깊은 것처럼, 왕의 마음도 헤아리기 어렵다.",
    Chn:"天之高，地之厚， 君王之心也测不透。",
    Eng:"As the heavens are high and the earth is deep, so the hearts of kings are unsearchable.",
    Ind:"Seperti tingginya langit dan dalamnya bumi, demikianlah hati raja-raja tidak terduga."
  },
  {Bible:"Proverbs", Chapter:25, Verse:4, Page:1,
    Kor:"은에서 찌꺼기를 없애라. 그래야 은장색의 손에서 그릇이 되어 나온다.",
    Chn:"除去银子的渣滓就有银子出来， 银匠能以做器皿。",
    Eng:"Remove the dross from the silver, and out comes material for the silversmith;",
    Ind:"Sisihkanlah sanga dari perak, maka keluarlah benda yang indah bagi pandai emas."
  },
  {Bible:"Proverbs", Chapter:25, Verse:5, Page:1,
    Kor:"왕 앞에서는 악한 사람을 없애라. 그래야 왕위가 공의 위에 굳게 선다.",
    Chn:"除去王面前的恶人， 国位就靠公义坚立。",
    Eng:"remove the wicked from the king's presence, and his throne will be established through righteousness.",
    Ind:"Sisihkanlah orang fasik dari hadapan raja, maka kokohlah takhtanya oleh kebenaran."
  },
  {Bible:"Proverbs", Chapter:25, Verse:6, Page:1,
    Kor:"왕 앞에서 스스로 높은 체하지 말며, 높은 사람의 자리에 끼여들지 말아라.",
    Chn:"不要在王面前妄自尊大； 不要在大人的位上站立。",
    Eng:"Do not exalt yourself in the king's presence, and do not claim a place among great men;",
    Ind:"Jangan berlagak di hadapan raja, atau berdiri di tempat para pembesar."
  },
  {Bible:"Proverbs", Chapter:25, Verse:7, Page:1,
    Kor:"너의 눈 앞에 있는 높은 관리들 앞에서 '저리로 내려가라'는 말을 듣는 것보다, '이리로 올라오라'는 말을 듣는 것이 더 낫기 때문이다.",
    Chn:"宁可有人说：请你上来， 强如在你觐见的王子面前叫你退下。",
    Eng:"it is better for him to say to you, \"Come up here,\" than for him to humiliate you before a nobleman. What you have seen with your eyes",
    Ind:"Karena lebih baik orang berkata kepadamu: \"Naiklah ke mari,\" dari pada engkau direndahkan di hadapan orang mulia. Apa matamu lihat,"
  },
  {Bible:"Proverbs", Chapter:25, Verse:8, Page:1,
    Kor:"너는 급하게 소송하지 말아라. 훗날에 너의 이웃이 너를 이겨 부끄럽게 만들 때에, 네가 어떻게 할지가 염려된다.",
    Chn:"不要冒失出去与人争竞， 免得至终被他羞辱， 你就不知道怎样行了。",
    Eng:"do not bring hastily to court, for what will you do in the end if your neighbor puts you to shame?",
    Ind:"jangan terburu-buru kaubuat perkara pengadilan. Karena pada akhirnya apa yang engkau dapat lakukan, kalau sesamamu telah mempermalukan engkau?"
  },
  {Bible:"Proverbs", Chapter:25, Verse:9, Page:1,
    Kor:"이웃과 다툴 일이 있으면 그와 직접 변론만 하고, 그의 비밀을 퍼뜨리지 말아라.",
    Chn:"你与邻舍争讼， 要与他一人辩论， 不可泄漏人的密事，",
    Eng:"If you argue your case with a neighbor, do not betray another man's confidence,",
    Ind:"Belalah perkaramu terhadap sesamamu itu, tetapi jangan buka rahasia orang lain,"
  },
  {Bible:"Proverbs", Chapter:25, Verse:10, Page:1,
    Kor:"그 말을 듣는 사람이 오히려 너를 비난하면, 그 나쁜 소문이 너에게서 떠나지 않고 따라다닐까 두렵다.",
    Chn:"恐怕听见的人骂你， 你的臭名就难以脱离。",
    Eng:"or he who hears it may shame you and you will never lose your bad reputation.",
    Ind:"supaya jangan orang yang mendengar engkau akan mencemoohkan engkau, dan umpat terhadap engkau akan tidak hilang."
  },
  {Bible:"Proverbs", Chapter:25, Verse:11, Page:1,
    Kor:"경우에 알맞은 말은, 은쟁반에 담긴 금사과이다.",
    Chn:"一句话说得合宜， 就如金苹果在银网子里。",
    Eng:"A word aptly spoken is like apples of gold in settings of silver.",
    Ind:"Perkataan yang diucapkan tepat pada waktunya adalah seperti buah apel emas di pinggan perak."
  },
  {Bible:"Proverbs", Chapter:25, Verse:12, Page:1,
    Kor:"지혜로운 사람의 책망은, 들을 줄 아는 사람의 귀에는, 금귀고리요, 순금 목걸이이다.",
    Chn:"智慧人的劝戒，在顺从的人耳中， 好像金耳环和精金的妆饰。",
    Eng:"Like an earring of gold or an ornament of fine gold is a wise man's rebuke to a listening ear.",
    Ind:"Teguran orang yang bijak adalah seperti cincin emas dan hiasan kencana untuk telinga yang mendengar."
  },
  {Bible:"Proverbs", Chapter:25, Verse:13, Page:1,
    Kor:"믿음직한 심부름꾼은 그를 보낸 주인에게는 무더운 추수 때의 시원한 냉수와 같아서, 그 주인의 마음을 시원하게 해준다.",
    Chn:"忠信的使者叫差他的人心里舒畅， 就如在收割时有冰雪的凉气。",
    Eng:"Like the coolness of snow at harvest time is a trustworthy messenger to those who send him; he refreshes the spirit of his masters.",
    Ind:"Seperti sejuk salju di musim panen, demikianlah pesuruh yang setia bagi orang-orang yang menyuruhnya. Ia menyegarkan hati tuan-tuannya."
  },
  {Bible:"Proverbs", Chapter:25, Verse:14, Page:1,
    Kor:"선물을 한다고 거짓말로 자랑을 퍼뜨리는 사람은 비를 내리지 못하는 구름과 바람 같다.",
    Chn:"空夸赠送礼物的， 好像无雨的风云。",
    Eng:"Like clouds and wind without rain is a man who boasts of gifts he does not give.",
    Ind:"Awan dan angin tanpa hujan, demikianlah orang yang menyombongkan diri dengan hadiah yang tidak pernah diberikannya."
  },
  {Bible:"Proverbs", Chapter:25, Verse:15, Page:1,
    Kor:"분노를 오래 참으면 지배자도 설득되고, 부드러운 혀는 뼈도 녹일 수 있다.",
    Chn:"恒常忍耐可以劝动君王； 柔和的舌头能折断骨头。",
    Eng:"Through patience a ruler can be persuaded, and a gentle tongue can break a bone.",
    Ind:"Dengan kesabaran seorang penguasa dapat diyakinkan dan lidah lembut mematahkan tulang."
  },
  {Bible:"Proverbs", Chapter:25, Verse:16, Page:1,
    Kor:"꿀을 발견하더라도 적당히 먹어라. 과식하면 토할지도 모른다.",
    Chn:"你得了蜜吗？只可吃够而已， 恐怕你过饱就呕吐出来。",
    Eng:"If you find honey, eat just enough--too much of it, and you will vomit.",
    Ind:"Kalau engkau mendapat madu, makanlah secukupnya, jangan sampai engkau terlalu kenyang dengan itu, lalu memuntahkannya."
  },
  {Bible:"Proverbs", Chapter:25, Verse:17, Page:1,
    Kor:"이웃집이라 하여 너무 자주 드나들지 말아라. 그가 싫증이 나서 너를 미워하게 될지도 모른다.",
    Chn:"你的脚要少进邻舍的家， 恐怕他厌烦你，恨恶你。",
    Eng:"Seldom set foot in your neighbor's house--too much of you, and he will hate you.",
    Ind:"Janganlah kerap kali datang ke rumah sesamamu, supaya jangan ia bosan, lalu membencimu."
  },
  {Bible:"Proverbs", Chapter:25, Verse:18, Page:1,
    Kor:"거짓말로 이웃에게 불리한 증언을 하는 사람은, 망치요, 칼이요, 뾰족한 화살이다.",
    Chn:"作假见证陷害邻舍的， 就是大槌，是利刀，是快箭。",
    Eng:"Like a club or a sword or a sharp arrow is the man who gives false testimony against his neighbor.",
    Ind:"Orang yang bersaksi dusta terhadap sesamanya adalah seperti gada, atau pedang, atau panah yang tajam."
  },
  {Bible:"Proverbs", Chapter:25, Verse:19, Page:1,
    Kor:"환난을 당할 때에, 진실하지 못한 사람을 믿는 것은, 마치 썩은 이와 뼈가 부러진 다리를 의지하는 것과 같다.",
    Chn:"患难时倚靠不忠诚的人， 好像破坏的牙，错骨缝的脚。",
    Eng:"Like a bad tooth or a lame foot is reliance on the unfaithful in times of trouble.",
    Ind:"Kepercayaan kepada pengkhianat di masa kesesakan adalah seperti gigi yang rapuh dan kaki yang goyah."
  },
  {Bible:"Proverbs", Chapter:25, Verse:20, Page:1,
    Kor:"마음이 상한 사람 앞에서 즐거운 노래를 부르는 것은, 추운 날에 옷을 벗기는 것과 같고, 상처에 초를 붓는 것과 같다.",
    Chn:"对伤心的人唱歌， 就如冷天脱衣服， 又如硷上倒醋。",
    Eng:"Like one who takes away a garment on a cold day, or like vinegar poured on soda, is one who sings songs to a heavy heart.",
    Ind:"Orang yang menyanyikan nyanyian untuk hati yang sedih adalah seperti orang yang menanggalkan baju di musim dingin, dan seperti cuka pada luka."
  },
  {Bible:"Proverbs", Chapter:25, Verse:21, Page:1,
    Kor:"네 원수가 배고파 하거든 먹을 것을 주고, 목말라 하거든 마실 물을 주어라.",
    Chn:"你的仇敌若饿了，就给他饭吃； 若渴了，就给他水喝；",
    Eng:"If your enemy is hungry, give him food to eat; if he is thirsty, give him water to drink.",
    Ind:"Jikalau seterumu lapar, berilah dia makan roti, dan jikalau ia dahaga, berilah dia minum air."
  },
  {Bible:"Proverbs", Chapter:25, Verse:22, Page:1,
    Kor:"이렇게 하는 것은, 그의 낯을 뜨겁게 하는 것이며, 주님께서 너에게 상으로 갚아 주실 것이다.",
    Chn:"因为，你这样行就是把炭火堆在他的头上； 耶和华也必赏赐你。",
    Eng:"In doing this, you will heap burning coals on his head, and the LORD will reward you.",
    Ind:"Karena engkau akan menimbun bara api di atas kepalanya, dan TUHAN akan membalas itu kepadamu."
  },
  {Bible:"Proverbs", Chapter:25, Verse:23, Page:1,
    Kor:"북풍이 비를 일으키듯, 헐뜯는 혀는 얼굴에 분노를 일으킨다.",
    Chn:"北风生雨， 谗谤人的舌头也生怒容。",
    Eng:"As a north wind brings rain, so a sly tongue brings angry looks.",
    Ind:"Angin utara membawa hujan, bicara secara rahasia muka marah."
  },
  {Bible:"Proverbs", Chapter:25, Verse:24, Page:1,
    Kor:"다투기를 좋아하는 여자와 넓은 집에서 함께 사는 것보다, 차라리 다락 한 구석에서 혼자 사는 것이 더 낫다.",
    Chn:"宁可住在房顶的角上， 不在宽阔的房屋与争吵的妇人同住。",
    Eng:"Better to live on a corner of the roof than share a house with a quarrelsome wife.",
    Ind:"Lebih baik tinggal pada sudut sotoh rumah dari pada diam serumah dengan perempuan yang suka bertengkar."
  },
  {Bible:"Proverbs", Chapter:25, Verse:25, Page:1,
    Kor:"먼 데서 오는 기쁜 소식은 목이 타는 사람에게 주어지는 냉수와 같다.",
    Chn:"有好消息从远方来， 就如拿凉水给口渴的人喝。",
    Eng:"Like cold water to a weary soul is good news from a distant land.",
    Ind:"Seperti air sejuk bagi jiwa yang dahaga, demikianlah kabar baik dari negeri yang jauh."
  },
  {Bible:"Proverbs", Chapter:25, Verse:26, Page:1,
    Kor:"의인이 악인 앞에 무릎을 꿇는 것은, 흐려진 샘물과 같고, 오염된 우물물과 같다.",
    Chn:"义人在恶人面前退缩， 好像趟浑之泉，弄浊之井。",
    Eng:"Like a muddied spring or a polluted well is a righteous man who gives way to the wicked.",
    Ind:"Seperti mata air yang keruh dan sumber yang kotor, demikianlah orang benar yang kuatir di hadapan orang fasik."
  },
  {Bible:"Proverbs", Chapter:25, Verse:27, Page:1,
    Kor:"꿀도 너무 많이 먹는 것은 좋지 않듯이, 영예를 지나치게 구하는 것은 좋지 않다.",
    Chn:"吃蜜过多是不好的； 考究自己的荣耀也是可厌的。",
    Eng:"It is not good to eat too much honey, nor is it honorable to seek one's own honor.",
    Ind:"Tidaklah baik makan banyak madu; sebab itu biarlah jarang kata-kata pujianmu."
  },
  {Bible:"Proverbs", Chapter:25, Verse:28, Page:1,
    Kor:"자기의 기분을 자제하지 못하는 사람은, 성이 무너져 성벽이 없는 것과 같다.",
    Chn:"人不制伏自己的心， 好像毁坏的城邑没有墙垣。",
    Eng:"Like a city whose walls are broken down is a man who lacks self-control.",
    Ind:"Orang yang tak dapat mengendalikan diri adalah seperti kota yang roboh temboknya."
  },
]);
