// 잠언 15장 · Proverbs 15
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Proverbs",15,33);
BibleDB.add([
  {Bible:"Proverbs", Chapter:15, Verse:1, Page:1, Kor:"<주님께서 보고 계신다> 부드러운 대답은 분노를 가라앉히지만, 거친 말은 화를 돋운다.", Chn:"", Eng:"A gentle answer turns away wrath, but a harsh word stirs up anger.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:2, Page:1, Kor:"지혜로운 사람의 혀는 좋은 지식을 베풀지만, 미련한 사람의 입은 어리석은 말만 쏟아낸다.", Chn:"", Eng:"The tongue of the wise commends knowledge, but the mouth of the fool gushes folly.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:3, Page:1, Kor:"주님의 눈은 어느 곳에서든지, 악한 사람과 선한 사람을 모두 지켜 보신다.", Chn:"", Eng:"The eyes of the LORD are everywhere, keeping watch on the wicked and the good.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:4, Page:1, Kor:"따뜻한 말은 생명나무와 같지만, 가시돋힌 말은 마음을 상하게 한다.", Chn:"", Eng:"The tongue that brings healing is a tree of life, but a deceitful tongue crushes the spirit.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:5, Page:1, Kor:"어리석은 사람은 자기 아버지의 훈계를 업신여기지만, 명철한 사람은 아버지의 책망을 간직한다.", Chn:"", Eng:"A fool spurns his father's discipline, but whoever heeds correction shows prudence.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:6, Page:1, Kor:"의인의 집에는 많은 재물이 쌓이나, 악인의 소득은 고통을 가져 온다.", Chn:"", Eng:"The house of the righteous contains great treasure, but the income of the wicked brings them trouble.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:7, Page:1, Kor:"지혜로운 사람의 입술은 지식을 전파하지만, a미련한 사람의 마음에는 그러한 생각이 없다. (a '미련한 사람'으로 번역된 히브리어 '크씰림'은 '어리석은 사람'으로 번역된 '에빌림'과 함께 도덕적 결함을 지닌 사람을 뜻함. 1:7의 주를 볼 것)", Chn:"", Eng:"The lips of the wise spread knowledge; not so the hearts of fools.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:8, Page:1, Kor:"악한 사람의 제사는 주님께서 역겨워하시지만, 정직한 사람의 기도는 주님께서 기뻐하신다.", Chn:"", Eng:"The LORD detests the sacrifice of the wicked, but the prayer of the upright pleases him.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:9, Page:1, Kor:"악한 사람의 길은 주님께서 싫어하시지만, 정의를 따르는 사람은 주님께서 사랑하신다.", Chn:"", Eng:"The LORD detests the way of the wicked but he loves those who pursue righteousness.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:10, Page:1, Kor:"옳은길을 저버리는 사람은 엄한 징계를 받고, 책망을 싫어하는 사람은 죽임을 당할 것이다.", Chn:"", Eng:"Stern discipline awaits him who leaves the path; he who hates correction will die.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:11, Page:1, Kor:"b'죽음'과 '파멸'도 주님 앞에서 드러나거늘, 사람의 마음이야 더욱 그러하지 않겠는가! (b 히, '스올과 아바돈')", Chn:"", Eng:"Death and Destruction lie open before the LORD--how much more the hearts of men!", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:12, Page:1, Kor:"거만한 사람은 자기를 책망하는 사람을 좋아하지 않으며, 지혜 있는 사람을 찾아가지도 않는다.", Chn:"", Eng:"A mocker resents correction; he will not consult the wise.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:13, Page:1, Kor:"즐거운 마음은 얼굴을 밝게 하지만, 근심하는 마음은 너를 상하게 한다.", Chn:"", Eng:"A happy heart makes the face cheerful, but heartache crushes the spirit.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:14, Page:1, Kor:"명철한 사람의 마음은 지식을 찾지만, 미련한 사람의 입은 어리석음을 즐긴다.", Chn:"", Eng:"The discerning heart seeks knowledge, but the mouth of a fool feeds on folly.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:15, Page:1, Kor:"고난받는 사람에게는 모든 날이 다 불행한 날이지만, 마음이 즐거운 사람에게는 모든 날이 잔칫날이다.", Chn:"", Eng:"All the days of the oppressed are wretched, but the cheerful heart has a continual feast.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:16, Page:1, Kor:"재산이 적어도 주님을 경외하며 사는 것이, 재산이 많아서 다투며 사는 것보다 낫다.", Chn:"", Eng:"Better a little with the fear of the LORD than great wealth with turmoil.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:17, Page:1, Kor:"서로 사랑하며 채소를 먹고 사는 것이, 서로 미워하며 기름진 쇠고기를 먹고 사는 것보다 낫다.", Chn:"", Eng:"Better a meal of vegetables where there is love than a fattened calf with hatred.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:18, Page:1, Kor:"화를 쉽게 내는 사람은 다툼을 일으키지만, 성을 더디 내는 사람은 싸움을 그치게 한다.", Chn:"", Eng:"A hot-tempered man stirs up dissension, but a patient man calms a quarrel.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:19, Page:1, Kor:"게으른 사람의 길은 가시덤불로 덮여 있는 것 같지만, 부지런한 사람의 길은 확 트인 큰길과 같다.", Chn:"", Eng:"The way of the sluggard is blocked with thorns, but the path of the upright is a highway.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:20, Page:1, Kor:"지혜로운 아들은 아버지를 기쁘게 하지만, 미련한 아들은 어머니를 업신여긴다.", Chn:"", Eng:"A wise son brings joy to his father, but a foolish man despises his mother.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:21, Page:1, Kor:"생각이 모자라는 사람은 미련함을 즐기지만, 명철한 사람은 길을 바로 걷는다.", Chn:"", Eng:"Folly delights a man who lacks judgment, but a man of understanding keeps a straight course.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:22, Page:1, Kor:"의논 없이 세워진 계획은 실패하지만, 조언자들이 많으면 그 계획이 이루어진다.", Chn:"", Eng:"Plans fail for lack of counsel, but with many advisers they succeed.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:23, Page:1, Kor:"적절한 대답은 사람을 기쁘게 하니, 알맞은 말이 제때에 나오면 참 즐겁다.", Chn:"", Eng:"A man finds joy in giving an apt reply--and how good is a timely word!", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:24, Page:1, Kor:"슬기로운 사람이 걷는 생명의 길은 위쪽으로 나 있어서, 아래로 난 스올 길을 벗어난다.", Chn:"", Eng:"The path of life leads upward for the wise to keep him from going down to the grave.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:25, Page:1, Kor:"주님은 거만한 사람의 집을 헐어 버리시지만, 과부가 사는 곳의 경계선은 튼튼히 세워 주신다.", Chn:"", Eng:"The LORD tears down the proud man's house but he keeps the widow's boundaries intact.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:26, Page:1, Kor:"악한 사람의 꾀는 주님께서 역겨워하시지만, 친절한 사람의 말은 정결한 제물처럼 받으신다.", Chn:"", Eng:"The LORD detests the thoughts of the wicked, but those of the pure are pleasing to him.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:27, Page:1, Kor:"불의한 이익을 탐내는 사람은 자기 집에 해를 끼치지만, 뇌물을 거절하는 사람은 오래 산다.", Chn:"", Eng:"A greedy man brings trouble to his family, but he who hates bribes will live.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:28, Page:1, Kor:"의인의 마음은 대답할 말을 깊이 생각하지만, 악인의 입은 악한 말을 쏟아낸다.", Chn:"", Eng:"The heart of the righteous weighs its answers, but the mouth of the wicked gushes evil.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:29, Page:1, Kor:"주님은 악인을 멀리하시지만, 의인의 기도는 들어주신다.", Chn:"", Eng:"The LORD is far from the wicked but he hears the prayer of the righteous.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:30, Page:1, Kor:"밝은 얼굴은 사람을 기쁘게 하고, 좋은 소식은 사람을 낫게 한다.", Chn:"", Eng:"A cheerful look brings joy to the heart, and good news gives health to the bones.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:31, Page:1, Kor:"목숨을 살리는 책망에 귀 기울이는 사람은 지혜로운 사람들 사이에 자리를 잡는다.", Chn:"", Eng:"He who listens to a life-giving rebuke will be at home among the wise.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:32, Page:1, Kor:"훈계를 싫어하는 사람은 자기 생명을 가볍게 여기는 사람이지만, 책망을 잘 듣는 사람은 지식을 얻는 사람이다.", Chn:"", Eng:"He who ignores discipline despises himself, but whoever heeds correction gains understanding.", Ind:""},
  {Bible:"Proverbs", Chapter:15, Verse:33, Page:1, Kor:"c주님을 경외하라는 것은 지혜가 주는 훈계이다. 겸손하면 영광이 따른다. (c 또는 '지혜는 주님을 경외하라고 가르친다' 또는 '주님을 경외하면 지혜를 배운다')", Chn:"", Eng:"The fear of the LORD teaches a man wisdom, and humility comes before honor.", Ind:""},
]);
