// 욥기 20장 · Job 20
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",20,29);
BibleDB.add([
  {Bible:"Job", Chapter:20, Verse:1, Page:1,
    Kor:"<소발의 두 번째 발언> 나아마 사람 소발이 대답하였다.",
    Chn:"拿玛人琐法回答说：",
    Eng:"Then Zophar the Naamathite replied:",
    Ind:"Maka Zofar, orang Naama, menjawab:"
  },
  {Bible:"Job", Chapter:20, Verse:2, Page:1,
    Kor:"입을 다물고 있으려 했으나, 네 말을 듣고 있자니 화가 나서 참을 수가 없다.",
    Chn:"我心中急躁， 所以我的思念叫我回答。",
    Eng:"\"My troubled thoughts prompt me to answer because I am greatly disturbed.",
    Ind:"\"Oleh sebab itulah pikiran-pikiranku mendorong aku menjawab, karena hatiku tidak sabar lagi."
  },
  {Bible:"Job", Chapter:20, Verse:3, Page:1,
    Kor:"네가 하는 말을 듣고 있자니 모두 나를 모욕하는 말이다. 그러나 깨닫게 하는 영이 내게 대답할 말을 일러주었다.",
    Chn:"我已听见那羞辱我，责备我的话； 我的悟性叫我回答。",
    Eng:"I hear a rebuke that dishonors me, and my understanding inspires me to reply.",
    Ind:"Kudengar teguran yang menghina aku, tetapi yang menjawab aku ialah akal budi yang tidak berpengertian."
  },
  {Bible:"Job", Chapter:20, Verse:4, Page:1,
    Kor:"너도 이런 것쯤은 알고 있을 것이다. 이 땅에 a사람이 생기기 시작한 그 옛날로부터, (a 또는 '아담')",
    Chn:"你岂不知亘古以来， 自从人生在地，",
    Eng:"\"Surely you know how it has been from of old, ever since man was placed on the earth,",
    Ind:"Belumkah engkau mengetahui semuanya itu sejak dahulu kala, sejak manusia ditempatkan di bumi,"
  },
  {Bible:"Job", Chapter:20, Verse:5, Page:1,
    Kor:"악한 자의 승전가는 언제나 잠깐뿐이었으며, 경건하지 못한 자의 기쁨도 순간일 뿐이었다.",
    Chn:"恶人夸胜是暂时的， 不敬虔人的喜乐不过转眼之间吗？",
    Eng:"that the mirth of the wicked is brief, the joy of the godless lasts but a moment.",
    Ind:"bahwa sorak-sorai orang fasik hanya sebentar saja, dan sukacita orang durhaka hanya sekejap mata?"
  },
  {Bible:"Job", Chapter:20, Verse:6, Page:1,
    Kor:"교만이 하늘 높은 줄 모르고, 머리가 구름에 닿는 것 같아도,",
    Chn:"他的尊荣虽达到天上， 头虽顶到云中，",
    Eng:"Though his pride reaches to the heavens and his head touches the clouds,",
    Ind:"Walaupun keangkuhannya sampai ke langit dan kepalanya mengenai awan,"
  },
  {Bible:"Job", Chapter:20, Verse:7, Page:1,
    Kor:"마침내 그도 분토처럼 사라지고 말며, 그를 본 적이 있는 사람도 그 교만한 자가 왜 안 보이느냐고 물으리라는 것쯤은, 너도 알고 있을 것이다.",
    Chn:"他终必灭亡，像自己的粪一样； 素来见他的人要说：他在哪里呢？",
    Eng:"he will perish forever, like his own dung; those who have seen him will say, 'Where is he?'",
    Ind:"namun seperti tahinya ia akan binasa untuk selama-lamanya; siapa yang pernah melihatnya, bertanya: Di mana dia?"
  },
  {Bible:"Job", Chapter:20, Verse:8, Page:1,
    Kor:"꿈같이 잊혀져 다시는 흔적을 찾을 수 없게 되며, 마치 밤에 본 환상처럼 사라질 것이다.",
    Chn:"他必飞去如梦，不再寻见， 速被赶去，如夜间的异象。",
    Eng:"Like a dream he flies away, no more to be found, banished like a vision of the night.",
    Ind:"Bagaikan impian ia melayang hilang, tak berbekas, lenyap bagaikan penglihatan waktu malam."
  },
  {Bible:"Job", Chapter:20, Verse:9, Page:1,
    Kor:"그를 본 적이 있는 사람도 다시는 그를 볼 수 없으며, 그가 살던 곳에서도 다시는 그를 볼 수 없을 것이다.",
    Chn:"亲眼见过他的，必不再见他； 他的本处也再见不着他。",
    Eng:"The eye that saw him will not see him again; his place will look on him no more.",
    Ind:"Ia tidak lagi tampak pada mata yang melihatnya, dan tempat kediamannya tidak melihatnya lagi."
  },
  {Bible:"Job", Chapter:20, Verse:10, Page:1,
    Kor:"그 자녀들이 가난한 사람에게 용서를 구할 것이며, 착취한 재물을 가난한 사람에게 배상하게 될 것이다.",
    Chn:"他的儿女要求穷人的恩； 他的手要赔还不义之财。",
    Eng:"His children must make amends to the poor; his own hands must give back his wealth.",
    Ind:"Anak-anaknya harus mencari belas kasihan orang miskin, dan tangannya sendiri harus mengembalikan kekayaannya."
  },
  {Bible:"Job", Chapter:20, Verse:11, Page:1,
    Kor:"그의 몸에 한때는 젊음이 넘쳤어도, 그 젊음은 역시 그와 함께 먼지 속에 눕게 될 것이다.",
    Chn:"他的骨头虽然有青年之力， 却要和他一同躺卧在尘土中。",
    Eng:"The youthful vigor that fills his bones will lie with him in the dust.",
    Ind:"Tulang-tulangnya boleh penuh tenaga orang muda, tetapi tenaga itupun akan membaringkan diri bersama dia dalam debu."
  },
  {Bible:"Job", Chapter:20, Verse:12, Page:1,
    Kor:"그가 혀로 악을 맛보니, 맛이 좋았다.",
    Chn:"他口内虽以恶为甘甜， 藏在舌头底下，",
    Eng:"\"Though evil is sweet in his mouth and he hides it under his tongue,",
    Ind:"Sungguhpun kejahatan manis rasanya di dalam mulutnya, sekalipun ia menyembunyikannya di bawah lidahnya,"
  },
  {Bible:"Job", Chapter:20, Verse:13, Page:1,
    Kor:"그래서 그는 악을 혀 밑에 넣고, 그 달콤한 맛을 즐겼다.",
    Chn:"爱恋不舍，含在口中；",
    Eng:"though he cannot bear to let it go and keeps it in his mouth,",
    Ind:"menikmatinya serta tidak melepaskannya, dan menahannya pada langit-langitnya,"
  },
  {Bible:"Job", Chapter:20, Verse:14, Page:1,
    Kor:"그러나 그것이 뱃속으로 내려가서는 쓴맛으로 변해 버렸다. 그것이 그의 몸 속에서 독사의 독이 되어 버렸다.",
    Chn:"他的食物在肚里却要化为酸， 在他里面成为虺蛇的恶毒。",
    Eng:"yet his food will turn sour in his stomach; it will become the venom of serpents within him.",
    Ind:"namun berubah juga makanannya di dalam perutnya, menjadi bisa ular tedung di dalamnya."
  },
  {Bible:"Job", Chapter:20, Verse:15, Page:1,
    Kor:"그 악한 자는 꿀꺽 삼킨 재물을 다 토해 냈다. 하나님은 이렇게 그 재물을 그 악한 자의 입에서 꺼내어서 빼앗긴 사람들에게 되돌려 주신다.",
    Chn:"他吞了财宝，还要吐出； 　神要从他腹中掏出来。",
    Eng:"He will spit out the riches he swallowed; God will make his stomach vomit them up.",
    Ind:"Harta benda ditelannya, tetapi dimuntahkannya lagi, Allah yang mengeluarkannya dari dalam perutnya."
  },
  {Bible:"Job", Chapter:20, Verse:16, Page:1,
    Kor:"악한 자가 삼킨 것은 독과도 같은 것, 독사에 물려 죽듯이 그 독으로 죽는다.",
    Chn:"他必吸饮虺蛇的毒气； 蝮蛇的舌头也必杀他。",
    Eng:"He will suck the poison of serpents; the fangs of an adder will kill him.",
    Ind:"Bisa ular tedung akan diisapnya, ia akan dibunuh oleh lidah ular."
  },
  {Bible:"Job", Chapter:20, Verse:17, Page:1,
    Kor:"올리브 기름이 강물처럼 흐르는 것을 그는 못 볼 것이다. 젖과 꿀이 흐르는 것도 못 볼 것이다.",
    Chn:"流奶与蜜之河， 他不得再见。",
    Eng:"He will not enjoy the streams, the rivers flowing with honey and cream.",
    Ind:"Ia tidak boleh melihat batang-batang air dan sungai-sungai yang mengalirkan madu dan dadih."
  },
  {Bible:"Job", Chapter:20, Verse:18, Page:1,
    Kor:"그는 수고하여 얻은 것을 마음대로 먹지도 못하고 되돌려보내며, 장사해서 얻은 재물을 마음대로 누리지도 못할 것이다.",
    Chn:"他劳碌得来的要赔还，不得享用； 不能照所得的财货欢乐。",
    Eng:"What he toiled for he must give back uneaten; he will not enjoy the profit from his trading.",
    Ind:"Ia harus mengembalikan apa yang diperolehnya dan tidak mengecapnya; ia tidak menikmati kekayaan hasil dagangnya."
  },
  {Bible:"Job", Chapter:20, Verse:19, Page:1,
    Kor:"이것은, 그가 가난한 이들을 억압하고 돌보지 않았기 때문이며, 자기가 세우지도 않은 남의 집을 강제로 빼앗았기 때문이다.",
    Chn:"他欺压穷人，且又离弃； 强取非自己所盖的房屋 。",
    Eng:"For he has oppressed the poor and left them destitute; he has seized houses he did not build.",
    Ind:"Karena ia telah menghancurkan orang miskin, dan meninggalkan mereka terlantar; ia merampas rumah yang tidak dibangunnya."
  },
  {Bible:"Job", Chapter:20, Verse:20, Page:1,
    Kor:"그는 아무리 가져도 만족하지 못한다. 탐욕에 얽매여 벗어나지를 못한다.",
    Chn:"他因贪而无厌， 所喜悦的连一样也不能保守。",
    Eng:"\"Surely he will have no respite from his craving; he cannot save himself by his treasure.",
    Ind:"Sesungguhnya, ia tidak mengenal ketenangan dalam batinnya, dan ia tidak akan terluput dengan membawa harta bendanya."
  },
  {Bible:"Job", Chapter:20, Verse:21, Page:1,
    Kor:"먹을 때에는 남기는 것 없이 모조리 먹어 치우지만, 그의 번영은 오래 가지 못한다.",
    Chn:"其余的没有一样他不吞灭， 所以他的福乐不能长久。",
    Eng:"Nothing is left for him to devour; his prosperity will not endure.",
    Ind:"Suatupun tidak luput dari pada lahapnya, itulah sebabnya kemujurannya tidak kekal."
  },
  {Bible:"Job", Chapter:20, Verse:22, Page:1,
    Kor:"성공하여 하늘 끝까지 이를 때에, 그가 재앙을 만나고, 온갖 불운이 그에게 밀어닥칠 것이다.",
    Chn:"他在满足有余的时候，必到狭窄的地步； 凡受苦楚的人都必加手在他身上。",
    Eng:"In the midst of his plenty, distress will overtake him; the full force of misery will come upon him.",
    Ind:"Dalam kemewahannya yang berlimpah-limpah ia penuh kuatir; ia ditimpa kesusahan dengan sangat dahsyatnya."
  },
  {Bible:"Job", Chapter:20, Verse:23, Page:1,
    Kor:"그가 먹고 싶은 대로 먹게 놓아 두어라. 하나님이 그에게 맹렬한 진노를 퍼부으시며, 분노를 비처럼 쏟으실 것이다.",
    Chn:"他正要充满肚腹的时候， 　神必将猛烈的忿怒降在他身上； 正在他吃饭的时候， 要将这忿怒像雨降在他身上。",
    Eng:"When he has filled his belly, God will vent his burning anger against him and rain down his blows upon him.",
    Ind:"Untuk mengisi perutnya, Allah melepaskan ke atasnya murka-Nya yang menyala-nyala, dan menghujankan itu kepadanya sebagai makanannya."
  },
  {Bible:"Job", Chapter:20, Verse:24, Page:1,
    Kor:"그가 철 무기를 피하려 해도, 놋화살이 그를 꿰뚫을 것이다.",
    Chn:"他要躲避铁器； 铜弓的箭要将他射透。",
    Eng:"Though he flees from an iron weapon, a bronze-tipped arrow pierces him.",
    Ind:"Ia dapat meluputkan diri terhadap senjata besi, namun panah tembaga menembus dia."
  },
  {Bible:"Job", Chapter:20, Verse:25, Page:1,
    Kor:"등을 뚫고 나온 화살을 빼낸다 하여도, 쓸개를 휘젓고 나온 번쩍이는 활촉이 그를 겁에 질리게 할 것이다.",
    Chn:"他把箭一抽，就从他身上出来； 发光的箭头从他胆中出来， 有惊惶临在他身上。",
    Eng:"He pulls it out of his back, the gleaming point out of his liver. Terrors will come over him;",
    Ind:"Anak panah itu tercabut dan keluar dari punggungnya, mata panah yang berkilat itu keluar dari empedunya: ia menjadi ngeri."
  },
  {Bible:"Job", Chapter:20, Verse:26, Page:1,
    Kor:"그가 간직한 평생 모은 모든 재산이 삽시간에 없어지고, 풀무질을 하지 않아도 저절로 타오르는 불길이 그를 삼킬 것이며, 그 불이 집에 남아 있는 사람들까지 사를 것이다.",
    Chn:"他的财宝归于黑暗； 人所不吹的火要把他烧灭， 要把他帐棚中所剩下的烧毁。",
    Eng:"total darkness lies in wait for his treasures. A fire unfanned will consume him and devour what is left in his tent.",
    Ind:"Kegelapan semata-mata tersedia bagi dia, api yang tidak ditiup memakan dia dan menghabiskan apa yang tersisa dalam kemahnya."
  },
  {Bible:"Job", Chapter:20, Verse:27, Page:1,
    Kor:"하늘이 그의 죄악을 밝히 드러내며, 땅이 그를 고발할 것이다.",
    Chn:"天要显明他的罪孽； 地要兴起攻击他。",
    Eng:"The heavens will expose his guilt; the earth will rise up against him.",
    Ind:"Langit menyingkapkan kesalahannya, dan bumi bangkit melawan dia."
  },
  {Bible:"Job", Chapter:20, Verse:28, Page:1,
    Kor:"하나님이 진노하시는 날에, 그 집의 모든 재산이 홍수에 쓸려가듯 다 쓸려갈 것이다.",
    Chn:"他的家产必然过去； 　神发怒的日子，他的货物都要消灭。",
    Eng:"A flood will carry off his house, rushing waters on the day of God's wrath.",
    Ind:"Hasil usahanya yang ada di rumahnya diangkut, semuanya habis pada hari murka-Nya."
  },
  {Bible:"Job", Chapter:20, Verse:29, Page:1,
    Kor:"이것이, 악한 사람이 하나님께 받을 몫이며, 하나님이 그의 것으로 정해 주신 유산이 될 것이다.",
    Chn:"这是恶人从　神所得的分， 是　神为他所定的产业。",
    Eng:"Such is the fate God allots the wicked, the heritage appointed for them by God.\" JOB",
    Ind:"Itulah ganjaran Allah bagi orang fasik, milik pusaka yang dijanjikan Allah kepadanya.\""
  },
]);
