// 욥기 29장 · Job 29
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",29,25);
BibleDB.add([
  {Bible:"Job", Chapter:29, Verse:1, Page:1,
    Kor:"<욥의 마지막 발언> 욥이 다시 비유를 써서 말을 하였다.",
    Chn:"约伯又接着说：",
    Eng:"Job continued his discourse:",
    Ind:"Maka Ayub melanjutkan uraiannya:"
  },
  {Bible:"Job", Chapter:29, Verse:2, Page:1,
    Kor:"지나간 세월로 되돌아갈 수만 있으면, 하나님이 보호해 주시던 그 지나간 날로 되돌아갈 수 있으면 좋으련만!",
    Chn:"惟愿我的景况如从前的月份， 如　神保守我的日子。",
    Eng:"\"How I long for the months gone by, for the days when God watched over me,",
    Ind:"\"Ah, kiranya aku seperti dalam bulan-bulan yang silam, seperti pada hari-hari, ketika Allah melindungi aku,"
  },
  {Bible:"Job", Chapter:29, Verse:3, Page:1,
    Kor:"그 때에는 하나님이 그 등불로 내 머리 위를 비추어 주셨고, 빛으로 인도해 주시는 대로, 내가 어둠 속을 활보하지 않았던가?",
    Chn:"那时他的灯照在我头上； 我借他的光行过黑暗。",
    Eng:"when his lamp shone upon my head and by his light I walked through darkness!",
    Ind:"ketika pelita-Nya bersinar di atas kepalaku, dan di bawah terang-Nya aku berjalan dalam gelap;"
  },
  {Bible:"Job", Chapter:29, Verse:4, Page:1,
    Kor:"내가 그처럼 잘 살던 그 시절로 다시 돌아가서 살 수 있으면 좋으련만! 내 집에서 하나님과 친밀하게 사귀던 그 시절로 되돌아갈 수 있으면 좋으련만!",
    Chn:"我愿如壮年的时候： 那时我在帐棚中， 　神待我有密友之情；",
    Eng:"Oh, for the days when I was in my prime, when God's intimate friendship blessed my house,",
    Ind:"seperti ketika aku mengalami masa remajaku, ketika Allah bergaul karib dengan aku di dalam kemahku;"
  },
  {Bible:"Job", Chapter:29, Verse:5, Page:1,
    Kor:"그 때에는 전능하신 분께서 나와 함께 계시고, 내 자녀들도 나와 함께 있었건만.",
    Chn:"全能者仍与我同在； 我的儿女都环绕我。",
    Eng:"when the Almighty was still with me and my children were around me,",
    Ind:"ketika Yang Mahakuasa masih beserta aku, dan anak-anakku ada di sekelilingku;"
  },
  {Bible:"Job", Chapter:29, Verse:6, Page:1,
    Kor:"젖소와 양들이 젖을 많이 내어서, 내 발이 젖으로 흠뻑 젖었건만. 돌짝 밭에서 자란 올리브 나무에서는, 올리브 기름이 강물처럼 흘러 나왔건만.",
    Chn:"奶多可洗我的脚； 磐石为我出油成河。",
    Eng:"when my path was drenched with cream and the rock poured out for me streams of olive oil.",
    Ind:"ketika langkah-langkahku bermandikan dadih, dan gunung batu mengalirkan sungai minyak di dekatku."
  },
  {Bible:"Job", Chapter:29, Verse:7, Page:1,
    Kor:"그 때에는 내가 성문 회관에 나가거나 광장에 자리를 잡고 앉으면,",
    Chn:"我出到城门， 在街上设立座位；",
    Eng:"\"When I went to the gate of the city and took my seat in the public square,",
    Ind:"Apabila aku keluar ke pintu gerbang kota, dan menyediakan tempat dudukku di tengah-tengah lapangan,"
  },
  {Bible:"Job", Chapter:29, Verse:8, Page:1,
    Kor:"젊은이들은 나를 보고 비켜 서고, 노인들은 일어나서 내게 인사하였건만.",
    Chn:"少年人见我而回避， 老年人也起身站立；",
    Eng:"the young men saw me and stepped aside and the old men rose to their feet;",
    Ind:"maka ketika aku kelihatan, mundurlah orang-orang muda dan bangkitlah orang-orang yang sudah lanjut umurnya, lalu tinggal berdiri;"
  },
  {Bible:"Job", Chapter:29, Verse:9, Page:1,
    Kor:"원로들도 하던 말을 멈추고 손으로 입을 가렸으며,",
    Chn:"王子都停止说话， 用手捂口；",
    Eng:"the chief men refrained from speaking and covered their mouths with their hands;",
    Ind:"para pembesar berhenti bicara, dan menutup mulut mereka dengan tangan;"
  },
  {Bible:"Job", Chapter:29, Verse:10, Page:1,
    Kor:"귀족들도 혀가 입천장에 달라붙기나 한 것처럼 말소리를 죽였건만.",
    Chn:"首领静默无声， 舌头贴住上膛。",
    Eng:"the voices of the nobles were hushed, and their tongues stuck to the roof of their mouths.",
    Ind:"suara para pemuka membisu, dan lidah mereka melekat pada langit-langitnya;"
  },
  {Bible:"Job", Chapter:29, Verse:11, Page:1,
    Kor:"내 소문을 들은 사람들은 내가 한 일을 칭찬하고, 나를 직접 본 사람들은 내가 한 일을 기꺼이 자랑하고 다녔다.",
    Chn:"耳朵听我的，就称我有福； 眼睛看我的，便称赞我；",
    Eng:"Whoever heard me spoke well of me, and those who saw me commended me,",
    Ind:"apabila telinga mendengar tentang aku, maka aku disebut berbahagia; dan apabila mata melihat, maka aku dipuji."
  },
  {Bible:"Job", Chapter:29, Verse:12, Page:1,
    Kor:"내게 도움을 청한 가난한 사람들을 내가 어떻게 구해 주었는지, 의지할 데가 없는 고아를 내가 어떻게 잘 보살펴 주었는지를 자랑하고 다녔다.",
    Chn:"因我拯救哀求的困苦人 和无人帮助的孤儿。",
    Eng:"because I rescued the poor who cried for help, and the fatherless who had none to assist him.",
    Ind:"Karena aku menyelamatkan orang sengsara yang berteriak minta tolong, juga anak piatu yang tidak ada penolongnya;"
  },
  {Bible:"Job", Chapter:29, Verse:13, Page:1,
    Kor:"비참하게 죽어 가는 사람들도, 내가 베푼 자선을 기억하고 나를 축복해 주었다. 과부들의 마음도 즐겁게 해주었다.",
    Chn:"将要灭亡的为我祝福； 我也使寡妇心中欢乐。",
    Eng:"The man who was dying blessed me; I made the widow's heart sing.",
    Ind:"aku mendapat ucapan berkat dari orang yang nyaris binasa, dan hati seorang janda kubuat bersukaria;"
  },
  {Bible:"Job", Chapter:29, Verse:14, Page:1,
    Kor:"나는 늘 정의를 실천하고, 매사를 공평하게 처리하였다.",
    Chn:"我以公义为衣服， 以公平为外袍和冠冕。",
    Eng:"I put on righteousness as my clothing; justice was my robe and my turban.",
    Ind:"aku berpakaian kebenaran dan keadilan menutupi aku seperti jubah dan serban;"
  },
  {Bible:"Job", Chapter:29, Verse:15, Page:1,
    Kor:"나는 앞을 못 보는 이에게는 눈이 되어 주고, 발을 저는 이에게는 발이 되어 주었다.",
    Chn:"我为瞎子的眼， 瘸子的脚。",
    Eng:"I was eyes to the blind and feet to the lame.",
    Ind:"aku menjadi mata bagi orang buta, dan kaki bagi orang lumpuh;"
  },
  {Bible:"Job", Chapter:29, Verse:16, Page:1,
    Kor:"궁핍한 사람들에게는 아버지가 되어 주고, 알지도 못하는 사람들의 하소연도 살펴보고서 처리해 주었다.",
    Chn:"我为穷乏人的父； 素不认识的人，我查明他的案件。",
    Eng:"I was a father to the needy; I took up the case of the stranger.",
    Ind:"aku menjadi bapa bagi orang miskin, dan perkara orang yang tidak kukenal, kuselidiki."
  },
  {Bible:"Job", Chapter:29, Verse:17, Page:1,
    Kor:"악을 행하는 자들의 턱뼈를 으스러뜨리고, 그들에게 희생당하는 사람들을 빼내어 주었다.",
    Chn:"我打破不义之人的牙床， 从他牙齿中夺了所抢的。",
    Eng:"I broke the fangs of the wicked and snatched the victims from their teeth.",
    Ind:"Geraham orang curang kuremuk, dan merebut mangsanya dari giginya."
  },
  {Bible:"Job", Chapter:29, Verse:18, Page:1,
    Kor:"그래서 나는 늘 '나는 죽을 때까지 이렇게 건장하게 살 것이다. 소털처럼 많은 나날 불사조처럼 오래 살 것이다.",
    Chn:"我便说：我必死在家中， 必增添我的日子，多如尘沙。",
    Eng:"\"I thought, 'I will die in my own house, my days as numerous as the grains of sand.",
    Ind:"Pikirku: Bersama-sama dengan sarangku aku akan binasa, dan memperbanyak hari-hariku seperti burung feniks."
  },
  {Bible:"Job", Chapter:29, Verse:19, Page:1,
    Kor:"나는, 뿌리가 물가로 뻗은 나무와 같고, 이슬을 머금은 나무와 같다.",
    Chn:"我的根长到水边； 露水终夜沾在我的枝上。",
    Eng:"My roots will reach to the water, and the dew will lie all night on my branches.",
    Ind:"Akarku mencapai air, dan embun bermalam di atas ranting-rantingku."
  },
  {Bible:"Job", Chapter:29, Verse:20, Page:1,
    Kor:"사람마다 늘 나를 칭찬하고, 내 정력은 쇠하지 않을 것이다' 하고 생각하였건만.",
    Chn:"我的荣耀在身上增新； 我的弓在手中日强。",
    Eng:"My glory will remain fresh in me, the bow ever new in my hand.'",
    Ind:"Kemuliaanku selalu baru padaku, dan busurku kuat kembali di tanganku."
  },
  {Bible:"Job", Chapter:29, Verse:21, Page:1,
    Kor:"사람들은 기대를 가지고 내 말을 듣고, 내 의견을 들으려고 잠잠히 기다렸다.",
    Chn:"人听见我而仰望， 静默等候我的指教。",
    Eng:"\"Men listened to me expectantly, waiting in silence for my counsel.",
    Ind:"Kepadakulah orang mendengar sambil menanti, dengan diam mereka mendengarkan nasihatku."
  },
  {Bible:"Job", Chapter:29, Verse:22, Page:1,
    Kor:"내가 말을 마치면 다시 뒷말이 없고, 내 말은 그들 위에 이슬처럼 젖어들었다.",
    Chn:"我说话之后，他们就不再说； 我的言语像雨露滴在他们身上。",
    Eng:"After I had spoken, they spoke no more; my words fell gently on their ears.",
    Ind:"Sehabis bicaraku tiada seorangpun angkat bicara lagi, dan perkataanku menetes ke atas mereka."
  },
  {Bible:"Job", Chapter:29, Verse:23, Page:1,
    Kor:"사람들은 내 말을 기다리기를 단비를 기다리듯 하고, 농부가 봄비를 기뻐하듯이 내 말을 받아들였다.",
    Chn:"他们仰望我如仰望雨， 又张开口如切慕春雨。",
    Eng:"They waited for me as for showers and drank in my words as the spring rain.",
    Ind:"Orang menantikan aku seperti menantikan hujan, dan menadahkan mulutnya seperti menadah hujan pada akhir musim."
  },
  {Bible:"Job", Chapter:29, Verse:24, Page:1,
    Kor:"내가 미소를 지으면 그들은 새로운 확신을 얻고, 내가 웃는 얼굴을 하면 그들은 새로운 용기를 얻었다.",
    Chn:"他们不敢自信，我就向他们含笑； 他们不使我脸上的光改变。",
    Eng:"When I smiled at them, they scarcely believed it; the light of my face was precious to them.",
    Ind:"Aku tersenyum kepada mereka, ketika mereka putus asa, dan seri mukaku tidak dapat disuramkan mereka."
  },
  {Bible:"Job", Chapter:29, Verse:25, Page:1,
    Kor:"나는 마치 군대를 거느린 왕처럼, 슬퍼하는 사람을 위로해 주는 사람처럼, 사람들을 돌보고, 그들이 갈 길을 정해 주곤 하였건만.",
    Chn:"我为他们选择道路，又坐首位； 我如君王在军队中居住， 又如吊丧的安慰伤心的人。",
    Eng:"I chose the way for them and sat as their chief; I dwelt as a king among his troops; I was like one who comforts mourners.",
    Ind:"Aku menentukan jalan mereka dan duduk sebagai pemimpin; aku bersemayam seperti raja di tengah-tengah rakyat, seperti seorang yang menghibur mereka yang berkabung.\""
  },
]);
