// 욥기 22장 · Job 22
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",22,30);
BibleDB.add([
  {Bible:"Job", Chapter:22, Verse:1, Page:1, Kor:"<엘리바스의 세 번째 발언> 데만 사람 엘리바스가 대답하였다.", Chn:"", Eng:"Then Eliphaz the Temanite replied:", Ind:""},
  {Bible:"Job", Chapter:22, Verse:2, Page:1, Kor:"사람이 하나님께 무슨 유익을 끼쳐드릴 수 있느냐? 아무리 슬기로운 사람이라고 해도, 그분께 아무런 유익을 끼쳐드릴 수가 없다.", Chn:"", Eng:"\"Can a man be of benefit to God? Can even a wise man benefit him?", Ind:""},
  {Bible:"Job", Chapter:22, Verse:3, Page:1, Kor:"네가 올바르다고 하여 그것이 전능하신 분께 무슨 기쁨이 되겠으며, 네 행위가 온전하다고 하여 그것이 그분께 무슨 유익이 되겠느냐?", Chn:"", Eng:"What pleasure would it give the Almighty if you were righteous? What would he gain if your ways were blameless?", Ind:""},
  {Bible:"Job", Chapter:22, Verse:4, Page:1, Kor:"네가 하나님을 경외한 것 때문에, 하나님이 너를 책망하시며, 너를 심판하시겠느냐?", Chn:"", Eng:"\"Is it for your piety that he rebukes you and brings charges against you?", Ind:""},
  {Bible:"Job", Chapter:22, Verse:5, Page:1, Kor:"오히려 네 죄가 많고, 네 죄악이 끝이 없으니, 그러한 것이 아니냐?", Chn:"", Eng:"Is not your wickedness great? Are not your sins endless?", Ind:""},
  {Bible:"Job", Chapter:22, Verse:6, Page:1, Kor:"네가 까닭 없이 친족의 재산을 압류하고, 옷을 빼앗아 헐벗게 하고,", Chn:"", Eng:"You demanded security from your brothers for no reason; you stripped men of their clothing, leaving them naked.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:7, Page:1, Kor:"목마른 사람에게 마실 물 한 모금도 주지 않고, 배고픈 사람에게 먹을 것도 주지 않았기 때문이 아니겠느냐?", Chn:"", Eng:"You gave no water to the weary and you withheld food from the hungry,", Ind:""},
  {Bible:"Job", Chapter:22, Verse:8, Page:1, Kor:"너는 권세를 이용하여 땅을 차지하고, 지위를 이용하여 이 땅에서 거들먹거리면서 살았다.", Chn:"", Eng:"though you were a powerful man, owning land--an honored man, living on it.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:9, Page:1, Kor:"너는 과부들을 빈 손으로 돌려보내고, 고아들을 혹사하고 학대하였다.", Chn:"", Eng:"And you sent widows away empty-handed and broke the strength of the fatherless.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:10, Page:1, Kor:"그러기에 이제 네가 온갖 올무에 걸려 들고, 공포에 사로잡힌 것이다.", Chn:"", Eng:"That is why snares are all around you, why sudden peril terrifies you,", Ind:""},
  {Bible:"Job", Chapter:22, Verse:11, Page:1, Kor:"어둠이 덮쳐서 네가 앞을 볼 수 없고, 홍수가 너를 뒤덮는 것이다.", Chn:"", Eng:"why it is so dark you cannot see, and why a flood of water covers you.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:12, Page:1, Kor:"하나님이 하늘 높은 곳에 계시지 않느냐? 저 공중에 높이 떠 있는 별들까지도, 하나님이 내려다보고 계시지 않느냐?", Chn:"", Eng:"\"Is not God in the heights of heaven? And see how lofty are the highest stars!", Ind:""},
  {Bible:"Job", Chapter:22, Verse:13, Page:1, Kor:"그런데도 너는 \"하나님이 무엇을 아시겠으며, 검은 구름 속에 숨어 계시면서 어떻게 우리를 심판하실 수 있겠느냐?", Chn:"", Eng:"Yet you say, 'What does God know? Does he judge through such darkness?", Ind:""},
  {Bible:"Job", Chapter:22, Verse:14, Page:1, Kor:"짙은 구름에 그가 둘러싸여 어떻게 보실 수 있겠느냐? 다만 하늘에서만 왔다갔다 하실 뿐이겠지!\" 하는구나.", Chn:"", Eng:"Thick clouds veil him, so he does not see us as he goes about in the vaulted heavens.'", Ind:""},
  {Bible:"Job", Chapter:22, Verse:15, Page:1, Kor:"너는 아직도 옛 길을 고집할 셈이냐? 악한 자들이 걷던 그 길을 고집할 셈이냐?", Chn:"", Eng:"Will you keep to the old path that evil men have trod?", Ind:""},
  {Bible:"Job", Chapter:22, Verse:16, Page:1, Kor:"그들은 때가 되기도 전에 사로잡혀 갔고, 그 기초가 무너져서 강물에 떠내려가 버렸다.", Chn:"", Eng:"They were carried off before their time, their foundations washed away by a flood.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:17, Page:1, Kor:"그런데도 그들은 하나님께 말하기를 \"우리를 좀 그냥 내버려 두십시오. 전능하신 분이라고 하여 우리에게 무슨 일을 더 하실 수 있겠습니까?\" 하였다.", Chn:"", Eng:"They said to God, 'Leave us alone! What can the Almighty do to us?'", Ind:""},
  {Bible:"Job", Chapter:22, Verse:18, Page:1, Kor:"그들의 집에 좋은 것을 가득 채워 주신 분이 바로 하나님이신데도 악한 자들이 그런 생각을 하다니, 나는 이해할 수 없다.", Chn:"", Eng:"Yet it was he who filled their houses with good things, so I stand aloof from the counsel of the wicked.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:19, Page:1, Kor:"그런 악한 자가 형벌을 받을 때에, 의로운 사람이 그것을 보고 기뻐하며, 죄 없는 사람들이 그것을 보고 비웃기를", Chn:"", Eng:"\"The righteous see their ruin and rejoice; the innocent mock them, saying,", Ind:""},
  {Bible:"Job", Chapter:22, Verse:20, Page:1, Kor:"\"과연 우리 원수는 전멸되고, 남은 재산은 불에 타서 없어졌다\" 할 것이다.", Chn:"", Eng:"'Surely our foes are destroyed, and fire devours their wealth.'", Ind:""},
  {Bible:"Job", Chapter:22, Verse:21, Page:1, Kor:"그러므로 너는 하나님과 화해하고, 하나님을 원수로 여기지 말아라. 그러면 하나님이 너에게 은총을 베푸실 것이다.", Chn:"", Eng:"\"Submit to God and be at peace with him; in this way prosperity will come to you.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:22, Page:1, Kor:"하나님이 친히 말씀하여 주시는 교훈을 받아들이고, 그의 말씀을 네 마음에 깊이 간직하여라.", Chn:"", Eng:"Accept instruction from his mouth and lay up his words in your heart.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:23, Page:1, Kor:"전능하신 분에게로 겸손하게 돌아가면, 너는 다시 회복될 것이다. 온갖 불의한 것을 네 집 안에서 내버려라.", Chn:"", Eng:"If you return to the Almighty, you will be restored: If you remove wickedness far from your tent", Ind:""},
  {Bible:"Job", Chapter:22, Verse:24, Page:1, Kor:"황금도 티끌 위에다가 내버리고, 오빌의 정금도 계곡의 돌바닥 위에 내던져라.", Chn:"", Eng:"and assign your nuggets to the dust, your gold of Ophir to the rocks in the ravines,", Ind:""},
  {Bible:"Job", Chapter:22, Verse:25, Page:1, Kor:"그러면 전능하신 분이 네 보물이 되시고, 산더미처럼 쌓이는 은이 되실 것이다.", Chn:"", Eng:"then the Almighty will be your gold, the choicest silver for you.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:26, Page:1, Kor:"그 때가 되어야 비로소 너는, 전능하신 분을 진정으로 의지하게 되고, 그분만이 네 기쁨의 근원이심을 알게 될 것이다.", Chn:"", Eng:"Surely then you will find delight in the Almighty and will lift up your face to God.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:27, Page:1, Kor:"네가 그분에게 기도를 드리면 들어주실 것이며, 너는 서원한 것을 다 이룰 것이다.", Chn:"", Eng:"You will pray to him, and he will hear you, and you will fulfill your vows.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:28, Page:1, Kor:"하는 일마다 다 잘 되고, 빛이 네가 걷는 길을 비추어 줄 것이다.", Chn:"", Eng:"What you decide on will be done, and light will shine on your ways.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:29, Page:1, Kor:"사람들이 쓰러지거든, 너는 그것이 교만 때문이라고 일러주어라. 하나님은 겸손한 사람을 구원하신다.", Chn:"", Eng:"When men are brought low and you say, 'Lift them up!' then he will save the downcast.", Ind:""},
  {Bible:"Job", Chapter:22, Verse:30, Page:1, Kor:"그분은 죄 없는 사람을 구원하신다. 너도 깨끗하게 되면, 그분께서 구해 주실 것이다.", Chn:"", Eng:"He will deliver even one who is not innocent, who will be delivered through the cleanness of your hands.\"", Ind:""},
]);
