// 욥기 9장 · Job 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",9,35);
BibleDB.add([
  {Bible:"Job", Chapter:9, Verse:1, Page:1, Kor:"<욥의 대답> 욥이 대답하였다.", Chn:"", Eng:"Then Job replied:", Ind:""},
  {Bible:"Job", Chapter:9, Verse:2, Page:1, Kor:"그것이 사실이라는 것은 나도 잘 알고 있다. 그러나 사람이 어떻게 하나님 앞에서 의롭다고 주장할 수 있겠느냐?", Chn:"", Eng:"\"Indeed, I know that this is true. But how can a mortal be righteous before God?", Ind:""},
  {Bible:"Job", Chapter:9, Verse:3, Page:1, Kor:"사람이 하나님과 논쟁을 한다고 해도, 그분의 천 마디 말씀에 한 마디도 대답하지 못할 것이다.", Chn:"", Eng:"Though one wished to dispute with him, he could not answer him one time out of a thousand.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:4, Page:1, Kor:"하나님이 전지전능하시니, 그를 거역하고 온전할 사람이 있겠느냐?", Chn:"", Eng:"His wisdom is profound, his power is vast. Who has resisted him and come out unscathed?", Ind:""},
  {Bible:"Job", Chapter:9, Verse:5, Page:1, Kor:"아무도 모르는 사이에 산을 옮기시며, 진노하셔서 산을 뒤집어엎기도 하신다.", Chn:"", Eng:"He moves mountains without their knowing it and overturns them in his anger.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:6, Page:1, Kor:"지진을 일으키시어 땅을 그 밑뿌리에서 흔드시고, 땅을 받치고 있는 기둥들을 흔드신다.", Chn:"", Eng:"He shakes the earth from its place and makes its pillars tremble.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:7, Page:1, Kor:"해에게 명령하시어 뜨지 못하게도 하시며, 별들을 가두시어 빛을 내지 못하게도 하신다.", Chn:"", Eng:"He speaks to the sun and it does not shine; he seals off the light of the stars.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:8, Page:1, Kor:"어느 누구에게 도움을 받지도 않고 하늘을 펼치시며, a바다 괴물의 등을 짓밟으신다. (a 또는 '바다의 파도를 짓밟으신다')", Chn:"", Eng:"He alone stretches out the heavens and treads on the waves of the sea.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:9, Page:1, Kor:"북두칠성과 삼성을 만드시고, 묘성과 남방의 밀실을 만드시며,", Chn:"", Eng:"He is the Maker of the Bear and Orion, the Pleiades and the constellations of the south.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:10, Page:1, Kor:"우리가 측량할 수 없는 큰 일을 하시며, 우리가 헤아릴 수 없는 기이한 일을 행하시는 분이시다.", Chn:"", Eng:"He performs wonders that cannot be fathomed, miracles that cannot be counted.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:11, Page:1, Kor:"하나님이 내 곁을 지나가신다 해도 볼 수 없으며, 내 앞에서 걸으신다 해도 알 수 없다.", Chn:"", Eng:"When he passes me, I cannot see him; when he goes by, I cannot perceive him.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:12, Page:1, Kor:"그가 가져 가신다면 누가 도로 찾을 수 있으며, 누가 감히 그에게 왜 그러시느냐고 할 수 있겠느냐?", Chn:"", Eng:"If he snatches away, who can stop him? Who can say to him, 'What are you doing?'", Ind:""},
  {Bible:"Job", Chapter:9, Verse:13, Page:1, Kor:"하나님이 진노를 풀지 아니하시면 b라합을 돕는 무리도 무릎을 꿇는데, (b 전설에 나오는 바다의 괴물, 혼돈과 악의 세력을 대표함)", Chn:"", Eng:"God does not restrain his anger; even the cohorts of Rahab cowered at his feet.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:14, Page:1, Kor:"내가 어찌 감히 그분에게 한 마디라도 대답할 수 있겠으며, 내가 무슨 말로 말대꾸를 할 수 있겠느냐?", Chn:"", Eng:"\"How then can I dispute with him? How can I find words to argue with him?", Ind:""},
  {Bible:"Job", Chapter:9, Verse:15, Page:1, Kor:"비록 내가 옳다 해도 감히 아무 대답도 할 수 없다. 다만 나로서 할 수 있는 일은 나를 심판하실 그분께 은총을 비는 것뿐이다.", Chn:"", Eng:"Though I were innocent, I could not answer him; I could only plead with my Judge for mercy.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:16, Page:1, Kor:"비록 그분께서 내가 말하는 것을 허락하신다 해도, 내가 부르짖는 소리를 귀기울여 들으실까?", Chn:"", Eng:"Even if I summoned him and he responded, I do not believe he would give me a hearing.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:17, Page:1, Kor:"그분께서 머리털 한 오라기만한 하찮은 일로도 나를 이렇게 짓눌러 부수시고, 나도 모를 이유로 나에게 많은 상처를 입히시는데,", Chn:"", Eng:"He would crush me with a storm and multiply my wounds for no reason.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:18, Page:1, Kor:"숨돌릴 틈도 주시지 않고 쓰라림만 안겨 주시는데, 그분께서 내 간구를 들어 주실까?", Chn:"", Eng:"He would not let me regain my breath but would overwhelm me with misery.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:19, Page:1, Kor:"강한 쪽이 그분이신데, 힘으로 겨룬다고 한들 어떻게 이기겠으며, 재판에 붙인다고 한들 누가 c그분을 재판정으로 불러올 수 있겠느냐? (c 칠십인역을 따름. 히, '나를')", Chn:"", Eng:"If it is a matter of strength, he is mighty! And if it is a matter of justice, who will summon him?", Ind:""},
  {Bible:"Job", Chapter:9, Verse:20, Page:1, Kor:"비록 내가 옳다고 하더라도, 그분께서 내 입을 시켜서 나를 정죄하실 것이며, 비록 내가 흠이 없다고 하더라도, 그분께서 나를 틀렸다고 하실 것이다.", Chn:"", Eng:"Even if I were innocent, my mouth would condemn me; if I were blameless, it would pronounce me guilty.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:21, Page:1, Kor:"비록 내가 흠이 없다고 하더라도, 나도 나 자신을 잘 모르겠고, 다만, 산다는 것이 싫을 뿐이다.", Chn:"", Eng:"\"Although I am blameless, I have no concern for myself; I despise my own life.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:22, Page:1, Kor:"나에게는 모든 것이 한 가지로만 여겨진다. 그러므로 나는 \"그분께서는 흠이 없는 사람이나, 악한 사람이나, 다 한 가지로 심판하신다\" 하고 말할 수밖에 없다.", Chn:"", Eng:"It is all the same; that is why I say, 'He destroys both the blameless and the wicked.'", Ind:""},
  {Bible:"Job", Chapter:9, Verse:23, Page:1, Kor:"갑작스러운 재앙으로 다들 죽게 되었을 때에도, 죄 없는 자마저 재앙을 받는 것을 보시고 비웃으실 것이다.", Chn:"", Eng:"When a scourge brings sudden death, he mocks the despair of the innocent.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:24, Page:1, Kor:"세상이 악한 권세자의 손에 넘어가도, 주님께서 재판관의 눈을 가려서 제대로 판결하지 못하게 하신다. 그렇지 않다고 하면, 그렇게 하는 이가 누구란 말이냐?", Chn:"", Eng:"When a land falls into the hands of the wicked, he blindfolds its judges. If it is not he, then who is it?", Ind:""},
  {Bible:"Job", Chapter:9, Verse:25, Page:1, Kor:"내 일생이 달리는 경주자보다 더 빨리 지나가므로, 좋은 세월을 누릴 겨를이 없습니다.", Chn:"", Eng:"\"My days are swifter than a runner; they fly away without a glimpse of joy.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:26, Page:1, Kor:"그 지나가는 것이 갈대 배와 같이 빠르고, 먹이를 덮치려고 내려오는 독수리처럼 빠릅니다.", Chn:"", Eng:"They skim past like boats of papyrus, like eagles swooping down on their prey.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:27, Page:1, Kor:"온갖 불평도 잊어버리고, 슬픈 얼굴빛을 고쳐서 애써 명랑하게 보이려고 해도,", Chn:"", Eng:"If I say, 'I will forget my complaint, I will change my expression, and smile,'", Ind:""},
  {Bible:"Job", Chapter:9, Verse:28, Page:1, Kor:"내가 겪는 이 모든 고통이 다만 두렵기만 합니다. 그러나 주님께서 나를 죄 없다고 여기지 않으실 것임을 압니다.", Chn:"", Eng:"I still dread all my sufferings, for I know you will not hold me innocent.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:29, Page:1, Kor:"주님께서 나를 정죄하신다면, 내가 무엇 때문에 이렇게 애써서 헛된 수고를 해야 합니까?", Chn:"", Eng:"Since I am already found guilty, why should I struggle in vain?", Ind:""},
  {Bible:"Job", Chapter:9, Verse:30, Page:1, Kor:"비록 내가 d비누로 몸을 씻고, 잿물로 손을 깨끗이 닦아도, (d 또는 '눈으로')", Chn:"", Eng:"Even if I washed myself with soap and my hands with washing soda,", Ind:""},
  {Bible:"Job", Chapter:9, Verse:31, Page:1, Kor:"주님께서 나를 다시 시궁창에 처넣으시니, 내 옷인들 나를 좋아하겠습니까?", Chn:"", Eng:"you would plunge me into a slime pit so that even my clothes would detest me.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:32, Page:1, Kor:"하나님이 나와 같은 사람이기만 하여도 내가 그분께 말을 할 수 있으련만, 함께 법정에 서서 이 논쟁을 끝낼 수 있으련만,", Chn:"", Eng:"\"He is not a man like me that I might answer him, that we might confront each other in court.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:33, Page:1, Kor:"우리 둘 사이를 중재할 사람이 없고, 하나님과 나 사이를 판결해 줄 이가 없구나!", Chn:"", Eng:"If only there were someone to arbitrate between us, to lay his hand upon us both,", Ind:""},
  {Bible:"Job", Chapter:9, Verse:34, Page:1, Kor:"내게 소원이 있다면, 내가 더 두려워 떨지 않도록, 하나님이 채찍을 거두시는 것.", Chn:"", Eng:"someone to remove God's rod from me, so that his terror would frighten me no more.", Ind:""},
  {Bible:"Job", Chapter:9, Verse:35, Page:1, Kor:"그렇게 되면 나는 두려움 없이 말하겠다. 그러나 나 스스로는, 그럴 수가 없는 줄을 알고 있다.", Chn:"", Eng:"Then I would speak up without fear of him, but as it now stands with me, I cannot.", Ind:""},
]);
