// 욥기 41장 · Job 41
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",41,34);
BibleDB.add([
  {Bible:"Job", Chapter:41, Verse:1, Page:1, Kor:"네가 낚시로 a리워야단을 낚을 수 있으며, 끈으로 그 혀를 맬 수 있느냐? (a 악어처럼 생긴 바다 괴물)", Chn:"", Eng:"\"Can you pull in the leviathan with a fishhook or tie down his tongue with a rope?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:2, Page:1, Kor:"그 코를 줄로 꿸 수 있으며, 갈고리로 그 턱을 꿸 수 있느냐?", Chn:"", Eng:"Can you put a cord through his nose or pierce his jaw with a hook?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:3, Page:1, Kor:"그것이 네게 살려 달라고 애원할 것 같으냐? 그것이 네게 자비를 베풀어 달라고 빌 것 같으냐?", Chn:"", Eng:"Will he keep begging you for mercy? Will he speak to you with gentle words?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:4, Page:1, Kor:"그것이 너와 언약을 맺기라도 하여, 영원히 네 종이 되겠다고 약속이라도 할 것 같으냐?", Chn:"", Eng:"Will he make an agreement with you for you to take him as your slave for life?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:5, Page:1, Kor:"네가 그것을 새처럼 길들여서 데리고 놀 수 있겠으며, 또 그것을 끈으로 매어서 여종들의 노리개로 삼을 수 있겠느냐?", Chn:"", Eng:"Can you make a pet of him like a bird or put him on a leash for your girls?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:6, Page:1, Kor:"어부들이 그것을 가지고 흥정하고, 그것을 토막 내어 상인들에게 팔 수 있겠느냐?", Chn:"", Eng:"Will traders barter for him? Will they divide him up among the merchants?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:7, Page:1, Kor:"네가 창으로  그것의 가죽을 꿰뚫을 수 있으며, 작살로 그 머리를 찌를 수 있겠느냐?", Chn:"", Eng:"Can you fill his hide with harpoons or his head with fishing spears?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:8, Page:1, Kor:"손으로 한 번 만져만 보아도, 그것과 싸울 생각은 못할 것이다.", Chn:"", Eng:"If you lay a hand on him, you will remember the struggle and never do it again!", Ind:""},
  {Bible:"Job", Chapter:41, Verse:9, Page:1, Kor:"a리워야단을 보는 사람은, 쳐다보기만 해도 기가 꺾이고, 땅에 고꾸라진다. (a 악어처럼 생긴 바다 괴물)", Chn:"", Eng:"Any hope of subduing him is false; the mere sight of him is overpowering.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:10, Page:1, Kor:"그것이 흥분하면 얼마나 난폭하겠느냐? 누가 그것과 맞서겠느냐?", Chn:"", Eng:"No one is fierce enough to rouse him. Who then is able to stand against me?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:11, Page:1, Kor:"그것에게 덤벼 들고 그 어느 누가 무사하겠느냐? 이 세상에는 그럴 사람이 없다.", Chn:"", Eng:"Who has a claim against me that I must pay? Everything under heaven belongs to me.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:12, Page:1, Kor:"a리워야단의 다리 이야기를 어찌 빼놓을 수 있겠느냐? 그 용맹을 어찌 말하지 않을 수 있겠느냐? 그 늠름한 체구를 어찌 말하지 않고 지나겠느냐? (a 악어처럼 생긴 바다 괴물)", Chn:"", Eng:"\"I will not fail to speak of his limbs, his strength and his graceful form.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:13, Page:1, Kor:"누가 그것의 가죽을 벗길 수 있겠느냐? 누가 두 겹 갑옷 같은 비늘 사이를 뚫을 수 있겠느냐?", Chn:"", Eng:"Who can strip off his outer coat? Who would approach him with a bridle?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:14, Page:1, Kor:"누가 그것의 턱을 벌릴 수 있겠느냐? 빙 둘러 돋아 있는 이빨은 보기만 해도 소름이 끼친다.", Chn:"", Eng:"Who dares open the doors of his mouth, ringed about with his fearsome teeth?", Ind:""},
  {Bible:"Job", Chapter:41, Verse:15, Page:1, Kor:"등비늘은, 그것이 자랑할 만한 것, 빽빽하게 짜여 있어서 돌처럼 단단하다.", Chn:"", Eng:"His back has rows of shields tightly sealed together;", Ind:""},
  {Bible:"Job", Chapter:41, Verse:16, Page:1, Kor:"그 비늘 하나하나가 서로 이어 있어서, 그 틈으로는 바람도 들어가지 못한다.", Chn:"", Eng:"each is so close to the next that no air can pass between.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:17, Page:1, Kor:"비늘이 서로 연결되어 꽉 달라붙어서, 그 얽힌 데가 떨어지지도 않는다.", Chn:"", Eng:"They are joined fast to one another; they cling together and cannot be parted.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:18, Page:1, Kor:"재채기를 하면 불빛이 번쩍거리고, 눈을 뜨면 그 눈꺼풀이 치켜 올라가는 모양이 동이 트는 것과 같다.", Chn:"", Eng:"His snorting throws out flashes of light; his eyes are like the rays of dawn.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:19, Page:1, Kor:"입에서는 횃불이 나오고, 불똥이 튄다.", Chn:"", Eng:"Firebrands stream from his mouth; sparks of fire shoot out.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:20, Page:1, Kor:"콧구멍에서 펑펑 쏟아지는 연기는, 끓는 가마 밑에서 타는 갈대 연기와 같다.", Chn:"", Eng:"Smoke pours from his nostrils as from a boiling pot over a fire of reeds.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:21, Page:1, Kor:"그 숨결은 숯불을 피울 만하고, 입에서는 불꽃이 나온다.", Chn:"", Eng:"His breath sets coals ablaze, and flames dart from his mouth.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:22, Page:1, Kor:"목에는 억센 힘이 들어 있어서, 보는 사람마다 겁에 질리고 만다.", Chn:"", Eng:"Strength resides in his neck; dismay goes before him.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:23, Page:1, Kor:"살갗은 쇠로 입힌 듯이, 약한 곳이 전혀 없다.", Chn:"", Eng:"The folds of his flesh are tightly joined; they are firm and immovable.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:24, Page:1, Kor:"심장이 돌처럼 단단하니, 그 단단하기가 맷돌 아래짝과 같다.", Chn:"", Eng:"His chest is hard as rock, hard as a lower millstone.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:25, Page:1, Kor:"일어나기만 하면 아무리 힘센 자도 벌벌 떨며, 그 몸부림 치는 소리에 기가 꺾인다.", Chn:"", Eng:"When he rises up, the mighty are terrified; they retreat before his thrashing.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:26, Page:1, Kor:"칼을 들이댄다 하여도 소용이 없고, 창이나 화살이나 표창도 맥을 쓰지 못한다.", Chn:"", Eng:"The sword that reaches him has no effect, nor does the spear or the dart or the javelin.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:27, Page:1, Kor:"쇠도 지푸라기로 여기고, 놋은 썩은 나무 정도로 생각하니,", Chn:"", Eng:"Iron he treats like straw and bronze like rotten wood.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:28, Page:1, Kor:"그것을 쏘아서 도망 치게 할 화살도 없고, 무릿매 돌도 아예 바람에 날리는 겨와 같다.", Chn:"", Eng:"Arrows do not make him flee; slingstones are like chaff to him.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:29, Page:1, Kor:"몽둥이는 지푸라기쯤으로 생각하며, 창이 날아오는 소리에는 코웃음만 친다.", Chn:"", Eng:"A club seems to him but a piece of straw; he laughs at the rattling of the lance.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:30, Page:1, Kor:"뱃가죽은 날카로운 질그릇 조각과 같아서, 타작기가 할퀸 진흙 바닥처럼, 지나간 흔적을 남긴다.", Chn:"", Eng:"His undersides are jagged potsherds, leaving a trail in the mud like a threshing sledge.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:31, Page:1, Kor:"물에 뛰어들면, 깊은 물을 가마솥의 물처럼 끓게 하고, 바다를 기름 가마처럼 휘젓는다.", Chn:"", Eng:"He makes the depths churn like a boiling caldron and stirs up the sea like a pot of ointment.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:32, Page:1, Kor:"한 번 지나가면 그 자취가 번쩍번쩍 빛을 내니, 깊은 바다가 백발을 휘날리는 것처럼 보인다.", Chn:"", Eng:"Behind him he leaves a glistening wake; one would think the deep had white hair.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:33, Page:1, Kor:"땅 위에는 그것과 겨룰 만한 것이 없으며, 그것은 처음부터 겁이 없는 것으로 지음을 받았다.", Chn:"", Eng:"Nothing on earth is his equal--a creature without fear.", Ind:""},
  {Bible:"Job", Chapter:41, Verse:34, Page:1, Kor:"모든 교만한 것들을 우습게 보고, 그 거만한 모든 것 앞에서 왕노릇을 한다.", Chn:"", Eng:"He looks down on all that are haughty; he is king over all that are proud.\"", Ind:""},
]);
