// 욥기 33장 · Job 33
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",33,33);
BibleDB.add([
  {Bible:"Job", Chapter:33, Verse:1, Page:1, Kor:"<엘리후가 욥에게 하는 말> 욥 어른은 부디 내가 하는 말을 잘 들어 주시기 바랍니다. 내가 하는 말 한마디 한마디에 귀를 기울여 주시기 바랍니다.", Chn:"", Eng:"\"But now, Job, listen to my words; pay attention to everything I say.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:2, Page:1, Kor:"이제 내 마음 속에 있는 것을 말할 준비가 되었습니다. 내 입 속에서 혀가 말을 합니다.", Chn:"", Eng:"I am about to open my mouth; my words are on the tip of my tongue.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:3, Page:1, Kor:"나는 지금 진지하게 말하고 있습니다. 나는 진실을 말하려고 합니다.", Chn:"", Eng:"My words come from an upright heart; my lips sincerely speak what I know.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:4, Page:1, Kor:"하나님의 영이 나를 만드시고, 전능하신 분의 입김이 내게 생명을 주셨습니다.", Chn:"", Eng:"The Spirit of God has made me; the breath of the Almighty gives me life.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:5, Page:1, Kor:"대답하실 수 있으면, 대답해 보시기 바랍니다. 토론할 준비를 하고 나서시기를 바랍니다.", Chn:"", Eng:"Answer me then, if you can; prepare yourself and confront me.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:6, Page:1, Kor:"보십시오, 하나님이 보시기에는, 어른이나 나나 똑같습니다. 우리는 모두 흙으로 지음을 받았습니다.", Chn:"", Eng:"I am just like you before God; I too have been taken from clay.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:7, Page:1, Kor:"그러므로 어른께서는 나를 두려워하실 까닭이 없습니다. 내게 압도되어서 기를 펴지 못하는 일이 있어서도 안 될 것입니다.", Chn:"", Eng:"No fear of me should alarm you, nor should my hand be heavy upon you.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:8, Page:1, Kor:"어른께서 이런 말씀을 하셨습니다.", Chn:"", Eng:"\"But you have said in my hearing--I heard the very words--", Ind:""},
  {Bible:"Job", Chapter:33, Verse:9, Page:1, Kor:"\"내게는 잘못이 없다. 나는 잘못을 저지르지 않았다. 나는 결백하다. 내게는 허물이 없다.", Chn:"", Eng:"'I am pure and without sin; I am clean and free from guilt.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:10, Page:1, Kor:"그런데도 하나님은 내게서 흠 잡을 것을 찾으시며, 나를 원수로 여기신다.", Chn:"", Eng:"Yet God has found fault with me; he considers me his enemy.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:11, Page:1, Kor:"하나님이 내 발에 차꼬를 채우시고, 내 일거수 일투족을 다 감시하신다\" 하고 말씀하셨습니다.", Chn:"", Eng:"He fastens my feet in shackles; he keeps close watch on all my paths.'", Ind:""},
  {Bible:"Job", Chapter:33, Verse:12, Page:1, Kor:"그러나 내가 욥 어른께 감히 말합니다. 어른은 잘못하셨습니다. 하나님은 어떤 사람보다도 크십니다.", Chn:"", Eng:"\"But I tell you, in this you are not right, for God is greater than man.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:13, Page:1, Kor:"그런데 어찌하여 어른께서는, 하나님께 불평을 하면서 대드시는 겁니까? 어른께서 하시는 모든 불평에 일일이 대답을 하지 않으신다고 해서, 하나님께 원망을 할 수 있습니까?", Chn:"", Eng:"Why do you complain to him that he answers none of man's words?", Ind:""},
  {Bible:"Job", Chapter:33, Verse:14, Page:1, Kor:"사실은 하나님이 말씀을 하시고 또 하신다고 하더라도, 사람이 그 말씀에 주의를 기울이지 못할 뿐입니다.", Chn:"", Eng:"For God does speak--now one way, now another--though man may not perceive it.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:15, Page:1, Kor:"사람이 꿈을 꿀 때에, 밤의 환상을 볼 때에, 또는 깊은 잠에 빠질 때에, 침실에서 잠을 잘 때에,", Chn:"", Eng:"In a dream, in a vision of the night, when deep sleep falls on men as they slumber in their beds,", Ind:""},
  {Bible:"Job", Chapter:33, Verse:16, Page:1, Kor:"바로 그 때에, 하나님은 사람들의 귀를 여시고, 말씀을 듣게 하십니다. 사람들은 거기에서 경고를 받고, 두려워합니다.", Chn:"", Eng:"he may speak in their ears and terrify them with warnings,", Ind:""},
  {Bible:"Job", Chapter:33, Verse:17, Page:1, Kor:"하나님은 사람들이 죄를 짓지 않도록 하십니다. 교만하지 않도록 하십니다.", Chn:"", Eng:"to turn man from wrongdoing and keep him from pride,", Ind:""},
  {Bible:"Job", Chapter:33, Verse:18, Page:1, Kor:"하나님은 사람의 생명을 파멸에 빠지지 않도록 지켜 주시며, 사람의 목숨을 사망에서 건져 주십니다.", Chn:"", Eng:"to preserve his soul from the pit, his life from perishing by the sword.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:19, Page:1, Kor:"하나님은 사람에게 질병을 보내셔서 잘못을 고쳐 주기도 하시고, 사람의 육체를 고통스럽게 해서라도 잘못을 고쳐 주기도 하십니다.", Chn:"", Eng:"Or a man may be chastened on a bed of pain with constant distress in his bones,", Ind:""},
  {Bible:"Job", Chapter:33, Verse:20, Page:1, Kor:"그렇게 되면, 병든 사람은 입맛을 잃을 것입니다. 좋은 음식을 보고도 구역질만 할 것입니다.", Chn:"", Eng:"so that his very being finds food repulsive and his soul loathes the choicest meal.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:21, Page:1, Kor:"살이 빠져 몸이 바짝 마르고, 전에 보이지 않던 앙상한 뼈만 두드러질 것입니다.", Chn:"", Eng:"His flesh wastes away to nothing, and his bones, once hidden, now stick out.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:22, Page:1, Kor:"이제, 그의 목숨은 무덤에 다가서고, 그의 생명은 죽음의 문턱에 이르게 될 것입니다.", Chn:"", Eng:"His soul draws near to the pit, and his life to the messengers of death.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:23, Page:1, Kor:"그 때에 하나님의 천사 천 명 가운데서 한 명이 그를 도우러 올 것입니다. 그 천사는 사람들에게 사람이 마땅히 해야 할 일을 상기시킬 것입니다.", Chn:"", Eng:"\"Yet if there is an angel on his side as a mediator, one out of a thousand, to tell a man what is right for him,", Ind:""},
  {Bible:"Job", Chapter:33, Verse:24, Page:1, Kor:"하나님은 그에게 은혜를 베푸시고, 천사에게 말씀하실 것입니다. \"그가 무덤으로 내려가지 않도록, 그를 살려 주어라. 내가 그의 몸값을 받았다.", Chn:"", Eng:"to be gracious to him and say, 'Spare him from going down to the pit; I have found a ransom for him'--", Ind:""},
  {Bible:"Job", Chapter:33, Verse:25, Page:1, Kor:"그렇게 되면, 그는 다시 젊음을 되찾고, 건강도 되찾을 것입니다.", Chn:"", Eng:"then his flesh is renewed like a child's; it is restored as in the days of his youth.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:26, Page:1, Kor:"그가 하나님께 기도를 드리면, 하나님은 그에게 응답하여 주실 것입니다. 그는 기쁨으로 하나님을 섬기고, 하나님은 그를 다시 정상적으로 회복시켜 주실 것입니다.", Chn:"", Eng:"He prays to God and finds favor with him, he sees God's face and shouts for joy; he is restored by God to his righteous state.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:27, Page:1, Kor:"그는 사람들 앞에서 고백할 것입니다. \"나는 죄를 지어서, 옳은 일을 그르쳤으나, 하나님이 나를 용서하여 주셨습니다.", Chn:"", Eng:"Then he comes to men and says, 'I sinned, and perverted what was right, but I did not get what I deserved.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:28, Page:1, Kor:"하나님이 나를 무덤에 내려가지 않게 구원해 주셨기에, 이렇게 살아서 빛을 즐기게 되었습니다\" 하고 말할 것입니다.", Chn:"", Eng:"He redeemed my soul from going down to the pit, and I will live to enjoy the light.'", Ind:""},
  {Bible:"Job", Chapter:33, Verse:29, Page:1, Kor:"이 모두가 하나님이 하시는 일입니다. 하나님이 사람에게 두 번, 세 번, 이렇게 되풀이하시는 것은,", Chn:"", Eng:"\"God does all these things to a man--twice, even three times--", Ind:""},
  {Bible:"Job", Chapter:33, Verse:30, Page:1, Kor:"사람의 생명을 무덤에서 다시 끌어내셔서 생명의 빛을 보게 하시려는 것입니다.", Chn:"", Eng:"to turn back his soul from the pit, that the light of life may shine on him.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:31, Page:1, Kor:"어른은 귀를 기울여, 내 말을 들으십시오. 내가 말하는 동안은 조용히 듣기만 해주십시오.", Chn:"", Eng:"\"Pay attention, Job, and listen to me; be silent, and I will speak.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:32, Page:1, Kor:"그러나 하실 말씀이 있으시면, 내가 듣겠습니다. 서슴지 말고 말씀해 주십시오. 나는 어른이 옳으시다는 것을 드러내고 싶습니다.", Chn:"", Eng:"If you have anything to say, answer me; speak up, for I want you to be cleared.", Ind:""},
  {Bible:"Job", Chapter:33, Verse:33, Page:1, Kor:"그러나 하실 말씀이 없으시면, 조용히 들어 주시기만 바랍니다. 그러면 내가 어른께 지혜를 가르쳐 드리겠습니다.", Chn:"", Eng:"But if not, then listen to me; be silent, and I will teach you wisdom.\"", Ind:""},
]);
