// 욥기 3장 · Job 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",3,26);
BibleDB.add([
  {Bible:"Job", Chapter:3, Verse:1, Page:1,
    Kor:"<욥이 하나님께 불평하다> 드디어 욥이 말문을 열고, 자기 생일을 저주하면서",
    Chn:"此后，约伯开口咒诅自己的生日，",
    Eng:"After this, Job opened his mouth and cursed the day of his birth.",
    Ind:"Sesudah itu Ayub membuka mulutnya dan mengutuki hari kelahirannya."
  },
  {Bible:"Job", Chapter:3, Verse:2, Page:1,
    Kor:"울부짖었다.",
    Chn:"说：",
    Eng:"He said:",
    Ind:"Maka berbicaralah Ayub:"
  },
  {Bible:"Job", Chapter:3, Verse:3, Page:1,
    Kor:"내가 태어나던 날이 차라리 사라져 버렸더라면, '남자 아이를 배었다'고 좋아하던 그 밤도 망해 버렸더라면,",
    Chn:"愿我生的那日 和说怀了男胎的那夜都灭没。",
    Eng:"\"May the day of my birth perish, and the night it was said, 'A boy is born!'",
    Ind:"\"Biarlah hilang lenyap hari kelahiranku dan malam yang mengatakan: Seorang anak laki-laki telah ada dalam kandungan."
  },
  {Bible:"Job", Chapter:3, Verse:4, Page:1,
    Kor:"그 날이 어둠에 덮여서, 높은 곳에 계신 하나님께서도 그 날을 기억하지 못하셨더라면, 아예 그 날이 밝지도 않았더라면,",
    Chn:"愿那日变为黑暗； 愿　神不从上面寻找它； 愿亮光不照于其上。",
    Eng:"That day--may it turn to darkness; may God above not care about it; may no light shine upon it.",
    Ind:"Biarlah hari itu menjadi kegelapan, janganlah kiranya Allah yang di atas menghiraukannya, dan janganlah cahaya terang menyinarinya."
  },
  {Bible:"Job", Chapter:3, Verse:5, Page:1,
    Kor:"어둠과 a사망의 그늘이 그 날을 제 것이라 하여, 검은 구름이 그 날을 덮었더라면, 낮을 어둠으로 덮어서, 그 날을 공포 속에 몰아넣었더라면, (a 또는 '깊은 흑암')",
    Chn:"愿黑暗和死荫索取那日； 愿密云停在其上； 愿日蚀恐吓它。",
    Eng:"May darkness and deep shadow claim it once more; may a cloud settle over it; may blackness overwhelm its light.",
    Ind:"Biarlah kegelapan dan kekelaman menuntut hari itu, awan-gemawan menudunginya, dan gerhana matahari mengejutkannya."
  },
  {Bible:"Job", Chapter:3, Verse:6, Page:1,
    Kor:"그 밤도 흑암에 사로잡혔더라면, 그 밤이 아예 날 수와 달 수에도 들지 않았더라면,",
    Chn:"愿那夜被幽暗夺取， 不在年中的日子同乐， 也不入月中的数目。",
    Eng:"That night--may thick darkness seize it; may it not be included among the days of the year nor be entered in any of the months.",
    Ind:"Malam itu--biarlah dia dicekam oleh kegelapan; janganlah ia bersukaria pada hari-hari dalam setahun; janganlah ia termasuk bilangan bulan-bulan."
  },
  {Bible:"Job", Chapter:3, Verse:7, Page:1,
    Kor:"아, 그 밤이 아무도 잉태하지 못하는 밤이었더라면, 아무도 기쁨의 소리를 낼 수 없는 밤이었더라면,",
    Chn:"愿那夜没有生育， 其间也没有欢乐的声音。",
    Eng:"May that night be barren; may no shout of joy be heard in it.",
    Ind:"Ya, biarlah pada malam itu tidak ada yang melahirkan, dan tidak terdengar suara kegirangan."
  },
  {Bible:"Job", Chapter:3, Verse:8, Page:1,
    Kor:"주문을 외워서 b바다를 저주하는 자들이, c리워야단도 길들일 수 있는 마력을 가진 자들이, 그 날을 저주하였더라면, (b 또는 '날을 저주하는 자가' c 악어처럼 생긴 바다 괴물)",
    Chn:"愿那咒诅日子且能惹动鳄鱼的 咒诅那夜。",
    Eng:"May those who curse days curse that day, those who are ready to rouse Leviathan.",
    Ind:"Biarlah ia disumpahi oleh para pengutuk hari, oleh mereka yang pandai membangkitkan marah Lewiatan."
  },
  {Bible:"Job", Chapter:3, Verse:9, Page:1,
    Kor:"그 밤에는 새벽 별들도 빛을 잃어서, 날이 밝기를 기다려도 밝지를 않고, 동트는 것도 볼 수 없었더라면, 좋았을 것을!",
    Chn:"愿那夜黎明的星宿变为黑暗， 盼亮却不亮， 也不见早晨的光线；",
    Eng:"May its morning stars become dark; may it wait for daylight in vain and not see the first rays of dawn,",
    Ind:"Biarlah bintang-bintang senja menjadi gelap; biarlah ia menantikan terang yang tak kunjung datang, janganlah ia melihat merekahnya fajar,"
  },
  {Bible:"Job", Chapter:3, Verse:10, Page:1,
    Kor:"어머니의 태가 열리지 않아, 내가 태어나지 않았어야 하는 건데. 그래서 이 고난을 겪지 않아야 하는 건데!",
    Chn:"因没有把怀我胎的门关闭， 也没有将患难对我的眼隐藏。",
    Eng:"for it did not shut the doors of the womb on me to hide trouble from my eyes.",
    Ind:"karena tidak ditutupnya pintu kandungan ibuku, dan tidak disembunyikannya kesusahan dari mataku."
  },
  {Bible:"Job", Chapter:3, Verse:11, Page:1,
    Kor:"어찌하여 내가 모태에서 죽지 않았던가? 어찌하여 어머니 배에서 나오는 그 순간에 숨이 끊어지지 않았던가?",
    Chn:"我为何不出母胎而死？ 为何不出母腹绝气？",
    Eng:"\"Why did I not perish at birth, and die as I came from the womb?",
    Ind:"Mengapa aku tidak mati waktu aku lahir, atau binasa waktu aku keluar dari kandungan?"
  },
  {Bible:"Job", Chapter:3, Verse:12, Page:1,
    Kor:"어찌하여 나를 무릎으로 받았으며, 어찌하여 어머니가 나를 품에 안고 젖을 물렸던가?",
    Chn:"为何有膝接收我？ 为何有奶哺养我？",
    Eng:"Why were there knees to receive me and breasts that I might be nursed?",
    Ind:"Mengapa pangkuan menerima aku; mengapa ada buah dada, sehingga aku dapat menyusu?"
  },
  {Bible:"Job", Chapter:3, Verse:13, Page:1,
    Kor:"그렇게만 하지 않았더라도, 지금쯤은 내가 편히 누워서 잠들어 쉬고 있을 텐데.",
    Chn:"不然，我就早已躺卧安睡，",
    Eng:"For now I would be lying down in peace; I would be asleep and at rest",
    Ind:"Jikalau tidak, aku sekarang berbaring dan tenang; aku tertidur dan mendapat istirahat"
  },
  {Bible:"Job", Chapter:3, Verse:14, Page:1,
    Kor:"지금은 폐허가 된 성읍이지만, 한때 그 성읍을 세우던 세상의 왕들과 고관들과 함께 잠들어 있을 텐데.",
    Chn:"和地上为自己重造荒邱的君王、谋士，",
    Eng:"with kings and counselors of the earth, who built for themselves places now lying in ruins,",
    Ind:"bersama-sama raja-raja dan penasihat-penasihat di bumi, yang mendirikan kembali reruntuhan bagi dirinya,"
  },
  {Bible:"Job", Chapter:3, Verse:15, Page:1,
    Kor:"금과 은으로 집을 가득 채운 그 통치자들과 함께 잠들어 있을 텐데.",
    Chn:"或与有金子、将银子装满了房屋的王子 一同安息；",
    Eng:"with rulers who had gold, who filled their houses with silver.",
    Ind:"atau bersama-sama pembesar-pembesar yang mempunyai emas, yang memenuhi rumahnya dengan perak."
  },
  {Bible:"Job", Chapter:3, Verse:16, Page:1,
    Kor:"낙태된 핏덩이처럼, 살아 있지도 않을 텐데. 햇빛도 못 본 핏덩이처럼 되었을 텐데!",
    Chn:"或像隐而未现、不到期而落的胎， 归于无有，如同未见光的婴孩。",
    Eng:"Or why was I not hidden in the ground like a stillborn child, like an infant who never saw the light of day?",
    Ind:"Atau mengapa aku tidak seperti anak gugur yang disembunyikan, seperti bayi yang tidak melihat terang?"
  },
  {Bible:"Job", Chapter:3, Verse:17, Page:1,
    Kor:"그 곳은 악한 사람들도 더 이상 소란을 피우지 못하고, 삶에 지친 사람들도 쉴 수 있는 곳인데.",
    Chn:"在那里恶人止息搅扰， 困乏人得享安息，",
    Eng:"There the wicked cease from turmoil, and there the weary are at rest.",
    Ind:"Di sanalah orang fasik berhenti menimbulkan huru-hara, di sanalah mereka yang kehabisan tenaga mendapat istirahat."
  },
  {Bible:"Job", Chapter:3, Verse:18, Page:1,
    Kor:"그 곳은 갇힌 사람들도 함께 평화를 누리고, 노예를 부리는 감독관의 소리도 들리지 않는 곳인데.",
    Chn:"被囚的人同得安逸， 不听见督工的声音。",
    Eng:"Captives also enjoy their ease; they no longer hear the slave driver's shout.",
    Ind:"Dan para tawanan bersama-sama menjadi tenang, mereka tidak lagi mendengar suara pengerah."
  },
  {Bible:"Job", Chapter:3, Verse:19, Page:1,
    Kor:"그 곳은 낮은 자와 높은 자의 구별이 없고, 종까지도 주인에게서 자유를 얻는 곳인데!",
    Chn:"大小都在那里； 奴仆脱离主人的辖制。",
    Eng:"The small and the great are there, and the slave is freed from his master.",
    Ind:"Di sana orang kecil dan orang besar sama, dan budak bebas dari pada tuannya."
  },
  {Bible:"Job", Chapter:3, Verse:20, Page:1,
    Kor:"어찌하여 하나님은, 고난당하는 자들을 태어나게 하셔서 빛을 보게 하시고, 이렇게 쓰디쓴 인생을 살아가는 자들에게 생명을 주시는가?",
    Chn:"受患难的人为何有光赐给他呢？ 心中愁苦的人为何有生命赐给他呢？",
    Eng:"\"Why is light given to those in misery, and life to the bitter of soul,",
    Ind:"Mengapa terang diberikan kepada yang bersusah-susah, dan hidup kepada yang pedih hati;"
  },
  {Bible:"Job", Chapter:3, Verse:21, Page:1,
    Kor:"이런 사람들은 죽기를 기다려도 죽음이 찾아와 주지 않는다. 그들은 보물을 찾기보다는 죽기를 더 바라다가",
    Chn:"他们切望死，却不得死； 求死，胜于求隐藏的珍宝。",
    Eng:"to those who long for death that does not come, who search for it more than for hidden treasure,",
    Ind:"yang menantikan maut, yang tak kunjung tiba, yang mengejarnya lebih dari pada menggali harta terpendam;"
  },
  {Bible:"Job", Chapter:3, Verse:22, Page:1,
    Kor:"무덤이라도 찾으면 기뻐서 어쩔 줄 모르는데,",
    Chn:"他们寻见坟墓就快乐， 极其欢喜。",
    Eng:"who are filled with gladness and rejoice when they reach the grave?",
    Ind:"yang bersukaria dan bersorak-sorai dan senang, bila mereka menemukan kubur;"
  },
  {Bible:"Job", Chapter:3, Verse:23, Page:1,
    Kor:"어찌하여 하나님은 길 잃은 사람을 붙잡아 놓으시고, 사방으로 그 길을 막으시는가?",
    Chn:"人的道路既然遮隐， 　神又把他四面围困， 为何有光赐给他呢？",
    Eng:"Why is life given to a man whose way is hidden, whom God has hedged in?",
    Ind:"kepada orang laki-laki yang jalannya tersembunyi, yang dikepung Allah?"
  },
  {Bible:"Job", Chapter:3, Verse:24, Page:1,
    Kor:"밥을 앞에 놓고서도, 나오느니 탄식이요, 신음 소리 그칠 날이 없다.",
    Chn:"我未曾吃饭就发出叹息； 我唉哼的声音涌出如水。",
    Eng:"For sighing comes to me instead of food; my groans pour out like water.",
    Ind:"Karena ganti rotiku adalah keluh kesahku, dan keluhanku tercurah seperti air."
  },
  {Bible:"Job", Chapter:3, Verse:25, Page:1,
    Kor:"마침내 그렇게도 두려워하던 일이 밀어닥치고, 그렇게도 무서워하던 일이 다가오고야 말았다.",
    Chn:"因我所恐惧的临到我身， 我所惧怕的迎我而来。",
    Eng:"What I feared has come upon me; what I dreaded has happened to me.",
    Ind:"Karena yang kutakutkan, itulah yang menimpa aku, dan yang kucemaskan, itulah yang mendatangi aku."
  },
  {Bible:"Job", Chapter:3, Verse:26, Page:1,
    Kor:"내게는 평화도 없고, 안정도 없고, 안식마저 사라지고, 두려움만 끝없이 밀려온다!",
    Chn:"我不得安逸，不得平静， 也不得安息，却有患难来到。",
    Eng:"I have no peace, no quietness; I have no rest, but only turmoil.\"",
    Ind:"Aku tidak mendapat ketenangan dan ketenteraman; aku tidak mendapat istirahat, tetapi kegelisahanlah yang timbul.\""
  },
]);
