// 욥기 42장 · Job 42
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",42,17);
BibleDB.add([
  {Bible:"Job", Chapter:42, Verse:1, Page:1, Kor:"<욥의 회개> 욥이 주님께 대답하였다.", Chn:"", Eng:"Then Job replied to the LORD:", Ind:""},
  {Bible:"Job", Chapter:42, Verse:2, Page:1, Kor:"주님께서는 못하시는 일이 없으시다는 것을, 이제 저는 알았습니다. 주님의 계획은 어김없이 이루어진다는 것도, 저는 깨달았습니다.", Chn:"", Eng:"\"I know that you can do all things; no plan of yours can be thwarted.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:3, Page:1, Kor:"잘 알지도 못하면서, 감히 주님의 뜻을 흐려 놓으려 한 자가 바로 저입니다. 깨닫지도 못하면서, 함부로 말을 하였습니다. 제가 알기에는, 너무나 신기한 일들이었습니다.", Chn:"", Eng:"You asked, 'Who is this that obscures my counsel without knowledge?' Surely I spoke of things I did not understand, things too wonderful for me to know.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:4, Page:1, Kor:"주님께서 말씀하셨습니다. \"들어라. 내가 말하겠다. 내가 물을 터이니, 내게 대답하여라\" 하셨습니다.", Chn:"", Eng:"\"You said, 'Listen now, and I will speak; I will question you, and you shall answer me.'", Ind:""},
  {Bible:"Job", Chapter:42, Verse:5, Page:1, Kor:"주님이 어떤 분이시라는 것을, 지금까지는 제가 귀로만 들었습니다. 그러나 이제는 제가 제 눈으로 주님을 뵙습니다.", Chn:"", Eng:"My ears had heard of you but now my eyes have seen you.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:6, Page:1, Kor:"그러므로 저는 제 주장을 거두어들이고, 티끌과 잿더미 위에 앉아서 회개합니다.", Chn:"", Eng:"Therefore I despise myself and repent in dust and ashes.\"", Ind:""},
  {Bible:"Job", Chapter:42, Verse:7, Page:1, Kor:"<결론> ○주님께서는 욥에게 말씀을 마치신 다음에, 데만 사람 엘리바스에게 이렇게 말씀하셨다. \"내가 너와 네 두 친구에게 분노한 것은, 너희가 나를 두고 말을 할 때에, 내 종 욥처럼 옳게 말하지 못하였기 때문이다.", Chn:"", Eng:"After the LORD had said these things to Job, he said to Eliphaz the Temanite, \"I am angry with you and your two friends, because you have not spoken of me what is right, as my servant Job has.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:8, Page:1, Kor:"그러므로 이제 너희는, 수송아지 일곱 마리와 숫양 일곱 마리를 마련하여, 내 종 욥에게 가지고 가서, 너희가 용서받을 수 있도록 번제를 드려라. 내 종 욥이 너희를 용서하여 달라고 빌면, 내가 그의 기도를 들어줄 것이다. 너희가 나를 두고 말을 할 때에, 내 종 욥처럼 옳게 말하지 않고, 어리석게 말하였지만, 내가 그대로 갚지는 않을 것이다.\"", Chn:"", Eng:"So now take seven bulls and seven rams and go to my servant Job and sacrifice a burnt offering for yourselves. My servant Job will pray for you, and I will accept his prayer and not deal with you according to your folly. You have not spoken of me what is right, as my servant Job has.\"", Ind:""},
  {Bible:"Job", Chapter:42, Verse:9, Page:1, Kor:"그래서 데만 사람 엘리바스와 수아 사람 빌닷과 나아마 사람 소발이 가서, 주님께서 그들에게 말씀하신 대로 하니, 주님께서 욥의 기도를 들어주셨다.", Chn:"", Eng:"So Eliphaz the Temanite, Bildad the Shuhite and Zophar the Naamathite did what the LORD told them; and the LORD accepted Job's prayer.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:10, Page:1, Kor:"<주님께서 욥에게 복을 주심> ○욥이 주님께, 자기 친구들을 용서해 달라고 기도를 드리고 난 다음에, 주님께서 욥의 재산을 회복시켜 주셨는데, 욥이 이전에 가졌던 모든 것보다 배나 더 돌려주셨다.", Chn:"", Eng:"After Job had prayed for his friends, the LORD made him prosperous again and gave him twice as much as he had before.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:11, Page:1, Kor:"그러자 그의 모든 형제와 자매와 전부터 그를 아는 친구들이 다 그를 찾아와, 그의 집에서 그와 함께 기뻐하면서, 먹고 마셨다. 그들은 주님께서 그에게 내리신 그 모든 재앙을 생각하면서, 그를 동정하기도 하고, 또 위로하기도 하였다. 그러면서 그들은 저마다, 그에게 돈을 주기도 하고, 금반지를 끼워 주기도 하였다.", Chn:"", Eng:"All his brothers and sisters and everyone who had known him before came and ate with him in his house. They comforted and consoled him over all the trouble the LORD had brought upon him, and each one gave him a piece of silver and a gold ring.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:12, Page:1, Kor:"주님께서 욥의 말년에 이전보다 더 많은 복을 주셔서, 욥이, 양을 만 사천 마리, 낙타를 육천 마리, 소를 천 겨리, 나귀를 천 마리나 거느리게 하셨다.", Chn:"", Eng:"The LORD blessed the latter part of Job's life more than the first. He had fourteen thousand sheep, six thousand camels, a thousand yoke of oxen and a thousand donkeys.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:13, Page:1, Kor:"그리고 그는 아들 일곱과 딸 셋을 낳았다.", Chn:"", Eng:"And he also had seven sons and three daughters.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:14, Page:1, Kor:"첫째 딸은 a여미마, 둘째 딸은 b긋시아, 셋째 딸은 c게렌합북이라고 불렀다.(a '비둘기' b '계피 향' c 화장도구, 특히 눈화장에 사용)", Chn:"", Eng:"The first daughter he named Jemimah, the second Keziah and the third Keren-Happuch.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:15, Page:1, Kor:"땅 위의 어디에서도 욥의 딸들처럼 아리따운 여자를 찾아볼 수 없었다. 더욱이 그들의 아버지는, 오라비들에게 준 것과 똑같이, 딸들에게도 유산을 물려주었다.", Chn:"", Eng:"Nowhere in all the land were there found women as beautiful as Job's daughters, and their father granted them an inheritance along with their brothers.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:16, Page:1, Kor:"○그 뒤에 욥은 d백사십 년을 살면서, 그의 아들과 손자 사 대를 보았다.(d 칠십인역에는 '이백사십 년')", Chn:"", Eng:"After this, Job lived a hundred and forty years; he saw his children and their children to the fourth generation.", Ind:""},
  {Bible:"Job", Chapter:42, Verse:17, Page:1, Kor:"욥은 이렇게 오래 살다가 세상을 떠났다.", Chn:"", Eng:"", Ind:""},
]);
