// 욥기 31장 · Job 31
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Job",31,40);
BibleDB.add([
  {Bible:"Job", Chapter:31, Verse:1, Page:1, Kor:"젊은 여인을 음탕한 눈으로 바라보지 않겠다고 나 스스로 엄격하게 다짐하였다.", Chn:"", Eng:"\"I made a covenant with my eyes not to look lustfully at a girl.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:2, Page:1, Kor:"여자나 유혹하고 다니면, 위에 계신 하나님이 내게 주실 몫이 무엇이겠으며, 높은 곳에 계신 a전능하신 분께서 내게 주실 유산은 무엇이겠는가? (a 히, '샤다이')", Chn:"", Eng:"For what is man's lot from God above, his heritage from the Almighty on high?", Ind:""},
  {Bible:"Job", Chapter:31, Verse:3, Page:1, Kor:"불의한 자에게는 불행이 미치고, 악한 일을 하는 자에게는 재앙이 닥치는 법이 아닌가?", Chn:"", Eng:"Is it not ruin for the wicked, disaster for those who do wrong?", Ind:""},
  {Bible:"Job", Chapter:31, Verse:4, Page:1, Kor:"하나님은 내가 하는 일을 낱낱이 알고 계신다. 내 모든 발걸음을 하나하나 세고 계신다.", Chn:"", Eng:"Does he not see my ways and count my every step?", Ind:""},
  {Bible:"Job", Chapter:31, Verse:5, Page:1, Kor:"나는 맹세할 수 있다. 여태까지 나는 악한 일을 하지 않았다. 다른 사람을 속이려고도 하지 않았다.", Chn:"", Eng:"\"If I have walked in falsehood or my foot has hurried after deceit--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:6, Page:1, Kor:"하나님이 내 정직함을 공평한 저울로 달아 보신다면, 내게 흠이 없음을 아실 것이다.", Chn:"", Eng:"let God weigh me in honest scales and he will know that I am blameless--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:7, Page:1, Kor:"내가 그릇된 길로 갔거나, 나 스스로 악에 이끌리어 따라갔거나, 내 손에 죄를 지은 흔적이라도 있다면,", Chn:"", Eng:"if my steps have turned from the path, if my heart has been led by my eyes, or if my hands have been defiled,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:8, Page:1, Kor:"내가 심은 것을 다른 사람이 거두어 먹어도, 내가 지은 농사가 망하더라도, 나는 할 말이 없을 것이다.", Chn:"", Eng:"then may others eat what I have sown, and may my crops be uprooted.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:9, Page:1, Kor:"남의 아내를 탐내서, 그 집 문 근처에 숨어 있으면서 그 여인을 범할 기회를 노렸다면,", Chn:"", Eng:"\"If my heart has been enticed by a woman, or if I have lurked at my neighbor's door,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:10, Page:1, Kor:"내 아내가 다른 남자의 노예가 되거나, 다른 남자의 품에 안긴다 해도, 나는 할 말이 없을 것이다.", Chn:"", Eng:"then may my wife grind another man's grain, and may other men sleep with her.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:11, Page:1, Kor:"남의 아내를 범하는 것은, 사형선고를 받아야 마땅한 범죄다.", Chn:"", Eng:"For that would have been shameful, a sin to be judged.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:12, Page:1, Kor:"그것은 사람을 b파멸시키는 불, 사람이 애써서 모은 재산을 다 태우는 불이다. (b 히, '아바돈')", Chn:"", Eng:"It is a fire that burns to Destruction; it would have uprooted my harvest.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:13, Page:1, Kor:"내 남종이나 여종이 내게 탄원을 하여 올 때마다, 나는 그들이 하는 말에 귀를 기울이고, 공평하게 처리하였다.", Chn:"", Eng:"\"If I have denied justice to my menservants and maidservants when they had a grievance against me,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:14, Page:1, Kor:"그렇게 하지 않았더라면, 내가 무슨 낯으로 하나님을 뵈며, 하나님이 나를 심판하러 오실 때에, 내가 무슨 말로 변명하겠는가?", Chn:"", Eng:"what will I do when God confronts me? What will I answer when called to account?", Ind:""},
  {Bible:"Job", Chapter:31, Verse:15, Page:1, Kor:"나를 창조하신 바로 그 하나님이 내 종들도 창조하셨다.", Chn:"", Eng:"Did not he who made me in the womb make them? Did not the same one form us both within our mothers?", Ind:""},
  {Bible:"Job", Chapter:31, Verse:16, Page:1, Kor:"가난한 사람들이 도와 달라고 할 때에, 나는 거절한 일이 없다. 앞길이 막막한 과부를 못 본 체 한 일도 없다.", Chn:"", Eng:"\"If I have denied the desires of the poor or let the eyes of the widow grow weary,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:17, Page:1, Kor:"나는 배부르게 먹으면서 고아를 굶긴 일도 없다.", Chn:"", Eng:"if I have kept my bread to myself, not sharing it with the fatherless--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:18, Page:1, Kor:"일찍부터 나는 고아를 내 아이처럼 길렀으며, 철이 나서는 줄곧 과부들을 돌보았다.", Chn:"", Eng:"but from my youth I reared him as would a father, and from my birth I guided the widow--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:19, Page:1, Kor:"너무나도 가난하여 옷도 걸치지 못하고 죽어 가는 사람이나, 덮고 잘 것이 없는 가난한 사람을 볼 때마다,", Chn:"", Eng:"if I have seen anyone perishing for lack of clothing, or a needy man without a garment,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:20, Page:1, Kor:"내가 기른 양 털을 깎아서, 그것으로 옷을 만들어 그들에게 입혔다. 시린 허리를 따뜻하게 해주었더니, 그들이 나를 진심으로 축복하곤 하였다.", Chn:"", Eng:"and his heart did not bless me for warming him with the fleece from my sheep,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:21, Page:1, Kor:"내가 재판에서 이길 것이라고 생각하고, 고아를 속이기라도 하였더라면,", Chn:"", Eng:"if I have raised my hand against the fatherless, knowing that I had influence in court,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:22, Page:1, Kor:"내 팔이 부러져도 할 말이 없다. 내 팔이 어깻죽지에서 빠져 나와도 할 말이 없다.", Chn:"", Eng:"then let my arm fall from the shoulder, let it be broken off at the joint.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:23, Page:1, Kor:"하나님이 내리시는 심판이 얼마나 무서운지를 잘 알고 있었으므로, 나는 차마 그런 파렴치한 짓은 할 수 없었다.", Chn:"", Eng:"For I dreaded destruction from God, and for fear of his splendor I could not do such things.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:24, Page:1, Kor:"나는 황금을 믿지도 않고, 정금을 의지하지도 않았다.", Chn:"", Eng:"\"If I have put my trust in gold or said to pure gold, 'You are my security,'", Ind:""},
  {Bible:"Job", Chapter:31, Verse:25, Page:1, Kor:"내가 재산이 많다고 하여 자랑하지도 않고, 벌어들인 것이 많다고 하여 기뻐하지도 않았다.", Chn:"", Eng:"if I have rejoiced over my great wealth, the fortune my hands had gained,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:26, Page:1, Kor:"해가 찬란한 빛을 낸다고 하여, 해를 섬기지도 않고, 달이 밝고 아름답다고 하여, 달을 섬기지도 않았다.", Chn:"", Eng:"if I have regarded the sun in its radiance or the moon moving in splendor,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:27, Page:1, Kor:"해와 달을 보고, 그 장엄함과 아름다움에 반하여 그것에다가 절을 하는 사람들이 있다. 해와 달을 경배하는 표시로 제 손에 입을 맞추기도 한다. 그러나 나는 그렇게 하지 않았다.", Chn:"", Eng:"so that my heart was secretly enticed and my hand offered them a kiss of homage,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:28, Page:1, Kor:"그런 일은 높이 계신 하나님을 부인하는 것이므로, 벌로 사형을 받아도 마땅하다.", Chn:"", Eng:"then these also would be sins to be judged, for I would have been unfaithful to God on high.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:29, Page:1, Kor:"내 원수가 고통받는 것을 보고, 나는 기뻐한 적이 없다. 원수가 재난을 당할 때에도, 나는 기뻐하지 않았다.", Chn:"", Eng:"\"If I have rejoiced at my enemy's misfortune or gloated over the trouble that came to him--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:30, Page:1, Kor:"나는 결코 원수들이 죽기를 바라는 기도를 하여 죄를 범한 적이 없다.", Chn:"", Eng:"I have not allowed my mouth to sin by invoking a curse against his life--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:31, Page:1, Kor:"내 집에서 일하는 사람은 모두, 내가 언제나 나그네를 기꺼이 영접한다는 것을 잘 알고 있다.", Chn:"", Eng:"if the men of my household have never said, 'Who has not had his fill of Job's meat?'--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:32, Page:1, Kor:"나는 나그네가 길거리에서 잠자도록 내버려 둔 적이 없으며, 길손에게 내 집 문을 기꺼이 열어 주지 않은 적도 없다.", Chn:"", Eng:"but no stranger had to spend the night in the street, for my door was always open to the traveler--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:33, Page:1, Kor:"다른 사람들은 자기 죄를 감추려고 하지만, 그러나 나는 내 허물을 아주 감추지 않았다.", Chn:"", Eng:"if I have concealed my sin as men do, by hiding my guilt in my heart", Ind:""},
  {Bible:"Job", Chapter:31, Verse:34, Page:1, Kor:"c사람들이 무슨 말로 나를 헐뜯든지, 나는 그것을 전혀 두려워하지 않았다. 남에게서 비웃음을 받을까 하여, 입을 다물거나 집 안에서만 머무르거나 하지도 않았다. (c 히, '아담이 하였듯이')", Chn:"", Eng:"because I so feared the crowd and so dreaded the contempt of the clans that I kept silent and would not go outside", Ind:""},
  {Bible:"Job", Chapter:31, Verse:35, Page:1, Kor:"내가 한 이 변명을 들어줄 사람이 없을까? 맹세코 나는 사실대로만 말하였다. 이제는, a전능하신 분께서 말씀하시는 대답을 듣고 싶다. (a 히, '샤다이')", Chn:"", Eng:"(\"Oh, that I had someone to hear me! I sign now my defense--let the Almighty answer me; let my accuser put his indictment in writing.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:36, Page:1, Kor:"내 원수가 나를 고발하면서, 뭐라고 말하였지? 내가 저지른 죄과를 기록한 소송장이라도 있어서, 내가 읽어 볼 수만 있다면, 나는 그것을 자랑스럽게 어깨에 메고 다니고, 그것을 왕관처럼 머리에 얹고 다니겠다.", Chn:"", Eng:"Surely I would wear it on my shoulder, I would put it on like a crown.", Ind:""},
  {Bible:"Job", Chapter:31, Verse:37, Page:1, Kor:"나는, 내가 한 모든 일을 그분께 낱낱이 말씀드리고 나서, 그분 앞에 떳떳이 서겠다.", Chn:"", Eng:"I would give him an account of my every step; like a prince I would approach him.)--", Ind:""},
  {Bible:"Job", Chapter:31, Verse:38, Page:1, Kor:"내가 가꾼 땅이 훔친 것이라면, 땅 주인에게서 부당하게 빼앗은 것이라면,", Chn:"", Eng:"\"if my land cries out against me and all its furrows are wet with tears,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:39, Page:1, Kor:"땅에서 나는 소산을 공짜로 먹으면서 곡식을 기른 농부를 굶겨 죽였다면,", Chn:"", Eng:"if I have devoured its yield without payment or broken the spirit of its tenants,", Ind:""},
  {Bible:"Job", Chapter:31, Verse:40, Page:1, Kor:"내 밭에서 밀 대신 찔레가 나거나 보리 대신 잡초가 돋아나더라도, 나는 기꺼이 받겠다. ○이것으로 욥의 말이 모두 끝났다.", Chn:"", Eng:"then let briers come up instead of wheat and weeds instead of barley.\" The words of Job are ended.", Ind:""},
]);
