// 느헤미야 9장 · Nehemiah 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Nehemiah",9,38);
BibleDB.add([
  {Bible:"Nehemiah", Chapter:9, Verse:1, Page:1,
    Kor:"<백성들이 죄를 뉘우치다> 그 달 이십사일에, 이스라엘 자손이 다 모여서 금식하면서, 굵은 베 옷을 입고, 먼지를 뒤집어썼다.",
    Chn:"这月二十四日，以色列人聚集禁食，身穿麻衣，头蒙灰尘。",
    Eng:"On the twenty-fourth day of the same month, the Israelites gathered together, fasting and wearing sackcloth and having dust on their heads.",
    Ind:"Pada hari yang kedua puluh empat bulan itu berkumpullah orang Israel dan berpuasa dengan mengenakan kain kabung dan dengan tanah di kepala."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:2, Page:1,
    Kor:"이스라엘 자손은 모든 이방 사람과 관계를 끊었다. 그들은 제자리에 선 채로 자신들의 허물과 조상의 죄를 자백하였다.",
    Chn:"以色列人就与一切外邦人离绝，站着承认自己的罪恶和列祖的罪孽。",
    Eng:"Those of Israelite descent had separated themselves from all foreigners. They stood in their places and confessed their sins and the wickedness of their fathers.",
    Ind:"Keturunan orang Israel memisahkan diri dari semua orang asing, lalu berdiri di tempatnya dan mengaku dosa mereka dan kesalahan nenek moyang mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:3, Page:1,
    Kor:"모두들 제자리에서 일어나서, 낮의 사분의 일은 주 하나님의 율법책을 읽고, 또 낮의 사분의 일은 자기들의 죄를 자백하고, 주 하나님께 경배하였다.",
    Chn:"那日的四分之一站在自己的地方念耶和华—他们　神的律法书，又四分之一认罪，敬拜耶和华—他们的　神。",
    Eng:"They stood where they were and read from the Book of the Law of the LORD their God for a quarter of the day, and spent another quarter in confession and in worshiping the LORD their God.",
    Ind:"Sementara mereka berdiri di tempat, dibacakanlah bagian-bagian dari pada kitab Taurat TUHAN, Allah mereka, selama seperempat hari, sedang seperempat hari lagi mereka mengucapkan pengakuan dan sujud menyembah kepada TUHAN, Allah mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:4, Page:1,
    Kor:"단 위에는 레위 사람인 예수아와 바니와 갓미엘과 스바냐와 분니와 세레뱌와 바니와 그나니가 올라서서, 주 하나님께 큰소리로 부르짖었다.",
    Chn:"耶书亚、巴尼、甲篾、示巴尼、布尼、示利比、巴尼、基拿尼站在利未人的台上，大声哀求耶和华—他们的　神。",
    Eng:"Standing on the stairs were the Levites--Jeshua, Bani, Kadmiel, Shebaniah, Bunni, Sherebiah, Bani and Kenani--who called with loud voices to the LORD their God.",
    Ind:"Di atas tangga tempat orang-orang Lewi berdirilah Yesua, Bani, Kadmiel, Sebanya, Buni, Serebya, Bani dan Kenani. Dengan suara yang nyaring mereka berseru kepada TUHAN, Allah mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:5, Page:1,
    Kor:"○레위 사람인 예수아와 갓미엘과 바니와 하삽느야와 세레뱌와 호디야와 스바냐와 브다히야가 외쳤다. ○\"모두 일어나서, 주 너희의 하나님을 찬양하여라.\" <죄를 자백하는 기도> ○영원 전부터 영원까지, 주님의 영화로운 이름은 찬양을 받아 마땅합니다. 어떠한 찬양이나 송축으로도, 주님의 이름을 다 기릴 수가 없습니다.",
    Chn:"利未人耶书亚、甲篾、巴尼、哈沙尼、示利比、荷第雅、示巴尼、毗他希雅说：「你们要站起来称颂耶和华—你们的　神，永世无尽。耶和华啊，你荣耀之名是应当称颂的！超乎一切称颂和赞美。」",
    Eng:"And the Levites--Jeshua, Kadmiel, Bani, Hashabneiah, Sherebiah, Hodiah, Shebaniah and Pethahiah--said: \"Stand up and praise the LORD your God, who is from everlasting to everlasting.\" \"Blessed be your glorious name, and may it be exalted above all blessing and praise.",
    Ind:"Dan berkatalah Yesua, Kadmiel, Bani, Hasabneya, Serebya, Hodia, Sebanya dan Petahya, orang-orang Lewi itu: \"Bangunlah, pujilah TUHAN Allahmu dari selama-lamanya sampai selama-lamanya! Terpujilah nama-Mu yang mulia, yang ditinggikan mengatasi segala puji dan hormat!\""
  },
  {Bible:"Nehemiah", Chapter:9, Verse:6, Page:1,
    Kor:"주님만이 홀로 우리의 주님이십니다. 주님께서는 하늘과, 하늘 위의 하늘과, 거기에 딸린 별들을 지으셨습니다. 땅과 그 위에 있는 온갖 것, 바다와 그 안에 있는 온갖 것들을 지으셨습니다. 주님께서는 이 모든 것에게 생명을 주십니다. 하늘의 별들이 주님께 경배합니다.",
    Chn:"「你，惟独你是耶和华！你造了天和天上的天，并天上的万象，地和地上的万物，海和海中所有的；这一切都是你所保存的。天军也都敬拜你。",
    Eng:"You alone are the LORD. You made the heavens, even the highest heavens, and all their starry host, the earth and all that is on it, the seas and all that is in them. You give life to everything, and the multitudes of heaven worship you.",
    Ind:"\"Hanya Engkau adalah TUHAN! Engkau telah menjadikan langit, ya langit segala langit dengan segala bala tentaranya, dan bumi dengan segala yang ada di atasnya, dan laut dengan segala yang ada di dalamnya. Engkau memberi hidup kepada semuanya itu dan bala tentara langit sujud menyembah kepada-Mu."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:7, Page:1,
    Kor:"주 하나님께서는, 아브람을 택하시어 바빌로니아의 우르에서 이끌어 내시고, 그의 이름을 아브라함이라고 고쳐서 부르셨습니다.",
    Chn:"你是耶和华　神，曾拣选亚伯兰，领他出迦勒底的吾珥，给他改名叫亚伯拉罕。",
    Eng:"\"You are the LORD God, who chose Abram and brought him out of Ur of the Chaldeans and named him Abraham.",
    Ind:"Engkaulah TUHAN, Allah yang telah memilih Abram dan membawanya keluar dari Ur-Kasdim dan memberikan kepadanya nama Abraham."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:8, Page:1,
    Kor:"아브라함의 마음이 주님 앞에서 진실함을 아시고, 가나안 사람과 헷 사람과 아모리 사람과 브리스 사람과 여부스 사람과 기르가스 사람의 땅을 그 자손에게 주시겠다고, 그와 언약을 세우셨습니다. 주님께서는 의로우셔서, 말씀하신 것을 지키셨습니다.",
    Chn:"你见他在你面前心里诚实，就与他立约，应许把迦南人、赫人、亚摩利人、比利洗人、耶布斯人、革迦撒人之地赐给他的后裔，且应验了你的话，因为你是公义的。",
    Eng:"You found his heart faithful to you, and you made a covenant with him to give to his descendants the land of the Canaanites, Hittites, Amorites, Perizzites, Jebusites and Girgashites. You have kept your promise because you are righteous.",
    Ind:"Engkau dapati bahwa hatinya setia terhadap-Mu dan Engkau mengikat perjanjian dengan dia untuk memberikan tanah orang Kanaan, tanah orang Het, tanah orang Amori, tanah orang Feris, tanah orang Yebus dan tanah orang Girgasi kepada keturunannya. Dan Engkau telah menepati janji-Mu, karena Engkau benar."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:9, Page:1,
    Kor:"○주님께서는 우리 조상이 이집트에서 고난받는 것을 보시고, 홍해에서 부르짖을 때에 들어주셨습니다.",
    Chn:"「你曾看见我们列祖在埃及所受的困苦，垂听他们在红海边的哀求，",
    Eng:"\"You saw the suffering of our forefathers in Egypt; you heard their cry at the Red Sea.",
    Ind:"Engkau melihat sengsara nenek moyang kami di Mesir dan mendengar teriakan mereka di tepi Laut Teberau."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:10, Page:1,
    Kor:"이집트 사람들이 우리 조상을 업신여기는 것을 아시고, 이적과 기사를 베푸셔서, 바로와 그의 모든 신하와 그 나라 온 백성을 치셨으며, 그 때에 떨치신 명성이 오늘까지 이릅니다.",
    Chn:"就施行神迹奇事在法老和他一切臣仆，并他国中的众民身上。你也得了名声，正如今日一样，因为你知道他们向我们列祖行事狂傲。",
    Eng:"You sent miraculous signs and wonders against Pharaoh, against all his officials and all the people of his land, for you knew how arrogantly the Egyptians treated them. You made a name for yourself, which remains to this day.",
    Ind:"Engkau telah memperlihatkan tanda-tanda dan mujizat-mujizat di depan Firaun dan semua pegawainya serta seluruh rakyat negerinya, karena Engkau mengetahui mereka bertindak angkuh terhadap nenek moyang kami. Dengan demikian Engkau telah memasyhurkan nama-Mu sebagaimana nyata hari ini."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:11, Page:1,
    Kor:"조상 앞에서 바다를 가르시고, 그들이 바다 한가운데를 마른 땅처럼 지나가게 하셨지만, 뒤쫓는 자들은, 깊은 바다에 돌이 잠기듯이, 거센 물결에 잠기게 하셨습니다.",
    Chn:"你又在我们列祖面前把海分开，使他们在海中行走干地，将追赶他们的人抛在深海，如石头抛在大水中；",
    Eng:"You divided the sea before them, so that they passed through it on dry ground, but you hurled their pursuers into the depths, like a stone into mighty waters.",
    Ind:"Di hadapan mereka Engkau membelah laut, sehingga mereka dapat menyeberang melalui tempat yang kering di tengah-tengah laut. Tetapi pengejar-pengejar mereka telah Kaucampakkan ke air yang dalam, seperti batu ke air yang dahsyat."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:12, Page:1,
    Kor:"○낮에는 구름기둥으로 그들을 이끌어 주시고, 밤에는 불기둥으로 그들이 가는 길을 밝히 비추어 주셨습니다.",
    Chn:"并且白昼用云柱引导他们，黑夜用火柱照亮他们当行的路。",
    Eng:"By day you led them with a pillar of cloud, and by night with a pillar of fire to give them light on the way they were to take.",
    Ind:"Dengan tiang awan Engkau memimpin mereka pada siang hari dan dengan tiang api pada malam hari untuk menerangi jalan yang mereka lalui."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:13, Page:1,
    Kor:"몸소 시내 산에 내려오시며, 하늘에서 그들에게 말씀하셔서, 바른 규례와 참된 율법, 좋은 율례와 계명을 주셨습니다.",
    Chn:"你也降临在西奈山，从天上与他们说话，赐给他们正直的典章、真实的律法、美好的条例与诫命，",
    Eng:"\"You came down on Mount Sinai; you spoke to them from heaven. You gave them regulations and laws that are just and right, and decrees and commands that are good.",
    Ind:"Engkau telah turun ke atas gunung Sinai dan berbicara dengan mereka dari langit dan memberikan mereka peraturan-peraturan yang adil, hukum-hukum yang benar serta ketetapan-ketetapan dan perintah-perintah yang baik."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:14, Page:1,
    Kor:"주님의 거룩한 안식일을 알려 주시고, 주님의 종 모세를 시키셔서 계명과 규정과 율법을 가르쳐 주셨습니다.",
    Chn:"又使他们知道你的安息圣日，并借你仆人摩西传给他们诫命、条例、律法。",
    Eng:"You made known to them your holy Sabbath and gave them commands, decrees and laws through your servant Moses.",
    Ind:"Juga Kauberitahukan kepada mereka sabat-Mu yang kudus dan memberikan kepada mereka perintah-perintah, ketetapan-ketetapan dan hukum-Mu dengan perantaraan Musa, hamba-Mu."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:15, Page:1,
    Kor:"○굶주릴까봐 하늘에서 먹거리를 내려 주시고, 목마를까봐 바위에서 물이 솟아나게 하셨습니다. 주님께서 손을 들어 맹세하며 주시겠다고 한 그 땅에 들어가서, 그 곳을 차지하라고 말씀하셨습니다.",
    Chn:"从天上赐下粮食充他们的饥，从磐石使水流出解他们的渴，又吩咐他们进去得你起誓应许赐给他们的地。",
    Eng:"In their hunger you gave them bread from heaven and in their thirst you brought them water from the rock; you told them to go in and take possession of the land you had sworn with uplifted hand to give them.",
    Ind:"Telah Kauberikan kepada mereka roti dari langit untuk menghilangkan lapar dan air Kaukeluarkan bagi mereka dari gunung batu untuk melepaskan dahaga. Pula Engkau menyuruh mereka memasuki dan menduduki negeri yang dengan mengangkat sumpah telah Kaujanjikan memberikannya kepada mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:16, Page:1,
    Kor:"그러나 우리 조상은 거만하여, 목이 뻣뻣하고 고집이 세어서, 주님의 명령을 지키지 않았습니다.",
    Chn:"「但我们的列祖行事狂傲，硬着颈项不听从你的诫命；",
    Eng:"\"But they, our forefathers, became arrogant and stiff-necked, and did not obey your commands.",
    Ind:"Tetapi mereka, nenek moyang kami itu, bertindak angkuh dan bersitegang leher dan tidak patuh kepada perintah-perintah-Mu."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:17, Page:1,
    Kor:"주님께 복종하기를 거부하고, 주님께서 보여 주신 그 놀라운 일들을 곧 잊었습니다. 뻣뻣한 목에 고집만 세어서, 종살이하던 이집트로 되돌아가려고, 반역자들은 우두머리를 세우기까지 하였습니다. 그러나 주님은 용서하시는 하나님, 은혜로우시며, 너그러우시며, 좀처럼 노여워하지 않으시며, 사랑이 많으셔서, 그들을 버리지 않으셨습니다.",
    Chn:"不肯顺从，也不记念你在他们中间所行的奇事，竟硬着颈项，居心背逆，自立首领，要回他们为奴之地。但你是乐意饶恕人，有恩典，有怜悯，不轻易发怒，有丰盛慈爱的　神，并不丢弃他们。",
    Eng:"They refused to listen and failed to remember the miracles you performed among them. They became stiff-necked and in their rebellion appointed a leader in order to return to their slavery. But you are a forgiving God, gracious and compassionate, slow to anger and abounding in love. Therefore you did not desert them,",
    Ind:"Mereka menolak untuk patuh dan tidak mengingat perbuatan-perbuatan yang ajaib yang telah Kaubuat di antara mereka. Mereka bersitegang leher malah berkeras kepala untuk kembali ke perbudakan di Mesir. Tetapi Engkaulah Allah yang sudi mengampuni, yang pengasih dan penyayang, yang panjang sabar dan berlimpah kasih setia-Nya. Engkau tidak meninggalkan mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:18, Page:1,
    Kor:"더욱이, 우리 조상은, 금붙이를 녹여서 송아지 상을 만들고는 '우리를 이집트에서 이끌어 내신 우리의 하나님이다' 하고 외치고, 주님을 크게 모독하였습니다.",
    Chn:"他们虽然铸了一只牛犊，彼此说『这是领你出埃及的神』，因而大大惹动你的怒气；",
    Eng:"even when they cast for themselves an image of a calf and said, 'This is your god, who brought you up out of Egypt,' or when they committed awful blasphemies.",
    Ind:"Bahkan, ketika mereka membuat anak lembu tuangan dan berkata: 'Inilah Allahmu yang menuntun engkau keluar dari Mesir!', dan berbuat nista yang besar,"
  },
  {Bible:"Nehemiah", Chapter:9, Verse:19, Page:1,
    Kor:"그런데도 주님께서는 언제나 그들을 불쌍히 보셔서, 차마 그들을 광야에다가 내다 버리지 못하셨습니다. 낮에는 줄곧 구름기둥으로 그들을 이끌어 주시고, 밤에는 불기둥으로 그들이 가는 길을 밝히 비추어 주셨습니다.",
    Chn:"你还是大施怜悯，在旷野不丢弃他们。白昼，云柱不离开他们，仍引导他们行路；黑夜，火柱也不离开他们，仍照亮他们当行的路。",
    Eng:"\"Because of your great compassion you did not abandon them in the desert. By day the pillar of cloud did not cease to guide them on their path, nor the pillar of fire by night to shine on the way they were to take.",
    Ind:"Engkau tidak meninggalkan mereka di padang gurun karena kasih sayang-Mu yang besar. Tiang awan tidak berpindah dari atas mereka pada siang hari untuk memimpin mereka pada perjalanan, begitu juga tiang api pada malam hari untuk menerangi jalan yang mereka lalui."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:20, Page:1,
    Kor:"선한 영을 주셔서, 그들을 슬기롭게 하셨습니다. 그들의 입에 만나가 끊이지 않게 하시며, 목말라 할 때에 물을 주셨습니다.",
    Chn:"你也赐下你良善的灵教训他们；未尝不赐吗哪使他们糊口，并赐水解他们的渴。",
    Eng:"You gave your good Spirit to instruct them. You did not withhold your manna from their mouths, and you gave them water for their thirst.",
    Ind:"Dan Engkau memberikan kepada mereka Roh-Mu yang baik untuk mengajar mereka. Juga manna-Mu tidak Kautahan dari mulut mereka dan Engkau memberikan air kepada mereka untuk melepaskan dahaga."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:21, Page:1,
    Kor:"광야에서 사십 년 동안이나 돌보셔서, 그들이 아쉬운 것 없게 하셨습니다. 옷이 해어지지도 않았고, 발이 부르트지도 않았습니다.",
    Chn:"在旷野四十年，你养育他们，他们就一无所缺：衣服没有穿破，脚也没有肿。",
    Eng:"For forty years you sustained them in the desert; they lacked nothing, their clothes did not wear out nor did their feet become swollen.",
    Ind:"Empat puluh tahun lamanya Engkau memberikan mereka makan di padang gurun. Mereka tidak berkekurangan, pakaian mereka tidak rusak, dan kaki mereka tidak bengkak."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:22, Page:1,
    Kor:"○여러 나라와 민족들을 우리 조상에게 굴복시키셔서, 우리 조상이 시혼 땅 곧 헤스본 왕의 땅과 바산 왕 옥의 땅을 차지하고, 그것을 나누어서 변방으로 삼았습니다.",
    Chn:"并且你将列国之地照分赐给他们，他们就得了西宏之地、希实本王之地，和巴珊王噩之地。",
    Eng:"\"You gave them kingdoms and nations, allotting to them even the remotest frontiers. They took over the country of Sihon king of Heshbon and the country of Og king of Bashan.",
    Ind:"Engkau menyerahkan kepada mereka kerajaan-kerajaan dan bangsa-bangsa dan membagikan itu kepada mereka sebagai daerah perbatasan, sebab mereka duduki tanah dari Sihon, raja negeri Hesbon dan tanah dari Og, raja negeri Basan."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:23, Page:1,
    Kor:"주님께서는 우리 조상의 자손을 하늘의 별만큼이나 불어나게 하시고, 조상들에게 말씀하신 땅으로 인도하셔서, 그 곳을 차지하게 하셨습니다.",
    Chn:"你也使他们的子孙多如天上的星，带他们到你所应许他们列祖进入得为业之地。",
    Eng:"You made their sons as numerous as the stars in the sky, and you brought them into the land that you told their fathers to enter and possess.",
    Ind:"Engkau membuat anak-anak mereka menjadi banyak seperti bintang-bintang di langit dan membawa mereka ke tanah yang Kausuruh kepada nenek moyang mereka untuk dimasuki dan diduduki."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:24, Page:1,
    Kor:"자손이 들어가서 그 땅을 차지할 때에, 그 땅에 살던 가나안 사람들을 그 자손에게 굴복시키고, 왕들과 그 땅의 백성마저 자손이 좋을 대로 하게 하셨습니다.",
    Chn:"这样，他们进去得了那地，你在他们面前制伏那地的居民，就是迦南人；将迦南人和其君王，并那地的居民，都交在他们手里，让他们任意而待。",
    Eng:"Their sons went in and took possession of the land. You subdued before them the Canaanites, who lived in the land; you handed the Canaanites over to them, along with their kings and the peoples of the land, to deal with them as they pleased.",
    Ind:"Lalu anak-anak itu memasuki dan menduduki tanah itu dan Engkau menundukkan di hadapan mereka penduduk tanah itu, yakni orang-orang Kanaan, dan menyerahkan orang-orang itu, baik raja-raja mereka, maupun bangsa-bangsa tanah itu, ke tangan mereka, supaya orang-orang itu diperlakukan sekehendak hati mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:25, Page:1,
    Kor:"자손은 요새화된 성채들과 기름진 땅을 차지하였습니다. 온갖 좋은 것으로 가득 찬 집과 이미 파 놓은 우물과 포도원과 올리브 밭과 과일이 흐드러지게 열리는 나무를 차지하였습니다. 그들은 먹고 만족하게 생각했으며, 살이 쪘습니다. 주님께서 주신 그 큰 복을 한껏 누렸습니다.",
    Chn:"他们得了坚固的城邑、肥美的地土、充满各样美物的房屋、凿成的水井、葡萄园、橄榄园，并许多果木树。他们就吃而得饱，身体肥胖，因你的大恩，心中快乐。",
    Eng:"They captured fortified cities and fertile land; they took possession of houses filled with all kinds of good things, wells already dug, vineyards, olive groves and fruit trees in abundance. They ate to the full and were well-nourished; they reveled in your great goodness.",
    Ind:"Mereka merebut kota-kota yang berkubu dan tanah yang subur. Mereka merampas rumah-rumah yang penuh berisi berbagai-bagai barang baik, tempat-tempat air pahatan, kebun-kebun anggur dan kebun-kebun zaitun dan pohon-pohon buah-buahan dalam jumlah yang sangat banyak. Mereka makan dan menjadi kenyang dan gemuk. Mereka hidup mewah karena kebaikan-Mu yang besar."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:26, Page:1,
    Kor:"○그런데도 그들은 순종하지 않고, 오히려 주님께 반역하였으며, 주님께서 주신 율법을 등졌습니다. 주님께로 돌아가라고 타이르던 예언자들을 죽이기까지 하였습니다. 이렇듯 엄청나게 주님을 욕되게 하였습니다.",
    Chn:"「然而，他们不顺从，竟背叛你，将你的律法丢在背后，杀害那劝他们归向你的众先知，大大惹动你的怒气。",
    Eng:"\"But they were disobedient and rebelled against you; they put your law behind their backs. They killed your prophets, who had admonished them in order to turn them back to you; they committed awful blasphemies.",
    Ind:"Tetapi mereka mendurhaka dan memberontak terhadap-Mu. Mereka membelakangi hukum-Mu dan membunuh nabi-nabi-Mu yang memperingatkan mereka dengan maksud membuat mereka berbalik kepada-Mu. Mereka berbuat nista yang besar."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:27, Page:1,
    Kor:"○주님께서는 그들을 원수들의 손에 내맡기시어 억압을 받게 하셨습니다. 그러나 억눌림을 받고 주님께 부르짖으면, 주님께서는 하늘에서 들으시고, 그들을 끔찍이도 불쌍히 여기시어, 원수의 손아귀에서 그들을 건져낼 구원자들을 보내 주시곤 하셨습니다.",
    Chn:"所以你将他们交在敌人的手中，磨难他们。他们遭难的时候哀求你，你就从天上垂听，照你的大怜悯赐给他们拯救者，救他们脱离敌人的手。",
    Eng:"So you handed them over to their enemies, who oppressed them. But when they were oppressed they cried out to you. From heaven you heard them, and in your great compassion you gave them deliverers, who rescued them from the hand of their enemies.",
    Ind:"Lalu Engkau menyerahkan mereka ke tangan lawan-lawan mereka, yang menyesakkan mereka. Dan pada waktu kesusahan mereka berteriak kepada-Mu, lalu Engkau mendengar dari langit dan karena kasih sayang-Mu yang besar Kauberikan kepada mereka orang-orang yang menyelamatkan mereka dari tangan lawan mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:28, Page:1,
    Kor:"그러나 편안하게 살만하면, 주님께서 보고 계시는데도, 또다시 못된 일을 저질렀습니다. 그럴 때에는, 주님께서 그들을 원수의 손에 버려 두셔서, 억눌림을 받게 하셨습니다. 그러다가도 다시 돌이켜 주님께 부르짖기만 하면, 주님께서는 하늘에서 들으시고 불쌍히 여기시어, 구하여 주시곤 하셨습니다.",
    Chn:"但他们得平安之后，又在你面前行恶，所以你丢弃他们在仇敌的手中，使仇敌辖制他们。然而他们转回哀求你，你仍从天上垂听，屡次照你的怜悯拯救他们，",
    Eng:"\"But as soon as they were at rest, they again did what was evil in your sight. Then you abandoned them to the hand of their enemies so that they ruled over them. And when they cried out to you again, you heard from heaven, and in your compassion you delivered them time after time.",
    Ind:"Tetapi begitu mereka mendapat keamanan, kembali mereka berbuat jahat di hadapan-Mu. Dan Engkau menyerahkan mereka ke tangan musuh-musuh mereka yang menguasai mereka. Kembali mereka berteriak kepada-Mu, dan Engkau mendengar dari langit, lalu menolong mereka berulang kali, karena kasih sayang-Mu."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:29, Page:1,
    Kor:"돌이켜 주님의 율법대로 바로 살라고, 주님께서 엄하게 타이르셨지만, 그들은 거만하여 주님의 명령을 따르지 않았습니다. 지키기만 하면 살게 되는 법을 주셨지만, 오히려 그 법을 거역하여 죄를 지었습니다. 주님께 등을 돌리고, 목이 뻣뻣하여 고집을 버리지 못하였으며, 복종하지 않았습니다.",
    Chn:"又警戒他们，要使他们归服你的律法。他们却行事狂傲，不听从你的诫命，干犯你的典章（人若遵行就必因此活着），扭转肩头，硬着颈项，不肯听从。",
    Eng:"\"You warned them to return to your law, but they became arrogant and disobeyed your commands. They sinned against your ordinances, by which a man will live if he obeys them. Stubbornly they turned their backs on you, became stiff-necked and refused to listen.",
    Ind:"Engkau memperingatkan mereka dengan maksud membuat mereka berbalik kepada hukum-Mu. Tetapi mereka bertindak angkuh, mereka tidak patuh kepada perintah-perintah-Mu dan mereka berdosa terhadap peraturan-peraturan-Mu, yang justru memberi hidup kepada orang yang melakukannya. Mereka melintangkan bahu untuk melawan, mereka bersitegang leher dan tidak mau dengar."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:30, Page:1,
    Kor:"그러나 주님께서는 여러 해 동안 참으셨습니다. 예언자들을 보내시어 주님의 영으로 타이르셨지만, 사람들은 귀도 기울이지 않았습니다. 하는 수 없이, 주님께서는 그들을 여러 나라 백성에게 넘기셨습니다.",
    Chn:"但你多年宽容他们，又用你的灵借众先知劝戒他们，他们仍不听从，所以你将他们交在列国之民的手中。",
    Eng:"For many years you were patient with them. By your Spirit you admonished them through your prophets. Yet they paid no attention, so you handed them over to the neighboring peoples.",
    Ind:"Namun bertahun-tahun lamanya Engkau melanjutkan sabar-Mu terhadap mereka. Dengan Roh-Mu Engkau memperingatkan mereka, yakni dengan perantaraan para nabi-Mu, tetapi mereka tidak menghiraukannya, sehingga Engkau menyerahkan mereka ke tangan bangsa-bangsa segala negeri."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:31, Page:1,
    Kor:"그러나 주님께서는 은혜로우시며, 사람을 불쌍히 여기시는 하나님이시기에, 그들을 끔찍이도 불쌍히 여기셔서, 멸망시키지도 않으시고, 버리지도 않으셨습니다.",
    Chn:"然而你大发怜悯，不全然灭绝他们，也不丢弃他们；因为你是有恩典、有怜悯的　神。",
    Eng:"But in your great mercy you did not put an end to them or abandon them, for you are a gracious and merciful God.",
    Ind:"Tetapi karena kasih sayang-Mu yang besar Engkau tidak membinasakan mereka sama sekali dan tidak meninggalkan mereka, karena Engkaulah Allah yang pengasih dan penyayang."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:32, Page:1,
    Kor:"○우리 하나님, 위대하고 강하고 두렵고, 한 번 세운 언약은 성실하게 지키시는 하나님, 앗시리아의 왕들이 쳐들어온 날로부터 이 날까지, 우리가 겪은 환난을, 우리의 왕들과 대신들과 제사장들과 예언자들과 조상들과 주님의 모든 백성이 겪은 이 환난을 작게 여기지 마십시오.",
    Chn:"「我们的　神啊，你是至大、至能、至可畏、守约施慈爱的　神。我们的君王、首领、祭司、先知、列祖，和你的众民，从亚述列王的时候直到今日所遭遇的苦难，现在求你不要以为小。",
    Eng:"\"Now therefore, O our God, the great, mighty and awesome God, who keeps his covenant of love, do not let all this hardship seem trifling in your eyes--the hardship that has come upon us, upon our kings and leaders, upon our priests and prophets, upon our fathers and all your people, from the days of the kings of Assyria until today.",
    Ind:"Sekarang, ya Allah kami, Allah yang maha besar, kuat dan dahsyat, yang berpegang pada perjanjian dan kasih setia-Nya, janganlah Kaupandang remeh segala kesusahan yang telah dialami oleh kami, oleh raja-raja kami, pemimpin-pemimpin kami, imam-imam kami, nabi-nabi kami dan nenek moyang kami, ya oleh seluruh umat-Mu, sejak zaman raja-raja Asyur sampai hari ini."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:33, Page:1,
    Kor:"우리에게 이 모든 일이 닥쳐왔지만, 이것은 주님의 잘못이 아닙니다. 잘못은 우리가 저질렀습니다. 주님께서는 일을 올바르게 처리하셨습니다.",
    Chn:"在一切临到我们的事上，你却是公义的；因你所行的是诚实，我们所做的是邪恶。",
    Eng:"In all that has happened to us, you have been just; you have acted faithfully, while we did wrong.",
    Ind:"Tetapi Engkaulah yang benar dalam segala hal yang menimpa kami, karena Engkau berlaku setia dan kamilah berbuat fasik."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:34, Page:1,
    Kor:"우리의 왕들과 대신들과 제사장들과 조상들은 주님의 율법을 따르지 않았습니다. 주님의 계명에 귀를 기울이지도 않고, 타이르시는 말씀도 듣지 않았습니다.",
    Chn:"我们的君王、首领、祭司、列祖都不遵守你的律法，不听从你的诫命和你警戒他们的话。",
    Eng:"Our kings, our leaders, our priests and our fathers did not follow your law; they did not pay attention to your commands or the warnings you gave them.",
    Ind:"Juga raja-raja kami, pemimpin-pemimpin kami, imam-imam kami, dan nenek moyang kami tidak melakukan hukum-Mu. Mereka tidak memperhatikan perintah-perintah-Mu dan peringatan-peringatan-Mu yang Kauberikan kepada mereka."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:35, Page:1,
    Kor:"그들은 나라를 세우고 주님께서 베푸신 큰 복을 누리면서도, 눈 앞에 펼쳐 주신 넓고 기름진 땅에 살면서도, 주님을 섬기지도 않고, 악한 길에서 돌이키지도 않았습니다.",
    Chn:"他们在本国里沾你大恩的时候，在你所赐给他们这广大肥美之地上不事奉你，也不转离他们的恶行。",
    Eng:"Even while they were in their kingdom, enjoying your great goodness to them in the spacious and fertile land you gave them, they did not serve you or turn from their evil ways.",
    Ind:"Dalam kedudukan sebagai raja mereka tidak mau beribadah kepada-Mu, walaupun Engkau telah mengaruniakan kepada mereka banyak kebaikan dan telah menyediakan bagi mereka tanah yang luas dan subur. Mereka tidak berbalik dari perbuatan-perbuatan mereka yang jahat."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:36, Page:1,
    Kor:"그러나 보십시오. 오늘 이처럼 우리는 종살이를 합니다. 다른 곳도 아니고, 좋은 과일과 곡식을 먹고 살라고 우리 조상에게 주신 바로 그 땅에서, 우리가 종이 되었습니다.",
    Chn:"我们现今作了奴仆；至于你所赐给我们列祖享受其上的土产，并美物之地，看哪，我们在这地上作了奴仆！",
    Eng:"\"But see, we are slaves today, slaves in the land you gave our forefathers so they could eat its fruit and the other good things it produces.",
    Ind:"Lihatlah, sekarang ini kami adalah budak. Ya, di tanah yang Kauberikan kepada nenek moyang kami untuk mengecap hasilnya dan segala kekayaannya kami ini adalah budak."
  },
  {Bible:"Nehemiah", Chapter:9, Verse:37, Page:1,
    Kor:"땅에서 나는 풍성한 소출은, 우리의 죄를 벌하시려고 세운 이방 왕들의 것이 되었습니다. 그 왕들은 우리의 몸뚱이도, 우리의 가축도, 마음대로 부립니다. 이처럼 우리는 무서운 고역을 치르고 있습니다.",
    Chn:"这地许多出产归了列王，就是你因我们的罪所派辖制我们的。他们任意辖制我们的身体和牲畜，我们遭了大难。」",
    Eng:"Because of our sins, its abundant harvest goes to the kings you have placed over us. They rule over our bodies and our cattle as they please. We are in great distress.",
    Ind:"Tanah itu menghasilkan banyak bagi raja-raja yang telah Kautetapkan atas kami karena dosa-dosa kami. Mereka itu memerintah sekehendak hati atas diri kami dan ternak kami, sehingga kami dalam kesesakan besar.\""
  },
  {Bible:"Nehemiah", Chapter:9, Verse:38, Page:1,
    Kor:"이 모든 것을 돌이켜 본 뒤에, 우리는 언약을 굳게 세우고, 그것을 글로 적었으며, 지도자들과 레위 사람들과 제사장들이 그 위에 서명하였다.",
    Chn:"因这一切的事，我们立确实的约，写在册上。我们的首领、利未人，和祭司都签了名。",
    Eng:"\"In view of all this, we are making a binding agreement, putting it in writing, and our leaders, our Levites and our priests are affixing their seals to it.\"",
    Ind:"Berdasarkan semuanya ini kami mengikat perjanjian yang teguh yang kami catat dengan dibubuhi meterai para pemimpin kami, orang-orang Lewi kami dan para imam kami."
  },
]);
