// 느헤미야 10장 · Nehemiah 10
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Nehemiah",10,39);
BibleDB.add([
  {Bible:"Nehemiah", Chapter:10, Verse:1, Page:1,
    Kor:"<언약에 서명한 사람들> 서명한 사람들은 다음과 같다. ○하가랴의 아들인 총독 느헤미야와 시드기야와",
    Chn:"签名的是：哈迦利亚的儿子—省长尼希米，和西底家；",
    Eng:"Those who sealed it were: Nehemiah the governor, the son of Hacaliah. Zedekiah,",
    Ind:"Yang membubuhi meterai adalah: kepala daerah Nehemia bin Hakhalya, Zedekia,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:2, Page:1,
    Kor:"스라야와 아사랴와 예레미야와",
    Chn:"祭司：西莱雅、亚撒利雅、耶利米、",
    Eng:"Seraiah, Azariah, Jeremiah,",
    Ind:"Seraya, Azarya, Yeremia,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:3, Page:1,
    Kor:"바스훌과 아마랴와 말기야와",
    Chn:"巴施户珥、亚玛利雅、玛基雅、",
    Eng:"Pashhur, Amariah, Malkijah,",
    Ind:"Pasyhur, Amarya, Malkia,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:4, Page:1,
    Kor:"핫두스와 스바냐와 말룩과",
    Chn:"哈突、示巴尼、玛鹿、",
    Eng:"Hattush, Shebaniah, Malluch,",
    Ind:"Hatus, Sebanya, Malukh,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:5, Page:1,
    Kor:"하림과 므레못과 오바댜와",
    Chn:"哈琳、米利末、俄巴底亚、",
    Eng:"Harim, Meremoth, Obadiah,",
    Ind:"Harim, Meremot, Obaja,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:6, Page:1,
    Kor:"다니엘과 긴느돈과 바룩과",
    Chn:"但以理、近顿、巴录、",
    Eng:"Daniel, Ginnethon, Baruch,",
    Ind:"Daniel, Gineton, Barukh,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:7, Page:1,
    Kor:"므술람과 아비야와 미야민과",
    Chn:"米书兰、亚比雅、米雅民、",
    Eng:"Meshullam, Abijah, Mijamin,",
    Ind:"Mesulam, Abia, Miyamin,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:8, Page:1,
    Kor:"마아시야와 빌개와 스마야는 제사장이다.",
    Chn:"玛西亚、璧该、示玛雅；",
    Eng:"Maaziah, Bilgai and Shemaiah. These were the priests.",
    Ind:"Maazya, Bilgai dan Semaya. Itulah para imam."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:9, Page:1,
    Kor:"○레위 사람으로는, 아사냐의 아들인 예수아와 헤나닷 자손인 빈누이와 갓미엘과",
    Chn:"又有利未人，就是亚散尼的儿子耶书亚、希拿达的子孙宾内、甲篾；",
    Eng:"The Levites: Jeshua son of Azaniah, Binnui of the sons of Henadad, Kadmiel,",
    Ind:"Sedang dari orang-orang Lewi: Yesua bin Azanya, Binui, seorang dari antara anak-anak Henadad, Kadmiel."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:10, Page:1,
    Kor:"그들의 동료 스바냐와 호디야와 그리다와 블라야와 하난과",
    Chn:"还有他们的弟兄示巴尼、荷第雅、基利他、毗莱雅、哈难、",
    Eng:"and their associates: Shebaniah, Hodiah, Kelita, Pelaiah, Hanan,",
    Ind:"Dan saudara-saudara mereka, yakni: Sebanya, Hodia, Kelita, Pelaya, Hanan,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:11, Page:1,
    Kor:"미가와 르홉과 하사뱌와",
    Chn:"米迦、利合、哈沙比雅、",
    Eng:"Mica, Rehob, Hashabiah,",
    Ind:"Mikha, Rehob, Hasabya,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:12, Page:1,
    Kor:"삭굴과 세레뱌와 스바냐와",
    Chn:"撒刻、示利比、示巴尼、",
    Eng:"Zaccur, Sherebiah, Shebaniah,",
    Ind:"Zakur, Serebya, Sebanya,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:13, Page:1,
    Kor:"호디야와 바니와 브니누가 있다.",
    Chn:"荷第雅、巴尼、比尼努；",
    Eng:"Hodiah, Bani and Beninu.",
    Ind:"Hodia, Bani dan Beninu."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:14, Page:1,
    Kor:"○백성의 지도자로는, 바로스와 바핫모압과 엘람과 삿두와 바니와",
    Chn:"又有民的首领，就是巴录、巴哈·摩押、以拦、萨土、巴尼、",
    Eng:"The leaders of the people: Parosh, Pahath-Moab, Elam, Zattu, Bani,",
    Ind:"Dan dari pemimpin-pemimpin bangsa: Paros, Pahat-Moab, Elam, Zatu, Bani,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:15, Page:1,
    Kor:"분니와 아스갓과 베배와",
    Chn:"布尼、押甲、比拜、",
    Eng:"Bunni, Azgad, Bebai,",
    Ind:"Buni, Azgad, Bebai,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:16, Page:1,
    Kor:"아도니야와 비그왜와 아딘과",
    Chn:"亚多尼雅、比革瓦伊、亚丁、",
    Eng:"Adonijah, Bigvai, Adin,",
    Ind:"Adonia, Bigwai, Adin,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:17, Page:1,
    Kor:"아델과 히스기야와 앗술과",
    Chn:"亚特、希西家、押朔、",
    Eng:"Ater, Hezekiah, Azzur,",
    Ind:"Ater, Hizkia, Azur,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:18, Page:1,
    Kor:"호디야와 하숨과 베새와",
    Chn:"荷第雅、哈顺、比赛、",
    Eng:"Hodiah, Hashum, Bezai,",
    Ind:"Hodia, Hasum, Bezai,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:19, Page:1,
    Kor:"하립과 아나돗과 노배와",
    Chn:"哈拉、亚拿突、尼拜、",
    Eng:"Hariph, Anathoth, Nebai,",
    Ind:"Harif, Anatot, Nebai,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:20, Page:1,
    Kor:"막비아스와 므술람과 헤실과",
    Chn:"抹比押、米书兰、希悉、",
    Eng:"Magpiash, Meshullam, Hezir,",
    Ind:"Magpias, Mesulam, Hezir,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:21, Page:1,
    Kor:"므세사벨과 사독과 얏두아와",
    Chn:"米示萨别、撒督、押杜亚、",
    Eng:"Meshezabel, Zadok, Jaddua,",
    Ind:"Mesezabeel, Zadok, Yadua,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:22, Page:1,
    Kor:"블라댜와 하난과 아나야와",
    Chn:"毗拉提、哈难、亚奈雅、",
    Eng:"Pelatiah, Hanan, Anaiah,",
    Ind:"Pelaca, Hanan, Anaya,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:23, Page:1,
    Kor:"호세아와 하나냐와 핫숩과",
    Chn:"何细亚、哈拿尼雅、哈述、",
    Eng:"Hoshea, Hananiah, Hasshub,",
    Ind:"Hosea, Hananya, Hasub,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:24, Page:1,
    Kor:"할르헤스와 빌하와 소벡과",
    Chn:"哈罗黑、毗利哈、朔百、",
    Eng:"Hallohesh, Pilha, Shobek,",
    Ind:"Halohesh, Pilha, Sobek,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:25, Page:1,
    Kor:"르훔과 하삽나와 마아세야와",
    Chn:"利宏、哈沙拿、玛西雅、",
    Eng:"Rehum, Hashabnah, Maaseiah,",
    Ind:"Rehum, Hasabna, Maaseya,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:26, Page:1,
    Kor:"아히야와 하난과 아난과",
    Chn:"亚希雅、哈难、亚难、",
    Eng:"Ahiah, Hanan, Anan,",
    Ind:"Ahia, Hanan, Anan,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:27, Page:1,
    Kor:"말룩과 하림과 바아나가 있다.",
    Chn:"玛鹿、哈琳、巴拿。",
    Eng:"Malluch, Harim and Baanah.",
    Ind:"Malukh, Harim dan Baana."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:28, Page:1,
    Kor:"○이 밖에 나머지 백성, 곧 제사장과 레위 사람과 성전 문지기와 노래하는 사람과 성전 막일꾼과 주님의 율법을 따르려고 그 땅의 여러 백성과 인연을 끊은 모든 이들과 그 아내들과 그들의 아들딸들과 알아들을 만한 지식이 있는 이들 모두가,",
    Chn:"其余的民、祭司、利未人、守门的、歌唱的、尼提宁，和一切离绝邻邦居民归服　神律法的，并他们的妻子、儿女，凡有知识能明白的，",
    Eng:"\"The rest of the people--priests, Levites, gatekeepers, singers, temple servants and all who separated themselves from the neighboring peoples for the sake of the Law of God, together with their wives and all their sons and daughters who are able to understand--",
    Ind:"Dan orang-orang yang lain, yakni: para imam dan orang-orang Lewi, para penunggu pintu gerbang, para penyanyi, para budak di bait Allah dan segala orang yang memisahkan diri dari penduduk negeri untuk patuh kepada hukum Allah, serta isteri mereka, anak-anak lelaki dan anak-anak perempuan mereka, begitu juga semua orang yang cukup dewasa untuk mengerti,"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:29, Page:1,
    Kor:"귀족 지도자들과 함께 하나님의 종 모세가 전하여 준 하나님의 율법을 따르기로 하고, 우리 주 하나님의 모든 계명과 규례와 율례에 복종하기로 하였으며, 그것을 어기면 저주를 받아도 좋다고 다음과 같이 맹세하였다.",
    Chn:"都随从他们贵胄的弟兄，发咒起誓，必遵行　神借他仆人摩西所传的律法，谨守遵行耶和华—我们主的一切诫命、典章、律例；",
    Eng:"all these now join their brothers the nobles, and bind themselves with a curse and an oath to follow the Law of God given through Moses the servant of God and to obey carefully all the commands, regulations and decrees of the LORD our LORD.",
    Ind:"menggabungkan diri dengan saudara-saudara mereka, yakni pemuka-pemuka mereka itu. Mereka bersumpah kutuk untuk hidup menurut hukum Allah yang diberikan dengan perantaraan Musa, hamba Allah itu, dan untuk tetap mengikuti dan melakukan segala perintah TUHAN, yakni Tuhan kami, serta segala peraturan dan ketetapan-Nya."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:30, Page:1,
    Kor:"○\"우리는 딸을 이 땅의 백성과 결혼시키지 않는다. 우리는 아들을 그들의 딸과 결혼시키지 않는다.",
    Chn:"并不将我们的女儿嫁给这地的居民，也不为我们的儿子娶他们的女儿。",
    Eng:"\"We promise not to give our daughters in marriage to the peoples around us or take their daughters for our sons.",
    Ind:"Pula kami tidak akan memberi anak-anak perempuan kami kepada penduduk negeri, ataupun mengambil anak-anak perempuan mereka bagi anak-anak lelaki kami."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:31, Page:1,
    Kor:"이 땅의 백성이 안식일에 물건이나 어떤 곡식을 내다가 팔더라도, 안식일에나 성일에는, 우리가 사지 않는다. 일곱 해마다 땅을 쉬게 하고, 육 년이 지난 빚은 모두 없애 준다.\"",
    Chn:"这地的居民若在安息日，或什么圣日，带了货物或粮食来卖给我们，我们必不买。每逢第七年必不耕种，凡欠我们债的必不追讨。",
    Eng:"\"When the neighboring peoples bring merchandise or grain to sell on the Sabbath, we will not buy from them on the Sabbath or on any holy day. Every seventh year we will forgo working the land and will cancel all debts.",
    Ind:"Dan bilamana penduduk negeri membawa barang-barang dan berbagai-bagai gandum untuk dijual pada hari Sabat, kami tidak akan membelinya dari mereka pada hari Sabat atau pada hari yang kudus. Dan kami akan membiarkan begitu saja hasil tanah pada tahun yang ketujuh dan tidak akan menagih sesuatu hutang."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:32, Page:1,
    Kor:"○우리는 다음과 같은 규례도 정하였다. ○\"하나님의 성전 비용으로 쓰도록, 우리는 해마다 삼분의 일 세겔씩 바친다.",
    Chn:"我们又为自己定例，每年各人捐银一舍客勒三分之一，为我们　神殿的使用，",
    Eng:"\"We assume the responsibility for carrying out the commands to give a third of a shekel each year for the service of the house of our God:",
    Ind:"Pula kami mewajibkan diri untuk memberi tiap tahun sepertiga syikal untuk ibadah di rumah Allah kami, yakni:"
  },
  {Bible:"Nehemiah", Chapter:10, Verse:33, Page:1,
    Kor:"이것은, 늘 차려 놓는 빵과 규칙적으로 드리는 곡식제물과 규칙적으로 드리는 번제와 안식일이나 초하루나 그 밖에 절기 때에 드리는 제물과 이스라엘의 죄를 속하는 속죄물과 우리 하나님의 성전에서 하는 모든 일에 쓸 것이다.",
    Chn:"就是为陈设饼、常献的素祭，和燔祭，安息日、月朔、节期所献的与圣物，并以色列人的赎罪祭，以及我们　神殿里一切的费用。",
    Eng:"for the bread set out on the table; for the regular grain offerings and burnt offerings; for the offerings on the Sabbaths, New Moon festivals and appointed feasts; for the holy offerings; for sin offerings to make atonement for Israel; and for all the duties of the house of our God.",
    Ind:"untuk roti sajian, untuk korban sajian yang tetap, untuk korban bakaran yang tetap, untuk hari-hari Sabat, bulan-bulan baru dan masa raya yang tetap, untuk persembahan-persembahan kudus dan korban-korban penghapus dosa, untuk mengadakan pendamaian bagi orang Israel serta segala pekerjaan di rumah Allah kami."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:34, Page:1,
    Kor:"제사장이나 레위 사람이나 일반 백성을 가리지 않고, 우리가 집안별로 주사위를 던져서, 해마다 정한 때에, 우리 하나님의 성전에 땔 나무를 바칠 순서를 정한다. 그것은 율법에 기록된 대로, 우리 주 하나님의 제단에서 불사를 때에 쓸 나무이다.",
    Chn:"我们的祭司、利未人，和百姓都掣签，看每年是哪一族按定期将献祭的柴奉到我们　神的殿里，照着律法上所写的，烧在耶和华—我们　神的坛上。",
    Eng:"\"We--the priests, the Levites and the people--have cast lots to determine when each of our families is to bring to the house of our God at set times each year a contribution of wood to burn on the altar of the LORD our God, as it is written in the Law.",
    Ind:"Pula dengan membuang undi kami, yakni para imam, orang-orang Lewi dan kaum awam, menetapkan suatu cara untuk menyediakan kayu api. Kayu itu harus dibawa ke rumah Allah kami secara bergilir oleh kaum-kaum keluarga kami pada waktu-waktu tertentu setiap tahun, supaya di atas mezbah TUHAN Allah kami ada api yang menyala, seperti tertulis dalam kitab Taurat."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:35, Page:1,
    Kor:"해마다 우리 밭에서 나는 맏물과 온갖 과일나무의 첫 열매를 주님의 성전에 바친다.",
    Chn:"又定每年将我们地上初熟的土产和各样树上初熟的果子都奉到耶和华的殿里。",
    Eng:"\"We also assume responsibility for bringing to the house of the LORD each year the firstfruits of our crops and of every fruit tree.",
    Ind:"Lagipula setiap tahun kami akan membawa ke rumah TUHAN hasil yang pertama dari tanah kami dan buah sulung segala pohon."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:36, Page:1,
    Kor:"율법에 기록된 대로, 우리의 맏아들과 가축의 첫 새끼 곧 처음 난 송아지와 새끼 양을 우리 하나님의 성전으로 가지고 가서, 그 성전에서 우리 하나님을 섬기는 제사장들에게 바친다.\"",
    Chn:"又照律法上所写的，将我们头胎的儿子和首生的牛羊都奉到我们　神的殿，交给我们　神殿里供职的祭司；",
    Eng:"\"As it is also written in the Law, we will bring the firstborn of our sons and of our cattle, of our herds and of our flocks to the house of our God, to the priests ministering there.",
    Ind:"Pun kami akan membawa ke rumah Allah kami, yakni kepada para imam yang menyelenggarakan kebaktian di rumah Allah kami, anak-anak sulung kami dan anak-anak sulung ternak kami seperti tertulis dalam kitab Taurat, juga anak-anak sulung lembu kami dan kambing domba kami."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:37, Page:1,
    Kor:"○또 우리는, 들어 바칠 예물인 처음 익은 밀의 가루와 온갖 과일나무의 열매와 새 포도주와 기름을 가져다가, 제사장의 몫으로 우리 하나님의 성전 창고에 넣기로 하고, 또 밭에서 나는 소출 가운데서 열의 하나는 레위 사람들의 몫으로 가져 오기로 하였다. 농사를 짓는 성읍으로 돌아다니면서 열의 하나를 거두어들일 사람은 바로 레위 사람이다.",
    Chn:"并将初熟之麦子所磨的面和举祭、各样树上初熟的果子、新酒与油奉给祭司，收在我们　神殿的库房里，把我们地上所产的十分之一奉给利未人，因利未人在我们一切城邑的土产中当取十分之一。",
    Eng:"\"Moreover, we will bring to the storerooms of the house of our God, to the priests, the first of our ground meal, of our grain offerings, of the fruit of all our trees and of our new wine and oil. And we will bring a tithe of our crops to the Levites, for it is the Levites who collect the tithes in all the towns where we work.",
    Ind:"Dan tepung jelai kami yang mula-mula, dan persembahan-persembahan khusus kami, dan buah segala pohon, dan anggur dan minyak akan kami bawa kepada para imam, ke bilik-bilik rumah Allah kami, dan kepada orang-orang Lewi akan kami bawa persembahan persepuluhan dari tanah kami, karena orang-orang Lewi inilah yang memungut persembahan-perse persepuluhan di segala kota pertanian kami."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:38, Page:1,
    Kor:"레위 사람이 열의 하나를 거두어들일 때에는, 아론의 자손인 제사장 한 사람이 같이 다니기로 하였다. 레위 사람은 거두어들인 열의 하나에서 다시 열의 하나를 떼어서, 우리 하나님의 성전 창고의 여러 방에 두기로 하였다.",
    Chn:"利未人取十分之一的时候，亚伦的子孙中，当有一个祭司与利未人同在。利未人也当从十分之一中取十分之一，奉到我们　神殿的屋子里，收在库房中。",
    Eng:"A priest descended from Aaron is to accompany the Levites when they receive the tithes, and the Levites are to bring a tenth of the tithes up to the house of our God, to the storerooms of the treasury.",
    Ind:"Seorang imam, anak Harun, akan menyertai orang-orang Lewi itu, bila mereka memungut persembahan persepuluhan. Dan orang-orang Lewi itu akan membawa persembahan persepuluhan dari pada persembahan persepuluhan itu ke rumah Allah kami, ke bilik-bilik rumah perbendaharaan."
  },
  {Bible:"Nehemiah", Chapter:10, Verse:39, Page:1,
    Kor:"이스라엘 자손과 레위 자손은 들어 바칠 예물인 곡식과 새 포도주와 기름을 그 여러 방에 가져다 놓기로 하였다. 그런 방은 성전 기구를 두기도 하고, 당번 제사장들과 성전 문지기들과 노래하는 사람들이 쓰기도 하는 곳이다. ○\"우리는 우리 하나님의 성전을 아무렇게나 버려 두지 않을 것이다.\"",
    Chn:"以色列人和利未人要将五谷、新酒，和油为举祭，奉到收存圣所器皿的屋子里，就是供职的祭司、守门的、歌唱的所住的屋子。这样，我们就不离弃我们　神的殿。",
    Eng:"The people of Israel, including the Levites, are to bring their contributions of grain, new wine and oil to the storerooms where the articles for the sanctuary are kept and where the ministering priests, the gatekeepers and the singers stay. \"We will not neglect the house of our God.\"",
    Ind:"Karena orang Israel dan orang Lewi harus membawa persembahan khusus dari pada gandum, anggur dan minyak ke bilik-bilik itu. Di situ ada perkakas-perkakas tempat kudus, pula para imam yang menyelenggarakan kebaktian, para penunggu pintu gerbang dan para penyanyi. Kami tidak akan membiarkan rumah Allah kami."
  },
]);
