// 느헤미야 8장 · Nehemiah 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Nehemiah",8,18);
BibleDB.add([
  {Bible:"Nehemiah", Chapter:8, Verse:1, Page:1, Kor:"모든 백성이 한꺼번에 수문 앞 광장에 모였다. 그들은 학자 에스라에게, 주님께서 이스라엘에게 명하신 모세의 율법책을 가지고 오라고 청하였다.", Chn:"", Eng:"all the people assembled as one man in the square before the Water Gate. They told Ezra the scribe to bring out the Book of the Law of Moses, which the LORD had commanded for Israel.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:2, Page:1, Kor:"일곱째 달 초하루에 에스라 제사장은 율법책을 가지고 회중 앞에 나왔다. 거기에는, 남자든 여자든, 알아들을 만한 사람은 모두 나와 있었다.", Chn:"", Eng:"So on the first day of the seventh month Ezra the priest brought the Law before the assembly, which was made up of men and women and all who were able to understand.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:3, Page:1, Kor:"그는 수문 앞 광장에서, 남자든 여자든, 알아들을 만한 모든 사람에게 새벽부터 정오까지, 큰소리로 율법책을 읽어 주었다. 백성은 모두 율법책 읽는 소리에 귀를 기울였다.", Chn:"", Eng:"He read it aloud from daybreak till noon as he faced the square before the Water Gate in the presence of the men, women and others who could understand. And all the people listened attentively to the Book of the Law.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:4, Page:1, Kor:"○학자 에스라는 임시로 만든 높은 나무 단 위에 섰다. 그 오른쪽으로는 맛디댜와 스마와 아나야와 우리야와 힐기야와 마아세야가 서고, 왼쪽으로는 브다야와 미사엘과 말기야와 하숨과 하스밧다나와 스가랴와 므술람이 섰다.", Chn:"", Eng:"Ezra the scribe stood on a high wooden platform built for the occasion. Beside him on his right stood Mattithiah, Shema, Anaiah, Uriah, Hilkiah and Maaseiah; and on his left were Pedaiah, Mishael, Malkijah, Hashum, Hashbaddanah, Zechariah and Meshullam.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:5, Page:1, Kor:"학자 에스라는 높은 단 위에 서 있었으므로, 백성들은 모두, 그가 책 펴는 것을 볼 수 있었다. 에스라가 책을 펴면, 백성들은 모두 일어섰다.", Chn:"", Eng:"Ezra opened the book. All the people could see him because he was standing above them; and as he opened it, the people all stood up.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:6, Page:1, Kor:"에스라가 위대하신 주 하나님을 찬양하면, 백성들은 모두 손을 들고 \"아멘! 아멘!\" 하고 응답하고, 엎드려 얼굴을 땅에 대고 주님께 경배하였다.", Chn:"", Eng:"Ezra praised the LORD, the great God; and all the people lifted their hands and responded, \"Amen! Amen!\" Then they bowed down and worshiped the LORD with their faces to the ground.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:7, Page:1, Kor:"레위 사람인 예수아와 바니와 세레뱌와 야민과 악굽과 사브대와 호디야와 마아세야와 그리다와 아사랴와 요사밧과 하난과 블라야는, 백성들이 제자리에 서 있는 동안에, 그들에게 율법을 설명하여 주었다.", Chn:"", Eng:"The Levites--Jeshua, Bani, Sherebiah, Jamin, Akkub, Shabbethai, Hodiah, Maaseiah, Kelita, Azariah, Jozabad, Hanan and Pelaiah--instructed the people in the Law while the people were standing there.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:8, Page:1, Kor:"하나님의 율법책이 낭독될 때에, 그들이 a통역을 하고 뜻을 밝혀 설명하여 주었으므로, 백성은 내용을 잘 알아들을 수 있었다.(a 히브리어에서 아람어로)", Chn:"", Eng:"They read from the Book of the Law of God, making it clear and giving the meaning so that the people could understand what was being read.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:9, Page:1, Kor:"○백성은 율법의 말씀을 들으면서, 모두 울었다. 그래서 총독 느헤미야와, 학자 에스라 제사장과, 백성을 가르치는 레위 사람들이, 이 날은 주 하나님의 거룩한 날이니, 슬퍼하지도 말고 울지도 말라고 모든 백성을 타일렀다.", Chn:"", Eng:"Then Nehemiah the governor, Ezra the priest and scribe, and the Levites who were instructing the people said to them all, \"This day is sacred to the LORD your God. Do not mourn or weep.\" For all the people had been weeping as they listened to the words of the Law.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:10, Page:1, Kor:"느헤미야는 그들에게 말하였다. \"돌아들 가십시오. 살진 짐승들을 잡아 푸짐하게 차려서, 먹고 마시도록 하십시오. 아무것도 차리지 못한 사람들에게는, 먹을 몫을 보내 주십시오. 오늘은 우리 주님의 거룩한 날입니다. 주님 앞에서 기뻐하면 힘이 생기는 법이니, 슬퍼하지들 마십시오.\"", Chn:"", Eng:"Nehemiah said, \"Go and enjoy choice food and sweet drinks, and send some to those who have nothing prepared. This day is sacred to our Lord. Do not grieve, for the joy of the LORD is your strength.\"", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:11, Page:1, Kor:"○레위 사람들도 모든 백성을 달래면서, 오늘은 거룩한 날이니, 조용히 하고, 슬퍼하지 말라고 타일렀다.", Chn:"", Eng:"The Levites calmed all the people, saying, \"Be still, for this is a sacred day. Do not grieve.\"", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:12, Page:1, Kor:"모든 백성은 배운 바를 밝히 깨달았으므로, 돌아가서 먹고 마시며, 없는 사람들에게는 먹을 것을 나누어 주면서, 크게 기뻐하였다.", Chn:"", Eng:"Then all the people went away to eat and drink, to send portions of food and to celebrate with great joy, because they now understood the words that had been made known to them.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:13, Page:1, Kor:"○이튿날에 모든 백성을 대표하는 각 가문의 어른들이 제사장들과 레위 사람들과 함께 율법의 말씀을 밝히 알고자 하여, 학자 에스라에게로 갔다.", Chn:"", Eng:"On the second day of the month, the heads of all the families, along with the priests and the Levites, gathered around Ezra the scribe to give attention to the words of the Law.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:14, Page:1, Kor:"그들은, 이스라엘 자손은 일곱째 달 축제에는 초막에서 지내도록 하라는, 주님께서 모세를 시켜서 명하신 말씀이, 율법에 기록되어 있는 것을 발견하였다.", Chn:"", Eng:"They found written in the Law, which the LORD had commanded through Moses, that the Israelites were to live in booths during the feast of the seventh month", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:15, Page:1, Kor:"또한 그들은 책에, 산으로 가서 올리브 나무와 들올리브 나무와 소귀나무와 종려나무와 참나무의 가지를 꺾어다가 초막을 짓도록 하라는 말이 기록되어 있기 때문에, 그 말을 이스라엘 자손이 사는 모든 마을과 예루살렘에 널리 알려야 한다는 것을 알게 되었다.", Chn:"", Eng:"and that they should proclaim this word and spread it throughout their towns and in Jerusalem: \"Go out into the hill country and bring back branches from olive and wild olive trees, and from myrtles, palms and shade trees, to make booths\"--as it is written.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:16, Page:1, Kor:"○그래서 백성은 나가서, 나뭇가지를 꺾어다가, 지붕 위와 마당과 하나님의 성전 뜰과 수문 앞 광장과 에브라임 문 앞 광장에 초막을 세웠다.", Chn:"", Eng:"So the people went out and brought back branches and built themselves booths on their own roofs, in their courtyards, in the courts of the house of God and in the square by the Water Gate and the one by the Gate of Ephraim.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:17, Page:1, Kor:"사로잡혀 갔다가 돌아온 모든 사람이 초막을 세우고 거기에 머물렀다. 눈의 아들 여호수아 때로부터 그 날까지, 이렇게 축제를 즐긴 일이 없었으므로, 이스라엘 자손은 크게 즐거워하였다.", Chn:"", Eng:"The whole company that had returned from exile built booths and lived in them. From the days of Joshua son of Nun until that day, the Israelites had not celebrated it like this. And their joy was very great.", Ind:""},
  {Bible:"Nehemiah", Chapter:8, Verse:18, Page:1, Kor:"에스라는 첫날로부터 마지막 날까지, 날마다 하나님의 율법책을 읽어 주었다. 백성은 이레 동안 절기를 지키고, 여드레째 되는 날에는 규례대로 성회를 열었다.", Chn:"", Eng:"Day after day, from the first day to the last, Ezra read from the Book of the Law of God. They celebrated the feast for seven days, and on the eighth day, in accordance with the regulation, there was an assembly.", Ind:""},
]);
