// 데살로니가전서 3장 · 1Thessalonians 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Thessalonians",3,13);
BibleDB.add([
  {Bible:"1Thessalonians", Chapter:3, Verse:1, Page:1, Kor:"그러므로, 우리는 참다 못하여, 우리만 아테네에 남아 있기로 하고,", Chn:"", Eng:"So when we could stand it no longer, we thought it best to be left by ourselves in Athens.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:2, Page:1, Kor:"우리의 형제요, a그리스도의 복음을 전하는 하나님의 일꾼인 디모데를 여러분에게로 보냈습니다. 그것은, 그가 여러분을 굳건하게 하고, 여러분의 믿음을 격려하여,(a 그, '그리스도 복음의 하나님의 일꾼')", Chn:"", Eng:"We sent Timothy, who is our brother and God's fellow worker in spreading the gospel of Christ, to strengthen and encourage you in your faith,", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:3, Page:1, Kor:"아무도 이러한 온갖 환난 가운데서 흔들리지 않게 하려는 것입니다. 여러분도 아는 대로, 우리는 이런 환난을 당하게 되어 있습니다.", Chn:"", Eng:"so that no one would be unsettled by these trials. You know quite well that we were destined for them.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:4, Page:1, Kor:"우리가 여러분과 함께 있을 때에, 장차 우리가 환난을 당하게 되리라는 것을 여러분에게 미리 말하였는데, 과연 그렇게 되었고, 여러분은 그것을 알고 있습니다.", Chn:"", Eng:"In fact, when we were with you, we kept telling you that we would be persecuted. And it turned out that way, as you well know.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:5, Page:1, Kor:"그러므로 내가 참다 못하여, 여러분의 믿음을 알아 보려고, 그를 보냈습니다. 그것은, 유혹하는 자가 여러분을 유혹하여 우리의 수고를 헛되게 하지 못하게 하려는 것이었습니다.", Chn:"", Eng:"For this reason, when I could stand it no longer, I sent to find out about your faith. I was afraid that in some way the tempter might have tempted you and our efforts might have been useless.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:6, Page:1, Kor:"○그런데 지금 디모데가 여러분에게서 우리에게로 돌아와서, 여러분의 믿음과 사랑의 기쁜 소식을 전하여 주었습니다. 또, 여러분이 우리를 늘 좋게 생각하고 있어서, 우리가 여러분을 간절히 보고 싶어하는 것과 같이, 여러분도 우리를 간절히 보고 싶어한다고 전하여 주었습니다.", Chn:"", Eng:"But Timothy has just now come to us from you and has brought good news about your faith and love. He has told us that you always have pleasant memories of us and that you long to see us, just as we also long to see you.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:7, Page:1, Kor:"그러므로 b형제자매 여러분, 우리는 여러분을 보고, 우리의 모든 곤경과 환난 가운데서도, 여러분의 믿음으로 말미암아 위로를 받았습니다.(b 그, '형제들')", Chn:"", Eng:"Therefore, brothers, in all our distress and persecution we were encouraged about you because of your faith.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:8, Page:1, Kor:"여러분이 주님 안에 굳게 서 있으면, 이제 우리가 살아 있는 셈이기 때문입니다.", Chn:"", Eng:"For now we really live, since you are standing firm in the Lord.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:9, Page:1, Kor:"우리가 우리 하나님 앞에서, 여러분 때문에 누리는 모든 기쁨을 두고, 여러분을 생각해서, 하나님께 어떠한 감사를 드려야 하겠습니까?", Chn:"", Eng:"How can we thank God enough for you in return for all the joy we have in the presence of our God because of you?", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:10, Page:1, Kor:"우리는 여러분의 얼굴을 볼 수 있기를, 또 여러분의 믿음에 부족한 것을 보충하여 줄 수 있기를 밤낮으로 간절히 빌고 있습니다.", Chn:"", Eng:"Night and day we pray most earnestly that we may see you again and supply what is lacking in your faith.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:11, Page:1, Kor:"○하나님 우리 아버지와 우리 주 예수께서 우리의 길을 친히 열어 주셔서, 우리를 여러분에게로 가게 해 주시기를 간구합니다.", Chn:"", Eng:"Now may our God and Father himself and our Lord Jesus clear the way for us to come to you.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:12, Page:1, Kor:"또, 우리가 여러분을 사랑하는 것과 같이, 주님께서 여러분끼리 서로 나누는 사랑과 모든 사람에게 베푸는 여러분의 사랑을 풍성하게 하고, 넘치게 해 주시기를 빕니다.", Chn:"", Eng:"May the Lord make your love increase and overflow for each other and for everyone else, just as ours does for you.", Ind:""},
  {Bible:"1Thessalonians", Chapter:3, Verse:13, Page:1, Kor:"그래서 주님께서 여러분의 마음을 굳세게 하셔서, 우리 주 예수께서 자기의 모든 성도들과 함께 오실 때에, 하나님 우리 아버지 앞에서 거룩함에 흠 잡힐 데가 없게 해 주시기를 빕니다.", Chn:"", Eng:"May he strengthen your hearts so that you will be blameless and holy in the presence of our God and Father when our Lord Jesus comes with all his holy ones.", Ind:""},
]);
