// 역대하 23장 · 2Chronicles 23
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Chronicles",23,21);
BibleDB.add([
  {Bible:"2Chronicles", Chapter:23, Verse:1, Page:1, Kor:"<아달랴에 대한 반란(왕하 11:4-16)> 여섯 해를 기다린 여호야다 제사장은, 일곱째 해가 되자, 드디어 용기 있게 결단을 내리고, 군대 지휘관들인 백부장들, 곧 여로함의 아들 아사랴와, 여호하난의 아들 이스마엘과, 오벳의 아들 아사랴와, 아다야의 아들 마아세야와, 시그리의 아들 엘리사밧과 밀약을 맺었다.", Chn:"", Eng:"In the seventh year Jehoiada showed his strength. He made a covenant with the commanders of units of a hundred: Azariah son of Jeroham, Ishmael son of Jehohanan, Azariah son of Obed, Maaseiah son of Adaiah, and Elishaphat son of Zicri.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:2, Page:1, Kor:"이들 백부장들은 유다의 모든 성읍으로 돌아다니며, 레위 사람들과 이스라엘 각 가문의 족장들을 모아서, 예루살렘으로 데리고 왔다.", Chn:"", Eng:"They went throughout Judah and gathered the Levites and the heads of Israelite families from all the towns. When they came to Jerusalem,", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:3, Page:1, Kor:"○그들이 모두 하나님의 성전에 모여, 왕의 아들 요아스와 언약을 세웠다. 여호야다가 그들에게 말하였다. \"여기에 왕세자가 계십니다. 이 분이 왕이 되셔야 합니다. 이것은 다윗 자손이 왕이 되어야 한다는 주님의 약속을 따르는 것입니다.", Chn:"", Eng:"the whole assembly made a covenant with the king at the temple of God. Jehoiada said to them, \"The king's son shall reign, as the LORD promised concerning the descendants of David.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:4, Page:1, Kor:"이제 여러분이 하여야 할 일을 말하겠습니다. 이번 안식일에 맡은 일을 하러 오는 당번 제사장들과 레위 사람들은, 여기 성전에 도착하여, 삼분의 일은 성전 문을 지키고,", Chn:"", Eng:"Now this is what you are to do: A third of you priests and Levites who are going on duty on the Sabbath are to keep watch at the doors,", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:5, Page:1, Kor:"또 삼분의 일은 왕궁을 지키고, 나머지는 '기초문'을 지키십시오. 일반 백성은 주님의 성전 뜰로 모입니다.", Chn:"", Eng:"a third of you at the royal palace and a third at the Foundation Gate, and all the other men are to be in the courtyards of the temple of the LORD.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:6, Page:1, Kor:"그 날 일을 맡은 제사장들과 그들을 돕는 레위 사람들 말고는, 어느 누구도 성전 안으로 들어오지 못합니다. 거룩하게 구별된 제사장들과 레위 사람들만 주님의 성전 안으로 들어오고, 그밖의 일반 백성은 주님께서 지시하신 대로 성전 밖에 서 있어야 합니다.", Chn:"", Eng:"No one is to enter the temple of the LORD except the priests and Levites on duty; they may enter because they are consecrated, but all the other men are to guard what the LORD has assigned to them.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:7, Page:1, Kor:"레위 사람들은 제각기 병기를 들고 왕을 호위하십시오. 임금님께서 드나드실 때에는 반드시 경호하도록 하십시오. 그리고 어느 누구라도 이 성전 안으로 들어오려고 하면 모두 죽여야 합니다.\"", Chn:"", Eng:"The Levites are to station themselves around the king, each man with his weapons in his hand. Anyone who enters the temple must be put to death. Stay close to the king wherever he goes.\"", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:8, Page:1, Kor:"○레위 사람들과 모든 유다 사람들은, 여호야다가 명령한 것을 그대로 다 하였다. 여호야다 제사장이 안식일에 맡은 일을 끝낸 사람들마저 집으로 돌아가지 못하게 붙들어 두었으므로, 지휘관들은 안식일 당번인 사람들과 비번인 사람들을 다 데리고 있었다.", Chn:"", Eng:"The Levites and all the men of Judah did just as Jehoiada the priest ordered. Each one took his men--those who were going on duty on the Sabbath and those who were going off duty--for Jehoiada the priest had not released any of the divisions.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:9, Page:1, Kor:"여호야다 제사장이 백부장들에게 창과 크고 작은 방패들을 나누어 주었다. 그것들은 다윗 왕의 것으로서, 하나님의 성전 안에 간직되어 있던 것들이었다.", Chn:"", Eng:"Then he gave the commanders of units of a hundred the spears and the large and small shields that had belonged to King David and that were in the temple of God.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:10, Page:1, Kor:"그는 또 일반 백성에게도 무기를 들려, 성전 남쪽에서 북쪽 끝에 이르기까지 전 지역에 그들을 배치시키고, 제단 근처에서나 성전 안에서 왕을 경호하게 하였다.", Chn:"", Eng:"He stationed all the men, each with his weapon in his hand, around the king--near the altar and the temple, from the south side to the north side of the temple.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:11, Page:1, Kor:"그런 다음에, 여호야다와 그의 아들들이 요아스 왕세자를 데리고 와서, 그에게 왕관을 씌우고, 왕의 직무를 규정한 규례서를 그에게 주고, 기름을 부어 왕으로 삼고 \"임금님 만세!\" 하고 외쳤다.", Chn:"", Eng:"Jehoiada and his sons brought out the king's son and put the crown on him; they presented him with a copy of the covenant and proclaimed him king. They anointed him and shouted, \"Long live the king!\"", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:12, Page:1, Kor:"아달랴가, 백성들이 뛰어 다니며 왕을 찬양하는 소리를 듣고, 주님의 성전에 모여 있는 백성에게로 가서,", Chn:"", Eng:"When Athaliah heard the noise of the people running and cheering the king, she went to them at the temple of the LORD.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:13, Page:1, Kor:"보니, 왕이 성전 어귀 기둥 곁에 서 있고, 관리들과 나팔수들이 왕을 모시고 서 있으며, 나라의 모든 백성이 기뻐하며 나팔을 불고 있고, 성전 성가대원들이 각종 악기로 찬양을 인도하고 있었다. 아달랴는 분을 참지 못하고 옷을 찢으며 \"반역이다! 반역이다!\" 하고 외쳤다.", Chn:"", Eng:"She looked, and there was the king, standing by his pillar at the entrance. The officers and the trumpeters were beside the king, and all the people of the land were rejoicing and blowing trumpets, and singers with musical instruments were leading the praises. Then Athaliah tore her robes and shouted, \"Treason! Treason!\"", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:14, Page:1, Kor:"○그 때에 여호야다 제사장이 군대를 거느린 백부장들을 불러 내어, 그들에게 명령을 내렸다. \"저 여자를 대열 밖으로 끌어 내시오. 저 여자를 따르는 사람도 모두 칼로 쳐죽이시오.\" 여호야다는 주님의 성전 안에서는 그 여자를 죽이지 말라고 하였다.", Chn:"", Eng:"Jehoiada the priest sent out the commanders of units of a hundred, who were in charge of the troops, and said to them: \"Bring her out between the ranks and put to the sword anyone who follows her.\" For the priest had said, \"Do not put her to death at the temple of the LORD.\"", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:15, Page:1, Kor:"○그래서 그들은 그 여자를 이끌고 왕궁 '말의 문' 어귀로 들어가, 거기에서 그 여자를 처형하였다.", Chn:"", Eng:"So they seized her as she reached the entrance of the Horse Gate on the palace grounds, and there they put her to death.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:16, Page:1, Kor:"<여호야다의 개혁(왕하 11:17-20)> ○그런 다음에 여호야다는, 자신과 백성과 왕이 주님의 백성이 되는 언약을 세웠다.", Chn:"", Eng:"Jehoiada then made a covenant that he and the people and the king would be the LORD'S people.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:17, Page:1, Kor:"그렇게 하고 난 다음에, 모든 백성이 바알 신전으로 몰려가서, 그 신전을 허물고, 제단들을 뒤엎고, 신상들을 완전히 부수어 버렸다. 또 그들은 거기 제단 앞에서 바알의 맛단 제사장을 죽였다.", Chn:"", Eng:"All the people went to the temple of Baal and tore it down. They smashed the altars and idols and killed Mattan the priest of Baal in front of the altars.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:18, Page:1, Kor:"여호야다는 주님의 성전을 돌보는 일을 정하여, 그것을 레위 사람 제사장들이 관리하도록 맡겼다. 모세의 율법에 기록된 대로, 주님께 번제를 드리고 즐거운 노래로 주님을 찬양하는 이러한 일들은, 본래 다윗이 성전 안에서 일하는 레위 사람 제사장들에게 맡긴 임무였다.", Chn:"", Eng:"Then Jehoiada placed the oversight of the temple of the LORD in the hands of the priests, who were Levites, to whom David had made assignments in the temple, to present the burnt offerings of the LORD as written in the Law of Moses, with rejoicing and singing, as David had ordered.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:19, Page:1, Kor:"여호야다는 또한 주님의 성전 문마다 문지기를 두어, 부정한 사람은 아무도 들어오지 못하게 하였다.", Chn:"", Eng:"He also stationed doorkeepers at the gates of the LORD'S temple so that no one who was in any way unclean might enter.", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:20, Page:1, Kor:"○여호야다는 백부장들과 귀족들과 백성의 지도자들과 그 땅의 모든 백성들과 함께, 왕을 호위하여 주님의 성전에서 데리고 나와서, 윗문을 지나 왕궁으로 가서, 왕을 왕좌에 앉히니,", Chn:"", Eng:"He took with him the commanders of hundreds, the nobles, the rulers of the people and all the people of the land and brought the king down from the temple of the LORD. They went into the palace through the Upper Gate and seated the king on the royal throne,", Ind:""},
  {Bible:"2Chronicles", Chapter:23, Verse:21, Page:1, Kor:"그 땅의 모든 백성들이 기뻐하였다. 아달랴가 살해된 뒤로, 도성은 평온을 되찾았다.", Chn:"", Eng:"and all the people of the land rejoiced. And the city was quiet, because Athaliah had been slain with the sword.", Ind:""},
]);
