// 역대하 35장 · 2Chronicles 35
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Chronicles",35,27);
BibleDB.add([
  {Bible:"2Chronicles", Chapter:35, Verse:1, Page:1,
    Kor:"<요시야가 유월절을 지키다(왕하 23:21-23)> 요시야는 예루살렘에서, 주님께 유월절을 지켰다. 사람들은 첫째 달 십사일에 유월절 어린 양을 잡았다.",
    Chn:"约西亚在耶路撒冷向耶和华守逾越节。正月十四日，就宰了逾越节的羊羔。",
    Eng:"Josiah celebrated the Passover to the LORD in Jerusalem, and the Passover lamb was slaughtered on the fourteenth day of the first month.",
    Ind:"Kemudian Yosia merayakan Paskah bagi TUHAN di Yerusalem. Domba Paskah disembelih pada tanggal empat belas bulan yang pertama."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:2, Page:1,
    Kor:"왕은 제사장들에게 각자가 해야 할 임무를 맡기고, 주님의 성전에서 할 일들을 잘 하도록 격려하였다.",
    Chn:"王分派祭司各尽其职，又勉励他们办耶和华殿中的事；",
    Eng:"He appointed the priests to their duties and encouraged them in the service of the LORD'S temple.",
    Ind:"Ia menetapkan tugas para imam, dan mendorong mereka menunaikan tugas jabatannya dalam rumah TUHAN."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:3, Page:1,
    Kor:"왕은 또, 주님께 거룩하게 구별되어서, 온 이스라엘을 가르치는 레위 사람들에게도 다음과 같이 지시하였다. \"거룩한 궤는 다윗의 아들, 이스라엘의 솔로몬 왕이 지은 성전 안에 두도록 하십시오. 이제부터 당신들은 그 궤를 어깨에 메어 옮기지 않아도 됩니다. 당신들은 다만 주 당신들 하나님과 그의 백성 이스라엘을 섬기는 일만을 맡게 됩니다.",
    Chn:"又对那归耶和华为圣、教训以色列人的利未人说：「你们将圣约柜安放在以色列王大卫儿子所罗门建造的殿里，不必再用肩扛抬。现在要事奉耶和华—你们的　神，服事他的民以色列。",
    Eng:"He said to the Levites, who instructed all Israel and who had been consecrated to the LORD: \"Put the sacred ark in the temple that Solomon son of David king of Israel built. It is not to be carried about on your shoulders. Now serve the LORD your God and his people Israel.",
    Ind:"Berkatalah ia kepada orang-orang Lewi yang adalah pengajar seluruh Israel dan orang-orang kudus TUHAN: \"Tempatkanlah tabut kudus itu di dalam rumah yang telah didirikan Salomo bin Daud, raja Israel. Tidak usah lagi kamu mengusungnya. Sekarang layanilah TUHAN, Allahmu, dan Israel, umat-Nya!"
  },
  {Bible:"2Chronicles", Chapter:35, Verse:4, Page:1,
    Kor:"당신들은, 이스라엘의 다윗 왕이 글로 써서 지시한 것과 다윗의 아들 솔로몬이 글로 써서 지시한 것을 따라, 가문별, 갈래별로 준비를 하고 있다가,",
    Chn:"你们应当按着宗族，照着班次，遵以色列王大卫和他儿子所罗门所写的，自己预备。",
    Eng:"Prepare yourselves by families in your divisions, according to the directions written by David king of Israel and by his son Solomon.",
    Ind:"Bersiaplah menurut puak-puakmu dan menurut rombonganmu sebagaimana yang dituliskan Daud, raja Israel, dan Salomo, anaknya."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:5, Page:1,
    Kor:"성소에 나가서 당신들의 친족 되는 모든 사람의 가문의 서열을 따라서, 또는 레위 가문의 서열을 따라서, 일을 맡도록 하십시오.",
    Chn:"要按着你们的弟兄，这民宗族的班次，站在圣所，每班中要利未宗族的几个人。",
    Eng:"\"Stand in the holy place with a group of Levites for each subdivision of the families of your fellow countrymen, the lay people.",
    Ind:"Berdirilah di halaman tempat kudus menurut golongan puak saudara-saudaramu yang lain, yakni kaum awam, dengan satu rombongan puak orang Lewi untuk tiap golongan saudara-saudaramu itu."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:6, Page:1,
    Kor:"당신들은 유월절 어린 양과 염소를 잡아야 합니다. 그리고 당신들은 스스로를 정결하게 하십시오. 그리고 동족을 위하여서도 준비하십시오. 이 모든 일은 주님께서 모세를 시켜서 말씀하신 그대로 해야 합니다.\"",
    Chn:"要宰逾越节的羊羔，洁净自己，为你们的弟兄预备了，好遵守耶和华借摩西所吩咐的话。」",
    Eng:"Slaughter the Passover lambs, consecrate yourselves and prepare the lambs for your fellow countrymen, doing what the LORD commanded through Moses.\"",
    Ind:"Sembelihlah domba Paskah, kuduskanlah dirimu, dan adakanlah persiapan bagi saudara-saudaramu, supaya dilakukan apa yang difirmankan TUHAN dengan perantaraan Musa.\""
  },
  {Bible:"2Chronicles", Chapter:35, Verse:7, Page:1,
    Kor:"○요시야는 자기가 가지고 있는 집짐승 떼 가운데서, 어린 양과 어린 염소 삼만 마리와 수소 삼천 마리를 일반 백성들이 유월절 때에 제물로 쓰도록, 백성에게 거저 주었다.",
    Chn:"约西亚从群畜中赐给在那里所有的人民，绵羊羔和山羊羔三万只，牛三千只，作逾越节的祭物；这都是出自王的产业中。",
    Eng:"Josiah provided for all the lay people who were there a total of thirty thousand sheep and goats for the Passover offerings, and also three thousand cattle--all from the king's own possessions.",
    Ind:"Yosia menyumbangkan kepada kaum awam sejumlah tiga puluh ribu ekor kambing domba, yakni domba-domba dan kambing-kambing jantan yang muda, semuanya sebagai korban Paskah bagi semua orang yang hadir. Selain itu disumbangkannya tiga ribu ekor lembu. Semuanya itu dari harta milik raja."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:8, Page:1,
    Kor:"왕의 신하들도 기꺼이 일반 백성과 제사장들과 레위 사람들에게 돌아갈 제물을 자원하여 내놓았다. 하나님의 성전의 최고 책임자인 힐기야와 스가랴와 여히엘은, 제사장들이 유월절 기간에 제물로 쓰도록, 어린 양과 어린 염소 이천육백 마리와 수소 삼백 마리를 내놓았다.",
    Chn:"约西亚的众首领也乐意将牺牲给百姓和祭司利未人；又有管理　神殿的希勒家、撒迦利亚、耶歇将羊羔二千六百只，牛三百只，给祭司作逾越节的祭物。",
    Eng:"His officials also contributed voluntarily to the people and the priests and Levites. Hilkiah, Zechariah and Jehiel, the administrators of God's temple, gave the priests twenty-six hundred Passover offerings and three hundred cattle.",
    Ind:"Juga para panglimanya memberi sumbangan sukarela kepada rakyat, para imam, dan orang-orang Lewi. Kemudian Hilkia, Zakharia dan Yehiel, para pemuka rumah Allah, memberi kepada para imam dua ribu enam ratus ekor kambing domba sebagai korban Paskah dan selain itu tiga ratus ekor lembu."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:9, Page:1,
    Kor:"레위 사람의 지도자들, 곧 고나냐와 그의 동기들인 스마야와 느다넬과 하사뱌와 여이엘과 요사밧은, 레위 사람들이 유월절 제물로 쓰라고, 어린 양과 어린 염소를 합하여, 오천 마리와 소 오백 마리를 내놓았다.",
    Chn:"利未人的族长歌楠雅和他两个兄弟示玛雅、拿坦业，与哈沙比雅、耶利、约撒拔将羊羔五千只，牛五百只，给利未人作逾越节的祭物。",
    Eng:"Also Conaniah along with Shemaiah and Nethanel, his brothers, and Hashabiah, Jeiel and Jozabad, the leaders of the Levites, provided five thousand Passover offerings and five hundred head of cattle for the Levites.",
    Ind:"Lalu Konanya dan kedua saudaranya, Semaya dan Netaneel, serta Hasabya, Yeiel dan Yozabad, para pemimpin orang-orang Lewi, menyumbangkan kepada orang-orang Lewi lima ribu ekor kambing domba sebagai korban Paskah dan selain itu lima ratus ekor lembu."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:10, Page:1,
    Kor:"○유월절을 지킬 제사 준비가 이렇게 다 되었을 때에, 제사장들과 레위 사람들은, 왕이 명령한 대로, 각각 제자리에 섰다.",
    Chn:"这样，供献的事齐备了。祭司站在自己的地方，利未人按着班次站立，都是照王所吩咐的。",
    Eng:"The service was arranged and the priests stood in their places with the Levites in their divisions as the king had ordered.",
    Ind:"Setelah upacara ibadah disiapkan, berdirilah para imam pada tempatnya dan orang-orang Lewi menurut rombongannya sesuai dengan perintah raja."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:11, Page:1,
    Kor:"희생제물인 양과 염소를 잡은 뒤에, 레위 사람들은, 잡은 짐승의 가죽을 벗기고, 제사장들은 손으로 피를 받아 제단에 뿌렸다.",
    Chn:"利未人宰了逾越节的羊羔，祭司从他们手里接过血来洒在坛上；利未人剥皮，",
    Eng:"The Passover lambs were slaughtered, and the priests sprinkled the blood handed to them, while the Levites skinned the animals.",
    Ind:"Maka disembelihlah domba Paskah, dan para imam menyiramkan darah yang mereka terima dari orang-orang Lewi, sedang orang-orang Lewi menguliti domba itu."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:12, Page:1,
    Kor:"그런 다음에, 레위 사람들은, 번제물로 바칠 짐승을 백성에게 가문별로 나누어 주어서, 백성이 모세의 율법에 기록되어 있는 대로 주님께 드리게 하고, 소도 같은 방법으로 하였다.",
    Chn:"将燔祭搬来，按着宗族的班次分给众民，好照摩西书上所写的，献给耶和华；献牛也是这样。",
    Eng:"They set aside the burnt offerings to give them to the subdivisions of the families of the people to offer to the LORD, as is written in the Book of Moses. They did the same with the cattle.",
    Ind:"Tetapi mereka memisahkan korban bakaran untuk diserahkan kepada kaum awam menurut golongan puak mereka, supaya dipersembahkan kepada TUHAN sebagaimana tertulis dalam kitab Musa. Demikian pula dilakukan mereka dengan lembu-lembu."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:13, Page:1,
    Kor:"레위 사람들은 유월절 어린 양을 규례에 따라서 불에 굽고, 나머지 거룩한 제물은 솥과 가마와 냄비에 삶아 모든 백성에게 속히 분배하였다.",
    Chn:"他们按着常例，用火烤逾越节的羊羔。别的圣物用锅，用釜，用罐煮了，速速地送给众民。",
    Eng:"They roasted the Passover animals over the fire as prescribed, and boiled the holy offerings in pots, caldrons and pans and served them quickly to all the people.",
    Ind:"Kemudian mereka memasak domba Paskah di atas api sesuai dengan peraturan, sedang persembahan-persembahan kudus mereka masak dalam kuali, belanga dan pinggan, lalu membawanya cepat-cepat kepada segenap kaum awam."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:14, Page:1,
    Kor:"이렇게 하고 난 뒤에, 그들은 자신들과 아론의 자손 제사장들 몫을 준비하였다. 그것은 제사장들이, 번제로 바치는 짐승들을 불에 태우고, 희생제물의 기름기를 태우느라고, 밤까지 바빴기 때문이다. 그래서 레위 사람들은 자신들과 아론의 자손 제사장들 몫을 준비하였던 것이다.",
    Chn:"然后为自己和祭司预备祭物；因为祭司亚伦的子孙献燔祭和脂油，直到晚上。所以利未人为自己和祭司亚伦的子孙，预备祭物。",
    Eng:"After this, they made preparations for themselves and for the priests, because the priests, the descendants of Aaron, were sacrificing the burnt offerings and the fat portions until nightfall. So the Levites made preparations for themselves and for the Aaronic priests.",
    Ind:"Kemudian mereka menyediakannya bagi dirinya dan bagi para imam, karena para imam, yakni anak-anak Harun, sampai malam hari sibuk mempersembahkan korban bakaran dan segala lemak. Oleh sebab itu orang-orang Lewi menyediakannya bagi dirinya dan bagi para imam, yakni anak-anak Harun."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:15, Page:1,
    Kor:"노래하는 사람들, 곧 아삽의 자손은, 다윗과 아삽과 헤만과 왕의 선견자 여두둔의 지시를 따라 각자 지정된 자리에 서 있었고, 문지기들은 각자가 책임 맡은 문을 지키고 있었다. 노래하는 사람들이나 문을 지키는 사람들이 그들의 근무 장소에서 떠나지 않아도 되었던 것은, 그들의 친족 레위 사람들이 그들의 몫을 준비하여 주었기 때문이다.",
    Chn:"歌唱的亚萨之子孙，照着大卫、亚萨、希幔，和王的先见耶杜顿所吩咐的，站在自己的地位上。守门的看守各门，不用离开他们的职事，因为他们的弟兄利未人给他们预备祭物。",
    Eng:"The musicians, the descendants of Asaph, were in the places prescribed by David, Asaph, Heman and Jeduthun the king's seer. The gatekeepers at each gate did not need to leave their posts, because their fellow Levites made the preparations for them.",
    Ind:"Para penyanyi, yakni bani Asaf, ada pada tempat mereka sesuai dengan perintah Daud, Asaf, Heman dan Yedutun, pelihat raja itu; juga para penunggu pintu gerbang ada pada tiap-tiap pintu gerbang. Mereka tidak usah meninggalkan tugas mereka, karena saudara-saudara mereka, orang-orang Lewi, menyediakannya untuk mereka."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:16, Page:1,
    Kor:"이와 같이, 그 날에 요시야 왕이 명령한 대로, 모든 일이 다 잘 준비되어 주님께 예배를 드릴 수 있었다. 사람들은 유월절을 지키며, 주님의 단에 번제를 드렸다.",
    Chn:"当日，供奉耶和华的事齐备了，就照约西亚王的吩咐守逾越节，献燔祭在耶和华的坛上。",
    Eng:"So at that time the entire service of the LORD was carried out for the celebration of the Passover and the offering of burnt offerings on the altar of the LORD, as King Josiah had ordered.",
    Ind:"Demikianlah seluruh upacara ibadah bagi TUHAN disiapkan pada hari itu untuk merayakan Paskah dan untuk mempersembahkan korban bakaran di atas mezbah TUHAN sesuai dengan perintah raja Yosia."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:17, Page:1,
    Kor:"그 때에 거기 모인 이스라엘 자손은 유월절을 지키고, 이어서 이레 동안 무교절을 지켰다.",
    Chn:"当时在耶路撒冷的以色列人守逾越节，又守除酵节七日。",
    Eng:"The Israelites who were present celebrated the Passover at that time and observed the Feast of Unleavened Bread for seven days.",
    Ind:"Pada waktu itu orang Israel yang hadir di situ merayakan Paskah dan hari raya Roti Tidak Beragi selama tujuh hari."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:18, Page:1,
    Kor:"예언자 사무엘 이후로 이스라엘 안에서 이처럼 유월절을 지킨 예가 없었고, 이스라엘의 역대 왕들 가운데서도, 요시야가 제사장들과 레위 사람들과 그 때에 거기 모인 온 유다와 이스라엘 사람들과 예루살렘 주민들과 함께 지킨 그런 유월절은, 일찍이 지켜 본 왕이 없었다.",
    Chn:"自从先知撒母耳以来，在以色列中没有守过这样的逾越节，以色列诸王也没有守过，像约西亚、祭司、利未人、在那里的犹大人，和以色列人，以及耶路撒冷居民所守的逾越节。",
    Eng:"The Passover had not been observed like this in Israel since the days of the prophet Samuel; and none of the kings of Israel had ever celebrated such a Passover as did Josiah, with the priests, the Levites and all Judah and Israel who were there with the people of Jerusalem.",
    Ind:"Paskah semacam itu tidak pernah lagi dirayakan di Israel sejak nabi Samuel. Seorangpun di antara raja-raja orang Israel tidak pernah merayakan Paskah seperti yang dirayakan Yosia dengan para imam dan orang-orang Lewi, dengan seluruh orang Yehuda dan Israel yang dapat hadir, dan dengan penduduk Yerusalem."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:19, Page:1,
    Kor:"유월절을 이렇게 지킨 것은 요시야가 나라를 다스린 지 열여덟째 해가 되던 때의 일이다.",
    Chn:"这逾越节是约西亚作王十八年守的。",
    Eng:"This Passover was celebrated in the eighteenth year of Josiah's reign.",
    Ind:"Paskah itu dirayakan pada tahun kedelapan belas pemerintahan Yosia."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:20, Page:1,
    Kor:"<요시야의 통치가 끝나다(왕하 23:28-30)> ○이런 모든 일이 일어난 뒤, 곧 요시야가 성전 정돈을 마치고 난 뒤에, 이집트의 느고 왕이 유프라테스 강 가에 있는 갈그미스를 치려고 올라왔으므로, 요시야가 그것을 막으러 나갔다.",
    Chn:"这事以后，约西亚修完了殿，有埃及王尼哥上来，要攻击靠近幼发拉底河的迦基米施；约西亚出去抵挡他。",
    Eng:"After all this, when Josiah had set the temple in order, Neco king of Egypt went up to fight at Carchemish on the Euphrates, and Josiah marched out to meet him in battle.",
    Ind:"Kemudian dari pada semua ini, setelah Yosia memperbaiki rumah TUHAN, majulah Nekho, raja Mesir, hendak berperang di Karkemis di tepi sungai Efrat. Yosia keluar menghadapinya."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:21, Page:1,
    Kor:"느고가 요시야에게 전령을 보내어 말하였다. \"유다의 왕은 들으시오. 왕은 왜 나의 일에 관여하려고 하오? 나는 오늘 왕을 치려고 온 것이 아니라, 나와 싸움이 벌어진 족속을 치려고 나선 것이오. 하나님께서 나에게, 속히 가라고 명하셨소. 그러니 하나님이 나와 함께 계시오. 하나님께 멸망을 당하지 아니하려거든, 하나님을 거역하는 이 일을 어서 멈추시오.\"",
    Chn:"他差遣使者来见约西亚，说：「犹大王啊，我与你何干？我今日来不是要攻击你，乃是要攻击与我争战之家，并且　神吩咐我速行，你不要干预　神的事，免得他毁灭你，因为　神是与我同在。」",
    Eng:"But Neco sent messengers to him, saying, \"What quarrel is there between you and me, O king of Judah? It is not you I am attacking at this time, but the house with which I am at war. God has told me to hurry; so stop opposing God, who is with me, or he will destroy you.\"",
    Ind:"Ia mengirim utusan kepada Yosia, dengan pesan: \"Apakah urusanmu dengan aku, raja Yehuda? Saat ini aku tidak datang melawan engkau, tetapi melawan keluarga raja yang sedang kuperangi. Allah memerintahkan aku supaya segera bertindak. Hentikanlah niatmu menentang Allah yang menyertai aku, supaya engkau jangan dimusnahkan-Nya!\""
  },
  {Bible:"2Chronicles", Chapter:35, Verse:22, Page:1,
    Kor:"그러나 요시야는 그에게서 돌이켜 되돌아가지 않고, 느고와 싸우려고 변장까지 하였다. 이처럼 요시야는, 하나님께서 느고를 시켜서 하시는 말씀을 듣지 아니하고, 므깃도 평원으로 진군하여 가서 싸웠다.",
    Chn:"约西亚却不肯转去离开他，改装要与他打仗，不听从　神借尼哥之口所说的话，便来到米吉多平原争战。",
    Eng:"Josiah, however, would not turn away from him, but disguised himself to engage him in battle. He would not listen to what Neco had said at God's command but went to fight him on the plain of Megiddo.",
    Ind:"Tetapi Yosia tidak berpaling dari padanya, melainkan menyamar untuk berperang melawan dia. Ia tidak mengindahkan kata-kata Nekho, yang merupakan pesan Allah, lalu berperang di lembah Megido."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:23, Page:1,
    Kor:"○그 때에, 적군이 쏜 화살이 요시야 왕에게 박혔다. 왕이 자기 부하들에게 명령하였다. \"내가 크게 다쳤다. 내가 여기서 빠져 나가도록, 나를 도와라.\"",
    Chn:"弓箭手射中约西亚王。王对他的臣仆说：「我受了重伤，你拉我出阵吧！」",
    Eng:"Archers shot King Josiah, and he told his officers, \"Take me away; I am badly wounded.\"",
    Ind:"Maka pemanah-pemanah menembaki raja Yosia, dan raja berseru kepada orang-orangnya: \"Bawa aku dari sini, karena aku luka parah!\""
  },
  {Bible:"2Chronicles", Chapter:35, Verse:24, Page:1,
    Kor:"그는 부하들의 부축을 받으면서 자기의 병거에서 내려, 그의 부사령관의 병거를 타고 예루살렘으로 돌아와, 숨을 거두었다. 사람들은 그를 그의 조상들의 묘에 장사하였다. 온 유다와 예루살렘 사람들이 그의 죽음을 슬퍼하였다.",
    Chn:"他的臣仆扶他下了战车，上了次车，送他到耶路撒冷，他就死了，葬在他列祖的坟墓里。犹大人和耶路撒冷人都为他悲哀。",
    Eng:"So they took him out of his chariot, put him in the other chariot he had and brought him to Jerusalem, where he died. He was buried in the tombs of his fathers, and all Judah and Jerusalem mourned for him.",
    Ind:"Orang-orangnya mengangkatnya dari keretanya, lalu mengangkutnya dengan kereta cadangannya lalu membawanya ke Yerusalem. Kemudian matilah ia, lalu dikuburkan di pekuburan nenek moyangnya. Seluruh Yehuda dan Yerusalem berkabung karena Yosia."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:25, Page:1,
    Kor:"○예레미야 예언자가 요시야의 전사를 애도하는 애가를 지었는데, 노래하는 남녀가 요시야 왕을 애도할 때에는, 이 애가를 부르는 것이 관례가 되어 오늘까지 이른다. 그 가사는 '애가집'에 기록되어 있다.",
    Chn:"耶利米为约西亚作哀歌。所有歌唱的男女也唱哀歌，追悼约西亚，直到今日；而且在以色列中成了定例。这歌载在哀歌书上。",
    Eng:"Jeremiah composed laments for Josiah, and to this day all the men and women singers commemorate Josiah in the laments. These became a tradition in Israel and are written in the Laments.",
    Ind:"Yeremia membuat suatu syair ratapan mengenai Yosia. Dan sampai sekarang ini semua penyanyi laki-laki dan penyanyi perempuan menyanyikan syair-syair ratapan mengenai Yosia, dan mereka jadikan itu suatu kebiasaan di Israel. Semuanya itu tertulis dalam Syair-syair Ratapan."
  },
  {Bible:"2Chronicles", Chapter:35, Verse:26, Page:1,
    Kor:"○요시야의 남은 사적, 곧 그가 주님의 율법에 기록된 대로 한 모든 선한 일과,",
    Chn:"约西亚其余的事和他遵着耶和华律法上所记而行的善事，",
    Eng:"The other events of Josiah's reign and his acts of devotion, according to what is written in the Law of the LORD--",
    Ind:"Selebihnya dari riwayat Yosia dan perbuatan-perbuatannya yang saleh yang sesuai dengan yang ada tertulis dalam Taurat TUHAN,"
  },
  {Bible:"2Chronicles", Chapter:35, Verse:27, Page:1,
    Kor:"그의 업적은, 처음부터 끝까지 '이스라엘과 유다 열왕기'에 기록되어 있다.",
    Chn:"并他自始至终所行的，都写在以色列和犹大列王记上。",
    Eng:"all the events, from beginning to end, are written in the book of the kings of Israel and Judah.",
    Ind:"yakni, riwayatnya dari awal sampai akhir, sesungguhnya semuanya itu tertulis dalam kitab raja-raja Israel dan Yehuda."
  },
]);
