// 역대하 6장 · 2Chronicles 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Chronicles",6,42);
BibleDB.add([
  {Bible:"2Chronicles", Chapter:6, Verse:1, Page:1,
    Kor:"<솔로몬의 성전 봉헌(왕상 8:12-21)> 그런 가운데 솔로몬이 주님께 아뢰었다. \"주님께서는 캄캄한 구름 속에 계시겠다고 말씀하셨습니다.",
    Chn:"那时，所罗门说： 耶和华曾说他必住在幽暗之处。",
    Eng:"Then Solomon said, \"The LORD has said that he would dwell in a dark cloud;",
    Ind:"Pada waktu itu berkatalah Salomo: \"TUHAN telah memutuskan untuk diam dalam kekelaman."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:2, Page:1,
    Kor:"이제 주님께서 계시라고, 내가 이 웅장한 집을 지었습니다. 이 집은 주님께서 영원히 계실 곳입니다.\"",
    Chn:"但我已经建造殿宇作你的居所， 为你永远的住处。",
    Eng:"I have built a magnificent temple for you, a place for you to dwell forever.\"",
    Ind:"Sekarang, aku telah mendirikan rumah kediaman bagi-Mu, tempat Engkau menetap selama-lamanya.\""
  },
  {Bible:"2Chronicles", Chapter:6, Verse:3, Page:1,
    Kor:"○그런 다음에, 왕은 얼굴을 돌려, 거기에 서 있는 이스라엘 온 회중을 둘러보며, 그들에게 복을 빌어 주었다.",
    Chn:"王转脸为以色列会众祝福，以色列会众就都站立。",
    Eng:"While the whole assembly of Israel was standing there, the king turned around and blessed them.",
    Ind:"Kemudian berpalinglah raja lalu memberkati seluruh jemaah Israel, sedang segenap jemaah Israel berdiri."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:4, Page:1,
    Kor:"그는 말하였다. ○\"주 이스라엘의 하나님을 찬양하십시오. 주님께서는 내 아버지 다윗에게 친히 말씀하신 것을 모두 그대로 이루어 주셨습니다. 주님께서 말씀하시기를,",
    Chn:"所罗门说：「耶和华—以色列的　神是应当称颂的！因他亲口向我父大卫所应许的，也亲手成就了。",
    Eng:"Then he said: \"Praise be to the LORD, the God of Israel, who with his hands has fulfilled what he promised with his mouth to my father David. For he said,",
    Ind:"Ia berkata: \"Terpujilah TUHAN, Allah orang Israel, yang telah menyelesaikan dengan tangan-Nya apa yang difirmankan-Nya dengan mulut-Nya kepada Daud, ayahku, demikian:"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:5, Page:1,
    Kor:"'내가 내 백성을 이집트 땅에서 이끌어 낸 날부터 오늘에 이르기까지, 내가 내 이름을 기릴 집을 지으려고, 이스라엘 어느 지파에서 어느 성읍을 택한 일이 없다. 또 내 백성 이스라엘을 다스릴 영도자를 삼으려고, 어느 누구도 택한 바가 없다.",
    Chn:"他说：『自从我领我民出埃及地以来，我未曾在以色列众支派中选择一城建造殿宇为我名的居所，也未曾拣选一人作我民以色列的君；",
    Eng:"'Since the day I brought my people out of Egypt, I have not chosen a city in any tribe of Israel to have a temple built for my Name to be there, nor have I chosen anyone to be the leader over my people Israel.",
    Ind:"Sejak Aku membawa umat-Ku keluar dari tanah Mesir, tidak ada kota yang Kupilih di antara segala suku Israel untuk mendirikan rumah di sana sebagai tempat kediaman nama-Ku, dan tidak ada orang yang Kupilih untuk menjadi raja atas umat-Ku Israel."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:6, Page:1,
    Kor:"그러나 이제는 내 이름을 둘 곳으로 예루살렘을 택하였고, 내 백성 이스라엘을 다스릴 사람으로 다윗을 택하였다' 하셨습니다.",
    Chn:"但选择耶路撒冷为我名的居所，又拣选大卫治理我民以色列。』」",
    Eng:"But now I have chosen Jerusalem for my Name to be there, and I have chosen David to rule my people Israel.'",
    Ind:"Tetapi kemudian Aku memilih Yerusalem sebagai tempat kediaman nama-Ku dan memilih Daud untuk berkuasa atas umat-Ku Israel."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:7, Page:1,
    Kor:"○내 아버지 다윗께서는 주 이스라엘의 하나님의 이름을 기릴 성전을 지으려고 생각하셨으나,",
    Chn:"所罗门说：「我父大卫曾立意要为耶和华—以色列　神的名建殿，",
    Eng:"\"My father David had it in his heart to build a temple for the Name of the LORD, the God of Israel.",
    Ind:"Ketika Daud, ayahku, bermaksud mendirikan rumah untuk nama TUHAN, Allah Israel,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:8, Page:1,
    Kor:"주님께서 내 아버지 다윗에게 이르시기를 '네가 내 이름을 기릴 성전을 지으려는 마음을 품은 것은 아주 좋은 일이다.",
    Chn:"耶和华却对我父大卫说：『你立意要为我的名建殿，这意思甚好；",
    Eng:"But the LORD said to my father David, 'Because it was in your heart to build a temple for my Name, you did well to have this in your heart.",
    Ind:"berfirmanlah TUHAN kepadanya: Engkau bermaksud mendirikan rumah untuk nama-Ku, dan maksudmu itu memanglah baik;"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:9, Page:1,
    Kor:"그런데 그 집을 지을 사람은 네가 아니다. 네 몸에서 태어날 네 아들이 내 이름을 기릴 성전을 지을 것이다' 하셨습니다.",
    Chn:"只是你不可建殿，惟你所生的儿子必为我名建殿。』",
    Eng:"Nevertheless, you are not the one to build the temple, but your son, who is your own flesh and blood--he is the one who will build the temple for my Name.'",
    Ind:"hanya, bukanlah engkau yang akan mendirikan rumah itu, melainkan anak kandungmu yang akan lahir kelak, dialah yang akan mendirikan rumah itu untuk nama-Ku."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:10, Page:1,
    Kor:"○주님께서 말씀하신 대로, 아버지 다윗의 뒤를 이어서, 이렇게 내가 이스라엘의 왕위를 이었으며, 주 이스라엘의 하나님의 이름을 기릴 성전을 지었으니, 주님께서는 이제 그 약속을 이루셨습니다.",
    Chn:"「现在耶和华成就了他所应许的话，使我接续我父大卫坐以色列的国位，是照耶和华所说的，又为耶和华—以色列　神的名建造了殿。",
    Eng:"\"The LORD has kept the promise he made. I have succeeded David my father and now I sit on the throne of Israel, just as the LORD promised, and I have built the temple for the Name of the LORD, the God of Israel.",
    Ind:"Jadi TUHAN telah menepati janji yang telah diucapkan-Nya; aku telah bangkit menggantikan Daud, ayahku, dan telah duduk di atas takhta kerajaan Israel, seperti yang difirmankan TUHAN; aku telah mendirikan rumah ini untuk nama TUHAN, Allah Israel,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:11, Page:1,
    Kor:"그리고 나는, 주님께서 이스라엘 자손과 더불어 세우신 언약을 넣은 궤를 여기에 옮겨다 놓았습니다.\"",
    Chn:"我将约柜安置在其中，柜内有耶和华的约，就是他与以色列人所立的约。」",
    Eng:"There I have placed the ark, in which is the covenant of the LORD that he made with the people of Israel.\"",
    Ind:"dan telah menempatkan di sana tabut, yang memuat perjanjian yang telah diikat TUHAN dengan orang Israel.\""
  },
  {Bible:"2Chronicles", Chapter:6, Verse:12, Page:1,
    Kor:"<솔로몬의 봉헌 기도(왕상 8:22-53)> ○그런 다음에, 솔로몬은 이스라엘 온 회중이 보는 데서, 주님의 제단 앞에 서서, 두 팔을 들어 폈다.",
    Chn:"所罗门当着以色列会众，站在耶和华的坛前，举起手来，",
    Eng:"Then Solomon stood before the altar of the LORD in front of the whole assembly of Israel and spread out his hands.",
    Ind:"Kemudian berdirilah ia di depan mezbah TUHAN di hadapan segenap jemaah Israel, lalu menadahkan tangannya;"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:13, Page:1,
    Kor:"솔로몬이 일찍이 놋쇠로, 길이 다섯 자, 너비 다섯 자, 높이 석 자인 대를 만들어 뜰 가운데 놓았는데, 바로 그 대에 올라가서, 이스라엘 온 회중 앞에서 무릎을 꿇고 하늘을 바라보며, 두 팔을 들어 펴고,",
    Chn:"（所罗门曾造一个铜台，长五肘，宽五肘，高三肘，放在院中）就站在台上，当着以色列的会众跪下，向天举手，",
    Eng:"Now he had made a bronze platform, five cubits long, five cubits wide and three cubits high, and had placed it in the center of the outer court. He stood on the platform and then knelt down before the whole assembly of Israel and spread out his hands toward heaven.",
    Ind:"--karena Salomo telah membuat sebuah mimbar tembaga yang panjangnya lima hasta, lebarnya lima hasta dan tingginya tiga hasta, yang ditaruhnya di halaman--;ia berdiri di atasnya lalu berlutut di hadapan segenap jemaah Israel dan menadahkan tangannya ke langit,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:14, Page:1,
    Kor:"이렇게 기도하였다. ○\"주 이스라엘의 하나님, 하늘에나 땅에나, 그 어디에도 주님과 같은 하나님은 없습니다. 주님은, 온 마음을 다 기울여 주님의 뜻을 따라 사는 주님의 종들에게는, 언약을 지키시고 은혜를 베푸시는 분이십니다.",
    Chn:"说：「耶和华—以色列的　神啊，天上地下没有神可比你的！你向那尽心行在你面前的仆人守约施慈爱；",
    Eng:"He said: \"O LORD, God of Israel, there is no God like you in heaven or on earth--you who keep your covenant of love with your servants who continue wholeheartedly in your way.",
    Ind:"sambil berkata: \"Ya TUHAN, Allah Israel! Tidak ada Allah seperti Engkau di langit dan di bumi; Engkau yang memelihara perjanjian dan kasih setia kepada hamba-hamba-Mu yang dengan segenap hatinya hidup di hadapan-Mu;"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:15, Page:1,
    Kor:"주님께서는 주님의 종인 내 아버지 다윗 임금에게 약속하신 것을 지키셨으며, 주님께서 친히 그에게 말씀하신 것을 오늘 이렇게 손수 이루어 주셨습니다.",
    Chn:"向你仆人—我父大卫所应许的话现在应验了。你亲口应许，亲手成就，正如今日一样。",
    Eng:"You have kept your promise to your servant David my father; with your mouth you have promised and with your hand you have fulfilled it--as it is today.",
    Ind:"Engkau yang tetap berpegang pada janji-Mu terhadap hamba-Mu Daud, ayahku, dan yang telah menggenapi dengan tangan-Mu apa yang Kaufirmankan dengan mulut-Mu, seperti yang terjadi pada hari ini."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:16, Page:1,
    Kor:"이제 주 이스라엘의 하나님, 주님께서 주님의 종인 내 아버지 다윗 임금에게 말씀하시기를 '네 자손이 저마다 길을 삼가서, 네가 내 앞에서 살아온 것같이 내 율법대로 살기만 하면, 네 자손 가운데서 이스라엘 왕위에 앉을 사람이, 내 앞에서 끊어지지 않게 하겠다' 하고 약속하신 것을, 지켜 주시기를 바랍니다.",
    Chn:"耶和华—以色列的　神啊，你所应许你仆人—我父大卫的话说：『你的子孙若谨慎自己的行为，遵守我的律法，像你在我面前所行的一样，就不断人坐以色列的国位。』现在求你应验这话。",
    Eng:"\"Now LORD, God of Israel, keep for your servant David my father the promises you made to him when you said, 'You shall never fail to have a man to sit before me on the throne of Israel, if only your sons are careful in all they do to walk before me according to my law, as you have done.'",
    Ind:"Maka sekarang, ya TUHAN, Allah Israel, peliharalah apa yang Kaujanjikan kepada hamba-Mu Daud, ayahku, dengan berkata: Keturunanmu takkan terputus di hadapan-Ku dan tetap akan duduk di atas takhta kerajaan Israel, asal anak-anakmu tetap hidup menurut hukum-Ku sama seperti engkau hidup di hadapan-Ku."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:17, Page:1,
    Kor:"이제 주 이스라엘의 하나님, 주님의 종인 다윗 임금에게 약속하신 말씀을, 주님께서 이루어 주시기를 빕니다.",
    Chn:"耶和华—以色列的　神啊，求你成就向你仆人大卫所应许的话。",
    Eng:"And now, O LORD, God of Israel, let your word that you promised your servant David come true.",
    Ind:"Maka sekarang, ya TUHAN, Allah Israel, biarlah terbukti kebenaran firman-Mu yang telah Kauucapkan kepada hamba-Mu Daud."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:18, Page:1,
    Kor:"○그러나 하나님, 하나님께서 사람과 함께 땅 위에 계시기를 우리가 어찌 바라겠습니까? 저 하늘, 저 하늘 위의 하늘이라도 주님을 모시기에 부족할 터인데, 내가 지은 이 성전이야 더 말해 무엇 하겠습니까?",
    Chn:"「　神果真与世人同住在地上吗？看哪，天和天上的天尚且不足你居住的，何况我所建的这殿呢？",
    Eng:"\"But will God really dwell on earth with men? The heavens, even the highest heavens, cannot contain you. How much less this temple I have built!",
    Ind:"Tetapi benarkah Allah hendak diam bersama dengan manusia di atas bumi? Sesungguhnya langit, bahkan langit yang mengatasi segala langitpun tidaklah dapat memuat Engkau, terlebih lagi rumah yang kudirikan ini."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:19, Page:1,
    Kor:"그러나 주 나의 하나님, 주님의 종이 드리는 기도와 간구를 돌아보시며, 주님의 종이 주님 앞에서 부르짖으며 드리는 이 기도를 들어주십시오.",
    Chn:"惟求耶和华—我的　神垂顾仆人的祷告祈求，俯听仆人在你面前的祈祷呼吁。",
    Eng:"Yet give attention to your servant's prayer and his plea for mercy, O LORD my God. Hear the cry and the prayer that your servant is praying in your presence.",
    Ind:"Maka berpalinglah kepada doa dan permohonan hamba-Mu ini, ya TUHAN Allahku, dengarkanlah seruan dan doa yang hamba-Mu panjatkan di hadapan-Mu ini!"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:20, Page:1,
    Kor:"주님께서 낮이나 밤이나 눈을 뜨시고, 이 성전을 살펴 주십시오. 이 곳은 주님께서 주님의 이름을 두시겠다고 말씀하신 곳입니다. 주님의 종이 이 곳을 바라보며 기도할 때에, 이 종의 기도를 들어주십시오.",
    Chn:"愿你昼夜看顾这殿，就是你应许立为你名的居所；求你垂听仆人向此处祷告的话。",
    Eng:"May your eyes be open toward this temple day and night, this place of which you said you would put your Name there. May you hear the prayer your servant prays toward this place.",
    Ind:"Kiranya mata-Mu terbuka terhadap rumah ini, siang dan malam, terhadap tempat yang Kaukatakan akan menjadi kediaman nama-Mu--dengarkanlah doa yang hamba-Mu panjatkan di tempat ini."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:21, Page:1,
    Kor:"그리고 주님의 종인 나와 주님의 백성 이스라엘이 이 곳을 바라보며 기도할 때에, 그 기도를 들어주십시오. 주님께서 계시는 곳, 하늘에서 들으시고, 들으시는 대로 용서해 주십시오.",
    Chn:"你仆人和你民以色列向此处祈祷的时候，求你从天上你的居所垂听，垂听而赦免。",
    Eng:"Hear the supplications of your servant and of your people Israel when they pray toward this place. Hear from heaven, your dwelling place; and when you hear, forgive.",
    Ind:"Dan dengarkanlah permohonan hamba-Mu dan umat-Mu Israel yang mereka panjatkan di tempat ini; bahwa Engkau juga yang mendengarnya dari tempat kediaman-Mu, dari sorga; dan apabila Engkau mendengarnya, maka Engkau akan mengampuni."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:22, Page:1,
    Kor:"○사람이 이웃에게 죄를 짓고, 맹세를 하게 되어, 그가 이 성전 안에 있는 주님의 제단 앞에 나와서 맹세를 하거든,",
    Chn:"「人若得罪邻舍，有人叫他起誓，他来到这殿，在你的坛前起誓，",
    Eng:"\"When a man wrongs his neighbor and is required to take an oath and he comes and swears the oath before your altar in this temple,",
    Ind:"Jika seseorang telah berdosa kepada temannya, lalu diwajibkan mengangkat sumpah dengan mengutuk dirinya, dan ia datang bersumpah ke depan mezbah-Mu di dalam rumah ini,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:23, Page:1,
    Kor:"주님께서는 하늘에서 들으시고 주님의 종들을 심판하시되, 악행을 저지른 사람은 죄가 있다고 판결하셔서 벌을 주시고, 옳은 일을 한 사람은 죄가 없다고 판결하셔서 그의 의로움을 밝혀 주십시오.",
    Chn:"求你从天上垂听，判断你的仆人，定恶人有罪，照他所行的报应在他头上；定义人有理，照他的义赏赐他。",
    Eng:"then hear from heaven and act. Judge between your servants, repaying the guilty by bringing down on his own head what he has done. Declare the innocent not guilty and so establish his innocence.",
    Ind:"maka Engkaupun hendaklah mendengar dari sorga dan bertindak serta mengadili hamba-hamba-Mu, yakni membalas perbuatan orang bersalah dengan menanggungkannya kepada orang itu sendiri, tetapi membenarkan orang yang benar dengan membalaskan kepadanya sesuai dengan kebenarannya."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:24, Page:1,
    Kor:"○주님의 백성 이스라엘이 주님께 죄를 지어 적에게 패배했다가도, 그들이 뉘우치고 돌아와서, 주님의 이름을 인정하고 이 성전에서 주님께 빌며 간구하거든,",
    Chn:"「你的民以色列若得罪你，败在仇敌面前，又回心转意承认你的名，在这殿里向你祈求祷告，",
    Eng:"\"When your people Israel have been defeated by an enemy because they have sinned against you and when they turn back and confess your name, praying and making supplication before you in this temple,",
    Ind:"Apabila umat-Mu Israel terpukul kalah oleh musuhnya karena mereka berdosa kepada-Mu, kemudian mereka berbalik dan mengakui nama-Mu, dan mereka berdoa dan memohon di hadapan-Mu di rumah ini,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:25, Page:1,
    Kor:"주님께서는 하늘에서 들으시고, 주님의 백성 이스라엘의 죄를 용서해 주십시오. 그리고 그들과 그들의 조상들에게 주신 땅으로, 그들을 다시 돌아오게 해주십시오.",
    Chn:"求你从天上垂听，赦免你民以色列的罪，使他们归回你赐给他们和他们列祖之地。",
    Eng:"then hear from heaven and forgive the sin of your people Israel and bring them back to the land you gave to them and their fathers.",
    Ind:"maka Engkaupun kiranya mendengar dari sorga dan mengampuni dosa umat-Mu Israel dan mengembalikan mereka ke tanah yang telah Kauberikan kepada mereka dan nenek moyang mereka."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:26, Page:1,
    Kor:"○또 그들이 주님께 죄를 지어서, 그 벌로 주님께서 하늘을 닫고 비를 내려 주시지 않을 때에라도, 그들이 이 곳을 바라보며 기도하고, 주님의 이름을 인정하고, 그 죄에서 돌이키거든,",
    Chn:"「你的民因得罪你，你惩罚他们，使天闭塞不下雨，他们若向此处祷告，承认你的名，离开他们的罪，",
    Eng:"\"When the heavens are shut up and there is no rain because your people have sinned against you, and when they pray toward this place and confess your name and turn from their sin because you have afflicted them,",
    Ind:"Apabila langit tertutup, sehingga tidak ada hujan, sebab mereka berdosa kepada-Mu, lalu mereka berdoa di tempat ini dan mengakui nama-Mu dan mereka berbalik dari dosanya, sebab Engkau telah menindas mereka,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:27, Page:1,
    Kor:"주님께서는 하늘에서 들으시고, 주님의 종들과 주님의 백성 이스라엘의 죄를 용서해 주시고, 그들이 살아갈 올바른 길을 그들에게 가르쳐 주시며, 주님의 백성에게 유산으로 주신 주님의 땅에 비를 다시 내려 주십시오.",
    Chn:"求你在天上垂听，赦免你仆人和你民以色列的罪，将当行的善道指教他们，且降雨在你的地，就是你赐给你民为业之地。",
    Eng:"then hear from heaven and forgive the sin of your servants, your people Israel. Teach them the right way to live, and send rain on the land you gave your people for an inheritance.",
    Ind:"maka Engkaupun kiranya mendengarkannya di sorga dan mengampuni dosa hamba-hamba-Mu, umat-Mu Israel, --karena Engkaulah yang menunjukkan kepada mereka jalan yang baik yang harus mereka jalani--dan Engkau kiranya memberikan hujan kepada tanah-Mu yang telah Kauberikan kepada umat-Mu menjadi milik pusaka."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:28, Page:1,
    Kor:"○이 땅에 기근이 들거나, 역병이 돌거나, 곡식이 시들거나, 깜부기가 나거나, 메뚜기 떼나 누리 떼가 곡식을 갉아먹거나, 또는 적들이 이 땅으로 쳐들어와서 성읍들 가운데 어느 하나를 에워싸거나, 온갖 재앙이 내리거나, 온갖 전염병이 번질 때에,",
    Chn:"「国中若有饥荒、瘟疫、旱风、霉烂、蝗虫、蚂蚱，或有仇敌犯境，围困城邑，无论遭遇什么灾祸疾病，",
    Eng:"\"When famine or plague comes to the land, or blight or mildew, locusts or grasshoppers, or when enemies besiege them in any of their cities, whatever disaster or disease may come,",
    Ind:"Apabila ada kelaparan di negeri ini, apabila ada penyakit sampar, hama dan penyakit gandum, belalang dan belalang pelahap, apabila musuh menyesakkan mereka di salah satu kota mereka, apabila ada tulah atau penyakit apapun,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:29, Page:1,
    Kor:"주님의 백성 이스라엘 가운데 어느 한 사람이나 혹은 주님의 백성 전체가, 저마다 재앙과 고통을 깨닫고 이 성전을 바라보며 두 팔을 펴고 간절히 기도하거든,",
    Chn:"你的民以色列，或是众人，或是一人，自觉灾祸甚苦，向这殿举手，无论祈求什么，祷告什么，",
    Eng:"and when a prayer or plea is made by any of your people Israel--each one aware of his afflictions and pains, and spreading out his hands toward this temple--",
    Ind:"lalu seseorang atau segenap umat-Mu Israel memanjatkan doa dan permohonan di rumah ini dengan menadahkan tangannya--karena mereka masing-masing mengenal tulahnya dan penderitaannya sendiri--"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:30, Page:1,
    Kor:"주님께서는, 주님께서 계시는 곳 하늘에서 들으시고, 그들을 용서하여 주십시오. 주님께서는 각 사람의 마음을 아시니, 주님께서 각 사람에게 그 행위대로 갚아 주십시오. 주님만이 사람의 마음을 아십니다.",
    Chn:"求你从天上你的居所垂听赦免。你是知道人心的，要照各人所行的待他们（惟有你知道世人的心），",
    Eng:"then hear from heaven, your dwelling place. Forgive, and deal with each man according to all he does, since you know his heart (for you alone know the hearts of men),",
    Ind:"maka Engkaupun kiranya mendengar dari sorga, tempat kediaman-Mu yang tetap, dan kiranya Engkau mengampuni, dan membalas kepada setiap orang sesuai dengan segala perbuatannya, karena Engkau mengenal hatinya--sebab Engkau sajalah yang mengenal hati anak-anak manusia, --"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:31, Page:1,
    Kor:"그렇게 하시면, 그들은, 주님께서 우리 조상에게 주신 이 땅 위에서 사는 동안, 언제나 주님을 경외하며, 주님의 길을 따라 살 것입니다.",
    Chn:"使他们在你赐给我们列祖之地上一生一世敬畏你，遵行你的道。",
    Eng:"so that they will fear you and walk in your ways all the time they live in the land you gave our fathers.",
    Ind:"supaya mereka takut akan Engkau dan mengikuti segala jalan yang Engkau tunjukkan selama mereka hidup di atas tanah yang telah Kauberikan kepada nenek moyang kami."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:32, Page:1,
    Kor:"○그리고 또 주님의 백성 이스라엘에 속하지 아니한 이방인이라도, 주님의 크신 이름과 강한 손과 편 팔로 하신 일을 듣고, 먼 곳에서 이리로 와서, 이 성전을 바라보며 기도하거든,",
    Chn:"「论到不属你民以色列的外邦人，为你的大名和大能的手，并伸出来的膀臂，从远方而来，向这殿祷告，",
    Eng:"\"As for the foreigner who does not belong to your people Israel but has come from a distant land because of your great name and your mighty hand and your outstretched arm--when he comes and prays toward this temple,",
    Ind:"Juga apabila seorang asing, yang tidak termasuk umat-Mu Israel, datang dari negeri jauh oleh karena nama-Mu yang besar, tangan-Mu yang kuat dan lengan-Mu yang teracung, dan ia datang berdoa di rumah ini,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:33, Page:1,
    Kor:"주님께서는, 주님께서 계시는 곳 하늘에서 들으시고, 그 이방인이 주님께 부르짖으며 간구하는 것을 그대로 다 들어 주셔서, 땅 위의 모든 백성이 주님의 이름을 알게 하시고, 주님의 백성 이스라엘처럼 주님을 경외하게 하시며, 내가 지은 이 성전이 주님의 이름을 부르는 곳임을 알게 하여 주십시오.",
    Chn:"求你从天上你的居所垂听，照着外邦人所祈求的而行，使天下万民都认识你的名，敬畏你，像你的民以色列一样，又使他们知道我建造的这殿是称为你名下的。",
    Eng:"then hear from heaven, your dwelling place, and do whatever the foreigner asks of you, so that all the peoples of the earth may know your name and fear you, as do your own people Israel, and may know that this house I have built bears your Name.",
    Ind:"maka Engkaupun kiranya mendengar dari sorga, dari tempat kediaman-Mu yang tetap, dan kiranya Engkau bertindak sesuai dengan segala yang diserukan kepada-Mu oleh orang asing itu, supaya segala bangsa di bumi mengenal nama-Mu, sehingga mereka takut akan Engkau sama seperti umat-Mu Israel, dan sehingga mereka tahu, bahwa nama-Mu telah diserukan atas rumah yang telah kudirikan ini."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:34, Page:1,
    Kor:"○주님의 백성이 적과 싸우려고 전선에 나갈 때에, 주님께서 그들을 어느 곳으로 보내시든지, 그 곳에서, 주님께서 선택하신 이 도성과, 내가 주님의 이름을 기리려고 지은 이 성전을 바라보며, 그들이 주님께 기도하거든,",
    Chn:"「你的民若奉你的差遣，无论往何处去与仇敌争战，向你所选择的城与我为你名所建造的殿祷告，",
    Eng:"\"When your people go to war against their enemies, wherever you send them, and when they pray to you toward this city you have chosen and the temple I have built for your Name,",
    Ind:"Apabila umat-Mu keluar untuk berperang melawan musuh-musuhnya, ke arah manapun Engkau menyuruh mereka, dan apabila mereka berdoa kepada-Mu dengan berkiblat ke kota yang telah Kaupilih ini dan ke rumah yang telah kudirikan bagi nama-Mu,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:35, Page:1,
    Kor:"주님께서는 하늘에서 그들의 기도와 간구를 들으시고, 그들의 사정을 살펴보아 주십시오.",
    Chn:"求你从天上垂听他们的祷告祈求，使他们得胜。",
    Eng:"then hear from heaven their prayer and their plea, and uphold their cause.",
    Ind:"maka Engkau kiranya mendengar dari sorga doa dan permohonan mereka dan Engkau kiranya memberikan keadilan kepada mereka."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:36, Page:1,
    Kor:"○죄를 짓지 아니하는 사람은 없습니다. 이 백성이 주님께 죄를 지어서, 주님께서 진노하셔서 그들을 원수에게 넘겨 주시게 될 때에, 멀든지 가깝든지, 백성이 남의 나라로 사로잡혀 가더라도,",
    Chn:"「你的民若得罪你（世上没有不犯罪的人），你向他们发怒，将他们交给仇敌掳到或远或近之地；",
    Eng:"\"When they sin against you--for there is no one who does not sin--and you become angry with them and give them over to the enemy, who takes them captive to a land far away or near;",
    Ind:"Apabila mereka berdosa kepada-Mu--karena tidak ada manusia yang tidak berdosa--dan Engkau murka kepada mereka dan menyerahkan mereka kepada musuh, sehingga mereka diangkut tertawan ke negeri yang jauh atau yang dekat,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:37, Page:1,
    Kor:"그들이 사로잡혀 간 그 땅에서라도, 마음을 돌이켜 회개하고, 그들을 사로잡아 간 사람의 땅에서 주님께 자복하여 이르기를 '우리가 죄를 지었고, 우리가 악행을 저질렀으며, 우리가 반역하였습니다' 하고 기도하거든,",
    Chn:"他们若在掳到之地想起罪来，回心转意，恳求你说：『我们有罪了，我们悖逆了，我们作恶了』；",
    Eng:"and if they have a change of heart in the land where they are held captive, and repent and plead with you in the land of their captivity and say, 'We have sinned, we have done wrong and acted wickedly';",
    Ind:"dan apabila mereka sadar kembali dalam hatinya di negeri tempat mereka tertawan, dan mereka berbalik, dan memohon kepada-Mu di negeri tempat mereka tertawan, dengan berkata: Kami telah berdosa, bersalah, dan berbuat fasik,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:38, Page:1,
    Kor:"또 그들이 자기들을 사로잡아 간 사람들의 땅에서라도 마음을 다하고 정성을 다하여 주님께 회개하고, 주님께서 그들의 조상에게 주신 땅과 주님께서 선택하신 이 도성과 내가 주님의 이름을 기리려고 지은 이 성전을 바라보면서 기도하거든,",
    Chn:"他们若在掳到之地尽心尽性归服你，又向自己的地，就是你赐给他们列祖之地和你所选择的城，并我为你名所建造的殿祷告，",
    Eng:"and if they turn back to you with all their heart and soul in the land of their captivity where they were taken, and pray toward the land you gave their fathers, toward the city you have chosen and toward the temple I have built for your Name;",
    Ind:"apabila mereka berbalik kepada-Mu dengan segenap hatinya dan dengan segenap jiwanya di negeri orang-orang yang mengangkut mereka tertawan, dan apabila mereka berdoa kepada-Mu dengan berkiblat ke negeri mereka yang telah Kauberikan kepada nenek moyang mereka, ke kota yang telah Kaupilih dan ke rumah yang telah kudirikan bagi nama-Mu,"
  },
  {Bible:"2Chronicles", Chapter:6, Verse:39, Page:1,
    Kor:"주님께서는, 주님께서 계시는 곳인 하늘에서, 그들의 기도와 간구를 들으시고, 그들의 사정을 살펴보아 주십시오. 주님께 죄를 지은 주님의 백성을 용서하여 주십시오.",
    Chn:"求你从天上你的居所垂听你民的祷告祈求，为他们伸冤，赦免他们的过犯。",
    Eng:"then from heaven, your dwelling place, hear their prayer and their pleas, and uphold their cause. And forgive your people, who have sinned against you.",
    Ind:"maka Engkau kiranya mendengarkan dari sorga, dari tempat kediaman-Mu yang tetap, kepada doa dan segala permohonan mereka dan kiranya Engkau memberikan keadilan kepada mereka, dan Engkau kiranya mengampuni umat-Mu yang telah berdosa kepada-Mu."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:40, Page:1,
    Kor:"○나의 하나님, 이 곳에서 사람들이 기도를 할 때마다, 주님께서 눈을 떠 살피시고, 귀를 기울여 들어 주십시오.",
    Chn:"「我的　神啊，现在求你睁眼看，侧耳听在此处所献的祷告。",
    Eng:"\"Now, my God, may your eyes be open and your ears attentive to the prayers offered in this place.",
    Ind:"Sebab itu, ya Allahku, kiranya mata-Mu terbuka dan telinga-Mu menaruh perhatian kepada doa yang dipanjatkan di tempat ini."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:41, Page:1,
    Kor:"주 하나님, 이제는 일어나셔서, 주님께서 쉬실 곳으로 들어가십시오. 주님의 능력이 깃든 궤와 함께 가십시오. 주 하나님, 주님을 섬기는 제사장들에게 구원의 옷을 입혀 주십시오. 주님을 믿는 신도들이 복을 누리며 기뻐하게 해주십시오.",
    Chn:"耶和华　神啊，求你起来， 和你有能力的约柜同入安息之所。 耶和华　神啊，愿你的祭司披上救恩； 愿你的圣民蒙福欢乐。",
    Eng:"\"Now arise, O LORD God, and come to your resting place, you and the ark of your might. May your priests, O LORD God, be clothed with salvation, may your saints rejoice in your goodness.",
    Ind:"Dan sekarang, bangunlah ya TUHAN Allah, dan pergilah ke tempat perhentian-Mu, Engkau serta tabut kekuatan-Mu! Kiranya, ya TUHAN Allah, imam-imam-Mu berpakaian keselamatan, dan orang-orang yang Kaukasihi bersukacita karena kebaikan-Mu."
  },
  {Bible:"2Chronicles", Chapter:6, Verse:42, Page:1,
    Kor:"주 하나님, 주님께서 기름 부어 세우신 사람을 내쫓지 마시고, 주님의 종 다윗에게 베푸신 은총을 기억하여 주십시오.\"",
    Chn:"耶和华　神啊，求你不要厌弃你的受膏者， 要记念向你仆人大卫所施的慈爱。」",
    Eng:"O LORD God, do not reject your anointed one. Remember the great love promised to David your servant.\"",
    Ind:"Ya TUHAN Allah, janganlah Engkau menolak orang yang telah Kauurapi, ingatlah akan segala kasih setia-Mu kepada Daud, hamba-Mu itu.\""
  },
]);
