// 역대하 34장 · 2Chronicles 34
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Chronicles",34,33);
BibleDB.add([
  {Bible:"2Chronicles", Chapter:34, Verse:1, Page:1,
    Kor:"<유다 왕 요시야(왕하 22:1-2)> 요시야가 왕이 되었을 때에, 그는 여덟 살이었다. 그는 예루살렘에서 서른한 해 동안 다스렸다.",
    Chn:"约西亚登基的时候年八岁，在耶路撒冷作王三十一年。",
    Eng:"Josiah was eight years old when he became king, and he reigned in Jerusalem thirty-one years.",
    Ind:"Yosia berumur delapan tahun pada waktu ia menjadi raja dan tiga puluh satu tahun lamanya ia memerintah di Yerusalem."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:2, Page:1,
    Kor:"그는, 주님께서 보시기에 옳은 일을 하였고, 그의 조상 다윗의 길을 본받아서, 오른쪽으로나 왼쪽으로 곁길로 벗어나지 않았다.",
    Chn:"他行耶和华眼中看为正的事，效法他祖大卫所行的，不偏左右。",
    Eng:"He did what was right in the eyes of the LORD and walked in the ways of his father David, not turning aside to the right or to the left.",
    Ind:"Ia melakukan apa yang benar di mata TUHAN dan hidup seperti Daud, bapa leluhurnya, dan tidak menyimpang ke kanan atau ke kiri."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:3, Page:1,
    Kor:"<종교 개혁의 첫 단계> ○요시야는 왕이 된 지 여덟째 해에, 아직도 매우 어린 나이에, 조상 다윗의 하나님을 찾기 시작하였다. 그의 통치 십이년이 되는 해에는, 산당과 아세라 목상들과 아로새긴 우상들과 부어 만든 우상들을 없애고, 유다와 예루살렘을 깨끗하게 하였다.",
    Chn:"他作王第八年，尚且年幼，就寻求他祖大卫的　神。到了十二年才洁净犹大和耶路撒冷，除掉邱坛、木偶、雕刻的像，和铸造的像。",
    Eng:"In the eighth year of his reign, while he was still young, he began to seek the God of his father David. In his twelfth year he began to purge Judah and Jerusalem of high places, Asherah poles, carved idols and cast images.",
    Ind:"Pada tahun kedelapan dari pemerintahannya, ketika ia masih muda belia, ia mulai mencari Allah Daud, bapa leluhurnya, dan pada tahun kedua belas ia mulai mentahirkan Yehuda dan Yerusalem dari pada bukit-bukit pengorbanan, tiang-tiang berhala, patung-patung pahatan dan patung-patung tuangan."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:4, Page:1,
    Kor:"요시야의 지시로, 사람들은 바알 신들을 섬기는 제단들을 헐었다. 요시야는 제단 위에 있는 분향단들도 부수게 하였다. 그는 또한 아세라 목상들과 아로새긴 우상들과 부어 만든 우상들을 빻아, 가루로 만들어서, 그 제단에서 제사를 드리던 자들의 무덤에 뿌리고,",
    Chn:"众人在他面前拆毁巴力的坛，砍断坛上高高的日像，又把木偶和雕刻的像，并铸造的像打碎成灰，撒在祭偶像人的坟上，",
    Eng:"Under his direction the altars of the Baals were torn down; he cut to pieces the incense altars that were above them, and smashed the Asherah poles, the idols and the images. These he broke to pieces and scattered over the graves of those who had sacrificed to them.",
    Ind:"Mezbah-mezbah para Baal dirobohkan di hadapannya; ia menghancurkan pedupaan-pedupaan yang ada di atasnya; ia meremukkan dan menghancurluluhkan tiang-tiang berhala, patung-patung pahatan dan patung-patung tuangan, dan menghamburkannya ke atas kuburan orang-orang yang mempersembahkan korban kepada berhala-berhala itu."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:5, Page:1,
    Kor:"제사장들의 뼈를 제단 위에 불살라서, 유다와 예루살렘을 깨끗하게 하였다.",
    Chn:"将他们祭司的骸骨烧在坛上，洁净了犹大和耶路撒冷；",
    Eng:"He burned the bones of the priests on their altars, and so he purged Judah and Jerusalem.",
    Ind:"Tulang-tulang para imam dibakarnya di atas mezbah-mezbah mereka. Demikianlah ia mentahirkan Yehuda dan Yerusalem."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:6, Page:1,
    Kor:"그는 같은 일을, 므낫세와 에브라임과 시므온 지역과, 저 멀리 사방이 다 폐허가 된 납달리 지역에 이르기까지, 직접 가서 행하였다.",
    Chn:"又在玛拿西、以法莲、西缅、拿弗他利各城，和四围破坏之处，都这样行；",
    Eng:"In the towns of Manasseh, Ephraim and Simeon, as far as Naphtali, and in the ruins around them,",
    Ind:"Juga di kota-kota Manasye, Efraim dan Simeon, sampai di kota-kota Naftali, yang di mana-mana telah menjadi reruntuhan,"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:7, Page:1,
    Kor:"그는 제단들을 헐고, 아세라 목상들과 아로새긴 우상들을 빻아 가루로 만들고, 온 이스라엘 땅에 있는 분향단도 모두 부수어 버리고 나서야, 예루살렘으로 돌아왔다.",
    Chn:"又拆毁祭坛，把木偶和雕刻的像打碎成灰，砍断以色列遍地所有的日像，就回耶路撒冷去了。",
    Eng:"he tore down the altars and the Asherah poles and crushed the idols to powder and cut to pieces all the incense altars throughout Israel. Then he went back to Jerusalem.",
    Ind:"ia merobohkan segala mezbah dan tiang berhala, meremukkan segala patung pahatan serta menghancurluluhkannya, dan menghancurkan semua pedupaan di seluruh tanah Israel. Sesudah itu ia kembali ke Yerusalem."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:8, Page:1,
    Kor:"<율법서의 발견(왕하 22:3-20)> ○요시야는 나라와 성전을 깨끗하게 한 뒤에, 통치한 지 열여덟째 해가 되는 때에, 아살랴의 아들 사반과 마아세야 성주와 요아하스의 아들 요아 서기관을 보내서, 주 그의 하나님의 성전을 수리하게 하였다.",
    Chn:"约西亚王十八年，净地净殿之后，就差遣亚萨利雅的儿子沙番、邑宰玛西雅、约哈斯的儿子史官约亚去修理耶和华—他　神的殿。",
    Eng:"In the eighteenth year of Josiah's reign, to purify the land and the temple, he sent Shaphan son of Azaliah and Maaseiah the ruler of the city, with Joah son of Joahaz, the recorder, to repair the temple of the LORD his God.",
    Ind:"Pada tahun kedelapan belas dari pemerintahannya, setelah selesai mentahirkan negeri dan rumah TUHAN, ia menyuruh Safan bin Azalya, dan Maaseya, penguasa kota, serta Yoah bin Yoahas, bendahara negara, untuk memperbaiki rumah TUHAN, Allahnya."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:9, Page:1,
    Kor:"이 세 사람은 힐기야 대제사장에게 가서, 하나님의 성전에 들어온 돈을 그에게 건네 주었다. 그 돈은, 므낫세와 에브라임과 북 이스라엘의 나머지 지역에 사는 백성과 유다와 베냐민의 모든 백성과 예루살렘 주민에게서 거두어들인 것으로서, 성전 문을 지키는 레위 사람들이 모아 둔 것이었다.",
    Chn:"他们就去见大祭司希勒家，将奉到　神殿的银子交给他；这银子是看守殿门的利未人从玛拿西、以法莲，和一切以色列剩下的人，以及犹大、便雅悯众人，并耶路撒冷的居民收来的。",
    Eng:"They went to Hilkiah the high priest and gave him the money that had been brought into the temple of God, which the Levites who were the doorkeepers had collected from the people of Manasseh, Ephraim and the entire remnant of Israel and from all the people of Judah and Benjamin and the inhabitants of Jerusalem.",
    Ind:"Maka datanglah mereka kepada imam besar Hilkia dan menyerahkan kepadanya uang yang telah dibawa ke rumah Allah dan yang telah dikumpulkan oleh orang-orang Lewi, yakni oleh para penjaga pintu, dari orang-orang Manasye dan Efraim, dan dari semua orang yang masih tinggal dari Israel, pula dari seluruh orang Yehuda dan Benyamin, dan dari penduduk Yerusalem."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:10, Page:1,
    Kor:"그들은 이 돈을 주님의 성전 수리를 맡은 이들에게 맡겼고, 그들은 또 그 돈을 주님의 성전 수리를 직접 맡아 건축하는 이들에게 주어서, 성전을 수리하게 하였다.",
    Chn:"又将这银子交给耶和华殿里督工的，转交修理耶和华殿的工匠，",
    Eng:"Then they entrusted it to the men appointed to supervise the work on the LORD'S temple. These men paid the workers who repaired and restored the temple.",
    Ind:"Uang itu diberikan mereka ke tangan para pekerja yang diangkat untuk mengawasi rumah TUHAN; dan mereka itu, yang bekerja dalam rumah TUHAN, mengeluarkannya untuk membetulkan dan memperbaiki rumah itu."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:11, Page:1,
    Kor:"그들은 그 돈을 목수와 돌 쌓는 이들에게도 맡겨서, 채석한 돌과 도리와 들보를 만들 나무를 사들여, 유다의 왕들이 폐허로 만들어 버린 건물들을 손질하게 하였다.",
    Chn:"就是交给木匠、石匠，买凿成的石头和架木与栋梁，修犹大王所毁坏的殿。",
    Eng:"They also gave money to the carpenters and builders to purchase dressed stone, and timber for joists and beams for the buildings that the kings of Judah had allowed to fall into ruin.",
    Ind:"Mereka memberikannya kepada tukang-tukang kayu dan tukang-tukang bangunan, supaya tukang-tukang itu membeli batu pahat dan kayu untuk tupai-tupai dan untuk memasang balok-balok pada gedung-gedung, yang oleh raja-raja Yehuda dibiarkan roboh."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:12, Page:1,
    Kor:"그 사람들은 일을 정직하게 하였다. 그들 위에 네 명의 감독이 있었다. 모두 레위 사람들인데, 므라리 자손 가운데서는 야핫과 오바댜, 고핫 자손 가운데서는 스가랴와 무술람이 성전을 수리하는 일을 맡아 하였다. 이 레위 사람들은 모두 음악에 익숙한 사람들이었다.",
    Chn:"这些人办事诚实，督工的是利未人米拉利的子孙雅哈、俄巴底；督催的是哥辖的子孙撒迦利亚、米书兰；还有善于作乐的利未人。",
    Eng:"The men did the work faithfully. Over them to direct them were Jahath and Obadiah, Levites descended from Merari, and Zechariah and Meshullam, descended from Kohath. The Levites--all who were skilled in playing musical instruments--",
    Ind:"Orang-orang itu melakukan pekerjaan itu dengan setia. Orang-orang yang diangkat menjadi pengawas mereka ialah: Yahat dan Obaja, orang-orang Lewi dari bani Merari, sedangkan Zakharia dan Mesulam dari bani Kehat mengepalai semua. Dan semua orang Lewi yang pandai memainkan alat-alat musik,"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:13, Page:1,
    Kor:"그들은 목도꾼을 감독하고, 각종 공사 책임자들을 감독하였으며, 어떤 레위 사람은 기록원과 사무원과 문지기의 일을 맡았다.",
    Chn:"他们又监管扛抬的人，督催一切做工的。利未人中也有作书记、作司事、作守门的。",
    Eng:"had charge of the laborers and supervised all the workers from job to job. Some of the Levites were secretaries, scribes and doorkeepers.",
    Ind:"mengepalai kuli-kuli dan mengiringi semua tukang dalam pekerjaan apapun. Dari antara orang-orang Lewi itu ada yang menjadi panitera, pengatur atau penunggu pintu gerbang."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:14, Page:1,
    Kor:"○힐기야 제사장은, 주님의 성전에서 궤에 보관된 돈을 꺼내다가, 모세가 전한 주님의 율법책을 발견하고,",
    Chn:"他们将奉到耶和华殿的银子运出来的时候，祭司希勒家偶然得了摩西所传耶和华的律法书。",
    Eng:"While they were bringing out the money that had been taken into the temple of the LORD, Hilkiah the priest found the Book of the Law of the LORD that had been given through Moses.",
    Ind:"Ketika mereka mengeluarkan uang yang telah dibawa ke rumah TUHAN, imam Hilkia menemukan kitab Taurat TUHAN, yang diberikan dengan perantaraan Musa."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:15, Page:1,
    Kor:"사반 서기관에게, 자기가 주님의 성전에서 율법책을 발견하였다고 하면서, 그 책을 사반에게 주었다.",
    Chn:"希勒家对书记沙番说：「我在耶和华殿里得了律法书。」遂将书递给沙番。",
    Eng:"Hilkiah said to Shaphan the secretary, \"I have found the Book of the Law in the temple of the LORD.\" He gave it to Shaphan.",
    Ind:"Maka berkatalah Hilkia kepada Safan, panitera negara itu: \"Aku telah menemukan kitab Taurat di rumah TUHAN!\" Lalu Hilkia memberikan kitab itu kepada Safan,"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:16, Page:1,
    Kor:"사반이 그 책을 가지고 왕에게 나아가서 보고하였다. \"임금님께서 종들에게 명령하신 것을 종들이 그대로 다 하였습니다.",
    Chn:"沙番把书拿到王那里，回复王说：「凡交给仆人们办的都办理了。",
    Eng:"Then Shaphan took the book to the king and reported to him: \"Your officials are doing everything that has been committed to them.",
    Ind:"dan Safan membawa kitab itu kepada raja. Ia juga menyampaikan kabar kepada raja: \"Segala sesuatu yang ditugaskan kepada hamba-hambamu, telah mereka laksanakan."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:17, Page:1,
    Kor:"또 주님의 성전에 있는 돈을 다 쏟아서, 감독들과 건축하는 사람들에게 맡겼습니다.\" 이렇게 보고하고 나서,",
    Chn:"耶和华殿里的银子倒出来，交给督工的和匠人的手里了。」",
    Eng:"They have paid out the money that was in the temple of the LORD and have entrusted it to the supervisors and workers.\"",
    Ind:"Mereka telah mengambil seluruh uang yang terdapat di rumah TUHAN dan memberikannya ke tangan para pengawas dan para pekerja.\""
  },
  {Bible:"2Chronicles", Chapter:34, Verse:18, Page:1,
    Kor:"사반 서기관은, 힐기야 제사장이 자기에게 책 한 권을 건네 주었다고 왕에게 보고했다. 그리고 사반은 그 책을 왕 앞에서 큰소리로 읽었다.",
    Chn:"书记沙番又对王说：「祭司希勒家递给我一卷书。」沙番就在王面前读那书。",
    Eng:"Then Shaphan the secretary informed the king, \"Hilkiah the priest has given me a book.\" And Shaphan read from it in the presence of the king.",
    Ind:"Safan, panitera negara itu, memberitahukan juga kepada raja: \"Imam Hilkia telah memberikan kitab kepadaku,\" lalu Safan membacakan sebagian di depan raja."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:19, Page:1,
    Kor:"○왕은 율법의 말씀을 다 듣고는, 애통해 하며 자기의 옷을 찢었다.",
    Chn:"王听见律法上的话，就撕裂衣服，",
    Eng:"When the king heard the words of the Law, he tore his robes.",
    Ind:"Segera sesudah raja mendengar perkataan Taurat itu, dikoyakkannyalah pakaiannya."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:20, Page:1,
    Kor:"왕은 힐기야와 사반의 아들 아히감과 미가의 아들 압돈과 사반 서기관과 왕의 시종 아사야에게 명령하였다.",
    Chn:"吩咐希勒家与沙番的儿子亚希甘、米迦的儿子亚比顿、书记沙番，和王的臣仆亚撒雅说：",
    Eng:"He gave these orders to Hilkiah, Ahikam son of Shaphan, Abdon son of Micah, Shaphan the secretary and Asaiah the king's attendant:",
    Ind:"Kemudian raja memberi perintah kepada Hilkia, kepada Ahikam bin Safan, kepada Abdon bin Mikha, kepada Safan, panitera negara itu, dan kepada Asaya, hamba raja, katanya:"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:21, Page:1,
    Kor:"\"그대들은 주님께로 나아가서, 나를 대신하여, 그리고 아직 이스라엘과 유다에 살아 남아 있는 백성을 대신하여, 이번에 발견된 이 두루마리의 말씀에 관하여 주님의 뜻을 여쭈어 보도록 하시오. 우리의 조상이 주님의 말씀을 지키지 않고, 이 두루마리에 기록된 모든 것을 지켜 따르지 않았으므로, 주님께서 우리에게 쏟으신 진노가 크오.\"",
    Chn:"「你们去为我、为以色列和犹大剩下的人，以这书上的话求问耶和华；因我们列祖没有遵守耶和华的言语，没有照这书上所记的去行，耶和华的烈怒就倒在我们身上。」",
    Eng:"\"Go and inquire of the LORD for me and for the remnant in Israel and Judah about what is written in this book that has been found. Great is the LORD'S anger that is poured out on us because our fathers have not kept the word of the LORD; they have not acted in accordance with all that is written in this book.\"",
    Ind:"\"Pergilah, mintalah petunjuk TUHAN bagiku, bagi yang masih tinggal di Israel dan di Yehuda tentang perkataan kitab yang ditemukan ini, sebab hebat kehangatan murka TUHAN yang dicurahkan kepada kita, oleh karena nenek moyang kita tidak memelihara firman TUHAN dengan berbuat tepat seperti yang tertulis dalam kitab ini!\""
  },
  {Bible:"2Chronicles", Chapter:34, Verse:22, Page:1,
    Kor:"○힐기야가 왕의 명령을 받은 사람들과 함께 훌다 예언자에게로 갔다. 그는 살룸의 아내였다. 살룸은 하스라의 손자요 독핫의 아들로서, 궁중 예복을 관리하는 사람이었다. 훌다는 예루살렘의 제 이 구역에 살고 있었는데, 그들이 그에게 가서 왕의 말을 전하니,",
    Chn:"于是，希勒家和王所派的众人都去见女先知户勒大。户勒大是掌管礼服沙龙的妻，沙龙是哈斯拉的孙子、特瓦的儿子。户勒大住在耶路撒冷第二区；他们请问于她。",
    Eng:"Hilkiah and those the king had sent with him went to speak to the prophetess Huldah, who was the wife of Shallum son of Tokhath, the son of Hasrah, keeper of the wardrobe. She lived in Jerusalem, in the Second District.",
    Ind:"Maka pergilah Hilkia dengan orang-orang yang disuruh raja kepada nabiah Hulda, isteri seorang yang mengurus pakaian-pakaian, yaitu Salum bin Tokhat bin Hasra, penunggu pakaian-pakaian; nabiah itu tinggal di Yerusalem, di perkampungan baru. Mereka berbicara kepadanya sebagaimana yang diperintahkan."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:23, Page:1,
    Kor:"훌다가 그들에게 말하였다. \"주 이스라엘의 하나님께서 이렇게 말씀하시니, 그대들을 나에게 보내어 주님의 뜻을 물어 보라고 한 그분에게 가서 전하시오.",
    Chn:"她对他们说：「耶和华—以色列的　神如此说：『你们可以回复那差遣你们来见我的人说，",
    Eng:"She said to them, \"This is what the LORD, the God of Israel, says: Tell the man who sent you to me,",
    Ind:"Perempuan itu menjawab mereka: \"Beginilah firman TUHAN, Allah Israel! Katakanlah kepada orang yang menyuruh kamu kepada-Ku!"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:24, Page:1,
    Kor:"'나 주가 이렇게 말한다. 유다 왕 앞에서 낭독한 책에 기록된 모든 저주대로, 내가 이 곳과 여기에 사는 주민에게 재앙을 내리겠다.",
    Chn:"耶和华如此说：我必照着在犹大王面前所读那书上的一切咒诅，降祸与这地和其上的居民；",
    Eng:"'This is what the LORD says: I am going to bring disaster on this place and its people--all the curses written in the book that has been read in the presence of the king of Judah.",
    Ind:"Beginilah firman TUHAN: Sesungguhnya Aku akan mendatangkan malapetaka atas tempat ini dan atas penduduknya, yakni segala kutuk yang tertulis dalam kitab yang telah dibacakan di depan raja Yehuda,"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:25, Page:1,
    Kor:"그들이 나를 버리고 다른 신들에게 분향하여, 그들이 한 모든 일이 나를 노엽게 하였기 때문이다. 그러므로 내 분노를 여기에다 쏟을 것이니, 아무도 끄지 못할 것이다' 하셨소.",
    Chn:"因为他们离弃我，向别神烧香，用他们手所做的惹我发怒，所以我的忿怒如火倒在这地上，总不息灭。』",
    Eng:"Because they have forsaken me and burned incense to other gods and provoked me to anger by all that their hands have made, my anger will be poured out on this place and will not be quenched.'",
    Ind:"karena mereka meninggalkan Aku dan membakar korban kepada allah lain dengan maksud menimbulkan sakit hati-Ku dengan segala pekerjaan tangan mereka; sebab itu nyala murka-Ku akan dicurahkan ke tempat ini dengan tidak padam-padam."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:26, Page:1,
    Kor:"주님의 뜻을 주님께 여쭈어 보려고 그대들을 나에게로 보낸 유다 왕에게는 이렇게 전하시오. '주 이스라엘의 하나님이 이렇게 말한다. 네가 들은 말씀을 설명하겠다.",
    Chn:"然而差遣你们来求问耶和华的犹大王，你们要这样回复他说：『耶和华—以色列的　神如此说：至于你所听见的话，",
    Eng:"Tell the king of Judah, who sent you to inquire of the LORD, 'This is what the LORD, the God of Israel, says concerning the words you heard:",
    Ind:"Tetapi kepada raja Yehuda yang telah menyuruh kamu untuk meminta petunjuk TUHAN, harus kamu katakan demikian: Beginilah firman TUHAN, Allah Israel: Mengenai perkataan yang telah kaudengar itu,"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:27, Page:1,
    Kor:"내가 이 곳과 이 곳에 사는 주민을 두고 말한 것을 네가 듣고, 마음에 느낀 바 있어서, 하나님 앞, 곧 내 앞에서 겸손해져서, 네가 옷을 찢으며 통곡하였으므로, 내가 네 기도를 들어주었다. 나 주가 말한다.",
    Chn:"就是听见我指着这地和其上居民所说的话，你便心里敬服，在我面前自卑，撕裂衣服，向我哭泣，因此我应允了你。这是我—耶和华说的。",
    Eng:"Because your heart was responsive and you humbled yourself before God when you heard what he spoke against this place and its people, and because you humbled yourself before me and tore your robes and wept in my presence, I have heard you, declares the LORD.",
    Ind:"oleh karena engkau sudah menyesal dan engkau merendahkan diri di hadapan Allah pada waktu engkau mendengar firman-Nya terhadap tempat ini dan terhadap penduduknya, oleh karena engkau merendahkan diri di hadapan-Ku, mengoyakkan pakaianmu dan menangis di hadapan-Ku, Akupun telah mendengarnya, demikianlah firman TUHAN,"
  },
  {Bible:"2Chronicles", Chapter:34, Verse:28, Page:1,
    Kor:"그러므로 이 곳과 이 곳 주민에게 내리기로 한 모든 재앙을, 네가 죽을 때까지는 내리지 않겠다. 내가 너를 네 조상에게로 보낼 때에는, 네가 평안히 무덤에 안장되게 하겠다' 하셨습니다.\" ○그들이 돌아와서, 이 말을 왕에게 전하였다.",
    Chn:"我必使你平平安安地归到坟墓，到你列祖那里，我要降与这地和其上居民的一切灾祸，你也不至亲眼看见。』」他们就回复王去了。",
    Eng:"Now I will gather you to your fathers, and you will be buried in peace. Your eyes will not see all the disaster I am going to bring on this place and on those who live here.'\" So they took her answer back to the king.",
    Ind:"maka sesungguhnya Aku akan mengumpulkan engkau kepada nenek moyangmu, dan engkau akan dikebumikan ke dalam kuburmu dengan damai, dan matamu tidak akan melihat segala malapetaka yang akan Kudatangkan atas tempat ini dan atas penduduknya.\" Lalu mereka menyampaikan jawab itu kepada raja."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:29, Page:1,
    Kor:"<요시야가 주님께 순종하기로 하다(왕하 23:1-20)> ○왕이 사람을 보내어 유다와 예루살렘의 모든 장로를 불러모았다.",
    Chn:"王差遣人招聚犹大和耶路撒冷的众长老来。",
    Eng:"Then the king called together all the elders of Judah and Jerusalem.",
    Ind:"Sesudah itu raja menyuruh orang mengumpulkan semua tua-tua Yehuda dan Yerusalem."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:30, Page:1,
    Kor:"왕은 주님의 성전에 올라갈 때에, 유다의 모든 백성과 예루살렘 주민과 제사장들과 레위 사람들과, 어른으로부터 아이에 이르기까지, 모든 백성을 다 데리고 주님의 성전으로 올라갔다. 그 때에 왕은 주님의 성전에서 발견된 언약책에 적힌 모든 말씀을 사람들에게 크게 읽어 들려 주도록 하였다.",
    Chn:"王和犹大众人，与耶路撒冷的居民，并祭司利未人，以及所有的百姓，无论大小，都一同上到耶和华的殿；王就把殿里所得的约书念给他们听。",
    Eng:"He went up to the temple of the LORD with the men of Judah, the people of Jerusalem, the priests and the Levites--all the people from the least to the greatest. He read in their hearing all the words of the Book of the Covenant, which had been found in the temple of the LORD.",
    Ind:"Kemudian pergilah raja ke rumah TUHAN bersama-sama semua orang Yehuda dan penduduk Yerusalem, para imam, orang-orang Lewi, dan seluruh orang awam, baik yang besar maupun yang masih kecil. Dengan didengar mereka ia membacakan segala perkataan dari kitab perjanjian yang ditemukan di rumah TUHAN itu."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:31, Page:1,
    Kor:"왕은 자기의 자리에 서서, 주님을 따를 것과, 마음과 목숨을 다 바쳐 그의 계명과 법도와 규례를 지킬 것과, 이 책에 적힌 언약의 말씀을 지킬 것을 맹세하는 언약을, 주님 앞에서 맺었다.",
    Chn:"王站在他的地位上，在耶和华面前立约，要尽心尽性地顺从耶和华，遵守他的诫命、法度、律例，成就这书上所记的约言；",
    Eng:"The king stood by his pillar and renewed the covenant in the presence of the LORD--to follow the LORD and keep his commands, regulations and decrees with all his heart and all his soul, and to obey the words of the covenant written in this book.",
    Ind:"Sesudah itu berdirilah raja pada tempatnya dan diikatnyalah perjanjian di hadapan TUHAN untuk hidup dengan mengikuti TUHAN, dan tetap menuruti perintah-perintah-Nya, peraturan-peraturan-Nya dan ketetapan-ketetapan-Nya dengan segenap hatinya dan dengan segenap jiwanya dan untuk melakukan perkataan perjanjian yang tertulis dalam kitab itu."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:32, Page:1,
    Kor:"왕이 거기에 있는 예루살렘과 베냐민 사람들도 이 언약에 참여하게 하니, 예루살렘 주민이 하나님, 곧 조상의 하나님이 세우신 언약을 따랐다.",
    Chn:"又使住耶路撒冷和便雅悯的人都服从这约。于是耶路撒冷的居民都遵行他们列祖之　神的约。",
    Eng:"Then he had everyone in Jerusalem and Benjamin pledge themselves to it; the people of Jerusalem did this in accordance with the covenant of God, the God of their fathers.",
    Ind:"Ia menyuruh semua orang yang berada di Yerusalem dan Benyamin ikut serta dalam perjanjian itu. Dan penduduk Yerusalem berbuat menurut perjanjian Allah, yakni Allah nenek moyang mereka."
  },
  {Bible:"2Chronicles", Chapter:34, Verse:33, Page:1,
    Kor:"이와 같이 요시야는 이스라엘 자손에게 속한 모든 땅에서 혐오스러운 것들을 다 없애 버리고, 이스라엘의 모든 사람으로 주 하나님을 섬기게 하였으므로, 요시야가 살아 있는 동안에는 백성이 주 조상의 하나님께 복종하고 떠나지 않았다.",
    Chn:"约西亚从以色列各处将一切可憎之物尽都除掉，使以色列境内的人都事奉耶和华—他们的　神。约西亚在世的日子，就跟从耶和华—他们列祖的　神，总不离开。",
    Eng:"Josiah removed all the detestable idols from all the territory belonging to the Israelites, and he had all who were present in Israel serve the LORD their God. As long as he lived, they did not fail to follow the LORD, the God of their fathers.",
    Ind:"Yosia menjauhkan segala dewa kekejian dari semua daerah orang Israel dan menyuruh semua orang yang ada di Israel beribadah kepada TUHAN, Allah mereka. Maka sepanjang hidup Yosia mereka tidak menyimpang mengikuti TUHAN, Allah nenek moyang mereka."
  },
]);
