// 역대하 10장 · 2Chronicles 10
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Chronicles",10,19);
BibleDB.add([
  {Bible:"2Chronicles", Chapter:10, Verse:1, Page:1, Kor:"<북쪽 지파의 반란(왕상 12:1-20)> 온 이스라엘이 르호보암을 왕으로 세우려고 세겜에 모였으므로, 르호보암이 세겜으로 갔다.", Chn:"", Eng:"Rehoboam went to Shechem, for all the Israelites had gone there to make him king.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:2, Page:1, Kor:"느밧의 아들 여로보암이 이 소식을 들었다. 그는 솔로몬 왕을 피하여 이집트에 가 있었는데, 이 소식을 듣고 이집트에서 돌아왔다.", Chn:"", Eng:"When Jeroboam son of Nebat heard this (he was in Egypt, where he had fled from King Solomon), he returned from Egypt.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:3, Page:1, Kor:"사람들이 여로보암을 불러내니, 그와 온 이스라엘이 르호보암에게 가서, 이렇게 말하였다.", Chn:"", Eng:"So they sent for Jeroboam, and he and all Israel went to Rehoboam and said to him:", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:4, Page:1, Kor:"\"임금님의 아버지께서는 우리에게 무거운 멍에를 메우셨습니다. 이제 임금님께서는, 임금님의 아버지께서 우리에게 메우신 중노동과, 그가 우리에게 지우신 이 무거운 멍에를, 가볍게 해주십시오. 그러면 우리가 임금님을 섬기겠습니다.\"", Chn:"", Eng:"\"Your father put a heavy yoke on us, but now lighten the harsh labor and the heavy yoke he put on us, and we will serve you.\"", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:5, Page:1, Kor:"○르호보암이 그들에게 말하였다. \"사흘 뒤에 나에게 다시 오시오.\" 이 말을 듣고 백성들은 돌아갔다.", Chn:"", Eng:"Rehoboam answered, \"Come back to me in three days.\" So the people went away.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:6, Page:1, Kor:"○르호보암 왕은 그의 아버지 솔로몬이 살아 있을 때에, 그의 아버지를 섬긴 원로들과 상의하였다. \"이 백성에게 내가 어떤 대답을 하여야 할지, 경들의 충고를 듣고 싶습니다.\"", Chn:"", Eng:"Then King Rehoboam consulted the elders who had served his father Solomon during his lifetime. \"How would you advise me to answer these people?\" he asked.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:7, Page:1, Kor:"○그들은 르호보암에게 이렇게 대답하였다. \"임금님께서 이 백성에게 너그럽게 대해 주시고, 백성을 반기셔서 그들에게 좋은 말로 대답해 주시면, 이 백성은 평생 임금님의 종이 될 것입니다.\"", Chn:"", Eng:"They replied, \"If you will be kind to these people and please them and give them a favorable answer, they will always be your servants.\"", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:8, Page:1, Kor:"○원로들이 이렇게 충고하였지만, 그는 원로들의 충고를 무시하고, 자기와 함께 자라 자기를 받드는 젊은 신하들과 의논하며,", Chn:"", Eng:"But Rehoboam rejected the advice the elders gave him and consulted the young men who had grown up with him and were serving him.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:9, Page:1, Kor:"그들에게 물었다. \"백성이 나에게, 선친께서 메워 주신 멍에를 가볍게 해 달라고 요청하고 있소. 이 백성에게 내가 어떤 대답을 해야 할지, 그대들의 충고를 듣고 싶소.\"", Chn:"", Eng:"He asked them, \"What is your advice? How should we answer these people who say to me, 'Lighten the yoke your father put on us'?\"", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:10, Page:1, Kor:"○왕과 함께 자라난 젊은 신하들이 그에게 말하였다. \"이 백성이 임금님의 아버지께서 그들에게 메우신 무거운 멍에를 가볍게 해 달라고 임금님께 요청하였습니다. 그러나 임금님께서는 이 백성에게 이렇게 말씀하십시오. '내 새끼 손가락 하나가 내 아버지의 허리보다 굵다.", Chn:"", Eng:"The young men who had grown up with him replied, \"Tell the people who have said to you, 'Your father put a heavy yoke on us, but make our yoke lighter'--tell them, 'My little finger is thicker than my father's waist.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:11, Page:1, Kor:"내 아버지가 너희에게 무거운 멍에를 메우셨으나, 나는 이제 너희에게 그것보다 더 무거운 멍에를 메우겠다. 내 아버지께서는 너희를 가죽 채찍으로 매질하셨으나, 나는 너희를 쇠 채찍으로 치겠다' 하고 말씀하십시오.\"", Chn:"", Eng:"My father laid on you a heavy yoke; I will make it even heavier. My father scourged you with whips; I will scourge you with scorpions.'\"", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:12, Page:1, Kor:"○왕이 백성에게 사흘 뒤에 다시 오라고 하였으므로, 여로보암과 온 백성이 사흘째 되는 날에 르호보암 앞에 나아왔다.", Chn:"", Eng:"Three days later Jeroboam and all the people returned to Rehoboam, as the king had said, \"Come back to me in three days.\"", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:13, Page:1, Kor:"왕은 원로들의 충고를 무시하고, 백성에게 가혹하게 대답하였다.", Chn:"", Eng:"The king answered them harshly. Rejecting the advice of the elders,", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:14, Page:1, Kor:"르호보암 왕은 젊은 신하들의 충고를 따라 백성에게 이렇게 대답하였다. ○\"내 아버지가 당신들에게 무거운 멍에를 메우셨으나, 나는 이제 당신들에게 그것보다 더 무거운 멍에를 메우겠소. 내 아버지께서는 당신들을 가죽 채찍으로 매질하셨으나, 나는 당신들을 쇠 채찍으로 치겠소.\"", Chn:"", Eng:"he followed the advice of the young men and said, \"My father made your yoke heavy; I will make it even heavier. My father scourged you with whips; I will scourge you with scorpions.\"", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:15, Page:1, Kor:"○왕이 이처럼 백성의 요구를 들어 주지 않았으니, 하나님께서 일이 그렇게 뒤틀리도록 시키셨던 것이다. 주님께서 이미 실로 사람 아히야를 시키셔서, 느밧의 아들 여로보암에게 하신 말씀을 이루시려는 것이었다.", Chn:"", Eng:"So the king did not listen to the people, for this turn of events was from God, to fulfill the word the LORD had spoken to Jeroboam son of Nebat through Ahijah the Shilonite.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:16, Page:1, Kor:"○온 이스라엘은, 왕이 그들의 요구를 전혀 듣지 않는 것을 보고 왕에게 외쳤다.  \"우리가 다윗에게서 받을 몫이 무엇이냐? 이새의 아들에게서는 받을 유산이 없다. 이스라엘아, 각자 자기의 장막으로 돌아가라. 다윗이여, 이제 너는 너의 집안이나 돌보아라.\" ○그런 다음에, 온 이스라엘은 각자 자기들의 장막으로 돌아갔다.", Chn:"", Eng:"When all Israel saw that the king refused to listen to them, they answered the king: \"What share do we have in David, what part in Jesse's son? To your tents, O Israel! Look after your own house, O David!\" So all the Israelites went home.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:17, Page:1, Kor:"그러나 유다의 여러 성읍에 살고 있는 이스라엘 자손은 르호보암의 통치 아래에 남아 있었다.", Chn:"", Eng:"But as for the Israelites who were living in the towns of Judah, Rehoboam still ruled over them.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:18, Page:1, Kor:"○르호보암 왕이 강제노동 감독관 a하도람을 이스라엘 자손에게 보내었더니, 이스라엘 자손이 그를 돌로 쳐서 죽였다. 그러자 르호보암 왕은 급히 수레에 올라서, 예루살렘으로 도망하였다.(a 아도니람의 변형)", Chn:"", Eng:"King Rehoboam sent out Adoniram, who was in charge of forced labor, but the Israelites stoned him to death. King Rehoboam, however, managed to get into his chariot and escape to Jerusalem.", Ind:""},
  {Bible:"2Chronicles", Chapter:10, Verse:19, Page:1, Kor:"이렇게 이스라엘은 다윗 왕조에 반역하여 오늘에 이르렀다.", Chn:"", Eng:"So Israel has been in rebellion against the house of David to this day. 2CH", Ind:""},
]);
