// 역대하 9장 · 2Chronicles 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Chronicles",9,31);
BibleDB.add([
  {Bible:"2Chronicles", Chapter:9, Verse:1, Page:1,
    Kor:"<스바의 여왕이 솔로몬을 찾아오다(왕상 10:1-13)> 스바의 여왕이 솔로몬의 명성을 듣고, 여러 가지 어려운 질문으로 그를 시험하여 보려고, 예루살렘으로 그를 찾아왔다. 그는 많은 수행원을 데리고, 또 여러 가지 향료와 많은 금과 보석들을 낙타에 싣고 왔다. 그는 솔로몬에게 이르자, 마음 속에 품고 있는 온갖 것들을 다 물어 보았다.",
    Chn:"示巴女王听见所罗门的名声，就来到耶路撒冷，要用难解的话试问所罗门；跟随她的人甚多，又有骆驼驮着香料、宝石，和许多金子。她来见了所罗门，就把心里所有的对所罗门都说出来。",
    Eng:"When the queen of Sheba heard of Solomon's fame, she came to Jerusalem to test him with hard questions. Arriving with a very great caravan--with camels carrying spices, large quantities of gold, and precious stones--she came to Solomon and talked with him about all she had on her mind.",
    Ind:"Ketika ratu negeri Syeba mendengar kabar tentang Salomo, maka dengan pasukan pengiring yang sangat besar dan dengan unta-unta yang membawa rempah-rempah, banyak emas dan batu permata yang mahal-mahal datanglah ia ke Yerusalem hendak menguji Salomo dengan teka-teki. Setelah ia sampai kepada Salomo, dipercakapkannyalah segala yang ada dalam hatinya dengan dia."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:2, Page:1,
    Kor:"솔로몬은 여왕이 묻는 모든 물음에 척척 대답하였다. 솔로몬이 몰라서 여왕에게 대답하지 못한 것은 하나도 없었다.",
    Chn:"所罗门将她所问的都答上了，没有一句不明白、不能答的。",
    Eng:"Solomon answered all her questions; nothing was too hard for him to explain to her.",
    Ind:"Dan Salomo menjawab segala pertanyaan ratu itu; bagi Salomo tidak ada yang tersembunyi, yang tidak dapat dijawabnya untuk ratu itu."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:3, Page:1,
    Kor:"스바의 여왕은, 솔로몬이 온갖 지혜를 갖추고 있는 것을 확인하고, 그가 지은 궁전을 두루 살펴보고,",
    Chn:"示巴女王见所罗门的智慧和他所建造的宫室、",
    Eng:"When the queen of Sheba saw the wisdom of Solomon, as well as the palace he had built,",
    Ind:"Ketika ratu negeri Syeba melihat hikmat Salomo dan rumah yang telah didirikannya,"
  },
  {Bible:"2Chronicles", Chapter:9, Verse:4, Page:1,
    Kor:"또 왕의 상에 오른 요리와, 신하들이 둘러 앉은 모습과, 그의 관리들이 일하는 모습과, 그들이 입은 제복과, 술잔을 받들어 올리는 시종들과, 그들이 입은 제복과, 주님의 성전에서 드리는 번제물을 보고 나서 넋을 잃었다.",
    Chn:"席上的珍馐美味、群臣分列而坐、仆人两旁侍立，以及他们的衣服装饰、酒政，和酒政的衣服装饰，又见他上耶和华殿的台阶，就诧异得神不守舍，",
    Eng:"the food on his table, the seating of his officials, the attending servants in their robes, the cupbearers in their robes and the burnt offerings he made at the temple of the LORD, she was overwhelmed.",
    Ind:"makanan di mejanya, cara duduk pegawai-pegawainya, cara pelayan-pelayannya melayani dan berpakaian, juru-juru minumannya dan pakaian mereka, dan korban bakaran yang biasa dipersembahkannya di rumah TUHAN, maka tercenganglah ratu itu."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:5, Page:1,
    Kor:"○여왕이 왕에게 말하였다. \"임금님께서 이루신 업적과 임금님의 지혜에 관한 소문을, 내가 내 나라에서 이미 들었지만, 와서 보니, 과연 들은 소문이 모두 사실입니다.",
    Chn:"对王说：「我在本国里所听见论到你的事和你的智慧实在是真的！",
    Eng:"She said to the king, \"The report I heard in my own country about your achievements and your wisdom is true.",
    Ind:"Dan ia berkata kepada raja: \"Benar juga kabar yang kudengar di negeriku tentang engkau dan tentang hikmatmu,"
  },
  {Bible:"2Chronicles", Chapter:9, Verse:6, Page:1,
    Kor:"내가 여기 오기 전까지는 그 소문을 믿지 못하였는데, 내 눈으로 직접 확인하고 보니, 오히려 내가 들은 소문은 사실의 절반도 안 되는 것 같습니다. 임금님께서는, 내가 들은 소문보다 훨씬 뛰어나신 분이십니다.",
    Chn:"我先不信那些话，及至我来亲眼见了，才知道你的大智慧；人所告诉我的，还不到一半；你的实迹越过我所听见的名声。",
    Eng:"But I did not believe what they said until I came and saw with my own eyes. Indeed, not even half the greatness of your wisdom was told me; you have far exceeded the report I heard.",
    Ind:"tetapi aku tidak percaya perkataan-perkataan mereka sampai aku datang dan melihatnya dengan mataku sendiri; sungguh, setengah dari hikmatmu yang besar itu belum diberitahukan kepadaku; engkau melebihi kabar yang kudengar."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:7, Page:1,
    Kor:"임금님의 백성은 참으로 행복한 사람들입니다. 임금님 앞에 서서, 늘 임금님의 지혜를 배우는 임금님의 신하들 또한, 참으로 행복하다 아니할 수 없습니다.",
    Chn:"你的群臣、你的仆人常侍立在你面前听你智慧的话是有福的。",
    Eng:"How happy your men must be! How happy your officials, who continually stand before you and hear your wisdom!",
    Ind:"Berbahagialah orang-orangmu, dan berbahagialah para pegawaimu ini yang selalu melayani engkau dan menyaksikan hikmatmu!"
  },
  {Bible:"2Chronicles", Chapter:9, Verse:8, Page:1,
    Kor:"주 임금님의 하나님께 찬양을 돌립니다. 하나님께서는 임금님을 좋아하셔서 임금님을 그의 보좌에 앉히시고, 주 하나님을 받드는 왕으로 삼으셨습니다. 임금님의 하나님께서는 이스라엘을 사랑하셔서, 그들을 영원히 굳게 세우시려고, 임금님을 그들 위에 왕으로 세우시고, 공평과 정의로 다스리게 하셨습니다.\"",
    Chn:"耶和华—你的　神是应当称颂的！他喜悦你，使你坐他的国位，为耶和华—你的　神作王；因为你的　神爱以色列人，要永远坚立他们，所以立你作他们的王，使你秉公行义。」",
    Eng:"Praise be to the LORD your God, who has delighted in you and placed you on his throne as king to rule for the LORD your God. Because of the love of your God for Israel and his desire to uphold them forever, he has made you king over them, to maintain justice and righteousness.\"",
    Ind:"Terpujilah TUHAN, Allahmu, yang telah berkenan kepadamu sedemikian, hingga Ia mendudukkan engkau di atas takhta-Nya sebagai raja untuk TUHAN, Allahmu! Karena Allahmu mengasihi orang Israel, maka Ia menetapkan mereka untuk selama-lamanya, dan menjadikan engkau raja atas mereka untuk melakukan keadilan dan kebenaran.\""
  },
  {Bible:"2Chronicles", Chapter:9, Verse:9, Page:1,
    Kor:"○그런 다음에, 여왕은, 금 백이십 달란트와 아주 많은 향료와 보석을 왕에게 선사하였다. 솔로몬 왕은, 스바의 여왕에게서 받은 만큼, 그렇게 많은 향료를, 다시는 어느 누구에게서도 더 받아 본 일이 없다.",
    Chn:"于是示巴女王将一百二十他连得金子和宝石，与极多的香料送给所罗门王；她送给王的香料，以后再没有这样的。",
    Eng:"Then she gave the king 120 talents of gold, large quantities of spices, and precious stones. There had never been such spices as those the queen of Sheba gave to King Solomon.",
    Ind:"Lalu diberikan kepada raja seratus dua puluh talenta emas, dan sangat banyak rempah-rempah dan batu permata yang mahal-mahal; tidak pernah lagi ada rempah-rempah seperti yang diberikan ratu negeri Syeba kepada raja Salomo itu."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:10, Page:1,
    Kor:"○(히람의 일꾼들과 솔로몬의 일꾼들도 오빌에서 금을 실어 왔다. 그들은 백단목과 보석도 가져 왔다.",
    Chn:"希兰的仆人和所罗门的仆人从俄斐运了金子来，也运了檀香木和宝石来。",
    Eng:"(The men of Hiram and the men of Solomon brought gold from Ophir; they also brought algumwood and precious stones.",
    Ind:"Lagipula hamba-hamba Huram dan hamba-hamba Salomo, yang membawa emas dari Ofir, membawa juga kayu cendana dan batu permata yang mahal-mahal."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:11, Page:1,
    Kor:"왕은 이 백단목으로 주님의 성전과 왕궁의 계단을 만들고, 합창단원이 쓸 수금과 거문고를 만들었다. 이와 같은 백단목은 일찍이 유다 땅에서는 본 일이 없었다.)",
    Chn:"王用檀香木为耶和华殿和王宫做台，又为歌唱的人做琴瑟；犹大地从来没有见过这样的。",
    Eng:"The king used the algumwood to make steps for the temple of the LORD and for the royal palace, and to make harps and lyres for the musicians. Nothing like them had ever been seen in Judah.)",
    Ind:"Raja mengerjakan kayu cendana itu menjadi tangga-tangga untuk rumah TUHAN dan istana raja, dan juga menjadi kecapi dan gambus untuk para penyanyi. Hal seperti itu tidak pernah kelihatan sebelumnya di tanah Yehuda."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:12, Page:1,
    Kor:"○솔로몬 왕은 스바의 여왕이 가져 온 것보다 더 많이 주었을 뿐만 아니라, 여왕이 요구하는 대로, 가지고 싶어 하는 것은 모두 주었다. 여왕은 신하들과 함께 자기의 나라로 돌아갔다.",
    Chn:"所罗门王按示巴女王所带来的，还她礼物，另外照她一切所要所求的，都送给她。于是女王和她臣仆转回本国去了。",
    Eng:"King Solomon gave the queen of Sheba all she desired and asked for; he gave her more than she had brought to him. Then she left and returned with her retinue to her own country.",
    Ind:"Raja Salomo memberikan kepada ratu negeri Syeba segala yang dikehendakinya dan yang dimintanya, melebihi yang dibawa ratu itu untuk raja. Lalu ratu itu berangkat pulang ke negerinya bersama-sama dengan pegawai-pegawainya."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:13, Page:1,
    Kor:"<솔로몬의 부귀 영화(왕상 10:14-25)> ○해마다 솔로몬에게 들어오는 금의 무게가 육백육십육 달란트나 되었다.",
    Chn:"所罗门每年所得的金子共有六百六十六他连得，",
    Eng:"The weight of the gold that Solomon received yearly was 666 talents,",
    Ind:"Adapun berat emas, yang dibawa kepada Salomo dalam satu tahun ialah seberat enam ratus enam puluh enam talenta,"
  },
  {Bible:"2Chronicles", Chapter:9, Verse:14, Page:1,
    Kor:"이 밖에도 관세 수입과 외국과의 무역에서 벌어들인 것이 있고, 아라비아의 모든 왕들과, 국내의 지방 장관들이 보내오는 금도 있었다.",
    Chn:"另外还有商人所进的金子，并且阿拉伯诸王与属国的省长都带金银给所罗门。",
    Eng:"not including the revenues brought in by merchants and traders. Also all the kings of Arabia and the governors of the land brought gold and silver to Solomon.",
    Ind:"belum terhitung yang dibawa oleh saudagar-saudagar dan pedagang-pedagang; juga semua raja Arab dan bupati-bupati di negeri itu membawa emas dan perak kepada Salomo."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:15, Page:1,
    Kor:"솔로몬 왕은 금을 두드려 펴서 입힌 큰 방패를 이백 개나 만들었는데, 방패 하나에 들어간 금만 해도 육백 세겔이나 되었다.",
    Chn:"所罗门王用锤出来的金子打成挡牌二百面，每面用金子六百舍客勒；",
    Eng:"King Solomon made two hundred large shields of hammered gold; six hundred bekas of hammered gold went into each shield.",
    Ind:"Raja Salomo membuat dua ratus perisai besar dari emas tempaan, enam ratus syikal emas tempaan dipakainya untuk setiap perisai besar;"
  },
  {Bible:"2Chronicles", Chapter:9, Verse:16, Page:1,
    Kor:"그는 또 금을 두드려 펴서 입힌 작은 방패를 삼백 개 만들었는데, 그 방패 하나에 들어간 금은 삼백 세겔이었다. 왕은 이 방패들을 '레바논 수풀 궁'에 두었다.",
    Chn:"又用锤出来的金子打成盾牌三百面，每面用金子三百舍客勒，都放在黎巴嫩林宫里。",
    Eng:"He also made three hundred small shields of hammered gold, with three hundred bekas of gold in each shield. The king put them in the Palace of the Forest of Lebanon.",
    Ind:"ia membuat juga tiga ratus perisai kecil dari emas tempaan, tiga ratus syikal emas dipakainya untuk setiap perisai kecil; lalu raja menaruh semuanya itu di dalam gedung \"Hutan Libanon\"."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:17, Page:1,
    Kor:"○왕은 또 상아로 큰 보좌를 만들고, 겉에 순금을 입혔다.",
    Chn:"王用象牙制造一个大宝座，用精金包裹。",
    Eng:"Then the king made a great throne inlaid with ivory and overlaid with pure gold.",
    Ind:"Juga raja membuat takhta besar dari gading, yang disalutnya dengan emas murni."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:18, Page:1,
    Kor:"그 보좌로 오르는 층계는 계단이 여섯이었으며, 보좌에 붙은 발받침대는 금으로 만든 것이었다. 앉는 자리 양쪽에는 팔걸이가 있고, 팔걸이 양 옆에는 사자 상이 하나씩 서 있었다.",
    Chn:"宝座有六层台阶，又有金脚凳，与宝座相连。宝座两旁有扶手，靠近扶手有两个狮子站立。",
    Eng:"The throne had six steps, and a footstool of gold was attached to it. On both sides of the seat were armrests, with a lion standing beside each of them.",
    Ind:"Takhta itu enam tingkatnya, dan tumpuan kakinya dari emas, yang dipautkan pada takhta itu, dan pada kedua sisi tempat duduk ada kelek-kelek. Di samping kelek-kelek itu berdiri dua singa,"
  },
  {Bible:"2Chronicles", Chapter:9, Verse:19, Page:1,
    Kor:"여섯 개의 계단 양쪽에도, 각각 여섯 개씩 열두 개의 사자 상이 서 있었다. 일찍이 어느 나라에서도 이렇게는 만들지 못하였다.",
    Chn:"六层台阶上有十二个狮子站立，每层有两个：左边一个，右边一个；在列国中没有这样做的。",
    Eng:"Twelve lions stood on the six steps, one at either end of each step. Nothing like it had ever been made for any other kingdom.",
    Ind:"sedang dua belas singa berdiri di atas keenam tingkat itu sebelah-menyebelah; belum pernah diperbuat yang demikian bagi sesuatu kerajaan."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:20, Page:1,
    Kor:"○솔로몬 왕이 마시는 데 쓰는 모든 그릇은 금으로 되어 있었고, '레바논 수풀 궁'에 있는 그릇도 모두 순금으로 만든 것이었다. 솔로몬 시대에는, 은은 귀금속 축에 들지도 못하였다.",
    Chn:"所罗门王一切的饮器都是金的，黎巴嫩林宫里的一切器皿都是精金的。所罗门年间，银子算不了什么。",
    Eng:"All King Solomon's goblets were gold, and all the household articles in the Palace of the Forest of Lebanon were pure gold. Nothing was made of silver, because silver was considered of little value in Solomon's day.",
    Ind:"Segala perkakas minuman raja Salomo dari emas dan segala barang di gedung \"Hutan Libanon\" itu dari emas murni; perak tidak dianggap berharga pada zaman Salomo."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:21, Page:1,
    Kor:"왕의 배들은 a히람의 일꾼들을 태우고 다시스로 다니며, 세 해마다 한 번씩 금과 은과 상아와 원숭이와 공작새 들을 실어 오곤 하였다.(a 히, '후람')",
    Chn:"因为王的船只与希兰的仆人一同往他施去；他施船只三年一次装载金、银、象牙、猿猴、孔雀回来。",
    Eng:"The king had a fleet of trading ships manned by Hiram's men. Once every three years it returned, carrying gold, silver and ivory, and apes and baboons.",
    Ind:"Sebab raja mempunyai kapal-kapal yang berlayar ke Tarsis bersama-sama dengan orang-orang Huram; dan sekali tiga tahun kapal-kapal Tarsis itu datang membawa emas dan perak serta gading; juga kera dan burung merak."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:22, Page:1,
    Kor:"○솔로몬 왕은 재산에 있어서나, 지혜에 있어서나, 이 세상의 어떤 왕보다 훨씬 뛰어났다.",
    Chn:"所罗门王的财宝与智慧胜过天下的列王。",
    Eng:"King Solomon was greater in riches and wisdom than all the other kings of the earth.",
    Ind:"Raja Salomo melebihi semua raja di bumi dalam hal kekayaan dan hikmat."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:23, Page:1,
    Kor:"그래서 세상의 모든 왕들은 솔로몬을 직접 만나서, 하나님께서 그의 마음 속에 넣어 주신 지혜의 말을 들으려고 하였다.",
    Chn:"普天下的王都求见所罗门，要听　神赐给他智慧的话。",
    Eng:"All the kings of the earth sought audience with Solomon to hear the wisdom God had put in his heart.",
    Ind:"Semua raja di bumi berikhtiar menghadap Salomo untuk menyaksikan hikmat yang telah ditaruh Allah di dalam hatinya."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:24, Page:1,
    Kor:"그리하여 그들은 각자, 은그릇과 금그릇과 옷과 갑옷과 향료와 말과 노새를 예물로 가지고 왔는데, 해마다 이런 사람들의 방문이 그치지 않았다.",
    Chn:"他们各带贡物，就是金器、银器、衣服、军械、香料、骡马，每年有一定之例。",
    Eng:"Year after year, everyone who came brought a gift--articles of silver and gold, and robes, weapons and spices, and horses and mules.",
    Ind:"Mereka datang masing-masing membawa persembahannya, yakni barang-barang perak dan barang-barang emas, pakaian, senjata, rempah-rempah, kuda dan bagal, dan begitulah tahun demi tahun."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:25, Page:1,
    Kor:"○병거 끄는 말을 매어 두는 마구간만 하더라도, 솔로몬이 가지고 있던 것이 사천 칸이나 되었다. 기병은 만 이천 명에 이르렀다. 솔로몬은 그들을, 병거 주둔성과 왕이 있는 예루살렘에다가 나누어서 배치하였다.",
    Chn:"所罗门有套车的马四千棚，有马兵一万二千，安置在屯车的城邑和耶路撒冷，就是王那里。",
    Eng:"Solomon had four thousand stalls for horses and chariots, and twelve thousand horses, which he kept in the chariot cities and also with him in Jerusalem.",
    Ind:"Salomo mempunyai juga empat ribu kandang untuk kuda-kudanya dan kereta-keretanya dan dua belas ribu orang berkuda, yang ditempatkan dalam kota-kota kereta dan dekat raja di Yerusalem."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:26, Page:1,
    Kor:"그는 유프라테스 강에서부터 블레셋 영토에 이르기까지, 또 이집트의 국경에 이르기까지 모든 왕을 다스렸다.",
    Chn:"所罗门统管诸王，从大河到非利士地，直到埃及的边界。",
    Eng:"He ruled over all the kings from the River to the land of the Philistines, as far as the border of Egypt.",
    Ind:"Dan ia memerintah atas semua raja mulai dari sungai Efrat sampai negeri orang Filistin dan sampai ke tapal batas Mesir."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:27, Page:1,
    Kor:"왕의 덕분에 예루살렘에는 은이 돌처럼 흔하였고, 백향목은 세펠라 평원지대의 뽕나무만큼이나 많았다.",
    Chn:"王在耶路撒冷使银子多如石头，香柏木多如高原的桑树。",
    Eng:"The king made silver as common in Jerusalem as stones, and cedar as plentiful as sycamore-fig trees in the foothills.",
    Ind:"Raja membuat banyaknya perak di Yerusalem sama seperti batu, dan banyaknya pohon kayu aras sama seperti pohon ara yang tumbuh di Daerah Bukit."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:28, Page:1,
    Kor:"솔로몬은 이집트에서 그리고 다른 모든 나라에서 군마를 사들였다.",
    Chn:"有人从埃及和各国为所罗门赶马群来。",
    Eng:"Solomon's horses were imported from Egypt and from all other countries.",
    Ind:"Kuda untuk Salomo didatangkan dari Misraim dan dari segala negeri."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:29, Page:1,
    Kor:"<솔로몬의 통치 개요(왕상 11:41-43)> ○솔로몬의 나머지 행적은 처음부터 끝까지, '나단 예언자의 역사책'과 '실로 사람 아히야의 예언서'와 '잇도 선견자의 묵시록', 곧 잇도가 느밧의 아들 여로보암에 대하여 쓴 책에 기록되어 있다.",
    Chn:"所罗门其余的事，自始至终，不都写在先知拿单的书上和示罗人亚希雅的预言书上，并先见易多论尼八儿子耶罗波安的默示书上吗？",
    Eng:"As for the other events of Solomon's reign, from beginning to end, are they not written in the records of Nathan the prophet, in the prophecy of Ahijah the Shilonite and in the visions of Iddo the seer concerning Jeroboam son of Nebat?",
    Ind:"Selebihnya dari riwayat Salomo dari awal sampai akhir, bukankah semuanya itu tertulis dalam riwayat nabi Natan dan dalam nubuat Ahia, orang Silo itu, dan dalam penglihatan-penglihatan Ido, pelihat itu, tentang Yerobeam bin Nebat?"
  },
  {Bible:"2Chronicles", Chapter:9, Verse:30, Page:1,
    Kor:"솔로몬은 예루살렘에서 마흔 해 동안 온 이스라엘을 다스렸다.",
    Chn:"所罗门在耶路撒冷作以色列众人的王共四十年。",
    Eng:"Solomon reigned in Jerusalem over all Israel forty years.",
    Ind:"Salomo memerintah di Yerusalem atas seluruh Israel empat puluh tahun lamanya."
  },
  {Bible:"2Chronicles", Chapter:9, Verse:31, Page:1,
    Kor:"솔로몬은 죽어서 그의 아버지 다윗의 성에 묻혔다. 그의 아들 르호보암이 그의 뒤를 이어 왕이 되었다.",
    Chn:"所罗门与他列祖同睡，葬在他父大卫城里。他儿子罗波安接续他作王。",
    Eng:"Then he rested with his fathers and was buried in the city of David his father. And Rehoboam his son succeeded him as king.",
    Ind:"Kemudian Salomo mendapat perhentian bersama-sama dengan nenek moyangnya, dan ia dikuburkan di kota Daud, ayahnya. Maka Rehabeam, anaknya, menjadi raja menggantikan dia."
  },
]);
