// 에베소서 6장 · Ephesians 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Ephesians",6,24);
BibleDB.add([
  {Bible:"Ephesians", Chapter:6, Verse:1, Page:1, Kor:"<자녀와 부모> 자녀 된 이 여러분, <주 안에서> 여러분의 부모에게 순종하십시오. 이것이 옳은 일입니다.", Chn:"", Eng:"Children, obey your parents in the Lord, for this is right.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:2, Page:1, Kor:"a\"네 부모를 공경하라\"고 하신 계명은, 약속이 딸려 있는 첫째 계명입니다.(a 출 20:12; 신 15:16)", Chn:"", Eng:"\"Honor your father and mother\"--which is the first commandment with a promise--", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:3, Page:1, Kor:"\"네가 잘 되고, 땅에서 오래 살 것이다\" 하신 약속입니다.", Chn:"", Eng:"\"that it may go well with you and that you may enjoy long life on the earth.\"", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:4, Page:1, Kor:"또 아버지 된 이 여러분, 여러분의 자녀를 노엽게 하지 말고, 주님의 훈련과 훈계로 기르십시오.", Chn:"", Eng:"Fathers, do not exasperate your children; instead, bring them up in the training and instruction of the Lord.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:5, Page:1, Kor:"<종과 주인> ○종으로 있는 이 여러분, 두려움과 떨림과 성실한 마음으로 육신의 주인에게 순종하십시오. 그리스도께 하듯이 해야 합니다.", Chn:"", Eng:"Slaves, obey your earthly masters with respect and fear, and with sincerity of heart, just as you would obey Christ.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:6, Page:1, Kor:"사람을 기쁘게 하는 자들처럼 눈가림으로 하지 말고, 그리스도의 종답게 진심으로 하나님의 뜻을 실천하십시오.", Chn:"", Eng:"Obey them not only to win their favor when their eye is on you, but like slaves of Christ, doing the will of God from your heart.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:7, Page:1, Kor:"사람에게가 아니라 주님께 하듯이, 기쁜 마음으로 섬기십시오.", Chn:"", Eng:"Serve wholeheartedly, as if you were serving the Lord, not men,", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:8, Page:1, Kor:"선한 일을 하는 사람은, 종이든지 자유인이든지, 각각 그 갚음을 주님께로부터 받게 됨을 여러분은 아십시오.", Chn:"", Eng:"because you know that the Lord will reward everyone for whatever good he does, whether he is slave or free.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:9, Page:1, Kor:"주인 된 이 여러분, 종들에게 이와 같이 대하고, 위협을 그만두십시오. 그들의 주님이시요 여러분의 주님이신 분께서 하늘에 계신다는 것과, 주님께서는 사람을 차별하여 대하지 않으신다는 것을, 여러분은 아십시오.", Chn:"", Eng:"And masters, treat your slaves in the same way. Do not threaten them, since you know that he who is both their Master and yours is in heaven, and there is no favoritism with him.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:10, Page:1, Kor:"<악마와 싸우는 싸움> ○끝으로 말합니다. 여러분은 주님 안에서 그분의 힘찬 능력으로 굳세게 되십시오.", Chn:"", Eng:"Finally, be strong in the Lord and in his mighty power.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:11, Page:1, Kor:"악마의 간계에 맞설 수 있도록, 하나님이 주시는 온몸을 덮는 갑옷을 입으십시오.", Chn:"", Eng:"Put on the full armor of God so that you can take your stand against the devil's schemes.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:12, Page:1, Kor:"b우리의 싸움은 인간을 적대자로 상대하는 것이 아니라, 통치자들과 권세자들과 이 어두운 세계의 지배자들과 하늘에 있는 악한 영들을 상대로 하는 것입니다.(b 다른 고대 사본들에는 '여러분의')", Chn:"", Eng:"For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:13, Page:1, Kor:"그러므로 하나님이 주시는 무기로 완전히 무장하십시오. 그래야만 여러분이 악한 날에 이 적대자들을 대항할 수 있으며 모든 일을 끝낸 뒤에 설 수 있을 것입니다.", Chn:"", Eng:"Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground, and after you have done everything, to stand.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:14, Page:1, Kor:"그러므로 여러분은 c진리의 허리띠로 허리를 동이고 정의의 가슴막이로 가슴을 가리고 버티어 서십시오.(c 사 11:5; 59:17)", Chn:"", Eng:"Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place,", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:15, Page:1, Kor:"d발에는 평화의 복음을 전할 차비를 하십시오.(d 사 52:7; 나 1:15)", Chn:"", Eng:"and with your feet fitted with the readiness that comes from the gospel of peace.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:16, Page:1, Kor:"e이 모든 것에 더하여 믿음의 방패를 손에 드십시오. 그것으로써 여러분은 악한 자가 쏘는 모든 불화살을 막아 꺼버릴 수 있을 것입니다.(e 또는 '어떤 경우에든지')", Chn:"", Eng:"In addition to all this, take up the shield of faith, with which you can extinguish all the flaming arrows of the evil one.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:17, Page:1, Kor:"그리고 f구원의 투구를 받고 성령의 검 곧 하나님의 말씀을 받으십시오(f 사 59:17)", Chn:"", Eng:"Take the helmet of salvation and the sword of the Spirit, which is the word of God.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:18, Page:1, Kor:"온갖 기도와 간구로 언제나 성령 안에서 기도하십시오. 이것을 위하여 늘 깨어서 끝까지 참으면서 모든 성도를 위하여 간구하십시오.", Chn:"", Eng:"And pray in the Spirit on all occasions with all kinds of prayers and requests. With this in mind, be alert and always keep on praying for all the saints.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:19, Page:1, Kor:"또 나를 위하여 기도하기를, 내가 입을 열 때에, 하나님께서 말씀을 주셔서 담대하게 g복음의 비밀을 알릴 수 있게 해 달라고 하십시오.(g 다른 고대 사본들에는 '복음의'가 없음)", Chn:"", Eng:"Pray also for me, that whenever I open my mouth, words may be given me so that I will fearlessly make known the mystery of the gospel,", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:20, Page:1, Kor:"나는 사슬에 매여 있으나, 이 복음을 전하는 사신입니다. 이런 형편에서도, 내가 마땅히 해야 할 말을 담대하게 말할 수 있게 기도하여 주십시오.", Chn:"", Eng:"for which I am an ambassador in chains. Pray that I may declare it fearlessly, as I should.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:21, Page:1, Kor:"<작별 인사> ○사랑하는 형제이며 주님 안에서 진실한 일꾼인 두기고가, 내가 지내는 형편과 내가 하고 있는 일과 그밖에 모든 것을 여러분에게 알릴 것입니다.", Chn:"", Eng:"Tychicus, the dear brother and faithful servant in the Lord, will tell you everything, so that you also may know how I am and what I am doing.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:22, Page:1, Kor:"우리의 사정을 알리고, 또, 여러분의 마음을 위로하게 하려고, 나는 그를 여러분에게 보냅니다.", Chn:"", Eng:"I am sending him to you for this very purpose, that you may know how we are, and that he may encourage you.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:23, Page:1, Kor:"○아버지 하나님과 주 예수 그리스도께서 h성도들에게 평화를 내려주시고, 믿음과 더불어 사랑을 베풀어주시기를 빕니다.(h 그, '형제들에게')", Chn:"", Eng:"Peace to the brothers, and love with faith from God the Father and the Lord Jesus Christ.", Ind:""},
  {Bible:"Ephesians", Chapter:6, Verse:24, Page:1, Kor:"우리 주 예수 그리스도를 변함없이 사랑하는 모든 사람에게 은혜가 있기를 빕니다.i(i 다른 고대 사본들에는 절 끝에 '아멘'이 있음)", Chn:"", Eng:"", Ind:""},
]);
