// 호세아 13장 · Hosea 13
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Hosea",13,16);
BibleDB.add([
  {Bible:"Hosea", Chapter:13, Verse:1, Page:1, Kor:"<이스라엘에 대한 최후의 심판> \"에브라임이 말만 하면 모두 떨었다. 온 이스라엘이 그렇게 에브라임을 우러러보았는데, 바알 신을 섬겨 죄를 짓고 말았으므로, 이제 망하고 말았다.", Chn:"", Eng:"When Ephraim spoke, men trembled; he was exalted in Israel. But he became guilty of Baal worship and died.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:2, Page:1, Kor:"그런데도 그들은 거듭 죄를 짓고 있다. 은을 녹여 거푸집에 부어서 우상들을 만든다. 재주껏 만든 은 신상들, 그것들은 모두 세공업자들이 만든 것인데도, 그들은, 이 신상 앞에 제물을 바치라고 하면서, 송아지 신상들에게 입을 맞춘다.", Chn:"", Eng:"Now they sin more and more; they make idols for themselves from their silver, cleverly fashioned images, all of them the work of craftsmen. It is said of these people, \"They offer human sacrifice and kiss the calf-idols.\"", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:3, Page:1, Kor:"그러므로 그들은 아침 안개처럼 되고, 이른 새벽에 사라지는 이슬처럼 될 것이다. 타작 마당에서 바람에 날려 나가는 쭉정이처럼 되고, 굴뚝에서 나오는 연기처럼 될 것이다.", Chn:"", Eng:"Therefore they will be like the morning mist, like the early dew that disappears, like chaff swirling from a threshing floor, like smoke escaping through a window.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:4, Page:1, Kor:"그러나 나는, a너희가 이집트 땅에 살 때로부터 주 너희의 하나님이다. 그 때에 너희가 아는 하나님은 나밖에 없고, 나 말고는 다른 구원자가 없었다. (a 또는 '너희를 이집트 땅에서 데리고 나온 때로부터')", Chn:"", Eng:"\"But I am the LORD your God, who brought you out of Egypt. You shall acknowledge no God but me, no Savior except me.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:5, Page:1, Kor:"나는 저 광야에서, 그 메마른 땅에서, 너희를 먹이고 살렸다.", Chn:"", Eng:"I cared for you in the desert, in the land of burning heat.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:6, Page:1, Kor:"그들을 잘 먹였더니 먹는 대로 배가 불렀고, 배가 부를수록 마음이 교만해지더니, 마침내 나를 잊었다.", Chn:"", Eng:"When I fed them, they were satisfied; when they were satisfied, they became proud; then they forgot me.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:7, Page:1, Kor:"그래서 내가 그들에게 사자처럼 되고, 이제는 표범처럼 되어서, 길목을 지키겠다.", Chn:"", Eng:"So I will come upon them like a lion, like a leopard I will lurk by the path.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:8, Page:1, Kor:"새끼 빼앗긴 암곰처럼 그들에게 달려들어, 염통을 갈기갈기 찢을 것이다. 암사자처럼, 그 자리에서 그들을 뜯어먹을 것이다. 들짐승들이 그들을 남김없이 찢어 먹을 것이다.", Chn:"", Eng:"Like a bear robbed of her cubs, I will attack them and rip them open. Like a lion I will devour them; a wild animal will tear them apart.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:9, Page:1, Kor:"b이스라엘아, 네가 나를 대적하니, 너를 돕는 자를 대적하니, 너는 이제 망했다. (b 또는 '이스라엘아, 내가 너를 멸망시키기로 작정하였는데, 이제 누가 너를 도울 수 있겠느냐')", Chn:"", Eng:"\"You are destroyed, O Israel, because you are against me, against your helper.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:10, Page:1, Kor:"왕과 대신들을 세워 달라고 조르더니, 도대체, 너의 왕이 지금 어디에 있느냐? 너를 구원하라고 하여라. 대신들이 지금 어디에 있느냐? 너의 모든 성읍에서 샅샅이 찾아보아라. 너를 궁지에서 건져 달라고 하여라.", Chn:"", Eng:"Where is your king, that he may save you? Where are your rulers in all your towns, of whom you said, 'Give me a king and princes'?", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:11, Page:1, Kor:"내가 홧김에 너에게 왕을 주었으나, 분을 참을 수 없어서 너의 왕을 없애 버렸다.", Chn:"", Eng:"So in my anger I gave you a king, and in my wrath I took him away.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:12, Page:1, Kor:"에브라임의 허물을 적은 문서를 모두 모았고, 죄상을 적은 기록을 모두 보관하고 있다.", Chn:"", Eng:"The guilt of Ephraim is stored up, his sins are kept on record.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:13, Page:1, Kor:"에브라임이 다시 태어나는 진통을 겪고 있다. 그러나 그는, 때가 되었는데도 태를 열고 나올 줄 모르는 미련한 아들과도 같다.", Chn:"", Eng:"Pains as of a woman in childbirth come to him, but he is a child without wisdom; when the time arrives, he does not come to the opening of the womb.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:14, Page:1, Kor:"c내가 그들을 스올의 권세에서 속량하며 내가 그들을 사망에서 구속하겠다. 사망아, 네 재앙이 어디 있느냐? 스올아, 네 멸망이 어디 있느냐? 이제는 내게 동정심 같은 것은 없다. (c 또는 '나더러 그들의 몸값을 갚아 주고 그들을 스올의 세력에서 빼내란 말이냐? 나더러 그들의 몸값을 치르고 그들을 죽음에서 살려내란 말이냐?')", Chn:"", Eng:"\"I will ransom them from the power of the grave; I will redeem them from death. Where, O death, are your plagues? Where, O grave, is your destruction? \"I will have no compassion,", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:15, Page:1, Kor:"이스라엘이 비록 형제들 가운데서 번성하여도, 사막에서 동풍이 불어오게 할 터이니, 주의 바람이 불면 샘과 우물이 모두 말라 버리고, 귀중한 보물상자들도 모두 빼앗길 것이다.", Chn:"", Eng:"even though he thrives among his brothers. An east wind from the LORD will come, blowing in from the desert; his spring will fail and his well dry up. His storehouse will be plundered of all its treasures.", Ind:""},
  {Bible:"Hosea", Chapter:13, Verse:16, Page:1, Kor:"사마리아가 저의 하나님에게 반항하였으니, 이제는 그 죄값을 치를 수밖에 없다. 사람들은 칼에 찔려 쓰러지고, 어린 아이들은 박살 나고, 아이 밴 여인들은 배가 찢길 것이다.\"", Chn:"", Eng:"The people of Samaria must bear their guilt, because they have rebelled against their God. They will fall by the sword; their little ones will be dashed to the ground, their pregnant women ripped open.\"", Ind:""},
]);
