// 고린도전서 8장 · 1Corinthians 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Corinthians",8,13);
BibleDB.add([
  {Bible:"1Corinthians", Chapter:8, Verse:1, Page:1, Kor:"<우상에게 바친 제물> 우상에게 바친 고기에 대하여 말하겠습니다. 우리는 우리 모두가 지식이 있는 줄로 알고 있습니다. 지식은 사람을 교만하게 하지만, 사랑은 덕을 세웁니다.", Chn:"", Eng:"Now about food sacrificed to idols: We know that we all possess knowledge. Knowledge puffs up, but love builds up.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:2, Page:1, Kor:"자기가 무엇을 안다고 생각하는 사람은, 아직도 그가 마땅히 알아야 할 방식대로 알지 못하는 사람입니다.", Chn:"", Eng:"The man who thinks he knows something does not yet know as he ought to know.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:3, Page:1, Kor:"그러나 하나님을 사랑하는 사람은 하나님께서 그를 알아주십니다.", Chn:"", Eng:"But the man who loves God is known by God.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:4, Page:1, Kor:"그런데 우상에게 바친 고기를 먹는 일을 두고 말하면, 우리가 알기로는, 세상에 우상이란 것은 아무것도 아니고, 오직 하나님 한 분 밖에는 신이 없습니다.", Chn:"", Eng:"So then, about eating food sacrificed to idols: We know that an idol is nothing at all in the world and that there is no God but one.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:5, Page:1, Kor:"이른바 신이라는 것들이 하늘에든 땅에든 있다고 칩시다. 그러면 많은 신과 많은 주가 있는 것 같습니다.", Chn:"", Eng:"For even if there are so-called gods, whether in heaven or on earth (as indeed there are many \"gods\" and many \"lords\"),", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:6, Page:1, Kor:"그러나 우리에게는 아버지가 되시는 하나님 한 분이 계실 뿐입니다. 만물은 그분에게서 났고, 우리는 그분을 위하여 있습니다. 그리고 한 분 주님이신 예수 그리스도가 계십니다. 만물이 그분으로 말미암아 있고, 우리도 그분으로 말미암아 있습니다.", Chn:"", Eng:"yet for us there is but one God, the Father, from whom all things came and for whom we live; and there is but one Lord, Jesus Christ, through whom all things came and through whom we live.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:7, Page:1, Kor:"○그러나 누구에게나 다 지식이 있는 것은 아닙니다. 어떤 사람들은 지금까지 우상을 섬기던 관습에 젖어 있어서, 그들이 먹는 고기가 우상의 것인 줄로 여기면서 먹습니다. 그들의 양심이 약하므로 더럽혀지는 것입니다.", Chn:"", Eng:"But not everyone knows this. Some people are still so accustomed to idols that when they eat such food they think of it as having been sacrificed to an idol, and since their conscience is weak, it is defiled.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:8, Page:1, Kor:"그러나 a\"우리를 하나님 앞에 내세우는 것은 음식이 아닙니다.\" 음식을 먹지 않는다고 해서 손해볼 것도 없고, 먹는다고 해서 이로울 것도 없습니다.(a 8절 전체가 다 인용일 수도 있음)", Chn:"", Eng:"But food does not bring us near to God; we are no worse if we do not eat, and no better if we do.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:9, Page:1, Kor:"그러나 여러분에게 있는 이 자유가 약한 사람들에게 걸림돌이 되지 않도록 조심하십시오.", Chn:"", Eng:"Be careful, however, that the exercise of your freedom does not become a stumbling block to the weak.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:10, Page:1, Kor:"지식이 있는 당신이 우상의 신당에 앉아서 먹고 있는 것을 어떤 사람이 보면, 그가 약한 사람일지라도, 그 양심에 용기가 생겨서, 우상에게 바친 고기를 먹게 되지 않겠습니까?", Chn:"", Eng:"For if anyone with a weak conscience sees you who have this knowledge eating in an idol's temple, won't he be emboldened to eat what has been sacrificed to idols?", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:11, Page:1, Kor:"그러면 그 약한 사람은 당신의 지식 때문에 망하는 것입니다. 그리스도께서는 그 약한 신도를 위하여 죽으셨습니다.", Chn:"", Eng:"So this weak brother, for whom Christ died, is destroyed by your knowledge.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:12, Page:1, Kor:"이렇게 여러분이 b형제자매들에게 죄를 짓고, 그들의 약한 양심을 상하게 하는 것은 그리스도께 죄를 짓는 것입니다.(b 그, '형제들')", Chn:"", Eng:"When you sin against your brothers in this way and wound their weak conscience, you sin against Christ.", Ind:""},
  {Bible:"1Corinthians", Chapter:8, Verse:13, Page:1, Kor:"그러므로 음식이 내 b형제를 걸어서 넘어지게 하는 것이라면, c그가 걸려서 넘어지지 않게 하기 위해서, 나는 평생 고기를 먹지 않겠습니다.(b 그, '형제들' c 그, '나의 형제')", Chn:"", Eng:"Therefore, if what I eat causes my brother to fall into sin, I will never eat meat again, so that I will not cause him to fall.", Ind:""},
]);
