// 고린도전서 2장 · 1Corinthians 2
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Corinthians",2,16);
BibleDB.add([
  {Bible:"1Corinthians", Chapter:2, Verse:1, Page:1, Kor:"<그리스도를 십자가에 못 박히신 분으로 전하다> a형제자매 여러분, 내가 여러분에게로 가서 하나님의 b비밀을 전할 때에, 훌륭한 말이나 지혜로 하지 않았습니다.(a 그, '형제들' b 다른 고대 사본들에는 '증언' 또는 '증거')", Chn:"", Eng:"When I came to you, brothers, I did not come with eloquence or superior wisdom as I proclaimed to you the testimony about God.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:2, Page:1, Kor:"나는 여러분 가운데서 예수 그리스도 곧 십자가에 달리신 그분 밖에는, 아무것도 알지 않기로 작정하였습니다.", Chn:"", Eng:"For I resolved to know nothing while I was with you except Jesus Christ and him crucified.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:3, Page:1, Kor:"내가 여러분과 함께 있을 때에, 나는 약하였으며, 두려워하였으며, 무척 떨었습니다.", Chn:"", Eng:"I came to you in weakness and fear, and with much trembling.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:4, Page:1, Kor:"나의 말과 나의 설교는 c지혜에서 나온 그럴 듯한 말로 한 것이 아니라, d성령의 능력이 나타낸 증거로 한 것입니다.(c 다른 고대 사본들에는 '지혜의 설득력으로' d 그, '영과 능력의 나타남으로')", Chn:"", Eng:"My message and my preaching were not with wise and persuasive words, but with a demonstration of the Spirit's power,", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:5, Page:1, Kor:"그것은, 여러분의 믿음이 사람의 지혜에 바탕을 두지 않고 하나님의 능력에 바탕을 두게 하려는 것이었습니다.", Chn:"", Eng:"so that your faith might not rest on men's wisdom, but on God's power.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:6, Page:1, Kor:"<성령으로 계시하시다> ○그러나 우리는 성숙한 사람들 가운데서는 지혜를 말합니다. 그런데 이 지혜는, 이 세상의 지혜나 멸망하여 버릴 자들인 이 세상 통치자들의 지혜가 아닙니다.", Chn:"", Eng:"We do, however, speak a message of wisdom among the mature, but not the wisdom of this age or of the rulers of this age, who are coming to nothing.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:7, Page:1, Kor:"우리는 비밀로 감추어져 있는 하나님의 지혜를 말합니다. 그것은, 하나님께서 우리를 영광스럽게 하시려고, 영세 전에 미리 정하신 지혜입니다.", Chn:"", Eng:"No, we speak of God's secret wisdom, a wisdom that has been hidden and that God destined for our glory before time began.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:8, Page:1, Kor:"이 세상 통치자들 가운데는, 이 지혜를 아는 사람이 하나도 없습니다. 그들이 알았더라면, 영광의 주님을 십자가에 못 박지 않았을 것입니다.", Chn:"", Eng:"None of the rulers of this age understood it, for if they had, they would not have crucified the Lord of glory.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:9, Page:1, Kor:"그러나 성경에 기록한 바  e\"눈으로 보지 못하고 귀로 듣지 못한 것들, 사람의 마음에 떠오르지 않은 것들을, 하나님께서는 자기를 사랑하는 사람들에게 마련해 주셨다\" 한 것과 같습니다.(e 사 64:4)", Chn:"", Eng:"However, as it is written: \"No eye has seen, no ear has heard, no mind has conceived what God has prepared for those who love him\"--", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:10, Page:1, Kor:"하나님께서는 성령을 통하여 이런 일들을 우리에게 계시해 주셨습니다. 성령은 모든 것을 살피시니, 곧 하나님의 깊은 경륜까지도 살피십니다.", Chn:"", Eng:"but God has revealed it to us by his Spirit. The Spirit searches all things, even the deep things of God.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:11, Page:1, Kor:"사람 속에 있는 그 사람의 영이 아니고서야, 누가 그 사람의 생각을 알 수 있겠습니까? 이와 같이, 하나님의 영이 아니고서는, 아무도 하나님의 생각을 깨닫지 못합니다.", Chn:"", Eng:"For who among men knows the thoughts of a man except the man's spirit within him? In the same way no one knows the thoughts of God except the Spirit of God.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:12, Page:1, Kor:"우리는 세상의 영을 받은 것이 아니라, 하나님에게서 오신 영을 받았습니다. 그것은, 하나님께서 우리에게 은혜로 주신 선물들을 우리로 하여금 깨달아 알게 하시려는 것입니다.", Chn:"", Eng:"We have not received the spirit of the world but the Spirit who is from God, that we may understand what God has freely given us.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:13, Page:1, Kor:"우리가 이 선물들을 말하되, 사람의 지혜에서 배운 말로 하지 아니하고, 성령께서 가르쳐 주시는 말로 합니다. 다시 말하면, f신령한 것을 가지고 신령한 것을 설명하는 것입니다.(f 또는 '신령한 것을 신령한 사람들에게 설명합니다' 또는 '신령한 것은 신령한 언어로 설명합니다')", Chn:"", Eng:"This is what we speak, not in words taught us by human wisdom but in words taught by the Spirit, expressing spiritual truths in spiritual words.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:14, Page:1, Kor:"그러나 g자연에 속한 사람은 하나님의 영에 속한 일들을 받아들이지 아니합니다. 그런 사람에게는 이런 일들이 어리석은 일이며, 그는 이런 일들을 이해할 수 없습니다. 이런 일들은 영적으로만 분별되기 때문입니다.(g 또는 '신령하지 아니한')", Chn:"", Eng:"The man without the Spirit does not accept the things that come from the Spirit of God, for they are foolishness to him, and he cannot understand them, because they are spiritually discerned.", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:15, Page:1, Kor:"신령한 사람은 모든 것을 판단하나, 자기는 아무에게서도 판단을 받지 않습니다.", Chn:"", Eng:"The spiritual man makes judgments about all things, but he himself is not subject to any man's judgment:", Ind:""},
  {Bible:"1Corinthians", Chapter:2, Verse:16, Page:1, Kor:"h\"누가 주님의 마음을 알았습니까? 누가 그분을 가르치겠습니까?\"  그러나 우리는 그리스도의 마음을 가지고 있습니다.(h 사 40:13(칠십인역))", Chn:"", Eng:"\"For who has known the mind of the Lord that he may instruct him?\" But we have the mind of Christ.", Ind:""},
]);
