// 고린도전서 16장 · 1Corinthians 16
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Corinthians",16,24);
BibleDB.add([
  {Bible:"1Corinthians", Chapter:16, Verse:1, Page:1, Kor:"<성도들을 돕는 헌금> 성도들을 도우려고 모으는 헌금에 대하여 말합니다. 내가 갈라디아 여러 교회에 지시한 것과 같이, 여러분도 그대로 하십시오.", Chn:"", Eng:"Now about the collection for God's people: Do what I told the Galatian churches to do.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:2, Page:1, Kor:"매주 첫날에, 여러분은 저마다 수입에 따라 얼마씩을 따로 저축해 두십시오. 그래서 내가 갈 때에, 그제야 헌금하는 일이 없어야 할 것입니다.", Chn:"", Eng:"On the first day of every week, each one of you should set aside a sum of money in keeping with his income, saving it up, so that when I come no collections will have to be made.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:3, Page:1, Kor:"내가 그리로 가게 되면, 그 때에 여러분이 선정한 사람에게 내가 편지를 써 주어서, 그가 여러분의 선물을 가지고 예루살렘으로 가게 하겠습니다.", Chn:"", Eng:"Then, when I arrive, I will give letters of introduction to the men you approve and send them with your gift to Jerusalem.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:4, Page:1, Kor:"나도 가는 것이 좋다면, 그들은 나와 함께 갈 것입니다.", Chn:"", Eng:"If it seems advisable for me to go also, they will accompany me.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:5, Page:1, Kor:"<여행 계획> ○나는 마케도니아를 거쳐서 여러분에게로 가겠습니다. 내가 마케도니아를 지나서", Chn:"", Eng:"After I go through Macedonia, I will come to you--for I will be going through Macedonia.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:6, Page:1, Kor:"여러분에게로 가면, 얼마 동안은 함께 지낼 것이고, 어쩌면 겨울을 나게 될지도 모르겠습니다. 그 다음에 여러분은, 내가 가려는 곳으로 나를 보내 주시기를 바랍니다.", Chn:"", Eng:"Perhaps I will stay with you awhile, or even spend the winter, so that you can help me on my journey, wherever I go.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:7, Page:1, Kor:"지금 나는, 지나가는 길에 잠깐 들러서 여러분을 만나 보려는 것은 아닙니다. 주님께서 허락해 주시면, 얼마 동안 여러분과 함께 머무르고 싶습니다.", Chn:"", Eng:"I do not want to see you now and make only a passing visit; I hope to spend some time with you, if the Lord permits.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:8, Page:1, Kor:"그러나 오순절까지는 에베소에 머물러 있겠습니다.", Chn:"", Eng:"But I will stay on at Ephesus until Pentecost,", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:9, Page:1, Kor:"나에게 큰 문이 활짝 열려서, 일을 많이 할 수 있는 기회가 왔습니다. 그러나 방해를 하는 사람도 많이 있습니다.", Chn:"", Eng:"because a great door for effective work has opened to me, and there are many who oppose me.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:10, Page:1, Kor:"○디모데가 그리로 가거든, 아무 두려움 없이 여러분과 함께 지낼 수 있도록 보살펴 주십시오. 그도 나와 마찬가지로 주님의 일을 하는 사람입니다.", Chn:"", Eng:"If Timothy comes, see to it that he has nothing to fear while he is with you, for he is carrying on the work of the Lord, just as I am.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:11, Page:1, Kor:"그러므로 아무도 그를 업신여겨서는 안 됩니다. 그리고 그가 내게로 돌아올 때에, 그를 평안한 마음을 지니게 해서 보내 주십시오. 나는 형제들과 함께 그를 기다리고 있습니다.", Chn:"", Eng:"No one, then, should refuse to accept him. Send him on his way in peace so that he may return to me. I am expecting him along with the brothers.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:12, Page:1, Kor:"○형제 아볼로에 대하여 말하겠습니다. 내가 그에게 다른 형제들과 함께 여러분에게 가라고 여러 번 권하였지만, a그는 지금, 갈 마음이 전혀 없습니다. 그러나 적절한 때가 오면 갈 것입니다.(a 또는 '이제 가는 것은 전혀 그에 대한 하나님의 뜻이 아닙니다')", Chn:"", Eng:"Now about our brother Apollos: I strongly urged him to go to you with the brothers. He was quite unwilling to go now, but he will go when he has the opportunity.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:13, Page:1, Kor:"<마지막 부탁과 인사> ○깨어 있으십시오. 믿음에 굳게 서 있으십시오. 용감하십시오. 힘을 내십시오.", Chn:"", Eng:"Be on your guard; stand firm in the faith; be men of courage; be strong.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:14, Page:1, Kor:"모든 일을 사랑으로 하십시오.", Chn:"", Eng:"Do everything in love.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:15, Page:1, Kor:"○b형제자매 여러분, 나는 여러분에게 권합니다. 여러분이 아는 바와 같이, 스데바나의 가정은 아가야에서 맺은 첫 열매요, 성도들을 섬기는 일에 몸을 바친 가정입니다.(b 그, '형제들')", Chn:"", Eng:"You know that the household of Stephanas were the first converts in Achaia, and they have devoted themselves to the service of the saints. I urge you, brothers,", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:16, Page:1, Kor:"그러므로 여러분도 이런 사람들에게 순종하십시오. 그리고 또 그들과 더불어 일하며 함께 수고하는 각 사람에게 순종하십시오.", Chn:"", Eng:"to submit to such as these and to everyone who joins in the work, and labors at it.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:17, Page:1, Kor:"나는 스데바나와 브드나도와 아가이고가 온 것을 기뻐합니다. 그것은, 여러분을 만나지 못해서 생긴 아쉬움을, 이 사람들이 채워 주었기 때문입니다.", Chn:"", Eng:"I was glad when Stephanas, Fortunatus and Achaicus arrived, because they have supplied what was lacking from you.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:18, Page:1, Kor:"이 사람들은 나의 마음과 여러분의 마음에 생기를 불어넣어 주었습니다. 여러분은 이런 사람들을 알아주어야 합니다.", Chn:"", Eng:"For they refreshed my spirit and yours also. Such men deserve recognition.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:19, Page:1, Kor:"○아시아에 있는 교회들이 여러분에게 문안합니다. 아굴라와 c브리스가와 그 집에 모이는 교회가 다 함께, 주님 안에서 진심으로 문안합니다.(c 또는 '브리스길라')", Chn:"", Eng:"The churches in the province of Asia send you greetings. Aquila and Priscilla greet you warmly in the Lord, and so does the church that meets at their house.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:20, Page:1, Kor:"모든 b형제자매들이 여러분에게 문안합니다. 거룩한 입맞춤으로 서로 인사하십시오.(b 그, '형제들')", Chn:"", Eng:"All the brothers here send you greetings. Greet one another with a holy kiss.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:21, Page:1, Kor:"○나 바울은 친필로 인사의 말을 씁니다.", Chn:"", Eng:"I, Paul, write this greeting in my own hand.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:22, Page:1, Kor:"누구든지 주님을 사랑하지 않는 사람은 저주를 받으라! d마라나 타, 우리 주님, 오십시오.(d 이 아람어를 달리 마란 아타라고 읽으면, '우리 주님 오셨다'가 됨)", Chn:"", Eng:"If anyone does not love the Lord--a curse be on him. Come, O Lord!", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:23, Page:1, Kor:"주 예수의 은혜가 여러분과 함께 있기를 빕니다.", Chn:"", Eng:"The grace of the Lord Jesus be with you.", Ind:""},
  {Bible:"1Corinthians", Chapter:16, Verse:24, Page:1, Kor:"나는 그리스도 예수 안에서 여러분 모두를 사랑합니다. e아멘.(e 다른 고대 사본들에는 '아멘'이 없음)", Chn:"", Eng:"", Ind:""},
]);
