// 스가랴 9장 · Zechariah 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Zechariah",9,17);
BibleDB.add([
  {Bible:"Zechariah", Chapter:9, Verse:1, Page:1, Kor:"<이스라엘 이웃 나라들에 대한 심판 경고> 주님께서 경고하신 말씀이다. 주님의 말씀이 하드락 땅에 내리고, 다마스쿠스에 머문다. 이방 사람들과 이스라엘의 모든 지파들이 주님을 바라본다.", Chn:"", Eng:"The word of the LORD is against the land of Hadrach and will rest upon Damascus--for the eyes of men and all the tribes of Israel are on the LORD--", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:2, Page:1, Kor:"하드락 가까이에 있는 하맛에도, 매우 지혜롭다고 하는 두로와 시돈에도, 그 말씀이 내린다.", Chn:"", Eng:"and upon Hamath too, which borders on it, and upon Tyre and Sidon, though they are very skillful.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:3, Page:1, Kor:"두로가 저를 지킬 요새를 짓고, 티끌처럼 은을 긁어 모으고, 길거리의 진흙같이 금을 쌓아 놓았지만,", Chn:"", Eng:"Tyre has built herself a stronghold; she has heaped up silver like dust, and gold like the dirt of the streets.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:4, Page:1, Kor:"주님께서 그들을 쫓아내시며 바다에서 떨치던 그의 힘을 깨뜨리시고, 성읍을 불에 태워 멸하실 것이다.", Chn:"", Eng:"But the LORD will take away her possessions and destroy her power on the sea, and she will be consumed by fire.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:5, Page:1, Kor:"아스글론이 그것을 보고 두려워할 것이며, 가사도 무서워서 벌벌 떨 것이며, 에그론도 희망을 잃고 떨 것이다. 가사에서는, 왕의 대가 끊길 것이고 아스글론에는 사는 사람이 없어질 것이다.", Chn:"", Eng:"Ashkelon will see it and fear; Gaza will writhe in agony, and Ekron too, for her hope will wither. Gaza will lose her king and Ashkelon will be deserted.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:6, Page:1, Kor:"아스돗은 낯선 외국인들이 차지할 것이다. 주님께서 말씀하신다. \"내가 블레셋의 교만을 꺾겠다.", Chn:"", Eng:"Foreigners will occupy Ashdod, and I will cut off the pride of the Philistines.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:7, Page:1, Kor:"내가 그들의 입에 묻은 희생제물의 피를 닦아 주고, 그들이 씹는 역겨운 제물을 그 입에서 꺼내 주겠다. 그들 가운데서 남은 자들은, 내 백성이 되어서 유다와 한 가족처럼 되며, 에그론은 여부스 사람처럼 될 것이다.", Chn:"", Eng:"I will take the blood from their mouths, the forbidden food from between their teeth. Those who are left will belong to our God and become leaders in Judah, and Ekron will be like the Jebusites.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:8, Page:1, Kor:"내가 내 집에 진을 둘러쳐서, 적군이 오가지 못하게 하겠다. 내가 지켜 보고 있으니, 압제자가 내 백성을 침범하지 못할 것이다.\"", Chn:"", Eng:"But I will defend my house against marauding forces. Never again will an oppressor overrun my people, for now I am keeping watch.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:9, Page:1, Kor:"<앞으로 올 왕> 도성 시온아, 크게 기뻐하여라. 도성 예루살렘아, 환성을 올려라. 네 왕이 네게로 오신다. 그는 공의로우신 왕, 구원을 베푸시는 왕이시다. 그는 온순하셔서, 나귀 곧 나귀 새끼인 어린 나귀를 타고 오신다.", Chn:"", Eng:"Rejoice greatly, O Daughter of Zion! Shout, Daughter of Jerusalem! See, your king comes to you, righteous and having salvation, gentle and riding on a donkey, on a colt, the foal of a donkey.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:10, Page:1, Kor:"\"내가 에브라임에서 병거를 없애고, 예루살렘에서 군마를 없애며, 전쟁할 때에 쓰는 활도 꺾으려 한다. 그 왕은 이방 민족들에게 평화를 선포할 것이며, 그의 다스림이 이 바다에서 저 바다까지, 유프라테스 강에서 땅 끝까지 이를 것이다.", Chn:"", Eng:"I will take away the chariots from Ephraim and the war-horses from Jerusalem, and the battle bow will be broken. He will proclaim peace to the nations. His rule will extend from sea to sea and from the River to the ends of the earth.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:11, Page:1, Kor:"너에게는 특별히, 너와 나 사이에 피로 맺은 언약이 있으니, 사로잡힌 네 백성을 내가 물 없는 구덩이에서 건져 낼 것이다.", Chn:"", Eng:"As for you, because of the blood of my covenant with you, I will free your prisoners from the waterless pit.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:12, Page:1, Kor:"사로잡혔어도 희망을 잃지 않은 사람들아, 이제 요새로 돌아오너라. 오늘도 또 말한다. 내가 네게 두 배로 갚아 주겠다.", Chn:"", Eng:"Return to your fortress, O prisoners of hope; even now I announce that I will restore twice as much to you.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:13, Page:1, Kor:"유다는 내가 당긴 활이다. 에브라임은 내가 먹인 화살이다. 시온아, 내가 네 자식을 불러 세워서, 그리스의 자식을 치게 하겠다. 내가 너희를 용사의 칼로 삼겠다.\"", Chn:"", Eng:"I will bend Judah as I bend my bow and fill it with Ephraim. I will rouse your sons, O Zion, against your sons, O Greece, and make you like a warrior's sword.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:14, Page:1, Kor:"주님께서 그의 백성에게 나타나셔서 그의 화살을 번개처럼 쏘실 것이다. 주 하나님이 나팔을 부시며, 남쪽에서 회리바람을 일으키며 진군하신다.", Chn:"", Eng:"Then the LORD will appear over them; his arrow will flash like lightning. The Sovereign LORD will sound the trumpet; he will march in the storms of the south,", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:15, Page:1, Kor:"만군의 주님께서 백성을 보호하실 것이니, 그 백성이 원수를 섬멸하여 무릿매 돌 던지는 자들을 짓밟을 것이다. a백성은 그들의 피를 포도주처럼 마실 것이며, 그들은 피가 가득한 동이와도 같고 피로 흠뻑 젖은 제단 뿔과도 같을 것이다. (a 칠십인역을 따름. 히, '백성은 마실 것이며 포도주에 취한 것처럼 소리를 지를 것이다')", Chn:"", Eng:"and the LORD Almighty will shield them. They will destroy and overcome with slingstones. They will drink and roar as with wine; they will be full like a bowl used for sprinkling the corners of the altar.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:16, Page:1, Kor:"그 날에 주 그들의 하나님이 백성을 양 떼같이 여기시고 구원하셔서, 그들을 주님의 땅에 심으시면, 그들은 왕관에 박힌 보석같이 빛날 것이다.", Chn:"", Eng:"The LORD their God will save them on that day as the flock of his people. They will sparkle in his land like jewels in a crown.", Ind:""},
  {Bible:"Zechariah", Chapter:9, Verse:17, Page:1, Kor:"아, 그들이 얼마나 좋고, 얼마나 아름다운가! 총각들은 햇곡식으로 튼튼해지고 처녀들은 새 포도주로 피어날 것이다.", Chn:"", Eng:"How attractive and beautiful they will be! Grain will make the young men thrive, and new wine the young women.", Ind:""},
]);
