// 스가랴 5장 · Zechariah 5
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Zechariah",5,11);
BibleDB.add([
  {Bible:"Zechariah", Chapter:5, Verse:1, Page:1, Kor:"<날아가는 두루마리> 내가 또 고개를 들고 보니, 내 앞에서 두루마리가 날아가고 있었다.", Chn:"", Eng:"I looked again--and there before me was a flying scroll!", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:2, Page:1, Kor:"그 천사는 내가 무엇을 보고 있느냐고 물었다. 내가 대답하였다. \"두루마리가 날아가는 것을 보고 있습니다. 길이는 스무 자이고, 너비는 열 자입니다.\"", Chn:"", Eng:"He asked me, \"What do you see?\" I answered, \"I see a flying scroll, thirty feet long and fifteen feet wide.\"", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:3, Page:1, Kor:"그는 나에게 이렇게 말하였다. \"이것은 온 땅 위에 내릴 저주다. 두루마리의 한 쪽에는 '도둑질하는 자가 모두 땅 위에서 말끔히 없어진다'고 씌어 있고, 두루마리의 다른 쪽에는 '거짓으로 맹세하는 자가 모두 땅 위에서 말끔히 없어진다'고 씌어 있다.\"", Chn:"", Eng:"And he said to me, \"This is the curse that is going out over the whole land; for according to what it says on one side, every thief will be banished, and according to what it says on the other, everyone who swears falsely will be banished.", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:4, Page:1, Kor:"만군의 주의 말이다. \"내가 저주를 내보낸다. 모든 도둑의 집과 내 이름을 두고 거짓으로 맹세하는 모든 자의 집에 저주가 들어가서, 그 집에 머무르면서, 나무 대들보와 돌로 쌓은 벽까지, 그 집을 다 허물어 버릴 것이다.\"", Chn:"", Eng:"The LORD Almighty declares, 'I will send it out, and it will enter the house of the thief and the house of him who swears falsely by my name. It will remain in his house and destroy it, both its timbers and its stones.'\"", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:5, Page:1, Kor:"<뒤주 속의 여인> ○내게 말하는 천사가 앞으로 나와서, 나에게 고개를 들고서, 가까이 오는 물체를 주의해 보라고 말하였다.", Chn:"", Eng:"Then the angel who was speaking to me came forward and said to me, \"Look up and see what this is that is appearing.\"", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:6, Page:1, Kor:"그것이 무엇이냐고 내가 물으니, 그는, 가까이 오는 그것이 곡식을 넣는 a뒤주라고 일러주면서, 그것은 온 땅에 가득한 죄악을 나타내는 것이라고 하였다.(a 히, '에바')", Chn:"", Eng:"I asked, \"What is it?\" He replied, \"It is a measuring basket*\" And he added, \"This is the iniquity of the people throughout the land.\"", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:7, Page:1, Kor:"그 뒤주에는 납으로 된 뚜껑이 덮여 있었다. 내가 보니, 뚜껑이 들리고, 그 안에 여인이 앉아 있는 것이 보였다.", Chn:"", Eng:"Then the cover of lead was raised, and there in the basket sat a woman!", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:8, Page:1, Kor:"천사는 나에게, 그 여인이 죄악의 상징이라고 말해 주고는, 그 여인을 뒤주 속으로 밀어 넣고, 뒤주 아가리 위에 납뚜껑을 눌러서 덮어 버렸다.", Chn:"", Eng:"He said, \"This is wickedness,\" and he pushed her back into the basket and pushed the lead cover down over its mouth.", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:9, Page:1, Kor:"○내가 또 고개를 들고 보니, 내 앞에 두 여인이 날개로 바람을 일으키면서 나타났다. 그들은 학과 같은 날개를 가지고 있었다. 그들은 그 뒤주를 들고 공중으로 높이 날아갔다.", Chn:"", Eng:"Then I looked up--and there before me were two women, with the wind in their wings! They had wings like those of a stork, and they lifted up the basket between heaven and earth.", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:10, Page:1, Kor:"내가 내게 말하는 천사에게, 저 여인들이 그 뒤주를 어디로 가져 가는 것이냐고 물었다.", Chn:"", Eng:"\"Where are they taking the basket?\" I asked the angel who was speaking to me.", Ind:""},
  {Bible:"Zechariah", Chapter:5, Verse:11, Page:1, Kor:"그가 나에게 대답하였다. \"바빌로니아 땅으로 간다. 거기에다가 그 뒤주를 둘 신전을 지을 것이다. 신전이 완성되면, 그 뒤주는 제자리에 놓일 것이다.\"", Chn:"", Eng:"He replied, \"To the country of Babylonia to build a house for it. When it is ready, the basket will be set there in its place.\"", Ind:""},
]);
