// 200,000. 23장 · 200,000. 23
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("200,000.",23,21);
BibleDB.add([
  {Bible:"200,000.", Chapter:23, Verse:1, Page:1, Kor:"", Chn:"", Eng:"In the seventh year Jehoiada showed his strength. He made a covenant with the commanders of units of a hundred: Azariah son of Jeroham, Ishmael son of Jehohanan, Azariah son of Obed, Maaseiah son of Adaiah, and Elishaphat son of Zicri.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:2, Page:1, Kor:"", Chn:"", Eng:"They went throughout Judah and gathered the Levites and the heads of Israelite families from all the towns. When they came to Jerusalem,", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:3, Page:1, Kor:"", Chn:"", Eng:"the whole assembly made a covenant with the king at the temple of God. Jehoiada said to them, "The king's son shall reign, as the LORD promised concerning the descendants of David.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Now this is what you are to do: A third of you priests and Levites who are going on duty on the Sabbath are to keep watch at the doors,", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:5, Page:1, Kor:"", Chn:"", Eng:"a third of you at the royal palace and a third at the Foundation Gate, and all the other men are to be in the courtyards of the temple of the LORD.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:6, Page:1, Kor:"", Chn:"", Eng:"No one is to enter the temple of the LORD except the priests and Levites on duty; they may enter because they are consecrated, but all the other men are to guard what the LORD has assigned to them.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:7, Page:1, Kor:"", Chn:"", Eng:"The Levites are to station themselves around the king, each man with his weapons in his hand. Anyone who enters the temple must be put to death. Stay close to the king wherever he goes."", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:8, Page:1, Kor:"", Chn:"", Eng:"The Levites and all the men of Judah did just as Jehoiada the priest ordered. Each one took his men--those who were going on duty on the Sabbath and those who were going off duty--for Jehoiada the priest had not released any of the divisions.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Then he gave the commanders of units of a hundred the spears and the large and small shields that had belonged to King David and that were in the temple of God.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:10, Page:1, Kor:"", Chn:"", Eng:"He stationed all the men, each with his weapon in his hand, around the king--near the altar and the temple, from the south side to the north side of the temple.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Jehoiada and his sons brought out the king's son and put the crown on him; they presented him with a copy of the covenant and proclaimed him king. They anointed him and shouted, "Long live the king!"", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:12, Page:1, Kor:"", Chn:"", Eng:"When Athaliah heard the noise of the people running and cheering the king, she went to them at the temple of the LORD.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:13, Page:1, Kor:"", Chn:"", Eng:"She looked, and there was the king, standing by his pillar at the entrance. The officers and the trumpeters were beside the king, and all the people of the land were rejoicing and blowing trumpets, and singers with musical instruments were leading the praises. Then Athaliah tore her robes and shouted, "Treason! Treason!"", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Jehoiada the priest sent out the commanders of units of a hundred, who were in charge of the troops, and said to them: "Bring her out between the ranks and put to the sword anyone who follows her." For the priest had said, "Do not put her to death at the temple of the LORD."", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:15, Page:1, Kor:"", Chn:"", Eng:"So they seized her as she reached the entrance of the Horse Gate on the palace grounds, and there they put her to death.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:16, Page:1, Kor:"", Chn:"", Eng:"Jehoiada then made a covenant that he and the people and the king would be the LORD'S people.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:17, Page:1, Kor:"", Chn:"", Eng:"All the people went to the temple of Baal and tore it down. They smashed the altars and idols and killed Mattan the priest of Baal in front of the altars.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:18, Page:1, Kor:"", Chn:"", Eng:"Then Jehoiada placed the oversight of the temple of the LORD in the hands of the priests, who were Levites, to whom David had made assignments in the temple, to present the burnt offerings of the LORD as written in the Law of Moses, with rejoicing and singing, as David had ordered.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:19, Page:1, Kor:"", Chn:"", Eng:"He also stationed doorkeepers at the gates of the LORD'S temple so that no one who was in any way unclean might enter.", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:20, Page:1, Kor:"", Chn:"", Eng:"He took with him the commanders of hundreds, the nobles, the rulers of the people and all the people of the land and brought the king down from the temple of the LORD. They went into the palace through the Upper Gate and seated the king on the royal throne,", Ind:""},
  {Bible:"200,000.", Chapter:23, Verse:21, Page:1, Kor:"", Chn:"", Eng:"and all the people of the land rejoiced. And the city was quiet, because Athaliah had been slain with the sword.", Ind:""},
]);
