// 베드로전서 1장 · 1Peter 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Peter",1,25);
BibleDB.add([
  {Bible:"1Peter", Chapter:1, Verse:1, Page:1,
    Kor:"<인사> 예수 그리스도의 사도인 베드로가, 본도와 갈라디아와 갑바도기아와 아시아와 비두니아에 흩어져서 사는 나그네들인, 택하심을 입은 이들에게 이 편지를 씁니다.",
    Chn:"耶稣基督的使徒彼得写信给那分散在本都、加拉太、加帕多家、亚细亚、庇推尼寄居的，",
    Eng:"Peter, an apostle of Jesus Christ, To God's elect, strangers in the world, scattered throughout Pontus, Galatia, Cappadocia, Asia and Bithynia,",
    Ind:"Dari Petrus, rasul Yesus Kristus, kepada orang-orang pendatang, yang tersebar di Pontus, Galatia, Kapadokia, Asia Kecil dan Bitinia,"
  },
  {Bible:"1Peter", Chapter:1, Verse:2, Page:1,
    Kor:"하나님 아버지께서 여러분을 미리 아시고 성령으로 거룩하게 해 주셔서, 여러분은 순종하게 되고, 예수 그리스도의 피 뿌림을 받게 되었습니다. 여러분에게 은혜와 평화가 더욱 가득 차기를 빕니다.",
    Chn:"就是照父　神的先见被拣选，借着圣灵得成圣洁，以致顺服耶稣基督，又蒙他血所洒的人。愿恩惠、平安多多地加给你们。",
    Eng:"who have been chosen according to the foreknowledge of God the Father, through the sanctifying work of the Spirit, for obedience to Jesus Christ and sprinkling by his blood: Grace and peace be yours in abundance.",
    Ind:"yaitu orang-orang yang dipilih, sesuai dengan rencana Allah, Bapa kita, dan yang dikuduskan oleh Roh, supaya taat kepada Yesus Kristus dan menerima percikan darah-Nya. Kiranya kasih karunia dan damai sejahtera makin melimpah atas kamu."
  },
  {Bible:"1Peter", Chapter:1, Verse:3, Page:1,
    Kor:"<산 소망> ○우리 주 예수 그리스도의 하나님 아버지께 찬양을 드립시다. 하나님께서는 그 크신 자비로 우리를 새로 태어나게 하셨습니다. 그리하여 그는, 죽은 사람들 가운데서 예수 그리스도가 부활하심으로 말미암아 우리로 하여금 산 a소망을 갖게 해 주셨으며,(a 또는 '희망')",
    Chn:"愿颂赞归与我们主耶稣基督的父　神！他曾照自己的大怜悯，借耶稣基督从死里复活，重生了我们，叫我们有活泼的盼望，",
    Eng:"Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead,",
    Ind:"Terpujilah Allah dan Bapa Tuhan kita Yesus Kristus, yang karena rahmat-Nya yang besar telah melahirkan kita kembali oleh kebangkitan Yesus Kristus dari antara orang mati, kepada suatu hidup yang penuh pengharapan,"
  },
  {Bible:"1Peter", Chapter:1, Verse:4, Page:1,
    Kor:"썩지 않고 더러워지지 않고 낡아 없어지지 않는 유산을 물려받게 하셨습니다. 이 유산은 여러분을 위하여 하늘에 간직되어 있습니다.",
    Chn:"可以得着不能朽坏、不能玷污、不能衰残、为你们存留在天上的基业。",
    Eng:"and into an inheritance that can never perish, spoil or fade--kept in heaven for you,",
    Ind:"untuk menerima suatu bagian yang tidak dapat binasa, yang tidak dapat cemar dan yang tidak dapat layu, yang tersimpan di sorga bagi kamu."
  },
  {Bible:"1Peter", Chapter:1, Verse:5, Page:1,
    Kor:"하나님께서는 여러분의 믿음을 보시고 그의 능력으로 여러분을 보호해 주시며, 마지막 때에 나타나기로 되어 있는 구원을 얻게 해 주십니다.",
    Chn:"你们这因信蒙　神能力保守的人，必能得着所预备、到末世要显现的救恩。",
    Eng:"who through faith are shielded by God's power until the coming of the salvation that is ready to be revealed in the last time.",
    Ind:"Yaitu kamu, yang dipelihara dalam kekuatan Allah karena imanmu sementara kamu menantikan keselamatan yang telah tersedia untuk dinyatakan pada zaman akhir."
  },
  {Bible:"1Peter", Chapter:1, Verse:6, Page:1,
    Kor:"그러므로 여러분이 지금 잠시동안 여러 가지 시련 속에서 어쩔 수 없이 슬픔을 당하게 되었다 하더라도 기뻐하십시오.",
    Chn:"因此，你们是大有喜乐；但如今，在百般的试炼中暂时忧愁，",
    Eng:"In this you greatly rejoice, though now for a little while you may have had to suffer grief in all kinds of trials.",
    Ind:"Bergembiralah akan hal itu, sekalipun sekarang ini kamu seketika harus berdukacita oleh berbagai-bagai pencobaan."
  },
  {Bible:"1Peter", Chapter:1, Verse:7, Page:1,
    Kor:"하나님께서는 여러분의 믿음을 단련하셔서, 불로 단련하지만 결국 없어지고 마는 금보다 더 귀한 것이 되게 하시며, 예수 그리스도께서 나타나실 때에 여러분에게 칭찬과 영광과 존귀를 얻게 해 주십니다.",
    Chn:"叫你们的信心既被试验，就比那被火试验仍然能坏的金子更显宝贵，可以在耶稣基督显现的时候得着称赞、荣耀、尊贵。",
    Eng:"These have come so that your faith--of greater worth than gold, which perishes even though refined by fire--may be proved genuine and may result in praise, glory and honor when Jesus Christ is revealed.",
    Ind:"Maksud semuanya itu ialah untuk membuktikan kemurnian imanmu--yang jauh lebih tinggi nilainya dari pada emas yang fana, yang diuji kemurniannya dengan api--sehingga kamu memperoleh puji-pujian dan kemuliaan dan kehormatan pada hari Yesus Kristus menyatakan diri-Nya."
  },
  {Bible:"1Peter", Chapter:1, Verse:8, Page:1,
    Kor:"여러분은 그리스도를 본 일이 없으면서도 사랑하며, 지금 그를 보지 못하면서도 믿으며, 말로 다 표현할 수 없는 즐거움과 영광을 누리면서 기뻐하고 있습니다.",
    Chn:"你们虽然没有见过他，却是爱他；如今虽不得看见，却因信他就有说不出来、满有荣光的大喜乐；",
    Eng:"Though you have not seen him, you love him; and even though you do not see him now, you believe in him and are filled with an inexpressible and glorious joy,",
    Ind:"Sekalipun kamu belum pernah melihat Dia, namun kamu mengasihi-Nya. Kamu percaya kepada Dia, sekalipun kamu sekarang tidak melihat-Nya. Kamu bergembira karena sukacita yang mulia dan yang tidak terkatakan,"
  },
  {Bible:"1Peter", Chapter:1, Verse:9, Page:1,
    Kor:"여러분은 믿음의 목표 곧 여러분의 영혼의 구원을 받고 있는 것입니다.",
    Chn:"并且得着你们信心的果效，就是灵魂的救恩。",
    Eng:"for you are receiving the goal of your faith, the salvation of your souls.",
    Ind:"karena kamu telah mencapai tujuan imanmu, yaitu keselamatan jiwamu."
  },
  {Bible:"1Peter", Chapter:1, Verse:10, Page:1,
    Kor:"○예언자들은 이 구원을 자세히 살피고 연구하였습니다. 그들은 여러분이 받을 은혜를 예언하였습니다.",
    Chn:"论到这救恩，那预先说你们要得恩典的众先知早已详细地寻求考察，",
    Eng:"Concerning this salvation, the prophets, who spoke of the grace that was to come to you, searched intently and with the greatest care,",
    Ind:"Keselamatan itulah yang diselidiki dan diteliti oleh nabi-nabi, yang telah bernubuat tentang kasih karunia yang diuntukkan bagimu."
  },
  {Bible:"1Peter", Chapter:1, Verse:11, Page:1,
    Kor:"누구에게 또는 어느 때에 이런 일이 일어날 것인지를 그들이 연구할 때에, 그들 안에 계신 그리스도의 영이 그리스도에게 닥칠 고난과 그 뒤에 올 영광을 미리 증언하여 드러내 주셨습니다.",
    Chn:"就是考察在他们心里基督的灵，预先证明基督受苦难，后来得荣耀，是指着什么时候，并怎样的时候。",
    Eng:"trying to find out the time and circumstances to which the Spirit of Christ in them was pointing when he predicted the sufferings of Christ and the glories that would follow.",
    Ind:"Dan mereka meneliti saat yang mana dan yang bagaimana yang dimaksudkan oleh Roh Kristus, yang ada di dalam mereka, yaitu Roh yang sebelumnya memberi kesaksian tentang segala penderitaan yang akan menimpa Kristus dan tentang segala kemuliaan yang menyusul sesudah itu."
  },
  {Bible:"1Peter", Chapter:1, Verse:12, Page:1,
    Kor:"예언자들은 자기들이 섬긴 그 일들이, 자기들을 위한 것이 아니라 여러분을 위한 것임을 계시로 알게 되었습니다. 그 일들은 하늘로부터 보내주신 성령을 힘입어서 여러분에게 복음을 전한 사람들이 이제 여러분에게 선포한 것입니다. 그 일들은 천사들도 보고 싶어하는 것입니다.",
    Chn:"他们得了启示，知道他们所传讲的一切事，不是为自己，乃是为你们。那靠着从天上差来的圣灵传福音给你们的人，现在将这些事报给你们；天使也愿意详细察看这些事。",
    Eng:"It was revealed to them that they were not serving themselves but you, when they spoke of the things that have now been told you by those who have preached the gospel to you by the Holy Spirit sent from heaven. Even angels long to look into these things.",
    Ind:"Kepada mereka telah dinyatakan, bahwa mereka bukan melayani diri mereka sendiri, tetapi melayani kamu dengan segala sesuatu yang telah diberitakan sekarang kepada kamu dengan perantaraan mereka, yang oleh Roh Kudus, yang diutus dari sorga, menyampaikan berita Injil kepada kamu, yaitu hal-hal yang ingin diketahui oleh malaikat-malaikat."
  },
  {Bible:"1Peter", Chapter:1, Verse:13, Page:1,
    Kor:"<불러주심에 따르는 거룩한 생활> ○그러므로 여러분은 마음을 단단히 먹고 정신을 차려서, 예수 그리스도께서 나타나실 때에 여러분이 받을 은혜를 끝까지 바라고 있으십시오.",
    Chn:"所以要约束你们的心，谨慎自守，专心盼望耶稣基督显现的时候所带来给你们的恩。",
    Eng:"Therefore, prepare your minds for action; be self-controlled; set your hope fully on the grace to be given you when Jesus Christ is revealed.",
    Ind:"Sebab itu siapkanlah akal budimu, waspadalah dan letakkanlah pengharapanmu seluruhnya atas kasih karunia yang dianugerahkan kepadamu pada waktu penyataan Yesus Kristus."
  },
  {Bible:"1Peter", Chapter:1, Verse:14, Page:1,
    Kor:"순종하는 자녀로서 여러분은 전에 모르고 좇았던 욕망을 따라 살지 말고,",
    Chn:"你们既作顺命的儿女，就不要效法从前蒙昧无知的时候那放纵私欲的样子。",
    Eng:"As obedient children, do not conform to the evil desires you had when you lived in ignorance.",
    Ind:"Hiduplah sebagai anak-anak yang taat dan jangan turuti hawa nafsu yang menguasai kamu pada waktu kebodohanmu,"
  },
  {Bible:"1Peter", Chapter:1, Verse:15, Page:1,
    Kor:"여러분을 불러주신 그 거룩하신 분을 따라 모든 행실을 거룩하게 하십시오.",
    Chn:"那召你们的既是圣洁，你们在一切所行的事上也要圣洁。",
    Eng:"But just as he who called you is holy, so be holy in all you do;",
    Ind:"tetapi hendaklah kamu menjadi kudus di dalam seluruh hidupmu sama seperti Dia yang kudus, yang telah memanggil kamu,"
  },
  {Bible:"1Peter", Chapter:1, Verse:16, Page:1,
    Kor:"성경에 기록하기를 b\"내가 거룩하니 너희도 거룩하여라\" 하였습니다.(b 레 11:44, 45; 19:2; 20:7)",
    Chn:"因为经上记着说：「你们要圣洁，因为我是圣洁的。」",
    Eng:"for it is written: \"Be holy, because I am holy.\"",
    Ind:"sebab ada tertulis: Kuduslah kamu, sebab Aku kudus."
  },
  {Bible:"1Peter", Chapter:1, Verse:17, Page:1,
    Kor:"○그리고 사람을 겉모양으로 판단하지 않으시고 각 사람의 행위대로 심판하시는 분을 여러분이 아버지라고 부르고 있으니, 여러분은 나그네 삶을 사는 동안 두려운 마음으로 살아가십시오.",
    Chn:"你们既称那不偏待人、按各人行为审判人的主为父，就当存敬畏的心度你们在世寄居的日子，",
    Eng:"Since you call on a Father who judges each man's work impartially, live your lives as strangers here in reverent fear.",
    Ind:"Dan jika kamu menyebut-Nya Bapa, yaitu Dia yang tanpa memandang muka menghakimi semua orang menurut perbuatannya, maka hendaklah kamu hidup dalam ketakutan selama kamu menumpang di dunia ini."
  },
  {Bible:"1Peter", Chapter:1, Verse:18, Page:1,
    Kor:"여러분은 조상으로부터 물려받은 여러분의 헛된 생활방식에서 해방되었습니다. 여러분도 아시지만, 그것은 은이나 금과 같은 썩어질 것으로 된 것이 아니라,",
    Chn:"知道你们得赎，脱去你们祖宗所传流虚妄的行为，不是凭着能坏的金银等物，",
    Eng:"For you know that it was not with perishable things such as silver or gold that you were redeemed from the empty way of life handed down to you from your forefathers,",
    Ind:"Sebab kamu tahu, bahwa kamu telah ditebus dari cara hidupmu yang sia-sia yang kamu warisi dari nenek moyangmu itu bukan dengan barang yang fana, bukan pula dengan perak atau emas,"
  },
  {Bible:"1Peter", Chapter:1, Verse:19, Page:1,
    Kor:"흠이 없고 티가 없는 어린 양의 피와 같은 그리스도의 귀한 피로 되었습니다.",
    Chn:"乃是凭着基督的宝血，如同无瑕疵、无玷污的羔羊之血。",
    Eng:"but with the precious blood of Christ, a lamb without blemish or defect.",
    Ind:"melainkan dengan darah yang mahal, yaitu darah Kristus yang sama seperti darah anak domba yang tak bernoda dan tak bercacat."
  },
  {Bible:"1Peter", Chapter:1, Verse:20, Page:1,
    Kor:"하나님께서는 이 그리스도를 세상이 창조되기 전에 미리 아셨고, 이 마지막 때에 여러분을 위하여 나타내셨습니다.",
    Chn:"基督在创世以前是预先被　神知道的，却在这末世才为你们显现。",
    Eng:"He was chosen before the creation of the world, but was revealed in these last times for your sake.",
    Ind:"Ia telah dipilih sebelum dunia dijadikan, tetapi karena kamu baru menyatakan diri-Nya pada zaman akhir."
  },
  {Bible:"1Peter", Chapter:1, Verse:21, Page:1,
    Kor:"여러분은 그리스도로 말미암아 하나님을 믿고 있습니다. 하나님은 그리스도를 죽은 사람 가운데서 살리시고 그에게 영광을 주셨습니다. 그래서 여러분의 믿음과 소망은 하나님을 향해 있습니다.",
    Chn:"你们也因着他，信那叫他从死里复活、又给他荣耀的　神，叫你们的信心和盼望都在于　神。",
    Eng:"Through him you believe in God, who raised him from the dead and glorified him, and so your faith and hope are in God.",
    Ind:"Oleh Dialah kamu percaya kepada Allah, yang telah membangkitkan Dia dari antara orang mati dan yang telah memuliakan-Nya, sehingga imanmu dan pengharapanmu tertuju kepada Allah."
  },
  {Bible:"1Peter", Chapter:1, Verse:22, Page:1,
    Kor:"○여러분은 진리에 순종함으로 c영혼을 정결하게 하여서 꾸밈없이 서로 사랑하기에 이르렀으니, <순결한> 마음으로 서로 d뜨겁게 사랑하십시오.(c 다른 고대 사본들에는 '성령(그, '영')을 통하여'가 더 있음 d 또는 '변함없이' 또는 '깊게')",
    Chn:"你们既因顺从真理，洁净了自己的心，以致爱弟兄没有虚假，就当从心里彼此切实相爱。",
    Eng:"Now that you have purified yourselves by obeying the truth so that you have sincere love for your brothers, love one another deeply, from the heart.",
    Ind:"Karena kamu telah menyucikan dirimu oleh ketaatan kepada kebenaran, sehingga kamu dapat mengamalkan kasih persaudaraan yang tulus ikhlas, hendaklah kamu bersungguh-sungguh saling mengasihi dengan segenap hatimu."
  },
  {Bible:"1Peter", Chapter:1, Verse:23, Page:1,
    Kor:"여러분은 다시 태어났습니다. 그것은 썩을 씨로 그렇게 된 것이 아니라, 썩지 않을 씨 곧 e살아 계시고 영원하신 하나님의 말씀으로 그렇게 되었습니다.(e 또는 '하나님의 살아 있는 영원한 말씀으로')",
    Chn:"你们蒙了重生，不是由于能坏的种子，乃是由于不能坏的种子，是借着　神活泼常存的道。",
    Eng:"For you have been born again, not of perishable seed, but of imperishable, through the living and enduring word of God.",
    Ind:"Karena kamu telah dilahirkan kembali bukan dari benih yang fana, tetapi dari benih yang tidak fana, oleh firman Allah, yang hidup dan yang kekal."
  },
  {Bible:"1Peter", Chapter:1, Verse:24, Page:1,
    Kor:"f\"모든 육체는 풀과 같고, 그 모든 영광은 풀의 꽃과 같다. 풀은 마르고 꽃은 떨어지되, (f 사 40:6-8(칠십인역))",
    Chn:"因为 凡有血气的，尽都如草； 他的美荣都像草上的花。 草必枯干，花必凋谢；",
    Eng:"For, \"All men are like grass, and all their glory is like the flowers of the field; the grass withers and the flowers fall,",
    Ind:"Sebab: \"Semua yang hidup adalah seperti rumput dan segala kemuliaannya seperti bunga rumput, rumput menjadi kering, dan bunga gugur,"
  },
  {Bible:"1Peter", Chapter:1, Verse:25, Page:1,
    Kor:"주님의 말씀은 영원히 있다.\" 이것이 여러분에게 복음으로 전해진 말씀입니다.",
    Chn:"惟有主的道是永存的。 所传给你们的福音就是这道。",
    Eng:"but the word of the Lord stands forever.\" And this is the word that was preached to you.",
    Ind:"tetapi firman Tuhan tetap untuk selama-lamanya.\" Inilah firman yang disampaikan Injil kepada kamu."
  },
]);
