// 베드로전서 2장 · 1Peter 2
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Peter",2,25);
BibleDB.add([
  {Bible:"1Peter", Chapter:2, Verse:1, Page:1,
    Kor:"<살아 있는 돌과 거룩한 국민> 그러므로 여러분은 모든 악의와 모든 기만과 위선과 시기와 온갖 비방하는 말을 버리십시오.",
    Chn:"所以，你们既除去一切的恶毒、诡诈，并假善、嫉妒，和一切毁谤的话，",
    Eng:"Therefore, rid yourselves of all malice and all deceit, hypocrisy, envy, and slander of every kind.",
    Ind:"Karena itu buanglah segala kejahatan, segala tipu muslihat dan segala macam kemunafikan, kedengkian dan fitnah."
  },
  {Bible:"1Peter", Chapter:2, Verse:2, Page:1,
    Kor:"갓난 아기들처럼 순수하고 신령한 젖을 그리워하십시오. 여러분은 그것을 먹고 자라서 구원에 이르러야 합니다.",
    Chn:"就要爱慕那纯净的灵奶，像才生的婴孩爱慕奶一样，叫你们因此渐长，以致得救。",
    Eng:"Like newborn babies, crave pure spiritual milk, so that by it you may grow up in your salvation,",
    Ind:"Dan jadilah sama seperti bayi yang baru lahir, yang selalu ingin akan air susu yang murni dan yang rohani, supaya olehnya kamu bertumbuh dan beroleh keselamatan,"
  },
  {Bible:"1Peter", Chapter:2, Verse:3, Page:1,
    Kor:"여러분은 주님의 인자하심을 맛보았습니다.",
    Chn:"你们若尝过主恩的滋味，就必如此。",
    Eng:"now that you have tasted that the Lord is good.",
    Ind:"jika kamu benar-benar telah mengecap kebaikan Tuhan."
  },
  {Bible:"1Peter", Chapter:2, Verse:4, Page:1,
    Kor:"주님께 나아오십시오. 그는 사람에게는 버림을 받으셨으나, 하나님께는 택하심을 받은 살아 있는 귀한 돌입니다.",
    Chn:"主乃活石，固然是被人所弃的，却是被　神所拣选、所宝贵的。",
    Eng:"As you come to him, the living Stone--rejected by men but chosen by God and precious to him--",
    Ind:"Dan datanglah kepada-Nya, batu yang hidup itu, yang memang dibuang oleh manusia, tetapi yang dipilih dan dihormat di hadirat Allah."
  },
  {Bible:"1Peter", Chapter:2, Verse:5, Page:1,
    Kor:"살아 있는 돌과 같은 존재로서 여러분도 집 짓는 데 사용되어 신령한 집이 됩니다. 그래서 여러분은 예수 그리스도로 말미암아 하나님께서 기쁘게 받으실 신령한 제사를 드리는 거룩한 제사장이 되십니다.",
    Chn:"你们来到主面前，也就像活石，被建造成为灵宫，作圣洁的祭司，借着耶稣基督奉献　神所悦纳的灵祭。",
    Eng:"you also, like living stones, are being built into a spiritual house to be a holy priesthood, offering spiritual sacrifices acceptable to God through Jesus Christ.",
    Ind:"Dan biarlah kamu juga dipergunakan sebagai batu hidup untuk pembangunan suatu rumah rohani, bagi suatu imamat kudus, untuk mempersembahkan persembahan rohani yang karena Yesus Kristus berkenan kepada Allah."
  },
  {Bible:"1Peter", Chapter:2, Verse:6, Page:1,
    Kor:"성경에 이런 말씀이 있습니다.  a\"보아라, 내가 골라낸 귀한 모퉁이 돌 하나를 시온에 둔다. 그를 믿는 사람은 결코 부끄러움을 당하지 않을 것이다.\" (a 사 28:16(칠십인역))",
    Chn:"因为经上说： 看哪，我把所拣选、 所宝贵的房角石安放在锡安； 信靠他的人必不至于羞愧。",
    Eng:"For in Scripture it says: \"See, I lay a stone in Zion, a chosen and precious cornerstone, and the one who trusts in him will never be put to shame.\"",
    Ind:"Sebab ada tertulis dalam Kitab Suci: \"Sesungguhnya, Aku meletakkan di Sion sebuah batu yang terpilih, sebuah batu penjuru yang mahal, dan siapa yang percaya kepada-Nya, tidak akan dipermalukan.\""
  },
  {Bible:"1Peter", Chapter:2, Verse:7, Page:1,
    Kor:"그러므로 이 돌은 믿는 사람들인 여러분에게는 귀한 것이지만, 믿지 않는 사람들에게는,  b\"집 짓는 자들이 버렸으나, 모퉁이의 머릿돌이 된 돌\"이요, (b 시 118:22(칠십인역))",
    Chn:"所以，他在你们信的人就为宝贵，在那不信的人有话说： 匠人所弃的石头 已作了房角的头块石头。",
    Eng:"Now to you who believe, this stone is precious. But to those who do not believe, \"The stone the builders rejected has become the capstone,\"",
    Ind:"Karena itu bagi kamu, yang percaya, ia mahal, tetapi bagi mereka yang tidak percaya: \"Batu yang telah dibuang oleh tukang-tukang bangunan, telah menjadi batu penjuru, juga telah menjadi batu sentuhan dan suatu batu sandungan.\""
  },
  {Bible:"1Peter", Chapter:2, Verse:8, Page:1,
    Kor:"또한  c\"걸리는 돌과 넘어지게 하는 바위\"입니다. 그들이 걸려서 넘어지는 것은 말씀을 순종하지 않기 때문이며, 또한 그렇게 되도록 정해 놓으셨기 때문입니다.(c 사 8:14)",
    Chn:"又说：作了绊脚的石头，跌人的磐石。他们既不顺从，就在道理上绊跌；他们这样绊跌也是预定的。",
    Eng:"and, \"A stone that causes men to stumble and a rock that makes them fall.\" They stumble because they disobey the message--which is also what they were destined for.",
    Ind:"Mereka tersandung padanya, karena mereka tidak taat kepada Firman Allah; dan untuk itu mereka juga telah disediakan."
  },
  {Bible:"1Peter", Chapter:2, Verse:9, Page:1,
    Kor:"○d그러나 여러분은 택하심을 받은 족속이요, 왕과 같은 제사장들이요, 거룩한 민족이요, 하나님의 소유가 된 백성입니다. 그래서 여러분을 어둠에서 불러내어 자기의 놀라운 빛 가운데로 인도하신 분의 업적을, 여러분이 선포하는 것입니다.(d 사 43:20; 출 19:5-6; 사 43:21)",
    Chn:"惟有你们是被拣选的族类，是有君尊的祭司，是圣洁的国度，是属　神的子民，要叫你们宣扬那召你们出黑暗入奇妙光明者的美德。",
    Eng:"But you are a chosen people, a royal priesthood, a holy nation, a people belonging to God, that you may declare the praises of him who called you out of darkness into his wonderful light.",
    Ind:"Tetapi kamulah bangsa yang terpilih, imamat yang rajani, bangsa yang kudus, umat kepunyaan Allah sendiri, supaya kamu memberitakan perbuatan-perbuatan yang besar dari Dia, yang telah memanggil kamu keluar dari kegelapan kepada terang-Nya yang ajaib:"
  },
  {Bible:"1Peter", Chapter:2, Verse:10, Page:1,
    Kor:"여러분이 전에는 하나님의 백성이 아니었으나, 지금은 하나님의 백성이요, 전에는 자비를 입지 못한 사람이었으나, 지금은 자비를 입은 사람입니다.",
    Chn:"你们从前算不得子民， 现在却作了　神的子民； 从前未曾蒙怜恤， 现在却蒙了怜恤。",
    Eng:"Once you were not a people, but now you are the people of God; once you had not received mercy, but now you have received mercy.",
    Ind:"kamu, yang dahulu bukan umat Allah, tetapi yang sekarang telah menjadi umat-Nya, yang dahulu tidak dikasihani tetapi yang sekarang telah beroleh belas kasihan."
  },
  {Bible:"1Peter", Chapter:2, Verse:11, Page:1,
    Kor:"<하나님의 종으로 살라> ○사랑하는 여러분, 나는 나그네와 거류민 같은 여러분에게 권합니다. 영혼을 거슬러 싸우는 육체적 정욕을 멀리하십시오.",
    Chn:"亲爱的弟兄啊，你们是客旅，是寄居的。我劝你们要禁戒肉体的私欲；这私欲是与灵魂争战的。",
    Eng:"Dear friends, I urge you, as aliens and strangers in the world, to abstain from sinful desires, which war against your soul.",
    Ind:"Saudara-saudaraku yang kekasih, aku menasihati kamu, supaya sebagai pendatang dan perantau, kamu menjauhkan diri dari keinginan-keinginan daging yang berjuang melawan jiwa."
  },
  {Bible:"1Peter", Chapter:2, Verse:12, Page:1,
    Kor:"여러분은 이방 사람 가운데서 행실을 바르게 하십시오. 그렇게 해야 그들은 여러분더러 악을 행하는 자라고 욕하다가도, 여러분의 바른 행위를 보고 하나님께서 찾아오시는 날에 하나님께 영광을 돌릴 것입니다.",
    Chn:"你们在外邦人中，应当品行端正，叫那些毁谤你们是作恶的，因看见你们的好行为，便在鉴察的日子归荣耀给　神。",
    Eng:"Live such good lives among the pagans that, though they accuse you of doing wrong, they may see your good deeds and glorify God on the day he visits us.",
    Ind:"Milikilah cara hidup yang baik di tengah-tengah bangsa-bangsa bukan Yahudi, supaya apabila mereka memfitnah kamu sebagai orang durjana, mereka dapat melihatnya dari perbuatan-perbuatanmu yang baik dan memuliakan Allah pada hari Ia melawat mereka."
  },
  {Bible:"1Peter", Chapter:2, Verse:13, Page:1,
    Kor:"○여러분은 인간이 세운 모든 제도에 주님을 위하여 복종하십시오. 주권자인 왕에게나,",
    Chn:"你们为主的缘故，要顺服人的一切制度，或是在上的君王，",
    Eng:"Submit yourselves for the Lord's sake to every authority instituted among men: whether to the king, as the supreme authority,",
    Ind:"Tunduklah, karena Allah, kepada semua lembaga manusia, baik kepada raja sebagai pemegang kekuasaan yang tertinggi,"
  },
  {Bible:"1Peter", Chapter:2, Verse:14, Page:1,
    Kor:"총독들에게나, 그렇게 하십시오. 총독들은 악을 행하는 사람에게 벌을 주고 선을 행하는 사람에게 상을 주게 하려고 왕이 보낸 이들입니다.",
    Chn:"或是君王所派罚恶赏善的臣宰。",
    Eng:"or to governors, who are sent by him to punish those who do wrong and to commend those who do right.",
    Ind:"maupun kepada wali-wali yang diutusnya untuk menghukum orang-orang yang berbuat jahat dan menghormati orang-orang yang berbuat baik."
  },
  {Bible:"1Peter", Chapter:2, Verse:15, Page:1,
    Kor:"선을 행함으로 어리석은 자들의 무지한 입을 막는 것이 하나님의 뜻입니다.",
    Chn:"因为　神的旨意原是要你们行善，可以堵住那糊涂无知人的口。",
    Eng:"For it is God's will that by doing good you should silence the ignorant talk of foolish men.",
    Ind:"Sebab inilah kehendak Allah, yaitu supaya dengan berbuat baik kamu membungkamkan kepicikan orang-orang yang bodoh."
  },
  {Bible:"1Peter", Chapter:2, Verse:16, Page:1,
    Kor:"여러분은 자유인으로 사십시오. 그러나 그 자유를 악을 행하는 구실로 쓰지 말고, 하나님의 종으로 사십시오.",
    Chn:"你们虽是自由的，却不可借着自由遮盖恶毒，总要作　神的仆人。",
    Eng:"Live as free men, but do not use your freedom as a cover-up for evil; live as servants of God.",
    Ind:"Hiduplah sebagai orang merdeka dan bukan seperti mereka yang menyalahgunakan kemerdekaan itu untuk menyelubungi kejahatan-kejahatan mereka, tetapi hiduplah sebagai hamba Allah."
  },
  {Bible:"1Peter", Chapter:2, Verse:17, Page:1,
    Kor:"모든 사람을 존중하며, 믿음의 식구들을 사랑하며, 하나님을 두려워하며, 왕을 공경하십시오.",
    Chn:"务要尊敬众人，亲爱教中的弟兄，敬畏　神，尊敬君王。",
    Eng:"Show proper respect to everyone: Love the brotherhood of believers, fear God, honor the king.",
    Ind:"Hormatilah semua orang, kasihilah saudara-saudaramu, takutlah akan Allah, hormatilah raja!"
  },
  {Bible:"1Peter", Chapter:2, Verse:18, Page:1,
    Kor:"<그리스도의 고난> ○하인으로 있는 여러분, 극히 두려운 마음으로 주인에게 복종하십시오. 선량하고 너그러운 주인에게만 아니라, 까다로운 주인에게도 그리하십시오.",
    Chn:"你们作仆人的，凡事要存敬畏的心顺服主人；不但顺服那善良温和的，就是那乖僻的也要顺服。",
    Eng:"Slaves, submit yourselves to your masters with all respect, not only to those who are good and considerate, but also to those who are harsh.",
    Ind:"Hai kamu, hamba-hamba, tunduklah dengan penuh ketakutan kepada tuanmu, bukan saja kepada yang baik dan peramah, tetapi juga kepada yang bengis."
  },
  {Bible:"1Peter", Chapter:2, Verse:19, Page:1,
    Kor:"억울하게 고난을 당하더라도 하나님을 생각하면서 괴로움을 참으면, 그것은 아름다운 일입니다.",
    Chn:"倘若人为叫良心对得住　神，就忍受冤屈的苦楚，这是可喜爱的。",
    Eng:"For it is commendable if a man bears up under the pain of unjust suffering because he is conscious of God.",
    Ind:"Sebab adalah kasih karunia, jika seorang karena sadar akan kehendak Allah menanggung penderitaan yang tidak harus ia tanggung."
  },
  {Bible:"1Peter", Chapter:2, Verse:20, Page:1,
    Kor:"죄를 짓고 매를 맞으면서 참으면, 그것이 무슨 자랑이 되겠습니까? 그러나 선을 행하다가 고난을 당하면서 참으면, 그것은 하나님께서 보시기에 아름다운 일입니다.",
    Chn:"你们若因犯罪受责打，能忍耐，有什么可夸的呢？但你们若因行善受苦，能忍耐，这在　神看是可喜爱的。",
    Eng:"But how is it to your credit if you receive a beating for doing wrong and endure it? But if you suffer for doing good and you endure it, this is commendable before God.",
    Ind:"Sebab dapatkah disebut pujian, jika kamu menderita pukulan karena kamu berbuat dosa? Tetapi jika kamu berbuat baik dan karena itu kamu harus menderita, maka itu adalah kasih karunia pada Allah."
  },
  {Bible:"1Peter", Chapter:2, Verse:21, Page:1,
    Kor:"○바로 이것을 위하여 여러분은 부르심을 받았습니다.  그리스도께서는 여러분을 위하여 고난을 당하심으로써 여러분이 자기의 발자취를 따르게 하시려고 여러분에게 본을 남겨 놓으셨습니다.",
    Chn:"你们蒙召原是为此；因基督也为你们受过苦，给你们留下榜样，叫你们跟随他的脚踪行。",
    Eng:"To this you were called, because Christ suffered for you, leaving you an example, that you should follow in his steps.",
    Ind:"Sebab untuk itulah kamu dipanggil, karena Kristuspun telah menderita untuk kamu dan telah meninggalkan teladan bagimu, supaya kamu mengikuti jejak-Nya."
  },
  {Bible:"1Peter", Chapter:2, Verse:22, Page:1,
    Kor:"e그는 죄를 지으신 일이 없고 그의 입에서는 아무런 거짓도 찾아볼 수 없었습니다. (e 사 53:9)",
    Chn:"他并没有犯罪，口里也没有诡诈。",
    Eng:"\"He committed no sin, and no deceit was found in his mouth.\"",
    Ind:"Ia tidak berbuat dosa, dan tipu tidak ada dalam mulut-Nya."
  },
  {Bible:"1Peter", Chapter:2, Verse:23, Page:1,
    Kor:"그는 모욕을 당하셨으나 모욕으로 갚지 않으시고, 고난을 당하셨으나 위협하지 않으시고, 정의롭게 심판하시는 이에게 다 맡기셨습니다.",
    Chn:"他被骂不还口；受害不说威吓的话，只将自己交托那按公义审判人的主。",
    Eng:"When they hurled their insults at him, he did not retaliate; when he suffered, he made no threats. Instead, he entrusted himself to him who judges justly.",
    Ind:"Ketika Ia dicaci maki, Ia tidak membalas dengan mencaci maki; ketika Ia menderita, Ia tidak mengancam, tetapi Ia menyerahkannya kepada Dia, yang menghakimi dengan adil."
  },
  {Bible:"1Peter", Chapter:2, Verse:24, Page:1,
    Kor:"그는 우리 죄를 자기의 몸에 몸소 지시고서, 나무에 달리셨습니다. 그것은, 우리가 죄에는 죽고 의에는 살게 하시려는 것이었습니다. 그가 매를 맞아 상함으로 여러분이 나음을 얻었습니다.",
    Chn:"他被挂在木头上，亲身担当了我们的罪，使我们既然在罪上死，就得以在义上活。因他受的鞭伤，你们便得了医治。",
    Eng:"He himself bore our sins in his body on the tree, so that we might die to sins and live for righteousness; by his wounds you have been healed.",
    Ind:"Ia sendiri telah memikul dosa kita di dalam tubuh-Nya di kayu salib, supaya kita, yang telah mati terhadap dosa, hidup untuk kebenaran. Oleh bilur-bilur-Nya kamu telah sembuh."
  },
  {Bible:"1Peter", Chapter:2, Verse:25, Page:1,
    Kor:"전에는 여러분은 길 잃은 양과 같았으나, 이제는 여러분의 영혼의 목자이며 감독이신 그에게로 돌아왔습니다.",
    Chn:"你们从前好像迷路的羊，如今却归到你们灵魂的牧人监督了。",
    Eng:"For you were like sheep going astray, but now you have returned to the Shepherd and Overseer of your souls.",
    Ind:"Sebab dahulu kamu sesat seperti domba, tetapi sekarang kamu telah kembali kepada gembala dan pemelihara jiwamu."
  },
]);
