// 사무엘하 6장 · 2Samuel 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Samuel",6,23);
BibleDB.add([
  {Bible:"2Samuel", Chapter:6, Verse:1, Page:1, Kor:"<하나님의 궤를 예루살렘으로 옮기다(대상 13:1-14; 15:25-16:6, 43)> 다윗이 다시 이스라엘에서 정병 삼만 명을 징집하여서,", Chn:"", Eng:"David again brought together out of Israel chosen men, thirty thousand in all.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:2, Page:1, Kor:"그들을 모두 이끌고 유다의 바알라로 올라갔다. 거기에서 하나님의 궤를 옮겨 올 생각이었다. 그 궤는 그룹들 위에 앉아 계신 만군의 주님의 이름으로 부르는 궤였다.", Chn:"", Eng:"He and all his men set out from Baalah of Judah to bring up from there the ark of God, which is called by the Name, the name of the LORD Almighty, who is enthroned between the cherubim that are on the ark.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:3, Page:1, Kor:"그들이 언덕 위에 있는 아비나답의 집에서 하나님의 궤를 꺼내서, 새 수레에 싣고 나올 때에, 아비나답의 두 아들 웃사와 아히요가 그 새 수레를 몰았다.", Chn:"", Eng:"They set the ark of God on a new cart and brought it from the house of Abinadab, which was on the hill. Uzzah and Ahio, sons of Abinadab, were guiding the new cart", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:4, Page:1, Kor:"그들이 산에 있는 아비나답의 집에서 하나님의 궤를 싣고 나올 때에, 아히요는 궤 앞에서 걸었고,", Chn:"", Eng:"with the ark of God on it, and Ahio was walking in front of it.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:5, Page:1, Kor:"다윗과 이스라엘의 모든 가문은, 온 힘을 다하여서, 잣나무로 만든 온갖 악기와 수금과 거문고를 타며, 소구와 꽹과리와 심벌즈를 치면서, 주님 앞에서 기뻐하였다.", Chn:"", Eng:"David and the whole house of Israel were celebrating with all their might before the LORD, with songs and with harps, lyres, tambourines, sistrums and cymbals.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:6, Page:1, Kor:"○그들이 나곤의 타작 마당에 이르렀을 때에, 소들이 뛰어서 궤가 떨어지려고 하였으므로, 웃사가 손을 내밀어 하나님의 궤를 꼭 붙들었는데,", Chn:"", Eng:"When they came to the threshing floor of Nacon, Uzzah reached out and took hold of the ark of God, because the oxen stumbled.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:7, Page:1, Kor:"주 하나님이 웃사에게 진노하셔서 거기에서 그를 치시니, 그가 거기 하나님의 궤 곁에서 죽었다.", Chn:"", Eng:"The LORD'S anger burned against Uzzah because of his irreverent act; therefore God struck him down and he died there beside the ark of God.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:8, Page:1, Kor:"주님께서 그렇게 급격히 웃사를 벌하셨으므로, 다윗이 화를 내었다. 그래서 그 곳 이름을 오늘날까지 a베레스 웃사라고 한다.(a '웃사를 침')", Chn:"", Eng:"Then David was angry because the LORD'S wrath had broken out against Uzzah, and to this day that place is called Perez Uzzah.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:9, Page:1, Kor:"○그 날 다윗은 이 일 때문에 주님이 무서워서 \"이래서야 내가 어떻게 주님의 궤를 내가 있는 곳으로 옮길 수 있겠는가?\" 하였다.", Chn:"", Eng:"David was afraid of the LORD that day and said, \"How can the ark of the LORD ever come to me?\"", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:10, Page:1, Kor:"그래서 다윗은 주님의 궤를 '다윗 성'으로 옮기지 않고, 가드 사람 오벳에돔의 집으로 실어 가게 하였다.", Chn:"", Eng:"He was not willing to take the ark of the LORD to be with him in the City of David. Instead, he took it aside to the house of Obed-Edom the Gittite.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:11, Page:1, Kor:"그래서 주님의 궤가 가드 사람 오벳에돔의 집에서 석 달 동안 머물렀는데, 그 때에 주님께서 오벳에돔과 그의 온 집안에 복을 내려 주셨다.", Chn:"", Eng:"The ark of the LORD remained in the house of Obed-Edom the Gittite for three months, and the LORD blessed him and his entire household.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:12, Page:1, Kor:"○누군가가, 오벳에돔의 집에 하나님의 궤를 보관하였기 때문에, 주님께서 오벳에돔의 집과 그에게 딸린 모든 것에 복을 내려 주셨다는 소식을, 다윗 왕에게 전하였다. 그리하여 다윗은 기쁜 마음으로 가서, 하나님의 궤를 오벳에돔의 집에서 '다윗 성'으로 가지고 올라왔다. 궤를 옮길 때에 그는 큰 축제를 벌였다.", Chn:"", Eng:"Now King David was told, \"The LORD has blessed the household of Obed-Edom and everything he has, because of the ark of God.\" So David went down and brought up the ark of God from the house of Obed-Edom to the City of David with rejoicing.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:13, Page:1, Kor:"다윗은, 주님의 궤를 멘 사람들이 여섯 걸음을 옮겼을 때에, 행렬을 멈추게 하고, 소와 살진 양을 제물로 잡아서 바쳤다.", Chn:"", Eng:"When those who were carrying the ark of the LORD had taken six steps, he sacrificed a bull and a fattened calf.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:14, Page:1, Kor:"그리고 다윗은 모시로 만든 에봇만을 걸치고, 주님 앞에서 온 힘을 다하여 힘차게 춤을 추었다.", Chn:"", Eng:"David, wearing a linen ephod, danced before the LORD with all his might,", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:15, Page:1, Kor:"다윗과 온 이스라엘 가문은 환호성을 올리고, 나팔 소리가 우렁찬 가운데, 주님의 궤를 옮겨 왔다.", Chn:"", Eng:"while he and the entire house of Israel brought up the ark of the LORD with shouts and the sound of trumpets.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:16, Page:1, Kor:"○주님의 궤가 '다윗 성'으로 들어올 때에, 사울의 딸 미갈이 창 밖을 내다보다가, 다윗 왕이 주님 앞에서 뛰면서 춤을 추는 것을 보고, 마음 속으로 그를 업신여겼다.", Chn:"", Eng:"As the ark of the LORD was entering the City of David, Michal daughter of Saul watched from a window. And when she saw King David leaping and dancing before the LORD, she despised him in her heart.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:17, Page:1, Kor:"그들이 주님의 궤를 들어다가, 다윗이 궤를 두려고 쳐 놓은 장막 안 제자리에 옮겨 놓았을 때에, 다윗이 주님 앞에 번제와 화목제를 드렸다.", Chn:"", Eng:"They brought the ark of the LORD and set it in its place inside the tent that David had pitched for it, and David sacrificed burnt offerings and fellowship offerings before the LORD.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:18, Page:1, Kor:"다윗은 번제와 화목제를 드리고 나서, 만군의 주님의 이름으로 백성에게 복을 빌어 주고,", Chn:"", Eng:"After he had finished sacrificing the burnt offerings and fellowship offerings, he blessed the people in the name of the LORD Almighty.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:19, Page:1, Kor:"그 곳에 모인 온 이스라엘 백성에게, 남녀를 가리지 않고, 각 사람에게, 빵 한 덩이와 고기 한 점과 건포도 과자 한 개씩을 나누어 주었다. 그런 다음에 온 백성이 각각 자기들의 집으로 돌아갔다.", Chn:"", Eng:"Then he gave a loaf of bread, a cake of dates and a cake of raisins to each person in the whole crowd of Israelites, both men and women. And all the people went to their homes.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:20, Page:1, Kor:"○다윗이 자기의 집안 식구들에게 복을 빌어 주려고 궁전으로 돌아가니, 사울의 딸 미갈이 다윗을 맞으러 나와서, 이렇게 말하였다. \"오늘 이스라엘의 임금님이, 건달패들이 맨살을 드러내고 춤을 추듯이, 신하들의 아내가 보는 앞에서 몸을 드러내며 춤을 추셨으니, 임금님의 체통이 어떻게 되었겠습니까?\"", Chn:"", Eng:"When David returned home to bless his household, Michal daughter of Saul came out to meet him and said, \"How the king of Israel has distinguished himself today, disrobing in the sight of the slave girls of his servants as any vulgar fellow would!\"", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:21, Page:1, Kor:"다윗이 미갈에게 대답하였다. \"그렇소. 내가 주님 앞에서 그렇게 춤을 추었소. 주님께서는, 그대의 아버지와 그의 온 집안이 있는데도, 그들을 마다하시고, 나를 뽑으셔서, 주님의 백성 이스라엘을 다스리도록, 통치자로 세워 주셨소. 그러니 나는 주님을 찬양할 수밖에 없소. 나는 언제나 주님 앞에서 기뻐하며 뛸 것이오.", Chn:"", Eng:"David said to Michal, \"It was before the LORD, who chose me rather than your father or anyone from his house when he appointed me ruler over the LORD'S people Israel--I will celebrate before the LORD.", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:22, Page:1, Kor:"내가 스스로를 보아도 천한 사람처럼 보이지만, 주님을 찬양하는 일 때문이라면, 이보다 더 낮아지고 싶소. 그래도 그대가 말한 그 여자들은 나를 더욱더 존경할 것이오.\"", Chn:"", Eng:"I will become even more undignified than this, and I will be humiliated in my own eyes. But by these slave girls you spoke of, I will be held in honor.\"", Ind:""},
  {Bible:"2Samuel", Chapter:6, Verse:23, Page:1, Kor:"○이런 일 때문에 사울의 딸 미갈은 죽는 날까지 자식을 낳지 못하였다.", Chn:"", Eng:"And Michal daughter of Saul had no children to the day of her death.", Ind:""},
]);
