// 사무엘하 9장 · 2Samuel 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Samuel",9,13);
BibleDB.add([
  {Bible:"2Samuel", Chapter:9, Verse:1, Page:1, Kor:"<다윗과 므비보셋> 하루는 다윗이 물었다. \"사울의 집안에 살아 남은 사람이 있느냐? 요나단을 보아서라도, 남아 있는 자손이 있으면, 잘 보살펴 주고 싶구나.\"", Chn:"", Eng:"David asked, \"Is there anyone still left of the house of Saul to whom I can show kindness for Jonathan's sake?\"", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:2, Page:1, Kor:"마침 사울의 집안에서 종노릇 하는 시바라는 사람이 있어서, 사람들이 그를 불러 다윗에게로 데리고 왔다. 왕이 그에게 \"네가 시바냐?\" 하고 물으니 \"그러합니다\" 하고 그가 대답하였다.", Chn:"", Eng:"Now there was a servant of Saul's household named Ziba. They called him to appear before David, and the king said to him, \"Are you Ziba?\" \"Your servant,\" he replied.", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:3, Page:1, Kor:"왕이 물었다. \"사울의 집안에 남은 사람이 없느냐? 있으면 내가 하나님의 은총을 그에게 베풀어 주고 싶다.\" 그러자 시바가 왕에게 대답하였다. \"요나단의 아들이 하나 남아 있습니다. 두 다리를 접니다.\"", Chn:"", Eng:"The king asked, \"Is there no one still left of the house of Saul to whom I can show God's kindness?\" Ziba answered the king, \"There is still a son of Jonathan; he is crippled in both feet.\"", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:4, Page:1, Kor:"왕이 그에게 물었다. \"그는 지금 어디에 있느냐?\" 시바가 왕에게 대답하였다. \"그는 지금 로드발에 있는 암미엘의 아들 마길의 집에서 삽니다.\"", Chn:"", Eng:"\"Where is he?\" the king asked. Ziba answered, \"He is at the house of Makir son of Ammiel in Lo Debar.\"", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:5, Page:1, Kor:"○다윗 왕이 사람을 보내어서, 로드발에 있는 암미엘의 아들 마길의 집에서 그를 데려왔다.", Chn:"", Eng:"So King David had him brought from Lo Debar, from the house of Makir son of Ammiel.", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:6, Page:1, Kor:"사울의 손자이며 요나단의 아들인 므비보셋은 다윗에게 와서 엎드려 절하였다. 다윗이 \"네가 므비보셋이냐?\" 하고 물었다. 그가 대답하였다. \"예, 임금님의 종, 므비보셋입니다.\"", Chn:"", Eng:"When Mephibosheth son of Jonathan, the son of Saul, came to David, he bowed down to pay him honor. David said, \"Mephibosheth!\" \"Your servant,\" he replied.", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:7, Page:1, Kor:"다윗이 그에게 말하였다. \"겁낼 것 없다. 내가 너의 아버지 요나단을 생각해서 네게 은총을 베풀어 주고 싶다. 너의 할아버지 사울 임금께서 가지고 계시던 토지를 너에게 모두 돌려주겠다. 그리고 너는 언제나 나의 식탁에서 함께 먹도록 하여라.\"", Chn:"", Eng:"\"Don't be afraid,\" David said to him, \"for I will surely show you kindness for the sake of your father Jonathan. I will restore to you all the land that belonged to your grandfather Saul, and you will always eat at my table.\"", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:8, Page:1, Kor:"므비보셋이 엎드려 아뢰었다. \"이 종이 무엇이기에 죽은 개나 다름없는 저를 임금님께서 이렇게까지 돌보아 주십니까?\"", Chn:"", Eng:"Mephibosheth bowed down and said, \"What is your servant, that you should notice a dead dog like me?\"", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:9, Page:1, Kor:"○다윗 왕은 사울의 종 시바를 불러서 일렀다. \"사울과 그의 온 집안이 가졌던 모든 것을, 내가 이제 너의 상전의 손자인 므비보셋에게 주었다.", Chn:"", Eng:"Then the king summoned Ziba, Saul's servant, and said to him, \"I have given your master's grandson everything that belonged to Saul and his family.", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:10, Page:1, Kor:"그러니 너는 너의 아들들과 종들과 함께 모두 그 땅을 갈고 거두어서, 너의 상전의 집안이 먹을 양식을 대도록 하여라. 그러나 너의 상전의 손자인 므비보셋은 언제나 나의 식탁에서 음식을 먹을 것이다.\" (시바에게는 아들 열다섯과 종 스무 명이 있었다.)", Chn:"", Eng:"You and your sons and your servants are to farm the land for him and bring in the crops, so that your master's grandson may be provided for. And Mephibosheth, grandson of your master, will always eat at my table.\" (Now Ziba had fifteen sons and twenty servants.)", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:11, Page:1, Kor:"시바가 왕에게 대답하였다. \"높으신 임금님께서 이 종에게 명령하신 그대로, 이 종이 모두 하겠습니다.\" 그리하여 므비보셋은 왕자들과 다름없이, 언제나 다윗 왕의 식탁에서 음식을 먹었다.", Chn:"", Eng:"Then Ziba said to the king, \"Your servant will do whatever my lord the king commands his servant to do.\" So Mephibosheth ate at David's table like one of the king's sons.", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:12, Page:1, Kor:"므비보셋에게는 미가라는 어린 아들이 하나 있었다. 시바의 집에 사는 사람들은 모두 므비보셋의 종이 되었다.", Chn:"", Eng:"Mephibosheth had a young son named Mica, and all the members of Ziba's household were servants of Mephibosheth.", Ind:""},
  {Bible:"2Samuel", Chapter:9, Verse:13, Page:1, Kor:"므비보셋은 언제나 왕의 식탁에서 먹었으며, 예루살렘에서만 살았다. 그는 두 다리를 다 절었다.", Chn:"", Eng:"And Mephibosheth lived in Jerusalem, because he always ate at the king's table, and he was crippled in both feet.", Ind:""},
]);
