// 열왕기하 16장 · 2Kings 16
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Kings",16,20);
BibleDB.add([
  {Bible:"2Kings", Chapter:16, Verse:1, Page:1, Kor:"<유다 왕 아하스(대하 28:1-27)> 르말리야의 아들 베가 제 십칠년에 유다의 요담 왕의 아들 아하스가 왕이 되었다.", Chn:"", Eng:"In the seventeenth year of Pekah son of Remaliah, Ahaz son of Jotham king of Judah began to reign.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:2, Page:1, Kor:"아하스가 왕이 되었을 때에, 그의 나이는 스무 살이었다. 그는 예루살렘에서 열여섯 해 동안 다스렸다. 그러나 그는 주 하나님께서 보시기에 올바른 일을 하지 않았다. 그는 그의 조상 다윗이 한 대로 하지 않았다.", Chn:"", Eng:"Ahaz was twenty years old when he became king, and he reigned in Jerusalem sixteen years. Unlike David his father, he did not do what was right in the eyes of the LORD his God.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:3, Page:1, Kor:"오히려 그는 이스라엘의 왕들이 걸어간 길을 걸어갔고, 자기의 a아들을 불에 태워 제물로 바쳤다. 이것은, 주님께서 이스라엘 자손이 보는 앞에서 쫓아내신 이방 민족의 역겨운 풍속을 본받은 행위였다.(a 또는 '아들을 불로 지나가게 하였다')", Chn:"", Eng:"He walked in the ways of the kings of Israel and even sacrificed his son in the fire, following the detestable ways of the nations the LORD had driven out before the Israelites.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:4, Page:1, Kor:"그는 직접 산당과 언덕과 모든 푸른 나무 아래에서 제사를 지내고 분향하였다.", Chn:"", Eng:"He offered sacrifices and burned incense at the high places, on the hilltops and under every spreading tree.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:5, Page:1, Kor:"○그 때에 시리아의 르신 왕과 이스라엘의 르말리야의 아들 베가 왕이 예루살렘을 치려고 올라와서, 아하스를 포위하기는 하였으나, 정복하지는 못하였다.", Chn:"", Eng:"Then Rezin king of Aram and Pekah son of Remaliah king of Israel marched up to fight against Jerusalem and besieged Ahaz, but they could not overpower him.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:6, Page:1, Kor:"그 때에 시리아의 르신 왕이, 시리아에게 엘랏을 되찾아 주었고, 엘랏에서 유다 사람들을 몰아내었으므로, 시리아 사람들이 이 날까지 엘랏에 와서 살고 있다.", Chn:"", Eng:"At that time, Rezin king of Aram recovered Elath for Aram by driving out the men of Judah. Edomites then moved into Elath and have lived there to this day.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:7, Page:1, Kor:"아하스는 앗시리아의 디글랏빌레셀 왕에게 전령을 보내어, 이렇게 말하였다. \"나는 임금님의 신하이며 아들입니다. 올라오셔서, 나를 공격하고 있는 시리아 왕과 이스라엘 왕의 손에서, 나를 구원하여 주십시오.\"", Chn:"", Eng:"Ahaz sent messengers to say to Tiglath-Pileser king of Assyria, \"I am your servant and vassal. Come up and save me out of the hand of the king of Aram and of the king of Israel, who are attacking me.\"", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:8, Page:1, Kor:"그런 다음에 아하스는 주님의 성전과 왕궁의 보물 창고에 있는 금과 은을 모두 꺼내어, 앗시리아의 왕에게 선물로 보냈다.", Chn:"", Eng:"And Ahaz took the silver and gold found in the temple of the LORD and in the treasuries of the royal palace and sent it as a gift to the king of Assyria.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:9, Page:1, Kor:"앗시리아의 왕이 그의 요청을 듣고, 다마스쿠스로 진군하여 올라와서는 그 성을 함락시켰다. 그리고 그 주민을 길로 사로잡아 가고, 르신은 살해하였다.", Chn:"", Eng:"The king of Assyria complied by attacking Damascus and capturing it. He deported its inhabitants to Kir and put Rezin to death.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:10, Page:1, Kor:"○아하스 왕은 앗시리아의 디글랏빌레셀 왕을 만나려고 다마스쿠스로 갔다. 그는 그 곳 다마스쿠스에 있는 제단을 보고, 그 제단의 모형과 도본을 세밀하게 그려서, 우리야 제사장에게 보냈다.", Chn:"", Eng:"Then King Ahaz went to Damascus to meet Tiglath-Pileser king of Assyria. He saw an altar in Damascus and sent to Uriah the priest a sketch of the altar, with detailed plans for its construction.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:11, Page:1, Kor:"그래서 우리야 제사장은, 아하스 왕이 다마스쿠스로부터 보내 온 것을 따라서, 제단을 만들었다. 우리야 제사장은 아하스 왕이 다마스쿠스로부터 돌아오기 전에 제단 건축을 모두 완성하였다.", Chn:"", Eng:"So Uriah the priest built an altar in accordance with all the plans that King Ahaz had sent from Damascus and finished it before King Ahaz returned.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:12, Page:1, Kor:"왕은 다마스쿠스로부터 돌아와서, 그 제단을 보고 제단으로 나아가 그 위로 올라갔다.", Chn:"", Eng:"When the king came back from Damascus and saw the altar, he approached it and presented offerings on it.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:13, Page:1, Kor:"그리고 거기에서 그가 직접 번제물과 곡식제물을 드렸고, '부어 드리는 제물'을 따르기도 하였다. 또 제단 위에 화목제물의 피도 뿌렸다.", Chn:"", Eng:"He offered up his burnt offering and grain offering, poured out his drink offering, and sprinkled the blood of his fellowship offerings on the altar.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:14, Page:1, Kor:"그리고 그는 주님 앞에 놓여 있는 놋제단을 성전 앞에서 옮겼는데, 새 제단과 주님의 성전 사이에 있는 놋제단을 새 제단 북쪽에 갖다 놓았다.", Chn:"", Eng:"The bronze altar that stood before the LORD he brought from the front of the temple--from between the new altar and the temple of the LORD--and put it on the north side of the new altar.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:15, Page:1, Kor:"아하스 왕은 우리야 제사장에게 명령하였다. \"아침 번제물과 저녁 곡식예물, 왕의 번제물과 곡식예물, 또 이 땅의 모든 백성의 번제물과 곡식예물과 부어 드리는 예물을, 모두 이 큰 제단 위에서 드리도록 하고, 번제물과 희생제물의 모든 피를, 그 위에 뿌리시오. 그러나 그 놋제단은, 내가 주님께 여쭈어 볼 때에만 쓰겠소.\"", Chn:"", Eng:"King Ahaz then gave these orders to Uriah the priest: \"On the large new altar, offer the morning burnt offering and the evening grain offering, the king's burnt offering and his grain offering, and the burnt offering of all the people of the land, and their grain offering and their drink offering. Sprinkle on the altar all the blood of the burnt offerings and sacrifices. But I will use the bronze altar for seeking guidance.\"", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:16, Page:1, Kor:"우리야 제사장은 아하스 왕이 명령한 대로 이행하였다.", Chn:"", Eng:"And Uriah the priest did just as King Ahaz had ordered.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:17, Page:1, Kor:"○아하스 왕은 대야의 놋쇠 테두리를 떼어 버리고, 놋대야를 그 자리에서 옮기고, 또 놋쇠 소가 받치고 있는 놋쇠 바다를 뜯어 내어 돌받침 위에 놓았다.", Chn:"", Eng:"King Ahaz took away the side panels and removed the basins from the movable stands. He removed the Sea from the bronze bulls that supported it and set it on a stone base.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:18, Page:1, Kor:"또 그는 앗시리아 왕에게 경의를 표하려고, 주님의 성전 안에 만들어 둔 왕의 안식일 전용 통로와 주님의 성전 바깥에 만든 전용 출입구를 모두 없애 버렸다.", Chn:"", Eng:"He took away the Sabbath canopy that had been built at the temple and removed the royal entryway outside the temple of the LORD, in deference to the king of Assyria.", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:19, Page:1, Kor:"○아하스가 행한 나머지 모든 일은 '유다 왕 역대지략'에 기록되어 있다.", Chn:"", Eng:"As for the other events of the reign of Ahaz, and what he did, are they not written in the book of the annals of the kings of Judah?", Ind:""},
  {Bible:"2Kings", Chapter:16, Verse:20, Page:1, Kor:"아하스가 죽어 잠드니, 그를 그의 조상과 함께 '다윗 성'에 장사하였고, 그의 아들 히스기야가 그의 뒤를 이어 왕이 되었다.", Chn:"", Eng:"Ahaz rested with his fathers and was buried with them in the City of David. And Hezekiah his son succeeded him as king.", Ind:""},
]);
