// 열왕기하 12장 · 2Kings 12
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Kings",12,21);
BibleDB.add([
  {Bible:"2Kings", Chapter:12, Verse:1, Page:1, Kor:"<유다 왕 요아스(대하 24:1-16)> 예후 제 칠년에 요아스가 왕이 되어, 마흔 해 동안을 예루살렘에서 다스렸다. 그의 어머니 시비아는 브엘세바 사람이었다.", Chn:"", Eng:"In the seventh year of Jehu, Joash became king, and he reigned in Jerusalem forty years. His mother's name was Zibiah; she was from Beersheba.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:2, Page:1, Kor:"요아스는 여호야다 제사장이 가르쳐 준 대로 하였으므로, 일생 동안 주님께서 보시기에 올바른 일을 하였다.", Chn:"", Eng:"Joash did what was right in the eyes of the LORD all the years Jehoiada the priest instructed him.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:3, Page:1, Kor:"다만 산당을 제거하지 않아서, 백성이 여전히 산당에서 제사를 지내고 향을 피웠다.", Chn:"", Eng:"The high places, however, were not removed; the people continued to offer sacrifices and burn incense there.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:4, Page:1, Kor:"○요아스가 제사장들에게 말하였다. \"주님의 성전에 들어오는 모든 헌금, 곧 일반 헌금과 의무적으로 부과된 헌금과 자원하여 주님의 성전에 가져 오는 헌금을 모두,", Chn:"", Eng:"Joash said to the priests, \"Collect all the money that is brought as sacred offerings to the temple of the LORD--the money collected in the census, the money received from personal vows and the money brought voluntarily to the temple.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:5, Page:1, Kor:"제사장들이 각 담당 회계로부터 받아서, 성전에 수리할 곳이 발견되는 대로 그 수리할 곳을 모두 고치도록 하십시오.\"", Chn:"", Eng:"Let every priest receive the money from one of the treasurers, and let it be used to repair whatever damage is found in the temple.\"", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:6, Page:1, Kor:"○그러나 요아스가 왕이 된 지 스물세 해가 지나도록, 제사장들은 그 성전의 수리할 곳을 고치지 않았다.", Chn:"", Eng:"But by the twenty-third year of King Joash the priests still had not repaired the temple.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:7, Page:1, Kor:"요아스 왕이 여호야다 제사장과 다른 제사장들을 모두 불러서, 그들에게 말하였다. \"어찌하여 아직 성전의 수리할 곳을 고치지 않고 있습니까? 이제는 더 이상 담당 회계로부터 돈을 받아 두지 말고, 성전을 수리하는 데 쓰도록 직접 넘기게 하십시오.\"", Chn:"", Eng:"Therefore King Joash summoned Jehoiada the priest and the other priests and asked them, \"Why aren't you repairing the damage done to the temple? Take no more money from your treasurers, but hand it over for repairing the temple.\"", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:8, Page:1, Kor:"제사장들은 이 일에 동의하여, 제사장들이 백성으로부터 돈을 받거나 성전을 직접 수리하거나 하는 일을 하지 않기로 하였다.", Chn:"", Eng:"The priests agreed that they would not collect any more money from the people and that they would not repair the temple themselves.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:9, Page:1, Kor:"○제사장 여호야다는 궤를 하나 가져다가, 그 뚜껑에 구멍을 뚫어 주님의 성전으로 들여와서, 오른쪽 곧 제단 곁에 그것을 놓았다. 그래서 문을 지키는 제사장들이, 주님의 성전으로 가져 오는 모든 헌금을 그 궤에 넣게 하였다.", Chn:"", Eng:"Jehoiada the priest took a chest and bored a hole in its lid. He placed it beside the altar, on the right side as one enters the temple of the LORD. The priests who guarded the entrance put into the chest all the money that was brought to the temple of the LORD.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:10, Page:1, Kor:"그 궤가 헌금으로 가득 찰 때마다, 왕실 서기관과 대제사장이 와서 주님의 성전에 헌납된 헌금을 쏟아 내어 계산하였다.", Chn:"", Eng:"Whenever they saw that there was a large amount of money in the chest, the royal secretary and the high priest came, counted the money that had been brought into the temple of the LORD and put it into bags.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:11, Page:1, Kor:"계산이 끝나면, 그 헌금은 주님의 성전 공사를 맡은 감독관들에게 전달되었고, 그것은 다시 주님의 성전을 수리하는 목수들과 건축자들에게 지불되었고,", Chn:"", Eng:"When the amount had been determined, they gave the money to the men appointed to supervise the work on the temple. With it they paid those who worked on the temple of the LORD--the carpenters and builders,", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:12, Page:1, Kor:"또 미장이와 석수에게도 지불되었으며, 주님의 성전을 수리하는 데 드는 나무와 돌을 사는 데와, 그 밖에 성전을 수리하는 데 필요한 경비로 쓰였다.", Chn:"", Eng:"the masons and stonecutters. They purchased timber and dressed stone for the repair of the temple of the LORD, and met all the other expenses of restoring the temple.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:13, Page:1, Kor:"주님의 성전에 헌납된 그 헌금은 주님의 성전에서 쓸 은대접들과 부집게와 대접들과 나팔 등의 금그릇이나 은그릇을 만드는 데 쓰이지는 않았다.", Chn:"", Eng:"The money brought into the temple was not spent for making silver basins, wick trimmers, sprinkling bowls, trumpets or any other articles of gold or silver for the temple of the LORD;", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:14, Page:1, Kor:"그 헌금은 오직 일꾼들에게 주어, 그것으로 주님의 성전을 수리하는 데만 사용하였다.", Chn:"", Eng:"it was paid to the workmen, who used it to repair the temple.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:15, Page:1, Kor:"또 돈을 받아 일꾼들에게 주는 감독관들에 대한 회계 감사를 하지 않았는데, 그것은 그들이 성실하게 일하고 있었기 때문이다.", Chn:"", Eng:"They did not require an accounting from those to whom they gave the money to pay the workers, because they acted with complete honesty.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:16, Page:1, Kor:"그리고 속건제와 속죄제에 바친 돈은, 주님의 성전의 수입으로 계산하지 않았다. 그것은 제사장들의 몫이었기 때문이다.", Chn:"", Eng:"The money from the guilt offerings and sin offerings was not brought into the temple of the LORD; it belonged to the priests.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:17, Page:1, Kor:"○그 무렵에 시리아 왕 하사엘이 가드를 공격하여 함락시켰다. 그런 다음에 하사엘은 또 예루살렘도 치려고 하였기 때문에,", Chn:"", Eng:"About this time Hazael king of Aram went up and attacked Gath and captured it. Then he turned to attack Jerusalem.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:18, Page:1, Kor:"유다 왕 요아스는, 앞서 유다를 다스린 여호사밧과 여호람과 아하시야가 주님께 바친 모든 물건과, 또 자신이 주님께 바친 것들을 비롯하여, 주님의 성전과 왕실 창고에 있는 모든 금을, 시리아 왕 하사엘에게 보냈다. 그러자 하사엘은 예루살렘을 치지 않고 물러갔다.", Chn:"", Eng:"But Joash king of Judah took all the sacred objects dedicated by his fathers--Jehoshaphat, Jehoram and Ahaziah, the kings of Judah--and the gifts he himself had dedicated and all the gold found in the treasuries of the temple of the LORD and of the royal palace, and he sent them to Hazael king of Aram, who then withdrew from Jerusalem.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:19, Page:1, Kor:"○요아스의 나머지 행적과 그가 한 모든 일은 '유다 왕 역대지략'에 기록되어 있다.", Chn:"", Eng:"As for the other events of the reign of Joash, and all he did, are they not written in the book of the annals of the kings of Judah?", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:20, Page:1, Kor:"○요아스의 신하들이 역모를 꾸며, 실라로 내려가는 길에 있는 밀로의 궁에서 요아스를 살해하였다.", Chn:"", Eng:"His officials conspired against him and assassinated him at Beth Millo, on the road down to Silla.", Ind:""},
  {Bible:"2Kings", Chapter:12, Verse:21, Page:1, Kor:"그를 살해한 신하는 시므앗의 아들 요사갈과 소멜의 아들 여호사바드였다. 그가 죽으니, 그의 조상들과 함께 '다윗 성'에 장사하였다. 그의 아들 아마샤가 그의 뒤를 이어 왕이 되었다.", Chn:"", Eng:"The officials who murdered him were Jozabad son of Shimeath and Jehozabad son of Shomer. He died and was buried with his fathers in the City of David. And Amaziah his son succeeded him as king.", Ind:""},
]);
