// 열왕기하 22장 · 2Kings 22
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Kings",22,20);
BibleDB.add([
  {Bible:"2Kings", Chapter:22, Verse:1, Page:1, Kor:"<유다 왕 요시야(대하 34:1-2)> 요시야는 왕이 되었을 때에 여덟 살이었다. 그는 예루살렘에서 서른한 해 동안 다스렸다. 그의 어머니 여디다는 보스갓 출신 아다야의 딸이다.", Chn:"", Eng:"Josiah was eight years old when he became king, and he reigned in Jerusalem thirty-one years. His mother's name was Jedidah daughter of Adaiah; she was from Bozkath.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:2, Page:1, Kor:"요시야는 주님께서 보시기에 올바른 일을 하였고, 그의 조상 다윗의 모든 길을 본받아, 곁길로 빠지지 않았다.", Chn:"", Eng:"He did what was right in the eyes of the LORD and walked in all the ways of his father David, not turning aside to the right or to the left.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:3, Page:1, Kor:"<율법책을 발견하다(대하 34:8-28)> ○요시야 왕 제 십팔년에 왕은, 아샬랴의 아들이요 므술람의 손자인 사반 서기관을, 주님의 성전으로 보내며 지시하였다.", Chn:"", Eng:"In the eighteenth year of his reign, King Josiah sent the secretary, Shaphan son of Azaliah, the son of Meshullam, to the temple of the LORD. He said:", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:4, Page:1, Kor:"\"힐기야 대제사장에게 올라가서, 백성이 주님의 성전에 바친 헌금, 곧 성전 문지기들이 백성으로부터 모은 돈을 모두 계산하도록 하고,", Chn:"", Eng:"\"Go up to Hilkiah the high priest and have him get ready the money that has been brought into the temple of the LORD, which the doorkeepers have collected from the people.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:5, Page:1, Kor:"그 돈을 주님의 성전 공사 감독관들에게 맡겨, 일하는 인부들에게 품삯으로 주어 주님의 성전에 파손된 곳을 수리하게 하시오.", Chn:"", Eng:"Have them entrust it to the men appointed to supervise the work on the temple. And have these men pay the workers who repair the temple of the LORD--", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:6, Page:1, Kor:"목수와 돌 쌓는 사람과 미장이에게 품삯을 주고, 또 성전 수리에 필요한 목재와 석재도 구입하게 하시오.", Chn:"", Eng:"the carpenters, the builders and the masons. Also have them purchase timber and dressed stone to repair the temple.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:7, Page:1, Kor:"그들은 모두 정직하게 일하는 사람들이니, 일단 돈을 넘겨 준 다음에는 그 돈을 계산하지 않도록 하시오.\"", Chn:"", Eng:"But they need not account for the money entrusted to them, because they are acting faithfully.\"", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:8, Page:1, Kor:"○힐기야 대제사장이 사반 서기관에게, 주님의 성전에서 율법책을 발견하였다고 하면서, 그 책을 사반에게 넘겨 주었으므로, 사반이 그 책을 읽어 보았다.", Chn:"", Eng:"Hilkiah the high priest said to Shaphan the secretary, \"I have found the Book of the Law in the temple of the LORD.\" He gave it to Shaphan, who read it.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:9, Page:1, Kor:"사반 서기관은 그 책을 읽어 본 다음에, 왕에게 가서 \"임금님의 신하들이 성전에 모아 둔 돈을 쏟아 내어, 작업 감독관, 곧 주님의 성전 수리를 맡은 감독들에게 넘겨 주었습니다\" 하고 보고하였다.", Chn:"", Eng:"Then Shaphan the secretary went to the king and reported to him: \"Your officials have paid out the money that was in the temple of the LORD and have entrusted it to the workers and supervisors at the temple.\"", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:10, Page:1, Kor:"사반 서기관은 왕에게, 힐기야 대제사장이 자기에게 책 한 권을 건네 주었다고 보고한 다음에, 그 책을 왕 앞에서 큰소리로 읽었다.", Chn:"", Eng:"Then Shaphan the secretary informed the king, \"Hilkiah the priest has given me a book.\" And Shaphan read from it in the presence of the king.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:11, Page:1, Kor:"왕이 그 율법책의 말씀을 듣고는, 애통해 하며 자기의 옷을 찢었다.", Chn:"", Eng:"When the king heard the words of the Book of the Law, he tore his robes.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:12, Page:1, Kor:"왕은 힐기야 대제사장과 사반의 아들 아히감과 미가야의 아들 악볼과 사반 서기관과 왕의 시종 아사야에게 명령하였다.", Chn:"", Eng:"He gave these orders to Hilkiah the priest, Ahikam son of Shaphan, Acbor son of Micaiah, Shaphan the secretary and Asaiah the king's attendant:", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:13, Page:1, Kor:"\"그대들은 주님께로 나아가서, 나를 대신하여, 그리고 이 백성과 온 유다를 대신하여, 이번에 발견된 이 두루마리의 말씀에 관하여 주님의 뜻을 여쭈어 보도록 하시오. 우리의 조상이 이 책의 말씀에 복종하지 아니하고, 우리들이 지키도록 규정된 이 기록대로 하지 않았으므로, 우리에게 내리신 주님의 진노가 크오.\"", Chn:"", Eng:"\"Go and inquire of the LORD for me and for the people and for all Judah about what is written in this book that has been found. Great is the LORD'S anger that burns against us because our fathers have not obeyed the words of this book; they have not acted in accordance with all that is written there concerning us.\"", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:14, Page:1, Kor:"○그리하여 힐기야 제사장과 아히감과 악볼과 사반과 아사야가 살룸의 아내 훌다 예언자에게 갔다. 살룸은 할하스의 손자요 디과의 아들로서, 궁중 예복을 관리하는 사람이었다. 훌다는 예루살렘의 제 이 구역에서 살고 있었는데, 그들이 그에게 가서 왕의 말을 전하였다.", Chn:"", Eng:"Hilkiah the priest, Ahikam, Acbor, Shaphan and Asaiah went to speak to the prophetess Huldah, who was the wife of Shallum son of Tikvah, the son of Harhas, keeper of the wardrobe. She lived in Jerusalem, in the Second District.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:15, Page:1, Kor:"그러자 훌다가 그들에게 말하였다. \"주 이스라엘의 하나님께서 이렇게 말씀하시니, 그대들을 나에게 보낸 그에게 가서 전하시오.", Chn:"", Eng:"She said to them, \"This is what the LORD, the God of Israel, says: Tell the man who sent you to me,", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:16, Page:1, Kor:"'나 주가 말한다. 유다 왕이 읽은 책에 있는 모든 말대로, 내가 이 곳과 여기에 사는 주민에게 재앙을 내리겠다.", Chn:"", Eng:"'This is what the LORD says: I am going to bring disaster on this place and its people, according to everything written in the book the king of Judah has read.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:17, Page:1, Kor:"그들이 나를 버리고 다른 신들에게 분향하고, a그들이 한 모든 일이 나의 분노를 격발하였기 때문이다. 그러므로 나의 분노를 이 곳에 쏟을 것이니, 아무도 끄지 못할 것이다.'(a 또는 '그들이 만든 우상으로')", Chn:"", Eng:"Because they have forsaken me and burned incense to other gods and provoked me to anger by all the idols their hands have made, my anger will burn against this place and will not be quenched.'", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:18, Page:1, Kor:"주님의 뜻을 주님께 여쭈어 보라고 그대들을 나에게로 보낸 유다 왕에게 또 이 말도 전하시오. '나 주 이스라엘의 하나님이 말한다. 네가 들은 말을 설명하겠다.", Chn:"", Eng:"Tell the king of Judah, who sent you to inquire of the LORD, 'This is what the LORD, the God of Israel, says concerning the words you heard:", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:19, Page:1, Kor:"이 곳이 황폐해지고 이 곳의 주민이 저주를 받을 것이라는 나의 말을 들었을 때에, 너는 깊이 뉘우치고, 나 주 앞에 겸손하게 무릎을 꿇고, 옷을 찢고, 내 앞에서 통곡하였다. 그러므로 내가 네 기도를 들어 준다. 나 주가 말한다.", Chn:"", Eng:"Because your heart was responsive and you humbled yourself before the LORD when you heard what I have spoken against this place and its people, that they would become accursed and laid waste, and because you tore your robes and wept in my presence, I have heard you, declares the LORD.", Ind:""},
  {Bible:"2Kings", Chapter:22, Verse:20, Page:1, Kor:"그러므로 내가 이 곳에 내리기로 한 모든 재앙을, 네가 죽을 때까지는 내리지 않겠다. 내가 너를 네 조상에게로 보낼 때에는, 네가 평안히 무덤에 안장되게 하겠다.'\" ○그들이 돌아와서, 이 말을 왕에게 전하였다.", Chn:"", Eng:"Therefore I will gather you to your fathers, and you will be buried in peace. Your eyes will not see all the disaster I am going to bring on this place.'\" So they took her answer back to the king.", Ind:""},
]);
