// 이사야 23장 · Isaiah 23
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Isaiah",23,18);
BibleDB.add([
  {Bible:"Isaiah", Chapter:23, Verse:1, Page:1, Kor:"<베니게에 대한 경고> 이것은 두로를 두고 하신 엄한 경고의 말씀이다.  다시스의 배들아, 너희는 슬피 울어라. 두로가 파멸되었으니, 들어갈 집도 없고, 닻을 내릴 항구도 없다. a키프로스에서 너희가 이 소식을 들었다. (a 히, '깃딤')", Chn:"", Eng:"An oracle concerning Tyre: Wail, O ships of Tarshish! For Tyre is destroyed and left without house or harbor. From the land of Cyprus word has come to them.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:2, Page:1, Kor:"항해자들이 부유하게 만들어 준 너희 섬 백성들아, 시돈의 상인들아, 잠잠하여라!", Chn:"", Eng:"Be silent, you people of the island and you merchants of Sidon, whom the seafarers have enriched.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:3, Page:1, Kor:"시홀의 곡식 곧 나일의 수확을 배로 실어 들였으니, 두로는 곧 뭇 나라의 시장이 되었다.", Chn:"", Eng:"On the great waters came the grain of the Shihor; the harvest of the Nile was the revenue of Tyre, and she became the marketplace of the nations.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:4, Page:1, Kor:"그러나 너 시돈아, 너 바다의 요새야, 네가 수치를 당하였다. 너의 어머니인 바다가 너를 버리고 이렇게 말한다. \"나는 산고를 겪지도 않았고, 아이를 낳지도 못하였다. 아들들을 기른 일도 없고, 딸들을 키운 일도 없다.\"", Chn:"", Eng:"Be ashamed, O Sidon, and you, O fortress of the sea, for the sea has spoken: \"I have neither been in labor nor given birth; I have neither reared sons nor brought up daughters.\"", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:5, Page:1, Kor:"두로가 파멸되었다는 소식이 이집트에 전해지면, 이집트마저도 충격을 받고 낙심할 것이다.", Chn:"", Eng:"When word comes to Egypt, they will be in anguish at the report from Tyre.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:6, Page:1, Kor:"베니게의 주민아, b스페인으로 건너가거라. 섬나라 백성아, 슬피 울어라. (b 히, '다시스')", Chn:"", Eng:"Cross over to Tarshish; wail, you people of the island.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:7, Page:1, Kor:"이것이 너희가 그렇게 좋아하던 도성 두로냐? 그토록 오랜 역사를 가지고 저 먼 곳에까지 가서 식민지를 세우던 도성이냐?", Chn:"", Eng:"Is this your city of revelry, the old, old city, whose feet have taken her to settle in far-off lands?", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:8, Page:1, Kor:"빛나는 왕관을 쓰고 있던 두로, 그 상인들은 귀족들이요, 그 무역상들은 세상이 우러러보던 사람들이었는데, 두로를 두고 누가 이런 일을 계획하였겠느냐?", Chn:"", Eng:"Who planned this against Tyre, the bestower of crowns, whose merchants are princes, whose traders are renowned in the earth?", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:9, Page:1, Kor:"그 일을 계획하신 분은 만군의 주님이시다. 온갖 영화를 누리며 으스대던 교만한 자들을 비천하게 만드시고, 이 세상에서 유명하다는 자들을 보잘 것 없이 만드시려고, 이런 계획을 세우셨다.", Chn:"", Eng:"The LORD Almighty planned it, to bring low the pride of all glory and to humble all who are renowned on the earth.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:10, Page:1, Kor:"b스페인의 c딸아, d너의 땅으로 돌아가서 땅이나 갈아라. 이제 너에게는 항구가 없다. (b 히, '다시스' c 또는 '주민아' d 사해 사본과 칠십인역 사본들을 따름. 마소라 본문에는 '다시스의 딸아, 나일 강처럼 땅 위에 넘쳐 흘러라. 너를 속박하던 것은 이미 없어졌다')", Chn:"", Eng:"Till your land as along the Nile, O Daughter of Tarshish, for you no longer have a harbor.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:11, Page:1, Kor:"주님께서 바다 위에 팔을 펴셔서, 왕국들을 뒤흔드시고, e베니게의 요새들을 허물라고 명하셨다. (e 히, '가나안')", Chn:"", Eng:"The LORD has stretched out his hand over the sea and made its kingdoms tremble. He has given an order concerning Phoenicia that her fortresses be destroyed.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:12, Page:1, Kor:"그래서 주님께서 이렇게 말씀하셨다. \"처녀, 딸 시돈아, 너는 망했다. 네가 다시는 우쭐대지 못할 것이다. 일어나서 a키프로스로 건너가 보아라. 그러나 거기에서도 네가 평안하지 못할 것이다.\" (a 히, '깃딤')", Chn:"", Eng:"He said, \"No more of your reveling, O Virgin Daughter of Sidon, now crushed! \"Up, cross over to Cyprus; even there you will find no rest.\"", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:13, Page:1, Kor:"f(바빌로니아 사람의 땅을 보아라. 백성이 없어졌다. 앗시리아 사람이 그 곳을 들짐승이 사는 곳으로 만들었다. 그들이 도성 바깥에 흙 언덕을 쌓고, 성을 공격하여, 궁전을 헐어 황폐하게 하였다.) (f 또는 '갈대아')", Chn:"", Eng:"Look at the land of the Babylonians, this people that is now of no account! The Assyrians have made it a place for desert creatures; they raised up their siege towers, they stripped its fortresses bare and turned it into a ruin.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:14, Page:1, Kor:"다시스의 배들아, 너희는 슬피 울어라. 너희의 요새가 파괴되었다.", Chn:"", Eng:"Wail, you ships of Tarshish; your fortress is destroyed!", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:15, Page:1, Kor:"그 날이 오면, 한 왕의 수명과 같은 칠십 년 동안 두로가 잊혀지겠으나, 칠십 년이 지난 뒤에는, 두로가 창녀의 노래에 나오는 주인공처럼 될 것이다.", Chn:"", Eng:"At that time Tyre will be forgotten for seventy years, the span of a king's life. But at the end of these seventy years, it will happen to Tyre as in the song of the prostitute:", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:16, Page:1, Kor:"망각 속으로 사라졌던 너 가련한 창녀야, 수금을 들고 성읍을 두루 다니며, 감미롭게 수금을 타고 노래나 실컷 불러라. 남자들마다 네 노랫소리를 듣고, 다시 너를 기억하여 모여들게 하여라.", Chn:"", Eng:"\"Take up a harp, walk through the city, O prostitute forgotten; play the harp well, sing many a song, so that you will be remembered.\"", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:17, Page:1, Kor:"칠십 년이 지나가면, 주님께서 두로를 돌보아 주셔서 옛날처럼 다시 해상무역을 하게 하실 것이다. 그 때에 두로는 다시 제 몸을 팔아서, 땅 위에 있는 세상의 모든 나라의 돈을 끌어들일 것이다.", Chn:"", Eng:"At the end of seventy years, the LORD will deal with Tyre. She will return to her hire as a prostitute and will ply her trade with all the kingdoms on the face of the earth.", Ind:""},
  {Bible:"Isaiah", Chapter:23, Verse:18, Page:1, Kor:"그러나 두로가 장사를 해서 벌어들인 소득은 주님의 몫이 될 것이다. 두로가 제 몫으로 간직하거나 쌓아 두지 못할 것이다. 주님을 섬기며 사는 사람들이, 두로가 벌어 놓은 것으로, 배불리 먹을 양식과 좋은 옷감을 살 것이다.", Chn:"", Eng:"Yet her profit and her earnings will be set apart for the LORD; they will not be stored up or hoarded. Her profits will go to those who live before the LORD, for abundant food and fine clothes.", Ind:""},
]);
