// 이사야 29장 · Isaiah 29
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Isaiah",29,24);
BibleDB.add([
  {Bible:"Isaiah", Chapter:29, Verse:1, Page:1, Kor:"<예루살렘의 운명> 너에게 재앙이 닥칠 것이다. a아리엘아, 아리엘아, 다윗이 진을 쳤던 성읍아, \"해마다 절기들은 돌아오련만,", Chn:"", Eng:"Woe to you, Ariel, Ariel, the city where David settled! Add year to year and let your cycle of festivals go on.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:2, Page:1, Kor:"내가 너 a아리엘을 포위하고 치겠다. b'나의 번제단'이라고 불리던 너를 칠 터이니, 네가 슬퍼하고 통곡할 것이다. (a '하나님의 암사자', 예루살렘을 가리킴 b 히, '아리엘(번제단)'. '하나님의 암사자'와 '번제단'이 히브리어로 발음이 같음)", Chn:"", Eng:"Yet I will besiege Ariel; she will mourn and lament, she will be to me like an altar hearth.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:3, Page:1, Kor:"내가 너의 사면을 둘러 진을 치며, 너를 삥 둘러서 탑들을 세우고, 흙더미를 쌓아 올려 너의 성을 치겠다.\"", Chn:"", Eng:"I will encamp against you all around; I will encircle you with towers and set up my siege works against you.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:4, Page:1, Kor:"그 때에 너는 낮아져서 땅바닥에서 말할 것이며, 너의 말소리는 네가 쓰러진 먼지바닥에서 나는 개미 소리와 같을 것이다. 너의 목소리는 땅에서 나는 유령의 소리와 같을 것이며, 너의 말은 먼지 바닥 속에서 나는 중얼거리는 소리와 같을 것이다.", Chn:"", Eng:"Brought low, you will speak from the ground; your speech will mumble out of the dust. Your voice will come ghostlike from the earth; out of the dust your speech will whisper.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:5, Page:1, Kor:"그러나 너를 친 원수의 무리는 가는 먼지처럼 되어 날아가며, 그 잔인한 무리는 겨처럼 흩날릴 것이다. 갑자기, 예기치 못한 순간에", Chn:"", Eng:"But your many enemies will become like fine dust, the ruthless hordes like blown chaff. Suddenly, in an instant,", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:6, Page:1, Kor:"만군의 주님께서 너를 찾아오시되, 우레와 지진과 큰 소리를 일으키시며, 회오리바람과 폭풍과 태워 버리는 불길로 찾아오실 것이다.", Chn:"", Eng:"the LORD Almighty will come with thunder and earthquake and great noise, with windstorm and tempest and flames of a devouring fire.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:7, Page:1, Kor:"a아리엘을 치는 모든 나라의 무리와 그의 요새들을 공격하여 그를 괴롭히는 자들 모두가, 마치 꿈을 꾸는 것처럼, 밤의 환상을 보는 것처럼, 헛수고를 할 것이다. (a '하나님의 암사자', 예루살렘을 가리킴)", Chn:"", Eng:"Then the hordes of all the nations that fight against Ariel, that attack her and her fortress and besiege her, will be as it is with a dream, with a vision in the night--", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:8, Page:1, Kor:"마치 굶주린 자가 꿈에 먹기는 하나, 깨어나면 더욱 허기를 느끼듯이, 목마른 자가 꿈에 마시기는 하나, 깨어나면 더욱 지쳐서 갈증을 느끼듯이, 시온 산을 치는 모든 나라의 무리가 그러할 것이다.", Chn:"", Eng:"as when a hungry man dreams that he is eating, but he awakens, and his hunger remains; as when a thirsty man dreams that he is drinking, but he awakens faint, with his thirst unquenched. So will it be with the hordes of all the nations that fight against Mount Zion.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:9, Page:1, Kor:"<무시된 경고> 너희는 놀라서, 기절할 것이다. 너희는 눈이 멀어서, 앞을 못 보는 사람이 될 것이다. 포도주 한 모금도 마시지 않았는데, 취할 것이다. 독한 술 한 방울도 마시지 않았는데, 비틀거릴 것이다.", Chn:"", Eng:"Be stunned and amazed, blind yourselves and be sightless; be drunk, but not from wine, stagger, but not from beer.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:10, Page:1, Kor:"주님께서는 너희에게 잠드는 영을 보내셔서, 너희를 깊은 잠에 빠지게 하셨다. 너희의 예언자로 너희의 눈 구실을 못하게 하셨으니, 너희의 눈을 멀게 하신 것이요, 너희의 선견자로 앞을 내다보지 못하게 하셨으니, 너희의 얼굴을 가려서 눈을 못 보게 하신 것이다.", Chn:"", Eng:"The LORD has brought over you a deep sleep: He has sealed your eyes (the prophets); he has covered your heads (the seers).", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:11, Page:1, Kor:"이 모든 묵시가 너희에게는 마치 밀봉된 두루마리의 글처럼 될 것이다. 너희가 그 두루마리를 유식한 사람에게 가지고 가서 \"이것을 좀 읽어 주시오\" 하고 내주면, 그는 \"두루마리가 밀봉되어 있어서 못 읽겠소\" 하고 말할 것이다.", Chn:"", Eng:"For you this whole vision is nothing but words sealed in a scroll. And if you give the scroll to someone who can read, and say to him, \"Read this, please,\" he will answer, \"I can't; it is sealed.\"", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:12, Page:1, Kor:"너희가 그 두루마리를 무식한 사람에게 가지고 가서 \"이것을 좀 읽어 주시오\" 하면, 그는 \"나는 글을 읽을 줄 모릅니다\" 하고 말할 것이다.", Chn:"", Eng:"Or if you give the scroll to someone who cannot read, and say, \"Read this, please,\" he will answer, \"I don't know how to read.\"", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:13, Page:1, Kor:"주님께서 말씀하신다. \"이 백성이 입으로는 나를 가까이하고, 입술로는 나를 영화롭게 하지만, 그 마음으로는 나를 멀리하고 있다. 그들이 나를 경외한다는 말은, 다만, 들은 말을 흉내내는 것일 뿐이다.", Chn:"", Eng:"The Lord says: \"These people come near to me with their mouth and honor me with their lips, but their hearts are far from me. Their worship of me is made up only of rules taught by men.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:14, Page:1, Kor:"그러므로 내가 다시 한 번 놀랍고 기이한 일로 이 백성을 놀라게 할 것이다.\" 지혜로운 사람들에게서 지혜가 없어지고, 총명한 사람들에게서 총명이 사라질 것이다.", Chn:"", Eng:"Therefore once more I will astound these people with wonder upon wonder; the wisdom of the wise will perish, the intelligence of the intelligent will vanish.\"", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:15, Page:1, Kor:"<장래에 대한 희망> 주님 몰래 음모를 깊이 숨기려는 자들에게 재앙이 닥칠 것이다. 그들은 어두운 곳에서 남 몰래 음모를 꾸미는 자들이다. \"누가 우리를 보랴! 누가 우리를 알랴!\" 한다.", Chn:"", Eng:"Woe to those who go to great depths to hide their plans from the LORD, who do their work in darkness and think, \"Who sees us? Who will know?\"", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:16, Page:1, Kor:"그들은 매사를 거꾸로 뒤집어 생각한다. 진흙으로 옹기를 만드는 사람과 옹기장이가 주무르는 진흙을 어찌 같이 생각할 수 있느냐? 만들어진 물건이 자기를 만든 사람을 두고 \"그가 나를 만들지 않았다\" 하고 말할 수 있느냐? 빚어진 것이 자기를 빚은 사람을 두고 \"그는 기술이 없어!\" 하고 말할 수 있느냐?", Chn:"", Eng:"You turn things upside down, as if the potter were thought to be like the clay! Shall what is formed say to him who formed it, \"He did not make me\"? Can the pot say of the potter, \"He knows nothing\"?", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:17, Page:1, Kor:"레바논의 밀림이 기름진 밭으로 변하고, 그 기름진 밭이 다시 밀림으로 변하는 것은, 시간 문제이다.", Chn:"", Eng:"In a very short time, will not Lebanon be turned into a fertile field and the fertile field seem like a forest?", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:18, Page:1, Kor:"그 날이 오면, 듣지 못하는 사람이 두루마리의 글을 읽는 소리를 듣고, 어둠과 흑암에 싸인 눈 먼 사람이 눈을 떠서 볼 것이다.", Chn:"", Eng:"In that day the deaf will hear the words of the scroll, and out of gloom and darkness the eyes of the blind will see.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:19, Page:1, Kor:"천한 사람들이 주님 안에서 더없이 기뻐하며 사람들 가운데 가난한 사람들이 이스라엘의 거룩하신 분 안에서 즐거워할 것이다.", Chn:"", Eng:"Once more the humble will rejoice in the LORD; the needy will rejoice in the Holy One of Israel.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:20, Page:1, Kor:"포악한 자는 사라질 것이다. 비웃는 사람은 자취를 감출 것이다. 죄 지을 기회를 엿보던 자들이 모두 끝장 날 것이다.", Chn:"", Eng:"The ruthless will vanish, the mockers will disappear, and all who have an eye for evil will be cut down--", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:21, Page:1, Kor:"그들은 말 한 마디로 사람에게 죄를 뒤집어씌우고, 성문에서 재판하는 사람을 올무에 걸리게 하며, 정당한 이유 없이 의로운 사람의 권리를 박탈하던 자들이다.", Chn:"", Eng:"those who with a word make a man out to be guilty, who ensnare the defender in court and with false testimony deprive the innocent of justice.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:22, Page:1, Kor:"그러므로 아브라함을 구속하신 주님께서, 곧 야곱 족속의 주 하나님께서 이렇게 말씀하신다. \"이제 야곱이 다시는 부끄러움을 당하지 않을 것이고, 이제 그의 얼굴이 다시는 수모 때문에 창백해지지는 않을 것이다.", Chn:"", Eng:"Therefore this is what the LORD, who redeemed Abraham, says to the house of Jacob: \"No longer will Jacob be ashamed; no longer will their faces grow pale.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:23, Page:1, Kor:"야곱이 자기의 자손 곧 그들 가운데서 내가 친히 만들어 준 그 자손을 볼 때, 그들은 내 이름을 거룩하게 할 것이다.\" '야곱의 거룩한 분'을 거룩하게 받들며, 이스라엘의 하나님을 경외할 것이다.", Chn:"", Eng:"When they see among them their children, the work of my hands, they will keep my name holy; they will acknowledge the holiness of the Holy One of Jacob, and will stand in awe of the God of Israel.", Ind:""},
  {Bible:"Isaiah", Chapter:29, Verse:24, Page:1, Kor:"그래서 마음이 혼미하던 사람이 총명해지고, 거스르던 사람이 교훈을 받을 것이다.", Chn:"", Eng:"Those who are wayward in spirit will gain understanding; those who complain will accept instruction.\"", Ind:""},
]);
