// 이사야 41장 · Isaiah 41
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Isaiah",41,29);
BibleDB.add([
  {Bible:"Isaiah", Chapter:41, Verse:1, Page:1,
    Kor:"<하나님께서 이스라엘에게 보증하시다> \"섬들아, 나의 앞에서 잠잠하여라. 백성들아, 송사를 가져 오너라. 가까이 와서 말하여 보아라. 와서 함께 판가름하여 보자.",
    Chn:"众海岛啊，当在我面前静默； 众民当从新得力， 都要近前来才可以说话， 我们可以彼此辩论。",
    Eng:"\"Be silent before me, you islands! Let the nations renew their strength! Let them come forward and speak; let us meet together at the place of judgment.",
    Ind:"Dengarkanlah Aku dengan berdiam diri, hai pulau-pulau; hendaklah bangsa-bangsa mendapat kekuatan baru! Biarlah mereka datang mendekat, kemudian berbicara; baiklah kita tampil bersama-sama untuk berperkara!"
  },
  {Bible:"Isaiah", Chapter:41, Verse:2, Page:1,
    Kor:"누가 동방에서 한 정복자를 일으켰느냐? 누가 그를 a가는 곳마다 승리하게 하였느냐? 누가 민족들을 그에게 굴복하게 하였느냐? 누가 그를 왕들의 통치자로 만들었느냐? 그의 칼은 그들을 쳐서 티끌처럼 만들고, 그의 활은 그들을 흩어서 검불처럼 날리게 하였다. (a 또는 '의로 불러서 그를 섬기게 하였느냐?')",
    Chn:"谁从东方兴起一人， 凭公义召他来到脚前呢？ 耶和华将列国交给他， 使他管辖君王， 把他们如灰尘交与他的刀， 如风吹的碎秸交与他的弓。",
    Eng:"\"Who has stirred up one from the east, calling him in righteousness to his service? He hands nations over to him and subdues kings before him. He turns them to dust with his sword, to windblown chaff with his bow.",
    Ind:"Siapakah yang menggerakkan dia dari timur, menggerakkan dia yang mendapat kemenangan di setiap langkahnya, yang menaklukkan bangsa-bangsa ke depannya dan menurunkan raja-raja? Pedangnya membuat mereka seperti debu dan panahnya membuat mereka seperti jerami yang tertiup."
  },
  {Bible:"Isaiah", Chapter:41, Verse:3, Page:1,
    Kor:"그가 거침없이 질주하여 그들을 추격하니, 미처 발이 땅에 닿지도 않는다.",
    Chn:"他追赶他们， 走他所未走的道， 坦然前行。",
    Eng:"He pursues them and moves on unscathed, by a path his feet have not traveled before.",
    Ind:"Ia mengejar mereka dan dengan selamat ia melalui jalan yang belum pernah diinjak kakinya."
  },
  {Bible:"Isaiah", Chapter:41, Verse:4, Page:1,
    Kor:"누가 이런 일을 일어나게 하였느냐? 누가 역사의 흐름을 결정하였느냐? 태초부터 나 주가 거기에 있었고, 끝 날에도 내가 거기에 있을 것이다.\"",
    Chn:"谁行做成就这事， 从起初宣召历代呢？ 就是我—耶和华！ 我是首先的， 也与末后的同在。",
    Eng:"Who has done this and carried it through, calling forth the generations from the beginning? I, the LORD--with the first of them and with the last--I am he.\"",
    Ind:"Siapakah yang melakukan dan mengerjakan semuanya itu? Dia yang dari dahulu memanggil bangkit keturunan-keturunan, Aku, TUHAN, yang terdahulu, dan bagi mereka yang terkemudian Aku tetap Dia juga."
  },
  {Bible:"Isaiah", Chapter:41, Verse:5, Page:1,
    Kor:"섬들이 주님께서 하신 일을 보고 두려워한다. 저 멀리 땅 끝에 있는 나라들이 무서워서 떤다. 사람들이 함께 모여서 나온다.",
    Chn:"海岛看见就都害怕； 地极也都战兢， 就近前来。",
    Eng:"The islands have seen it and fear; the ends of the earth tremble. They approach and come forward;",
    Ind:"Pulau-pulau telah melihatnya dan menjadi takut, ujung-ujung bumipun menjadi gemetar; mereka datang dan makin mendekat."
  },
  {Bible:"Isaiah", Chapter:41, Verse:6, Page:1,
    Kor:"그들은 서로 손발이 맞아서, 서로 힘을 내라고 격려한다.",
    Chn:"他们各人帮助邻舍， 各人对弟兄说：壮胆吧！",
    Eng:"each helps the other and says to his brother, \"Be strong!\"",
    Ind:"Yang seorang menolong yang lain dan berkata kepada temannya: \"Kuatkanlah hatimu!\""
  },
  {Bible:"Isaiah", Chapter:41, Verse:7, Page:1,
    Kor:"대장장이는 도금장이를 격려하고, 마치로 고르게 하는 자는 모루를 치는 자를 격려하여 이르기를 '잘했다. 잘했다' 하며, 못을 박아서 우상이 기우뚱거리지 않게 한다.",
    Chn:"木匠勉励银匠， 用锤打光的勉励打砧的， 论焊工说，焊得好； 又用钉子钉稳，免得偶像动摇。",
    Eng:"The craftsman encourages the goldsmith, and he who smooths with the hammer spurs on him who strikes the anvil. He says of the welding, \"It is good.\" He nails down the idol so it will not topple.",
    Ind:"Tukang besi menguatkan hati tukang emas, dan orang yang memipihkan logam dengan martil menguatkan hati orang yang menempa di atas landasan; ia berkata tentang patrian: \"Itu baik,\" lalu menguatkannya dengan paku-paku, sehingga tidak goyang."
  },
  {Bible:"Isaiah", Chapter:41, Verse:8, Page:1,
    Kor:"\"그러나 나의 종 너 이스라엘아, 내가 선택한 야곱아, 나의 친구 아브라함의 자손아!",
    Chn:"惟你以色列—我的仆人， 雅各—我所拣选的， 我朋友亚伯拉罕的后裔，",
    Eng:"\"But you, O Israel, my servant, Jacob, whom I have chosen, you descendants of Abraham my friend,",
    Ind:"Tetapi engkau, hai Israel, hamba-Ku, hai Yakub, yang telah Kupilih, keturunan Abraham, yang Kukasihi;"
  },
  {Bible:"Isaiah", Chapter:41, Verse:9, Page:1,
    Kor:"내가 땅 끝에서부터 너를 데리고 왔으며, 세상의 가장 먼 곳으로부터 너를 불러냈다. 그리고 내가 너에게 말하였다. 너는 나의 종이니, 내가 너를 선택하였고, 버리지 않았다고 하였다.",
    Chn:"你是我从地极所领来的， 从地角所召来的， 且对你说：你是我的仆人； 我拣选你，并不弃绝你。",
    Eng:"I took you from the ends of the earth, from its farthest corners I called you. I said, 'You are my servant'; I have chosen you and have not rejected you.",
    Ind:"engkau yang telah Kuambil dari ujung-ujung bumi dan yang telah Kupanggil dari penjuru-penjurunya, Aku berkata kepadamu: \"Engkau hamba-Ku, Aku telah memilih engkau dan tidak menolak engkau\";"
  },
  {Bible:"Isaiah", Chapter:41, Verse:10, Page:1,
    Kor:"내가 너와 함께 있으니, 두려워하지 말아라. 내가 너의 하나님이니, 떨지 말아라. 내가 너를 강하게 하겠다. 내가 너를 도와주고, 내 승리의 오른팔로 너를 붙들어 주겠다.",
    Chn:"你不要害怕，因为我与你同在； 不要惊惶，因为我是你的　神。 我必坚固你，我必帮助你； 我必用我公义的右手扶持你。",
    Eng:"So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.",
    Ind:"janganlah takut, sebab Aku menyertai engkau, janganlah bimbang, sebab Aku ini Allahmu; Aku akan meneguhkan, bahkan akan menolong engkau; Aku akan memegang engkau dengan tangan kanan-Ku yang membawa kemenangan."
  },
  {Bible:"Isaiah", Chapter:41, Verse:11, Page:1,
    Kor:"너에게 화를 낸 모든 자들이 수치를 당하며 당황할 것이다. 너와 다투는 자들이 아무것도 아닌 자들처럼 되어서 멸망할 것이다.",
    Chn:"凡向你发怒的必都抱愧蒙羞； 与你相争的必如无有，并要灭亡。",
    Eng:"\"All who rage against you will surely be ashamed and disgraced; those who oppose you will be as nothing and perish.",
    Ind:"Sesungguhnya, semua orang yang bangkit amarahnya terhadap engkau akan mendapat malu dan kena noda; orang-orang yang membantah engkau akan seperti tidak ada dan akan binasa;"
  },
  {Bible:"Isaiah", Chapter:41, Verse:12, Page:1,
    Kor:"네가 아무리 찾아보아도 너에게 대적하는 자들은 만나지 못할 것이며, 너와 싸우는 자들이 아무것도 아닌 것 같이, 허무한 것 같이 될 것이다.",
    Chn:"与你争竞的，你要找他们也找不着； 与你争战的必如无有，成为虚无。",
    Eng:"Though you search for your enemies, you will not find them. Those who wage war against you will be as nothing at all.",
    Ind:"engkau akan mencari orang-orang yang berkelahi dengan engkau, tetapi tidak akan menemui mereka; orang-orang yang berperang melawan engkau akan seperti tidak ada dan hampa."
  },
  {Bible:"Isaiah", Chapter:41, Verse:13, Page:1,
    Kor:"나는 주 너의 하나님이다. 내가 너의 오른손을 붙잡고 있다. 내가 너에게 말한다. 두려워하지 말아라. 내가 너를 돕겠다.\"",
    Chn:"因为我耶和华— 你的　神必搀扶你的右手， 对你说：不要害怕！ 我必帮助你。",
    Eng:"For I am the LORD, your God, who takes hold of your right hand and says to you, Do not fear; I will help you.",
    Ind:"Sebab Aku ini, TUHAN, Allahmu, memegang tangan kananmu dan berkata kepadamu: \"Janganlah takut, Akulah yang menolong engkau.\""
  },
  {Bible:"Isaiah", Chapter:41, Verse:14, Page:1,
    Kor:"너 지렁이 같은 야곱아, 벌레 같은 이스라엘아, 두려워하지 말아라. 주님께서 말씀하시기를 '내가 너를 돕겠다. 나 이스라엘의 거룩한 하나님이 너를 속량한다'고 하셨다.",
    Chn:"你这虫雅各和你们以色列人， 不要害怕！ 耶和华说：我必帮助你。 你的救赎主就是以色列的圣者。",
    Eng:"Do not be afraid, O worm Jacob, O little Israel, for I myself will help you,\" declares the LORD, your Redeemer, the Holy One of Israel.",
    Ind:"Janganlah takut, hai si cacing Yakub, hai si ulat Israel! Akulah yang menolong engkau, demikianlah firman TUHAN, dan yang menebus engkau ialah Yang Mahakudus, Allah Israel."
  },
  {Bible:"Isaiah", Chapter:41, Verse:15, Page:1,
    Kor:"\"내가 너를 날이 날카로운 새 타작기로 만들 터이니, 네가 산을 쳐서 부스러기를 만들 것이며 언덕을 겨로 만들 것이다.",
    Chn:"看哪，我已使你成为 有快齿打粮的新器具； 你要把山岭打得粉碎， 使冈陵如同糠秕。",
    Eng:"\"See, I will make you into a threshing sledge, new and sharp, with many teeth. You will thresh the mountains and crush them, and reduce the hills to chaff.",
    Ind:"Sesungguhnya, Aku membuat engkau menjadi papan pengirik yang tajam dan baru, dengan gigi dua jajar; engkau akan mengirik gunung-gunung dan menghancurkannya, dan bukit-bukitpun akan kaubuat seperti sekam."
  },
  {Bible:"Isaiah", Chapter:41, Verse:16, Page:1,
    Kor:"네가 산들을 까불면, 바람이 그 가루를 날려 버릴 것이며, 회오리바람이 그것들을 흩을 것이다. 그러나 너만은 나 주와 더불어 기뻐할 것이며, 나 이스라엘의 거룩한 하나님을 찬양할 것이다.",
    Chn:"你要把它簸扬，风要吹去； 旋风要把它刮散。 你倒要以耶和华为喜乐， 以以色列的圣者为夸耀。",
    Eng:"You will winnow them, the wind will pick them up, and a gale will blow them away. But you will rejoice in the LORD and glory in the Holy One of Israel.",
    Ind:"Engkau akan menampi mereka, lalu angin akan menerbangkan mereka, dan badai akan menyerakkan mereka. Tetapi engkau ini akan bersorak-sorak di dalam TUHAN dan bermegah di dalam Yang Mahakudus, Allah Israel."
  },
  {Bible:"Isaiah", Chapter:41, Verse:17, Page:1,
    Kor:"가련하고 빈궁한 사람들이 물을 찾지 못하여 갈증으로 그들의 혀가 탈 때에, 나 주가 그들의 기도에 응답하겠고, 나 이스라엘의 하나님이 그들을 버리지 않겠다.",
    Chn:"困苦穷乏人寻求水却没有； 他们因口渴，舌头干燥。 我—耶和华必应允他们； 我—以色列的　神必不离弃他们。",
    Eng:"\"The poor and needy search for water, but there is none; their tongues are parched with thirst. But I the LORD will answer them; I, the God of Israel, will not forsake them.",
    Ind:"Orang-orang sengsara dan orang-orang miskin sedang mencari air, tetapi tidak ada, lidah mereka kering kehausan; tetapi Aku, TUHAN, akan menjawab mereka, dan sebagai Allah orang Israel Aku tidak akan meninggalkan mereka."
  },
  {Bible:"Isaiah", Chapter:41, Verse:18, Page:1,
    Kor:"내가 메마른 산에서 강물이 터져 나오게 하며, 골짜기 가운데서 샘물이 솟아나게 하겠다. 내가 광야를 못으로 바꿀 것이며, 마른 땅을 샘 근원으로 만들겠다.",
    Chn:"我要在净光的高处开江河， 在谷中开泉源； 我要使沙漠变为水池， 使干地变为涌泉。",
    Eng:"I will make rivers flow on barren heights, and springs within the valleys. I will turn the desert into pools of water, and the parched ground into springs.",
    Ind:"Aku akan membuat sungai-sungai memancar di atas bukit-bukit yang gundul, dan membuat mata-mata air membual di tengah dataran; Aku akan membuat padang gurun menjadi telaga dan memancarkan air dari tanah kering."
  },
  {Bible:"Isaiah", Chapter:41, Verse:19, Page:1,
    Kor:"내가 광야에는 백향목과 아카시아와 화석류와 들올리브 나무를 심고, 사막에는 잣나무와 소나무와 회양목을 함께 심겠다.\"",
    Chn:"我要在旷野种上香柏树、 皂荚树、番石榴树，和野橄榄树。 我在沙漠要把松树、杉树， 并黄杨树一同栽植；",
    Eng:"I will put in the desert the cedar and the acacia, the myrtle and the olive. I will set pines in the wasteland, the fir and the cypress together,",
    Ind:"Aku akan menanam pohon aras di padang gurun, pohon penaga, pohon murad dan pohon minyak; Aku akan menumbuhkan pohon sanobar di padang belantara dan pohon berangan serta pohon cemara di sampingnya,"
  },
  {Bible:"Isaiah", Chapter:41, Verse:20, Page:1,
    Kor:"사람들이 이것을 보고, 주님께서 이 일을 몸소 하셨다는 것을 알게 될 것이다. 이스라엘의 거룩하신 하나님께서 이것을 창조하셨다는 것을 깨닫게 될 것이다.",
    Chn:"好叫人看见、知道、 思想、明白； 这是耶和华的手所做的， 是以色列的圣者所造的。",
    Eng:"so that people may see and know, may consider and understand, that the hand of the LORD has done this, that the Holy One of Israel has created it.",
    Ind:"supaya semua orang melihat dan mengetahui, memperhatikan dan memahami, bahwa tangan TUHAN yang membuat semuanya ini dan Yang Mahakudus, Allah Israel, yang menciptakannya."
  },
  {Bible:"Isaiah", Chapter:41, Verse:21, Page:1,
    Kor:"<주님께서 거짓 신들에게 도전하시다> 주님께서 말씀하신다. \"민족의 신들아, 소송을 제기하여 보아라.\" \"너희는 확실한 증거를 제시하여 보아라.\" 야곱의 왕께서 말씀하신다.",
    Chn:"耶和华对假神说： 你们要呈上你们的案件； 雅各的君说： 你们要声明你们确实的理由。",
    Eng:"\"Present your case,\" says the LORD. \"Set forth your arguments,\" says Jacob's King.",
    Ind:"Ajukanlah perkaramu, firman TUHAN, kemukakanlah alasan-alasanmu, firman Raja, Allah Yakub."
  },
  {Bible:"Isaiah", Chapter:41, Verse:22, Page:1,
    Kor:"이리 와서, 장차 무슨 일이 일어날 것인지, 우리에게 말하여 보아라. 지난날에 있었던 일들이 어떤 것이었는지, 말하여 보아라. 그러면 우리가 그것들을 살펴 그 결과를 알아보겠다. 아니면, 앞으로 올 일들을 우리에게 말하여 보아라.",
    Chn:"可以声明，指示我们将来必遇的事， 说明先前的是什么事， 好叫我们思索，得知事的结局， 或者把将来的事指示我们。",
    Eng:"\"Bring in your idols to tell us what is going to happen. Tell us what the former things were, so that we may consider them and know their final outcome. Or declare to us the things to come,",
    Ind:"Biarlah mereka maju dan memberitahukan kepada kami apa yang akan terjadi! Nubuat yang dahulu, beritahukanlah apa artinya, supaya kami memperhatikannya, atau hal-hal yang akan datang, kabarkanlah kepada kami, supaya kami mengetahui kesudahannya!"
  },
  {Bible:"Isaiah", Chapter:41, Verse:23, Page:1,
    Kor:"장차 올 일들을 말하여 보아라. 그러면 우리가 너희들이 신이라는 것을 알 수 있을 것이다. 복을 내리든 화를 내리든, 좀 하여 보아라. 그러면 우리가 모두 놀라며 두려워하게 될 것이다.",
    Chn:"要说明后来的事， 好叫我们知道你们是神。 你们或降福，或降祸， 使我们惊奇，一同观看。",
    Eng:"tell us what the future holds, so we may know that you are gods. Do something, whether good or bad, so that we will be dismayed and filled with fear.",
    Ind:"Beritahukanlah hal-hal yang akan datang kemudian, supaya kami mengetahui, bahwa kamu ini sungguh allah; bertindak sajalah, biar secara baik ataupun secara buruk, supaya kami bersama-sama tercengang melihatnya!"
  },
  {Bible:"Isaiah", Chapter:41, Verse:24, Page:1,
    Kor:"참으로 너희는 아무것도 아니며, 너희가 하는 일도 헛것이니, 너희를 섬겨 예배하는 자도 혐오스러울 뿐이다.",
    Chn:"看哪，你们属乎虚无； 你们的作为也属乎虚空。 那选择你们的是可憎恶的。",
    Eng:"But you are less than nothing and your works are utterly worthless; he who chooses you is detestable.",
    Ind:"Sesungguhnya, kamu ini adalah seperti tidak ada dan perbuatan-perbuatanmu adalah hampa; orang yang memilih kamu adalah kejijikan."
  },
  {Bible:"Isaiah", Chapter:41, Verse:25, Page:1,
    Kor:"\"내가 북쪽에서 한 사람을 일으켜 오게 하였다. 나의 이름을 부르는 그 사람을 해 뜨는 곳에서 오게 하였다. 그가 와서, 토기장이가 진흙을 밟아 이기듯, 통치자들을 진흙처럼 밟을 것이다.\"",
    Chn:"我从北方兴起一人； 他是求告我名的， 从日出之地而来。 他必临到掌权的， 好像临到灰泥， 仿佛窑匠踹泥一样。",
    Eng:"\"I have stirred up one from the north, and he comes--one from the rising sun who calls on my name. He treads on rulers as if they were mortar, as if he were a potter treading the clay.",
    Ind:"Aku telah menggerakkan seorang dari utara dan ia telah datang, dari sebelah matahari terbit Aku telah memanggil dia dengan namanya. Seperti tukang periuk menginjak-injak tanah liat, demikian dia akan menginjak-injak penguasa-penguasa seperti lumpur."
  },
  {Bible:"Isaiah", Chapter:41, Verse:26, Page:1,
    Kor:"너희 우상들 가운데서, 어떤 우상이 처음부터 이 일을 우리에게 일러주어 알게 하였느냐? 누가 이전부터 우리에게 일러주어서, 우리가 '그것이 옳다' 하고 말하게 한 일이 있느냐? 일러준 자도 없고, 들려준 자도 없었다. 우리는 너희 말을 들어본 일이 전혀 없다.",
    Chn:"谁从起初指明这事，使我们知道呢？ 谁从先前说明，使我们说他不错呢？ 谁也没有指明； 谁也没有说明； 谁也没有听见你们的话。",
    Eng:"Who told of this from the beginning, so we could know, or beforehand, so we could say, 'He was right'? No one told of this, no one foretold it, no one heard any words from you.",
    Ind:"Siapakah yang memberitahukannya dari mulanya, sehingga kami mengetahuinya, dan dari dahulu, sehingga kami mengatakan: \"Benarlah dia?\" Sungguh, tidak ada orang yang memberitahukannya, tidak ada orang yang mengabarkannya, tidak ada orang yang mendengar sepatah katapun dari padamu."
  },
  {Bible:"Isaiah", Chapter:41, Verse:27, Page:1,
    Kor:"\"나 주가 비로소 처음부터 시온에게 알렸다. '이런 일들을 보아라' 하고 말하였다. 내가 기쁜 소식을 전할 사람을 예루살렘에 보냈다.",
    Chn:"我首先对锡安说： 看哪，我要将一位报好信息的赐给耶路撒冷。",
    Eng:"I was the first to tell Zion, 'Look, here they are!' I gave to Jerusalem a messenger of good tidings.",
    Ind:"Sebagai yang pertama Aku memberitahukannya kepada Sion, dan Aku memberikan orang yang membawa kabar baik kepada Yerusalem."
  },
  {Bible:"Isaiah", Chapter:41, Verse:28, Page:1,
    Kor:"내가 우상들을 둘러보았다. 그들 가운데 말을 하는 우상은 하나도 없었다. 어떤 우상도 내가 묻는 말에 대답하지 못하였다.",
    Chn:"我看的时候并没有人； 我问的时候， 他们中间也没有谋士可以回答一句。",
    Eng:"I look but there is no one--no one among them to give counsel, no one to give answer when I ask them.",
    Ind:"Apabila Aku melihat berkeliling, maka tidak ada seorangpun, dan di antara semua mereka ini tidak ada yang dapat memberi petunjuk, atau yang dapat memberi jawab kalau Aku menanyakan mereka."
  },
  {Bible:"Isaiah", Chapter:41, Verse:29, Page:1,
    Kor:"보아라, 이 모든 우상은 쓸모가 없으며, 그것들은 아무것도 할 수 없다. 부어 만든 우상은 바람일 뿐이요, 헛것일 뿐이다.\"",
    Chn:"看哪，他们和他们的工作都是虚空， 且是虚无。 他们所铸的偶像都是风， 都是虚的。",
    Eng:"See, they are all false! Their deeds amount to nothing; their images are but wind and confusion.",
    Ind:"Sesungguhnya, sekaliannya mereka seperti tidak ada, perbuatan-perbuatan mereka hampa, patung-patung tuangan mereka angin dan kesia-siaan."
  },
]);
