// 이사야 59장 · Isaiah 59
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Isaiah",59,21);
BibleDB.add([
  {Bible:"Isaiah", Chapter:59, Verse:1, Page:1, Kor:"<예언자가 백성의 죄를 규탄하다> 주님의 손이 짧아서 구원하지 못하시는 것도 아니고, 주님의 귀가 어두워서 듣지 못하시는 것도 아니다.", Chn:"", Eng:"Surely the arm of the LORD is not too short to save, nor his ear too dull to hear.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:2, Page:1, Kor:"오직, 너희 죄악이 너희와 너희의 하나님 사이를 갈라놓았고, 너희의 죄 때문에 주님께서 너희에게서 얼굴을 돌리셔서, 너희의 말을 듣지 않으실 뿐이다.", Chn:"", Eng:"But your iniquities have separated you from your God; your sins have hidden his face from you, so that he will not hear.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:3, Page:1, Kor:"너희의 손이 피로 더러워졌으며, 너희의 손가락이 죄악으로 더러워졌고, 너희의 입술이 거짓말을 하며, 너희의 혀가 악독한 말을 하기 때문이다.", Chn:"", Eng:"For your hands are stained with blood, your fingers with guilt. Your lips have spoken lies, and your tongue mutters wicked things.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:4, Page:1, Kor:"공의로써 소송을 제기하는 사람이 아무도 없고, 진실되게 재판하는 사람이 하나도 없다. 헛된 것을 믿고 거짓을 말하며, 해로운 생각을 품고서, 죄를 짓는다.", Chn:"", Eng:"No one calls for justice; no one pleads his case with integrity. They rely on empty arguments and speak lies; they conceive trouble and give birth to evil.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:5, Page:1, Kor:"그들은 독사의 알을 품고, 거미줄로 옷감을 짠다. 그 알을 먹는 사람은 죽을 것이요, 그 알이 밟혀서 터지면, 독사가 나올 것이다.", Chn:"", Eng:"They hatch the eggs of vipers and spin a spider's web. Whoever eats their eggs will die, and when one is broken, an adder is hatched.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:6, Page:1, Kor:"그들이 거미줄로 짠 것은 옷이 되지 못하고, 그들이 만든 것으로는 아무도 몸을 덮지 못한다. 그들이 하는 일이란 죄악을 저지르는 것뿐이며, 그들의 손에는 폭행만 있다.", Chn:"", Eng:"Their cobwebs are useless for clothing; they cannot cover themselves with what they make. Their deeds are evil deeds, and acts of violence are in their hands.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:7, Page:1, Kor:"그들의 발은 나쁜 일을 하는 데 빠르고, 죄 없는 사람을 죽이는 일에 신속하다. 그들의 생각이란 죄악으로 가득 차 있을 뿐이며, 그들이 가는 길에는 황폐와 파멸이 있을 뿐이다.", Chn:"", Eng:"Their feet rush into sin; they are swift to shed innocent blood. Their thoughts are evil thoughts; ruin and destruction mark their ways.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:8, Page:1, Kor:"그들은 안전한 길을 알지 못하며 그들이 가는 길에는 공평이 없다. 스스로 길을 굽게 만드니, 그 길을 걷는 모든 사람에게 안전이 없다.", Chn:"", Eng:"The way of peace they do not know; there is no justice in their paths. They have turned them into crooked roads; no one who walks in them will know peace.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:9, Page:1, Kor:"<백성이 죄를 고백하다> 그러므로 공평이 우리에게서 멀고, 공의가 우리에게 미치지 못한다. 우리가 빛을 바라나, 어둠뿐이며, 밝음을 바라나, 암흑 속을 걸을 뿐이다.", Chn:"", Eng:"So justice is far from us, and righteousness does not reach us. We look for light, but all is darkness; for brightness, but we walk in deep shadows.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:10, Page:1, Kor:"우리는 앞을 못 보는 사람처럼 담을 더듬고, 눈먼 사람처럼 더듬고 다닌다. 대낮에도 우리가 밤길을 걸을 때처럼 넘어지니, 몸이 건강하다고 하나 죽은 사람과 다를 바 없다.", Chn:"", Eng:"Like the blind we grope along the wall, feeling our way like men without eyes. At midday we stumble as if it were twilight; among the strong, we are like the dead.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:11, Page:1, Kor:"우리 모두가 곰처럼 부르짖고, 비둘기처럼 슬피 울며, 공평을 바라지만 공평이 없고, 구원을 바라지만 그 구원이 우리에게서 멀다.", Chn:"", Eng:"We all growl like bears; we moan mournfully like doves. We look for justice, but find none; for deliverance, but it is far away.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:12, Page:1, Kor:"주님, 주님께 지은 우리의 죄가 매우 많습니다. 우리의 죄가 우리를 고발합니다. 우리가 지은 죄를 우리가 발뺌할 수 없으며, 우리의 죄를 우리가 잘 압니다.", Chn:"", Eng:"For our offenses are many in your sight, and our sins testify against us. Our offenses are ever with us, and we acknowledge our iniquities:", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:13, Page:1, Kor:"우리가 죄를 짓고 주님을 부정하였습니다. 우리의 하나님께 등을 돌리고 물러가서, 포학한 말과 거역하는 말을 하면서, 거짓말을 마음에 품었고, 또 실제로 거짓말을 하였습니다.", Chn:"", Eng:"rebellion and treachery against the LORD, turning our backs on our God, fomenting oppression and revolt, uttering lies our hearts have conceived.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:14, Page:1, Kor:"그래서 공평이 뒤로 밀려나고 공의가 멀어졌으며, 성실이 땅바닥에 떨어졌고, 정직이 발붙이지 못합니다.", Chn:"", Eng:"So justice is driven back, and righteousness stands at a distance; truth has stumbled in the streets, honesty cannot enter.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:15, Page:1, Kor:"성실이 사라지니, 악에서 떠난 자가 오히려 약탈을 당합니다. <주님께서 백성을 건져내려고 하시다> 주님께서 이것을 보셨다. 공평이 없는 것을 보시고 슬퍼하셨다.", Chn:"", Eng:"Truth is nowhere to be found, and whoever shuns evil becomes a prey. The LORD looked and was displeased that there was no justice.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:16, Page:1, Kor:"압박받는 사람을 도우려는 사람이 없음을 보시고, 중재자가 없음을 보시고, 주님께서는 놀라셨다. 주님께서는 직접, 억압받는 사람들을 구원하시려고, 반드시 공의를 이루시려고, 당신의 능력을 친히 발휘하실 것이다.", Chn:"", Eng:"He saw that there was no one, he was appalled that there was no one to intervene; so his own arm worked salvation for him, and his own righteousness sustained him.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:17, Page:1, Kor:"주님께서 공의를 갑옷으로 입으시고, 구원의 투구를 머리에 쓰셨다. 응징을 속옷으로 입으셨다. 열심을 겉옷으로 입으셨다.", Chn:"", Eng:"He put on righteousness as his breastplate, and the helmet of salvation on his head; he put on the garments of vengeance and wrapped himself in zeal as in a cloak.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:18, Page:1, Kor:"그들이 한 대로 갚으신다. 적들에게 진노하시며, 원수들에게 보복하신다. 섬들에게도 보복하신다.", Chn:"", Eng:"According to what they have done, so will he repay wrath to his enemies and retribution to his foes; he will repay the islands their due.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:19, Page:1, Kor:"해 지는 곳에서 주님의 이름을 두려워하며, 해 뜨는 곳에서 주님의 영광을 두려워할 것이다. 원수가 강물처럼 몰려오겠으나, 주님의 영이 그들을 물리치실 것이다.", Chn:"", Eng:"From the west, men will fear the name of the LORD, and from the rising of the sun, they will revere his glory. For he will come like a pent-up flood that the breath of the LORD drives along.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:20, Page:1, Kor:"주님께서 시온에 속량자로 오시고, 야곱의 자손 가운데서 죄를 회개한 사람들에게 오신다. 주님께서 하신 말씀이다.", Chn:"", Eng:"\"The Redeemer will come to Zion, to those in Jacob who repent of their sins,\" declares the LORD.", Ind:""},
  {Bible:"Isaiah", Chapter:59, Verse:21, Page:1, Kor:"주님께서 말씀하신다. \"내가 그들과 맺은 나의 언약은 이러하다. 너의 위에 있는 나의 영과 너의 입에 담긴 나의 말이, 이제부터 영원토록, 너의 입과 너의 자손의 입과 또 그 자손의 자손의 입에서 떠나지 않을 것이다.\" 주님께서 하신 말씀이다.", Chn:"", Eng:"\"As for me, this is my covenant with them,\" says the LORD. \"My Spirit, who is on you, and my words that I have put in your mouth will not depart from your mouth, or from the mouths of your children, or from the mouths of their descendants from this time on and forever,\" says the LORD.", Ind:""},
]);
