// 이사야 58장 · Isaiah 58
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Isaiah",58,14);
BibleDB.add([
  {Bible:"Isaiah", Chapter:58, Verse:1, Page:1, Kor:"<참 금식> \"목소리를 크게 내어 힘껏 외쳐라. 주저하지 말아라. 너의 목소리를 나팔 소리처럼 높여서 나의 백성에게 그들의 허물을 알리고, 야곱의 집에 그들의 죄를 알려라.", Chn:"", Eng:"\"Shout it aloud, do not hold back. Raise your voice like a trumpet. Declare to my people their rebellion and to the house of Jacob their sins.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:2, Page:1, Kor:"그들이 마치 공의를 행하고 하나님의 규례를 저버리지 않는 민족이나 되듯이, 날마다 나를 찾으며, 나의 길을 알기를 좋아한다. 그들은 무엇이 공의로운 판단인가를 나에게 묻고, 하나님께 가까이 나가기를 즐거워한다고 한다.\"", Chn:"", Eng:"For day after day they seek me out; they seem eager to know my ways, as if they were a nation that does what is right and has not forsaken the commands of its God. They ask me for just decisions and seem eager for God to come near them.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:3, Page:1, Kor:"주님께서 보시지도 않는데, 우리가 무엇 때문에 금식을 합니까? 주님께서 알아 주시지도 않는데, 우리가 무엇 때문에 고행을 하겠습니까? 너희들이 금식하는 날, 너희 자신의 향락만을 찾고, 일꾼들에게는 무리하게 일을 시킨다.", Chn:"", Eng:"'Why have we fasted,' they say, 'and you have not seen it? Why have we humbled ourselves, and you have not noticed?' \"Yet on the day of your fasting, you do as you please and exploit all your workers.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:4, Page:1, Kor:"너희가 다투고 싸우면서, 금식을 하는구나. 이렇게 못된 주먹질이나 하려고 금식을 하느냐? 너희의 목소리를 저 높은 곳에 들리게 할 생각이 있다면, 오늘과 같은 이런 금식을 해서는 안 된다.", Chn:"", Eng:"Your fasting ends in quarreling and strife, and in striking each other with wicked fists. You cannot fast as you do today and expect your voice to be heard on high.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:5, Page:1, Kor:"\"이것이 어찌 내가 기뻐하는 금식이겠느냐? 이것이 어찌 사람이 통회하며 괴로워하는 날이 되겠느냐?\" 머리를 갈대처럼 숙이고 굵은 베와 재를 깔고 앉는다고 해서 어찌 이것을 금식이라고 하겠으며, 주님께서 너희를 기쁘게 반기실 날이라고 할 수 있겠느냐?", Chn:"", Eng:"Is this the kind of fast I have chosen, only a day for a man to humble himself? Is it only for bowing one's head like a reed and for lying on sackcloth and ashes? Is that what you call a fast, a day acceptable to the LORD?", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:6, Page:1, Kor:"\"내가 기뻐하는 금식은, 부당한 결박을 풀어 주는 것, 멍에의 줄을 끌러 주는 것, 압제받는 사람을 놓아 주는 것, 모든 멍에를 꺾어 버리는 것, 바로 이런 것들이 아니냐?\"", Chn:"", Eng:"\"Is not this the kind of fasting I have chosen: to loose the chains of injustice and untie the cords of the yoke, to set the oppressed free and break every yoke?", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:7, Page:1, Kor:"또한 굶주린 사람에게 너의 먹거리를 나누어 주는 것, 떠도는 불쌍한 사람을 집에 맞아들이는 것이 아니겠느냐? 헐벗은 사람을 보았을 때에 그에게 옷을 입혀 주는 것, 너의 골육을 피하여 숨지 않는 것이 아니겠느냐?", Chn:"", Eng:"Is it not to share your food with the hungry and to provide the poor wanderer with shelter--when you see the naked, to clothe him, and not to turn away from your own flesh and blood?", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:8, Page:1, Kor:"그리하면 네 빛이 새벽 햇살처럼 비칠 것이며, 네 상처가 빨리 나을 것이다. 네 의를 드러내실 분이 네 앞에 가실 것이며, 주님의 영광이 네 뒤에서 호위할 것이다.", Chn:"", Eng:"Then your light will break forth like the dawn, and your healing will quickly appear; then your righteousness will go before you, and the glory of the LORD will be your rear guard.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:9, Page:1, Kor:"그 때에 네가 주님을 부르면 주님께서 응답하실 것이다. 네가 부르짖을 때에, 주님께서 '내가 여기에 있다' 하고 대답하실 것이다. 네가 너의 나라에서 무거운 멍에와 온갖 폭력과 폭언을 없애 버린다면,", Chn:"", Eng:"Then you will call, and the LORD will answer; you will cry for help, and he will say: Here am I. \"If you do away with the yoke of oppression, with the pointing finger and malicious talk,", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:10, Page:1, Kor:"네가 너의 정성을 굶주린 사람에게 쏟으며, 불쌍한 자의 소원을 충족시켜 주면, 너의 빛이 어둠 가운데서 나타나며, 캄캄한 밤이 오히려 대낮같이 될 것이다.", Chn:"", Eng:"and if you spend yourselves in behalf of the hungry and satisfy the needs of the oppressed, then your light will rise in the darkness, and your night will become like the noonday.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:11, Page:1, Kor:"주님께서 너를 늘 인도하시고, 메마른 곳에서도 너의 영혼을 충족시켜 주시며, 너의 뼈마디에 원기를 주실 것이다. 너는 마치 물 댄 동산처럼 되고, 물이 끊어지지 않는 샘처럼 될 것이다.", Chn:"", Eng:"The LORD will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame. You will be like a well-watered garden, like a spring whose waters never fail.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:12, Page:1, Kor:"너의 백성이 해묵은 폐허에서 성읍을 재건하며, 대대로 버려 두었던 기초를 다시 쌓을 것이다. 사람들은 너를 두고 \"갈라진 벽을 고친 왕!\" \"길거리를 고쳐 사람이 살 수 있도록 한 왕!\" 이라고 부를 것이다.", Chn:"", Eng:"Your people will rebuild the ancient ruins and will raise up the age-old foundations; you will be called Repairer of Broken Walls, Restorer of Streets with Dwellings.", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:13, Page:1, Kor:"<안식일을 지키는 보상> \"유다야, 네가 안식일에 발길을 삼가 여행을 하지 않으며, 나의 거룩한 날에 너의 쾌락을 일삼지 않으며, 안식일을 '즐거운 날'이라고 부르며, 주의 거룩한 날을 '존귀한 날'이라고 한다면, 그리고 이 날을 귀하게 여겨서, 네 멋대로 하지 않으며, 너 자신의 쾌락을 찾지 않으며, 함부로 말하지 않으면,", Chn:"", Eng:"\"If you keep your feet from breaking the Sabbath and from doing as you please on my holy day, if you call the Sabbath a delight and the LORD'S holy day honorable, and if you honor it by not going your own way and not doing as you please or speaking idle words,", Ind:""},
  {Bible:"Isaiah", Chapter:58, Verse:14, Page:1, Kor:"그 때에 너는 주 안에서 즐거움을 얻을 것이다. 내가 너를 땅에서 영화롭게 하고, 너의 조상 야곱의 유산을 먹고 살도록 하겠다.\" 이것은 주님께서 친히 하신 말씀이다.", Chn:"", Eng:"then you will find your joy in the LORD, and I will cause you to ride on the heights of the land and to feast on the inheritance of your father Jacob.\" The mouth of the LORD has spoken.", Ind:""},
]);
