// 이사야 1장 · Isaiah 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Isaiah",1,31);
BibleDB.add([
  {Bible:"Isaiah", Chapter:1, Verse:1, Page:1, Kor:"", Chn:"", Eng:"The vision concerning Judah and Jerusalem that Isaiah son of Amoz saw during the reigns of Uzziah, Jotham, Ahaz and Hezekiah, kings of Judah.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:2, Page:1, Kor:"", Chn:"", Eng:"Hear, O heavens! Listen, O earth! For the LORD has spoken: "I reared children and brought them up, but they have rebelled against me.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:3, Page:1, Kor:"", Chn:"", Eng:"The ox knows his master, the donkey his owner's manger, but Israel does not know, my people do not understand."", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Ah, sinful nation, a people loaded with guilt, a brood of evildoers, children given to corruption! They have forsaken the LORD; they have spurned the Holy One of Israel and turned their backs on him.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Why should you be beaten anymore? Why do you persist in rebellion? Your whole head is injured, your whole heart afflicted.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:6, Page:1, Kor:"", Chn:"", Eng:"From the sole of your foot to the top of your head there is no soundness--only wounds and welts and open sores, not cleansed or bandaged or soothed with oil.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Your country is desolate, your cities burned with fire; your fields are being stripped by foreigners right before you, laid waste as when overthrown by strangers.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:8, Page:1, Kor:"", Chn:"", Eng:"The Daughter of Zion is left like a shelter in a vineyard, like a hut in a field of melons, like a city under siege.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Unless the LORD Almighty had left us some survivors, we would have become like Sodom, we would have been like Gomorrah.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Hear the word of the LORD, you rulers of Sodom; listen to the law of our God, you people of Gomorrah!", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:11, Page:1, Kor:"", Chn:"", Eng:""The multitude of your sacrifices--what are they to me?" says the LORD. "I have more than enough of burnt offerings, of rams and the fat of fattened animals; I have no pleasure in the blood of bulls and lambs and goats.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:12, Page:1, Kor:"", Chn:"", Eng:"When you come to appear before me, who has asked this of you, this trampling of my courts?", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Stop bringing meaningless offerings! Your incense is detestable to me. New Moons, Sabbaths and convocations--I cannot bear your evil assemblies.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Your New Moon festivals and your appointed feasts my soul hates. They have become a burden to me; I am weary of bearing them.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:15, Page:1, Kor:"", Chn:"", Eng:"When you spread out your hands in prayer, I will hide my eyes from you; even if you offer many prayers, I will not listen. Your hands are full of blood;", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:16, Page:1, Kor:"", Chn:"", Eng:"wash and make yourselves clean. Take your evil deeds out of my sight! Stop doing wrong,", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:17, Page:1, Kor:"", Chn:"", Eng:"learn to do right! Seek justice, encourage the oppressed. Defend the cause of the fatherless, plead the case of the widow.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:18, Page:1, Kor:"", Chn:"", Eng:""Come now, let us reason together," says the LORD. "Though your sins are like scarlet, they shall be as white as snow; though they are red as crimson, they shall be like wool.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:19, Page:1, Kor:"", Chn:"", Eng:"If you are willing and obedient, you will eat the best from the land;", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:20, Page:1, Kor:"", Chn:"", Eng:"but if you resist and rebel, you will be devoured by the sword." For the mouth of the LORD has spoken.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:21, Page:1, Kor:"", Chn:"", Eng:"See how the faithful city has become a harlot! She once was full of justice; righteousness used to dwell in her--but now murderers!", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:22, Page:1, Kor:"", Chn:"", Eng:"Your silver has become dross, your choice wine is diluted with water.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:23, Page:1, Kor:"", Chn:"", Eng:"Your rulers are rebels, companions of thieves; they all love bribes and chase after gifts. They do not defend the cause of the fatherless; the widow's case does not come before them.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:24, Page:1, Kor:"", Chn:"", Eng:"Therefore the Lord, the LORD Almighty, the Mighty One of Israel, declares: "Ah, I will get relief from my foes and avenge myself on my enemies.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:25, Page:1, Kor:"", Chn:"", Eng:"I will turn my hand against you; I will thoroughly purge away your dross and remove all your impurities.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:26, Page:1, Kor:"", Chn:"", Eng:"I will restore your judges as in days of old, your counselors as at the beginning. Afterward you will be called the City of Righteousness, the Faithful City."", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Zion will be redeemed with justice, her penitent ones with righteousness.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:28, Page:1, Kor:"", Chn:"", Eng:"But rebels and sinners will both be broken, and those who forsake the LORD will perish.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:29, Page:1, Kor:"", Chn:"", Eng:""You will be ashamed because of the sacred oaks in which you have delighted; you will be disgraced because of the gardens that you have chosen.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:30, Page:1, Kor:"", Chn:"", Eng:"You will be like an oak with fading leaves, like a garden without water.", Ind:""},
  {Bible:"Isaiah", Chapter:1, Verse:31, Page:1, Kor:"", Chn:"", Eng:"The mighty man will become tinder and his work a spark; both will burn together, with no one to quench the fire."", Ind:""},
]);
