// 이사야 1장 · Isaiah 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Isaiah",1,31);
BibleDB.add([
  {Bible:"Isaiah", Chapter:1, Verse:1, Page:1,
    Kor:"이것은, 아모스의 아들 이사야가, 유다 왕 웃시야와 요담과 아하스와 히스기야 시대에, 유다와 예루살렘에 대하여 본 이상이다.",
    Chn:"当乌西雅、约坦、亚哈斯、希西家作犹大王的时候，亚摩斯的儿子以赛亚得默示，论到犹大和耶路撒冷。",
    Eng:"The vision concerning Judah and Jerusalem that Isaiah son of Amoz saw during the reigns of Uzziah, Jotham, Ahaz and Hezekiah, kings of Judah.",
    Ind:"Penglihatan yang telah dilihat Yesaya bin Amos tentang Yehuda dan Yerusalem dalam zaman Uzia, Yotam, Ahas dan Hizkia, raja-raja Yehuda."
  },
  {Bible:"Isaiah", Chapter:1, Verse:2, Page:1,
    Kor:"<하나님께서 백성을 꾸짖으시다> 하늘아, 들어라! 땅아, 귀를 기울여라! 주님께서 말씀하신다. \"내가 자식이라고 기르고 키웠는데, 그들이 나를 거역하였다.",
    Chn:"天哪，要听！地啊，侧耳而听！ 因为耶和华说： 我养育儿女，将他们养大， 他们竟悖逆我。",
    Eng:"Hear, O heavens! Listen, O earth! For the LORD has spoken: \"I reared children and brought them up, but they have rebelled against me.",
    Ind:"Dengarlah, hai langit, dan perhatikanlah, hai bumi, sebab TUHAN berfirman: \"Aku membesarkan anak-anak dan mengasuhnya, tetapi mereka memberontak terhadap Aku."
  },
  {Bible:"Isaiah", Chapter:1, Verse:3, Page:1,
    Kor:"소도 제 임자를 알고, 나귀도 주인이 저를 어떻게 먹여 키우는지 알건마는, 이스라엘은 알지 못하고, 나의 백성은 깨닫지 못하는구나.\"",
    Chn:"牛认识主人， 驴认识主人的槽， 以色列却不认识； 我的民却不留意。",
    Eng:"The ox knows his master, the donkey his owner's manger, but Israel does not know, my people do not understand.\"",
    Ind:"Lembu mengenal pemiliknya, tetapi Israel tidak; keledai mengenal palungan yang disediakan tuannya, tetapi umat-Ku tidak memahaminya.\""
  },
  {Bible:"Isaiah", Chapter:1, Verse:4, Page:1,
    Kor:"슬프다! 죄 지은 민족, 허물이 많은 백성, 흉악한 종자, 타락한 자식들! 너희가 주님을 버렸구나. 이스라엘의 거룩하신 분을 업신여겨서, 등을 돌리고 말았구나.",
    Chn:"嗐！犯罪的国民， 担着罪孽的百姓； 行恶的种类， 败坏的儿女！ 他们离弃耶和华， 藐视以色列的圣者， 与他生疏，往后退步。",
    Eng:"Ah, sinful nation, a people loaded with guilt, a brood of evildoers, children given to corruption! They have forsaken the LORD; they have spurned the Holy One of Israel and turned their backs on him.",
    Ind:"Celakalah bangsa yang berdosa, kaum yang sarat dengan kesalahan, keturunan yang jahat-jahat, anak-anak yang berlaku buruk! Mereka meninggalkan TUHAN, menista Yang Mahakudus, Allah Israel, dan berpaling membelakangi Dia."
  },
  {Bible:"Isaiah", Chapter:1, Verse:5, Page:1,
    Kor:"어찌하여 너희는 더 맞을 일만 하느냐? 어찌하여 여전히 배반을 일삼느냐? 머리는 온통 상처투성이고, 속은 온통 골병이 들었으며,",
    Chn:"你们为什么屡次悖逆， 还要受责打吗？ 你们已经满头疼痛， 全心发昏。",
    Eng:"Why should you be beaten anymore? Why do you persist in rebellion? Your whole head is injured, your whole heart afflicted.",
    Ind:"Di mana kamu mau dipukul lagi, kamu yang bertambah murtad? Seluruh kepala sakit dan seluruh hati lemah lesu."
  },
  {Bible:"Isaiah", Chapter:1, Verse:6, Page:1,
    Kor:"발바닥에서 정수리까지 성한 데가 없이, 상처난 곳과 매맞은 곳과 또 새로 맞아 생긴 상처뿐인데도, 그것을 짜내지도 못하고, 싸매지도 못하고, 상처가 가라앉게 기름을 바르지도 못하였구나.",
    Chn:"从脚掌到头顶， 没有一处完全的， 尽是伤口、青肿，与新打的伤痕， 都没有收口，没有缠裹， 也没有用膏滋润。",
    Eng:"From the sole of your foot to the top of your head there is no soundness--only wounds and welts and open sores, not cleansed or bandaged or soothed with oil.",
    Ind:"Dari telapak kaki sampai kepala tidak ada yang sehat: bengkak dan bilur dan luka baru, tidak dipijit dan tidak dibalut dan tidak ditaruh minyak."
  },
  {Bible:"Isaiah", Chapter:1, Verse:7, Page:1,
    Kor:"너희의 땅이 황폐해지고, 너희의 성읍들이 송두리째 불에 탔으며, 너희의 농토에서 난 것을, 너희가 보는 앞에서 이방 사람들이 약탈해 갔다. 이방 사람들이 너희의 땅을 박살냈을 때처럼 황폐해지고 말았구나.",
    Chn:"你们的地土已经荒凉； 你们的城邑被火焚毁。 你们的田地在你们眼前为外邦人所侵吞， 既被外邦人倾覆就成为荒凉。",
    Eng:"Your country is desolate, your cities burned with fire; your fields are being stripped by foreigners right before you, laid waste as when overthrown by strangers.",
    Ind:"Negerimu menjadi sunyi sepi, kota-kotamu habis terbakar; di depan matamu orang-orang asing memakan hasil dari tanahmu. Sunyi sepi negeri itu seolah-olah ditunggangbalikkan orang asing."
  },
  {Bible:"Isaiah", Chapter:1, Verse:8, Page:1,
    Kor:"도성 시온이 외롭게 남아 있는 것이 포도원의 초막과 같으며, 참외밭의 원두막과 같고, 포위된 성읍과 같구나.",
    Chn:"仅存锡安城， 好像葡萄园的草棚， 瓜田的茅屋， 被围困的城邑。",
    Eng:"The Daughter of Zion is left like a shelter in a vineyard, like a hut in a field of melons, like a city under siege.",
    Ind:"Puteri Sion tertinggal sendirian seperti pondok di kebun anggur, seperti gubuk di kebun mentimun dan seperti kota yang terkepung."
  },
  {Bible:"Isaiah", Chapter:1, Verse:9, Page:1,
    Kor:"만군의 주님께서 우리 가운데 얼마라도 살아 남게 하시지 않으셨다면, 우리는 마치 소돔처럼 되고 고모라처럼 될 뻔하였다.",
    Chn:"若不是万军之耶和华给我们稍留余种， 我们早已像所多玛、蛾摩拉的样子了。",
    Eng:"Unless the LORD Almighty had left us some survivors, we would have become like Sodom, we would have been like Gomorrah.",
    Ind:"Seandainya TUHAN semesta alam tidak meninggalkan pada kita sedikit orang yang terlepas, kita sudah menjadi seperti Sodom, dan sama seperti Gomora."
  },
  {Bible:"Isaiah", Chapter:1, Verse:10, Page:1,
    Kor:"너희 소돔의 a통치자들아! 주님의 말씀을 들어라. 너희 고모라의 백성아! 우리 하나님의 b법에 귀를 기울여라. (a 또는 '사사들아' b 또는 '가르침' 또는 '교훈')",
    Chn:"你们这所多玛的官长啊， 要听耶和华的话！ 你们这蛾摩拉的百姓啊， 要侧耳听我们　神的训诲！",
    Eng:"Hear the word of the LORD, you rulers of Sodom; listen to the law of our God, you people of Gomorrah!",
    Ind:"Dengarlah firman TUHAN, hai pemimpin-pemimpin, manusia Sodom! Perhatikanlah pengajaran Allah kita, hai rakyat, manusia Gomora!"
  },
  {Bible:"Isaiah", Chapter:1, Verse:11, Page:1,
    Kor:"주님께서 말씀하신다. \"무엇하러 나에게 이 많은 제물을 바치느냐? 나는 이제 숫양의 번제물과 살진 짐승의 기름기가 지겹고, 나는 이제 수송아지와 어린 양과 숫염소의 피도 싫다.",
    Chn:"耶和华说： 你们所献的许多祭物与我何益呢？ 公绵羊的燔祭和肥畜的脂油， 我已经够了； 公牛的血，羊羔的血，公山羊的血， 我都不喜悦。",
    Eng:"\"The multitude of your sacrifices--what are they to me?\" says the LORD. \"I have more than enough of burnt offerings, of rams and the fat of fattened animals; I have no pleasure in the blood of bulls and lambs and goats.",
    Ind:"\"Untuk apa itu korbanmu yang banyak-banyak?\" firman TUHAN; \"Aku sudah jemu akan korban-korban bakaran berupa domba jantan dan akan lemak dari anak lembu gemukan; darah lembu jantan dan domba-domba dan kambing jantan tidak Kusukai."
  },
  {Bible:"Isaiah", Chapter:1, Verse:12, Page:1,
    Kor:"너희가 나의 앞에 보이러 오지만, 누가 너희에게 그것을 요구하였느냐? 나의 뜰만 밟을 뿐이다!",
    Chn:"你们来朝见我， 谁向你们讨这些， 使你们践踏我的院宇呢？",
    Eng:"When you come to appear before me, who has asked this of you, this trampling of my courts?",
    Ind:"Apabila kamu datang untuk menghadap di hadirat-Ku, siapakah yang menuntut itu dari padamu, bahwa kamu menginjak-injak pelataran Bait Suci-Ku?"
  },
  {Bible:"Isaiah", Chapter:1, Verse:13, Page:1,
    Kor:"다시는 헛된 제물을 가져 오지 말아라. 다 쓸모 없는 것들이다. 분향하는 것도 나에게는 역겹고, 초하루와 안식일과 대회로 모이는 것도 참을 수 없으며, 거룩한 집회를 열어 놓고 못된 짓도 함께 하는 것을, 내가 더 이상 견딜 수 없다.",
    Chn:"你们不要再献虚浮的供物。 香品是我所憎恶的； 月朔和安息日，并宣召的大会， 也是我所憎恶的； 作罪孽，又守严肃会， 我也不能容忍。",
    Eng:"Stop bringing meaningless offerings! Your incense is detestable to me. New Moons, Sabbaths and convocations--I cannot bear your evil assemblies.",
    Ind:"Jangan lagi membawa persembahanmu yang tidak sungguh, sebab baunya adalah kejijikan bagi-Ku. Kalau kamu merayakan bulan baru dan sabat atau mengadakan pertemuan-pertemuan, Aku tidak tahan melihatnya, karena perayaanmu itu penuh kejahatan."
  },
  {Bible:"Isaiah", Chapter:1, Verse:14, Page:1,
    Kor:"나는 정말로 너희의 초하루 행사와 정한 절기들이 싫다. 그것들은 오히려 나에게 짐이 될 뿐이다. 그것들을 짊어지기에는 내가 너무 지쳤다.",
    Chn:"你们的月朔和节期，我心里恨恶， 我都以为麻烦； 我担当，便不耐烦。",
    Eng:"Your New Moon festivals and your appointed feasts my soul hates. They have become a burden to me; I am weary of bearing them.",
    Ind:"Perayaan-perayaan bulan barumu dan pertemuan-pertemuanmu yang tetap, Aku benci melihatnya; semuanya itu menjadi beban bagi-Ku, Aku telah payah menanggungnya."
  },
  {Bible:"Isaiah", Chapter:1, Verse:15, Page:1,
    Kor:"너희가 팔을 벌리고 기도한다 하더라도, 나는 거들떠보지도 않겠다. 너희가 아무리 많이 기도를 한다 하여도 나는 듣지 않겠다. 너희의 손에는 피가 가득하다.",
    Chn:"你们举手祷告，我必遮眼不看； 就是你们多多地祈祷，我也不听。 你们的手都满了杀人的血。",
    Eng:"When you spread out your hands in prayer, I will hide my eyes from you; even if you offer many prayers, I will not listen. Your hands are full of blood;",
    Ind:"Apabila kamu menadahkan tanganmu untuk berdoa, Aku akan memalingkan muka-Ku, bahkan sekalipun kamu berkali-kali berdoa, Aku tidak akan mendengarkannya, sebab tanganmu penuh dengan darah."
  },
  {Bible:"Isaiah", Chapter:1, Verse:16, Page:1,
    Kor:"너희는 씻어라. 스스로 정결하게 하여라. 내가 보는 앞에서 너희의 악한 행실을 버려라. 악한 일을 그치고,",
    Chn:"你们要洗濯、自洁， 从我眼前除掉你们的恶行， 要止住作恶，",
    Eng:"wash and make yourselves clean. Take your evil deeds out of my sight! Stop doing wrong,",
    Ind:"Basuhlah, bersihkanlah dirimu, jauhkanlah perbuatan-perbuatanmu yang jahat dari depan mata-Ku. Berhentilah berbuat jahat,"
  },
  {Bible:"Isaiah", Chapter:1, Verse:17, Page:1,
    Kor:"옳은 일을 하는 것을 배워라. 정의를 찾아라. c억압받는 사람을 도와주어라. 고아의 송사를 변호하여 주고 과부의 송사를 변론하여 주어라.\" (c 또는 '억압하는 자들을 꾸짖어라')",
    Chn:"学习行善， 寻求公平， 解救受欺压的； 给孤儿伸冤， 为寡妇辨屈。",
    Eng:"learn to do right! Seek justice, encourage the oppressed. Defend the cause of the fatherless, plead the case of the widow.",
    Ind:"belajarlah berbuat baik; usahakanlah keadilan, kendalikanlah orang kejam; belalah hak anak-anak yatim, perjuangkanlah perkara janda-janda!"
  },
  {Bible:"Isaiah", Chapter:1, Verse:18, Page:1,
    Kor:"주님께서 말씀하신다. \"오너라! 우리가 서로 변론하자. 너희의 죄가 주홍빛과 같다 하여도 눈과 같이 희어질 것이며, 진홍빛과 같이 붉어도 양털과 같이 희어질 것이다.",
    Chn:"耶和华说： 你们来，我们彼此辩论。 你们的罪虽像朱红，必变成雪白； 虽红如丹颜，必白如羊毛。",
    Eng:"\"Come now, let us reason together,\" says the LORD. \"Though your sins are like scarlet, they shall be as white as snow; though they are red as crimson, they shall be like wool.",
    Ind:"Marilah, baiklah kita berperkara! --firman TUHAN--Sekalipun dosamu merah seperti kirmizi, akan menjadi putih seperti salju; sekalipun berwarna merah seperti kain kesumba, akan menjadi putih seperti bulu domba."
  },
  {Bible:"Isaiah", Chapter:1, Verse:19, Page:1,
    Kor:"너희가 기꺼이 하려는 마음으로 순종하면, 땅에서 나는 가장 좋은 소산을 먹을 것이다.",
    Chn:"你们若甘心听从， 必吃地上的美物，",
    Eng:"If you are willing and obedient, you will eat the best from the land;",
    Ind:"Jika kamu menurut dan mau mendengar, maka kamu akan memakan hasil baik dari negeri itu."
  },
  {Bible:"Isaiah", Chapter:1, Verse:20, Page:1,
    Kor:"그러나 너희가 거절하고 배반하면, 칼날이 너희를 삼킬 것이다.\" 이것은 주님께서 친히 하신 말씀이다.",
    Chn:"若不听从，反倒悖逆， 必被刀剑吞灭。 这是耶和华亲口说的。",
    Eng:"but if you resist and rebel, you will be devoured by the sword.\" For the mouth of the LORD has spoken.",
    Ind:"Tetapi jika kamu melawan dan memberontak, maka kamu akan dimakan oleh pedang.\" Sungguh, TUHAN yang mengucapkannya."
  },
  {Bible:"Isaiah", Chapter:1, Verse:21, Page:1,
    Kor:"<죄로 가득 찬 성읍> 그 신실하던 성읍이 어찌하여 창녀가 되었습니까? 그 안에 정의가 충만하고, 공의가 가득하더니, 이제는 살인자들이 판을 칩니다.",
    Chn:"可叹，忠信的城变为妓女！ 从前充满了公平， 公义居在其中， 现今却有凶手居住。",
    Eng:"See how the faithful city has become a harlot! She once was full of justice; righteousness used to dwell in her--but now murderers!",
    Ind:"Bagaimana ini, kota yang dahulu setia sekarang sudah menjadi sundal! Tadinya penuh keadilan dan di situ selalu diam kebenaran, tetapi sekarang penuh pembunuh."
  },
  {Bible:"Isaiah", Chapter:1, Verse:22, Page:1,
    Kor:"네가 만든 은은 불순물의 찌꺼기뿐이고, 네가 만든 가장 좋은 포도주에는 물이 섞여 있구나.",
    Chn:"你的银子变为渣滓； 你的酒用水搀对。",
    Eng:"Your silver has become dross, your choice wine is diluted with water.",
    Ind:"Perakmu tidak murni lagi dan arakmu bercampur air."
  },
  {Bible:"Isaiah", Chapter:1, Verse:23, Page:1,
    Kor:"너의 지도자들은 주님께 반역하는 자들이요, 도둑의 짝이다. 모두들 뇌물이나 좋아하고, 보수나 계산하면서 쫓아다니고, 고아의 송사를 변호하여 주지 않고, 과부의 하소연쯤은 귓전으로 흘리는구나.",
    Chn:"你的官长居心悖逆， 与盗贼作伴， 各都喜爱贿赂， 追求赃私。 他们不为孤儿伸冤； 寡妇的案件也不得呈到他们面前。",
    Eng:"Your rulers are rebels, companions of thieves; they all love bribes and chase after gifts. They do not defend the cause of the fatherless; the widow's case does not come before them.",
    Ind:"Para pemimpinmu adalah pemberontak dan bersekongkol dengan pencuri. Semuanya suka menerima suap dan mengejar sogok. Mereka tidak membela hak anak-anak yatim, dan perkara janda-janda tidak sampai kepada mereka."
  },
  {Bible:"Isaiah", Chapter:1, Verse:24, Page:1,
    Kor:"그러므로 주 곧 만군의 주, 이스라엘의 전능하신 분께서 말씀하신다. \"내가 나의 대적들에게 나의 분노를 쏟겠다. 내가 나의 원수들에게 보복하여 한을 풀겠다.",
    Chn:"因此，主—万军之耶和华、 以色列的大能者说： 哎！我要向我的对头雪恨， 向我的敌人报仇。",
    Eng:"Therefore the Lord, the LORD Almighty, the Mighty One of Israel, declares: \"Ah, I will get relief from my foes and avenge myself on my enemies.",
    Ind:"Sebab itu demikianlah firman Tuhan, TUHAN semesta alam, Yang Mahakuat pelindung Israel; \"Ha, Aku akan melampiaskan dendam-Ku kepada para lawan-Ku, dan melakukan pembalasan kepada para musuh-Ku."
  },
  {Bible:"Isaiah", Chapter:1, Verse:25, Page:1,
    Kor:"이제 다시 내가 너를 때려서라도 잿물로 찌꺼기를 깨끗이 씻어 내듯 너를 씻고, 너에게서 모든 불순물을 없애겠다.",
    Chn:"我必反手加在你身上， 炼尽你的渣滓， 除净你的杂质。",
    Eng:"I will turn my hand against you; I will thoroughly purge away your dross and remove all your impurities.",
    Ind:"Aku akan bertindak terhadap engkau: Aku akan memurnikan perakmu dengan garam soda, dan akan menyingkirkan segala timah dari padanya."
  },
  {Bible:"Isaiah", Chapter:1, Verse:26, Page:1,
    Kor:"옛날처럼 내가 사사들을 너에게 다시 세우고, 처음에 한 것처럼 슬기로운 지도자들을 너에게 보내 주겠다. 그런 다음에야 너를 '의의 성읍', '신실한 성읍'이라고 부르겠다.\"",
    Chn:"我也必复还你的审判官，像起初一样， 复还你的谋士，像起先一般。 然后，你必称为公义之城， 忠信之邑。",
    Eng:"I will restore your judges as in days of old, your counselors as at the beginning. Afterward you will be called the City of Righteousness, the Faithful City.\"",
    Ind:"Aku akan mengembalikan para hakimmu seperti dahulu, dan para penasihatmu seperti semula. Sesudah itu engkau akan disebutkan kota keadilan, kota yang setia.\""
  },
  {Bible:"Isaiah", Chapter:1, Verse:27, Page:1,
    Kor:"시온은 정의로 구속함을 받고, 회개한 백성은 공의로 구속함을 받을 것이다.",
    Chn:"锡安必因公平得蒙救赎； 其中归正的人必因公义得蒙救赎。",
    Eng:"Zion will be redeemed with justice, her penitent ones with righteousness.",
    Ind:"Sion akan Kubebaskan dengan penghakiman yang adil dan orang-orangnya yang bertobat akan Kubebaskan dengan tindakan yang benar."
  },
  {Bible:"Isaiah", Chapter:1, Verse:28, Page:1,
    Kor:"그러나 거역하는 자들과 죄인들은 모두 함께 패망하고, 주님을 버리는 자들은 모두 멸망을 당할 것이다.",
    Chn:"但悖逆的和犯罪的必一同败亡； 离弃耶和华的必致消灭。",
    Eng:"But rebels and sinners will both be broken, and those who forsake the LORD will perish.",
    Ind:"Tetapi orang-orang yang memberontak dan orang-orang berdosa akan dihancurkan bersama, dan orang-orang yang meninggalkan TUHAN akan habis lenyap."
  },
  {Bible:"Isaiah", Chapter:1, Verse:29, Page:1,
    Kor:"너희가 상수리나무 아래에서 우상 숭배를 즐겼으니, 수치를 당할 것이며, 너희가 동산에서 이방 신들을 즐겨 섬겼으므로 창피를 당할 것이다.",
    Chn:"那等人必因你们所喜爱的橡树抱愧； 你们必因所选择的园子蒙羞。",
    Eng:"\"You will be ashamed because of the sacred oaks in which you have delighted; you will be disgraced because of the gardens that you have chosen.",
    Ind:"Sungguh, kamu akan mendapat malu karena pohon-pohon keramat yang kamu inginkan; dan kamu akan tersipu-sipu karena taman-taman dewa yang kamu pilih."
  },
  {Bible:"Isaiah", Chapter:1, Verse:30, Page:1,
    Kor:"기어이 너희는 잎이 시든 상수리나무처럼 될 것이며, 물이 없는 동산과 같이 메마를 것이다.",
    Chn:"因为，你们必如叶子枯干的橡树， 好像无水浇灌的园子。",
    Eng:"You will be like an oak with fading leaves, like a garden without water.",
    Ind:"Sebab kamu akan seperti pohon keramat yang daunnya layu, dan seperti kebun yang kekurangan air."
  },
  {Bible:"Isaiah", Chapter:1, Verse:31, Page:1,
    Kor:"강한 자가 삼오라기와 같이 되고, 그가 한 일은 불티와 같이 될 것이다. 이 둘이 함께 불타도 꺼 줄 사람 하나 없을 것이다.",
    Chn:"有权势的必如麻瓤； 他的工作好像火星， 都要一同焚毁，无人扑灭。",
    Eng:"The mighty man will become tinder and his work a spark; both will burn together, with no one to quench the fire.\"",
    Ind:"Maka yang kuat menjadi seolah-olah kapas dan pekerjaannya menjadi seolah-olah bunga api; keduanya menimbulkan api dan tidak ada yang dapat memadamkan."
  },
]);
