// 요한일서 4장 · 1John 4
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1John",4,21);
BibleDB.add([
  {Bible:"1John", Chapter:4, Verse:1, Page:1, Kor:"<하나님의 영과 그리스도의 적대자의 영> 사랑하는 여러분, 어느 영이든지 다 믿지 말고, 그 영들이 하나님에게서 났는가를 시험하여 보십시오. 거짓 예언자가 세상에 많이 나타났기 때문입니다.", Chn:"", Eng:"Dear friends, do not believe every spirit, but test the spirits to see whether they are from God, because many false prophets have gone out into the world.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:2, Page:1, Kor:"여러분은 하나님의 영을 이것으로 알 수 있습니다. 곧 예수 그리스도께서 육신을 입고 오셨음을 시인하는 영은 다 하나님에게서 난 영입니다.", Chn:"", Eng:"This is how you can recognize the Spirit of God: Every spirit that acknowledges that Jesus Christ has come in the flesh is from God,", Ind:""},
  {Bible:"1John", Chapter:4, Verse:3, Page:1, Kor:"그러나 예수를 시인하지 않는 영은 다 하나님에게서 나지 않은 영입니다. 그것은 그리스도의 적대자의 영입니다. 여러분은 그 영이 올 것이라는 말을 들었습니다. 그런데 그 영이 세상에 벌써 와 있습니다.", Chn:"", Eng:"but every spirit that does not acknowledge Jesus is not from God. This is the spirit of the antichrist, which you have heard is coming and even now is already in the world.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:4, Page:1, Kor:"자녀 된 이 여러분, 여러분은 하나님에게서 난 사람들이며, 여러분은 그 거짓 예언자들을 이겼습니다. 여러분 안에 계신 분이 세상에 있는 자보다 크시기 때문입니다.", Chn:"", Eng:"You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:5, Page:1, Kor:"그들은 세상에서 났습니다. 그런 까닭에 그들은 세상에 속한 것을 말하고, 세상은 그들의 말을 듣습니다.", Chn:"", Eng:"They are from the world and therefore speak from the viewpoint of the world, and the world listens to them.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:6, Page:1, Kor:"우리는 하나님에게서 났습니다. 하나님을 아는 사람은 우리의 말을 듣고, 하나님에게서 나지 아니한 사람은 우리의 말을 듣지 아니합니다. 이것으로 우리는 진리의 영과 미혹의 영을 알아봅니다.", Chn:"", Eng:"We are from God, and whoever knows God listens to us; but whoever is not from God does not listen to us. This is how we recognize the Spirit of truth and the spirit of falsehood.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:7, Page:1, Kor:"<하나님은 사랑이시다> ○사랑하는 여러분, 서로 사랑합시다. 사랑은 하나님에게서 난 것입니다. 사랑하는 사람은 다 하나님에게서 났고, 하나님을 압니다.", Chn:"", Eng:"Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:8, Page:1, Kor:"사랑하지 않는 사람은 하나님을 알지 못합니다. 하나님은 사랑이시기 때문입니다.", Chn:"", Eng:"Whoever does not love does not know God, because God is love.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:9, Page:1, Kor:"하나님의 사랑이 우리에게 이렇게 드러났으니, 곧 하나님이 자기 외아들을 세상에 보내주셔서 우리로 하여금 그로 말미암아 살게 해주신 것입니다.", Chn:"", Eng:"This is how God showed his love among us: He sent his one and only Son into the world that we might live through him.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:10, Page:1, Kor:"사랑은 이 사실에 있으니, 곧 우리가 하나님을 사랑한 것이 아니라, 하나님이 우리를 사랑하셔서, 자기 아들을 보내어 우리의 죄를 위하여 화목제물이 되게 하신 것입니다.", Chn:"", Eng:"This is love: not that we loved God, but that he loved us and sent his Son as an atoning sacrifice for our sins.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:11, Page:1, Kor:"사랑하는 여러분, 하나님께서 이렇게까지 우리를 사랑하셨으니, 우리도 서로 사랑해야 합니다.", Chn:"", Eng:"Dear friends, since God so loved us, we also ought to love one another.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:12, Page:1, Kor:"지금까지 하나님을 본 사람은 없습니다. 그러나 우리가 서로 사랑하면, 하나님이 우리 가운데 계시고, 또 하나님의 사랑이 우리 가운데서 완성된 것입니다.", Chn:"", Eng:"No one has ever seen God; but if we love one another, God lives in us and his love is made complete in us.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:13, Page:1, Kor:"○하나님이 우리에게 자기 영을 나누어 주셨습니다. 이것으로 우리가 하나님 안에 있고, 또 하나님이 우리 안에 계시다는 것을 우리는 압니다.", Chn:"", Eng:"We know that we live in him and he in us, because he has given us of his Spirit.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:14, Page:1, Kor:"우리는 아버지께서 아들을 세상의 구주로 보내신 것을 보았고, 또 그것을 증언합니다.", Chn:"", Eng:"And we have seen and testify that the Father has sent his Son to be the Savior of the world.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:15, Page:1, Kor:"누구든지 예수를 하나님의 아들로 시인하면, 하나님이 그 사람 안에 계시고, 그 사람은 하나님 안에 있습니다.", Chn:"", Eng:"If anyone acknowledges that Jesus is the Son of God, God lives in him and he in God.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:16, Page:1, Kor:"우리는 하나님이 우리에게 베푸시는 사랑을 알았고, 또 믿었습니다. ○하나님은 사랑이십니다. 사랑 안에 있는 사람은 하나님 안에 있고 하나님도 그 사람 안에 계십니다.", Chn:"", Eng:"And so we know and rely on the love God has for us. God is love. Whoever lives in love lives in God, and God in him.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:17, Page:1, Kor:"사랑이 우리에게서 완성되었다는 사실은 이 점에 있으니, 곧 우리로 하여금 심판 날에 담대함을 가지게 하려는 것입니다. 우리가 이렇게 담대해지는 것은, 그리스도께서 사신 대로 또한 우리도 이 세상에서 그렇게 살기 때문입니다.", Chn:"", Eng:"In this way, love is made complete among us so that we will have confidence on the day of judgment, because in this world we are like him.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:18, Page:1, Kor:"사랑에는 두려움이 없습니다. 완전한 사랑은 두려움을 내쫓습니다. 두려움은 징벌과 관련이 있습니다. 두려워하는 사람은 아직 사랑을 완성하지 못한 사람입니다.", Chn:"", Eng:"There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:19, Page:1, Kor:"우리가 a사랑하는 것은 하나님이 우리를 먼저 사랑하셨기 때문입니다.(a 다른 고대 사본들에는 '그를' 또는 '하나님을'이 첨가됨)", Chn:"", Eng:"We love because he first loved us.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:20, Page:1, Kor:"누가 하나님을 사랑한다고 하면서, 자기 b형제자매를 미워하면, 그는 거짓말쟁이입니다. 보이는 자기 b형제자매를 사랑하지 않는 사람이 보이지 않는 하나님을 사랑할 수 없습니다.(b 그, '형제')", Chn:"", Eng:"If anyone says, \"I love God,\" yet hates his brother, he is a liar. For anyone who does not love his brother, whom he has seen, cannot love God, whom he has not seen.", Ind:""},
  {Bible:"1John", Chapter:4, Verse:21, Page:1, Kor:"하나님을 사랑하는 사람은 자기 b형제자매도 사랑해야 합니다. 우리는 이 계명을 주님에게서 받았습니다.(b 그, '형제')", Chn:"", Eng:"And he has given us this command: Whoever loves God must also love his brother.", Ind:""},
]);
