// 요한복음 15장 · John 15
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("John",15,27);
BibleDB.add([
  {Bible:"John", Chapter:15, Verse:1, Page:1, Kor:"", Chn:"", Eng:"\"I am the true vine, and my Father is the gardener.", Ind:""},
  {Bible:"John", Chapter:15, Verse:2, Page:1, Kor:"", Chn:"", Eng:"He cuts off every branch in me that bears no fruit, while every branch that does bear fruit he prunes so that it will be even more fruitful.", Ind:""},
  {Bible:"John", Chapter:15, Verse:3, Page:1, Kor:"", Chn:"", Eng:"You are already clean because of the word I have spoken to you.", Ind:""},
  {Bible:"John", Chapter:15, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Remain in me, and I will remain in you. No branch can bear fruit by itself; it must remain in the vine. Neither can you bear fruit unless you remain in me.", Ind:""},
  {Bible:"John", Chapter:15, Verse:5, Page:1, Kor:"", Chn:"", Eng:"\"I am the vine; you are the branches. If a man remains in me and I in him, he will bear much fruit; apart from me you can do nothing.", Ind:""},
  {Bible:"John", Chapter:15, Verse:6, Page:1, Kor:"", Chn:"", Eng:"If anyone does not remain in me, he is like a branch that is thrown away and withers; such branches are picked up, thrown into the fire and burned.", Ind:""},
  {Bible:"John", Chapter:15, Verse:7, Page:1, Kor:"", Chn:"", Eng:"If you remain in me and my words remain in you, ask whatever you wish, and it will be given you.", Ind:""},
  {Bible:"John", Chapter:15, Verse:8, Page:1, Kor:"", Chn:"", Eng:"This is to my Father's glory, that you bear much fruit, showing yourselves to be my disciples.", Ind:""},
  {Bible:"John", Chapter:15, Verse:9, Page:1, Kor:"", Chn:"", Eng:"\"As the Father has loved me, so have I loved you. Now remain in my love.", Ind:""},
  {Bible:"John", Chapter:15, Verse:10, Page:1, Kor:"", Chn:"", Eng:"If you obey my commands, you will remain in my love, just as I have obeyed my Father's commands and remain in his love.", Ind:""},
  {Bible:"John", Chapter:15, Verse:11, Page:1, Kor:"", Chn:"", Eng:"I have told you this so that my joy may be in you and that your joy may be complete.", Ind:""},
  {Bible:"John", Chapter:15, Verse:12, Page:1, Kor:"", Chn:"", Eng:"My command is this: Love each other as I have loved you.", Ind:""},
  {Bible:"John", Chapter:15, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Greater love has no one than this, that he lay down his life for his friends.", Ind:""},
  {Bible:"John", Chapter:15, Verse:14, Page:1, Kor:"", Chn:"", Eng:"You are my friends if you do what I command.", Ind:""},
  {Bible:"John", Chapter:15, Verse:15, Page:1, Kor:"", Chn:"", Eng:"I no longer call you servants, because a servant does not know his master's business. Instead, I have called you friends, for everything that I learned from my Father I have made known to you.", Ind:""},
  {Bible:"John", Chapter:15, Verse:16, Page:1, Kor:"", Chn:"", Eng:"You did not choose me, but I chose you and appointed you to go and bear fruit--fruit that will last. Then the Father will give you whatever you ask in my name.", Ind:""},
  {Bible:"John", Chapter:15, Verse:17, Page:1, Kor:"", Chn:"", Eng:"This is my command: Love each other.", Ind:""},
  {Bible:"John", Chapter:15, Verse:18, Page:1, Kor:"", Chn:"", Eng:"\"If the world hates you, keep in mind that it hated me first.", Ind:""},
  {Bible:"John", Chapter:15, Verse:19, Page:1, Kor:"", Chn:"", Eng:"If you belonged to the world, it would love you as its own. As it is, you do not belong to the world, but I have chosen you out of the world. That is why the world hates you.", Ind:""},
  {Bible:"John", Chapter:15, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Remember the words I spoke to you: 'No servant is greater than his master.' If they persecuted me, they will persecute you also. If they obeyed my teaching, they will obey yours also.", Ind:""},
  {Bible:"John", Chapter:15, Verse:21, Page:1, Kor:"", Chn:"", Eng:"They will treat you this way because of my name, for they do not know the One who sent me.", Ind:""},
  {Bible:"John", Chapter:15, Verse:22, Page:1, Kor:"", Chn:"", Eng:"If I had not come and spoken to them, they would not be guilty of sin. Now, however, they have no excuse for their sin.", Ind:""},
  {Bible:"John", Chapter:15, Verse:23, Page:1, Kor:"", Chn:"", Eng:"He who hates me hates my Father as well.", Ind:""},
  {Bible:"John", Chapter:15, Verse:24, Page:1, Kor:"", Chn:"", Eng:"If I had not done among them what no one else did, they would not be guilty of sin. But now they have seen these miracles, and yet they have hated both me and my Father.", Ind:""},
  {Bible:"John", Chapter:15, Verse:25, Page:1, Kor:"", Chn:"", Eng:"But this is to fulfill what is written in their Law: 'They hated me without reason.'", Ind:""},
  {Bible:"John", Chapter:15, Verse:26, Page:1, Kor:"", Chn:"", Eng:"\"When the Counselor comes, whom I will send to you from the Father, the Spirit of truth who goes out from the Father, he will testify about me.", Ind:""},
  {Bible:"John", Chapter:15, Verse:27, Page:1, Kor:"", Chn:"", Eng:"And you also must testify, for you have been with me from the beginning.", Ind:""},
]);
