// 요한복음 9장 · John 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("John",9,41);
BibleDB.add([
  {Bible:"John", Chapter:9, Verse:1, Page:1, Kor:"", Chn:"", Eng:"As he went along, he saw a man blind from birth.", Ind:""},
  {Bible:"John", Chapter:9, Verse:2, Page:1, Kor:"", Chn:"", Eng:"His disciples asked him, \"Rabbi, who sinned, this man or his parents, that he was born blind?\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:3, Page:1, Kor:"", Chn:"", Eng:"\"Neither this man nor his parents sinned,\" said Jesus, \"but this happened so that the work of God might be displayed in his life.", Ind:""},
  {Bible:"John", Chapter:9, Verse:4, Page:1, Kor:"", Chn:"", Eng:"As long as it is day, we must do the work of him who sent me. Night is coming, when no one can work.", Ind:""},
  {Bible:"John", Chapter:9, Verse:5, Page:1, Kor:"", Chn:"", Eng:"While I am in the world, I am the light of the world.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:6, Page:1, Kor:"", Chn:"", Eng:"Having said this, he spit on the ground, made some mud with the saliva, and put it on the man's eyes.", Ind:""},
  {Bible:"John", Chapter:9, Verse:7, Page:1, Kor:"", Chn:"", Eng:"\"Go,\" he told him, \"wash in the Pool of Siloam\" (this word means Sent). So the man went and washed, and came home seeing.", Ind:""},
  {Bible:"John", Chapter:9, Verse:8, Page:1, Kor:"", Chn:"", Eng:"His neighbors and those who had formerly seen him begging asked, \"Isn't this the same man who used to sit and beg?\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Some claimed that he was. Others said, \"No, he only looks like him.\" But he himself insisted, \"I am the man.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:10, Page:1, Kor:"", Chn:"", Eng:"\"How then were your eyes opened?\" they demanded.", Ind:""},
  {Bible:"John", Chapter:9, Verse:11, Page:1, Kor:"", Chn:"", Eng:"He replied, \"The man they call Jesus made some mud and put it on my eyes. He told me to go to Siloam and wash. So I went and washed, and then I could see.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:12, Page:1, Kor:"", Chn:"", Eng:"\"Where is this man?\" they asked him. \"I don't know,\" he said.", Ind:""},
  {Bible:"John", Chapter:9, Verse:13, Page:1, Kor:"", Chn:"", Eng:"They brought to the Pharisees the man who had been blind.", Ind:""},
  {Bible:"John", Chapter:9, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Now the day on which Jesus had made the mud and opened the man's eyes was a Sabbath.", Ind:""},
  {Bible:"John", Chapter:9, Verse:15, Page:1, Kor:"", Chn:"", Eng:"Therefore the Pharisees also asked him how he had received his sight. \"He put mud on my eyes,\" the man replied, \"and I washed, and now I see.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:16, Page:1, Kor:"", Chn:"", Eng:"Some of the Pharisees said, \"This man is not from God, for he does not keep the Sabbath.\" But others asked, \"How can a sinner do such miraculous signs?\" So they were divided.", Ind:""},
  {Bible:"John", Chapter:9, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Finally they turned again to the blind man, \"What have you to say about him? It was your eyes he opened.\" The man replied, \"He is a prophet.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:18, Page:1, Kor:"", Chn:"", Eng:"The Jews still did not believe that he had been blind and had received his sight until they sent for the man's parents.", Ind:""},
  {Bible:"John", Chapter:9, Verse:19, Page:1, Kor:"", Chn:"", Eng:"\"Is this your son?\" they asked. \"Is this the one you say was born blind? How is it that now he can see?\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:20, Page:1, Kor:"", Chn:"", Eng:"\"We know he is our son,\" the parents answered, \"and we know he was born blind.", Ind:""},
  {Bible:"John", Chapter:9, Verse:21, Page:1, Kor:"", Chn:"", Eng:"But how he can see now, or who opened his eyes, we don't know. Ask him. He is of age; he will speak for himself.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:22, Page:1, Kor:"", Chn:"", Eng:"His parents said this because they were afraid of the Jews, for already the Jews had decided that anyone who acknowledged that Jesus was the Christ would be put out of the synagogue.", Ind:""},
  {Bible:"John", Chapter:9, Verse:23, Page:1, Kor:"", Chn:"", Eng:"That was why his parents said, \"He is of age; ask him.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:24, Page:1, Kor:"", Chn:"", Eng:"A second time they summoned the man who had been blind. \"Give glory to God,\" they said. \"We know this man is a sinner.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:25, Page:1, Kor:"", Chn:"", Eng:"He replied, \"Whether he is a sinner or not, I don't know. One thing I do know. I was blind but now I see!\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:26, Page:1, Kor:"", Chn:"", Eng:"Then they asked him, \"What did he do to you? How did he open your eyes?\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:27, Page:1, Kor:"", Chn:"", Eng:"He answered, \"I have told you already and you did not listen. Why do you want to hear it again? Do you want to become his disciples, too?\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Then they hurled insults at him and said, \"You are this fellow's disciple! We are disciples of Moses!", Ind:""},
  {Bible:"John", Chapter:9, Verse:29, Page:1, Kor:"", Chn:"", Eng:"We know that God spoke to Moses, but as for this fellow, we don't even know where he comes from.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:30, Page:1, Kor:"", Chn:"", Eng:"The man answered, \"Now that is remarkable! You don't know where he comes from, yet he opened my eyes.", Ind:""},
  {Bible:"John", Chapter:9, Verse:31, Page:1, Kor:"", Chn:"", Eng:"We know that God does not listen to sinners. He listens to the godly man who does his will.", Ind:""},
  {Bible:"John", Chapter:9, Verse:32, Page:1, Kor:"", Chn:"", Eng:"Nobody has ever heard of opening the eyes of a man born blind.", Ind:""},
  {Bible:"John", Chapter:9, Verse:33, Page:1, Kor:"", Chn:"", Eng:"If this man were not from God, he could do nothing.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:34, Page:1, Kor:"", Chn:"", Eng:"To this they replied, \"You were steeped in sin at birth; how dare you lecture us!\" And they threw him out.", Ind:""},
  {Bible:"John", Chapter:9, Verse:35, Page:1, Kor:"", Chn:"", Eng:"Jesus heard that they had thrown him out, and when he found him, he said, \"Do you believe in the Son of Man?\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:36, Page:1, Kor:"", Chn:"", Eng:"\"Who is he, sir?\" the man asked. \"Tell me so that I may believe in him.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:37, Page:1, Kor:"", Chn:"", Eng:"Jesus said, \"You have now seen him; in fact, he is the one speaking with you.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:38, Page:1, Kor:"", Chn:"", Eng:"Then the man said, \"Lord, I believe,\" and he worshiped him.", Ind:""},
  {Bible:"John", Chapter:9, Verse:39, Page:1, Kor:"", Chn:"", Eng:"Jesus said, \"For judgment I have come into this world, so that the blind will see and those who see will become blind.\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:40, Page:1, Kor:"", Chn:"", Eng:"Some Pharisees who were with him heard him say this and asked, \"What? Are we blind too?\"", Ind:""},
  {Bible:"John", Chapter:9, Verse:41, Page:1, Kor:"", Chn:"", Eng:"Jesus said, \"If you were blind, you would not be guilty of sin; but now that you claim you can see, your guilt remains.", Ind:""},
]);
