// 요한복음 5장 · John 5
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("John",5,47);
BibleDB.add([
  {Bible:"John", Chapter:5, Verse:1, Page:1, Kor:"", Chn:"", Eng:"Some time later, Jesus went up to Jerusalem for a feast of the Jews.", Ind:""},
  {Bible:"John", Chapter:5, Verse:2, Page:1, Kor:"", Chn:"", Eng:"Now there is in Jerusalem near the Sheep Gate a pool, which in Aramaic is called Bethesda and which is surrounded by five covered colonnades.", Ind:""},
  {Bible:"John", Chapter:5, Verse:3, Page:1, Kor:"", Chn:"", Eng:"Here a great number of disabled people used to lie--the blind, the lame, the paralyzed.", Ind:""},
  {Bible:"John", Chapter:5, Verse:4, Page:1, Kor:"", Chn:"", Eng:"", Ind:""},
  {Bible:"John", Chapter:5, Verse:5, Page:1, Kor:"", Chn:"", Eng:"One who was there had been an invalid for thirty-eight years.", Ind:""},
  {Bible:"John", Chapter:5, Verse:6, Page:1, Kor:"", Chn:"", Eng:"When Jesus saw him lying there and learned that he had been in this condition for a long time, he asked him, \"Do you want to get well?\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:7, Page:1, Kor:"", Chn:"", Eng:"\"Sir,\" the invalid replied, \"I have no one to help me into the pool when the water is stirred. While I am trying to get in, someone else goes down ahead of me.\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Then Jesus said to him, \"Get up! Pick up your mat and walk.\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:9, Page:1, Kor:"", Chn:"", Eng:"At once the man was cured; he picked up his mat and walked. The day on which this took place was a Sabbath,", Ind:""},
  {Bible:"John", Chapter:5, Verse:10, Page:1, Kor:"", Chn:"", Eng:"and so the Jews said to the man who had been healed, \"It is the Sabbath; the law forbids you to carry your mat.\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:11, Page:1, Kor:"", Chn:"", Eng:"But he replied, \"The man who made me well said to me, 'Pick up your mat and walk.'\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:12, Page:1, Kor:"", Chn:"", Eng:"So they asked him, \"Who is this fellow who told you to pick it up and walk?\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:13, Page:1, Kor:"", Chn:"", Eng:"The man who was healed had no idea who it was, for Jesus had slipped away into the crowd that was there.", Ind:""},
  {Bible:"John", Chapter:5, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Later Jesus found him at the temple and said to him, \"See, you are well again. Stop sinning or something worse may happen to you.\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:15, Page:1, Kor:"", Chn:"", Eng:"The man went away and told the Jews that it was Jesus who had made him well.", Ind:""},
  {Bible:"John", Chapter:5, Verse:16, Page:1, Kor:"", Chn:"", Eng:"So, because Jesus was doing these things on the Sabbath, the Jews persecuted him.", Ind:""},
  {Bible:"John", Chapter:5, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Jesus said to them, \"My Father is always at his work to this very day, and I, too, am working.\"", Ind:""},
  {Bible:"John", Chapter:5, Verse:18, Page:1, Kor:"", Chn:"", Eng:"For this reason the Jews tried all the harder to kill him; not only was he breaking the Sabbath, but he was even calling God his own Father, making himself equal with God.", Ind:""},
  {Bible:"John", Chapter:5, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Jesus gave them this answer: \"I tell you the truth, the Son can do nothing by himself; he can do only what he sees his Father doing, because whatever the Father does the Son also does.", Ind:""},
  {Bible:"John", Chapter:5, Verse:20, Page:1, Kor:"", Chn:"", Eng:"For the Father loves the Son and shows him all he does. Yes, to your amazement he will show him even greater things than these.", Ind:""},
  {Bible:"John", Chapter:5, Verse:21, Page:1, Kor:"", Chn:"", Eng:"For just as the Father raises the dead and gives them life, even so the Son gives life to whom he is pleased to give it.", Ind:""},
  {Bible:"John", Chapter:5, Verse:22, Page:1, Kor:"", Chn:"", Eng:"Moreover, the Father judges no one, but has entrusted all judgment to the Son,", Ind:""},
  {Bible:"John", Chapter:5, Verse:23, Page:1, Kor:"", Chn:"", Eng:"that all may honor the Son just as they honor the Father. He who does not honor the Son does not honor the Father, who sent him.", Ind:""},
  {Bible:"John", Chapter:5, Verse:24, Page:1, Kor:"", Chn:"", Eng:"\"I tell you the truth, whoever hears my word and believes him who sent me has eternal life and will not be condemned; he has crossed over from death to life.", Ind:""},
  {Bible:"John", Chapter:5, Verse:25, Page:1, Kor:"", Chn:"", Eng:"I tell you the truth, a time is coming and has now come when the dead will hear the voice of the Son of God and those who hear will live.", Ind:""},
  {Bible:"John", Chapter:5, Verse:26, Page:1, Kor:"", Chn:"", Eng:"For as the Father has life in himself, so he has granted the Son to have life in himself.", Ind:""},
  {Bible:"John", Chapter:5, Verse:27, Page:1, Kor:"", Chn:"", Eng:"And he has given him authority to judge because he is the Son of Man.", Ind:""},
  {Bible:"John", Chapter:5, Verse:28, Page:1, Kor:"", Chn:"", Eng:"\"Do not be amazed at this, for a time is coming when all who are in their graves will hear his voice", Ind:""},
  {Bible:"John", Chapter:5, Verse:29, Page:1, Kor:"", Chn:"", Eng:"and come out--those who have done good will rise to live, and those who have done evil will rise to be condemned.", Ind:""},
  {Bible:"John", Chapter:5, Verse:30, Page:1, Kor:"", Chn:"", Eng:"By myself I can do nothing; I judge only as I hear, and my judgment is just, for I seek not to please myself but him who sent me.", Ind:""},
  {Bible:"John", Chapter:5, Verse:31, Page:1, Kor:"", Chn:"", Eng:"\"If I testify about myself, my testimony is not valid.", Ind:""},
  {Bible:"John", Chapter:5, Verse:32, Page:1, Kor:"", Chn:"", Eng:"There is another who testifies in my favor, and I know that his testimony about me is valid.", Ind:""},
  {Bible:"John", Chapter:5, Verse:33, Page:1, Kor:"", Chn:"", Eng:"\"You have sent to John and he has testified to the truth.", Ind:""},
  {Bible:"John", Chapter:5, Verse:34, Page:1, Kor:"", Chn:"", Eng:"Not that I accept human testimony; but I mention it that you may be saved.", Ind:""},
  {Bible:"John", Chapter:5, Verse:35, Page:1, Kor:"", Chn:"", Eng:"John was a lamp that burned and gave light, and you chose for a time to enjoy his light.", Ind:""},
  {Bible:"John", Chapter:5, Verse:36, Page:1, Kor:"", Chn:"", Eng:"\"I have testimony weightier than that of John. For the very work that the Father has given me to finish, and which I am doing, testifies that the Father has sent me.", Ind:""},
  {Bible:"John", Chapter:5, Verse:37, Page:1, Kor:"", Chn:"", Eng:"And the Father who sent me has himself testified concerning me. You have never heard his voice nor seen his form,", Ind:""},
  {Bible:"John", Chapter:5, Verse:38, Page:1, Kor:"", Chn:"", Eng:"nor does his word dwell in you, for you do not believe the one he sent.", Ind:""},
  {Bible:"John", Chapter:5, Verse:39, Page:1, Kor:"", Chn:"", Eng:"You diligently study the Scriptures because you think that by them you possess eternal life. These are the Scriptures that testify about me,", Ind:""},
  {Bible:"John", Chapter:5, Verse:40, Page:1, Kor:"", Chn:"", Eng:"yet you refuse to come to me to have life.", Ind:""},
  {Bible:"John", Chapter:5, Verse:41, Page:1, Kor:"", Chn:"", Eng:"\"I do not accept praise from men,", Ind:""},
  {Bible:"John", Chapter:5, Verse:42, Page:1, Kor:"", Chn:"", Eng:"but I know you. I know that you do not have the love of God in your hearts.", Ind:""},
  {Bible:"John", Chapter:5, Verse:43, Page:1, Kor:"", Chn:"", Eng:"I have come in my Father's name, and you do not accept me; but if someone else comes in his own name, you will accept him.", Ind:""},
  {Bible:"John", Chapter:5, Verse:44, Page:1, Kor:"", Chn:"", Eng:"How can you believe if you accept praise from one another, yet make no effort to obtain the praise that comes from the only God?", Ind:""},
  {Bible:"John", Chapter:5, Verse:45, Page:1, Kor:"", Chn:"", Eng:"\"But do not think I will accuse you before the Father. Your accuser is Moses, on whom your hopes are set.", Ind:""},
  {Bible:"John", Chapter:5, Verse:46, Page:1, Kor:"", Chn:"", Eng:"If you believed Moses, you would believe me, for he wrote about me.", Ind:""},
  {Bible:"John", Chapter:5, Verse:47, Page:1, Kor:"", Chn:"", Eng:"But since you do not believe what he wrote, how are you going to believe what I say?\"", Ind:""},
]);
