// 출애굽기 26장 · Exodus 26
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Exodus",26,37);
BibleDB.add([
  {Bible:"Exodus", Chapter:26, Verse:1, Page:1,
    Kor:"<성막(출 36:8-38)> \"열 폭으로 성막을 만들어라. 그 천은, 가늘게 꼰 모시 실과 청색 실과 자주색 실과 홍색 실로, 그룹을 정교하게 수놓아 짠 것이라야 한다.",
    Chn:"「你要用十幅幔子做帐幕。这些幔子要用捻的细麻和蓝色、紫色、朱红色线制造，并用巧匠的手工绣上基路伯。",
    Eng:"\"Make the tabernacle with ten curtains of finely twisted linen and blue, purple and scarlet yarn, with cherubim worked into them by a skilled craftsman.",
    Ind:"\"Kemah Suci itu haruslah kaubuat dari sepuluh tenda dari lenan halus yang dipintal benangnya dan dari kain ungu tua, kain ungu muda dan kain kirmizi; dengan ada kerubnya, buatan ahli tenun, haruslah kaubuat semuanya itu."
  },
  {Bible:"Exodus", Chapter:26, Verse:2, Page:1,
    Kor:"각 폭의 길이는 스물여덟 자로 하고, 너비는 넉 자로 하되, 폭마다 그 치수를 모두 같게 하여야 한다.",
    Chn:"每幅幔子要长二十八肘，宽四肘，幔子都要一样的尺寸。",
    Eng:"All the curtains are to be the same size--twenty-eight cubits long and four cubits wide.",
    Ind:"Panjang tiap-tiap tenda haruslah dua puluh delapan hasta dan lebar tiap-tiap tenda empat hasta: segala tenda itu harus sama ukurannya."
  },
  {Bible:"Exodus", Chapter:26, Verse:3, Page:1,
    Kor:"먼저 다섯 폭을 옆으로 나란히 이어 한 벌을 만들고, 또 다른 다섯 폭도 옆으로 나란히 이어 한 벌을 만들어야 한다.",
    Chn:"这五幅幔子要幅幅相连；那五幅幔子也要幅幅相连。",
    Eng:"Join five of the curtains together, and do the same with the other five.",
    Ind:"Lima dari tenda itu haruslah dirangkap menjadi satu, dan yang lima lagi juga harus dirangkap menjadi satu."
  },
  {Bible:"Exodus", Chapter:26, Verse:4, Page:1,
    Kor:"그리고 나서, 나란히 이은 천의 한쪽 가장자리의 폭에 청색 실로 고를 만들고, 나란히 이은 다른 한쪽 가장자리의 폭에도 이와 같이 하여, 서로 맞물릴 수 있게 하여야 한다.",
    Chn:"在这相连的幔子末幅边上要做蓝色的钮扣；在那相连的幔子末幅边上也要照样做。",
    Eng:"Make loops of blue material along the edge of the end curtain in one set, and do the same with the end curtain in the other set.",
    Ind:"Pada rangkapan yang pertama, di tepi satu tenda yang di ujung, haruslah engkau membuat sosok-sosok kain ungu tua dan demikian juga di tepi satu tenda yang paling ujung pada rangkapan yang kedua."
  },
  {Bible:"Exodus", Chapter:26, Verse:5, Page:1,
    Kor:"서로 맞물릴 두 벌 끝 폭 가장자리에 만들 고의 수는 각각 쉰 개이다. 그 고들을 서로 마주보게 하여라.",
    Chn:"要在这相连的幔子上做五十个钮扣；在那相连的幔子上也做五十个钮扣，都要两两相对。",
    Eng:"Make fifty loops on one curtain and fifty loops on the end curtain of the other set, with the loops opposite each other.",
    Ind:"Lima puluh sosok harus kaubuat pada tenda yang satu dan lima puluh sosok pada tenda yang di ujung pada rangkapan yang kedua, sehingga sosok-sosok itu tepat berhadapan satu sama lain."
  },
  {Bible:"Exodus", Chapter:26, Verse:6, Page:1,
    Kor:"그리고 금으로 갈고리 쉰 개를 만들어야 한다. 이 갈고리로 두 벌 천을 서로 이어, 한 성막을 이루게 하여라.",
    Chn:"又要做五十个金钩，用钩使幔子相连，这才成了一个帐幕。",
    Eng:"Then make fifty gold clasps and use them to fasten the curtains together so that the tabernacle is a unit.",
    Ind:"Dan haruslah engkau membuat lima puluh kaitan emas dan menyambung tenda-tenda Kemah Suci yang satu dengan yang lain dengan memakai kaitan itu, sehingga menjadi satu."
  },
  {Bible:"Exodus", Chapter:26, Verse:7, Page:1,
    Kor:"○성막 위에 덮을 천막은 염소 털로 짠 열한 폭 천으로 만들어야 한다.",
    Chn:"「你要用山羊毛织十一幅幔子，作为帐幕以上的罩棚。",
    Eng:"\"Make curtains of goat hair for the tent over the tabernacle--eleven altogether.",
    Ind:"Juga haruslah engkau membuat tenda-tenda dari bulu kambing menjadi atap kemah yang menudungi Kemah Suci, sebelas tenda harus kaubuat."
  },
  {Bible:"Exodus", Chapter:26, Verse:8, Page:1,
    Kor:"각 폭의 길이는 서른 자로 하고, 너비는 넉 자로 하되, 열한 폭의 치수를 모두 같게 하여야 한다.",
    Chn:"每幅幔子要长三十肘，宽四肘；十一幅幔子都要一样的尺寸。",
    Eng:"All eleven curtains are to be the same size--thirty cubits long and four cubits wide.",
    Ind:"Panjang tiap-tiap tenda harus tiga puluh hasta dan lebar tiap-tiap tenda empat hasta: yang sebelas tenda itu harus sama ukurannya."
  },
  {Bible:"Exodus", Chapter:26, Verse:9, Page:1,
    Kor:"다섯 폭을 따로 잇고, 나머지 여섯 폭도 따로 이어야 한다. 그리고 여섯 번째 폭은 천막 앞쪽으로 반을 접어서 올려야 한다.",
    Chn:"要把五幅幔子连成一幅，又把六幅幔子连成一幅，这第六幅幔子要在罩棚的前面折上去。",
    Eng:"Join five of the curtains together into one set and the other six into another set. Fold the sixth curtain double at the front of the tent.",
    Ind:"Lima dari tenda itu haruslah kausambung dengan tersendiri, dan enam dari tenda itu dengan tersendiri, dan tenda yang keenam haruslah kaulipat dua, di sebelah depan kemah itu."
  },
  {Bible:"Exodus", Chapter:26, Verse:10, Page:1,
    Kor:"다섯 폭으로 이은 천의 가장자리에 고 쉰 개를 만들고, 여섯 폭을 이은 천의 가장자리에도 고 쉰 개를 만들어라.",
    Chn:"在这相连的幔子末幅边上要做五十个钮扣；在那相连的幔子末幅边上也做五十个钮扣。",
    Eng:"Make fifty loops along the edge of the end curtain in one set and also along the edge of the end curtain in the other set.",
    Ind:"Haruslah engkau membuat lima puluh sosok pada rangkapan yang pertama di tepi satu tenda yang di ujung dan lima puluh sosok di tepi satu tenda pada rangkapan yang kedua."
  },
  {Bible:"Exodus", Chapter:26, Verse:11, Page:1,
    Kor:"또 놋쇠 갈고리 쉰 개를 만들고, 그 갈고리를 양쪽 고에 마주 걸어서, 한 천막을 만들어라.",
    Chn:"又要做五十个铜钩，钩在钮扣中，使罩棚连成一个。",
    Eng:"Then make fifty bronze clasps and put them in the loops to fasten the tent together as a unit.",
    Ind:"Haruslah engkau membuat lima puluh kaitan tembaga dan memasukkan kaitan itu ke dalam sosok-sosok dan menyambung tenda-tenda kemah itu, supaya menjadi satu."
  },
  {Bible:"Exodus", Chapter:26, Verse:12, Page:1,
    Kor:"그리고 여분으로 남아 있는 천막 반 폭은 성막 뒤로 늘어뜨려라.",
    Chn:"罩棚的幔子所余那垂下来的半幅幔子，要垂在帐幕的后头。",
    Eng:"As for the additional length of the tent curtains, the half curtain that is left over is to hang down at the rear of the tabernacle.",
    Ind:"Mengenai bagian yang berjuntai itu, yang berlebih pada tenda kemah itu, haruslah setengah dari tenda yang berlebih itu berjuntai di sebelah belakang Kemah Suci."
  },
  {Bible:"Exodus", Chapter:26, Verse:13, Page:1,
    Kor:"천막 폭 너비에서 양쪽으로 한 자씩 남아 있는 것은, 성막 양 옆으로 늘어뜨려서 성막을 덮게 하여라.",
    Chn:"罩棚的幔子所余长的，这边一肘，那边一肘，要垂在帐幕的两旁，遮盖帐幕。",
    Eng:"The tent curtains will be a cubit longer on both sides; what is left will hang over the sides of the tabernacle so as to cover it.",
    Ind:"Sehasta di sebelah sini dan sehasta di sebelah sana pada bagian yang berlebih pada panjang tenda-tenda kemah itu haruslah berjuntai pada sisi-sisi Kemah Suci, di sebelah sini dan di sebelah sana untuk menudunginya."
  },
  {Bible:"Exodus", Chapter:26, Verse:14, Page:1,
    Kor:"○천막 덮개를 두 개 더 만들어라. 하나는 붉게 물들인 숫양 가죽으로 만들고, 그 위에 덮을 또 다른 덮개는 돌고래 가죽으로 만들어라.",
    Chn:"又要用染红的公羊皮做罩棚的盖；再用海狗皮做一层罩棚上的顶盖。",
    Eng:"Make for the tent a covering of ram skins dyed red, and over that a covering of hides of sea cows.",
    Ind:"Juga haruslah engkau membuat untuk kemah itu tudung dari kulit domba jantan yang diwarnai merah, dan tudung dari kulit lumba-lumba di atasnya lagi."
  },
  {Bible:"Exodus", Chapter:26, Verse:15, Page:1,
    Kor:"○성막을 세울 널빤지는 아카시아 나무로 만들어라.",
    Chn:"「你要用皂荚木做帐幕的竖板。",
    Eng:"\"Make upright frames of acacia wood for the tabernacle.",
    Ind:"Haruslah engkau membuat untuk Kemah Suci papan dari kayu penaga yang berdiri tegak,"
  },
  {Bible:"Exodus", Chapter:26, Verse:16, Page:1,
    Kor:"각 널빤지는, 길이를 열 자, 너비를 한 자 반으로 하고,",
    Chn:"每块要长十肘，宽一肘半；",
    Eng:"Each frame is to be ten cubits long and a cubit and a half wide,",
    Ind:"sepuluh hasta panjangnya satu papan dan satu setengah hasta lebarnya tiap-tiap papan."
  },
  {Bible:"Exodus", Chapter:26, Verse:17, Page:1,
    Kor:"널빤지마다 거기에 촉꽂이 두 개를 만들어, 서로 잇대어 세워라. 너는 성막의 모든 널빤지를 이와 같이 만들어라.",
    Chn:"每块必有两榫相对。帐幕一切的板都要这样做。",
    Eng:"with two projections set parallel to each other. Make all the frames of the tabernacle in this way.",
    Ind:"Tiap-tiap papan harus ada dua pasaknya yang disengkang satu sama lain; demikianlah harus kauperbuat dengan segala papan Kemah Suci."
  },
  {Bible:"Exodus", Chapter:26, Verse:18, Page:1,
    Kor:"성막의 남쪽 벽면에 세울 널빤지는 스무 개를 만들어라.",
    Chn:"帐幕的南面要做板二十块。",
    Eng:"Make twenty frames for the south side of the tabernacle",
    Ind:"Haruslah engkau membuat papan-papan untuk Kemah Suci, dua puluh papan pada sebelah selatan."
  },
  {Bible:"Exodus", Chapter:26, Verse:19, Page:1,
    Kor:"그 스무 개나 되는 널빤지 밑에 받칠 밑받침은 은으로 마흔 개를 만들어라. 널빤지마다 그 밑에 촉꽂이를 꽂을 밑받침을 두 개씩 만들어라.",
    Chn:"在这二十块板底下要做四十个带卯的银座，两卯接这块板上的两榫，两卯接那块板上的两榫。",
    Eng:"and make forty silver bases to go under them--two bases for each frame, one under each projection.",
    Ind:"Dan haruslah kaubuat empat puluh alas perak di bawah kedua puluh papan itu, dua alas di bawah satu papan untuk kedua pasaknya, dan seterusnya dua alas di bawah setiap papan untuk kedua pasaknya."
  },
  {Bible:"Exodus", Chapter:26, Verse:20, Page:1,
    Kor:"그리고 그 반대쪽인 성막의 북쪽 벽면에 세울 널빤지는 스무 개를 만들어라.",
    Chn:"帐幕第二面，就是北面，也要做板二十块",
    Eng:"For the other side, the north side of the tabernacle, make twenty frames",
    Ind:"Juga untuk sisi yang kedua dari Kemah Suci, pada sebelah utara, kaubuatlah dua puluh papan"
  },
  {Bible:"Exodus", Chapter:26, Verse:21, Page:1,
    Kor:"밑받침 마흔 개를 은으로 만들되, 널빤지마다 그 밑에 받칠 밑받침을 두 개씩 만들어라.",
    Chn:"和带卯的银座四十个；这板底下有两卯，那板底下也有两卯。",
    Eng:"and forty silver bases--two under each frame.",
    Ind:"dengan empat puluh alas peraknya: dua alas di bawah satu papan dan seterusnya dua alas di bawah setiap papan."
  },
  {Bible:"Exodus", Chapter:26, Verse:22, Page:1,
    Kor:"성막 뒤쪽인 서쪽 벽면에 세울 널빤지는 여섯 개를 만들어라.",
    Chn:"帐幕的后面，就是西面，要做板六块。",
    Eng:"Make six frames for the far end, that is, the west end of the tabernacle,",
    Ind:"Untuk sisi belakang Kemah Suci, pada sebelah barat, haruslah kaubuat enam papan."
  },
  {Bible:"Exodus", Chapter:26, Verse:23, Page:1,
    Kor:"성막 뒤쪽의 두 모퉁이에 세울 널빤지는 두 개를 만들어라.",
    Chn:"帐幕后面的拐角要做板两块。",
    Eng:"and make two frames for the corners at the far end.",
    Ind:"Dua papan haruslah kaubuat untuk sudut Kemah Suci, di sisi belakang."
  },
  {Bible:"Exodus", Chapter:26, Verse:24, Page:1,
    Kor:"두 모퉁이에 세울 이 널빤지들은 밑에서부터 꼭대기까지 겹으로 세워서, 완전히 한 고리로 연결하여라. 그 두 모퉁이를 다 이와 같이 하여라.",
    Chn:"板的下半截要双的，上半截要整的，直顶到第一个环子；两块都要这样做两个拐角。",
    Eng:"At these two corners they must be double from the bottom all the way to the top, and fitted into a single ring; both shall be like that.",
    Ind:"Kedua papan itu haruslah kembar pasaknya di sebelah bawah dan seperti itu juga kembar pasaknya di sebelah atas, di dekat gelang yang satu itu; demikianlah harus kedua papan itu; haruslah itu merupakan kedua sudutnya."
  },
  {Bible:"Exodus", Chapter:26, Verse:25, Page:1,
    Kor:"그러면 그것은 여덟 개의 널빤지에, 널빤지마다 그 밑에 밑받침이 두 개씩이니, 은 밑받침은 모두 열여섯 개가 될 것이다.",
    Chn:"必有八块板和十六个带卯的银座；这板底下有两卯，那板底下也有两卯。",
    Eng:"So there will be eight frames and sixteen silver bases--two under each frame.",
    Ind:"Jadi harus ada delapan papan dengan alas peraknya: enam belas alas; dua alas di bawah satu papan dan seterusnya dua alas di bawah setiap papan."
  },
  {Bible:"Exodus", Chapter:26, Verse:26, Page:1,
    Kor:"○아카시아 나무로 가로다지를 만들어라. 성막 한쪽 옆 벽의 널빤지에 다섯 개,",
    Chn:"「你要用皂荚木作闩：为帐幕这面的板作五闩，",
    Eng:"\"Also make crossbars of acacia wood: five for the frames on one side of the tabernacle,",
    Ind:"Juga haruslah kaubuat kayu lintang dari kayu penaga: lima untuk papan-papan pada sisi yang satu dari Kemah Suci,"
  },
  {Bible:"Exodus", Chapter:26, Verse:27, Page:1,
    Kor:"성막의 다른 한쪽 옆 벽의 널빤지에 다섯 개, 서쪽에 해당하는 성막 뒤 벽의 널빤지에 다섯 개를 만들어라.",
    Chn:"为帐幕那面的板做五闩，又为帐幕后面的板做五闩。",
    Eng:"five for those on the other side, and five for the frames on the west, at the far end of the tabernacle.",
    Ind:"lima kayu lintang untuk papan-papan pada sisi yang kedua dari Kemah Suci, dan lima kayu lintang untuk papan-papan pada sisi Kemah Suci yang merupakan sisi belakangnya, pada sebelah barat."
  },
  {Bible:"Exodus", Chapter:26, Verse:28, Page:1,
    Kor:"널빤지들의 가운데에 끼울 중간 가로다지는 이쪽 끝에서 저쪽 끝까지 미치게 하여야 한다.",
    Chn:"板腰间的中闩要从这一头通到那一头。",
    Eng:"The center crossbar is to extend from end to end at the middle of the frames.",
    Ind:"Dan kayu lintang yang di tengah, di tengah-tengah papan-papan itu, haruslah melintang terus dari ujung ke ujung."
  },
  {Bible:"Exodus", Chapter:26, Verse:29, Page:1,
    Kor:"널빤지에는 금을 입히고, 가로다지를 꿸 고리를 금으로 만들어라. 또 가로다지에도 금을 입혀라.",
    Chn:"板要用金子包裹，又要做板上的金环套闩；闩也要用金子包裹。",
    Eng:"Overlay the frames with gold and make gold rings to hold the crossbars. Also overlay the crossbars with gold.",
    Ind:"Papan-papan itu haruslah kausalut dengan emas, gelang-gelang itu haruslah kaubuat dari emas sebagai tempat memasukkan kayu-kayu lintang itu, dan kayu-kayu lintang itu haruslah kausalut dengan emas."
  },
  {Bible:"Exodus", Chapter:26, Verse:30, Page:1,
    Kor:"성막은 내가 이 산에서 너에게 보여 준 규격대로 세워라.",
    Chn:"要照着在山上指示你的样式立起帐幕。",
    Eng:"\"Set up the tabernacle according to the plan shown you on the mountain.",
    Ind:"Kemudian haruslah kaudirikan Kemah Suci sesuai dengan rancangan yang telah ditunjukkan kepadamu di atas gunung itu."
  },
  {Bible:"Exodus", Chapter:26, Verse:31, Page:1,
    Kor:"○청색 실과 자주색 실과 홍색 실과 가늘게 꼰 모시 실로 휘장을 짜고, 그 위에 그룹을 정교하게 수를 놓아라.",
    Chn:"「你要用蓝色、紫色、朱红色线，和捻的细麻织幔子，以巧匠的手工绣上基路伯。",
    Eng:"\"Make a curtain of blue, purple and scarlet yarn and finely twisted linen, with cherubim worked into it by a skilled craftsman.",
    Ind:"Haruslah kaubuat tabir dari kain ungu tua, dan kain ungu muda, kain kirmizi dan lenan halus yang dipintal benangnya; haruslah dibuat dengan ada kerubnya, buatan ahli tenun."
  },
  {Bible:"Exodus", Chapter:26, Verse:32, Page:1,
    Kor:"휘장을 아카시아 나무로 만든 네 기둥 위에 드리워야 하는데, 기둥마다 거기에 모두 금을 입히고, 금 갈고리를 달아야 하며, 이 기둥들을 은으로 만든 네 밑받침 위에 세워야 한다.",
    Chn:"要把幔子挂在四根包金的皂荚木柱子上，柱子上当有金钩，柱子安在四个带卯的银座上。",
    Eng:"Hang it with gold hooks on four posts of acacia wood overlaid with gold and standing on four silver bases.",
    Ind:"Haruslah engkau menggantungkannya pada empat tiang dari kayu penaga, yang disalut dengan emas, dengan ada kaitannya dari emas, berdasarkan empat alas perak."
  },
  {Bible:"Exodus", Chapter:26, Verse:33, Page:1,
    Kor:"너는 그 휘장을 갈고리에 걸어서 늘어뜨리고, 그 휘장 뒤에 a증거궤를 들여 놓아라. 그 휘장이 너희에게 성소와 지성소를 구별할 수 있게 할 것이다.",
    Chn:"要使幔子垂在钩子下，把法柜抬进幔子内；这幔子要将圣所和至圣所隔开。",
    Eng:"Hang the curtain from the clasps and place the ark of the Testimony behind the curtain. The curtain will separate the Holy Place from the Most Holy Place.",
    Ind:"Haruslah tabir itu kaugantungkan pada kaitan penyambung tenda itu dan haruslah kaubawa tabut hukum ke sana, ke belakang tabir itu, sehingga tabir itu menjadi pemisah bagimu antara tempat kudus dan tempat maha kudus."
  },
  {Bible:"Exodus", Chapter:26, Verse:34, Page:1,
    Kor:"지성소에 있는 a증거궤는 b속죄판으로 덮어라.(a 또는 '법궤' b 또는 '속죄소' 또는 '시은좌')",
    Chn:"又要把施恩座安在至圣所内的法柜上，",
    Eng:"Put the atonement cover on the ark of the Testimony in the Most Holy Place.",
    Ind:"Tutup pendamaian itu haruslah kauletakkan di atas tabut hukum di dalam tempat maha kudus."
  },
  {Bible:"Exodus", Chapter:26, Verse:35, Page:1,
    Kor:"휘장 앞으로는 북쪽에 상을 차려 놓고, 그 상의 맞은쪽인 성막의 남쪽에는 등잔대를 놓아라.",
    Chn:"把桌子安在幔子外帐幕的北面；把灯台安在帐幕的南面，彼此相对。",
    Eng:"Place the table outside the curtain on the north side of the tabernacle and put the lampstand opposite it on the south side.",
    Ind:"Meja itu haruslah kautaruh di depan tabir itu, dan kandil itu berhadapan dengan meja itu pada sisi selatan dari Kemah Suci, dan meja itu haruslah kautempatkan pada sisi utara."
  },
  {Bible:"Exodus", Chapter:26, Verse:36, Page:1,
    Kor:"○청색 실과 자주색 실과 홍색 실과 가늘게 꼰 모시 실로 수를 놓아, 장막 어귀를 가리는 막을 짜라.",
    Chn:"「你要拿蓝色、紫色、朱红色线，和捻的细麻，用绣花的手工织帐幕的门帘。",
    Eng:"\"For the entrance to the tent make a curtain of blue, purple and scarlet yarn and finely twisted linen--the work of an embroiderer.",
    Ind:"Juga haruslah kaubuat tirai untuk pintu kemah itu dari kain ungu tua, kain ungu muda, kain kirmizi dan lenan halus yang dipintal benangnya: tenunan yang berwarna-warna."
  },
  {Bible:"Exodus", Chapter:26, Verse:37, Page:1,
    Kor:"아카시아 나무 기둥 다섯을 만들어서, 거기에 금을 입히고, 금 갈고리를 만들어 붙여서, 이 막을 치는 데 쓰도록 하여라. 그리고 밑받침 다섯은 놋쇠를 부어 만들어라.\"",
    Chn:"要用皂荚木为帘子做五根柱子，用金子包裹。柱子上当有金钩；又要为柱子用铜铸造五个带卯的座。」",
    Eng:"Make gold hooks for this curtain and five posts of acacia wood overlaid with gold. And cast five bronze bases for them.",
    Ind:"Haruslah kaubuat lima tiang dari kayu penaga untuk tirai itu dan kausalutlah itu dengan emas, dengan ada kaitannya dari emas, dan untuk itu haruslah kautuang lima alas dari tembaga.\""
  },
]);
