// 출애굽기 34장 · Exodus 34
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Exodus",34,35);
BibleDB.add([
  {Bible:"Exodus", Chapter:34, Verse:1, Page:1, Kor:"", Chn:"", Eng:"The LORD said to Moses, \"Chisel out two stone tablets like the first ones, and I will write on them the words that were on the first tablets, which you broke.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:2, Page:1, Kor:"", Chn:"", Eng:"Be ready in the morning, and then come up on Mount Sinai. Present yourself to me there on top of the mountain.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:3, Page:1, Kor:"", Chn:"", Eng:"No one is to come with you or be seen anywhere on the mountain; not even the flocks and herds may graze in front of the mountain.\"", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:4, Page:1, Kor:"", Chn:"", Eng:"So Moses chiseled out two stone tablets like the first ones and went up Mount Sinai early in the morning, as the LORD had commanded him; and he carried the two stone tablets in his hands.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Then the LORD came down in the cloud and stood there with him and proclaimed his name, the LORD.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:6, Page:1, Kor:"", Chn:"", Eng:"And he passed in front of Moses, proclaiming, \"The LORD, the LORD, the compassionate and gracious God, slow to anger, abounding in love and faithfulness,", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:7, Page:1, Kor:"", Chn:"", Eng:"maintaining love to thousands, and forgiving wickedness, rebellion and sin. Yet he does not leave the guilty unpunished; he punishes the children and their children for the sin of the fathers to the third and fourth generation.\"", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Moses bowed to the ground at once and worshiped.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:9, Page:1, Kor:"", Chn:"", Eng:"\"O Lord, if I have found favor in your eyes,\" he said, \"then let the Lord go with us. Although this is a stiff-necked people, forgive our wickedness and our sin, and take us as your inheritance.\"", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said: \"I am making a covenant with you. Before all your people I will do wonders never before done in any nation in all the world. The people you live among will see how awesome is the work that I, the LORD, will do for you.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Obey what I command you today. I will drive out before you the Amorites, Canaanites, Hittites, Perizzites, Hivites and Jebusites.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:12, Page:1, Kor:"", Chn:"", Eng:"Be careful not to make a treaty with those who live in the land where you are going, or they will be a snare among you.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Break down their altars, smash their sacred stones and cut down their Asherah poles.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Do not worship any other god, for the LORD, whose name is Jealous, is a jealous God.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:15, Page:1, Kor:"", Chn:"", Eng:"\"Be careful not to make a treaty with those who live in the land; for when they prostitute themselves to their gods and sacrifice to them, they will invite you and you will eat their sacrifices.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:16, Page:1, Kor:"", Chn:"", Eng:"And when you choose some of their daughters as wives for your sons and those daughters prostitute themselves to their gods, they will lead your sons to do the same.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:17, Page:1, Kor:"", Chn:"", Eng:"\"Do not make cast idols.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:18, Page:1, Kor:"", Chn:"", Eng:"\"Celebrate the Feast of Unleavened Bread. For seven days eat bread made without yeast, as I commanded you. Do this at the appointed time in the month of Abib, for in that month you came out of Egypt.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:19, Page:1, Kor:"", Chn:"", Eng:"\"The first offspring of every womb belongs to me, including all the firstborn males of your livestock, whether from herd or flock.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Redeem the firstborn donkey with a lamb, but if you do not redeem it, break its neck. Redeem all your firstborn sons. \"No one is to appear before me empty-handed.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:21, Page:1, Kor:"", Chn:"", Eng:"\"Six days you shall labor, but on the seventh day you shall rest; even during the plowing season and harvest you must rest.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:22, Page:1, Kor:"", Chn:"", Eng:"\"Celebrate the Feast of Weeks with the firstfruits of the wheat harvest, and the Feast of Ingathering at the turn of the year.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:23, Page:1, Kor:"", Chn:"", Eng:"Three times a year all your men are to appear before the Sovereign LORD, the God of Israel.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:24, Page:1, Kor:"", Chn:"", Eng:"I will drive out nations before you and enlarge your territory, and no one will covet your land when you go up three times each year to appear before the LORD your God.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:25, Page:1, Kor:"", Chn:"", Eng:"\"Do not offer the blood of a sacrifice to me along with anything containing yeast, and do not let any of the sacrifice from the Passover Feast remain until morning.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:26, Page:1, Kor:"", Chn:"", Eng:"\"Bring the best of the firstfruits of your soil to the house of the LORD your God. \"Do not cook a young goat in its mother's milk.\"", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said to Moses, \"Write down these words, for in accordance with these words I have made a covenant with you and with Israel.\"", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Moses was there with the LORD forty days and forty nights without eating bread or drinking water. And he wrote on the tablets the words of the covenant--the Ten Commandments.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:29, Page:1, Kor:"", Chn:"", Eng:"When Moses came down from Mount Sinai with the two tablets of the Testimony in his hands, he was not aware that his face was radiant because he had spoken with the LORD.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:30, Page:1, Kor:"", Chn:"", Eng:"When Aaron and all the Israelites saw Moses, his face was radiant, and they were afraid to come near him.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:31, Page:1, Kor:"", Chn:"", Eng:"But Moses called to them; so Aaron and all the leaders of the community came back to him, and he spoke to them.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:32, Page:1, Kor:"", Chn:"", Eng:"Afterward all the Israelites came near him, and he gave them all the commands the LORD had given him on Mount Sinai.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:33, Page:1, Kor:"", Chn:"", Eng:"When Moses finished speaking to them, he put a veil over his face.", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:34, Page:1, Kor:"", Chn:"", Eng:"But whenever he entered the LORD'S presence to speak with him, he removed the veil until he came out. And when he came out and told the Israelites what he had been commanded,", Ind:""},
  {Bible:"Exodus", Chapter:34, Verse:35, Page:1, Kor:"", Chn:"", Eng:"they saw that his face was radiant. Then Moses would put the veil back over his face until he went in to speak with the LORD.", Ind:""},
]);
