// 출애굽기 17장 · Exodus 17
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Exodus",17,16);
BibleDB.add([
  {Bible:"Exodus", Chapter:17, Verse:1, Page:1, Kor:"<바위에서 물이 솟다(민 20:1-1c> 이스라엘 자손의 온 회중은 신 광야를 떠나서, 주님의 명령대로 진을 옮겨 가면서 이동하였다. 그들은 르비딤에 진을 쳤는데, 거기에는 백성이 마실 물이 없었다.", Chn:"", Eng:"The whole Israelite community set out from the Desert of Sin, traveling from place to place as the LORD commanded. They camped at Rephidim, but there was no water for the people to drink.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:2, Page:1, Kor:"백성이 모세에게 마실 물을 달라고 대들었다. 이에 모세가 \"당신들은 어찌하여 나에게 대드십니까? 어찌하여 주님을 시험하십니까?\" 하고 책망하였다.", Chn:"", Eng:"So they quarreled with Moses and said, \"Give us water to drink.\" Moses replied, \"Why do you quarrel with me? Why do you put the LORD to the test?\"", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:3, Page:1, Kor:"그러나 거기에 있는 백성은 몹시 목이 말라서, 모세를 원망하며, 모세가 왜 그들을 이집트에서 데려왔느냐고, 그들과 그들의 자식들과 그들이 먹이는 집짐승들을 목말라 죽게 할 작정이냐고 하면서 대들었다.", Chn:"", Eng:"But the people were thirsty for water there, and they grumbled against Moses. They said, \"Why did you bring us up out of Egypt to make us and our children and livestock die of thirst?\"", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:4, Page:1, Kor:"○모세가 주님께 부르짖었다. \"이 백성을 제가 어떻게 해야 합니까? 그들은 지금이라도 곧 저를 돌로 쳐서 죽이려고 합니다.\"", Chn:"", Eng:"Then Moses cried out to the LORD, \"What am I to do with these people? They are almost ready to stone me.\"", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:5, Page:1, Kor:"주님께서 모세에게 말씀하셨다. \"너는 이스라엘 장로들을 데리고, 이 백성보다 앞서서 가거라. 그리고 나일 강을 친 그 지팡이를 손에 들고 가거라.", Chn:"", Eng:"The LORD answered Moses, \"Walk on ahead of the people. Take with you some of the elders of Israel and take in your hand the staff with which you struck the Nile, and go.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:6, Page:1, Kor:"이제 내가 저기 호렙 산 바위 위에서 너의 앞에 서겠으니, 너는 그 바위를 쳐라. 그러면 거기에서 이 백성이 마실 물이 터져 나올 것이다.\" 모세가, 이스라엘 장로들이 보는 앞에서, 하나님이 시키신 대로 하였다.", Chn:"", Eng:"I will stand there before you by the rock at Horeb. Strike the rock, and water will come out of it for the people to drink.\" So Moses did this in the sight of the elders of Israel.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:7, Page:1, Kor:"이스라엘 자손이 거기에서 주님께 대들었다고 해서, 사람들은 그 곳의 이름을 a므리바라고도 하고, 또 거기에서 \"주님께서 우리 가운데 계시는가, 안 계시는가?\" 하면서 주님을 시험하였다고 해서, 그 곳의 이름을 b맛사라고도 한다.(a '다툼' b '시험함')", Chn:"", Eng:"And he called the place Massah and Meribah because the Israelites quarreled and because they tested the LORD saying, \"Is the LORD among us or not?\"", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:8, Page:1, Kor:"<아말렉 사람들과 싸우다> ○그 때에 아말렉 사람들이 몰려와서, 르비딤에 있는 이스라엘 사람을 공격하였다.", Chn:"", Eng:"The Amalekites came and attacked the Israelites at Rephidim.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:9, Page:1, Kor:"모세가 여호수아에게 말하였다. \"장정들을 뽑아서 아말렉과 싸우러 나가시오. 내일 내가 하나님의 지팡이를 손에 들고, 산꼭대기에 서 있겠소.\"", Chn:"", Eng:"Moses said to Joshua, \"Choose some of our men and go out to fight the Amalekites. Tomorrow I will stand on top of the hill with the staff of God in my hands.\"", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:10, Page:1, Kor:"여호수아는 모세가 그에게 말한 대로 아말렉과 싸우러 나가고, 모세와 아론과 훌은 언덕 위로 올라갔다.", Chn:"", Eng:"So Joshua fought the Amalekites as Moses had ordered, and Moses, Aaron and Hur went to the top of the hill.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:11, Page:1, Kor:"모세가 그의 팔을 들면 이스라엘이 더욱 우세하고, 그가 팔을 내리면 아말렉이 더욱 우세하였다.", Chn:"", Eng:"As long as Moses held up his hands, the Israelites were winning, but whenever he lowered his hands, the Amalekites were winning.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:12, Page:1, Kor:"모세가 피곤하여 팔을 들고 있을 수 없게 되니, 아론과 훌이 돌을 가져 와서 모세를 앉게 하고, 그들이 각각 그 양쪽에 서서 그의 팔을 붙들어 올렸다. 해가 질 때까지 그가 팔을 내리지 않았다.", Chn:"", Eng:"When Moses' hands grew tired, they took a stone and put it under him and he sat on it. Aaron and Hur held his hands up--one on one side, one on the other--so that his hands remained steady till sunset.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:13, Page:1, Kor:"이렇게 해서, 여호수아는 아말렉과 그 백성을 칼로 무찔렀다.", Chn:"", Eng:"So Joshua overcame the Amalekite army with the sword.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:14, Page:1, Kor:"○그 때에 주님께서 모세에게 말씀하셨다. \"너는 오늘의 승리를 책에 기록하여 사람들이 잊지 않도록 하고, 여호수아에게는, '내가 아말렉을 이 세상에서 완전히 없애서 아무도 아말렉을 기억하지 못하게 하겠다'고 한 나의 결심을 일러주어라.\"", Chn:"", Eng:"Then the LORD said to Moses, \"Write this on a scroll as something to be remembered and make sure that Joshua hears it, because I will completely blot out the memory of Amalek from under heaven.\"", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:15, Page:1, Kor:"모세는 거기에 제단을 쌓고 그 곳 이름을 c '여호와닛시'라 하고,(c 히, '아도나이 닛시(주님은 나의 깃발)')", Chn:"", Eng:"Moses built an altar and called it The LORD is my Banner.", Ind:""},
  {Bible:"Exodus", Chapter:17, Verse:16, Page:1, Kor:"\"d주님의 깃발을 높이 들어라. 주님께서 대대로 아말렉과 싸우실 것이다\" 하고 외쳤다.(d 또는 '한 손이 주님의 보좌 위에 있으니' 또는 '주님의 보좌를 치려고 손이 들렸으니'. 히브리어 본문이 불확실함)", Chn:"", Eng:"He said, \"For hands were lifted up to the throne of the LORD. The LORD will be at war against the Amalekites from generation to generation.\"", Ind:""},
]);
