// 출애굽기 37장 · Exodus 37
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Exodus",37,29);
BibleDB.add([
  {Bible:"Exodus", Chapter:37, Verse:1, Page:1,
    Kor:"<언약궤를 만들다(출 25:10-22)> 브살렐은 아카시아 나무로, 길이가 두 자 반, 너비가 한 자 반, 높이가 한 자 반인 궤를 만들었다.",
    Chn:"比撒列用皂荚木做柜，长二肘半，宽一肘半，高一肘半。",
    Eng:"Bezalel made the ark of acacia wood--two and a half cubits long, a cubit and a half wide, and a cubit and a half high.",
    Ind:"Bezaleel membuat tabut itu dari kayu penaga, dua setengah hasta panjangnya, satu setengah hasta lebarnya, dan satu setengah hasta tingginya."
  },
  {Bible:"Exodus", Chapter:37, Verse:2, Page:1,
    Kor:"순금으로 그 안팎을 입히고, 그 둘레에는 금테를 둘렀다.",
    Chn:"里外包上精金，四围镶上金牙边，",
    Eng:"He overlaid it with pure gold, both inside and out, and made a gold molding around it.",
    Ind:"Disalutnyalah itu dengan emas murni, dari dalam dan dari luar, dan dibuatnyalah bingkai emas sekelilingnya."
  },
  {Bible:"Exodus", Chapter:37, Verse:3, Page:1,
    Kor:"금고리 네 개를 만들어서, 그 밑 네 모퉁이에 달았는데, 한쪽에 고리 두 개, 다른 한쪽에 고리 두 개를 달았다.",
    Chn:"又铸四个金环，安在柜的四脚上：这边两环，那边两环。",
    Eng:"He cast four gold rings for it and fastened them to its four feet, with two rings on one side and two rings on the other.",
    Ind:"Dituangnyalah empat gelang emas untuk tabut itu, pada keempat penjurunya, yaitu dua gelang pada rusuknya yang satu dan dua gelang pada rusuknya yang kedua."
  },
  {Bible:"Exodus", Chapter:37, Verse:4, Page:1,
    Kor:"아카시아 나무로 채를 만들어서 금을 입히고,",
    Chn:"用皂荚木做两根杠，用金包裹。",
    Eng:"Then he made poles of acacia wood and overlaid them with gold.",
    Ind:"Dibuatnyalah kayu pengusung dari kayu penaga dan disalutnyalah itu dengan emas."
  },
  {Bible:"Exodus", Chapter:37, Verse:5, Page:1,
    Kor:"이 채를 궤의 양쪽 고리에 끼워서 궤를 멜 수 있게 하였다.",
    Chn:"把杠穿在柜旁的环内，以便抬柜。",
    Eng:"And he inserted the poles into the rings on the sides of the ark to carry it.",
    Ind:"Dan dimasukkannyalah kayu pengusung itu ke dalam gelang yang pada rusuk tabut itu, supaya tabut dapat diangkut."
  },
  {Bible:"Exodus", Chapter:37, Verse:6, Page:1,
    Kor:"○그는 순금으로, 길이가 두 자 반이요 너비가 한 자 반인 속죄판을 만들었다.",
    Chn:"用精金做施恩座，长二肘半，宽一肘半。",
    Eng:"He made the atonement cover of pure gold--two and a half cubits long and a cubit and a half wide.",
    Ind:"Dibuatnyalah tutup pendamaian dari emas murni, dua setengah hasta panjangnya dan satu setengah hasta lebarnya."
  },
  {Bible:"Exodus", Chapter:37, Verse:7, Page:1,
    Kor:"그리고 금을 두들겨서 두 그룹을 만들고, 그것들을 속죄판의 양쪽 끝에 각각 자리잡게 하였다.",
    Chn:"用金子锤出两个基路伯来，安在施恩座的两头，",
    Eng:"Then he made two cherubim out of hammered gold at the ends of the cover.",
    Ind:"Dibuatnyalah dua kerub dari emas, dari emas tempaan dibuatnya itu, pada kedua ujung tutup pendamaian itu,"
  },
  {Bible:"Exodus", Chapter:37, Verse:8, Page:1,
    Kor:"그룹 하나는 이쪽 끝에, 또 다른 하나는 맞은쪽 끝에 자리잡게 만들되, 속죄판과 그 양쪽 끝에 있는 그룹이 한 덩이가 되도록 만들었다.",
    Chn:"这头做一个基路伯，那头做一个基路伯，二基路伯接连一块，在施恩座的两头。",
    Eng:"He made one cherub on one end and the second cherub on the other; at the two ends he made them of one piece with the cover.",
    Ind:"satu kerub pada ujung sebelah sini dan satu kerub pada ujung sebelah sana; seiras dengan tutup pendamaian itu dibuatnya kerub itu pada kedua ujungnya."
  },
  {Bible:"Exodus", Chapter:37, Verse:9, Page:1,
    Kor:"그룹들은 날개를 위로 펴서 그 날개로 속죄판을 덮게 하였고, 그룹의 얼굴들은 속죄판 쪽으로 서로 마주 보게 하였다.",
    Chn:"二基路伯高张翅膀，遮掩施恩座；基路伯是脸对脸，朝着施恩座。",
    Eng:"The cherubim had their wings spread upward, overshadowing the cover with them. The cherubim faced each other, looking toward the cover.",
    Ind:"Kerub-kerub itu mengembangkan kedua sayapnya ke atas, sayap-sayapnya menudungi tutup pendamaian itu dan mukanya menghadap kepada masing-masing; kepada tutup pendamaian itulah menghadap muka kerub-kerub itu."
  },
  {Bible:"Exodus", Chapter:37, Verse:10, Page:1,
    Kor:"<상을 만들다(출 25:23-30)> ○그는 아카시아 나무로, 길이가 두 자이고 너비가 한 자이고 높이가 한 자 반인 상을 만들어서,",
    Chn:"他用皂荚木做一张桌子，长二肘，宽一肘，高一肘半，",
    Eng:"They made the table of acacia wood--two cubits long, a cubit wide, and a cubit and a half high.",
    Ind:"Dibuatnyalah meja itu dari kayu penaga, dua hasta panjangnya, sehasta lebarnya dan satu setengah hasta tingginya."
  },
  {Bible:"Exodus", Chapter:37, Verse:11, Page:1,
    Kor:"순금으로 입히고, 둘레에는 금테를 둘렀다.",
    Chn:"又包上精金，四围镶上金牙边。",
    Eng:"Then they overlaid it with pure gold and made a gold molding around it.",
    Ind:"Disalutnyalah itu dengan emas murni dan dibuatnya bingkai emas sekelilingnya."
  },
  {Bible:"Exodus", Chapter:37, Verse:12, Page:1,
    Kor:"그리고 손바닥 너비만한 턱을 만들어 상 둘레에 붙이고, 그 턱의 둘레에도 금테를 둘렀다.",
    Chn:"桌子的四围各做一掌宽的横梁，横梁上镶着金牙边，",
    Eng:"They also made around it a rim a handbreadth wide and put a gold molding on the rim.",
    Ind:"Dibuatnyalah sekelilingnya jalur pinggir yang setapak tangan lebarnya dan dibuatnya bingkai emas sekeliling jalur pinggirnya itu."
  },
  {Bible:"Exodus", Chapter:37, Verse:13, Page:1,
    Kor:"금고리 넷을 부어 만들어서, 이 고리를 상 다리가 붙어 있는 네 모퉁이에 하나씩 붙였다.",
    Chn:"又铸了四个金环，安在桌子四脚的四角上。",
    Eng:"They cast four gold rings for the table and fastened them to the four corners, where the four legs were.",
    Ind:"Dituangnyalah untuk meja itu empat gelang emas dan dipasangnyalah gelang-gelang itu di keempat penjurunya, pada keempat kakinya."
  },
  {Bible:"Exodus", Chapter:37, Verse:14, Page:1,
    Kor:"그 고리들을 턱 곁에 달아서, 상을 운반할 때에 쓰는 채를 끼워 넣을 수 있게 하였다.",
    Chn:"安环子的地方是挨近横梁，可以穿杠抬桌子。",
    Eng:"The rings were put close to the rim to hold the poles used in carrying the table.",
    Ind:"Dekat ke jalur pinggirnyalah gelang itu, yakni tempat memasukkan kayu pengusung, supaya meja itu dapat diangkut."
  },
  {Bible:"Exodus", Chapter:37, Verse:15, Page:1,
    Kor:"그 채는 아카시아 나무로 만들고, 거기에 금을 입혀서 상을 운반할 수 있게 하였다.",
    Chn:"他用皂荚木做两根杠，用金包裹，以便抬桌子；",
    Eng:"The poles for carrying the table were made of acacia wood and were overlaid with gold.",
    Ind:"Dibuatnyalah kayu pengusung itu dari kayu penaga dan disalutnya dengan emas, yaitu supaya meja itu dapat diangkut."
  },
  {Bible:"Exodus", Chapter:37, Verse:16, Page:1,
    Kor:"상에 쓸 기구들, 곧 그 상에 올려 놓을 대접과 종지와 부어 드리는 제물을 담을 병과 잔을 순금으로 만들었다.",
    Chn:"又用精金做桌子上的器皿，就是盘子、调羹，并奠酒的瓶和爵。",
    Eng:"And they made from pure gold the articles for the table--its plates and dishes and bowls and its pitchers for the pouring out of drink offerings.",
    Ind:"Dan dibuatnyalah perkakas yang di atas meja itu, yakni pinggannya, cawannya, piala dan kendinya, yang dipakai untuk persembahan curahan, semuanya dari emas murni."
  },
  {Bible:"Exodus", Chapter:37, Verse:17, Page:1,
    Kor:"<등잔대를 만들다(출 25:31-40)> ○그는 순금을 두들겨서 등잔대를 만들었으며, 등잔대의 밑받침과 줄기와 등잔과 꽃받침과 꽃을 하나로 잇게 하였다.",
    Chn:"他用精金做一个灯台；这灯台的座和干，与杯、球、花，都是接连一块锤出来的。",
    Eng:"They made the lampstand of pure gold and hammered it out, base and shaft; its flowerlike cups, buds and blossoms were of one piece with it.",
    Ind:"Dibuatnyalah kandil itu dari emas murni; dari emas tempaan dibuatnya kandil itu, baik kakinya baik batangnya; kelopaknya--dengan tombolnya dan kembangnya--dibuat seiras dengan kandil itu."
  },
  {Bible:"Exodus", Chapter:37, Verse:18, Page:1,
    Kor:"등잔대의 줄기 양쪽에서 곁가지 여섯 개가 나오게 하였는데, 등잔대 한쪽에서 곁가지 세 개, 또 다른 한쪽에서도 곁가지 세 개가 나오게 하였다.",
    Chn:"灯台两旁杈出六个枝子：这旁三个，那旁三个。",
    Eng:"Six branches extended from the sides of the lampstand--three on one side and three on the other.",
    Ind:"Ada enam cabang timbul dari sisinya: tiga cabang kandil itu dari sisi yang satu dan tiga cabang dari sisi yang lain."
  },
  {Bible:"Exodus", Chapter:37, Verse:19, Page:1,
    Kor:"등잔대의 각 곁가지는 꽃받침과 꽃잎을 갖춘 감복숭아꽃 모양의 잔 세 개를 연결하여 만들고, 그 맞은쪽 곁가지도 꽃받침과 꽃잎을 갖춘 감복숭아꽃 모양 잔 세 개를 연결하여 만들었다. 등잔대의 줄기에서 나온 곁가지 여섯 개를 모두 이와 같이 하였다.",
    Chn:"这旁每枝上有三个杯，形状像杏花，有球有花；那旁每枝上也有三个杯，形状像杏花，有球有花。从灯台杈出来的六个枝子都是如此。",
    Eng:"Three cups shaped like almond flowers with buds and blossoms were on one branch, three on the next branch and the same for all six branches extending from the lampstand.",
    Ind:"Tiga kelopak yang berupa bunga badam pada cabang yang satu--dengan tombol dan kembangnya--dan tiga kelopak yang serupa pada cabang yang lain--dengan tombol dan kembangnya--;demikian juga dibuat keenam cabang yang timbul dari kandil itu."
  },
  {Bible:"Exodus", Chapter:37, Verse:20, Page:1,
    Kor:"등잔대 줄기는 꽃받침과 꽃잎을 갖춘 감복숭아꽃 모양 잔 네 개를 쌓아 놓은 모양으로 만들었다.",
    Chn:"灯台上有四个杯，形状像杏花，有球有花。",
    Eng:"And on the lampstand were four cups shaped like almond flowers with buds and blossoms.",
    Ind:"Pada kandil itu sendiri ada empat kelopak berupa bunga badam--dengan tombolnya dan kembangnya."
  },
  {Bible:"Exodus", Chapter:37, Verse:21, Page:1,
    Kor:"그리고 등잔대의 맨 위에 있는 좌우 두 곁가지가 줄기에서 뻗어 나올 때에는 밑에서 세 번째 놓인 꽃받침에서 뻗어 나오게 하고, 그 아래에 있는 좌우 두 곁가지가 줄기에서 뻗어 나올 때에는 밑에서 두 번째 놓인 꽃받침에서 뻗어 나오게 하고, 그리고 맨 아래에 있는 좌우 두 곁가지가 줄기에서 02 37:뻗어 나올 때에는 맨 아래에 놓인 꽃받침에서 뻗어 나오게 하여, 곁가지 여섯 개가 줄기와 연결되어 한 덩이가 되게 하였다. 이렇게 등잔대의 줄기에서 좌우로 곁가지가 나오게 하였다.",
    Chn:"灯台每两个枝子以下有球，与枝子接连一块；灯台杈出的六个枝子都是如此。",
    Eng:"One bud was under the first pair of branches extending from the lampstand, a second bud under the second pair, and a third bud under the third pair--six branches in all.",
    Ind:"Juga ada satu tombol di bawah sepasang cabang yang pertama yang timbul dari kandil itu, dan satu tombol di bawah yang kedua, dan satu tombol di bawah yang ketiga; demikianlah juga dibuat keenam cabang yang timbul dari situ."
  },
  {Bible:"Exodus", Chapter:37, Verse:22, Page:1,
    Kor:"등잔대 줄기의 꽃받침에 연결된 곁가지들은 모두 순금을 두들겨 만들어서, 전체를 하나로 잇게 하였다.",
    Chn:"球和枝子是接连一块，都是一块精金锤出来的。",
    Eng:"The buds and the branches were all of one piece with the lampstand, hammered out of pure gold.",
    Ind:"Tombol dan cabang itu timbul dari kandil itu, dan semuanya itu dibuat dari sepotong emas tempaan yang murni."
  },
  {Bible:"Exodus", Chapter:37, Verse:23, Page:1,
    Kor:"등잔 일곱 개와 등잔불 집게와 불똥 그릇을 순금으로 만들었는데,",
    Chn:"用精金做灯台的七个灯盏，并灯台的蜡剪和蜡花盘。",
    Eng:"They made its seven lamps, as well as its wick trimmers and trays, of pure gold.",
    Ind:"Dibuatnyalah pada kandil itu tujuh lampu dengan sepitnya dan penadahnya dari emas murni."
  },
  {Bible:"Exodus", Chapter:37, Verse:24, Page:1,
    Kor:"등잔대와 이 모든 기구를 순금 한 달란트를 들여서 만들었다.",
    Chn:"他用精金一他连得做灯台和灯台的一切器具。",
    Eng:"They made the lampstand and all its accessories from one talent of pure gold.",
    Ind:"Dari satu talenta emas murni dibuatnyalah kandil itu dengan segala perkakasnya."
  },
  {Bible:"Exodus", Chapter:37, Verse:25, Page:1,
    Kor:"<분향단을 만들다(출 30:1-5)> ○그는 아카시아 나무로 분향단을 만들었는데, 그 길이가 한 자요 너비가 한 자인 네모난 모양으로서, 높이는 두 자로 하고, 그 뿔과 단은 하나로 잇게 만들었다.",
    Chn:"他用皂荚木做香坛，是四方的，长一肘，宽一肘，高二肘，坛的四角与坛接连一块；",
    Eng:"They made the altar of incense out of acacia wood. It was square, a cubit long and a cubit wide, and two cubits high--its horns of one piece with it.",
    Ind:"Dibuatnyalah mezbah pembakaran ukupan itu dari kayu penaga, sehasta panjangnya dan sehasta lebarnya, empat persegi, tetapi dua hasta tingginya; tanduk-tanduknya seiras dengan mezbah itu."
  },
  {Bible:"Exodus", Chapter:37, Verse:26, Page:1,
    Kor:"그리고 그 단의 윗면과 네 옆면과 뿔을 순금으로 입히고, 그 가장자리에 금테를 둘렀다.",
    Chn:"又用精金把坛的上面与坛的四面并坛的四角包裹，又在坛的四围镶上金牙边。",
    Eng:"They overlaid the top and all the sides and the horns with pure gold, and made a gold molding around it.",
    Ind:"Disalutnyalah itu dengan emas murni, bidang atasnya dan bidang-bidang sisinya sekelilingnya, serta tanduk-tanduknya. Dibuatnyalah bingkai emas sekelilingnya."
  },
  {Bible:"Exodus", Chapter:37, Verse:27, Page:1,
    Kor:"금고리 둘을 만들어 그 금테 아래 양쪽 옆에 붙여서, 그것을 들고 다닐 채를 끼울 수 있게 하였다.",
    Chn:"做两个金环，安在牙子边以下，在坛的两旁、两根横撑上，作为穿杠的用处，以便抬坛。",
    Eng:"They made two gold rings below the molding--two on opposite sides--to hold the poles used to carry it.",
    Ind:"Dibuatnyalah dua gelang emas untuk mezbah itu di bawah bingkainya, pada kedua rusuknya, pada kedua bidang sisinya, sebagai tempat memasukkan kayu pengusung, supaya dengan itu mezbah dapat diangkut."
  },
  {Bible:"Exodus", Chapter:37, Verse:28, Page:1,
    Kor:"아카시아 나무로 채를 만들고, 거기에 금을 입혔다.",
    Chn:"用皂荚木做杠，用金包裹。",
    Eng:"They made the poles of acacia wood and overlaid them with gold.",
    Ind:"Dan dibuatnyalah kayu pengusung itu dari kayu penaga dan disalutnya dengan emas."
  },
  {Bible:"Exodus", Chapter:37, Verse:29, Page:1,
    Kor:"<성별하는 기름과 향(출 30:22-38)> ○그는, 향을 제조하는 법을 따라서, 성별하는 기름과 향기롭고 순수한 향을 만들었다.",
    Chn:"又按做香之法做圣膏油和馨香料的净香。",
    Eng:"They also made the sacred anointing oil and the pure, fragrant incense--the work of a perfumer.",
    Ind:"Dan dibuatnyalah minyak urapan yang kudus itu dan ukupan murni dari wangi-wangian, seperti buatan seorang tukang campur rempah-rempah."
  },
]);
