// 출애굽기 39장 · Exodus 39
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Exodus",39,43);
BibleDB.add([
  {Bible:"Exodus", Chapter:39, Verse:1, Page:1,
    Kor:"<제사장의 예복을 만들다(출 28:1-14)> 그들은 청색 실과 자주색 실과 홍색 실로 성소에서 예배드릴 때에 입는 옷을 정교하게 짜서 만들었다. 그들은 이렇게, 주님께서 모세에게 명하신 대로, 아론이 입을 거룩한 옷을 만들었다.",
    Chn:"比撒列用蓝色、紫色、朱红色线做精致的衣服，在圣所用以供职，又为亚伦做圣衣，是照耶和华所吩咐摩西的。",
    Eng:"From the blue, purple and scarlet yarn they made woven garments for ministering in the sanctuary. They also made sacred garments for Aaron, as the LORD commanded Moses.",
    Ind:"Dari kain ungu tua, kain ungu muda dan kain kirmizi dibuat merekalah pakaian jabatan yang dipakai apabila diselenggarakan kebaktian di tempat kudus; juga dibuat mereka pakaian-pakaian kudus untuk Harun, seperti yang diperintahkan TUHAN kepada Musa."
  },
  {Bible:"Exodus", Chapter:39, Verse:2, Page:1,
    Kor:"○금 실과 청색 실과 자주색 실과 홍색 실과 가늘게 꼰 모시 실로 에봇을 만들었다.",
    Chn:"他用金线和蓝色、紫色、朱红色线，并捻的细麻做以弗得；",
    Eng:"They made the ephod of gold, and of blue, purple and scarlet yarn, and of finely twisted linen.",
    Ind:"Dibuatnyalah baju efod dari emas, kain ungu tua dan kain ungu muda, kain kirmizi dan lenan halus yang dipintal benangnya."
  },
  {Bible:"Exodus", Chapter:39, Verse:3, Page:1,
    Kor:"금을 얇게 두들겨 가지고 오려 내어서 실을 만들고, 청색 실과 자주색 실과 홍색 실과 가는 모시 실을 섞어 가며 정교하게 감을 짰다.",
    Chn:"把金子锤成薄片，剪出线来，与蓝色、紫色、朱红色线，用巧匠的手工一同绣上。",
    Eng:"They hammered out thin sheets of gold and cut strands to be worked into the blue, purple and scarlet yarn and fine linen--the work of a skilled craftsman.",
    Ind:"Mereka menempa emas papan dan dipotong-potongnyalah itu menjadi benang emas, untuk dipakankan pada kain ungu tua, pada kain ungu muda, pada kain kirmizi dan pada lenan halus: buatan seorang ahli."
  },
  {Bible:"Exodus", Chapter:39, Verse:4, Page:1,
    Kor:"에봇의 양쪽에 멜빵을 만들어서, 에봇을 입을 때에 멜빵을 조여서 조정하게 하였다.",
    Chn:"又为以弗得做两条相连的肩带，接连在以弗得的两头。",
    Eng:"They made shoulder pieces for the ephod, which were attached to two of its corners, so it could be fastened.",
    Ind:"Dibuat merekalah tutup bahu pada baju efod itu, yang disambung kepadanya, dikedua ujungnyalah baju efod itu disambung."
  },
  {Bible:"Exodus", Chapter:39, Verse:5, Page:1,
    Kor:"에봇 위에 띨 허리띠는 에봇을 짤 때와 같은 방법으로, 금 실과 청색 실과 자주색 실과 홍색 실과 가늘게 꼰 모시 실로 짜서, 에봇과 한데 이어 붙였다. 이것은 모두 주님께서 모세에게 명하신 대로 한 것이다.",
    Chn:"其上巧工织的带子和以弗得一样的做法，用以束上，与以弗得接连一块，是用金线和蓝色、紫色、朱红色线，并捻的细麻做的，是照耶和华所吩咐摩西的。",
    Eng:"Its skillfully woven waistband was like it--of one piece with the ephod and made with gold, and with blue, purple and scarlet yarn, and with finely twisted linen, as the LORD commanded Moses.",
    Ind:"Sabuk pengikat yang ada pada baju efod itu adalah seiras dan sama buatannya dengan baju efod itu, yakni dari emas, kain ungu tua, kain ungu muda, kain kirmizi dan lenan halus yang dipintal benangnya, seperti yang diperintahkan TUHAN kepada Musa."
  },
  {Bible:"Exodus", Chapter:39, Verse:6, Page:1,
    Kor:"○홍옥수 두 개를 깎아서 금테에 물리고, 인장 반지를 새기듯이, 그 위에 이스라엘의 아들들의 이름을 새겨 넣었다.",
    Chn:"又琢出两块红玛瑙，镶在金槽上，仿佛刻图书，按着以色列儿子的名字雕刻；",
    Eng:"They mounted the onyx stones in gold filigree settings and engraved them like a seal with the names of the sons of Israel.",
    Ind:"Dikerjakan merekalah permata krisopras, yakni dililit dengan ikat emas, diukirkan padanya nama para anak Israel, yang diukirkan seperti meterai."
  },
  {Bible:"Exodus", Chapter:39, Verse:7, Page:1,
    Kor:"그리고 이스라엘 지파들을 상징하는 이 기념 보석들을 에봇의 양쪽 멜빵 위에 달았다. 이는 주님께서 모세에게 명하신 대로 한 것이다.",
    Chn:"将这两块宝石安在以弗得的两条肩带上，为以色列人做纪念石，是照耶和华所吩咐摩西的。",
    Eng:"Then they fastened them on the shoulder pieces of the ephod as memorial stones for the sons of Israel, as the LORD commanded Moses.",
    Ind:"Ditaruhnyalah itu pada kedua tutup bahu baju efod sebagai permata peringatan untuk mengingat orang Israel, seperti yang diperintahkan TUHAN kepada Musa."
  },
  {Bible:"Exodus", Chapter:39, Verse:8, Page:1,
    Kor:"<가슴받이를 만들다(출 28:15-30)> ○그들은 에봇을 만들 때와 마찬가지로 금 실과 청색 실과 자주색 실과 홍색 실과 가늘게 꼰 모시 실로 가슴받이를 정교하게 만들었다.",
    Chn:"他用巧匠的手工做胸牌，和以弗得一样的做法，用金线与蓝色、紫色、朱红色线，并捻的细麻做的。",
    Eng:"They fashioned the breastpiece--the work of a skilled craftsman. They made it like the ephod: of gold, and of blue, purple and scarlet yarn, and of finely twisted linen.",
    Ind:"Dibuatnyalah tutup dada, buatan seorang ahli. Buatannya sama dengan baju efod, yakni dari emas, kain ungu tua, kain ungu muda, kain kirmizi dan lenan halus yang dipintal benangnya."
  },
  {Bible:"Exodus", Chapter:39, Verse:9, Page:1,
    Kor:"그것은 두 겹으로 겹쳐서 네모나게 만든 것으로, 길이가 한 뼘이요 너비가 한 뼘인 가슴받이이다.",
    Chn:"胸牌是四方的，叠为两层；这两层长一虎口，宽一虎口，",
    Eng:"It was square--a span long and a span wide--and folded double.",
    Ind:"Empat persegi dibuatnya itu; lipat dua dibuat mereka tutup dada itu, sejengkal panjangnya dan sejengkal lebarnya."
  },
  {Bible:"Exodus", Chapter:39, Verse:10, Page:1,
    Kor:"거기에 보석을 네 줄 물렸다. 첫째 줄에는 홍보석과 황옥과 취옥을 박고,",
    Chn:"上面镶着宝石四行：第一行是红宝石、红璧玺、红玉；",
    Eng:"Then they mounted four rows of precious stones on it. In the first row there was a ruby, a topaz and a beryl;",
    Ind:"Ditatah merekalah itu dengan empat jajar permata: permata yaspis merah, krisolit, malakit, itulah jajar yang pertama;"
  },
  {Bible:"Exodus", Chapter:39, Verse:11, Page:1,
    Kor:"둘째 줄에는 녹주석과 청옥과 백수정을 박고,",
    Chn:"第二行是绿宝石、蓝宝石、金钢石；",
    Eng:"in the second row a turquoise, a sapphire and an emerald;",
    Ind:"jajar yang kedua: permata batu darah, lazurit, yaspis hijau;"
  },
  {Bible:"Exodus", Chapter:39, Verse:12, Page:1,
    Kor:"셋째 줄에는 풍신자석과 마노와 자수정을 박고,",
    Chn:"第三行是紫玛瑙、白玛瑙、紫晶；",
    Eng:"in the third row a jacinth, an agate and an amethyst;",
    Ind:"jajar yang ketiga: permata ambar, akik, kecubung;"
  },
  {Bible:"Exodus", Chapter:39, Verse:13, Page:1,
    Kor:"넷째 줄에는 녹주석과 얼룩 마노와 벽옥을 박고, 이 보석들을 모두 금테에 물렸다.",
    Chn:"第四行是水苍玉、红玛瑙、碧玉。这都镶在金槽中。",
    Eng:"in the fourth row a chrysolite, an onyx and a jasper. They were mounted in gold filigree settings.",
    Ind:"jajar yang keempat: permata pirus, krisopras dan nefrit. Dililit dengan ikat emas, demikianlah permata-permata itu dalam tatahannya."
  },
  {Bible:"Exodus", Chapter:39, Verse:14, Page:1,
    Kor:"이 보석들은 이스라엘의 아들들의 수대로 열둘이었는데, 인장 반지를 새기듯이, 보석마다 각 사람의 이름을 새겨서, 이 보석들로 열두 지파를 나타내게 하였다.",
    Chn:"这些宝石都是按着以色列十二个儿子的名字，仿佛刻图书，刻十二个支派的名字。",
    Eng:"There were twelve stones, one for each of the names of the sons of Israel, each engraved like a seal with the name of one of the twelve tribes.",
    Ind:"Sesuai dengan nama para anak Israel, permata itu adalah dua belas banyaknya; dan pada tiap-tiap permata ada diukirkan seperti meterai, nama salah satu suku dari yang dua belas itu."
  },
  {Bible:"Exodus", Chapter:39, Verse:15, Page:1,
    Kor:"가슴받이를 가슴에 매달 사슬은 순금으로 노끈처럼 꼬아서 만들었다.",
    Chn:"在胸牌上，用精金拧成如绳子的链子。",
    Eng:"For the breastpiece they made braided chains of pure gold, like a rope.",
    Ind:"Juga dibuat merekalah untuk tutup dada itu untai berpilin, yang buatannya sebagai tali berjalin, dari emas murni."
  },
  {Bible:"Exodus", Chapter:39, Verse:16, Page:1,
    Kor:"금테 두 개와 금고리 두 개를 만들어서, 그 두 고리를 가슴받이의 양쪽 끝에 달았다.",
    Chn:"又做两个金槽和两个金环，安在胸牌的两头。",
    Eng:"They made two gold filigree settings and two gold rings, and fastened the rings to two of the corners of the breastpiece.",
    Ind:"Dibuat merekalah dua ikat emas dan dua gelang emas dan kedua gelang itu dipasang pada kedua ujung tutup dada."
  },
  {Bible:"Exodus", Chapter:39, Verse:17, Page:1,
    Kor:"금사슬 두 개를 꼬아서, 가슴받이 양쪽 끝에 있는 두 고리에 매었다.",
    Chn:"把那两条拧成的金链子穿过胸牌两头的环子，",
    Eng:"They fastened the two gold chains to the rings at the corners of the breastpiece,",
    Ind:"Dipasang merekalah kedua untai emas yang berjalin itu pada kedua gelang itu di ujung tutup dada."
  },
  {Bible:"Exodus", Chapter:39, Verse:18, Page:1,
    Kor:"그리고 꼰 사슬의 다른 두 끝을 에봇 앞쪽의 멜빵에 달린 두 금테에 매고,",
    Chn:"又把链子的那两头接在两槽上，安在以弗得前面肩带上。",
    Eng:"and the other ends of the chains to the two settings, attaching them to the shoulder pieces of the ephod at the front.",
    Ind:"Kedua ujung lain dari kedua untai berjalin itu dipasang merekalah pada kedua ikat emas itu, demikianlah dipasang pada tutup bahu baju efod, di sebelah depannya."
  },
  {Bible:"Exodus", Chapter:39, Verse:19, Page:1,
    Kor:"또 금고리 두 개를 더 만들었으며, 그것을 가슴받이 아래의 양쪽 가장자리 안쪽인 에봇과 겹치는 곳에 달았다.",
    Chn:"做两个金环，安在胸牌的两头，在以弗得里面的边上，",
    Eng:"They made two gold rings and attached them to the other two corners of the breastpiece on the inside edge next to the ephod.",
    Ind:"Dibuat merekalah dua gelang emas dan dibubuh pada kedua ujung tutup dada itu, pada pinggirnya yang sebelah dalam, yang berhadapan dengan baju efod."
  },
  {Bible:"Exodus", Chapter:39, Verse:20, Page:1,
    Kor:"그리고 다른 금고리 두 개를 더 만들어서, 에봇의 양쪽 멜빵 앞자락 아래, 곧 정교하게 짠 에봇 띠를 매는 곳 조금 위에 달았다.",
    Chn:"又做两个金环，安在以弗得前面两条肩带的下边，挨近相接之处，在以弗得巧工织的带子以上。",
    Eng:"Then they made two more gold rings and attached them to the bottom of the shoulder pieces on the front of the ephod, close to the seam just above the waistband of the ephod.",
    Ind:"Juga dibuat merekalah dua gelang emas dan dipasang pada kedua tutup bahu baju efod, di sebelah bawah pada bagian depan, dekat ke tempat persambungannya, di sebelah atas sabuk baju efod."
  },
  {Bible:"Exodus", Chapter:39, Verse:21, Page:1,
    Kor:"청색 실로 꼰 끈으로 가슴받이 고리를 에봇 고리에 매되, 정교하게 짠 에봇 띠 조금 위에다 매어서, 가슴받이가 에봇에서 떨어지지 않게 하였다. 이는 주님께서 모세에게 명하신 대로 한 것이다.",
    Chn:"用一条蓝细带子把胸牌的环子和以弗得的环子系住，使胸牌贴在以弗得巧工织的带子上，不可与以弗得离缝，是照耶和华所吩咐摩西的。",
    Eng:"They tied the rings of the breastpiece to the rings of the ephod with blue cord, connecting it to the waistband so that the breastpiece would not swing out from the ephod--as the LORD commanded Moses.",
    Ind:"Kemudian diikatkan merekalah tutup dada itu dengan gelangnya kepada gelang baju efod dengan memakai tali ungu tua, sehingga tetap di atas sabuk baju efod, dan tutup dada itu tidak dapat bergeser dari baju efod--seperti yang diperintahkan TUHAN kepada Musa."
  },
  {Bible:"Exodus", Chapter:39, Verse:22, Page:1,
    Kor:"<제사장의 또다른 예복을 만들다(출 28:31-43)> ○그들은 에봇에 딸린 겉옷을 전부 청색으로 짜서 만들었다.",
    Chn:"他用织工做以弗得的外袍，颜色全是蓝的。",
    Eng:"They made the robe of the ephod entirely of blue cloth--the work of a weaver--",
    Ind:"Dibuatnyalah gamis baju efod, buatan tukang tenun, dari kain ungu tua seluruhnya."
  },
  {Bible:"Exodus", Chapter:39, Verse:23, Page:1,
    Kor:"그 겉옷 한가운데에 구멍을 내고, 그 구멍의 둘레를 갑옷의 깃처럼 단단히 홀쳐서, 찢어지지 않게 하였다.",
    Chn:"袍上留一领口，口的周围织出领边来，仿佛铠甲的领口，免得破裂。",
    Eng:"with an opening in the center of the robe like the opening of a collar, and a band around this opening, so that it would not tear.",
    Ind:"Leher gamis itu di tengah-tengahnya seperti leher baju zirah, lehernya itu mempunyai pinggir sekelilingnya, supaya jangan koyak."
  },
  {Bible:"Exodus", Chapter:39, Verse:24, Page:1,
    Kor:"그들은 겉옷 자락 둘레에 청색 실과 자주색 실과 홍색 실과 가늘게 꼰 모시 실로 석류 모양 술을 만들어 달았다.",
    Chn:"在袍子底边上，用蓝色、紫色、朱红色线，并捻的细麻做石榴，",
    Eng:"They made pomegranates of blue, purple and scarlet yarn and finely twisted linen around the hem of the robe.",
    Ind:"Dibuat merekalah pada ujung gamis itu buah delima dari kain ungu tua, kain ungu muda dan kain kirmizi, yang dipintal benangnya."
  },
  {Bible:"Exodus", Chapter:39, Verse:25, Page:1,
    Kor:"그리고 순금으로 방울을 만들어서, 그 방울을 겉옷 자락에 달린 석류 술 사이사이에 돌아가면서 달았다.",
    Chn:"又用精金做铃铛，把铃铛钉在袍子周围底边上的石榴中间：",
    Eng:"And they made bells of pure gold and attached them around the hem between the pomegranates.",
    Ind:"Dibuat merekalah giring-giring dari emas murni dan ditaruhlah giring-giring itu di antara buah delima, pada ujung gamis itu, berselang-seling di antara buah delima itu,"
  },
  {Bible:"Exodus", Chapter:39, Verse:26, Page:1,
    Kor:"이렇게, 제사를 드릴 때에 입을 수 있게, 겉옷 자락을 돌아가며, 방울 하나 석류 하나, 또 방울 하나 석류 하나를 달았으니, 이는 주님께서 모세에게 명하신 대로 한 것이다.",
    Chn:"一个铃铛一个石榴，一个铃铛一个石榴，在袍子周围底边上用以供职，是照耶和华所吩咐摩西的。",
    Eng:"The bells and pomegranates alternated around the hem of the robe to be worn for ministering, as the LORD commanded Moses.",
    Ind:"sehingga satu giring-giring dan satu buah delima selalu berselang-seling, pada sekeliling ujung gamis, yang dipakai apabila diselenggarakan kebaktian seperti yang diperintahkan TUHAN kepada Musa."
  },
  {Bible:"Exodus", Chapter:39, Verse:27, Page:1,
    Kor:"○그들은 또 아론과 그의 아들들이 입을 속옷을 가는 모시 실로 정교하게 짜서 만들었다.",
    Chn:"他用织成的细麻布为亚伦和他的儿子做内袍，",
    Eng:"For Aaron and his sons, they made tunics of fine linen--the work of a weaver--",
    Ind:"Dibuat merekalah kemeja dari lenan halus, buatan tukang tenun, untuk Harun dan anak-anaknya,"
  },
  {Bible:"Exodus", Chapter:39, Verse:28, Page:1,
    Kor:"고운 모시 두건과 고운 모시 관과 가늘게 꼰 모시 실로 짠 속바지를 만들었다.",
    Chn:"并用细麻布做冠冕和华美的裹头巾，用捻的细麻布做裤子，",
    Eng:"and the turban of fine linen, the linen headbands and the undergarments of finely twisted linen.",
    Ind:"serban dari lenan halus, destar yang indah dari lenan halus, celana lenan dari lenan halus yang dipintal benangnya,"
  },
  {Bible:"Exodus", Chapter:39, Verse:29, Page:1,
    Kor:"가늘게 꼰 모시 실과 청색 실과 자주색 실과 홍색 실로 수를 놓아, 허리띠를 만들었다. 이 모든 것은 주님께서 모세에게 명하신 대로 한 것이다.",
    Chn:"又用蓝色、紫色、朱红色线，并捻的细麻，以绣花的手工做腰带，是照耶和华所吩咐摩西的。",
    Eng:"The sash was of finely twisted linen and blue, purple and scarlet yarn--the work of an embroiderer--as the LORD commanded Moses.",
    Ind:"dan ikat pinggang dari lenan halus yang dipintal benangnya, kain ungu tua, kain ungu muda dan kain kirmizi, dari tenunan yang berwarna-warna--seperti yang diperintahkan TUHAN kepada Musa."
  },
  {Bible:"Exodus", Chapter:39, Verse:30, Page:1,
    Kor:"○그들은 또 성직자의 관에 붙이는 거룩한 패를 순금으로 만들고, 그 위에, 인장 반지를 새기듯이 '주님의 성직자'라고 새겨 넣었다.",
    Chn:"他用精金做圣冠上的牌，在上面按刻图书之法，刻着「归耶和华为圣」。",
    Eng:"They made the plate, the sacred diadem, out of pure gold and engraved on it, like an inscription on a seal: HOLY TO THE LORD.",
    Ind:"Dibuat merekalah patam, jamang yang kudus dari emas murni, dan pada jamang itu dituliskan tulisan, diukirkan seperti meterai: Kudus bagi TUHAN."
  },
  {Bible:"Exodus", Chapter:39, Verse:31, Page:1,
    Kor:"그것을 청색 실로 꼰 끈에 매어서 제사장이 쓰는 관에 달았다. 이것은 주님께서 모세에게 명하신 대로 한 것이다.",
    Chn:"又用一条蓝细带子将牌系在冠冕上，是照耶和华所吩咐摩西的。",
    Eng:"Then they fastened a blue cord to it to attach it to the turban, as the LORD commanded Moses.",
    Ind:"Dipasang merekalah pada patam itu tali ungu tua untuk mengikatkan patam itu pada serbannya, di sebelah atas--seperti yang diperintahkan TUHAN kepada Musa."
  },
  {Bible:"Exodus", Chapter:39, Verse:32, Page:1,
    Kor:"<성막 완공 검사(출 35:10-19)> ○이렇게 해서, 성막 곧 회막의 공사가 완성되었다. 이스라엘 자손은, 주님께서 모세에게 명하신 모든 것을 그대로 다 하였다.",
    Chn:"帐幕，就是会幕，一切的工就这样做完了。凡耶和华所吩咐摩西的，以色列人都照样做了。",
    Eng:"So all the work on the tabernacle, the Tent of Meeting, was completed. The Israelites did everything just as the LORD commanded Moses.",
    Ind:"Demikianlah diselesaikan segala pekerjaan melengkapi Kemah Suci, yakni Kemah Pertemuan itu. Orang Israel telah melakukannya tepat seperti yang diperintahkan TUHAN kepada Musa, demikianlah mereka melakukannya."
  },
  {Bible:"Exodus", Chapter:39, Verse:33, Page:1,
    Kor:"그런 다음에, 그들은 성막을 모세에게 가져 왔으니, 이는 천막과 거기에 딸린 모든 기구, 곧 갈고리와 널빤지와 가로다지와 기둥과 밑받침과,",
    Chn:"他们送到摩西那里。帐幕和帐幕的一切器具，就是钩子、板、闩、柱子、带卯的座，",
    Eng:"Then they brought the tabernacle to Moses: the tent and all its furnishings, its clasps, frames, crossbars, posts and bases;",
    Ind:"Dibawa merekalah Kemah Suci itu kepada Musa, yakni kemah dengan segala perabotannya: kaitannya, papannya, kayu lintangnya, tiangnya dan alasnya,"
  },
  {Bible:"Exodus", Chapter:39, Verse:34, Page:1,
    Kor:"붉게 물들인 숫양 가죽 덮개와 돌고래 가죽 덮개와 칸막이 휘장과,",
    Chn:"染红公羊皮的盖、海狗皮的顶盖，和遮掩柜的幔子，",
    Eng:"the covering of ram skins dyed red, the covering of hides of sea cows and the shielding curtain;",
    Ind:"tudung dari kulit domba jantan yang diwarnai merah, tudung dari kulit lumba-lumba, tabir penudung,"
  },
  {Bible:"Exodus", Chapter:39, Verse:35, Page:1,
    Kor:"증거궤와 그것에 딸린 채와 속죄판과,",
    Chn:"法柜和柜的杠并施恩座，",
    Eng:"the ark of the Testimony with its poles and the atonement cover;",
    Ind:"tabut hukum Allah dengan kayu-kayu pengusungnya dan tutup pendamaian,"
  },
  {Bible:"Exodus", Chapter:39, Verse:36, Page:1,
    Kor:"상과 그 밖의 모든 기구와 상에 차려 놓을 빵과,",
    Chn:"桌子和桌子的一切器具并陈设饼，",
    Eng:"the table with all its articles and the bread of the Presence;",
    Ind:"meja, segala perkakasnya dan roti sajian,"
  },
  {Bible:"Exodus", Chapter:39, Verse:37, Page:1,
    Kor:"순금 등잔대와 거기에 얹어 놓을 등잔들과 그 밖의 모든 기구와 등잔용 기름과,",
    Chn:"精金的灯台和摆列的灯盏，与灯台的一切器具，并点灯的油，",
    Eng:"the pure gold lampstand with its row of lamps and all its accessories, and the oil for the light;",
    Ind:"kandil dari emas murni, lampu-lampunya--lampu yang harus teratur di atasnya--dan segala perkakasnya, minyak untuk penerangan,"
  },
  {Bible:"Exodus", Chapter:39, Verse:38, Page:1,
    Kor:"금제단과 예식용 기름과 분향할 향과 장막 어귀의 휘장과,",
    Chn:"金坛、膏油、馨香的香料、会幕的门帘，",
    Eng:"the gold altar, the anointing oil, the fragrant incense, and the curtain for the entrance to the tent;",
    Ind:"mezbah dari emas, minyak urapan, ukupan dari wangi-wangian, tirai pintu kemah,"
  },
  {Bible:"Exodus", Chapter:39, Verse:39, Page:1,
    Kor:"놋제단과 거기에 딸린 놋그물과 놋제단을 옮기는 데 쓸 채와 모든 기구와 물두멍과 그 받침과,",
    Chn:"铜坛和坛上的铜网，坛的杠并坛的一切器具，洗濯盆和盆座，",
    Eng:"the bronze altar with its bronze grating, its poles and all its utensils; the basin with its stand;",
    Ind:"mezbah tembaga dengan kisi-kisi tembaganya, kayu-kayu pengusungnya dan segala perkakasnya, bejana pembasuhan dengan alasnya,"
  },
  {Bible:"Exodus", Chapter:39, Verse:40, Page:1,
    Kor:"뜰의 휘장과 그 기둥과 밑받침과 뜰의 정문 휘장과 그 줄과 말뚝과, 성막 곧 회막에서 예배를 드릴 때에 쓰는 모든 기구와,",
    Chn:"院子的帷子和柱子，并带卯的座，院子的门帘、绳子、橛子，并帐幕和会幕中一切使用的器具，",
    Eng:"the curtains of the courtyard with its posts and bases, and the curtain for the entrance to the courtyard; the ropes and tent pegs for the courtyard; all the furnishings for the tabernacle, the Tent of Meeting;",
    Ind:"layar pelataran, tiangnya dan alasnya, dan tirai untuk pintu gerbang pelataran, talinya dan patoknya, segala perkakas untuk pekerjaan mendirikan Kemah Suci, yakni Kemah Pertemuan itu;"
  },
  {Bible:"Exodus", Chapter:39, Verse:41, Page:1,
    Kor:"성소에서 예식을 올릴 때에 입는 잘 짠 옷 곧 제사장 아론의 거룩한 옷과 그 아들들이 제사장 일을 할 때에 입는 옷 들이다.",
    Chn:"精工做的礼服，和祭司亚伦并他儿子在圣所用以供祭司职分的圣衣。",
    Eng:"and the woven garments worn for ministering in the sanctuary, both the sacred garments for Aaron the priest and the garments for his sons when serving as priests.",
    Ind:"pakaian jabatan yang dipakai apabila diselenggarakan kebaktian di tempat kudus, pakaian kudus untuk imam Harun, dan pakaian anak-anaknya untuk memegang jabatan imam."
  },
  {Bible:"Exodus", Chapter:39, Verse:42, Page:1,
    Kor:"이스라엘 자손은, 주님께서 모세에게 명하신 모든 것을 그대로 하여, 일을 완수하였다.",
    Chn:"这一切工作都是以色列人照耶和华所吩咐摩西做的。",
    Eng:"The Israelites had done all the work just as the LORD had commanded Moses.",
    Ind:"Tepat seperti yang diperintahkan TUHAN kepada Musa, demikianlah dilakukan orang Israel segala pekerjaan melengkapi itu."
  },
  {Bible:"Exodus", Chapter:39, Verse:43, Page:1,
    Kor:"모세가 그 모든 일을 점검하여 보니, 그들이 주님께서 명하신 그대로 하였으므로, 그들에게 복을 빌어 주었다.",
    Chn:"耶和华怎样吩咐的，他们就怎样做了。摩西看见一切的工都做成了，就给他们祝福。",
    Eng:"Moses inspected the work and saw that they had done it just as the LORD had commanded. So Moses blessed them.",
    Ind:"Dan Musa melihat segala pekerjaan itu, dan sesungguhnyalah, mereka telah melakukannya seperti yang diperintahkan TUHAN, demikianlah mereka melakukannya. Lalu Musa memberkati mereka."
  },
]);
