// 출애굽기 6장 · Exodus 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Exodus",6,30);
BibleDB.add([
  {Bible:"Exodus", Chapter:6, Verse:1, Page:1,
    Kor:"주님께서 모세에게 말씀하셨다. \"이제 너는, 내가 바로에게 하는 일을 보게 될 것이다. 틀림없이 그는 강한 손에 밀려서, 그들을 내보내게 될 것이다. 강한 손에 밀려서야, 그들을 이 땅에서 내쫓다시피 할 것이다.\"",
    Chn:"耶和华对摩西说：「现在你必看见我向法老所行的事，使他因我大能的手容以色列人去，且把他们赶出他的地。」",
    Eng:"Then the LORD said to Moses, \"Now you will see what I will do to Pharaoh: Because of my mighty hand he will let them go; because of my mighty hand he will drive them out of his country.\"",
    Ind:"(5-24) Tetapi TUHAN berfirman kepada Musa: \"Sekarang engkau akan melihat, apa yang akan Kulakukan kepada Firaun; sebab dipaksa oleh tangan yang kuat ia akan membiarkan mereka pergi, ya dipaksa oleh tangan yang kuat ia akan mengusir mereka dari negerinya.\""
  },
  {Bible:"Exodus", Chapter:6, Verse:2, Page:1,
    Kor:"<하나님이 모세를 부르시다> ○하나님이 모세에게 이렇게 말씀하셨다. \"나는 '주'다.",
    Chn:"神晓谕摩西说：「我是耶和华。",
    Eng:"God also said to Moses, \"I am the LORD.",
    Ind:"(6-1) Selanjutnya berfirmanlah Allah kepada Musa: \"Akulah TUHAN."
  },
  {Bible:"Exodus", Chapter:6, Verse:3, Page:1,
    Kor:"나는 아브라함과 이삭과 야곱에게 a '전능한 하나님'으로는 나타났으나, 그들에게 나의 이름을 b '여호와'로는 알리지 않았다.(a 히, '엘 샤다이' b 하나님의 이름을 표기한 히브리어 네 자음 글자를 유대교에서는 '아도나이(주)' 또는 '엘로힘(하나님)'으로 읽고, 같은 이름을 칠십인역과 신약에서는 '퀴리오스(주)'로 부르고 있음. 16세기 이래 이 이름을 여호와로 부르기 시작하였으나 지금은 대다수의 번역이 오랜 전통을 따라 '주'로 부르고 있음)",
    Chn:"我从前向亚伯拉罕、以撒、雅各显现为全能的　神；至于我名耶和华，他们未曾知道。",
    Eng:"I appeared to Abraham, to Isaac and to Jacob as God Almighty, but by my name the LORD I did not make myself known to them.",
    Ind:"(6-2) Aku telah menampakkan diri kepada Abraham, Ishak dan Yakub sebagai Allah Yang Mahakuasa, tetapi dengan nama-Ku TUHAN Aku belum menyatakan diri."
  },
  {Bible:"Exodus", Chapter:6, Verse:4, Page:1,
    Kor:"나는 또한, 그들이 한동안 나그네로 몸붙여 살던 가나안 땅을 그들에게 주기로 그들과 언약을 세웠는데,",
    Chn:"我与他们坚定所立的约，要把他们寄居的迦南地赐给他们。",
    Eng:"I also established my covenant with them to give them the land of Canaan, where they lived as aliens.",
    Ind:"(6-3) Bukan saja Aku telah mengadakan perjanjian-Ku dengan mereka untuk memberikan kepada mereka tanah Kanaan, tempat mereka tinggal sebagai orang asing,"
  },
  {Bible:"Exodus", Chapter:6, Verse:5, Page:1,
    Kor:"이제 나는 이집트 사람이 종으로 부리는 이스라엘 자손의 신음소리를 듣고, 내가 세운 언약을 생각한다.",
    Chn:"我也听见以色列人被埃及人苦待的哀声，我也记念我的约。",
    Eng:"Moreover, I have heard the groaning of the Israelites, whom the Egyptians are enslaving, and I have remembered my covenant.",
    Ind:"(6-4) tetapi Aku sudah mendengar juga erang orang Israel yang telah diperbudak oleh orang Mesir, dan Aku ingat kepada perjanjian-Ku."
  },
  {Bible:"Exodus", Chapter:6, Verse:6, Page:1,
    Kor:"그러므로 너는 이스라엘 자손에게 말하여라. '나는 주다. 나는 이집트 사람들이 너희를 강제로 부리지 못하게 거기에서 너희를 이끌어 내고, 그 종살이에서 너희를 건지고, 나의 팔을 펴서 큰 심판을 내리면서, 너희를 구하여 내겠다.",
    Chn:"所以你要对以色列人说：『我是耶和华；我要用伸出来的膀臂重重地刑罚埃及人，救赎你们脱离他们的重担，不做他们的苦工。",
    Eng:"\"Therefore, say to the Israelites: 'I am the LORD, and I will bring you out from under the yoke of the Egyptians. I will free you from being slaves to them, and I will redeem you with an outstretched arm and with mighty acts of judgment.",
    Ind:"(6-5) Sebab itu katakanlah kepada orang Israel: Akulah TUHAN, Aku akan membebaskan kamu dari kerja paksa orang Mesir, melepaskan kamu dari perbudakan mereka dan menebus kamu dengan tangan yang teracung dan dengan hukuman-hukuman yang berat."
  },
  {Bible:"Exodus", Chapter:6, Verse:7, Page:1,
    Kor:"그래서 너희를 나의 백성으로 삼고, 나는 너희의 하나님이 될 것이다. 그러면 너희는, 내가 주 곧 너희를 이집트 사람의 강제노동에서 이끌어 낸 너희의 하나님임을 알게 될 것이다.",
    Chn:"我要以你们为我的百姓，我也要作你们的　神。你们要知道我是耶和华—你们的　神，是救你们脱离埃及人之重担的。",
    Eng:"I will take you as my own people, and I will be your God. Then you will know that I am the LORD your God, who brought you out from under the yoke of the Egyptians.",
    Ind:"(6-6) Aku akan mengangkat kamu menjadi umat-Ku dan Aku akan menjadi Allahmu, supaya kamu mengetahui, bahwa Akulah, TUHAN, Allahmu, yang membebaskan kamu dari kerja paksa orang Mesir."
  },
  {Bible:"Exodus", Chapter:6, Verse:8, Page:1,
    Kor:"내가, 아브라함과 이삭과 야곱에게 주기로 손을 들어 맹세한 그 땅으로 너희를 데리고 가서, 그 땅을 너희에게 주어, 너희의 소유가 되게 하겠다. 나는 주다.'\"",
    Chn:"我起誓应许给亚伯拉罕、以撒、雅各的那地，我要把你们领进去，将那地赐给你们为业。我是耶和华。』」",
    Eng:"And I will bring you to the land I swore with uplifted hand to give to Abraham, to Isaac and to Jacob. I will give it to you as a possession. I am the LORD.'\"",
    Ind:"(6-7) Dan Aku akan membawa kamu ke negeri yang dengan sumpah telah Kujanjikan memberikannya kepada Abraham, Ishak dan Yakub, dan Aku akan memberikannya kepadamu untuk menjadi milikmu; Akulah TUHAN.\""
  },
  {Bible:"Exodus", Chapter:6, Verse:9, Page:1,
    Kor:"모세가 이스라엘 자손에게 이와 같이 전하였으나, 그들은 무거운 노동에 지치고 기가 죽어서, 모세의 말을 들으려고 하지 않았다.",
    Chn:"摩西将这话告诉以色列人，只是他们因苦工愁烦，不肯听他的话。",
    Eng:"Moses reported this to the Israelites, but they did not listen to him because of their discouragement and cruel bondage.",
    Ind:"(6-8) Lalu Musa mengatakan demikian kepada orang Israel, tetapi mereka tidak mendengarkan Musa karena mereka putus asa dan karena perbudakan yang berat itu."
  },
  {Bible:"Exodus", Chapter:6, Verse:10, Page:1,
    Kor:"○주님께서 모세에게 이르셨다.",
    Chn:"耶和华晓谕摩西说：",
    Eng:"Then the LORD said to Moses,",
    Ind:"(6-9) Kemudian TUHAN berfirman kepada Musa:"
  },
  {Bible:"Exodus", Chapter:6, Verse:11, Page:1,
    Kor:"\"너는 이집트의 왕 바로에게 가서, 이스라엘 자손을 그의 나라에서 내보내라고 하여라.\"",
    Chn:"「你进去对埃及王法老说，要容以色列人出他的地。」",
    Eng:"\"Go, tell Pharaoh king of Egypt to let the Israelites go out of his country.\"",
    Ind:"(6-10) \"Pergilah menghadap, katakanlah kepada Firaun, raja Mesir, bahwa ia harus membiarkan orang Israel pergi dari negerinya.\""
  },
  {Bible:"Exodus", Chapter:6, Verse:12, Page:1,
    Kor:"이에 모세가 주님께 아뢰었다. \"이스라엘 자손도 저의 말을 듣지 않는데, 어찌 바로가 저의 말을 듣겠습니까? 저는 입이 둔하여 말을 할 줄 모릅니다.\"",
    Chn:"摩西在耶和华面前说：「以色列人尚且不听我的话，法老怎肯听我这拙口笨舌的人呢？」",
    Eng:"But Moses said to the LORD, \"If the Israelites will not listen to me, why would Pharaoh listen to me, since I speak with faltering lips?\"",
    Ind:"(6-11) Tetapi Musa berkata di hadapan TUHAN: \"Orang Israel sendiri tidak mendengarkan aku, bagaimanakah mungkin Firaun akan mendengarkan aku, aku seorang yang tidak petah lidahnya!\""
  },
  {Bible:"Exodus", Chapter:6, Verse:13, Page:1,
    Kor:"○주님께서는 모세와 아론에게 이스라엘 자손을 이집트 땅에서 인도하여 내라고 명하셨는데, 이 사실을 이스라엘 자손에게도 알리고 이집트 왕 바로에게도 알리라고 모세와 아론에게 명하셨다.",
    Chn:"耶和华吩咐摩西、亚伦往以色列人和埃及王法老那里去，把以色列人从埃及地领出来。",
    Eng:"Now the LORD spoke to Moses and Aaron about the Israelites and Pharaoh king of Egypt, and he commanded them to bring the Israelites out of Egypt.",
    Ind:"(6-12) Demikianlah TUHAN telah berfirman kepada Musa dan Harun, serta mengutus mereka kepada orang Israel dan kepada Firaun, raja Mesir, dengan membawa perintah supaya orang Israel dibawa keluar dari Mesir."
  },
  {Bible:"Exodus", Chapter:6, Verse:14, Page:1,
    Kor:"<모세와 아론의 족보> ○모세와 아론의 조상은 이러하다. ○이스라엘의 맏아들 르우벤의 아들들은 하녹과 발루와 헤스론과 갈미인데, 이들이 르우벤 가문이다.",
    Chn:"以色列人家长的名字记在下面。以色列长子吕便的儿子是哈诺、法路、希斯伦、迦米；这是吕便的各家。",
    Eng:"These were the heads of their families: The sons of Reuben the firstborn son of Israel were Hanoch and Pallu, Hezron and Carmi. These were the clans of Reuben.",
    Ind:"(6-13) Inilah para kepala kaum keluarga mereka: Anak-anak Ruben anak sulung Israel: Henokh, Palu, Hezron dan Karmi; itulah kaum-kaum Ruben."
  },
  {Bible:"Exodus", Chapter:6, Verse:15, Page:1,
    Kor:"○시므온의 아들들은 여무엘과 야민과 오핫과 야긴과 소할과, 가나안 여자가 낳은 아들 사울인데, 이들이 시므온 가문이다.",
    Chn:"西缅的儿子是耶母利、雅悯、阿辖、雅斤、琐辖，和迦南女子的儿子扫罗；这是西缅的各家。",
    Eng:"The sons of Simeon were Jemuel, Jamin, Ohad, Jakin, Zohar and Shaul the son of a Canaanite woman. These were the clans of Simeon.",
    Ind:"(6-14) Anak-anak Simeon: Yemuel, Yamin, Ohad, Yakhin, Zohar, dan Saul, anak seorang perempuan Kanaan; itulah kaum-kaum Simeon."
  },
  {Bible:"Exodus", Chapter:6, Verse:16, Page:1,
    Kor:"○레위의 아들들의 이름은, 그 태어난 순서대로, 게르손과 고핫과 므라리인데, 레위는 백삼십칠 년을 살았다.",
    Chn:"利未众子的名字按着他们的后代记在下面：就是革顺、哥辖、米拉利。利未一生的岁数是一百三十七岁。",
    Eng:"These were the names of the sons of Levi according to their records: Gershon, Kohath and Merari. Levi lived 137 years.",
    Ind:"(6-15) Inilah nama anak-anak Lewi menurut urutan kelahirannya: Gerson, Kehat dan Merari. Umur Lewi seratus tiga puluh tujuh tahun."
  },
  {Bible:"Exodus", Chapter:6, Verse:17, Page:1,
    Kor:"○게르손의 아들들은 가문별로는 립니와 시므이이다.",
    Chn:"革顺的儿子按着家室是立尼、示每。",
    Eng:"The sons of Gershon, by clans, were Libni and Shimei.",
    Ind:"(6-16) Anak-anak Gerson: Libni dan Simei, menurut kaum mereka."
  },
  {Bible:"Exodus", Chapter:6, Verse:18, Page:1,
    Kor:"○고핫의 아들들은 아므람과 이스할과 헤브론과 웃시엘인데, 고핫은 백삼십삼 년을 살았다.",
    Chn:"哥辖的儿子是暗兰、以斯哈、希伯伦、乌薛。哥辖一生的岁数是一百三十三岁。",
    Eng:"The sons of Kohath were Amram, Izhar, Hebron and Uzziel. Kohath lived 133 years.",
    Ind:"(6-17) Anak-anak Kehat: Amram, Yizhar, Hebron dan Uziel. Umur Kehat seratus tiga puluh tiga tahun."
  },
  {Bible:"Exodus", Chapter:6, Verse:19, Page:1,
    Kor:"○므라리의 아들들은 마흘리와 무시이다. ○이들이 세대별로 본 레위 가문이다.",
    Chn:"米拉利的儿子是抹利和母示；这是利未的家，都按着他们的后代。",
    Eng:"The sons of Merari were Mahli and Mushi. These were the clans of Levi according to their records.",
    Ind:"(6-18) Anak-anak Merari: Mahli dan Musi. Itulah kaum-kaum Lewi menurut urutannya."
  },
  {Bible:"Exodus", Chapter:6, Verse:20, Page:1,
    Kor:"○아므람은 자기의 고모 요게벳을 아내로 맞아 아론과 모세를 낳았다. 아므람은 백삼십칠 년을 살았다.",
    Chn:"暗兰娶了他父亲的妹妹约基别为妻，她给他生了亚伦和摩西。暗兰一生的岁数是一百三十七岁。",
    Eng:"Amram married his father's sister Jochebed, who bore him Aaron and Moses. Amram lived 137 years.",
    Ind:"(6-19) Dan Amram mengambil Yokhebed, saudara ayahnya, menjadi isterinya, dan perempuan ini melahirkan Harun dan Musa baginya. Umur Amram seratus tiga puluh tujuh tahun."
  },
  {Bible:"Exodus", Chapter:6, Verse:21, Page:1,
    Kor:"○이스할의 아들들은 고라와 네벡과 시그리이다.",
    Chn:"以斯哈的儿子是可拉、尼斐、细基利。",
    Eng:"The sons of Izhar were Korah, Nepheg and Zicri.",
    Ind:"(6-20) Anak-anak Yizhar: Korah, Nefeg dan Zikhri."
  },
  {Bible:"Exodus", Chapter:6, Verse:22, Page:1,
    Kor:"○웃시엘의 아들들은 미사엘과 엘사반과 시드리이다.",
    Chn:"乌薛的儿子是米沙利、以利撒反、西提利。",
    Eng:"The sons of Uzziel were Mishael, Elzaphan and Sithri.",
    Ind:"(6-21) Anak-anak Uziel: Misael, Elsafan dan Sitri."
  },
  {Bible:"Exodus", Chapter:6, Verse:23, Page:1,
    Kor:"○아론은, 암미나답의 딸이요 나손의 누이인 엘리세바와 결혼하여, 나답과 아비후와 엘르아살과 이다말을 낳았다.",
    Chn:"亚伦娶了亚米拿达的女儿，拿顺的妹妹，以利沙巴为妻，她给他生了拿答、亚比户、以利亚撒、以他玛。",
    Eng:"Aaron married Elisheba, daughter of Amminadab and sister of Nahshon, and she bore him Nadab and Abihu, Eleazar and Ithamar.",
    Ind:"(6-22) Dan Harun mengambil Eliseba, anak perempuan Aminadab, saudara perempuan Nahason, menjadi isterinya, dan perempuan ini melahirkan baginya Nadab, Abihu, Eleazar dan Itamar."
  },
  {Bible:"Exodus", Chapter:6, Verse:24, Page:1,
    Kor:"○고라의 아들들은 앗실과 엘가나와 아비아삽인데, 이들은 고라 가문이다.",
    Chn:"可拉的儿子是亚惜、以利加拿、亚比亚撒；这是可拉的各家。",
    Eng:"The sons of Korah were Assir, Elkanah and Abiasaph. These were the Korahite clans.",
    Ind:"(6-23) Anak-anak Korah: Asir, Elkana dan Abiasaf; itulah kaum-kaum orang Korah."
  },
  {Bible:"Exodus", Chapter:6, Verse:25, Page:1,
    Kor:"○아론의 아들 엘르아살은 부디엘의 한 딸과 결혼하여, 비느하스를 낳았다. 이들이 다 가문별로 본 레위 일가의 조상이다.",
    Chn:"亚伦的儿子以利亚撒娶了普铁的一个女儿为妻，她给他生了非尼哈。这是利未人的家长，都按着他们的家。",
    Eng:"Eleazar son of Aaron married one of the daughters of Putiel, and she bore him Phinehas. These were the heads of the Levite families, clan by clan.",
    Ind:"(6-24) Eleazar, anak Harun, mengambil salah seorang anak perempuan Putiel menjadi isterinya dan perempuan ini melahirkan Pinehas baginya. Itulah para kepala kaum keluarga orang Lewi menurut kaum mereka."
  },
  {Bible:"Exodus", Chapter:6, Verse:26, Page:1,
    Kor:"○이스라엘 자손을 부대별로 편성하여 이집트 땅에서 인도하여 내라는 주님의 분부를 받은 이들이, 바로 이들 아론과 모세이고,",
    Chn:"耶和华说：「将以色列人按着他们的军队从埃及地领出来。」这是对那亚伦、摩西说的。",
    Eng:"It was this same Aaron and Moses to whom the LORD said, \"Bring the Israelites out of Egypt by their divisions.\"",
    Ind:"(6-25) Itulah Harun dan Musa, yang diperintahkan TUHAN: \"Bawalah orang Israel keluar dari tanah Mesir menurut pasukan mereka.\""
  },
  {Bible:"Exodus", Chapter:6, Verse:27, Page:1,
    Kor:"이집트의 왕 바로에게 가서 이스라엘 자손을 내보내 달라고 말한 이들도, 바로 이들 모세와 아론이다.",
    Chn:"对埃及王法老说要将以色列人从埃及领出来的，就是这摩西、亚伦。",
    Eng:"They were the ones who spoke to Pharaoh king of Egypt about bringing the Israelites out of Egypt. It was the same Moses and Aaron.",
    Ind:"(6-26) Merekalah yang berbicara kepada Firaun, raja Mesir, supaya mereka membawa orang Israel keluar dari Mesir. Itulah Musa dan Harun."
  },
  {Bible:"Exodus", Chapter:6, Verse:28, Page:1,
    Kor:"<모세와 아론에게 내린 주님의 명령> ○주님께서 이집트 땅에서 모세에게 말씀하실 때이다.",
    Chn:"当耶和华在埃及地对摩西说话的日子，",
    Eng:"Now when the LORD spoke to Moses in Egypt,",
    Ind:"(6-27) Pada waktu TUHAN berfirman kepada Musa di tanah Mesir,"
  },
  {Bible:"Exodus", Chapter:6, Verse:29, Page:1,
    Kor:"주님께서 모세에게 이르시기를 \"나는 주다. 너는 내가 너에게 하는 말을 모두 이집트의 임금 바로에게 전하여라\" 하셨다.",
    Chn:"他向摩西说：「我是耶和华；我对你说的一切话，你都要告诉埃及王法老。」",
    Eng:"he said to him, \"I am the LORD. Tell Pharaoh king of Egypt everything I tell you.\"",
    Ind:"(6-28) TUHAN berfirman kepadanya: \"Akulah TUHAN; katakanlah kepada Firaun, raja Mesir, segala yang Kufirmankan kepadamu.\""
  },
  {Bible:"Exodus", Chapter:6, Verse:30, Page:1,
    Kor:"그러나 모세는 주님께 이렇게 대답하였다. \"보십시오, 저는 입이 둔하여 말을 할 줄 모릅니다. 바로가 어찌 저의 말을 듣겠습니까?\"",
    Chn:"摩西在耶和华面前说：「看哪，我是拙口笨舌的人，法老怎肯听我呢？」",
    Eng:"But Moses said to the LORD, \"Since I speak with faltering lips, why would Pharaoh listen to me?\"",
    Ind:"(6-29) Tetapi Musa berkata di hadapan TUHAN: \"Bukankah aku ini seorang yang tidak petah lidahnya, bagaimanakah mungkin Firaun akan mendengarkan aku?\""
  },
]);
