// 출애굽기 8장 · Exodus 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Exodus",8,32);
BibleDB.add([
  {Bible:"Exodus", Chapter:8, Verse:1, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said to Moses, \"Go to Pharaoh and say to him, 'This is what the LORD says: Let my people go, so that they may worship me.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:2, Page:1, Kor:"", Chn:"", Eng:"If you refuse to let them go, I will plague your whole country with frogs.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:3, Page:1, Kor:"", Chn:"", Eng:"The Nile will teem with frogs. They will come up into your palace and your bedroom and onto your bed, into the houses of your officials and on your people, and into your ovens and kneading troughs.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:4, Page:1, Kor:"", Chn:"", Eng:"The frogs will go up on you and your people and all your officials.'\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said to Moses, \"Tell Aaron, 'Stretch out your hand with your staff over the streams and canals and ponds, and make frogs come up on the land of Egypt.'\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:6, Page:1, Kor:"", Chn:"", Eng:"So Aaron stretched out his hand over the waters of Egypt, and the frogs came up and covered the land.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:7, Page:1, Kor:"", Chn:"", Eng:"But the magicians did the same things by their secret arts; they also made frogs come up on the land of Egypt.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Pharaoh summoned Moses and Aaron and said, \"Pray to the LORD to take the frogs away from me and my people, and I will let your people go to offer sacrifices to the LORD.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Moses said to Pharaoh, \"I leave to you the honor of setting the time for me to pray for you and your officials and your people that you and your houses may be rid of the frogs, except for those that remain in the Nile.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:10, Page:1, Kor:"", Chn:"", Eng:"\"Tomorrow,\" Pharaoh said. Moses replied, \"It will be as you say, so that you may know there is no one like the LORD our God.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:11, Page:1, Kor:"", Chn:"", Eng:"The frogs will leave you and your houses, your officials and your people; they will remain only in the Nile.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:12, Page:1, Kor:"", Chn:"", Eng:"After Moses and Aaron left Pharaoh, Moses cried out to the LORD about the frogs he had brought on Pharaoh.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:13, Page:1, Kor:"", Chn:"", Eng:"And the LORD did what Moses asked. The frogs died in the houses, in the courtyards and in the fields.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:14, Page:1, Kor:"", Chn:"", Eng:"They were piled into heaps, and the land reeked of them.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:15, Page:1, Kor:"", Chn:"", Eng:"But when Pharaoh saw that there was relief, he hardened his heart and would not listen to Moses and Aaron, just as the LORD had said.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:16, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said to Moses, \"Tell Aaron, 'Stretch out your staff and strike the dust of the ground,' and throughout the land of Egypt the dust will become gnats.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:17, Page:1, Kor:"", Chn:"", Eng:"They did this, and when Aaron stretched out his hand with the staff and struck the dust of the ground, gnats came upon men and animals. All the dust throughout the land of Egypt became gnats.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:18, Page:1, Kor:"", Chn:"", Eng:"But when the magicians tried to produce gnats by their secret arts, they could not. And the gnats were on men and animals.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:19, Page:1, Kor:"", Chn:"", Eng:"The magicians said to Pharaoh, \"This is the finger of God.\" But Pharaoh's heart was hard and he would not listen, just as the LORD had said.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said to Moses, \"Get up early in the morning and confront Pharaoh as he goes to the water and say to him, 'This is what the LORD says: Let my people go, so that they may worship me.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:21, Page:1, Kor:"", Chn:"", Eng:"If you do not let my people go, I will send swarms of flies on you and your officials, on your people and into your houses. The houses of the Egyptians will be full of flies, and even the ground where they are.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:22, Page:1, Kor:"", Chn:"", Eng:"\"'But on that day I will deal differently with the land of Goshen, where my people live; no swarms of flies will be there, so that you will know that I, the LORD, am in this land.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:23, Page:1, Kor:"", Chn:"", Eng:"I will make a distinction between my people and your people. This miraculous sign will occur tomorrow.'\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:24, Page:1, Kor:"", Chn:"", Eng:"And the LORD did this. Dense swarms of flies poured into Pharaoh's palace and into the houses of his officials, and throughout Egypt the land was ruined by the flies.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Then Pharaoh summoned Moses and Aaron and said, \"Go, sacrifice to your God here in the land.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:26, Page:1, Kor:"", Chn:"", Eng:"But Moses said, \"That would not be right. The sacrifices we offer the LORD our God would be detestable to the Egyptians. And if we offer sacrifices that are detestable in their eyes, will they not stone us?", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:27, Page:1, Kor:"", Chn:"", Eng:"We must take a three-day journey into the desert to offer sacrifices to the LORD our God, as he commands us.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Pharaoh said, \"I will let you go to offer sacrifices to the LORD your God in the desert, but you must not go very far. Now pray for me.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Moses answered, \"As soon as I leave you, I will pray to the LORD, and tomorrow the flies will leave Pharaoh and his officials and his people. Only be sure that Pharaoh does not act deceitfully again by not letting the people go to offer sacrifices to the LORD.\"", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:30, Page:1, Kor:"", Chn:"", Eng:"Then Moses left Pharaoh and prayed to the LORD,", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:31, Page:1, Kor:"", Chn:"", Eng:"and the LORD did what Moses asked: The flies left Pharaoh and his officials and his people; not a fly remained.", Ind:""},
  {Bible:"Exodus", Chapter:8, Verse:32, Page:1, Kor:"", Chn:"", Eng:"But this time also Pharaoh hardened his heart and would not let the people go.", Ind:""},
]);
