// 요한복음 6장 · John 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("John",6,71);
BibleDB.add([
  {Bible:"John", Chapter:6, Verse:1, Page:1,
    Kor:"<오천 명을 먹이시다(마 14:13-21; 막 6:30-44; 눅 9:10-17)> 그 뒤에 예수께서 a갈릴리 바다 곧 디베랴 바다 건너편으로 가시니(a 그, '티베리우스의 갈릴리 바다')",
    Chn:"这事以后，耶稣渡过加利利海，就是提比哩亚海。",
    Eng:"Some time after this, Jesus crossed to the far shore of the Sea of Galilee (that is, the Sea of Tiberias),",
    Ind:"Sesudah itu Yesus berangkat ke seberang danau Galilea, yaitu danau Tiberias."
  },
  {Bible:"John", Chapter:6, Verse:2, Page:1,
    Kor:"큰 무리가 예수를 따라갔다. 그것은, 그들이 예수가 병자들을 고치신 b표징들을 보았기 때문이다.(b 예수의 신성을 보여주기 위한 상징으로서의 기적(그리스어 세메이온))",
    Chn:"有许多人因为看见他在病人身上所行的神迹，就跟随他。",
    Eng:"and a great crowd of people followed him because they saw the miraculous signs he had performed on the sick.",
    Ind:"Orang banyak berbondong-bondong mengikuti Dia, karena mereka melihat mujizat-mujizat penyembuhan, yang diadakan-Nya terhadap orang-orang sakit."
  },
  {Bible:"John", Chapter:6, Verse:3, Page:1,
    Kor:"예수께서 산에 올라가서, 제자들과 함께 앉으셨다.",
    Chn:"耶稣上了山，和门徒一同坐在那里。",
    Eng:"Then Jesus went up on a mountainside and sat down with his disciples.",
    Ind:"Dan Yesus naik ke atas gunung dan duduk di situ dengan murid-murid-Nya."
  },
  {Bible:"John", Chapter:6, Verse:4, Page:1,
    Kor:"마침 유대 사람의 명절인 c유월절이 가까운 때였다.(c 출 12:13, 21-28을 볼 것)",
    Chn:"那时犹太人的逾越节近了。",
    Eng:"The Jewish Passover Feast was near.",
    Ind:"Dan Paskah, hari raya orang Yahudi, sudah dekat."
  },
  {Bible:"John", Chapter:6, Verse:5, Page:1,
    Kor:"예수께서 눈을 들어서, 큰 무리가 자기에게로 모여드는 것을 보시고, 빌립에게 말씀하셨다. \"우리가 어디에서 빵을 사다가, 이 사람들을 먹이겠느냐?\"",
    Chn:"耶稣举目看见许多人来，就对腓力说：「我们从哪里买饼叫这些人吃呢？」（",
    Eng:"When Jesus looked up and saw a great crowd coming toward him, he said to Philip, \"Where shall we buy bread for these people to eat?\"",
    Ind:"Ketika Yesus memandang sekeliling-Nya dan melihat, bahwa orang banyak berbondong-bondong datang kepada-Nya, berkatalah Ia kepada Filipus: \"Di manakah kita akan membeli roti, supaya mereka ini dapat makan?\""
  },
  {Bible:"John", Chapter:6, Verse:6, Page:1,
    Kor:"예수께서는 빌립을 시험해 보시고자 이렇게 말씀하신 것이었다. 예수께서는 자기가 하실 일을 잘 알고 계셨던 것이다.",
    Chn:"他说这话是要试验腓力；他自己原知道要怎样行。）",
    Eng:"He asked this only to test him, for he already had in mind what he was going to do.",
    Ind:"Hal itu dikatakan-Nya untuk mencobai dia, sebab Ia sendiri tahu, apa yang hendak dilakukan-Nya."
  },
  {Bible:"John", Chapter:6, Verse:7, Page:1,
    Kor:"빌립이 예수께 이렇게 대답하였다. \"이 사람들에게 모두 조금씩이라도 먹게 하려면, 빵 이백 d데나리온어치를 가지고서도 충분하지 못합니다.\"(d 한 데나리온은 노동자의 하루 품삯)",
    Chn:"腓力回答说：「就是二十两银子的饼，叫他们各人吃一点也是不够的。」",
    Eng:"Philip answered him, \"Eight months' wages would not buy enough bread for each one to have a bite!\"",
    Ind:"Jawab Filipus kepada-Nya: \"Roti seharga dua ratus dinar tidak akan cukup untuk mereka ini, sekalipun masing-masing mendapat sepotong kecil saja.\""
  },
  {Bible:"John", Chapter:6, Verse:8, Page:1,
    Kor:"제자 가운데 하나이며 시몬 베드로와 형제간인 안드레가 예수께 말하였다.",
    Chn:"有一个门徒，就是西门·彼得的兄弟安得烈，对耶稣说：",
    Eng:"Another of his disciples, Andrew, Simon Peter's brother, spoke up,",
    Ind:"Seorang dari murid-murid-Nya, yaitu Andreas, saudara Simon Petrus, berkata kepada-Nya:"
  },
  {Bible:"John", Chapter:6, Verse:9, Page:1,
    Kor:"\"여기에 보리빵 다섯 개와 물고기 두 마리를 가지고 있는 한 아이가 있습니다. 그러나 이렇게 많은 사람에게 그것이 무슨 소용이 있겠습니까?\"",
    Chn:"「在这里有一个孩童，带着五个大麦饼、两条鱼，只是分给这许多人还算什么呢？」",
    Eng:"\"Here is a boy with five small barley loaves and two small fish, but how far will they go among so many?\"",
    Ind:"\"Di sini ada seorang anak, yang mempunyai lima roti jelai dan dua ikan; tetapi apakah artinya itu untuk orang sebanyak ini?\""
  },
  {Bible:"John", Chapter:6, Verse:10, Page:1,
    Kor:"예수께서는 \"사람들을 앉게 하여라\" 하고 말씀하셨다. 그 곳에는 풀이 많았다. 그래서 그들이 앉았는데, 남자의 수가 오천 명쯤 되었다.",
    Chn:"耶稣说：「你们叫众人坐下。」原来那地方的草多，众人就坐下，数目约有五千。",
    Eng:"Jesus said, \"Have the people sit down.\" There was plenty of grass in that place, and the men sat down, about five thousand of them.",
    Ind:"Kata Yesus: \"Suruhlah orang-orang itu duduk.\" Adapun di tempat itu banyak rumput. Maka duduklah orang-orang itu, kira-kira lima ribu laki-laki banyaknya."
  },
  {Bible:"John", Chapter:6, Verse:11, Page:1,
    Kor:"예수께서 빵을 들어서 감사를 드리신 다음에, 앉은 사람들에게 나누어주시고, 물고기도 그와 같이 해서, 그들이 원하는 대로 주셨다.",
    Chn:"耶稣拿起饼来，祝谢了，就分给那坐着的人；分鱼也是这样，都随着他们所要的。",
    Eng:"Jesus then took the loaves, gave thanks, and distributed to those who were seated as much as they wanted. He did the same with the fish.",
    Ind:"Lalu Yesus mengambil roti itu, mengucap syukur dan membagi-bagikannya kepada mereka yang duduk di situ, demikian juga dibuat-Nya dengan ikan-ikan itu, sebanyak yang mereka kehendaki."
  },
  {Bible:"John", Chapter:6, Verse:12, Page:1,
    Kor:"그들이 배불리 먹은 뒤에, 예수께서 제자들에게 이렇게 말씀하셨다. \"남은 부스러기를 다 모으고, 조금도 버리지 말아라.\"",
    Chn:"他们吃饱了，耶稣对门徒说：「把剩下的零碎收拾起来，免得有糟蹋的。」",
    Eng:"When they had all had enough to eat, he said to his disciples, \"Gather the pieces that are left over. Let nothing be wasted.\"",
    Ind:"Dan setelah mereka kenyang Ia berkata kepada murid-murid-Nya: \"Kumpulkanlah potongan-potongan yang lebih supaya tidak ada yang terbuang.\""
  },
  {Bible:"John", Chapter:6, Verse:13, Page:1,
    Kor:"그래서 보리빵 다섯 덩이에서, 먹고 남은 부스러기를 모으니, 열두 광주리에 가득 찼다.",
    Chn:"他们便将那五个大麦饼的零碎，就是众人吃了剩下的，收拾起来，装满了十二个篮子。",
    Eng:"So they gathered them and filled twelve baskets with the pieces of the five barley loaves left over by those who had eaten.",
    Ind:"Maka merekapun mengumpulkannya, dan mengisi dua belas bakul penuh dengan potongan-potongan dari kelima roti jelai yang lebih setelah orang makan."
  },
  {Bible:"John", Chapter:6, Verse:14, Page:1,
    Kor:"사람들은 예수께서 행하신 b표징을 보고 \"이분은 참으로 세상에 오시기로 된 그 예언자이다\" 하고 말하였다.(b 예수의 신성을 보여주기 위한 상징으로서의 기적(그리스어 세메이온))",
    Chn:"众人看见耶稣所行的神迹，就说：「这真是那要到世间来的先知！」",
    Eng:"After the people saw the miraculous sign that Jesus did, they began to say, \"Surely this is the Prophet who is to come into the world.\"",
    Ind:"Ketika orang-orang itu melihat mujizat yang telah diadakan-Nya, mereka berkata: \"Dia ini adalah benar-benar nabi yang akan datang ke dalam dunia.\""
  },
  {Bible:"John", Chapter:6, Verse:15, Page:1,
    Kor:"예수께서는, 사람들이 와서 억지로 자기를 모셔다가 왕으로 삼으려고 한다는 것을 아시고, 혼자서 다시 산으로 물러가셨다.",
    Chn:"耶稣既知道众人要来强逼他作王，就独自又退到山上去了。",
    Eng:"Jesus, knowing that they intended to come and make him king by force, withdrew again to a mountain by himself.",
    Ind:"Karena Yesus tahu, bahwa mereka hendak datang dan hendak membawa Dia dengan paksa untuk menjadikan Dia raja, Ia menyingkir pula ke gunung, seorang diri."
  },
  {Bible:"John", Chapter:6, Verse:16, Page:1,
    Kor:"<예수께서 물 위를 걸으시다(마 14:22-27; 막 6:45-52)> ○날이 저물었을 때에, 예수의 제자들은 바다로 내려가서,",
    Chn:"到了晚上，他的门徒下海边去，",
    Eng:"When evening came, his disciples went down to the lake,",
    Ind:"Dan ketika hari sudah mulai malam, murid-murid Yesus pergi ke danau, lalu naik ke perahu"
  },
  {Bible:"John", Chapter:6, Verse:17, Page:1,
    Kor:"배를 타고, 바다 건너편 가버나움으로 갔다. 이미 어두워졌는데도, 예수께서는 아직 그들이 있는 곳으로 오시지 않았다.",
    Chn:"上了船，要过海往迦百农去。天已经黑了，耶稣还没有来到他们那里。",
    Eng:"where they got into a boat and set off across the lake for Capernaum. By now it was dark, and Jesus had not yet joined them.",
    Ind:"dan menyeberang ke Kapernaum. Ketika hari sudah gelap Yesus belum juga datang mendapatkan mereka,"
  },
  {Bible:"John", Chapter:6, Verse:18, Page:1,
    Kor:"그런데 큰 바람이 불고, 물결이 사나워졌다.",
    Chn:"忽然狂风大作，海就翻腾起来。",
    Eng:"A strong wind was blowing and the waters grew rough.",
    Ind:"sedang laut bergelora karena angin kencang."
  },
  {Bible:"John", Chapter:6, Verse:19, Page:1,
    Kor:"제자들이 배를 저어서, e십여 리쯤 갔을 때였다. 그들은, 예수께서 바다 위로 걸어서 배에 가까이 오시는 것을 보고, 무서워하였다.(e 그, '이십오에서 삼십 스타디아쯤'. 약 5-6킬로미터)",
    Chn:"门徒摇橹，约行了十里多路，看见耶稣在海面上走，渐渐近了船，他们就害怕。",
    Eng:"When they had rowed three or three and a half miles, they saw Jesus approaching the boat, walking on the water; and they were terrified.",
    Ind:"Sesudah mereka mendayung kira-kira dua tiga mil jauhnya, mereka melihat Yesus berjalan di atas air mendekati perahu itu. Maka ketakutanlah mereka."
  },
  {Bible:"John", Chapter:6, Verse:20, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"나다. 두려워하지 말아라.\"",
    Chn:"耶稣对他们说：「是我，不要怕！」",
    Eng:"But he said to them, \"It is I; don't be afraid.\"",
    Ind:"Tetapi Ia berkata kepada mereka: \"Aku ini, jangan takut!\""
  },
  {Bible:"John", Chapter:6, Verse:21, Page:1,
    Kor:"그래서 그들은 기꺼이 예수를 배 안으로 모셔들였다. 배는 곧 그들이 가려던 땅에 이르렀다.",
    Chn:"门徒就喜欢接他上船，船立时到了他们所要去的地方。",
    Eng:"Then they were willing to take him into the boat, and immediately the boat reached the shore where they were heading.",
    Ind:"Mereka mau menaikkan Dia ke dalam perahu, dan seketika juga perahu itu sampai ke pantai yang mereka tujui."
  },
  {Bible:"John", Chapter:6, Verse:22, Page:1,
    Kor:"<예수는 생명의 빵이시다> ○그 다음날이었다. 바다 건너편에 서 있던 무리는, 거기에 배 한 척만 있었다는 것과, 예수께서는 제자들과 함께 그 배를 타지 않으셨고, 제자들만 따로 떠나갔다는 것을 알았다.",
    Chn:"第二日，站在海那边的众人知道那里没有别的船，只有一只小船，又知道耶稣没有同他的门徒上船，乃是门徒自己去的。",
    Eng:"The next day the crowd that had stayed on the opposite shore of the lake realized that only one boat had been there, and that Jesus had not entered it with his disciples, but that they had gone away alone.",
    Ind:"Pada keesokan harinya orang banyak, yang masih tinggal di seberang, melihat bahwa di situ tidak ada perahu selain dari pada yang satu tadi dan bahwa Yesus tidak turut naik ke perahu itu bersama-sama dengan murid-murid-Nya, dan bahwa murid-murid-Nya saja yang berangkat."
  },
  {Bible:"John", Chapter:6, Verse:23, Page:1,
    Kor:"그런데 디베랴에서 온 배 몇 척이, f주님께서 감사 기도를 드리고 무리에게 빵을 먹이신 곳에 가까이 닿았다.(f 다른 고대 사본들에는 '주님께서 감사 기도를 드리고'가 없음)",
    Chn:"然而，有几只小船从提比哩亚来，靠近主祝谢后分饼给人吃的地方。",
    Eng:"Then some boats from Tiberias landed near the place where the people had eaten the bread after the Lord had given thanks.",
    Ind:"Tetapi sementara itu beberapa perahu lain datang dari Tiberias dekat ke tempat mereka makan roti, sesudah Tuhan mengucapkan syukur atasnya."
  },
  {Bible:"John", Chapter:6, Verse:24, Page:1,
    Kor:"무리는 거기에 예수도 안 계시고 제자들도 없는 것을 알고서, 배를 나누어 타고, 예수를 찾아 가버나움으로 갔다.",
    Chn:"众人见耶稣和门徒都不在那里，就上了船，往迦百农去找耶稣。",
    Eng:"Once the crowd realized that neither Jesus nor his disciples were there, they got into the boats and went to Capernaum in search of Jesus.",
    Ind:"Ketika orang banyak melihat, bahwa Yesus tidak ada di situ dan murid-murid-Nya juga tidak, mereka naik ke perahu-perahu itu lalu berangkat ke Kapernaum untuk mencari Yesus."
  },
  {Bible:"John", Chapter:6, Verse:25, Page:1,
    Kor:"그들은 바다 건너편에서 예수를 만나서 말하였다. \"선생님, 언제 여기에 오셨습니까?\"",
    Chn:"既在海那边找着了，就对他说：「拉比，是几时到这里来的？」",
    Eng:"When they found him on the other side of the lake, they asked him, \"Rabbi, when did you get here?\"",
    Ind:"Ketika orang banyak menemukan Yesus di seberang laut itu, mereka berkata kepada-Nya: \"Rabi, bilamana Engkau tiba di sini?\""
  },
  {Bible:"John", Chapter:6, Verse:26, Page:1,
    Kor:"예수께서 그들에게 대답하셨다. \"내가 진정으로 진정으로 너희에게 말한다. 너희가 나를 찾는 것은 b표징을 보았기 때문이 아니라, 빵을 먹고 배가 불렀기 때문이다.(b 예수의 신성을 보여주기 위한 상징으로서의 기적(그리스어 세메이온))",
    Chn:"耶稣回答说：「我实实在在地告诉你们，你们找我，并不是因见了神迹，乃是因吃饼得饱。",
    Eng:"Jesus answered, \"I tell you the truth, you are looking for me, not because you saw miraculous signs but because you ate the loaves and had your fill.",
    Ind:"Yesus menjawab mereka: \"Aku berkata kepadamu, sesungguhnya kamu mencari Aku, bukan karena kamu telah melihat tanda-tanda, melainkan karena kamu telah makan roti itu dan kamu kenyang."
  },
  {Bible:"John", Chapter:6, Verse:27, Page:1,
    Kor:"너희는 썩어 없어질 양식을 얻으려고 일하지 말고, 영생에 이르도록 남아 있을 양식을 얻으려고 일하여라. 이 양식은, 인자가 너희에게 줄 것이다. 아버지 하나님께서 인자를 인정하셨기 때문이다.\"",
    Chn:"不要为那必坏的食物劳力，要为那存到永生的食物劳力，就是人子要赐给你们的，因为人子是父　神所印证的。」",
    Eng:"Do not work for food that spoils, but for food that endures to eternal life, which the Son of Man will give you. On him God the Father has placed his seal of approval.\"",
    Ind:"Bekerjalah, bukan untuk makanan yang akan dapat binasa, melainkan untuk makanan yang bertahan sampai kepada hidup yang kekal, yang akan diberikan Anak Manusia kepadamu; sebab Dialah yang disahkan oleh Bapa, Allah, dengan meterai-Nya.\""
  },
  {Bible:"John", Chapter:6, Verse:28, Page:1,
    Kor:"그들이 예수께 물었다. \"우리가 무엇을 하여야 하나님의 일을 하는 것이 됩니까?\"",
    Chn:"众人问他说：「我们当行什么才算做　神的工呢？」",
    Eng:"Then they asked him, \"What must we do to do the works God requires?\"",
    Ind:"Lalu kata mereka kepada-Nya: \"Apakah yang harus kami perbuat, supaya kami mengerjakan pekerjaan yang dikehendaki Allah?\""
  },
  {Bible:"John", Chapter:6, Verse:29, Page:1,
    Kor:"예수께서 그들에게 대답하셨다. \"하나님께서 보내신 이를 믿는 것이 곧 하나님의 일이다.\"",
    Chn:"耶稣回答说：「信　神所差来的，这就是做　神的工。」",
    Eng:"Jesus answered, \"The work of God is this: to believe in the one he has sent.\"",
    Ind:"Jawab Yesus kepada mereka: \"Inilah pekerjaan yang dikehendaki Allah, yaitu hendaklah kamu percaya kepada Dia yang telah diutus Allah.\""
  },
  {Bible:"John", Chapter:6, Verse:30, Page:1,
    Kor:"그들은 다시 물었다. \"우리에게 무슨 b표징을 행하셔서, 우리로 하여금 보고 당신을 믿게 하시겠습니까? 당신이 하시는 일이 무엇입니까?(b 예수의 신성을 보여주기 위한 상징으로서의 기적(그리스어 세메이온))",
    Chn:"他们又说：「你行什么神迹，叫我们看见就信你；你到底做什么事呢？",
    Eng:"So they asked him, \"What miraculous sign then will you give that we may see it and believe you? What will you do?",
    Ind:"Maka kata mereka kepada-Nya: \"Tanda apakah yang Engkau perbuat, supaya dapat kami melihatnya dan percaya kepada-Mu? Pekerjaan apakah yang Engkau lakukan?"
  },
  {Bible:"John", Chapter:6, Verse:31, Page:1,
    Kor:"g'그는 하늘에서 빵을 내려서, 그들에게 먹게 하셨다' 한 성경 말씀대로, 우리 조상들은 광야에서 만나를 먹었습니다.\"(g 출 16:4, 5; 시 78:24)",
    Chn:"我们的祖宗在旷野吃过吗哪，如经上写着说：『他从天上赐下粮来给他们吃。』」",
    Eng:"Our forefathers ate the manna in the desert; as it is written: 'He gave them bread from heaven to eat.'\"",
    Ind:"Nenek moyang kami telah makan manna di padang gurun, seperti ada tertulis: Mereka diberi-Nya makan roti dari sorga.\""
  },
  {Bible:"John", Chapter:6, Verse:32, Page:1,
    Kor:"예수께서 그들에게 대답하셨다. \"내가 진정으로 진정으로 너희에게 말한다. 하늘에서 너희에게 빵을 내려다 주신 이는 모세가 아니다. 하늘에서 참 빵을 너희에게 주시는 분은 내 아버지시다.",
    Chn:"耶稣说：「我实实在在地告诉你们，那从天上来的粮不是摩西赐给你们的，乃是我父将天上来的真粮赐给你们。",
    Eng:"Jesus said to them, \"I tell you the truth, it is not Moses who has given you the bread from heaven, but it is my Father who gives you the true bread from heaven.",
    Ind:"Maka kata Yesus kepada mereka: \"Aku berkata kepadamu, sesungguhnya bukan Musa yang memberikan kamu roti dari sorga, melainkan Bapa-Ku yang memberikan kamu roti yang benar dari sorga."
  },
  {Bible:"John", Chapter:6, Verse:33, Page:1,
    Kor:"하나님의 빵은 하늘에서 내려와 세상에 생명을 주는 것이다.\"",
    Chn:"因为　神的粮就是那从天上降下来、赐生命给世界的。」",
    Eng:"For the bread of God is he who comes down from heaven and gives life to the world.\"",
    Ind:"Karena roti yang dari Allah ialah roti yang turun dari sorga dan yang memberi hidup kepada dunia.\""
  },
  {Bible:"John", Chapter:6, Verse:34, Page:1,
    Kor:"○그들은 예수께 말하였다. \"주님, 그 빵을 언제나 우리에게 주십시오.\"",
    Chn:"他们说：「主啊，常将这粮赐给我们！」",
    Eng:"\"Sir,\" they said, \"from now on give us this bread.\"",
    Ind:"Maka kata mereka kepada-Nya: \"Tuhan, berikanlah kami roti itu senantiasa.\""
  },
  {Bible:"John", Chapter:6, Verse:35, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"내가 생명의 빵이다. 내게로 오는 사람은 결코 주리지 않을 것이요, 나를 믿는 사람은 다시는 목마르지 않을 것이다.",
    Chn:"耶稣说：「我就是生命的粮。到我这里来的，必定不饿；信我的，永远不渴。",
    Eng:"Then Jesus declared, \"I am the bread of life. He who comes to me will never go hungry, and he who believes in me will never be thirsty.",
    Ind:"Kata Yesus kepada mereka: \"Akulah roti hidup; barangsiapa datang kepada-Ku, ia tidak akan lapar lagi, dan barangsiapa percaya kepada-Ku, ia tidak akan haus lagi."
  },
  {Bible:"John", Chapter:6, Verse:36, Page:1,
    Kor:"그러나 내가 이미 말한 대로, 너희는 <나를> 보고도 믿지 않는다.",
    Chn:"只是我对你们说过，你们已经看见我，还是不信。",
    Eng:"But as I told you, you have seen me and still you do not believe.",
    Ind:"Tetapi Aku telah berkata kepadamu: Sungguhpun kamu telah melihat Aku, kamu tidak percaya."
  },
  {Bible:"John", Chapter:6, Verse:37, Page:1,
    Kor:"아버지께서 내게 주시는 사람은 다 내게로 올 것이요, 또 내게로 오는 사람은 내가 물리치지 않을 것이다.",
    Chn:"凡父所赐给我的人必到我这里来；到我这里来的，我总不丢弃他。",
    Eng:"All that the Father gives me will come to me, and whoever comes to me I will never drive away.",
    Ind:"Semua yang diberikan Bapa kepada-Ku akan datang kepada-Ku, dan barangsiapa datang kepada-Ku, ia tidak akan Kubuang."
  },
  {Bible:"John", Chapter:6, Verse:38, Page:1,
    Kor:"그것은, 내가 내 뜻을 행하려고 하늘에서 내려온 것이 아니라, 나를 보내신 분의 뜻을 행하려고 왔기 때문이다.",
    Chn:"因为我从天上降下来，不是要按自己的意思行，乃是要按那差我来者的意思行。",
    Eng:"For I have come down from heaven not to do my will but to do the will of him who sent me.",
    Ind:"Sebab Aku telah turun dari sorga bukan untuk melakukan kehendak-Ku, tetapi untuk melakukan kehendak Dia yang telah mengutus Aku."
  },
  {Bible:"John", Chapter:6, Verse:39, Page:1,
    Kor:"나를 보내신 분의 뜻은, 내게 주신 사람을 내가 한 사람도 잃어버리지 않고, 마지막 날에 모두 살리는 일이다.",
    Chn:"差我来者的意思就是：他所赐给我的，叫我一个也不失落，在末日却叫他复活。",
    Eng:"And this is the will of him who sent me, that I shall lose none of all that he has given me, but raise them up at the last day.",
    Ind:"Dan Inilah kehendak Dia yang telah mengutus Aku, yaitu supaya dari semua yang telah diberikan-Nya kepada-Ku jangan ada yang hilang, tetapi supaya Kubangkitkan pada akhir zaman."
  },
  {Bible:"John", Chapter:6, Verse:40, Page:1,
    Kor:"또한 아들을 보고 그를 믿는 사람은 누구든지 영생을 얻게 하시는 것이 내 아버지의 뜻이다. 나는 마지막 날에 그들을 살릴 것이다.\"",
    Chn:"因为我父的意思是叫一切见子而信的人得永生，并且在末日我要叫他复活。」",
    Eng:"For my Father's will is that everyone who looks to the Son and believes in him shall have eternal life, and I will raise him up at the last day.\"",
    Ind:"Sebab inilah kehendak Bapa-Ku, yaitu supaya setiap orang, yang melihat Anak dan yang percaya kepada-Nya beroleh hidup yang kekal, dan supaya Aku membangkitkannya pada akhir zaman.\""
  },
  {Bible:"John", Chapter:6, Verse:41, Page:1,
    Kor:"○유대인들은 예수께서 \"내가 하늘에서 내려온 빵이다\" 하고 말씀하셨으므로, 그분을 두고 수군거리면서",
    Chn:"犹太人因为耶稣说「我是从天上降下来的粮」，就私下议论他，",
    Eng:"At this the Jews began to grumble about him because he said, \"I am the bread that came down from heaven.\"",
    Ind:"Maka bersungut-sungutlah orang Yahudi tentang Dia, karena Ia telah mengatakan: \"Akulah roti yang telah turun dari sorga.\""
  },
  {Bible:"John", Chapter:6, Verse:42, Page:1,
    Kor:"말하였다. \"이 사람은 요셉의 아들 예수가 아닌가? 그의 부모를 우리가 알지 않는가? 그런데 이 사람이 어떻게 하늘에서 내려왔다고 하는가?\"",
    Chn:"说：「这不是约瑟的儿子耶稣吗？他的父母我们岂不认得吗？他如今怎么说『我是从天上降下来的』呢？」",
    Eng:"They said, \"Is this not Jesus, the son of Joseph, whose father and mother we know? How can he now say, 'I came down from heaven'?\"",
    Ind:"Kata mereka: \"Bukankah Ia ini Yesus, anak Yusuf, yang ibu bapanya kita kenal? Bagaimana Ia dapat berkata: Aku telah turun dari sorga?\""
  },
  {Bible:"John", Chapter:6, Verse:43, Page:1,
    Kor:"그 때에 예수께서 그들에게 말씀하셨다. \"서로 수군거리지 말아라.",
    Chn:"耶稣回答说：「你们不要大家议论。",
    Eng:"\"Stop grumbling among yourselves,\" Jesus answered.",
    Ind:"Jawab Yesus kepada mereka: \"Jangan kamu bersungut-sungut."
  },
  {Bible:"John", Chapter:6, Verse:44, Page:1,
    Kor:"나를 보내신 아버지께서 이끌어 주지 아니하시면, 아무도 내게 올 수 없다. 나는 그 사람들을 마지막 날에 살릴 것이다.",
    Chn:"若不是差我来的父吸引人，就没有能到我这里来的；到我这里来的，在末日我要叫他复活。",
    Eng:"\"No one can come to me unless the Father who sent me draws him, and I will raise him up at the last day.",
    Ind:"Tidak ada seorangpun yang dapat datang kepada-Ku, jikalau ia tidak ditarik oleh Bapa yang mengutus Aku, dan ia akan Kubangkitkan pada akhir zaman."
  },
  {Bible:"John", Chapter:6, Verse:45, Page:1,
    Kor:"예언서에 기록하기를 h'그들이 모두 하나님께 가르침을 받을 것이다' 하였다. 아버지께 듣고 배운 사람은 다 내게로 온다.(h 사 54:13)",
    Chn:"在先知书上写着说：『他们都要蒙　神的教训。』凡听见父之教训又学习的，就到我这里来。",
    Eng:"It is written in the Prophets: 'They will all be taught by God.' Everyone who listens to the Father and learns from him comes to me.",
    Ind:"Ada tertulis dalam kitab nabi-nabi: Dan mereka semua akan diajar oleh Allah. Dan setiap orang, yang telah mendengar dan menerima pengajaran dari Bapa, datang kepada-Ku."
  },
  {Bible:"John", Chapter:6, Verse:46, Page:1,
    Kor:"이 말은, 하나님께로부터 온 사람 외에 누가 아버지를 보았다는 것을 뜻하지 않는다. 하나님께로부터 온 사람만이 아버지를 보았다.",
    Chn:"这不是说有人看见过父，惟独从　神来的，他看见过父。",
    Eng:"No one has seen the Father except the one who is from God; only he has seen the Father.",
    Ind:"Hal itu tidak berarti, bahwa ada orang yang telah melihat Bapa. Hanya Dia yang datang dari Allah, Dialah yang telah melihat Bapa."
  },
  {Bible:"John", Chapter:6, Verse:47, Page:1,
    Kor:"내가 진정으로 진정으로 너희에게 말한다. 믿는 사람은 영생을 가지고 있다.",
    Chn:"我实实在在地告诉你们，信的人有永生。",
    Eng:"I tell you the truth, he who believes has everlasting life.",
    Ind:"Aku berkata kepadamu: Sesungguhnya barangsiapa percaya, ia mempunyai hidup yang kekal."
  },
  {Bible:"John", Chapter:6, Verse:48, Page:1,
    Kor:"나는 생명의 빵이다.",
    Chn:"我就是生命的粮。",
    Eng:"I am the bread of life.",
    Ind:"Akulah roti hidup."
  },
  {Bible:"John", Chapter:6, Verse:49, Page:1,
    Kor:"너희의 조상은 광야에서 만나를 먹었어도 죽었다.",
    Chn:"你们的祖宗在旷野吃过吗哪，还是死了。",
    Eng:"Your forefathers ate the manna in the desert, yet they died.",
    Ind:"Nenek moyangmu telah makan manna di padang gurun dan mereka telah mati."
  },
  {Bible:"John", Chapter:6, Verse:50, Page:1,
    Kor:"그러나 하늘에서 내려오는 빵은 이러하니, 누구든지 그것을 먹으면 죽지 않는다.",
    Chn:"这是从天上降下来的粮，叫人吃了就不死。",
    Eng:"But here is the bread that comes down from heaven, which a man may eat and not die.",
    Ind:"Inilah roti yang turun dari sorga: Barangsiapa makan dari padanya, ia tidak akan mati."
  },
  {Bible:"John", Chapter:6, Verse:51, Page:1,
    Kor:"나는 하늘에서 내려온 살아 있는 빵이다. 이 빵을 먹는 사람은 누구나 영원히 살 것이다. 내가 줄 빵은 나의 살이다. 그것은 세상에 생명을 준다.\"",
    Chn:"我是从天上降下来生命的粮；人若吃这粮，就必永远活着。我所要赐的粮就是我的肉，为世人之生命所赐的。」",
    Eng:"I am the living bread that came down from heaven. If anyone eats of this bread, he will live forever. This bread is my flesh, which I will give for the life of the world.\"",
    Ind:"Akulah roti hidup yang telah turun dari sorga. Jikalau seorang makan dari roti ini, ia akan hidup selama-lamanya, dan roti yang Kuberikan itu ialah daging-Ku, yang akan Kuberikan untuk hidup dunia.\""
  },
  {Bible:"John", Chapter:6, Verse:52, Page:1,
    Kor:"○그러자 유대 사람들은 서로 논란을 하면서 말하였다. \"이 사람이 어떻게 우리에게 <자기> 살을 먹으라고 줄 수 있을까?\"",
    Chn:"因此，犹太人彼此争论说：「这个人怎能把他的肉给我们吃呢？」",
    Eng:"Then the Jews began to argue sharply among themselves, \"How can this man give us his flesh to eat?\"",
    Ind:"Orang-orang Yahudi bertengkar antara sesama mereka dan berkata: \"Bagaimana Ia ini dapat memberikan daging-Nya kepada kita untuk dimakan.\""
  },
  {Bible:"John", Chapter:6, Verse:53, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"내가 진정으로 진정으로 너희에게 말한다. 너희가 인자의 살을 먹지 아니하고, 또 인자의 피를 마시지 아니하면, 너희 속에는 생명이 없다.",
    Chn:"耶稣说：「我实实在在地告诉你们，你们若不吃人子的肉，不喝人子的血，就没有生命在你们里面。",
    Eng:"Jesus said to them, \"I tell you the truth, unless you eat the flesh of the Son of Man and drink his blood, you have no life in you.",
    Ind:"Maka kata Yesus kepada mereka: \"Aku berkata kepadamu, sesungguhnya jikalau kamu tidak makan daging Anak Manusia dan minum darah-Nya, kamu tidak mempunyai hidup di dalam dirimu."
  },
  {Bible:"John", Chapter:6, Verse:54, Page:1,
    Kor:"내 살을 먹고, 내 피를 마시는 사람은 영원한 생명을 가지고 있고, 마지막 날에 내가 그를 살릴 것이다.",
    Chn:"吃我肉、喝我血的人就有永生，在末日我要叫他复活。",
    Eng:"Whoever eats my flesh and drinks my blood has eternal life, and I will raise him up at the last day.",
    Ind:"Barangsiapa makan daging-Ku dan minum darah-Ku, ia mempunyai hidup yang kekal dan Aku akan membangkitkan dia pada akhir zaman."
  },
  {Bible:"John", Chapter:6, Verse:55, Page:1,
    Kor:"내 살은 참 양식이요, 내 피는 참 음료이다.",
    Chn:"我的肉真是可吃的，我的血真是可喝的。",
    Eng:"For my flesh is real food and my blood is real drink.",
    Ind:"Sebab daging-Ku adalah benar-benar makanan dan darah-Ku adalah benar-benar minuman."
  },
  {Bible:"John", Chapter:6, Verse:56, Page:1,
    Kor:"내 살을 먹고, 내 피를 마시는 사람은 내 안에 있고, 나도 그 사람 안에 있다.",
    Chn:"吃我肉、喝我血的人常在我里面，我也常在他里面。",
    Eng:"Whoever eats my flesh and drinks my blood remains in me, and I in him.",
    Ind:"Barangsiapa makan daging-Ku dan minum darah-Ku, ia tinggal di dalam Aku dan Aku di dalam dia."
  },
  {Bible:"John", Chapter:6, Verse:57, Page:1,
    Kor:"살아 계신 아버지께서 나를 보내셨고, 내가 아버지 때문에 사는 것과 같이, 나를 먹는 사람도 나 때문에 살 것이다.",
    Chn:"永活的父怎样差我来，我又因父活着；照样，吃我肉的人也要因我活着。",
    Eng:"Just as the living Father sent me and I live because of the Father, so the one who feeds on me will live because of me.",
    Ind:"Sama seperti Bapa yang hidup mengutus Aku dan Aku hidup oleh Bapa, demikian juga barangsiapa yang memakan Aku, akan hidup oleh Aku."
  },
  {Bible:"John", Chapter:6, Verse:58, Page:1,
    Kor:"이것은 하늘에서 내려온 빵이다. 이것은 너희의 조상이 먹고서도 죽은 그런 것과는 같지 아니하다. 이 빵을 먹는 사람은 영원히 살 것이다.\"",
    Chn:"这就是从天上降下来的粮。吃这粮的人就永远活着，不像你们的祖宗吃过吗哪还是死了。」",
    Eng:"This is the bread that came down from heaven. Your forefathers ate manna and died, but he who feeds on this bread will live forever.\"",
    Ind:"Inilah roti yang telah turun dari sorga, bukan roti seperti yang dimakan nenek moyangmu dan mereka telah mati. Barangsiapa makan roti ini, ia akan hidup selama-lamanya.\""
  },
  {Bible:"John", Chapter:6, Verse:59, Page:1,
    Kor:"이것은 예수께서 가버나움 회당에서 가르치실 때에 하신 말씀이다.",
    Chn:"这些话是耶稣在迦百农会堂里教训人说的。",
    Eng:"He said this while teaching in the synagogue in Capernaum.",
    Ind:"Semuanya ini dikatakan Yesus di Kapernaum ketika Ia mengajar di rumah ibadat."
  },
  {Bible:"John", Chapter:6, Verse:60, Page:1,
    Kor:"<영원한 생명의 말씀> ○예수의 제자들 가운데서 여럿이 이 말씀을 듣고 말하기를 \"이 말씀이 이렇게 어려우니 누가 알아들을 수 있겠는가?\" 하였다.",
    Chn:"他的门徒中有好些人听见了，就说：「这话甚难，谁能听呢？」",
    Eng:"On hearing it, many of his disciples said, \"This is a hard teaching. Who can accept it?\"",
    Ind:"Sesudah mendengar semuanya itu banyak dari murid-murid Yesus yang berkata: \"Perkataan ini keras, siapakah yang sanggup mendengarkannya?\""
  },
  {Bible:"John", Chapter:6, Verse:61, Page:1,
    Kor:"예수께서, 제자들이 자기의 말을 두고 수군거리는 것을 아시고, 그들에게 말씀하셨다. \"이 말이 너희의 마음에 걸리느냐?",
    Chn:"耶稣心里知道门徒为这话议论，就对他们说：「这话是叫你们厌弃吗？",
    Eng:"Aware that his disciples were grumbling about this, Jesus said to them, \"Does this offend you?",
    Ind:"Yesus yang di dalam hati-Nya tahu, bahwa murid-murid-Nya bersungut-sungut tentang hal itu, berkata kepada mereka: \"Adakah perkataan itu menggoncangkan imanmu?"
  },
  {Bible:"John", Chapter:6, Verse:62, Page:1,
    Kor:"인자가 전에 있던 곳으로 올라가는 것을 보면, 어떻게 하겠느냐?",
    Chn:"倘或你们看见人子升到他原来所在之处，怎么样呢？",
    Eng:"What if you see the Son of Man ascend to where he was before!",
    Ind:"Dan bagaimanakah, jikalau kamu melihat Anak Manusia naik ke tempat di mana Ia sebelumnya berada?"
  },
  {Bible:"John", Chapter:6, Verse:63, Page:1,
    Kor:"생명을 주는 것은 영이다. 육은 아무 데도 소용이 없다. 내가 너희에게 한 이 말은 영이요 생명이다.",
    Chn:"叫人活着的乃是灵，肉体是无益的。我对你们所说的话就是灵，就是生命。",
    Eng:"The Spirit gives life; the flesh counts for nothing. The words I have spoken to you are spirit and they are life.",
    Ind:"Rohlah yang memberi hidup, daging sama sekali tidak berguna. Perkataan-perkataan yang Kukatakan kepadamu adalah roh dan hidup."
  },
  {Bible:"John", Chapter:6, Verse:64, Page:1,
    Kor:"그러나 너희 가운데는 믿지 않는 사람들이 있다.\" 처음부터 예수께서는, 믿지 않는 사람이 누구이며, 자기를 넘겨줄 사람이 누구인지를, 알고 계셨던 것이다.",
    Chn:"只是你们中间有不信的人。」耶稣从起头就知道谁不信他，谁要卖他。",
    Eng:"Yet there are some of you who do not believe.\" For Jesus had known from the beginning which of them did not believe and who would betray him.",
    Ind:"Tetapi di antaramu ada yang tidak percaya.\" Sebab Yesus tahu dari semula, siapa yang tidak percaya dan siapa yang akan menyerahkan Dia."
  },
  {Bible:"John", Chapter:6, Verse:65, Page:1,
    Kor:"예수께서 또 말씀하셨다. \"그러므로 내가 너희에게 이르기를, 아버지께서 허락하여 주신 사람이 아니고는 아무도 나에게로 올 수 없다고 말한 것이다.\"",
    Chn:"耶稣又说：「所以我对你们说过，若不是蒙我父的恩赐，没有人能到我这里来。」",
    Eng:"He went on to say, \"This is why I told you that no one can come to me unless the Father has enabled him.\"",
    Ind:"Lalu Ia berkata: \"Sebab itu telah Kukatakan kepadamu: Tidak ada seorangpun dapat datang kepada-Ku, kalau Bapa tidak mengaruniakannya kepadanya.\""
  },
  {Bible:"John", Chapter:6, Verse:66, Page:1,
    Kor:"○i이 때문에 제자 가운데서 많은 사람이 떠나갔고, 더 이상 그와 함께 다니지 않았다.(i '이 때부터'라고 번역할 수도 있음)",
    Chn:"从此，他门徒中多有退去的，不再和他同行。",
    Eng:"From this time many of his disciples turned back and no longer followed him.",
    Ind:"Mulai dari waktu itu banyak murid-murid-Nya mengundurkan diri dan tidak lagi mengikut Dia."
  },
  {Bible:"John", Chapter:6, Verse:67, Page:1,
    Kor:"예수께서 열두 제자에게 물으셨다. \"너희까지도 떠나가려 하느냐?\"",
    Chn:"耶稣就对那十二个门徒说：「你们也要去吗？」",
    Eng:"\"You do not want to leave too, do you?\" Jesus asked the Twelve.",
    Ind:"Maka kata Yesus kepada kedua belas murid-Nya: \"Apakah kamu tidak mau pergi juga?\""
  },
  {Bible:"John", Chapter:6, Verse:68, Page:1,
    Kor:"시몬 베드로가 대답하였다. \"주님, 우리가 누구에게로 가겠습니까? 선생님께는 영생의 말씀이 있습니다.",
    Chn:"西门·彼得回答说：「主啊，你有永生之道，我们还归从谁呢？",
    Eng:"Simon Peter answered him, \"Lord, to whom shall we go? You have the words of eternal life.",
    Ind:"Jawab Simon Petrus kepada-Nya: \"Tuhan, kepada siapakah kami akan pergi? Perkataan-Mu adalah perkataan hidup yang kekal;"
  },
  {Bible:"John", Chapter:6, Verse:69, Page:1,
    Kor:"우리는, 선생님이 j하나님의 거룩한 분이심을 믿고, 또 알았습니다.\"(j 다른 고대 사본들에는 '살아 계신 하나님의 아들 그리스도이심을')",
    Chn:"我们已经信了，又知道你是　神的圣者。」",
    Eng:"We believe and know that you are the Holy One of God.\"",
    Ind:"dan kami telah percaya dan tahu, bahwa Engkau adalah Yang Kudus dari Allah.\""
  },
  {Bible:"John", Chapter:6, Verse:70, Page:1,
    Kor:"예수께서 그들에게 대답하셨다. \"내가 너희 열둘을 택하지 않았느냐? 그러나 너희 가운데서 하나는 악마이다.\"",
    Chn:"耶稣说：「我不是拣选了你们十二个门徒吗？但你们中间有一个是魔鬼。」",
    Eng:"Then Jesus replied, \"Have I not chosen you, the Twelve? Yet one of you is a devil!\"",
    Ind:"Jawab Yesus kepada mereka: \"Bukankah Aku sendiri yang telah memilih kamu yang dua belas ini? Namun seorang di antaramu adalah Iblis.\""
  },
  {Bible:"John", Chapter:6, Verse:71, Page:1,
    Kor:"이것은 k시몬 가룟의 아들 유다를 가리켜서 하신 말씀인데, 그는 열두 제자 가운데 한 사람으로, 예수를 넘겨줄 사람이었다.(k 다른 고대 사본들에는 '시몬의 아들 유다 가룟' 또는 '가룟 사람 시몬의 아들 유다')",
    Chn:"耶稣这话是指着加略人西门的儿子犹大说的；他本是十二个门徒里的一个，后来要卖耶稣的。",
    Eng:"(He meant Judas, the son of Simon Iscariot, who, though one of the Twelve, was later to betray him.)",
    Ind:"Yang dimaksudkan-Nya ialah Yudas, anak Simon Iskariot; sebab dialah yang akan menyerahkan Yesus, dia seorang di antara kedua belas murid itu."
  },
]);
