// 요한복음 12장 · John 12
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("John",12,50);
BibleDB.add([
  {Bible:"John", Chapter:12, Verse:1, Page:1,
    Kor:"<한 여자가 예수의 발에 향유를 붓다(마 26:6-13; 막 14:3-9)> a유월절 엿새 전에, 예수께서 베다니에 가셨다. 그 곳은 예수께서 죽은 사람 가운데에 살리신 나사로가 사는 곳이다.(a 출 12:13, 21-28을 볼 것)",
    Chn:"逾越节前六日，耶稣来到伯大尼，就是他叫拉撒路从死里复活之处。",
    Eng:"Six days before the Passover, Jesus arrived at Bethany, where Lazarus lived, whom Jesus had raised from the dead.",
    Ind:"Enam hari sebelum Paskah Yesus datang ke Betania, tempat tinggal Lazarus yang dibangkitkan Yesus dari antara orang mati."
  },
  {Bible:"John", Chapter:12, Verse:2, Page:1,
    Kor:"거기서 예수를 위하여 잔치를 베풀었는데, 마르다는 시중을 들고 있었고, 나사로는 식탁에서 예수와 함께 음식을 먹고 있는 사람 가운데 끼여 있었다.",
    Chn:"有人在那里给耶稣预备筵席；马大伺候，拉撒路也在那同耶稣坐席的人中。",
    Eng:"Here a dinner was given in Jesus' honor. Martha served, while Lazarus was among those reclining at the table with him.",
    Ind:"Di situ diadakan perjamuan untuk Dia dan Marta melayani, sedang salah seorang yang turut makan dengan Yesus adalah Lazarus."
  },
  {Bible:"John", Chapter:12, Verse:3, Page:1,
    Kor:"그 때에 마리아가 매우 값진 순 나드 향유 한 근을 가져다가 예수의 발에 붓고, 자기 머리털로 그 발을 닦았다. 온 집 안에 향유 냄새가 가득 찼다.",
    Chn:"马利亚就拿着一斤极贵的真哪哒香膏，抹耶稣的脚，又用自己头发去擦，屋里就满了膏的香气。",
    Eng:"Then Mary took about a pint of pure nard, an expensive perfume; she poured it on Jesus' feet and wiped his feet with her hair. And the house was filled with the fragrance of the perfume.",
    Ind:"Maka Maria mengambil setengah kati minyak narwastu murni yang mahal harganya, lalu meminyaki kaki Yesus dan menyekanya dengan rambutnya; dan bau minyak semerbak di seluruh rumah itu."
  },
  {Bible:"John", Chapter:12, Verse:4, Page:1,
    Kor:"예수의 제자 가운데 하나이며 장차 예수를 넘겨줄 가룟 유다가 말하였다.",
    Chn:"有一个门徒，就是那将要卖耶稣的加略人犹大，",
    Eng:"But one of his disciples, Judas Iscariot, who was later to betray him, objected,",
    Ind:"Tetapi Yudas Iskariot, seorang dari murid-murid Yesus, yang akan segera menyerahkan Dia, berkata:"
  },
  {Bible:"John", Chapter:12, Verse:5, Page:1,
    Kor:"\"이 향유를 b삼백 데나리온에 팔아서 가난한 사람들에게 주지 않고, 왜 이렇게 낭비하는가?\"(b 삼백 데나리온은 노동자의 일년 품삯)",
    Chn:"说：「这香膏为什么不卖三十两银子周济穷人呢？」",
    Eng:"\"Why wasn't this perfume sold and the money given to the poor? It was worth a year's wages.\"",
    Ind:"\"Mengapa minyak narwastu ini tidak dijual tiga ratus dinar dan uangnya diberikan kepada orang-orang miskin?\""
  },
  {Bible:"John", Chapter:12, Verse:6, Page:1,
    Kor:"(그가 이렇게 말한 것은, 가난한 사람을 생각해서가 아니다. 그는 도둑이어서 돈자루를 맡아 가지고 있으면서, 거기에 든 것을 훔쳐내곤 하였기 때문이다.)",
    Chn:"他说这话，并不是挂念穷人，乃因他是个贼，又带着钱囊，常取其中所存的。",
    Eng:"He did not say this because he cared about the poor but because he was a thief; as keeper of the money bag, he used to help himself to what was put into it.",
    Ind:"Hal itu dikatakannya bukan karena ia memperhatikan nasib orang-orang miskin, melainkan karena ia adalah seorang pencuri; ia sering mengambil uang yang disimpan dalam kas yang dipegangnya."
  },
  {Bible:"John", Chapter:12, Verse:7, Page:1,
    Kor:"예수께서 말씀하셨다. \"그대로 두어라. 그는 나의 장사 날에 쓰려고 간직한 것을 쓴 것이다.",
    Chn:"耶稣说：「由她吧！她是为我安葬之日存留的。",
    Eng:"\"Leave her alone,\" Jesus replied. \"It was intended that she should save this perfume for the day of my burial.",
    Ind:"Maka kata Yesus: \"Biarkanlah dia melakukan hal ini mengingat hari penguburan-Ku."
  },
  {Bible:"John", Chapter:12, Verse:8, Page:1,
    Kor:"가난한 사람들은 언제나 너희와 함께 있지만, 나는 언제나 너희와 함께 있는 것이 아니다.\"",
    Chn:"因为常有穷人和你们同在，只是你们不常有我。」",
    Eng:"You will always have the poor among you, but you will not always have me.\"",
    Ind:"Karena orang-orang miskin selalu ada pada kamu, tetapi Aku tidak akan selalu ada pada kamu.\""
  },
  {Bible:"John", Chapter:12, Verse:9, Page:1,
    Kor:"<나사로를 해하려고 모의하다> ○유대 사람들이 예수가 거기에 계신다는 것을 알고, 크게 떼를 지어 몰려왔다. 그들은 예수를 보려는 것만이 아니라, 그가 죽은 사람들 가운데서 다시 살리신 나사로를 보려는 것이었다.",
    Chn:"有许多犹太人知道耶稣在那里，就来了，不但是为耶稣的缘故，也是要看他从死里所复活的拉撒路。",
    Eng:"Meanwhile a large crowd of Jews found out that Jesus was there and came, not only because of him but also to see Lazarus, whom he had raised from the dead.",
    Ind:"Sejumlah besar orang Yahudi mendengar, bahwa Yesus ada di sana dan mereka datang bukan hanya karena Yesus, melainkan juga untuk melihat Lazarus, yang telah dibangkitkan-Nya dari antara orang mati."
  },
  {Bible:"John", Chapter:12, Verse:10, Page:1,
    Kor:"그래서 대제사장들은 나사로도 죽이려고 모의하였다.",
    Chn:"但祭司长商议连拉撒路也要杀了；",
    Eng:"So the chief priests made plans to kill Lazarus as well,",
    Ind:"Lalu imam-imam kepala bermupakat untuk membunuh Lazarus juga,"
  },
  {Bible:"John", Chapter:12, Verse:11, Page:1,
    Kor:"그것은 나사로 때문에 많은 유대 사람이 떨어져 나가서, 예수를 믿었기 때문이다.",
    Chn:"因有好些犹太人为拉撒路的缘故，回去信了耶稣。",
    Eng:"for on account of him many of the Jews were going over to Jesus and putting their faith in him.",
    Ind:"sebab karena dia banyak orang Yahudi meninggalkan mereka dan percaya kepada Yesus."
  },
  {Bible:"John", Chapter:12, Verse:12, Page:1,
    Kor:"<예루살렘 입성(마 21:1-11; 막 11:1-11; 눅 19:28-40)> ○다음날에는 명절을 지키러 온 많은 무리가, 예수께서 예루살렘에 들어오신다는 말을 듣고,",
    Chn:"第二天，有许多上来过节的人听见耶稣将到耶路撒冷，",
    Eng:"The next day the great crowd that had come for the Feast heard that Jesus was on his way to Jerusalem.",
    Ind:"Keesokan harinya ketika orang banyak yang datang merayakan pesta mendengar, bahwa Yesus sedang di tengah jalan menuju Yerusalem,"
  },
  {Bible:"John", Chapter:12, Verse:13, Page:1,
    Kor:"종려나무 가지를 꺾어 들고, 그분을 맞으러 나가서  c\"호산나! d주님의 이름으로 오시는 이에게 복이 있기를! 이스라엘의 왕에게 복이 있기를!\" 하고 외쳤다.(c '구원하여 주십시오!' 라는 뜻을 지닌 말로서 찬양에서 쓰임 d 시 118:25, 26)",
    Chn:"就拿着棕树枝出去迎接他，喊着说： 和散那！ 奉主名来的以色列王是应当称颂的！",
    Eng:"They took palm branches and went out to meet him, shouting, \"Hosanna!\" \"Blessed is he who comes in the name of the Lord!\" \"Blessed is the King of Israel!\"",
    Ind:"mereka mengambil daun-daun palem, dan pergi menyongsong Dia sambil berseru-seru: \"Hosana! Diberkatilah Dia yang datang dalam nama Tuhan, Raja Israel!\""
  },
  {Bible:"John", Chapter:12, Verse:14, Page:1,
    Kor:"예수께서 어린 나귀를 보시고, 그 위에 올라타셨다. 그것은 이렇게 기록한 성경 말씀과 같았다.",
    Chn:"耶稣得了一个驴驹，就骑上，如经上所记的说：",
    Eng:"Jesus found a young donkey and sat upon it, as it is written,",
    Ind:"Yesus menemukan seekor keledai muda lalu Ia naik ke atasnya, seperti ada tertulis:"
  },
  {Bible:"John", Chapter:12, Verse:15, Page:1,
    Kor:"e\"시온의 딸아, 두려워하지 말아라. 보아라, 네 임금이 어린 나귀를 타고 오신다.\" (e 슥 9:9)",
    Chn:"锡安的民哪，不要惧怕！ 你的王骑着驴驹来了。",
    Eng:"\"Do not be afraid, O Daughter of Zion; see, your king is coming, seated on a donkey's colt.\"",
    Ind:"\"Jangan takut, hai puteri Sion, lihatlah, Rajamu datang, duduk di atas seekor anak keledai.\""
  },
  {Bible:"John", Chapter:12, Verse:16, Page:1,
    Kor:"제자들은 처음에는 이 말씀을 깨닫지 못하였으나, 예수께서 영광을 받으신 뒤에야, 이것이 예수를 두고 기록한 것이며, 또 사람들도 그에게 그렇게 대하였다는 것을 회상하였다.",
    Chn:"这些事门徒起先不明白，等到耶稣得了荣耀以后才想起这话是指着他写的，并且众人果然向他这样行了。",
    Eng:"At first his disciples did not understand all this. Only after Jesus was glorified did they realize that these things had been written about him and that they had done these things to him.",
    Ind:"Mula-mula murid-murid Yesus tidak mengerti akan hal itu, tetapi sesudah Yesus dimuliakan, teringatlah mereka, bahwa nas itu mengenai Dia, dan bahwa mereka telah melakukannya juga untuk Dia."
  },
  {Bible:"John", Chapter:12, Verse:17, Page:1,
    Kor:"또 예수께서 무덤에서 나사로를 불러내어 죽은 사람들 가운데서 살리실 때에 함께 있던 사람들이, 그 일어난 일을 증언하였다.",
    Chn:"当耶稣呼唤拉撒路，叫他从死复活出坟墓的时候，同耶稣在那里的众人就作见证。",
    Eng:"Now the crowd that was with him when he called Lazarus from the tomb and raised him from the dead continued to spread the word.",
    Ind:"Orang banyak yang bersama-sama dengan Dia ketika Ia memanggil Lazarus keluar dari kubur dan membangkitkannya dari antara orang mati, memberi kesaksian tentang Dia."
  },
  {Bible:"John", Chapter:12, Verse:18, Page:1,
    Kor:"이렇게 무리가 예수를 맞으러 나온 것은, 예수가 이런 f표징을 행하셨다는 말을 들었기 때문이다.(f 예수의 신성을 보여주기 위한 상징으로서의 기적(그리스어 세메이온))",
    Chn:"众人因听见耶稣行了这神迹，就去迎接他。",
    Eng:"Many people, because they had heard that he had given this miraculous sign, went out to meet him.",
    Ind:"Sebab itu orang banyak itu pergi menyongsong Dia, karena mereka mendengar, bahwa Ia yang membuat mujizat itu."
  },
  {Bible:"John", Chapter:12, Verse:19, Page:1,
    Kor:"그래서 바리새파 사람들이 서로 말하였다. \"이제 다 틀렸소. 보시오. 온 세상이 그를 따라갔소.\"",
    Chn:"法利赛人彼此说：「看哪，你们是徒劳无益，世人都随从他去了。」",
    Eng:"So the Pharisees said to one another, \"See, this is getting us nowhere. Look how the whole world has gone after him!\"",
    Ind:"Maka kata orang-orang Farisi seorang kepada yang lain: \"Kamu lihat sendiri, bahwa kamu sama sekali tidak berhasil, lihatlah, seluruh dunia datang mengikuti Dia.\""
  },
  {Bible:"John", Chapter:12, Verse:20, Page:1,
    Kor:"<예수를 보러 온 그리스 사람들> ○명절에 예배하러 올라온 사람들 가운데 그리스 사람이 몇 있었는데,",
    Chn:"那时，上来过节礼拜的人中，有几个希腊人。",
    Eng:"Now there were some Greeks among those who went up to worship at the Feast.",
    Ind:"Di antara mereka yang berangkat untuk beribadah pada hari raya itu, terdapat beberapa orang Yunani."
  },
  {Bible:"John", Chapter:12, Verse:21, Page:1,
    Kor:"그들은 갈릴리 벳새다 출신 빌립에게로 가서 청하였다. \"선생님, 우리가 예수를 뵙고 싶습니다.\"",
    Chn:"他们来见加利利、伯赛大的腓力，求他说：「先生，我们愿意见耶稣。」",
    Eng:"They came to Philip, who was from Bethsaida in Galilee, with a request. \"Sir,\" they said, \"we would like to see Jesus.\"",
    Ind:"Orang-orang itu pergi kepada Filipus, yang berasal dari Betsaida di Galilea, lalu berkata kepadanya: \"Tuan, kami ingin bertemu dengan Yesus.\""
  },
  {Bible:"John", Chapter:12, Verse:22, Page:1,
    Kor:"빌립은 안드레에게로 가서 말하고, 안드레와 빌립은 예수께 그 말을 전하였다.",
    Chn:"腓力去告诉安得烈，安得烈同腓力去告诉耶稣。",
    Eng:"Philip went to tell Andrew; Andrew and Philip in turn told Jesus.",
    Ind:"Filipus pergi memberitahukannya kepada Andreas; Andreas dan Filipus menyampaikannya pula kepada Yesus."
  },
  {Bible:"John", Chapter:12, Verse:23, Page:1,
    Kor:"예수께서 그들에게 대답하셨다. \"인자가 영광을 받을 때가 왔다.",
    Chn:"耶稣说：「人子得荣耀的时候到了。",
    Eng:"Jesus replied, \"The hour has come for the Son of Man to be glorified.",
    Ind:"Tetapi Yesus menjawab mereka, kata-Nya: \"Telah tiba saatnya Anak Manusia dimuliakan."
  },
  {Bible:"John", Chapter:12, Verse:24, Page:1,
    Kor:"내가 진정으로 진정으로 너희에게 말한다. 밀알 하나가 땅에 떨어져서 죽지 않으면 한 알 그대로 있고, 죽으면 열매를 많이 맺는다.",
    Chn:"我实实在在地告诉你们，一粒麦子不落在地里死了，仍旧是一粒，若是死了，就结出许多子粒来。",
    Eng:"I tell you the truth, unless a kernel of wheat falls to the ground and dies, it remains only a single seed. But if it dies, it produces many seeds.",
    Ind:"Aku berkata kepadamu: Sesungguhnya jikalau biji gandum tidak jatuh ke dalam tanah dan mati, ia tetap satu biji saja; tetapi jika ia mati, ia akan menghasilkan banyak buah."
  },
  {Bible:"John", Chapter:12, Verse:25, Page:1,
    Kor:"자기의 목숨을 사랑하는 사람은 잃을 것이요, 이 세상에서 자기의 목숨을 미워하는 사람은, 영생에 이르도록 그 목숨을 보존할 것이다.",
    Chn:"爱惜自己生命的，就失丧生命；在这世上恨恶自己生命的，就要保守生命到永生。",
    Eng:"The man who loves his life will lose it, while the man who hates his life in this world will keep it for eternal life.",
    Ind:"Barangsiapa mencintai nyawanya, ia akan kehilangan nyawanya, tetapi barangsiapa tidak mencintai nyawanya di dunia ini, ia akan memeliharanya untuk hidup yang kekal."
  },
  {Bible:"John", Chapter:12, Verse:26, Page:1,
    Kor:"나를 섬기려고 하는 사람은, 누구든지 나를 따라오너라. 내가 있는 곳에는, 나를 섬기는 사람도 나와 함께 있을 것이다. 누구든지 나를 섬기면, 내 아버지께서 그를 높여주실 것이다.\"",
    Chn:"若有人服事我，就当跟从我；我在哪里，服事我的人也要在那里；若有人服事我，我父必尊重他。」",
    Eng:"Whoever serves me must follow me; and where I am, my servant also will be. My Father will honor the one who serves me.",
    Ind:"Barangsiapa melayani Aku, ia harus mengikut Aku dan di mana Aku berada, di situpun pelayan-Ku akan berada. Barangsiapa melayani Aku, ia akan dihormati Bapa."
  },
  {Bible:"John", Chapter:12, Verse:27, Page:1,
    Kor:"<인자는 들려야 한다> ○\"지금 내 마음이 괴로우니, 무슨 말을 하여야 할까? '아버지, 이 시간을 벗어나게 하여 주십시오' 하고 말할까? 아니다. 나는 바로 이 일 때문에 이 때에 왔다.",
    Chn:"「我现在心里忧愁，我说什么才好呢？父啊，救我脱离这时候；但我原是为这时候来的。",
    Eng:"\"Now my heart is troubled, and what shall I say? 'Father, save me from this hour'? No, it was for this very reason I came to this hour.",
    Ind:"Sekarang jiwa-Ku terharu dan apakah yang akan Kukatakan? Bapa, selamatkanlah Aku dari saat ini? Tidak, sebab untuk itulah Aku datang ke dalam saat ini."
  },
  {Bible:"John", Chapter:12, Verse:28, Page:1,
    Kor:"아버지, 아버지의 이름을 영광스럽게 드러내십시오.\" 그 때에 하늘에서 소리가 들려 왔다. \"내가 이미 영광되게 하였고, 앞으로도 영광되게 하겠다.\"",
    Chn:"父啊，愿你荣耀你的名！」当时就有声音从天上来，说：「我已经荣耀了我的名，还要再荣耀。」",
    Eng:"Father, glorify your name!\" Then a voice came from heaven, \"I have glorified it, and will glorify it again.\"",
    Ind:"Bapa, muliakanlah nama-Mu!\" Maka terdengarlah suara dari sorga: \"Aku telah memuliakan-Nya, dan Aku akan memuliakan-Nya lagi!\""
  },
  {Bible:"John", Chapter:12, Verse:29, Page:1,
    Kor:"거기에 서서 듣고 있던 무리 가운데서 더러는 천둥이 울렸다고 하고, 또 더러는 천사가 그에게 말하였다고 하였다.",
    Chn:"站在旁边的众人听见，就说：「打雷了。」还有人说：「有天使对他说话。」",
    Eng:"The crowd that was there and heard it said it had thundered; others said an angel had spoken to him.",
    Ind:"Orang banyak yang berdiri di situ dan mendengarkannya berkata, bahwa itu bunyi guntur. Ada pula yang berkata: \"Seorang malaikat telah berbicara dengan Dia.\""
  },
  {Bible:"John", Chapter:12, Verse:30, Page:1,
    Kor:"예수께서 대답하셨다. \"이 소리가 난 것은, 나를 위해서가 아니라 너희를 위해서이다.",
    Chn:"耶稣说：「这声音不是为我，是为你们来的。",
    Eng:"Jesus said, \"This voice was for your benefit, not mine.",
    Ind:"Jawab Yesus: \"Suara itu telah terdengar bukan oleh karena Aku, melainkan oleh karena kamu."
  },
  {Bible:"John", Chapter:12, Verse:31, Page:1,
    Kor:"지금은 이 세상이 심판을 받을 때이다. 이제는 이 세상의 통치자가 쫓겨날 것이다.",
    Chn:"现在这世界受审判，这世界的王要被赶出去。",
    Eng:"Now is the time for judgment on this world; now the prince of this world will be driven out.",
    Ind:"Sekarang berlangsung penghakiman atas dunia ini: sekarang juga penguasa dunia ini akan dilemparkan ke luar;"
  },
  {Bible:"John", Chapter:12, Verse:32, Page:1,
    Kor:"내가 땅에서 들려서 올라갈 때에, 나는 모든 사람을 내게로 이끌어 올 것이다.\"",
    Chn:"我若从地上被举起来，就要吸引万人来归我。」",
    Eng:"But I, when I am lifted up from the earth, will draw all men to myself.\"",
    Ind:"dan Aku, apabila Aku ditinggikan dari bumi, Aku akan menarik semua orang datang kepada-Ku.\""
  },
  {Bible:"John", Chapter:12, Verse:33, Page:1,
    Kor:"이것은 예수께서 자기가 당하실 죽음이 어떠한 것인지를 암시하려고 하신 말씀이다.",
    Chn:"耶稣这话原是指着自己将要怎样死说的。",
    Eng:"He said this to show the kind of death he was going to die.",
    Ind:"Ini dikatakan-Nya untuk menyatakan bagaimana caranya Ia akan mati."
  },
  {Bible:"John", Chapter:12, Verse:34, Page:1,
    Kor:"그 때에 무리가 예수께 말하였다. \"우리는 율법에서 g그리스도는 영원히 살아 계시다는 것을 배웠습니다. 그런데 어떻게 당신은 인자가 들려야 한다고 말씀하십니까? 인자가 누구입니까?\"(g 또는 '메시아'. 그리스어 그리스도와 히브리어 메시아는 둘 다 '기름 부음 받은 이'를 뜻함)",
    Chn:"众人回答说：「我们听见律法上有话说，基督是永存的，你怎么说『人子必须被举起来』呢？这人子是谁呢？」",
    Eng:"The crowd spoke up, \"We have heard from the Law that the Christ will remain forever, so how can you say, 'The Son of Man must be lifted up'? Who is this 'Son of Man'?\"",
    Ind:"Lalu jawab orang banyak itu: \"Kami telah mendengar dari hukum Taurat, bahwa Mesias tetap hidup selama-lamanya; bagaimana mungkin Engkau mengatakan, bahwa Anak Manusia harus ditinggikan? Siapakah Anak Manusia itu?\""
  },
  {Bible:"John", Chapter:12, Verse:35, Page:1,
    Kor:"예수께서 그들에게 대답하셨다. \"아직 얼마 동안은 빛이 너희 가운데 있을 것이다. 빛이 있는 동안에 걸어다녀라. 어둠이 너희를 이기지 못하게 하여라. 어둠 속을 다니는 사람은 자기가 어디로 가는지를 모른다.",
    Chn:"耶稣对他们说：「光在你们中间还有不多的时候，应当趁着有光行走，免得黑暗临到你们；那在黑暗里行走的，不知道往何处去。",
    Eng:"Then Jesus told them, \"You are going to have the light just a little while longer. Walk while you have the light, before darkness overtakes you. The man who walks in the dark does not know where he is going.",
    Ind:"Kata Yesus kepada mereka: \"Hanya sedikit waktu lagi terang ada di antara kamu. Selama terang itu ada padamu, percayalah kepadanya, supaya kegelapan jangan menguasai kamu; barangsiapa berjalan dalam kegelapan, ia tidak tahu ke mana ia pergi."
  },
  {Bible:"John", Chapter:12, Verse:36, Page:1,
    Kor:"빛이 있는 동안에 너희는 그 빛을 믿어서, 빛의 자녀가 되어라.\" <유대 사람들의 불신앙> ○이 말씀을 하신 뒤에, 예수께서는 그들을 떠나서 몸을 숨기셨다.",
    Chn:"你们应当趁着有光，信从这光，使你们成为光明之子。」 耶稣说了这话，就离开他们隐藏了。",
    Eng:"Put your trust in the light while you have it, so that you may become sons of light.\" When he had finished speaking, Jesus left and hid himself from them.",
    Ind:"Percayalah kepada terang itu, selama terang itu ada padamu, supaya kamu menjadi anak-anak terang.\" Sesudah berkata demikian, Yesus pergi bersembunyi dari antara mereka."
  },
  {Bible:"John", Chapter:12, Verse:37, Page:1,
    Kor:"예수께서 그렇게 많은 f표징을 그들 앞에 행하셨으나, 그들은 예수를 믿지 아니하였다.(f 예수의 신성을 보여주기 위한 상징으로서의 기적(그리스어 세메이온))",
    Chn:"他虽然在他们面前行了许多神迹，他们还是不信他。",
    Eng:"Even after Jesus had done all these miraculous signs in their presence, they still would not believe in him.",
    Ind:"Dan meskipun Yesus mengadakan begitu banyak mujizat di depan mata mereka, namun mereka tidak percaya kepada-Nya,"
  },
  {Bible:"John", Chapter:12, Verse:38, Page:1,
    Kor:"그리하여 예언자 이사야가 한 말이 이루어졌다.  h\"주님, 우리가 전한 것을 누가 믿었으며, 주님의 팔이 누구에게 나타났습니까?\" (h 사 53:1(칠십인역))",
    Chn:"这是要应验先知以赛亚的话，说： 主啊，我们所传的有谁信呢？ 主的膀臂向谁显露呢？",
    Eng:"This was to fulfill the word of Isaiah the prophet: \"Lord, who has believed our message and to whom has the arm of the Lord been revealed?\"",
    Ind:"supaya genaplah firman yang disampaikan oleh nabi Yesaya: \"Tuhan, siapakah yang percaya kepada pemberitaan kami? Dan kepada siapakah tangan kekuasaan Tuhan dinyatakan?\""
  },
  {Bible:"John", Chapter:12, Verse:39, Page:1,
    Kor:"그들이 믿을 수 없었던 까닭을, 이사야가 또 이렇게 말하였다.",
    Chn:"他们所以不能信，因为以赛亚又说：",
    Eng:"For this reason they could not believe, because, as Isaiah says elsewhere:",
    Ind:"Karena itu mereka tidak dapat percaya, sebab Yesaya telah berkata juga:"
  },
  {Bible:"John", Chapter:12, Verse:40, Page:1,
    Kor:"i\"주님께서 그들의 눈을 멀게 하시고, 그들의 마음을 무디게 하셨다. 그것은 그들이 눈이 있어도 보지 못하게 하고, 마음으로 깨달아서 돌아서지 못하게 하여, j나에게 고침을 받지 못하게 하려는 것이다.\" (i 사 6:10(칠십인역) j '나'는 '주'를 가리킴)",
    Chn:"主叫他们瞎了眼， 硬了心， 免得他们眼睛看见， 心里明白，回转过来， 我就医治他们。",
    Eng:"\"He has blinded their eyes and deadened their hearts, so they can neither see with their eyes, nor understand with their hearts, nor turn--and I would heal them.\"",
    Ind:"\"Ia telah membutakan mata dan mendegilkan hati mereka, supaya mereka jangan melihat dengan mata, dan menanggap dengan hati, lalu berbalik, sehingga Aku menyembuhkan mereka.\""
  },
  {Bible:"John", Chapter:12, Verse:41, Page:1,
    Kor:"이사야가 이렇게 말한 것은, 그가 예수의 영광을 보았기 때문이다. 이 말은 그가 예수를 가리켜서 한 것이다.",
    Chn:"以赛亚因为看见他的荣耀，就指着他说这话。",
    Eng:"Isaiah said this because he saw Jesus' glory and spoke about him.",
    Ind:"Hal ini dikatakan oleh Yesaya, karena ia telah melihat kemuliaan-Nya dan telah berkata-kata tentang Dia."
  },
  {Bible:"John", Chapter:12, Verse:42, Page:1,
    Kor:"지도자 가운데서도 예수를 믿는 사람이 많이 생겼으나, 그들은 바리새파 사람들 때문에, 믿는다는 사실을 드러내지는 못하였다. 그것은, 그들이 회당에서 쫓겨날까봐 두려워하였기 때문이다.",
    Chn:"虽然如此，官长中却有好些信他的，只因法利赛人的缘故，就不承认，恐怕被赶出会堂。",
    Eng:"Yet at the same time many even among the leaders believed in him. But because of the Pharisees they would not confess their faith for fear they would be put out of the synagogue;",
    Ind:"Namun banyak juga di antara pemimpin yang percaya kepada-Nya, tetapi oleh karena orang-orang Farisi mereka tidak mengakuinya berterus terang, supaya mereka jangan dikucilkan."
  },
  {Bible:"John", Chapter:12, Verse:43, Page:1,
    Kor:"그들은 하나님의 영광보다도 사람의 영광을 더 사랑하였다.",
    Chn:"这是因他们爱人的荣耀过于爱　神的荣耀。",
    Eng:"for they loved praise from men more than praise from God.",
    Ind:"Sebab mereka lebih suka akan kehormatan manusia dari pada kehormatan Allah."
  },
  {Bible:"John", Chapter:12, Verse:44, Page:1,
    Kor:"<마지막 날과 심판> ○예수께서 큰 소리로 말씀하셨다. \"나를 믿는 사람은 나를 믿는 것이 아니라 나를 보내신 분을 믿는 것이요,",
    Chn:"耶稣大声说：「信我的，不是信我，乃是信那差我来的。",
    Eng:"Then Jesus cried out, \"When a man believes in me, he does not believe in me only, but in the one who sent me.",
    Ind:"Tetapi Yesus berseru kata-Nya: \"Barangsiapa percaya kepada-Ku, ia bukan percaya kepada-Ku, tetapi kepada Dia, yang telah mengutus Aku;"
  },
  {Bible:"John", Chapter:12, Verse:45, Page:1,
    Kor:"나를 보는 사람은 나를 보내신 분을 보는 것이다.",
    Chn:"人看见我，就是看见那差我来的。",
    Eng:"When he looks at me, he sees the one who sent me.",
    Ind:"dan barangsiapa melihat Aku, ia melihat Dia, yang telah mengutus Aku."
  },
  {Bible:"John", Chapter:12, Verse:46, Page:1,
    Kor:"나는 빛으로서 세상에 왔다. 그것은, 나를 믿는 사람은 아무도 어둠 속에 머무르지 않도록 하려는 것이다.",
    Chn:"我到世上来，乃是光，叫凡信我的，不住在黑暗里。",
    Eng:"I have come into the world as a light, so that no one who believes in me should stay in darkness.",
    Ind:"Aku telah datang ke dalam dunia sebagai terang, supaya setiap orang yang percaya kepada-Ku, jangan tinggal di dalam kegelapan."
  },
  {Bible:"John", Chapter:12, Verse:47, Page:1,
    Kor:"어떤 사람이 내 말을 듣고서 그것을 지키지 않는다 하더라도, 나는 그를 심판하지 아니한다. 나는 세상을 심판하러 온 것이 아니라 구원하러 왔다.",
    Chn:"若有人听见我的话不遵守，我不审判他。我来本不是要审判世界，乃是要拯救世界。",
    Eng:"\"As for the person who hears my words but does not keep them, I do not judge him. For I did not come to judge the world, but to save it.",
    Ind:"Dan jikalau seorang mendengar perkataan-Ku, tetapi tidak melakukannya, Aku tidak menjadi hakimnya, sebab Aku datang bukan untuk menghakimi dunia, melainkan untuk menyelamatkannya."
  },
  {Bible:"John", Chapter:12, Verse:48, Page:1,
    Kor:"나를 배척하고 내 말을 받아들이지 않는 사람을 심판하시는 분이 따로 계시다. 내가 말한 바로 이 말이, 마지막 날에 그를 심판할 것이다.",
    Chn:"弃绝我、不领受我话的人，有审判他的—就是我所讲的道在末日要审判他。",
    Eng:"There is a judge for the one who rejects me and does not accept my words; that very word which I spoke will condemn him at the last day.",
    Ind:"Barangsiapa menolak Aku, dan tidak menerima perkataan-Ku, ia sudah ada hakimnya, yaitu firman yang telah Kukatakan, itulah yang akan menjadi hakimnya pada akhir zaman."
  },
  {Bible:"John", Chapter:12, Verse:49, Page:1,
    Kor:"나는 내 마음대로 말한 것이 아니다. 나를 보내신 아버지께서, 내가 무엇을 말해야 하고, 또 무엇을 이야기해야 하는가를, 친히 나에게 명령해 주셨다.",
    Chn:"因为我没有凭着自己讲，惟有差我来的父已经给我命令，叫我说什么，讲什么。",
    Eng:"For I did not speak of my own accord, but the Father who sent me commanded me what to say and how to say it.",
    Ind:"Sebab Aku berkata-kata bukan dari diri-Ku sendiri, tetapi Bapa, yang mengutus Aku, Dialah yang memerintahkan Aku untuk mengatakan apa yang harus Aku katakan dan Aku sampaikan."
  },
  {Bible:"John", Chapter:12, Verse:50, Page:1,
    Kor:"나는 그의 명령이 영생인 줄 안다. 그러므로 나는 무엇이든지 아버지께서 나에게 말씀하여 주신 대로 말할 뿐이다.\"",
    Chn:"我也知道他的命令就是永生。故此，我所讲的话正是照着父对我所说的。」",
    Eng:"I know that his command leads to eternal life. So whatever I say is just what the Father has told me to say.\"",
    Ind:"Dan Aku tahu, bahwa perintah-Nya itu adalah hidup yang kekal. Jadi apa yang Aku katakan, Aku menyampaikannya sebagaimana yang difirmankan oleh Bapa kepada-Ku.\""
  },
]);
