// 요한복음 16장 · John 16
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("John",16,33);
BibleDB.add([
  {Bible:"John", Chapter:16, Verse:1, Page:1,
    Kor:"\"내가 너희에게 이 말을 한 것은, a너희를 넘어지지 않게 하려는 것이다.(a 또는 '너희의 믿음이 흔들리지 않도록')",
    Chn:"「我已将这些事告诉你们，使你们不至于跌倒。",
    Eng:"\"All this I have told you so that you will not go astray.",
    Ind:"\"Semuanya ini Kukatakan kepadamu, supaya kamu jangan kecewa dan menolak Aku."
  },
  {Bible:"John", Chapter:16, Verse:2, Page:1,
    Kor:"사람들이 너희를 회당에서 내쫓을 것이다. 그리고 너희를 죽이는 사람마다, 자기네가 하는 그러한 일이 하나님을 섬기는 일이라고 생각할 때가 올 것이다.",
    Chn:"人要把你们赶出会堂，并且时候将到，凡杀你们的就以为是事奉　神。",
    Eng:"They will put you out of the synagogue; in fact, a time is coming when anyone who kills you will think he is offering a service to God.",
    Ind:"Kamu akan dikucilkan, bahkan akan datang saatnya bahwa setiap orang yang membunuh kamu akan menyangka bahwa ia berbuat bakti bagi Allah."
  },
  {Bible:"John", Chapter:16, Verse:3, Page:1,
    Kor:"그들은 아버지도 나도 알지 못하므로, 그런 일들을 할 것이다.",
    Chn:"他们这样行，是因未曾认识父，也未曾认识我。",
    Eng:"They will do such things because they have not known the Father or me.",
    Ind:"Mereka akan berbuat demikian, karena mereka tidak mengenal baik Bapa maupun Aku."
  },
  {Bible:"John", Chapter:16, Verse:4, Page:1,
    Kor:"내가 너희에게 이 말을 하여 두는 것은, 그들이 그러한 일들을 행하는 때가 올 때에, 너희로 하여금 내가 너희에게 말한 사실을 다시 생각나게 하려는 것이다. <성령의 일> ○또 내가 이 말을 b처음에 하지 않은 것은, 내가 너희와 함께 있었기 때문이다.(b 그, '처음부터')",
    Chn:"我将这事告诉你们，是叫你们到了时候可以想起我对你们说过了。」 「我起先没有将这事告诉你们，因为我与你们同在。",
    Eng:"I have told you this, so that when the time comes you will remember that I warned you. I did not tell you this at first because I was with you.",
    Ind:"Tetapi semuanya ini Kukatakan kepadamu, supaya apabila datang saatnya kamu ingat, bahwa Aku telah mengatakannya kepadamu.\" (16-4b) \"Hal ini tidak Kukatakan kepadamu dari semula, karena selama ini Aku masih bersama-sama dengan kamu,"
  },
  {Bible:"John", Chapter:16, Verse:5, Page:1,
    Kor:"그러나 나는 지금 나를 보내신 분에게로 간다. 그런데 너희 가운데서 아무도 나더러 어디로 가느냐고 묻는 사람이 없고,",
    Chn:"现今我往差我来的父那里去，你们中间并没有人问我：『你往哪里去？』",
    Eng:"\"Now I am going to him who sent me, yet none of you asks me, 'Where are you going?'",
    Ind:"tetapi sekarang Aku pergi kepada Dia yang telah mengutus Aku, dan tiada seorangpun di antara kamu yang bertanya kepada-Ku: Ke mana Engkau pergi?"
  },
  {Bible:"John", Chapter:16, Verse:6, Page:1,
    Kor:"도리어 내가 한 말 때문에 너희 마음에는 슬픔이 가득 찼다.",
    Chn:"只因我将这事告诉你们，你们就满心忧愁。",
    Eng:"Because I have said these things, you are filled with grief.",
    Ind:"Tetapi karena Aku mengatakan hal itu kepadamu, sebab itu hatimu berdukacita."
  },
  {Bible:"John", Chapter:16, Verse:7, Page:1,
    Kor:"그러나, 내가 너희에게 진실을 말하는데, 내가 떠나가는 것이 너희에게 유익하다. 내가 떠나가지 않으면, c보혜사가 너희에게 오시지 않을 것이다. 그러나 내가 가면, 보혜사를 너희에게 보내주겠다.(c '변호해 주시는 분' 또는 '도와주시는 분')",
    Chn:"然而，我将真情告诉你们，我去是与你们有益的；我若不去，保惠师就不到你们这里来；我若去，就差他来。",
    Eng:"But I tell you the truth: It is for your good that I am going away. Unless I go away, the Counselor will not come to you; but if I go, I will send him to you.",
    Ind:"Namun benar yang Kukatakan ini kepadamu: Adalah lebih berguna bagi kamu, jika Aku pergi. Sebab jikalau Aku tidak pergi, Penghibur itu tidak akan datang kepadamu, tetapi jikalau Aku pergi, Aku akan mengutus Dia kepadamu."
  },
  {Bible:"John", Chapter:16, Verse:8, Page:1,
    Kor:"그가 오시면, 죄와 의와 심판에 대하여 세상의 잘못을 깨우치실 것이다.",
    Chn:"他既来了，就要叫世人为罪、为义、为审判，自己责备自己。",
    Eng:"When he comes, he will convict the world of guilt in regard to sin and righteousness and judgment:",
    Ind:"Dan kalau Ia datang, Ia akan menginsafkan dunia akan dosa, kebenaran dan penghakiman;"
  },
  {Bible:"John", Chapter:16, Verse:9, Page:1,
    Kor:"죄에 대하여 깨우친다고 함은 세상 사람들이 나를 믿지 않기 때문이요,",
    Chn:"为罪，是因他们不信我；",
    Eng:"in regard to sin, because men do not believe in me;",
    Ind:"akan dosa, karena mereka tetap tidak percaya kepada-Ku;"
  },
  {Bible:"John", Chapter:16, Verse:10, Page:1,
    Kor:"의에 대하여 깨우친다고 함은 내가 아버지께로 가고 너희가 나를 더 이상 못 볼 것이기 때문이요,",
    Chn:"为义，是因我往父那里去，你们就不再见我；",
    Eng:"in regard to righteousness, because I am going to the Father, where you can see me no longer;",
    Ind:"akan kebenaran, karena Aku pergi kepada Bapa dan kamu tidak melihat Aku lagi;"
  },
  {Bible:"John", Chapter:16, Verse:11, Page:1,
    Kor:"심판에 대하여 깨우친다고 함은 이 세상의 통치자가 심판을 받았기 때문이다.",
    Chn:"为审判，是因这世界的王受了审判。",
    Eng:"and in regard to judgment, because the prince of this world now stands condemned.",
    Ind:"akan penghakiman, karena penguasa dunia ini telah dihukum."
  },
  {Bible:"John", Chapter:16, Verse:12, Page:1,
    Kor:"○아직도, 내가 너희에게 할 말이 많으나, 너희가 지금은 감당하지 못한다.",
    Chn:"「我还有好些事要告诉你们，但你们现在担当不了。",
    Eng:"\"I have much more to say to you, more than you can now bear.",
    Ind:"Masih banyak hal yang harus Kukatakan kepadamu, tetapi sekarang kamu belum dapat menanggungnya."
  },
  {Bible:"John", Chapter:16, Verse:13, Page:1,
    Kor:"그러나 그분 곧 진리의 영이 오시면, 그가 너희를 모든 진리 가운데로 인도하실 것이다. 그는 자기 마음대로 말씀하지 않으시고, 듣는 것만 일러주실 것이요, 앞으로 올 일들을 너희에게 알려 주실 것이다.",
    Chn:"只等真理的圣灵来了，他要引导你们明白一切的真理；因为他不是凭自己说的，乃是把他所听见的都说出来，并要把将来的事告诉你们。",
    Eng:"But when he, the Spirit of truth, comes, he will guide you into all truth. He will not speak on his own; he will speak only what he hears, and he will tell you what is yet to come.",
    Ind:"Tetapi apabila Ia datang, yaitu Roh Kebenaran, Ia akan memimpin kamu ke dalam seluruh kebenaran; sebab Ia tidak akan berkata-kata dari diri-Nya sendiri, tetapi segala sesuatu yang didengar-Nya itulah yang akan dikatakan-Nya dan Ia akan memberitakan kepadamu hal-hal yang akan datang."
  },
  {Bible:"John", Chapter:16, Verse:14, Page:1,
    Kor:"또 그는 나를 영광되게 하실 것이다. 그가 나의 것을 받아서, 너희에게 알려 주실 것이기 때문이다.",
    Chn:"他要荣耀我，因为他要将受于我的告诉你们。",
    Eng:"He will bring glory to me by taking from what is mine and making it known to you.",
    Ind:"Ia akan memuliakan Aku, sebab Ia akan memberitakan kepadamu apa yang diterimanya dari pada-Ku."
  },
  {Bible:"John", Chapter:16, Verse:15, Page:1,
    Kor:"아버지께서 가지신 것은 다 나의 것이다. 그렇기 때문에 내가, 성령이 나의 것을 받아서 너희에게 알려 주실 것이라고 말한 것이다.\"",
    Chn:"凡父所有的，都是我的；所以我说，他要将受于我的告诉你们。」",
    Eng:"All that belongs to the Father is mine. That is why I said the Spirit will take from what is mine and make it known to you.",
    Ind:"Segala sesuatu yang Bapa punya, adalah Aku punya; sebab itu Aku berkata: Ia akan memberitakan kepadamu apa yang diterimanya dari pada-Ku.\""
  },
  {Bible:"John", Chapter:16, Verse:16, Page:1,
    Kor:"<근심이 기쁨으로 변할 것이다> ○\"조금 있으면 너희는 나를 보지 못할 것이다. 그러나 또 조금 있으면 나를 볼 것이다.\"",
    Chn:"「等不多时，你们就不得见我；再等不多时，你们还要见我。」",
    Eng:"\"In a little while you will see me no more, and then after a little while you will see me.\"",
    Ind:"\"Tinggal sesaat saja dan kamu tidak melihat Aku lagi dan tinggal sesaat saja pula dan kamu akan melihat Aku.\""
  },
  {Bible:"John", Chapter:16, Verse:17, Page:1,
    Kor:"그의 제자 가운데서 몇몇이 서로 말하였다. \"그가 우리에게 '조금 있으면 나를 보지 못하게 되고, 또 조금 있으면 나를 볼 것이다' 하신 말씀이나, '내가 아버지께로 가기 때문에'라고 하신 말씀은 무슨 뜻일까?\"",
    Chn:"有几个门徒就彼此说：「他对我们说：『等不多时，你们就不得见我；再等不多时，你们还要见我』；又说：『因我往父那里去。』这是什么意思呢？」",
    Eng:"Some of his disciples said to one another, \"What does he mean by saying, 'In a little while you will see me no more, and then after a little while you will see me,' and 'Because I am going to the Father'?\"",
    Ind:"Mendengar itu beberapa dari murid-Nya berkata seorang kepada yang lain: \"Apakah artinya Ia berkata kepada kita: Tinggal sesaat saja dan kamu tidak melihat Aku dan tinggal sesaat saja pula dan kamu akan melihat Aku? Dan: Aku pergi kepada Bapa?\""
  },
  {Bible:"John", Chapter:16, Verse:18, Page:1,
    Kor:"그들은 말하기를 \"도대체 '조금 있으면'이라는 말씀이 무슨 뜻일까? 우리는, 그가 무엇을 말씀하시는지 모르겠다\" 하였다.",
    Chn:"门徒彼此说：「他说『等不多时』到底是什么意思呢？我们不明白他所说的话。」",
    Eng:"They kept asking, \"What does he mean by 'a little while'? We don't understand what he is saying.\"",
    Ind:"Maka kata mereka: \"Apakah artinya Ia berkata: Tinggal sesaat saja? Kita tidak tahu apa maksud-Nya.\""
  },
  {Bible:"John", Chapter:16, Verse:19, Page:1,
    Kor:"예수께서는, 제자들이 자기에게 물어 보고 싶어하는 마음을 아시고, 그들에게 말씀하셨다. \"내가, '조금 있으면, 너희가 나를 보지 못하게 되고, 또 조금 있으면 나를 볼 것이다' 한 말을 가지고 서로 논의하고 있느냐?",
    Chn:"耶稣看出他们要问他，就说：「我说『等不多时，你们就不得见我；再等不多时，你们还要见我』，你们为这话彼此相问吗？",
    Eng:"Jesus saw that they wanted to ask him about this, so he said to them, \"Are you asking one another what I meant when I said, 'In a little while you will see me no more, and then after a little while you will see me'?",
    Ind:"Yesus tahu, bahwa mereka hendak menanyakan sesuatu kepada-Nya, lalu Ia berkata kepada mereka: \"Adakah kamu membicarakan seorang dengan yang lain apa yang Kukatakan tadi, yaitu: Tinggal sesaat saja dan kamu tidak melihat Aku dan tinggal sesaat saja pula dan kamu akan melihat Aku?"
  },
  {Bible:"John", Chapter:16, Verse:20, Page:1,
    Kor:"내가 진정으로 진정으로 너희에게 말한다. 너희는 울며 애통하겠으나, 세상은 기뻐할 것이다. 그러나 너희가 근심에 싸여도, 그 근심이 기쁨으로 변할 것이다.",
    Chn:"我实实在在地告诉你们，你们将要痛哭、哀号，世人倒要喜乐；你们将要忧愁，然而你们的忧愁要变为喜乐。",
    Eng:"I tell you the truth, you will weep and mourn while the world rejoices. You will grieve, but your grief will turn to joy.",
    Ind:"Aku berkata kepadamu: Sesungguhnya kamu akan menangis dan meratap, tetapi dunia akan bergembira; kamu akan berdukacita, tetapi dukacitamu akan berubah menjadi sukacita."
  },
  {Bible:"John", Chapter:16, Verse:21, Page:1,
    Kor:"여자가 해산할 때에는 근심에 잠긴다. 진통할 때가 왔기 때문이다. 그러나 아이를 낳으면, 사람이 세상에 태어났다는 기쁨 때문에, 그 고통을 더 이상 기억하지 않는다.",
    Chn:"妇人生产的时候就忧愁，因为她的时候到了；既生了孩子，就不再记念那苦楚，因为欢喜世上生了一个人。",
    Eng:"A woman giving birth to a child has pain because her time has come; but when her baby is born she forgets the anguish because of her joy that a child is born into the world.",
    Ind:"Seorang perempuan berdukacita pada saat ia melahirkan, tetapi sesudah ia melahirkan anaknya, ia tidak ingat lagi akan penderitaannya, karena kegembiraan bahwa seorang manusia telah dilahirkan ke dunia."
  },
  {Bible:"John", Chapter:16, Verse:22, Page:1,
    Kor:"이와 같이, 지금 너희가 근심에 싸여 있지만, 내가 다시 너희를 볼 때에는, 너희의 마음이 기쁠 것이며, 그 기쁨을 너희에게서 빼앗을 사람이 없을 것이다.",
    Chn:"你们现在也是忧愁，但我要再见你们，你们的心就喜乐了；这喜乐也没有人能夺去。",
    Eng:"So with you: Now is your time of grief, but I will see you again and you will rejoice, and no one will take away your joy.",
    Ind:"Demikian juga kamu sekarang diliputi dukacita, tetapi Aku akan melihat kamu lagi dan hatimu akan bergembira dan tidak ada seorangpun yang dapat merampas kegembiraanmu itu dari padamu."
  },
  {Bible:"John", Chapter:16, Verse:23, Page:1,
    Kor:"그 날에는 너희가 나에게 아무것도 d묻지 않을 것이다. 내가 진정으로 진정으로 너희에게 말한다. e너희가 아버지께 구하는 것은, 무엇이나 아버지께서 내 이름으로 주실 것이다.(d 또는 '요구하지' e 다른 고대 사본들에는 '너희가 내 이름으로 아버지께 구하면, 아버지께서 그것을 너희에게 주실 것이다')",
    Chn:"到那日，你们什么也就不问我了。我实实在在地告诉你们，你们若向父求什么，他必因我的名赐给你们。",
    Eng:"In that day you will no longer ask me anything. I tell you the truth, my Father will give you whatever you ask in my name.",
    Ind:"Dan pada hari itu kamu tidak akan menanyakan apa-apa kepada-Ku. Aku berkata kepadamu: Sesungguhnya segala sesuatu yang kamu minta kepada Bapa, akan diberikan-Nya kepadamu dalam nama-Ku."
  },
  {Bible:"John", Chapter:16, Verse:24, Page:1,
    Kor:"지금까지는 너희가 아무것도 내 이름으로 구하지 않았다. 구하여라. 그러면 받을 것이다. 그래서 너희의 기쁨이 넘치게 될 것이다.\"",
    Chn:"向来你们没有奉我的名求什么，如今你们求，就必得着，叫你们的喜乐可以满足。」",
    Eng:"Until now you have not asked for anything in my name. Ask and you will receive, and your joy will be complete.",
    Ind:"Sampai sekarang kamu belum meminta sesuatupun dalam nama-Ku. Mintalah maka kamu akan menerima, supaya penuhlah sukacitamu."
  },
  {Bible:"John", Chapter:16, Verse:25, Page:1,
    Kor:"<내가 세상을 이겼다> ○\"지금까지는 이런 것들을 내가 너희에게 비유로 말하였으나, 다시는 내가 비유로 말하지 아니하고 아버지에 대하여 분명히 말해 줄 때가 올 것이다.",
    Chn:"「这些事，我是用比喻对你们说的；时候将到，我不再用比喻对你们说，乃要将父明明地告诉你们。",
    Eng:"\"Though I have been speaking figuratively, a time is coming when I will no longer use this kind of language but will tell you plainly about my Father.",
    Ind:"Semuanya ini Kukatakan kepadamu dengan kiasan. Akan tiba saatnya Aku tidak lagi berkata-kata kepadamu dengan kiasan, tetapi terus terang memberitakan Bapa kepadamu."
  },
  {Bible:"John", Chapter:16, Verse:26, Page:1,
    Kor:"그 날에는 너희가 내 이름으로 아버지께 구할 것이다. 내가 너희를 위하여 아버지께 구하겠다는 말이 아니다.",
    Chn:"到那日，你们要奉我的名祈求；我并不对你们说，我要为你们求父。",
    Eng:"In that day you will ask in my name. I am not saying that I will ask the Father on your behalf.",
    Ind:"Pada hari itu kamu akan berdoa dalam nama-Ku. Dan tidak Aku katakan kepadamu, bahwa Aku meminta bagimu kepada Bapa,"
  },
  {Bible:"John", Chapter:16, Verse:27, Page:1,
    Kor:"아버지께서는 친히 너희를 사랑하신다. 그것은, 너희가 나를 사랑하였고, 또 내가 f하나님께로부터 온 것을 믿었기 때문이다.(f 다른 고대 사본들에는 '아버지께로부터')",
    Chn:"父自己爱你们；因为你们已经爱我，又信我是从父出来的。",
    Eng:"No, the Father himself loves you because you have loved me and have believed that I came from God.",
    Ind:"sebab Bapa sendiri mengasihi kamu, karena kamu telah mengasihi Aku dan percaya, bahwa Aku datang dari Allah."
  },
  {Bible:"John", Chapter:16, Verse:28, Page:1,
    Kor:"나는 아버지에게서 나와서 세상에 왔다. 나는 세상을 떠나서 아버지께로 간다.\"",
    Chn:"我从父出来，到了世界；我又离开世界，往父那里去。」",
    Eng:"I came from the Father and entered the world; now I am leaving the world and going back to the Father.\"",
    Ind:"Aku datang dari Bapa dan Aku datang ke dalam dunia; Aku meninggalkan dunia pula dan pergi kepada Bapa.\""
  },
  {Bible:"John", Chapter:16, Verse:29, Page:1,
    Kor:"그의 제자들이 말하였다. \"보십시오. 이제 밝히어 말씀하여 주시고, 비유로 말씀하지 않으시니,",
    Chn:"门徒说：「如今你是明说，并不用比喻了。",
    Eng:"Then Jesus' disciples said, \"Now you are speaking clearly and without figures of speech.",
    Ind:"Kata murid-murid-Nya: \"Lihat, sekarang Engkau terus terang berkata-kata dan Engkau tidak memakai kiasan."
  },
  {Bible:"John", Chapter:16, Verse:30, Page:1,
    Kor:"이제야 우리는, 선생님께서 모든 것을 알고 계시다는 것과, 누가 선생님께 물어볼 필요가 없을 정도로 환히 알려 주신다는 것을 알았습니다. 이것으로 우리는 선생님이 하나님께로부터 오신 것을 믿습니다.\"",
    Chn:"现在我们晓得你凡事都知道，也不用人问你，因此我们信你是从　神出来的。」",
    Eng:"Now we can see that you know all things and that you do not even need to have anyone ask you questions. This makes us believe that you came from God.\"",
    Ind:"Sekarang kami tahu, bahwa Engkau mengetahui segala sesuatu dan tidak perlu orang bertanya kepada-Mu. Karena itu kami percaya, bahwa Engkau datang dari Allah.\""
  },
  {Bible:"John", Chapter:16, Verse:31, Page:1,
    Kor:"예수께서 대답하셨다. \"이제는 너희가 믿느냐?",
    Chn:"耶稣说：「现在你们信吗？",
    Eng:"\"You believe at last!\" Jesus answered.",
    Ind:"Jawab Yesus kepada mereka: \"Percayakah kamu sekarang?"
  },
  {Bible:"John", Chapter:16, Verse:32, Page:1,
    Kor:"보아라, 너희가 나를 혼자 버려 두고, 제각기 자기 집으로 흩어져 갈 때가 올 것이다. 그 때가 벌써 왔다. 그런데 아버지께서 나와 함께 계시니, 나는 혼자 있는 것이 아니다.",
    Chn:"看哪，时候将到，且是已经到了，你们要分散，各归自己的地方去，留下我独自一人；其实我不是独自一人，因为有父与我同在。",
    Eng:"\"But a time is coming, and has come, when you will be scattered, each to his own home. You will leave me all alone. Yet I am not alone, for my Father is with me.",
    Ind:"Lihat, saatnya datang, bahkan sudah datang, bahwa kamu diceraiberaikan masing-masing ke tempatnya sendiri dan kamu meninggalkan Aku seorang diri. Namun Aku tidak seorang diri, sebab Bapa menyertai Aku."
  },
  {Bible:"John", Chapter:16, Verse:33, Page:1,
    Kor:"내가 이것을 너희에게 말한 것은, 너희가 내 안에서 평화를 얻게 하려는 것이다. 너희는 세상에서 환난을 당할 것이다. 그러나 용기를 내어라. 내가 세상을 이겼다.\"",
    Chn:"我将这些事告诉你们，是要叫你们在我里面有平安。在世上，你们有苦难；但你们可以放心，我已经胜了世界。」",
    Eng:"\"I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.\"",
    Ind:"Semuanya itu Kukatakan kepadamu, supaya kamu beroleh damai sejahtera dalam Aku. Dalam dunia kamu menderita penganiayaan, tetapi kuatkanlah hatimu, Aku telah mengalahkan dunia.\""
  },
]);
