// 사무엘상 8장 · 1Samuel 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Samuel",8,22);
BibleDB.add([
  {Bible:"1Samuel", Chapter:8, Verse:1, Page:1, Kor:"<백성이 왕을 요구하다> 사무엘은 늙자, 자기의 아들들을 이스라엘의 사사로 세웠다.", Chn:"", Eng:"When Samuel grew old, he appointed his sons as judges for Israel.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:2, Page:1, Kor:"맏아들의 이름은 요엘이요, 둘째 아들의 이름은 아비야다. 그들은 브엘세바에서 사사로 일하였다.", Chn:"", Eng:"The name of his firstborn was Joel and the name of his second was Abijah, and they served at Beersheba.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:3, Page:1, Kor:"그러나 그 아들들은 아버지의 길을 따라 살지 않고, 돈벌이에만 정신이 팔려, 뇌물을 받고서, 치우치게 재판을 하였다.", Chn:"", Eng:"But his sons did not walk in his ways. They turned aside after dishonest gain and accepted bribes and perverted justice.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:4, Page:1, Kor:"○그래서 이스라엘의 모든 장로가 모여서, 라마로 사무엘을 찾아갔다.", Chn:"", Eng:"So all the elders of Israel gathered together and came to Samuel at Ramah.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:5, Page:1, Kor:"그들이 사무엘에게 말하였다. \"보십시오, 어른께서는 늙으셨고, 아드님들은 어른께서 걸어오신 그 길을 따라 살지 않습니다. 그러므로 이제 모든 이방 나라들처럼, 우리에게 왕을 세워 주셔서, 왕이 우리를 다스리게 하여 주십시오.\"", Chn:"", Eng:"They said to him, \"You are old, and your sons do not walk in your ways; now appoint a king to lead us, such as all the other nations have.\"", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:6, Page:1, Kor:"그러나 사무엘은 왕을 세워 다스리게 해 달라는 장로들의 말에 마음이 상하여, 주님께 기도를 드렸더니,", Chn:"", Eng:"But when they said, \"Give us a king to lead us,\" this displeased Samuel; so he prayed to the LORD.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:7, Page:1, Kor:"주님께서 사무엘에게 말씀하셨다. \"백성이 너에게 한 말을 다 들어 주어라. 그들이 너를 버린 것이 아니라, 나를 버려서 자기들의 왕이 되지 못하게 한 것이다.", Chn:"", Eng:"And the LORD told him: \"Listen to all that the people are saying to you; it is not you they have rejected, but they have rejected me as their king.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:8, Page:1, Kor:"그들은 내가 이집트에서 데리고 올라온 날부터 오늘까지, 하는 일마다 그렇게 하여, 나를 버리고 다른 신들을 섬기더니, 너에게도 그렇게 하고 있다.", Chn:"", Eng:"As they have done from the day I brought them up out of Egypt until this day, forsaking me and serving other gods, so they are doing to you.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:9, Page:1, Kor:"그러니 너는 이제 그들의 말을 들어 주되, 엄히 경고하여, 그들을 다스릴 왕의 권한이 어떠한 것인지를 알려 주어라.\"", Chn:"", Eng:"Now listen to them; but warn them solemnly and let them know what the king who will reign over them will do.\"", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:10, Page:1, Kor:"○사무엘은 왕을 세워 달라고 요구하는 백성들에게, 주님께서 하신 모든 말씀을 그대로 전하였다.", Chn:"", Eng:"Samuel told all the words of the LORD to the people who were asking him for a king.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:11, Page:1, Kor:"\"당신들을 다스릴 왕의 권한은 이러합니다. 그는 당신들의 아들들을 데려다가 그의 병거와 말을 다루는 일을 시키고, 병거 앞에서 달리게 할 것입니다.", Chn:"", Eng:"He said, \"This is what the king who will reign over you will do: He will take your sons and make them serve with his chariots and horses, and they will run in front of his chariots.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:12, Page:1, Kor:"그는 당신들의 아들들을 천부장과 오십부장으로 임명하기도 하고, 왕의 밭을 갈게도 하고, 곡식을 거두어들이게도 하고, 무기와 병거의 장비도 만들게 할 것입니다.", Chn:"", Eng:"Some he will assign to be commanders of thousands and commanders of fifties, and others to plow his ground and reap his harvest, and still others to make weapons of war and equipment for his chariots.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:13, Page:1, Kor:"그는 당신들의 딸들을 데려다가, 향유도 만들게 하고 요리도 시키고 빵도 굽게 할 것입니다.", Chn:"", Eng:"He will take your daughters to be perfumers and cooks and bakers.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:14, Page:1, Kor:"그는 당신들의 밭과 포도원과 올리브 밭에서 가장 좋은 것을 가져다가 왕의 신하들에게 줄 것이며,", Chn:"", Eng:"He will take the best of your fields and vineyards and olive groves and give them to his attendants.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:15, Page:1, Kor:"당신들이 둔 곡식과 포도에서도 열에 하나를 거두어 왕의 관리들과 신하들에게 줄 것입니다.", Chn:"", Eng:"He will take a tenth of your grain and of your vintage and give it to his officials and attendants.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:16, Page:1, Kor:"그는 당신들의 남종들과 여종들과 a가장 뛰어난 젊은이들과 나귀들을 끌어다가 왕의 일을 시킬 것입니다.(a 칠십인역에는 '너희가 가진 가장 좋은 짐승들과')", Chn:"", Eng:"Your menservants and maidservants and the best of your cattle and donkeys he will take for his own use.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:17, Page:1, Kor:"그는 또 당신들의 양 떼 가운데서 열에 하나를 거두어 갈 것이며, 마침내 당신들까지 왕의 종이 될 것입니다.", Chn:"", Eng:"He will take a tenth of your flocks, and you yourselves will become his slaves.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:18, Page:1, Kor:"그 때에야 당신들이 스스로 택한 왕 때문에 울부짖을 터이지만, 그 때에 주님께서는 당신들의 기도에 응답하지 않으실 것입니다.\"", Chn:"", Eng:"When that day comes, you will cry out for relief from the king you have chosen, and the LORD will not answer you in that day.\"", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:19, Page:1, Kor:"○이렇게 일러주어도 백성은, 사무엘의 말을 듣지 않고 말하였다. \"그렇지 않습니다. 우리에게도 왕이 있어야 되겠습니다.", Chn:"", Eng:"But the people refused to listen to Samuel. \"No!\" they said. \"We want a king over us.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:20, Page:1, Kor:"우리도 모든 이방 나라들처럼, 우리의 왕이 우리를 다스리며, 그 왕이 우리를 이끌고 나가서, 전쟁에서 싸워야 할 것입니다.\"", Chn:"", Eng:"Then we will be like all the other nations, with a king to lead us and to go out before us and fight our battles.\"", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:21, Page:1, Kor:"사무엘이 백성의 모든 말을 듣고 나서, 주님께서 들으시도록 다 아뢰니,", Chn:"", Eng:"When Samuel heard all that the people said, he repeated it before the LORD.", Ind:""},
  {Bible:"1Samuel", Chapter:8, Verse:22, Page:1, Kor:"주님께서 사무엘에게 말씀하셨다. \"너는 그들의 말을 받아들여서 그들에게 왕을 세워 주어라.\" 그래서 사무엘은 이스라엘 사람들에게, 각자 자기의 성읍으로 돌아가라고 일렀다.", Chn:"", Eng:"The LORD answered, \"Listen to them and give them a king.\" Then Samuel said to the men of Israel, \"Everyone go back to his town.\"", Ind:""},
]);
