// 사무엘상 28장 · 1Samuel 28
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Samuel",28,25);
BibleDB.add([
  {Bible:"1Samuel", Chapter:28, Verse:1, Page:1,
    Kor:"그럴 즈음에 블레셋 사람이 이스라엘에 쳐들어가려고 모든 부대를 집결시켰다. 그러자 아기스가 다윗에게 말하였다. \"귀관이 나와 함께 출정하여야 한다는 것을 알고 있을 줄 아오. 귀관은 부하들을 거느리고 직접 출정하시오.\"",
    Chn:"那时，非利士人聚集军旅，要与以色列人打仗。亚吉对大卫说：「你当知道，你和跟随你的人都要随我出战。」",
    Eng:"In those days the Philistines gathered their forces to fight against Israel. Achish said to David, \"You must understand that you and your men will accompany me in the army.\"",
    Ind:"Pada waktu itu orang Filistin mengerahkan tentaranya untuk berperang melawan orang Israel. Lalu berkatalah Akhis kepada Daud: \"Ketahuilah baik-baik, bahwa engkau beserta orang-orangmu harus maju berperang bersama-sama dengan aku dalam tentara.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:2, Page:1,
    Kor:"다윗이 아기스에게 대답하였다. \"그렇게 하겠습니다. 이 종이 무엇을 할 수 있는지, 임금님이 아시게 될 것입니다.\" 아기스가 다윗에게 말하였다. \"좋소! 귀관을 나의 종신 경호대장으로 삼겠소.\"",
    Chn:"大卫对亚吉说：「仆人所能做的事，王必知道。」亚吉对大卫说：「这样，我立你永远作我的护卫长。」",
    Eng:"David said, \"Then you will see for yourself what your servant can do.\" Achish replied, \"Very well, I will make you my bodyguard for life.\"",
    Ind:"Jawab Daud kepada Akhis: \"Baik, engkau akan tahu, apa yang dapat diperbuat hambamu ini.\" Lalu Akhis berkata kepada Daud: \"Sebab itu aku mengangkat engkau menjadi pengawalku sendiri sampai selamanya.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:3, Page:1,
    Kor:"<사울이 무당을 찾아가다> ○사무엘이 이미 죽어서 온 이스라엘 백성이 그의 죽음을 슬퍼하며, 그를 그의 고향 라마에 장사지낸 뒤였다. 그리고 사울이 나라 안에서 무당과 박수를 모조리 쫓아낸 때였다.",
    Chn:"那时撒母耳已经死了，以色列众人为他哀哭，葬他在拉玛，就是在他本城里。扫罗曾在国内不容有交鬼的和行巫术的人。",
    Eng:"Now Samuel was dead, and all Israel had mourned for him and buried him in his own town of Ramah. Saul had expelled the mediums and spiritists from the land.",
    Ind:"Adapun Samuel sudah mati. Seluruh orang Israel sudah meratapi dia dan mereka telah menguburkan dia di Rama, di kotanya. Dan Saul telah menyingkirkan dari dalam negeri para pemanggil arwah dan roh peramal."
  },
  {Bible:"1Samuel", Chapter:28, Verse:4, Page:1,
    Kor:"○바로 그 때에 블레셋 군대가 모여서 수넴에 진을 쳤다. 사울도 온 이스라엘 군을 집결시켜, 길보아 산에 진을 쳤다.",
    Chn:"非利士人聚集，来到书念安营；扫罗聚集以色列众人在基利波安营。",
    Eng:"The Philistines assembled and came and set up camp at Shunem, while Saul gathered all the Israelites and set up camp at Gilboa.",
    Ind:"Orang Filistin itu berkumpul, lalu bergerak maju, dan berkemah dekat Sunem. Saul mengumpulkan seluruh orang Israel, lalu mereka berkemah di Gilboa."
  },
  {Bible:"1Samuel", Chapter:28, Verse:5, Page:1,
    Kor:"사울은 블레셋 군의 진을 보고, 두려워서 마음이 몹시 떨렸다.",
    Chn:"扫罗看见非利士的军旅就惧怕，心中发颤。",
    Eng:"When Saul saw the Philistine army, he was afraid; terror filled his heart.",
    Ind:"Ketika Saul melihat tentara Filistin itu, maka takutlah ia dan hatinya sangat gemetar."
  },
  {Bible:"1Samuel", Chapter:28, Verse:6, Page:1,
    Kor:"사울이 주님께 물었으나, 주님께서는 그에게 꿈으로도, 우림으로도, 예언자로도, 대답하여 주지 않으셨다.",
    Chn:"扫罗求问耶和华，耶和华却不借梦，或乌陵，或先知回答他。",
    Eng:"He inquired of the LORD, but the LORD did not answer him by dreams or Urim or prophets.",
    Ind:"Dan Saul bertanya kepada TUHAN, tetapi TUHAN tidak menjawab dia, baik dengan mimpi, baik dengan Urim, baik dengan perantaraan para nabi."
  },
  {Bible:"1Samuel", Chapter:28, Verse:7, Page:1,
    Kor:"그래서 사울은 자기의 신하들에게 명령하였다. \"망령을 불러올리는 여자 무당을 한 사람 찾아 보아라. 내가 그 여인을 찾아가서 물어 보겠다.\" 사울의 신하들이 그에게 말하였다. \"엔돌에 망령을 불러올리는 무당이 한 사람 있습니다.\"",
    Chn:"扫罗吩咐臣仆说：「当为我找一个交鬼的妇人，我好去问她。」臣仆说：「在隐·多珥有一个交鬼的妇人。」",
    Eng:"Saul then said to his attendants, \"Find me a woman who is a medium, so I may go and inquire of her.\" \"There is one in Endor,\" they said.",
    Ind:"Lalu berkatalah Saul kepada para pegawainya: \"Carilah bagiku seorang perempuan yang sanggup memanggil arwah; maka aku hendak pergi kepadanya dan meminta petunjuk kepadanya.\" Para pegawainya menjawab dia: \"Di En-Dor ada seorang perempuan yang sanggup memanggil arwah.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:8, Page:1,
    Kor:"○사울은 다른 옷으로 갈아 입고 변장한 다음에, 두 신하를 데리고 갔다. 밤에 그들이 그 여인에게 이르렀는데, 사울이 그에게 말하였다. \"망령을 부르는 술법으로, 내가 당신에게 말하는 사람을 나에게 불러올려 주시오.\"",
    Chn:"于是扫罗改了装，穿上别的衣服，带着两个人，夜里去见那妇人。扫罗说：「求你用交鬼的法术，将我所告诉你的死人，为我招上来。」",
    Eng:"So Saul disguised himself, putting on other clothes, and at night he and two men went to the woman. \"Consult a spirit for me,\" he said, \"and bring up for me the one I name.\"",
    Ind:"Lalu menyamarlah Saul, ia mengenakan pakaian lain dan pergilah ia dengan dua orang. Ketika mereka pada waktu malam sampai kepada perempuan itu, berkatalah Saul: \"Cobalah engkau menenung bagiku dengan perantaraan arwah, dan panggillah supaya muncul kepadaku orang yang akan kusebut kepadamu.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:9, Page:1,
    Kor:"그러나 그 여인이 그에게 대답하였다. \"이것 보시오. 사울이 이 나라에서 무당과 박수를 모조리 잡아 죽인 것은, 당신도 잘 아시지 않습니까? 그런데 왜 당신은 나의 목에 올가미를 씌워, 나를 죽이려고 하십니까?\"",
    Chn:"妇人对他说：「你知道扫罗从国中剪除交鬼的和行巫术的。你为何陷害我的性命，使我死呢？」",
    Eng:"But the woman said to him, \"Surely you know what Saul has done. He has cut off the mediums and spiritists from the land. Why have you set a trap for my life to bring about my death?\"",
    Ind:"Tetapi perempuan itu menjawabnya: \"Tentu engkau mengetahui apa yang diperbuat Saul, bahwa ia telah melenyapkan dari dalam negeri para pemanggil arwah dan roh peramal. Mengapa engkau memasang jerat terhadap nyawaku untuk membunuh aku?\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:10, Page:1,
    Kor:"사울이 주님의 이름을 걸고 그 여인에게 맹세하였다. \"주님께서 확실히 살아 계심을 걸고 맹세하지만, 당신이 이 일로는 아무런 벌도 받지 않을 것이오.\"",
    Chn:"扫罗向妇人指着耶和华起誓说：「我指着永生的耶和华起誓，你必不因这事受刑。」",
    Eng:"Saul swore to her by the LORD, \"As surely as the LORD lives, you will not be punished for this.\"",
    Ind:"Lalu bersumpahlah Saul kepadanya demi TUHAN, katanya: \"Demi TUHAN yang hidup, tidak akan ada kesalahan tertimpa kepadamu karena perkara ini.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:11, Page:1,
    Kor:"그 여인이 물었다. \"내가 당신에게 누구를 불러올릴까요?\" 사울이 대답하였다. \"나에게 사무엘을 불러올리시오.\"",
    Chn:"妇人说：「我为你招谁上来呢？」回答说：「为我招撒母耳上来。」",
    Eng:"Then the woman asked, \"Whom shall I bring up for you?\" \"Bring up Samuel,\" he said.",
    Ind:"Sesudah itu bertanyalah perempuan itu: \"Siapakah yang harus kupanggil supaya muncul kepadamu?\" Jawabnya: \"Panggillah Samuel supaya muncul kepadaku.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:12, Page:1,
    Kor:"○그 여인은 사무엘이 올라온 것을 보고, 놀라서 큰소리를 질렀다. 그런 다음에, 그 여인은 사울에게 항의하였다. \"사울 임금님이 몸소 오셨으면서도 왜 저를 속이셨습니까?\"",
    Chn:"妇人看见撒母耳，就大声呼叫，对扫罗说：「你是扫罗，为什么欺哄我呢？」",
    Eng:"When the woman saw Samuel, she cried out at the top of her voice and said to Saul, \"Why have you deceived me? You are Saul!\"",
    Ind:"Ketika perempuan itu melihat Samuel, berteriaklah ia dengan suara nyaring. Lalu perempuan itu berkata kepada Saul, demikian: \"Mengapa engkau menipu aku? Engkau sendirilah Saul!\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:13, Page:1,
    Kor:"왕이 그 여인에게 말하였다. \"무서워하지 말아라. 네가 무엇을 보고 있느냐?\" 여인이 사울에게 대답하였다. \"땅 속에서 a영이 올라온 것을 보고 있습니다.\"(a 또는 '신' 또는 '신들')",
    Chn:"王对妇人说：「不要惧怕，你看见了什么呢？」妇人对扫罗说：「我看见有神从地里上来。」",
    Eng:"The king said to her, \"Don't be afraid. What do you see?\" The woman said, \"I see a spirit coming up out of the ground.\"",
    Ind:"Maka berbicaralah raja kepadanya: \"Janganlah takut; tetapi apakah yang kaulihat?\" Perempuan itu menjawab Saul: \"Aku melihat sesuatu yang ilahi muncul dari dalam bumi.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:14, Page:1,
    Kor:"사울이 그 여인에게 물었다. \"그 모습이 어떠하냐?\" 여인이 대답하였다. \"한 노인이 올라오는데, 겉옷을 걸치고 있습니다.\" 사울은 그가 사무엘인 것을 알아차리고, 얼굴이 땅에 닿도록 엎드려 절을 하였다.",
    Chn:"扫罗说：「他是怎样的形状？」妇人说：「有一个老人上来，身穿长衣。」扫罗知道是撒母耳，就屈身，脸伏于地下拜。",
    Eng:"\"What does he look like?\" he asked. \"An old man wearing a robe is coming up,\" she said. Then Saul knew it was Samuel, and he bowed down and prostrated himself with his face to the ground.",
    Ind:"Kemudian bertanyalah ia kepada perempuan itu: \"Bagaimana rupanya?\" Jawabnya: \"Ada seorang tua muncul, berselubungkan jubah.\" Maka tahulah Saul, bahwa itulah Samuel, lalu berlututlah ia dengan mukanya sampai ke tanah dan sujud menyembah."
  },
  {Bible:"1Samuel", Chapter:28, Verse:15, Page:1,
    Kor:"○사무엘이 사울에게 물었다. \"당신이 왜 나를 불러올려 귀찮게 하시오?\" 사울이 대답하였다. \"제가 매우 궁지에 몰려 있습니다. 블레셋 사람이 지금 저를 치고 있는데, 하나님이 이미 저에게서 떠나셨고, 예언자로도, 꿈으로도, 더 이상 저에게 응답을 하지 않으십니다. 그래서 제가 무엇을 어떻게 해야 하는지 알고 싶어서, 이처럼 어른을 뵙도록 해 달라고 부탁하였습니다.\"",
    Chn:"撒母耳对扫罗说：「你为什么搅扰我，招我上来呢？」扫罗回答说：「我甚窘急；因为非利士人攻击我，　神也离开我，不再借先知或梦回答我。因此请你上来，好指示我应当怎样行。」",
    Eng:"Samuel said to Saul, \"Why have you disturbed me by bringing me up?\" \"I am in great distress,\" Saul said. \"The Philistines are fighting against me, and God has turned away from me. He no longer answers me, either by prophets or by dreams. So I have called on you to tell me what to do.\"",
    Ind:"Sesudah itu berbicaralah Samuel kepada Saul: \"Mengapa engkau mengganggu aku dengan memanggil aku muncul?\" Kata Saul: \"Aku sangat dalam keadaan terjepit: orang Filistin berperang melawan aku, dan Allah telah undur dari padaku. Ia tidak menjawab aku lagi, baik dengan perantaraan nabi maupun dengan mimpi. Sebab itu aku memanggil engkau, supaya engkau memberitahukan kepadaku, apa yang harus kuperbuat.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:16, Page:1,
    Kor:"사무엘이 책망하였다. \"주님께서는 이미 당신에게서 떠나 당신의 원수가 되셨는데, 나에게 더 묻는 이유가 무엇이오?",
    Chn:"撒母耳说：「耶和华已经离开你，且与你为敌，你何必问我呢？",
    Eng:"Samuel said, \"Why do you consult me, now that the LORD has turned away from you and become your enemy?",
    Ind:"Lalu berbicaralah Samuel: \"Mengapa engkau bertanya kepadaku, padahal TUHAN telah undur dari padamu dan telah menjadi musuhmu?"
  },
  {Bible:"1Samuel", Chapter:28, Verse:17, Page:1,
    Kor:"주님께서는, 나를 시켜 전하신 말씀 그대로 당신에게 하셔서, 이미 이 나라의 왕위를 당신의 손에서 빼앗아 당신의 가까이에 있는 다윗에게 주셨소.",
    Chn:"耶和华照他借我说的话，已经从你手里夺去国权，赐与别人，就是大卫。",
    Eng:"The LORD has done what he predicted through me. The LORD has torn the kingdom out of your hands and given it to one of your neighbors--to David.",
    Ind:"TUHAN telah melakukan kepadamu seperti yang difirmankan-Nya dengan perantaraanku, yakni TUHAN telah mengoyakkan kerajaan dari tanganmu dan telah memberikannya kepada orang lain, kepada Daud."
  },
  {Bible:"1Samuel", Chapter:28, Verse:18, Page:1,
    Kor:"당신은 주님께 순종하지 아니하고, 주님의 분노를 아말렉에게 쏟지 아니하였소. 그렇기 때문에 주님께서 오늘 당신에게 이렇게 하셨소.",
    Chn:"因你没有听从耶和华的命令；他恼怒亚玛力人，你没有灭绝他们，所以今日耶和华向你这样行，",
    Eng:"Because you did not obey the LORD or carry out his fierce wrath against the Amalekites, the LORD has done this to you today.",
    Ind:"Karena engkau tidak mendengarkan suara TUHAN dan tidak melaksanakan murka-Nya yang bernyala-nyala itu atas Amalek, itulah sebabnya TUHAN melakukan hal itu kepadamu pada hari ini."
  },
  {Bible:"1Samuel", Chapter:28, Verse:19, Page:1,
    Kor:"주님께서는 이제 당신과 함께 이스라엘도 블레셋 사람의 손에 넘겨 주실 터인데, 당신은 내일 당신 자식들과 함께 내가 있는 이 곳으로 오게 될 것이오. 주님께서는 이스라엘 군대도 블레셋 사람의 손에 넘겨 주실 것이오.\"",
    Chn:"并且耶和华必将你和以色列人交在非利士人的手里。明日你和你众子必与我在一处了；耶和华必将以色列的军兵交在非利士人手里。」",
    Eng:"The LORD will hand over both Israel and you to the Philistines, and tomorrow you and your sons will be with me. The LORD will also hand over the army of Israel to the Philistines.\"",
    Ind:"Juga orang Israel bersama-sama dengan engkau akan diserahkan TUHAN ke dalam tangan orang Filistin, dan besok engkau serta anak-anakmu sudah ada bersama-sama dengan daku. Juga tentara Israel akan diserahkan TUHAN ke dalam tangan orang Filistin.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:20, Page:1,
    Kor:"○그러자 사울은 갑자기 그 자리에 쓰러져 땅바닥에 벌렁 넘어졌다. 사무엘의 말을 듣고서, 너무나 두려웠기 때문이다. 게다가 그는 그 날 하루 종일, 그리고 밤새도록 굶었으므로, 힘마저 쭉 빠져 있었다.",
    Chn:"扫罗猛然仆倒，挺身在地，因撒母耳的话甚是惧怕；那一昼一夜，没有吃什么，就毫无气力。",
    Eng:"Immediately Saul fell full length on the ground, filled with fear because of Samuel's words. His strength was gone, for he had eaten nothing all that day and night.",
    Ind:"Pada saat itu juga rebahlah Saul memanjang ke tanah sebab ia sangat ketakutan oleh karena perkataan Samuel itu. Juga tidak ada lagi kekuatannya, karena sehari semalam itu ia tidak makan apa-apa."
  },
  {Bible:"1Samuel", Chapter:28, Verse:21, Page:1,
    Kor:"그 여인이 사울에게 가까이 와서, 그가 아주 기진맥진해 있는 것을 보고, 그에게 말하였다. \"보십시오, 이 종은 임금님의 분부를 다 따랐습니다. 저는 목숨을 내놓고, 임금님이 저에게 명령하신 대로 다 이루어 드렸습니다.",
    Chn:"妇人到扫罗面前，见他极其惊恐，对他说：「婢女听从你的话，不顾惜自己的性命，遵从你所吩咐的。",
    Eng:"When the woman came to Saul and saw that he was greatly shaken, she said, \"Look, your maidservant has obeyed you. I took my life in my hands and did what you told me to do.",
    Ind:"Perempuan itu mendekati Saul lalu melihat, bahwa Saul sangat terkejut. Kemudian berkatalah perempuan itu kepadanya: \"Lihat, budakmu ini telah mendengarkan permintaanmu; aku telah mempertaruhkan nyawaku dan mendengarkan perkataan yang kaukatakan kepadaku."
  },
  {Bible:"1Samuel", Chapter:28, Verse:22, Page:1,
    Kor:"그러므로 이제는 임금님도 이 종의 말씀을 들어 주시기 바랍니다. 제가 임금님께 음식을 좀 대접하여 드리겠습니다. 임금님이 길을 더 가시려면 기운을 차리셔야 하니, 음식을 드시기 바랍니다.\"",
    Chn:"现在求你听婢女的话，容我在你面前摆上一点食物，你吃了，可以有气力行路。」",
    Eng:"Now please listen to your servant and let me give you some food so you may eat and have the strength to go on your way.\"",
    Ind:"Oleh sebab itu, kiranya engkaupun mendengarkan permintaan budakmu ini. Izinkanlah aku menyajikan kepadamu sepotong roti; makanlah, supaya ada kekuatanmu, apabila engkau berjalan pula.\""
  },
  {Bible:"1Samuel", Chapter:28, Verse:23, Page:1,
    Kor:"그러나 사울은 \"아무것도 먹고 싶지 않다!\" 하고 말하면서, 그 여인의 청을 거절하였다. 그러나 사울의 신하들까지 그 여인과 함께 사울에게 권하니, 사울이 그들의 말을 듣고, 땅바닥에서 일어나 평상에 앉았다.",
    Chn:"扫罗不肯，说：「我不吃。」但他的仆人和妇人再三劝他，他才听了他们的话，从地上起来，坐在床上。",
    Eng:"He refused and said, \"I will not eat.\" But his men joined the woman in urging him, and he listened to them. He got up from the ground and sat on the couch.",
    Ind:"Tetapi Saul menolak dan berkata: \"Aku tidak mau makan.\" Tetapi ketika para pegawainya serta perempuan itu juga mendesak, maka didengarkannyalah permintaan mereka, lalu bangkitlah ia dari tanah dan duduk di balai-balai."
  },
  {Bible:"1Samuel", Chapter:28, Verse:24, Page:1,
    Kor:"그 여인에게는 집에서 키운 살진 송아지가 한 마리 있었는데, 서둘러서 그것을 잡고, 밀가루를 가져다가 반죽하여 누룩을 넣지 않은 빵을 구워서,",
    Chn:"妇人急忙将家里的一只肥牛犊宰了，又拿面抟成无酵饼烤了，",
    Eng:"The woman had a fattened calf at the house, which she butchered at once. She took some flour, kneaded it and baked bread without yeast.",
    Ind:"Perempuan itu mempunyai seekor anak lembu tambun di rumahnya maka segeralah ia menyembelih itu. Ia mengambil tepung, diremasnya dan dibakarnya menjadi roti yang tidak beragi."
  },
  {Bible:"1Samuel", Chapter:28, Verse:25, Page:1,
    Kor:"사울과 그의 신하들 앞에 차려 놓으니, 그들은 그 음식을 먹고 일어나서, 그 밤에 떠났다.",
    Chn:"摆在扫罗和他仆人面前。他们吃完，当夜就起身走了。",
    Eng:"Then she set it before Saul and his men, and they ate. That same night they got up and left.",
    Ind:"Dihidangkannyalah semuanya itu ke depan Saul dan ke depan para pegawainya, lalu mereka makan. Kemudian bangkitlah mereka dan pergi pada malam itu juga."
  },
]);
