// 사무엘상 21장 · 1Samuel 21
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Samuel",21,15);
BibleDB.add([
  {Bible:"1Samuel", Chapter:21, Verse:1, Page:1, Kor:"<다윗이 사울을 피하여 도망가다> 다윗은 놉으로 가서 제사장 아히멜렉에게 이르렀다. 아히멜렉이 떨면서 나와서, 다윗을 맞으며 물었다. \"동행자도 없이 어떻게 혼자 오셨습니까?\"", Chn:"", Eng:"David went to Nob, to Ahimelech the priest. Ahimelech trembled when he met him, and asked, \"Why are you alone? Why is no one with you?\"", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:2, Page:1, Kor:"다윗이 제사장 아히멜렉에게 대답하였다. \"나는 임금님의 명령을 띠고 길을 떠났습니다. 임금님이 나에게 임무를 맡기면서 부탁하시기를, 나에게 맡기신 임무를 어느 누구에게도 알리지 말라고 하셨습니다. 그래서 부하들과는 약속된 곳에서 만나기로 하였습니다.", Chn:"", Eng:"David answered Ahimelech the priest, \"The king charged me with a certain matter and said to me, 'No one is to know anything about your mission and your instructions.' As for my men, I have told them to meet me at a certain place.", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:3, Page:1, Kor:"그런데 지금 제사장님이 혹시 무엇이든 가까이 가지신 것이 좀 없습니까? 빵 다섯 덩이가 있으면 저에게 주십시오. 그렇게 안 되면, 있는 대로라도 주십시오.\"", Chn:"", Eng:"Now then, what do you have on hand? Give me five loaves of bread, or whatever you can find.\"", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:4, Page:1, Kor:"그러자 제사장이 다윗에게 말하였다. \"지금 보통 빵은 내게 없고, 있는 것은 거룩한 빵뿐입니다. 그 젊은이들이 여자만 가까이하지 않았다면, 줄 수가 있습니다.\"", Chn:"", Eng:"But the priest answered David, \"I don't have any ordinary bread on hand; however, there is some consecrated bread here--provided the men have kept themselves from women.\"", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:5, Page:1, Kor:"다윗이 제사장에게 말하였다. \"원정 길에 오를 때에 늘 그렇게 하듯이, 이번에도 우리는 이삼일 전부터 여자와 가까이하지 않았습니다. 비록 이번 출정이 보통의 사명을 띤 길이기는 하지만, 제가 출정할 때에 이미 부하들의 몸은 정결했습니다. 그러니 오늘쯤은 그들의 몸이 얼마나 더 정결하겠습니까?\"", Chn:"", Eng:"David replied, \"Indeed women have been kept from us, as usual whenever I set out. The men's things are holy even on missions that are not holy. How much more so today!\"", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:6, Page:1, Kor:"제사장은 그에게 거룩한 빵을 주었다. 주님 앞에 차려 놓은 빵 말고는, 다른 빵이 달리 더 없었기 때문이다. 그 빵은 새로 만든 뜨거운 빵을 차려 놓으면서, 주님 앞에서 물려 낸 것이었다.", Chn:"", Eng:"So the priest gave him the consecrated bread, since there was no bread there except the bread of the Presence that had been removed from before the LORD and replaced by hot bread on the day it was taken away.", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:7, Page:1, Kor:"○(그런데 바로 그 날 사울의 신하 가운데 한 사람이 그 곳에 있었는데, 그는 주님 앞에서 하여야 할 일이 있어서 거기에 머물러 있었다. 그의 이름은 도엑인데, 에돔 사람으로서 사울의 목자 가운데서 우두머리였다.)", Chn:"", Eng:"Now one of Saul's servants was there that day, detained before the LORD; he was Doeg the Edomite, Saul's head shepherd.", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:8, Page:1, Kor:"○다윗이 아히멜렉에게 또 한 가지를 물었다. \"제사장님은 지금 혹시 창이나 칼을 가지고 계신 것이 없습니까? 저는 임금님의 명령이 너무도 급하여서, 나의 칼이나 무기를 가져오지 못했습니다.\"", Chn:"", Eng:"David asked Ahimelech, \"Don't you have a spear or a sword here? I haven't brought my sword or any other weapon, because the king's business was urgent.\"", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:9, Page:1, Kor:"제사장이 대답하였다. \"그대가 엘라 골짜기에서 쳐죽인 블레셋 사람 골리앗의 칼을, 보자기에 싸서 여기 에봇 뒤에 두었습니다. 여기에 이것 말고는 다른 칼이 없으니, 이 칼을 가지고 싶으면 가지십시오.\" 다윗이 말하였다. \"그만한 것이 어디에 또 있겠습니까? 그것을 나에게 주십시오.\"", Chn:"", Eng:"The priest replied, \"The sword of Goliath the Philistine, whom you killed in the Valley of Elah, is here; it is wrapped in a cloth behind the ephod. If you want it, take it; there is no sword here but that one.\" David said, \"There is none like it; give it to me.\"", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:10, Page:1, Kor:"<블레셋 족속에게 망명한 다윗> ○다윗이 거기를 떠나, 그 날로 사울에게서 도망하여, 가드 왕 아기스에게로 갔다.", Chn:"", Eng:"That day David fled from Saul and went to Achish king of Gath.", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:11, Page:1, Kor:"아기스의 신하들이 왕에게 보고하였다. \"이 사람은 분명히 저 나라의 왕 다윗입니다. 이 사람을 두고서, 저 나라의 백성이 춤을 추며, 이렇게 노래하였습니다.  '사울은 수천 명을 죽이고, 다윗은 수만 명을 죽였다.'\"", Chn:"", Eng:"But the servants of Achish said to him, \"Isn't this David, the king of the land? Isn't he the one they sing about in their dances: \"'Saul has slain his thousands, and David his tens of thousands'?\"", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:12, Page:1, Kor:"다윗은 이 말을 듣고 가슴이 뜨끔했다. 그는 가드 왕 아기스 옆에 있는 것도 안전하지 못하다는 생각이 들었다.", Chn:"", Eng:"David took these words to heart and was very much afraid of Achish king of Gath.", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:13, Page:1, Kor:"그래서 그는 그들이 보는 앞에서는 미친 척을 하였다. 그들에게 잡혀 있는 동안 그는 미친 사람처럼 행동하여 성문 문짝 위에 아무렇게나 글자를 긁적거리기도 하고, 수염에 침을 질질 흘리기도 하였다.", Chn:"", Eng:"So he pretended to be insane in their presence; and while he was in their hands he acted like a madman, making marks on the doors of the gate and letting saliva run down his beard.", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:14, Page:1, Kor:"그러자 아기스가 신하들에게 소리쳤다. \"아니, 미친 녀석이 아니냐? 왜 저런 자를 나에게 끌어 왔느냐?", Chn:"", Eng:"Achish said to his servants, \"Look at the man! He is insane! Why bring him to me?", Ind:""},
  {Bible:"1Samuel", Chapter:21, Verse:15, Page:1, Kor:"나에게 미치광이가 부족해서 저런 자까지 데려다가 내 앞에서 미친 짓을 하게 하느냐? 왕궁에 저런 자까지 들어와 있어야 하느냐?\"", Chn:"", Eng:"Am I so short of madmen that you have to bring this fellow here to carry on like this in front of me? Must this man come into my house?\"", Ind:""},
]);
