// 사무엘상 10장 · 1Samuel 10
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Samuel",10,27);
BibleDB.add([
  {Bible:"1Samuel", Chapter:10, Verse:1, Page:1,
    Kor:"사무엘이 기름병을 가져다가 사울의 머리에 붓고, 그에게 입을 맞춘 다음에, 이렇게 말하였다. \"주님께서 그대에게 기름을 부으시어, 주님의 소유이신 이 백성을 다스릴 영도자로 세우셨습니다.a(a 칠십인역과 불가타에는 1절 끝에 '이제 그대는 주님의 백성을 다스리고, 모든 적에게서 이 백성을 보호하십시오. 이제, 주님께서 그대를 택하셔서 당신의 백성을 다스릴 통치자로 09 10:삼으신 증거를 보여 드리겠습니다'의 내용이 더 있음)",
    Chn:"撒母耳拿瓶膏油倒在扫罗的头上，与他亲嘴，说：「这不是耶和华膏你作他产业的君吗？",
    Eng:"Then Samuel took a flask of oil and poured it on Saul's head and kissed him, saying, \"Has not the LORD anointed you leader over his inheritance?",
    Ind:"Lalu Samuel mengambil buli-buli berisi minyak, dituangnyalah ke atas kepala Saul, diciumnyalah dia sambil berkata: \"Bukankah TUHAN telah mengurapi engkau menjadi raja atas umat-Nya Israel? Engkau akan memegang tampuk pemerintahan atas umat TUHAN, dan engkau akan menyelamatkannya dari tangan musuh-musuh di sekitarnya. Inilah tandanya bagimu, bahwa TUHAN telah mengurapi engkau menjadi raja atas milik-Nya sendiri:"
  },
  {Bible:"1Samuel", Chapter:10, Verse:2, Page:1,
    Kor:"오늘 나를 떠나서 가시다가 베냐민 지역 셀사에 이르시면, 라헬의 무덤 근처에서 두 사람을 만나실 터인데, 그들은, 그대의 부친이 찾으러 다니던 암나귀들은 벌써 찾았고, 부친께서는 암나귀들 걱정은 놓으셨지만, 이제 오히려 아들과 종의 일이 걱정이 되어 찾고 계신다고 말할 것입니다.",
    Chn:"你今日与我离别之后，在便雅悯境内的泄撒，靠近拉结的坟墓，要遇见两个人。他们必对你说：『你去找的那几头驴已经找着了。现在你父亲不为驴挂心，反为你担忧，说：我为儿子怎么才好呢？』",
    Eng:"When you leave me today, you will meet two men near Rachel's tomb, at Zelzah on the border of Benjamin. They will say to you, 'The donkeys you set out to look for have been found. And now your father has stopped thinking about them and is worried about you. He is asking, \"What shall I do about my son?\"'",
    Ind:"Apabila engkau pada hari ini pergi meninggalkan aku, maka engkau akan bertemu dengan dua orang laki-laki di dekat kubur Rahel, di daerah Benyamin, di Zelzah. Mereka akan berkata kepadamu: Keledai-keledai yang engkau cari itu telah diketemukan; dan ayahmu tidak memikirkan keledai-keledai itu lagi, tetapi ia kuatir mengenai kamu, katanya: Apakah yang akan kuperbuat untuk anakku itu?"
  },
  {Bible:"1Samuel", Chapter:10, Verse:3, Page:1,
    Kor:"또 거기에서 더 가다가 다볼의 상수리나무에 이르면, 거기에서 하나님을 뵈려고 올라가는 세 사람을 만날 것입니다. 한 사람은 염소 새끼 세 마리를 데리고 가고, 한 사람은 빵 세 덩이를 가지고 가고, 또 한 사람은 포도주 가죽부대를 하나 메고 갈 것입니다.",
    Chn:"你从那里往前行，到了他泊的橡树那里，必遇见三个往伯特利去拜　神的人：一个带着三只山羊羔，一个带着三个饼，一个带着一皮袋酒。",
    Eng:"\"Then you will go on from there until you reach the great tree of Tabor. Three men going up to God at Bethel will meet you there. One will be carrying three young goats, another three loaves of bread, and another a skin of wine.",
    Ind:"Dari sana engkau akan berjalan terus lagi dan sampai ke pohon tarbantin Tabor, maka di sana engkau akan ditemui oleh tiga orang laki-laki yang naik menghadap Allah di Betel; seorang membawa tiga ekor anak kambing, seorang membawa tiga ketul roti dan yang lain lagi sebuyung anggur."
  },
  {Bible:"1Samuel", Chapter:10, Verse:4, Page:1,
    Kor:"그들이 그대에게 안부를 묻고, 빵 두 덩이를 줄 것이니, 그것을 받으십시오.",
    Chn:"他们必问你安，给你两个饼，你就从他们手中接过来。",
    Eng:"They will greet you and offer you two loaves of bread, which you will accept from them.",
    Ind:"Mereka akan memberi salam kepadamu dan memberikan kepadamu dua ketul roti yang akan kauterima dari mereka."
  },
  {Bible:"1Samuel", Chapter:10, Verse:5, Page:1,
    Kor:"그런 다음에 그대는 하나님의 산으로 가십시오. 그 곳에는 블레셋 수비대가 있습니다. 그 곳을 지나 성읍으로 들어갈 때에, 거문고를 뜯고 소구를 치고 피리를 불고 수금을 뜯으면서 예배 처소에서 내려오는 예언자의 무리를 만날 것입니다. 그들은 모두 춤을 추고 소리를 지르면서 예언을 하고 있을 것입니다.",
    Chn:"此后你到　神的山，在那里有非利士人的防兵。你到了城的时候，必遇见一班先知从邱坛下来，前面有鼓瑟的、击鼓的、吹笛的、弹琴的，他们都受感说话。",
    Eng:"\"After that you will go to Gibeah of God, where there is a Philistine outpost. As you approach the town, you will meet a procession of prophets coming down from the high place with lyres, tambourines, flutes and harps being played before them, and they will be prophesying.",
    Ind:"Sesudah itu engkau akan sampai ke Gibea Allah, tempat kedudukan pasukan orang Filistin. Dan apabila engkau masuk kota, engkau akan berjumpa di sana dengan serombongan nabi, yang turun dari bukit pengorbanan dengan gambus, rebana, suling dan kecapi di depan mereka; mereka sendiri akan kepenuhan seperti nabi."
  },
  {Bible:"1Samuel", Chapter:10, Verse:6, Page:1,
    Kor:"그러면 그대에게도 주님의 영이 강하게 내리어, 그들과 함께 춤을 추고 소리를 지르면서 예언을 할 것이며, 그대는 전혀 딴 사람으로 변할 것입니다.",
    Chn:"耶和华的灵必大大感动你，你就与他们一同受感说话；你要变为新人。",
    Eng:"The Spirit of the LORD will come upon you in power, and you will prophesy with them; and you will be changed into a different person.",
    Ind:"Maka Roh TUHAN akan berkuasa atasmu; engkau akan kepenuhan bersama-sama dengan mereka dan berubah menjadi manusia lain."
  },
  {Bible:"1Samuel", Chapter:10, Verse:7, Page:1,
    Kor:"이런 일들이 그대에게 나타나거든, 하나님이 함께 계시는 증거이니, 하나님이 인도하시는 대로 따라 하십시오.",
    Chn:"这兆头临到你，你就可以趁时而做，因为　神与你同在。",
    Eng:"Once these signs are fulfilled, do whatever your hand finds to do, for God is with you.",
    Ind:"Apabila tanda-tanda ini terjadi kepadamu, lakukanlah apa saja yang didapat oleh tanganmu, sebab Allah menyertai engkau."
  },
  {Bible:"1Samuel", Chapter:10, Verse:8, Page:1,
    Kor:"그대는 나보다 먼저 길갈로 내려가십시오. 그러면 나도 뒤따라 그대에게 내려가서 번제와 화목제물을 드릴 것이니, 내가 갈 때까지 이레 동안 기다려 주십시오. 그 때에 가서 하셔야 할 일을 알려 드리겠습니다.\"",
    Chn:"你当在我以先下到吉甲，我也必下到那里献燔祭和平安祭。你要等候七日，等我到了那里，指示你当行的事。」",
    Eng:"\"Go down ahead of me to Gilgal. I will surely come down to you to sacrifice burnt offerings and fellowship offerings, but you must wait seven days until I come to you and tell you what you are to do.\"",
    Ind:"Engkau harus pergi ke Gilgal mendahului aku, dan camkanlah, aku akan datang kepadamu untuk mempersembahkan korban bakaran dan korban keselamatan. Engkau harus menunggu tujuh hari lamanya, sampai aku datang kepadamu dan memberitahukan kepadamu apa yang harus kaulakukan.\""
  },
  {Bible:"1Samuel", Chapter:10, Verse:9, Page:1,
    Kor:"○사울이 사무엘에게서 떠나려고 몸을 돌이켰을 때에, 하나님이 사울에게 새 마음을 주셨다. 그리고 사무엘이 말한 그 모든 증거들이 그 날로 다 나타났다.",
    Chn:"扫罗转身离别撒母耳，　神就赐他一个新心。当日这一切兆头都应验了。",
    Eng:"As Saul turned to leave Samuel, God changed Saul's heart, and all these signs were fulfilled that day.",
    Ind:"Sedang ia berpaling untuk pergi meninggalkan Samuel, maka Allah mengubah hatinya menjadi lain. Dan segala tanda-tanda yang tersebut itu terjadi pada hari itu juga."
  },
  {Bible:"1Samuel", Chapter:10, Verse:10, Page:1,
    Kor:"사울이 종과 함께 산에 이르자, 예언자의 무리가 그를 맞아 주었다. 그 때에 하나님의 영이 그에게 세차게 내리니, 사울이 그들과 함께, 춤추며 소리를 지르면서 예언을 하였다.",
    Chn:"扫罗到了那山，有一班先知遇见他，　神的灵大大感动他，他就在先知中受感说话。",
    Eng:"When they arrived at Gibeah, a procession of prophets met him; the Spirit of God came upon him in power, and he joined in their prophesying.",
    Ind:"Ketika mereka sampai di Gibea dari sana, maka bertemulah ia dengan serombongan nabi; Roh Allah berkuasa atasnya dan Saul turut kepenuhan seperti nabi di tengah-tengah mereka."
  },
  {Bible:"1Samuel", Chapter:10, Verse:11, Page:1,
    Kor:"이전부터 그를 알던 모든 사람들이 보니, 사울이 과연 예언자들과 함께 그렇게 예언을 하는 것이 아닌가! 그래서 그들이 \"기스의 아들에게 무슨 일이 일어났는가? 사울이 예언자가 되었는가?\" 하고 서로 말하였다.",
    Chn:"素来认识扫罗的，看见他和先知一同受感说话，就彼此说：「基士的儿子遇见什么了？扫罗也列在先知中吗？」",
    Eng:"When all those who had formerly known him saw him prophesying with the prophets, they asked each other, \"What is this that has happened to the son of Kish? Is Saul also among the prophets?\"",
    Ind:"Dan semua orang yang mengenalnya dari dahulu melihat dengan heran, bahwa ia bernubuat bersama-sama dengan nabi-nabi itu; lalu berkatalah orang banyak yang satu kepada yang lain: \"Apakah gerangan yang terjadi dengan anak Kish itu? Apa Saul juga termasuk golongan nabi?\""
  },
  {Bible:"1Samuel", Chapter:10, Verse:12, Page:1,
    Kor:"거기에 사는 한 사람이 \"다른 예언자들은 어떻습니까? 그들의 아버지가 누구라고 생각하십니까?\" 하고 물었으므로, \"사울마저도 예언자가 되었는가?\" 하는 속담이 생겼다.",
    Chn:"那地方有一个人说：「这些人的父亲是谁呢？」此后有句俗语说：「扫罗也列在先知中吗？」",
    Eng:"A man who lived there answered, \"And who is their father?\" So it became a saying: \"Is Saul also among the prophets?\"",
    Ind:"Lalu seorang dari tempat itu menjawab: \"Siapakah bapa mereka?\" --Itulah sebabnya menjadi peribahasa: Apa Saul juga termasuk golongan nabi?"
  },
  {Bible:"1Samuel", Chapter:10, Verse:13, Page:1,
    Kor:"사울은 예언을 마치고 나서, 산당으로 갔다.",
    Chn:"扫罗受感说话已毕，就上邱坛去了。",
    Eng:"After Saul stopped prophesying, he went to the high place.",
    Ind:"Setelah habis ia kepenuhan seperti nabi, pulanglah ia."
  },
  {Bible:"1Samuel", Chapter:10, Verse:14, Page:1,
    Kor:"○사울의 삼촌이 사울과 그 종에게 \"어디를 갔었느냐?\" 하고 물었다. 사울이 대답하였다. \"암나귀들을 찾으러 갔지만, 찾을 수가 없어서 사무엘에게 갔었습니다.\"",
    Chn:"扫罗的叔叔问扫罗和他仆人说：「你们往哪里去了？」回答说：「找驴去了。我们见没有驴，就到了撒母耳那里。」",
    Eng:"Now Saul's uncle asked him and his servant, \"Where have you been?\" \"Looking for the donkeys,\" he said. \"But when we saw they were not to be found, we went to Samuel.\"",
    Ind:"Dan paman Saul berkata kepadanya dan bujangnya: \"Dari mana kamu?\" Jawabnya: \"Mencari keledai-keledai itu, tetapi ketika tidak terlihat, maka kami pergi kepada Samuel.\""
  },
  {Bible:"1Samuel", Chapter:10, Verse:15, Page:1,
    Kor:"사울의 삼촌이 또 말하였다. \"사무엘이 너희에게 무슨 말씀을 하시더냐? 나에게 말하여라.\"",
    Chn:"扫罗的叔叔说：「请将撒母耳向你们所说的话告诉我。」",
    Eng:"Saul's uncle said, \"Tell me what Samuel said to you.\"",
    Ind:"Kemudian paman Saul itu berkata: \"Coba ceritakan kepadaku apa yang dikatakan Samuel kepada kamu.\""
  },
  {Bible:"1Samuel", Chapter:10, Verse:16, Page:1,
    Kor:"사울이 삼촌에게 말하였다. \"암나귀들은 이미 찾았다고 우리에게 일러주셨습니다.\" 그러나 사무엘이 사울 자신에게 왕이 될 것이라고 말한 것은, 그에게 알려 주지 않았다.",
    Chn:"扫罗对他叔叔说：「他明明地告诉我们驴已经找着了。」至于撒母耳所说的国事，扫罗却没有告诉叔叔。",
    Eng:"Saul replied, \"He assured us that the donkeys had been found.\" But he did not tell his uncle what Samuel had said about the kingship.",
    Ind:"Kata Saul kepada pamannya itu: \"Terus saja diberitahukannya kepada kami, bahwa keledai-keledai itu telah diketemukan.\" Tetapi perihal menjadi raja yang telah dikatakan Samuel kepadanya, tidak diceritakan kepadanya."
  },
  {Bible:"1Samuel", Chapter:10, Verse:17, Page:1,
    Kor:"<사울이 왕으로 뽑히다> ○사무엘이 백성을 미스바로 불러 주님 앞에 모아 놓고,",
    Chn:"撒母耳将百姓招聚到米斯巴耶和华那里，",
    Eng:"Samuel summoned the people of Israel to the LORD at Mizpah",
    Ind:"Kemudian Samuel mengerahkan bangsa itu ke hadapan TUHAN di Mizpa"
  },
  {Bible:"1Samuel", Chapter:10, Verse:18, Page:1,
    Kor:"이스라엘 자손에게 하나님이 하신 말씀을 전하였다. \"나 주 이스라엘의 하나님이 말한다. 내가 이스라엘을 이집트에서 데리고 올라왔고, 내가 너희를 이집트 사람의 손과, 너희를 학대하던 모든 나라의 손에서 건져 내었다.",
    Chn:"对他们说：「耶和华—以色列的　神如此说：『我领你们以色列人出埃及，救你们脱离埃及人的手，又救你们脱离欺压你们各国之人的手。』",
    Eng:"and said to them, \"This is what the LORD, the God of Israel, says: 'I brought Israel up out of Egypt, and I delivered you from the power of Egypt and all the kingdoms that oppressed you.'",
    Ind:"dan ia berkata kepada orang Israel itu: \"Beginilah firman TUHAN, Allah Israel: Aku telah menuntun orang Israel keluar dari Mesir dan telah melepaskan kamu dari tangan orang Mesir dan dari tangan segala kerajaan yang menindas kamu."
  },
  {Bible:"1Samuel", Chapter:10, Verse:19, Page:1,
    Kor:"그러나 오늘날 너희는, 너희를 모든 환난과 고난 속에서 건져 낸 너희 하나님을 버리고, 너희에게 왕을 세워 달라고 나에게 요구하였다. 좋다, 이제 너희는 지파와 집안별로, 나 주 앞에 나와 서거라!\"",
    Chn:"你们今日却厌弃了救你们脱离一切灾难的　神，说：『求你立一个王治理我们。』现在你们应当按着支派、宗族都站在耶和华面前。」",
    Eng:"But you have now rejected your God, who saves you out of all your calamities and distresses. And you have said, 'No, set a king over us.' So now present yourselves before the LORD by your tribes and clans.\"",
    Ind:"Tetapi sekarang kamu menolak Allahmu yang menyelamatkan kamu dari segala malapetaka dan kesusahanmu, dengan berkata: Tidak, angkatlah seorang raja atas kami. Maka sebab itu, berdirilah kamu di hadapan TUHAN, menurut sukumu dan menurut kaummu.\""
  },
  {Bible:"1Samuel", Chapter:10, Verse:20, Page:1,
    Kor:"○사무엘이 이스라엘의 모든 지파를 앞으로 나오게 하니, 주님께서 베냐민 지파를 뽑으셨다.",
    Chn:"于是，撒母耳使以色列众支派近前来掣签，就掣出便雅悯支派来；",
    Eng:"When Samuel brought all the tribes of Israel near, the tribe of Benjamin was chosen.",
    Ind:"Lalu Samuel menyuruh segala suku Israel tampil ke muka, maka didapati suku Benyamin."
  },
  {Bible:"1Samuel", Chapter:10, Verse:21, Page:1,
    Kor:"사무엘이 베냐민 지파를 각 집안별로 앞으로 나오게 하니, 마드리의 집안이 뽑혔고, 마드리의 집안 남자들을 앞으로 나오게 하니, 기스의 아들 사울이 뽑혔다. 사람들이 그를 찾았지만, 보이지 않았다.",
    Chn:"又使便雅悯支派按着宗族近前来，就掣出玛特利族，从其中又掣出基士的儿子扫罗。众人寻找他却寻不着，",
    Eng:"Then he brought forward the tribe of Benjamin, clan by clan, and Matri's clan was chosen. Finally Saul son of Kish was chosen. But when they looked for him, he was not to be found.",
    Ind:"Sesudah itu disuruhnyalah suku Benyamin tampil ke muka menurut kaum keluarganya, maka didapati kaum keluarga Matri. Akhirnya disuruhnyalah kaum keluarga Matri tampil ke muka seorang demi seorang, maka didapati Saul bin Kish. Tetapi ketika ia dicari, ia tidak diketemukan."
  },
  {Bible:"1Samuel", Chapter:10, Verse:22, Page:1,
    Kor:"그래서 사람들이 다시 주님께 여쭈어 보았다. \"그 사람이 여기에 와 있습니까?\" 주님께서 말씀하셨다. \"그는 짐짝 사이에 숨어 있다.\"",
    Chn:"就问耶和华说：「那人到这里来了没有？」耶和华说：「他藏在器具中了。」",
    Eng:"So they inquired further of the LORD, \"Has the man come here yet?\" And the LORD said, \"Yes, he has hidden himself among the baggage.\"",
    Ind:"Sebab itu ditanyakan pulalah kepada TUHAN: \"Apa orang itu juga datang ke mari?\" TUHAN menjawab: \"Sesungguhnya ia bersembunyi di antara barang-barang.\""
  },
  {Bible:"1Samuel", Chapter:10, Verse:23, Page:1,
    Kor:"사람들이 달려가 거기에서 그를 데리고 나왔다. 그가 사람들 가운데 섰는데, 다른 사람들보다 어깨 위만큼은 더 커 보였다.",
    Chn:"众人就跑去从那里领出他来。他站在百姓中间，身体比众民高过一头。",
    Eng:"They ran and brought him out, and as he stood among the people he was a head taller than any of the others.",
    Ind:"Berlarilah orang ke sana dan mengambilnya dari sana, dan ketika ia berdiri di tengah-tengah orang-orang sebangsanya, ternyata ia dari bahu ke atas lebih tinggi dari pada setiap orang sebangsanya."
  },
  {Bible:"1Samuel", Chapter:10, Verse:24, Page:1,
    Kor:"사무엘이 온 백성에게 말하였다. \"주님께서 뽑으신 이 사람을 보아라. 온 백성 가운데 이만한 인물이 없다.\" 그러자 온 백성이 환호성을 지르며 \"임금님 만세!\" 하고 외쳤다.",
    Chn:"撒母耳对众民说：「你们看耶和华所拣选的人，众民中有可比他的吗？」众民就大声欢呼说：「愿王万岁！」",
    Eng:"Samuel said to all the people, \"Do you see the man the LORD has chosen? There is no one like him among all the people.\" Then the people shouted, \"Long live the king!\"",
    Ind:"Dan Samuel berkata kepada seluruh bangsa itu: \"Kamu lihatkah orang yang dipilih TUHAN itu? Sebab tidak ada seorangpun yang sama seperti dia di antara seluruh bangsa itu.\" Lalu bersoraklah seluruh bangsa itu, demikian: \"Hidup raja!\""
  },
  {Bible:"1Samuel", Chapter:10, Verse:25, Page:1,
    Kor:"○사무엘이 왕의 제도를 백성에게 알려 준 다음, 그것을 책에 써서 주님 앞에 보관하여 두고, 온 백성을 각자의 집으로 돌아가게 하였다.",
    Chn:"撒母耳将国法对百姓说明，又记在书上，放在耶和华面前，然后遣散众民，各回各家去了。",
    Eng:"Samuel explained to the people the regulations of the kingship. He wrote them down on a scroll and deposited it before the LORD. Then Samuel dismissed the people, each to his own home.",
    Ind:"Kemudian Samuel menguraikan kepada bangsa itu tentang hak-hak kerajaan, menuliskannya pada suatu piagam dan meletakkannya di hadapan TUHAN; sesudah itu Samuel menyuruh seluruh bangsa itu pulang, masing-masing ke rumahnya."
  },
  {Bible:"1Samuel", Chapter:10, Verse:26, Page:1,
    Kor:"사울이 기브아에 있는 자기의 집으로 돌아갈 때에, 하나님께 감동을 받은 용감한 사람들이 사울을 따라갔다.",
    Chn:"扫罗往基比亚回家去，有　神感动的一群人跟随他。",
    Eng:"Saul also went to his home in Gibeah, accompanied by valiant men whose hearts God had touched.",
    Ind:"Saulpun pulang ke rumahnya, ke Gibea, dan bersama-sama dengan dia ikut pergi orang-orang gagah perkasa yang hatinya telah digerakkan Allah."
  },
  {Bible:"1Samuel", Chapter:10, Verse:27, Page:1,
    Kor:"그러나 몇몇 불량배들은 \"이런 사람이 어떻게 우리를 구할 수 있겠느냐?\" 하고 떠들면서 그를 업신여기고, 그에게 예물도 바치지 않았다. 그러나 사울은 못 들은 척하였다.",
    Chn:"但有些匪徒说：「这人怎能救我们呢？」就藐视他，没有送他礼物；扫罗却不理会。",
    Eng:"But some troublemakers said, \"How can this fellow save us?\" They despised him and brought him no gifts. But Saul kept silent. 1SA",
    Ind:"Tetapi orang-orang dursila berkata: \"Masakan orang ini dapat menyelamatkan kita!\" Mereka menghina dia dan tidak membawa persembahan kepadanya. Tetapi ia pura-pura tuli."
  },
]);
