// 사무엘상 1장 · 1Samuel 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Samuel",1,28);
BibleDB.add([
  {Bible:"1Samuel", Chapter:1, Verse:1, Page:1,
    Kor:"<엘가나의 실로 순례> 에브라임 지파에 속한 숩의 자손 엘가나라는 사람이, 에브라임의 산간지방에 있는 라마다임에 살고 있었다. 그의 아버지는 여로함이고, 할아버지는 엘리후이고, 그 윗대는 도후이고, 그 윗대는 숩이다.",
    Chn:"以法莲山地的拉玛·琐非有一个以法莲人，名叫以利加拿，是苏弗的玄孙，托户的曾孙，以利户的孙子，耶罗罕的儿子。",
    Eng:"There was a certain man from Ramathaim, a Zuphite from the hill country of Ephraim, whose name was Elkanah son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an Ephraimite.",
    Ind:"Ada seorang laki-laki dari Ramataim-Zofim, dari pegunungan Efraim, namanya Elkana bin Yeroham bin Elihu bin Tohu bin Zuf, seorang Efraim."
  },
  {Bible:"1Samuel", Chapter:1, Verse:2, Page:1,
    Kor:"엘가나에게는 두 아내가 있었는데, 한 아내의 이름은 a한나요, 또 한 아내의 이름은 b브닌나였다. 브닌나에게는 자녀들이 있었지만, 한나에게는 자녀가 하나도 없었다.(a '풍성한 은혜' b '홍보석')",
    Chn:"他有两个妻：一名哈拿，一名毗尼拿。毗尼拿有儿女，哈拿没有儿女。",
    Eng:"He had two wives; one was called Hannah and the other Peninnah. Peninnah had children, but Hannah had none.",
    Ind:"Orang ini mempunyai dua isteri: yang seorang bernama Hana dan yang lain bernama Penina; Penina mempunyai anak, tetapi Hana tidak."
  },
  {Bible:"1Samuel", Chapter:1, Verse:3, Page:1,
    Kor:"엘가나는 매년 한 번씩 자기가 사는 성읍에서 실로로 올라가서, 만군의 주님께 경배하며 제사를 드렸다. 그 곳에는 엘리의 두 아들인 홉니와 비느하스가 주님의 제사장으로 있었다.",
    Chn:"这人每年从本城上到示罗，敬拜祭祀万军之耶和华；在那里有以利的两个儿子何弗尼、非尼哈当耶和华的祭司。",
    Eng:"Year after year this man went up from his town to worship and sacrifice to the LORD Almighty at Shiloh, where Hophni and Phinehas, the two sons of Eli, were priests of the LORD.",
    Ind:"Orang itu dari tahun ke tahun pergi meninggalkan kotanya untuk sujud menyembah dan mempersembahkan korban kepada TUHAN semesta alam di Silo. Di sana yang menjadi imam TUHAN ialah kedua anak Eli, Hofni dan Pinehas."
  },
  {Bible:"1Samuel", Chapter:1, Verse:4, Page:1,
    Kor:"○엘가나는 제사를 드리고 나서는, 늘 아내 브닌나와 그가 낳은 모든 아들딸에게 제물을 각각 한 몫씩 나누어 주곤 하였다.",
    Chn:"以利加拿每逢献祭的日子，将祭肉分给他的妻毗尼拿和毗尼拿所生的儿女；",
    Eng:"Whenever the day came for Elkanah to sacrifice, he would give portions of the meat to his wife Peninnah and to all her sons and daughters.",
    Ind:"Pada hari Elkana mempersembahkan korban, diberikannyalah kepada Penina, isterinya, dan kepada semua anaknya yang laki-laki dan perempuan masing-masing sebagian."
  },
  {Bible:"1Samuel", Chapter:1, Verse:5, Page:1,
    Kor:"그러나 한나에게는 두 몫을 주었다. 비록 주님께서 한나의 태를 닫아 놓으셨지만, 엘가나는 한나를 사랑하였다.",
    Chn:"给哈拿的却是双分，因为他爱哈拿。无奈耶和华不使哈拿生育。",
    Eng:"But to Hannah he gave a double portion because he loved her, and the LORD had closed her womb.",
    Ind:"Meskipun ia mengasihi Hana, ia memberikan kepada Hana hanya satu bagian, sebab TUHAN telah menutup kandungannya."
  },
  {Bible:"1Samuel", Chapter:1, Verse:6, Page:1,
    Kor:"주님께서 한나의 태를 닫아 놓으셨으므로, 그의 적수인 브닌나는 한나를 괴롭히고 업신여겼다.",
    Chn:"毗尼拿见耶和华不使哈拿生育，就作她的对头，大大激动她，要使她生气。",
    Eng:"And because the LORD had closed her womb, her rival kept provoking her in order to irritate her.",
    Ind:"Tetapi madunya selalu menyakiti hatinya supaya ia gusar, karena TUHAN telah menutup kandungannya."
  },
  {Bible:"1Samuel", Chapter:1, Verse:7, Page:1,
    Kor:"이런 일이 매년 거듭되었다. 한나가 주님의 집으로 올라갈 때마다, 브닌나가 한나의 마음을 늘 그렇게 괴롭혔으므로, 한나는 울기만 하고, 아무것도 먹지 않았다.",
    Chn:"每年上到耶和华殿的时候，以利加拿都以双分给哈拿；毗尼拿仍是激动她，以致她哭泣不吃饭。",
    Eng:"This went on year after year. Whenever Hannah went up to the house of the LORD, her rival provoked her till she wept and would not eat.",
    Ind:"Demikianlah terjadi dari tahun ke tahun; setiap kali Hana pergi ke rumah TUHAN, Penina menyakiti hati Hana, sehingga ia menangis dan tidak mau makan."
  },
  {Bible:"1Samuel", Chapter:1, Verse:8, Page:1,
    Kor:"그럴 때마다 남편 엘가나가 한나를 위로하였다. \"여보, 왜 울기만 하오? 왜 먹지 않으려 하오? 왜 늘 그렇게 슬퍼만 하는 거요? 당신이 열 아들을 두었다고 해도, 내가 당신에게 하는 만큼 하겠소?\"",
    Chn:"她丈夫以利加拿对她说：「哈拿啊，你为何哭泣，不吃饭，心里愁闷呢？有我不比十个儿子还好吗？」",
    Eng:"Elkanah her husband would say to her, \"Hannah, why are you weeping? Why don't you eat? Why are you downhearted? Don't I mean more to you than ten sons?\"",
    Ind:"Lalu Elkana, suaminya, berkata kepadanya: \"Hana, mengapa engkau menangis dan mengapa engkau tidak mau makan? Mengapa hatimu sedih? Bukankah aku lebih berharga bagimu dari pada sepuluh anak laki-laki?\""
  },
  {Bible:"1Samuel", Chapter:1, Verse:9, Page:1,
    Kor:"<한나와 엘리> ○한번은 엘가나 일행이 실로에 있는 주님의 집에서 음식을 먹고 마신 뒤에, 한나가 일어나서 자리를 떴다. 그 때에 제사장 엘리는 c주님의 성전 문설주 곁에 있는 의자에 앉아 있었다.(c 히, '헤칼 아도나이'. 솔로몬의 성전이 건축되기 이전이므로, '성막'을 가리킴)",
    Chn:"他们在示罗吃喝完了，哈拿就站起来。祭司以利在耶和华殿的门框旁边，坐在自己的位上。",
    Eng:"Once when they had finished eating and drinking in Shiloh, Hannah stood up. Now Eli the priest was sitting on a chair by the doorpost of the LORD'S temple.",
    Ind:"Pada suatu kali, setelah mereka habis makan dan minum di Silo, berdirilah Hana, sedang imam Eli duduk di kursi dekat tiang pintu bait suci TUHAN,"
  },
  {Bible:"1Samuel", Chapter:1, Verse:10, Page:1,
    Kor:"한나는 괴로운 마음으로 주님께 나아가, 흐느껴 울면서 기도하였다.",
    Chn:"哈拿心里愁苦，就痛痛哭泣，祈祷耶和华，",
    Eng:"In bitterness of soul Hannah wept much and prayed to the LORD.",
    Ind:"dan dengan hati pedih ia berdoa kepada TUHAN sambil menangis tersedu-sedu."
  },
  {Bible:"1Samuel", Chapter:1, Verse:11, Page:1,
    Kor:"한나는 서원하며 아뢰었다. \"만군의 주님, 주님께서 주님의 종의 이 비천한 모습을 참으로 불쌍히 보시고, 저를 기억하셔서, 주님의 종을 잊지 않으시고, 이 종에게 아들을 하나 허락하여 주시면, 저는 그 아이의 한평생을 주님께 바치고, 삭도를 그의 머리에 대지 않도록 하겠습니다.\"",
    Chn:"许愿说：「万军之耶和华啊，你若垂顾婢女的苦情，眷念不忘婢女，赐我一个儿子，我必使他终身归与耶和华，不用剃头刀剃他的头。」",
    Eng:"And she made a vow, saying, \"O LORD Almighty, if you will only look upon your servant's misery and remember me, and not forget your servant but give her a son, then I will give him to the LORD for all the days of his life, and no razor will ever be used on his head.\"",
    Ind:"Kemudian bernazarlah ia, katanya: \"TUHAN semesta alam, jika sungguh-sungguh Engkau memperhatikan sengsara hamba-Mu ini dan mengingat kepadaku dan tidak melupakan hamba-Mu ini, tetapi memberikan kepada hamba-Mu ini seorang anak laki-laki, maka aku akan memberikan dia kepada TUHAN untuk seumur hidupnya dan pisau cukur tidak akan menyentuh kepalanya.\""
  },
  {Bible:"1Samuel", Chapter:1, Verse:12, Page:1,
    Kor:"○한나가 주님 앞에서 계속 기도를 드리고 있는 동안에, 엘리는 한나의 입술을 지켜보고 있었다.",
    Chn:"哈拿在耶和华面前不住地祈祷，以利定睛看她的嘴。（",
    Eng:"As she kept on praying to the LORD, Eli observed her mouth.",
    Ind:"Ketika perempuan itu terus-menerus berdoa di hadapan TUHAN, maka Eli mengamat-amati mulut perempuan itu;"
  },
  {Bible:"1Samuel", Chapter:1, Verse:13, Page:1,
    Kor:"한나가 마음 속으로만 기도를 드리고 있었으므로, 입술만 움직이고 소리는 내지 않았다. 그러므로 엘리는, 한나가 술에 취한 줄로 생각하고,",
    Chn:"原来哈拿心中默祷，只动嘴唇，不出声音，因此以利以为她喝醉了。）",
    Eng:"Hannah was praying in her heart, and her lips were moving but her voice was not heard. Eli thought she was drunk",
    Ind:"dan karena Hana berkata-kata dalam hatinya dan hanya bibirnya saja bergerak-gerak, tetapi suaranya tidak kedengaran, maka Eli menyangka perempuan itu mabuk."
  },
  {Bible:"1Samuel", Chapter:1, Verse:14, Page:1,
    Kor:"그를 꾸짖었다. \"언제까지 술에 취해 있을 것이오? 포도주를 끊으시오.\"",
    Chn:"以利对她说：「你要醉到几时呢？你不应该喝酒。」",
    Eng:"and said to her, \"How long will you keep on getting drunk? Get rid of your wine.\"",
    Ind:"Lalu kata Eli kepadanya: \"Berapa lama lagi engkau berlaku sebagai orang mabuk? Lepaskanlah dirimu dari pada mabukmu.\""
  },
  {Bible:"1Samuel", Chapter:1, Verse:15, Page:1,
    Kor:"한나가 대답하였다. \"제사장님, 저는 술에 취한 것이 아닙니다. 포도주나 d독한 술을 마신 것이 아닙니다. 다만 슬픈 마음을 가눌 길이 없어서, 저의 마음을 주님 앞에 쏟아 놓았을 뿐입니다.(d 곡식이나 과일로 만든 도수가 높은 술(히, 셰카르))",
    Chn:"哈拿回答说：「主啊，不是这样。我是心里愁苦的妇人，清酒浓酒都没有喝，但在耶和华面前倾心吐意。",
    Eng:"\"Not so, my lord,\" Hannah replied, \"I am a woman who is deeply troubled. I have not been drinking wine or beer; I was pouring out my soul to the LORD.",
    Ind:"Tetapi Hana menjawab: \"Bukan, tuanku, aku seorang perempuan yang sangat bersusah hati; anggur ataupun minuman yang memabukkan tidak kuminum, melainkan aku mencurahkan isi hatiku di hadapan TUHAN."
  },
  {Bible:"1Samuel", Chapter:1, Verse:16, Page:1,
    Kor:"이 종을 e나쁜 여자로 여기지 마시기 바랍니다. 너무나도 원통하고 괴로워서, 이처럼 기도를 드리고 있습니다.\"(e 히, '밧 블리야알(블리야알의 딸)', '악한 여자')",
    Chn:"不要将婢女看作不正经的女子。我因被人激动，愁苦太多，所以祈求到如今。」",
    Eng:"Do not take your servant for a wicked woman; I have been praying here out of my great anguish and grief.\"",
    Ind:"Janganlah anggap hambamu ini seorang perempuan dursila; sebab karena besarnya cemas dan sakit hati aku berbicara demikian lama.\""
  },
  {Bible:"1Samuel", Chapter:1, Verse:17, Page:1,
    Kor:"그러자 엘리가 말하였다. \"그렇다면 평안한 마음으로 돌아가시오. 이스라엘의 하나님이, 그대가 간구한 것을 이루어 주실 것이오.\"",
    Chn:"以利说：「你可以平平安安地回去。愿以色列的　神允准你向他所求的！」",
    Eng:"Eli answered, \"Go in peace, and may the God of Israel grant you what you have asked of him.\"",
    Ind:"Jawab Eli: \"Pergilah dengan selamat, dan Allah Israel akan memberikan kepadamu apa yang engkau minta dari pada-Nya.\""
  },
  {Bible:"1Samuel", Chapter:1, Verse:18, Page:1,
    Kor:"한나가 대답하였다. \"제사장님, 이 종을 좋게 보아 주시기 바랍니다.\" 한나는 그 길로 가서 음식을 먹었다. 그리고 다시는 얼굴에 슬픈 기색을 띠지 않았다.",
    Chn:"哈拿说：「愿婢女在你眼前蒙恩。」于是妇人走去吃饭，面上再不带愁容了。",
    Eng:"She said, \"May your servant find favor in your eyes.\" Then she went her way and ate something, and her face was no longer downcast.",
    Ind:"Sesudah itu berkatalah perempuan itu: \"Biarlah hambamu ini mendapat belas kasihan dari padamu.\" Lalu keluarlah perempuan itu, ia mau makan dan mukanya tidak muram lagi."
  },
  {Bible:"1Samuel", Chapter:1, Verse:19, Page:1,
    Kor:"다음날 아침, 그들은 일찍 일어나 주님께 경배를 드리고 나서, 라마에 있는 집으로 돌아왔다. ○엘가<사무엘의 출생과 봉헌> 나가 아내 한나와 동침하니, 주님께서 한나를 기억하여 주셨다.",
    Chn:"次日清早，他们起来，在耶和华面前敬拜，就回拉玛。到了家里，以利加拿和妻哈拿同房，耶和华顾念哈拿，",
    Eng:"Early the next morning they arose and worshiped before the LORD and then went back to their home at Ramah. Elkanah lay with Hannah his wife, and the LORD remembered her.",
    Ind:"Keesokan harinya bangunlah mereka itu pagi-pagi, lalu sujud menyembah di hadapan TUHAN; kemudian pulanglah mereka ke rumahnya di Rama. Ketika Elkana bersetubuh dengan Hana, isterinya, TUHAN ingat kepadanya."
  },
  {Bible:"1Samuel", Chapter:1, Verse:20, Page:1,
    Kor:"한나가 임신을 하고, 달이 차서 아들을 낳았다. 한나는, 주님께 구하여 얻은 아들이라고 하여, 그 아이의 이름을 f사무엘이라고 지었다.(f '하나님이 들으셨다', '그의 이름은 하나님이시다', '그의 이름에 권능이 있다' 또는 '하나님에게 간구하였다')",
    Chn:"哈拿就怀孕。日期满足，生了一个儿子，给他起名叫撒母耳，说：「这是我从耶和华那里求来的。」",
    Eng:"So in the course of time Hannah conceived and gave birth to a son. She named him Samuel, saying, \"Because I asked the LORD for him.\"",
    Ind:"Maka setahun kemudian mengandunglah Hana dan melahirkan seorang anak laki-laki. Ia menamai anak itu Samuel, sebab katanya: \"Aku telah memintanya dari pada TUHAN.\""
  },
  {Bible:"1Samuel", Chapter:1, Verse:21, Page:1,
    Kor:"○남편 엘가나가 자기의 온 가족을 데리고 주님께 매년제사와 서원제사를 드리러 올라갈 때가 되었을 때에,",
    Chn:"以利加拿和他全家都上示罗去，要向耶和华献年祭，并还所许的愿。",
    Eng:"When the man Elkanah went up with all his family to offer the annual sacrifice to the LORD and to fulfill his vow,",
    Ind:"Elkana, laki-laki itu, pergi dengan seisi rumahnya mempersembahkan korban sembelihan tahunan dan korban nazarnya kepada TUHAN."
  },
  {Bible:"1Samuel", Chapter:1, Verse:22, Page:1,
    Kor:"한나는 함께 올라가지 않고, 자기 남편에게 이렇게 말하였다. \"나는 아이가 젖을 뗄 때까지 기다렸다가, 젖을 뗀 다음에, 아이를 주님의 집으로 데리고 올라가서, 주님을 뵙게 하고, 아이가 평생 그 곳에 머물러 있게 하려고 합니다. g나는 그 아이를 평생 나실 사람으로 바치겠습니다.\"(g 사해 사본에는 이 말이 더 있음. 나실 사람은 '구별된 사람', '거룩하게 바쳐진 사람')",
    Chn:"哈拿却没有上去，对丈夫说：「等孩子断了奶，我便带他上去朝见耶和华，使他永远住在那里。」",
    Eng:"Hannah did not go. She said to her husband, \"After the boy is weaned, I will take him and present him before the LORD, and he will live there always.\"",
    Ind:"Tetapi Hana tidak ikut pergi, sebab katanya kepada suaminya: \"Nanti apabila anak itu cerai susu, aku akan mengantarkan dia, maka ia akan menghadap ke hadirat TUHAN dan tinggal di sana seumur hidupnya.\""
  },
  {Bible:"1Samuel", Chapter:1, Verse:23, Page:1,
    Kor:"남편 엘가나가 그에게 대답하였다. \"당신 생각에 그것이 좋으면, 그렇게 하시오. 그 아이가 젖을 뗄 때까지 집에 있으시오. 주님께서 h당신의 말대로 이루어 주시기를 바라오.\" 그래서 그의 아내는 아들이 젖을 뗄 때까지 집에 머무르면서 아이를 길렀다.(h 사해 사본과 칠십인역과 시리아어역을 따름. 마소라 본문에는 '주님의 말씀대로')",
    Chn:"她丈夫以利加拿说：「就随你的意行吧！可以等儿子断了奶。但愿耶和华应验他的话。」于是妇人在家里乳养儿子，直到断了奶；",
    Eng:"\"Do what seems best to you,\" Elkanah her husband told her. \"Stay here until you have weaned him; only may the LORD make good his word.\" So the woman stayed at home and nursed her son until she had weaned him.",
    Ind:"Kemudian Elkana, suaminya itu, berkata kepadanya: \"Perbuatlah apa yang kaupandang baik; tinggallah sampai engkau menyapih dia; hanya, TUHAN kiranya menepati janji-Nya.\" Jadi tinggallah perempuan itu dan menyusui anaknya sampai disapihnya."
  },
  {Bible:"1Samuel", Chapter:1, Verse:24, Page:1,
    Kor:"○마침내 아이가 젖을 떼니, 한나는 아이를 데리고, i삼 년 된 수소 한 마리를 끌고, 밀가루 한 에바와 포도주가 든 가죽부대 하나를 가지고, 실로로 올라갔다. 한나는 어린 사무엘을 데리고 실로에 있는 주님의 집으로 갔다.(i 사해 사본과 칠십인역과 시리아어역을 따름. 마소라 본문에는 '수소 세 마리')",
    Chn:"既断了奶，就把孩子带上示罗，到了耶和华的殿；又带了三只公牛，一伊法细面，一皮袋酒。（那时，孩子还小。）",
    Eng:"After he was weaned, she took the boy with her, young as he was, along with a three-year-old bull, an ephah of flour and a skin of wine, and brought him to the house of the LORD at Shiloh.",
    Ind:"Setelah perempuan itu menyapih anaknya, dibawanyalah dia, dengan seekor lembu jantan yang berumur tiga tahun, satu efa tepung dan sebuyung anggur, lalu diantarkannya ke dalam rumah TUHAN di Silo. Waktu itu masih kecil betul kanak-kanak itu."
  },
  {Bible:"1Samuel", Chapter:1, Verse:25, Page:1,
    Kor:"그들이 수소를 잡고 나서, 그 아이를 엘리에게 데리고 갔다.",
    Chn:"宰了一只公牛，就领孩子到以利面前。",
    Eng:"When they had slaughtered the bull, they brought the boy to Eli,",
    Ind:"Setelah mereka menyembelih lembu, mereka mengantarkan kanak-kanak itu kepada Eli;"
  },
  {Bible:"1Samuel", Chapter:1, Verse:26, Page:1,
    Kor:"한나가 엘리에게 말하였다. \"제사장님, 나를 기억하시겠습니까? 내가, 주님께 기도를 드리려고 이 곳에 와서, 제사장님과 함께 서 있던 바로 그 여자입니다.",
    Chn:"妇人说：「主啊，我敢在你面前起誓，从前在你这里站着祈求耶和华的那妇人，就是我。",
    Eng:"and she said to him, \"As surely as you live, my lord, I am the woman who stood here beside you praying to the LORD.",
    Ind:"lalu kata perempuan itu: \"Mohon bicara tuanku, demi tuanku hidup, akulah perempuan yang dahulu berdiri di sini dekat tuanku untuk berdoa kepada TUHAN."
  },
  {Bible:"1Samuel", Chapter:1, Verse:27, Page:1,
    Kor:"아이를 낳게 해 달라고 기도하였는데, 주님께서 내가 간구한 것을 이루어 주셨습니다.",
    Chn:"我祈求为要得这孩子；耶和华已将我所求的赐给我了。",
    Eng:"I prayed for this child, and the LORD has granted me what I asked of him.",
    Ind:"Untuk mendapat anak inilah aku berdoa, dan TUHAN telah memberikan kepadaku, apa yang kuminta dari pada-Nya."
  },
  {Bible:"1Samuel", Chapter:1, Verse:28, Page:1,
    Kor:"그래서 나도 이 아이를 주님께 바칩니다. 이 아이의 한평생을 주님께 바칩니다.\" ○j그런 다음에, 그들은 거기에서 주님께 경배하였다.(j 칠십인역(사해 사본 참조)에는, '그(한나)는 그(사무엘)를 거기에 두어 주님을 섬기게 하였다')",
    Chn:"所以，我将这孩子归与耶和华，使他终身归与耶和华。」 于是在那里敬拜耶和华。",
    Eng:"So now I give him to the LORD. For his whole life he will be given over to the LORD.\" And he worshiped the LORD there.",
    Ind:"Maka akupun menyerahkannya kepada TUHAN; seumur hidup terserahlah ia kiranya kepada TUHAN.\" Lalu sujudlah mereka di sana menyembah kepada TUHAN."
  },
]);
