// 사무엘하 23장 · 2Samuel 23
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("2Samuel",23,39);
BibleDB.add([
  {Bible:"2Samuel", Chapter:23, Verse:1, Page:1, Kor:"", Chn:"", Eng:"These are the last words of David: \"The oracle of David son of Jesse, the oracle of the man exalted by the Most High, the man anointed by the God of Jacob, Israel's singer of songs:", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:2, Page:1, Kor:"", Chn:"", Eng:"\"The Spirit of the LORD spoke through me; his word was on my tongue.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:3, Page:1, Kor:"", Chn:"", Eng:"The God of Israel spoke, the Rock of Israel said to me: 'When one rules over men in righteousness, when he rules in the fear of God,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:4, Page:1, Kor:"", Chn:"", Eng:"he is like the light of morning at sunrise on a cloudless morning, like the brightness after rain that brings the grass from the earth.'", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:5, Page:1, Kor:"", Chn:"", Eng:"\"Is not my house right with God? Has he not made with me an everlasting covenant, arranged and secured in every part? Will he not bring to fruition my salvation and grant me my every desire?", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:6, Page:1, Kor:"", Chn:"", Eng:"But evil men are all to be cast aside like thorns, which are not gathered with the hand.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Whoever touches thorns uses a tool of iron or the shaft of a spear; they are burned up where they lie.\"", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:8, Page:1, Kor:"", Chn:"", Eng:"These are the names of David's mighty men: Josheb-Basshebeth, a Tahkemonite, was chief of the Three; he raised his spear against eight hundred men, whom he killed in one encounter.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Next to him was Eleazar son of Dodai the Ahohite. As one of the three mighty men, he was with David when they taunted the Philistines gathered at Pas Dammim for battle. Then the men of Israel retreated,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:10, Page:1, Kor:"", Chn:"", Eng:"but he stood his ground and struck down the Philistines till his hand grew tired and froze to the sword. The LORD brought about a great victory that day. The troops returned to Eleazar, but only to strip the dead.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Next to him was Shammah son of Agee the Hararite. When the Philistines banded together at a place where there was a field full of lentils, Israel's troops fled from them.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:12, Page:1, Kor:"", Chn:"", Eng:"But Shammah took his stand in the middle of the field. He defended it and struck the Philistines down, and the LORD brought about a great victory.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:13, Page:1, Kor:"", Chn:"", Eng:"During harvest time, three of the thirty chief men came down to David at the cave of Adullam, while a band of Philistines was encamped in the Valley of Rephaim.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:14, Page:1, Kor:"", Chn:"", Eng:"At that time David was in the stronghold, and the Philistine garrison was at Bethlehem.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:15, Page:1, Kor:"", Chn:"", Eng:"David longed for water and said, \"Oh, that someone would get me a drink of water from the well near the gate of Bethlehem!\"", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:16, Page:1, Kor:"", Chn:"", Eng:"So the three mighty men broke through the Philistine lines, drew water from the well near the gate of Bethlehem and carried it back to David. But he refused to drink it; instead, he poured it out before the LORD.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:17, Page:1, Kor:"", Chn:"", Eng:"\"Far be it from me, O LORD, to do this!\" he said. \"Is it not the blood of men who went at the risk of their lives?\" And David would not drink it. Such were the exploits of the three mighty men.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:18, Page:1, Kor:"", Chn:"", Eng:"Abishai the brother of Joab son of Zeruiah was chief of the Three. He raised his spear against three hundred men, whom he killed, and so he became as famous as the Three.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Was he not held in greater honor than the Three? He became their commander, even though he was not included among them.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Benaiah son of Jehoiada was a valiant fighter from Kabzeel, who performed great exploits. He struck down two of Moab's best men. He also went down into a pit on a snowy day and killed a lion.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:21, Page:1, Kor:"", Chn:"", Eng:"And he struck down a huge Egyptian. Although the Egyptian had a spear in his hand, Benaiah went against him with a club. He snatched the spear from the Egyptian's hand and killed him with his own spear.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:22, Page:1, Kor:"", Chn:"", Eng:"Such were the exploits of Benaiah son of Jehoiada; he too was as famous as the three mighty men.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:23, Page:1, Kor:"", Chn:"", Eng:"He was held in greater honor than any of the Thirty, but he was not included among the Three. And David put him in charge of his bodyguard.", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:24, Page:1, Kor:"", Chn:"", Eng:"Among the Thirty were: Asahel the brother of Joab, Elhanan son of Dodo from Bethlehem,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Shammah the Harodite, Elika the Harodite,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:26, Page:1, Kor:"", Chn:"", Eng:"Helez the Paltite, Ira son of Ikkesh from Tekoa,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Abiezer from Anathoth, Mebunnai the Hushathite,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Zalmon the Ahohite, Maharai the Netophathite,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Heled son of Baanah the Netophathite, Ithai son of Ribai from Gibeah in Benjamin,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:30, Page:1, Kor:"", Chn:"", Eng:"Benaiah the Pirathonite, Hiddai from the ravines of Gaash,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:31, Page:1, Kor:"", Chn:"", Eng:"Abi-Albon the Arbathite, Azmaveth the Barhumite,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:32, Page:1, Kor:"", Chn:"", Eng:"Eliahba the Shaalbonite, the sons of Jashen, Jonathan", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:33, Page:1, Kor:"", Chn:"", Eng:"son of Shammah the Hararite, Ahiam son of Sharar the Hararite,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:34, Page:1, Kor:"", Chn:"", Eng:"Eliphelet son of Ahasbai the Maacathite, Eliam son of Ahithophel the Gilonite,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:35, Page:1, Kor:"", Chn:"", Eng:"Hezro the Carmelite, Paarai the Arbite,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:36, Page:1, Kor:"", Chn:"", Eng:"Igal son of Nathan from Zobah, the son of Hagri,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:37, Page:1, Kor:"", Chn:"", Eng:"Zelek the Ammonite, Naharai the Beerothite, the armor-bearer of Joab son of Zeruiah,", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:38, Page:1, Kor:"", Chn:"", Eng:"Ira the Ithrite, Gareb the Ithrite", Ind:""},
  {Bible:"2Samuel", Chapter:23, Verse:39, Page:1, Kor:"", Chn:"", Eng:"and Uriah the Hittite. There were thirty-seven in all.", Ind:""},
]);
