// 사무엘상 30장 · Samuel1 30
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Samuel1",30,31);
BibleDB.add([
  {Bible:"Samuel1", Chapter:30, Verse:1, Page:1, Kor:"", Chn:"", Eng:"David and his men reached Ziklag on the third day. Now the Amalekites had raided the Negev and Ziklag. They had attacked Ziklag and burned it,", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:2, Page:1, Kor:"", Chn:"", Eng:"and had taken captive the women and all who were in it, both young and old. They killed none of them, but carried them off as they went on their way.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:3, Page:1, Kor:"", Chn:"", Eng:"When David and his men came to Ziklag, they found it destroyed by fire and their wives and sons and daughters taken captive.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:4, Page:1, Kor:"", Chn:"", Eng:"So David and his men wept aloud until they had no strength left to weep.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:5, Page:1, Kor:"", Chn:"", Eng:"David's two wives had been captured--Ahinoam of Jezreel and Abigail, the widow of Nabal of Carmel.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:6, Page:1, Kor:"", Chn:"", Eng:"David was greatly distressed because the men were talking of stoning him; each one was bitter in spirit because of his sons and daughters. But David found strength in the LORD his God.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Then David said to Abiathar the priest, the son of Ahimelech, "Bring me the ephod." Abiathar brought it to him,", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:8, Page:1, Kor:"", Chn:"", Eng:"and David inquired of the LORD, "Shall I pursue this raiding party? Will I overtake them?" "Pursue them," he answered. "You will certainly overtake them and succeed in the rescue."", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:9, Page:1, Kor:"", Chn:"", Eng:"David and the six hundred men with him came to the Besor Ravine, where some stayed behind,", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:10, Page:1, Kor:"", Chn:"", Eng:"for two hundred men were too exhausted to cross the ravine. But David and four hundred men continued the pursuit.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:11, Page:1, Kor:"", Chn:"", Eng:"They found an Egyptian in a field and brought him to David. They gave him water to drink and food to eat--", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:12, Page:1, Kor:"", Chn:"", Eng:"part of a cake of pressed figs and two cakes of raisins. He ate and was revived, for he had not eaten any food or drunk any water for three days and three nights.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:13, Page:1, Kor:"", Chn:"", Eng:"David asked him, "To whom do you belong, and where do you come from?" He said, "I am an Egyptian, the slave of an Amalekite. My master abandoned me when I became ill three days ago.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:14, Page:1, Kor:"", Chn:"", Eng:"We raided the Negev of the Kerethites and the territory belonging to Judah and the Negev of Caleb. And we burned Ziklag."", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:15, Page:1, Kor:"", Chn:"", Eng:"David asked him, "Can you lead me down to this raiding party?" He answered, "Swear to me before God that you will not kill me or hand me over to my master, and I will take you down to them."", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:16, Page:1, Kor:"", Chn:"", Eng:"He led David down, and there they were, scattered over the countryside, eating, drinking and reveling because of the great amount of plunder they had taken from the land of the Philistines and from Judah.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:17, Page:1, Kor:"", Chn:"", Eng:"David fought them from dusk until the evening of the next day, and none of them got away, except four hundred young men who rode off on camels and fled.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:18, Page:1, Kor:"", Chn:"", Eng:"David recovered everything the Amalekites had taken, including his two wives.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Nothing was missing: young or old, boy or girl, plunder or anything else they had taken. David brought everything back.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:20, Page:1, Kor:"", Chn:"", Eng:"He took all the flocks and herds, and his men drove them ahead of the other livestock, saying, "This is David's plunder."", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:21, Page:1, Kor:"", Chn:"", Eng:"Then David came to the two hundred men who had been too exhausted to follow him and who were left behind at the Besor Ravine. They came out to meet David and the people with him. As David and his men approached, he greeted them.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:22, Page:1, Kor:"", Chn:"", Eng:"But all the evil men and troublemakers among David's followers said, "Because they did not go out with us, we will not share with them the plunder we recovered. However, each man may take his wife and children and go."", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:23, Page:1, Kor:"", Chn:"", Eng:"David replied, "No, my brothers, you must not do that with what the LORD has given us. He has protected us and handed over to us the forces that came against us.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:24, Page:1, Kor:"", Chn:"", Eng:"Who will listen to what you say? The share of the man who stayed with the supplies is to be the same as that of him who went down to the battle. All will share alike."", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:25, Page:1, Kor:"", Chn:"", Eng:"David made this a statute and ordinance for Israel from that day to this.", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:26, Page:1, Kor:"", Chn:"", Eng:"When David arrived in Ziklag, he sent some of the plunder to the elders of Judah, who were his friends, saying, "Here is a present for you from the plunder of the LORD'S enemies."", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:27, Page:1, Kor:"", Chn:"", Eng:"He sent it to those who were in Bethel, Ramoth Negev and Jattir;", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:28, Page:1, Kor:"", Chn:"", Eng:"to those in Aroer, Siphmoth, Eshtemoa", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:29, Page:1, Kor:"", Chn:"", Eng:"and Racal; to those in the towns of the Jerahmeelites and the Kenites;", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:30, Page:1, Kor:"", Chn:"", Eng:"to those in Hormah, Bor Ashan, Athach", Ind:""},
  {Bible:"Samuel1", Chapter:30, Verse:31, Page:1, Kor:"", Chn:"", Eng:"and Hebron; and to those in all the other places where David and his men had roamed.", Ind:""},
]);
