// 누가복음 2장 · Luke 2
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Luke",2,52);
BibleDB.add([
  {Bible:"Luke", Chapter:2, Verse:1, Page:1, Kor:"", Chn:"", Eng:"In those days Caesar Augustus issued a decree that a census should be taken of the entire Roman world.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:2, Page:1, Kor:"", Chn:"", Eng:"(This was the first census that took place while Quirinius was governor of Syria.)", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:3, Page:1, Kor:"", Chn:"", Eng:"And everyone went to his own town to register.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:4, Page:1, Kor:"", Chn:"", Eng:"So Joseph also went up from the town of Nazareth in Galilee to Judea, to Bethlehem the town of David, because he belonged to the house and line of David.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:5, Page:1, Kor:"", Chn:"", Eng:"He went there to register with Mary, who was pledged to be married to him and was expecting a child.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:6, Page:1, Kor:"", Chn:"", Eng:"While they were there, the time came for the baby to be born,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:7, Page:1, Kor:"", Chn:"", Eng:"and she gave birth to her firstborn, a son. She wrapped him in cloths and placed him in a manger, because there was no room for them in the inn.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:8, Page:1, Kor:"", Chn:"", Eng:"And there were shepherds living out in the fields nearby, keeping watch over their flocks at night.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:9, Page:1, Kor:"", Chn:"", Eng:"An angel of the Lord appeared to them, and the glory of the Lord shone around them, and they were terrified.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:10, Page:1, Kor:"", Chn:"", Eng:"But the angel said to them, "Do not be afraid. I bring you good news of great joy that will be for all the people.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Today in the town of David a Savior has been born to you; he is Christ the Lord.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:12, Page:1, Kor:"", Chn:"", Eng:"This will be a sign to you: You will find a baby wrapped in cloths and lying in a manger."", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Suddenly a great company of the heavenly host appeared with the angel, praising God and saying,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:14, Page:1, Kor:"", Chn:"", Eng:""Glory to God in the highest, and on earth peace to men on whom his favor rests."", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:15, Page:1, Kor:"", Chn:"", Eng:"When the angels had left them and gone into heaven, the shepherds said to one another, "Let's go to Bethlehem and see this thing that has happened, which the Lord has told us about."", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:16, Page:1, Kor:"", Chn:"", Eng:"So they hurried off and found Mary and Joseph, and the baby, who was lying in the manger.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:17, Page:1, Kor:"", Chn:"", Eng:"When they had seen him, they spread the word concerning what had been told them about this child,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:18, Page:1, Kor:"", Chn:"", Eng:"and all who heard it were amazed at what the shepherds said to them.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:19, Page:1, Kor:"", Chn:"", Eng:"But Mary treasured up all these things and pondered them in her heart.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:20, Page:1, Kor:"", Chn:"", Eng:"The shepherds returned, glorifying and praising God for all the things they had heard and seen, which were just as they had been told.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:21, Page:1, Kor:"", Chn:"", Eng:"On the eighth day, when it was time to circumcise him, he was named Jesus, the name the angel had given him before he had been conceived.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:22, Page:1, Kor:"", Chn:"", Eng:"When the time of their purification according to the Law of Moses had been completed, Joseph and Mary took him to Jerusalem to present him to the Lord", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:23, Page:1, Kor:"", Chn:"", Eng:"(as it is written in the Law of the Lord, "Every firstborn male is to be consecrated to the Lord"),", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:24, Page:1, Kor:"", Chn:"", Eng:"and to offer a sacrifice in keeping with what is said in the Law of the Lord: "a pair of doves or two young pigeons."", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Now there was a man in Jerusalem called Simeon, who was righteous and devout. He was waiting for the consolation of Israel, and the Holy Spirit was upon him.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:26, Page:1, Kor:"", Chn:"", Eng:"It had been revealed to him by the Holy Spirit that he would not die before he had seen the Lord's Christ.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Moved by the Spirit, he went into the temple courts. When the parents brought in the child Jesus to do for him what the custom of the Law required,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Simeon took him in his arms and praised God, saying:", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:29, Page:1, Kor:"", Chn:"", Eng:""Sovereign Lord, as you have promised, you now dismiss your servant in peace.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:30, Page:1, Kor:"", Chn:"", Eng:"For my eyes have seen your salvation,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:31, Page:1, Kor:"", Chn:"", Eng:"which you have prepared in the sight of all people,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:32, Page:1, Kor:"", Chn:"", Eng:"a light for revelation to the Gentiles and for glory to your people Israel."", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:33, Page:1, Kor:"", Chn:"", Eng:"The child's father and mother marveled at what was said about him.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:34, Page:1, Kor:"", Chn:"", Eng:"Then Simeon blessed them and said to Mary, his mother: "This child is destined to cause the falling and rising of many in Israel, and to be a sign that will be spoken against,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:35, Page:1, Kor:"", Chn:"", Eng:"so that the thoughts of many hearts will be revealed. And a sword will pierce your own soul too."", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:36, Page:1, Kor:"", Chn:"", Eng:"There was also a prophetess, Anna, the daughter of Phanuel, of the tribe of Asher. She was very old; she had lived with her husband seven years after her marriage,", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:37, Page:1, Kor:"", Chn:"", Eng:"and then was a widow until she was eighty-four. She never left the temple but worshiped night and day, fasting and praying.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:38, Page:1, Kor:"", Chn:"", Eng:"Coming up to them at that very moment, she gave thanks to God and spoke about the child to all who were looking forward to the redemption of Jerusalem.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:39, Page:1, Kor:"", Chn:"", Eng:"When Joseph and Mary had done everything required by the Law of the Lord, they returned to Galilee to their own town of Nazareth.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:40, Page:1, Kor:"", Chn:"", Eng:"And the child grew and became strong; he was filled with wisdom, and the grace of God was upon him.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:41, Page:1, Kor:"", Chn:"", Eng:"Every year his parents went to Jerusalem for the Feast of the Passover.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:42, Page:1, Kor:"", Chn:"", Eng:"When he was twelve years old, they went up to the Feast, according to the custom.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:43, Page:1, Kor:"", Chn:"", Eng:"After the Feast was over, while his parents were returning home, the boy Jesus stayed behind in Jerusalem, but they were unaware of it.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:44, Page:1, Kor:"", Chn:"", Eng:"Thinking he was in their company, they traveled on for a day. Then they began looking for him among their relatives and friends.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:45, Page:1, Kor:"", Chn:"", Eng:"When they did not find him, they went back to Jerusalem to look for him.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:46, Page:1, Kor:"", Chn:"", Eng:"After three days they found him in the temple courts, sitting among the teachers, listening to them and asking them questions.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:47, Page:1, Kor:"", Chn:"", Eng:"Everyone who heard him was amazed at his understanding and his answers.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:48, Page:1, Kor:"", Chn:"", Eng:"When his parents saw him, they were astonished. His mother said to him, "Son, why have you treated us like this? Your father and I have been anxiously searching for you."", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:49, Page:1, Kor:"", Chn:"", Eng:""Why were you searching for me?" he asked. "Didn't you know I had to be in my Father's house?"", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:50, Page:1, Kor:"", Chn:"", Eng:"But they did not understand what he was saying to them.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:51, Page:1, Kor:"", Chn:"", Eng:"Then he went down to Nazareth with them and was obedient to them. But his mother treasured all these things in her heart.", Ind:""},
  {Bible:"Luke", Chapter:2, Verse:52, Page:1, Kor:"", Chn:"", Eng:"And Jesus grew in wisdom and stature, and in favor with God and men.", Ind:""},
]);
