// 누가복음 21장 · Luke 21
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Luke",21,38);
BibleDB.add([
  {Bible:"Luke", Chapter:21, Verse:1, Page:1, Kor:"", Chn:"", Eng:"As he looked up, Jesus saw the rich putting their gifts into the temple treasury.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:2, Page:1, Kor:"", Chn:"", Eng:"He also saw a poor widow put in two very small copper coins.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:3, Page:1, Kor:"", Chn:"", Eng:"\"I tell you the truth,\" he said, \"this poor widow has put in more than all the others.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:4, Page:1, Kor:"", Chn:"", Eng:"All these people gave their gifts out of their wealth; but she out of her poverty put in all she had to live on.\"", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Some of his disciples were remarking about how the temple was adorned with beautiful stones and with gifts dedicated to God. But Jesus said,", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:6, Page:1, Kor:"", Chn:"", Eng:"\"As for what you see here, the time will come when not one stone will be left on another; every one of them will be thrown down.\"", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:7, Page:1, Kor:"", Chn:"", Eng:"\"Teacher,\" they asked, \"when will these things happen? And what will be the sign that they are about to take place?\"", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:8, Page:1, Kor:"", Chn:"", Eng:"He replied: \"Watch out that you are not deceived. For many will come in my name, claiming, 'I am he,' and, 'The time is near.' Do not follow them.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:9, Page:1, Kor:"", Chn:"", Eng:"When you hear of wars and revolutions, do not be frightened. These things must happen first, but the end will not come right away.\"", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Then he said to them: \"Nation will rise against nation, and kingdom against kingdom.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:11, Page:1, Kor:"", Chn:"", Eng:"There will be great earthquakes, famines and pestilences in various places, and fearful events and great signs from heaven.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:12, Page:1, Kor:"", Chn:"", Eng:"\"But before all this, they will lay hands on you and persecute you. They will deliver you to synagogues and prisons, and you will be brought before kings and governors, and all on account of my name.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:13, Page:1, Kor:"", Chn:"", Eng:"This will result in your being witnesses to them.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:14, Page:1, Kor:"", Chn:"", Eng:"But make up your mind not to worry beforehand how you will defend yourselves.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:15, Page:1, Kor:"", Chn:"", Eng:"For I will give you words and wisdom that none of your adversaries will be able to resist or contradict.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:16, Page:1, Kor:"", Chn:"", Eng:"You will be betrayed even by parents, brothers, relatives and friends, and they will put some of you to death.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:17, Page:1, Kor:"", Chn:"", Eng:"All men will hate you because of me.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:18, Page:1, Kor:"", Chn:"", Eng:"But not a hair of your head will perish.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:19, Page:1, Kor:"", Chn:"", Eng:"By standing firm you will gain life.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:20, Page:1, Kor:"", Chn:"", Eng:"\"When you see Jerusalem being surrounded by armies, you will know that its desolation is near.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:21, Page:1, Kor:"", Chn:"", Eng:"Then let those who are in Judea flee to the mountains, let those in the city get out, and let those in the country not enter the city.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:22, Page:1, Kor:"", Chn:"", Eng:"For this is the time of punishment in fulfillment of all that has been written.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:23, Page:1, Kor:"", Chn:"", Eng:"How dreadful it will be in those days for pregnant women and nursing mothers! There will be great distress in the land and wrath against this people.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:24, Page:1, Kor:"", Chn:"", Eng:"They will fall by the sword and will be taken as prisoners to all the nations. Jerusalem will be trampled on by the Gentiles until the times of the Gentiles are fulfilled.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:25, Page:1, Kor:"", Chn:"", Eng:"\"There will be signs in the sun, moon and stars. On the earth, nations will be in anguish and perplexity at the roaring and tossing of the sea.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:26, Page:1, Kor:"", Chn:"", Eng:"Men will faint from terror, apprehensive of what is coming on the world, for the heavenly bodies will be shaken.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:27, Page:1, Kor:"", Chn:"", Eng:"At that time they will see the Son of Man coming in a cloud with power and great glory.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:28, Page:1, Kor:"", Chn:"", Eng:"When these things begin to take place, stand up and lift up your heads, because your redemption is drawing near.\"", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:29, Page:1, Kor:"", Chn:"", Eng:"He told them this parable: \"Look at the fig tree and all the trees.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:30, Page:1, Kor:"", Chn:"", Eng:"When they sprout leaves, you can see for yourselves and know that summer is near.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:31, Page:1, Kor:"", Chn:"", Eng:"Even so, when you see these things happening, you know that the kingdom of God is near.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:32, Page:1, Kor:"", Chn:"", Eng:"\"I tell you the truth, this generation will certainly not pass away until all these things have happened.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:33, Page:1, Kor:"", Chn:"", Eng:"Heaven and earth will pass away, but my words will never pass away.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:34, Page:1, Kor:"", Chn:"", Eng:"\"Be careful, or your hearts will be weighed down with dissipation, drunkenness and the anxieties of life, and that day will close on you unexpectedly like a trap.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:35, Page:1, Kor:"", Chn:"", Eng:"For it will come upon all those who live on the face of the whole earth.", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:36, Page:1, Kor:"", Chn:"", Eng:"Be always on the watch, and pray that you may be able to escape all that is about to happen, and that you may be able to stand before the Son of Man.\"", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:37, Page:1, Kor:"", Chn:"", Eng:"Each day Jesus was teaching at the temple, and each evening he went out to spend the night on the hill called the Mount of Olives,", Ind:""},
  {Bible:"Luke", Chapter:21, Verse:38, Page:1, Kor:"", Chn:"", Eng:"and all the people came early in the morning to hear him at the temple.", Ind:""},
]);
