// 누가복음 1장 · Luke 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Luke",1,80);
BibleDB.add([
  {Bible:"Luke", Chapter:1, Verse:1, Page:1,
    Kor:"<데오빌로에게 보내는 헌사> 우리 가운데서 일어난 일들에 대하여 차례대로 이야기를 엮어내려고 손을 댄 사람이 많이 있었습니다.",
    Chn:"提阿非罗大人哪，有好些人提笔作书，述说在我们中间所成就的事，是照传道的人从起初亲眼看见又传给我们的。",
    Eng:"Many have undertaken to draw up an account of the things that have been fulfilled among us,",
    Ind:"Teofilus yang mulia, Banyak orang telah berusaha menyusun suatu berita tentang peristiwa-peristiwa yang telah terjadi di antara kita,",
    ChnVerseEnd:2
  },
  {Bible:"Luke", Chapter:1, Verse:2, Page:1,
    Kor:"그들은 이것을 처음부터 말씀의 목격자요 전파자가 된 이들이 우리에게 전하여 준 대로 엮어냈습니다.",
    Chn:"",
    Eng:"just as they were handed down to us by those who from the first were eyewitnesses and servants of the word.",
    Ind:"seperti yang disampaikan kepada kita oleh mereka, yang dari semula adalah saksi mata dan pelayan Firman."
  },
  {Bible:"Luke", Chapter:1, Verse:3, Page:1,
    Kor:"그런데 존귀하신 데오빌로님, 나도 모든 것을 a시초부터 정확하게 조사하여 보았으므로, 각하께 그것을 순서대로 써 드리는 것이 좋겠다고 생각하였습니다.(a 또는 '오랫동안')",
    Chn:"这些事我既从起头都详细考察了，就定意要按着次序写给你，",
    Eng:"Therefore, since I myself have carefully investigated everything from the beginning, it seemed good also to me to write an orderly account for you, most excellent Theophilus,",
    Ind:"Karena itu, setelah aku menyelidiki segala peristiwa itu dengan seksama dari asal mulanya, aku mengambil keputusan untuk membukukannya dengan teratur bagimu,"
  },
  {Bible:"Luke", Chapter:1, Verse:4, Page:1,
    Kor:"이리하여 각하께서 이미 배우신 일들이 확실한 사실임을 아시게 되기를 바라는 바입니다.",
    Chn:"使你知道所学之道都是确实的。",
    Eng:"so that you may know the certainty of the things you have been taught.",
    Ind:"supaya engkau dapat mengetahui, bahwa segala sesuatu yang diajarkan kepadamu sungguh benar."
  },
  {Bible:"Luke", Chapter:1, Verse:5, Page:1,
    Kor:"<세례자 요한의 출생을 예고하다> ○유대왕 헤롯 때에, 아비야 조에 배속된 제사장으로서, 사가랴라고 하는 사람이 있었다. 그의 아내는 아론의 자손인데, 이름은 엘리사벳이다.",
    Chn:"当犹太王希律的时候，亚比雅班里有一个祭司，名叫撒迦利亚；他妻子是亚伦的后人，名叫伊利莎白。",
    Eng:"In the time of Herod king of Judea there was a priest named Zechariah, who belonged to the priestly division of Abijah; his wife Elizabeth was also a descendant of Aaron.",
    Ind:"Pada zaman Herodes, raja Yudea, adalah seorang imam yang bernama Zakharia dari rombongan Abia. Isterinya juga berasal dari keturunan Harun, namanya Elisabet."
  },
  {Bible:"Luke", Chapter:1, Verse:6, Page:1,
    Kor:"그 두 사람은 다 하나님 앞에서 의로운 사람이어서, 주님의 모든 계명과 규율을 흠잡을 데 없이 잘 지켰다.",
    Chn:"他们二人在　神面前都是义人，遵行主的一切诫命礼仪，没有可指摘的，",
    Eng:"Both of them were upright in the sight of God, observing all the Lord's commandments and regulations blamelessly.",
    Ind:"Keduanya adalah benar di hadapan Allah dan hidup menurut segala perintah dan ketetapan Tuhan dengan tidak bercacat."
  },
  {Bible:"Luke", Chapter:1, Verse:7, Page:1,
    Kor:"그런데 그들에게는 자녀가 없었다. 엘리사벳이 임신을 하지 못하는 여자이고, 두 사람은 다 나이가 많았기 때문이다.",
    Chn:"只是没有孩子；因为伊利莎白不生育，两个人又年纪老迈了。",
    Eng:"But they had no children, because Elizabeth was barren; and they were both well along in years.",
    Ind:"Tetapi mereka tidak mempunyai anak, sebab Elisabet mandul dan keduanya telah lanjut umurnya."
  },
  {Bible:"Luke", Chapter:1, Verse:8, Page:1,
    Kor:"○사가랴가 자기 조의 차례가 되어서, 하나님 앞에서 제사장의 직분을 담당하게 되었다.",
    Chn:"撒迦利亚按班次在　神面前供祭司的职分，",
    Eng:"Once when Zechariah's division was on duty and he was serving as priest before God,",
    Ind:"Pada suatu kali, waktu tiba giliran rombongannya, Zakharia melakukan tugas keimaman di hadapan Tuhan."
  },
  {Bible:"Luke", Chapter:1, Verse:9, Page:1,
    Kor:"어느 날 제사직의 관례를 따라 제비를 뽑았는데, 그가 주님의 성소에 들어가 분향하는 일을 맡게 되었다.",
    Chn:"照祭司的规矩掣签，得进主殿烧香。",
    Eng:"he was chosen by lot, according to the custom of the priesthood, to go into the temple of the Lord and burn incense.",
    Ind:"Sebab ketika diundi, sebagaimana lazimnya, untuk menentukan imam yang bertugas, dialah yang ditunjuk untuk masuk ke dalam Bait Suci dan membakar ukupan di situ."
  },
  {Bible:"Luke", Chapter:1, Verse:10, Page:1,
    Kor:"그가 분향하는 동안에, 온 백성은 다 밖에서 기도하고 있었다.",
    Chn:"烧香的时候，众百姓在外面祷告。",
    Eng:"And when the time for the burning of incense came, all the assembled worshipers were praying outside.",
    Ind:"Sementara itu seluruh umat berkumpul di luar dan sembahyang. Waktu itu adalah waktu pembakaran ukupan."
  },
  {Bible:"Luke", Chapter:1, Verse:11, Page:1,
    Kor:"그 때에 주님의 천사가 사가랴에게 나타나서, 분향하는 제단 오른쪽에 섰다.",
    Chn:"有主的使者站在香坛的右边，向他显现。",
    Eng:"Then an angel of the Lord appeared to him, standing at the right side of the altar of incense.",
    Ind:"Maka tampaklah kepada Zakharia seorang malaikat Tuhan berdiri di sebelah kanan mezbah pembakaran ukupan."
  },
  {Bible:"Luke", Chapter:1, Verse:12, Page:1,
    Kor:"그는 천사를 보고 놀라서, 두려움에 사로잡혔다.",
    Chn:"撒迦利亚看见，就惊慌害怕。",
    Eng:"When Zechariah saw him, he was startled and was gripped with fear.",
    Ind:"Melihat hal itu ia terkejut dan menjadi takut."
  },
  {Bible:"Luke", Chapter:1, Verse:13, Page:1,
    Kor:"천사가 그에게 말하였다. \"사가랴야, 두려워하지 말아라. 네 간구를 주님께서 들어 주셨다. 네 아내 엘리사벳이 너에게 아들을 낳아 줄 것이니, 그 이름을 요한이라고 하여라.",
    Chn:"天使对他说：「撒迦利亚，不要害怕，因为你的祈祷已经被听见了。你的妻子伊利莎白要给你生一个儿子，你要给他起名叫约翰。",
    Eng:"But the angel said to him: \"Do not be afraid, Zechariah; your prayer has been heard. Your wife Elizabeth will bear you a son, and you are to give him the name John.",
    Ind:"Tetapi malaikat itu berkata kepadanya: \"Jangan takut, hai Zakharia, sebab doamu telah dikabulkan dan Elisabet, isterimu, akan melahirkan seorang anak laki-laki bagimu dan haruslah engkau menamai dia Yohanes."
  },
  {Bible:"Luke", Chapter:1, Verse:14, Page:1,
    Kor:"그 아들은 네게 기쁨과 즐거움이 되고, 많은 사람이 그의 출생을 기뻐할 것이다.",
    Chn:"你必欢喜快乐；有许多人因他出世，也必喜乐。",
    Eng:"He will be a joy and delight to you, and many will rejoice because of his birth,",
    Ind:"Engkau akan bersukacita dan bergembira, bahkan banyak orang akan bersukacita atas kelahirannya itu."
  },
  {Bible:"Luke", Chapter:1, Verse:15, Page:1,
    Kor:"그는 주님께서 보시기에 큰 인물이 될 것이다. 그는 포도주와 독한 술을 입에 대지 않을 것이요, 어머니 뱃속에 있을 때부터 성령을 충만하게 받을 것이며,",
    Chn:"他在主面前将要为大，淡酒浓酒都不喝，从母腹里就被圣灵充满了。",
    Eng:"for he will be great in the sight of the Lord. He is never to take wine or other fermented drink, and he will be filled with the Holy Spirit even from birth.",
    Ind:"Sebab ia akan besar di hadapan Tuhan dan ia tidak akan minum anggur atau minuman keras dan ia akan penuh dengan Roh Kudus mulai dari rahim ibunya;"
  },
  {Bible:"Luke", Chapter:1, Verse:16, Page:1,
    Kor:"이스라엘 자손 가운데서 많은 사람을 그들의 주 하나님께로 돌아오게 할 것이다.",
    Chn:"他要使许多以色列人回转，归于主—他们的　神。",
    Eng:"Many of the people of Israel will he bring back to the Lord their God.",
    Ind:"ia akan membuat banyak orang Israel berbalik kepada Tuhan, Allah mereka,"
  },
  {Bible:"Luke", Chapter:1, Verse:17, Page:1,
    Kor:"그는 또한 엘리야의 심령과 능력을 가지고 주님보다 앞서 와서, 부모의 마음을 자녀에게로 돌아오게 하고 거역하는 자들을 의인의 지혜의 길로 돌아서게 해서, 주님을 맞이할 준비가 된 백성을 마련할 것이다.\"",
    Chn:"他必有以利亚的心志能力，行在主的前面，叫为父的心转向儿女，叫悖逆的人转从义人的智慧，又为主预备合用的百姓。」",
    Eng:"And he will go on before the Lord, in the spirit and power of Elijah, to turn the hearts of the fathers to their children and the disobedient to the wisdom of the righteous--to make ready a people prepared for the Lord.\"",
    Ind:"dan ia akan berjalan mendahului Tuhan dalam roh dan kuasa Elia untuk membuat hati bapa-bapa berbalik kepada anak-anaknya dan hati orang-orang durhaka kepada pikiran orang-orang benar dan dengan demikian menyiapkan bagi Tuhan suatu umat yang layak bagi-Nya.\""
  },
  {Bible:"Luke", Chapter:1, Verse:18, Page:1,
    Kor:"사가랴가 천사에게 말하였다. \"어떻게 그것을 알겠습니까? 나는 늙은 사람이요, 내 아내도 나이가 많으니 말입니다.\"",
    Chn:"撒迦利亚对天使说：「我凭着什么可知道这事呢？我已经老了，我的妻子也年纪老迈了。」",
    Eng:"Zechariah asked the angel, \"How can I be sure of this? I am an old man and my wife is well along in years.\"",
    Ind:"Lalu kata Zakharia kepada malaikat itu: \"Bagaimanakah aku tahu, bahwa hal ini akan terjadi? Sebab aku sudah tua dan isteriku sudah lanjut umurnya.\""
  },
  {Bible:"Luke", Chapter:1, Verse:19, Page:1,
    Kor:"천사가 그에게 말하였다. \"나는 하나님 앞에 서 있는 가브리엘인데, 나는 네게 이 기쁜 소식을 전해 주려고 보내심을 받았다.",
    Chn:"天使回答说：「我是站在　神面前的加百列，奉差而来对你说话，将这好信息报给你。",
    Eng:"The angel answered, \"I am Gabriel. I stand in the presence of God, and I have been sent to speak to you and to tell you this good news.",
    Ind:"Jawab malaikat itu kepadanya: \"Akulah Gabriel yang melayani Allah dan aku telah diutus untuk berbicara dengan engkau dan untuk menyampaikan kabar baik ini kepadamu."
  },
  {Bible:"Luke", Chapter:1, Verse:20, Page:1,
    Kor:"보아라, 그 때가 되면 다 이루어질 내 말을 네가 믿지 않았으므로, 이 일이 이루어지는 날까지, 너는 벙어리가 되어서 말을 못하게 될 것이다.\"",
    Chn:"到了时候，这话必然应验；只因你不信，你必哑巴，不能说话，直到这事成就的日子。」",
    Eng:"And now you will be silent and not able to speak until the day this happens, because you did not believe my words, which will come true at their proper time.\"",
    Ind:"Sesungguhnya engkau akan menjadi bisu dan tidak dapat berkata-kata sampai kepada hari, di mana semuanya ini terjadi, karena engkau tidak percaya akan perkataanku yang akan nyata kebenarannya pada waktunya.\""
  },
  {Bible:"Luke", Chapter:1, Verse:21, Page:1,
    Kor:"○백성이 사가랴를 기다리는데, 그가 성소 안에서 너무도 오래 지체하므로, 이상하게 여기고 있었다.",
    Chn:"百姓等候撒迦利亚，诧异他许久在殿里。",
    Eng:"Meanwhile, the people were waiting for Zechariah and wondering why he stayed so long in the temple.",
    Ind:"Sementara itu orang banyak menanti-nantikan Zakharia. Mereka menjadi heran, bahwa ia begitu lama berada dalam Bait Suci."
  },
  {Bible:"Luke", Chapter:1, Verse:22, Page:1,
    Kor:"그런데 그가 나와서도 말을 못하니까, 사람들은 그가 성소 안에서 환상을 본 줄로 알았다. 사가랴는 그들에게 손짓만 할 뿐이요, 그냥 말을 못하는 채로 있었다.",
    Chn:"及至他出来，不能和他们说话，他们就知道他在殿里见了异象；因为他直向他们打手式，竟成了哑巴。",
    Eng:"When he came out, he could not speak to them. They realized he had seen a vision in the temple, for he kept making signs to them but remained unable to speak.",
    Ind:"Ketika ia keluar, ia tidak dapat berkata-kata kepada mereka dan mengertilah mereka, bahwa ia telah melihat suatu penglihatan di dalam Bait Suci. Lalu ia memberi isyarat kepada mereka, sebab ia tetap bisu."
  },
  {Bible:"Luke", Chapter:1, Verse:23, Page:1,
    Kor:"사가랴는 제사 당번 기간이 끝난 뒤에 집으로 돌아갔다.",
    Chn:"他供职的日子已满，就回家去了。",
    Eng:"When his time of service was completed, he returned home.",
    Ind:"Ketika selesai jangka waktu tugas jabatannya, ia pulang ke rumah."
  },
  {Bible:"Luke", Chapter:1, Verse:24, Page:1,
    Kor:"그 뒤에 얼마 지나서, 그의 아내 엘리사벳이 임신하고, 다섯 달 동안 숨어 살면서 이렇게 말하였다.",
    Chn:"这些日子以后，他的妻子伊利莎白怀了孕，就隐藏了五个月，",
    Eng:"After this his wife Elizabeth became pregnant and for five months remained in seclusion.",
    Ind:"Beberapa lama kemudian Elisabet, isterinya, mengandung dan selama lima bulan ia tidak menampakkan diri, katanya:"
  },
  {Bible:"Luke", Chapter:1, Verse:25, Page:1,
    Kor:"\"주님께서 나를 돌아보셔서 사람들에게 당하는 내 부끄러움을 없이해 주시던 날에 나에게 이런 일을 베풀어 주셨다.\"",
    Chn:"说：「主在眷顾我的日子，这样看待我，要把我在人间的羞耻除掉。」",
    Eng:"\"The Lord has done this for me,\" she said. \"In these days he has shown his favor and taken away my disgrace among the people.\"",
    Ind:"\"Inilah suatu perbuatan Tuhan bagiku, dan sekarang Ia berkenan menghapuskan aibku di depan orang.\""
  },
  {Bible:"Luke", Chapter:1, Verse:26, Page:1,
    Kor:"<예수의 탄생을 예고하다> ○그 뒤로 여섯 달이 되었을 때에, 하나님께서 천사 가브리엘을 갈릴리 지방의 나사렛 동네로 보내시어,",
    Chn:"到了第六个月，天使加百列奉　神的差遣往加利利的一座城去（这城名叫拿撒勒），",
    Eng:"In the sixth month, God sent the angel Gabriel to Nazareth, a town in Galilee,",
    Ind:"Dalam bulan yang keenam Allah menyuruh malaikat Gabriel pergi ke sebuah kota di Galilea bernama Nazaret,"
  },
  {Bible:"Luke", Chapter:1, Verse:27, Page:1,
    Kor:"다윗의 가문에 속한 요셉이라는 남자와 약혼한 처녀에게 가게 하셨다. 그 처녀의 이름은 마리아였다.",
    Chn:"到一个童女那里，是已经许配大卫家的一个人，名叫约瑟。童女的名字叫马利亚；",
    Eng:"to a virgin pledged to be married to a man named Joseph, a descendant of David. The virgin's name was Mary.",
    Ind:"kepada seorang perawan yang bertunangan dengan seorang bernama Yusuf dari keluarga Daud; nama perawan itu Maria."
  },
  {Bible:"Luke", Chapter:1, Verse:28, Page:1,
    Kor:"천사가 안으로 들어가서, 마리아에게 말하였다. \"기뻐하여라, 은혜를 입은 자야, b주님께서 그대와 함께 하신다.\"(b 다른 고대 사본들에는 '여인들 가운데서 너는 복이 있다. 주님께서……')",
    Chn:"天使进去，对她说：「蒙大恩的女子，我问你安，主和你同在了！」",
    Eng:"The angel went to her and said, \"Greetings, you who are highly favored! The Lord is with you.\"",
    Ind:"Ketika malaikat itu masuk ke rumah Maria, ia berkata: \"Salam, hai engkau yang dikaruniai, Tuhan menyertai engkau.\""
  },
  {Bible:"Luke", Chapter:1, Verse:29, Page:1,
    Kor:"마리아는 그 말을 듣고 몹시 놀라, 도대체 그 인사말이 무슨 뜻일까 하고 궁금히 여겼다.",
    Chn:"马利亚因这话就很惊慌，又反复思想这样问安是什么意思。",
    Eng:"Mary was greatly troubled at his words and wondered what kind of greeting this might be.",
    Ind:"Maria terkejut mendengar perkataan itu, lalu bertanya di dalam hatinya, apakah arti salam itu."
  },
  {Bible:"Luke", Chapter:1, Verse:30, Page:1,
    Kor:"천사가 마리아에게 말하였다. \"두려워하지 말아라. 마리아야, 그대는 하나님의 은혜를 입었다.",
    Chn:"天使对她说：「马利亚，不要怕！你在　神面前已经蒙恩了。",
    Eng:"But the angel said to her, \"Do not be afraid, Mary, you have found favor with God.",
    Ind:"Kata malaikat itu kepadanya: \"Jangan takut, hai Maria, sebab engkau beroleh kasih karunia di hadapan Allah."
  },
  {Bible:"Luke", Chapter:1, Verse:31, Page:1,
    Kor:"보아라, 그대가 잉태하여 아들을 낳을 터이니, 그의 이름을 예수라고 하여라.",
    Chn:"你要怀孕生子，可以给他起名叫耶稣。",
    Eng:"You will be with child and give birth to a son, and you are to give him the name Jesus.",
    Ind:"Sesungguhnya engkau akan mengandung dan akan melahirkan seorang anak laki-laki dan hendaklah engkau menamai Dia Yesus."
  },
  {Bible:"Luke", Chapter:1, Verse:32, Page:1,
    Kor:"그는 위대하게 되고, 더없이 높으신 분의 아들이라고 불릴 것이다. 주 하나님께서 그에게 그의 조상 다윗의 왕위를 주실 것이다.",
    Chn:"他要为大，称为至高者的儿子；主　神要把他祖大卫的位给他。",
    Eng:"He will be great and will be called the Son of the Most High. The Lord God will give him the throne of his father David,",
    Ind:"Ia akan menjadi besar dan akan disebut Anak Allah Yang Mahatinggi. Dan Tuhan Allah akan mengaruniakan kepada-Nya takhta Daud, bapa leluhur-Nya,"
  },
  {Bible:"Luke", Chapter:1, Verse:33, Page:1,
    Kor:"그는 영원히 야곱의 집을 다스리고, 그의 나라는 무궁할 것이다.\"",
    Chn:"他要作雅各家的王，直到永远；他的国也没有穷尽。」",
    Eng:"and he will reign over the house of Jacob forever; his kingdom will never end.\"",
    Ind:"dan Ia akan menjadi raja atas kaum keturunan Yakub sampai selama-lamanya dan Kerajaan-Nya tidak akan berkesudahan.\""
  },
  {Bible:"Luke", Chapter:1, Verse:34, Page:1,
    Kor:"마리아가 천사에게 말하였다. \"나는 c남자를 알지 못하는데, 어떻게 이런 일이 있겠습니까?\"(c 처녀라는 뜻)",
    Chn:"马利亚对天使说：「我没有出嫁，怎么有这事呢？」",
    Eng:"\"How will this be,\" Mary asked the angel, \"since I am a virgin?\"",
    Ind:"Kata Maria kepada malaikat itu: \"Bagaimana hal itu mungkin terjadi, karena aku belum bersuami?\""
  },
  {Bible:"Luke", Chapter:1, Verse:35, Page:1,
    Kor:"천사가 마리아에게 대답하였다. \"성령이 그대에게 임하시고, 더없이 높으신 분의 능력이 그대를 감싸 줄 것이다. 그러므로 d태어날 아기는 거룩한 분이요, 하나님의 아들이라고 불릴 것이다.(d 다른 고대 사본들에는 '너에게 태어날')",
    Chn:"天使回答说：「圣灵要临到你身上，至高者的能力要荫庇你，因此所要生的圣者必称为　神的儿子。",
    Eng:"The angel answered, \"The Holy Spirit will come upon you, and the power of the Most High will overshadow you. So the holy one to be born will be called the Son of God.",
    Ind:"Jawab malaikat itu kepadanya: \"Roh Kudus akan turun atasmu dan kuasa Allah Yang Mahatinggi akan menaungi engkau; sebab itu anak yang akan kaulahirkan itu akan disebut kudus, Anak Allah."
  },
  {Bible:"Luke", Chapter:1, Verse:36, Page:1,
    Kor:"보아라, 그대의 친척 엘리사벳도 늙어서 임신하였다. 임신하지 못하는 여자라 불리던 그가 임신한 지 벌써 여섯 달이 되었다.",
    Chn:"况且你的亲戚伊利莎白，在年老的时候也怀了男胎，就是那素来称为不生育的，现在有孕六个月了。",
    Eng:"Even Elizabeth your relative is going to have a child in her old age, and she who was said to be barren is in her sixth month.",
    Ind:"Dan sesungguhnya, Elisabet, sanakmu itu, iapun sedang mengandung seorang anak laki-laki pada hari tuanya dan inilah bulan yang keenam bagi dia, yang disebut mandul itu."
  },
  {Bible:"Luke", Chapter:1, Verse:37, Page:1,
    Kor:"하나님께는 불가능한 일이 없다.\"",
    Chn:"因为，出于　神的话，没有一句不带能力的。」",
    Eng:"For nothing is impossible with God.\"",
    Ind:"Sebab bagi Allah tidak ada yang mustahil.\""
  },
  {Bible:"Luke", Chapter:1, Verse:38, Page:1,
    Kor:"마리아가 말하였다. \"보십시오, 나는 주님의 여종입니다. 당신의 말씀대로 나에게 이루어지기를 바랍니다.\" 천사는 마리아에게서 떠나갔다.",
    Chn:"马利亚说：「我是主的使女，情愿照你的话成就在我身上。」天使就离开她去了。",
    Eng:"\"I am the Lord's servant,\" Mary answered. \"May it be to me as you have said.\" Then the angel left her.",
    Ind:"Kata Maria: \"Sesungguhnya aku ini adalah hamba Tuhan; jadilah padaku menurut perkataanmu itu.\" Lalu malaikat itu meninggalkan dia."
  },
  {Bible:"Luke", Chapter:1, Verse:39, Page:1,
    Kor:"<마리아가 엘리사벳을 방문하다> ○그 무렵에, 마리아가 일어나, 서둘러 유대 산골에 있는 한 동네로 가서,",
    Chn:"那时候，马利亚起身，急忙往山地里去，来到犹大的一座城；",
    Eng:"At that time Mary got ready and hurried to a town in the hill country of Judea,",
    Ind:"Beberapa waktu kemudian berangkatlah Maria dan langsung berjalan ke pegunungan menuju sebuah kota di Yehuda."
  },
  {Bible:"Luke", Chapter:1, Verse:40, Page:1,
    Kor:"사가랴의 집에 들어가, 엘리사벳에게 문안하였다.",
    Chn:"进了撒迦利亚的家，问伊利莎白安。",
    Eng:"where she entered Zechariah's home and greeted Elizabeth.",
    Ind:"Di situ ia masuk ke rumah Zakharia dan memberi salam kepada Elisabet."
  },
  {Bible:"Luke", Chapter:1, Verse:41, Page:1,
    Kor:"엘리사벳이 마리아의 인사말을 들었을 때에, 아이가 그의 뱃속에서 뛰놀았다. 엘리사벳이 성령으로 충만해서,",
    Chn:"伊利莎白一听马利亚问安，所怀的胎就在腹里跳动。伊利莎白且被圣灵充满，",
    Eng:"When Elizabeth heard Mary's greeting, the baby leaped in her womb, and Elizabeth was filled with the Holy Spirit.",
    Ind:"Dan ketika Elisabet mendengar salam Maria, melonjaklah anak yang di dalam rahimnya dan Elisabetpun penuh dengan Roh Kudus,"
  },
  {Bible:"Luke", Chapter:1, Verse:42, Page:1,
    Kor:"큰 소리로 외쳐 말하였다. \"그대는 여자들 가운데서 복을 받았고, 그대의 태중의 아이도 복을 받았습니다.",
    Chn:"高声喊着说：「你在妇女中是有福的！你所怀的胎也是有福的！",
    Eng:"In a loud voice she exclaimed: \"Blessed are you among women, and blessed is the child you will bear!",
    Ind:"lalu berseru dengan suara nyaring: \"Diberkatilah engkau di antara semua perempuan dan diberkatilah buah rahimmu."
  },
  {Bible:"Luke", Chapter:1, Verse:43, Page:1,
    Kor:"내 주님의 어머니께서 내게 오시다니, 이것이 어찌된 일입니까?",
    Chn:"我主的母到我这里来，这是从哪里得的呢？",
    Eng:"But why am I so favored, that the mother of my Lord should come to me?",
    Ind:"Siapakah aku ini sampai ibu Tuhanku datang mengunjungi aku?"
  },
  {Bible:"Luke", Chapter:1, Verse:44, Page:1,
    Kor:"보십시오. 그대의 인사말이 내 귀에 들어왔을 때에, 내 태중의 아이가 기뻐서 뛰놀았습니다.",
    Chn:"因为你问安的声音一入我耳，我腹里的胎就欢喜跳动。",
    Eng:"As soon as the sound of your greeting reached my ears, the baby in my womb leaped for joy.",
    Ind:"Sebab sesungguhnya, ketika salammu sampai kepada telingaku, anak yang di dalam rahimku melonjak kegirangan."
  },
  {Bible:"Luke", Chapter:1, Verse:45, Page:1,
    Kor:"주님께서 하신 말씀이 이루어질 줄 믿은 여자는 행복합니다.\"",
    Chn:"这相信的女子是有福的！因为主对她所说的话都要应验。」",
    Eng:"Blessed is she who has believed that what the Lord has said to her will be accomplished!\"",
    Ind:"Dan berbahagialah ia, yang telah percaya, sebab apa yang dikatakan kepadanya dari Tuhan, akan terlaksana.\""
  },
  {Bible:"Luke", Chapter:1, Verse:46, Page:1,
    Kor:"<마리아의 찬가> ○그리하여 e마리아가 말하였다.  \"내 영혼이 주님을 찬양하며 (e 다른 고대 역본들에는 '엘리사벳이')",
    Chn:"马利亚说： 我心尊主为大；",
    Eng:"And Mary said: \"My soul glorifies the Lord",
    Ind:"Lalu kata Maria: \"Jiwaku memuliakan Tuhan,"
  },
  {Bible:"Luke", Chapter:1, Verse:47, Page:1,
    Kor:"내 마음이 내 구주 하나님을 좋아함은,",
    Chn:"我灵以　神我的救主为乐；",
    Eng:"and my spirit rejoices in God my Savior,",
    Ind:"dan hatiku bergembira karena Allah, Juruselamatku,"
  },
  {Bible:"Luke", Chapter:1, Verse:48, Page:1,
    Kor:"그가 이 여종의 비천함을 보살펴 주셨기 때문입니다. 이제부터는 모든 세대가 나를 행복하다 할 것입니다.",
    Chn:"因为他顾念他使女的卑微； 从今以后， 万代要称我有福。",
    Eng:"for he has been mindful of the humble state of his servant. From now on all generations will call me blessed,",
    Ind:"sebab Ia telah memperhatikan kerendahan hamba-Nya. Sesungguhnya, mulai dari sekarang segala keturunan akan menyebut aku berbahagia,"
  },
  {Bible:"Luke", Chapter:1, Verse:49, Page:1,
    Kor:"힘센 분이 나에게 큰 일을 하셨기 때문입니다. 그의 이름은 거룩하고,",
    Chn:"那有权能的，为我成就了大事； 他的名为圣。",
    Eng:"for the Mighty One has done great things for me--holy is his name.",
    Ind:"karena Yang Mahakuasa telah melakukan perbuatan-perbuatan besar kepadaku dan nama-Nya adalah kudus."
  },
  {Bible:"Luke", Chapter:1, Verse:50, Page:1,
    Kor:"그의 자비하심은, 그를 두려워하는 사람들에게 대대로 있을 것입니다.",
    Chn:"他怜悯敬畏他的人， 直到世世代代。",
    Eng:"His mercy extends to those who fear him, from generation to generation.",
    Ind:"Dan rahmat-Nya turun-temurun atas orang yang takut akan Dia."
  },
  {Bible:"Luke", Chapter:1, Verse:51, Page:1,
    Kor:"그는 그 팔로 권능을 행하시고 마음이 교만한 사람들을 흩으셨으니,",
    Chn:"他用膀臂施展大能； 那狂傲的人正心里妄想就被他赶散了。",
    Eng:"He has performed mighty deeds with his arm; he has scattered those who are proud in their inmost thoughts.",
    Ind:"Ia memperlihatkan kuasa-Nya dengan perbuatan tangan-Nya dan mencerai-beraikan orang-orang yang congkak hatinya;"
  },
  {Bible:"Luke", Chapter:1, Verse:52, Page:1,
    Kor:"제왕들을 왕좌에서 끌어내리시고 비천한 사람을 높이셨습니다.",
    Chn:"他叫有权柄的失位， 叫卑贱的升高；",
    Eng:"He has brought down rulers from their thrones but has lifted up the humble.",
    Ind:"Ia menurunkan orang-orang yang berkuasa dari takhtanya dan meninggikan orang-orang yang rendah;"
  },
  {Bible:"Luke", Chapter:1, Verse:53, Page:1,
    Kor:"주린 사람들을 좋은 것으로 배부르게 하시고, 부한 사람들을 빈손으로 떠나보내셨습니다.",
    Chn:"叫饥饿的得饱美食， 叫富足的空手回去。",
    Eng:"He has filled the hungry with good things but has sent the rich away empty.",
    Ind:"Ia melimpahkan segala yang baik kepada orang yang lapar, dan menyuruh orang yang kaya pergi dengan tangan hampa;"
  },
  {Bible:"Luke", Chapter:1, Verse:54, Page:1,
    Kor:"그는 자비를 기억하셔서, 자기의 종 이스라엘을 도우셨습니다.",
    Chn:"他扶助了他的仆人以色列，",
    Eng:"He has helped his servant Israel, remembering to be merciful",
    Ind:"Ia menolong Israel, hamba-Nya, karena Ia mengingat rahmat-Nya,"
  },
  {Bible:"Luke", Chapter:1, Verse:55, Page:1,
    Kor:"우리 조상들에게 말씀하신 대로, 그 자비는 아브라함과 그 자손에게 영원토록 있을 것입니다.\"",
    Chn:"为要记念亚伯拉罕和他的后裔， 施怜悯直到永远， 正如从前对我们列祖所说的话。",
    Eng:"to Abraham and his descendants forever, even as he said to our fathers.\"",
    Ind:"seperti yang dijanjikan-Nya kepada nenek moyang kita, kepada Abraham dan keturunannya untuk selama-lamanya.\""
  },
  {Bible:"Luke", Chapter:1, Verse:56, Page:1,
    Kor:"○마리아는 엘리사벳과 함께 석 달쯤 있다가 자기 집으로 돌아갔다.",
    Chn:"马利亚和伊利莎白同住，约有三个月，就回家去了。",
    Eng:"Mary stayed with Elizabeth for about three months and then returned home.",
    Ind:"Dan Maria tinggal kira-kira tiga bulan lamanya bersama dengan Elisabet, lalu pulang kembali ke rumahnya."
  },
  {Bible:"Luke", Chapter:1, Verse:57, Page:1,
    Kor:"<세례자 요한의 출생> ○엘리사벳은 해산할 달이 차서, 아들을 낳았다.",
    Chn:"伊利莎白的产期到了，就生了一个儿子。",
    Eng:"When it was time for Elizabeth to have her baby, she gave birth to a son.",
    Ind:"Kemudian genaplah bulannya bagi Elisabet untuk bersalin dan iapun melahirkan seorang anak laki-laki."
  },
  {Bible:"Luke", Chapter:1, Verse:58, Page:1,
    Kor:"이웃 사람들과 친척들은, 주님께서 큰 자비를 그에게 베푸셨다는 말을 듣고서, 그와 함께 기뻐하였다.",
    Chn:"邻里亲族听见主向她大施怜悯，就和她一同欢乐。",
    Eng:"Her neighbors and relatives heard that the Lord had shown her great mercy, and they shared her joy.",
    Ind:"Ketika tetangga-tetangganya serta sanak saudaranya mendengar, bahwa Tuhan telah menunjukkan rahmat-Nya yang begitu besar kepadanya, bersukacitalah mereka bersama-sama dengan dia."
  },
  {Bible:"Luke", Chapter:1, Verse:59, Page:1,
    Kor:"○아기가 태어난 지 여드레째 되는 날에, 그들은 아기에게 할례를 행하러 와서, 그의 아버지의 이름을 따서, 그를 사가랴라 하고자 하였다.",
    Chn:"到了第八日，他们来要给孩子行割礼，并要照他父亲的名字叫他撒迦利亚。",
    Eng:"On the eighth day they came to circumcise the child, and they were going to name him after his father Zechariah,",
    Ind:"Maka datanglah mereka pada hari yang kedelapan untuk menyunatkan anak itu dan mereka hendak menamai dia Zakharia menurut nama bapanya,"
  },
  {Bible:"Luke", Chapter:1, Verse:60, Page:1,
    Kor:"그러나 아기 어머니가 말하였다. \"안 됩니다. 요한이라고 해야 합니다.\"",
    Chn:"他母亲说：「不可！要叫他约翰。」",
    Eng:"but his mother spoke up and said, \"No! He is to be called John.\"",
    Ind:"tetapi ibunya berkata: \"Jangan, ia harus dinamai Yohanes.\""
  },
  {Bible:"Luke", Chapter:1, Verse:61, Page:1,
    Kor:"사람들이 말하였다. \"당신의 친척 가운데는 아무도 이런 이름을 가진 사람이 없습니다.\"",
    Chn:"他们说：「你亲族中没有叫这名字的。」",
    Eng:"They said to her, \"There is no one among your relatives who has that name.\"",
    Ind:"Kata mereka kepadanya: \"Tidak ada di antara sanak saudaramu yang bernama demikian.\""
  },
  {Bible:"Luke", Chapter:1, Verse:62, Page:1,
    Kor:"그들은 그 아버지에게 아기의 이름을 무엇으로 하려는지 손짓으로 물어 보았다.",
    Chn:"他们就向他父亲打手式，问他要叫这孩子什么名字。",
    Eng:"Then they made signs to his father, to find out what he would like to name the child.",
    Ind:"Lalu mereka memberi isyarat kepada bapanya untuk bertanya nama apa yang hendak diberikannya kepada anaknya itu."
  },
  {Bible:"Luke", Chapter:1, Verse:63, Page:1,
    Kor:"그가 서판을 달라 하여 \"그의 이름은 요한이다\" 하고 쓰니, 모두들 이상히 여겼다.",
    Chn:"他要了一块写字的板，就写上，说：「他的名字是约翰。」他们便都希奇。",
    Eng:"He asked for a writing tablet, and to everyone's astonishment he wrote, \"His name is John.\"",
    Ind:"Ia meminta batu tulis, lalu menuliskan kata-kata ini: \"Namanya adalah Yohanes.\" Dan merekapun heran semuanya."
  },
  {Bible:"Luke", Chapter:1, Verse:64, Page:1,
    Kor:"그런데 그의 입이 곧 열리고 혀가 풀려서, 말을 하며 하나님을 찬양하였다.",
    Chn:"撒迦利亚的口立时开了，舌头也舒展了，就说出话来，称颂　神。",
    Eng:"Immediately his mouth was opened and his tongue was loosed, and he began to speak, praising God.",
    Ind:"Dan seketika itu juga terbukalah mulutnya dan terlepaslah lidahnya, lalu ia berkata-kata dan memuji Allah."
  },
  {Bible:"Luke", Chapter:1, Verse:65, Page:1,
    Kor:"이웃 사람들은 모두 두려워하였다. 이 모든 이야기는 유대 온 산골에 두루 퍼졌다.",
    Chn:"周围居住的人都惧怕；这一切的事就传遍了犹太的山地。",
    Eng:"The neighbors were all filled with awe, and throughout the hill country of Judea people were talking about all these things.",
    Ind:"Maka ketakutanlah semua orang yang tinggal di sekitarnya, dan segala peristiwa itu menjadi buah tutur di seluruh pegunungan Yudea."
  },
  {Bible:"Luke", Chapter:1, Verse:66, Page:1,
    Kor:"이 말을 들은 사람들은 모두 이 사실을 그들의 마음에 두고 \"이 아기가 대체 어떤 사람이 될 것인가?\" 하고 말하였다. 주님의 보살피는 손길이 그 아기와 함께 하시는 것이 분명했기 때문이다.",
    Chn:"凡听见的人都将这事放在心里，说：「这个孩子将来怎么样呢？因为有主与他同在。」",
    Eng:"Everyone who heard this wondered about it, asking, \"What then is this child going to be?\" For the Lord's hand was with him.",
    Ind:"Dan semua orang, yang mendengarnya, merenungkannya dan berkata: \"Menjadi apakah anak ini nanti?\" Sebab tangan Tuhan menyertai dia."
  },
  {Bible:"Luke", Chapter:1, Verse:67, Page:1,
    Kor:"<사가랴의 예언> ○요한의 아버지 사가랴가 성령으로 충만하여, 이렇게 예언하였다.",
    Chn:"他父亲撒迦利亚被圣灵充满了，就预言说：",
    Eng:"His father Zechariah was filled with the Holy Spirit and prophesied:",
    Ind:"Dan Zakharia, ayahnya, penuh dengan Roh Kudus, lalu bernubuat, katanya:"
  },
  {Bible:"Luke", Chapter:1, Verse:68, Page:1,
    Kor:"\"주 이스라엘의 하나님은 찬양받으실 분이시다. 그는 자기 백성을 돌보아 속량하시고,",
    Chn:"主—以色列的　神是应当称颂的！ 因他眷顾他的百姓，为他们施行救赎，",
    Eng:"\"Praise be to the Lord, the God of Israel, because he has come and has redeemed his people.",
    Ind:"\"Terpujilah Tuhan, Allah Israel, sebab Ia melawat umat-Nya dan membawa kelepasan baginya,"
  },
  {Bible:"Luke", Chapter:1, Verse:69, Page:1,
    Kor:"우리를 위하여 f능력 있는 구원자를 자기의 종 다윗의 집에 일으키셨다. (f 그, '구원의 뿔')",
    Chn:"在他仆人大卫家中， 为我们兴起了拯救的角，",
    Eng:"He has raised up a horn of salvation for us in the house of his servant David",
    Ind:"Ia menumbuhkan sebuah tanduk keselamatan bagi kita di dalam keturunan Daud, hamba-Nya itu,"
  },
  {Bible:"Luke", Chapter:1, Verse:70, Page:1,
    Kor:"예로부터 자기의 거룩한 예언자들의 입으로 주님께서 말씀하신 대로",
    Chn:"正如主借着从创世以来圣先知的口所说的话，",
    Eng:"(as he said through his holy prophets of long ago),",
    Ind:"--seperti yang telah difirmankan-Nya sejak purbakala oleh mulut nabi-nabi-Nya yang kudus--"
  },
  {Bible:"Luke", Chapter:1, Verse:71, Page:1,
    Kor:"우리를 원수들에게서 구원하시고, 우리를 미워하는 모든 사람들의 손에서 건져내셨다.",
    Chn:"拯救我们脱离仇敌 和一切恨我们之人的手，",
    Eng:"salvation from our enemies and from the hand of all who hate us--",
    Ind:"untuk melepaskan kita dari musuh-musuh kita dan dari tangan semua orang yang membenci kita,"
  },
  {Bible:"Luke", Chapter:1, Verse:72, Page:1,
    Kor:"주님께서 우리 조상에게 자비를 베푸시고, 자기의 거룩한 언약을 기억하셨다.",
    Chn:"向我们列祖施怜悯， 记念他的圣约—",
    Eng:"to show mercy to our fathers and to remember his holy covenant,",
    Ind:"untuk menunjukkan rahmat-Nya kepada nenek moyang kita dan mengingat akan perjanjian-Nya yang kudus,"
  },
  {Bible:"Luke", Chapter:1, Verse:73, Page:1,
    Kor:"이것은 주님께서 우리에게 주시려고 우리 조상 아브라함에게 하신 맹세이니,",
    Chn:"就是他对我们祖宗亚伯拉罕所起的誓—",
    Eng:"the oath he swore to our father Abraham:",
    Ind:"yaitu sumpah yang diucapkan-Nya kepada Abraham, bapa leluhur kita, bahwa Ia mengaruniai kita,"
  },
  {Bible:"Luke", Chapter:1, Verse:74, Page:1,
    Kor:"우리를 원수들의 손에서 건져주셔서 두려움이 없이 주님을 섬기게 하시고,",
    Chn:"叫我们既从仇敌手中被救出来，",
    Eng:"to rescue us from the hand of our enemies, and to enable us to serve him without fear",
    Ind:"supaya kita, terlepas dari tangan musuh, dapat beribadah kepada-Nya tanpa takut,"
  },
  {Bible:"Luke", Chapter:1, Verse:75, Page:1,
    Kor:"우리가 평생 동안 주님 앞에서 거룩하고 의롭게 살아가게 하셨다.",
    Chn:"就可以终身在他面前， 坦然无惧地用圣洁、公义事奉他。",
    Eng:"in holiness and righteousness before him all our days.",
    Ind:"dalam kekudusan dan kebenaran di hadapan-Nya seumur hidup kita."
  },
  {Bible:"Luke", Chapter:1, Verse:76, Page:1,
    Kor:"아가야, 너는 더없이 높으신 분의 예언자라 불릴 것이니, 주님보다 앞서 가서 그의 길을 예비하고,",
    Chn:"孩子啊！你要称为至高者的先知； 因为你要行在主的前面， 预备他的道路，",
    Eng:"And you, my child, will be called a prophet of the Most High; for you will go on before the Lord to prepare the way for him,",
    Ind:"Dan engkau, hai anakku, akan disebut nabi Allah Yang Mahatinggi; karena engkau akan berjalan mendahului Tuhan untuk mempersiapkan jalan bagi-Nya,"
  },
  {Bible:"Luke", Chapter:1, Verse:77, Page:1,
    Kor:"죄 사함을 받아서 구원을 얻는 지식을 그의 백성에게 가르쳐 줄 것이다.",
    Chn:"叫他的百姓因罪得赦， 就知道救恩。",
    Eng:"to give his people the knowledge of salvation through the forgiveness of their sins,",
    Ind:"untuk memberikan kepada umat-Nya pengertian akan keselamatan yang berdasarkan pengampunan dosa-dosa mereka,"
  },
  {Bible:"Luke", Chapter:1, Verse:78, Page:1,
    Kor:"이것은 우리 하나님의 자비로운 심정에서 오는 것이다. 그는 해를 하늘 높이 뜨게 하셔서,",
    Chn:"因我们　神怜悯的心肠， 叫清晨的日光从高天临到我们，",
    Eng:"because of the tender mercy of our God, by which the rising sun will come to us from heaven",
    Ind:"oleh rahmat dan belas kasihan dari Allah kita, dengan mana Ia akan melawat kita, Surya pagi dari tempat yang tinggi,"
  },
  {Bible:"Luke", Chapter:1, Verse:79, Page:1,
    Kor:"어둠 속과 죽음의 그늘 아래에 앉아 있는 사람들에게 빛을 비추게 하시고, 우리의 발을 평화의 길로 인도하실 것이다.\"",
    Chn:"要照亮坐在黑暗中死荫里的人， 把我们的脚引到平安的路上。",
    Eng:"to shine on those living in darkness and in the shadow of death, to guide our feet into the path of peace.\"",
    Ind:"untuk menyinari mereka yang diam dalam kegelapan dan dalam naungan maut untuk mengarahkan kaki kita kepada jalan damai sejahtera.\""
  },
  {Bible:"Luke", Chapter:1, Verse:80, Page:1,
    Kor:"○아기는 자라서, 심령이 굳세어졌다. 그는 이스라엘 백성 앞에 나타나는 날까지 광야에서 살았다.",
    Chn:"那孩子渐渐长大，心灵强健，住在旷野，直到他显明在以色列人面前的日子。",
    Eng:"And the child grew and became strong in spirit; and he lived in the desert until he appeared publicly to Israel.",
    Ind:"Adapun anak itu bertambah besar dan makin kuat rohnya. Dan ia tinggal di padang gurun sampai kepada hari ia harus menampakkan diri kepada Israel."
  },
]);
