// 누가복음 22장 · Luke 22
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Luke",22,71);
BibleDB.add([
  {Bible:"Luke", Chapter:22, Verse:1, Page:1,
    Kor:"<예수를 죽일 음모(마 26:1-5, 14-16; 막 14:1-2, 10-11; 요 11:45-53)> a유월절이라고 하는 b무교절이 다가왔다.(a 출 12:13, 21-28을 볼 것 b 출 12:15-20을 볼 것)",
    Chn:"除酵节（又名逾越节）近了。",
    Eng:"Now the Feast of Unleavened Bread, called the Passover, was approaching,",
    Ind:"Hari raya Roti Tidak Beragi, yang disebut Paskah, sudah dekat."
  },
  {Bible:"Luke", Chapter:22, Verse:2, Page:1,
    Kor:"그런데 대제사장들과 율법학자들은 예수를 없애버릴 방책을 찾고 있었다. 그들은 백성을 두려워하였다.",
    Chn:"祭司长和文士想法子怎么才能杀害耶稣，是因他们惧怕百姓。",
    Eng:"and the chief priests and the teachers of the law were looking for some way to get rid of Jesus, for they were afraid of the people.",
    Ind:"Imam-imam kepala dan ahli-ahli Taurat mencari jalan, bagaimana mereka dapat membunuh Yesus, sebab mereka takut kepada orang banyak."
  },
  {Bible:"Luke", Chapter:22, Verse:3, Page:1,
    Kor:"열둘 가운데 하나인 가룟이라는 유다에게 사탄이 들어갔다.",
    Chn:"这时，撒但入了那称为加略人犹大的心；他本是十二门徒里的一个。",
    Eng:"Then Satan entered Judas, called Iscariot, one of the Twelve.",
    Ind:"Maka masuklah Iblis ke dalam Yudas, yang bernama Iskariot, seorang dari kedua belas murid itu."
  },
  {Bible:"Luke", Chapter:22, Verse:4, Page:1,
    Kor:"유다는 떠나가서 대제사장들과 성전 경비대장들과 더불어 어떻게 예수를 그들에게 넘겨줄지를 의논하였다.",
    Chn:"他去和祭司长并守殿官商量，怎么可以把耶稣交给他们。",
    Eng:"And Judas went to the chief priests and the officers of the temple guard and discussed with them how he might betray Jesus.",
    Ind:"Lalu pergilah Yudas kepada imam-imam kepala dan kepala-kepala pengawal Bait Allah dan berunding dengan mereka, bagaimana ia dapat menyerahkan Yesus kepada mereka."
  },
  {Bible:"Luke", Chapter:22, Verse:5, Page:1,
    Kor:"그래서 그들은 기뻐하여, 그에게 돈을 주겠다고 약조하였다.",
    Chn:"他们欢喜，就约定给他银子。",
    Eng:"They were delighted and agreed to give him money.",
    Ind:"Mereka sangat gembira dan bermupakat untuk memberikan sejumlah uang kepadanya."
  },
  {Bible:"Luke", Chapter:22, Verse:6, Page:1,
    Kor:"유다는 동의하고, 무리가 없을 때에 예수를 그들에게 넘겨주려고, 기회를 노리고 있었다.",
    Chn:"他应允了，就找机会，要趁众人不在跟前的时候把耶稣交给他们。",
    Eng:"He consented, and watched for an opportunity to hand Jesus over to them when no crowd was present.",
    Ind:"Ia menyetujuinya, dan mulai dari waktu itu ia mencari kesempatan yang baik untuk menyerahkan Yesus kepada mereka tanpa setahu orang banyak."
  },
  {Bible:"Luke", Chapter:22, Verse:7, Page:1,
    Kor:"<유월절 준비(마 26:17-25; 막 14:12-21; 요 13:21-30)> ○a유월절 양을 잡아야 하는 무교절 날이 왔다.(a 출 12:13, 21-28을 볼 것)",
    Chn:"除酵节，须宰逾越羊羔的那一天到了。",
    Eng:"Then came the day of Unleavened Bread on which the Passover lamb had to be sacrificed.",
    Ind:"Maka tibalah hari raya Roti Tidak Beragi, yaitu hari di mana orang harus menyembelih domba Paskah."
  },
  {Bible:"Luke", Chapter:22, Verse:8, Page:1,
    Kor:"예수께서 베드로와 요한을 보내시며 말씀하셨다. \"가서, 우리가 먹을 수 있게 a유월절을 준비하여라.\"(a 출 12:13, 21-28을 볼 것)",
    Chn:"耶稣打发彼得、约翰，说：「你们去为我们预备逾越节的筵席，好叫我们吃。」",
    Eng:"Jesus sent Peter and John, saying, \"Go and make preparations for us to eat the Passover.\"",
    Ind:"Lalu Yesus menyuruh Petrus dan Yohanes, kata-Nya: \"Pergilah, persiapkanlah perjamuan Paskah bagi kita supaya kita makan.\""
  },
  {Bible:"Luke", Chapter:22, Verse:9, Page:1,
    Kor:"그들이 예수께 말하였다. \"어디에다 준비하기를 바라십니까?\"",
    Chn:"他们问他说：「要我们在哪里预备？」",
    Eng:"\"Where do you want us to prepare for it?\" they asked.",
    Ind:"Kata mereka kepada-Nya: \"Di manakah Engkau kehendaki kami mempersiapkannya?\""
  },
  {Bible:"Luke", Chapter:22, Verse:10, Page:1,
    Kor:"예수께서 대답하셨다. \"너희가 성 안으로 들어가면, 물 한 동이를 메고 오는 사람을 만날 것이니, 그가 들어가는 집으로 따라가거라.",
    Chn:"耶稣说：「你们进了城，必有人拿着一瓶水迎面而来，你们就跟着他，到他所进的房子里去，",
    Eng:"He replied, \"As you enter the city, a man carrying a jar of water will meet you. Follow him to the house that he enters,",
    Ind:"Jawab-Nya: \"Apabila kamu masuk ke dalam kota, kamu akan bertemu dengan seorang yang membawa kendi berisi air. Ikutilah dia ke dalam rumah yang dimasukinya,"
  },
  {Bible:"Luke", Chapter:22, Verse:11, Page:1,
    Kor:"그리고 그 집주인에게 말하기를 '선생님께서 당신에게 말씀하시기를, 내가 내 제자들과 함께 a유월절 음식을 먹을 그 방이 어디에 있느냐고 하십니다' 하여라.(a 출 12:13, 21-28을 볼 것)",
    Chn:"对那家的主人说：『夫子说：客房在哪里？我与门徒好在那里吃逾越节的筵席。』",
    Eng:"and say to the owner of the house, 'The Teacher asks: Where is the guest room, where I may eat the Passover with my disciples?'",
    Ind:"dan katakanlah kepada tuan rumah itu: Guru bertanya kepadamu: di manakah ruangan tempat Aku bersama-sama dengan murid-murid-Ku akan makan Paskah?"
  },
  {Bible:"Luke", Chapter:22, Verse:12, Page:1,
    Kor:"그러면 그 사람은 자리를 깔아 놓은 큰 다락방을 너희에게 보여 줄 것이니, 너희는 거기에다 준비를 하여라.\"",
    Chn:"他必指给你们摆设整齐的一间大楼，你们就在那里预备。」",
    Eng:"He will show you a large upper room, all furnished. Make preparations there.\"",
    Ind:"Lalu orang itu akan menunjukkan kepadamu sebuah ruangan atas yang besar yang sudah lengkap, di situlah kamu harus mempersiapkannya.\""
  },
  {Bible:"Luke", Chapter:22, Verse:13, Page:1,
    Kor:"그들이 가서 보니, 예수께서 말씀하신 그대로였다. 그리하여 그들은 a유월절을 준비하였다.(a 출 12:13, 21-28을 볼 것)",
    Chn:"他们去了，所遇见的正如耶稣所说的；他们就预备了逾越节的筵席。",
    Eng:"They left and found things just as Jesus had told them. So they prepared the Passover.",
    Ind:"Maka berangkatlah mereka dan mereka mendapati semua seperti yang dikatakan Yesus kepada mereka. Lalu mereka mempersiapkan Paskah."
  },
  {Bible:"Luke", Chapter:22, Verse:14, Page:1,
    Kor:"<마지막 만찬(마 26:26-30; 막 14:22-26; 고전 11:23-25)> ○시간이 되어서, 예수께서 자리에 앉으시니, 사도들도 그와 함께 앉았다.",
    Chn:"时候到了，耶稣坐席，使徒也和他同坐。",
    Eng:"When the hour came, Jesus and his apostles reclined at the table.",
    Ind:"Ketika tiba saatnya, Yesus duduk makan bersama-sama dengan rasul-rasul-Nya."
  },
  {Bible:"Luke", Chapter:22, Verse:15, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"내가 고난을 당하기 전에, 너희와 함께 이 a유월절 음식을 먹기를 참으로 간절히 바랐다.(a 출 12:13, 21-28을 볼 것)",
    Chn:"耶稣对他们说：「我很愿意在受害以先和你们吃这逾越节的筵席。",
    Eng:"And he said to them, \"I have eagerly desired to eat this Passover with you before I suffer.",
    Ind:"Kata-Nya kepada mereka: \"Aku sangat rindu makan Paskah ini bersama-sama dengan kamu, sebelum Aku menderita."
  },
  {Bible:"Luke", Chapter:22, Verse:16, Page:1,
    Kor:"내가 너희에게 말한다. a유월절이 하나님의 나라에서 이루어질 때까지, 나는 다시는 a유월절 음식을 먹지 않을 것이다.\"(a 출 12:13, 21-28을 볼 것)",
    Chn:"我告诉你们，我不再吃这筵席，直到成就在　神的国里。」",
    Eng:"For I tell you, I will not eat it again until it finds fulfillment in the kingdom of God.\"",
    Ind:"Sebab Aku berkata kepadamu: Aku tidak akan memakannya lagi sampai ia beroleh kegenapannya dalam Kerajaan Allah.\""
  },
  {Bible:"Luke", Chapter:22, Verse:17, Page:1,
    Kor:"그리고 잔을 받아서 감사를 드리신 다음에 말씀하셨다. \"이것을 받아서 함께 나누어 마셔라.",
    Chn:"耶稣接过杯来，祝谢了，说：「你们拿这个，大家分着喝。",
    Eng:"After taking the cup, he gave thanks and said, \"Take this and divide it among you.",
    Ind:"Kemudian Ia mengambil sebuah cawan, mengucap syukur, lalu berkata: \"Ambillah ini dan bagikanlah di antara kamu."
  },
  {Bible:"Luke", Chapter:22, Verse:18, Page:1,
    Kor:"내가 너희에게 말한다. 나는 이제부터 하나님의 나라가 올 때까지, 포도나무 열매에서 난 것을 절대로 마시지 않을 것이다.\"",
    Chn:"我告诉你们，从今以后，我不再喝这葡萄汁，直等　神的国来到。」",
    Eng:"For I tell you I will not drink again of the fruit of the vine until the kingdom of God comes.\"",
    Ind:"Sebab Aku berkata kepada kamu: mulai dari sekarang ini Aku tidak akan minum lagi hasil pokok anggur sampai Kerajaan Allah telah datang.\""
  },
  {Bible:"Luke", Chapter:22, Verse:19, Page:1,
    Kor:"예수께서는 또 빵을 들어서 감사를 드리신 다음에, 떼어서 그들에게 주시고 말씀하셨다. \"이것은 c너희를 위하여 주는 내 몸이다. d이것을 행하여 나를 기억하여라.\"(c 다른 고대 사본들에는 '너희를 위하여 주는'이 없음 d 다른 고대 사본들에는 여기에서부터 20절까지 전부, 또는 부분적으로 없음)",
    Chn:"又拿起饼来，祝谢了，就擘开，递给他们，说：「这是我的身体，为你们舍的，你们也应当如此行，为的是记念我。」",
    Eng:"And he took bread, gave thanks and broke it, and gave it to them, saying, \"This is my body given for you; do this in remembrance of me.\"",
    Ind:"Lalu Ia mengambil roti, mengucap syukur, memecah-mecahkannya dan memberikannya kepada mereka, kata-Nya: \"Inilah tubuh-Ku yang diserahkan bagi kamu; perbuatlah ini menjadi peringatan akan Aku.\""
  },
  {Bible:"Luke", Chapter:22, Verse:20, Page:1,
    Kor:"그리고 저녁을 먹은 뒤에, 잔을 그와 같이 하시고서 말씀하셨다. \"이 잔은 너희를 위하여 흘리는 내 피로 세우는 새 언약이다.",
    Chn:"饭后也照样拿起杯来，说：「这杯是用我血所立的新约，是为你们流出来的。",
    Eng:"In the same way, after the supper he took the cup, saying, \"This cup is the new covenant in my blood, which is poured out for you.",
    Ind:"Demikian juga dibuat-Nya dengan cawan sesudah makan; Ia berkata: \"Cawan ini adalah perjanjian baru oleh darah-Ku, yang ditumpahkan bagi kamu."
  },
  {Bible:"Luke", Chapter:22, Verse:21, Page:1,
    Kor:"그러나 보아라, 나를 넘겨줄 사람의 손이 나와 함께 상 위에 있다.",
    Chn:"看哪，那卖我之人的手与我一同在桌子上。",
    Eng:"But the hand of him who is going to betray me is with mine on the table.",
    Ind:"Tetapi, lihat, tangan orang yang menyerahkan Aku, ada bersama dengan Aku di meja ini."
  },
  {Bible:"Luke", Chapter:22, Verse:22, Page:1,
    Kor:"인자는 하나님께서 정하신 대로 가지만, 인자를 넘겨주는 그 사람에게는 화가 있다.\"",
    Chn:"人子固然要照所预定的去世，但卖人子的人有祸了！」",
    Eng:"The Son of Man will go as it has been decreed, but woe to that man who betrays him.\"",
    Ind:"Sebab Anak Manusia memang akan pergi seperti yang telah ditetapkan, akan tetapi, celakalah orang yang olehnya Ia diserahkan!\""
  },
  {Bible:"Luke", Chapter:22, Verse:23, Page:1,
    Kor:"그들은, 자기들 가운데 이런 일을 할 사람이 누구일까 하고, 자기들끼리 서로 물었다.",
    Chn:"他们就彼此对问，是哪一个要做这事。",
    Eng:"They began to question among themselves which of them it might be who would do this.",
    Ind:"Lalu mulailah mereka mempersoalkan, siapa di antara mereka yang akan berbuat demikian."
  },
  {Bible:"Luke", Chapter:22, Verse:24, Page:1,
    Kor:"<참으로 높은 사람> ○제자들 가운데서 누구를 가장 큰 사람으로 칠 것이냐는 물음을 놓고, 그들 사이에 말다툼이 벌어졌다.",
    Chn:"门徒起了争论，他们中间哪一个可算为大。",
    Eng:"Also a dispute arose among them as to which of them was considered to be greatest.",
    Ind:"Terjadilah juga pertengkaran di antara murid-murid Yesus, siapakah yang dapat dianggap terbesar di antara mereka."
  },
  {Bible:"Luke", Chapter:22, Verse:25, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"뭇 민족들의 왕들은 백성들 위에 군림한다. 그리고 백성들에게 권세를 부리는 자들은 은인으로 행세한다.",
    Chn:"耶稣说：「外邦人有君王为主治理他们，那掌权管他们的称为恩主。",
    Eng:"Jesus said to them, \"The kings of the Gentiles lord it over them; and those who exercise authority over them call themselves Benefactors.",
    Ind:"Yesus berkata kepada mereka: \"Raja-raja bangsa-bangsa memerintah rakyat mereka dan orang-orang yang menjalankan kuasa atas mereka disebut pelindung-pelindung."
  },
  {Bible:"Luke", Chapter:22, Verse:26, Page:1,
    Kor:"그러나 너희는 그렇지 않다. 너희 가운데서 가장 큰 사람은 가장 어린 사람과 같이 되어야 하고, 또 다스리는 사람은 섬기는 사람과 같이 되어야 한다.",
    Chn:"但你们不可这样；你们里头为大的，倒要像年幼的，为首领的，倒要像服事人的。",
    Eng:"But you are not to be like that. Instead, the greatest among you should be like the youngest, and the one who rules like the one who serves.",
    Ind:"Tetapi kamu tidaklah demikian, melainkan yang terbesar di antara kamu hendaklah menjadi sebagai yang paling muda dan pemimpin sebagai pelayan."
  },
  {Bible:"Luke", Chapter:22, Verse:27, Page:1,
    Kor:"누가 더 높으냐? 밥상에 앉은 사람이냐, 시중드는 사람이냐? 밥상에 앉은 사람이 아니냐? 그러나 나는 섬기는 사람으로 너희 가운데 있다.",
    Chn:"是谁为大？是坐席的呢？是服事人的呢？不是坐席的大吗？然而，我在你们中间如同服事人的。",
    Eng:"For who is greater, the one who is at the table or the one who serves? Is it not the one who is at the table? But I am among you as one who serves.",
    Ind:"Sebab siapakah yang lebih besar: yang duduk makan, atau yang melayani? Bukankah dia yang duduk makan? Tetapi Aku ada di tengah-tengah kamu sebagai pelayan."
  },
  {Bible:"Luke", Chapter:22, Verse:28, Page:1,
    Kor:"○너희는 내가 시련을 겪는 동안에 나와 함께 한 사람들이다.",
    Chn:"我在磨炼之中，常和我同在的就是你们。",
    Eng:"You are those who have stood by me in my trials.",
    Ind:"Kamulah yang tetap tinggal bersama-sama dengan Aku dalam segala pencobaan yang Aku alami."
  },
  {Bible:"Luke", Chapter:22, Verse:29, Page:1,
    Kor:"내 아버지께서 내게 왕권을 주신 것과 같이, 나도 너희에게 왕권을 준다.",
    Chn:"我将国赐给你们，正如我父赐给我一样，",
    Eng:"And I confer on you a kingdom, just as my Father conferred one on me,",
    Ind:"Dan Aku menentukan hak-hak Kerajaan bagi kamu, sama seperti Bapa-Ku menentukannya bagi-Ku,"
  },
  {Bible:"Luke", Chapter:22, Verse:30, Page:1,
    Kor:"그리하여 너희가 내 나라에 들어와 내 밥상에서 먹고 마시게 하고, 옥좌에 앉아서 이스라엘의 열두 지파를 심판하게 하겠다.\"",
    Chn:"叫你们在我国里，坐在我的席上吃喝，并且坐在宝座上，审判以色列十二个支派。」",
    Eng:"so that you may eat and drink at my table in my kingdom and sit on thrones, judging the twelve tribes of Israel.",
    Ind:"bahwa kamu akan makan dan minum semeja dengan Aku di dalam Kerajaan-Ku dan kamu akan duduk di atas takhta untuk menghakimi kedua belas suku Israel."
  },
  {Bible:"Luke", Chapter:22, Verse:31, Page:1,
    Kor:"<베드로의 부인을 예고하시다(마 26:31-35; 막 14:27-31; 요 13:36-38)> ○\"시몬아, 시몬아, 보아라. 사탄이 밀처럼 너희를 e체질하려고 너희를 손아귀에 넣기를 요구하였다.(e 또는 '너희를 체질할 허락을 이미 받았다')",
    Chn:"主又说：「西门！西门！撒但想要得着你们，好筛你们像筛麦子一样；",
    Eng:"\"Simon, Simon, Satan has asked to sift you as wheat.",
    Ind:"Simon, Simon, lihat, Iblis telah menuntut untuk menampi kamu seperti gandum,"
  },
  {Bible:"Luke", Chapter:22, Verse:32, Page:1,
    Kor:"그러나 나는 네 믿음이 꺾이지 않도록, 너를 위하여 기도하였다. 네가 다시 돌아올 때에는, 네 형제를 굳세게 하여라.\"",
    Chn:"但我已经为你祈求，叫你不至于失了信心。你回头以后，要坚固你的弟兄。」",
    Eng:"But I have prayed for you, Simon, that your faith may not fail. And when you have turned back, strengthen your brothers.\"",
    Ind:"tetapi Aku telah berdoa untuk engkau, supaya imanmu jangan gugur. Dan engkau, jikalau engkau sudah insaf, kuatkanlah saudara-saudaramu.\""
  },
  {Bible:"Luke", Chapter:22, Verse:33, Page:1,
    Kor:"베드로가 예수께 말하였다. \"주님, 나는 감옥에도, 죽는 자리에도, 주님과 함께 갈 각오가 되어 있습니다.\"",
    Chn:"彼得说：「主啊，我就是同你下监，同你受死，也是甘心！」",
    Eng:"But he replied, \"Lord, I am ready to go with you to prison and to death.\"",
    Ind:"Jawab Petrus: \"Tuhan, aku bersedia masuk penjara dan mati bersama-sama dengan Engkau!\""
  },
  {Bible:"Luke", Chapter:22, Verse:34, Page:1,
    Kor:"그러나 예수께서 말씀하셨다. \"베드로야, 내가 네게 말한다. 오늘 닭이 울기 전에, 네가 세 번 나를 모른다고 할 것이다.\"",
    Chn:"耶稣说：「彼得，我告诉你，今日鸡还没有叫，你要三次说不认得我。」",
    Eng:"Jesus answered, \"I tell you, Peter, before the rooster crows today, you will deny three times that you know me.\"",
    Ind:"Tetapi Yesus berkata: \"Aku berkata kepadamu, Petrus, hari ini ayam tidak akan berkokok, sebelum engkau tiga kali menyangkal, bahwa engkau mengenal Aku.\""
  },
  {Bible:"Luke", Chapter:22, Verse:35, Page:1,
    Kor:"<돈주머니와 검> ○예수께서 제자들에게 말씀하셨다. \"내가 너희를 돈주머니와 자루와 신발이 없이 내보냈을 때에, 너희에게 부족한 것이 있더냐?\" 그들이 대답하였다. \"없었습니다.\"",
    Chn:"耶稣又对他们说：「我差你们出去的时候，没有钱囊，没有口袋，没有鞋，你们缺少什么没有？」他们说：「没有。」",
    Eng:"Then Jesus asked them, \"When I sent you without purse, bag or sandals, did you lack anything?\" \"Nothing,\" they answered.",
    Ind:"Lalu Ia berkata kepada mereka: \"Ketika Aku mengutus kamu dengan tiada membawa pundi-pundi, bekal dan kasut, adakah kamu kekurangan apa-apa?\""
  },
  {Bible:"Luke", Chapter:22, Verse:36, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"이제는 돈주머니가 있는 사람은 그것을 챙겨라, 또 자루도 그렇게 하여라. 그리고 칼이 없는 사람은, 옷을 팔아서 칼을 사라.",
    Chn:"耶稣说：「但如今有钱囊的可以带着，有口袋的也可以带着，没有刀的要卖衣服买刀。",
    Eng:"He said to them, \"But now if you have a purse, take it, and also a bag; and if you don't have a sword, sell your cloak and buy one.",
    Ind:"Jawab mereka: \"Suatupun tidak.\" Kata-Nya kepada mereka: \"Tetapi sekarang ini, siapa yang mempunyai pundi-pundi, hendaklah ia membawanya, demikian juga yang mempunyai bekal; dan siapa yang tidak mempunyainya hendaklah ia menjual jubahnya dan membeli pedang."
  },
  {Bible:"Luke", Chapter:22, Verse:37, Page:1,
    Kor:"내가 너희에게 말한다. f'그는 무법자들과 한 패로 몰렸다'고 하는 이 성경 말씀이, 내게서 반드시 이루어져야 한다. 과연, 나에 관하여 기록한 일은 이루어지고 있다.\"(f 사 53:12)",
    Chn:"我告诉你们，经上写着说：『他被列在罪犯之中。』这话必应验在我身上，因为那关系我的事必然成就。」",
    Eng:"It is written: 'And he was numbered with the transgressors'; and I tell you that this must be fulfilled in me. Yes, what is written about me is reaching its fulfillment.\"",
    Ind:"Sebab Aku berkata kepada kamu, bahwa nas Kitab Suci ini harus digenapi pada-Ku: Ia akan terhitung di antara pemberontak-pemberontak. Sebab apa yang tertulis tentang Aku sedang digenapi.\""
  },
  {Bible:"Luke", Chapter:22, Verse:38, Page:1,
    Kor:"제자들이 예수께 말하였다. \"주님, 보십시오. 여기에 칼 두 자루가 있습니다.\" 예수께서 그들에게 말씀하시기를 \"넉넉하다\" 하셨다.",
    Chn:"他们说：「主啊，请看！这里有两把刀。」耶稣说：「够了。」",
    Eng:"The disciples said, \"See, Lord, here are two swords.\" \"That is enough,\" he replied.",
    Ind:"Kata mereka: \"Tuhan, ini dua pedang.\" Jawab-Nya: \"Sudah cukup.\""
  },
  {Bible:"Luke", Chapter:22, Verse:39, Page:1,
    Kor:"<예수께서 기도하시다(마 26:36-46; 막 14:32-42)> ○예수께서 나가시어, 늘 하시던 대로 올리브 산으로 가시니, 제자들도 그를 따라갔다.",
    Chn:"耶稣出来，照常往橄榄山去，门徒也跟随他。",
    Eng:"Jesus went out as usual to the Mount of Olives, and his disciples followed him.",
    Ind:"Lalu pergilah Yesus ke luar kota dan sebagaimana biasa Ia menuju Bukit Zaitun. Murid-murid-Nya juga mengikuti Dia."
  },
  {Bible:"Luke", Chapter:22, Verse:40, Page:1,
    Kor:"그 곳에 이르러서, 예수께서 제자들에게 말씀하시기를 \"시험에 빠지지 않도록 기도하여라\" 하신 뒤에,",
    Chn:"到了那地方，就对他们说：「你们要祷告，免得入了迷惑。」",
    Eng:"On reaching the place, he said to them, \"Pray that you will not fall into temptation.\"",
    Ind:"Setelah tiba di tempat itu Ia berkata kepada mereka: \"Berdoalah supaya kamu jangan jatuh ke dalam pencobaan.\""
  },
  {Bible:"Luke", Chapter:22, Verse:41, Page:1,
    Kor:"그들과 헤어져서, 돌을 던져서 닿을 만한 거리에 가서, 무릎을 꿇고 이렇게 기도하셨다.",
    Chn:"于是离开他们约有扔一块石头那么远，跪下祷告，",
    Eng:"He withdrew about a stone's throw beyond them, knelt down and prayed,",
    Ind:"Kemudian Ia menjauhkan diri dari mereka kira-kira sepelempar batu jaraknya, lalu Ia berlutut dan berdoa, kata-Nya:"
  },
  {Bible:"Luke", Chapter:22, Verse:42, Page:1,
    Kor:"\"아버지, 만일 아버지의 뜻이면, 내게서 이 잔을 거두어 주십시오. 그러나 내 뜻대로 되게 하지 마시고, 아버지의 뜻대로 되게 하여 주십시오.\"",
    Chn:"说：「父啊！你若愿意，就把这杯撤去；然而，不要成就我的意思，只要成就你的意思。」",
    Eng:"\"Father, if you are willing, take this cup from me; yet not my will, but yours be done.\"",
    Ind:"\"Ya Bapa-Ku, jikalau Engkau mau, ambillah cawan ini dari pada-Ku; tetapi bukanlah kehendak-Ku, melainkan kehendak-Mulah yang terjadi.\""
  },
  {Bible:"Luke", Chapter:22, Verse:43, Page:1,
    Kor:"<그 때에 천사가 하늘로부터 그에게 나타나서, 힘을 북돋우어 드렸다.",
    Chn:"有一位天使从天上显现，加添他的力量。",
    Eng:"An angel from heaven appeared to him and strengthened him.",
    Ind:"Maka seorang malaikat dari langit menampakkan diri kepada-Nya untuk memberi kekuatan kepada-Nya."
  },
  {Bible:"Luke", Chapter:22, Verse:44, Page:1,
    Kor:"예수께서 고뇌에 차서, 더욱 간절히 기도하시니, 땀이 핏방울같이 되어서 땅에 떨어졌다.>>",
    Chn:"耶稣极其伤痛，祷告更加恳切，汗珠如大血点滴在地上。",
    Eng:"And being in anguish, he prayed more earnestly, and his sweat was like drops of blood falling to the ground.",
    Ind:"Ia sangat ketakutan dan makin bersungguh-sungguh berdoa. Peluh-Nya menjadi seperti titik-titik darah yang bertetesan ke tanah."
  },
  {Bible:"Luke", Chapter:22, Verse:45, Page:1,
    Kor:"기도를 마치고 일어나, 제자들에게로 와서 보시니, 그들이 슬픔에 지쳐서 잠들어 있었다.",
    Chn:"祷告完了，就起来，到门徒那里，见他们因为忧愁都睡着了，",
    Eng:"When he rose from prayer and went back to the disciples, he found them asleep, exhausted from sorrow.",
    Ind:"Lalu Ia bangkit dari doa-Nya dan kembali kepada murid-murid-Nya, tetapi Ia mendapati mereka sedang tidur karena dukacita."
  },
  {Bible:"Luke", Chapter:22, Verse:46, Page:1,
    Kor:"그래서 그들에게 말씀하셨다. \"왜들 자고 있느냐? 시험에 빠지지 않도록, 일어나서 기도하여라.\"",
    Chn:"就对他们说：「你们为什么睡觉呢？起来祷告，免得入了迷惑！」",
    Eng:"\"Why are you sleeping?\" he asked them. \"Get up and pray so that you will not fall into temptation.\"",
    Ind:"Kata-Nya kepada mereka: \"Mengapa kamu tidur? Bangunlah dan berdoalah, supaya kamu jangan jatuh ke dalam pencobaan.\""
  },
  {Bible:"Luke", Chapter:22, Verse:47, Page:1,
    Kor:"<예수께서 잡히시다(마 26:47-56; 막 14:43-50; 요 18:3-11)> ○예수께서 아직 말씀하시고 계실 때에, 한 무리가 나타났다. 열둘 가운데 하나인 유다라는 사람이 그들의 앞장을 서서 왔다. 그는 예수께 입을 맞추려고 가까이 왔다.",
    Chn:"说话之间，来了许多人。那十二个门徒里名叫犹大的，走在前头，就近耶稣，要与他亲嘴。",
    Eng:"While he was still speaking a crowd came up, and the man who was called Judas, one of the Twelve, was leading them. He approached Jesus to kiss him,",
    Ind:"Waktu Yesus masih berbicara datanglah serombongan orang, sedang murid-Nya yang bernama Yudas, seorang dari kedua belas murid itu, berjalan di depan mereka. Yudas mendekati Yesus untuk mencium-Nya."
  },
  {Bible:"Luke", Chapter:22, Verse:48, Page:1,
    Kor:"예수께서 그에게 말씀하셨다. \"유다야, 너는 입맞춤으로 인자를 넘겨주려고 하느냐?\"",
    Chn:"耶稣对他说：「犹大！你用亲嘴的暗号卖人子吗？」",
    Eng:"but Jesus asked him, \"Judas, are you betraying the Son of Man with a kiss?\"",
    Ind:"Maka kata Yesus kepadanya: \"Hai Yudas, engkau menyerahkan Anak Manusia dengan ciuman?\""
  },
  {Bible:"Luke", Chapter:22, Verse:49, Page:1,
    Kor:"예수의 둘레에 있는 사람들이 사태를 보고서 말하였다. \"주님, 우리가 칼을 쓸까요?\"",
    Chn:"左右的人见光景不好，就说：「主啊！我们拿刀砍可以不可以？」",
    Eng:"When Jesus' followers saw what was going to happen, they said, \"Lord, should we strike with our swords?\"",
    Ind:"Ketika mereka, yang bersama-sama dengan Yesus, melihat apa yang akan terjadi, berkatalah mereka: \"Tuhan, mestikah kami menyerang mereka dengan pedang?\""
  },
  {Bible:"Luke", Chapter:22, Verse:50, Page:1,
    Kor:"그 가운데 한 사람이 대제사장의 종의 오른쪽 귀를 쳐서 떨어뜨렸다.",
    Chn:"内中有一个人把大祭司的仆人砍了一刀，削掉了他的右耳。",
    Eng:"And one of them struck the servant of the high priest, cutting off his right ear.",
    Ind:"Dan seorang dari mereka menyerang hamba Imam Besar sehingga putus telinga kanannya."
  },
  {Bible:"Luke", Chapter:22, Verse:51, Page:1,
    Kor:"예수께서 말씀하시기를 \"그만해 두어라!\" 하시고, 그 사람의 귀를 만져서 고쳐 주셨다.",
    Chn:"耶稣说：「到了这个地步，由他们吧！」就摸那人的耳朵，把他治好了。",
    Eng:"But Jesus answered, \"No more of this!\" And he touched the man's ear and healed him.",
    Ind:"Tetapi Yesus berkata: \"Sudahlah itu.\" Lalu Ia menjamah telinga orang itu dan menyembuhkannya."
  },
  {Bible:"Luke", Chapter:22, Verse:52, Page:1,
    Kor:"그런 다음에, 자기를 잡으러 온 대제사장들과 성전 경비대장들과 장로들에게 말씀하셨다. \"너희가 강도를 잡듯이 칼과 몽둥이를 들고 나왔느냐?",
    Chn:"耶稣对那些来拿他的祭司长和守殿官并长老说：「你们带着刀棒出来拿我，如同拿强盗吗？",
    Eng:"Then Jesus said to the chief priests, the officers of the temple guard, and the elders, who had come for him, \"Am I leading a rebellion, that you have come with swords and clubs?",
    Ind:"Maka Yesus berkata kepada imam-imam kepala dan kepala-kepala pengawal Bait Allah serta tua-tua yang datang untuk menangkap Dia, kata-Nya: \"Sangkamu Aku ini penyamun, maka kamu datang lengkap dengan pedang dan pentung?"
  },
  {Bible:"Luke", Chapter:22, Verse:53, Page:1,
    Kor:"내가 날마다 성전에서 너희와 함께 있었으나, 너희는 내게 손을 대지 않았다. 그러나 지금은 너희의 때요, 어둠의 권세가 판을 치는 때다.\"",
    Chn:"我天天同你们在殿里，你们不下手拿我。现在却是你们的时候，黑暗掌权了。」",
    Eng:"Every day I was with you in the temple courts, and you did not lay a hand on me. But this is your hour--when darkness reigns.\"",
    Ind:"Padahal tiap-tiap hari Aku ada di tengah-tengah kamu di dalam Bait Allah, dan kamu tidak menangkap Aku. Tetapi inilah saat kamu, dan inilah kuasa kegelapan itu.\""
  },
  {Bible:"Luke", Chapter:22, Verse:54, Page:1,
    Kor:"<베드로가 예수를 부인하다(마 26:57-58, 69-75; 막 14:53-54, 66-72; 요 18:12-18, 25-27)> ○그들은 예수를 붙잡아서, 끌고 대제사장의 집으로 데리고 갔다. 그런데 베드로는 멀찍이 떨어져서 뒤따라갔다.",
    Chn:"他们拿住耶稣，把他带到大祭司的宅里。彼得远远地跟着。",
    Eng:"Then seizing him, they led him away and took him into the house of the high priest. Peter followed at a distance.",
    Ind:"Lalu Yesus ditangkap dan dibawa dari tempat itu. Ia digiring ke rumah Imam Besar. Dan Petrus mengikut dari jauh."
  },
  {Bible:"Luke", Chapter:22, Verse:55, Page:1,
    Kor:"사람들이 뜰 한가운데 불을 피워놓고 둘러앉아 있는데, 베드로도 그들 가운데 끼여 앉아 있었다.",
    Chn:"他们在院子里生了火，一同坐着；彼得也坐在他们中间。",
    Eng:"But when they had kindled a fire in the middle of the courtyard and had sat down together, Peter sat down with them.",
    Ind:"Di tengah-tengah halaman rumah itu orang memasang api dan mereka duduk mengelilinginya. Petrus juga duduk di tengah-tengah mereka."
  },
  {Bible:"Luke", Chapter:22, Verse:56, Page:1,
    Kor:"그 때에 한 하녀가 베드로가 불빛을 안고 앉아 있는 것을 보고, 그를 빤히 노려보고 말하였다. \"이 사람도 그와 함께 있었어요.\"",
    Chn:"有一个使女看见彼得坐在火光里，就定睛看他，说：「这个人素来也是同那人一伙的。」",
    Eng:"A servant girl saw him seated there in the firelight. She looked closely at him and said, \"This man was with him.\"",
    Ind:"Seorang hamba perempuan melihat dia duduk dekat api; ia mengamat-amatinya lalu berkata: \"Juga orang ini bersama-sama dengan Dia.\""
  },
  {Bible:"Luke", Chapter:22, Verse:57, Page:1,
    Kor:"그러나 베드로는 그것을 부인하여 이렇게 말하였다. \"g여보시오, 나는 그를 모르오.\"(g 그, '여자여')",
    Chn:"彼得却不承认，说：「女子，我不认得他。」",
    Eng:"But he denied it. \"Woman, I don't know him,\" he said.",
    Ind:"Tetapi Petrus menyangkal, katanya: \"Bukan, aku tidak kenal Dia!\""
  },
  {Bible:"Luke", Chapter:22, Verse:58, Page:1,
    Kor:"조금 뒤에 다른 사람이 베드로를 보고서 말했다. \"당신도 그들과 한패요.\" 그러나 베드로는 \"이 사람아, 나는 아니란 말이오\" 하고 말하였다.",
    Chn:"过了不多的时候，又有一个人看见他，说：「你也是他们一党的。」彼得说：「你这个人！我不是。」",
    Eng:"A little later someone else saw him and said, \"You also are one of them.\" \"Man, I am not!\" Peter replied.",
    Ind:"Tidak berapa lama kemudian seorang lain melihat dia lalu berkata: \"Engkau juga seorang dari mereka!\" Tetapi Petrus berkata: \"Bukan, aku tidak!\""
  },
  {Bible:"Luke", Chapter:22, Verse:59, Page:1,
    Kor:"그리고 한 시간쯤 지났을 때에, 또 다른 사람이 강경하게 주장하였다. \"틀림없이, 이 사람도 그와 함께 있었소. 이 사람은 갈릴리 사람이니까요.\"",
    Chn:"约过了一小时，又有一个人极力地说：「他实在是同那人一伙的，因为他也是加利利人。」",
    Eng:"About an hour later another asserted, \"Certainly this fellow was with him, for he is a Galilean.\"",
    Ind:"Dan kira-kira sejam kemudian seorang lain berkata dengan tegas: \"Sungguh, orang ini juga bersama-sama dengan Dia, sebab ia juga orang Galilea.\""
  },
  {Bible:"Luke", Chapter:22, Verse:60, Page:1,
    Kor:"그러나 베드로는 이렇게 말하였다. \"h여보시오, 나는 당신이 무슨 소리를 하는지 모르겠소.\" 베드로가 아직 말을 채 끝내기도 전에, 곧 닭이 울었다.(h 그, '사람아' 또는 '남자야')",
    Chn:"彼得说：「你这个人！我不晓得你说的是什么！」正说话之间，鸡就叫了。",
    Eng:"Peter replied, \"Man, I don't know what you're talking about!\" Just as he was speaking, the rooster crowed.",
    Ind:"Tetapi Petrus berkata: \"Bukan, aku tidak tahu apa yang engkau katakan.\" Seketika itu juga, sementara ia berkata, berkokoklah ayam."
  },
  {Bible:"Luke", Chapter:22, Verse:61, Page:1,
    Kor:"주님께서 돌아서서 베드로를 똑바로 보셨다. 베드로는, 주님께서 자기에게 \"오늘 닭이 울기 전에, 네가 세 번 나를 모른다고 할 것이다\" 하신 그 말씀이 생각났다.",
    Chn:"主转过身来看彼得，彼得便想起主对他所说的话：「今日鸡叫以先，你要三次不认我。」",
    Eng:"The Lord turned and looked straight at Peter. Then Peter remembered the word the Lord had spoken to him: \"Before the rooster crows today, you will disown me three times.\"",
    Ind:"Lalu berpalinglah Tuhan memandang Petrus. Maka teringatlah Petrus bahwa Tuhan telah berkata kepadanya: \"Sebelum ayam berkokok pada hari ini, engkau telah tiga kali menyangkal Aku.\""
  },
  {Bible:"Luke", Chapter:22, Verse:62, Page:1,
    Kor:"그리하여 그는 바깥으로 나가서 비통하게 울었다.",
    Chn:"他就出去痛哭。",
    Eng:"And he went outside and wept bitterly.",
    Ind:"Lalu ia pergi ke luar dan menangis dengan sedihnya."
  },
  {Bible:"Luke", Chapter:22, Verse:63, Page:1,
    Kor:"<예수를 모욕하고 때리다(마 26:67-68; 막 14:65)> ○예수를 지키는 사람들이 예수를 때리면서 모욕하였다.",
    Chn:"看守耶稣的人戏弄他，打他，",
    Eng:"The men who were guarding Jesus began mocking and beating him.",
    Ind:"Dan orang-orang yang menahan Yesus, mengolok-olokkan Dia dan memukuli-Nya."
  },
  {Bible:"Luke", Chapter:22, Verse:64, Page:1,
    Kor:"또 그들은 예수의 눈을 가리고 말하였다. \"너를 때린 사람이 누구인지 알아맞추어 보아라.\"",
    Chn:"又蒙着他的眼，问他说：「你是先知，告诉我们打你的是谁？」",
    Eng:"They blindfolded him and demanded, \"Prophesy! Who hit you?\"",
    Ind:"Mereka menutupi muka-Nya dan bertanya: \"Cobalah katakan siapakah yang memukul Engkau?\""
  },
  {Bible:"Luke", Chapter:22, Verse:65, Page:1,
    Kor:"그들은 그 밖에도 온갖 말로 모욕하면서 예수에게 욕설을 퍼부었다.",
    Chn:"他们还用许多别的话辱骂他。",
    Eng:"And they said many other insulting things to him.",
    Ind:"Dan banyak lagi hujat yang diucapkan mereka kepada-Nya."
  },
  {Bible:"Luke", Chapter:22, Verse:66, Page:1,
    Kor:"<공회 앞에 서시다(마 26:59-66; 막 14:55-64; 요 18:19-24)> ○날이 밝으니, 백성의 장로회, 곧 대제사장들과 율법학자들이 모여서, 예수를 그들의 공의회로 끌고 가서,",
    Chn:"天一亮，民间的众长老连祭司长带文士都聚会，把耶稣带到他们的公会里，",
    Eng:"At daybreak the council of the elders of the people, both the chief priests and teachers of the law, met together, and Jesus was led before them.",
    Ind:"Dan setelah hari siang berkumpullah sidang para tua-tua bangsa Yahudi dan imam-imam kepala dan ahli-ahli Taurat, lalu mereka menghadapkan Dia ke Mahkamah Agama mereka,"
  },
  {Bible:"Luke", Chapter:22, Verse:67, Page:1,
    Kor:"이렇게 말하였다. \"그대가 그리스도이면, 그렇다고 우리에게 말해 주시오.\" 예수께서 그들에게 말씀하셨다. \"내가 그렇다고 여러분에게 말하더라도, 여러분은 믿지 않을 것이요,",
    Chn:"说：「你若是基督，就告诉我们。」耶稣说：「我若告诉你们，你们也不信；",
    Eng:"\"If you are the Christ,\" they said, \"tell us.\" Jesus answered, \"If I tell you, you will not believe me,",
    Ind:"katanya: \"Jikalau Engkau adalah Mesias, katakanlah kepada kami.\" Jawab Yesus: \"Sekalipun Aku mengatakannya kepada kamu, namun kamu tidak akan percaya;"
  },
  {Bible:"Luke", Chapter:22, Verse:68, Page:1,
    Kor:"내가 물어보아도, 여러분은 대답하지 않을 것이오.",
    Chn:"我若问你们，你们也不回答。",
    Eng:"and if I asked you, you would not answer.",
    Ind:"dan sekalipun Aku bertanya sesuatu kepada kamu, namun kamu tidak akan menjawab."
  },
  {Bible:"Luke", Chapter:22, Verse:69, Page:1,
    Kor:"그러나 이제부터 인자는 전능하신 하나님의 오른쪽에 앉게 될 것이오.\"",
    Chn:"从今以后，人子要坐在　神权能的右边。」",
    Eng:"But from now on, the Son of Man will be seated at the right hand of the mighty God.\"",
    Ind:"Mulai sekarang Anak Manusia sudah duduk di sebelah kanan Allah Yang Mahakuasa.\""
  },
  {Bible:"Luke", Chapter:22, Verse:70, Page:1,
    Kor:"그러자 모두가 말하였다. \"그러면 그대가 하나님의 아들이오?\" 예수께서 그들에게 말씀하셨다. \"내가 그라고 여러분이 말하고 있소.\"",
    Chn:"他们都说：「这样，你是　神的儿子吗？」耶稣说：「你们所说的是。」",
    Eng:"They all asked, \"Are you then the Son of God?\" He replied, \"You are right in saying I am.\"",
    Ind:"Kata mereka semua: \"Kalau begitu, Engkau ini Anak Allah?\" Jawab Yesus: \"Kamu sendiri mengatakan, bahwa Akulah Anak Allah.\""
  },
  {Bible:"Luke", Chapter:22, Verse:71, Page:1,
    Kor:"그러자 그들은 말하였다. \"이제 우리에게 무슨 증언이 더 필요하겠소? 우리가 그의 입에서 나오는 말을 직접 들었으니 말이오.\"",
    Chn:"他们说：「何必再用见证呢？他亲口所说的，我们都亲自听见了。」",
    Eng:"Then they said, \"Why do we need any more testimony? We have heard it from his own lips.\"",
    Ind:"Lalu kata mereka: \"Untuk apa kita perlu kesaksian lagi? Kita ini telah mendengarnya dari mulut-Nya sendiri.\""
  },
]);
