// 누가복음 13장 · Luke 13
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Luke",13,35);
BibleDB.add([
  {Bible:"Luke", Chapter:13, Verse:1, Page:1,
    Kor:"<회개하지 않으면 망한다> 바로 그 때에 몇몇 사람이 와서, 빌라도가 갈릴리 사람들을 학살해서 그 피를 그들이 바치려던 희생제물에 섞었다는 사실을 예수께 일러드렸다.",
    Chn:"正当那时，有人将彼拉多使加利利人的血搀杂在他们祭物中的事告诉耶稣。",
    Eng:"Now there were some present at that time who told Jesus about the Galileans whose blood Pilate had mixed with their sacrifices.",
    Ind:"Pada waktu itu datanglah kepada Yesus beberapa orang membawa kabar tentang orang-orang Galilea, yang darahnya dicampurkan Pilatus dengan darah korban yang mereka persembahkan."
  },
  {Bible:"Luke", Chapter:13, Verse:2, Page:1,
    Kor:"예수께서 그들에게 대답하셨다. \"이 갈릴리 사람들이 이런 변을 당했다고 해서, 다른 모든 갈릴리 사람보다 더 큰 죄인이라고 생각하느냐?",
    Chn:"耶稣说：「你们以为这些加利利人比众加利利人更有罪，所以受这害吗？",
    Eng:"Jesus answered, \"Do you think that these Galileans were worse sinners than all the other Galileans because they suffered this way?",
    Ind:"Yesus menjawab mereka: \"Sangkamu orang-orang Galilea ini lebih besar dosanya dari pada dosa semua orang Galilea yang lain, karena mereka mengalami nasib itu?"
  },
  {Bible:"Luke", Chapter:13, Verse:3, Page:1,
    Kor:"그렇지 않다. 내가 너희에게 말한다. 너희도 회개하지 않으면, 모두 그렇게 망할 것이다.",
    Chn:"我告诉你们，不是的！你们若不悔改，都要如此灭亡！",
    Eng:"I tell you, no! But unless you repent, you too will all perish.",
    Ind:"Tidak! kata-Ku kepadamu. Tetapi jikalau kamu tidak bertobat, kamu semua akan binasa atas cara demikian."
  },
  {Bible:"Luke", Chapter:13, Verse:4, Page:1,
    Kor:"또 실로암에 있는 탑이 무너져서 치여 죽은 열여덟 사람은 예루살렘에 사는 다른 모든 사람보다 더 많이 죄를 지은 사람이라고 생각하느냐?",
    Chn:"从前西罗亚楼倒塌了，压死十八个人；你们以为那些人比一切住在耶路撒冷的人更有罪吗？",
    Eng:"Or those eighteen who died when the tower in Siloam fell on them--do you think they were more guilty than all the others living in Jerusalem?",
    Ind:"Atau sangkamu kedelapan belas orang, yang mati ditimpa menara dekat Siloam, lebih besar kesalahannya dari pada kesalahan semua orang lain yang diam di Yerusalem?"
  },
  {Bible:"Luke", Chapter:13, Verse:5, Page:1,
    Kor:"그렇지 않다. 내가 너희에게 말한다. 너희도 회개하지 않으면, 모두 그렇게 망할 것이다.\"",
    Chn:"我告诉你们，不是的！你们若不悔改，都要如此灭亡！」",
    Eng:"I tell you, no! But unless you repent, you too will all perish.\"",
    Ind:"Tidak! kata-Ku kepadamu. Tetapi jikalau kamu tidak bertobat, kamu semua akan binasa atas cara demikian.\""
  },
  {Bible:"Luke", Chapter:13, Verse:6, Page:1,
    Kor:"<열매를 맺지 못하는 무화과나무의 비유> ○예수께서는 이런 비유를 말씀하셨다. \"어떤 사람이 자기 포도원에다가 무화과나무를 한 그루 심었는데, 그 나무에서 열매를 얻을까 하고 왔으나, 찾지 못하였다.",
    Chn:"于是用比喻说：「一个人有一棵无花果树栽在葡萄园里。他来到树前找果子，却找不着。",
    Eng:"Then he told this parable: \"A man had a fig tree, planted in his vineyard, and he went to look for fruit on it, but did not find any.",
    Ind:"Lalu Yesus mengatakan perumpamaan ini: \"Seorang mempunyai pohon ara yang tumbuh di kebun anggurnya, dan ia datang untuk mencari buah pada pohon itu, tetapi ia tidak menemukannya."
  },
  {Bible:"Luke", Chapter:13, Verse:7, Page:1,
    Kor:"그래서 그는 포도원지기에게 말하였다. '보아라, 내가 세 해나 이 무화과나무에서 열매를 얻을까 하고 왔으나, 열매를 본 적이 없다. 찍어 버려라. 무엇 때문에 땅만 버리게 하겠느냐?'",
    Chn:"就对管园的说：『看哪，我这三年来到这无花果树前找果子，竟找不着。把它砍了吧，何必白占地土呢！』",
    Eng:"So he said to the man who took care of the vineyard, 'For three years now I've been coming to look for fruit on this fig tree and haven't found any. Cut it down! Why should it use up the soil?'",
    Ind:"Lalu ia berkata kepada pengurus kebun anggur itu: Sudah tiga tahun aku datang mencari buah pada pohon ara ini dan aku tidak menemukannya. Tebanglah pohon ini! Untuk apa ia hidup di tanah ini dengan percuma!"
  },
  {Bible:"Luke", Chapter:13, Verse:8, Page:1,
    Kor:"그러자 포도원지기가 그에게 말하였다. '주인님, 올해만 그냥 두십시오. 그 동안에 내가 그 둘레를 파고 거름을 주겠습니다.",
    Chn:"管园的说：『主啊，今年且留着，等我周围掘开土，加上粪；",
    Eng:"\"'Sir,' the man replied, 'leave it alone for one more year, and I'll dig around it and fertilize it.",
    Ind:"Jawab orang itu: Tuan, biarkanlah dia tumbuh tahun ini lagi, aku akan mencangkul tanah sekelilingnya dan memberi pupuk kepadanya,"
  },
  {Bible:"Luke", Chapter:13, Verse:9, Page:1,
    Kor:"그렇게 하면, 다음 철에 열매를 맺을지도 모릅니다. 그 때에 가서도 열매를 맺지 못하면, 찍어 버리십시오.'\"",
    Chn:"以后若结果子便罢，不然再把它砍了。』」",
    Eng:"If it bears fruit next year, fine! If not, then cut it down.'\"",
    Ind:"mungkin tahun depan ia berbuah; jika tidak, tebanglah dia!\""
  },
  {Bible:"Luke", Chapter:13, Verse:10, Page:1,
    Kor:"<안식일에 등 굽은 여자를 고치시다> ○예수께서 안식일에 회당에서 가르치고 계셨다.",
    Chn:"安息日，耶稣在会堂里教训人。",
    Eng:"On a Sabbath Jesus was teaching in one of the synagogues,",
    Ind:"Pada suatu kali Yesus sedang mengajar dalam salah satu rumah ibadat pada hari Sabat."
  },
  {Bible:"Luke", Chapter:13, Verse:11, Page:1,
    Kor:"그런데 거기에 열여덟 해 동안이나 병마에 시달리고 있는 여자가 있었는데, 그는 허리가 굽어 있어서, 몸을 조금도 펼 수 없었다.",
    Chn:"有一个女人被鬼附着，病了十八年，腰弯得一点直不起来。",
    Eng:"and a woman was there who had been crippled by a spirit for eighteen years. She was bent over and could not straighten up at all.",
    Ind:"Di situ ada seorang perempuan yang telah delapan belas tahun dirasuk roh sehingga ia sakit sampai bungkuk punggungnya dan tidak dapat berdiri lagi dengan tegak."
  },
  {Bible:"Luke", Chapter:13, Verse:12, Page:1,
    Kor:"예수께서는 이 여자를 보시고, 가까이 불러서 말씀하시기를, \"여자야, 너는 병에서 풀려났다\" 하시고,",
    Chn:"耶稣看见，便叫过她来，对她说：「女人，你脱离这病了！」",
    Eng:"When Jesus saw her, he called her forward and said to her, \"Woman, you are set free from your infirmity.\"",
    Ind:"Ketika Yesus melihat perempuan itu, Ia memanggil dia dan berkata kepadanya: \"Hai ibu, penyakitmu telah sembuh.\""
  },
  {Bible:"Luke", Chapter:13, Verse:13, Page:1,
    Kor:"그 여자에게 손을 얹으셨다. 그러자 그 여자는 곧 허리를 펴고, 하나님께 영광을 돌렸다.",
    Chn:"于是用两只手按着她；她立刻直起腰来，就归荣耀与　神。",
    Eng:"Then he put his hands on her, and immediately she straightened up and praised God.",
    Ind:"Lalu Ia meletakkan tangan-Nya atas perempuan itu, dan seketika itu juga berdirilah perempuan itu, dan memuliakan Allah."
  },
  {Bible:"Luke", Chapter:13, Verse:14, Page:1,
    Kor:"그런데 회당장은, 예수께서 안식일에 병을 고치신 것에 분개하여 무리에게 말하였다. \"일을 해야 할 날이 엿새가 있으니, 엿새 가운데서 어느 날에든지 와서, 고침을 받으시오. 그러나 안식일에는 그렇게 하지 마시오.\"",
    Chn:"管会堂的因为耶稣在安息日治病，就气忿忿地对众人说：「有六日应当做工；那六日之内可以来求医，在安息日却不可。」",
    Eng:"Indignant because Jesus had healed on the Sabbath, the synagogue ruler said to the people, \"There are six days for work. So come and be healed on those days, not on the Sabbath.\"",
    Ind:"Tetapi kepala rumah ibadat gusar karena Yesus menyembuhkan orang pada hari Sabat, lalu ia berkata kepada orang banyak: \"Ada enam hari untuk bekerja. Karena itu datanglah pada salah satu hari itu untuk disembuhkan dan jangan pada hari Sabat.\""
  },
  {Bible:"Luke", Chapter:13, Verse:15, Page:1,
    Kor:"주님께서 그에게 대답하셨다. \"너희 위선자들아, 너희는 저마다 안식일에도 소나 나귀를 외양간에서 풀어내어, 끌고 나가서 물을 먹이지 않느냐?",
    Chn:"主说：「假冒为善的人哪，难道你们各人在安息日不解开槽上的牛、驴，牵去饮吗？",
    Eng:"The Lord answered him, \"You hypocrites! Doesn't each of you on the Sabbath untie his ox or donkey from the stall and lead it out to give it water?",
    Ind:"Tetapi Tuhan menjawab dia, kata-Nya: \"Hai orang-orang munafik, bukankah setiap orang di antaramu melepaskan lembunya atau keledainya pada hari Sabat dari kandangnya dan membawanya ke tempat minuman?"
  },
  {Bible:"Luke", Chapter:13, Verse:16, Page:1,
    Kor:"그렇다면, 아브라함의 딸인 이 여자가 열여덟 해 동안이나 사탄에게 매여 있었으니, 안식일에라도 이 매임을 풀어 주어야 하지 않겠느냐?\"",
    Chn:"况且这女人本是亚伯拉罕的后裔，被撒但捆绑了这十八年，不当在安息日解开她的绑吗？」",
    Eng:"Then should not this woman, a daughter of Abraham, whom Satan has kept bound for eighteen long years, be set free on the Sabbath day from what bound her?\"",
    Ind:"Bukankah perempuan ini, yang sudah delapan belas tahun diikat oleh Iblis, harus dilepaskan dari ikatannya itu, karena ia adalah keturunan Abraham?\""
  },
  {Bible:"Luke", Chapter:13, Verse:17, Page:1,
    Kor:"예수께서 이 말씀을 하시니, 그를 반대하던 사람들은 모두 부끄러워하였고, 무리는 모두 예수께서 하신 모든 영광스러운 일을 두고 기뻐하였다.",
    Chn:"耶稣说这话，他的敌人都惭愧了；众人因他所行一切荣耀的事，就都欢喜了。",
    Eng:"When he said this, all his opponents were humiliated, but the people were delighted with all the wonderful things he was doing.",
    Ind:"Dan waktu Ia berkata demikian, semua lawan-Nya merasa malu dan semua orang banyak bersukacita karena segala perkara mulia, yang telah dilakukan-Nya."
  },
  {Bible:"Luke", Chapter:13, Verse:18, Page:1,
    Kor:"<겨자씨와 누룩의 비유(마 13:31-33; 막 4:30-32)> ○예수께서 말씀하셨다. \"하나님 나라는 무엇과 같은가? 그것을 무엇에다가 비길까?",
    Chn:"耶稣说：「　神的国好像什么？我拿什么来比较呢？",
    Eng:"Then Jesus asked, \"What is the kingdom of God like? What shall I compare it to?",
    Ind:"Maka kata Yesus: \"Seumpama apakah hal Kerajaan Allah dan dengan apakah Aku akan mengumpamakannya?"
  },
  {Bible:"Luke", Chapter:13, Verse:19, Page:1,
    Kor:"그것은 겨자씨의 다음 경우와 같다. 어떤 사람이 겨자씨를 가져다가 자기 정원에 심었더니, 자라서 나무가 되어, 공중의 새들이 그 가지에 깃들였다.\"",
    Chn:"好像一粒芥菜种，有人拿去种在园子里，长大成树，天上的飞鸟宿在它的枝上。」",
    Eng:"It is like a mustard seed, which a man took and planted in his garden. It grew and became a tree, and the birds of the air perched in its branches.\"",
    Ind:"Ia seumpama biji sesawi, yang diambil dan ditaburkan orang di kebunnya; biji itu tumbuh dan menjadi pohon dan burung-burung di udara bersarang pada cabang-cabangnya.\""
  },
  {Bible:"Luke", Chapter:13, Verse:20, Page:1,
    Kor:"○예수께서 다시 말씀하셨다. \"하나님 나라를 무엇에다가 비길까?",
    Chn:"又说：「我拿什么来比　神的国呢？",
    Eng:"Again he asked, \"What shall I compare the kingdom of God to?",
    Ind:"Dan Ia berkata lagi: \"Dengan apakah Aku akan mengumpamakan Kerajaan Allah?"
  },
  {Bible:"Luke", Chapter:13, Verse:21, Page:1,
    Kor:"그것은 누룩의 다음 경우와 같다. 어떤 여자가 누룩을 가져다가, 가루 서 a말 속에 b섞어 넣었더니, 마침내 온통 부풀어올랐다.\"(a 그, '사타스'. 세 사타스는 약 22리터 b 그, '감추었더니')",
    Chn:"好比面酵，有妇人拿来藏在三斗面里，直等全团都发起来。」",
    Eng:"It is like yeast that a woman took and mixed into a large amount of flour until it worked all through the dough.\"",
    Ind:"Ia seumpama ragi yang diambil seorang perempuan dan diadukkan ke dalam tepung terigu tiga sukat sampai khamir seluruhnya.\""
  },
  {Bible:"Luke", Chapter:13, Verse:22, Page:1,
    Kor:"<좁은 문으로 들어가기를 힘써라(마 7:13-14, 21-23)> ○예수께서 여러 성읍과 마을에 들르셔서, 가르치시면서 예루살렘으로 여행하셨다.",
    Chn:"耶稣往耶路撒冷去，在所经过的各城各乡教训人。",
    Eng:"Then Jesus went through the towns and villages, teaching as he made his way to Jerusalem.",
    Ind:"Kemudian Yesus berjalan keliling dari kota ke kota dan dari desa ke desa sambil mengajar dan meneruskan perjalanan-Nya ke Yerusalem."
  },
  {Bible:"Luke", Chapter:13, Verse:23, Page:1,
    Kor:"그런데 어떤 사람이 예수께 물었다. \"주님, 구원받을 사람은 적습니까?\" 예수께서 그들에게 대답하셨다.",
    Chn:"有一个人问他说：「主啊，得救的人少吗？」",
    Eng:"Someone asked him, \"Lord, are only a few people going to be saved?\" He said to them,",
    Ind:"Dan ada seorang yang berkata kepada-Nya: \"Tuhan, sedikit sajakah orang yang diselamatkan?\""
  },
  {Bible:"Luke", Chapter:13, Verse:24, Page:1,
    Kor:"\"너희는 좁은 문으로 들어가기를 힘써라. 내가 너희에게 말한다. 들어가려고 해도 들어가지 못하는 사람이 많을 것이다.",
    Chn:"耶稣对众人说：「你们要努力进窄门。我告诉你们，将来有许多人想要进去，却是不能。",
    Eng:"\"Make every effort to enter through the narrow door, because many, I tell you, will try to enter and will not be able to.",
    Ind:"Jawab Yesus kepada orang-orang di situ: \"Berjuanglah untuk masuk melalui pintu yang sesak itu! Sebab Aku berkata kepadamu: Banyak orang akan berusaha untuk masuk, tetapi tidak akan dapat."
  },
  {Bible:"Luke", Chapter:13, Verse:25, Page:1,
    Kor:"집주인이 일어나서, 문을 닫아 버리면, 너희가 밖에 서서 문을 두드리면서 '주인님, 문을 열어 주십시오' 하고 졸라도, 주인은 '너희가 어디에서 왔는지, 나는 모른다' 하고 대답할 것이다.",
    Chn:"及至家主起来关了门，你们站在外面叩门，说：『主啊，给我们开门！』他就回答说：『我不认识你们，不晓得你们是哪里来的！』",
    Eng:"Once the owner of the house gets up and closes the door, you will stand outside knocking and pleading, 'Sir, open the door for us.' \"But he will answer, 'I don't know you or where you come from.'",
    Ind:"Jika tuan rumah telah bangkit dan telah menutup pintu, kamu akan berdiri di luar dan mengetok-ngetok pintu sambil berkata: Tuan, bukakanlah kami pintu! dan Ia akan menjawab dan berkata kepadamu: Aku tidak tahu dari mana kamu datang."
  },
  {Bible:"Luke", Chapter:13, Verse:26, Page:1,
    Kor:"그 때에 너희가 말하기를 '우리는 주인님 앞에서 먹고 마셨으며, 주인님은 우리를 길거리에서 가르치셨습니다' 할 터이나,",
    Chn:"那时，你们要说：『我们在你面前吃过喝过，你也在我们的街上教训过人。』",
    Eng:"\"Then you will say, 'We ate and drank with you, and you taught in our streets.'",
    Ind:"Maka kamu akan berkata: Kami telah makan dan minum di hadapan-Mu dan Engkau telah mengajar di jalan-jalan kota kami."
  },
  {Bible:"Luke", Chapter:13, Verse:27, Page:1,
    Kor:"주인이 너희에게 말하기를 '나는 너희가 어디에서 왔는지 모른다. 불의를 일삼는 자들아, 모두 내게서 물러가거라' 할 것이다.",
    Chn:"他要说：『我告诉你们，我不晓得你们是哪里来的。你们这一切作恶的人，离开我去吧！』",
    Eng:"\"But he will reply, 'I don't know you or where you come from. Away from me, all you evildoers!'",
    Ind:"Tetapi Ia akan berkata kepadamu: Aku tidak tahu dari mana kamu datang, enyahlah dari hadapan-Ku, hai kamu sekalian yang melakukan kejahatan!"
  },
  {Bible:"Luke", Chapter:13, Verse:28, Page:1,
    Kor:"아브라함과 이삭과 야곱과 모든 예언자는 하나님 나라 안에 있는데, 너희는 바깥으로 쫓겨난 것을 너희가 보게 될 때에, 거기서 슬피 울면서 이를 갈 것이다.",
    Chn:"你们要看见亚伯拉罕、以撒、雅各，和众先知都在　神的国里，你们却被赶到外面，在那里必要哀哭切齿了。",
    Eng:"\"There will be weeping there, and gnashing of teeth, when you see Abraham, Isaac and Jacob and all the prophets in the kingdom of God, but you yourselves thrown out.",
    Ind:"Di sanalah akan terdapat ratap dan kertak gigi, apabila kamu akan melihat Abraham dan Ishak dan Yakub dan semua nabi di dalam Kerajaan Allah, tetapi kamu sendiri dicampakkan ke luar."
  },
  {Bible:"Luke", Chapter:13, Verse:29, Page:1,
    Kor:"사람들이 동과 서에서, 또 남과 북에서 와서, 하나님 나라 잔치 자리에 앉을 것이다.",
    Chn:"从东、从西、从南、从北将有人来，在　神的国里坐席。",
    Eng:"People will come from east and west and north and south, and will take their places at the feast in the kingdom of God.",
    Ind:"Dan orang akan datang dari Timur dan Barat dan dari Utara dan Selatan dan mereka akan duduk makan di dalam Kerajaan Allah."
  },
  {Bible:"Luke", Chapter:13, Verse:30, Page:1,
    Kor:"보아라, 꼴찌가 첫째가 될 사람이 있고, 첫째가 꼴찌가 될 사람이 있다.\"",
    Chn:"只是有在后的，将要在前；有在前的，将要在后。」",
    Eng:"Indeed there are those who are last who will be first, and first who will be last.\"",
    Ind:"Dan sesungguhnya ada orang yang terakhir yang akan menjadi orang yang terdahulu dan ada orang yang terdahulu yang akan menjadi orang yang terakhir.\""
  },
  {Bible:"Luke", Chapter:13, Verse:31, Page:1,
    Kor:"<예루살렘을 보고 한탄하시다(마 23:37-39)> ○바로 그 때에 몇몇 바리새파 사람들이 다가와서 예수께 말하였다. \"여기에서 떠나가십시오. 헤롯 왕이 당신을 죽이고자 합니다.\"",
    Chn:"正当那时，有几个法利赛人来对耶稣说：「离开这里去吧，因为希律想要杀你。」",
    Eng:"At that time some Pharisees came to Jesus and said to him, \"Leave this place and go somewhere else. Herod wants to kill you.\"",
    Ind:"Pada waktu itu datanglah beberapa orang Farisi dan berkata kepada Yesus: \"Pergilah, tinggalkanlah tempat ini, karena Herodes hendak membunuh Engkau.\""
  },
  {Bible:"Luke", Chapter:13, Verse:32, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"가서, 그 여우에게 전하기를 '보아라, 오늘과 내일은 내가 귀신을 내쫓고 병을 고칠 것이요, 사흘째 되는 날에는 내 일을 끝낸다' 하여라.",
    Chn:"耶稣说：「你们去告诉那个狐狸说：『今天、明天我赶鬼治病，第三天我的事就成全了。』",
    Eng:"He replied, \"Go tell that fox, 'I will drive out demons and heal people today and tomorrow, and on the third day I will reach my goal.'",
    Ind:"Jawab Yesus kepada mereka: \"Pergilah dan katakanlah kepada si serigala itu: Aku mengusir setan dan menyembuhkan orang, pada hari ini dan besok, dan pada hari yang ketiga Aku akan selesai."
  },
  {Bible:"Luke", Chapter:13, Verse:33, Page:1,
    Kor:"그러나 오늘도 내일도 그 다음 날도, 나는 내 길을 가야 하겠다. 예언자가 예루살렘이 아닌 다른 곳에서는 죽을 수 없기 때문이다.",
    Chn:"虽然这样，今天、明天、后天，我必须前行，因为先知在耶路撒冷之外丧命是不能的。",
    Eng:"In any case, I must keep going today and tomorrow and the next day--for surely no prophet can die outside Jerusalem!",
    Ind:"Tetapi hari ini dan besok dan lusa Aku harus meneruskan perjalanan-Ku, sebab tidaklah semestinya seorang nabi dibunuh kalau tidak di Yerusalem."
  },
  {Bible:"Luke", Chapter:13, Verse:34, Page:1,
    Kor:"예루살렘아, 예루살렘아, 예언자들을 죽이고, 네게 파송된 사람들을 돌로 치는구나! 암탉이 제 새끼를 날개 아래에 품듯이, 내가 몇 번이나 네 자녀를 모아 품으려 하였더냐! 그러나 너희는 그것을 원하지 않았다.",
    Chn:"耶路撒冷啊！耶路撒冷啊！你常杀害先知，又用石头打死那奉差遣到你这里来的人。我多次愿意聚集你的儿女，好像母鸡把小鸡聚集在翅膀底下；只是你们不愿意。",
    Eng:"\"O Jerusalem, Jerusalem, you who kill the prophets and stone those sent to you, how often I have longed to gather your children together, as a hen gathers her chicks under her wings, but you were not willing!",
    Ind:"Yerusalem, Yerusalem, engkau yang membunuh nabi-nabi dan melempari dengan batu orang-orang yang diutus kepadamu! Berkali-kali Aku rindu mengumpulkan anak-anakmu, sama seperti induk ayam mengumpulkan anak-anaknya di bawah sayapnya, tetapi kamu tidak mau."
  },
  {Bible:"Luke", Chapter:13, Verse:35, Page:1,
    Kor:"보아라, 너희의 집은 버림을 받을 것이다. 내가 너희에게 말한다. 너희가 말하기를 c'주님의 이름으로 오시는 분은 복되시다' 할 그 때가 오기까지, 너희는 나를 다시는 보지 못할 것이다.\"(c 시 118:26)",
    Chn:"看哪，你们的家成为荒场留给你们。我告诉你们，从今以后你们不得再见我，直等到你们说：『奉主名来的是应当称颂的。』」",
    Eng:"Look, your house is left to you desolate. I tell you, you will not see me again until you say, 'Blessed is he who comes in the name of the Lord.'\"",
    Ind:"Sesungguhnya rumahmu ini akan ditinggalkan dan menjadi sunyi. Tetapi Aku berkata kepadamu: Kamu tidak akan melihat Aku lagi hingga pada saat kamu berkata: Diberkatilah Dia yang datang dalam nama Tuhan!\""
  },
]);
