// 민수기 27장 · Numbers 27
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Numbers",27,23);
BibleDB.add([
  {Bible:"Numbers", Chapter:27, Verse:1, Page:1, Kor:"<슬로브핫의 딸들> 슬로브핫의 딸들이 나아왔다. 슬로브핫은 요셉의 아들인 므낫세의 가족으로서, 헤벨의 아들이요, 길르앗의 손자요, 마길의 증손이요, 므낫세의 현손이다. 그의 딸들의 이름은 말라와 노아와 호글라와 밀가와 디르사이다.", Chn:"", Eng:"The daughters of Zelophehad son of Hepher, the son of Gilead, the son of Makir, the son of Manasseh, belonged to the clans of Manasseh son of Joseph. The names of the daughters were Mahlah, Noah, Hoglah, Milcah and Tirzah. They approached", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:2, Page:1, Kor:"그들은 회막 어귀에서 모세와 제사장 엘르아살과 지도자들과 온 회중 앞에 서서 호소하였다.", Chn:"", Eng:"the entrance to the Tent of Meeting and stood before Moses, Eleazar the priest, the leaders and the whole assembly, and said,", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:3, Page:1, Kor:"\"우리의 아버지는 광야에서 돌아가셨습니다. 그러나 주님을 거역하여 모였던 고라의 무리 속에 끼지는 않으셨습니다. 아버지께서는 다만 자신의 죄로 돌아가셨습니다. 그런데 아버지께는 아들이 없습니다.", Chn:"", Eng:"\"Our father died in the desert. He was not among Korah's followers, who banded together against the LORD, but he died for his own sin and left no sons.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:4, Page:1, Kor:"그러나 아들이 없다는 이유로 아버지의 가족 가운데서 아버지의 이름이 없어져야 한다니, 어찌 이럴 수가 있습니까? 우리 아버지의 남자 친족들이 유산을 물려받을 때에, 우리에게도 유산을 주시기 바랍니다.\"", Chn:"", Eng:"Why should our father's name disappear from his clan because he had no son? Give us property among our father's relatives.\"", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:5, Page:1, Kor:"○모세가 그들의 사정을 주님께 아뢰었다.", Chn:"", Eng:"So Moses brought their case before the LORD", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:6, Page:1, Kor:"주님께서 모세에게 말씀하셨다.", Chn:"", Eng:"and the LORD said to him,", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:7, Page:1, Kor:"\"슬로브핫의 딸들이 한 말이 옳다. 그 아버지의 남자 친족들이 유산을 물려받을 때에, 너는 그들에게도 반드시 땅을 유산으로 주어라. 너는 그들의 아버지가 받을 유산이 그 딸들에게 돌아가게 하여라.", Chn:"", Eng:"\"What Zelophehad's daughters are saying is right. You must certainly give them property as an inheritance among their father's relatives and turn their father's inheritance over to them.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:8, Page:1, Kor:"너는 또 이스라엘 자손에게 이렇게 일러두어라. 어떤 사람이 아들이 없이 죽으면, 그 유산을 딸에게 상속시켜라.", Chn:"", Eng:"\"Say to the Israelites, 'If a man dies and leaves no son, turn his inheritance over to his daughter.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:9, Page:1, Kor:"만일 딸이 없으면, 그 유산을 고인의 형제들에게 주어라.", Chn:"", Eng:"If he has no daughter, give his inheritance to his brothers.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:10, Page:1, Kor:"그에게 형제마저도 없으면, 그 유산을 아버지의 형제들에게 상속시켜라.", Chn:"", Eng:"If he has no brothers, give his inheritance to his father's brothers.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:11, Page:1, Kor:"아버지의 형제들마저도 없으면, 그 유산을 그의 가문에서 그와 가장 가까운 친족에게 주어서, 그가 그것을 물려받게 하여라. 나 주가 모세에게 명한 것인 만큼, 여기에서 말한 것은 이스라엘 자손이 지켜야 할 율례이다.\"", Chn:"", Eng:"If his father had no brothers, give his inheritance to the nearest relative in his clan, that he may possess it. This is to be a legal requirement for the Israelites, as the LORD commanded Moses.'\"", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:12, Page:1, Kor:"<모세의 후계자 여호수아(신 31:1-8)> ○주님께서 모세에게 말씀하셨다. \"너는 여기 아바림 산줄기를 타고 올라가서, 내가 이스라엘 자손에게 준 땅을 바라보아라.", Chn:"", Eng:"Then the LORD said to Moses, \"Go up this mountain in the Abarim range and see the land I have given the Israelites.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:13, Page:1, Kor:"그 땅을 본 다음에는, 너의 형 아론이 간 것같이, 너 또한 너의 a조상에게로 돌아갈 것이다.(a 히, '백성')", Chn:"", Eng:"After you have seen it, you too will be gathered to your people, as your brother Aaron was,", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:14, Page:1, Kor:"너희 둘이 신 광야에서 나의 명을 어겼기 때문에, 그 땅에는 들어가지 못한다. 온 회중이 므리바에서 나를 거역하여 반란을 일으켰을 때에, 너희들은 물을 터뜨려 회중이 보는 앞에서, 나의 거룩한 권능을 보였어야만 하였는데, 너희는 그렇게 하지 않았다.\" 이것은 신 광야에 있는 가데스의 므리바에서 04 27:물이 터질 때의 일을 두고 말씀하신 것이다.", Chn:"", Eng:"for when the community rebelled at the waters in the Desert of Zin, both of you disobeyed my command to honor me as holy before their eyes.\" (These were the waters of Meribah Kadesh, in the Desert of Zin.)", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:15, Page:1, Kor:"○모세가 주님께 이렇게 아뢰었다.", Chn:"", Eng:"Moses said to the LORD,", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:16, Page:1, Kor:"\"모든 사람에게 영을 주시는 주 하나님, 이 회중 위에 한 사람을 임명하여 주시기를 바랍니다.", Chn:"", Eng:"\"May the LORD, the God of the spirits of all mankind, appoint a man over this community", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:17, Page:1, Kor:"그가 백성 앞에서 나가기도 하고, 백성 앞에서 들어오기도 할 것입니다. 백성을 데리고 나가기도 하고, 데리고 들어오기도 할 것입니다. 주님의 회중이 목자 없는 양 떼처럼 되지 않도록 하여 주십시오.\"", Chn:"", Eng:"to go out and come in before them, one who will lead them out and bring them in, so the LORD'S people will not be like sheep without a shepherd.\"", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:18, Page:1, Kor:"○주님께서 모세에게 말씀하셨다. \"너는 눈의 아들 여호수아를 데리고 오너라. 그는 영감을 받은 사람이다. 너는 그에게 손을 얹어라.", Chn:"", Eng:"So the LORD said to Moses, \"Take Joshua son of Nun, a man in whom is the spirit, and lay your hand on him.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:19, Page:1, Kor:"너는 그를 제사장 엘르아살과 온 회중 앞에 세우고, 그들이 보는 앞에서 그를 후계자로 임명하여라.", Chn:"", Eng:"Have him stand before Eleazar the priest and the entire assembly and commission him in their presence.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:20, Page:1, Kor:"너는 그에게 네가 가지고 있는 권위를 물려주어서, 이스라엘 자손 온 회중이 그에게 복종하게 하여라.", Chn:"", Eng:"Give him some of your authority so the whole Israelite community will obey him.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:21, Page:1, Kor:"그는, 상의할 일이 있을 때마다 제사장 엘르아살 앞에 가서 설 것이며, 여호수아를 대신하여, 엘르아살이 우림의 판결을 사용하여 나 주에게 여쭐 것이다. 그러면 여호수아와 그와 함께 있는 온 이스라엘 자손, 곧 온 총회는 그의 말에 따라서 나가기도 하고, 그의 말에 따라서 들어오기도 할 것이다.\"", Chn:"", Eng:"He is to stand before Eleazar the priest, who will obtain decisions for him by inquiring of the Urim before the LORD. At his command he and the entire community of the Israelites will go out, and at his command they will come in.\"", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:22, Page:1, Kor:"○모세는 주님께서 그에게 명하신 대로 하였다. 모세는 여호수아를 데려다가 제사장 엘르아살과 온 회중 앞에 세우고,", Chn:"", Eng:"Moses did as the LORD commanded him. He took Joshua and had him stand before Eleazar the priest and the whole assembly.", Ind:""},
  {Bible:"Numbers", Chapter:27, Verse:23, Page:1, Kor:"주님께서 말씀하신 대로 자기의 손을 여호수아에게 얹어서, 그를 후계자로 임명하였다.", Chn:"", Eng:"Then he laid his hands on him and commissioned him, as the LORD instructed through Moses.", Ind:""},
]);
