// 민수기 36장 · Numbers 36
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Numbers",36,13);
BibleDB.add([
  {Bible:"Numbers", Chapter:36, Verse:1, Page:1, Kor:"<결혼한 여자의 유산> 요셉 자손 가문 가운데 므낫세의 손자이자 마길의 아들인 길르앗 자손 가문이 있는데, 바로 길르앗 자손에 속한 각 가문의 우두머리들이 나서서, 모세와 이스라엘 자손의 지도자들인 각 가문의 우두머리 앞에 나와서 이렇게 말하였다.", Chn:"", Eng:"The family heads of the clan of Gilead son of Makir, the son of Manasseh, who were from the clans of the descendants of Joseph, came and spoke before Moses and the leaders, the heads of the Israelite families.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:2, Page:1, Kor:"\"이 땅을 제비뽑아 이스라엘 자손에게 분배하여 유산을 삼게 하라고 주님께서 어른께 명하셨을 때에, 주님께서는 어른께 우리의 친족 슬로브핫의 토지 유산을 그의 딸들에게 주라고 명하셨습니다.", Chn:"", Eng:"They said, \"When the LORD commanded my lord to give the land as an inheritance to the Israelites by lot, he ordered you to give the inheritance of our brother Zelophehad to his daughters.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:3, Page:1, Kor:"그러나 그 딸들이 이스라엘 자손의 다른 지파 남자들과 결혼할 때에는, 그 딸들이 받은 유산은 우리 조상 대대로 물려 온 유산에서 떨어져 나가, 그 딸들이 시집간 그 지파의 유산이 될 것입니다. 그렇게 된다면 우리 지파의 몫으로 분배된 유산의 일부를 우리는 잃고 맙니다.", Chn:"", Eng:"Now suppose they marry men from other Israelite tribes; then their inheritance will be taken from our ancestral inheritance and added to that of the tribe they marry into. And so part of the inheritance allotted to us will be taken away.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:4, Page:1, Kor:"이스라엘 자손이 누리는 a희년이 되어도, 그 딸들이 물려받은 유산은 그 딸들의 시집 지파의 유산에 합쳐질 것이므로, 결국 우리는 조상 대대로 물려받은 지파 유산에서 그만큼의 유산을 잃는 것입니다.\"(a 레 25:8-17을 볼 것)", Chn:"", Eng:"When the Year of Jubilee for the Israelites comes, their inheritance will be added to that of the tribe into which they marry, and their property will be taken from the tribal inheritance of our forefathers.\"", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:5, Page:1, Kor:"○주님의 명을 받들어, 모세가 이스라엘 자손에게 명령하였다. \"요셉 자손 지파의 말이 옳소.", Chn:"", Eng:"Then at the LORD'S command Moses gave this order to the Israelites: \"What the tribe of the descendants of Joseph is saying is right.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:6, Page:1, Kor:"주님께서는 슬로브핫 딸들의 경우를 두고 이렇게 명하셨소. 그 딸들은 자기들의 마음에 드는 남자가 있으면 누구하고든지 결혼할 수는 있소. 그러나 그들이 속한 조상 지파의 가족에게만 시집갈 수 있소.", Chn:"", Eng:"This is what the LORD commands for Zelophehad's daughters: They may marry anyone they please as long as they marry within the tribal clan of their father.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:7, Page:1, Kor:"이스라엘 자손의 지파 유산이 이 지파에서 저 지파로 옮겨지는 일이 없어야, 이스라엘 자손이 제각기 자기 조상으로부터 물려받은 지파의 유산을 그대로 간직할 수 있을 것이오.", Chn:"", Eng:"No inheritance in Israel is to pass from tribe to tribe, for every Israelite shall keep the tribal land inherited from his forefathers.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:8, Page:1, Kor:"이스라엘 자손의 지파 가운데서 유산을 받은 딸들은 누구나, 자기 조상 지파의 가족에게로 시집가야 하오. 그래야만 이스라엘 자손이 지파마다 조상으로부터 물려받은 유산을 간직할 수 있을 것이오.", Chn:"", Eng:"Every daughter who inherits land in any Israelite tribe must marry someone in her father's tribal clan, so that every Israelite will possess the inheritance of his fathers.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:9, Page:1, Kor:"지파의 유산이 한 지파에서 다른 지파로 옮겨지는 일이 없어야, 이스라엘 자손 각 지파가 제각기 물려받은 유산을 그대로 간직할 수 있을 것이오.\"", Chn:"", Eng:"No inheritance may pass from tribe to tribe, for each Israelite tribe is to keep the land it inherits.\"", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:10, Page:1, Kor:"○그리하여 슬로브핫의 딸들은 주님께서 모세에게 명하신 대로 하였다.", Chn:"", Eng:"So Zelophehad's daughters did as the LORD commanded Moses.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:11, Page:1, Kor:"슬로브핫의 딸들, 곧 말라와 디르사와 호글라와 밀가와 노아는 모두 자기 사촌 오라버니들과 결혼하였다.", Chn:"", Eng:"Zelophehad's daughters--Mahlah, Tirzah, Hoglah, Milcah and Noah--married their cousins on their father's side.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:12, Page:1, Kor:"그 딸들이 모두 요셉의 아들인 므낫세 자손 가문과 결혼하였기 때문에, 그들이 받은 유산은 자기 조상의 가문과 지파에 그대로 남아 있었다.", Chn:"", Eng:"They married within the clans of the descendants of Manasseh son of Joseph, and their inheritance remained in their father's clan and tribe.", Ind:""},
  {Bible:"Numbers", Chapter:36, Verse:13, Page:1, Kor:"○이것은 주님께서 여리고 건너편 요단 강 가 모압 평지에서 모세를 시켜 이스라엘 자손에게 말씀하신 명령과 규례이다.", Chn:"", Eng:"", Ind:""},
]);
