// 민수기 33장 · Numbers 33
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Numbers",33,56);
BibleDB.add([
  {Bible:"Numbers", Chapter:33, Verse:1, Page:1, Kor:"", Chn:"", Eng:"Here are the stages in the journey of the Israelites when they came out of Egypt by divisions under the leadership of Moses and Aaron.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:2, Page:1, Kor:"", Chn:"", Eng:"At the LORD'S command Moses recorded the stages in their journey. This is their journey by stages:", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:3, Page:1, Kor:"", Chn:"", Eng:"The Israelites set out from Rameses on the fifteenth day of the first month, the day after the Passover. They marched out boldly in full view of all the Egyptians,", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:4, Page:1, Kor:"", Chn:"", Eng:"who were burying all their firstborn, whom the LORD had struck down among them; for the LORD had brought judgment on their gods.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:5, Page:1, Kor:"", Chn:"", Eng:"The Israelites left Rameses and camped at Succoth.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:6, Page:1, Kor:"", Chn:"", Eng:"They left Succoth and camped at Etham, on the edge of the desert.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:7, Page:1, Kor:"", Chn:"", Eng:"They left Etham, turned back to Pi Hahiroth, to the east of Baal Zephon, and camped near Migdol.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:8, Page:1, Kor:"", Chn:"", Eng:"They left Pi Hahiroth and passed through the sea into the desert, and when they had traveled for three days in the Desert of Etham, they camped at Marah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:9, Page:1, Kor:"", Chn:"", Eng:"They left Marah and went to Elim, where there were twelve springs and seventy palm trees, and they camped there.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:10, Page:1, Kor:"", Chn:"", Eng:"They left Elim and camped by the Red Sea.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:11, Page:1, Kor:"", Chn:"", Eng:"They left the Red Sea and camped in the Desert of Sin.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:12, Page:1, Kor:"", Chn:"", Eng:"They left the Desert of Sin and camped at Dophkah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:13, Page:1, Kor:"", Chn:"", Eng:"They left Dophkah and camped at Alush.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:14, Page:1, Kor:"", Chn:"", Eng:"They left Alush and camped at Rephidim, where there was no water for the people to drink.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:15, Page:1, Kor:"", Chn:"", Eng:"They left Rephidim and camped in the Desert of Sinai.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:16, Page:1, Kor:"", Chn:"", Eng:"They left the Desert of Sinai and camped at Kibroth Hattaavah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:17, Page:1, Kor:"", Chn:"", Eng:"They left Kibroth Hattaavah and camped at Hazeroth.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:18, Page:1, Kor:"", Chn:"", Eng:"They left Hazeroth and camped at Rithmah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:19, Page:1, Kor:"", Chn:"", Eng:"They left Rithmah and camped at Rimmon Perez.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:20, Page:1, Kor:"", Chn:"", Eng:"They left Rimmon Perez and camped at Libnah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:21, Page:1, Kor:"", Chn:"", Eng:"They left Libnah and camped at Rissah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:22, Page:1, Kor:"", Chn:"", Eng:"They left Rissah and camped at Kehelathah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:23, Page:1, Kor:"", Chn:"", Eng:"They left Kehelathah and camped at Mount Shepher.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:24, Page:1, Kor:"", Chn:"", Eng:"They left Mount Shepher and camped at Haradah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:25, Page:1, Kor:"", Chn:"", Eng:"They left Haradah and camped at Makheloth.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:26, Page:1, Kor:"", Chn:"", Eng:"They left Makheloth and camped at Tahath.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:27, Page:1, Kor:"", Chn:"", Eng:"They left Tahath and camped at Terah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:28, Page:1, Kor:"", Chn:"", Eng:"They left Terah and camped at Mithcah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:29, Page:1, Kor:"", Chn:"", Eng:"They left Mithcah and camped at Hashmonah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:30, Page:1, Kor:"", Chn:"", Eng:"They left Hashmonah and camped at Moseroth.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:31, Page:1, Kor:"", Chn:"", Eng:"They left Moseroth and camped at Bene Jaakan.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:32, Page:1, Kor:"", Chn:"", Eng:"They left Bene Jaakan and camped at Hor Haggidgad.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:33, Page:1, Kor:"", Chn:"", Eng:"They left Hor Haggidgad and camped at Jotbathah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:34, Page:1, Kor:"", Chn:"", Eng:"They left Jotbathah and camped at Abronah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:35, Page:1, Kor:"", Chn:"", Eng:"They left Abronah and camped at Ezion Geber.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:36, Page:1, Kor:"", Chn:"", Eng:"They left Ezion Geber and camped at Kadesh, in the Desert of Zin.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:37, Page:1, Kor:"", Chn:"", Eng:"They left Kadesh and camped at Mount Hor, on the border of Edom.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:38, Page:1, Kor:"", Chn:"", Eng:"At the LORD'S command Aaron the priest went up Mount Hor, where he died on the first day of the fifth month of the fortieth year after the Israelites came out of Egypt.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:39, Page:1, Kor:"", Chn:"", Eng:"Aaron was a hundred and twenty-three years old when he died on Mount Hor.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:40, Page:1, Kor:"", Chn:"", Eng:"The Canaanite king of Arad, who lived in the Negev of Canaan, heard that the Israelites were coming.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:41, Page:1, Kor:"", Chn:"", Eng:"They left Mount Hor and camped at Zalmonah.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:42, Page:1, Kor:"", Chn:"", Eng:"They left Zalmonah and camped at Punon.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:43, Page:1, Kor:"", Chn:"", Eng:"They left Punon and camped at Oboth.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:44, Page:1, Kor:"", Chn:"", Eng:"They left Oboth and camped at Iye Abarim, on the border of Moab.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:45, Page:1, Kor:"", Chn:"", Eng:"They left Iyim and camped at Dibon Gad.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:46, Page:1, Kor:"", Chn:"", Eng:"They left Dibon Gad and camped at Almon Diblathaim.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:47, Page:1, Kor:"", Chn:"", Eng:"They left Almon Diblathaim and camped in the mountains of Abarim, near Nebo.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:48, Page:1, Kor:"", Chn:"", Eng:"They left the mountains of Abarim and camped on the plains of Moab by the Jordan across from Jericho.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:49, Page:1, Kor:"", Chn:"", Eng:"There on the plains of Moab they camped along the Jordan from Beth Jeshimoth to Abel Shittim.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:50, Page:1, Kor:"", Chn:"", Eng:"On the plains of Moab by the Jordan across from Jericho the LORD said to Moses,", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:51, Page:1, Kor:"", Chn:"", Eng:"\"Speak to the Israelites and say to them: 'When you cross the Jordan into Canaan,", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:52, Page:1, Kor:"", Chn:"", Eng:"drive out all the inhabitants of the land before you. Destroy all their carved images and their cast idols, and demolish all their high places.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:53, Page:1, Kor:"", Chn:"", Eng:"Take possession of the land and settle in it, for I have given you the land to possess.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:54, Page:1, Kor:"", Chn:"", Eng:"Distribute the land by lot, according to your clans. To a larger group give a larger inheritance, and to a smaller group a smaller one. Whatever falls to them by lot will be theirs. Distribute it according to your ancestral tribes.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:55, Page:1, Kor:"", Chn:"", Eng:"\"'But if you do not drive out the inhabitants of the land, those you allow to remain will become barbs in your eyes and thorns in your sides. They will give you trouble in the land where you will live.", Ind:""},
  {Bible:"Numbers", Chapter:33, Verse:56, Page:1, Kor:"", Chn:"", Eng:"And then I will do to you what I plan to do to them.'\"", Ind:""},
]);
