// 민수기 26장 · Numbers 26
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Numbers",26,65);
BibleDB.add([
  {Bible:"Numbers", Chapter:26, Verse:1, Page:1,
    Kor:"<두 번째 인구조사> 염병이 지나간 뒤에, 주님께서 모세와 아론의 아들 제사장 엘르아살에게 말씀하셨다.",
    Chn:"瘟疫之后，耶和华晓谕摩西和祭司亚伦的儿子以利亚撒说：",
    Eng:"After the plague the LORD said to Moses and Eleazar son of Aaron, the priest,",
    Ind:"Sesudah tulah itu berfirmanlah TUHAN kepada Musa dan kepada Eleazar, anak imam Harun:"
  },
  {Bible:"Numbers", Chapter:26, Verse:2, Page:1,
    Kor:"\"이스라엘 자손의 온 회중의 머리 수를 세어라. 스무 살부터 그 위로, 이스라엘에서 군대에 나갈 수 있는 이들을 모두 조상의 가문별로 세어라.\"",
    Chn:"「你们要将以色列全会众，按他们的宗族，凡以色列中从二十岁以外、能出去打仗的，计算总数。」",
    Eng:"\"Take a census of the whole Israelite community by families--all those twenty years old or more who are able to serve in the army of Israel.\"",
    Ind:"\"Hitunglah jumlah segenap umat Israel, yang berumur dua puluh tahun ke atas menurut suku mereka, semua orang yang sanggup berperang di antara orang Israel.\""
  },
  {Bible:"Numbers", Chapter:26, Verse:3, Page:1,
    Kor:"모세와 제사장 엘르아살은 여리고 건너편 요단 강 가의 모압 평지에서 백성에게 이 사실을 알리고, 이렇게 지시하였다.",
    Chn:"摩西和祭司以利亚撒在摩押平原与耶利哥相对的约旦河边向以色列人说：",
    Eng:"So on the plains of Moab by the Jordan across from Jericho, Moses and Eleazar the priest spoke with them and said,",
    Ind:"Lalu berkatalah Musa dan imam Eleazar kepada mereka di dataran Moab, di tepi sungai Yordan dekat Yerikho:"
  },
  {Bible:"Numbers", Chapter:26, Verse:4, Page:1,
    Kor:"\"주님께서 모세에게 명하신 대로, 스무 살부터 그 위로 남자의 수를 세시오.\" ○이집트 땅에서 나온 이스라엘 자손은 다음과 같다.",
    Chn:"「将你们中间从二十岁以外的计算总数」；是照耶和华吩咐出埃及地的摩西和以色列人的话。",
    Eng:"\"Take a census of the men twenty years old or more, as the LORD commanded Moses.\" These were the Israelites who came out of Egypt:",
    Ind:"\"Hitunglah jumlah semua orang yang berumur dua puluh tahun ke atas!\" --seperti yang diperintahkan TUHAN kepada Musa. Inilah orang Israel yang telah keluar dari tanah Mesir:"
  },
  {Bible:"Numbers", Chapter:26, Verse:5, Page:1,
    Kor:"○이스라엘의 맏아들은 르우벤이다. 르우벤의 자손은, 하녹에게서 난 하녹 가족과, 발루에게서 난 발루 가족과,",
    Chn:"以色列的长子是吕便。吕便的众子：属哈诺的，有哈诺族；属法路的，有法路族；",
    Eng:"The descendants of Reuben, the firstborn son of Israel, were: through Hanoch, the Hanochite clan; through Pallu, the Palluite clan;",
    Ind:"Ruben ialah anak sulung Israel; bani Ruben ialah dari Henokh kaum orang Henokh; dari Palu kaum orang Palu;"
  },
  {Bible:"Numbers", Chapter:26, Verse:6, Page:1,
    Kor:"헤스론에게서 난 헤스론 가족과, 갈미에게서 난 갈미 가족이다.",
    Chn:"属希斯伦的，有希斯伦族；属迦米的，有迦米族；",
    Eng:"through Hezron, the Hezronite clan; through Carmi, the Carmite clan.",
    Ind:"dari Hezron kaum orang Hezron dan dari Karmi kaum orang Karmi."
  },
  {Bible:"Numbers", Chapter:26, Verse:7, Page:1,
    Kor:"이들은 르우벤 가족이며, 등록된 이들은 사만 삼천칠백삼십 명이다.",
    Chn:"这就是吕便的各族；其中被数的，共有四万三千七百三十名。",
    Eng:"These were the clans of Reuben; those numbered were 43,730.",
    Ind:"Itulah kaum-kaum orang Ruben, dan orang-orang yang dicatat dari mereka berjumlah empat puluh tiga ribu tujuh ratus tiga puluh orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:8, Page:1,
    Kor:"○발루의 아들 가운데는 엘리압이 있었다.",
    Chn:"法路的儿子是以利押。",
    Eng:"The son of Pallu was Eliab,",
    Ind:"Adapun anak Palu ialah Eliab,"
  },
  {Bible:"Numbers", Chapter:26, Verse:9, Page:1,
    Kor:"엘리압의 아들은 느무엘과 다단과 아비람이다. 다단과 아비람은, 바로 모세와 아론에게 맞서 반역한 자들로서, 고라의 무리가 주님께 대항하여 반역할 때에 그들 가운데 있던 자들이며, 회중에서 부름받은 자들이다.",
    Chn:"以利押的众子是尼母利、大坍、亚比兰。这大坍、亚比兰，就是从会中选召的，与可拉一党同向耶和华争闹的时候也向摩西、亚伦争闹；",
    Eng:"and the sons of Eliab were Nemuel, Dathan and Abiram. The same Dathan and Abiram were the community officials who rebelled against Moses and Aaron and were among Korah's followers when they rebelled against the LORD.",
    Ind:"dan anak-anak Eliab ialah Nemuel, Datan dan Abiram. Datan dan Abiram, orang-orang yang dipilih oleh umat itu, ialah orang-orang yang telah membantah Musa dan Harun dalam kumpulan Korah, ketika mereka membantah TUHAN,"
  },
  {Bible:"Numbers", Chapter:26, Verse:10, Page:1,
    Kor:"땅이 그 입을 벌려, 고라와 함께 그들도 삼켰다. 그 무리가 죽을 때에, 불이 사람 이백오십 명을 살랐는데, 그들은 본보기가 되었다.",
    Chn:"地便开口吞了他们，和可拉、可拉的党类一同死亡。那时火烧灭了二百五十个人；他们就作了警戒。",
    Eng:"The earth opened its mouth and swallowed them along with Korah, whose followers died when the fire devoured the 250 men. And they served as a warning sign.",
    Ind:"tetapi bumi membuka mulutnya dan menelan mereka bersama-sama dengan Korah, ketika kumpulan itu mati, ketika kedua ratus lima puluh orang itu dimakan api, sehingga mereka menjadi peringatan."
  },
  {Bible:"Numbers", Chapter:26, Verse:11, Page:1,
    Kor:"그렇지만 고라의 자손은 죽지 않았다.",
    Chn:"然而可拉的众子没有死亡。",
    Eng:"The line of Korah, however, did not die out.",
    Ind:"Tetapi anak-anak Korah tidaklah mati."
  },
  {Bible:"Numbers", Chapter:26, Verse:12, Page:1,
    Kor:"○시므온 자손은 가족별로, 느무엘에게서 난 느무엘 가족과, 야민에게서 난 야민 가족과, 야긴에게서 난 야긴 가족과,",
    Chn:"按着家族，西缅的众子：属尼母利的，有尼母利族；属雅悯的，有雅悯族；属雅斤的，有雅斤族；",
    Eng:"The descendants of Simeon by their clans were: through Nemuel, the Nemuelite clan; through Jamin, the Jaminite clan; through Jakin, the Jakinite clan;",
    Ind:"Bani Simeon, menurut kaum mereka, ialah: dari Nemuel kaum orang Nemuel; dari Yamin kaum orang Yamin; dari Yakhin kaum orang Yakhin;"
  },
  {Bible:"Numbers", Chapter:26, Verse:13, Page:1,
    Kor:"세라에게서 난 세라 가족과, 사울에게서 난 사울 가족이다.",
    Chn:"属谢拉的，有谢拉族；属扫罗的，有扫罗族。",
    Eng:"through Zerah, the Zerahite clan; through Shaul, the Shaulite clan.",
    Ind:"dari Zerah kaum orang Zerah dan dari Saul kaum orang Saul."
  },
  {Bible:"Numbers", Chapter:26, Verse:14, Page:1,
    Kor:"이들은 시므온 가족이며, 등록된 이들은 이만 이천이백 명이다.",
    Chn:"这就是西缅的各族，共有二万二千二百名。",
    Eng:"These were the clans of Simeon; there were 22,200 men.",
    Ind:"Itulah kaum-kaum orang Simeon, dua puluh dua ribu dua ratus orang banyaknya."
  },
  {Bible:"Numbers", Chapter:26, Verse:15, Page:1,
    Kor:"○갓 자손은 가족별로, 스본에게서 난 스본 가족과, 학기에게서 난 학기 가족과, 수니에게서 난 수니 가족과,",
    Chn:"按着家族，迦得的众子：属洗分的，有洗分族；属哈基的，有哈基族；属书尼的，有书尼族；",
    Eng:"The descendants of Gad by their clans were: through Zephon, the Zephonite clan; through Haggi, the Haggite clan; through Shuni, the Shunite clan;",
    Ind:"Bani Gad, menurut kaum mereka, ialah: dari Zefon kaum orang Zefon; dari Hagi kaum orang Hagi; dari Syuni kaum orang Syuni;"
  },
  {Bible:"Numbers", Chapter:26, Verse:16, Page:1,
    Kor:"오스니에게서 난 오스니 가족과, 에리에게서 난 에리 가족과,",
    Chn:"属阿斯尼的，有阿斯尼族；属以利的，有以利族；",
    Eng:"through Ozni, the Oznite clan; through Eri, the Erite clan;",
    Ind:"dari Ozni kaum orang Ozni, dari Eri kaum orang Eri;"
  },
  {Bible:"Numbers", Chapter:26, Verse:17, Page:1,
    Kor:"아롯에게서 난 아롯 가족과, 아렐리에게서 난 아렐리 가족이다.",
    Chn:"属亚律的，有亚律族；属亚列利的，有亚列利族。",
    Eng:"through Arodi, the Arodite clan; through Areli, the Arelite clan.",
    Ind:"dari Arod kaum orang Arod dan dari Areli kaum orang Areli."
  },
  {Bible:"Numbers", Chapter:26, Verse:18, Page:1,
    Kor:"이들은 갓 자손의 가족이며, 등록된 이들은 사만 오백 명이다.",
    Chn:"这就是迦得子孙的各族，照他们中间被数的，共有四万零五百名。",
    Eng:"These were the clans of Gad; those numbered were 40,500.",
    Ind:"Itulah kaum-kaum bani Gad, dan orang-orang yang dicatat dari mereka berjumlah empat puluh ribu lima ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:19, Page:1,
    Kor:"○유다의 아들들은 에르와 오난이다. 에르와 오난은 가나안 땅에서 죽었다.",
    Chn:"犹大的儿子是珥和俄南。这珥和俄南死在迦南地。",
    Eng:"Er and Onan were sons of Judah, but they died in Canaan.",
    Ind:"Anak-anak Yehuda ialah: Er dan Onan; tetapi Er dan Onan itu mati di tanah Kanaan."
  },
  {Bible:"Numbers", Chapter:26, Verse:20, Page:1,
    Kor:"○유다 자손은 가족별로, 셀라에게서 난 셀라 가족과, 베레스에게서 난 베레스 가족과, 세라에게서 난 세라 가족이다.",
    Chn:"按着家族，犹大其余的众子：属示拉的，有示拉族；属法勒斯的，有法勒斯族；属谢拉的有谢拉族。",
    Eng:"The descendants of Judah by their clans were: through Shelah, the Shelanite clan; through Perez, the Perezite clan; through Zerah, the Zerahite clan.",
    Ind:"Bani Yehuda, menurut kaum mereka, ialah: dari Syela kaum orang Syela; dari Peres kaum orang Peres dan dari Zerah kaum orang Zerah."
  },
  {Bible:"Numbers", Chapter:26, Verse:21, Page:1,
    Kor:"베레스 자손은 헤스론에게서 난 헤스론 가족과, 하물에게서 난 하물 가족이다.",
    Chn:"法勒斯的儿子：属希斯 的，有希斯 族；属哈母勒的，有哈母勒族。",
    Eng:"The descendants of Perez were: through Hezron, the Hezronite clan; through Hamul, the Hamulite clan.",
    Ind:"Bani Peres ialah: dari Hezron kaum orang Hezron dan dari Hamul kaum orang Hamul."
  },
  {Bible:"Numbers", Chapter:26, Verse:22, Page:1,
    Kor:"이들은 유다 가족이며, 등록된 이들은 칠만 육천오백 명이다.",
    Chn:"这就是犹大的各族，照他们中间被数的，共有七万六千五百名。",
    Eng:"These were the clans of Judah; those numbered were 76,500.",
    Ind:"Itulah kaum-kaum Yehuda, dan orang-orang yang dicatat dari mereka berjumlah tujuh puluh enam ribu lima ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:23, Page:1,
    Kor:"○잇사갈 자손은 가족별로, 돌라에게서 난 돌라 가족과, 부와에게서 난 부니 가족과,",
    Chn:"按着家族，以萨迦的众子：属陀拉的，有陀拉族；属普瓦的，有普瓦族；",
    Eng:"The descendants of Issachar by their clans were: through Tola, the Tolaite clan; through Puah, the Puite clan;",
    Ind:"Bani Isakhar, menurut kaum mereka, ialah: dari Tola kaum orang Tola; dari Pua kaum orang Pua;"
  },
  {Bible:"Numbers", Chapter:26, Verse:24, Page:1,
    Kor:"야숩에게서 난 야숩 가족과, 시므론에게서 난 시므론 가족이다.",
    Chn:"属雅述的，有雅述族；属伸 的，有伸 族。",
    Eng:"through Jashub, the Jashubite clan; through Shimron, the Shimronite clan.",
    Ind:"dari Yasub kaum orang Yasub dan dari Simron kaum orang Simron."
  },
  {Bible:"Numbers", Chapter:26, Verse:25, Page:1,
    Kor:"이들은 잇사갈 가족이며, 등록된 이들은 육만 사천삼백 명이다.",
    Chn:"这就是以萨迦的各族，照他们中间被数的，共有六万四千三百名。",
    Eng:"These were the clans of Issachar; those numbered were 64,300.",
    Ind:"Itulah kaum-kaum Isakhar, dan orang-orang yang dicatat dari mereka, berjumlah enam puluh empat ribu tiga ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:26, Page:1,
    Kor:"○스불론 자손은 가족별로, 세렛에게서 난 세렛 가족과, 엘론에게서 난 엘론 가족과, 얄르엘에게서 난 얄르엘 가족이다.",
    Chn:"按着家族，西布伦的众子：属西烈的，有西烈族；属以伦的，有以伦族；属雅利的，有雅利族。",
    Eng:"The descendants of Zebulun by their clans were: through Sered, the Seredite clan; through Elon, the Elonite clan; through Jahleel, the Jahleelite clan.",
    Ind:"Bani Zebulon, menurut kaum mereka, ialah: dari Sered kaum orang Sered; dari Elon kaum orang Elon dan dari Yahleel kaum orang Yahleel."
  },
  {Bible:"Numbers", Chapter:26, Verse:27, Page:1,
    Kor:"이들은 스불론 가족이며, 등록된 이들은 육만 오백 명이다.",
    Chn:"这就是西布伦的各族，照他们中间被数的，共有六万零五百名。",
    Eng:"These were the clans of Zebulun; those numbered were 60,500.",
    Ind:"Itulah kaum-kaum orang Zebulon, dan orang-orang yang dicatat dari mereka berjumlah enam puluh ribu lima ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:28, Page:1,
    Kor:"○요셉 자손은, 가족별로는 므낫세와 에브라임으로 나뉜다.",
    Chn:"按着家族，约瑟的儿子有玛拿西、以法莲。",
    Eng:"The descendants of Joseph by their clans through Manasseh and Ephraim were:",
    Ind:"Keturunan Yusuf, menurut kaum mereka, ialah orang Manasye dan orang Efraim."
  },
  {Bible:"Numbers", Chapter:26, Verse:29, Page:1,
    Kor:"○므낫세 자손은, 마길에게서 난 마길 가족과, 마길의 아들인 길르앗에게서 난 길르앗 가족이다.",
    Chn:"玛拿西的众子：属玛吉的，有玛吉族；玛吉生基列；属基列的，有基列族。",
    Eng:"The descendants of Manasseh: through Makir, the Makirite clan (Makir was the father of Gilead); through Gilead, the Gileadite clan.",
    Ind:"Bani Manasye ialah: dari Makhir kaum orang Makhir; dan Makhir beranakkan Gilead; dari Gilead kaum orang Gilead."
  },
  {Bible:"Numbers", Chapter:26, Verse:30, Page:1,
    Kor:"길르앗 자손은, 이에셀에게서 난 이에셀 가족과, 헬렉에게서 난 헬렉 가족과,",
    Chn:"基列的众子：属伊以谢的，有伊以谢族；属希勒的，有希勒族；",
    Eng:"These were the descendants of Gilead: through Iezer, the Iezerite clan; through Helek, the Helekite clan;",
    Ind:"Inilah bani Gilead: dari Iezer kaum orang Iezer; dari Helek kaum orang Helek;"
  },
  {Bible:"Numbers", Chapter:26, Verse:31, Page:1,
    Kor:"아스리엘에게서 난 아스리엘 가족과, 세겜에게서 난 세겜 가족과,",
    Chn:"属亚斯烈的，有亚斯烈族；属示剑的，有示剑族；",
    Eng:"through Asriel, the Asrielite clan; through Shechem, the Shechemite clan;",
    Ind:"dari Asriel kaum orang Asriel; dari Sekhem kaum orang Sekhem;"
  },
  {Bible:"Numbers", Chapter:26, Verse:32, Page:1,
    Kor:"스미다에게서 난 스미다 가족과, 헤벨에게서 난 헤벨 가족이다.",
    Chn:"属示米大的，有示米大族；属希弗的，有希弗族。",
    Eng:"through Shemida, the Shemidaite clan; through Hepher, the Hepherite clan.",
    Ind:"dari Semida kaum orang Semida dan dari Hefer kaum orang Hefer."
  },
  {Bible:"Numbers", Chapter:26, Verse:33, Page:1,
    Kor:"헤벨의 아들 슬로브핫에게는 아들이 없다. 그에게는 오직 딸들만 있는데, 그 딸들의 이름은 말라와 노아와 호글라와 밀가와 디르사이다.",
    Chn:"希弗的儿子：西罗非哈没儿子，只有女儿。西罗非哈女儿的名字就是玛拉、挪阿、曷拉、密迦、得撒。",
    Eng:"(Zelophehad son of Hepher had no sons; he had only daughters, whose names were Mahlah, Noah, Hoglah, Milcah and Tirzah.)",
    Ind:"Adapun Zelafehad bin Hefer tidak mempunyai anak laki-laki, tetapi anak perempuan saja, dan nama anak-anak perempuan Zelafehad ialah Mahla, Noa, Hogla, Milka dan Tirza."
  },
  {Bible:"Numbers", Chapter:26, Verse:34, Page:1,
    Kor:"이들은 므낫세 가족이며, 등록된 이들은 오만 이천칠백 명이다.",
    Chn:"这就是玛拿西的各族；他们中间被数的，共有五万二千七百名。",
    Eng:"These were the clans of Manasseh; those numbered were 52,700.",
    Ind:"Itulah kaum-kaum Manasye, dan orang-orang yang dicatat dari mereka berjumlah lima puluh dua ribu tujuh ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:35, Page:1,
    Kor:"○에브라임 자손은 가족별로, 수델라에게서 난 수델라 가족과, 베겔에게서 난 베겔 가족과, 다한에게서 난 다한 가족이다.",
    Chn:"按着家族，以法莲的众子：属书提拉的，有书提拉族；属比结的，有比结族；属他罕的，有他罕族。",
    Eng:"These were the descendants of Ephraim by their clans: through Shuthelah, the Shuthelahite clan; through Beker, the Bekerite clan; through Tahan, the Tahanite clan.",
    Ind:"Inilah bani Efraim, menurut kaum mereka: dari Sutelah kaum orang Sutelah; dari Bekher kaum orang Bekher dan dari Tahan kaum orang Tahan."
  },
  {Bible:"Numbers", Chapter:26, Verse:36, Page:1,
    Kor:"수델라 자손은 에란에게서 난 에란 가족이다.",
    Chn:"书提拉的众子：属以兰的，有以兰族。",
    Eng:"These were the descendants of Shuthelah: through Eran, the Eranite clan.",
    Ind:"Dan inilah bani Sutelah: dari Eran kaum orang Eran."
  },
  {Bible:"Numbers", Chapter:26, Verse:37, Page:1,
    Kor:"이들은 에브라임 자손 가족이다. 등록된 이들은 삼만 이천오백 명이다. 이것은 요셉 자손을 그 가족별로 나누어 본 것이다.",
    Chn:"这就是以法莲子孙的各族，照他们中间被数的，共有三万二千五百名。按着家族，这都是约瑟的子孙。",
    Eng:"These were the clans of Ephraim; those numbered were 32,500. These were the descendants of Joseph by their clans.",
    Ind:"Itulah kaum-kaum bani Efraim, dan orang-orang yang dicatat dari mereka berjumlah tiga puluh dua ribu lima ratus orang banyaknya. Itulah bani Yusuf menurut kaum mereka."
  },
  {Bible:"Numbers", Chapter:26, Verse:38, Page:1,
    Kor:"○베냐민 자손은 가족별로, 벨라에게서 난 벨라 가족과, 아스벨에게서 난 아스벨 가족과, 아히람에게서 난 아히람 가족과,",
    Chn:"按着家族，便雅悯的众子：属比拉的，有比拉族；属亚实别的，有亚实别族；属亚希兰的，有亚希兰族；",
    Eng:"The descendants of Benjamin by their clans were: through Bela, the Belaite clan; through Ashbel, the Ashbelite clan; through Ahiram, the Ahiramite clan;",
    Ind:"Bani Benyamin, menurut kaum mereka, ialah: dari Bela kaum orang Bela; dari Asybel kaum orang Asybel; dari Ahiram kaum orang Ahiram;"
  },
  {Bible:"Numbers", Chapter:26, Verse:39, Page:1,
    Kor:"스부밤에게서 난 스부밤 가족과, 후밤에게서 난 후밤 가족이다.",
    Chn:"属书反的，有书反族；属户反的，有户反族。",
    Eng:"through Shupham, the Shuphamite clan; through Hupham, the Huphamite clan.",
    Ind:"dari Sefufam kaum orang Sefufam dan dari Hufam kaum orang Hufam."
  },
  {Bible:"Numbers", Chapter:26, Verse:40, Page:1,
    Kor:"벨라 자손은 아릇과 나아만이다. 아릇에게서 난 아릇 가족과, 나아만에게서 난 나아만 가족이다.",
    Chn:"比拉的众子是亚勒、乃幔。属 亚勒 的，有亚勒族；属乃幔的，有乃幔族。",
    Eng:"The descendants of Bela through Ard and Naaman were: through Ard, the Ardite clan; through Naaman, the Naamite clan.",
    Ind:"Dan anak-anak Bela ialah Ared dan Naaman; dari Ared kaum orang Ared dan dari Naaman kaum orang Naaman."
  },
  {Bible:"Numbers", Chapter:26, Verse:41, Page:1,
    Kor:"이들은 가족별로 본 베냐민 자손이며, 등록된 이들은 사만 오천육백 명이다.",
    Chn:"按着家族，这就是便雅悯的子孙，其中被数的，共有四万五千六百名。",
    Eng:"These were the clans of Benjamin; those numbered were 45,600.",
    Ind:"Itulah bani Benyamin menurut kaum mereka, dan orang-orang yang dicatat dari mereka berjumlah empat puluh lima ribu enam ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:42, Page:1,
    Kor:"○다음은 단 자손을 가족별로 본 것이다. 수함에게서 수함 가족이 났다. 이들은 가족별로 본 단 가족들이다.",
    Chn:"按着家族，但的众子：属书含的，有书含族。按着家族，这就是但的各族。",
    Eng:"These were the descendants of Dan by their clans: through Shuham, the Shuhamite clan. These were the clans of Dan:",
    Ind:"Inilah bani Dan, menurut kaum mereka: dari Suham kaum orang Suham. Itulah kaum-kaum Dan menurut kaum mereka."
  },
  {Bible:"Numbers", Chapter:26, Verse:43, Page:1,
    Kor:"이들은 모두 수함 가족이며, 등록된 이들은 육만 사천사백 명이다.",
    Chn:"照其中被数的，书含所有的各族，共有六万四千四百名。",
    Eng:"All of them were Shuhamite clans; and those numbered were 64,400.",
    Ind:"Segala kaum orang Suham, orang-orang yang dicatat dari mereka berjumlah enam puluh empat ribu empat ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:44, Page:1,
    Kor:"○아셀 자손은 가족별로 보면, 임나에게서 난 임나 가족과, 이스위에게서 난 이스위 가족과, 브리아에게서 난 브리아 가족이다.",
    Chn:"按着家族，亚设的众子：属音拿的，有音拿族；属亦施韦的，有亦施韦族；属比利亚的，有比利亚族。",
    Eng:"The descendants of Asher by their clans were: through Imnah, the Imnite clan; through Ishvi, the Ishvite clan; through Beriah, the Beriite clan;",
    Ind:"Bani Asyer, menurut kaum mereka, ialah: dari Yimna kaum orang Yimna; dari Yiswi kaum orang Yiswi dan dari Beria kaum orang Beria."
  },
  {Bible:"Numbers", Chapter:26, Verse:45, Page:1,
    Kor:"브리아 자손은, 헤벨에게서 난 헤벨 가족과, 말기엘에게서 난 말기엘 가족이다.",
    Chn:"比利亚的众子：属希别的，有希别族；属玛结的，有玛结族。",
    Eng:"and through the descendants of Beriah: through Heber, the Heberite clan; through Malkiel, the Malkielite clan.",
    Ind:"Mengenai bani Beria: dari Heber kaum orang Heber dan dari Malkiel kaum orang Malkiel."
  },
  {Bible:"Numbers", Chapter:26, Verse:46, Page:1,
    Kor:"아셀에게는 딸이 있었는데, 그 이름은 세라이다.",
    Chn:"亚设的女儿名叫西拉。",
    Eng:"(Asher had a daughter named Serah.)",
    Ind:"Dan nama anak perempuan Asyer ialah Serah."
  },
  {Bible:"Numbers", Chapter:26, Verse:47, Page:1,
    Kor:"이들은 아셀 가족이며, 등록된 이들은 오만 삼천사백 명이다.",
    Chn:"这就是亚设子孙的各族，照他们中间被数的，共有五万三千四百名。",
    Eng:"These were the clans of Asher; those numbered were 53,400.",
    Ind:"Itulah kaum-kaum bani Asyer, dan orang-orang yang dicatat dari mereka berjumlah lima puluh tiga ribu empat ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:48, Page:1,
    Kor:"○납달리 자손은 가족별로, 야스엘에게서 난 야스엘 가족과, 구니에게서 난 구니 가족과,",
    Chn:"按着家族，拿弗他利的众子：属雅薛的，有雅薛族；属沽尼的，有沽尼族；",
    Eng:"The descendants of Naphtali by their clans were: through Jahzeel, the Jahzeelite clan; through Guni, the Gunite clan;",
    Ind:"Bani Naftali, menurut kaum mereka, ialah: dari Yahzeel kaum orang Yahzeel; dari Guni kaum orang Guni;"
  },
  {Bible:"Numbers", Chapter:26, Verse:49, Page:1,
    Kor:"예셀에게서 난 예셀 가족과, 실렘에게서 난 실렘 가족이다.",
    Chn:"属耶色的，有耶色族；属示冷的，有示冷族。",
    Eng:"through Jezer, the Jezerite clan; through Shillem, the Shillemite clan.",
    Ind:"dari Yezer kaum orang Yezer dan dari Syilem kaum orang Syilem."
  },
  {Bible:"Numbers", Chapter:26, Verse:50, Page:1,
    Kor:"이들은 가족별로 본 납달리 가족이며, 등록된 이들은 사만 오천사백 명이다.",
    Chn:"按着家族，这就是拿弗他利的各族；他们中间被数的，共有四万五千四百名。",
    Eng:"These were the clans of Naphtali; those numbered were 45,400.",
    Ind:"Itulah kaum-kaum Naftali menurut kaum mereka, dan orang-orang yang dicatat dari mereka berjumlah empat puluh lima ribu empat ratus orang."
  },
  {Bible:"Numbers", Chapter:26, Verse:51, Page:1,
    Kor:"○이들과 같이 등록된 이스라엘 자손은, 모두 육십만 천칠백삼십 명이었다.",
    Chn:"以色列人中被数的，共有六十万零一千七百三十名。",
    Eng:"The total number of the men of Israel was 601,730.",
    Ind:"Itulah orang-orang yang dicatat dari orang Israel, enam ratus satu ribu tujuh ratus tiga puluh orang banyaknya."
  },
  {Bible:"Numbers", Chapter:26, Verse:52, Page:1,
    Kor:"○주님께서 모세에게 말씀하셨다.",
    Chn:"耶和华晓谕摩西说：",
    Eng:"The LORD said to Moses,",
    Ind:"TUHAN berfirman kepada Musa:"
  },
  {Bible:"Numbers", Chapter:26, Verse:53, Page:1,
    Kor:"\"땅은 사람 수에 따라서, 그들의 유산으로 나누어 주어야 한다.",
    Chn:"「你要按着人名的数目将地分给这些人为业。",
    Eng:"\"The land is to be allotted to them as an inheritance based on the number of names.",
    Ind:"\"Kepada suku-suku itulah harus dibagikan tanah itu menjadi milik pusaka menurut nama-nama yang dicatat;"
  },
  {Bible:"Numbers", Chapter:26, Verse:54, Page:1,
    Kor:"사람이 많으면 유산을 많이 주어야 하고, 사람이 적으면 유산을 적게 주어야 한다. 유산은 등록된 사람 수에 따라서, 각기 나누어 주어야 한다.",
    Chn:"人多的，你要把产业多分给他们；人少的，你要把产业少分给他们；要照被数的人数，把产业分给各人。",
    Eng:"To a larger group give a larger inheritance, and to a smaller group a smaller one; each is to receive its inheritance according to the number of those listed.",
    Ind:"kepada yang besar jumlahnya haruslah engkau memberikan milik pusaka yang besar dan kepada yang kecil jumlahnya haruslah engkau memberikan milik pusaka yang kecil; kepada setiap suku sesuai dengan jumlah orang-orangnya yang dicatat haruslah diberikan milik pusaka."
  },
  {Bible:"Numbers", Chapter:26, Verse:55, Page:1,
    Kor:"유산으로 받는 땅은 오직 제비를 뽑아 나누어야 하고, 그들은 그것을 조상 때부터 내려오는 지파의 이름으로 물려받아야 한다.",
    Chn:"虽是这样，还要拈阄分地。他们要按着祖宗各支派的名字承受为业。",
    Eng:"Be sure that the land is distributed by lot. What each group inherits will be according to the names for its ancestral tribe.",
    Ind:"Tetapi tanah itu harus dibagikan dengan membuang undi; menurut nama suku-suku nenek moyang mereka haruslah mereka mendapat milik pusaka;"
  },
  {Bible:"Numbers", Chapter:26, Verse:56, Page:1,
    Kor:"각 유산은 제비를 뽑아 나누어야 한다. 사람 수가 많은 지파들은 큰 땅을, 사람 수가 적은 지파들은 적은 땅을 놓고 추첨하여야 한다.\"",
    Chn:"要按着所拈的阄，看人数多，人数少，把产业分给他们。」",
    Eng:"Each inheritance is to be distributed by lot among the larger and smaller groups.\"",
    Ind:"seperti yang ditunjukkan undian haruslah dibagikan milik pusaka setiap suku, di antara yang besar dan yang kecil jumlahnya.\""
  },
  {Bible:"Numbers", Chapter:26, Verse:57, Page:1,
    Kor:"○가족별로 등록된 레위 사람은, 게르손에게서 난 게르손 가족과, 고핫에게서 난 고핫 가족과, 므라리에게서 난 므라리 가족이다.",
    Chn:"利未人，按着他们的各族被数的：属革顺的，有革顺族；属哥辖的，有哥辖族；属米拉利的，有米拉利族。",
    Eng:"These were the Levites who were counted by their clans: through Gershon, the Gershonite clan; through Kohath, the Kohathite clan; through Merari, the Merarite clan.",
    Ind:"Inilah orang-orang yang dicatat dari orang Lewi, menurut kaum mereka: dari Gerson kaum orang Gerson; dari Kehat kaum orang Kehat dan dari Merari kaum orang Merari."
  },
  {Bible:"Numbers", Chapter:26, Verse:58, Page:1,
    Kor:"다음은 레위 가족인데, 립니 가족과 헤브론 가족과 마흘리 가족과 무시 가족과 고라 가족이다. 고핫은 아므람을 낳았으며,",
    Chn:"利未的各族有立尼族、希伯伦族、玛利族、母示族、可拉族。哥辖生暗兰。",
    Eng:"These also were Levite clans: the Libnite clan, the Hebronite clan, the Mahlite clan, the Mushite clan, the Korahite clan. (Kohath was the forefather of Amram;",
    Ind:"Inilah kaum-kaum Lewi: kaum orang Libni, kaum orang Hebron, kaum orang Mahli, kaum orang Musi dan kaum orang Korah. Adapun Kehat beranakkan Amram."
  },
  {Bible:"Numbers", Chapter:26, Verse:59, Page:1,
    Kor:"아므람의 아내의 이름은 요게벳인데, 그는 레위가 이집트에서 얻은 딸이다. 요게벳은 아므람에게서 아론과 모세와 그 누이 미리암을 낳았다.",
    Chn:"暗兰的妻名叫约基别，是利未女子，生在埃及。她给暗兰生了亚伦、摩西，并他们的姊姊米利暗。",
    Eng:"the name of Amram's wife was Jochebed, a descendant of Levi, who was born to the Levites in Egypt. To Amram she bore Aaron, Moses and their sister Miriam.",
    Ind:"Dan nama isteri Amram ialah Yokhebed, anak perempuan Lewi, yang dilahirkan bagi Lewi di Mesir; dan bagi Amram perempuan itu melahirkan Harun dan Musa dan Miryam, saudara mereka yang perempuan."
  },
  {Bible:"Numbers", Chapter:26, Verse:60, Page:1,
    Kor:"아론에게서는 나답과 아비후와 엘르아살과 이다말이 태어났다.",
    Chn:"亚伦生拿答、亚比户、以利亚撒、以他玛。",
    Eng:"Aaron was the father of Nadab and Abihu, Eleazar and Ithamar.",
    Ind:"Pada Harun lahir Nadab dan Abihu, Eleazar dan Itamar."
  },
  {Bible:"Numbers", Chapter:26, Verse:61, Page:1,
    Kor:"그러나 나답과 아비후는 금지된 불을 주 앞에 드리다가 죽었다.",
    Chn:"拿答、亚比户在耶和华面前献凡火的时候就死了。",
    Eng:"But Nadab and Abihu died when they made an offering before the LORD with unauthorized fire.)",
    Ind:"Tetapi Nadab dan Abihu mati, ketika mereka mempersembahkan persembahan api yang asing ke hadapan TUHAN."
  },
  {Bible:"Numbers", Chapter:26, Verse:62, Page:1,
    Kor:"○난 지 한 달 된 사람으로부터 그 위로 등록된 모든 레위 남자는 이만 삼천 명이다. 이스라엘 자손 가운데서 그들에게만은 땅을 유산으로 주지 않았기 때문에, 그들은 다른 이스라엘 자손이 등록된 명부에는 오르지 않았다.",
    Chn:"利未人中，凡一个月以外、被数的男丁，共有二万三千。他们本来没有数在以色列人中；因为在以色列人中，没有分给他们产业。",
    Eng:"All the male Levites a month old or more numbered 23,000. They were not counted along with the other Israelites because they received no inheritance among them.",
    Ind:"Dan orang-orang yang dicatat dari mereka berjumlah dua puluh tiga ribu orang, semuanya laki-laki, yang berumur satu bulan ke atas, sebab mereka tidak dicatat bersama-sama dengan orang Israel, karena mereka tidak diberikan milik pusaka di tengah-tengah orang Israel."
  },
  {Bible:"Numbers", Chapter:26, Verse:63, Page:1,
    Kor:"○이들은, 모세와 제사장 엘르아살이 여리고 맞은편 요단 강 가 모압 평지에서 이스라엘 자손의 인구를 조사할 때에, 그들이 등록시킨 이들이다.",
    Chn:"这些就是被摩西和祭司以利亚撒所数的；他们在摩押平原与耶利哥相对的约旦河边数点以色列人。",
    Eng:"These are the ones counted by Moses and Eleazar the priest when they counted the Israelites on the plains of Moab by the Jordan across from Jericho.",
    Ind:"Itulah orang-orang yang dicatat oleh Musa dan imam Eleazar, ketika keduanya mencatat orang-orang Israel di dataran Moab di tepi sungai Yordan dekat Yerikho."
  },
  {Bible:"Numbers", Chapter:26, Verse:64, Page:1,
    Kor:"등록된 사람들 가운데는, 모세와 제사장 아론이 시내 광야에서 이스라엘 자손의 인구를 조사할 때에 등록시켰던 사람은 한 명도 들어 있지 않았다.",
    Chn:"但被数的人中，没有一个是摩西和祭司亚伦从前在西奈的旷野所数的以色列人，",
    Eng:"Not one of them was among those counted by Moses and Aaron the priest when they counted the Israelites in the Desert of Sinai.",
    Ind:"Di antara mereka tidak ada terdapat seorangpun yang dicatat Musa dan imam Harun, ketika keduanya mencatat orang Israel di padang gurun Sinai"
  },
  {Bible:"Numbers", Chapter:26, Verse:65, Page:1,
    Kor:"주님께서, 그들이 광야에서 반드시 죽을 것이라고 말씀하셨기 때문이다. 여분네의 아들 갈렙과 눈의 아들 여호수아를 제외하고는, 그들 가운데서 어느 한 사람도 살아 남지 못하였다.",
    Chn:"因为耶和华论到他们说：「他们必要死在旷野。」所以，除了耶孚尼的儿子迦勒和嫩的儿子约书亚以外，连一个人也没有存留。",
    Eng:"For the LORD had told those Israelites they would surely die in the desert, and not one of them was left except Caleb son of Jephunneh and Joshua son of Nun.",
    Ind:"sebab TUHAN telah berfirman tentang mereka: \"Pastilah mereka mati di padang gurun.\" Dari mereka itu tidak ada seorangpun yang masih tinggal hidup selain dari Kaleb bin Yefune dan Yosua bin Nun."
  },
]);
