// 민수기 33장 · Numbers 33
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Numbers",33,56);
BibleDB.add([
  {Bible:"Numbers", Chapter:33, Verse:1, Page:1,
    Kor:"<이집트에서 모압까지> 이스라엘 자손이 모세와 아론의 지휘를 받아 부대를 편성하여, 이집트에서 나와서 행군한 경로는 다음과 같다.",
    Chn:"以色列人按着军队，在摩西、亚伦的手下出埃及地所行的路程记在下面。",
    Eng:"Here are the stages in the journey of the Israelites when they came out of Egypt by divisions under the leadership of Moses and Aaron.",
    Ind:"Inilah tempat-tempat persinggahan orang Israel, setelah mereka keluar dari tanah Mesir, pasukan demi pasukan, di bawah pimpinan Musa dan Harun;"
  },
  {Bible:"Numbers", Chapter:33, Verse:2, Page:1,
    Kor:"모세는 주님의 명에 따라, 머물렀다가 떠난 출발지를 기록하였다. 머물렀다가 떠난 출발지는 다음과 같다.",
    Chn:"摩西遵着耶和华的吩咐记载他们所行的路程，其路程乃是这样：",
    Eng:"At the LORD'S command Moses recorded the stages in their journey. This is their journey by stages:",
    Ind:"Musa menuliskan perjalanan mereka dari tempat persinggahan ke tempat persinggahan sesuai dengan titah TUHAN; dan inilah tempat-tempat persinggahan mereka dalam perjalanan mereka:"
  },
  {Bible:"Numbers", Chapter:33, Verse:3, Page:1,
    Kor:"○이스라엘 자손이 라암셋을 떠난 것은 첫째 달 십오일, 곧 유월절 다음날이었다. 그들은 모든 이집트 사람이 훤히 보는 앞에서, 팔을 휘저으며 당당하게 행군하여 나왔다.",
    Chn:"正月十五日，就是逾越节的次日，以色列人从兰塞起行，在一切埃及人眼前昂然无惧地出去。",
    Eng:"The Israelites set out from Rameses on the fifteenth day of the first month, the day after the Passover. They marched out boldly in full view of all the Egyptians,",
    Ind:"Mereka berangkat dari Rameses pada bulan yang pertama, pada hari yang kelima belas bulan yang pertama itu; pada hari sesudah Paskah berjalanlah orang Israel keluar, oleh tangan yang dinaikkan, di depan mata semua orang Mesir,"
  },
  {Bible:"Numbers", Chapter:33, Verse:4, Page:1,
    Kor:"그 때에 이집트 사람은 주님께서 쳐죽이신 자기들의 맏아들들의 장례를 치르고 있었다. 주님께서는 이집트 사람이 섬기는 신들에게도 큰 벌을 내리셨다.",
    Chn:"那时，埃及人正葬埋他们的长子，就是耶和华在他们中间所击杀的；耶和华也败坏他们的神。",
    Eng:"who were burying all their firstborn, whom the LORD had struck down among them; for the LORD had brought judgment on their gods.",
    Ind:"sementara orang Mesir sedang menguburkan orang-orang yang telah dibunuh TUHAN di antara mereka, yakni semua anak sulung; sebab TUHAN telah menjatuhkan hukuman-hukuman kepada para allah mereka."
  },
  {Bible:"Numbers", Chapter:33, Verse:5, Page:1,
    Kor:"○이스라엘 자손은 라암셋을 떠나 숙곳에 이르러 진을 쳤다.",
    Chn:"以色列人从兰塞起行，安营在疏割。",
    Eng:"The Israelites left Rameses and camped at Succoth.",
    Ind:"Berangkatlah orang Israel dari Rameses, lalu berkemah di Sukot."
  },
  {Bible:"Numbers", Chapter:33, Verse:6, Page:1,
    Kor:"숙곳을 떠나서는 광야가 시작되는 에담에 이르러 진을 쳤다.",
    Chn:"从疏割起行，安营在旷野边的以倘。",
    Eng:"They left Succoth and camped at Etham, on the edge of the desert.",
    Ind:"Mereka berangkat dari Sukot, lalu berkemah di Etam yang di tepi padang gurun."
  },
  {Bible:"Numbers", Chapter:33, Verse:7, Page:1,
    Kor:"에담을 떠나서는 비하히롯으로 돌아갔다. 바알스본의 동쪽으로 가서 믹돌 부근에 이르러 진을 쳤다.",
    Chn:"从以倘起行，转到比哈·希录，是在巴力·洗分对面，就在密夺安营。",
    Eng:"They left Etham, turned back to Pi Hahiroth, to the east of Baal Zephon, and camped near Migdol.",
    Ind:"Mereka berangkat dari Etam, lalu balik kembali ke Pi-Hahirot yang di depan Baal-Zefon, kemudian berkemah di tentangan Migdol."
  },
  {Bible:"Numbers", Chapter:33, Verse:8, Page:1,
    Kor:"비하히롯을 떠나서는 a바다 한가운데를 지나 광야로 빠졌다. 에담 광야에서는 사흘 길을 들어가서 마라에 이르러 진을 쳤다.(a '홍해'. 히, '얌 쑤프')",
    Chn:"从比哈·希录对面起行，经过海中到了书珥旷野，又在伊坦的旷野走了三天的路程，就安营在玛拉。",
    Eng:"They left Pi Hahiroth and passed through the sea into the desert, and when they had traveled for three days in the Desert of Etham, they camped at Marah.",
    Ind:"Mereka berangkat dari Pi-Hahirot dan lewat dari tengah-tengah laut ke padang gurun, lalu mereka berjalan tiga hari perjalanan jauhnya di padang gurun Etam, kemudian mereka berkemah di Mara."
  },
  {Bible:"Numbers", Chapter:33, Verse:9, Page:1,
    Kor:"마라를 떠나서는 엘림으로 갔다. 거기에는 샘이 열두 곳이나 있고, 종려나무가 일흔 그루나 있어서, 거기에 진을 쳤다.",
    Chn:"从玛拉起行，来到以琳（以琳有十二股水泉，七十棵棕树），就在那里安营。",
    Eng:"They left Marah and went to Elim, where there were twelve springs and seventy palm trees, and they camped there.",
    Ind:"Mereka berangkat dari Mara, lalu sampai ke Elim; di Elim ada dua belas mata air dan tujuh puluh pohon korma; di sanalah mereka berkemah."
  },
  {Bible:"Numbers", Chapter:33, Verse:10, Page:1,
    Kor:"엘림을 떠나서는 홍해 부근에 이르러 진을 쳤다.",
    Chn:"从以琳起行，安营在红海边。",
    Eng:"They left Elim and camped by the Red Sea.",
    Ind:"Mereka berangkat dari Elim, lalu berkemah di tepi Laut Teberau."
  },
  {Bible:"Numbers", Chapter:33, Verse:11, Page:1,
    Kor:"홍해 부근을 떠나서는 신 광야에 이르러 진을 쳤다.",
    Chn:"从红海边起行，安营在汛的旷野。",
    Eng:"They left the Red Sea and camped in the Desert of Sin.",
    Ind:"Mereka berangkat dari Laut Teberau, lalu berkemah di padang gurun Sin."
  },
  {Bible:"Numbers", Chapter:33, Verse:12, Page:1,
    Kor:"신 광야를 떠나서는 돕가에 이르러 진을 쳤다.",
    Chn:"从汛的旷野起行，安营在脱加。",
    Eng:"They left the Desert of Sin and camped at Dophkah.",
    Ind:"Mereka berangkat dari padang gurun Sin, lalu berkemah di Dofka."
  },
  {Bible:"Numbers", Chapter:33, Verse:13, Page:1,
    Kor:"돕가를 떠나서는 알루스에 이르러 진을 쳤다.",
    Chn:"从脱加起行，安营在亚录。",
    Eng:"They left Dophkah and camped at Alush.",
    Ind:"Mereka berangkat dari Dofka, lalu berkemah di Alus."
  },
  {Bible:"Numbers", Chapter:33, Verse:14, Page:1,
    Kor:"알루스를 떠나서는 르비딤에 이르러 진을 쳤다. 그러나 거기에는 백성이 마실 물이 없었다.",
    Chn:"从亚录起行，安营在利非订；在那里，百姓没有水喝。",
    Eng:"They left Alush and camped at Rephidim, where there was no water for the people to drink.",
    Ind:"Mereka berangkat dari Alus, lalu berkemah di Rafidim, dan di sana tidak ada air minum untuk bangsa itu."
  },
  {Bible:"Numbers", Chapter:33, Verse:15, Page:1,
    Kor:"르비딤을 떠나서는 시내 광야에 이르러 진을 쳤다.",
    Chn:"从利非订起行，安营在西奈的旷野。",
    Eng:"They left Rephidim and camped in the Desert of Sinai.",
    Ind:"Mereka berangkat dari Rafidim, lalu berkemah di padang gurun Sinai."
  },
  {Bible:"Numbers", Chapter:33, Verse:16, Page:1,
    Kor:"시내 광야를 떠나서는 기브롯핫다아와에 이르러 진을 쳤다.",
    Chn:"从西奈的旷野起行，安营在基博罗·哈他瓦。",
    Eng:"They left the Desert of Sinai and camped at Kibroth Hattaavah.",
    Ind:"Mereka berangkat dari padang gurun Sinai, lalu berkemah di Kibrot-Taawa."
  },
  {Bible:"Numbers", Chapter:33, Verse:17, Page:1,
    Kor:"기브롯핫다아와를 떠나서는 하세롯에 이르러 진을 쳤다.",
    Chn:"从基博罗·哈他瓦起行，安营在哈洗录。",
    Eng:"They left Kibroth Hattaavah and camped at Hazeroth.",
    Ind:"Mereka berangkat dari Kibrot-Taawa, lalu berkemah di Hazerot."
  },
  {Bible:"Numbers", Chapter:33, Verse:18, Page:1,
    Kor:"하세롯을 떠나서는 릿마에 이르러 진을 쳤다.",
    Chn:"从哈洗录起行，安营在利提玛。",
    Eng:"They left Hazeroth and camped at Rithmah.",
    Ind:"Mereka berangkat dari Hazerot, lalu berkemah di Ritma."
  },
  {Bible:"Numbers", Chapter:33, Verse:19, Page:1,
    Kor:"릿마를 떠나서는 림몬베레스에 이르러 진을 쳤다.",
    Chn:"从利提玛起行，安营在临门·帕烈。",
    Eng:"They left Rithmah and camped at Rimmon Perez.",
    Ind:"Mereka berangkat dari Ritma, lalu berkemah di Rimon-Peros."
  },
  {Bible:"Numbers", Chapter:33, Verse:20, Page:1,
    Kor:"림몬베레스를 떠나서는 립나에 이르러 진을 쳤다.",
    Chn:"从临门·帕烈起行，安营在立拿。",
    Eng:"They left Rimmon Perez and camped at Libnah.",
    Ind:"Mereka berangkat dari Rimon-Peros, lalu berkemah di Libna."
  },
  {Bible:"Numbers", Chapter:33, Verse:21, Page:1,
    Kor:"립나를 떠나서는 릿사에 이르러 진을 쳤다.",
    Chn:"从立拿起行，安营在勒撒。",
    Eng:"They left Libnah and camped at Rissah.",
    Ind:"Mereka berangkat dari Libna, lalu berkemah di Risa."
  },
  {Bible:"Numbers", Chapter:33, Verse:22, Page:1,
    Kor:"릿사를 떠나서는 그헬라다에 이르러 진을 쳤다.",
    Chn:"从勒撒起行，安营在基希拉他。",
    Eng:"They left Rissah and camped at Kehelathah.",
    Ind:"Mereka berangkat dari Risa, lalu berkemah di Kehelata."
  },
  {Bible:"Numbers", Chapter:33, Verse:23, Page:1,
    Kor:"그헬라다를 떠나서는 세벨 산에 이르러 진을 쳤다.",
    Chn:"从基希拉他起行，安营在沙斐山。",
    Eng:"They left Kehelathah and camped at Mount Shepher.",
    Ind:"Mereka berangkat dari Kehelata, lalu berkemah di Har-Syafer."
  },
  {Bible:"Numbers", Chapter:33, Verse:24, Page:1,
    Kor:"세벨 산을 떠나서는 하라다에 이르러 진을 쳤다.",
    Chn:"从沙斐山起行，安营在哈拉大。",
    Eng:"They left Mount Shepher and camped at Haradah.",
    Ind:"Mereka berangkat dari Har-Syafer, lalu berkemah di Harada."
  },
  {Bible:"Numbers", Chapter:33, Verse:25, Page:1,
    Kor:"하라다를 떠나서는 막헬롯에 이르러 진을 쳤다.",
    Chn:"从哈拉大起行，安营在玛吉希录。",
    Eng:"They left Haradah and camped at Makheloth.",
    Ind:"Mereka berangkat dari Harada, lalu berkemah di Makhelot."
  },
  {Bible:"Numbers", Chapter:33, Verse:26, Page:1,
    Kor:"막헬롯을 떠나서는 다핫에 이르러 진을 쳤다.",
    Chn:"从玛吉希录起行，安营在他哈。",
    Eng:"They left Makheloth and camped at Tahath.",
    Ind:"Mereka berangkat dari Makhelot, lalu berkemah di Tahat."
  },
  {Bible:"Numbers", Chapter:33, Verse:27, Page:1,
    Kor:"다핫을 떠나서는 데라에 이르러 진을 쳤다.",
    Chn:"从他哈起行，安营在他拉。",
    Eng:"They left Tahath and camped at Terah.",
    Ind:"Mereka berangkat dari Tahat, lalu berkemah di Tarah."
  },
  {Bible:"Numbers", Chapter:33, Verse:28, Page:1,
    Kor:"데라를 떠나서는 밋가에 이르러 진을 쳤다.",
    Chn:"从他拉起行，安营在密加。",
    Eng:"They left Terah and camped at Mithcah.",
    Ind:"Mereka berangkat dari Tarah, lalu berkemah di Mitka."
  },
  {Bible:"Numbers", Chapter:33, Verse:29, Page:1,
    Kor:"밋가를 떠나서는 하스모나에 이르러 진을 쳤다.",
    Chn:"从密加起行，安营在哈摩拿。",
    Eng:"They left Mithcah and camped at Hashmonah.",
    Ind:"Mereka berangkat dari Mitka, lalu berkemah di Hasmona."
  },
  {Bible:"Numbers", Chapter:33, Verse:30, Page:1,
    Kor:"하스모나를 떠나서는 모세롯에 이르러 진을 쳤다.",
    Chn:"从哈摩拿起行，安营在摩西录。",
    Eng:"They left Hashmonah and camped at Moseroth.",
    Ind:"Mereka berangkat dari Hasmona, lalu berkemah di Moserot."
  },
  {Bible:"Numbers", Chapter:33, Verse:31, Page:1,
    Kor:"모세롯을 떠나서는 브네야아간에 이르러 진을 쳤다.",
    Chn:"从摩西录起行，安营在比尼·亚干。",
    Eng:"They left Moseroth and camped at Bene Jaakan.",
    Ind:"Mereka berangkat dari Moserot, lalu berkemah di Bene-Yaakan."
  },
  {Bible:"Numbers", Chapter:33, Verse:32, Page:1,
    Kor:"브네야아간을 떠나서는 홀하깃갓에 이르러 진을 쳤다.",
    Chn:"从比尼·亚干起行，安营在曷·哈及甲。",
    Eng:"They left Bene Jaakan and camped at Hor Haggidgad.",
    Ind:"Mereka berangkat dari Bene-Yaakan, lalu berkemah di Hor-Gidgad."
  },
  {Bible:"Numbers", Chapter:33, Verse:33, Page:1,
    Kor:"홀하깃갓을 떠나서는 욧바다에 이르러 진을 쳤다.",
    Chn:"从曷·哈及甲起行，安营在约巴他。",
    Eng:"They left Hor Haggidgad and camped at Jotbathah.",
    Ind:"Mereka berangkat dari Hor-Gidgad, lalu berkemah di Yotbata."
  },
  {Bible:"Numbers", Chapter:33, Verse:34, Page:1,
    Kor:"욧바다를 떠나서는 아브로나에 이르러 진을 쳤다.",
    Chn:"从约巴他起行，安营在阿博拿。",
    Eng:"They left Jotbathah and camped at Abronah.",
    Ind:"Mereka berangkat dari Yotbata, lalu berkemah di Abrona."
  },
  {Bible:"Numbers", Chapter:33, Verse:35, Page:1,
    Kor:"아브로나를 떠나서는 에시온게벨에 이르러 진을 쳤다.",
    Chn:"从阿博拿起行，安营在以旬·迦别。",
    Eng:"They left Abronah and camped at Ezion Geber.",
    Ind:"Mereka berangkat dari Abrona, lalu berkemah di Ezion-Geber."
  },
  {Bible:"Numbers", Chapter:33, Verse:36, Page:1,
    Kor:"에시온게벨을 떠나서는 신 광야의 가데스에 이르러 진을 쳤다.",
    Chn:"从以旬·迦别起行，安营在寻的旷野，就是加低斯。",
    Eng:"They left Ezion Geber and camped at Kadesh, in the Desert of Zin.",
    Ind:"Mereka berangkat dari Ezion-Geber, lalu berkemah di padang gurun Zin, yaitu Kadesh."
  },
  {Bible:"Numbers", Chapter:33, Verse:37, Page:1,
    Kor:"가데스를 떠나서는 에돔 땅 국경 호르 산에 이르러 진을 쳤다.",
    Chn:"从加低斯起行，安营在何珥山，以东地的边界。",
    Eng:"They left Kadesh and camped at Mount Hor, on the border of Edom.",
    Ind:"Mereka berangkat dari Kadesh, lalu berkemah di gunung Hor, di perbatasan tanah Edom."
  },
  {Bible:"Numbers", Chapter:33, Verse:38, Page:1,
    Kor:"○제사장 아론이 주님의 명을 따라 호르 산으로 올라가 죽으니, 그 때는 이스라엘 자손이 이집트 땅에서 나온 지 사십 년 되던 해 다섯째 달, 그 달 초하루였다.",
    Chn:"以色列人出了埃及地后四十年，五月初一日，祭司亚伦遵着耶和华的吩咐上何珥山，就死在那里。",
    Eng:"At the LORD'S command Aaron the priest went up Mount Hor, where he died on the first day of the fifth month of the fortieth year after the Israelites came out of Egypt.",
    Ind:"Ketika itu imam Harun naik ke gunung Hor sesuai dengan titah TUHAN, dan di situ ia mati pada tahun keempat puluh sesudah orang Israel keluar dari tanah Mesir, pada bulan yang kelima, pada tanggal satu bulan itu;"
  },
  {Bible:"Numbers", Chapter:33, Verse:39, Page:1,
    Kor:"아론이 호르 산에서 죽을 때의 나이는 백이십삼 세이다.",
    Chn:"亚伦死在何珥山的时候年一百二十三岁。",
    Eng:"Aaron was a hundred and twenty-three years old when he died on Mount Hor.",
    Ind:"Harun berumur seratus dua puluh tiga tahun, ketika ia mati di gunung Hor."
  },
  {Bible:"Numbers", Chapter:33, Verse:40, Page:1,
    Kor:"○가나안 사람으로서 가나안 땅 네겝 지방에서 살고 있던 아랏의 왕은 이스라엘 자손이 온다는 소문을 들었다.",
    Chn:"住在迦南南地的迦南人亚拉得王听说以色列人来了。",
    Eng:"The Canaanite king of Arad, who lived in the Negev of Canaan, heard that the Israelites were coming.",
    Ind:"Pada waktu itu raja negeri Arad, orang Kanaan itu, yang tinggal di Tanah Negeb di tanah Kanaan, mendengar kabar tentang kedatangan orang Israel."
  },
  {Bible:"Numbers", Chapter:33, Verse:41, Page:1,
    Kor:"○이스라엘 자손은 호르 산을 떠나서는 살모나에 이르러 진을 쳤다.",
    Chn:"以色列人从何珥山起行，安营在撒摩拿。",
    Eng:"They left Mount Hor and camped at Zalmonah.",
    Ind:"Berangkatlah mereka dari gunung Hor, lalu berkemah di Zalmona."
  },
  {Bible:"Numbers", Chapter:33, Verse:42, Page:1,
    Kor:"살모나를 떠나서는 부논에 이르러 진을 쳤다.",
    Chn:"从撒摩拿起行，安营在普嫩。",
    Eng:"They left Zalmonah and camped at Punon.",
    Ind:"Mereka berangkat dari Zalmona, lalu berkemah di Funon."
  },
  {Bible:"Numbers", Chapter:33, Verse:43, Page:1,
    Kor:"부논을 떠나서는 오봇에 이르러 진을 쳤다.",
    Chn:"从普嫩起行，安营在阿伯。",
    Eng:"They left Punon and camped at Oboth.",
    Ind:"Mereka berangkat dari Funon, lalu berkemah di Obot."
  },
  {Bible:"Numbers", Chapter:33, Verse:44, Page:1,
    Kor:"오봇을 떠나서는 모압 국경지대의 이예아바림에 이르러 진을 쳤다.",
    Chn:"从阿伯起行，安营在以耶·亚巴琳，摩押的边界。",
    Eng:"They left Oboth and camped at Iye Abarim, on the border of Moab.",
    Ind:"Mereka berangkat dari Obot, lalu berkemah dekat reruntuhan di Abarim di daerah Moab."
  },
  {Bible:"Numbers", Chapter:33, Verse:45, Page:1,
    Kor:"그 폐허를 떠나서는 디본갓에 이르러 진을 쳤다.",
    Chn:"从以耶·亚巴琳起行，安营在底本·迦得。",
    Eng:"They left Iyim and camped at Dibon Gad.",
    Ind:"Mereka berangkat dari reruntuhan itu, lalu berkemah di Dibon-Gad."
  },
  {Bible:"Numbers", Chapter:33, Verse:46, Page:1,
    Kor:"디본갓을 떠나서는 알몬디블라다임에 이르러 진을 쳤다.",
    Chn:"从底本·迦得起行，安营在亚门·低比拉太音。",
    Eng:"They left Dibon Gad and camped at Almon Diblathaim.",
    Ind:"Mereka berangkat dari Dibon-Gad, lalu berkemah di Almon-Diblataim."
  },
  {Bible:"Numbers", Chapter:33, Verse:47, Page:1,
    Kor:"알몬디블라다임을 떠나서는 느보 앞 아바림 산에 이르러 진을 쳤다.",
    Chn:"从亚门·低比拉太音起行，安营在尼波对面的亚巴琳山里。",
    Eng:"They left Almon Diblathaim and camped in the mountains of Abarim, near Nebo.",
    Ind:"Mereka berangkat dari Almon-Diblataim, lalu berkemah di pegunungan Abarim di depan Nebo."
  },
  {Bible:"Numbers", Chapter:33, Verse:48, Page:1,
    Kor:"아바림 산을 떠나서는 여리고 부근 요단 강 가 모압 평야에 이르러 진을 쳤다.",
    Chn:"从亚巴琳山起行，安营在摩押平原—约旦河边、耶利哥对面。",
    Eng:"They left the mountains of Abarim and camped on the plains of Moab by the Jordan across from Jericho.",
    Ind:"Mereka berangkat dari pegunungan Abarim, lalu berkemah di dataran Moab di tepi sungai Yordan dekat Yerikho."
  },
  {Bible:"Numbers", Chapter:33, Verse:49, Page:1,
    Kor:"요단 강 가를 따라서 모압 평야에 친 진은, 벳여시못에서부터 아벨싯딤에까지 이르렀다.",
    Chn:"他们在摩押平原沿约旦河边安营，从伯·耶施末直到亚伯·什亭。",
    Eng:"There on the plains of Moab they camped along the Jordan from Beth Jeshimoth to Abel Shittim.",
    Ind:"Mereka berkemah di tepi sungai Yordan, dari Bet-Yesimot sampai ke Abel-Sitim di dataran Moab."
  },
  {Bible:"Numbers", Chapter:33, Verse:50, Page:1,
    Kor:"<가나안 땅 분할 지시> ○여리고 건너편 요단 강 가 모압 평야에서 주님께서 모세에게 말씀하셨다.",
    Chn:"耶和华在摩押平原—约旦河边、耶利哥对面晓谕摩西说：",
    Eng:"On the plains of Moab by the Jordan across from Jericho the LORD said to Moses,",
    Ind:"TUHAN berfirman kepada Musa di dataran Moab di tepi sungai Yordan dekat Yerikho:"
  },
  {Bible:"Numbers", Chapter:33, Verse:51, Page:1,
    Kor:"\"너는 이스라엘 자손에게 말하여라. 그들에게 다음과 같이 일러라. ○너희가 요단 강을 건너 가나안 땅에 들어가거든,",
    Chn:"「你吩咐以色列人说：你们过约旦河进迦南地的时候，",
    Eng:"\"Speak to the Israelites and say to them: 'When you cross the Jordan into Canaan,",
    Ind:"\"Berbicaralah kepada orang Israel dan katakanlah kepada mereka: Apabila kamu menyeberangi sungai Yordan ke tanah Kanaan,"
  },
  {Bible:"Numbers", Chapter:33, Verse:52, Page:1,
    Kor:"너희는 직접 그 땅 주민을 다 쫓아내어라. 새겨 만든 우상과 부어 만든 우상을 다 깨뜨려 버리고, 산당들도 다 헐어 버려라.",
    Chn:"就要从你们面前赶出那里所有的居民，毁灭他们一切錾成的石像和他们一切铸成的偶像，又拆毁他们一切的邱坛。",
    Eng:"drive out all the inhabitants of the land before you. Destroy all their carved images and their cast idols, and demolish all their high places.",
    Ind:"maka haruslah kamu menghalau semua penduduk negeri itu dari depanmu dan membinasakan segala batu berukir kepunyaan mereka; juga haruslah kamu membinasakan segala patung tuangan mereka dan memusnahkan segala bukit pengorbanan mereka."
  },
  {Bible:"Numbers", Chapter:33, Verse:53, Page:1,
    Kor:"내가 그 땅을 너희의 소유로 준 것이니, 너희는 그 땅을 차지하고 거기에서 정착하여라.",
    Chn:"你们要夺那地，住在其中，因我把那地赐给你们为业。",
    Eng:"Take possession of the land and settle in it, for I have given you the land to possess.",
    Ind:"Haruslah kamu menduduki negeri itu dan diam di sana, sebab kepadamulah Kuberikan negeri itu untuk diduduki."
  },
  {Bible:"Numbers", Chapter:33, Verse:54, Page:1,
    Kor:"땅은 주사위를 던져, 가족별로 나누어 가지도록 하여라. 큰 쪽에는 큰 땅덩어리를 유산으로 주고, 작은 쪽에는 작은 땅덩어리를 유산으로 주어라. 주사위를 던져 나오는 대로, 각자 자기 것으로 삼도록 하여라. 땅을 나눌 때에는 같은 조상을 둔 지파들끼리 나누어 가지도록 하여라.",
    Chn:"你们要按家室拈阄，承受那地；人多的，要把产业多分给他们；人少的，要把产业少分给他们。拈出何地给何人，就要归何人。你们要按宗族的支派承受。",
    Eng:"Distribute the land by lot, according to your clans. To a larger group give a larger inheritance, and to a smaller group a smaller one. Whatever falls to them by lot will be theirs. Distribute it according to your ancestral tribes.",
    Ind:"Maka haruslah kamu membagi negeri itu sebagai milik pusaka dengan membuang undi menurut kaummu: kepada yang besar jumlahnya haruslah kamu memberikan milik pusaka yang besar, dan kepada yang kecil jumlahnya haruslah kamu memberikan milik pusaka yang kecil; yang ditunjuk oleh undi bagi masing-masing, itulah bagian undiannya; menurut suku nenek moyangmu haruslah kamu membagi milik pusaka itu."
  },
  {Bible:"Numbers", Chapter:33, Verse:55, Page:1,
    Kor:"너희가 그 땅의 주민을 다 쫓아내지 아니하고, 너희와 함께 있도록 허락하였다가는, 그들이 너희 눈에 가시가 되고, 옆구리를 찌르는 바늘이 되어서, 너희가 살아갈 그 땅에서 너희를 괴롭힐 것이다.",
    Chn:"倘若你们不赶出那地的居民，所容留的居民就必作你们眼中的刺，肋下的荆棘，也必在你们所住的地上扰害你们。",
    Eng:"\"'But if you do not drive out the inhabitants of the land, those you allow to remain will become barbs in your eyes and thorns in your sides. They will give you trouble in the land where you will live.",
    Ind:"Tetapi jika kamu tidak menghalau penduduk negeri itu dari depanmu, maka orang-orang yang kamu tinggalkan hidup dari mereka akan menjadi seperti selumbar di matamu dan seperti duri yang menusuk lambungmu, dan mereka akan menyesatkan kamu di negeri yang kamu diami itu."
  },
  {Bible:"Numbers", Chapter:33, Verse:56, Page:1,
    Kor:"그뿐만 아니라, 나는 그들에게 하기로 계획한 것을 그대로 너희에게 하겠다.\"",
    Chn:"而且我素常有意怎样待他们，也必照样待你们。」",
    Eng:"And then I will do to you what I plan to do to them.'\"",
    Ind:"Maka akan Kulakukan kepadamu seperti yang Kurancang melakukan kepada mereka.\""
  },
]);
