// 민수기 3장 · Numbers 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Numbers",3,51);
BibleDB.add([
  {Bible:"Numbers", Chapter:3, Verse:1, Page:1, Kor:"", Chn:"", Eng:"This is the account of the family of Aaron and Moses at the time the LORD talked with Moses on Mount Sinai.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:2, Page:1, Kor:"", Chn:"", Eng:"The names of the sons of Aaron were Nadab the firstborn and Abihu, Eleazar and Ithamar.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:3, Page:1, Kor:"", Chn:"", Eng:"Those were the names of Aaron's sons, the anointed priests, who were ordained to serve as priests.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Nadab and Abihu, however, fell dead before the LORD when they made an offering with unauthorized fire before him in the Desert of Sinai. They had no sons; so only Eleazar and Ithamar served as priests during the lifetime of their father Aaron.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:5, Page:1, Kor:"", Chn:"", Eng:"The LORD said to Moses,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:6, Page:1, Kor:"", Chn:"", Eng:"\"Bring the tribe of Levi and present them to Aaron the priest to assist him.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:7, Page:1, Kor:"", Chn:"", Eng:"They are to perform duties for him and for the whole community at the Tent of Meeting by doing the work of the tabernacle.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:8, Page:1, Kor:"", Chn:"", Eng:"They are to take care of all the furnishings of the Tent of Meeting, fulfilling the obligations of the Israelites by doing the work of the tabernacle.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Give the Levites to Aaron and his sons; they are the Israelites who are to be given wholly to him.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Appoint Aaron and his sons to serve as priests; anyone else who approaches the sanctuary must be put to death.\"", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:11, Page:1, Kor:"", Chn:"", Eng:"The LORD also said to Moses,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:12, Page:1, Kor:"", Chn:"", Eng:"\"I have taken the Levites from among the Israelites in place of the first male offspring of every Israelite woman. The Levites are mine,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:13, Page:1, Kor:"", Chn:"", Eng:"for all the firstborn are mine. When I struck down all the firstborn in Egypt, I set apart for myself every firstborn in Israel, whether man or animal. They are to be mine. I am the LORD.\"", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:14, Page:1, Kor:"", Chn:"", Eng:"The LORD said to Moses in the Desert of Sinai,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:15, Page:1, Kor:"", Chn:"", Eng:"\"Count the Levites by their families and clans. Count every male a month old or more.\"", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:16, Page:1, Kor:"", Chn:"", Eng:"So Moses counted them, as he was commanded by the word of the LORD.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:17, Page:1, Kor:"", Chn:"", Eng:"These were the names of the sons of Levi: Gershon, Kohath and Merari.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:18, Page:1, Kor:"", Chn:"", Eng:"These were the names of the Gershonite clans: Libni and Shimei.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:19, Page:1, Kor:"", Chn:"", Eng:"The Kohathite clans: Amram, Izhar, Hebron and Uzziel.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:20, Page:1, Kor:"", Chn:"", Eng:"The Merarite clans: Mahli and Mushi. These were the Levite clans, according to their families.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:21, Page:1, Kor:"", Chn:"", Eng:"To Gershon belonged the clans of the Libnites and Shimeites; these were the Gershonite clans.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:22, Page:1, Kor:"", Chn:"", Eng:"The number of all the males a month old or more who were counted was 7,500.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:23, Page:1, Kor:"", Chn:"", Eng:"The Gershonite clans were to camp on the west, behind the tabernacle.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:24, Page:1, Kor:"", Chn:"", Eng:"The leader of the families of the Gershonites was Eliasaph son of Lael.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:25, Page:1, Kor:"", Chn:"", Eng:"At the Tent of Meeting the Gershonites were responsible for the care of the tabernacle and tent, its coverings, the curtain at the entrance to the Tent of Meeting,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:26, Page:1, Kor:"", Chn:"", Eng:"the curtains of the courtyard, the curtain at the entrance to the courtyard surrounding the tabernacle and altar, and the ropes--and everything related to their use.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:27, Page:1, Kor:"", Chn:"", Eng:"To Kohath belonged the clans of the Amramites, Izharites, Hebronites and Uzzielites; these were the Kohathite clans.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:28, Page:1, Kor:"", Chn:"", Eng:"The number of all the males a month old or more was 8,600. The Kohathites were responsible for the care of the sanctuary.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:29, Page:1, Kor:"", Chn:"", Eng:"The Kohathite clans were to camp on the south side of the tabernacle.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:30, Page:1, Kor:"", Chn:"", Eng:"The leader of the families of the Kohathite clans was Elizaphan son of Uzziel.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:31, Page:1, Kor:"", Chn:"", Eng:"They were responsible for the care of the ark, the table, the lampstand, the altars, the articles of the sanctuary used in ministering, the curtain, and everything related to their use.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:32, Page:1, Kor:"", Chn:"", Eng:"The chief leader of the Levites was Eleazar son of Aaron, the priest. He was appointed over those who were responsible for the care of the sanctuary.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:33, Page:1, Kor:"", Chn:"", Eng:"To Merari belonged the clans of the Mahlites and the Mushites; these were the Merarite clans.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:34, Page:1, Kor:"", Chn:"", Eng:"The number of all the males a month old or more who were counted was 6,200.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:35, Page:1, Kor:"", Chn:"", Eng:"The leader of the families of the Merarite clans was Zuriel son of Abihail; they were to camp on the north side of the tabernacle.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:36, Page:1, Kor:"", Chn:"", Eng:"The Merarites were appointed to take care of the frames of the tabernacle, its crossbars, posts, bases, all its equipment, and everything related to their use,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:37, Page:1, Kor:"", Chn:"", Eng:"as well as the posts of the surrounding courtyard with their bases, tent pegs and ropes.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:38, Page:1, Kor:"", Chn:"", Eng:"Moses and Aaron and his sons were to camp to the east of the tabernacle, toward the sunrise, in front of the Tent of Meeting. They were responsible for the care of the sanctuary on behalf of the Israelites. Anyone else who approached the sanctuary was to be put to death.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:39, Page:1, Kor:"", Chn:"", Eng:"The total number of Levites counted at the LORD'S command by Moses and Aaron according to their clans, including every male a month old or more, was 22,000.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:40, Page:1, Kor:"", Chn:"", Eng:"The LORD said to Moses, \"Count all the firstborn Israelite males who are a month old or more and make a list of their names.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:41, Page:1, Kor:"", Chn:"", Eng:"Take the Levites for me in place of all the firstborn of the Israelites, and the livestock of the Levites in place of all the firstborn of the livestock of the Israelites. I am the LORD.\"", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:42, Page:1, Kor:"", Chn:"", Eng:"So Moses counted all the firstborn of the Israelites, as the LORD commanded him.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:43, Page:1, Kor:"", Chn:"", Eng:"The total number of firstborn males a month old or more, listed by name, was 22,273.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:44, Page:1, Kor:"", Chn:"", Eng:"The LORD also said to Moses,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:45, Page:1, Kor:"", Chn:"", Eng:"\"Take the Levites in place of all the firstborn of Israel, and the livestock of the Levites in place of their livestock. The Levites are to be mine. I am the LORD.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:46, Page:1, Kor:"", Chn:"", Eng:"To redeem the 273 firstborn Israelites who exceed the number of the Levites,", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:47, Page:1, Kor:"", Chn:"", Eng:"collect five shekels for each one, according to the sanctuary shekel, which weighs twenty gerahs.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:48, Page:1, Kor:"", Chn:"", Eng:"Give the money for the redemption of the additional Israelites to Aaron and his sons.\"", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:49, Page:1, Kor:"", Chn:"", Eng:"So Moses collected the redemption money from those who exceeded the number redeemed by the Levites.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:50, Page:1, Kor:"", Chn:"", Eng:"From the firstborn of the Israelites he collected silver weighing 1,365 shekels, according to the sanctuary shekel.", Ind:""},
  {Bible:"Numbers", Chapter:3, Verse:51, Page:1, Kor:"", Chn:"", Eng:"Moses gave the redemption money to Aaron and his sons, as he was commanded by the word of the LORD.", Ind:""},
]);
