// 민수기 1장 · Numbers 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Numbers",1,54);
BibleDB.add([
  {Bible:"Numbers", Chapter:1, Verse:1, Page:1,
    Kor:"<첫 번째 병적 조사> 이스라엘 자손이 이집트 땅에서 나온 지 이 년이 되던 해 a둘째 달 초하루에, 주님께서 시내 광야의 b회막에서 모세에게 말씀하셨다.(a 시브월, 양력 사월 중순 이후 b 하나님이 백성을 만나시는 곳)",
    Chn:"以色列人出埃及地后，第二年二月初一日，耶和华在西奈的旷野、会幕中晓谕摩西说：",
    Eng:"The LORD spoke to Moses in the Tent of Meeting in the Desert of Sinai on the first day of the second month of the second year after the Israelites came out of Egypt. He said:",
    Ind:"TUHAN berfirman kepada Musa di padang gurun Sinai, dalam Kemah Pertemuan, pada tanggal satu bulan yang kedua dalam tahun yang kedua sesudah mereka keluar dari tanah Mesir:"
  },
  {Bible:"Numbers", Chapter:1, Verse:2, Page:1,
    Kor:"\"c너희는 이스라엘 자손의 온 회중을 각 가문별, 가족별로 인구를 조사하여라. 남자의 경우는 그 머리 수대로 하나하나 모두 올려 명단을 만들어라.(c 모세와 아론)",
    Chn:"「你要按以色列全会众的家室、宗族、人名的数目计算所有的男丁。",
    Eng:"\"Take a census of the whole Israelite community by their clans and families, listing every man by name, one by one.",
    Ind:"\"Hitunglah jumlah segenap umat Israel menurut kaum-kaum yang ada dalam setiap suku mereka, dan catatlah nama semua laki-laki di Israel"
  },
  {Bible:"Numbers", Chapter:1, Verse:3, Page:1,
    Kor:"너는 아론과 함께, 이스라엘 사람 가운데서 스무 살이 넘어 군대에 입대할 수 있는 남자들을, 모두 각 부대별로 세어라.",
    Chn:"凡以色列中，从二十岁以外，能出去打仗的，你和亚伦要照他们的军队数点。",
    Eng:"You and Aaron are to number by their divisions all the men in Israel twenty years old or more who are able to serve in the army.",
    Ind:"yang berumur dua puluh tahun ke atas dan yang sanggup berperang, orang demi orang. Engkau ini beserta Harun harus mencatat mereka menurut pasukannya masing-masing."
  },
  {Bible:"Numbers", Chapter:1, Verse:4, Page:1,
    Kor:"각 지파에서 한 사람씩, 곧 한 가족에서 지도자가 한 사람씩 나오게 하여 너희를 돕게 하여라.",
    Chn:"每支派中必有一人作本支派的族长，帮助你们。",
    Eng:"One man from each tribe, each the head of his family, is to help you.",
    Ind:"Dari tiap-tiap suku harus ada satu orang yang mendampingi kamu, yakni orang yang menjadi kepala dari suku yang diwakilinya itu."
  },
  {Bible:"Numbers", Chapter:1, Verse:5, Page:1,
    Kor:"다음은 너희 곁에 서서 너희를 도울 사람들의 이름이다.\" ○\"르우벤 지파에서는 스데울의 아들 엘리술이요,",
    Chn:"他们的名字：属吕便的，有示丢珥的儿子以利蓿；",
    Eng:"These are the names of the men who are to assist you: from Reuben, Elizur son of Shedeur;",
    Ind:"Dan inilah nama semua orang yang harus mendampingi kamu. Dari suku Ruben: Elizur bin Syedeur;"
  },
  {Bible:"Numbers", Chapter:1, Verse:6, Page:1,
    Kor:"○시므온 지파에서는 수리삿대의 아들 슬루미엘이요,",
    Chn:"属西缅的，有苏利沙代的儿子示路蔑；",
    Eng:"from Simeon, Shelumiel son of Zurishaddai;",
    Ind:"dari suku Simeon: Selumiel bin Zurisyadai;"
  },
  {Bible:"Numbers", Chapter:1, Verse:7, Page:1,
    Kor:"○유다 지파에서는 암미나답의 아들 나손이요,",
    Chn:"属犹大的，有亚米拿达的儿子拿顺；",
    Eng:"from Judah, Nahshon son of Amminadab;",
    Ind:"dari suku Yehuda: Nahason bin Aminadab;"
  },
  {Bible:"Numbers", Chapter:1, Verse:8, Page:1,
    Kor:"○잇사갈 지파에서는 수알의 아들 느다넬이요,",
    Chn:"属以萨迦的，有苏押的儿子拿坦业；",
    Eng:"from Issachar, Nethanel son of Zuar;",
    Ind:"dari suku Isakhar: Netaneel bin Zuar;"
  },
  {Bible:"Numbers", Chapter:1, Verse:9, Page:1,
    Kor:"○스불론 지파에서는 헬론의 아들 엘리압이요,",
    Chn:"属西布伦的，有希伦的儿子以利押；",
    Eng:"from Zebulun, Eliab son of Helon;",
    Ind:"dari suku Zebulon: Eliab bin Helon;"
  },
  {Bible:"Numbers", Chapter:1, Verse:10, Page:1,
    Kor:"○요셉의 아들들 가운데, 에브라임 지파에서는 암미훗의 아들 엘리사마요, 므낫세 지파에서는 브다술의 아들 가말리엘이요,",
    Chn:"约瑟子孙、属以法莲的，有亚米忽的儿子以利沙玛；属玛拿西的，有比大蓿的儿子迦玛列；",
    Eng:"from the sons of Joseph: from Ephraim, Elishama son of Ammihud; from Manasseh, Gamaliel son of Pedahzur;",
    Ind:"dari keturunan Yusuf: Elisama bin Amihud dari suku Efraim, dan Gamaliel bin Pedazur dari suku Manasye;"
  },
  {Bible:"Numbers", Chapter:1, Verse:11, Page:1,
    Kor:"○베냐민 지파에서는 기드오니의 아들 아비단이요,",
    Chn:"属便雅悯的，有基多尼的儿子亚比但；",
    Eng:"from Benjamin, Abidan son of Gideoni;",
    Ind:"dari suku Benyamin: Abidan bin Gideoni;"
  },
  {Bible:"Numbers", Chapter:1, Verse:12, Page:1,
    Kor:"○단 지파에서는 암미삿대의 아들 아히에셀이요,",
    Chn:"属但的，有亚米沙代的儿子亚希以谢；",
    Eng:"from Dan, Ahiezer son of Ammishaddai;",
    Ind:"dari suku Dan: Ahiezer bin Amisyadai;"
  },
  {Bible:"Numbers", Chapter:1, Verse:13, Page:1,
    Kor:"○아셀 지파에서는 오그란의 아들 바기엘이요,",
    Chn:"属亚设的，有俄兰的儿子帕结；",
    Eng:"from Asher, Pagiel son of Ocran;",
    Ind:"dari suku Asyer: Pagiel bin Okhran;"
  },
  {Bible:"Numbers", Chapter:1, Verse:14, Page:1,
    Kor:"○갓 지파에서는 d르우엘의 아들 엘리아삽이요,(d 히, '드우엘'. 2:14절을 따름)",
    Chn:"属迦得的，有丢珥的儿子以利雅萨；",
    Eng:"from Gad, Eliasaph son of Deuel;",
    Ind:"dari suku Gad: Elyasaf bin Rehuel;"
  },
  {Bible:"Numbers", Chapter:1, Verse:15, Page:1,
    Kor:"○납달리 지파에서는 에난의 아들 아히라이다.\"",
    Chn:"属拿弗他利的，有以南的儿子亚希拉。",
    Eng:"from Naphtali, Ahira son of Enan.\"",
    Ind:"dari suku Naftali: Ahira bin Enan.\""
  },
  {Bible:"Numbers", Chapter:1, Verse:16, Page:1,
    Kor:"○이들은 회중이 추대하여, 조상 때부터 내려온 각 지파의 지도자가 된 사람들이다. 이 사람들이 바로 이스라엘 군대 각 부대의 지휘관이다.",
    Chn:"这都是从会中选召的，各作本支派的首领，都是以色列军中的统领。」",
    Eng:"These were the men appointed from the community, the leaders of their ancestral tribes. They were the heads of the clans of Israel.",
    Ind:"Itulah orang-orang yang dipilih dari umat itu, masing-masing sebagai pemimpin dari suku bapa leluhurnya; mereka inilah kepala-kepala pasukan Israel."
  },
  {Bible:"Numbers", Chapter:1, Verse:17, Page:1,
    Kor:"○모세와 아론은 임명받은 이 사람들을 거느리고",
    Chn:"于是，摩西、亚伦带着这些按名指定的人，",
    Eng:"Moses and Aaron took these men whose names had been given,",
    Ind:"Lalu Musa dan Harun memanggil orang-orang yang tertunjuk namanya itu,"
  },
  {Bible:"Numbers", Chapter:1, Verse:18, Page:1,
    Kor:"둘째 달 초하루에 전체 회중을 불러모았다. 회중들은 모두 가문별, 가족별로 등록하였다. 스무 살이 넘은 남자는, 모두 그 머리 수대로 하나하나 명단에 올렸다.",
    Chn:"当二月初一日招聚全会众。会众就照他们的家室、宗族、人名的数目，从二十岁以外的，都述说自己的家谱。",
    Eng:"and they called the whole community together on the first day of the second month. The people indicated their ancestry by their clans and families, and the men twenty years old or more were listed by name, one by one,",
    Ind:"dan pada tanggal satu bulan yang kedua mereka menyuruh segenap umat berkumpul. Kemudian silsilah orang-orang Israel disusun menurut kaum-kaum yang ada dalam setiap suku mereka, sedang nama-nama mereka yang berumur dua puluh tahun ke atas dicatat orang demi orang,"
  },
  {Bible:"Numbers", Chapter:1, Verse:19, Page:1,
    Kor:"이것은 주님께서 모세에게 명하신 대로 한 것이다. 모세가 시내 광야에서 그들의 수를 세었다.",
    Chn:"耶和华怎样吩咐摩西，他就怎样在西奈的旷野数点他们。",
    Eng:"as the LORD commanded Moses. And so he counted them in the Desert of Sinai:",
    Ind:"seperti yang diperintahkan TUHAN kepada Musa. Demikianlah Musa mencatat mereka di padang gurun Sinai."
  },
  {Bible:"Numbers", Chapter:1, Verse:20, Page:1,
    Kor:"○이스라엘의 맏아들 르우벤의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로, 그 머리 수대로, 하나하나 명단에 올렸다.",
    Chn:"以色列的长子，吕便子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的男丁，共有四万六千五百名。",
    Eng:"From the descendants of Reuben the firstborn son of Israel: All the men twenty years old or more who were able to serve in the army were listed by name, one by one, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Ruben, yaitu keturunan anak sulung Israel, disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama semua laki-laki yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang, orang demi orang.",
    ChnVerseEnd:21
  },
  {Bible:"Numbers", Chapter:1, Verse:21, Page:1,
    Kor:"르우벤 지파에서 등록된 사람의 수는 사만 육천오백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Reuben was 46,500.",
    Ind:"Jumlah yang dicatat dari suku Ruben ada empat puluh enam ribu lima ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:22, Page:1,
    Kor:"○시므온의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로, 그 머리 수대로, 하나하나 명단에 올렸다.",
    Chn:"西缅子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的男丁，共有五万九千三百名。",
    Eng:"From the descendants of Simeon: All the men twenty years old or more who were able to serve in the army were counted and listed by name, one by one, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Simeon disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama semua laki-laki yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang, orang demi orang.",
    ChnVerseEnd:23
  },
  {Bible:"Numbers", Chapter:1, Verse:23, Page:1,
    Kor:"시므온 지파에서 등록된 사람의 수는 오만 구천삼백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Simeon was 59,300.",
    Ind:"Jumlah yang dicatat dari suku Simeon ada lima puluh sembilan ribu tiga ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:24, Page:1,
    Kor:"○갓의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"迦得子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有四万五千六百五十名。",
    Eng:"From the descendants of Gad: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Gad disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:25
  },
  {Bible:"Numbers", Chapter:1, Verse:25, Page:1,
    Kor:"갓 지파에서 등록된 사람의 수는 사만 오천육백오십 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Gad was 45,650.",
    Ind:"Jumlah yang dicatat dari suku Gad ada empat puluh lima ribu enam ratus lima puluh orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:26, Page:1,
    Kor:"○유다의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"犹大子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有七万四千六百名。",
    Eng:"From the descendants of Judah: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Yehuda disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:27
  },
  {Bible:"Numbers", Chapter:1, Verse:27, Page:1,
    Kor:"유다 지파에서 등록된 사람의 수는 칠만 사천육백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Judah was 74,600.",
    Ind:"Jumlah yang dicatat dari suku Yehuda ada tujuh puluh empat ribu enam ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:28, Page:1,
    Kor:"○잇사갈의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"以萨迦子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有五万四千四百名。",
    Eng:"From the descendants of Issachar: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Isakhar disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:29
  },
  {Bible:"Numbers", Chapter:1, Verse:29, Page:1,
    Kor:"잇사갈 지파에서 등록된 사람의 수는 오만 사천사백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Issachar was 54,400.",
    Ind:"Jumlah yang dicatat dari suku Isakhar ada lima puluh empat ribu empat ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:30, Page:1,
    Kor:"○스불론의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"西布伦子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有五万七千四百名。",
    Eng:"From the descendants of Zebulun: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Zebulon disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:31
  },
  {Bible:"Numbers", Chapter:1, Verse:31, Page:1,
    Kor:"스불론 지파에서 등록된 사람의 수는 오만 칠천사백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Zebulun was 57,400.",
    Ind:"Jumlah yang dicatat dari suku Zebulon ada lima puluh tujuh ribu empat ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:32, Page:1,
    Kor:"○요셉의 아들 에브라임의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별 가족별로 명단에 올렸다.",
    Chn:"约瑟子孙属以法莲子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有四万零五百名。",
    Eng:"From the sons of Joseph: From the descendants of Ephraim: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Mengenai keturunan Yusuf: Ketika silsilah bani Efraim disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:33
  },
  {Bible:"Numbers", Chapter:1, Verse:33, Page:1,
    Kor:"에브라임 지파에서 등록된 사람의 수는 사만 오백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Ephraim was 40,500.",
    Ind:"Jumlah yang dicatat dari suku Efraim ada empat puluh ribu lima ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:34, Page:1,
    Kor:"○므낫세의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"玛拿西子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有三万二千二百名。",
    Eng:"From the descendants of Manasseh: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Dan ketika silsilah bani Manasye disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:35
  },
  {Bible:"Numbers", Chapter:1, Verse:35, Page:1,
    Kor:"므낫세 지파에서 등록된 사람의 수는 삼만 이천이백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Manasseh was 32,200.",
    Ind:"Jumlah yang dicatat dari suku Manasye ada tiga puluh dua ribu dua ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:36, Page:1,
    Kor:"○베냐민의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"便雅悯子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有三万五千四百名。",
    Eng:"From the descendants of Benjamin: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Benyamin disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:37
  },
  {Bible:"Numbers", Chapter:1, Verse:37, Page:1,
    Kor:"베냐민 지파에서 등록된 사람의 수는 삼만 오천사백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Benjamin was 35,400.",
    Ind:"Jumlah yang dicatat dari suku Benyamin ada tiga puluh lima ribu empat ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:38, Page:1,
    Kor:"○단의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"但子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有六万二千七百名。",
    Eng:"From the descendants of Dan: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Dan disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:39
  },
  {Bible:"Numbers", Chapter:1, Verse:39, Page:1,
    Kor:"단 지파에서 등록된 사람의 수는 육만 이천칠백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Dan was 62,700.",
    Ind:"Jumlah yang dicatat dari suku Dan ada enam puluh dua ribu tujuh ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:40, Page:1,
    Kor:"○아셀의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"亚设子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有四万一千五百名。",
    Eng:"From the descendants of Asher: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Asyer disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:41
  },
  {Bible:"Numbers", Chapter:1, Verse:41, Page:1,
    Kor:"아셀 지파에서 등록된 사람의 수는 사만 천오백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Asher was 41,500.",
    Ind:"Jumlah yang dicatat dari suku Asyer ada empat puluh satu ribu lima ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:42, Page:1,
    Kor:"○납달리의 자손 가운데서, 군대에 입대할 수 있는, 스무 살이 넘은 모든 남자를, 각각 가문별, 가족별로 명단에 올렸다.",
    Chn:"拿弗他利子孙的后代，照着家室、宗族、人名的数目，从二十岁以外，凡能出去打仗、被数的，共有五万三千四百名。",
    Eng:"From the descendants of Naphtali: All the men twenty years old or more who were able to serve in the army were listed by name, according to the records of their clans and families.",
    Ind:"Ketika silsilah bani Naftali disusun menurut kaum-kaum yang ada dalam suku mereka, maka dicatatlah nama orang-orang yang berumur dua puluh tahun ke atas, semua orang yang sanggup berperang.",
    ChnVerseEnd:43
  },
  {Bible:"Numbers", Chapter:1, Verse:43, Page:1,
    Kor:"납달리 지파에서 등록된 사람의 수는 오만 삼천사백 명이다.",
    Chn:"",
    Eng:"The number from the tribe of Naphtali was 53,400.",
    Ind:"Jumlah yang dicatat dari suku Naftali ada lima puluh tiga ribu empat ratus orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:44, Page:1,
    Kor:"○이 사람들은, 모세와 아론이, 각 집안에서 한 사람씩 뽑힌 이스라엘의 열두 지도자들과 함께 조사하여 등록시킨 사람들이다.",
    Chn:"这些就是被数点的，是摩西、亚伦，和以色列中十二个首领所数点的；这十二个人各作各宗族的代表。",
    Eng:"These were the men counted by Moses and Aaron and the twelve leaders of Israel, each one representing his family.",
    Ind:"Itulah jumlah orang-orang yang dicatat oleh Musa dengan Harun dan dengan kedua belas pemimpin Israel yang masing-masing mewakili sukunya."
  },
  {Bible:"Numbers", Chapter:1, Verse:45, Page:1,
    Kor:"이스라엘 군대에 입대할 수 있는, 스무 살이 넘은 모든 이스라엘 자손이, 각 집안별로 등록되었다.",
    Chn:"这样，凡以色列人中被数的，照着宗族，从二十岁以外，能出去打仗、被数的，共有六十万零三千五百五十名。",
    Eng:"All the Israelites twenty years old or more who were able to serve in Israel's army were counted according to their families.",
    Ind:"Jadi semua orang Israel yang dicatat menurut suku-suku mereka, yaitu orang-orang yang berumur dua puluh tahun ke atas dan yang sanggup berperang di antara orang Israel,",
    ChnVerseEnd:46
  },
  {Bible:"Numbers", Chapter:1, Verse:46, Page:1,
    Kor:"등록된 이들은 모두 육십만 삼천오백오십 명이다.",
    Chn:"",
    Eng:"The total number was 603,550.",
    Ind:"berjumlah enam ratus tiga ribu lima ratus lima puluh orang."
  },
  {Bible:"Numbers", Chapter:1, Verse:47, Page:1,
    Kor:"그러나 레위 사람은, 조상의 지파별로, 그들과 함께 등록되지 않았다.",
    Chn:"利未人却没有按着支派数在其中，",
    Eng:"The families of the tribe of Levi, however, were not counted along with the others.",
    Ind:"Tetapi mereka yang menurut suku bapa leluhurnya termasuk orang Lewi, tidak turut dicatat bersama-sama dengan mereka itu."
  },
  {Bible:"Numbers", Chapter:1, Verse:48, Page:1,
    Kor:"<레위 지파의 병역 면제> ○주님께서 모세에게 이렇게 분부하여 이르셨다.",
    Chn:"因为耶和华晓谕摩西说：",
    Eng:"The LORD had said to Moses:",
    Ind:"Sebab TUHAN telah berfirman kepada Musa:"
  },
  {Bible:"Numbers", Chapter:1, Verse:49, Page:1,
    Kor:"\"레위 지파만은 인구조사에서 빼고 이스라엘 징집자 명단에 올리지 말아라.",
    Chn:"「惟独利未支派你不可数点，也不可在以色列人中计算他们的总数。",
    Eng:"\"You must not count the tribe of Levi or include them in the census of the other Israelites.",
    Ind:"\"Hanya suku Lewi janganlah kaucatat dan janganlah kauhitung jumlahnya bersama-sama dengan orang Israel,"
  },
  {Bible:"Numbers", Chapter:1, Verse:50, Page:1,
    Kor:"그 대신 너는 레위 사람을 시켜, e증거궤가 보관된 성막을 보살피게 하여라. 모든 기구와 그 안에 있는 모든 비품을 그들이 관리할 것이다. 그들은 성막을 옮기는 일과 그 안에 있는 모든 기구를 옮기는 일을 맡을 것이다. 그들은 성막을 돌보며, 성막 둘레에 진을 치고 살아야 한다.(e 또는 '법막' 또는 '증거막')",
    Chn:"只要派利未人管法柜的帐幕和其中的器具，并属乎帐幕的；他们要抬帐幕和其中的器具，并要办理帐幕的事，在帐幕的四围安营。",
    Eng:"Instead, appoint the Levites to be in charge of the tabernacle of the Testimony--over all its furnishings and everything belonging to it. They are to carry the tabernacle and all its furnishings; they are to take care of it and encamp around it.",
    Ind:"tetapi tugaskanlah mereka untuk mengawasi Kemah Suci, tempat hukum Allah dengan segala perabotan dan perlengkapannya; mereka harus mengangkat Kemah Suci dengan segala perabotannya; mereka harus mengurusnya dan harus berkemah di sekelilingnya."
  },
  {Bible:"Numbers", Chapter:1, Verse:51, Page:1,
    Kor:"성막을 옮길 때마다 레위 사람이 그것을 거두어야 하고, 성막을 칠 때에는 레위 사람만이 그것을 세워야 한다. 다른 사람들이 거기에 다가갔다가는 죽을 것이다.",
    Chn:"帐幕将往前行的时候，利未人要拆卸；将支搭的时候，利未人要竖起。近前来的外人必被治死。",
    Eng:"Whenever the tabernacle is to move, the Levites are to take it down, and whenever the tabernacle is to be set up, the Levites shall do it. Anyone else who goes near it shall be put to death.",
    Ind:"Apabila berangkat, Kemah Suci harus dibongkar oleh orang Lewi, dan apabila berkemah, Kemah Suci harus dipasang oleh mereka; sedang orang awam yang mendekat harus dihukum mati."
  },
  {Bible:"Numbers", Chapter:1, Verse:52, Page:1,
    Kor:"이스라엘 자손은 각기 부대별로, 각기 자기 진 안의 부대기를 중심으로 장막을 쳐야 한다.",
    Chn:"以色列人支搭帐棚，要照他们的军队，各归本营，各归本纛。",
    Eng:"The Israelites are to set up their tents by divisions, each man in his own camp under his own standard.",
    Ind:"Orang Israel haruslah berkemah masing-masing di tempat perkemahannya dan masing-masing dekat panji-panjinya, menurut pasukan mereka,"
  },
  {Bible:"Numbers", Chapter:1, Verse:53, Page:1,
    Kor:"그러나 레위 사람은 e증거궤가 보관된 성막 둘레에 진을 쳐서, 나의 진노가 이스라엘 자손의 회중에게 내리지 않게 해야 한다. 레위 사람은 e증거궤가 보관된 성막을 보호할 임무를 맡는다.\"(e 또는 '법막' 또는 '증거막')",
    Chn:"但利未人要在法柜帐幕的四围安营，免得忿怒临到以色列会众；利未人并要谨守法柜的帐幕。」",
    Eng:"The Levites, however, are to set up their tents around the tabernacle of the Testimony so that wrath will not fall on the Israelite community. The Levites are to be responsible for the care of the tabernacle of the Testimony.\"",
    Ind:"tetapi orang Lewi haruslah berkemah di sekeliling Kemah Suci, tempat hukum Allah supaya umat Israel jangan kena murka; orang Lewi haruslah memelihara Kemah Suci, tempat hukum itu.\""
  },
  {Bible:"Numbers", Chapter:1, Verse:54, Page:1,
    Kor:"○이스라엘 자손은, 주님께서 모세에게 명하신 모든 것을 다 그대로 하였다.",
    Chn:"以色列人就这样行。凡耶和华所吩咐摩西的，他们就照样行了。",
    Eng:"The Israelites did all this just as the LORD commanded Moses.",
    Ind:"Maka orang Israel berbuat demikian; tepat seperti yang diperintahkan TUHAN kepada Musa, demikianlah diperbuat mereka."
  },
]);
