// 여호수아 15장 · Joshua 15
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Joshua",15,63);
BibleDB.add([
  {Bible:"Joshua", Chapter:15, Verse:1, Page:1,
    Kor:"<유다 지파의 땅> 유다 자손 지파에게 가문을 따라 제비를 뽑아서 나누어 준 땅은 다음과 같다. 유다 지파가 차지한 땅은 남쪽으로는 에돔의 경계선과 만나는 지역 곧 남쪽 맨 끝에 있는 신 광야에까지 이른다.",
    Chn:"犹大支派按着宗族拈阄所得之地是在尽南边，到以东的交界，向南直到寻的旷野。",
    Eng:"The allotment for the tribe of Judah, clan by clan, extended down to the territory of Edom, to the Desert of Zin in the extreme south.",
    Ind:"Bagian yang diundikan kepada suku bani Yehuda menurut kaum-kaum mereka adalah sampai ke batas tanah Edom, sampai ke padang gurun Zin ke selatan, di ujung selatan."
  },
  {Bible:"Joshua", Chapter:15, Verse:2, Page:1,
    Kor:"남쪽의 가로 경계선은 사해의 남쪽 끝 곧 남쪽으로 난 하구에서부터",
    Chn:"他们的南界是从盐海的尽边，就是从朝南的海汊起，",
    Eng:"Their southern boundary started from the bay at the southern end of the Salt Sea,",
    Ind:"Batas selatan bagi mereka mulai dari ujung Laut Asin, dari teluk yang menghadap ke selatan;"
  },
  {Bible:"Joshua", Chapter:15, Verse:3, Page:1,
    Kor:"아그랍빔 비탈 남쪽을 지나 신에 이르고, 가데스바네아 남쪽으로 내려가서 헤스론을 지나 앗달로 올라가 갈가로 뻗어가다가,",
    Chn:"通到亚克拉滨坡的南边，接连到寻，上到加低斯·巴尼亚的南边，又过希斯 ，上到亚达珥，绕到甲加，",
    Eng:"crossed south of Scorpion Pass, continued on to Zin and went over to the south of Kadesh Barnea. Then it ran past Hezron up to Addar and curved around to Karka.",
    Ind:"lalu keluar pada sebelah selatan pendakian Akrabim, terus ke Zin, naik ke sebelah selatan Kadesh-Barnea, terus ke Hezron, naik ke Adar, membelok ke Karka,"
  },
  {Bible:"Joshua", Chapter:15, Verse:4, Page:1,
    Kor:"거기에서 아스몬에 이르고, 이집트 국경지대의 강을 따라가다가 지중해에 이르러서 그 경계가 끝난다. 이것이 유다의 남쪽 경계선이다.",
    Chn:"接连到押们，通到埃及小河，直通到海为止。这就是他们的南界。",
    Eng:"It then passed along to Azmon and joined the Wadi of Egypt, ending at the sea. This is their southern boundary.",
    Ind:"terus ke Azmon dan keluar pada sungai tanah Mesir, sehingga batas itu berakhir ke laut. Itulah bagi kamu batas selatan."
  },
  {Bible:"Joshua", Chapter:15, Verse:5, Page:1,
    Kor:"○동쪽 경계선은 요단 강 하구, 사해 북단부터 남단까지이다. 북쪽 경계선은 요단 강이 끝나는 곳, 요단 강의 하구와 사해 바다가 만나는 곳에서 시작하여",
    Chn:"东界是从盐海南边到约旦河口。北界是从约旦河口的海汊起，",
    Eng:"The eastern boundary is the Salt Sea as far as the mouth of the Jordan. The northern boundary started from the bay of the sea at the mouth of the Jordan,",
    Ind:"Batas timur ialah Laut Asin sampai ke muara sungai Yordan. Batas pada sisi utara mulai dari teluk di muara sungai Yordan itu:"
  },
  {Bible:"Joshua", Chapter:15, Verse:6, Page:1,
    Kor:"벳호글라로 뻗고, 벳아라바의 북쪽을 지나, 르우벤의 아들 보한의 돌이 있는 곳에 이른다.",
    Chn:"上到伯·曷拉，过伯·亚拉巴的北边，上到吕便之子波罕的磐石；",
    Eng:"went up to Beth Hoglah and continued north of Beth Arabah to the Stone of Bohan son of Reuben.",
    Ind:"batas itu naik ke Bet-Hogla, melalui sebelah utara Bet-Araba, kemudian batas itu naik ke batu Bohan bin Ruben;"
  },
  {Bible:"Joshua", Chapter:15, Verse:7, Page:1,
    Kor:"그리고 그 경계선은 다시 아골 골짜기에서 드빌을 지나 북쪽으로 올라가, 강의 남쪽에 있는 아둠밈 비탈 맞은쪽의 길갈에 이르고, 거기에서 다시 a엔세메스 물을 지나서 엔 로겔에 이른다.(a '태양의 샘')",
    Chn:"从亚割谷往北，上到底璧，直向河南亚都冥坡对面的吉甲；又接连到隐·示麦泉，直通到隐·罗结，",
    Eng:"The boundary then went up to Debir from the Valley of Achor and turned north to Gilgal, which faces the Pass of Adummim south of the gorge. It continued along to the waters of En Shemesh and came out at En Rogel.",
    Ind:"lalu dari lembah Akhor batas itu naik ke Debir, dan menuju ke utara ke Gilgal di seberang pendakian Adumim, yang di sebelah selatan sungai. Kemudian batas itu terus ke mata air En-Semes dan keluar ke En-Rogel."
  },
  {Bible:"Joshua", Chapter:15, Verse:8, Page:1,
    Kor:"그 경계선은 다시 힌놈의 아들 골짜기로 올라가서, 여부스 곧 예루살렘의 남쪽 비탈에 이르고, 또 힌놈의 골짜기 앞 서쪽 산꼭대기에 이르는데, 이 곳은 르바임 골짜기의 북쪽 끝이다.",
    Chn:"上到欣嫩子谷，贴近耶布斯的南界（耶布斯就是耶路撒冷）；又上到欣嫩谷西边的山顶，就是在利乏音谷极北的边界；",
    Eng:"Then it ran up the Valley of Ben Hinnom along the southern slope of the Jebusite city (that is, Jerusalem). From there it climbed to the top of the hill west of the Hinnom Valley at the northern end of the Valley of Rephaim.",
    Ind:"Kemudian batas itu naik ke lembah Ben-Hinom, di sebelah selatan sepanjang lereng gunung Yebus, itulah Yerusalem; kemudian batas itu naik ke puncak gunung yang di seberang lembah Hinom, di sebelah barat, di ujung utara lembah orang Refaim."
  },
  {Bible:"Joshua", Chapter:15, Verse:9, Page:1,
    Kor:"그 경계선은 다시 산꼭대기로부터 넵도아 샘물까지 이르러 에브론 산 성읍들에 미치고, 또 바알라 곧 기럇여아림에 이른다.",
    Chn:"又从山顶延到尼弗多亚的水源，通到以弗 山的城邑，又延到巴拉（巴拉就是基列·耶琳）；",
    Eng:"From the hilltop the boundary headed toward the spring of the waters of Nephtoah, came out at the towns of Mount Ephron and went down toward Baalah (that is, Kiriath Jearim).",
    Ind:"Kemudian batas itu melengkung dari puncak gunung itu ke mata air Me-Neftoah, lalu keluar ke kota-kota pegunungan Efron; selanjutnya batas itu melengkung ke Baala, itulah Kiryat-Yearim."
  },
  {Bible:"Joshua", Chapter:15, Verse:10, Page:1,
    Kor:"그 경계선은 다시 바알라에서 서쪽으로 돌아서 세일 산에 이르고, 여아림 산 곧 그살론 북쪽 비탈에 미쳐, b벳세메스로 내려가서 딤나에 이르고,(b '태양의 집')",
    Chn:"又从巴拉往西绕到西珥山，接连到耶琳山的北边（耶琳就是基撒 ）；又下到伯·示麦过亭纳，",
    Eng:"Then it curved westward from Baalah to Mount Seir, ran along the northern slope of Mount Jearim (that is, Kesalon), continued down to Beth Shemesh and crossed to Timnah.",
    Ind:"Kemudian batas itu membelok dari Baala ke barat ke pegunungan Seir, terus ke utara ke lereng gunung Yearim, itulah Kesalon, turun ke Bet-Semes dan terus ke Timna."
  },
  {Bible:"Joshua", Chapter:15, Verse:11, Page:1,
    Kor:"그 경계선은 다시 에그론 북쪽 비탈로 나아가 식그론에 이르고, 바알라 산을 지나 얍느엘에 미쳐, 그 끝이 바다에 이른다.",
    Chn:"通到以革伦北边，延到施基 ，接连到巴拉山；又通到雅比聂，直通到海为止。",
    Eng:"It went to the northern slope of Ekron, turned toward Shikkeron, passed along to Mount Baalah and reached Jabneel. The boundary ended at the sea.",
    Ind:"Kemudian batas itu keluar ke utara ke lereng gunung Ekron; kemudian batas itu melengkung ke Sikron, terus ke gunung Baala dan keluar dekat Yabneel, sehingga batas itu berakhir di laut."
  },
  {Bible:"Joshua", Chapter:15, Verse:12, Page:1,
    Kor:"서쪽 경계선은 지중해와 그 연안이다. ○이것이 유다 지파에 속한 여러 가문이 나누어 받은 땅의 사방 경계선이다.",
    Chn:"西界就是大海和靠近大海之地。这是犹大人按着宗族所得之地四围的交界。",
    Eng:"The western boundary is the coastline of the Great Sea. These are the boundaries around the people of Judah by their clans.",
    Ind:"Batas barat ialah Laut Besar dan pantainya. Itulah, ke segala penjuru, batas-batas daerah bani Yehuda menurut kaum-kaum mereka."
  },
  {Bible:"Joshua", Chapter:15, Verse:13, Page:1,
    Kor:"<갈렙이 헤브론과 드빌을 정복하다(삿 1:11-15)> ○주님께서 여호수아에게 명하신 대로, 여호수아가 여분네의 아들 갈렙에게 유다 자손의 분깃 가운데서, 아르바에 가지고 있던 성읍 헤브론을 주었는데, 아르바라는 사람은 아낙 사람의 조상이다.",
    Chn:"约书亚照耶和华所吩咐的，将犹大人中的一段地，就是基列·亚巴，分给耶孚尼的儿子迦勒。亚巴是亚衲族的始祖（基列·亚巴就是希伯 ）。",
    Eng:"In accordance with the LORD'S command to him, Joshua gave to Caleb son of Jephunneh a portion in Judah--Kiriath Arba, that is, Hebron. (Arba was the forefather of Anak.)",
    Ind:"Tetapi kepada Kaleb bin Yefune diberikan Yosua sebagian di tengah-tengah bani Yehuda itu, yakni Kiryat-Arba, seperti yang dititahkan TUHAN kepadanya; Arba ialah bapa Enak. Itulah Hebron."
  },
  {Bible:"Joshua", Chapter:15, Verse:14, Page:1,
    Kor:"갈렙은 거기에서 아낙의 세 아들 곧 아낙이 낳은 세새와 아히만과 달매를 쫓아내었다.",
    Chn:"迦勒就从那里赶出亚衲族的三个族长，就是示筛、亚希幔、挞买；",
    Eng:"From Hebron Caleb drove out the three Anakites--Sheshai, Ahiman and Talmai--descendants of Anak.",
    Ind:"Dan Kaleb menghalau dari sana ketiga orang Enak, yakni Sesai, Ahiman dan Talmai, anak-anak Enak."
  },
  {Bible:"Joshua", Chapter:15, Verse:15, Page:1,
    Kor:"거기에서 그들은 드빌 주민을 치러 올라갔다. 드빌은 일찍이 기럇세벨이라고 불리던 곳이다.",
    Chn:"又从那里上去，攻击底璧的居民。（这底璧从前名叫基列·西弗。）",
    Eng:"From there he marched against the people living in Debir (formerly called Kiriath Sepher).",
    Ind:"Dari sana ia maju menyerang penduduk Debir. Nama Debir itu dahulu ialah Kiryat-Sefer."
  },
  {Bible:"Joshua", Chapter:15, Verse:16, Page:1,
    Kor:"그 때에 갈렙이, 기럇세벨을 쳐서 점령하는 사람은 그의 딸 악사와 결혼시키겠다고 말하였다.",
    Chn:"迦勒说：「谁能攻打基列·西弗将城夺取，我就把我女儿押撒给他为妻。」",
    Eng:"And Caleb said, \"I will give my daughter Acsah in marriage to the man who attacks and captures Kiriath Sepher.\"",
    Ind:"Lalu berkatalah Kaleb: \"Siapa yang menggempur Kiryat-Sefer dan merebutnya, kepadanya akan kuberikan Akhsa, anakku, menjadi isterinya.\""
  },
  {Bible:"Joshua", Chapter:15, Verse:17, Page:1,
    Kor:"갈렙의 형제 그나스의 아들인 옷니엘이 그 곳을 점령하였으므로, 갈렙은 그를 자기의 딸 악사와 결혼시켰다.",
    Chn:"迦勒兄弟基纳斯的儿子俄陀聂夺取了那城，迦勒就把女儿押撒给他为妻。",
    Eng:"Othniel son of Kenaz, Caleb's brother, took it; so Caleb gave his daughter Acsah to him in marriage.",
    Ind:"Dan Otniel, anak Kenas saudara Kaleb, merebut kota itu; lalu Kaleb memberikan kepadanya Akhsa, anaknya, menjadi isterinya."
  },
  {Bible:"Joshua", Chapter:15, Verse:18, Page:1,
    Kor:"결혼을 하고 나서, c악사는 자기의 남편 옷니엘에게 아버지에게서 밭을 얻어내라고 재촉하였다. 악사가 나귀에서 내리자, 갈렙이 딸에게 물었다. \"뭐 더 필요한 것이 있느냐?\"(c 히브리어 본문과 칠십인역 사본 가운데 몇몇은 악사가 그의 남편 옷니엘을 시켜 갈렙에게서 밭을 얻어내라고 재촉한 것으로 되어 있으나, 칠십인역 사본 가운데 더러는 옷니엘이 그의 아내 악사를 06 15:시켜 장인 갈렙에게서 밭을 얻어내라고 재촉함)",
    Chn:"押撒过门的时候，劝丈夫向她父亲求一块田，押撒一下驴，迦勒问她说：「你要什么？」",
    Eng:"One day when she came to Othniel, she urged him to ask her father for a field. When she got off her donkey, Caleb asked her, \"What can I do for you?\"",
    Ind:"Ketika perempuan itu tiba, dibujuknya suaminya untuk meminta ladang kepada ayahnya. Maka turunlah perempuan itu dari keledainya, lalu berkatalah Kaleb kepadanya: \"Ada apa?\""
  },
  {Bible:"Joshua", Chapter:15, Verse:19, Page:1,
    Kor:"악사가 대답하였다. \"저의 부탁을 하나 들어주시기 바랍니다. 아버지께서 저에게 이 d메마른 땅을 주셨으니, 샘 몇 개만이라도 주시기 바랍니다.\" 그는 딸에게 윗샘과 아랫샘을 주었다.(d 히, '네겝 땅' 또는 '남방 땅')",
    Chn:"她说：「求你赐福给我，你既将我安置在南地，求你也给我水泉。」她父亲就把上泉下泉赐给她。",
    Eng:"She replied, \"Do me a special favor. Since you have given me land in the Negev, give me also springs of water.\" So Caleb gave her the upper and lower springs.",
    Ind:"Jawabnya: \"Berikanlah kepadaku hadiah; telah kauberikan kepadaku tanah yang gersang, berikanlah juga kepadaku mata air.\" Lalu diberikannyalah kepadanya mata air yang di hulu dan mata air yang di hilir."
  },
  {Bible:"Joshua", Chapter:15, Verse:20, Page:1,
    Kor:"<유다의 성읍들> ○이 땅이 유다 자손의 지파에 속한 여러 가문이 나누어 받은 유산이다.",
    Chn:"以下是犹大支派按着宗族所得的产业。",
    Eng:"This is the inheritance of the tribe of Judah, clan by clan:",
    Ind:"Inilah milik pusaka suku bani Yehuda menurut kaum-kaum mereka."
  },
  {Bible:"Joshua", Chapter:15, Verse:21, Page:1,
    Kor:"유다 자손 지파가 차지한 성읍들 가운데서 에돔 경계선 가까이 가장 남쪽에 있는 성읍들은, 갑스엘과 에델과 야굴과",
    Chn:"犹大支派尽南边的城邑，与以东交界相近的，就是甲薛、以得、雅姑珥、",
    Eng:"The southernmost towns of the tribe of Judah in the Negev toward the boundary of Edom were: Kabzeel, Eder, Jagur,",
    Ind:"Kota-kota suku bani Yehuda yang paling ujung, dekat batas tanah Edom di Tanah Negeb, ialah Kabzeel, Eder, Yagur,"
  },
  {Bible:"Joshua", Chapter:15, Verse:22, Page:1,
    Kor:"기나와 디모나와 아다다와",
    Chn:"基拿、底摩拿、亚大达、",
    Eng:"Kinah, Dimonah, Adadah,",
    Ind:"Kina, Dimona, Adada,"
  },
  {Bible:"Joshua", Chapter:15, Verse:23, Page:1,
    Kor:"게데스와 하솔과 잇난과",
    Chn:"基低斯、夏琐、以提楠、",
    Eng:"Kedesh, Hazor, Ithnan,",
    Ind:"Kedesh, Hazor, Yitnan,"
  },
  {Bible:"Joshua", Chapter:15, Verse:24, Page:1,
    Kor:"십과 델렘과 브알롯과",
    Chn:"西弗、提链、比亚绿、",
    Eng:"Ziph, Telem, Bealoth,",
    Ind:"Zif, Telem, Bealot,"
  },
  {Bible:"Joshua", Chapter:15, Verse:25, Page:1,
    Kor:"하솔하닷다와 그리욧헤스론, 곧 하솔과",
    Chn:"夏琐·哈大他、加略·希斯 （加略·希斯 就是夏琐）、",
    Eng:"Hazor Hadattah, Kerioth Hezron (that is, Hazor),",
    Ind:"Hazor-Hadata, Keriot-Hezron, itulah Hazor;"
  },
  {Bible:"Joshua", Chapter:15, Verse:26, Page:1,
    Kor:"아맘과 세마와 몰라다와",
    Chn:"亚曼、示玛、摩拉大、",
    Eng:"Amam, Shema, Moladah,",
    Ind:"Amam, Sema, Molada,"
  },
  {Bible:"Joshua", Chapter:15, Verse:27, Page:1,
    Kor:"하살갓다와 헤스몬과 벳벨렛과",
    Chn:"哈萨·迦大、黑实门、伯·帕列、",
    Eng:"Hazar Gaddah, Heshmon, Beth Pelet,",
    Ind:"Hazar-Gada, Hesmon, Bet-Pelet,"
  },
  {Bible:"Joshua", Chapter:15, Verse:28, Page:1,
    Kor:"하살수알과 브엘세바와 비스요댜와",
    Chn:"哈萨·书亚、别是巴、比斯约他、",
    Eng:"Hazar Shual, Beersheba, Biziothiah,",
    Ind:"Hazar-Sual, Bersyeba dan segala anak kotanya,"
  },
  {Bible:"Joshua", Chapter:15, Verse:29, Page:1,
    Kor:"바알라와 이임과 에셈과",
    Chn:"巴拉、以因、以森、",
    Eng:"Baalah, Iim, Ezem,",
    Ind:"Baala, Iyim, Ezem,"
  },
  {Bible:"Joshua", Chapter:15, Verse:30, Page:1,
    Kor:"엘돌랏과 그실과 호르마와",
    Chn:"伊勒多腊、基失、何珥玛、",
    Eng:"Eltolad, Kesil, Hormah,",
    Ind:"Eltolad, Kesil, Horma,"
  },
  {Bible:"Joshua", Chapter:15, Verse:31, Page:1,
    Kor:"시글락과 맛만나와 산산나와",
    Chn:"洗革拉、麦玛拿、三撒拿、",
    Eng:"Ziklag, Madmannah, Sansannah,",
    Ind:"Ziklag, Madmana, Sansana,"
  },
  {Bible:"Joshua", Chapter:15, Verse:32, Page:1,
    Kor:"르바옷과 실힘과 아인과 림몬, 이렇게 모두 스물아홉 성읍과 그 주변 마을들이다.",
    Chn:"利巴勿、实忻、亚因、临门，共二十九座城，还有属城的村庄。",
    Eng:"Lebaoth, Shilhim, Ain and Rimmon--a total of twenty-nine towns and their villages.",
    Ind:"Lebaot, Silhim, Ain dan Rimon; seluruhnya dua puluh sembilan kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:33, Page:1,
    Kor:"○유다 지파가 차지한 평지의 성읍들은, 에스다올과 소라와 아스나와",
    Chn:"在高原有以实陶、琐拉、亚实拿、",
    Eng:"In the western foothills: Eshtaol, Zorah, Ashnah,",
    Ind:"Di Daerah Bukit: Esytaol, Zora, Asna,"
  },
  {Bible:"Joshua", Chapter:15, Verse:34, Page:1,
    Kor:"사노아와 엔간님과 답부아와 에남과",
    Chn:"撒挪亚、隐·干宁、他普亚、以楠、",
    Eng:"Zanoah, En Gannim, Tappuah, Enam,",
    Ind:"Zanoah, En-Ganim, Tapuah, Enam,"
  },
  {Bible:"Joshua", Chapter:15, Verse:35, Page:1,
    Kor:"야르뭇과 아둘람과 소고와 아세가와",
    Chn:"耶末、亚杜兰、梭哥、亚西加、",
    Eng:"Jarmuth, Adullam, Socoh, Azekah,",
    Ind:"Yarmut, Adulam, Sokho, Azeka,"
  },
  {Bible:"Joshua", Chapter:15, Verse:36, Page:1,
    Kor:"사아라임과 아디다임과 그데라와 그데로다임, 이렇게 열네 성읍과 그 주변 마을들이다.",
    Chn:"沙拉音、亚底他音、基底拉、基底罗他音，共十四座城，还有属城的村庄。",
    Eng:"Shaaraim, Adithaim and Gederah (or Gederothaim)--fourteen towns and their villages.",
    Ind:"Saaraim, Aditaim, Gedera dan Gederotaim; empat belas kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:37, Page:1,
    Kor:"스난과 하다사와 믹달갓과",
    Chn:"又有洗楠、哈大沙、麦大·迦得、",
    Eng:"Zenan, Hadashah, Migdal Gad,",
    Ind:"Zenan, Hadasa, Migdal-Gad,"
  },
  {Bible:"Joshua", Chapter:15, Verse:38, Page:1,
    Kor:"딜르안과 미스바와 욕드엘과",
    Chn:"底连、米斯巴、约帖、",
    Eng:"Dilean, Mizpah, Joktheel,",
    Ind:"Dilean, Mizpa, Yokteel,"
  },
  {Bible:"Joshua", Chapter:15, Verse:39, Page:1,
    Kor:"라기스와 보스갓과 에글론과",
    Chn:"拉吉、波斯加、伊矶伦、",
    Eng:"Lachish, Bozkath, Eglon,",
    Ind:"Lakhis, Bozkat, Eglon,"
  },
  {Bible:"Joshua", Chapter:15, Verse:40, Page:1,
    Kor:"갑본과 라맘과 기들리스와",
    Chn:"迦本、拉幔、基提利、",
    Eng:"Cabbon, Lahmas, Kitlish,",
    Ind:"Kabon, Lahmas, Kitlis,"
  },
  {Bible:"Joshua", Chapter:15, Verse:41, Page:1,
    Kor:"그데롯과 벳다곤과 나아마와 막게다, 이렇게 열여섯 성읍과 그 주변 마을들도 있었다.",
    Chn:"基低罗、伯·大衮、拿玛、玛基大，共十六座城，还有属城的村庄。",
    Eng:"Gederoth, Beth Dagon, Naamah and Makkedah--sixteen towns and their villages.",
    Ind:"Gederot, Bet-Dagon, Naama dan Makeda; enam belas kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:42, Page:1,
    Kor:"립나와 에델과 아산과",
    Chn:"又有立拿、以帖、亚珊、",
    Eng:"Libnah, Ether, Ashan,",
    Ind:"Libna, Eter, Asan,"
  },
  {Bible:"Joshua", Chapter:15, Verse:43, Page:1,
    Kor:"입다와 아스나와 느십과",
    Chn:"益弗他、亚实拿、尼悉、",
    Eng:"Iphtah, Ashnah, Nezib,",
    Ind:"Yiftah, Asna, Nezib,"
  },
  {Bible:"Joshua", Chapter:15, Verse:44, Page:1,
    Kor:"그일라와 악십과 마레사, 이렇게 아홉 성읍과 그 주변 마을들도 있었다.",
    Chn:"基伊拉、亚革悉、玛利沙，共九座城，还有属城的村庄。",
    Eng:"Keilah, Aczib and Mareshah--nine towns and their villages.",
    Ind:"Kehila, Akhzib dan Maresa; sembilan kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:45, Page:1,
    Kor:"에그론과 그 변두리 촌락과 주변 부락들,",
    Chn:"又有以革伦和属以革伦的镇市村庄；",
    Eng:"Ekron, with its surrounding settlements and villages;",
    Ind:"Ekron dengan segala anak kota dan desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:46, Page:1,
    Kor:"에그론에서 바다까지, 아스돗에 인접한 모든 성읍과 주변 마을들도 있었다.",
    Chn:"从以革伦直到海，一切靠近亚实突之地，并属其地的村庄。",
    Eng:"west of Ekron, all that were in the vicinity of Ashdod, together with their villages;",
    Ind:"Mulai dari Ekron sampai ke laut, segala yang di sisi Asdod dan desa-desanya,"
  },
  {Bible:"Joshua", Chapter:15, Verse:47, Page:1,
    Kor:"아스돗과 그 변두리 촌락과 주변 마을들도 있었다. 또 이집트 국경지대의 강과 지중해와 그 해안 일대에 있는 가사와 그 변두리 촌락과 주변 마을들도 있었다.",
    Chn:"亚实突和属亚实突的镇市村庄；迦萨和属迦萨的镇市村庄；直到埃及小河，并大海和靠近大海之地。",
    Eng:"Ashdod, its surrounding settlements and villages; and Gaza, its settlements and villages, as far as the Wadi of Egypt and the coastline of the Great Sea.",
    Ind:"Asdod dengan segala anak kota dan desa-desanya, Gaza dengan segala anak kota dan desa-desanya, sampai ke sungai tanah Mesir, Laut Besar dan pantainya."
  },
  {Bible:"Joshua", Chapter:15, Verse:48, Page:1,
    Kor:"유다 지파가 차지한 산간지방의 성읍들은, 사밀과 얏딜과 소고와",
    Chn:"在山地有沙密、雅提珥、梭哥、",
    Eng:"In the hill country: Shamir, Jattir, Socoh,",
    Ind:"Lagi di Pegunungan: Samir, Yatir, Sokho,"
  },
  {Bible:"Joshua", Chapter:15, Verse:49, Page:1,
    Kor:"단나와 기럇산나 곧 드빌과",
    Chn:"大拿、基列·萨拿（基列·萨拿就是底璧）、",
    Eng:"Dannah, Kiriath Sannah (that is, Debir),",
    Ind:"Dana, Kiryat-Sana, itulah Debir;"
  },
  {Bible:"Joshua", Chapter:15, Verse:50, Page:1,
    Kor:"아납과 에스드모와 아님과",
    Chn:"亚拿伯、以实提莫、亚念、",
    Eng:"Anab, Eshtemoh, Anim,",
    Ind:"Anab, Estemo, Anim,"
  },
  {Bible:"Joshua", Chapter:15, Verse:51, Page:1,
    Kor:"고센과 홀론과 길로, 이렇게 열한 성읍과 그 주변 마을들이다.",
    Chn:"歌珊、何伦、基罗，共十一座城，还有属城的村庄。",
    Eng:"Goshen, Holon and Giloh--eleven towns and their villages.",
    Ind:"Gosyen, Holon dan Gilo; sebelas kota dengan desa-desanya;"
  },
  {Bible:"Joshua", Chapter:15, Verse:52, Page:1,
    Kor:"이 밖에도 아랍과 두마와 에산과",
    Chn:"又有亚拉、度玛、以珊、",
    Eng:"Arab, Dumah, Eshan,",
    Ind:"Arab, Duma, Esan,"
  },
  {Bible:"Joshua", Chapter:15, Verse:53, Page:1,
    Kor:"야님과 벳답부아와 아베가와",
    Chn:"雅农、伯·他普亚、亚非加、",
    Eng:"Janim, Beth Tappuah, Aphekah,",
    Ind:"Yanum, Bet-Tapuah, Afeka,"
  },
  {Bible:"Joshua", Chapter:15, Verse:54, Page:1,
    Kor:"훔다와 기럇아르바 곧 헤브론과 시올, 이렇게 아홉 성읍과 그 주변 마을들이 있었다.",
    Chn:"宏他、基列·亚巴（基列·亚巴就是希伯 ）、洗珥，共九座城，还有属城的村庄。",
    Eng:"Humtah, Kiriath Arba (that is, Hebron) and Zior--nine towns and their villages.",
    Ind:"Humta, Kiryat-Arba, itulah Hebron, dan Zior; sembilan kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:55, Page:1,
    Kor:"그리고 마온과 갈멜과 십과 윳다와",
    Chn:"又有玛云、迦密、西弗、淤他、",
    Eng:"Maon, Carmel, Ziph, Juttah,",
    Ind:"Maon, Karmel, Zif, Yuta,"
  },
  {Bible:"Joshua", Chapter:15, Verse:56, Page:1,
    Kor:"이스르엘과 욕드암과 사노아와",
    Chn:"耶斯列、约甸、撒挪亚、",
    Eng:"Jezreel, Jokdeam, Zanoah,",
    Ind:"Yizreel, Yokdeam, Zanoah,"
  },
  {Bible:"Joshua", Chapter:15, Verse:57, Page:1,
    Kor:"가인과 기브아와 딤나, 이렇게 열 성읍과 그 주변 마을들이 있었다.",
    Chn:"该隐、基比亚、亭纳，共十座城，还有属城的村庄。",
    Eng:"Kain, Gibeah and Timnah--ten towns and their villages.",
    Ind:"Kain, Gibea dan Timna; sepuluh kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:58, Page:1,
    Kor:"그리고 할훌과 벳술과 그돌과",
    Chn:"又有哈忽、伯·夙、基突、",
    Eng:"Halhul, Beth Zur, Gedor,",
    Ind:"Halhul, Bet-Zur, Gedor,"
  },
  {Bible:"Joshua", Chapter:15, Verse:59, Page:1,
    Kor:"마아랏과 벳아놋과 엘드곤, 이렇게 여섯 성읍과 그 주변 마을들도 있었다.",
    Chn:"玛腊、伯·亚诺、伊勒提君，共六座城，还有属城的村庄。",
    Eng:"Maarath, Beth Anoth and Eltekon--six towns and their villages.",
    Ind:"Maarat, Bet-Anot dan Eltekon; enam kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:60, Page:1,
    Kor:"기럇바알 곧 기럇여아림과 랍바, 이 두 성읍과 그 주변 마을들도 있었다.",
    Chn:"又有基列·巴力（基列·巴力就是基列·耶琳）、拉巴，共两座城，还有属城的村庄。",
    Eng:"Kiriath Baal (that is, Kiriath Jearim) and Rabbah--two towns and their villages.",
    Ind:"Kiryat-Baal, itulah Kiryat-Yearim, dan Raba; dua kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:61, Page:1,
    Kor:"유다 지파가 차지한 사막지대의 성읍들은, 벳아라바와 밋딘과 스가가와",
    Chn:"在旷野有伯·亚拉巴、密丁、西迦迦、",
    Eng:"In the desert: Beth Arabah, Middin, Secacah,",
    Ind:"Di padang gurun: Bet-Araba, Midin, Sekhakha,"
  },
  {Bible:"Joshua", Chapter:15, Verse:62, Page:1,
    Kor:"닙산과 소금 성읍과 엔게디, 이렇게 여섯 성읍과 그 주변 마을들이다.",
    Chn:"匿珊、盐城、隐·基底，共六座城，还有属城的村庄。",
    Eng:"Nibshan, the City of Salt and En Gedi--six towns and their villages.",
    Ind:"Nibsan, Kota Garam dan En-Gedi; enam kota dengan desa-desanya."
  },
  {Bible:"Joshua", Chapter:15, Verse:63, Page:1,
    Kor:"○그러나 유다 자손이 예루살렘 성에 살던 여부스 사람을 쫓아내지 못하였으므로, 여부스 사람과 유다 자손이 오늘날까지 예루살렘 성에 함께 살고 있다.",
    Chn:"至于住耶路撒冷的耶布斯人，犹大人不能把他们赶出去，耶布斯人却在耶路撒冷与犹大人同住，直到今日。",
    Eng:"Judah could not dislodge the Jebusites, who were living in Jerusalem; to this day the Jebusites live there with the people of Judah.",
    Ind:"Tetapi orang Yebus, penduduk kota Yerusalem, tidak dapat dihalau oleh bani Yehuda. Jadi orang Yebus itu masih tetap diam bersama-sama dengan bani Yehuda di Yerusalem sampai sekarang."
  },
]);
