// 요한계시록 8장 · Revelation 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Revelation",8,13);
BibleDB.add([
  {Bible:"Revelation", Chapter:8, Verse:1, Page:1, Kor:"<일곱째 봉인과 금향로> 그 어린 양이 일곱째 봉인을 뗄 때에, 하늘은 약 반 시간 동안 고요하였습니다.", Chn:"", Eng:"When he opened the seventh seal, there was silence in heaven for about half an hour.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:2, Page:1, Kor:"그리고 나는 하나님 앞에 서 있는 일곱 천사를 보았습니다. 그들은 나팔을 하나씩 받아 가지고 있었습니다.", Chn:"", Eng:"And I saw the seven angels who stand before God, and to them were given seven trumpets.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:3, Page:1, Kor:"○또 다른 천사가 와서, 금향로를 들고 제단에 섰습니다. 그는 모든 성도의 기도에 향을 더해서 보좌 앞 금제단에 드리려고 많은 향을 받았습니다.", Chn:"", Eng:"Another angel, who had a golden censer, came and stood at the altar. He was given much incense to offer, with the prayers of all the saints, on the golden altar before the throne.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:4, Page:1, Kor:"그래서 향의 연기가 성도들의 기도와 함께 천사의 손으로부터 하나님 앞으로 올라갔습니다.", Chn:"", Eng:"The smoke of the incense, together with the prayers of the saints, went up before God from the angel's hand.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:5, Page:1, Kor:"그 뒤에 그 천사가 향로를 가져다가, 거기에 제단 불을 가득 채워서 땅에 던지니, 천둥과 요란한 소리와 번개와 지진이 일어났습니다.", Chn:"", Eng:"Then the angel took the censer, filled it with fire from the altar, and hurled it on the earth; and there came peals of thunder, rumblings, flashes of lightning and an earthquake.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:6, Page:1, Kor:"<나팔 소리> ○그 때에 나팔을 하나씩 가진 일곱 천사가 나팔을 불 준비를 하였습니다.", Chn:"", Eng:"Then the seven angels who had the seven trumpets prepared to sound them.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:7, Page:1, Kor:"○첫째 천사가 나팔을 부니, 우박과 불이 피에 섞여서 땅에 떨어졌습니다. 그래서 땅의 삼분의 일이 타버리고, 나무의 삼분의 일이 타버리고, 푸른 풀이 다 타버렸습니다.", Chn:"", Eng:"The first angel sounded his trumpet, and there came hail and fire mixed with blood, and it was hurled down upon the earth. A third of the earth was burned up, a third of the trees were burned up, and all the green grass was burned up.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:8, Page:1, Kor:"○둘째 천사가 나팔을 부니, 불타는 큰 산과 같은 것이 바다에 던져졌습니다. 그래서 바다의 삼분의 일이 피가 되고,", Chn:"", Eng:"The second angel sounded his trumpet, and something like a huge mountain, all ablaze, was thrown into the sea. A third of the sea turned into blood,", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:9, Page:1, Kor:"바다에 사는, 생명이 있는 피조물들의 삼분의 일이 죽고, 배들의 삼분의 일이 부서졌습니다.", Chn:"", Eng:"a third of the living creatures in the sea died, and a third of the ships were destroyed.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:10, Page:1, Kor:"○셋째 천사가 나팔을 부니, 큰 별 하나가 횃불처럼 타면서 하늘에서 떨어져서, 강들의 삼분의 일과 샘물들 위에 덮쳤습니다.", Chn:"", Eng:"The third angel sounded his trumpet, and a great star, blazing like a torch, fell from the sky on a third of the rivers and on the springs of water--", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:11, Page:1, Kor:"그 별의 이름은 '쑥'이라고 합니다. 그래서 물의 삼분의 일이 쑥이 되고, 많은 사람이 그 물을 마시고 죽었습니다. 그 물이 쓴 물로 변하였기 때문입니다.", Chn:"", Eng:"the name of the star is Wormwood. A third of the waters turned bitter, and many people died from the waters that had become bitter.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:12, Page:1, Kor:"○넷째 천사가 나팔을 부니, 해의 삼분의 일과 달의 삼분의 일과 별들의 삼분의 일이 타격을 입어서, 그것들의 삼분의 일이 어두워지고, 낮의 삼분의 일이 빛을 잃고, 밤도 역시 그렇게 되었습니다.", Chn:"", Eng:"The fourth angel sounded his trumpet, and a third of the sun was struck, a third of the moon, and a third of the stars, so that a third of them turned dark. A third of the day was without light, and also a third of the night.", Ind:""},
  {Bible:"Revelation", Chapter:8, Verse:13, Page:1, Kor:"○그리고 내가 보고 들으니, 날아가는 독수리 한 마리가 하늘 한가운데로 날면서, 큰 소리로 외쳤습니다. \"화가 있다. 화가 있다. 땅 위에 사는 사람들에게 화가 있다. 아직도 세 천사가 불어야 할 나팔 소리가 남아 있다.\"", Chn:"", Eng:"As I watched, I heard an eagle that was flying in midair call out in a loud voice: \"Woe! Woe! Woe to the inhabitants of the earth, because of the trumpet blasts about to be sounded by the other three angels!\"", Ind:""},
]);
