// 요한계시록 22장 · Revelation 22
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Revelation",22,21);
BibleDB.add([
  {Bible:"Revelation", Chapter:22, Verse:1, Page:1, Kor:"천사는 또, 수정과 같이 빛나는 생명수의 강을 내게 보여 주었습니다. 그 강은 하나님의 보좌와 어린 양의 보좌로부터 흘러 나와서,", Chn:"", Eng:"Then the angel showed me the river of the water of life, as clear as crystal, flowing from the throne of God and of the Lamb", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:2, Page:1, Kor:"도시의 넓은 거리 한가운데를 흘렀습니다. 강 양쪽에는 열두 종류의 열매를 맺는 생명 나무가 있어서, 달마다 열매를 내고, 그 나뭇잎은 민족들을 치료하는 데 쓰입니다.", Chn:"", Eng:"down the middle of the great street of the city. On each side of the river stood the tree of life, bearing twelve crops of fruit, yielding its fruit every month. And the leaves of the tree are for the healing of the nations.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:3, Page:1, Kor:"다시 저주를 받을 일이라고는 아무것도 그 도성에 없을 것입니다. 하나님과 어린 양의 보좌가 도성 안에 있고, 그의 종들이 그를 예배하며,", Chn:"", Eng:"No longer will there be any curse. The throne of God and of the Lamb will be in the city, and his servants will serve him.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:4, Page:1, Kor:"하나님의 얼굴을 뵐 것입니다. 그들의 이마에는 그의 이름이 적혀 있고,", Chn:"", Eng:"They will see his face, and his name will be on their foreheads.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:5, Page:1, Kor:"다시는 밤이 없고, 등불이나 햇빛이 필요 없습니다. 그것은 주 하나님께서 그들을 비추시기 때문입니다. 그들은 영원무궁 하도록 다스릴 것입니다.", Chn:"", Eng:"There will be no more night. They will not need the light of a lamp or the light of the sun, for the Lord God will give them light. And they will reign for ever and ever.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:6, Page:1, Kor:"<오십시오, 주 예수님> ○천사가 또 나에게 말하였습니다. \"이 말씀은 믿음직하고 참되다. 예언자들에게 영을 내려 주시는 주 하나님께서 자기의 종들에게 곧 일어날 일들을 보여 주시려고, 자기의 천사들을 보내셨다.", Chn:"", Eng:"The angel said to me, \"These words are trustworthy and true. The Lord, the God of the spirits of the prophets, sent his angel to show his servants the things that must soon take place.\"", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:7, Page:1, Kor:"'보아라, 내가 곧 오겠다' 하신 주님의 말씀을 기억하여라.\" 이 책에 기록된 예언의 말씀을 지키는 사람들은 복이 있습니다.", Chn:"", Eng:"\"Behold, I am coming soon! Blessed is he who keeps the words of the prophecy in this book.\"", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:8, Page:1, Kor:"○이 모든 것을 듣고 본 사람은 나 요한입니다. 내가 이 모든 것을 듣고 볼 때에, 이것들을 내게 보여 준 그 천사의 발 앞에 엎드려 경배하려고 하였더니,", Chn:"", Eng:"I, John, am the one who heard and saw these things. And when I had heard and seen them, I fell down to worship at the feet of the angel who had been showing them to me.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:9, Page:1, Kor:"그가 나에게 말하였습니다. \"이렇게 하지 말아라. 나도, 너와 너의 a동료 예언자들과 이 책의 말씀을 지키는 사람들과 같은 종이다. 경배는 하나님께 드려라.\"(a 그, '형제들')", Chn:"", Eng:"But he said to me, \"Do not do it! I am a fellow servant with you and with your brothers the prophets and of all who keep the words of this book. Worship God!\"", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:10, Page:1, Kor:"또 그가 나에게 말하였습니다. \"때가 가까이 왔으니, 이 책에 적힌 예언의 말씀을 봉인하지 말아라.", Chn:"", Eng:"Then he told me, \"Do not seal up the words of the prophecy of this book, because the time is near.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:11, Page:1, Kor:"이제는 불의를 행하는 자는 그대로 불의를 행하고, 더러운 자는 그대로 더러운 채로 있어라. 의로운 사람은 그대로 의를 행하고, 거룩한 사람은 그대로 거룩한 채로 있어라.\"", Chn:"", Eng:"Let him who does wrong continue to do wrong; let him who is vile continue to be vile; let him who does right continue to do right; and let him who is holy continue to be holy.\"", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:12, Page:1, Kor:"○\"보아라, 내가 곧 가겠다. 나는 각 사람에게 그 행위대로 갚아 주려고 상을 가지고 간다.", Chn:"", Eng:"\"Behold, I am coming soon! My reward is with me, and I will give to everyone according to what he has done.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:13, Page:1, Kor:"나는 알파며 오메가, 곧 처음이며 마지막이요, 시작이며 끝이다.", Chn:"", Eng:"I am the Alpha and the Omega, the First and the Last, the Beginning and the End.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:14, Page:1, Kor:"○생명 나무에 이르는 권리를 차지하려고, 그리고 성문으로 해서 도성에 들어가려고, 자기 겉옷을 깨끗이 빠는 사람은 복이 있다.", Chn:"", Eng:"\"Blessed are those who wash their robes, that they may have the right to the tree of life and may go through the gates into the city.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:15, Page:1, Kor:"개들과 마술쟁이들과 음행하는 자들과 살인자들과 우상 숭배자들과 거짓을 사랑하고 행하는 자는 다 바깥에 남아 있게 될 것이다.", Chn:"", Eng:"Outside are the dogs, those who practice magic arts, the sexually immoral, the murderers, the idolaters and everyone who loves and practices falsehood.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:16, Page:1, Kor:"○나 예수는 나의 천사를 너희에게 보내어, 교회들에 주는 이 모든 증언을 전하게 하였다. 나는 다윗의 뿌리요, 그의 자손이요, 빛나는 샛별이다.\"", Chn:"", Eng:"\"I, Jesus, have sent my angel to give you this testimony for the churches. I am the Root and the Offspring of David, and the bright Morning Star.\"", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:17, Page:1, Kor:"성령과 신부가 \"오십시오!\" 하고 말씀하십니다. 이 말을 듣는 사람도 또한 \"오십시오!\" 하고 외치십시오. 목이 마른 사람도 오십시오. 생명의 물을 원하는 사람은 거저 받으십시오.", Chn:"", Eng:"The Spirit and the bride say, \"Come!\" And let him who hears say, \"Come!\" Whoever is thirsty, let him come; and whoever wishes, let him take the free gift of the water of life.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:18, Page:1, Kor:"○나는 이 책에 기록한 예언의 말씀을 듣는 모든 사람에게 증언합니다. 누구든지 여기에 무엇을 덧붙이면, 하나님께서 그에게 이 책에 기록한 재앙들을 덧붙이실 것이요,", Chn:"", Eng:"I warn everyone who hears the words of the prophecy of this book: If anyone adds anything to them, God will add to him the plagues described in this book.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:19, Page:1, Kor:"또 누구든지 이 예언의 책에 기록한 말씀에서 무엇을 없애 버리면, 하나님께서 이 책에 기록한 생명 나무와 그 거룩한 도성에서 그가 누릴 몫을 없애 버리실 것입니다.", Chn:"", Eng:"And if anyone takes words away from this book of prophecy, God will take away from him his share in the tree of life and in the holy city, which are described in this book.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:20, Page:1, Kor:"○이 모든 계시를 증언하시는 분이 이렇게 말씀하셨습니다. \"그렇다. 내가 곧 가겠다.\" 아멘. 오십시오, 주 예수님!", Chn:"", Eng:"He who testifies to these things says, \"Yes, I am coming soon.\" Amen. Come, Lord Jesus.", Ind:""},
  {Bible:"Revelation", Chapter:22, Verse:21, Page:1, Kor:"○주 예수의 은혜가 b모든 사람에게 있기를 빕니다. c아멘.(b 다른 고대 사본들에는 '성도에게' c 다른 고대 사본들은 절 끝에 '아멘'이 없음)", Chn:"", Eng:"", Ind:""},
]);
