// 요한계시록 6장 · Revelation 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Revelation",6,17);
BibleDB.add([
  {Bible:"Revelation", Chapter:6, Verse:1, Page:1, Kor:"<일곱 봉인에 담긴 심판> 나는 그 어린 양이 그 일곱 봉인 가운데 하나를 떼는 것을 보았습니다. 그리고 나는 네 생물 가운데 하나가 우레 같은 소리로 a\"오너라!\" 하고 말하는 것을 들었습니다.(a 또는 '가거라!')", Chn:"", Eng:"I watched as the Lamb opened the first of the seven seals. Then I heard one of the four living creatures say in a voice like thunder, \"Come!\"", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:2, Page:1, Kor:"그리고 내가 보니, 흰 말 한 마리가 있는데, 그 위에 탄 사람은 활을 가지고 있었습니다. 그는 면류관을 쓰고 있는데, 그는 이기면서 나아가고, 이기려고 나아갔습니다.", Chn:"", Eng:"I looked, and there before me was a white horse! Its rider held a bow, and he was given a crown, and he rode out as a conqueror bent on conquest.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:3, Page:1, Kor:"○그 어린 양이 둘째 봉인을 뗄 때에, 나는 둘째 생물이 a\"오너라!\" 하고 말하는 것을 들었습니다.(a 또는 '가거라!')", Chn:"", Eng:"When the Lamb opened the second seal, I heard the second living creature say, \"Come!\"", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:4, Page:1, Kor:"그 때에 불빛과 같은 다른 말 한 마리가 뛰어나오는데, 그 위에 탄 사람은 사람들이 서로 죽이는 일이 벌어지도록 땅에서 평화를 없애는 권세를 받아서 가졌습니다. 또 큰 칼을 받아서 가지고 있었습니다.", Chn:"", Eng:"Then another horse came out, a fiery red one. Its rider was given power to take peace from the earth and to make men slay each other. To him was given a large sword.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:5, Page:1, Kor:"○그 어린 양이 셋째 봉인을 뗄 때에, 나는 셋째 생물이 a\"오너라!\" 하고 말하는 것을 들었습니다. 그리고 내가 보니, 검은 말 한 마리가 있는데, 그 위에 탄 사람은 손에 저울을 들고 있었습니다.(a 또는 '가거라!')", Chn:"", Eng:"When the Lamb opened the third seal, I heard the third living creature say, \"Come!\" I looked, and there before me was a black horse! Its rider was holding a pair of scales in his hand.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:6, Page:1, Kor:"그리고 네 생물 가운데서 나오는 듯한 음성이 들려 왔는데 \"밀 한 되도 하루 b품삯이요, 보리 석 되도 하루 b품삯이다. 올리브 기름과 포도주에는 해를 끼치지 말아라\" 하고 말하였습니다.(b 그, '데나리온')", Chn:"", Eng:"Then I heard what sounded like a voice among the four living creatures, saying, \"A quart of wheat for a day's wages, and three quarts of barley for a day's wages, and do not damage the oil and the wine!\"", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:7, Page:1, Kor:"○그 어린 양이 넷째 봉인을 뗄 때에, 나는 이 넷째 생물이 a\"오너라!\" 하고 말하는 것을 들었습니다.(a 또는 '가거라!')", Chn:"", Eng:"When the Lamb opened the fourth seal, I heard the voice of the fourth living creature say, \"Come!\"", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:8, Page:1, Kor:"그리고 내가 보니, 청황색 말 한 마리가 있는데, 그 위에 탄 사람의 이름은 '사망'이고, c지옥이 그를 뒤따르고 있었습니다. 그들은 칼과 기근과 죽음과 들짐승으로써 사분의 일에 이르는 땅의 주민들을 멸하는 권세를 받아 가지고 있었습니다.(c 그, '하데스')", Chn:"", Eng:"I looked, and there before me was a pale horse! Its rider was named Death, and Hades was following close behind him. They were given power over a fourth of the earth to kill by sword, famine and plague, and by the wild beasts of the earth.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:9, Page:1, Kor:"○그 어린 양이 다섯째 봉인을 뗄 때에, 나는 제단 아래에서, 하나님의 말씀 때문에, 또 그들이 말한 증언 때문에, 죽임을 당한 사람들의 영혼을 보았습니다.", Chn:"", Eng:"When he opened the fifth seal, I saw under the altar the souls of those who had been slain because of the word of God and the testimony they had maintained.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:10, Page:1, Kor:"그들은 큰 소리로 부르짖었습니다. \"거룩하시고 참되신 지배자님, 우리가 얼마나 더 오래 기다려야 지배자님께서 땅 위에 사는 자들을 심판하시어 우리가 흘린 피의 원한을 풀어 주시겠습니까?\"", Chn:"", Eng:"They called out in a loud voice, \"How long, Sovereign Lord, holy and true, until you judge the inhabitants of the earth and avenge our blood?\"", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:11, Page:1, Kor:"그리고 그들은 흰 두루마기를 한 벌씩 받아 가지고 있었습니다. 그들은 그들과 같은 동료 종들과 그들의 d형제자매들 가운데서 그들과 같이 죽임을 당하기로 되어 있는 사람의 수가 차기까지, 아직도 더 쉬어야 한다는 말씀을 들었습니다.(d 그, '형제들')", Chn:"", Eng:"Then each of them was given a white robe, and they were told to wait a little longer, until the number of their fellow servants and brothers who were to be killed as they had been was completed.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:12, Page:1, Kor:"○그 어린 양이 여섯째 봉인을 뗄 때에, 나는 큰 지진이 일어나는 것을 보았습니다. 그리고 해는 검은 머리털로 짠 천과 같이 검게 되고, 달은 온통 피와 같이 되고,", Chn:"", Eng:"I watched as he opened the sixth seal. There was a great earthquake. The sun turned black like sackcloth made of goat hair, the whole moon turned blood red,", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:13, Page:1, Kor:"하늘의 별들은, 무화과나무가 거센 바람에 흔들려서 설익은 열매가 떨어지듯이, 떨어졌습니다.", Chn:"", Eng:"and the stars in the sky fell to earth, as late figs drop from a fig tree when shaken by a strong wind.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:14, Page:1, Kor:"하늘은 두루마리가 말리듯이 사라지고, 모든 산과 섬은 제자리에서 옮겨졌습니다.", Chn:"", Eng:"The sky receded like a scroll, rolling up, and every mountain and island was removed from its place.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:15, Page:1, Kor:"그러자 땅의 왕들과 고관들과 장군들과 부자들과 세도가들과 노예들과 자유인들이 동굴과 산의 바위들 틈에 숨어서,", Chn:"", Eng:"Then the kings of the earth, the princes, the generals, the rich, the mighty, and every slave and every free man hid in caves and among the rocks of the mountains.", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:16, Page:1, Kor:"산과 바위를 향하여 말하였습니다. \"우리 위에 무너져 내려서, 보좌에 앉으신 분의 얼굴과 어린 양의 진노로부터 우리를 숨겨다오.", Chn:"", Eng:"They called to the mountains and the rocks, \"Fall on us and hide us from the face of him who sits on the throne and from the wrath of the Lamb!", Ind:""},
  {Bible:"Revelation", Chapter:6, Verse:17, Page:1, Kor:"그들이 진노를 받을 큰 날이 이르렀다. 누가 이것을 버티어 낼 수 있겠느냐?\"", Chn:"", Eng:"For the great day of their wrath has come, and who can stand?\"", Ind:""},
]);
