// 요한계시록 3장 · Revelation 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Revelation",3,22);
BibleDB.add([
  {Bible:"Revelation", Chapter:3, Verse:1, Page:1, Kor:"<사데 교회에 보내는 말씀> \"사데 교회의 a심부름꾼에게 이렇게 써 보내어라. '하나님의 일곱 영과 일곱 별을 가지신 분이 말씀하신다. ○나는 네 행위를 안다. 너는 살아 있다는 이름은 있으나, 실상은 죽은 것이다.(a 또는 '천사')", Chn:"", Eng:"\"To the angel of the church in Sardis write: These are the words of him who holds the seven spirits of God and the seven stars. I know your deeds; you have a reputation of being alive, but you are dead.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:2, Page:1, Kor:"깨어나라. 그리고 아직 남아 있지만 막 죽어 가는 자들을 굳건하게 하여라. 나는 네 행위가 나의 하나님 앞에서 완전하다고는 생각하지 않는다.", Chn:"", Eng:"Wake up! Strengthen what remains and is about to die, for I have not found your deeds complete in the sight of my God.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:3, Page:1, Kor:"그러므로 네가 그 가르침을 어떻게 받고 어떻게 들었는지를 되새겨서, 굳게 지키고, 회개하여라. 만일 네가 깨어 있지 않으면 내가 도둑같이 올 것인데, 어느 때에 내가 네게 올지를 너는 알지 못한다.", Chn:"", Eng:"Remember, therefore, what you have received and heard; obey it, and repent. But if you do not wake up, I will come like a thief, and you will not know at what time I will come to you.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:4, Page:1, Kor:"그러나 사데에는 자기 옷을 더럽히지 않은 사람 몇이 있다. 그들은 흰 옷을 입고 나와 함께 다닐 것인데, 그들은 그럴 자격이 있기 때문이다.", Chn:"", Eng:"Yet you have a few people in Sardis who have not soiled their clothes. They will walk with me, dressed in white, for they are worthy.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:5, Page:1, Kor:"이기는 사람은 이와 같이 흰 옷을 입을 것인데, 나는 그의 이름을 생명책에서 지워 버리지 않을 것이며, 내 아버지 앞과 아버지의 천사들 앞에서 그의 이름을 시인할 것이다.", Chn:"", Eng:"He who overcomes will, like them, be dressed in white. I will never blot out his name from the book of life, but will acknowledge his name before my Father and his angels.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:6, Page:1, Kor:"귀가 있는 사람은, 성령이 교회들에 하시는 말씀을 들어라.'\"", Chn:"", Eng:"He who has an ear, let him hear what the Spirit says to the churches.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:7, Page:1, Kor:"<빌라델비아 교회에 보내는 말씀> ○\"빌라델비아 교회의 a심부름꾼에게 이렇게 써 보내라.  '거룩하신 분, 참되신 분, 다윗의 열쇠를 가지고 계신 분, 여시면 닫을 사람이 없고 닫으시면 열 사람이 없는 그분이 말씀하신다. (a 또는 '천사')", Chn:"", Eng:"\"To the angel of the church in Philadelphia write: These are the words of him who is holy and true, who holds the key of David. What he opens no one can shut, and what he shuts no one can open.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:8, Page:1, Kor:"나는 네 행위를 안다. 보아라, 내가 네 앞에 문을 하나 열어 두었는데, 아무도 그것을 닫을 수 없다. 네가 힘은 적으나, 내 말을 지키며, 내 이름을 모른다고 하지 않았다.", Chn:"", Eng:"I know your deeds. See, I have placed before you an open door that no one can shut. I know that you have little strength, yet you have kept my word and have not denied my name.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:9, Page:1, Kor:"보아라, 내가 사탄의 무리에 속한 자들을 네 손에 맡기겠다. 그들은 스스로 유대 사람이라고 하지만, 사실은 그렇지 않고, 거짓말을 하는 자들이다. 보아라, 내가 그들이 와서 네 앞에 꿇어 엎드리게 하고, 내가 너를 사랑하였다는 것을 알게 하겠다.", Chn:"", Eng:"I will make those who are of the synagogue of Satan, who claim to be Jews though they are not, but are liars--I will make them come and fall down at your feet and acknowledge that I have loved you.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:10, Page:1, Kor:"인내하라는 내 말을 네가 지켰으니, 온 세상에 닥쳐올 시험을 받을 때에, 나도 너를 지켜 주겠다. 시험은 땅 위에 사는 사람들을 시험하려고 닥치는 것이다.", Chn:"", Eng:"Since you have kept my command to endure patiently, I will also keep you from the hour of trial that is going to come upon the whole world to test those who live on the earth.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:11, Page:1, Kor:"내가 곧 가겠다. 너는 네가 가진 것을 굳게 붙잡아서, 아무도 네 b면류관을 빼앗지 못하게 하여라.(b 그, '월계관')", Chn:"", Eng:"I am coming soon. Hold on to what you have, so that no one will take your crown.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:12, Page:1, Kor:"이기는 사람은, 내가 내 하나님의 성전에 기둥이 되게 하겠다. 그는 다시는 성전을 떠나지 않을 것이다. 나는 내 하나님의 이름과 내 하나님의 도시, 곧 하늘에서 내 하나님께로부터 내려오는 새 예루살렘의 이름과 또 나의 새 이름을 그 사람의 몸에 써 두겠다.", Chn:"", Eng:"Him who overcomes I will make a pillar in the temple of my God. Never again will he leave it. I will write on him the name of my God and the name of the city of my God, the new Jerusalem, which is coming down out of heaven from my God; and I will also write on him my new name.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:13, Page:1, Kor:"귀가 있는 사람은, 성령이 교회들에 하시는 말씀을 들어라.'\"", Chn:"", Eng:"He who has an ear, let him hear what the Spirit says to the churches.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:14, Page:1, Kor:"<라오디게아 교회에 보내는 말씀> ○\"라오디게아 교회의 a심부름꾼에게 이렇게 써 보내어라. '아멘이신 분이시요, 신실하시고 참되신 증인이시요, 하나님의 창조의 c처음이신 분이 말씀하신다.(a 또는 '천사' c 또는 '기원' 또는 '근원')", Chn:"", Eng:"\"To the angel of the church in Laodicea write: These are the words of the Amen, the faithful and true witness, the ruler of God's creation.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:15, Page:1, Kor:"○나는 네 행위를 안다. 너는 차지도 않고, 뜨겁지도 않다. 네가 차든지 뜨겁든지 하면 좋겠다.", Chn:"", Eng:"I know your deeds, that you are neither cold nor hot. I wish you were either one or the other!", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:16, Page:1, Kor:"네가 이렇게 미지근하여, 뜨겁지도 않고 차지도 않으니, 나는 너를 내 입에서 뱉어 버리겠다.", Chn:"", Eng:"So, because you are lukewarm--neither hot nor cold--I am about to spit you out of my mouth.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:17, Page:1, Kor:"너는 풍족하여 부족한 것이 조금도 없다고 하지만, 실상 너는, 네가 비참하고 불쌍하고 가난하고 눈이 멀고 벌거벗은 것을 알지 못한다.", Chn:"", Eng:"You say, 'I am rich; I have acquired wealth and do not need a thing.' But you do not realize that you are wretched, pitiful, poor, blind and naked.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:18, Page:1, Kor:"그러므로 나는 네게 권한다. 네가 부유하게 되려거든 불에 정련한 금을 내게서 사고, 네 벌거벗은 수치를 가려서 드러내지 않으려거든 흰 옷을 사서 입고, 네 눈이 밝아지려거든 안약을 사서 눈에 발라라.", Chn:"", Eng:"I counsel you to buy from me gold refined in the fire, so you can become rich; and white clothes to wear, so you can cover your shameful nakedness; and salve to put on your eyes, so you can see.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:19, Page:1, Kor:"나는 내가 사랑하는 사람은 누구든지 책망도 하고 징계도 한다. 그러므로 너는 열심을 내어 노력하고, 회개하여라.", Chn:"", Eng:"Those whom I love I rebuke and discipline. So be earnest, and repent.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:20, Page:1, Kor:"보아라, 내가 문 밖에 서서, 문을 두드리고 있다. 누구든지 내 음성을 듣고 문을 열면, 나는 그에게로 들어가서 그와 함께 먹고, 그는 나와 함께 먹을 것이다.", Chn:"", Eng:"Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with him, and he with me.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:21, Page:1, Kor:"이기는 사람은, 내가 이긴 뒤에 내 아버지와 함께 아버지의 보좌에 앉은 것과 같이, 나와 함께 내 보좌에 앉게 하여 주겠다.", Chn:"", Eng:"To him who overcomes, I will give the right to sit with me on my throne, just as I overcame and sat down with my Father on his throne.", Ind:""},
  {Bible:"Revelation", Chapter:3, Verse:22, Page:1, Kor:"귀가 있는 사람은, 성령이 교회들에 하시는 말씀을 들어라.'\"", Chn:"", Eng:"He who has an ear, let him hear what the Spirit says to the churches.\"", Ind:""},
]);
