// 역대상 8장 · 1Chronicles 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",8,40);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:8, Verse:1, Page:1,
    Kor:"<베냐민의 자손> 베냐민은 맏아들 벨라와 둘째 아스벨과 셋째 아하라와",
    Chn:"便雅悯的长子比拉，次子亚实别，三子亚哈拉，",
    Eng:"Benjamin was the father of Bela his firstborn, Ashbel the second son, Aharah the third,",
    Ind:"Benyamin memperanakkan Bela, anak sulungnya, Asybel, anak yang kedua, Ahrah, anak yang ketiga,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:2, Page:1,
    Kor:"넷째 노하와 다섯째 라바를 낳았다.",
    Chn:"四子挪哈，五子拉法。",
    Eng:"Nohah the fourth and Rapha the fifth.",
    Ind:"Noha, anak yang keempat dan Rafa, anak yang kelima."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:3, Page:1,
    Kor:"○벨라에게 자손이 있는데, 그들은 앗달과 게라와 a아비훗과(a 또는 '에훗의 아버지')",
    Chn:"比拉的儿子是亚大、基拉、亚比忽、",
    Eng:"The sons of Bela were: Addar, Gera, Abihud,",
    Ind:"Anak-anak Bela ialah Adar, Gera, Abihud,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:4, Page:1,
    Kor:"아비수아와 나아만과 아호아와",
    Chn:"亚比书、乃幔、亚何亚、",
    Eng:"Abishua, Naaman, Ahoah,",
    Ind:"Abisua, Naaman, Ahoah,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:5, Page:1,
    Kor:"게라와 스부반과 후람이다.",
    Chn:"基拉、示孚汛、户兰。",
    Eng:"Gera, Shephuphan and Huram.",
    Ind:"Gera, Sefufan dan Huram."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:6, Page:1,
    Kor:"○에훗의 자손은 다음과 같다. 이들은 게바에 사는 가문들의 족장들로서, 게바 주민을 마나핫으로 사로잡아 간",
    Chn:"以忽的儿子作迦巴居民的族长，被掳到玛拿辖；",
    Eng:"These were the descendants of Ehud, who were heads of families of those living in Geba and were deported to Manahath:",
    Ind:"Inilah anak-anak Ehud; mereka ini adalah kepala-kepala puak penduduk Geba yang diangkut ke dalam pembuangan ke Manahat;"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:7, Page:1,
    Kor:"나아만과 아히야와 게라인데, 그들을 사로잡아 간 게라가 웃사와 아히훗을 낳았다.",
    Chn:"以忽的儿子乃幔、亚希亚、基拉也被掳去。基拉生乌撒、亚希忽。",
    Eng:"Naaman, Ahijah, and Gera, who deported them and who was the father of Uzza and Ahihud.",
    Ind:"Naaman, Ahia dan Gera mengangkut mereka ke dalam pembuangan; dia memperanakkan Uza dan Ahihud."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:8, Page:1,
    Kor:"○사하라임은 모압 평지에서 자기의 아내 후심과 바아라를 내보낸 뒤에 아들을 낳았는데,",
    Chn:"沙哈连休他二妻户伸和巴拉之后，在摩押地生了儿子。",
    Eng:"Sons were born to Shaharaim in Moab after he had divorced his wives Hushim and Baara.",
    Ind:"Saharaim mendapat anak di daerah Moab, sesudah diusirnya Husim dan Baara, isteri-isterinya."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:9, Page:1,
    Kor:"아내 호데스에게서 요밥과 시비야와 메사와 말감과",
    Chn:"他与妻贺得同房，生了约巴、洗比雅、米沙、玛拉干、",
    Eng:"By his wife Hodesh he had Jobab, Zibia, Mesha, Malcam,",
    Ind:"Ia mendapat anak dari Hodesh, isterinya, yakni Yobab, Zibya, Mesa, Malkam,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:10, Page:1,
    Kor:"여우스와 사갸와 미르마를 낳았다. 이 아들들은 그들 가문의 족장들이다.",
    Chn:"耶乌斯、沙迦、米玛。他这些儿子都是族长。",
    Eng:"Jeuz, Sakia and Mirmah. These were his sons, heads of families.",
    Ind:"Yeus, Sokhya dan Mirma; itulah anak-anaknya, kepala-kepala puak;"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:11, Page:1,
    Kor:"○또 사하라임은 아내 후심에게서 아비둡과 엘바알을 낳았다.",
    Chn:"他的妻户伸给他生的儿子有亚比突、以利巴力。",
    Eng:"By Hushim he had Abitub and Elpaal.",
    Ind:"sebelum itu dari Husim ia telah mendapat anak, yakni Abitub dan Elpaal."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:12, Page:1,
    Kor:"○엘바알의 아들은 에벨과 미삼과 세멧인데, 이 세멧이 오노와 롯과 그 주변 마을들을 세웠다.",
    Chn:"以利巴力的儿子是希伯、米珊、沙麦。沙麦建立阿挪和罗德二城与其村庄。",
    Eng:"The sons of Elpaal: Eber, Misham, Shemed (who built Ono and Lod with its surrounding villages),",
    Ind:"Anak-anak Elpaal ialah Eber, Misam dan Semed; dia ini mendirikan kota Ono dan kota Lod dengan segala anak kotanya."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:13, Page:1,
    Kor:"<갓과 아얄론의 베냐민 사람> ○브리아와 세마는 아얄론에 사는 가문들의 족장으로서, 이들이 가드 주민을 내쫓았다.",
    Chn:"又有比利亚和示玛是亚雅 居民的族长，是驱逐迦特人的。",
    Eng:"and Beriah and Shema, who were heads of families of those living in Aijalon and who drove out the inhabitants of Gath.",
    Ind:"Beria dan Sema adalah kepala-kepala puak penduduk Ayalon; mereka telah menghalau penduduk Gat."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:14, Page:1,
    Kor:"아히요와 사삭과 여레못과",
    Chn:"亚希约、沙煞、耶利末、",
    Eng:"Ahio, Shashak, Jeremoth,",
    Ind:"Ahyo, Sasak, Yeremot,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:15, Page:1,
    Kor:"스바댜와 아랏과 에델과",
    Chn:"西巴第雅、亚拉得、亚得、",
    Eng:"Zebadiah, Arad, Eder,",
    Ind:"Zebaja, Arad, Eder,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:16, Page:1,
    Kor:"미가엘과 이스바와 요하는 브리아의 아들이다.",
    Chn:"米迦勒、伊施巴、约哈都是比利亚的儿子。",
    Eng:"Michael, Ishpah and Joha were the sons of Beriah.",
    Ind:"Mikhael, Yispa dan Yoha ialah anak-anak Beria."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:17, Page:1,
    Kor:"<예루살렘의 베냐민 사람들> ○스바댜와 므술람과 히스기와 헤벨과",
    Chn:"西巴第雅、米书兰、希西基、希伯、",
    Eng:"Zebadiah, Meshullam, Hizki, Heber,",
    Ind:"Zebaja, Mesulam, Hizki, Heber,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:18, Page:1,
    Kor:"이스므래와 이슬리아와 요밥은 엘바알의 아들이다.",
    Chn:"伊施米莱、伊斯利亚、约巴都是以利巴力的儿子。",
    Eng:"Ishmerai, Izliah and Jobab were the sons of Elpaal.",
    Ind:"Yismerai, Yizlia dan Yobab ialah anak-anak Elpaal."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:19, Page:1,
    Kor:"○야김과 시그리와 삽디와",
    Chn:"雅金、细基 利、撒底、",
    Eng:"Jakim, Zicri, Zabdi,",
    Ind:"Yakim, Zikhri, Zabdi,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:20, Page:1,
    Kor:"엘리에내와 실르대와 엘리엘과",
    Chn:"以利乃、洗勒太、以列、",
    Eng:"Elienai, Zillethai, Eliel,",
    Ind:"Elyoenai, Ziletai, Eliel,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:21, Page:1,
    Kor:"아다야와 브라야와 시므랏은 시므이의 아들이다.",
    Chn:"亚大雅、比拉雅、申拉都是示每的儿子。",
    Eng:"Adaiah, Beraiah and Shimrath were the sons of Shimei.",
    Ind:"Adaya, Beraya dan Simrat ialah anak-anak Simei."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:22, Page:1,
    Kor:"○이스반과 에벨과 엘리엘과",
    Chn:"伊施班、希伯、以列、",
    Eng:"Ishpan, Eber, Eliel,",
    Ind:"Yispan, Eber, Eliel,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:23, Page:1,
    Kor:"압돈과 시그리와 하난과",
    Chn:"亚伯顿、细基利、哈难、",
    Eng:"Abdon, Zicri, Hanan,",
    Ind:"Abdon, Zikhri, Hanan,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:24, Page:1,
    Kor:"하나냐와 엘람과 안도디야와",
    Chn:"哈拿尼雅、以拦、安陀提雅、",
    Eng:"Hananiah, Elam, Anthothijah,",
    Ind:"Hananya, Elam, Antotia,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:25, Page:1,
    Kor:"이브드야와 브누엘은 사삭의 아들이다.",
    Chn:"伊弗底雅、毗努伊勒都是沙煞的儿子。",
    Eng:"Iphdeiah and Penuel were the sons of Shashak.",
    Ind:"Yifdeya dan Pnuel ialah anak-anak Sasak."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:26, Page:1,
    Kor:"○삼스래와 스하랴와 아달랴와",
    Chn:"珊示莱、示哈利、亚他利雅、",
    Eng:"Shamsherai, Shehariah, Athaliah,",
    Ind:"Samserai, Seharya, Atalya,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:27, Page:1,
    Kor:"야아레시야와 엘리야와 시그리는 여로함의 아들이다.",
    Chn:"雅利西、以利亚、细基利都是耶罗罕的儿子。",
    Eng:"Jaareshiah, Elijah and Zicri were the sons of Jeroham.",
    Ind:"Yaaresya, Elia dan Zikhri ialah anak-anak Yeroham."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:28, Page:1,
    Kor:"○이들은 족보에 오른 각 가문의 족장들이며 이 족장들은 예루살렘에서 살았다.",
    Chn:"这些人都是著名的族长，住在耶路撒冷。",
    Eng:"All these were heads of families, chiefs as listed in their genealogy, and they lived in Jerusalem.",
    Ind:"Itulah para kepala puak, para kepala menurut keturunan mereka; mereka ini diam di Yerusalem."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:29, Page:1,
    Kor:"<기브온과 예루살렘의 베냐민 사람> ○기브온의 b아버지 c여이엘이 기브온에 살았는데, 그 아내의 이름은 마아가이다.(b 또는 '성읍 지도자' 또는 '군지휘관'을 뜻하기도 함 c 칠십인역 사본들을 따름)",
    Chn:"在基遍住的有基遍的父亲耶利。他的妻名叫玛迦；",
    Eng:"Jeiel the father of Gibeon lived in Gibeon. His wife's name was Maacah,",
    Ind:"Tetapi di Gibeon diam bapa Gibeon, yakni Yeiel, dan nama isterinya ialah Maakha."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:30, Page:1,
    Kor:"그의 맏아들은 압돈이며, 그 아래로 수르와 기스와 바알과 나답과",
    Chn:"他长子是亚伯顿。他又生苏珥、基士、巴力、拿答、",
    Eng:"and his firstborn son was Abdon, followed by Zur, Kish, Baal, Ner, Nadab,",
    Ind:"Anak sulungnya ialah Abdon, lalu Zur, Kish, Baal, Nadab,"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:31, Page:1,
    Kor:"그돌과 아히요와 세겔이 있다.",
    Chn:"基多、亚希约、撒迦、米基罗。",
    Eng:"Gedor, Ahio, Zeker",
    Ind:"Gedor, Ahyo, Zekher"
  },
  {Bible:"1Chronicles", Chapter:8, Verse:32, Page:1,
    Kor:"미글롯은 시므아를 낳았는데, 이들도 다른 친족들을 마주 보며, 자기들의 친족들과 함께 예루살렘에서 살았다.",
    Chn:"米基罗生示米暗。这些人和他们的弟兄在耶路撒冷对面居住。",
    Eng:"and Mikloth, who was the father of Shimeah. They too lived near their relatives in Jerusalem.",
    Ind:"dan Miklot yang memperanakkan Simea. Juga mereka ini pergi diam berdekatan dengan saudara-saudara mereka di Yerusalem bersama-sama saudara mereka yang lain."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:33, Page:1,
    Kor:"<사울 왕의 가족> ○넬은 기스를 낳고, 기스는 사울을 낳고, 사울은 요나단과 말기수아와 아비나답과 d에스바알을 낳았다.(d 일명, '이스보셋')",
    Chn:"尼珥生基士；基士生扫罗；扫罗生约拿单、麦基舒亚、亚比拿达、伊施·巴力。",
    Eng:"Ner was the father of Kish, Kish the father of Saul, and Saul the father of Jonathan, Malki-Shua, Abinadab and Esh-Baal.",
    Ind:"Ner memperanakkan Kish; Kish memperanakkan Saul; Saul memperanakkan Yonatan, Malkisua, Abinadab dan Esybaal."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:34, Page:1,
    Kor:"요나단의 아들은 e므립바알이며 므립바알은 미가를 낳았다.(e 일명, '므비보셋')",
    Chn:"约拿单的儿子是米力·巴力；米力·巴力生米迦。",
    Eng:"The son of Jonathan: Merib-Baal, who was the father of Micah.",
    Ind:"Anak Yonatan ialah Meribaal dan Meribaal memperanakkan Mikha."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:35, Page:1,
    Kor:"○미가의 아들들은 비돈과 멜렉과 다레아와 아하스이다.",
    Chn:"米迦的儿子是毗敦、米勒、他利亚、亚哈斯；",
    Eng:"The sons of Micah: Pithon, Melech, Tarea and Ahaz.",
    Ind:"Anak Mikha ialah Piton, Melekh, Tarea dan Ahas."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:36, Page:1,
    Kor:"아하스는 여호앗다를 낳고, 여호앗다는 알레멧과 아스마웻과 시므리를 낳고, 시므리는 모사를 낳았다.",
    Chn:"亚哈斯生耶何阿达；耶何阿达生亚拉篾、亚斯玛威、心利；心利生摩撒；",
    Eng:"Ahaz was the father of Jehoaddah, Jehoaddah was the father of Alemeth, Azmaveth and Zimri, and Zimri was the father of Moza.",
    Ind:"Ahas memperanakkan Yoada; Yoada memperanakkan Alemet, Azmawet dan Zimri; Zimri memperanakkan Moza."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:37, Page:1,
    Kor:"모사는 비느아를 낳았다. 비느아의 아들은 라바이고, 그 아들은 엘르아사이고, 그 아들은 아셀이다.",
    Chn:"摩撒生比尼亚；比尼亚的儿子是拉法；拉法的儿子是以利亚萨；以利亚萨的儿子是亚悉。",
    Eng:"Moza was the father of Binea; Raphah was his son, Eleasah his son and Azel his son.",
    Ind:"Moza memperanakkan Bina; anak orang ini ialah Rafa, dan anak orang ini ialah Elasa, dan anak orang ini ialah Azel."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:38, Page:1,
    Kor:"○아셀에게 여섯 아들이 있는데, 그들의 이름은 아스리감과 보그루와 이스마엘과 스아랴와 오바댜와 하난이다. 이 모두가 아셀의 아들이다.",
    Chn:"亚悉有六个儿子，他们的名字是亚斯利干、波基路、以实玛利、示亚利雅、俄巴底雅、哈难。这都是亚悉的儿子。",
    Eng:"Azel had six sons, and these were their names: Azrikam, Bokeru, Ishmael, Sheariah, Obadiah and Hanan. All these were the sons of Azel.",
    Ind:"Azel mempunyai enam orang anak, dan inilah nama-nama mereka: Azrikam, Bokhru, Ismael, Searya, Obaja dan Hanan. Itulah sekaliannya anak-anak Azel."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:39, Page:1,
    Kor:"아셀의 아우 에섹의 아들은, 맏아들이 울람이고, 둘째가 여우스이고, 셋째가 엘리벨렛이다.",
    Chn:"亚悉兄弟以设的长子是乌兰，次子耶乌施，三子是以利法列。",
    Eng:"The sons of his brother Eshek: Ulam his firstborn, Jeush the second son and Eliphelet the third.",
    Ind:"Anak-anak Esek, saudaranya, ialah Ulam, anak sulungnya, lalu Yeush, anak yang kedua, dan Elifelet, anak yang ketiga."
  },
  {Bible:"1Chronicles", Chapter:8, Verse:40, Page:1,
    Kor:"○울람의 아들은 활을 잘 쏘는 용감한 군인들인데, 아들과 손자가 많아서 모두 백오십 명이나 되었다. 이들이 모두 베냐민의 자손이다.",
    Chn:"乌兰的儿子都是大能的勇士，是弓箭手，他们有许多的子孙，共一百五十名，都是便雅悯人。",
    Eng:"The sons of Ulam were brave warriors who could handle the bow. They had many sons and grandsons--150 in all. All these were the descendants of Benjamin.",
    Ind:"Anak-anak Ulam itu adalah orang-orang berani, pahlawan-pahlawan yang gagah perkasa, pemanah-pemanah; anak dan cucu mereka banyak: seratus lima puluh orang. Mereka semuanya itu termasuk bani Benyamin."
  },
]);
