// 역대상 26장 · 1Chronicles 26
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",26,34);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:26, Verse:1, Page:1,
    Kor:"<성전 문지기> 문지기의 갈래는 다음과 같다. 고라 가문에서는, 아삽의 자손인 고레의 아들 므셀레먀와,",
    Chn:"守门的班次记在下面：可拉族亚萨的子孙中，有可利的儿子米施利米雅。",
    Eng:"This is the list of the Israelites--heads of families, commanders of thousands and commanders of hundreds, and their officers, who served the king in all that concerned the army divisions that were on duty month by month throughout the year. Each division consisted of 24,000 men.",
    Ind:"Tentang rombongan para penunggu pintu: dari orang Korah ialah Meselemya bin Kore dari keturunan Ebyasaf."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:2, Page:1,
    Kor:"므셀레먀의 아들인 맏아들 스가랴와, 둘째 여디아엘과, 셋째 스바댜와, 넷째 야드니엘과,",
    Chn:"米施利米雅的长子是撒迦利亚，次子是耶叠，三子是西巴第雅，四子是耶提聂，",
    Eng:"In charge of the first division, for the first month, was Jashobeam son of Zabdiel. There were 24,000 men in his division.",
    Ind:"Meselemya mempunyai anak-anak, yakni Zakharia, anak sulung, Yediael, anak yang kedua, Zebaja, anak yang ketiga, Yatniel, anak yang keempat,"
  },
  {Bible:"1Chronicles", Chapter:26, Verse:3, Page:1,
    Kor:"다섯째 엘람과, 여섯째 여호하난과, 일곱째 엘여호에내이다.",
    Chn:"五子是以拦，六子是约哈难，七子是以利约乃。",
    Eng:"He was a descendant of Perez and chief of all the army officers for the first month.",
    Ind:"Elam, anak yang kelima, Yohanan, anak yang keenam, Elyoenai, anak yang ketujuh."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:4, Page:1,
    Kor:"○오벳에돔의 아들은, 맏아들 스마야와, 둘째 여호사밧과, 셋째 요아와, 넷째 사갈과, 다섯째 느다넬과,",
    Chn:"俄别·以东的长子是示玛雅，次子是约萨拔，三子是约亚，四子是沙甲，五子是拿坦业，",
    Eng:"In charge of the division for the second month was Dodai the Ahohite; Mikloth was the leader of his division. There were 24,000 men in his division.",
    Ind:"Obed-Edom mempunyai anak-anak, yakni Semaya, anak sulung, Yozabad, anak yang kedua, Yoah, anak yang ketiga, Sakhar, anak yang keempat, Netaneel, anak yang kelima,"
  },
  {Bible:"1Chronicles", Chapter:26, Verse:5, Page:1,
    Kor:"여섯째 암미엘과, 일곱째 잇사갈과, 여덟째 브울래대이다. 하나님께서 오벳에돔에게 이와 같이 복을 주셨다.",
    Chn:"六子是亚米利，七子是以萨迦，八子是毗乌利太，因为　神赐福与俄别·以东。",
    Eng:"The third army commander, for the third month, was Benaiah son of Jehoiada the priest. He was chief and there were 24,000 men in his division.",
    Ind:"Amiel, anak yang keenam, Isakhar, anak yang ketujuh dan Peuletai, anak yang kedelapan, sebab Allah telah memberkati dia."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:6, Page:1,
    Kor:"○오벳에돔의 아들 스마야도 아들들을 낳았다. 그들은 용맹스러운 사람들이었으므로, 그들 가문의 지도자가 되었다.",
    Chn:"他的儿子示玛雅有几个儿子，都是大能的壮士，掌管父亲的家。",
    Eng:"This was the Benaiah who was a mighty man among the Thirty and was over the Thirty. His son Ammizabad was in charge of his division.",
    Ind:"Bagi Semaya, anak Obed-Edom itu, lahir anak-anak. Mereka memegang pemerintahan di antara puak mereka, sebab mereka itu adalah pahlawan-pahlawan yang gagah perkasa."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:7, Page:1,
    Kor:"스마야의 아들은 오드니와 르바엘과 오벳과 엘사밧이다. 엘사밧의 형제 엘리후와 스마갸는 유능한 사람이다.",
    Chn:"示玛雅的儿子是俄得尼、利法益、俄备得、以利萨巴。以利萨巴的弟兄是壮士，还有以利户和西玛迦。",
    Eng:"The fourth, for the fourth month, was Asahel the brother of Joab; his son Zebadiah was his successor. There were 24,000 men in his division.",
    Ind:"Anak-anak Semaya ialah Otni, Refael, Obed dan Elzabad serta saudara-saudaranya, yakni Elihu dan Semakhya, orang-orang gagah perkasa."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:8, Page:1,
    Kor:"○이들이 모두 오벳에돔의 자손이다. 그들과 그 아들과 형제들은 맡은 일을 할 수 있는 능력을 가진 용맹스러운 사람들이다. 오벳에돔 집안에 딸린 사람은 예순두 명이다.",
    Chn:"这都是俄别·以东的子孙，他们和他们的儿子并弟兄，都是善于办事的壮士。俄别·以东的子孙共六十二人。",
    Eng:"The fifth, for the fifth month, was the commander Shamhuth the Izrahite. There were 24,000 men in his division.",
    Ind:"Mereka sekalian adalah dari keturunan Obed-Edom, yakni mereka sendiri, anak-anak mereka dan saudara-saudara mereka, masing-masing orang yang gagah perkasa, cakap untuk pekerjaan itu, enam puluh dua orang jumlahnya dari Obed-Edom."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:9, Page:1,
    Kor:"○므셀레먀의 아들과 형제들도 용맹스러운 사람들이며, 모두 열여덟 명이다.",
    Chn:"米施利米雅的儿子和弟兄都是壮士，共十八人。",
    Eng:"The sixth, for the sixth month, was Ira the son of Ikkesh the Tekoite. There were 24,000 men in his division.",
    Ind:"Dan Meselemya mempunyai delapan belas orang anak dan saudara, orang-orang yang gagah perkasa."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:10, Page:1,
    Kor:"○므라리의 자손인 호사의 아들 가운데서는 시므리가 족장이다. 시므리는 맏아들은 아니었으나, 그의 아버지가 그를 우두머리로 삼았다.",
    Chn:"米拉利子孙何萨有几个儿子：长子是申利，他原不是长子，是他父亲立他作长子。",
    Eng:"The seventh, for the seventh month, was Helez the Pelonite, an Ephraimite. There were",
    Ind:"Hosa dari bani Merari mempunyai anak-anak, yakni Simri, seorang kepala--sebab sekalipun ia bukan anak sulung, tetapi ayahnya mengangkat dia menjadi kepala--"
  },
  {Bible:"1Chronicles", Chapter:26, Verse:11, Page:1,
    Kor:"둘째는 힐기야이고, 셋째는 드발리야이고, 넷째는 스가랴이다. 호사의 아들과 형제는 모두 열세 명이다.",
    Chn:"次子是希勒家，三子是底巴利雅，四子是撒迦利亚。何萨的儿子并弟兄共十三人。",
    Eng:"The eighth, for the eighth month, was Sibbecai the Hushathite, a Zerahite. There were",
    Ind:"Hilkia, anak yang kedua, Tebalya, anak yang ketiga dan Zakharia, anak yang keempat. Semua anak dan saudara Hosa itu ada tiga belas orang."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:12, Page:1,
    Kor:"○이 문지기 갈래의 우두머리들과 형제들 모두에게 주님의 성전을 섬기는 임무를 맡겼다.",
    Chn:"这些人都是守门的班长，与他们的弟兄一同在耶和华殿里按班供职。",
    Eng:"The ninth, for the ninth month, was Abiezer the Anathothite, a Benjamite. There were 24,000 men in his division.",
    Ind:"Rombongan-rombongan para penunggu pintu itu, yang dibagi menurut kepala kaum, mempunyai tugas melayani di rumah TUHAN, sama seperti saudara-saudara sesuku mereka."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:13, Page:1,
    Kor:"그들은 큰 가문이나 작은 가문을 가리지 않고, 그들의 가문을 따라 제비를 뽑아, 각 문을 맡았다.",
    Chn:"他们无论大小，都按着宗族掣签分守各门。",
    Eng:"The tenth, for the tenth month, was Maharai the Netophathite, a Zerahite. There were 24,000 men in his division.",
    Ind:"Untuk setiap pintu gerbang mereka membuang undi, menurut puak-puak mereka, baik puak yang kecil maupun puak yang besar."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:14, Page:1,
    Kor:"셀레먀는 동쪽 문에 뽑혔고, 그의 아들 스가랴는 슬기로운 참모인데, 사람들이 제비를 뽑은 결과 북쪽 문에 뽑혔다.",
    Chn:"掣签守东门的是示利米雅；他的儿子撒迦利亚是精明的谋士，掣签守北门。",
    Eng:"The eleventh, for the eleventh month, was Benaiah the Pirathonite, an Ephraimite. There were 24,000 men in his division.",
    Ind:"Undian untuk pintu timur jatuh pada Selemya; selanjutnya mereka membuang undi bagi Zakharia, anaknya, seorang penasihat yang berakal budi, lalu jatuhlah undiannya untuk pintu utara."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:15, Page:1,
    Kor:"오벳에돔은 남쪽 문에 뽑히고, 그의 아들들은 곳간에 뽑혔다.",
    Chn:"俄别·以东守南门，他的儿子守库房。",
    Eng:"The twelfth, for the twelfth month, was Heldai the Netophathite, from the family of Othniel. There were 24,000 men in his division.",
    Ind:"Bagi Obed-Edom ialah pintu selatan dan bagi anak-anaknya gudang perlengkapan."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:16, Page:1,
    Kor:"숩빔과 호사는 서쪽 문과 올라가는 길 가에 있는 살래겟 문의 문지기로 뽑혀, 두 문을 다 지켰다.",
    Chn:"书聘与何萨守西门，在靠近沙利基门、通着往上去的街道上，班与班相对。",
    Eng:"The officers over the tribes of Israel: over the Reubenites: Eliezer son of Zicri; over the Simeonites: Shephatiah son of Maacah;",
    Ind:"Bagi Supim dan Hosa ialah pintu barat beserta Pintu Gerbang Syalekhet di jalan raya tanjakan. Penjaga yang satu ditaruh berdampingan dengan penjaga yang lain."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:17, Page:1,
    Kor:"이렇게 하여, 레위 사람이 동쪽 문에 여섯 사람, 북쪽 문에 매일 네 사람, 남쪽 문에 매일 네 사람, 곳간에는 각각 두 사람씩,",
    Chn:"每日东门有六个利未人，北门有四个，南门有四个，库房有两个，又有两个轮班替换。",
    Eng:"over Levi: Hashabiah son of Kemuel; over Aaron: Zadok;",
    Ind:"Di sebelah timur ada enam orang setiap hari, di sebelah utara ada empat orang setiap hari, di sebelah selatan ada empat orang setiap hari, tetapi pada gudang perlengkapan selalu ada dua orang;"
  },
  {Bible:"1Chronicles", Chapter:26, Verse:18, Page:1,
    Kor:"서쪽 문의 회랑에 네 사람, 길가의 회랑에 두 사람이 배치되었다.",
    Chn:"在西面街道上有四个，在游廊上有两个。",
    Eng:"over Judah: Elihu, a brother of David; over Issachar: Omri son of Michael;",
    Ind:"pada Parbar di sebelah barat: empat orang di jalan raya dan dua orang pada Parbar."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:19, Page:1,
    Kor:"이들은 고라 자손과 므라리 자손의 문지기 갈래이다.",
    Chn:"以上是可拉子孙和米拉利子孙守门的班次。",
    Eng:"over Zebulun: Ishmaiah son of Obadiah; over Naphtali: Jerimoth son of Azriel;",
    Ind:"Itulah rombongan-rombongan para penunggu pintu dari bani Korah dan dari bani Merari."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:20, Page:1,
    Kor:"<성전 관리인> ○레위 사람 가운데 다른 사람들은 하나님의 성전 곳간과 성물 곳간을 맡았다.",
    Chn:"利未子孙中有亚希雅掌管　神殿的府库和圣物的府库。",
    Eng:"over the Ephraimites: Hoshea son of Azaziah; over half the tribe of Manasseh: Joel son of Pedaiah;",
    Ind:"Orang-orang Lewi, saudara-saudara sesuku mereka, yang mengawasi perbendaharaan rumah Allah dan yang mengawasi perbendaharaan barang-barang kudus;"
  },
  {Bible:"1Chronicles", Chapter:26, Verse:21, Page:1,
    Kor:"게르손 자손인 라단 자손 곧 게르손 사람 라단 가문의 족장은 여히엘리이다.",
    Chn:"革顺族、拉但子孙里，作族长的是革顺族拉但的子孙耶希伊利。",
    Eng:"over the half-tribe of Manasseh in Gilead: Iddo son of Zechariah; over Benjamin: Jaasiel son of Abner;",
    Ind:"bani Ladan, yakni keturunan Gerson melalui Ladan, mempunyai orang-orang Yehiel sebagai kepala puak."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:22, Page:1,
    Kor:"여히엘리의 아들은 세담과 그 아우 요엘이며, 이들은 주님의 성전 곳간을 맡았다.",
    Chn:"耶希伊利的儿子西坦和他兄弟约珥掌管耶和华殿里的府库。",
    Eng:"over Dan: Azarel son of Jeroham. These were the officers over the tribes of Israel.",
    Ind:"Keturunan Yehiel, yakni Zetam dan Yoel, saudaranya, mengawasi perbendaharaan rumah TUHAN."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:23, Page:1,
    Kor:"○아므람과 이스할과 헤브론과 웃시엘의 자손에서는",
    Chn:"暗兰族、以斯哈族、希伯伦族、乌泄族也有职分。",
    Eng:"David did not take the number of the men twenty years old or less, because the LORD had promised to make Israel as numerous as the stars in the sky.",
    Ind:"Dari orang Amram, orang Yizhar, orang Hebron dan orang Uziel"
  },
  {Bible:"1Chronicles", Chapter:26, Verse:24, Page:1,
    Kor:"모세의 아들인 게르솜의 자손 스브엘이 곳간의 책임자이다.",
    Chn:"摩西的孙子、革舜的儿子细布业掌管府库。",
    Eng:"Joab son of Zeruiah began to count the men but did not finish. Wrath came on Israel on account of this numbering, and the number was not entered in the book of the annals of King David.",
    Ind:"adalah Sebuel bin Gersom bin Musa yang menjadi kepala perbendaharaan."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:25, Page:1,
    Kor:"그의 아우인 엘리에셀에게는 그의 아들 르하뱌와, 르하뱌의 아들 여사야와, 여사야의 아들 요람과, 요람의 아들 시그리와, 시그리의 아들 슬로못이 있다.",
    Chn:"还有他的弟兄以利以谢。以利以谢的儿子是利哈比雅；利哈比雅的儿子是耶筛亚；耶筛亚的儿子是约兰；约兰的儿子是细基利；细基利的儿子是示罗密。",
    Eng:"Azmaveth son of Adiel was in charge of the royal storehouses. Jonathan son of Uzziah was in charge of the storehouses in the outlying districts, in the towns, the villages and the watchtowers.",
    Ind:"Sanak saudara Sebuel melalui Eliezer ialah Rehabya, anak Eliezer, dan Yesaya, anak Rehabya, dan Yoram, anak Yesaya, dan Zikhri, anak Yoram, dan Selomit, anak Zikhri."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:26, Page:1,
    Kor:"이 슬로못이 그의 가족들과 함께 성물을 보관한 모든 곳간을 관리하였다. 이 성물은 다윗 왕과 족장들과 천부장과 백부장과 군대 지휘관들이 구별하여 바친 물건들이다.",
    Chn:"这示罗密和他的弟兄掌管府库的圣物，就是大卫王和众族长、千夫长、百夫长，并军长所分别为圣的物。",
    Eng:"Ezri son of Kelub was in charge of the field workers who farmed the land.",
    Ind:"Selomit ini beserta sanak saudaranya mengawasi perbendaharaan barang-barang kudus yang telah dikuduskan oleh raja Daud dan oleh para kepala puak dan para pemimpin pasukan seribu dan pasukan seratus dan para panglima."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:27, Page:1,
    Kor:"그들은 전쟁에서 빼앗은 물건들을 주님의 성전 건축과 수리를 위하여 구별하여 바쳤다.",
    Chn:"他们将争战时所夺的财物分别为圣，以备修造耶和华的殿。",
    Eng:"Shimei the Ramathite was in charge of the vineyards. Zabdi the Shiphmite was in charge of the produce of the vineyards for the wine vats.",
    Ind:"Mereka telah menguduskannya dari rampasan perang untuk menyemarakkan rumah TUHAN."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:28, Page:1,
    Kor:"선견자 사무엘, 기스의 아들 사울, 넬의 아들 아브넬, 스루야의 아들 요압이 구별하여 바친 모든 성물도 슬로못과 그의 가족들이 관리하였다.",
    Chn:"先见撒母耳、基士的儿子扫罗、尼珥的儿子押尼珥、洗鲁雅的儿子约押所分别为圣的物都归示罗密和他的弟兄掌管。",
    Eng:"Baal-Hanan the Gederite was in charge of the olive and sycamore-fig trees in the western foothills. Joash was in charge of the supplies of olive oil.",
    Ind:"Juga segala yang dikuduskan oleh Samuel, pelihat itu, oleh Saul bin Kish, oleh Abner bin Ner dan oleh Yoab, anak Zeruya, ya segala barang yang dikuduskan ada di bawah pengawasan Selomit beserta sanak saudaranya."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:29, Page:1,
    Kor:"<다른 레위 사람들의 직무> ○이스할 사람 그나냐와 그의 아들들은 서기관과 재판관으로서, 이스라엘의 일반 행정을 담당하였다.",
    Chn:"以斯哈族有基拿尼雅和他众子作官长和士师，管理以色列的外事。",
    Eng:"Shitrai the Sharonite was in charge of the herds grazing in Sharon. Shaphat son of Adlai was in charge of the herds in the valleys.",
    Ind:"Dari orang Yizhar adalah Kenanya beserta anak-anaknya yang diserahi tugas luar di Israel, yaitu menjadi pengatur dan hakim."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:30, Page:1,
    Kor:"○헤브론 사람 하사뱌와 그의 형제 가운데서 유능한 사람 천칠백 명이 요단 강 서쪽의 이스라엘을 관리하며, 주님의 모든 일과 왕을 섬기는 일을 담당하였다.",
    Chn:"希伯伦族有哈沙比雅和他弟兄一千七百人，都是壮士，在约旦河西、以色列地办理耶和华与王的事。",
    Eng:"Obil the Ishmaelite was in charge of the camels. Jehdeiah the Meronothite was in charge of the donkeys.",
    Ind:"Dari orang Hebron adalah Hasabya beserta sanak saudaranya, orang-orang gagah perkasa, seribu tujuh ratus orang jumlahnya, yang diserahi urusan pemerintahan Israel di sebelah barat sungai Yordan dalam segala urusan untuk TUHAN dan segala pekerjaan untuk raja."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:31, Page:1,
    Kor:"헤브론 사람의 족장은 여리야이다. 다윗이 통치한 지 사십 년이 되던 해에, 헤브론의 족보와 가문을 따라, 길르앗의 야스엘에서 사람들을 조사하여 용사를 찾아냈다.",
    Chn:"希伯伦族中有耶利雅作族长。大卫作王第四十年，在基列的雅谢，从这族中寻得大能的勇士。",
    Eng:"Jaziz the Hagrite was in charge of the flocks. All these were the officials in charge of King David's property.",
    Ind:"Dari orang Hebron adalah Yeria yang menjadi kepala. Tentang orang Hebron, mengenai keturunannya dan puaknya, dalam tahun keempat puluh zaman pemerintahan Daud diadakan penyelidikan tentang mereka dan ternyata, bahwa di antara mereka ada pahlawan-pahlawan yang gagah perkasa di Yaezer-Gilead."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:32, Page:1,
    Kor:"그의 친족 이천칠백 명은 용사들이며, 이들은 모두 족장이었다. 다윗 왕이 그들을 르우벤과 갓과 므낫세 반쪽 지파의 관리자로 세워, 하나님의 모든 일과 왕의 일을 담당하게 하였다.",
    Chn:"耶利雅的弟兄有二千七百人，都是壮士，且作族长；大卫王派他们在吕便支派、迦得支派、玛拿西半支派中办理　神和王的事。",
    Eng:"Jonathan, David's uncle, was a counselor, a man of insight and a scribe. Jehiel son of Hacmoni took care of the king's sons.",
    Ind:"Sanak saudara Yeria, orang-orang yang gagah perkasa, kepala-kepala puak ada dua ribu tujuh ratus orang. Mereka itu diangkat raja Daud mengawasi orang Ruben, orang Gad dan suku Manasye yang setengah itu dalam segala perkara untuk Allah dan segala perkara untuk raja."
  },
  {Bible:"1Chronicles", Chapter:26, Verse:33, Page:1,
    Kor:"",
    Chn:"",
    Eng:"Ahithophel was the king's counselor. Hushai the Arkite was the king's friend.",
    Ind:""
  },
  {Bible:"1Chronicles", Chapter:26, Verse:34, Page:1,
    Kor:"",
    Chn:"",
    Eng:"Ahithophel was succeeded by Jehoiada son of Benaiah and by Abiathar. Joab was the commander of the royal army.",
    Ind:""
  },
]);
