// 역대상 4장 · 1Chronicles 4
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",4,43);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:4, Verse:1, Page:1,
    Kor:"<유다의 자손> 유다의 아들은 베레스와 헤스론과 갈미와 훌과 소발이다.",
    Chn:"犹大的儿子是法勒斯、希斯 、迦米、户珥、朔巴。",
    Eng:"The descendants of Judah: Perez, Hezron, Carmi, Hur and Shobal.",
    Ind:"Anak-anak Yehuda ialah Peres, Hezron, Karmi, Hur dan Syobal."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:2, Page:1,
    Kor:"소발의 아들 르아야는 야핫을 낳고, 야핫은 아후매와 라핫을 낳았는데, 이들이 소라 족이다.",
    Chn:"朔巴的儿子利亚雅生雅哈；雅哈生亚户买和拉哈。这是琐拉人的诸族。",
    Eng:"Reaiah son of Shobal was the father of Jahath, and Jahath the father of Ahumai and Lahad. These were the clans of the Zorathites.",
    Ind:"Reaya, anak Syobal, memperanakkan Yahat, dan Yahat memperanakkan Ahumai dan Lahad. Itulah kaum-kaum orang Zora."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:3, Page:1,
    Kor:"○에담의 아들은 a이스르엘과 이스마와 잇바스이며, 그들의 누이는 하술렐보니이다.(a 칠십인역과 불가타를 따름. 히, '조상은')",
    Chn:"以坦之祖的儿子是耶斯列、伊施玛、伊得巴；他们的妹子名叫哈悉勒玻尼。",
    Eng:"These were the sons of Etam: Jezreel, Ishma and Idbash. Their sister was named Hazzelelponi.",
    Ind:"Inilah anak-anak Etam: Yizreel, Isma dan Idbas; nama saudara perempuan mereka ialah Hazelelponi;"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:4, Page:1,
    Kor:"그돌의 아버지 브누엘과 후사의 아버지 에셀은, 에브라다의 맏아들 훌의 아들인데, 훌은 베들레헴의 아버지이다.",
    Chn:"基多之祖是毗努伊勒。户沙之祖是以谢珥。这都是伯利恒之祖以法她的长子户珥所生的。",
    Eng:"Penuel was the father of Gedor, and Ezer the father of Hushah. These were the descendants of Hur, the firstborn of Ephrathah and father of Bethlehem.",
    Ind:"lalu Pnuel, bapa Gedor, dan Ezer, bapa Husa. Itulah keturunan Hur, anak sulung Efrata, bapa Betlehem."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:5, Page:1,
    Kor:"○드고아의 아버지 아스훌에게는 헬라와 나아라라는 두 아내가 있었다.",
    Chn:"提哥亚之祖亚施户有两个妻子：一名希拉，一名拿拉。",
    Eng:"Ashhur the father of Tekoa had two wives, Helah and Naarah.",
    Ind:"Asyur, bapa Tekoa, mempunyai dua isteri, yakni Hela dan Naara."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:6, Page:1,
    Kor:"아스훌과 나아라 사이에서는 아훗삼과 헤벨과 데므니와 하아하스다리가 태어났다. 이들이 나아라의 아들들이다.",
    Chn:"拿拉给亚施户生亚户撒、希弗、提米尼、哈辖斯他利。这都是拿拉的儿子。",
    Eng:"Naarah bore him Ahuzzam, Hepher, Temeni and Haahashtari. These were the descendants of Naarah.",
    Ind:"Naara melahirkan baginya Ahuzam, Hefer, Temeni dan orang Ahastari. Itulah anak-anak Naara."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:7, Page:1,
    Kor:"아스훌과 헬라 사이에서는 세렛과 이소할과 에드난, 세 아들이 태어났다.",
    Chn:"希拉的儿子是洗列、琐辖、伊提南。",
    Eng:"The sons of Helah: Zereth, Zohar, Ethnan,",
    Ind:"Anak-anak Hela ialah Zeret, Yezohar dan Etnan."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:8, Page:1,
    Kor:"○고스는 아눕과 소베바를 낳았으며, 하룸의 아들 아하헬 족을 낳았다.",
    Chn:"哥斯生亚诺、琐比巴，并哈 儿子亚哈黑的诸族。",
    Eng:"and Koz, who was the father of Anub and Hazzobebah and of the clans of Aharhel son of Harum.",
    Ind:"Kos memperanakkan Anub, Hazobeba dan kaum-kaum Aharhel bin Harum."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:9, Page:1,
    Kor:"○야베스는 그의 가족들 중에서 가장 존경을 받았는데, 그의 어머니는 고통을 겪으면서 낳은 아들이라고 하여 그의 이름을 b야베스라고 불렀다.(b '고통')",
    Chn:"雅比斯比他众弟兄更尊贵，他母亲给他起名叫雅比斯，意思说：我生他甚是痛苦。",
    Eng:"Jabez was more honorable than his brothers. His mother had named him Jabez, saying, \"I gave birth to him in pain.\"",
    Ind:"Yabes lebih dimuliakan dari pada saudara-saudaranya; nama Yabes itu diberi ibunya kepadanya sebab katanya: \"Aku telah melahirkan dia dengan kesakitan.\""
  },
  {Bible:"1Chronicles", Chapter:4, Verse:10, Page:1,
    Kor:"야베스가 이스라엘 하나님께 \"나에게 복에 복을 더해 주시고, 내 영토를 넓혀 주시고, 주님의 손으로 나를 도우시어 불행을 막아 주시고, 고통을 받지 않게 하여 주십시오\" 하고 간구하였더니, 하나님께서 그가 구한 것을 이루어 주셨다.",
    Chn:"雅比斯求告以色列的　神说：「甚愿你赐福与我，扩张我的境界，常与我同在，保佑我不遭患难，不受艰苦。」　神就应允他所求的。",
    Eng:"Jabez cried out to the God of Israel, \"Oh, that you would bless me and enlarge my territory! Let your hand be with me, and keep me from harm so that I will be free from pain.\" And God granted his request.",
    Ind:"Yabes berseru kepada Allah Israel, katanya: \"Kiranya Engkau memberkati aku berlimpah-limpah dan memperluas daerahku, dan kiranya tangan-Mu menyertai aku, dan melindungi aku dari pada malapetaka, sehingga kesakitan tidak menimpa aku!\" Dan Allah mengabulkan permintaannya itu."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:11, Page:1,
    Kor:"<다른 족보> ○수하의 형제 글룹이 므힐을 낳았는데, 그가 에스돈의 아버지이다.",
    Chn:"书哈的弟兄基绿生米黑，米黑是伊施屯之祖。",
    Eng:"Kelub, Shuhah's brother, was the father of Mehir, who was the father of Eshton.",
    Ind:"Kelub, saudara Suha, memperanakkan Mehir, dialah ayah Eston;"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:12, Page:1,
    Kor:"에스돈은 베드라바와 바세아와 이르나하스의 아버지 드힌나를 낳았는데, 이들이 레가 사람이다.",
    Chn:"伊施屯生伯拉巴、巴西亚，并珥拿辖之祖提欣拿，这都是利迦人。",
    Eng:"Eshton was the father of Beth Rapha, Paseah and Tehinnah the father of Ir Nahash. These were the men of Recah.",
    Ind:"dan Eston memperanakkan Bet-Rafa, Paseah dan Tehina, bapa Ir-Nahas. Itulah orang-orang Rekha."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:13, Page:1,
    Kor:"○그나스의 아들은 옷니엘과 스라야이며, 옷니엘의 아들은 하닷과 c므오노대이다.(c 칠십인역과 불가타를 따름)",
    Chn:"基纳斯的儿子是俄陀聂、西莱雅。俄陀聂的儿子是哈塔。",
    Eng:"The sons of Kenaz: Othniel and Seraiah. The sons of Othniel: Hathath and Meonothai.",
    Ind:"Anak-anak Kenas ialah Otniel dan Seraya; dan anak-anak Otniel ialah Hatat dan Meonotai;"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:14, Page:1,
    Kor:"므오노대는 오브라를 낳았다. ○스라야는 게하라심의 아버지 요압을 낳았는데, 그는 '기능공 마을'의 창시자이다. 그 곳에 사는 사람들이 모두 기능공이다.",
    Chn:"悯挪太生俄弗拉；西莱雅生革·夏纳欣人之祖约押。他们都是匠人。",
    Eng:"Meonothai was the father of Ophrah. Seraiah was the father of Joab, the father of Ge Harashim. It was called this because its people were craftsmen.",
    Ind:"dan Meonotai memperanakkan Ofra. Seraya memperanakkan Yoab, bapa Lembah Tukang-tukang, karena mereka adalah tukang-tukang."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:15, Page:1,
    Kor:"여분네의 아들인 갈렙이 낳은 아들은 이루와 엘라와 나암이고, 엘라의 아들은 그나스이다.",
    Chn:"耶孚尼的儿子是迦勒；迦勒的儿子是以路、以拉、拿安。以拉的儿子是基纳斯。",
    Eng:"The sons of Caleb son of Jephunneh: Iru, Elah and Naam. The son of Elah: Kenaz.",
    Ind:"Anak-anak Kaleb bin Yefune ialah Iru, Ela dan Naam; dan keturunan Ela ialah Kenas."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:16, Page:1,
    Kor:"○여할렐렐의 아들은 십과 시바와 디리아와 아사렐이다.",
    Chn:"耶哈利勒的儿子是西弗、西法、提利、亚撒列。",
    Eng:"The sons of Jehallelel: Ziph, Ziphah, Tiria and Asarel.",
    Ind:"Anak-anak Yehaleleel ialah Zif, Zifa, Tireya dan Asareel."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:17, Page:1,
    Kor:"○에스라의 아들은 예델과 메렛과 에벨과 얄론이다. 메렛의 한 아내가 미리암과 삼매와 에스드모아의 아버지 이스바를 낳았는데,",
    Chn:"以斯拉的儿子是益帖、米列、以弗、雅伦。米列娶法老女儿比提雅为妻，生米利暗、沙买，和以实提摩之祖益巴。米列又娶犹大女子为妻，生基多之祖雅列，梭哥之祖希伯，和撒挪亚之祖耶古铁。",
    Eng:"The sons of Ezrah: Jether, Mered, Epher and Jalon. One of Mered's wives gave birth to Miriam, Shammai and Ishbah the father of Eshtemoa.",
    Ind:"Anak-anak Ezra ialah Yeter, Mered, Efer dan Yalon. Itulah anak-anak Bica, puteri Firaun yang telah dikawini Mered. Perempuan ini melahirkan Miryam, Samai dan Yisbah, bapa Estemoa.",
    ChnVerseEnd:18
  },
  {Bible:"1Chronicles", Chapter:4, Verse:18, Page:1,
    Kor:"이들은 메렛과 결혼한 바로의 딸 비디아의 아들이다. 또 유다 지파인 그의 아내는 그돌의 아버지 예렛과 소고의 아버지 헤벨과 사노아의 아버지 여구디엘을 낳았다.",
    Chn:"",
    Eng:"(His Judean wife gave birth to Jered the father of Gedor, Heber the father of Soco, and Jekuthiel the father of Zanoah.) These were the children of Pharaoh's daughter Bithiah, whom Mered had married.",
    Ind:"Isteri Mered, perempuan Yehuda itu, melahirkan Yered, bapa Gedor, dan Heber, bapa Sokho, dan Yekutiel, bapa Zanoah."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:19, Page:1,
    Kor:"○나함의 누이인 호디야의 아들은 가미 족인 그일라의 아버지와, 마아가 족인 에스드모아이다.",
    Chn:"荷第雅的妻是拿含的妹子，她所生的儿子是迦米人基伊拉和玛迦人以实提摩之祖。",
    Eng:"The sons of Hodiah's wife, the sister of Naham: the father of Keilah the Garmite, and Eshtemoa the Maacathite.",
    Ind:"Anak-anak isteri Hodia, saudara perempuan Naham, ialah Abu Kehila, orang Garmi itu, dan Estemoa, orang Maakha itu."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:20, Page:1,
    Kor:"○시몬의 아들은 암논과 린나와 벤하난과 딜론이다. ○이시의 아들은 소헷과 벤소헷이다.",
    Chn:"示门的儿子是暗嫩、林拿、便·哈南、提伦。 以示的儿子是梭黑与便·梭黑。",
    Eng:"The sons of Shimon: Amnon, Rinnah, Ben-Hanan and Tilon. The descendants of Ishi: Zoheth and Ben-Zoheth.",
    Ind:"Anak-anak Simon ialah Amnon, Rina, Benhanan dan Tilon. Anak-anak Yisei ialah Zohet dan Ben-Zohet."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:21, Page:1,
    Kor:"<셀라의 자손> ○유다의 아들 셀라의 자손은 레가의 아버지 에르와, 마레사의 아버지 라아다와, 벳아스베야에서 고운 베를 짜는 가문과,",
    Chn:"犹大的儿子是示拉；示拉的儿子是利迦之祖珥，玛利沙之祖拉大，和属亚实比族织细麻布的各家。",
    Eng:"The sons of Shelah son of Judah: Er the father of Lecah, Laadah the father of Mareshah and the clans of the linen workers at Beth Ashbea,",
    Ind:"Keturunan Sela, anak Yehuda, ialah Er, bapa Lekha, dan Lada, bapa Maresa, dan kaum-kaum para pengusaha kain lenan halus di Bet-Asybea,"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:22, Page:1,
    Kor:"모압과 야수비네헴을 다스리던 요김과, 고세바 사람들과, 요아스와, 사랍인데, 이 사실들은 옛 기록에 있다.",
    Chn:"还有约敬、哥西巴人、约阿施、萨拉，就是在摩押地掌权的，又有雅叔比利恒。这都是古时所记载的。",
    Eng:"Jokim, the men of Cozeba, and Joash and Saraph, who ruled in Moab and Jashubi Lehem. (These records are from ancient times.)",
    Ind:"lalu Yokim dan orang-orang Kozeba, lagi Yoas dan Saraf yang menguasai Moab dan kemudian pulang ke Betlehem; --riwayat-riwayat ini tua."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:23, Page:1,
    Kor:"이들은 옹기 굽는 사람들로서, 왕을 섬기면서 느다임과 그데라에서 살았다.",
    Chn:"这些人都是窑匠，是尼他应和基低拉的居民；与王同处，为王做工。",
    Eng:"They were the potters who lived at Netaim and Gederah; they stayed there and worked for the king.",
    Ind:"Mereka ini adalah tukang-tukang periuk yang diam di Netaim dan Gedera; mereka diam di sana dan bekerja untuk raja."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:24, Page:1,
    Kor:"<시므온의 자손> ○시므온의 아들은 느무엘과 야민과 야립과 세라와 사울이다.",
    Chn:"西缅的儿子是尼母利、雅悯、雅立、谢拉、扫罗。",
    Eng:"The descendants of Simeon: Nemuel, Jamin, Jarib, Zerah and Shaul;",
    Ind:"Anak-anak Simeon ialah Nemuel, Yamin, Yarib, Zerah dan Saul;"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:25, Page:1,
    Kor:"사울의 아들은 살룸이고, 그 아들은 밉삼이고, 그 아들은 미스마이다.",
    Chn:"扫罗的儿子是沙龙；沙龙的儿子是米比衫；米比衫的儿子是米施玛；",
    Eng:"Shallum was Shaul's son, Mibsam his son and Mishma his son.",
    Ind:"anak orang ini ialah Salum; anak orang ini ialah Mibsam; anak orang ini ialah Misma."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:26, Page:1,
    Kor:"미스마의 아들은 함무엘이고, 그 아들은 삭굴이고, 그 아들은 시므이이다.",
    Chn:"米施玛的儿子是哈母利；哈母利的儿子是撒刻；撒刻的儿子是示每。",
    Eng:"The descendants of Mishma: Hammuel his son, Zaccur his son and Shimei his son.",
    Ind:"Keturunan Misma ialah Hamuel, anaknya; anak orang ini ialah Zakur; anak orang ini ialah Simei."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:27, Page:1,
    Kor:"시므이에게는 아들 열여섯과 딸 여섯이 있었으나, 그의 형제들에게는 아들이 많지 않았으므로, 그들의 온 일족은 유다 자손만큼 퍼지지 못하였다.",
    Chn:"示每有十六个儿子，六个女儿，他弟兄的儿女不多，他们各家不如犹大族的人丁增多。",
    Eng:"Shimei had sixteen sons and six daughters, but his brothers did not have many children; so their entire clan did not become as numerous as the people of Judah.",
    Ind:"Simei mempunyai enam belas orang anak laki-laki dan enam orang anak perempuan; tetapi saudara-saudaranya tidak mempunyai banyak anak; seluruh kaum mereka tidak bertambah banyak seperti bani Yehuda."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:28, Page:1,
    Kor:"○시므온 자손은 브엘세바와 몰라다와 하살수알과",
    Chn:"西缅人住在别是巴、摩拉大、哈萨·书亚、",
    Eng:"They lived in Beersheba, Moladah, Hazar Shual,",
    Ind:"Mereka diam di Bersyeba, Molada, Hazar-Sual,"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:29, Page:1,
    Kor:"빌하와 에셈과 돌랏과",
    Chn:"辟拉、以森、陀腊、",
    Eng:"Bilhah, Ezem, Tolad,",
    Ind:"Bilha, Ezem, Tolad,"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:30, Page:1,
    Kor:"브두엘과 호르마와 시글락과",
    Chn:"彼土利、何珥玛、洗革拉、",
    Eng:"Bethuel, Hormah, Ziklag,",
    Ind:"Betuel, Horma, Ziklag,"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:31, Page:1,
    Kor:"벳말가봇과 하살수심과 벳비리와 사아라임에 살았는데, 이 성읍들은 다윗 왕 때까지 그들에게 딸려 있었다.",
    Chn:"伯·玛嘉博、哈萨·苏撒、伯·比利、沙拉音，这些城邑直到大卫作王的时候都是属西缅人的。",
    Eng:"Beth Marcaboth, Hazar Susim, Beth Biri and Shaaraim. These were their towns until the reign of David.",
    Ind:"Bet-Markabot, Hazar-Susim, Bet-Biri dan di Saaraim. Itulah kota-kota mereka sampai Daud menjadi raja."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:32, Page:1,
    Kor:"여기에 마을들이 딸려 있었는데, 에담과 아인과 림몬과 도겐과 아산의 다섯 성읍과",
    Chn:"他们的五个城邑是以坦、亚因、临门、陀健、亚珊；",
    Eng:"Their surrounding villages were Etam, Ain, Rimmon, Token and Ashan--five towns--",
    Ind:"Dan desa-desanya ialah Etam, Ain, Rimon, Tokhen dan Asan, lima perkampungan;"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:33, Page:1,
    Kor:"d바알까지 이르는 여러 성읍의 주위에 마을들이 있었다. 이것이 그들의 거주지로서 모두 족보에 기록되었다.(d 칠십인역에는 '바알랏')",
    Chn:"还有属城的乡村，直到巴力。这是他们的住处，他们都有家谱。",
    Eng:"and all the villages around these towns as far as Baalath. These were their settlements. And they kept a genealogical record.",
    Ind:"juga segala desanya yang di sekitar perkampungan-perkampungan itu sampai ke Baal. Itulah tempat-tempat kediaman mereka dan mereka mempunyai silsilahnya sendiri."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:34, Page:1,
    Kor:"○또 메소밥과 야믈렉과 아마쟈의 아들 요사와",
    Chn:"还有米所巴、雅米勒、亚玛谢的儿子约沙、",
    Eng:"Meshobab, Jamlech, Joshah son of Amaziah,",
    Ind:"Dan Mesobab, Yamlekh, Yosa bin Amazia,"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:35, Page:1,
    Kor:"요엘과 예후가 있는데, 예후는 요시비야의 아들이요, 스라야의 손자요, 아시엘의 증손이다.",
    Chn:"约珥、约示比的儿子耶户；约示比是西莱雅的儿子；西莱雅是亚薛的儿子。",
    Eng:"Joel, Jehu son of Joshibiah, the son of Seraiah, the son of Asiel,",
    Ind:"Yoel, Yehu bin Yosibya bin Seraya bin Asiel,"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:36, Page:1,
    Kor:"그리고 엘료에내와 야아고바와 여소하야와 아사야와 아디엘과 여시미엘과 브나야와",
    Chn:"还有以利约乃、雅哥巴、约朔海、亚帅雅、亚底业、耶西篾、比拿雅、",
    Eng:"also Elioenai, Jaakobah, Jeshohaiah, Asaiah, Adiel, Jesimiel, Benaiah,",
    Ind:"Elyoenai, Yaakoba, Yesohaya, Asaya, Adiel, Yesimiel, Benaya,"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:37, Page:1,
    Kor:"시사가 있는데, 시사는 시비의 아들이요, 알론의 손자요, 여다야의 증손자요, 시므리의 현손이요, 스마야의 오대 손이다.",
    Chn:"示非的儿子细撒。示非是亚龙的儿子；亚龙是耶大雅的儿子；耶大雅是申利的儿子；申利是示玛雅的儿子。",
    Eng:"and Ziza son of Shiphi, the son of Allon, the son of Jedaiah, the son of Shimri, the son of Shemaiah.",
    Ind:"Ziza bin Sifei bin Alon bin Yedaya bin Simri bin Semaya--"
  },
  {Bible:"1Chronicles", Chapter:4, Verse:38, Page:1,
    Kor:"이 명단에 오른 사람은 그 일족의 지도자들이다. ○그들의 가문은 많이 불어나서 퍼졌으므로,",
    Chn:"以上所记的人名都是作族长的，他们宗族的人数增多。",
    Eng:"The men listed above by name were leaders of their clans. Their families increased greatly,",
    Ind:"orang-orang ini yang disebutkan dengan nama-namanya adalah pemimpin-pemimpin di antara kaum-kaum mereka. Keluarga-keluarga mereka makin bertambah banyak."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:39, Page:1,
    Kor:"그들은 그들의 양을 칠 목장을 찾아서 그돌 어귀에 있는 골짜기의 동쪽에까지 이르렀다.",
    Chn:"他们往平原东边基多口去，寻找牧放羊群的草场，",
    Eng:"and they went to the outskirts of Gedor to the east of the valley in search of pasture for their flocks.",
    Ind:"Oleh sebab itu mereka pindah ke arah Gedor sampai ke sebelah timur lembah untuk mencari padang rumput bagi kambing domba mereka."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:40, Page:1,
    Kor:"거기에서 기름진 좋은 목장을 발견하였는데, 이 땅은 사방이 넓고 조용하고 평화스러우며, 전에 함 족이 살던 곳이었다.",
    Chn:"寻得肥美的草场地，又宽阔又平静。从前住那里的是含族的人。",
    Eng:"They found rich, good pasture, and the land was spacious, peaceful and quiet. Some Hamites had lived there formerly.",
    Ind:"Mereka menemui padang rumput yang gemuk dan baik; negeri itu luas, aman dan sentosa; orang-orang yang diam di sana sebelum mereka berasal dari Ham."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:41, Page:1,
    Kor:"○이 명단에 기록된 사람들이 유다 왕 히스기야 시대에 이리로 와서, 함 족의 천막들과, 거기에 있는 므우님 족을 쳐부수어 그들을 e전멸시키고, 그들 대신 오늘까지 거기에 살고 있는데, 거기에 양을 칠 목장이 있기 때문이다.(e 완전히 파멸시켜 주님께 바쳐야 하는 물건이나 생명. 가지면 안되는 것, 손을 대었다가는 멸망을 받게끔 저주받은 것. 동사는 '전멸시키다' 또는 '전멸시켜 바치다')",
    Chn:"以上录名的人，在犹大王希西家年间，来攻击含族人的帐棚和那里所有的米乌尼人，将他们灭尽，就住在他们的地方，直到今日，因为那里有草场可以牧放羊群。",
    Eng:"The men whose names were listed came in the days of Hezekiah king of Judah. They attacked the Hamites in their dwellings and also the Meunites who were there and completely destroyed them, as is evident to this day. Then they settled in their place, because there was pasture for their flocks.",
    Ind:"Orang-orang yang namanya tertulis ini datang dalam zaman Hizkia, raja Yehuda, dan memusnahkan kemah-kemah orang Ham dan orang Meunim yang terdapat di sana dan menumpas mereka; demikianlah sampai hari ini. Kemudian mereka menduduki tempat orang-orang itu, sebab di sana ada padang rumput bagi kambing domba mereka."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:42, Page:1,
    Kor:"시므온 자손 가운데서 오백 명이 이시의 아들인 블라댜와 느아랴와 르바야와 웃시엘을 두령으로 삼고 세일 산으로 가서,",
    Chn:"这西缅人中，有五百人上西珥山，率领他们的是以示的儿子毗拉提、尼利雅、利法雅，和乌薛，",
    Eng:"And five hundred of these Simeonites, led by Pelatiah, Neariah, Rephaiah and Uzziel, the sons of Ishi, invaded the hill country of Seir.",
    Ind:"Dan sebagian dari mereka, dari bani Simeon, sebanyak lima ratus orang, pindah ke pegunungan Seir. Sebagai kepala mereka ialah Pelaca, Nearya, Refaya dan Uziel, anak-anak Yisei."
  },
  {Bible:"1Chronicles", Chapter:4, Verse:43, Page:1,
    Kor:"피하여 살아 남은 아말렉 사람을 쳐부수고, 오늘까지 거기에서 살고 있다.",
    Chn:"杀了逃脱剩下的亚玛力人，就住在那里直到今日。",
    Eng:"They killed the remaining Amalekites who had escaped, and they have lived there to this day.",
    Ind:"Mereka membinasakan sisa orang Amalek yang telah meluputkan diri. Lalu mereka diam di sana sampai hari ini."
  },
]);
