// 역대상 9장 · 1Chronicles 9
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",9,44);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:9, Verse:1, Page:1, Kor:"", Chn:"", Eng:"All Israel was listed in the genealogies recorded in the book of the kings of Israel. The people of Judah were taken captive to Babylon because of their unfaithfulness.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:2, Page:1, Kor:"", Chn:"", Eng:"Now the first to resettle on their own property in their own towns were some Israelites, priests, Levites and temple servants.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:3, Page:1, Kor:"", Chn:"", Eng:"Those from Judah, from Benjamin, and from Ephraim and Manasseh who lived in Jerusalem were:", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Uthai son of Ammihud, the son of Omri, the son of Imri, the son of Bani, a descendant of Perez son of Judah.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Of the Shilonites: Asaiah the firstborn and his sons.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:6, Page:1, Kor:"", Chn:"", Eng:"Of the Zerahites: Jeuel. The people from Judah numbered 690.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Of the Benjamites: Sallu son of Meshullam, the son of Hodaviah, the son of Hassenuah;", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Ibneiah son of Jeroham; Elah son of Uzzi, the son of Micri; and Meshullam son of Shephatiah, the son of Reuel, the son of Ibnijah.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:9, Page:1, Kor:"", Chn:"", Eng:"The people from Benjamin, as listed in their genealogy, numbered 956. All these men were heads of their families.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Of the priests: Jedaiah; Jehoiarib; Jakin;", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Azariah son of Hilkiah, the son of Meshullam, the son of Zadok, the son of Meraioth, the son of Ahitub, the official in charge of the house of God;", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:12, Page:1, Kor:"", Chn:"", Eng:"Adaiah son of Jeroham, the son of Pashhur, the son of Malkijah; and Maasai son of Adiel, the son of Jahzerah, the son of Meshullam, the son of Meshillemith, the son of Immer.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:13, Page:1, Kor:"", Chn:"", Eng:"The priests, who were heads of families, numbered 1,760. They were able men, responsible for ministering in the house of God.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Of the Levites: Shemaiah son of Hasshub, the son of Azrikam, the son of Hashabiah, a Merarite;", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:15, Page:1, Kor:"", Chn:"", Eng:"Bakbakkar, Heresh, Galal and Mattaniah son of Mica, the son of Zicri, the son of Asaph;", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:16, Page:1, Kor:"", Chn:"", Eng:"Obadiah son of Shemaiah, the son of Galal, the son of Jeduthun; and Berekiah son of Asa, the son of Elkanah, who lived in the villages of the Netophathites.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:17, Page:1, Kor:"", Chn:"", Eng:"The gatekeepers: Shallum, Akkub, Talmon, Ahiman and their brothers, Shallum their chief", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:18, Page:1, Kor:"", Chn:"", Eng:"being stationed at the King's Gate on the east, up to the present time. These were the gatekeepers belonging to the camp of the Levites.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Shallum son of Kore, the son of Ebiasaph, the son of Korah, and his fellow gatekeepers from his family (the Korahites) were responsible for guarding the thresholds of the Tent just as their fathers had been responsible for guarding the entrance to the dwelling of the LORD.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:20, Page:1, Kor:"", Chn:"", Eng:"In earlier times Phinehas son of Eleazar was in charge of the gatekeepers, and the LORD was with him.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:21, Page:1, Kor:"", Chn:"", Eng:"Zechariah son of Meshelemiah was the gatekeeper at the entrance to the Tent of Meeting.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:22, Page:1, Kor:"", Chn:"", Eng:"Altogether, those chosen to be gatekeepers at the thresholds numbered 212. They were registered by genealogy in their villages. The gatekeepers had been assigned to their positions of trust by David and Samuel the seer.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:23, Page:1, Kor:"", Chn:"", Eng:"They and their descendants were in charge of guarding the gates of the house of the LORD--the house called the Tent.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:24, Page:1, Kor:"", Chn:"", Eng:"The gatekeepers were on the four sides: east, west, north and south.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Their brothers in their villages had to come from time to time and share their duties for seven-day periods.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:26, Page:1, Kor:"", Chn:"", Eng:"But the four principal gatekeepers, who were Levites, were entrusted with the responsibility for the rooms and treasuries in the house of God.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:27, Page:1, Kor:"", Chn:"", Eng:"They would spend the night stationed around the house of God, because they had to guard it; and they had charge of the key for opening it each morning.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Some of them were in charge of the articles used in the temple service; they counted them when they were brought in and when they were taken out.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Others were assigned to take care of the furnishings and all the other articles of the sanctuary, as well as the flour and wine, and the oil, incense and spices.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:30, Page:1, Kor:"", Chn:"", Eng:"But some of the priests took care of mixing the spices.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:31, Page:1, Kor:"", Chn:"", Eng:"A Levite named Mattithiah, the firstborn son of Shallum the Korahite, was entrusted with the responsibility for baking the offering bread.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:32, Page:1, Kor:"", Chn:"", Eng:"Some of their Kohathite brothers were in charge of preparing for every Sabbath the bread set out on the table.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:33, Page:1, Kor:"", Chn:"", Eng:"Those who were musicians, heads of Levite families, stayed in the rooms of the temple and were exempt from other duties because they were responsible for the work day and night.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:34, Page:1, Kor:"", Chn:"", Eng:"All these were heads of Levite families, chiefs as listed in their genealogy, and they lived in Jerusalem.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:35, Page:1, Kor:"", Chn:"", Eng:"Jeiel the father of Gibeon lived in Gibeon. His wife's name was Maacah,", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:36, Page:1, Kor:"", Chn:"", Eng:"and his firstborn son was Abdon, followed by Zur, Kish, Baal, Ner, Nadab,", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:37, Page:1, Kor:"", Chn:"", Eng:"Gedor, Ahio, Zechariah and Mikloth.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:38, Page:1, Kor:"", Chn:"", Eng:"Mikloth was the father of Shimeam. They too lived near their relatives in Jerusalem.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:39, Page:1, Kor:"", Chn:"", Eng:"Ner was the father of Kish, Kish the father of Saul, and Saul the father of Jonathan, Malki-Shua, Abinadab and Esh-Baal.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:40, Page:1, Kor:"", Chn:"", Eng:"The son of Jonathan: Merib-Baal, who was the father of Micah.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:41, Page:1, Kor:"", Chn:"", Eng:"The sons of Micah: Pithon, Melech, Tahrea and Ahaz.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:42, Page:1, Kor:"", Chn:"", Eng:"Ahaz was the father of Jadah, Jadah was the father of Alemeth, Azmaveth and Zimri, and Zimri was the father of Moza.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:43, Page:1, Kor:"", Chn:"", Eng:"Moza was the father of Binea; Rephaiah was his son, Eleasah his son and Azel his son.", Ind:""},
  {Bible:"1Chronicles", Chapter:9, Verse:44, Page:1, Kor:"", Chn:"", Eng:"Azel had six sons, and these were their names: Azrikam, Bokeru, Ishmael, Sheariah, Obadiah and Hanan. These were the sons of Azel.", Ind:""},
]);
