// 역대상 13장 · 1Chronicles 13
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",13,14);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:13, Verse:1, Page:1, Kor:"<언약궤를 옮기다(삼하 6:1-11)> 다윗이 천부장과 백부장과 그 밖의 모든 지도자와 의논하고,", Chn:"", Eng:"David conferred with each of his officers, the commanders of thousands and commanders of hundreds.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:2, Page:1, Kor:"이스라엘 온 회중에게 말하였다. \"여러분이 좋게 여기고 우리 주 하나님께서 기뻐하신다면, 우리가 이스라엘 온 땅에 남아 있는 우리 백성과 또 그들의 목초지에 있는 성읍들에서 그들과 함께 살고 있는 제사장과 레위 사람에게 전갈을 보내어, 그들을 우리에게로 모이게 합시다.", Chn:"", Eng:"He then said to the whole assembly of Israel, \"If it seems good to you and if it is the will of the LORD our God, let us send word far and wide to the rest of our brothers throughout the territories of Israel, and also to the priests and Levites who are with them in their towns and pasturelands, to come and join us.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:3, Page:1, Kor:"그런 다음에, 우리 모두 하나님의 궤를 우리에게로 옮겨 오도록 합시다. 사울 시대에는 우리가 궤 앞에서 하나님의 뜻을 여쭈어 볼 수가 없지 않았습니까!\"", Chn:"", Eng:"Let us bring the ark of our God back to us, for we did not inquire of it during the reign of Saul.\"", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:4, Page:1, Kor:"온 백성이 이 일을 옳게 여겼으므로 온 회중이 그렇게 하겠다고 대답하였다.", Chn:"", Eng:"The whole assembly agreed to do this, because it seemed right to all the people.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:5, Page:1, Kor:"○그래서 다윗은 하나님의 궤를 기럇여아림에서 옮겨 오려고, 이집트의 시홀에서부터 하맛 어귀에 이르기까지 온 이스라엘을 불러모았다.", Chn:"", Eng:"So David assembled all the Israelites, from the Shihor River in Egypt to Lebo Hamath, to bring the ark of God from Kiriath Jearim.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:6, Page:1, Kor:"다윗과 온 이스라엘이 하나님의 궤를 옮겨 오려고, 바알라 곧 유다의 기럇여아림으로 올라갔다. 그 궤는, 그룹들 위에 앉아 계신 주님의 이름으로 불리는 궤이다.", Chn:"", Eng:"David and all the Israelites with him went to Baalah of Judah (Kiriath Jearim) to bring up from there the ark of God the LORD, who is enthroned between the cherubim--the ark that is called by the Name.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:7, Page:1, Kor:"그들이 아비나답의 집에서 하나님의 궤를 꺼내서 새 수레에 싣고 나올 때에, 웃사와 아히요가 그 수레를 몰았다.", Chn:"", Eng:"They moved the ark of God from Abinadab's house on a new cart, with Uzzah and Ahio guiding it.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:8, Page:1, Kor:"다윗과 온 이스라엘은 있는 힘을 다하여 노래하며, 수금과 거문고를 타며, 소구와 심벌즈를 치며, 나팔을 불면서, 하나님 앞에서 기뻐하였다.", Chn:"", Eng:"David and all the Israelites were celebrating with all their might before God, with songs and with harps, lyres, tambourines, cymbals and trumpets.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:9, Page:1, Kor:"○그들이 기돈의 타작 마당에 이르렀을 때에, 소들이 뛰어서 궤가 떨어지려고 하였으므로, 웃사가 그 손을 내밀어 궤를 붙들었다.", Chn:"", Eng:"When they came to the threshing floor of Kidon, Uzzah reached out his hand to steady the ark, because the oxen stumbled.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:10, Page:1, Kor:"웃사가 궤를 붙들었으므로, 주님께서 웃사에게 진노하셔서 그를 치시니, 그가 거기 하나님 앞에서 죽었다.", Chn:"", Eng:"The LORD'S anger burned against Uzzah, and he struck him down because he had put his hand on the ark. So he died there before God.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:11, Page:1, Kor:"주님께서 그토록 급격하게 웃사를 벌하셨으므로, 다윗이 화를 냈다. 그래서 그 곳 이름을 오늘날까지 a베레스 웃사라고 한다.(a '웃사를 침')", Chn:"", Eng:"Then David was angry because the LORD'S wrath had broken out against Uzzah, and to this day that place is called Perez Uzzah.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:12, Page:1, Kor:"○그 날 다윗은 이 일 때문에 하나님이 무서워서 \"이래서야 내가 어떻게 하나님의 궤를 내가 있는 곳으로 옮길 수 있겠는가?\" 하였다.", Chn:"", Eng:"David was afraid of God that day and asked, \"How can I ever bring the ark of God to me?\"", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:13, Page:1, Kor:"그래서 다윗은 그 궤를 자기가 있는 '다윗 성'으로 옮기지 않고, 가드 사람 오벳에돔의 집으로 실어 가게 하였다.", Chn:"", Eng:"He did not take the ark to be with him in the City of David. Instead, he took it aside to the house of Obed-Edom the Gittite.", Ind:""},
  {Bible:"1Chronicles", Chapter:13, Verse:14, Page:1, Kor:"그래서 하나님의 궤가 오벳에돔의 집에서 그의 가족과 함께 석 달 동안 머물렀는데, 그 때에 주님께서 오벳에돔의 가족과 그에게 딸린 모든 것 위에 복을 내려 주셨다.", Chn:"", Eng:"The ark of God remained with the family of Obed-Edom in his house for three months, and the LORD blessed his household and everything he had.", Ind:""},
]);
