// 역대상 7장 · 1Chronicles 7
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",7,40);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:7, Verse:1, Page:1,
    Kor:"<잇사갈의 자손> 잇사갈의 아들은 돌라와 부아와 야숩과 시므론, 이렇게 넷이다.",
    Chn:"以萨迦的儿子是陀拉、普瓦、雅述、伸 ，共四人。",
    Eng:"The sons of Issachar: Tola, Puah, Jashub and Shimron--four in all.",
    Ind:"Anak-anak Isakhar ialah Tola dan Pua, Yasub dan Simron, empat orang."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:2, Page:1,
    Kor:"돌라의 아들은 웃시와 르바야와 여리엘과 야매와 입삼과 스므엘인데, 이들은 돌라 가문의 족장들이다. 다윗 시대에 족보에 오른 용감한 군인들의 수는 이만 이천육백 명이다.",
    Chn:"陀拉的儿子是乌西、利法雅、耶勒、雅买、易伯散、示母利，都是陀拉的族长，是大能的勇士。到大卫年间，他们的人数共有二万二千六百名。",
    Eng:"The sons of Tola: Uzzi, Rephaiah, Jeriel, Jahmai, Ibsam and Samuel--heads of their families. During the reign of David, the descendants of Tola listed as fighting men in their genealogy numbered 22,600.",
    Ind:"Anak-anak Tola ialah Uzi, Refaya, Yeriel, Yahmai, Yibsam dan Samuel, kepala-kepala puak turunan Tola, pahlawan-pahlawan yang gagah perkasa; menurut daftar keturunan mereka jumlahnya di zaman Daud ada dua puluh dua ribu enam ratus orang."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:3, Page:1,
    Kor:"○웃시의 아들은 이스라히야이며, 이스라히야의 아들은 미가엘과 오바댜와 요엘과 잇시야, 이렇게 다섯인데, 이들은 모두 족장이다.",
    Chn:"乌西的儿子是伊斯拉希；伊斯拉希的儿子是米迦勒、俄巴底亚、约珥、伊示雅，共五人，都是族长。",
    Eng:"The son of Uzzi: Izrahiah. The sons of Izrahiah: Michael, Obadiah, Joel and Isshiah. All five of them were chiefs.",
    Ind:"Keturunan Uzi ialah Yizrahya dan anak-anak Yizrahya ialah Mikhael, Obaja, Yoel dan Yisia, lima orang, semuanya mereka adalah kepala-kepala."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:4, Page:1,
    Kor:"이들의 각 가문에 따라 족보에 오른 전쟁 용사는 삼만 육천 명이나 되었는데, 그들에게 아내와 자식이 많았기 때문이다.",
    Chn:"他们所率领的，按着宗族出战的军队，共有三万六千人，因为他们的妻和子众多。",
    Eng:"According to their family genealogy, they had 36,000 men ready for battle, for they had many wives and children.",
    Ind:"Di bawah mereka itu, menurut daftar keturunan dan menurut puak mereka, ada pasukan-pasukan tentara tiga puluh enam ribu orang, sebab isteri dan anak-anak mereka banyak."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:5, Page:1,
    Kor:"○잇사갈의 모든 종족에 속한 그들의 형제는 용감한 군인들이며, 팔만 칠천 명 모두가 족보에 올랐다.",
    Chn:"他们的族弟兄在以萨迦各族中都是大能的勇士，按着家谱计算共有八万七千人。",
    Eng:"The relatives who were fighting men belonging to all the clans of Issachar, as listed in their genealogy, were 87,000 in all.",
    Ind:"Saudara-saudara sesuku mereka dari segala kaum Isakhar, pahlawan-pahlawan yang gagah perkasa, semuanya ada delapan puluh tujuh ribu orang yang terdaftar dalam silsilah."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:6, Page:1,
    Kor:"<베냐민과 단의 자손> ○베냐민의 아들은 벨라와 베겔과 여디아엘, 이렇게 셋이다.",
    Chn:"便雅悯的儿子是比拉、比结、耶叠，共三人。",
    Eng:"Three sons of Benjamin: Bela, Beker and Jediael.",
    Ind:"Anak-anak Benyamin ialah Bela, Bekher dan Yediael, tiga orang."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:7, Page:1,
    Kor:"벨라의 아들은 에스본과 우시와 웃시엘과 여리못과 이리, 이렇게 다섯인데, 이들은 모두 다 각 가문의 족장들이다. 그들의 족보에 오른 용감한 군인들은 이만 이천삼십사 명이다.",
    Chn:"比拉的儿子是以斯本、乌西、乌薛、耶利摩、以利，共五人，都是族长，是大能的勇士。按着家谱计算，他们的子孙共有二万二千零三十四人。",
    Eng:"The sons of Bela: Ezbon, Uzzi, Uzziel, Jerimoth and Iri, heads of families--five in all. Their genealogical record listed 22,034 fighting men.",
    Ind:"Anak-anak Bela ialah Ezbon, Uzi, Uziel, Yerimot dan Iri, lima orang, kepala-kepala puak, pahlawan-pahlawan yang gagah perkasa; mereka yang terdaftar dalam silsilah ada dua puluh dua ribu tiga puluh empat orang."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:8, Page:1,
    Kor:"○베겔의 아들은 스미라와 요아스와 엘리에셀과 엘료에내와 오므리와 여레못과 아비야와 아나돗과 알레멧이다. 이들은 모두 베겔의 아들이다.",
    Chn:"比结的儿子是细米拉、约阿施、以利以谢、以利约乃、暗利、耶利摩、亚比雅、亚拿突、亚拉篾。这都是比结的儿子。",
    Eng:"The sons of Beker: Zemirah, Joash, Eliezer, Elioenai, Omri, Jeremoth, Abijah, Anathoth and Alemeth. All these were the sons of Beker.",
    Ind:"Anak-anak Bekher ialah Zemira, Yoas, Eliezer, Elyoenai, Omri, Yeremot, Abia, Anatot dan Alemet; sekaliannya itu ialah anak-anak Bekher."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:9, Page:1,
    Kor:"그들의 족보에 각 가문의 족장들로 기록된 용감한 군인들은 이만 이백 명이다.",
    Chn:"他们都是族长，是大能的勇士。按着家谱计算，他们的子孙共有二万零二百人。",
    Eng:"Their genealogical record listed the heads of families and 20,200 fighting men.",
    Ind:"Mereka yang terdaftar dalam silsilah, menurut keturunan mereka, sebagai kepala-kepala puak mereka, pahlawan-pahlawan yang gagah perkasa, ada dua puluh ribu dua ratus orang."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:10, Page:1,
    Kor:"○여디아엘의 아들은 빌한이고, 빌한의 아들은 여우스와 베냐민과 에훗과 그나아나와 세단과 다시스와 아히사할이다.",
    Chn:"耶叠的儿子是比勒罕；比勒罕的儿子是耶乌施、便雅悯、以忽、基拿拿、细坦、他施、亚希沙哈。",
    Eng:"The son of Jediael: Bilhan. The sons of Bilhan: Jeush, Benjamin, Ehud, Kenaanah, Zethan, Tarshish and Ahishahar.",
    Ind:"Keturunan Yediael ialah Bilhan dan anak-anak Bilhan ialah Yeush, Benyamin, Ehud, Kenaana, Zetan, Tarsis dan Ahisahar."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:11, Page:1,
    Kor:"이들은 모두 여디아엘의 아들이요 각 가문의 족장들이며, 싸움에 나갈 만한 용감한 군인들은 만 칠천이백 명이다.",
    Chn:"这都是耶叠的儿子，都是族长，是大能的勇士；他们的子孙能上阵打仗的，共有一万七千二百人。",
    Eng:"All these sons of Jediael were heads of families. There were 17,200 fighting men ready to go out to war.",
    Ind:"Sekaliannya itu ialah keturunan Yediael, kepala-kepala puak mereka, pahlawan-pahlawan yang gagah perkasa; orang-orang yang sanggup berperang ada tujuh belas ribu dua ratus."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:12, Page:1,
    Kor:"이르의 자손은 숩빔과 훕빔이고, 아헬의 아들은 후심이다.",
    Chn:"还有以珥的儿子书品、户品，并亚黑的儿子户伸。",
    Eng:"The Shuppites and Huppites were the descendants of Ir, and the Hushites the descendants of Aher.",
    Ind:"Dan Supim dan Hupim ialah keturunan Ir; Husim ialah keturunan Aher."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:13, Page:1,
    Kor:"<납달리의 자손> ○납달리의 아들은 a야스엘과 구니와 예셀과 살룸인데, 이들은 빌하의 손자이다.(a 히, '야시엘')",
    Chn:"拿弗他利的儿子是雅薛、沽尼、耶色、沙龙。这都是辟拉的子孙。",
    Eng:"The sons of Naphtali: Jahziel, Guni, Jezer and Shillem--the descendants of Bilhah.",
    Ind:"Anak-anak Naftali ialah Yahziel, Guni, Yezer dan Salum, anak-anaknya dari Bilha."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:14, Page:1,
    Kor:"<므낫세의 자손> ○므낫세의 아들은 그의 첩 아람 여자가 낳은 아스리엘이다. 길르앗의 아버지 마길도 이 여자가 낳았다.",
    Chn:"玛拿西的儿子亚斯列是他妾亚兰人所生的，又生了基列之父玛吉。",
    Eng:"The descendants of Manasseh: Asriel was his descendant through his Aramean concubine. She gave birth to Makir the father of Gilead.",
    Ind:"Keturunan Manasye ialah Asriel yang dilahirkan oleh gundiknya, perempuan Aram itu; perempuan ini melahirkan Makhir, bapa Gilead."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:15, Page:1,
    Kor:"마길은 훕빔과 숩빔에게 아내를 얻어 주었는데, 그 누이의 이름은 마아가이다. 므낫세의 둘째 아들의 이름은 슬로브핫인데, 슬로브핫은 딸만 낳았다.",
    Chn:"玛吉娶的妻是户品、书品的妹子，名叫玛迦。玛拿西的次子名叫西罗非哈；西罗非哈但有几个女儿。",
    Eng:"Makir took a wife from among the Huppites and Shuppites. His sister's name was Maacah. Another descendant was named Zelophehad, who had only daughters.",
    Ind:"Makhir mengambil seorang isteri bagi Hupim dan Supim; nama saudaranya perempuan ialah Maakha. Nama anak yang kedua ialah Zelafead. Zelafead hanya mempunyai anak-anak perempuan."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:16, Page:1,
    Kor:"○마길의 아내 마아가는 아들을 낳아, 그 이름을 베레스라고 불렀다. 그 아우의 이름은 세레스이며, 그 아들은 울람과 라겜이다.",
    Chn:"玛吉的妻玛迦生了一个儿子，起名叫毗利施。毗利施的兄弟名叫示利施；示利施的儿子是乌兰和利金。",
    Eng:"Makir's wife Maacah gave birth to a son and named him Peresh. His brother was named Sheresh, and his sons were Ulam and Rakem.",
    Ind:"Tetapi Maakha, isteri Makhir, melahirkan seorang anak laki-laki dan menamainya Peresh; nama saudaranya laki-laki ialah Seres dan anak-anak orang ini ialah Ulam dan Rekem."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:17, Page:1,
    Kor:"울람의 아들은 브단이다. 이들이 므낫세의 손자요, 마길의 아들인 길르앗의 자손이다.",
    Chn:"乌兰的儿子是比但。这都是基列的子孙。基列是玛吉的儿子，玛吉是玛拿西的儿子。",
    Eng:"The son of Ulam: Bedan. These were the sons of Gilead son of Makir, the son of Manasseh.",
    Ind:"Keturunan Ulam ialah Bedan. Itulah keturunan Gilead bin Makhir bin Manasye."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:18, Page:1,
    Kor:"그의 누이 함몰레겟은 이스홋과 아비에셀과 말라를 낳았다.",
    Chn:"基列的妹子哈摩利吉生了伊施荷、亚比以谢、玛拉。（",
    Eng:"His sister Hammoleketh gave birth to Ishhod, Abiezer and Mahlah.",
    Ind:"Saudaranya perempuan, Molekhet, melahirkan Isyhod, Abiezer dan Mahla."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:19, Page:1,
    Kor:"(스미다의 아들은 아히안과 세겜과 릭히와 아니암이다.)",
    Chn:"示米大的儿子是亚现、示剑、利克希、阿尼安。）",
    Eng:"The sons of Shemida were: Ahian, Shechem, Likhi and Aniam.",
    Ind:"Anak-anak Semida ialah Ahyan, Sekhem, Likhi dan Aniam."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:20, Page:1,
    Kor:"<에브라임의 자손> ○에브라임의 아들은 수델라이고, 그 아들은 베렛이고, 그 아들은 다핫이고, 그 아들은 엘르아다이고, 그 아들은 다핫이고,",
    Chn:"以法莲的儿子是书提拉；书提拉的儿子是比列；比列的儿子是他哈；他哈的儿子是以拉大；以拉大的儿子是他哈；",
    Eng:"The descendants of Ephraim: Shuthelah, Bered his son, Tahath his son, Eleadah his son, Tahath his son,",
    Ind:"Keturunan Efraim ialah Sutelah, dan anak orang ini ialah Bered, dan anak orang ini ialah Tahat, dan anak orang ini ialah Elada, dan anak orang ini ialah Tahat,"
  },
  {Bible:"1Chronicles", Chapter:7, Verse:21, Page:1,
    Kor:"그 아들은 사밧이고, 그 아들은 수델라이고, 또 에셀과 엘르앗이 있다. 그 땅의 토박이인 가드 사람이 그들을 죽였는데, 그들이 가드 사람의 짐승을 빼앗으려고 내려갔기 때문이다.",
    Chn:"他哈的儿子是撒拔；撒拔的儿子是书提拉。以法莲又生以谢、以列；这二人因为下去夺取迦特人的牲畜，被本地的迦特人杀了。",
    Eng:"Zabad his son and Shuthelah his son. Ezer and Elead were killed by the native-born men of Gath, when they went down to seize their livestock.",
    Ind:"dan anak orang ini ialah Zabad, dan anak orang ini ialah Sutelah, kemudian Ezer dan Elad. Mereka dibunuh oleh orang-orang Gat yang lahir di negeri itu, sebab mereka pergi merampas ternak orang-orang itu."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:22, Page:1,
    Kor:"그들의 아버지 에브라임이 여러 날 동안 슬퍼하였으므로, 그 친척들이 찾아와서 그를 위로하였다.",
    Chn:"他们的父亲以法莲为他们悲哀了多日，他的弟兄都来安慰他。",
    Eng:"Their father Ephraim mourned for them many days, and his relatives came to comfort him.",
    Ind:"Efraim, ayah mereka, berkabung berhari-hari lamanya, sehingga saudara-saudaranya datang untuk menghiburkan dia."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:23, Page:1,
    Kor:"그 뒤에 에브라임이 아내와 동침하였고, 그 아내가 임신하여 아들을 낳았다. 에브라임은 자기 집에 불행한 일이 있었기 때문에, 아들의 이름을 브리아라고 불렀다.",
    Chn:"以法莲与妻同房，他妻就怀孕生了一子，以法莲因为家里遭祸，就给这儿子起名叫比利亚。",
    Eng:"Then he lay with his wife again, and she became pregnant and gave birth to a son. He named him Beriah, because there had been misfortune in his family.",
    Ind:"Sesudah itu ia bersetubuh dengan isterinya, lalu mengandunglah perempuan itu dan melahirkan seorang anak laki-laki. Ia menamainya Beria, sebab malapetaka telah menimpa keluarganya."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:24, Page:1,
    Kor:"○에브라임의 딸은 세에라인데, 그는 아래 위 벳호론과 우센세에라 성읍을 세웠다.",
    Chn:"他的女儿名叫舍伊拉，就是建筑上伯·和 、下伯·和 与乌羡·舍伊拉的。",
    Eng:"His daughter was Sheerah, who built Lower and Upper Beth Horon as well as Uzzen Sheerah.",
    Ind:"Anaknya perempuan ialah Seera yang telah mendirikan Bet-Horon-Hilir dan Bet-Horon-Hulu serta Uzen-Seera."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:25, Page:1,
    Kor:"○브리아의 아들은 레바와 레셉이다. 레셉의 아들은 델라이고, 그 아들은 다한이고,",
    Chn:"比利阿的儿子是利法和利悉。利悉的儿子是他拉；他拉的儿子是他罕；",
    Eng:"Rephah was his son, Resheph his son, Telah his son, Tahan his son,",
    Ind:"Anak laki-laki Beria ialah Refah, lalu Resef; anak orang ini ialah Telah, dan anak orang ini ialah Tahan,"
  },
  {Bible:"1Chronicles", Chapter:7, Verse:26, Page:1,
    Kor:"그 아들은 라단이고, 그 아들은 암미훗이고, 그 아들은 엘리사마이고,",
    Chn:"他罕的儿子是拉但；拉但的儿子是亚米忽；亚米忽的儿子是以利沙玛；",
    Eng:"Ladan his son, Ammihud his son, Elishama his son,",
    Ind:"dan anak orang ini ialah Ladan, dan anak orang ini ialah Amihud, dan anak orang ini ialah Elisama,"
  },
  {Bible:"1Chronicles", Chapter:7, Verse:27, Page:1,
    Kor:"그 아들은 눈이고, 그 아들은 여호수아이다.",
    Chn:"以利沙玛的儿子是嫩；嫩的儿子是约书亚。",
    Eng:"Nun his son and Joshua his son.",
    Ind:"dan anak orang ini ialah Nun, dan anak orang ini ialah Yosua."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:28, Page:1,
    Kor:"○에브라임 자손의 소유지와 거주지는 베델과 그 주변 마을들과, 동쪽의 나아란과, 서쪽의 게셀 및 그 주변 마을들과, 세겜과 그 주변 마을들이며, 또 아사와 그 주변 마을에까지 이른다.",
    Chn:"以法莲人的地业和住处是伯特利与其村庄；东边拿兰，西边基色与其村庄；示剑与其村庄，直到迦萨与其村庄；",
    Eng:"Their lands and settlements included Bethel and its surrounding villages, Naaran to the east, Gezer and its villages to the west, and Shechem and its villages all the way to Ayyah and its villages.",
    Ind:"Tanah milik mereka dan tempat kediaman mereka ialah Betel dengan segala anak kotanya, Naaran di sebelah timur dan Gezer dengan segala anak kotanya di sebelah barat, kemudian Sikhem dengan segala anak kotanya sampai Aya dengan segala anak kotanya,"
  },
  {Bible:"1Chronicles", Chapter:7, Verse:29, Page:1,
    Kor:"○벳산과 그 주변 마을과, 다아낙과 그 주변 마을과, 므깃도와 그 주변 마을과, 돌과 그 주변 마을은 므낫세 자손에게 돌아갔다. ○이 여러 곳에 이스라엘의 아들 요셉의 자손이 살았다.",
    Chn:"还有靠近玛拿西人的境界，伯·善与其村庄；他纳与其村庄；米吉多与其村庄；多珥与其村庄。以色列儿子约瑟的子孙住在这些地方。",
    Eng:"Along the borders of Manasseh were Beth Shan, Taanach, Megiddo and Dor, together with their villages. The descendants of Joseph son of Israel lived in these towns.",
    Ind:"dan pada perbatasan bani Manasye: Bet-Sean dengan segala anak kotanya, juga Taanakh dengan segala anak kotanya, Megido dengan segala anak kotanya, Dor dengan segala anak kotanya. Di tempat-tempat itulah keturunan Yusuf bin Israel diam."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:30, Page:1,
    Kor:"<아셀의 자손> ○아셀의 아들은 임나와 이스와와 이스위와 브리아이며, 그들의 누이는 세라이다.",
    Chn:"亚设的儿子是音拿、亦施瓦、亦施韦、比利亚，还有他们的妹子西 拉。",
    Eng:"The sons of Asher: Imnah, Ishvah, Ishvi and Beriah. Their sister was Serah.",
    Ind:"Anak-anak Asyer ialah Yimna, Yiswa, Yiswi dan Beria; Serah ialah saudara perempuan mereka."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:31, Page:1,
    Kor:"○브리아의 아들은 헤벨과 말기엘인데, 말기엘은 비르사잇의 아버지이다.",
    Chn:"比利亚的儿子是希别、玛结；玛结是比撒威的父亲。",
    Eng:"The sons of Beriah: Heber and Malkiel, who was the father of Birzaith.",
    Ind:"Anak-anak Beria ialah Heber dan Malkiel; dialah bapa Birzait."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:32, Page:1,
    Kor:"○헤벨은 야블렛과 소멜과 호담과 그들의 누이 수아를 낳았다.",
    Chn:"希别生雅弗勒、朔默、何坦，和他们的妹子书雅。",
    Eng:"Heber was the father of Japhlet, Shomer and Hotham and of their sister Shua.",
    Ind:"Heber memperanakkan Yaflet, Somer dan Hotam serta Sua, saudara perempuan mereka."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:33, Page:1,
    Kor:"○야블렛의 아들은 바삭과 빔할과 아스왓이니, 이들이 야블렛의 아들이다.",
    Chn:"雅弗勒的儿子是巴萨、宾哈、亚施法。这都是雅弗勒的儿子。",
    Eng:"The sons of Japhlet: Pasach, Bimhal and Ashvath. These were Japhlet's sons.",
    Ind:"Anak-anak Yaflet ialah Pasakh, Bimhab dan Asywat. Itulah anak-anak Yaflet."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:34, Page:1,
    Kor:"○소멜의 아들은 아히와 로가와 호바와 아람이다.",
    Chn:"朔默的儿子是亚希、罗迦、耶户巴、亚兰。",
    Eng:"The sons of Shomer: Ahi, Rohgah, Hubbah and Aram.",
    Ind:"Anak-anak Semer ialah Ahi, Rohga, Yehuba dan Aram."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:35, Page:1,
    Kor:"○소멜의 아우 헬렘의 아들은 소바와 임나와 셀레스와 아말이다.",
    Chn:"朔默兄弟希连的儿子是琐法、音那、示利斯、亚抹。",
    Eng:"The sons of his brother Helem: Zophah, Imna, Shelesh and Amal.",
    Ind:"Anak-anak Helem, saudaranya laki-laki, ialah Zofah, Yimna, Seles dan Amal."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:36, Page:1,
    Kor:"○소바의 아들은 수아와 하르네벨과 수알과 베리와 이므라와",
    Chn:"琐法的儿子是书亚、哈尼弗、书阿勒、比利、音拉、",
    Eng:"The sons of Zophah: Suah, Harnepher, Shual, Beri, Imrah,",
    Ind:"Anak-anak Zofah ialah Suah, Harnefer, Syual, Beri dan Yimra,"
  },
  {Bible:"1Chronicles", Chapter:7, Verse:37, Page:1,
    Kor:"베셀과 홋과 사마와 실사와 이드란과 브에라이다.",
    Chn:"比悉、河得、珊玛、施沙、益兰、比拉。",
    Eng:"Bezer, Hod, Shamma, Shilshah, Ithran and Beera.",
    Ind:"Bezer, Hod, Sama, Silsa, Yitran dan Beera."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:38, Page:1,
    Kor:"예델의 아들은 여분네와 비스바와 아라이다.",
    Chn:"益帖的儿子是耶孚尼、毗斯巴、亚拉。",
    Eng:"The sons of Jether: Jephunneh, Pispah and Ara.",
    Ind:"Anak-anak Yeter ialah Yefune, Pispa dan Ara."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:39, Page:1,
    Kor:"울라의 아들은 아라와 한니엘과 리시아이다.",
    Chn:"乌拉的儿子是亚拉、汉尼业、利写。",
    Eng:"The sons of Ulla: Arah, Hanniel and Rizia.",
    Ind:"Anak-anak Ula ialah Arah, Haniel dan Rizya."
  },
  {Bible:"1Chronicles", Chapter:7, Verse:40, Page:1,
    Kor:"○이들은 모두 아셀의 자손으로서, 각 가문의 족장들이요, 뽑힌 용감한 군인들이요, 지도자급 족장들이다. 싸움에 나갈 만한 군인으로서 족보에 오른 사람의 수는 이만 육천 명이다.",
    Chn:"这都是亚设的子孙，都是族长，是精壮大能的勇士，也是首领中的头目，按着家谱计算，他们的子孙能出战的共有二万六千人。",
    Eng:"All these were descendants of Asher--heads of families, choice men, brave warriors and outstanding leaders. The number of men ready for battle, as listed in their genealogy, was 26,000.",
    Ind:"Itulah sekaliannya keturunan Asyer, kepala-kepala puak mereka, pahlawan-pahlawan gagah perkasa yang terpilih, pemimpin-pemimpin utama. Jumlah yang terdaftar dalam silsilah mereka sebagai pasukan perang ada dua puluh enam ribu orang."
  },
]);
