// 역대상 15장 · 1Chronicles 15
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",15,29);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:15, Verse:1, Page:1,
    Kor:"<언약궤를 옮길 준비> 다윗이 '다윗 성'에 자기가 살 궁궐을 지었다. 또 하나님의 궤를 둘 한 장소를 마련하고 궤를 안치할 장소에 장막을 치고,",
    Chn:"大卫在大卫城为自己建造宫殿，又为　神的约柜预备地方，支搭帐幕。",
    Eng:"After David had constructed buildings for himself in the City of David, he prepared a place for the ark of God and pitched a tent for it.",
    Ind:"Daud membuat bagi dirinya gedung-gedung di kota Daud, lalu ia menyiapkan tempat bagi tabut Allah dan membentangkan kemah untuk itu."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:2, Page:1,
    Kor:"이렇게 말하였다. \"레위 사람 말고는 아무도 하나님의 궤를 메어서는 안 된다. 주님께서 그들을 선택하여, 그들이 하나님의 궤를 메고 영원히 하나님을 섬기게 하셨기 때문이다.\"",
    Chn:"那时大卫说：「除了利未人之外，无人可抬　神的约柜；因为耶和华拣选他们抬　神的约柜，且永远事奉他。」",
    Eng:"Then David said, \"No one but the Levites may carry the ark of God, because the LORD chose them to carry the ark of the LORD and to minister before him forever.\"",
    Ind:"Ketika itu berkatalah Daud: \"Janganlah ada yang mengangkat tabut Allah selain dari orang Lewi, sebab merekalah yang dipilih TUHAN untuk mengangkat tabut TUHAN dan untuk menyelenggarakannya sampai selama-lamanya.\""
  },
  {Bible:"1Chronicles", Chapter:15, Verse:3, Page:1,
    Kor:"다윗은 그가 마련한 장소에 주님의 궤를 옮겨 오려고, 온 이스라엘을 예루살렘으로 불러모았다.",
    Chn:"大卫招聚以色列众人到耶路撒冷，要将耶和华的约柜抬到他所预备的地方。",
    Eng:"David assembled all Israel in Jerusalem to bring up the ark of the LORD to the place he had prepared for it.",
    Ind:"Kemudian Daud mengumpulkan segenap Israel ke Yerusalem untuk mengangkut tabut TUHAN ke tempat yang telah disiapkannya untuk itu."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:4, Page:1,
    Kor:"다윗이 불러모은 아론의 자손과 레위 사람은 다음과 같다.",
    Chn:"大卫又聚集亚伦的子孙和利未人。",
    Eng:"He called together the descendants of Aaron and the Levites:",
    Ind:"Daud mengumpulkan bani Harun dan orang Lewi:"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:5, Page:1,
    Kor:"고핫 자손 가운데서 족장 우리엘과 그의 친족 백이십 명,",
    Chn:"哥辖子孙中有族长乌列和他的弟兄一百二十人。",
    Eng:"From the descendants of Kohath, Uriel the leader and 120 relatives;",
    Ind:"dari bani Kehat: Uriel, seorang pemimpin, dan saudara-saudara sepuaknya: seratus dua puluh orang;"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:6, Page:1,
    Kor:"므라리 자손 가운데서 족장 아사야와 그의 친족 이백이십 명,",
    Chn:"米拉利子孙中有族长亚帅雅和他的弟兄二百二十人。",
    Eng:"from the descendants of Merari, Asaiah the leader and 220 relatives;",
    Ind:"dari bani Merari: Asaya, seorang pemimpin, dan saudara-saudara sepuaknya: dua ratus dua puluh orang;"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:7, Page:1,
    Kor:"a게르손 자손 가운데서 족장 요엘과 그의 친족 백삼십 명,(a 히, '게르솜', 게르손의 변형)",
    Chn:"革顺子孙中有族长约珥和他的弟兄一百三十人。",
    Eng:"from the descendants of Gershon, Joel the leader and 130 relatives;",
    Ind:"dari bani Gerson: Yoel, seorang pemimpin, dan saudara-saudara sepuaknya: seratus tiga puluh orang;"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:8, Page:1,
    Kor:"엘리사반 자손 가운데서 족장 스마야와 그의 친족 이백 명,",
    Chn:"以利撒反子孙中有族长示玛雅和他的弟兄二百人。",
    Eng:"from the descendants of Elizaphan, Shemaiah the leader and 200 relatives;",
    Ind:"dari bani Elsafan: Semaya, seorang pemimpin, dan saudara-saudara sepuaknya: dua ratus orang;"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:9, Page:1,
    Kor:"헤브론 자손 가운데서 족장 엘리엘과 그의 친족 여든 명,",
    Chn:"希伯 子孙中有族长以列和他的弟兄八十人。",
    Eng:"from the descendants of Hebron, Eliel the leader and 80 relatives;",
    Ind:"dari bani Hebron: Eliel, seorang pemimpin, dan saudara-saudara sepuaknya: delapan puluh orang;"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:10, Page:1,
    Kor:"웃시엘 자손 가운데서 족장 암미나답과 그의 친족 백십이 명이다.",
    Chn:"乌薛子孙中有族长亚米拿达和他的弟兄一百一十二人。",
    Eng:"from the descendants of Uzziel, Amminadab the leader and 112 relatives.",
    Ind:"dari bani Uziel: Aminadab, seorang pemimpin, dan saudara-saudara sepuaknya: seratus dua belas orang."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:11, Page:1,
    Kor:"○다윗은 제사장 사독과 아비아달과 레위 사람 우리엘과 아사야와 요엘과 스마야와 엘리엘과 암미나답을 불러,",
    Chn:"大卫将祭司撒督和亚比亚他，并利未人乌列、亚帅雅、约珥、示玛雅、以列、亚米拿达召来，",
    Eng:"Then David summoned Zadok and Abiathar the priests, and Uriel, Asaiah, Joel, Shemaiah, Eliel and Amminadab the Levites.",
    Ind:"Lalu Daud memanggil Zadok dan Abyatar, imam-imam itu, dan orang-orang Lewi, yakni Uriel, Asaya, Yoel, Semaya, Eliel dan Aminadab,"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:12, Page:1,
    Kor:"그들에게 말하였다. \"여러분은 레위 가문의 족장들입니다. 여러분 자신과 여러분의 친족들을 성결하게 하고, 주 이스라엘의 하나님의 궤를 내가 마련한 장소로 옮기십시오.",
    Chn:"对他们说：「你们是利未人的族长，你们和你们的弟兄应当自洁，好将耶和华—以色列　神的约柜抬到我所预备的地方。",
    Eng:"He said to them, \"You are the heads of the Levitical families; you and your fellow Levites are to consecrate yourselves and bring up the ark of the LORD, the God of Israel, to the place I have prepared for it.",
    Ind:"dan berkata kepada mereka: \"Hai kamu ini, para kepala puak dari orang Lewi, kuduskanlah dirimu, kamu ini dan saudara-saudara sepuakmu, supaya kamu mengangkut tabut TUHAN, Allah Israel, ke tempat yang telah kusiapkan untuk itu."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:13, Page:1,
    Kor:"지난번에는 여러분이 메지 않았으므로, 주 우리 하나님께서 우리를 치셨습니다. 우리가 그분께 규례대로 하지 않아서 그렇게 된 것입니다.\"",
    Chn:"因你们先前没有抬这约柜，按定例求问耶和华—我们的　神，所以他刑罚我们。」",
    Eng:"It was because you, the Levites, did not bring it up the first time that the LORD our God broke out in anger against us. We did not inquire of him about how to do it in the prescribed way.\"",
    Ind:"Sebab oleh karena pada pertama kali kamu tidak hadir, maka TUHAN, Allah kita, telah menyambar di tengah-tengah kita, sebab kita tidak meminta petunjuk-Nya seperti seharusnya.\""
  },
  {Bible:"1Chronicles", Chapter:15, Verse:14, Page:1,
    Kor:"○그러자 제사장들과 레위 사람들이 주 이스라엘의 하나님의 궤를 옮겨 오려고, 스스로를 성결하게 하였다.",
    Chn:"于是祭司利未人自洁，好将耶和华—以色列　神的约柜抬上来。",
    Eng:"So the priests and Levites consecrated themselves in order to bring up the ark of the LORD, the God of Israel.",
    Ind:"Jadi para imam dan orang-orang Lewi menguduskan dirinya untuk mengangkut tabut TUHAN, Allah Israel."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:15, Page:1,
    Kor:"레위 자손은, 모세가 명령한 하나님의 말씀대로, 하나님의 궤를 채에 꿰어 그들의 어깨에 메었다.",
    Chn:"利未子孙就用杠，肩抬　神的约柜，是照耶和华借摩西所吩咐的。",
    Eng:"And the Levites carried the ark of God with the poles on their shoulders, as Moses had commanded in accordance with the word of the LORD.",
    Ind:"Kemudian bani Lewi mengangkat tabut Allah itu dengan gandar pengusung di atas bahu mereka, seperti yang diperintahkan Musa, sesuai dengan firman TUHAN."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:16, Page:1,
    Kor:"○다윗은 레위 사람의 족장들에게 지시하여, 그들의 친족으로 찬양하는 사람들에 임명하게 하고, 거문고와 수금과 심벌즈 등 악기를 연주하며, 큰소리로 즐겁게 노래를 부르게 하였다.",
    Chn:"大卫吩咐利未人的族长，派他们歌唱的弟兄用琴瑟和钹作乐，欢欢喜喜地大声歌颂。",
    Eng:"David told the leaders of the Levites to appoint their brothers as singers to sing joyful songs, accompanied by musical instruments: lyres, harps and cymbals.",
    Ind:"Daud memerintahkan para kepala orang Lewi itu, supaya mereka menyuruh berdiri saudara-saudara sepuak mereka, yakni para penyanyi, dengan membawa alat-alat musik seperti gambus, kecapi dan ceracap, untuk memperdengarkan dengan nyaring lagu-lagu gembira."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:17, Page:1,
    Kor:"레위 사람은, 요엘의 아들 헤만과, 그의 친족 가운데서 베레야의 아들 아삽과, 또 그들의 친족인 므라리 자손 가운데서 구사야의 아들 에단을 임명하였다.",
    Chn:"于是利未人派约珥的儿子希幔和他弟兄中比利家的儿子亚萨，并他们族弟兄米拉利子孙里古沙雅的儿子以探。",
    Eng:"So the Levites appointed Heman son of Joel; from his brothers, Asaph son of Berekiah; and from their brothers the Merarites, Ethan son of Kushaiah;",
    Ind:"Maka orang Lewi itu menyuruh berdiri Heman bin Yoel; dan dari saudara-saudara sepuaknya: Asaf bin Berekhya; dari bani Merari, saudara-saudara sepuak mereka: Etan bin Kusaya;"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:18, Page:1,
    Kor:"그들 말고, 두 번째 서열에 속한 그들의 친족들은, 스가랴와 벤과 야아시엘과 스미라못과 여히엘과 운니와 엘리압과 브나야와 마아세야와 맛디디야와 엘리블레후와 믹네야와 문지기 오벳에돔과 여이엘이다.",
    Chn:"其次还有他们的弟兄撒迦利雅、便雅薛、示米拉末、耶歇、乌尼、以利押、比拿雅、玛西雅、玛他提雅、以利斐利户、弥克尼雅，并守门的俄别·以东和耶利。",
    Eng:"and with them their brothers next in rank: Zechariah, Jaaziel, Shemiramoth, Jehiel, Unni, Eliab, Benaiah, Maaseiah, Mattithiah, Eliphelehu, Mikneiah, Obed-Edom and Jeiel, the gatekeepers.",
    Ind:"dan bersama-sama mereka itu saudara-saudara mereka dari tingkat kedua: Zakharia, Yaaziel, Semiramot, Yehiel, Uni, Eliab, Benaya, Maaseya, Matica, Elifele, Mikneya, dan Obed-Edom serta Yeiel, para penunggu pintu gerbang."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:19, Page:1,
    Kor:"찬양대에 속한, 헤만과 아삽과 에단은 놋 심벌즈를 치고,",
    Chn:"这样，派歌唱的希幔、亚萨、以探敲铜钹，大发响声；",
    Eng:"The musicians Heman, Asaph and Ethan were to sound the bronze cymbals;",
    Ind:"Para penyanyi, yakni Heman, Asaf dan Etan harus memperdengarkan lagu dengan ceracap tembaga."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:20, Page:1,
    Kor:"스가랴와 아시엘과 스미라못과 여히엘과 운니와 엘리압과 마아세야와 브나야는 알라못 방식으로 거문고를 타고,",
    Chn:"派撒迦利雅、雅薛、示米拉末、耶歇、乌尼、以利押、玛西雅、比拿雅鼓瑟，调用女音；",
    Eng:"Zechariah, Aziel, Shemiramoth, Jehiel, Unni, Eliab, Maaseiah and Benaiah were to play the lyres according to alamoth,",
    Ind:"Zakharia, Aziel, Semiramot, Yehiel, Uni, Eliab, Maaseya, Benaya harus memainkan gambus yang tinggi nadanya,"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:21, Page:1,
    Kor:"맛디디야와 엘리블레후와 믹네야와 오벳에돔과 여이엘과 아사시야는 스미닛 방식으로 수금을 탔다.",
    Chn:"又派玛他提雅、以利斐利户、弥克尼雅、俄别·以东、耶利、亚撒西雅领首弹琴，调用第八。",
    Eng:"and Mattithiah, Eliphelehu, Mikneiah, Obed-Edom, Jeiel and Azaziah were to play the harps, directing according to sheminith.",
    Ind:"sedang Matica, Elifele, Mikneya, Obed-Edom, Yeiel dan Azazya harus memainkan kecapi yang delapan nada lebih rendah tingkatnya untuk mengiringi nyanyian."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:22, Page:1,
    Kor:"○레위 사람의 족장 그나냐는 지휘를 맡았다. 그는 음악에 조예가 깊었으므로 찬양하는 것을 지도하였다.",
    Chn:"利未人的族长基拿尼雅是歌唱人的首领，又教训人歌唱，因为他精通此事。",
    Eng:"Kenaniah the head Levite was in charge of the singing; that was his responsibility because he was skillful at it.",
    Ind:"Kenanya, pemimpin orang Lewi, mendapat tugas pengangkutan; ia mengepalai pengangkutan, sebab ia paham dalam hal itu."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:23, Page:1,
    Kor:"베레갸와 엘가나는 궤를 지키는 문지기이다.",
    Chn:"比利家、以利加拿是约柜前守门的。",
    Eng:"Berekiah and Elkanah were to be doorkeepers for the ark.",
    Ind:"Berekhya dan Elkana adalah penunggu pintu pada tabut;"
  },
  {Bible:"1Chronicles", Chapter:15, Verse:24, Page:1,
    Kor:"제사장인, 스바냐와 요사밧과 느다넬과 아마새와 스가랴와 브나야와 엘리에셀은, 하나님의 궤 앞에서 나팔을 불었다. 오벳에돔과 여히야는 궤를 지키는 문지기이다.",
    Chn:"祭司示巴尼、约沙法、拿坦业、亚玛赛、撒迦利雅、比拿亚、以利以谢在　神的约柜前吹号。俄别·以东和耶希亚也是约柜前守门的。",
    Eng:"Shebaniah, Joshaphat, Nethanel, Amasai, Zechariah, Benaiah and Eliezer the priests were to blow trumpets before the ark of God. Obed-Edom and Jehiah were also to be doorkeepers for the ark.",
    Ind:"dan Sebanya, Yosafat, Netaneel, Amasai, Zakharia, Benaya dan Eliezer, yakni imam-imam itu, meniup nafiri di hadapan tabut Allah, sedang Obed-Edom dan Yehia adalah penunggu pintu pada tabut itu."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:25, Page:1,
    Kor:"<언약궤를 예루살렘으로 옮기다(삼하 6:12-22)> ○다윗과 이스라엘 장로들과 천부장들이 오벳에돔의 집에서 주님의 언약궤를 옮겨 오려고 기쁜 마음으로 그리로 갔다.",
    Chn:"于是，大卫和以色列的长老，并千夫长都去从俄别·以东的家欢欢喜喜地将耶和华的约柜抬上来。",
    Eng:"So David and the elders of Israel and the commanders of units of a thousand went to bring up the ark of the covenant of the LORD from the house of Obed-Edom, with rejoicing.",
    Ind:"Maka Daud dan para tua-tua Israel dan para pemimpin pasukan seribu pergi untuk mengangkut tabut perjanjian TUHAN itu dari rumah Obed-Edom dengan sukacita."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:26, Page:1,
    Kor:"하나님께서 주님의 언약궤를 운반하는 레위 사람들을 도우셨으므로, 그들이 수송아지 일곱 마리와 숫양 일곱 마리를 제물로 잡아서 바쳤다.",
    Chn:"神赐恩与抬耶和华约柜的利未人，他们就献上七只公牛，七只公羊。",
    Eng:"Because God had helped the Levites who were carrying the ark of the covenant of the LORD, seven bulls and seven rams were sacrificed.",
    Ind:"Dan oleh karena Allah menolong orang Lewi yang mengangkat tabut perjanjian TUHAN itu, maka dipersembahkanlah tujuh ekor lembu jantan dan tujuh ekor domba jantan."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:27, Page:1,
    Kor:"다윗과, 하나님의 궤를 멘 레위 사람들과, 찬양하는 사람들과, 찬양하는 사람들의 지휘자 그나냐가 모두 다 고운 모시로 만든 겉옷을 입고 있었으며, 다윗은 모시로 만든 에봇을 입고 있었다.",
    Chn:"大卫和抬约柜的利未人，并歌唱人的首领基拿尼雅，以及歌唱的人，都穿着细麻布的外袍；大卫另外穿着细麻布的以弗得。",
    Eng:"Now David was clothed in a robe of fine linen, as were all the Levites who were carrying the ark, and as were the singers, and Kenaniah, who was in charge of the singing of the choirs. David also wore a linen ephod.",
    Ind:"Daud memakai jubah dari kain lenan halus, juga segala orang Lewi yang mengangkat tabut itu dan para penyanyi, dan Kenanya yang mengepalai pengangkutan dan para penyanyi. Daud juga memakai baju efod dari kain lenan."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:28, Page:1,
    Kor:"온 이스라엘은 환호성을 올리며, 뿔나팔과 나팔을 불고, 심벌즈를 우렁차게 치고, 거문고와 수금을 타면서, 주님의 언약궤를 메고 올라왔다.",
    Chn:"这样，以色列众人欢呼吹角、吹号、敲钹、鼓瑟、弹琴，大发响声，将耶和华的约柜抬上来。",
    Eng:"So all Israel brought up the ark of the covenant of the LORD with shouts, with the sounding of rams' horns and trumpets, and of cymbals, and the playing of lyres and harps.",
    Ind:"Seluruh orang Israel mengangkut tabut perjanjian TUHAN itu dengan diiringi sorak dan bunyi sangkakala, nafiri dan ceracap, sambil memperdengarkan permainan gambus dan kecapi."
  },
  {Bible:"1Chronicles", Chapter:15, Verse:29, Page:1,
    Kor:"○주님의 언약궤가 '다윗 성'으로 들어올 때에, 사울의 딸 미갈이 창 밖을 내다보다가, 다윗 왕이 춤추며 기뻐하는 것을 보고, 마음 속으로 그를 업신여겼다.",
    Chn:"耶和华的约柜进了大卫城的时候，扫罗的女儿米甲从窗户里观看，见大卫王踊跃跳舞，心里就轻视他。",
    Eng:"As the ark of the covenant of the LORD was entering the City of David, Michal daughter of Saul watched from a window. And when she saw King David dancing and celebrating, she despised him in her heart.",
    Ind:"Ketika tabut perjanjian TUHAN itu sampai ke kota Daud, maka Mikhal, anak perempuan Saul, menjenguk dari jendela, lalu melihat raja Daud melompat-lompat dan menari-nari. Sebab itu ia memandang rendah Daud dalam hatinya."
  },
]);
