// 역대상 27장 · 1Chronicles 27
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Chronicles",27,34);
BibleDB.add([
  {Bible:"1Chronicles", Chapter:27, Verse:1, Page:1,
    Kor:"<군대와 시민> 이스라엘 자손 가운데서 각 갈래에 부과된 모든 일을 하면서 왕을 섬기는, 각 가문의 족장과 천부장과 백부장과 서기관의 수는 다음과 같다. 그들은 한 해에 한 달씩 번갈아 가며 근무를 하였는데, 한 갈래는 이만 사천 명씩이다.",
    Chn:"以色列人的族长、千夫长、百夫长，和官长都分定班次，每班是二万四千人，周年按月轮流，替换出入服事王。",
    Eng:"David summoned all the officials of Israel to assemble at Jerusalem: the officers over the tribes, the commanders of the divisions in the service of the king, the commanders of thousands and commanders of hundreds, and the officials in charge of all the property and livestock belonging to the king and his sons, together with the palace officials, the mighty men and all the brave warriors.",
    Ind:"Adapun orang Israel, inilah daftar para kepala puak, para panglima pasukan seribu dan pasukan seratus dan para pengatur yang melayani raja dalam segala hal mengenai rombongan orang-orang yang bertugas dan libur, bulan demi bulan, sepanjang tahun. Setiap rombongan berjumlah dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:2, Page:1,
    Kor:"○첫째 달에 복무할 첫째 갈래의 지휘관은 삽디엘의 아들 야소브암이며, 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"正月第一班的班长是撒巴第业的儿子雅朔班；他班内有二万四千人。",
    Eng:"King David rose to his feet and said: \"Listen to me, my brothers and my people. I had it in my heart to build a house as a place of rest for the ark of the covenant of the LORD, for the footstool of our God, and I made plans to build it.",
    Ind:"Yang mengepalai rombongan pertama untuk bulan pertama ialah Yasobam bin Zabdiel dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:3, Page:1,
    Kor:"그는 베레스의 자손으로서, 정월에 복무하는 모든 부대 지휘관의 우두머리이다.",
    Chn:"他是法勒斯的子孙，统管正月班的一切军长。",
    Eng:"But God said to me, 'You are not to build a house for my Name, because you are a warrior and have shed blood.'",
    Ind:"Ia dari bani Peres dan mengepalai semua panglima untuk bulan yang pertama."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:4, Page:1,
    Kor:"둘째 달에 복무할 둘째 갈래의 지휘관은 아호아 사람 도대이며, 그 갈래의 부지휘관은 미글롯이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"二月的班长是亚哈希人朵代，还有副官密基罗；他班内有二万四千人。",
    Eng:"\"Yet the LORD, the God of Israel, chose me from my whole family to be king over Israel forever. He chose Judah as leader, and from the house of Judah he chose my family, and from my father's sons he was pleased to make me king over all Israel.",
    Ind:"Yang mengepalai rombongan bulan yang kedua ialah Dodai, orang Ahohi, sedang pemimpin rombongannya yang berjumlah dua puluh empat ribu orang, adalah Miklot."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:5, Page:1,
    Kor:"셋째 달에 복무할 셋째 갈래의 지휘관은 여호야다의 아들 브나야이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"三月第三班的班长是祭司耶何耶大的儿子比拿雅；他班内有二万四千人。",
    Eng:"Of all my sons--and the LORD has given me many--he has chosen my son Solomon to sit on the throne of the kingdom of the LORD over Israel.",
    Ind:"Panglima yang ketiga untuk bulan yang ketiga ialah Benaya, anak imam kepala Yoyada, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:6, Page:1,
    Kor:"바로 이 브나야가 서른 명의 용사 가운데 하나로서 서른 명을 지휘하였다. 그의 아들 암미사밧은 그 갈래의 부지휘관이다.",
    Chn:"这比拿雅是那三十人中的勇士，管理那三十人；他班内又有他儿子暗米萨拔。",
    Eng:"He said to me: 'Solomon your son is the one who will build my house and my courts, for I have chosen him to be my son, and I will be his father.",
    Ind:"Benaya ini adalah seorang dari ketiga puluh pahlawan dan mengepalai ketiga puluh orang itu, tetapi yang memegang pimpinan rombongannya ialah Amizabad, anaknya."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:7, Page:1,
    Kor:"넷째 달에 복무할 넷째 갈래의 지휘관은 요압의 동생 아사헬이다. 그의 아들 스바댜가 부지휘관이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"四月第四班的班长是约押的兄弟亚撒黑。接续他的是他儿子西巴第雅；他班内有二万四千人。",
    Eng:"I will establish his kingdom forever if he is unswerving in carrying out my commands and laws, as is being done at this time.'",
    Ind:"Yang keempat untuk bulan yang keempat ialah Asael, saudara Yoab, kemudian ia digantikan oleh Zebaja, anaknya, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:8, Page:1,
    Kor:"다섯째 달에 복무할 다섯째 갈래의 지휘관은 이스라 사람 삼훗이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"五月第五班的班长是伊斯拉人珊合；他班内有二万四千人。",
    Eng:"\"So now I charge you in the sight of all Israel and of the assembly of the LORD, and in the hearing of our God: Be careful to follow all the commands of the LORD your God, that you may possess this good land and pass it on as an inheritance to your descendants forever.",
    Ind:"Yang kelima untuk bulan yang kelima ialah Samhut orang Yizrah, panglima itu, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:9, Page:1,
    Kor:"여섯째 달에 복무할 여섯째 갈래의 지휘관은 드고아 사람 익게스의 아들 이라이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"六月第六班的班长是提哥亚人益吉的儿子以拉；他班内有二万四千人。",
    Eng:"\"And you, my son Solomon, acknowledge the God of your father, and serve him with wholehearted devotion and with a willing mind, for the LORD searches every heart and understands every motive behind the thoughts. If you seek him, he will be found by you; but if you forsake him, he will reject you forever.",
    Ind:"Yang keenam untuk bulan yang keenam ialah Ira anak Ikesh orang Tekoa dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:10, Page:1,
    Kor:"일곱째 달에 복무할 일곱째 갈래의 지휘관은 에브라임 자손인 발론 사람 헬레스이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"七月第七班的班长是以法莲族比伦人希利斯；他班内有二万四千人。",
    Eng:"Consider now, for the LORD has chosen you to build a temple as a sanctuary. Be strong and do the work.\"",
    Ind:"Yang ketujuh untuk bulan yang ketujuh ialah Heles, orang Peloni, dari bani Efraim, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:11, Page:1,
    Kor:"여덟째 달에 복무할 여덟째 갈래의 지휘관은 세라 족속에 속한 후사 사람 십브개이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"八月第八班的班长是谢拉族户沙人西比该；他班内有二万四千人。",
    Eng:"Then David gave his son Solomon the plans for the portico of the temple, its buildings, its storerooms, its upper parts, its inner rooms and the place of atonement.",
    Ind:"Yang kedelapan untuk bulan yang kedelapan ialah Sibkhai, orang Husa dari orang Zerah itu, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:12, Page:1,
    Kor:"아홉째 달에 복무할 아홉째 갈래의 지휘관은 베냐민 지파의 아나돗 사람 아비에셀이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"九月第九班的班长是便雅悯族亚拿突人亚比以谢；他班内有二万四千人。",
    Eng:"He gave him the plans of all that the Spirit had put in his mind for the courts of the temple of the LORD and all the surrounding rooms, for the treasuries of the temple of God and for the treasuries for the dedicated things.",
    Ind:"Yang kesembilan untuk bulan yang kesembilan ialah Abiezer, orang Anatot itu, dari bani Benyamin, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:13, Page:1,
    Kor:"열째 달에 복무할 열째 갈래의 지휘관은 세라 족속에 속한 느도바 사람 마하래이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"十月第十班的班长是谢拉族尼陀法人玛哈莱；他班内有二万四千人。",
    Eng:"He gave him instructions for the divisions of the priests and Levites, and for all the work of serving in the temple of the LORD, as well as for all the articles to be used in its service.",
    Ind:"Yang kesepuluh untuk bulan yang kesepuluh ialah Maharai, orang Netofa dari orang Zerah itu, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:14, Page:1,
    Kor:"열한째 달에 복무할 열한째 갈래의 지휘관은 에브라임 자손인 비라돈 사람 브나야이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"十一月第十一班的班长是以法莲族比拉顿人比拿雅；他班内有二万四千人。",
    Eng:"He designated the weight of gold for all the gold articles to be used in various kinds of service, and the weight of silver for all the silver articles to be used in various kinds of service:",
    Ind:"Yang kesebelas untuk bulan yang kesebelas ialah Benaya, orang Piraton, dari bani Efraim, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:15, Page:1,
    Kor:"열두째 달에 복무할 열두째 갈래의 지휘관은 옷니엘 자손의 느도바 사람 헬대이다. 그의 갈래에는 이만 사천 명이 있다.",
    Chn:"十二月第十二班的班长是俄陀聂族尼陀法人黑玳；他班内有二万四千人。",
    Eng:"the weight of gold for the gold lampstands and their lamps, with the weight for each lampstand and its lamps; and the weight of silver for each silver lampstand and its lamps, according to the use of each lampstand;",
    Ind:"Yang kedua belas untuk bulan yang kedua belas ialah Heldai, orang Netofa itu, keturunan Otniel, dan dalam rombongannya ada dua puluh empat ribu orang."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:16, Page:1,
    Kor:"<각 지파의 영도자들> ○이스라엘 각 지파의 영도자들은 다음과 같다. 르우벤 지파의 영도자는 시그리의 아들 엘리에셀이고, 시므온 지파의 영도자는 마아가의 아들 스바댜이고,",
    Chn:"管理以色列众支派的记在下面：管吕便人的是细基利的儿子以利以谢；管西缅人的是玛迦的儿子示法提雅；",
    Eng:"the weight of gold for each table for consecrated bread; the weight of silver for the silver tables;",
    Ind:"Yang mengepalai suku-suku Israel: untuk orang Ruben ialah Eliezer bin Zikhri sebagai pemimpin; untuk orang Simeon ialah Sefaca bin Maakha;"
  },
  {Bible:"1Chronicles", Chapter:27, Verse:17, Page:1,
    Kor:"레위 지파의 영도자는 그무엘의 아들 하사뱌이고, 아론 지파의 영도자는 사독이고,",
    Chn:"管利未人的是基母利的儿子哈沙比雅；管亚伦子孙的是撒督；",
    Eng:"the weight of pure gold for the forks, sprinkling bowls and pitchers; the weight of gold for each gold dish; the weight of silver for each silver dish;",
    Ind:"untuk suku Lewi ialah Hasabya bin Kemuel; untuk keturunan Harun ialah Zadok;"
  },
  {Bible:"1Chronicles", Chapter:27, Verse:18, Page:1,
    Kor:"유다 지파의 영도자는 다윗의 형 엘리후이고, 잇사갈 지파의 영도자는 미가엘의 아들 오므리이고,",
    Chn:"管犹大人的是大卫的一个哥哥以利户；管以萨迦人的是米迦勒的儿子暗利；",
    Eng:"and the weight of the refined gold for the altar of incense. He also gave him the plan for the chariot, that is, the cherubim of gold that spread their wings and shelter the ark of the covenant of the LORD.",
    Ind:"untuk suku Yehuda ialah Elihu, salah seorang saudara Daud; untuk suku Isakhar ialah Omri bin Mikhael;"
  },
  {Bible:"1Chronicles", Chapter:27, Verse:19, Page:1,
    Kor:"스불론 지파의 영도자는 오바댜의 아들 이스마야이고, 납달리 지파의 영도자는 아스리엘의 아들 여레못이고,",
    Chn:"管西布伦人的是俄巴第雅的儿子伊施玛雅；管拿弗他利人的是亚斯列的儿子耶利摩；",
    Eng:"\"All this,\" David said, \"I have in writing from the hand of the LORD upon me, and he gave me understanding in all the details of the plan.\"",
    Ind:"untuk suku Zebulon ialah Yismaya bin Obaja; untuk suku Naftali ialah Yerimot bin Azriel;"
  },
  {Bible:"1Chronicles", Chapter:27, Verse:20, Page:1,
    Kor:"에브라임 지파의 영도자는 아사시야의 아들 호세아이고, 므낫세 반쪽 지파의 영도자는 브다야의 아들 요엘이고,",
    Chn:"管以法莲人的是阿撒细雅的儿子何细亚；管玛拿西半支派的是毗大雅的儿子约珥；",
    Eng:"David also said to Solomon his son, \"Be strong and courageous, and do the work. Do not be afraid or discouraged, for the LORD God, my God, is with you. He will not fail you or forsake you until all the work for the service of the temple of the LORD is finished.",
    Ind:"untuk bani Efraim ialah Hosea bin Azazya; untuk setengah suku Manasye ialah Yoel bin Pedaya;"
  },
  {Bible:"1Chronicles", Chapter:27, Verse:21, Page:1,
    Kor:"길르앗에 있는 므낫세 반쪽 지파의 영도자는 스가랴의 아들 잇도이고, 베냐민 지파의 영도자는 아브넬의 아들 야아시엘이고,",
    Chn:"管基列地玛拿西那半支派的是撒迦利亚的儿子易多；管便雅悯人的是押尼珥的儿子雅西业；",
    Eng:"The divisions of the priests and Levites are ready for all the work on the temple of God, and every willing man skilled in any craft will help you in all the work. The officials and all the people will obey your every command.\"",
    Ind:"untuk setengah suku Manasye yang di Gilead ialah Yido bin Zakharia; untuk suku Benyamin ialah Yaasiel bin Abner;"
  },
  {Bible:"1Chronicles", Chapter:27, Verse:22, Page:1,
    Kor:"단 지파의 영도자는 여로함의 아들 아사렐이다. 이들이 이스라엘 각 지파의 영도자이다.",
    Chn:"管但人的是耶罗罕的儿子亚萨列。以上是以色列众支派的首领。",
    Eng:"",
    Ind:"untuk suku Dan ialah Azareel bin Yeroham. Itulah para kepala suku-suku Israel."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:23, Page:1,
    Kor:"○주님께서 이스라엘 사람을 하늘의 별만큼 많게 해주겠다고 약속하셨기 때문에, 다윗이 스무 살 이하의 사람 숫자는 조사하지 않았다.",
    Chn:"以色列人二十岁以内的，大卫没有记其数目；因耶和华曾应许说，必加增以色列人如天上的星那样多。",
    Eng:"",
    Ind:"Daud tidak menghitung jumlah orang-orang yang berumur dua puluh tahun ke bawah, sebab TUHAN telah menjanjikan untuk membuat orang Israel sebanyak bintang-bintang di langit."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:24, Page:1,
    Kor:"스루야의 아들 요압이 인구조사를 시작하였으나, 이 일 때문에 주님께서 이스라엘에게 진노하셨으므로 끝마치지 못하였다. 그래서 인구조사 결과가 다윗 왕의 실록에 기록되지 못하였다.",
    Chn:"洗鲁雅的儿子约押动手数点，当时耶和华的烈怒临到以色列人；因此，没有点完，数目也没有写在大卫王记上。",
    Eng:"",
    Ind:"Memang Yoab, anak Zeruya, telah mulai menghitung, tetapi ia tidak menyelesaikannya, sebab oleh karena hal itu orang Israel tertimpa murka; dengan demikian jumlah mereka tidak dibukukan dalam kitab sejarah raja Daud."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:25, Page:1,
    Kor:"<왕실 재산 관리자> ○아디엘의 아들 아스마웻은 왕의 곳간을 맡고, 웃시야의 아들 요나단은 들녘과 성읍과 마을과 요새에 있는 곳간을 맡았다.",
    Chn:"掌管王府库的是亚叠的儿子押斯马威。掌管田野城邑村庄保障之仓库的是乌西雅的儿子约拿单。",
    Eng:"",
    Ind:"Yang mengawasi persediaan raja ialah Azmawet bin Adiel dan yang mengawasi persediaan di luar kota, di kota-kota, di desa-desa dan di dalam menara-menara lumbung ialah Yonatan bin Uzia."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:26, Page:1,
    Kor:"글룹의 아들 에스리는 밭에서 일하는 농민을 관리하였다.",
    Chn:"掌管耕田种地的是基绿的儿子以斯利。",
    Eng:"",
    Ind:"Yang mengawasi para pekerja di ladang yang harus mengusahakan tanah ialah Ezri bin Kelub."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:27, Page:1,
    Kor:"라마 사람 시므이는 포도원을 관리하고, 스밤 사람 삽디는 포도원에서 포도주 곳간을 관리하였다.",
    Chn:"掌管葡萄园的是拉玛人示每。掌管葡萄园酒窖的是实弗米人撒巴底。",
    Eng:"",
    Ind:"Yang mengawasi kebun-kebun anggur ialah Simei, orang Rama. Yang mengawasi hasil kebun anggur untuk persediaan anggur ialah Zabdi, orang Syifmi."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:28, Page:1,
    Kor:"게델 사람 바알하난은 평야의 올리브 나무와 뽕나무를 관리하고, 요아스는 기름 곳간을 관리하였다.",
    Chn:"掌管高原橄榄树和桑树的是基第利人巴勒·哈南。掌管油库的是约阿施。",
    Eng:"",
    Ind:"Yang mengawasi pohon-pohon zaitun dan pohon-pohon ara di Daerah Bukit ialah Baal-Hanan, orang Gederi; yang mengawasi persediaan minyak ialah Yoas."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:29, Page:1,
    Kor:"샤론 사람 시드래는 샤론에서 기르는 소 떼를 관리하고, 아들래의 아들 사밧은 골짜기에 있는 소 떼를 관리하였다.",
    Chn:"掌管沙 牧放牛群的是沙 人施提赉。掌管山谷牧养牛群的是亚第赉的儿子沙法。",
    Eng:"",
    Ind:"Yang mengawasi lembu sapi yang digembalakan di tanah Saron ialah Sitrai, orang Saron; yang mengawasi lembu sapi di lembah-lembah ialah Safat bin Adlai."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:30, Page:1,
    Kor:"이스마엘 사람 오빌은 낙타를 관리하고, 메로놋 사람 예드야는 나귀를 관리하고,",
    Chn:"掌管驼群的是以实玛利人阿比勒。掌管驴群的是米 人耶希底亚。掌管羊群的是夏甲人雅悉。",
    Eng:"",
    Ind:"Yang mengawasi unta-unta ialah Obil, orang Ismael; yang mengawasi keledai-keledai betina ialah Yehdeya, orang Meronot."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:31, Page:1,
    Kor:"하갈 사람 야시스는 양 떼를 관리하였다. 이들이 다윗 왕의 재산을 관리하는 사람들이다.",
    Chn:"这都是给大卫王掌管产业的。",
    Eng:"",
    Ind:"Yang mengawasi kambing domba ialah Yazis, orang Hagri. Mereka ini sekalian ialah para pengawas harta milik raja Daud."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:32, Page:1,
    Kor:"<다윗의 개인 고문> ○다윗의 삼촌 요나단은 고문이며 서기관이다. 그는 사리에 밝은 사람이다. 학모니의 아들 여히엘은 왕자들을 돌보았다.",
    Chn:"大卫的叔叔约拿单作谋士；这人有智慧，又作书记。哈摩尼的儿子耶歇作王众子的师傅。",
    Eng:"",
    Ind:"Yonatan, saudara ayah Daud, adalah penasihat; dia seorang cerdas dan ahli kitab. Yehiel bin Hakhmoni membantu anak-anak raja."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:33, Page:1,
    Kor:"아히도벨은 왕의 고문이고, 아렉 사람 후새는 왕의 친구가 되었다.",
    Chn:"亚希多弗也作王的谋士。亚基人户筛作王的陪伴。",
    Eng:"",
    Ind:"Ahitofel adalah penasihat raja; Husai, orang Arki, adalah sahabat raja."
  },
  {Bible:"1Chronicles", Chapter:27, Verse:34, Page:1,
    Kor:"브나야의 아들 여호야다와 아비아달은 아히도벨의 후임자가 되고, 요압은 왕의 군대 총사령관이 되었다.",
    Chn:"亚希多弗之后，有比拿雅的儿子耶何耶大和亚比亚他接续他作谋士。约押作王的元帅。",
    Eng:"",
    Ind:"Yang menggantikan Ahitofel kemudian ialah Yoyada bin Benaya dan Abyatar. Panglima raja ialah Yoab."
  },
]);
