// 열왕기상 6장 · 1Kings 6
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Kings",6,38);
BibleDB.add([
  {Bible:"1Kings", Chapter:6, Verse:1, Page:1,
    Kor:"<솔로몬이 성전을 짓다> 이스라엘 자손이 이집트 땅에서 나온 지 a사백팔십 년, 솔로몬이 이스라엘의 왕이 된 지 사 년째 되는 해 b시브월 곧 둘째 달에, 솔로몬은 주님의 성전을 짓기 시작하였다.(a 칠십인역에는 '사백사십 년' b 양력 사월 중순 이후)",
    Chn:"以色列人出埃及地后四百八十年，所罗门作以色列王第四年西弗月，就是二月，开工建造耶和华的殿。",
    Eng:"In the four hundred and eightieth year after the Israelites had come out of Egypt, in the fourth year of Solomon's reign over Israel, in the month of Ziv, the second month, he began to build the temple of the LORD.",
    Ind:"Dan terjadilah pada tahun keempat ratus delapan puluh sesudah orang Israel keluar dari tanah Mesir, pada tahun keempat sesudah Salomo menjadi raja atas Israel, dalam bulan Ziw, yakni bulan yang kedua, maka Salomo mulai mendirikan rumah bagi TUHAN."
  },
  {Bible:"1Kings", Chapter:6, Verse:2, Page:1,
    Kor:"솔로몬 왕이 주님께 지어 바친 성전은, 길이가 예순 자이고, 너비가 스무 자이고, 높이가 서른 자이다.",
    Chn:"所罗门王为耶和华所建的殿，长六十肘，宽二十肘，高三十肘。",
    Eng:"The temple that King Solomon built for the LORD was sixty cubits long, twenty wide and thirty high.",
    Ind:"Rumah yang didirikan raja Salomo bagi TUHAN itu enam puluh hasta panjangnya dan dua puluh hasta lebarnya dan tiga puluh hasta tingginya."
  },
  {Bible:"1Kings", Chapter:6, Verse:3, Page:1,
    Kor:"성전의 본당 앞에 있는 현관은, 그 길이가 스무 자로서, 그 본당의 너비와 똑같고, 그 너비는 성전 본당 밖으로 열 자를 더 달아냈다.",
    Chn:"殿前的廊子长二十肘，与殿的宽窄一样，阔十肘；",
    Eng:"The portico at the front of the main hall of the temple extended the width of the temple, that is twenty cubits, and projected ten cubits from the front of the temple.",
    Ind:"Balai di sebelah depan ruang besar rumah itu dua puluh hasta panjangnya, menurut lebar rumah itu, dan sepuluh hasta lebarnya ke sebelah depan rumah itu."
  },
  {Bible:"1Kings", Chapter:6, Verse:4, Page:1,
    Kor:"그리고 그는 성전 벽에다가 붙박이창을 만들었는데, 바깥쪽을 안쪽보다 좁게 만들었다.",
    Chn:"又为殿做了严紧的窗棂。",
    Eng:"He made narrow clerestory windows in the temple.",
    Ind:"Dibuatnya juga pada rumah itu jendela-jendela yang rapat bidainya."
  },
  {Bible:"1Kings", Chapter:6, Verse:5, Page:1,
    Kor:"그리고 그 사방에 골방을 만들었다. 성전의 벽 곧 본당 양 옆과 뒤로는, 쭉 돌아가면서 삼층으로 다락을 만들었다.",
    Chn:"靠着殿墙，围着外殿内殿，造了三层旁屋；",
    Eng:"Against the walls of the main hall and inner sanctuary he built a structure around the building, in which there were side rooms.",
    Ind:"Pada dinding rumah itu sekelilingnya didirikannya kamar tambahan, sekeliling ruang besar dan ruang belakang, dan seluruhnya dibuatnya bertingkat-tingkat."
  },
  {Bible:"1Kings", Chapter:6, Verse:6, Page:1,
    Kor:"아래층에 있는 다락은 그 너비가 다섯 자이고, 가운데 층에 있는 다락은 그 너비가 여섯 자이고, 삼 층에 있는 다락은 그 너비가 일곱 자이다. 이것은 성전 바깥으로 돌아가면서 턱을 내어서, 골방의 서까래가 성전의 벽에 박히지 않게 하였다.",
    Chn:"下层宽五肘，中层宽六肘，上层宽七肘。殿外旁屋的梁木搁在殿墙坎上，免得插入殿墙。",
    Eng:"The lowest floor was five cubits wide, the middle floor six cubits and the third floor seven. He made offset ledges around the outside of the temple so that nothing would be inserted into the temple walls.",
    Ind:"Tingkat bawah lima hasta lebarnya, yang tengah enam hasta dan yang ketiga tujuh hasta, sebab telah dibuatnya ceruk-ceruk pada rumah itu sekeliling sebelah luar, sehingga dinding rumah itu tidak usah dilobangi."
  },
  {Bible:"1Kings", Chapter:6, Verse:7, Page:1,
    Kor:"○돌은 채석장에서 잘 다듬어낸 것을 썼으므로, 막상 성전을 지을 때에는, 망치나 정 등, 쇠로 만든 어떠한 연장 소리도, 성전에서는 전혀 들리지 않았다.",
    Chn:"建殿是用山中凿成的石头。建殿的时候，锤子、斧子，和别样铁器的响声都没有听见。",
    Eng:"In building the temple, only blocks dressed at the quarry were used, and no hammer, chisel or any other iron tool was heard at the temple site while it was being built.",
    Ind:"Pada waktu rumah itu didirikan, dipakailah batu-batu yang telah disiapkan di penggalian, sehingga tidak kedengaran palu atau kapak atau sesuatu perkakas besipun selama pembangunan rumah itu."
  },
  {Bible:"1Kings", Chapter:6, Verse:8, Page:1,
    Kor:"○가운데 층에 있는 골방으로 들어가는 문은 성전의 남쪽 측면에 있으며, 나사 모양의 층계를 따라서, 가운데 층으로 올라가게 하였다. 또 가운데 층에서부터 삼층까지도 나사 모양의 층계를 따라서 올라가게 하였다.",
    Chn:"在殿右边当中的旁屋有门，门内有旋螺的楼梯，可以上到第二层，从第二层可以上到第三层。",
    Eng:"The entrance to the lowest floor was on the south side of the temple; a stairway led up to the middle level and from there to the third.",
    Ind:"Pintu tingkat bawah ada pada lambung kanan rumah itu, dan orang naik dengan tangga-tangga pilin ke tingkat tengah dan dari tingkat tengah ke tingkat yang ketiga."
  },
  {Bible:"1Kings", Chapter:6, Verse:9, Page:1,
    Kor:"이렇게 해서 그는 성전 짓기를 완성하였다. 성전의 천장은 백향목 서까래와 널빤지로 덮었다.",
    Chn:"所罗门建殿，安置香柏木的栋梁，又用香柏木板遮盖。",
    Eng:"So he built the temple and completed it, roofing it with beams and cedar planks.",
    Ind:"Setelah ia selesai mendirikan rumah itu, dibuatnyalah langit-langit rumah itu dari bingkai dan pemapan dari kayu aras."
  },
  {Bible:"1Kings", Chapter:6, Verse:10, Page:1,
    Kor:"또한 성전 전체에다가 돌아가면서 높이가 저마다 다섯 자씩 되는 다락을 지었는데, 백향목 들보로 성전에 연결하였다.",
    Chn:"靠着殿所造的旁屋，每层高五肘，香柏木的栋梁搁在殿墙坎上。",
    Eng:"And he built the side rooms all along the temple. The height of each was five cubits, and they were attached to the temple by beams of cedar.",
    Ind:"Dan setelah ia mendirikan kamar tambahan itu pada rumah itu sekeliling, yakni setiap tingkat lima hasta tingginya, maka rumah itu ditutupinya dengan kayu aras."
  },
  {Bible:"1Kings", Chapter:6, Verse:11, Page:1,
    Kor:"○주님께서 솔로몬에게 말씀하셨다.",
    Chn:"耶和华的话临到所罗门说：",
    Eng:"The word of the LORD came to Solomon:",
    Ind:"Kemudian datanglah firman TUHAN kepada Salomo, demikian:"
  },
  {Bible:"1Kings", Chapter:6, Verse:12, Page:1,
    Kor:"\"드디어 네가 성전을 짓기 시작하였구나. 네가 내 법도와 율례를 따르고, 또 나의 계명에 순종하여, 그대로 그것을 지키면, 내가 네 아버지 다윗에게 약속한 바를 네게서 이루겠다.",
    Chn:"「论到你所建的这殿，你若遵行我的律例，谨守我的典章，遵从我的一切诫命，我必向你应验我所应许你父亲大卫的话。",
    Eng:"\"As for this temple you are building, if you follow my decrees, carry out my regulations and keep all my commands and obey them, I will fulfill through you the promise I gave to David your father.",
    Ind:"\"Mengenai rumah yang sedang kaudirikan ini, jika engkau hidup menurut segala ketetapan-Ku dan melakukan segala peraturan-Ku dan tetap mengikuti segala perintah-Ku dan tidak menyimpang dari padanya, maka Aku akan menepati janji-Ku kepadamu yang telah Kufirmankan kepada Daud, ayahmu,"
  },
  {Bible:"1Kings", Chapter:6, Verse:13, Page:1,
    Kor:"또한 나는 이스라엘 자손과 더불어, 그들 가운데서 함께 살겠고, 내 백성 이스라엘을 결코 버리지 않겠다.\"",
    Chn:"我必住在以色列人中间，并不丢弃我民以色列。」",
    Eng:"And I will live among the Israelites and will not abandon my people Israel.\"",
    Ind:"yakni bahwa Aku akan diam di tengah-tengah orang Israel dan tidak hendak meninggalkan umat-Ku Israel.\""
  },
  {Bible:"1Kings", Chapter:6, Verse:14, Page:1,
    Kor:"○솔로몬이 성전 짓기를 마쳤다.",
    Chn:"所罗门建造殿宇。",
    Eng:"So Solomon built the temple and completed it.",
    Ind:"Setelah Salomo selesai mendirikan rumah itu,"
  },
  {Bible:"1Kings", Chapter:6, Verse:15, Page:1,
    Kor:"<성전 내부 장식(대하 3:8-14)> ○성전의 안쪽 벽에는 바닥에서 천장에 닿기까지 벽 전체에 백향목 널빤지를 입히고, 성전의 바닥에는 잣나무 널빤지를 깔았다.",
    Chn:"殿里面用香柏木板贴墙，从地到棚顶都用木板遮蔽，又用松木板铺地。",
    Eng:"He lined its interior walls with cedar boards, paneling them from the floor of the temple to the ceiling, and covered the floor of the temple with planks of pine.",
    Ind:"ia melapisi dinding rumah itu dari dalam dengan papan kayu aras; dari lantai sampai ke balok langit-langit dilapisinya dengan kayu aras, tetapi lantai rumah itu dilapisinya dengan papan kayu sanobar."
  },
  {Bible:"1Kings", Chapter:6, Verse:16, Page:1,
    Kor:"성전 뒤쪽에서 앞쪽으로 스무 자를 재어서, 바닥에서부터 천장의 서까래에 이르기까지 백향목 널빤지로 가로막아서, 성전의 내실 곧 지성소를 만들었다.",
    Chn:"内殿，就是至圣所，长二十肘，从地到棚顶用香柏木板遮蔽。",
    Eng:"He partitioned off twenty cubits at the rear of the temple with cedar boards from floor to ceiling to form within the temple an inner sanctuary, the Most Holy Place.",
    Ind:"Kemudian disekatnyalah dua puluh hasta bagian belakang rumah itu dengan papan kayu aras, dari lantai sampai ke balok-balok; lalu dibuatnyalah ruang itu menjadi ruang belakang, menjadi tempat maha kudus."
  },
  {Bible:"1Kings", Chapter:6, Verse:17, Page:1,
    Kor:"내실 앞에 있는 성전의 외실은, 그 길이가 마흔 자였다.",
    Chn:"内殿前的外殿，长四十肘。",
    Eng:"The main hall in front of this room was forty cubits long.",
    Ind:"Dan empat puluh hasta panjangnya ruang yang di depan ruang belakang itu, yakni ruang besar."
  },
  {Bible:"1Kings", Chapter:6, Verse:18, Page:1,
    Kor:"성전 안쪽 벽에 입힌 백향목에는, 호리병 모양 박과 활짝 핀 꽃 모양을 새겼는데, 전체가 백향목이라서, 석재는 하나도 보이지 않았다.",
    Chn:"殿里一点石头都不显露，一概用香柏木遮蔽；上面刻着野瓜和初开的花。",
    Eng:"The inside of the temple was cedar, carved with gourds and open flowers. Everything was cedar; no stone was to be seen.",
    Ind:"Kayu aras sebelah dalam rumah itu berukirkan buah labu dan bunga mengembang; semuanya ditutupi kayu aras, tidak ada batu kelihatan."
  },
  {Bible:"1Kings", Chapter:6, Verse:19, Page:1,
    Kor:"○성전 안에는, 주님의 언약궤를 놓아 둘 내실을 마련하였다.",
    Chn:"殿里预备了内殿，好安放耶和华的约柜。",
    Eng:"He prepared the inner sanctuary within the temple to set the ark of the covenant of the LORD there.",
    Ind:"Demikianlah dilengkapinya ruang belakang di dalam rumah itu, di sebelah dalam sekali, supaya di sana ditaruh tabut perjanjian TUHAN."
  },
  {Bible:"1Kings", Chapter:6, Verse:20, Page:1,
    Kor:"성전의 내실 곧 지성소는 길이가 스무 자, 너비가 스무 자, 높이가 스무 자이고, 순금으로 입혔으며, 백향목 제단에도 순금으로 입혔다.",
    Chn:"内殿长二十肘，宽二十肘，高二十肘，墙面都贴上精金；又用香柏木做坛，包上精金。",
    Eng:"The inner sanctuary was twenty cubits long, twenty wide and twenty high. He overlaid the inside with pure gold, and he also overlaid the altar of cedar.",
    Ind:"Ruang belakang itu dua puluh hasta panjangnya dan dua puluh hasta lebarnya dan dua puluh hasta tingginya. Ia melapisinya dengan emas kertas, lalu ia membuat mezbah dari kayu aras di depannya."
  },
  {Bible:"1Kings", Chapter:6, Verse:21, Page:1,
    Kor:"솔로몬은 성전 내부도 순금으로 입히고, 지성소 앞에는 금사슬을 드리웠으며, 그 지성소를 모두 금으로 입혔다.",
    Chn:"所罗门用精金贴了殿内的墙，又用金链子挂在内殿前门扇，用金包裹。",
    Eng:"Solomon covered the inside of the temple with pure gold, and he extended gold chains across the front of the inner sanctuary, which was overlaid with gold.",
    Ind:"Sesudah Salomo melapisi rumah itu dari dalam dengan emas kertas, direntangkannyalah tabir pada rantai-rantai emas yang di depan ruang belakang itu, lalu ruang itu dilapisinya dengan emas."
  },
  {Bible:"1Kings", Chapter:6, Verse:22, Page:1,
    Kor:"그래서 그는 온 성전을, 빠진 곳이 전혀 없도록, 금으로 입혔다. 심지어는 성소에 속하여 있는 제단들까지도, 모두 금으로 입혔다.",
    Chn:"全殿都贴上金子，直到贴完；内殿前的坛，也都用金包裹。",
    Eng:"So he overlaid the whole interior with gold. He also overlaid with gold the altar that belonged to the inner sanctuary.",
    Ind:"Seluruh rumah itu dilapisinya dengan emas, ya rumah itu seluruhnya; juga seluruh mezbah yang di depan ruang belakang itu dilapisinya dengan emas."
  },
  {Bible:"1Kings", Chapter:6, Verse:23, Page:1,
    Kor:"○그는 지성소 안에 올리브 나무로 두 개의 그룹을 만들었는데, 높이는 각각 열 자이다.",
    Chn:"他用橄榄木做两个基路伯，各高十肘，安在内殿。",
    Eng:"In the inner sanctuary he made a pair of cherubim of olive wood, each ten cubits high.",
    Ind:"Selanjutnya di dalam ruang belakang itu dibuatnya dua kerub dari kayu minyak, masing-masing sepuluh hasta tingginya."
  },
  {Bible:"1Kings", Chapter:6, Verse:24, Page:1,
    Kor:"그 한 그룹의 한쪽 날개는 다섯 자, 그룹의 다른 쪽 날개 역시 다섯 자이다. 그 날개의 한쪽 끝으로부터 다른 쪽 날개의 끝까지는 열 자이다.",
    Chn:"这一个基路伯有两个翅膀，各长五肘，从这翅膀尖到那翅膀尖共有十肘；",
    Eng:"One wing of the first cherub was five cubits long, and the other wing five cubits--ten cubits from wing tip to wing tip.",
    Ind:"Sayap yang satu dari kerub itu lima hasta panjangnya dan sayap yang lain juga lima hasta, sehingga dari ujung sayap yang satu sampai ke ujung sayap yang lain sepuluh hasta panjangnya."
  },
  {Bible:"1Kings", Chapter:6, Verse:25, Page:1,
    Kor:"두 번째 그룹도 열 자이며, 두 그룹이 같은 치수와 같은 모양이었다.",
    Chn:"那一个基路伯的两个翅膀也是十肘，两个基路伯的尺寸、形象都是一样。",
    Eng:"The second cherub also measured ten cubits, for the two cherubim were identical in size and shape.",
    Ind:"Juga kerub yang kedua adalah sepuluh hasta panjangnya; dan kedua kerub itu sama ukuran dan sama potongan badannya."
  },
  {Bible:"1Kings", Chapter:6, Verse:26, Page:1,
    Kor:"이쪽 그룹의 높이도 열 자이고, 저쪽 것도 열 자이다.",
    Chn:"这基路伯高十肘，那基路伯也是如此。",
    Eng:"The height of each cherub was ten cubits.",
    Ind:"Tinggi kerub yang satu sepuluh hasta dan demikian juga kerub yang kedua."
  },
  {Bible:"1Kings", Chapter:6, Verse:27, Page:1,
    Kor:"솔로몬은 그 그룹들을 지성소의 가장 깊숙한 곳에 놓았다. 그룹들의 날개는 펴져 있어서, 이쪽 그룹의 한 날개가 저쪽 벽에 닿았고, 저쪽 그룹의 한 날개는 이쪽 벽에 닿았다. 그리고 지성소의 중앙에서 그들의 다른 날개들은 서로 닿아 있었다.",
    Chn:"他将两个基路伯安在内殿里；基路伯的翅膀是张开的，这基路伯的一个翅膀挨着这边的墙，那基路伯的一个翅膀挨着那边的墙，里边的两个翅膀在殿中间彼此相接；",
    Eng:"He placed the cherubim inside the innermost room of the temple, with their wings spread out. The wing of one cherub touched one wall, while the wing of the other touched the other wall, and their wings touched each other in the middle of the room.",
    Ind:"Maka ditaruhnyalah kerub-kerub itu di tengah-tengah ruang yang di sebelah dalam sekali; kerub-kerub itu mengembangkan sayapnya, sehingga kerub yang satu menyentuh dinding dengan sayapnya dan kerub yang kedua menyentuh dinding yang lain, sedang sayap-sayap yang arah ke tengah rumah itu bersentuhan ujungnya."
  },
  {Bible:"1Kings", Chapter:6, Verse:28, Page:1,
    Kor:"그는 이 그룹에도 금으로 입혔다.",
    Chn:"又用金子包裹二基路伯。",
    Eng:"He overlaid the cherubim with gold.",
    Ind:"Dan kerub-kerub itu dilapisinya dengan emas."
  },
  {Bible:"1Kings", Chapter:6, Verse:29, Page:1,
    Kor:"○그는 성전의 지성소와 외실의 벽으로 돌아가면서, 그룹의 형상과 종려나무와 활짝 핀 꽃 모양을 새겼다.",
    Chn:"内殿、外殿周围的墙上都刻着基路伯、棕树，和初开的花。",
    Eng:"On the walls all around the temple, in both the inner and outer rooms, he carved cherubim, palm trees and open flowers.",
    Ind:"Dan pada segala dinding rumah itu berkeliling ia mengukir gambar kerub, pohon korma dan bunga mengembang, baik di ruang sebelah dalam maupun di ruang sebelah luar."
  },
  {Bible:"1Kings", Chapter:6, Verse:30, Page:1,
    Kor:"또 그 성전의 지성소와 외실 마루에도 금으로 입혔다.",
    Chn:"内殿、外殿的地板都贴上金子。",
    Eng:"He also covered the floors of both the inner and outer rooms of the temple with gold.",
    Ind:"Juga lantai rumah itu dilapisinya dengan emas, baik di ruang sebelah dalam maupun di ruang sebelah luar."
  },
  {Bible:"1Kings", Chapter:6, Verse:31, Page:1,
    Kor:"○지성소 어귀에는 올리브 나무로 문을 두 짝 만들고, 그 인방과 문설주는 오각형으로 만들었다.",
    Chn:"又用橄榄木制造内殿的门扇、门楣、门框；门口有墙的五分之一。",
    Eng:"For the entrance of the inner sanctuary he made doors of olive wood with five-sided jambs.",
    Ind:"Sebagai pintu masuk ke ruang belakang dibuatnyalah pintu dari kayu minyak; ambang dan tiangnya merupakan segi lima."
  },
  {Bible:"1Kings", Chapter:6, Verse:32, Page:1,
    Kor:"그리고 올리브 나무로 만든 문 두 짝에는, 그룹의 형상과 종려나무와 활짝 핀 꽃 모양을 새겼는데, 그룹 모양과 종려나무 모양 위에도 금으로 입혔다.",
    Chn:"在橄榄木做的两门扇上刻着基路伯、棕树，和初开的花，都贴上金子。",
    Eng:"And on the two olive wood doors he carved cherubim, palm trees and open flowers, and overlaid the cherubim and palm trees with beaten gold.",
    Ind:"Pada kedua daun pintu yang dari kayu minyak itu ia mengukir gambar kerub, pohon korma dan bunga mengembang, kemudian dilapisinya dengan emas; juga pada kerub dan pada pohon korma itu disalutkannya emas."
  },
  {Bible:"1Kings", Chapter:6, Verse:33, Page:1,
    Kor:"또 올리브 나무로 본당의 외실 어귀를 만들었는데, 그 문설주는 사각형으로 만들었다.",
    Chn:"又用橄榄木制造外殿的门框，门口有墙的四分之一。",
    Eng:"In the same way he made four-sided jambs of olive wood for the entrance to the main hall.",
    Ind:"Demikian juga untuk pintu masuk ke ruang besar itu dibuatnya tiang-tiang dari kayu minyak yang merupakan segi empat;"
  },
  {Bible:"1Kings", Chapter:6, Verse:34, Page:1,
    Kor:"그리고 잣나무로 만든 두 개의 문이 있는데, 한 쪽의 문도 두 부분으로 접히고, 다른 문도 두 부분으로 접히게 되어 있었다.",
    Chn:"用松木做门两扇。这扇分两扇，是折叠的；那扇分两扇，也是折叠的。",
    Eng:"He also made two pine doors, each having two leaves that turned in sockets.",
    Ind:"dan dua pintu dari kayu sanobar; kedua papan pintu dari pintu yang satu dapat dilipat dan demikian juga kedua papan pintu yang lain."
  },
  {Bible:"1Kings", Chapter:6, Verse:35, Page:1,
    Kor:"그 위에 그룹들과 종려나무와 활짝 핀 꽃 모양을 새겼는데, 그 위에 고루고루 금을 입혔다.",
    Chn:"上面刻着基路伯、棕树，和初开的花，都用金子贴了。",
    Eng:"He carved cherubim, palm trees and open flowers on them and overlaid them with gold hammered evenly over the carvings.",
    Ind:"Lalu diukirnyalah padanya kerub, pohon korma dan bunga mengembang, kemudian dilapisinya pintu itu dengan emas pipih pada gambar ukiran itu."
  },
  {Bible:"1Kings", Chapter:6, Verse:36, Page:1,
    Kor:"○또 성전 앞에다가 안뜰을 만들었는데, 안뜰 벽은 잘 다듬은 돌 세 켜와 두꺼운 백향목 판자 한 켜로 벽을 쳤다.",
    Chn:"他又用凿成的石头三层、香柏木一层建筑内院。",
    Eng:"And he built the inner courtyard of three courses of dressed stone and one course of trimmed cedar beams.",
    Ind:"Ia mendirikan tembok pelataran dalam dari tiga jajar batu pahat dan dari satu jajar balok kayu aras."
  },
  {Bible:"1Kings", Chapter:6, Verse:37, Page:1,
    Kor:"○주님의 성전 기초를 놓은 것은 솔로몬의 통치 제 사년 시브월이고,",
    Chn:"所罗门 在位第四年西弗月，立了耶和华殿的根基。",
    Eng:"The foundation of the temple of the LORD was laid in the fourth year, in the month of Ziv.",
    Ind:"Dalam tahun yang keempat, dalam bulan Ziw, diletakkanlah dasar rumah TUHAN,"
  },
  {Bible:"1Kings", Chapter:6, Verse:38, Page:1,
    Kor:"성전이 그 세밀한 부분까지 설계한 대로 완공된 것은 제 십일년 c불월 곧 여덟째 달이다. 솔로몬이 성전을 건축하는 데는 일곱 해가 걸렸다.(c 양력 시월 중순 이후)",
    Chn:"到十一年布勒月，就是八月，殿和一切属殿的都按着样式造成。他建殿的工夫共有七年。",
    Eng:"In the eleventh year in the month of Bul, the eighth month, the temple was finished in all its details according to its specifications. He had spent seven years building it.",
    Ind:"dan dalam tahun yang kesebelas, dalam bulan Bul, yaitu bulan kedelapan, selesailah rumah itu dengan segala bagian-bagiannya dan sesuai dengan segala rancangannya; jadi tujuh tahun lamanya ia mendirikan rumah itu."
  },
]);
