// 열왕기상 11장 · 1Kings 11
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Kings",11,43);
BibleDB.add([
  {Bible:"1Kings", Chapter:11, Verse:1, Page:1,
    Kor:"<솔로몬이 하나님에게서 돌아서다> 솔로몬 왕은 외국 여자들을 좋아하였다. 이집트의 바로의 딸 말고도, 모압 사람과 암몬 사람과 에돔 사람과 시돈 사람과 헷 사람에게서, 많은 외국 여자를 후궁으로 맞아들였다.",
    Chn:"所罗门王在法老的女儿之外，又宠爱许多外邦女子，就是摩押女子、亚扪女子、以东女子、西顿女子、赫人女子。",
    Eng:"King Solomon, however, loved many foreign women besides Pharaoh's daughter--Moabites, Ammonites, Edomites, Sidonians and Hittites.",
    Ind:"Adapun raja Salomo mencintai banyak perempuan asing. Di samping anak Firaun ia mencintai perempuan-perempuan Moab, Amon, Edom, Sidon dan Het,"
  },
  {Bible:"1Kings", Chapter:11, Verse:2, Page:1,
    Kor:"주님께서 일찍이 이 여러 민족을 두고, 이스라엘 자손에게 경고하신 일이 있다. \"너희는 그들과 결혼을 하고자 해서도 안 되고, 그들이 청혼하여 오더라도 받아들여서는 안 된다. 분명히 그들은 너희의 마음을, 그들이 믿는 신에게로 기울어지게 할 것이다\" 하고 말씀하셨다. 그런데도 솔로몬은 외국 여자들을 좋아하였으므로, 마음을 돌리지 못하였다.",
    Chn:"论到这些国的人，耶和华曾晓谕以色列人说：「你们不可与她们往来相通，因为她们必诱惑你们的心去随从她们的神。」所罗门却恋爱这些女子。",
    Eng:"They were from nations about which the LORD had told the Israelites, \"You must not intermarry with them, because they will surely turn your hearts after their gods.\" Nevertheless, Solomon held fast to them in love.",
    Ind:"padahal tentang bangsa-bangsa itu TUHAN telah berfirman kepada orang Israel: \"Janganlah kamu bergaul dengan mereka dan merekapun janganlah bergaul dengan kamu, sebab sesungguhnya mereka akan mencondongkan hatimu kepada allah-allah mereka.\" Hati Salomo telah terpaut kepada mereka dengan cinta."
  },
  {Bible:"1Kings", Chapter:11, Verse:3, Page:1,
    Kor:"그는 자그마치 칠백 명의 후궁과 삼백 명의 첩을 두었는데, 그 아내들이 그의 마음을 사로잡았다.",
    Chn:"所罗门有妃七百，都是公主；还有嫔三百。这些妃嫔诱惑他的心。",
    Eng:"He had seven hundred wives of royal birth and three hundred concubines, and his wives led him astray.",
    Ind:"Ia mempunyai tujuh ratus isteri dari kaum bangsawan dan tiga ratus gundik; isteri-isterinya itu menarik hatinya dari pada TUHAN."
  },
  {Bible:"1Kings", Chapter:11, Verse:4, Page:1,
    Kor:"솔로몬이 늙으니, 그 아내들이 솔로몬을 꾀어서, 다른 신들을 따르게 하였다. 그래서 솔로몬은, 자기의 주 하나님께 그의 아버지 다윗만큼은 완전하지 못하였다.",
    Chn:"所罗门年老的时候，他的妃嫔诱惑他的心去随从别神，不效法他父亲大卫诚诚实实地顺服耶和华—他的　神。",
    Eng:"As Solomon grew old, his wives turned his heart after other gods, and his heart was not fully devoted to the LORD his God, as the heart of David his father had been.",
    Ind:"Sebab pada waktu Salomo sudah tua, isteri-isterinya itu mencondongkan hatinya kepada allah-allah lain, sehingga ia tidak dengan sepenuh hati berpaut kepada TUHAN, Allahnya, seperti Daud, ayahnya."
  },
  {Bible:"1Kings", Chapter:11, Verse:5, Page:1,
    Kor:"솔로몬이 시돈 사람의 여신 아스다롯과 암몬 사람의 우상 a밀곰을 따라가서,(a 또는 '몰렉')",
    Chn:"因为所罗门随从西顿人的女神亚斯她录和亚扪人可憎的神米勒公。",
    Eng:"He followed Ashtoreth the goddess of the Sidonians, and Molech the detestable god of the Ammonites.",
    Ind:"Demikianlah Salomo mengikuti Asytoret, dewi orang Sidon, dan mengikuti Milkom, dewa kejijikan sembahan orang Amon,"
  },
  {Bible:"1Kings", Chapter:11, Verse:6, Page:1,
    Kor:"주님 앞에서 악행을 하였다. 그의 아버지 다윗은 주님께 충성을 다하였으나, 솔로몬은 그러하지 못하였다.",
    Chn:"所罗门行耶和华眼中看为恶的事，不效法他父亲大卫专心顺从耶和华。",
    Eng:"So Solomon did evil in the eyes of the LORD; he did not follow the LORD completely, as David his father had done.",
    Ind:"dan Salomo melakukan apa yang jahat di mata TUHAN, dan ia tidak dengan sepenuh hati mengikuti TUHAN, seperti Daud, ayahnya."
  },
  {Bible:"1Kings", Chapter:11, Verse:7, Page:1,
    Kor:"솔로몬은 예루살렘 동쪽 산에 모압의 혐오스러운 우상 그모스를 섬기는 산당을 짓고, 암몬 자손의 혐오스러운 우상 몰렉을 섬기는 산당도 지었는데,",
    Chn:"所罗门为摩押可憎的神基抹和亚扪人可憎的神摩洛，在耶路撒冷对面的山上建筑邱坛。",
    Eng:"On a hill east of Jerusalem, Solomon built a high place for Chemosh the detestable god of Moab, and for Molech the detestable god of the Ammonites.",
    Ind:"Pada waktu itu Salomo mendirikan bukit pengorbanan bagi Kamos, dewa kejijikan sembahan orang Moab, di gunung di sebelah timur Yerusalem dan bagi Molokh, dewa kejijikan sembahan bani Amon."
  },
  {Bible:"1Kings", Chapter:11, Verse:8, Page:1,
    Kor:"그는 그의 외국인 아내들이 하자는 대로, 그들의 신들에게 향을 피우며, 제사를 지냈다.",
    Chn:"他为那些向自己的神烧香献祭的外邦女子，就是他娶来的妃嫔也是这样行。",
    Eng:"He did the same for all his foreign wives, who burned incense and offered sacrifices to their gods.",
    Ind:"Demikian juga dilakukannya bagi semua isterinya, orang-orang asing itu, yang mempersembahkan korban ukupan dan korban sembelihan kepada allah-allah mereka."
  },
  {Bible:"1Kings", Chapter:11, Verse:9, Page:1,
    Kor:"○이와 같이, 솔로몬의 마음이 주 이스라엘의 하나님을 떠났으므로, 주님께서 솔로몬에게 진노하셨다. 주님께서는 두 번씩이나 솔로몬에게 나타나셔서,",
    Chn:"耶和华向所罗门发怒，因为他的心偏离向他两次显现的耶和华—以色列的　神。",
    Eng:"The LORD became angry with Solomon because his heart had turned away from the LORD, the God of Israel, who had appeared to him twice.",
    Ind:"Sebab itu TUHAN menunjukkan murka-Nya kepada Salomo, sebab hatinya telah menyimpang dari pada TUHAN, Allah Israel, yang telah dua kali menampakkan diri kepadanya,"
  },
  {Bible:"1Kings", Chapter:11, Verse:10, Page:1,
    Kor:"다른 신들을 따라가지 말라고 당부하셨지만, 솔로몬은 주님께서 하신 말씀에 순종하지 않았다.",
    Chn:"耶和华曾吩咐他不可随从别神，他却没有遵守耶和华所吩咐的。",
    Eng:"Although he had forbidden Solomon to follow other gods, Solomon did not keep the LORD'S command.",
    Ind:"dan yang telah memerintahkan kepadanya dalam hal ini supaya jangan mengikuti allah-allah lain, akan tetapi ia tidak berpegang pada yang diperintahkan TUHAN."
  },
  {Bible:"1Kings", Chapter:11, Verse:11, Page:1,
    Kor:"그러므로 주님께서 솔로몬에게 이렇게 말씀하셨다. \"네가 이러한 일을 하였고, 내 언약과 내가 너에게 명령한 내 법규를 지키지 아니하였으니, 내가 반드시 네게서 왕국을 떼어서, 네 신하에게 주겠다.",
    Chn:"所以耶和华对他说：「你既行了这事，不遵守我所吩咐你守的约和律例，我必将你的国夺回，赐给你的臣子。",
    Eng:"So the LORD said to Solomon, \"Since this is your attitude and you have not kept my covenant and my decrees, which I commanded you, I will most certainly tear the kingdom away from you and give it to one of your subordinates.",
    Ind:"Lalu berfirmanlah TUHAN kepada Salomo: \"Oleh karena begitu kelakuanmu, yakni engkau tidak berpegang pada perjanjian dan segala ketetapan-Ku yang telah Kuperintahkan kepadamu, maka sesungguhnya Aku akan mengoyakkan kerajaan itu dari padamu dan akan memberikannya kepada hambamu."
  },
  {Bible:"1Kings", Chapter:11, Verse:12, Page:1,
    Kor:"다만 네가 사는 날 동안에는, 네 아버지 다윗을 보아서 그렇게 하지 않겠지만, 네 아들 대에 이르러서는, 내가 이 나라를 갈라 놓겠다.",
    Chn:"然而，因你父亲大卫的缘故，我不在你活着的日子行这事，必从你儿子的手中将国夺回。",
    Eng:"Nevertheless, for the sake of David your father, I will not do it during your lifetime. I will tear it out of the hand of your son.",
    Ind:"Hanya, pada waktu hidupmu ini Aku belum mau melakukannya oleh karena Daud, ayahmu; dari tangan anakmulah Aku akan mengoyakkannya."
  },
  {Bible:"1Kings", Chapter:11, Verse:13, Page:1,
    Kor:"그러나 이 나라를 갈라서, 다 남에게 내주지는 않고, 나의 종 다윗과 내가 선택한 예루살렘을 생각해서, 한 지파만은 네 아들에게 주겠다.\"",
    Chn:"只是我不将全国夺回，要因我仆人大卫和我所选择的耶路撒冷，还留一支派给你的儿子。」",
    Eng:"Yet I will not tear the whole kingdom from him, but will give him one tribe for the sake of David my servant and for the sake of Jerusalem, which I have chosen.\"",
    Ind:"Namun demikian, kerajaan itu tidak seluruhnya akan Kukoyakkan dari padanya, satu suku akan Kuberikan kepada anakmu oleh karena hamba-Ku Daud dan oleh karena Yerusalem yang telah Kupilih.\""
  },
  {Bible:"1Kings", Chapter:11, Verse:14, Page:1,
    Kor:"<솔로몬의 적> ○이렇게 해서, 주님께서는, 에돔 출신으로 에돔에 살고 있는 왕손 하닷을 일으키셔서, 솔로몬의 대적이 되게 하셨다.",
    Chn:"耶和华使以东人哈达兴起，作所罗门的敌人；他是以东王的后裔。",
    Eng:"Then the LORD raised up against Solomon an adversary, Hadad the Edomite, from the royal line of Edom.",
    Ind:"Kemudian TUHAN membangkitkan seorang lawan Salomo, yakni Hadad, orang Edom; ia dari keturunan raja Edom."
  },
  {Bible:"1Kings", Chapter:11, Verse:15, Page:1,
    Kor:"전에 다윗이 에돔에 있을 때에, 군사령관 요압 장군이 살해당한 사람들을 묻으려고 그 곳으로 내려갔다가, 에돔에 있는 모든 남자를 다 쳐죽인 일이 있다.",
    Chn:"先前大卫攻击以东，元帅约押上去葬埋阵亡的人，将以东的男丁都杀了。",
    Eng:"Earlier when David was fighting with Edom, Joab the commander of the army, who had gone up to bury the dead, had struck down all the men in Edom.",
    Ind:"Sesudah Daud memukul kalah orang Edom, maka panglima Yoab pergi menguburkan orang-orang yang mati terbunuh, lalu menewaskan semua laki-laki di Edom;"
  },
  {Bible:"1Kings", Chapter:11, Verse:16, Page:1,
    Kor:"요압은 온 이스라엘 사람과 함께, 에돔에 있는 모든 남자를 다 진멸할 때까지, 여섯 달 동안 거기에 머물러 있었다.",
    Chn:"约押和以色列众人在以东住了六个月，直到将以东的男丁尽都剪除。",
    Eng:"Joab and all the Israelites stayed there for six months, until they had destroyed all the men in Edom.",
    Ind:"enam bulan lamanya Yoab diam di sana dengan seluruh Israel, sampai dilenyapkannya semua laki-laki di Edom."
  },
  {Bible:"1Kings", Chapter:11, Verse:17, Page:1,
    Kor:"그러나 하닷은 자기 아버지의 신하이던 에돔 사람들을 데리고서, 이집트로 도망하였다. 그 때에 하닷은 아직 어린 소년이었다.",
    Chn:"那时哈达还是幼童；他和他父亲的臣仆，几个以东人逃往埃及。",
    Eng:"But Hadad, still only a boy, fled to Egypt with some Edomite officials who had served his father.",
    Ind:"Tetapi Hadad melarikan diri bersama-sama dengan beberapa orang Edom dari pegawai-pegawai ayahnya, dan mengungsi ke Mesir; adapun Hadad itu masih sangat muda."
  },
  {Bible:"1Kings", Chapter:11, Verse:18, Page:1,
    Kor:"그들은 미디안에서 출발하여 바란에 이르렀고, 그 곳에서 장정 몇 사람을 데리고 이집트로 내려가서, 이집트 왕 바로에게로 갔다. 이집트 왕 바로는 그에게, 집과 얼마만큼의 음식을 내주고, 땅도 주었다.",
    Chn:"他们从米甸起行，到了巴兰；从巴兰带着几个人来到埃及见埃及王法老；法老为他派定粮食，又给他房屋田地。",
    Eng:"They set out from Midian and went to Paran. Then taking men from Paran with them, they went to Egypt, to Pharaoh king of Egypt, who gave Hadad a house and land and provided him with food.",
    Ind:"Mereka berangkat dari Midian, lalu sampai ke Paran; mereka membawa beberapa orang dari Paran, lalu mereka sampai ke Mesir kepada Firaun, raja Mesir. Ia ini memberikan rumah kepada Hadad, menentukan belanjanya dan menyerahkan sebidang tanah kepadanya."
  },
  {Bible:"1Kings", Chapter:11, Verse:19, Page:1,
    Kor:"하닷이 바로의 눈에 들었으므로, 바로는 자기의 처제 곧 다브네스 왕비의 동생과 하닷을 결혼하게 하였다.",
    Chn:"哈达在法老面前大蒙恩惠，以致法老将王后答比匿的妹子赐他为妻。",
    Eng:"Pharaoh was so pleased with Hadad that he gave him a sister of his own wife, Queen Tahpenes, in marriage.",
    Ind:"Hadad demikian disayangi Firaun, sehingga diberikannya kepadanya seorang isteri, yakni adik isterinya sendiri, adik permaisuri Tahpenes."
  },
  {Bible:"1Kings", Chapter:11, Verse:20, Page:1,
    Kor:"다브네스의 동생은 아들 그누밧을 낳았는데, 다브네스는 그를 바로의 궁 안에서 양육하였으므로, 그누밧은 바로의 궁에서 바로의 아들들과 함께 자랐다.",
    Chn:"答比匿的妹子给哈达生了一个儿子，名叫基努拔。答比匿使基努拔在法老的宫里断奶，基努拔就与法老的众子一同住在法老的宫里。",
    Eng:"The sister of Tahpenes bore him a son named Genubath, whom Tahpenes brought up in the royal palace. There Genubath lived with Pharaoh's own children.",
    Ind:"Lalu adik Tahpenes itu melahirkan baginya seorang anak laki-laki, Genubat namanya, dan Tahpenes menyapih dia di istana Firaun, sehingga Genubat ada di istana Firaun di tengah-tengah anak-anak Firaun sendiri."
  },
  {Bible:"1Kings", Chapter:11, Verse:21, Page:1,
    Kor:"그 뒤에 하닷은, 다윗과 군사령관 요압 장군이 죽었다는 것을 이집트에서 듣고서, 고국 땅으로 돌아가게 허락해 달라고 바로에게 요청하였다.",
    Chn:"哈达在埃及听见大卫与他列祖同睡，元帅约押也死了，就对法老说：「求王容我回本国去。」",
    Eng:"While he was in Egypt, Hadad heard that David rested with his fathers and that Joab the commander of the army was also dead. Then Hadad said to Pharaoh, \"Let me go, that I may return to my own country.\"",
    Ind:"Ketika didengar Hadad di Mesir, bahwa Daud telah mendapat perhentian bersama-sama dengan nenek moyangnya dan bahwa panglima Yoab sudah mati juga, maka berkatalah Hadad kepada Firaun: \"Biarkanlah aku pergi ke negeriku.\""
  },
  {Bible:"1Kings", Chapter:11, Verse:22, Page:1,
    Kor:"그러자 바로는 그에게 \"나와 함께 있는 것이 무엇이 부족해서, 그렇게도 고국으로 가려고만 하오?\" 하면서 말렸다. 그러나 하닷은, 부족한 것은 아무것도 없지만, 보내 달라고 간청하였다.",
    Chn:"法老对他说：「你在我这里有什么缺乏，你竟要回你本国去呢？」他回答说：「我没有缺乏什么，只是求王容我回去。」",
    Eng:"\"What have you lacked here that you want to go back to your own country?\" Pharaoh asked. \"Nothing,\" Hadad replied, \"but do let me go!\"",
    Ind:"Lalu bertanyalah Firaun kepadanya: \"Tetapi kekurangan apakah engkau padaku ini, maka engkau tiba-tiba berniat pergi ke negerimu?\" Jawabnya: \"Aku tidak kekurangan apapun, namun demikian, biarkanlah juga aku pergi.\""
  },
  {Bible:"1Kings", Chapter:11, Verse:23, Page:1,
    Kor:"○하나님께서는 솔로몬의 또 다른 대적자로서, 엘리아다의 아들 르손을 일으키셨다. 그는 자기가 섬기던 소바 왕 하닷에셀에게서 도망한 사람이다.",
    Chn:"神又使以利亚大的儿子利逊兴起，作所罗门的敌人。他先前逃避主人琐巴王哈大底谢。",
    Eng:"And God raised up against Solomon another adversary, Rezon son of Eliada, who had fled from his master, Hadadezer king of Zobah.",
    Ind:"Allah membangkitkan pula seorang lawan Salomo, yakni Rezon bin Elyada, yang telah melarikan diri dari tuannya, yakni Hadadezer, raja Zoba."
  },
  {Bible:"1Kings", Chapter:11, Verse:24, Page:1,
    Kor:"다윗이 소바 사람들을 죽일 때에, 그는 사람들을 모으고, 그 모은 무리의 두목이 되어서, 다마스쿠스로 가서 살다가, 마침내 다마스쿠스를 다스리는 왕이 되었다.",
    Chn:"大卫击杀琐巴人的时候，利逊招聚了一群人，自己作他们的头目，往大马士革居住，在那里作王。",
    Eng:"He gathered men around him and became the leader of a band of rebels when David destroyed the forces of Zobah; the rebels went to Damascus, where they settled and took control.",
    Ind:"Ia mengumpulkan orang-orang, lalu menjadi kepala gerombolan. Ketika Daud hendak membunuh mereka, maka pergilah mereka ke Damsyik; mereka diam di sana dan di situlah mereka mengangkat Rezon menjadi raja."
  },
  {Bible:"1Kings", Chapter:11, Verse:25, Page:1,
    Kor:"르손은 솔로몬의 일생 동안에 이스라엘의 대적자가 되었다. 그렇지 않아도, 솔로몬은 하닷에게 시달리고 있었는데, 엎친 데 덮친 격으로, 르손에게도 시달렸다. 르손은 시리아를 다스리는 왕이 되어서, 계속하여 이스라엘을 괴롭혔다.",
    Chn:"所罗门活着的时候，哈达为患之外，利逊也作以色列的敌人。他恨恶以色列人，且作了亚兰人的王。",
    Eng:"Rezon was Israel's adversary as long as Solomon lived, adding to the trouble caused by Hadad. So Rezon ruled in Aram and was hostile toward Israel.",
    Ind:"Dialah yang menjadi lawan Israel sepanjang umur Salomo; ia mendatangkan malapetaka sama seperti Hadad. Ia muak akan orang Israel dan menjadi raja atas Aram."
  },
  {Bible:"1Kings", Chapter:11, Verse:26, Page:1,
    Kor:"<여로보암에게 하신 하나님의 약속> ○느밧의 아들 여로보암은 에브라임 족의 스레다 사람으로서, 한동안은 솔로몬의 신하였다. 이 사람까지도 솔로몬 왕에게 반기를 들어서 대적하였다. 그의 어머니는 과부 스루아이다.",
    Chn:"所罗门的臣仆、尼八的儿子耶罗波安也举手攻击王。他是以法莲支派的洗利达人，他母亲是寡妇，名叫洗鲁阿。",
    Eng:"Also, Jeroboam son of Nebat rebelled against the king. He was one of Solomon's officials, an Ephraimite from Zeredah, and his mother was a widow named Zeruah.",
    Ind:"Juga Yerobeam bin Nebat, seorang Efraim dari Zereda, seorang pegawai Salomo, nama ibunya Zerua, seorang janda, memberontak terhadap raja."
  },
  {Bible:"1Kings", Chapter:11, Verse:27, Page:1,
    Kor:"그가 왕에게 반기를 든 사정은 이러하다. 솔로몬이 밀로를 건축하고, 그의 아버지 다윗 성의 갈라진 성벽 틈을 수리할 때이다.",
    Chn:"他举手攻击王的缘故，乃由先前所罗门建造米罗，修补他父亲大卫城的破口。",
    Eng:"Here is the account of how he rebelled against the king: Solomon had built the supporting terraces and had filled in the gap in the wall of the city of David his father.",
    Ind:"Inilah alasannya, mengapa ia memberontak terhadap raja: Salomo mendirikan Milo, dan ia menutup tembusan tembok kota Daud, ayahnya."
  },
  {Bible:"1Kings", Chapter:11, Verse:28, Page:1,
    Kor:"그 사람 여로보암은 능력이 있는 용사였다. 솔로몬은, 이 젊은이가 일 처리하는 것을 보고는, 그에게 요셉 가문의 부역을 감독하게 하였다.",
    Chn:"耶罗波安是大有才能的人。所罗门见这少年人殷勤，就派他监管约瑟家的一切工程。",
    Eng:"Now Jeroboam was a man of standing, and when Solomon saw how well the young man did his work, he put him in charge of the whole labor force of the house of Joseph.",
    Ind:"Yerobeam adalah seorang tangkas; ketika Salomo melihat, bahwa orang muda itu seorang yang rajin bekerja, maka ditempatkannyalah dia mengawasi semua pekerja wajib dari keturunan Yusuf."
  },
  {Bible:"1Kings", Chapter:11, Verse:29, Page:1,
    Kor:"그 무렵에 여로보암이 예루살렘에서 나아오다가, 길에서 실로의 아히야 예언자와 마주쳤다. 아히야는 새 옷을 걸치고 있었고, 들에는 그들 둘만 있었는데,",
    Chn:"一日，耶罗波安出了耶路撒冷，示罗人先知亚希雅在路上遇见他；亚希雅身上穿着一件新衣。他们二人在田野，以外并无别人。",
    Eng:"About that time Jeroboam was going out of Jerusalem, and Ahijah the prophet of Shiloh met him on the way, wearing a new cloak. The two of them were alone out in the country,",
    Ind:"Pada waktu itu, ketika Yerobeam keluar dari Yerusalem, nabi Ahia, orang Silo itu, mendatangi dia di jalan dengan berselubungkan kain baru. Dan hanya mereka berdua ada di padang."
  },
  {Bible:"1Kings", Chapter:11, Verse:30, Page:1,
    Kor:"아히야는 그가 입고 있는 새 옷을 찢어서, 열두 조각을 내고,",
    Chn:"亚希雅将自己穿的那件新衣撕成十二片，",
    Eng:"and Ahijah took hold of the new cloak he was wearing and tore it into twelve pieces.",
    Ind:"Ahia memegang kain baru yang di badannya, lalu dikoyakkannya menjadi dua belas koyakan;"
  },
  {Bible:"1Kings", Chapter:11, Verse:31, Page:1,
    Kor:"여로보암에게 말하였다. ○\"열 조각은 그대가 가지십시오. 주 이스라엘의 하나님께서 그대에게 이렇게 말씀하셨습니다. '자, 내가 솔로몬의 왕국을 찢어서, 열 지파를 너에게 준다.",
    Chn:"对耶罗波安说：「你可以拿十片。耶和华—以色列的　神如此说：『我必将国从所罗门手里夺回，将十个支派赐给你。（",
    Eng:"Then he said to Jeroboam, \"Take ten pieces for yourself, for this is what the LORD, the God of Israel, says: 'See, I am going to tear the kingdom out of Solomon's hand and give you ten tribes.",
    Ind:"dan ia berkata kepada Yerobeam: \"Ambillah bagimu sepuluh koyakan, sebab beginilah firman TUHAN, Allah Israel: Sesungguhnya Aku akan mengoyakkan kerajaan itu dari tangan Salomo dan akan memberikan kepadamu sepuluh suku."
  },
  {Bible:"1Kings", Chapter:11, Verse:32, Page:1,
    Kor:"그리고 한 지파는 내 종 다윗을 생각해서, 그리고 이스라엘의 모든 지파 가운데서 내가 선택한 성읍 예루살렘을 생각해서, 솔로몬이 다스리도록 그대로 남겨 둔다.",
    Chn:"我因仆人大卫和我在以色列众支派中所选择的耶路撒冷城的缘故，仍给所罗门留一个支派。）",
    Eng:"But for the sake of my servant David and the city of Jerusalem, which I have chosen out of all the tribes of Israel, he will have one tribe.",
    Ind:"Tetapi satu suku akan tetap padanya oleh karena hamba-Ku Daud dan oleh karena Yerusalem, kota yang Kupilih itu dari segala suku Israel."
  },
  {Bible:"1Kings", Chapter:11, Verse:33, Page:1,
    Kor:"b솔로몬은 나를 버리고, 시돈 사람의 여신인 아스다롯과 모압의 신 그모스와 암몬 자손의 신 밀곰에게 절하며, 그의 아버지 다윗과는 달리, 내 앞에서 바르게 살지도 않고, 법도와 율례를 지키지도 않았지만,(b 칠십인역과 불가타와 시리아어역을 따름. 히, '그들이 나를 버리고……')",
    Chn:"因为他离弃我，敬拜西顿人的女神亚斯她录、摩押的神基抹，和亚扪人的神米勒公，没有遵从我的道，行我眼中看为正的事，守我的律例典章，像他父亲大卫一样。",
    Eng:"I will do this because they have forsaken me and worshiped Ashtoreth the goddess of the Sidonians, Chemosh the god of the Moabites, and Molech the god of the Ammonites, and have not walked in my ways, nor done what is right in my eyes, nor kept my statutes and laws as David, Solomon's father, did.",
    Ind:"Sebabnya ialah karena ia telah meninggalkan Aku dan sujud menyembah kepada Asytoret, dewi orang Sidon, kepada Kamos, allah orang Moab dan kepada Milkom, allah bani Amon, dan ia tidak hidup menurut jalan yang Kutunjukkan dengan melakukan apa yang benar di mata-Ku dan dengan tetap mengikuti segala ketetapan dan peraturan-Ku, seperti Daud, ayahnya."
  },
  {Bible:"1Kings", Chapter:11, Verse:34, Page:1,
    Kor:"내가 택한 나의 종 다윗이 내 명령과 법규를 지킨 것을 생각해서, 솔로몬이 살아 있는 동안에는, 그 온 왕국을 그의 손에서 빼앗지 아니하고, 그가 계속해서 통치하도록 할 것이다.",
    Chn:"但我不从他手里将全国夺回；使他终身为君，是因我所拣选的仆人大卫谨守我的诫命律例。",
    Eng:"\"'But I will not take the whole kingdom out of Solomon's hand; I have made him ruler all the days of his life for the sake of David my servant, whom I chose and who observed my commands and statutes.",
    Ind:"Bukan dari tangannya akan Kuambil seluruh kerajaan itu; Aku akan membiarkan dia tetap menjadi raja seumur hidupnya, oleh karena hamba-Ku Daud yang telah Kupilih dan yang tetap mengikuti segala perintah dan ketetapan-Ku."
  },
  {Bible:"1Kings", Chapter:11, Verse:35, Page:1,
    Kor:"그렇지만 그의 아들 대에 가서는, 내가 그 나라를 빼앗아서, 그 가운데서 열 지파를 너에게 주고,",
    Chn:"我必从他儿子的手里将国夺回，以十个支派赐给你，",
    Eng:"I will take the kingdom from his son's hands and give you ten tribes.",
    Ind:"Tetapi dari tangan anaknyalah Aku akan mengambil kerajaan itu dan akan memberikannya kepadamu, yakni sepuluh suku."
  },
  {Bible:"1Kings", Chapter:11, Verse:36, Page:1,
    Kor:"한 지파는 솔로몬의 아들에게 주어서 다스리게 할 것이다. 그러면 그가, 내 이름을 기리도록 내가 선택한 도성 예루살렘에서 다스릴 것이고, 내 종 다윗에게 준 불씨가 꺼지지 않을 것이다.",
    Chn:"还留一个支派给他的儿子，使我仆人大卫在我所选择立我名的耶路撒冷城里，在我面前长有灯光。",
    Eng:"I will give one tribe to his son so that David my servant may always have a lamp before me in Jerusalem, the city where I chose to put my Name.",
    Ind:"Dan kepada anaknya akan Kuberikan satu suku, supaya hamba-Ku Daud selalu mempunyai keturunan di hadapan-Ku di Yerusalem, kota yang Kupilih bagi-Ku supaya nama-Ku tinggal di sana."
  },
  {Bible:"1Kings", Chapter:11, Verse:37, Page:1,
    Kor:"여로보암아, 내가 너를 이스라엘의 왕으로 삼겠다. 너는 네가 원하는 모든 지역을 다스릴 것이다.",
    Chn:"我必拣选你，使你照心里一切所愿的，作王治理以色列。",
    Eng:"However, as for you, I will take you, and you will rule over all that your heart desires; you will be king over Israel.",
    Ind:"Maka engkau ini akan Kuambil, supaya engkau memerintah atas segala yang dikehendaki hatimu dan menjadi raja atas Israel."
  },
  {Bible:"1Kings", Chapter:11, Verse:38, Page:1,
    Kor:"네가, 나의 종 다윗이 한 것과 같이, 내가 명령한 모든 것을 따르고, 내가 가르친 대로 살며, 내 율례와 명령을 지켜서, 내가 보는 앞에서 바르게 살면, 내가 너와 함께 있을 것이며, 내가 다윗 왕조를 견고하게 세운 것 같이, 네 왕조도 견고하게 세워서, 이스라엘을 너에게 맡기겠다.",
    Chn:"你若听从我一切所吩咐你的，遵行我的道，行我眼中看为正的事，谨守我的律例诫命，像我仆人大卫所行的，我就与你同在，为你立坚固的家，像我为大卫所立的一样，将以色列人赐给你。",
    Eng:"If you do whatever I command you and walk in my ways and do what is right in my eyes by keeping my statutes and commands, as David my servant did, I will be with you. I will build you a dynasty as enduring as the one I built for David and will give Israel to you.",
    Ind:"Dan jika engkau mendengarkan segala yang Kuperintahkan kepadamu dan hidup menurut jalan yang Kutunjukkan dan melakukan apa yang benar di mata-Ku dengan tetap mengikuti segala ketetapan dan perintah-Ku seperti yang telah dilakukan oleh hamba-Ku Daud, maka Aku akan menyertai engkau dan Aku akan membangunkan bagimu suatu keluarga yang teguh seperti yang Kubangunkan bagi Daud, dan Aku akan memberikan orang Israel kepadamu."
  },
  {Bible:"1Kings", Chapter:11, Verse:39, Page:1,
    Kor:"솔로몬이 지은 죄 때문에 내가 다윗 자손에게 이러한 형벌을 줄 것이지만, 항상 그러하지는 않을 것이다.'\"",
    Chn:"我必因所罗门所行的使大卫后裔受患难，但不至于永远。』」",
    Eng:"I will humble David's descendants because of this, but not forever.'\"",
    Ind:"Dan untuk itu Aku akan merendahkan keturunan Daud, tetapi bukan untuk selamanya.\""
  },
  {Bible:"1Kings", Chapter:11, Verse:40, Page:1,
    Kor:"○솔로몬이 여로보암을 죽이려고 하니, 여로보암은 일어나서 이집트 왕 시삭에게로 도망하여, 솔로몬이 죽을 때까지 이집트에 머물러 있었다.",
    Chn:"所罗门因此想要杀耶罗波安。耶罗波安却起身逃往埃及；到了埃及王示撒那里，就住在埃及，直到所罗门死了。",
    Eng:"Solomon tried to kill Jeroboam, but Jeroboam fled to Egypt, to Shishak the king, and stayed there until Solomon's death.",
    Ind:"Lalu Salomo berikhtiar membunuh Yerobeam, tetapi Yerobeam bangkit dan melarikan diri ke Mesir, kepada Sisak, raja Mesir, dan di Mesirlah ia tinggal sampai Salomo mati."
  },
  {Bible:"1Kings", Chapter:11, Verse:41, Page:1,
    Kor:"<솔로몬이 죽다(대하 9:29-31)> ○솔로몬의 나머지 행적과 그가 한 모든 일과 그의 지혜는 모두 '솔로몬 왕의 실록'에 기록되어 있다.",
    Chn:"所罗门其余的事，凡他所行的和他的智慧都写在所罗门记上。",
    Eng:"As for the other events of Solomon's reign--all he did and the wisdom he displayed--are they not written in the book of the annals of Solomon?",
    Ind:"Selebihnya dari riwayat Salomo dan segala yang dilakukannya dan hikmatnya, bukankah semuanya itu tertulis dalam kitab riwayat Salomo?"
  },
  {Bible:"1Kings", Chapter:11, Verse:42, Page:1,
    Kor:"솔로몬은 예루살렘에서 사십 년 동안 온 이스라엘을 다스렸다.",
    Chn:"所罗门在耶路撒冷作以色列众人的王共四十年。",
    Eng:"Solomon reigned in Jerusalem over all Israel forty years.",
    Ind:"Lamanya Salomo memerintah di Yerusalem atas seluruh Israel ialah empat puluh tahun."
  },
  {Bible:"1Kings", Chapter:11, Verse:43, Page:1,
    Kor:"솔로몬은 죽어서, 그의 아버지 다윗의 성에 묻혔다. 그의 아들 르호보암이 그의 뒤를 이어, 왕이 되었다.",
    Chn:"所罗门与他列祖同睡，葬在他父亲大卫的城里。他儿子罗波安接续他作王。",
    Eng:"Then he rested with his fathers and was buried in the city of David his father. And Rehoboam his son succeeded him as king.",
    Ind:"Kemudian Salomo mendapat perhentian bersama-sama dengan nenek moyangnya, dan ia dikuburkan di kota Daud, ayahnya. Maka Rehabeam, anaknya, menjadi raja menggantikan dia."
  },
]);
