// 열왕기상 7장 · 1Kings 7
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Kings",7,51);
BibleDB.add([
  {Bible:"1Kings", Chapter:7, Verse:1, Page:1,
    Kor:"<솔로몬의 궁전> 솔로몬은, 자기의 궁을 건축하기 시작하여 그것을 완공하는 데, 열세 해가 걸렸다.",
    Chn:"所罗门为自己建造宫室，十三年方才造成；",
    Eng:"It took Solomon thirteen years, however, to complete the construction of his palace.",
    Ind:"Salomo mendirikan istananya sampai tiga belas tahun lamanya, barulah selesai seluruh istananya itu."
  },
  {Bible:"1Kings", Chapter:7, Verse:2, Page:1,
    Kor:"그는 '레바논 수풀 궁'을 지었는데, 그 길이는 백 자이고, 그 너비는 쉰 자이고, 그 높이는 서른 자이다. 백향목 기둥을 네 줄로 세우고, 그 기둥 위에는 백향목 서까래를 얹었다.",
    Chn:"又建造黎巴嫩林宫，长一百肘，宽五十肘，高三十肘，有香柏木柱三行，柱上有香柏木柁梁。",
    Eng:"He built the Palace of the Forest of Lebanon a hundred cubits long, fifty wide and thirty high, with four rows of cedar columns supporting trimmed cedar beams.",
    Ind:"Ia mendirikan gedung \"Hutan Libanon\", seratus hasta panjangnya dan lima puluh hasta lebarnya dan tiga puluh hasta tingginya, disangga oleh tiga jajar tiang kayu aras dengan ganja kayu aras di atas tiang itu."
  },
  {Bible:"1Kings", Chapter:7, Verse:3, Page:1,
    Kor:"지붕에는, 한 줄에 열다섯 개씩, 모두 마흔다섯 개의 서까래를 대고, 백향목 판자로 덮었다.",
    Chn:"其上以香柏木为盖，每行柱子十五根，共有四十五根。",
    Eng:"It was roofed with cedar above the beams that rested on the columns--forty-five beams, fifteen to a row.",
    Ind:"Gedung itu ditutup dari atas dengan langit-langit kayu aras, di atas balok-balok melintang yang disangga oleh tiang-tiang itu, empat puluh lima jumlahnya, yakni lima belas sejajar."
  },
  {Bible:"1Kings", Chapter:7, Verse:4, Page:1,
    Kor:"창틀은 세 줄로 되어 있고, 그 창문들은 세 단으로 되어서, 서로 마주 보고 있었다.",
    Chn:"有窗户三层，窗与窗相对。",
    Eng:"Its windows were placed high in sets of three, facing each other.",
    Ind:"Ada pula tiga jajar jendela berbidai, jendela berhadapan dengan jendela, tiga kali."
  },
  {Bible:"1Kings", Chapter:7, Verse:5, Page:1,
    Kor:"문과 문설주는 모두 네모난 모양이고, 창문은 창문끼리 세 줄로 마주 보고 있었다.",
    Chn:"所有的门框都是厚木见方的，有窗户三层，窗与窗相对。",
    Eng:"All the doorways had rectangular frames; they were in the front part in sets of three, facing each other.",
    Ind:"Dan semua pintu dan jendela segi empat bangunnya; jendela berhadapan dengan jendela, tiga kali."
  },
  {Bible:"1Kings", Chapter:7, Verse:6, Page:1,
    Kor:"○그는 기둥들을 나란히 세워 주랑을 만들었다. 그것은 길이가 쉰 자이고 너비가 서른 자인, 벽이 없는 복도였다. 주랑 앞에는 현관이 있고, 현관 앞에 또 기둥들이 있고, 그 기둥들 위에는 차양이 걸려 있었다.",
    Chn:"并建造有柱子的廊子，长五十肘，宽三十肘；在这廊前又有廊子，廊外有柱子和台阶。",
    Eng:"He made a colonnade fifty cubits long and thirty wide. In front of it was a portico, and in front of that were pillars and an overhanging roof.",
    Ind:"Ia membuat juga Balai Saka, lima puluh hasta panjangnya dan tiga puluh hasta lebarnya, dengan di sebelah depannya sebuah balai lagi yang bertiang dan bertangga di sebelah depannya."
  },
  {Bible:"1Kings", Chapter:7, Verse:7, Page:1,
    Kor:"○또 그는 '옥좌실' 곧 '재판정'을 짓고, 그 마루를 모두 백향목으로 깔았다.",
    Chn:"又建造一廊，其中设立审判的座位，这廊从地到顶都用香柏木遮蔽。",
    Eng:"He built the throne hall, the Hall of Justice, where he was to judge, and he covered it with cedar from floor to ceiling.",
    Ind:"Dibuatnya juga Balai Singgasana, tempat ia memutuskan hukum, balai pengadilan, yang ditutupi dengan kayu aras dari lantai sampai ke balok langit-langit."
  },
  {Bible:"1Kings", Chapter:7, Verse:8, Page:1,
    Kor:"○자기가 있을 왕궁은, '재판정' 뒤에 있는 다른 뜰에 지었는데, 그 건축 양식은 다른 건물들의 건축 양식과 서로 비슷하였다. 또 솔로몬은 이것과 같은 궁전을, 그가 결혼하여 아내로 맞아들인 바로의 딸에게도 지어 주었다.",
    Chn:"廊后院内有所罗门住的宫室；工作与这工作相同。所罗门又为所娶法老的女儿建造一宫，做法与这廊子一样。",
    Eng:"And the palace in which he was to live, set farther back, was similar in design. Solomon also made a palace like this hall for Pharaoh's daughter, whom he had married.",
    Ind:"Dan gedung kediamannya sendiri, di pelataran yang lain, lebih ke sebelah dalam lagi dari balai itu, adalah sama buatannya. Dan bagi anak Firaun, yang diambil Salomo menjadi isterinya, dibuatnya juga sebuah gedung sama dengan balai itu."
  },
  {Bible:"1Kings", Chapter:7, Verse:9, Page:1,
    Kor:"○왕궁을 포함한 모든 건물은, 치수를 재어서 깎은 귀한 돌, 앞뒤를 톱으로 자른 값진 돌들로 지었는데, 기초에서부터 갓돌까지, 또 바깥은 물론이고, 건물 안의 큰 뜰까지, 다 그러한 재료를 써서 지었다.",
    Chn:"建造这一切所用的石头都是宝贵的，是按着尺寸凿成的，是用锯里外锯齐的；从根基直到檐石，从外头直到大院，都是如此。",
    Eng:"All these structures, from the outside to the great courtyard and from foundation to eaves, were made of blocks of high-grade stone cut to size and trimmed with a saw on their inner and outer faces.",
    Ind:"Tembok dari semuanya ini dibuat dari batu yang mahal-mahal, yang sesuai dengan ukuran batu pahat digergaji dengan gergaji dari sebelah dalam dan dari sebelah luar, dari dasar sampai ke atas, dan juga dari tembok luar sampai kepada tembok pelataran besar."
  },
  {Bible:"1Kings", Chapter:7, Verse:10, Page:1,
    Kor:"기초를 놓을 때에도 값진 큰 돌들을 놓았는데, 어떤 돌은 열 자나 되고, 어떤 돌은 여덟 자나 되었다.",
    Chn:"根基是宝贵的大石头，有长十肘的，有长八肘的；",
    Eng:"The foundations were laid with large stones of good quality, some measuring ten cubits and some eight.",
    Ind:"Bahkan dasar gedung-gedung itu dari batu yang mahal-mahal, batu yang besar-besar, batu yang sepuluh hasta dan batu yang delapan hasta."
  },
  {Bible:"1Kings", Chapter:7, Verse:11, Page:1,
    Kor:"기초를 다진 다음에는, 그 위에다가 치수를 재어서, 잘 다듬은 값진 돌과 백향목으로 벽을 올렸다.",
    Chn:"上面有香柏木和按着尺寸凿成宝贵的石头。",
    Eng:"Above were high-grade stones, cut to size, and cedar beams.",
    Ind:"Di bagian atas ada batu yang mahal-mahal, berukuran batu pahat, dan kayu aras juga."
  },
  {Bible:"1Kings", Chapter:7, Verse:12, Page:1,
    Kor:"왕궁 뜰의 담이나, 주님의 성전 안뜰의 담이나, 성전의 어귀 현관의 담은, 모두 잘 다듬은 돌 세 켜와 두꺼운 백향목 판자 한 켜를 놓아서 쌓았다.",
    Chn:"大院周围有凿成的石头三层、香柏木一层，都照耶和华殿的内院和殿廊的样式。",
    Eng:"The great courtyard was surrounded by a wall of three courses of dressed stone and one course of trimmed cedar beams, as was the inner courtyard of the temple of the LORD with its portico.",
    Ind:"Sekeliling pelataran besar ada tembok dari tiga jajar batu pahat dan satu jajar balok kayu aras; demikian juga sekeliling pelataran dalam rumah TUHAN dan balainya."
  },
  {Bible:"1Kings", Chapter:7, Verse:13, Page:1,
    Kor:"<후람의 임무> ○솔로몬 왕은 사람을 보내어서, 두로에서 a후람을 불러 왔는데,(a 히, '히람')",
    Chn:"所罗门王差遣人往泰尔去，将户兰召了来。",
    Eng:"King Solomon sent to Tyre and brought Huram,",
    Ind:"Kemudian raja Salomo menyuruh orang menjemput Hiram dari Tirus."
  },
  {Bible:"1Kings", Chapter:7, Verse:14, Page:1,
    Kor:"그는 납달리 지파에 속한 과부의 아들이다. 그의 아버지는 두로 사람으로서, 놋쇠 대장장이이다. 그는, 놋쇠를 다루는 일에는, 뛰어난 지혜와 기술과 전문 지식을 두루 갖춘 사람이었다. 그가 솔로몬 왕에게 불려와서, 공사를 거의 도맡아 하였다.",
    Chn:"他是拿弗他利支派中一个寡妇的儿子，他父亲是泰尔人，作铜匠的。户兰满有智慧、聪明、技能，善于各样铜作。他来到所罗门王那里，做王一切所要做的。",
    Eng:"whose mother was a widow from the tribe of Naphtali and whose father was a man of Tyre and a craftsman in bronze. Huram was highly skilled and experienced in all kinds of bronze work. He came to King Solomon and did all the work assigned to him.",
    Ind:"Dia adalah anak seorang janda dari suku Naftali, sedang ayahnya orang Tirus, tukang tembaga; ia penuh dengan keahlian, pengertian dan pengetahuan untuk melakukan segala pekerjaan tembaga; ia datang kepada raja Salomo, lalu melakukan segala pekerjaan itu bagi raja."
  },
  {Bible:"1Kings", Chapter:7, Verse:15, Page:1,
    Kor:"<두 놋쇠 기둥(대하 3:15-17)> ○그는 두 개의 놋쇠 기둥을 만들었다. b둘 다 열여덟 자 높이에, 열두 자 둘레였다.(b 히, '한 기둥은 높이가 열여덟 자, 또 다른 기둥은 둘레가 열두 자였다')",
    Chn:"他制造两根铜柱，每根高十八肘，围十二肘；",
    Eng:"He cast two bronze pillars, each eighteen cubits high and twelve cubits around, by line.",
    Ind:"Ia membentuk dua tiang tembaga, tinggi tiang yang satu delapan belas hasta dan dapat dililit oleh tali yang dua belas hasta panjangnya; tiang yang kedua demikian juga."
  },
  {Bible:"1Kings", Chapter:7, Verse:16, Page:1,
    Kor:"그는 또, 그 두 기둥의 꼭대기에 얹어 놓을 두 개의 기둥 머리를, 놋을 녹여 부어서 만들었는데, 그 기둥 머리는 둘 다 꼭 같이 높이가 다섯 자이다.",
    Chn:"又用铜铸了两个柱顶安在柱上，各高五肘。",
    Eng:"He also made two capitals of cast bronze to set on the tops of the pillars; each capital was five cubits high.",
    Ind:"Dibuatnya juga dua ganja untuk ditaruh di kepala tiang-tiang itu, dari tembaga tuangan, tinggi ganja yang satu lima hasta dan tinggi ganja yang kedua lima hasta."
  },
  {Bible:"1Kings", Chapter:7, Verse:17, Page:1,
    Kor:"기둥 꼭대기에 얹은 기둥 머리를 장식하려고, 바둑판 모양으로 얽은 그물과 사슬 모양의 고리를 각각 일곱 개씩 만들었다.",
    Chn:"柱顶上有装修的网子和拧成的链索，每顶七个。",
    Eng:"A network of interwoven chains festooned the capitals on top of the pillars, seven for each capital.",
    Ind:"Dibuatnya pula dua jala-jala untuk ganja yang ada di kepala tiang itu--jala-jala itu semacam kawat berpilin, semacam untaian rantai--satu jala-jala untuk ganja yang satu dan satu jala-jala untuk ganja yang kedua."
  },
  {Bible:"1Kings", Chapter:7, Verse:18, Page:1,
    Kor:"이렇게 두 기둥을 만들고 나서, 기둥 꼭대기에 얹은 기둥 머리를 장식하였다. 놋쇠로 석류를 만들고, 그물에다가 석류를 두 줄로 늘어뜨려서 기둥 머리를 장식하였다.",
    Chn:"网子周围有两行石榴遮盖柱顶，两个柱顶都是如此。",
    Eng:"He made pomegranates in two rows encircling each network to decorate the capitals on top of the pillars. He did the same for each capital.",
    Ind:"Kemudian dibuatnya juga buah-buah delima, dua jajar berkeliling pada jala-jala yang satu, untuk menutupi ganja yang di ujung tiang itu, dan demikian pula dibuatnya pada ganja yang kedua."
  },
  {Bible:"1Kings", Chapter:7, Verse:19, Page:1,
    Kor:"기둥 꼭대기에 얹은 기둥 머리는 그 높이가 넉 자이다. 나리꽃 모양으로 만들었는데,",
    Chn:"廊子的柱顶径四肘，刻着百合花。",
    Eng:"The capitals on top of the pillars in the portico were in the shape of lilies, four cubits high.",
    Ind:"Dan ganja yang di kepala tiang dekat balai depan itu berbentuk bunga bakung, tingginya empat hasta,"
  },
  {Bible:"1Kings", Chapter:7, Verse:20, Page:1,
    Kor:"사슬 장식 위에 둥그렇게 돌출된 부분에다가 얹었다. 기둥 머리에는 놋쇠로 만든 석류 이백 개가 둥그렇게 열을 지어 있었다. 다른 기둥 머리도 마찬가지였다.",
    Chn:"两柱顶的鼓肚上挨着网子，各有两行石榴环绕，两行共有二百。",
    Eng:"On the capitals of both pillars, above the bowl-shaped part next to the network, were the two hundred pomegranates in rows all around.",
    Ind:"yakni ganja-ganja yang di atas kedua tiang itu, di sebelah atas sekali, lewat jala-jala yang meliliti perut ganja itu; dan buah-buah delima ada dua ratus berjajar berkeliling pada ganja yang satu, demikian juga pada yang kedua."
  },
  {Bible:"1Kings", Chapter:7, Verse:21, Page:1,
    Kor:"○a후람은 이렇게 해서 만든 두 기둥을 성전의 현관에다가 세웠다. 오른쪽 기둥을 세우고, 그 이름을 c야긴이라고 하였고, 왼쪽 기둥을 세우고, 그 이름을 d보아스라고 하였다.(a 히, '히람' c '그가 세우다' d '그에게 힘이 있다')",
    Chn:"他将两根柱子立在殿廊前头：右边立一根，起名叫雅斤；左边立一根，起名叫波阿斯。",
    Eng:"He erected the pillars at the portico of the temple. The pillar to the south he named Jakin and the one to the north Boaz.",
    Ind:"Kemudian tiang-tiang itu didirikannya dekat balai ruang besar. Ketika ia mendirikan tiang kanan, ia menamainya Yakhin; ketika ia mendirikan tiang kiri, ia menamainya Boas."
  },
  {Bible:"1Kings", Chapter:7, Verse:22, Page:1,
    Kor:"그 다음에 기둥들의 꼭대기에는 나리꽃 모양으로 만든 기둥 머리를 얹었는데, 이렇게 해서, a후람은 기둥 세우는 일을 마쳤다.(a 히, '히람')",
    Chn:"在柱顶上刻着百合花。这样，造柱子的工就完毕了。",
    Eng:"The capitals on top were in the shape of lilies. And so the work on the pillars was completed.",
    Ind:"Dan setelah bentukan bunga bakung itu ditaruh di kepala tiang-tiang itu, maka siaplah pekerjaan membuat tiang-tiang itu."
  },
  {Bible:"1Kings", Chapter:7, Verse:23, Page:1,
    Kor:"<놋쇠 물통(대하 4:2-5)> ○그 다음에 a후람은 놋쇠를 부어서 바다 모양 물통을 만들었는데, 그 바다 모양 물통은, 지름이 열 자, 높이가 다섯 자, 둘레가 서른 자이고, 둥근 모양을 한 물통이었다.(a 히, '히람')",
    Chn:"他又铸一个铜海，样式是圆的，高五肘，径十肘，围三十肘。",
    Eng:"He made the Sea of cast metal, circular in shape, measuring ten cubits from rim to rim and five cubits high. It took a line of thirty cubits to measure around it.",
    Ind:"Kemudian dibuatnyalah \"laut\" tuangan yang sepuluh hasta dari tepi ke tepi, bundar keliling, lima hasta tingginya, dan yang dapat dililit berkeliling oleh tali yang tiga puluh hasta panjangnya."
  },
  {Bible:"1Kings", Chapter:7, Verse:24, Page:1,
    Kor:"그 가장자리 아래로는, 돌아가면서, 놋쇠로 만든 호리병 모양의 박이 있는데, 이것들은 놋쇠를 부어서 바다 모양 물통을 만들 때에, 두 줄로 부어서 만든 것이다.",
    Chn:"在海边之下，周围有野瓜的样式；每肘十瓜，共有两行，是铸海的时候铸上的。",
    Eng:"Below the rim, gourds encircled it--ten to a cubit. The gourds were cast in two rows in one piece with the Sea.",
    Ind:"Dan di bawah tepinya ada gambar buah labu yang mengelilinginya sama sekali, sepuluh dalam sehasta, merangkum \"laut\" itu berkeliling; labu itu dua jajar, dituang setuangan dengan bejana itu."
  },
  {Bible:"1Kings", Chapter:7, Verse:25, Page:1,
    Kor:"또한 열두 마리의 놋쇠 황소가 바다 모양 물통을 떠받치고 있는데, 세 마리는 북쪽을 바라보고, 세 마리는 서쪽을 바라보고, 세 마리는 남쪽을 바라보고, 세 마리는 동쪽을 바라보고 서 있었고, 등으로 바다 모형을 떠받치고 있었다. 황소는 모두 엉덩이를 안쪽으로 향하고 있었다.",
    Chn:"有十二只铜牛驮海：三只向北，三只向西，三只向南，三只向东；海在牛上，牛尾都向内。",
    Eng:"The Sea stood on twelve bulls, three facing north, three facing west, three facing south and three facing east. The Sea rested on top of them, and their hindquarters were toward the center.",
    Ind:"\"Laut\" itu menumpang di atas dua belas lembu, tiga menghadap ke utara dan tiga menghadap ke barat, tiga menghadap ke selatan dan tiga menghadap ke timur; \"laut\" itu menumpang di atasnya, sedang segala buntut lembu itu menuju ke dalam."
  },
  {Bible:"1Kings", Chapter:7, Verse:26, Page:1,
    Kor:"그 놋쇠로 된 바다 모양 물통의 두께는 손 너비 만하였다. 그 테두리는 나리꽃 봉오리 모양으로, 잔의 테두리처럼 둥글게 만들었다. 그 용량은 물을 이천 말 정도 담을 수 있는 것이었다.",
    Chn:"海厚一掌，边如杯边，又如百合花，可容二千罢特。",
    Eng:"It was a handbreadth in thickness, and its rim was like the rim of a cup, like a lily blossom. It held two thousand baths.",
    Ind:"Tebal \"laut\" itu setapak tangan dan tepinya serupa tepi piala, seperti bunga bakung yang berkembang. \"Laut\" itu dapat memuat dua ribu bat air."
  },
  {Bible:"1Kings", Chapter:7, Verse:27, Page:1,
    Kor:"<놋쇠 받침대와 대야> ○그는 또 놋으로 받침대를 열 개 만들었는데, 받침대마다 길이가 넉 자, 너비가 넉 자, 높이가 석 자이다.",
    Chn:"他用铜制造十个盆座，每座长四肘，宽四肘，高三肘。",
    Eng:"He also made ten movable stands of bronze; each was four cubits long, four wide and three high.",
    Ind:"Selanjutnya dibuatnya sepuluh kereta penopang dari tembaga, satu kereta empat hasta panjangnya, empat hasta lebarnya dan tiga hasta tingginya."
  },
  {Bible:"1Kings", Chapter:7, Verse:28, Page:1,
    Kor:"받침대의 구조는 다음과 같다. 받침대는 판자 테두리를 가지고 있고, 그 테두리는 틀 사이에 끼어 있었다.",
    Chn:"座的造法是这样：四面都有心子，心子在边子当中，",
    Eng:"This is how the stands were made: They had side panels attached to uprights.",
    Ind:"Beginilah bentuk kereta penopang itu: ada papan penutupnya dan papan itu diapit oleh bingkai."
  },
  {Bible:"1Kings", Chapter:7, Verse:29, Page:1,
    Kor:"틀 사이에 낀 판자 테두리 위에다가는, 사자와 소와 그룹을 그려 넣었다. 사자와 소의 위 아래로는 화환 무늬를 새겨 넣었다.",
    Chn:"心子上有狮子和牛，并基路伯；边上有小座，狮子和牛以下有垂下的璎珞。",
    Eng:"On the panels between the uprights were lions, bulls and cherubim--and on the uprights as well. Above and below the lions and bulls were wreaths of hammered work.",
    Ind:"Dan pada papan penutup yang diapit oleh bingkai itu ada singa, lembu dan kerub, dan demikian juga pada bingkai itu; di sebelah atas dan di sebelah bawah singa dan lembu itu ada karangan-karangan bunga yang tergantung."
  },
  {Bible:"1Kings", Chapter:7, Verse:30, Page:1,
    Kor:"그리고 각 받침대에는, 네 개의 놋쇠 바퀴와 놋쇠 축과 네 개의 다리를 달았다. 그 네 개의 다리는 놋쇠 대야 아래에서 어깨 모양의 받침두리를 괴고 있었다. 이 받침두리들은 화환 무늬의 맞은쪽에서 녹여 부어서 만든 것이었다.",
    Chn:"每盆座有四个铜轮和铜轴。小座的四角上在盆以下，有铸成的盆架，其旁都有璎珞。",
    Eng:"Each stand had four bronze wheels with bronze axles, and each had a basin resting on four supports, cast with wreaths on each side.",
    Ind:"Pada satu kereta penopang ada empat roda tembaga dengan poros tembaga; dan pada keempat penjurunya ada sangga untuk menyangga bejana pembasuhan; sangga-sangga itu dituang dan di sebelah luar setiap sangga ada karangan bunga."
  },
  {Bible:"1Kings", Chapter:7, Verse:31, Page:1,
    Kor:"그 아가리는 받침두리 안에서 위로 한 자 높이로 솟아나와 있었는데, 그 아가리는 지름이 한 자 반으로, 둥글게 받침두리와 같은 모양으로 되어 있고, 그 아가리에는 돌아가면서, 새긴 것이 있었다. 그러나 그 테두리 판자들은 네모지고, 둥글지 않았다.",
    Chn:"小座高一肘，口是圆的，仿佛座的样式，径一肘半，在口上有雕工，心子是方的，不是圆的。",
    Eng:"On the inside of the stand there was an opening that had a circular frame one cubit deep. This opening was round, and with its basework it measured a cubit and a half. Around its opening there was engraving. The panels of the stands were square, not round.",
    Ind:"Dan mulut kereta penopang itu ada di sebelah dalam sangga-sangga itu, menonjol ke atas satu hasta; mulutnya itu bundar, buatannya sebagai tumpuan, dan dalamnya satu setengah hasta; juga pada mulutnya itu ada ukiran, tetapi papan-papan penutupnya empat persegi, jadi tidak bundar."
  },
  {Bible:"1Kings", Chapter:7, Verse:32, Page:1,
    Kor:"그 테두리 판자의 아래에는 네 개의 바퀴를 달고, 바퀴의 축은 받침대 안에다 넣었다. 바퀴 하나의 높이는 한 자 반이었다.",
    Chn:"四个轮子在心子以下，轮轴与座相连，每轮高一肘半。",
    Eng:"The four wheels were under the panels, and the axles of the wheels were attached to the stand. The diameter of each wheel was a cubit and a half.",
    Ind:"Keempat roda itu ada di bawah papan penutup, dan tangan-tangan roda itu ada pada kereta penopang itu; dan tinggi satu roda ialah satu setengah hasta."
  },
  {Bible:"1Kings", Chapter:7, Verse:33, Page:1,
    Kor:"그 바퀴의 구조는 말이 끄는 전차 바퀴의 구조와 같았다. 바퀴의 축과 테두리와 바퀴살과 그 축의 통은 모두 놋쇠를 녹여 부어서 만든 것이었다.",
    Chn:"轮的样式如同车轮；轴、辋、辐、毂都是铸的。",
    Eng:"The wheels were made like chariot wheels; the axles, rims, spokes and hubs were all of cast metal.",
    Ind:"Dan buatan roda itu seperti buatan roda kereta; tetapi tangan-tangannya, lingkarnya, jari-jarinya dan napnya, semuanya tuangan."
  },
  {Bible:"1Kings", Chapter:7, Verse:34, Page:1,
    Kor:"그리고 받침대의 네 귀퉁이에는, 어깨 모양의 받침두리가 네 개 붙어 있는데, 그 받침대에서 받침두리가 잇따라 나와 있었다.",
    Chn:"每座四角上都有盆架，是与座一同铸成的。",
    Eng:"Each stand had four handles, one on each corner, projecting from the stand.",
    Ind:"Keempat sangga pada keempat sudut setiap kereta penopang adalah seiras dengan kereta itu."
  },
  {Bible:"1Kings", Chapter:7, Verse:35, Page:1,
    Kor:"받침대 꼭대기에는 반 자 높이의 테두리가 둥글게 둘려 있고, 또 받침대의 아래에는 바퀴축인 버팀대와 테두리 판자들이 연결되어 있었다.",
    Chn:"座上有圆架，高半肘；座上有撑子和心子，是与座一同铸的。",
    Eng:"At the top of the stand there was a circular band half a cubit deep. The supports and panels were attached to the top of the stand.",
    Ind:"Dan di sebelah atas kereta penopang itu ada leher bundar berkeliling, setengah hasta tingginya; di sebelah atas kereta itu ada pula topang-topang dan papan penutup yang seiras dengan dia."
  },
  {Bible:"1Kings", Chapter:7, Verse:36, Page:1,
    Kor:"바퀴축인 버팀대 판자와 테두리 판자 위의 빈 곳에는, 그룹과 사자와 종려나무를 활짝 핀 꽃 모양과 함께 새겼다.",
    Chn:"在撑子和心子上刻着基路伯、狮子，和棕树，周围有璎珞。",
    Eng:"He engraved cherubim, lions and palm trees on the surfaces of the supports and on the panels, in every available space, with wreaths all around.",
    Ind:"Maka pada muka topang-topangnya itu dan pada papan-papan penutupnya diukirkannyalah kerub, singa dan pohon korma, masing-masing menurut tempat yang ada, dan karangan bunga sekeliling."
  },
  {Bible:"1Kings", Chapter:7, Verse:37, Page:1,
    Kor:"그는 이러한 방식으로 받침대 열 개를 만들었는데, 모두가 같은 치수와 같은 양식으로, 일일이 부어서 만들었다.",
    Chn:"十个盆座都是这样，铸法、尺寸、样式相同。",
    Eng:"This is the way he made the ten stands. They were all cast in the same molds and were identical in size and shape.",
    Ind:"Demikianlah dikerjakannya kesepuluh kereta penopang itu; tuangannya sama, ukurannya sama dan potongannya sama semuanya."
  },
  {Bible:"1Kings", Chapter:7, Verse:38, Page:1,
    Kor:"○또 그는 놋쇠로 대야 열 개를 만들었다. 대야마다 물을 마흔 말씩 담을 수 있었다. 대야들의 지름은 넉 자이다. 받침대 열 개에는 모두 대야 하나씩을 달았다.",
    Chn:"又用铜制造十个盆，每盆可容四十罢特。盆径四肘，在那十座上，每座安设一盆。",
    Eng:"He then made ten bronze basins, each holding forty baths and measuring four cubits across, one basin to go on each of the ten stands.",
    Ind:"Lagipula dibuatnya sepuluh bejana pembasuhan dari tembaga: setiap bejana dapat memuat empat puluh bat air, setiap bejana empat hasta besarnya dan ada satu bejana di atas setiap kereta dari kesepuluh kereta penopang itu."
  },
  {Bible:"1Kings", Chapter:7, Verse:39, Page:1,
    Kor:"받침대 다섯 개는 성전의 오른쪽에, 다섯 개는 성전의 왼쪽에 놓았고, 바다 모양 물통은 성전 오른쪽의 동남쪽 모퉁이에 놓았다.",
    Chn:"五个安在殿门的右边，五个放在殿门的左边；又将海放在殿门的右旁，就是南边。",
    Eng:"He placed five of the stands on the south side of the temple and five on the north. He placed the Sea on the south side, at the southeast corner of the temple.",
    Ind:"Lima kereta penopang ditaruhnya pada sisi kanan rumah itu dan lima pada sisi kirinya; tetapi \"laut\" itu ditaruhnya pada sisi kanan rumah itu, arah tenggara."
  },
  {Bible:"1Kings", Chapter:7, Verse:40, Page:1,
    Kor:"<성전 기구(대하 4:11-5:1)> ○a후람은 또 솥과 부삽과 피 뿌리는 대접을 만들었다. 이렇게 a후람은, 솔로몬 왕이 주님의 성전에다가 해 놓으라고 시킨 모든 일을 마쳤다.(a 히, '히람')",
    Chn:"户兰又造了盆、铲子，和盘子。这样，他为所罗门王做完了耶和华殿的一切工。",
    Eng:"He also made the basins and shovels and sprinkling bowls. So Huram finished all the work he had undertaken for King Solomon in the temple of the LORD:",
    Ind:"Dan Hiram membuat juga kuali-kuali, penyodok-penyodok dan bokor-bokor penyiraman. Demikianlah Hiram menyelesaikan segala pekerjaan yang harus dilakukannya bagi raja Salomo di rumah TUHAN,"
  },
  {Bible:"1Kings", Chapter:7, Verse:41, Page:1,
    Kor:"그가 만든 것들은, 두 기둥과, 그 두 기둥 꼭대기에 얹은 둥근 공 모양을 한 기둥 머리 둘과, 그 두 기둥 꼭대기에 있는 공 모양을 한 기둥 머리에 씌운 그물 두 개와,",
    Chn:"所造的就是：两根柱子和柱上两个如球的顶；并两个盖柱顶的网子；",
    Eng:"the two pillars; the two bowl-shaped capitals on top of the pillars; the two sets of network decorating the two bowl-shaped capitals on top of the pillars;",
    Ind:"yakni kedua tiang dengan kedua bulatan ganja yang di kepala tiang itu, dan kedua jala-jala yang menutup kedua bulatan ganja itu;"
  },
  {Bible:"1Kings", Chapter:7, Verse:42, Page:1,
    Kor:"기둥 꼭대기에 있는 공 모양을 한 기둥 머리에 씌운 각 그물에다가 두 줄로 장식한 석류 사백 개와,",
    Chn:"和四百石榴，安在两个网子上，每网两行，盖着两个柱上如球的顶；",
    Eng:"the four hundred pomegranates for the two sets of network (two rows of pomegranates for each network, decorating the bowl-shaped capitals on top of the pillars);",
    Ind:"keempat ratus buah delima untuk kedua jala-jala itu, dua jajar buah delima untuk satu jala-jala guna menutupi kedua bulatan ganja yang di atas tiang itu;"
  },
  {Bible:"1Kings", Chapter:7, Verse:43, Page:1,
    Kor:"또 받침대 열 개와, 받침대 위에 놓을 대야 열 개와,",
    Chn:"十个座和其上的十个盆；",
    Eng:"the ten stands with their ten basins;",
    Ind:"kesepuluh kereta penopang dan kesepuluh bejana pembasuhan yang di atas kereta itu;"
  },
  {Bible:"1Kings", Chapter:7, Verse:44, Page:1,
    Kor:"바다 모양 물통 한 개와, 그 바다 모양 물통 아래에 받쳐 놓은 황소 모양 열두 개와,",
    Chn:"海和海下的十二只牛；",
    Eng:"the Sea and the twelve bulls under it;",
    Ind:"\"laut\" yang satu itu dan kedua belas lembu yang di bawah \"laut\" itu;"
  },
  {Bible:"1Kings", Chapter:7, Verse:45, Page:1,
    Kor:"솥과 부삽과 피 뿌리는 대접 들이다. ○a후람이 솔로몬 왕을 도와서 만든 주님의 성전의 이 모든 기구는 모두 광택나는 놋쇠로 만든 것이다.(a 히, '히람')",
    Chn:"盆、铲子、盘子。这一切都是户兰给所罗门王用光亮的铜为耶和华的殿造成的，",
    Eng:"the pots, shovels and sprinkling bowls. All these objects that Huram made for King Solomon for the temple of the LORD were of burnished bronze.",
    Ind:"kuali-kuali, penyodok-penyodok dan bokor-bokor penyiraman; segala perlengkapan yang dibuat Hiram bagi raja Salomo di rumah TUHAN itu adalah dari tembaga yang diupam."
  },
  {Bible:"1Kings", Chapter:7, Verse:46, Page:1,
    Kor:"왕은 이 기구들을, 숙곳과 사르단 사이에 있는 요단 계곡의 진흙에 부어서 만들게 하였다.",
    Chn:"是遵王命在约旦平原、疏割和撒拉但中间借胶泥铸成的。",
    Eng:"The king had them cast in clay molds in the plain of the Jordan between Succoth and Zarethan.",
    Ind:"Raja menuang semuanya itu di Lembah Yordan di dalam tanah liat antara Sukot dan Sartan."
  },
  {Bible:"1Kings", Chapter:7, Verse:47, Page:1,
    Kor:"이 기구들이 너무 많아서, 솔로몬이 그 무게를 달지 못하였으므로, 여기에 사용된 놋쇠의 무게는 아무도 모른다.",
    Chn:"这一切所罗门都没有过秤；因为甚多，铜的轻重也无法可查。",
    Eng:"Solomon left all these things unweighed, because there were so many; the weight of the bronze was not determined.",
    Ind:"Dan Salomo membiarkan segala perlengkapan itu tidak ditimbang karena jumlahnya yang amat besar; berat tembaga itu tidaklah terhitung."
  },
  {Bible:"1Kings", Chapter:7, Verse:48, Page:1,
    Kor:"○솔로몬은 또 주님의 성전 안에다가 둘 기구를 만들었는데, 곧 금 제단과, 빵을 늘 차려 놓는 금으로 만든 상과,",
    Chn:"所罗门又造耶和华殿里的金坛和陈设饼的金桌子；",
    Eng:"Solomon also made all the furnishings that were in the LORD'S temple: the golden altar; the golden table on which was the bread of the Presence;",
    Ind:"Salomo membuat juga segala perlengkapan yang ada di rumah TUHAN, yakni mezbah emas dan meja emas tempat menaruh roti sajian;"
  },
  {Bible:"1Kings", Chapter:7, Verse:49, Page:1,
    Kor:"또 등잔대들, 곧 지성소 앞의 오른쪽에 다섯 왼쪽에 다섯 개씩 놓을 순금 등잔대들과, 금으로 만든 꽃 장식과, 등잔과, 부집게와,",
    Chn:"内殿前的精金灯台：右边五个，左边五个，并其上的金花、灯盏、蜡剪，",
    Eng:"the lampstands of pure gold (five on the right and five on the left, in front of the inner sanctuary); the gold floral work and lamps and tongs;",
    Ind:"kandil-kandil dari emas murni, lima di sebelah kanan dan lima di sebelah kiri, di depan ruang belakang; kembang-kembangnya, lampu-lampunya dan sepit-sepitnya, dari emas;"
  },
  {Bible:"1Kings", Chapter:7, Verse:50, Page:1,
    Kor:"순금으로 된 잔과, 심지 다듬는 집게와, 피 뿌리는 대접과, 향로와, 불 옮기는 그릇과, 내실 곧 지성소 문에 다는 금돌쩌귀와, 성전의 바깥 문에 다는 금돌쩌귀 들이다.",
    Chn:"与精金的杯、盘、镊子、调羹、火鼎，以及至圣所、内殿的门枢，和外殿的门枢。",
    Eng:"the pure gold basins, wick trimmers, sprinkling bowls, dishes and censers; and the gold sockets for the doors of the innermost room, the Most Holy Place, and also for the doors of the main hall of the temple.",
    Ind:"pasu-pasunya, pisau-pisaunya, bokor-bokor penyiramannya, cawan-cawannya dan perbaraan-perbaraannya, dari emas murni; engsel-engsel untuk pintu ruang dalam, yakni tempat maha kudus, dan engsel-engsel untuk pintu ruang besar Bait Suci, dari emas."
  },
  {Bible:"1Kings", Chapter:7, Verse:51, Page:1,
    Kor:"○이렇게 해서, 솔로몬 왕은 주님의 성전을 짓는 모든 일을 완성하였다. 솔로몬은 그의 아버지 다윗이 거룩하게 구별해서 바친 성물 곧 은과 금과 기구들을 가져다가, 주님의 성전 창고에 넣었다.",
    Chn:"所罗门王做完了耶和华殿的一切工，就把他父大卫分别为圣的金银和器皿都带来放在耶和华殿的府库里。",
    Eng:"When all the work King Solomon had done for the temple of the LORD was finished, he brought in the things his father David had dedicated--the silver and gold and the furnishings--and he placed them in the treasuries of the LORD'S temple.",
    Ind:"Maka genaplah segala pekerjaan yang dilakukan Salomo di rumah TUHAN itu. Kemudian Salomo memasukkan barang-barang kudus Daud, ayahnya, dan menaruh perak, emas dan barang-barang itu dalam perbendaharaan rumah TUHAN."
  },
]);
