// 열왕기상 20장 · 1Kings 20
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("1Kings",20,43);
BibleDB.add([
  {Bible:"1Kings", Chapter:20, Verse:1, Page:1,
    Kor:"<시리아와의 전쟁> 시리아 왕 벤하닷은 군대를 모두 모았다. 지방 영주 서른두 명과 기마병과 병거들이 모이자, 그는 올라가서, 사마리아 성을 포위하고, 공격하였다.",
    Chn:"亚兰王便·哈达聚集他的全军，率领三十二个王，带着车马上来围攻撒马利亚；",
    Eng:"Now Ben-Hadad king of Aram mustered his entire army. Accompanied by thirty-two kings with their horses and chariots, he went up and besieged Samaria and attacked it.",
    Ind:"Benhadad, raja Aram, mengumpulkan seluruh tentaranya, tiga puluh dua orang raja bersama-sama dia beserta kuda dan kereta. Lalu ia maju, ia mengepung Samaria dan memeranginya."
  },
  {Bible:"1Kings", Chapter:20, Verse:2, Page:1,
    Kor:"그는 그 성 안에 있는 이스라엘 왕 아합에게 사절들을 보내어,",
    Chn:"又差遣使者进城见以色列王亚哈，对他说：「便·哈达如此说：",
    Eng:"He sent messengers into the city to Ahab king of Israel, saying, \"This is what Ben-Hadad says:",
    Ind:"Kemudian ia mengirim utusan ke kota itu, kepada Ahab, raja Israel,"
  },
  {Bible:"1Kings", Chapter:20, Verse:3, Page:1,
    Kor:"그에게 말하였다. \"나 벤하닷이 말한다. 너의 은과 금은 모두 나의 것이다. 그리고 네 아리따운 아내들과 자녀도 모두 나의 것이다.\"",
    Chn:"你的金银都要归我，你妻子儿女中最美的也要归我。」",
    Eng:"'Your silver and gold are mine, and the best of your wives and children are mine.'\"",
    Ind:"dengan pesan: \"Beginilah pesan Benhadad: Emasmu dan perakmu adalah milikku, dan juga isteri-isteri dan anak-anakmu yang cantik-cantik adalah milikku.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:4, Page:1,
    Kor:"이스라엘 왕이 회답을 보내어 말하였다. \"나의 상전이신 임금님, 임금님의 말씀대로, 나와 내가 소유하고 있는 것은 모두 임금님의 것입니다.\"",
    Chn:"以色列王回答说：「我主我王啊，可以依着你的话，我与我所有的都归你。」",
    Eng:"The king of Israel answered, \"Just as you say, my lord the king. I and all I have are yours.\"",
    Ind:"Raja Israel menjawab, katanya: \"Seperti bicaramu itulah, ya tuanku raja. Aku ini dengan segala yang ada padaku adalah milikmu!\""
  },
  {Bible:"1Kings", Chapter:20, Verse:5, Page:1,
    Kor:"사절들이 다시 아합에게 와서, 벤하닷의 말을 전하였다. ○\"나 벤하닷이 말한다. 내가 전에 사절을 보내어서 전달한 것은, 너의 은과 금과 아내들과 자녀들을 모두 나에게로 보내라는 말이었다.",
    Chn:"使者又来说：「便·哈达如此说：我已差遣人去见你，要你将你的金银、妻子、儿女都给我。",
    Eng:"The messengers came again and said, \"This is what Ben-Hadad says: 'I sent to demand your silver and gold, your wives and your children.",
    Ind:"Sesudah itu utusan-utusan itu kembali dan berkata: \"Beginilah pesan Benhadad: Memang aku telah menyuruh orang kepadamu mengatakan: Emas dan perakmu, isteri-isteri dan anak-anakmu harus kauserahkan kepadaku,"
  },
  {Bible:"1Kings", Chapter:20, Verse:6, Page:1,
    Kor:"내일 이맘때쯤에 내가 내 신하들을 보내겠다. 그들이 네 집과 신하들의 집을 뒤져서, a그들의 눈에 드는 것은 무엇이나 가져 올 것이니, 그리 알아라.\"(a 칠십인역과 시리아어역과 불가타를 따름. 히, '네 눈에')",
    Chn:"但明日约在这时候，我还要差遣臣仆到你那里，搜查你的家和你仆人的家，将你眼中一切所喜爱的都拿了去。」",
    Eng:"But about this time tomorrow I am going to send my officials to search your palace and the houses of your officials. They will seize everything you value and carry it away.'\"",
    Ind:"tetapi besok kira-kira pada waktu ini, aku akan menyuruh pegawai-pegawaiku kepadamu dan mereka akan menggeledah rumahmu dan rumah pegawai-pegawaimu, maka segala yang mereka lihat dan ingini akan mereka ambil dan mereka bawa.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:7, Page:1,
    Kor:"○그래서 이스라엘 왕은 나라 안의 모든 원로들을 모아 놓고 의논하였다. \"벤하닷이라는 사람이 꾀하고 있는 일이 얼마나 악한 일인지, 잘 생각해 보시오. 그가 나에게 왕비들과 자녀들을 내놓으라고 하고, 또 은과 금까지 요구하고 있는데, 나로서는 이것을 거절할 수가 없소.\"",
    Chn:"以色列王召了国中的长老来，对他们说：「请你们看看，这人是怎样地谋害我，他先差遣人到我这里来，要我的妻子、儿女，和金银，我并没有推辞他。」",
    Eng:"The king of Israel summoned all the elders of the land and said to them, \"See how this man is looking for trouble! When he sent for my wives and my children, my silver and my gold, I did not refuse him.\"",
    Ind:"Lalu raja Israel memanggil semua tua-tua negeri itu dan berkata: \"Camkanlah, orang ini mengikhtiarkan kecelakaan kita, sebab ia telah menyuruh orang kepadaku meminta isteri-isteriku, anak-anakku, emas dan perakku, dan aku tidak menolak memberikannya kepadanya.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:8, Page:1,
    Kor:"그러나 모든 원로와 백성들은 왕에게, 벤하닷의 말을 듣지도 말고, 요구한 것을 보내지도 말라고 간언하였다.",
    Chn:"长老和百姓对王说：「不要听从他，也不要应允他。」",
    Eng:"The elders and the people all answered, \"Don't listen to him or agree to his demands.\"",
    Ind:"Lalu kata semua tua-tua dan segenap rakyat itu kepadanya: \"Jangan dengarkan, jangan luluskan!\""
  },
  {Bible:"1Kings", Chapter:20, Verse:9, Page:1,
    Kor:"그래서 그는 벤하닷의 사절들에게 말하였다. \"임금님께 가서, 첫 번째 요구는 내가 듣겠지만, 두 번째 요구는 내가 들어 줄 수 없다고 전하시오.\" 사절들은 돌아가서, 그대로 보고하였다.",
    Chn:"故此，以色列王对便·哈达的使者说：「你们告诉我主我王说：王头一次差遣人向仆人所要的，仆人都依从；但这次所要的，我不能依从。」使者就去回复便·哈达。",
    Eng:"So he replied to Ben-Hadad's messengers, \"Tell my lord the king, 'Your servant will do all you demanded the first time, but this demand I cannot meet.'\" They left and took the answer back to Ben-Hadad.",
    Ind:"Sebab itu ia berkata kepada utusan-utusan Benhadad: \"Katakanlah kepada tuanku raja: Segala yang pertama kali kausuruhkan kepada hambamu ini, aku akan melakukannya, tetapi tuntutan yang kemudian ini tidak dapat kupenuhi.\" Lalu pergilah utusan-utusan itu dan menyampaikan jawab itu kepada Benhadad."
  },
  {Bible:"1Kings", Chapter:20, Verse:10, Page:1,
    Kor:"벤하닷은 다시 전갈을 보내어서 말하였다. \"내가 네 사마리아 성을 잿더미로 만들어서, 깨어진 조각 하나도 남지 않게 하겠다. 내가 이끄는 군인들이, 자기들의 손에 깨어진 조각 하나라도 주울 수 있으면, 신들이 나에게, 천벌이 아니라 그보다 더한 재앙을 내려도, 내가 달게 받겠다.\"",
    Chn:"便·哈达又差遣人去见亚哈说：「撒马利亚的尘土若够跟从我的人每人捧一捧的，愿神明重重地降罚与我！」",
    Eng:"Then Ben-Hadad sent another message to Ahab: \"May the gods deal with me, be it ever so severely, if enough dust remains in Samaria to give each of my men a handful.\"",
    Ind:"Benhadad menyuruh orang kepada Ahab dengan pesan: \"Beginilah kiranya para allah menghukum aku, bahkan lebih lagi dari pada itu, jika rakyat yang mengikut aku masih dapat menjemput segenggam penuh debu puing Samaria!\""
  },
  {Bible:"1Kings", Chapter:20, Verse:11, Page:1,
    Kor:"이스라엘 왕이 회신을 보냈다. \"너의 왕에게 가서, 참 군인은 갑옷을 입을 때에 자랑하지 아니하고, 갑옷을 벗을 때에 자랑하는 법이라고 일러라.\"",
    Chn:"以色列王说：「你告诉他说，才顶盔贯甲的，休要像摘盔卸甲的夸口。」",
    Eng:"The king of Israel answered, \"Tell him: 'One who puts on his armor should not boast like one who takes it off.'\"",
    Ind:"Tetapi raja Israel menjawab, katanya: \"Katakanlah! Orang yang baru menyandangkan pedang janganlah memegahkan diri seperti orang yang sudah menanggalkannya.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:12, Page:1,
    Kor:"벤하닷은 지방 영주들과 함께 막사에서 술을 마시고 있다가, 이 말을 듣고는, 신하들에게 공격 준비를 갖추라고 명령을 내렸다. 그들은 곧 b사마리아 성을 공격할 준비를 갖추었다.(b 히, '성을')",
    Chn:"便·哈达和诸王正在帐幕里喝酒，听见这话，就对他臣仆说：「摆队吧！」他们就摆队攻城。",
    Eng:"Ben-Hadad heard this message while he and the kings were drinking in their tents, and he ordered his men: \"Prepare to attack.\" So they prepared to attack the city.",
    Ind:"Segera sesudah Benhadad mendengar perkataan itu, pada waktu ia sedang minum-minum dengan raja-raja di pondok, berkatalah ia kepada pegawai-pegawainya: \"Aturlah barisanmu,\" lalu mereka mengatur barisannya melawan kota itu."
  },
  {Bible:"1Kings", Chapter:20, Verse:13, Page:1,
    Kor:"○그 때에 예언자 한 사람이 이스라엘 왕 아합에게 와서 말하였다. \"나 주가 말한다. 네가 이렇게 큰 군대를 본 적이 있느냐? 그러나 내가 오늘 그들을 네 손에 넘겨 줄 것이니, 너는, 내가 주인 줄 알게 될 것이다.\"",
    Chn:"有一个先知来见以色列王亚哈，说：「耶和华如此说：『这一大群人你看见了吗？今日我必将他们交在你手里，你就知道我是耶和华。』」",
    Eng:"Meanwhile a prophet came to Ahab king of Israel and announced, \"This is what the LORD says: 'Do you see this vast army? I will give it into your hand today, and then you will know that I am the LORD.'\"",
    Ind:"Tetapi tiba-tiba tampillah seorang nabi kepada Ahab, raja Israel, serta berkata: \"Beginilah firman TUHAN: Sudahkah kaulihat semua orang yang sangat ramai itu? Bahwasanya pada hari ini Aku akan menyerahkan mereka ke dalam tanganmu, supaya engkau tahu, bahwa Akulah TUHAN.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:14, Page:1,
    Kor:"아합이 물었다. \"진 앞에는 누가 섭니까?\" 예언자가 대답하였다. \"주님께서 말씀하시기를, 지방장관들의 젊은 부하들을 앞세우라고 하셨습니다.\" 그러자 아합은 다시 물었다. \"누가 총지휘를 합니까?\" 그 예언자가 대답하였다. \"임금님이십니다.\"",
    Chn:"亚哈说：「借着谁呢？」他回答说：「耶和华说，借着跟从省长的少年人。」亚哈说：「要谁率领呢？」他说：「要你亲自率领。」",
    Eng:"\"But who will do this?\" asked Ahab. The prophet replied, \"This is what the LORD says: 'The young officers of the provincial commanders will do it.'\" \"And who will start the battle?\" he asked. The prophet answered, \"You will.\"",
    Ind:"Lalu bertanyalah Ahab: \"Dengan bantuan siapa?\" Jawabnya: \"Beginilah firman TUHAN: Dengan bantuan orang-orang muda pengiring kepala-kepala daerah.\" Tanyanya pula: \"Siapakah yang akan memulai perang?\" Jawabnya: \"Engkau!\""
  },
  {Bible:"1Kings", Chapter:20, Verse:15, Page:1,
    Kor:"그래서 아합이 지방장관들의 젊은 부하들을 점검하여 보니, 그들은 모두 이백서른두 명이었다. 그런 다음에, 그가 이스라엘 군대를 모두 점검하여 보니, 모두 칠천 명이었다.",
    Chn:"于是亚哈数点跟从省长的少年人，共有二百三十二名，后又数点以色列的众兵，共有七千名。",
    Eng:"So Ahab summoned the young officers of the provincial commanders, 232 men. Then he assembled the rest of the Israelites, 7,000 in all.",
    Ind:"Kemudian ia menghitung jumlah orang-orang muda pengiring kepala-kepala daerah itu. Ada dua ratus tiga puluh dua orang banyaknya dan sesudah mereka itu ia menghitung jumlah seluruh rakyat, yakni segenap orang Israel. Ada tujuh ribu orang banyaknya."
  },
  {Bible:"1Kings", Chapter:20, Verse:16, Page:1,
    Kor:"○정오가 되자, 아합의 군대가 공격을 시작하였다. 그 때에 벤하닷은 자기를 돕는 지방 영주 서른두 명과 함께 막사에서 술에 취해 있었다.",
    Chn:"午间，他们就出城；便·哈达和帮助他的三十二个王正在帐幕里痛饮。",
    Eng:"They set out at noon while Ben-Hadad and the 32 kings allied with him were in their tents getting drunk.",
    Ind:"Lalu mereka maju menyerang pada waktu tengah hari, sementara Benhadad minum-minum sampai mabuk di pondoknya, bersama dengan ketiga puluh dua raja yang membantunya."
  },
  {Bible:"1Kings", Chapter:20, Verse:17, Page:1,
    Kor:"지방장관들의 젊은 부하들이 먼저 공격을 시작하였다. 벤하닷의 정찰병들이 벤하닷에게, 적군들이 사마리아 성에서 나오고 있다고 보고하였다.",
    Chn:"跟从省长的少年人先出城；便·哈达差遣人去探望，他们回报说：「有人从撒马利亚出来了。」",
    Eng:"The young officers of the provincial commanders went out first. Now Ben-Hadad had dispatched scouts, who reported, \"Men are advancing from Samaria.\"",
    Ind:"Ketika orang-orang muda pengiring kepala-kepala daerah itu maju menyerang lebih dahulu, maka Benhadad menyuruh orang menyelidiknya, dan mereka memberitahukan kepadanya, demikian: \"Ada orang-orang maju menyerang dari Samaria.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:18, Page:1,
    Kor:"보고를 받은 벤하닷은, 그들이 화친을 하러 나왔더라도 사로잡고, 싸움을 하러 나왔더라도 사로잡으라고 명령하였다.",
    Chn:"他说：「他们若为讲和出来，要活捉他们；若为打仗出来，也要活捉他们。」",
    Eng:"He said, \"If they have come out for peace, take them alive; if they have come out for war, take them alive.\"",
    Ind:"Lalu katanya: \"Entah mereka datang dengan maksud damai, entah dengan maksud perang, tangkaplah mereka hidup-hidup!\""
  },
  {Bible:"1Kings", Chapter:20, Verse:19, Page:1,
    Kor:"○그러나 지방장관의 젊은 부하들과 그들을 뒤따르는 군대는 이미 성읍 바깥으로 나와서,",
    Chn:"跟从省长的少年人出城，军兵跟随他们；",
    Eng:"The young officers of the provincial commanders marched out of the city with the army behind them",
    Ind:"Sementara itu keluarlah mereka itu dari dalam kota, yakni orang-orang muda pengiring kepala-kepala daerah dan juga tentara yang mengikuti mereka."
  },
  {Bible:"1Kings", Chapter:20, Verse:20, Page:1,
    Kor:"저마다 닥치는 대로 벤하닷의 군대를 무찔렀다. 그래서 시리아 군인들은 다 도망하였고, 이스라엘 군대가 그들을 추격하였다. 시리아 왕 벤하닷도 기병들과 함께 말을 타고 도망하였다.",
    Chn:"各人遇见敌人就杀。亚兰人逃跑，以色列人追赶他们；亚兰王便·哈达骑着马和马兵一同逃跑。",
    Eng:"and each one struck down his opponent. At that, the Arameans fled, with the Israelites in pursuit. But Ben-Hadad king of Aram escaped on horseback with some of his horsemen.",
    Ind:"Lalu mereka masing-masing membunuh lawan yang dihadapinya, sehingga orang Aram itu melarikan diri dan dikejar oleh orang Israel. Tetapi Benhadad, raja Aram dapat meluputkan diri dengan naik kuda, beserta sejumlah orang berkuda."
  },
  {Bible:"1Kings", Chapter:20, Verse:21, Page:1,
    Kor:"이렇게 해서 이스라엘 왕은, 첫 싸움에서 많은 말과 병거를 격파하고, 시리아 군대를 크게 무찔렀다.",
    Chn:"以色列王出城攻打车马，大大击杀亚兰人。",
    Eng:"The king of Israel advanced and overpowered the horses and chariots and inflicted heavy losses on the Arameans.",
    Ind:"Juga raja Israel maju, lalu memusnahkan kuda dan kereta itu dan mendatangkan kekalahan yang besar kepada orang Aram."
  },
  {Bible:"1Kings", Chapter:20, Verse:22, Page:1,
    Kor:"○그 예언자가 다시 이스라엘 왕에게 와서, 이렇게 말하였다. \"임금님께서는 힘을 키우시고, 앞으로 하셔야 할 일이 무엇인지를 생각해 두십시오. 내년에 시리아 임금이 다시 임금님을 치려고 올라올 것입니다.\"",
    Chn:"那先知来见以色列王，对他说：「你当自强，留心怎样防备；因为到明年这时候，亚兰王必上来攻击你。」",
    Eng:"Afterward, the prophet came to the king of Israel and said, \"Strengthen your position and see what must be done, because next spring the king of Aram will attack you again.\"",
    Ind:"Lalu tampillah nabi itu kepada raja Israel dan berkata kepadanya: \"Baiklah, kuatkanlah hatimu, pertimbangkan dan pikirkanlah apa yang harus kauperbuat, sebab pada pergantian tahun raja Aram akan maju menyerang engkau.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:23, Page:1,
    Kor:"<시리아 군대의 두 번째 공격> ○시리아 왕의 신하들이 자기들의 왕에게 말하였다. ○\"이스라엘의 신은 산의 신입니다. 저번에는 산에서 싸웠으므로, 우리가 졌습니다. 그러나 평지에서 싸우면, 우리가 그들을 반드시 이길 것입니다.",
    Chn:"亚兰王的臣仆对亚兰王说：「以色列人的神是山神，所以他们胜过我们；但在平原与他们打仗，我们必定得胜。",
    Eng:"Meanwhile, the officials of the king of Aram advised him, \"Their gods are gods of the hills. That is why they were too strong for us. But if we fight them on the plains, surely we will be stronger than they.",
    Ind:"Pegawai-pegawai raja Aram berkata kepadanya: \"Allah mereka ialah allah gunung; itulah sebabnya mereka lebih kuat dari pada kita. Tetapi apabila kita berperang melawan mereka di tanah rata, pastilah kita lebih kuat dari pada mereka."
  },
  {Bible:"1Kings", Chapter:20, Verse:24, Page:1,
    Kor:"그러므로 임금님께서는 이렇게 하시는 것이 좋을 줄 압니다. 지방 영주를 모두 그 자리에서 물러나게 하시고, 그 대신에 군사령관들을 그 자리에 임명하십시오.",
    Chn:"王当这样行：把诸王革去，派军长代替他们，",
    Eng:"Do this: Remove all the kings from their commands and replace them with other officers.",
    Ind:"Bertindaklah begini: Pecatlah raja-raja itu masing-masing dari kedudukannya, dan angkatlah bupati-bupati menggantikan mereka."
  },
  {Bible:"1Kings", Chapter:20, Verse:25, Page:1,
    Kor:"잃은 수만큼, 군대와 기마와 병거를 보충하십시오. 그런 다음에 평지에서 싸우면, 틀림없이 우리가 이길 것입니다.\" 왕은 그들의 말을 듣고, 그대로 하였다.",
    Chn:"又照着王丧失军兵之数，再招募一军，马补马，车补车，我们在平原与他们打仗，必定得胜。」王便听臣仆的话去行。",
    Eng:"You must also raise an army like the one you lost--horse for horse and chariot for chariot--so we can fight Israel on the plains. Then surely we will be stronger than they.\" He agreed with them and acted accordingly.",
    Ind:"Lalu kerahkanlah tentara sebanyak tentara yang telah gugur dari pihakmu itu, demikian pula kuda dan kereta sebanyak yang dahulu. Marilah kita berperang melawan mereka di tanah rata, pastilah kita lebih kuat dari pada mereka.\" Raja mendengarkan usul mereka, dan bertindak demikian."
  },
  {Bible:"1Kings", Chapter:20, Verse:26, Page:1,
    Kor:"○해가 바뀌었다. 벤하닷은 시리아 군대를 소집하고, 이스라엘과 싸우려고 아벡으로 올라갔다.",
    Chn:"次年，便·哈达果然点齐亚兰人上亚弗去，要与以色列人打仗。",
    Eng:"The next spring Ben-Hadad mustered the Arameans and went up to Aphek to fight against Israel.",
    Ind:"Dalam tahun yang berikutnya Benhadad memeriksa barisan orang Aram, lalu ia maju ke Afek untuk berperang melawan orang Israel."
  },
  {Bible:"1Kings", Chapter:20, Verse:27, Page:1,
    Kor:"이스라엘 군대도 소집이 되어서, 식량을 배급받고는, 그들과 싸우려고 나아갔다. 이스라엘 군대가 그들 앞에 진을 쳤으나, 이스라엘 군대는 시리아 군대에 비하면, 마치 작은 염소 두 떼와 같았고, 시리아 군대는 그 땅을 가득 채울 만큼 많았다.",
    Chn:"以色列人也点齐军兵，预备食物，迎着亚兰人出去，对着他们安营，好像两小群山羊羔；亚兰人却满了地面。",
    Eng:"When the Israelites were also mustered and given provisions, they marched out to meet them. The Israelites camped opposite them like two small flocks of goats, while the Arameans covered the countryside.",
    Ind:"Orang Israelpun memeriksa barisannya dan setelah dibekali mereka berangkat menghadapi orang Aram. Orang Israel berkemah di hadapan mereka seperti dua kawanan kambing, sedang orang Aram telah datang membanjiri negeri itu."
  },
  {Bible:"1Kings", Chapter:20, Verse:28, Page:1,
    Kor:"그 때에 하나님의 사람이 가까이 와서, 이스라엘 왕에게 말하였다. \"주님께서 이렇게 말씀하셨습니다. '시리아 사람이 말하기를, 내가 산의 신이지, 평지의 신은 아니라고 하니, 내가 이 큰 군대를 모두 네 손에 내주겠다. 이제 너희는 곧, 내가 주인 줄 알게 될 것이다.'\"",
    Chn:"有神人来见以色列王，说：「耶和华如此说：『亚兰人既说我—耶和华是山神，不是平原的神，所以我必将这一大群人都交在你手中，你们就知道我是耶和华。』」",
    Eng:"The man of God came up and told the king of Israel, \"This is what the LORD says: 'Because the Arameans think the LORD is a god of the hills and not a god of the valleys, I will deliver this vast army into your hands, and you will know that I am the LORD.'\"",
    Ind:"Maka tampillah abdi Allah dan berkata kepada raja Israel: \"Beginilah firman TUHAN: Oleh karena orang Aram itu telah berkata: TUHAN ialah allah gunung dan bukan allah dataran, maka Aku akan menyerahkan seluruh tentara yang besar itu ke dalam tanganmu, supaya kamu tahu, bahwa Akulah TUHAN.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:29, Page:1,
    Kor:"○양쪽 군대는 서로 대치하여서, 이레 동안 진을 치고 있었다. 드디어 이레째 되는 날 전투가 벌어졌는데, 이스라엘 군대가 시리아 군대를 쳐서 하루만에 보병 십만 명을 무찔렀다.",
    Chn:"以色列人与亚兰人相对安营七日，到第七日两军交战；那一日以色列人杀了亚兰人步兵十万，",
    Eng:"For seven days they camped opposite each other, and on the seventh day the battle was joined. The Israelites inflicted a hundred thousand casualties on the Aramean foot soldiers in one day.",
    Ind:"Tujuh hari lamanya mereka berkemah berhadap-hadapan. Tetapi pada hari yang ketujuh mulailah pertempuran, dan pada suatu hari orang Israel menewaskan seratus ribu orang berjalan kaki dari orang Aram itu."
  },
  {Bible:"1Kings", Chapter:20, Verse:30, Page:1,
    Kor:"그 나머지는 아벡 성으로 도망하였으나, 성벽이 무너져서, 나머지 이만 칠천 명을 덮쳐 버렸다. ○벤하닷도 도망하여서, 그 성 안의 어느 골방으로 들어갔다.",
    Chn:"其余的逃入亚弗城；城墙塌倒，压死剩下的二万七千人。 便·哈达也逃入城，藏在严密的屋子里。",
    Eng:"The rest of them escaped to the city of Aphek, where the wall collapsed on twenty-seven thousand of them. And Ben-Hadad fled to the city and hid in an inner room.",
    Ind:"Orang-orang yang masih tinggal melarikan diri ke Afek, ke dalam kota, tetapi temboknya roboh menimpa kedua puluh tujuh ribu orang yang masih tinggal itu. Sementara itu Benhadad melarikan diri dan masuk ke kota, dan bersembunyi dari satu kamar ke kamar yang lain."
  },
  {Bible:"1Kings", Chapter:20, Verse:31, Page:1,
    Kor:"그의 신하들이 그에게 말하였다. \"이스라엘 왕가의 왕들은 모두 인정이 많은 왕이라고 들었습니다. 우리가 굵은 베로 허리를 묶고, 목에 줄을 동여 매고, 이스라엘 왕에게 가면, 어쩌면 그가 임금님의 생명을 살려 줄지도 모릅니다.\"",
    Chn:"他的臣仆对他说：「我们听说以色列王都是仁慈的王，现在我们不如腰束麻布，头套绳索，出去投降以色列王，或者他存留王的性命。」",
    Eng:"His officials said to him, \"Look, we have heard that the kings of the house of Israel are merciful. Let us go to the king of Israel with sackcloth around our waists and ropes around our heads. Perhaps he will spare your life.\"",
    Ind:"Lalu berkatalah pegawai-pegawainya kepadanya: \"Ketahuilah, kami telah mendengar, bahwa raja-raja kaum Israel itu adalah raja-raja pemurah. Marilah kita menaruh kain kabung pada pinggang kita dan tali pada kepala kita, dan dengan demikian keluar menghadap raja Israel; barangkali ia akan menyelamatkan nyawamu.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:32, Page:1,
    Kor:"그래서 그들은 굵은 베로 허리를 묶고, 목에 줄을 동여 매고 이스라엘 왕에게 나아가서 \"왕의 종 벤하닷이, 제발 목숨만은 살려 달라고 애원하고 있습니다.\" 하고 말하니, 아합 왕이 말하였다. \"아직도 그가 살아 있느냐? 그는 나의 형제다.\"",
    Chn:"于是他们腰束麻布，头套绳索，去见以色列王，说：「王的仆人便·哈达说，求王存留我的性命。」亚哈说：「他还活着吗？他是我的兄弟。」",
    Eng:"Wearing sackcloth around their waists and ropes around their heads, they went to the king of Israel and said, \"Your servant Ben-Hadad says: 'Please let me live.'\" The king answered, \"Is he still alive? He is my brother.\"",
    Ind:"Lalu mereka melilitkan kain kabung pada pinggang mereka dan tali pada kepala mereka, kemudian mereka pergi menghadap raja Israel sambil berkata: \"Hambamu Benhadad berkata: Kiranya tuanku membiarkan aku hidup.\" Jawabnya: \"Masih hidupkah dia? Dia saudaraku.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:33, Page:1,
    Kor:"그들은 이것을 좋은 징조로 여기고, 얼른 말을 받아서 대답하였다. \"예, 벤하닷은 임금님의 형제입니다.\" 그러자 왕이 말하였다. \"가서 그를 데려오너라.\" 벤하닷이 아합 왕에게 나아오니, 왕은 그를 자기 병거에 올라타게 하였다.",
    Chn:"这些人留心探出他的口气来，便急忙就着他的话说：「便·哈达是王的兄弟！」王说：「你们去请他来。」便·哈达出来见王，王就请他上车。",
    Eng:"The men took this as a good sign and were quick to pick up his word. \"Yes, your brother Ben-Hadad!\" they said. \"Go and get him,\" the king said. When Ben-Hadad came out, Ahab had him come up into his chariot.",
    Ind:"Orang-orang itu menganggap hal itu sebagai tanda yang baik, maka segeralah mereka berpegang pada perkataannya itu, lalu berkata: \"Memang saudaramu Benhadad!\" Sesudah itu berkatalah Ahab: \"Pergilah, ambil dia!\" Jadi keluarlah Benhadad mendapatkan dia, lalu diajak naik ke atas kereta."
  },
  {Bible:"1Kings", Chapter:20, Verse:34, Page:1,
    Kor:"벤하닷은 아합에게 말하였다. \"나의 부친이 왕의 부친에게서 빼앗은 성들을 다 돌려드리겠습니다. 나의 부친이 사마리아 안에 상업 중심지인 광장을 만든 것 같이, 임금님께서도 손수 다마스쿠스 안에 그러한 광장들을 만드십시오.\" 그러자 아합은 \"그러면 나는 그런 조약을 조건으로 하고, 당신을 보내드리겠소\" 하고 말한 뒤에, 그와 조약을 맺고서, 벤하닷을 놓아 주었다.",
    Chn:"便·哈达对王说：「我父从你父那里所夺的城邑，我必归还。你可以在大马士革立街市，像我父在撒马利亚所立的一样。」亚哈说：「我照此立约，放你回去」，就与他立约，放他去了。",
    Eng:"\"I will return the cities my father took from your father,\" Ben-Hadad offered. \"You may set up your own market areas in Damascus, as my father did in Samaria.\" Ahab said,\"On the basis of a treaty I will set you free.\" So he made a treaty with him, and let him go.",
    Ind:"Kata Benhadad kepadanya: \"Kota-kota yang telah diambil bapaku dari pihak bapamu akan kukembalikan; engkau boleh juga membuat pasar bagimu di Damsyik, seperti yang dibuat bapaku di Samaria.\" \"Dan aku sendiri,\" kata Ahab, \"akan membiarkan engkau pergi dengan perjanjian.\" Lalu ia mengadakan perjanjian dengan dia dan membiarkannya pergi."
  },
  {Bible:"1Kings", Chapter:20, Verse:35, Page:1,
    Kor:"<한 예언자가 아합을 규탄하다> ○c예언자의 무리 가운데서 어떤 예언자가 주님의 명령을 받고서, 동료에게 자기를 때리라고 말하였으나, 그 동료가 때리기를 거절하니,(c 히, '예언자의 아들들 가운데서')",
    Chn:"有先知的一个门徒奉耶和华的命对他的同伴说：「你打我吧！」那人不肯打他。",
    Eng:"By the word of the LORD one of the sons of the prophets said to his companion, \"Strike me with your weapon,\" but the man refused.",
    Ind:"Seorang dari rombongan nabi berkata kepada temannya atas perintah TUHAN: \"Pukullah aku!\" Tetapi orang itu menolak memukulnya."
  },
  {Bible:"1Kings", Chapter:20, Verse:36, Page:1,
    Kor:"그 예언자가 말하였다. \"네가 주님의 말씀에 순종하지 않았으니, 네가 나를 떠날 때에 사자가 너를 죽일 것이다.\" 과연 그 사람이 그를 떠날 때에 사자가 나타나서 그를 죽였다.",
    Chn:"他就对那人说：「你既不听从耶和华的话，你一离开我，必有狮子咬死你。」那人一离开他，果然遇见狮子，把他咬死了。",
    Eng:"So the prophet said, \"Because you have not obeyed the LORD, as soon as you leave me a lion will kill you.\" And after the man went away, a lion found him and killed him.",
    Ind:"Lalu ia berkata kepadanya: \"Oleh sebab engkau tidak mendengarkan suara TUHAN, ketahuilah, apabila engkau pergi dari padaku, seekor singa akan menerkam engkau.\" Dan ketika orang itu pergi dari padanya, maka seekor singa bertemu dengan dia, lalu menerkam dia."
  },
  {Bible:"1Kings", Chapter:20, Verse:37, Page:1,
    Kor:"○그 예언자가 또 다른 사람을 만나서, 자기를 때리라고 말하였다. 그러자 그 사람은 예언자를 때려서, 심한 상처를 입혔다.",
    Chn:"先知的门徒又遇见一个人，对他说：「你打我吧！」那人就打他，将他打伤。",
    Eng:"The prophet found another man and said, \"Strike me, please.\" So the man struck him and wounded him.",
    Ind:"Kemudian nabi itu bertemu dengan orang lain, lalu ia berkata: \"Pukullah aku!\" Orang itu memukul dan melukai dia."
  },
  {Bible:"1Kings", Chapter:20, Verse:38, Page:1,
    Kor:"그 예언자는 붕대로 눈을 감아서 위장하고는, 길목으로 가서, 왕을 기다렸다.",
    Chn:"他就去了，用头巾蒙眼，改换面目，在路旁等候王。",
    Eng:"Then the prophet went and stood by the road waiting for the king. He disguised himself with his headband down over his eyes.",
    Ind:"Sesudah itu nabi itu pergi dan berdiri menantikan raja di jalan, sambil menyamar dengan membubuh kain pembalut pada matanya."
  },
  {Bible:"1Kings", Chapter:20, Verse:39, Page:1,
    Kor:"왕이 그대로 지나치려고 하니, 예언자는 왕을 부르며 말하였다. \"임금님의 종인 제가 전쟁터에 갔습니다. 그런데 어떤 사람이 저에게로 포로 한 명을 데리고 와서는, 그 사람을 감시하라고 하였습니다. 포로가 도망을 하면, 제가 대신 죽든지, 아니면 은 한 달란트를 물어 내야 한다고 하였습니다.",
    Chn:"王从那里经过，他向王呼叫说：「仆人在阵上的时候，有人带了一个人来，对我说：『你看守这人，若把他失了，你的性命必代替他的性命；不然，你必交出一他连得银子来。』",
    Eng:"As the king passed by, the prophet called out to him, \"Your servant went into the thick of the battle, and someone came to me with a captive and said, 'Guard this man. If he is missing, it will be your life for his life, or you must pay a talent of silver.'",
    Ind:"Pada waktu raja lewat, ia mengadukan halnya kepada raja, katanya: \"Ketika hambamu ini maju ke tengah pertempuran, tiba-tiba ada seorang meninggalkan barisan dan membawa seorang kepadaku sambil berkata: Jagalah orang ini, jika ia hilang dengan cara bagaimanapun juga, maka nyawamu adalah ganti nyawanya, atau engkau harus membayar setalenta perak."
  },
  {Bible:"1Kings", Chapter:20, Verse:40, Page:1,
    Kor:"그런데 임금님의 종인 소인이 이 일 저 일을 하는 동안에, 그 포로가 없어지고 말았습니다.\" 그러자 이스라엘 왕이 그에게 말하였다. \"네가 받아들인 것이니, 벌금을 물어야 한다.\"",
    Chn:"仆人正在忙乱之间，那人就不见了。」以色列王对他说：「你自己定妥了，必照样判断你。」",
    Eng:"While your servant was busy here and there, the man disappeared.\" \"That is your sentence,\" the king of Israel said. \"You have pronounced it yourself.\"",
    Ind:"Ketika hambamu ini repot sana sini, orang itu menghilang.\" Kemudian raja Israel itu berkata kepadanya: \"Begitu jugalah hukumanmu, engkau sendiri telah menetapkannya.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:41, Page:1,
    Kor:"그 예언자는 그의 눈에 감은 붕대를 급히 풀었다. 그 때에야 이스라엘 왕은, 그가 예언자 가운데 한 사람임을 알았다.",
    Chn:"他急忙除掉蒙眼的头巾，以色列王就认出他是一个先知。",
    Eng:"Then the prophet quickly removed the headband from his eyes, and the king of Israel recognized him as one of the prophets.",
    Ind:"Lalu segeralah ia membuka kain pembalut itu dari matanya, sehingga raja Israel mengenali dia sebagai seorang dari rombongan nabi."
  },
  {Bible:"1Kings", Chapter:20, Verse:42, Page:1,
    Kor:"그 예언자는 왕에게 이렇게 말하였다. \"주님께서 이렇게 말씀하셨습니다. '내가 멸망시키기로 작정한 사람을 네가 직접 놓아 주었으니, 너는 그 목숨을 대신하여서 죽게 될 것이고, 네 백성은 그의 백성을 대신하여서 멸망할 것이다.'\"",
    Chn:"他对王说：「耶和华如此说：『因你将我定要灭绝的人放去，你的命就必代替他的命，你的民也必代替他的民。』」",
    Eng:"He said to the king, \"This is what the LORD says: 'You have set free a man I had determined should die. Therefore it is your life for his life, your people for his people.'\"",
    Ind:"Kata nabi itu kepadanya: \"Beginilah firman TUHAN: Oleh karena engkau telah membiarkan lolos orang yang dikhususkan bagi-Ku untuk ditumpas, maka nyawamu adalah ganti nyawanya dan rakyatmu ganti rakyatnya.\""
  },
  {Bible:"1Kings", Chapter:20, Verse:43, Page:1,
    Kor:"이스라엘 왕은, 마음이 상하여 화를 내면서, 사마리아에 있는 자기의 궁으로 돌아갔다.",
    Chn:"于是以色列王闷闷不乐地回到撒马利亚，进了他的宫。",
    Eng:"Sullen and angry, the king of Israel went to his palace in Samaria.",
    Ind:"Lalu raja Israel pergi ke istananya dengan kesal hati dan gusar, maka sampailah ia di Samaria."
  },
]);
