// 열왕기하 7장 · Kings2 7
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Kings2",7,20);
BibleDB.add([
  {Bible:"Kings2", Chapter:7, Verse:1, Page:1, Kor:"", Chn:"", Eng:"Elisha said, "Hear the word of the LORD. This is what the LORD says: About this time tomorrow, a seah of flour will sell for a shekel and two seahs of barley for a shekel at the gate of Samaria."", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:2, Page:1, Kor:"", Chn:"", Eng:"The officer on whose arm the king was leaning said to the man of God, "Look, even if the LORD should open the floodgates of the heavens, could this happen?" "You will see it with your own eyes," answered Elisha, "but you will not eat any of it!"", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:3, Page:1, Kor:"", Chn:"", Eng:"Now there were four men with leprosy at the entrance of the city gate. They said to each other, "Why stay here until we die?", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:4, Page:1, Kor:"", Chn:"", Eng:"If we say, 'We'll go into the city'--the famine is there, and we will die. And if we stay here, we will die. So let's go over to the camp of the Arameans and surrender. If they spare us, we live; if they kill us, then we die."", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:5, Page:1, Kor:"", Chn:"", Eng:"At dusk they got up and went to the camp of the Arameans. When they reached the edge of the camp, not a man was there,", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:6, Page:1, Kor:"", Chn:"", Eng:"for the Lord had caused the Arameans to hear the sound of chariots and horses and a great army, so that they said to one another, "Look, the king of Israel has hired the Hittite and Egyptian kings to attack us!"", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:7, Page:1, Kor:"", Chn:"", Eng:"So they got up and fled in the dusk and abandoned their tents and their horses and donkeys. They left the camp as it was and ran for their lives.", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:8, Page:1, Kor:"", Chn:"", Eng:"The men who had leprosy reached the edge of the camp and entered one of the tents. They ate and drank, and carried away silver, gold and clothes, and went off and hid them. They returned and entered another tent and took some things from it and hid them also.", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Then they said to each other, "We're not doing right. This is a day of good news and we are keeping it to ourselves. If we wait until daylight, punishment will overtake us. Let's go at once and report this to the royal palace."", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:10, Page:1, Kor:"", Chn:"", Eng:"So they went and called out to the city gatekeepers and told them, "We went into the Aramean camp and not a man was there--not a sound of anyone--only tethered horses and donkeys, and the tents left just as they were."", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:11, Page:1, Kor:"", Chn:"", Eng:"The gatekeepers shouted the news, and it was reported within the palace.", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:12, Page:1, Kor:"", Chn:"", Eng:"The king got up in the night and said to his officers, "I will tell you what the Arameans have done to us. They know we are starving; so they have left the camp to hide in the countryside, thinking, 'They will surely come out, and then we will take them alive and get into the city.'"", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:13, Page:1, Kor:"", Chn:"", Eng:"One of his officers answered, "Have some men take five of the horses that are left in the city. Their plight will be like that of all the Israelites left here--yes, they will only be like all these Israelites who are doomed. So let us send them to find out what happened."", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:14, Page:1, Kor:"", Chn:"", Eng:"So they selected two chariots with their horses, and the king sent them after the Aramean army. He commanded the drivers, "Go and find out what has happened."", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:15, Page:1, Kor:"", Chn:"", Eng:"They followed them as far as the Jordan, and they found the whole road strewn with the clothing and equipment the Arameans had thrown away in their headlong flight. So the messengers returned and reported to the king.", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:16, Page:1, Kor:"", Chn:"", Eng:"Then the people went out and plundered the camp of the Arameans. So a seah of flour sold for a shekel, and two seahs of barley sold for a shekel, as the LORD had said.", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Now the king had put the officer on whose arm he leaned in charge of the gate, and the people trampled him in the gateway, and he died, just as the man of God had foretold when the king came down to his house.", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:18, Page:1, Kor:"", Chn:"", Eng:"It happened as the man of God had said to the king: "About this time tomorrow, a seah of flour will sell for a shekel and two seahs of barley for a shekel at the gate of Samaria."", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:19, Page:1, Kor:"", Chn:"", Eng:"The officer had said to the man of God, "Look, even if the LORD should open the floodgates of the heavens, could this happen?" The man of God had replied, "You will see it with your own eyes, but you will not eat any of it!"", Ind:""},
  {Bible:"Kings2", Chapter:7, Verse:20, Page:1, Kor:"", Chn:"", Eng:"And that is exactly what happened to him, for the people trampled him in the gateway, and he died.", Ind:""},
]);
