// 마가복음 2장 · Mark 2
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Mark",2,28);
BibleDB.add([
  {Bible:"Mark", Chapter:2, Verse:1, Page:1, Kor:"", Chn:"", Eng:"A few days later, when Jesus again entered Capernaum, the people heard that he had come home.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:2, Page:1, Kor:"", Chn:"", Eng:"So many gathered that there was no room left, not even outside the door, and he preached the word to them.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:3, Page:1, Kor:"", Chn:"", Eng:"Some men came, bringing to him a paralytic, carried by four of them.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Since they could not get him to Jesus because of the crowd, they made an opening in the roof above Jesus and, after digging through it, lowered the mat the paralyzed man was lying on.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:5, Page:1, Kor:"", Chn:"", Eng:"When Jesus saw their faith, he said to the paralytic, "Son, your sins are forgiven."", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:6, Page:1, Kor:"", Chn:"", Eng:"Now some teachers of the law were sitting there, thinking to themselves,", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:7, Page:1, Kor:"", Chn:"", Eng:""Why does this fellow talk like that? He's blaspheming! Who can forgive sins but God alone?"", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Immediately Jesus knew in his spirit that this was what they were thinking in their hearts, and he said to them, "Why are you thinking these things?", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Which is easier: to say to the paralytic, 'Your sins are forgiven,' or to say, 'Get up, take your mat and walk'?", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:10, Page:1, Kor:"", Chn:"", Eng:"But that you may know that the Son of Man has authority on earth to forgive sins...." He said to the paralytic,", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:11, Page:1, Kor:"", Chn:"", Eng:""I tell you, get up, take your mat and go home."", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:12, Page:1, Kor:"", Chn:"", Eng:"He got up, took his mat and walked out in full view of them all. This amazed everyone and they praised God, saying, "We have never seen anything like this!"", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Once again Jesus went out beside the lake. A large crowd came to him, and he began to teach them.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:14, Page:1, Kor:"", Chn:"", Eng:"As he walked along, he saw Levi son of Alphaeus sitting at the tax collector's booth. "Follow me," Jesus told him, and Levi got up and followed him.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:15, Page:1, Kor:"", Chn:"", Eng:"While Jesus was having dinner at Levi's house, many tax collectors and "sinners" were eating with him and his disciples, for there were many who followed him.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:16, Page:1, Kor:"", Chn:"", Eng:"When the teachers of the law who were Pharisees saw him eating with the "sinners" and tax collectors, they asked his disciples: "Why does he eat with tax collectors and 'sinners'?"", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:17, Page:1, Kor:"", Chn:"", Eng:"On hearing this, Jesus said to them, "It is not the healthy who need a doctor, but the sick. I have not come to call the righteous, but sinners."", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:18, Page:1, Kor:"", Chn:"", Eng:"Now John's disciples and the Pharisees were fasting. Some people came and asked Jesus, "How is it that John's disciples and the disciples of the Pharisees are fasting, but yours are not?"", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Jesus answered, "How can the guests of the bridegroom fast while he is with them? They cannot, so long as they have him with them.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:20, Page:1, Kor:"", Chn:"", Eng:"But the time will come when the bridegroom will be taken from them, and on that day they will fast.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:21, Page:1, Kor:"", Chn:"", Eng:""No one sews a patch of unshrunk cloth on an old garment. If he does, the new piece will pull away from the old, making the tear worse.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:22, Page:1, Kor:"", Chn:"", Eng:"And no one pours new wine into old wineskins. If he does, the wine will burst the skins, and both the wine and the wineskins will be ruined. No, he pours new wine into new wineskins."", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:23, Page:1, Kor:"", Chn:"", Eng:"One Sabbath Jesus was going through the grainfields, and as his disciples walked along, they began to pick some heads of grain.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:24, Page:1, Kor:"", Chn:"", Eng:"The Pharisees said to him, "Look, why are they doing what is unlawful on the Sabbath?"", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:25, Page:1, Kor:"", Chn:"", Eng:"He answered, "Have you never read what David did when he and his companions were hungry and in need?", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:26, Page:1, Kor:"", Chn:"", Eng:"In the days of Abiathar the high priest, he entered the house of God and ate the consecrated bread, which is lawful only for priests to eat. And he also gave some to his companions."", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Then he said to them, "The Sabbath was made for man, not man for the Sabbath.", Ind:""},
  {Bible:"Mark", Chapter:2, Verse:28, Page:1, Kor:"", Chn:"", Eng:"So the Son of Man is Lord even of the Sabbath."", Ind:""},
]);
