// 마가복음 16장 · Mark 16
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Mark",16,20);
BibleDB.add([
  {Bible:"Mark", Chapter:16, Verse:1, Page:1, Kor:"<예수께서 부활하시다(마 28:1-8; 눅 24:1-12; 요 20:1-10)> 안식일이 지났을 때에, 막달라 마리아와 야고보의 어머니 마리아와 살로메는 가서 예수께 발라 드리려고 향료를 샀다.", Chn:"", Eng:"When the Sabbath was over, Mary Magdalene, Mary the mother of James, and Salome bought spices so that they might go to anoint Jesus' body.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:2, Page:1, Kor:"그래서 a이레의 첫날 새벽, 해가 막 돋은 때에, 무덤으로 갔다.(a 또는 '안식일 첫날')", Chn:"", Eng:"Very early on the first day of the week, just after sunrise, they were on their way to the tomb", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:3, Page:1, Kor:"그들은 \"누가 우리를 위하여 그 돌을 무덤 어귀에서 굴려내 주겠는가?\" 하고 서로 말하였다.", Chn:"", Eng:"and they asked each other, \"Who will roll the stone away from the entrance of the tomb?\"", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:4, Page:1, Kor:"그런데 눈을 들어서 보니, 그 돌덩이는 이미 굴려져 있었다. 그 돌은 엄청나게 컸다.", Chn:"", Eng:"But when they looked up, they saw that the stone, which was very large, had been rolled away.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:5, Page:1, Kor:"그 여자들은 무덤 안으로 들어가서, 웬 젊은 남자가 흰 옷을 입고 오른쪽에 앉아 있는 것을 보고 몹시 놀랐다.", Chn:"", Eng:"As they entered the tomb, they saw a young man dressed in a white robe sitting on the right side, and they were alarmed.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:6, Page:1, Kor:"그가 여자들에게 말하였다. \"놀라지 마시오. 그대들은 십자가에 못박히신 나사렛 사람 예수를 찾고 있지만, 그는 살아나셨소. 그는 여기에 계시지 않소. 보시오, 그를 안장했던 곳이오.", Chn:"", Eng:"\"Don't be alarmed,\" he said. \"You are looking for Jesus the Nazarene, who was crucified. He has risen! He is not here. See the place where they laid him.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:7, Page:1, Kor:"그러니 그대들은 가서, 그의 제자들과 베드로에게 말하기를 그는 그들보다 먼저 갈릴리로 가실 것이니, 그가 그들에게 말씀하신 대로, 그들은 거기에서 그를 볼 것이라고 하시오.\"", Chn:"", Eng:"But go, tell his disciples and Peter, 'He is going ahead of you into Galilee. There you will see him, just as he told you.'\"", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:8, Page:1, Kor:"그들은 뛰쳐 나와서, 무덤에서 도망하였다. 그들은 벌벌 떨며 넋을 잃었던 것이다. 그들은 무서워서, 아무에게도 아무 말도 못하였다.b(b 권위를 인정받는 대다수의 고대 사본들은, 8절에서 마가복음서가 끝남. 권위를 인정받는 한 사본은 8절 끝에 '짧은 끝맺음'(9절의 주를 볼 것)을 가지고 있음. 다른 사본들은 '짧은 끝맺음'과 함께 9-20절의 '긴 끝맺음'도 함께 반영하고 41 16:있음. 그러나 다른 고대 사본들 대다수는 8절 뒤에 곧바로 9-20절의 '긴 끝맺음'을 기록하였음)", Chn:"", Eng:"Trembling and bewildered, the women went out and fled from the tomb. They said nothing to anyone, because they were afraid.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:9, Page:1, Kor:"<예수께서 막달라 마리아에게 나타나시다(마 28:9-10; 요 20:11-18)> ○c<예수께서 이레의 첫날 새벽에 살아나신 뒤에, 맨 처음으로 막달라 마리아에게 나타나셨다. 마리아는 예수께서 일곱 귀신을 쫓아내 주신 여자이다.(c '마가복음서의 긴 끝맺음'(16:9-20). 이 긴 끝맺음 대신에 '마가복음서의 짧은 끝맺음'만을 가진 사본들도 있다. '그 여자들은 명령 받은 모든 41 16:일을 베드로와 그와 함께 있는 사람들에게 간추려서 말해 주었다. 그 뒤에 예수께서는 친히 그들을 시켜서, 동에서 서에 이르기까지, 영원한 구원을 담은, 성스러우며 없어지지 않는 복음을 퍼져나가게 하셨다')", Chn:"", Eng:"When Jesus rose early on the first day of the week, he appeared first to Mary Magdalene, out of whom he had driven seven demons.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:10, Page:1, Kor:"마리아는 예수와 함께 지내던 사람들이 슬퍼하며 울고 있는 곳으로 가서, 그들에게 이 소식을 전하였다.", Chn:"", Eng:"She went and told those who had been with him and who were mourning and weeping.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:11, Page:1, Kor:"그러나 그들은, 예수가 살아 계시다는 것과, 마리아가 예수를 목격했다는 말을 듣고서도, 믿지 않았다.", Chn:"", Eng:"When they heard that Jesus was alive and that she had seen him, they did not believe it.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:12, Page:1, Kor:"<예수께서 두 제자에게 나타나시다(눅 24:13-35)> ○그 뒤에 그들 가운데 두 사람이 걸어서 시골로 내려가는데, 예수께서는 다른 모습으로 그들에게 나타나셨다.", Chn:"", Eng:"Afterward Jesus appeared in a different form to two of them while they were walking in the country.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:13, Page:1, Kor:"그들은 다른 제자들에게 되돌아가서 알렸으나, 제자들은 그들의 말도 믿지 않았다.", Chn:"", Eng:"These returned and reported it to the rest; but they did not believe them either.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:14, Page:1, Kor:"<제자들이 선교의 사명을 받다(마 28:16-20; 눅 24:36-49; 요 20:19-23; 행 1:6-8)> ○그 뒤에 d열한 제자가 음식을 먹을 때에, 예수께서는 그들에게 나타나셔서, 그들이 믿음이 없고 마음이 무딘 것을 꾸짖으셨다. 그들이, 자기가 살아난 것을 본 사람들의 말을 믿지 않았기 때문이다.(d 그, '열한 명이')", Chn:"", Eng:"Later Jesus appeared to the Eleven as they were eating; he rebuked them for their lack of faith and their stubborn refusal to believe those who had seen him after he had risen.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:15, Page:1, Kor:"또 예수께서 그들에게 말씀하셨다. \"너희는 온 세상에 나가서, 만민에게 e복음을 전파하여라.(e 또는 '기쁜 소식')", Chn:"", Eng:"He said to them, \"Go into all the world and preach the good news to all creation.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:16, Page:1, Kor:"믿고 f세례를 받는 사람은 구원을 얻을 것이요, 믿지 않는 사람은 정죄를 받을 것이다.(f 또는 '침례')", Chn:"", Eng:"Whoever believes and is baptized will be saved, but whoever does not believe will be condemned.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:17, Page:1, Kor:"믿는 사람들에게는 이런 표징들이 따를 터인데, 곧 그들은 내 이름으로 귀신을 쫓아내며, 새 방언으로 말하며,", Chn:"", Eng:"And these signs will accompany those who believe: In my name they will drive out demons; they will speak in new tongues;", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:18, Page:1, Kor:"손으로 뱀을 집어들며, 독약을 마실지라도 절대로 해를 입지 않으며, 아픈 사람들에게 손을 얹으면 나을 것이다.\"", Chn:"", Eng:"they will pick up snakes with their hands; and when they drink deadly poison, it will not hurt them at all; they will place their hands on sick people, and they will get well.\"", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:19, Page:1, Kor:"<예수의 승천(눅 24:50-53; 행 1:9-11)> ○주 예수께서 그들에게 말씀하신 뒤에, 하늘로 들려 올라가셔서, 하나님의 오른쪽에 앉으셨다.", Chn:"", Eng:"After the Lord Jesus had spoken to them, he was taken up into heaven and he sat at the right hand of God.", Ind:""},
  {Bible:"Mark", Chapter:16, Verse:20, Page:1, Kor:"그들은 나가서, 곳곳에서 복음을 전파하였다. 주님께서 그들과 함께 일하시고, 여러 가지 표징이 따르게 하셔서, 말씀을 확증하여 주셨다.>>g(g 다른 고대 사본들에는 '아멘'이 첨가되어 있음)", Chn:"", Eng:"", Ind:""},
]);
