// 마가복음 11장 · Mark 11
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Mark",11,33);
BibleDB.add([
  {Bible:"Mark", Chapter:11, Verse:1, Page:1,
    Kor:"<예루살렘에 입성하시다(마 21:1-11; 눅 19:28-40; 요 12:12-19)> 그들이 예루살렘 가까이에, 곧 올리브 산에 있는 벳바게와 베다니 가까이에 이르렀을 때에, 예수께서 제자 둘을 보내시며,",
    Chn:"耶稣和门徒将近耶路撒冷，到了伯法其和伯大尼，在橄榄山那里；耶稣就打发两个门徒，",
    Eng:"As they approached Jerusalem and came to Bethphage and Bethany at the Mount of Olives, Jesus sent two of his disciples,",
    Ind:"Ketika Yesus dan murid-murid-Nya telah dekat Yerusalem, dekat Betfage dan Betania yang terletak di Bukit Zaitun, Yesus menyuruh dua orang murid-Nya"
  },
  {Bible:"Mark", Chapter:11, Verse:2, Page:1,
    Kor:"그들에게 말씀하셨다. \"너희는 맞은편 마을로 가거라. 거기에 들어가서 보면, 아직 아무도 탄 적이 없는 새끼 나귀 한 마리가 매여 있을 것이다. 그것을 풀어서 끌고 오너라.",
    Chn:"对他们说：「你们往对面村子里去，一进去的时候，必看见一匹驴驹拴在那里，是从来没有人骑过的，可以解开，牵来。",
    Eng:"saying to them, \"Go to the village ahead of you, and just as you enter it, you will find a colt tied there, which no one has ever ridden. Untie it and bring it here.",
    Ind:"dengan pesan: \"Pergilah ke kampung yang di depanmu itu. Pada waktu kamu masuk di situ, kamu akan segera menemukan seekor keledai muda tertambat, yang belum pernah ditunggangi orang. Lepaskan keledai itu dan bawalah ke mari."
  },
  {Bible:"Mark", Chapter:11, Verse:3, Page:1,
    Kor:"어느 누가 '왜 이러는 거요?' 하고 물으면 '주님께서 쓰시려고 하십니다. 쓰시고 나면, 지체없이 이리로 돌려보내실 것입니다' 하고 말하여라.\"",
    Chn:"若有人对你们说：『为什么做这事？』你们就说：『主要用它。』那人必立时让你们牵来。」",
    Eng:"If anyone asks you, 'Why are you doing this?' tell him, 'The Lord needs it and will send it back here shortly.'\"",
    Ind:"Dan jika ada orang mengatakan kepadamu: Mengapa kamu lakukan itu, jawablah: Tuhan memerlukannya. Ia akan segera mengembalikannya ke sini.\""
  },
  {Bible:"Mark", Chapter:11, Verse:4, Page:1,
    Kor:"그들은 가서, 새끼 나귀가 바깥 길 쪽으로 나 있는 문에 매여 있는 것을 보고, 그것을 풀었다.",
    Chn:"他们去了，便看见一匹驴驹拴在门外街道上，就把它解开。",
    Eng:"They went and found a colt outside in the street, tied at a doorway. As they untied it,",
    Ind:"Merekapun pergi, dan menemukan seekor keledai muda tertambat di depan pintu di luar, di pinggir jalan, lalu melepaskannya."
  },
  {Bible:"Mark", Chapter:11, Verse:5, Page:1,
    Kor:"거기에 서 있는 사람들 가운데 몇 사람이 그들에게 물었다. \"새끼 나귀를 풀다니, 무슨 짓이오?\"",
    Chn:"在那里站着的人，有几个说：「你们解驴驹做什么？」",
    Eng:"some people standing there asked, \"What are you doing, untying that colt?\"",
    Ind:"Dan beberapa orang yang ada di situ berkata kepada mereka: \"Apa maksudnya kamu melepaskan keledai itu?\""
  },
  {Bible:"Mark", Chapter:11, Verse:6, Page:1,
    Kor:"제자들은 예수께서 일러주신 대로 그들에게 말하였다. 그러자 그들은 가만히 있었다.",
    Chn:"门徒照着耶稣所说的回答，那些人就任凭他们牵去了。",
    Eng:"They answered as Jesus had told them to, and the people let them go.",
    Ind:"Lalu mereka menjawab seperti yang sudah dikatakan Yesus. Maka orang-orang itu membiarkan mereka."
  },
  {Bible:"Mark", Chapter:11, Verse:7, Page:1,
    Kor:"제자들이 그 새끼 나귀를 예수께로 끌고 와서, 자기들의 겉옷을 그 등에 걸쳐놓으니, 예수께서 그 위에 올라 타셨다.",
    Chn:"他们把驴驹牵到耶稣那里，把自己的衣服搭在上面，耶稣就骑上。",
    Eng:"When they brought the colt to Jesus and threw their cloaks over it, he sat on it.",
    Ind:"Lalu mereka membawa keledai itu kepada Yesus, dan mengalasinya dengan pakaian mereka, kemudian Yesus naik ke atasnya."
  },
  {Bible:"Mark", Chapter:11, Verse:8, Page:1,
    Kor:"많은 사람이 자기들의 겉옷을 길에다 폈으며, 다른 사람들은 들에서 잎 많은 생나무 가지들을 꺾어다가 길에다 깔았다.",
    Chn:"有许多人把衣服铺在路上，也有人把田间的树枝砍下来，铺在路上。",
    Eng:"Many people spread their cloaks on the road, while others spread branches they had cut in the fields.",
    Ind:"Banyak orang yang menghamparkan pakaiannya di jalan, ada pula yang menyebarkan ranting-ranting hijau yang mereka ambil dari ladang."
  },
  {Bible:"Mark", Chapter:11, Verse:9, Page:1,
    Kor:"그리고 앞에 서서 가는 사람들과 뒤따르는 사람들이 외쳤다.  a\"b호산나!\" \"복되시다! 주님의 이름으로 오시는 분!\" (a 시 118:25, 26 b '구하여 주십시오!'라는 뜻을 지닌 히브리어. 여기에는 찬양의 감탄으로 사용됨)",
    Chn:"前行后随的人都喊着说： 和散那！ 奉主名来的是应当称颂的！",
    Eng:"Those who went ahead and those who followed shouted, \"Hosanna!\" \"Blessed is he who comes in the name of the Lord!\"",
    Ind:"Orang-orang yang berjalan di depan dan mereka yang mengikuti dari belakang berseru: \"Hosana! Diberkatilah Dia yang datang dalam nama Tuhan,"
  },
  {Bible:"Mark", Chapter:11, Verse:10, Page:1,
    Kor:"\"복되다! 다가오는 우리 조상 다윗의 나라여!\" \"더 없이 높은 곳에서, 호산나!\"",
    Chn:"那将要来的我祖大卫之国是应当称颂的！ 高高在上和散那！",
    Eng:"\"Blessed is the coming kingdom of our father David!\" \"Hosanna in the highest!\"",
    Ind:"diberkatilah Kerajaan yang datang, Kerajaan bapak kita Daud, hosana di tempat yang maha tinggi!\""
  },
  {Bible:"Mark", Chapter:11, Verse:11, Page:1,
    Kor:"예수께서 예루살렘에 이르러 성전에 들어가셨다. 그는 거기서 모든 것을 둘러보신 뒤에, 날이 이미 저물었으므로, 열두 제자와 함께 베다니로 나가셨다.",
    Chn:"耶稣进了耶路撒冷，入了圣殿，周围看了各样物件。天色已晚，就和十二个门徒出城，往伯大尼去了。",
    Eng:"Jesus entered Jerusalem and went to the temple. He looked around at everything, but since it was already late, he went out to Bethany with the Twelve.",
    Ind:"Sesampainya di Yerusalem Ia masuk ke Bait Allah. Di sana Ia meninjau semuanya, tetapi sebab hari sudah hampir malam Ia keluar ke Betania bersama dengan kedua belas murid-Nya."
  },
  {Bible:"Mark", Chapter:11, Verse:12, Page:1,
    Kor:"<무화과나무를 저주하시다(마 21:18-19)> ○이튿날 그들이 베다니를 떠나갈 때에, 예수께서는 시장하셨다.",
    Chn:"第二天，他们从伯大尼出来，耶稣饿了。",
    Eng:"The next day as they were leaving Bethany, Jesus was hungry.",
    Ind:"Keesokan harinya sesudah Yesus dan kedua belas murid-Nya meninggalkan Betania, Yesus merasa lapar."
  },
  {Bible:"Mark", Chapter:11, Verse:13, Page:1,
    Kor:"멀리서 잎이 무성한 무화과나무를 보시고, 혹시 그 나무에 열매가 있을까 하여 가까이 가서 보셨는데, 잎사귀 밖에는 아무것도 없었다. 무화과의 철이 아니었기 때문이다.",
    Chn:"远远地看见一棵无花果树，树上有叶子，就往那里去，或者在树上可以找着什么。到了树下，竟找不着什么，不过有叶子，因为不是收无花果的时候。",
    Eng:"Seeing in the distance a fig tree in leaf, he went to find out if it had any fruit. When he reached it, he found nothing but leaves, because it was not the season for figs.",
    Ind:"Dan dari jauh Ia melihat pohon ara yang sudah berdaun. Ia mendekatinya untuk melihat kalau-kalau Ia mendapat apa-apa pada pohon itu. Tetapi waktu Ia tiba di situ, Ia tidak mendapat apa-apa selain daun-daun saja, sebab memang bukan musim buah ara."
  },
  {Bible:"Mark", Chapter:11, Verse:14, Page:1,
    Kor:"예수께서 그 나무에게 말씀하셨다. \"이제부터 영원히, 네게서 열매를 따먹을 사람이 없을 것이다.\" 제자들이 예수께서 말씀하시는 것을 들었다.",
    Chn:"耶稣就对树说：「从今以后，永没有人吃你的果子。」他的门徒也听见了。",
    Eng:"Then he said to the tree, \"May no one ever eat fruit from you again.\" And his disciples heard him say it.",
    Ind:"Maka kata-Nya kepada pohon itu: \"Jangan lagi seorangpun makan buahmu selama-lamanya!\" Dan murid-murid-Nyapun mendengarnya."
  },
  {Bible:"Mark", Chapter:11, Verse:15, Page:1,
    Kor:"<성전을 깨끗하게 하시다(마 21:12-17; 눅 19:45-48; 요 2:13-22)> ○그리고 그들은 예루살렘에 들어갔다. 예수께서 성전에 들어가셔서, c성전 뜰에서 팔고 사고 하는 사람들을 내쫓으시면서 돈을 바꾸어 주는 사람들의 상과 비둘기를 파는 사람들의 의자를 둘러엎으시고,(c 그, '성전에서' 곧 '성전 바깥 뜰에서')",
    Chn:"他们来到耶路撒冷。耶稣进入圣殿，赶出殿里做买卖的人，推倒兑换银钱之人的桌子和卖鸽子之人的凳子；",
    Eng:"On reaching Jerusalem, Jesus entered the temple area and began driving out those who were buying and selling there. He overturned the tables of the money changers and the benches of those selling doves,",
    Ind:"Lalu tibalah Yesus dan murid-murid-Nya di Yerusalem. Sesudah Yesus masuk ke Bait Allah, mulailah Ia mengusir orang-orang yang berjual beli di halaman Bait Allah. Meja-meja penukar uang dan bangku-bangku pedagang merpati dibalikkan-Nya,"
  },
  {Bible:"Mark", Chapter:11, Verse:16, Page:1,
    Kor:"d성전 뜰을 가로질러 물건을 나르는 것을 금하셨다.(d 그, '성전 바깥 뜰을')",
    Chn:"也不许人拿着器具从殿里经过；",
    Eng:"and would not allow anyone to carry merchandise through the temple courts.",
    Ind:"dan Ia tidak memperbolehkan orang membawa barang-barang melintasi halaman Bait Allah."
  },
  {Bible:"Mark", Chapter:11, Verse:17, Page:1,
    Kor:"예수께서는 가르치시면서, 그들에게 말씀하셨다. e\"기록한 바  '내 집은 만민이 기도하는 집이라고 불릴 것이다' 하지 않았느냐? 그런데 너희는 그 곳을 f'강도들의 소굴'로 만들어 버렸다.\" (e 사 56:7 f 렘 7:11)",
    Chn:"便教训他们说：「经上不是记着说： 我的殿必称为万国祷告的殿吗？ 你们倒使它成为贼窝了。」",
    Eng:"And as he taught them, he said, \"Is it not written: \"'My house will be called a house of prayer for all nations'? But you have made it 'a den of robbers.'\"",
    Ind:"Lalu Ia mengajar mereka, kata-Nya: \"Bukankah ada tertulis: Rumah-Ku akan disebut rumah doa bagi segala bangsa? Tetapi kamu ini telah menjadikannya sarang penyamun!\""
  },
  {Bible:"Mark", Chapter:11, Verse:18, Page:1,
    Kor:"대제사장들과 율법학자들이 이 말씀을 듣고서는, 어떻게 예수를 없애 버릴까 하고 방도를 찾고 있었다. 그들은 예수를 두려워하고 있었던 것이다. 무리가 다 예수의 가르침에 놀라고 있었기 때문이다.",
    Chn:"祭司长和文士听见这话，就想法子要除灭耶稣，却又怕他，因为众人都希奇他的教训。",
    Eng:"The chief priests and the teachers of the law heard this and began looking for a way to kill him, for they feared him, because the whole crowd was amazed at his teaching.",
    Ind:"Imam-imam kepala dan ahli-ahli Taurat mendengar tentang peristiwa itu, dan mereka berusaha untuk membinasakan Dia, sebab mereka takut kepada-Nya, melihat seluruh orang banyak takjub akan pengajaran-Nya."
  },
  {Bible:"Mark", Chapter:11, Verse:19, Page:1,
    Kor:"저녁때가 되면, g예수와 제자들은 으레 성 밖으로 나갔다.(g 그, '그들은'. 다른 고대 사본들에는 '그는')",
    Chn:"每天晚上，耶稣出城去。",
    Eng:"When evening came, they went out of the city.",
    Ind:"Menjelang malam mereka keluar lagi dari kota."
  },
  {Bible:"Mark", Chapter:11, Verse:20, Page:1,
    Kor:"<무화과나무가 마르다(마 21:20-22)> ○이른 아침에 그들이 지나가다가, 그 무화과나무가 뿌리째 말라 버린 것을 보았다.",
    Chn:"早晨，他们从那里经过，看见无花果树连根都枯干了。",
    Eng:"In the morning, as they went along, they saw the fig tree withered from the roots.",
    Ind:"Pagi-pagi ketika Yesus dan murid-murid-Nya lewat, mereka melihat pohon ara tadi sudah kering sampai ke akar-akarnya."
  },
  {Bible:"Mark", Chapter:11, Verse:21, Page:1,
    Kor:"그래서 베드로가 전날 일이 생각나서 예수께 말하였다. \"h랍비님, 저것 좀 보십시오, 선생님이 저주하신 저 무화과나무가 말라 버렸습니다.\"",
    Chn:"彼得想起耶稣的话来，就对他说：「拉比，请看！你所咒诅的无花果树已经枯干了。」",
    Eng:"Peter remembered and said to Jesus, \"Rabbi, look! The fig tree you cursed has withered!\"",
    Ind:"Maka teringatlah Petrus akan apa yang telah terjadi, lalu ia berkata kepada Yesus: \"Rabi, lihatlah, pohon ara yang Kaukutuk itu sudah kering.\""
  },
  {Bible:"Mark", Chapter:11, Verse:22, Page:1,
    Kor:"예수께서는 그들에게 말씀하셨다. \"하나님을 믿어라.(h '스승')",
    Chn:"耶稣回答说：「你们当信服　神。",
    Eng:"\"Have faith in God,\" Jesus answered.",
    Ind:"Yesus menjawab mereka: \"Percayalah kepada Allah!"
  },
  {Bible:"Mark", Chapter:11, Verse:23, Page:1,
    Kor:"내가 진정으로 너희에게 말한다. 누구든지 이 산더러 '번쩍 들려서 바다에 빠져라' 하고 말하고, 마음에 의심하지 않고 말한 대로 될 것을 믿으면, 그대로 이루어질 것이다.",
    Chn:"我实在告诉你们，无论何人对这座山说：『你挪开此地，投在海里！』他若心里不疑惑，只信他所说的必成，就必给他成了。",
    Eng:"\"I tell you the truth, if anyone says to this mountain, 'Go, throw yourself into the sea,' and does not doubt in his heart but believes that what he says will happen, it will be done for him.",
    Ind:"Aku berkata kepadamu: Sesungguhnya barangsiapa berkata kepada gunung ini: Beranjaklah dan tercampaklah ke dalam laut! asal tidak bimbang hatinya, tetapi percaya, bahwa apa yang dikatakannya itu akan terjadi, maka hal itu akan terjadi baginya."
  },
  {Bible:"Mark", Chapter:11, Verse:24, Page:1,
    Kor:"그러므로 나는 너희에게 말한다. 너희가 기도하면서 구하는 것은 무엇이든지, 이미 그것을 받은 줄로 믿어라. 그리하면, 너희에게 그대로 이루어질 것이다.",
    Chn:"所以我告诉你们，凡你们祷告祈求的，无论是什么，只要信是得着的，就必得着。",
    Eng:"Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.",
    Ind:"Karena itu Aku berkata kepadamu: apa saja yang kamu minta dan doakan, percayalah bahwa kamu telah menerimanya, maka hal itu akan diberikan kepadamu."
  },
  {Bible:"Mark", Chapter:11, Verse:25, Page:1,
    Kor:"○너희가 서서 기도할 때에, 어떤 사람과 서로 등진 일이 있으면, 용서하여라. 그래야, 하늘에 계신 너희 아버지께서도 너희의 잘못을 용서해 주실 것이다.\"",
    Chn:"你们站着祷告的时候，若想起有人得罪你们，就当饶恕他，好叫你们在天上的父也饶恕你们的过犯。",
    Eng:"And when you stand praying, if you hold anything against anyone, forgive him, so that your Father in heaven may forgive you your sins.\"",
    Ind:"Dan jika kamu berdiri untuk berdoa, ampunilah dahulu sekiranya ada barang sesuatu dalam hatimu terhadap seseorang, supaya juga Bapamu yang di sorga mengampuni kesalahan-kesalahanmu.\""
  },
  {Bible:"Mark", Chapter:11, Verse:26, Page:1,
    Kor:"i(26절 없음)(i 다른 고대 사본들에는 '26. 만일 너희가 용서해 주지 않으면 하늘에 계신 너희의 아버지께서도 너희의 잘못을 용서해 주지 않으실 것이다')",
    Chn:"你们若不饶恕人，你们在天上的父也不饶恕你们的过犯。」",
    Eng:"",
    Ind:"(Tetapi jika kamu tidak mengampuni, maka Bapamu yang di sorga juga tidak akan mengampuni kesalahan-kesalahanmu.)"
  },
  {Bible:"Mark", Chapter:11, Verse:27, Page:1,
    Kor:"<예수의 권한을 두고 논란하다(마 21:23-27; 눅 20:1-8)> ○그들은 다시 예루살렘에 들어갔다. 예수께서 c성전 뜰에서 거닐고 계실 때에, 대제사장들과 율법학자들과 장로들이 예수께로 와서(c 그, '성전에서' 곧 '성전 바깥 뜰에서')",
    Chn:"他们又来到耶路撒冷。耶稣在殿里行走的时候，祭司长和文士并长老进前来，",
    Eng:"They arrived again in Jerusalem, and while Jesus was walking in the temple courts, the chief priests, the teachers of the law and the elders came to him.",
    Ind:"Lalu Yesus dan murid-murid-Nya tiba pula di Yerusalem. Ketika Yesus berjalan di halaman Bait Allah, datanglah kepada-Nya imam-imam kepala, ahli-ahli Taurat dan tua-tua,"
  },
  {Bible:"Mark", Chapter:11, Verse:28, Page:1,
    Kor:"물었다. \"당신은 무슨 권한으로 이런 일을 합니까? 누가 당신에게 이런 일을 할 수 있는 권한을 주었습니까?\"",
    Chn:"问他说：「你仗着什么权柄做这些事？给你这权柄的是谁呢？」",
    Eng:"\"By what authority are you doing these things?\" they asked. \"And who gave you authority to do this?\"",
    Ind:"dan bertanya kepada-Nya: \"Dengan kuasa manakah Engkau melakukan hal-hal itu? Dan siapakah yang memberikan kuasa itu kepada-Mu, sehingga Engkau melakukan hal-hal itu?\""
  },
  {Bible:"Mark", Chapter:11, Verse:29, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"나도 너희에게 한 가지를 물어 보겠으니, 나에게 대답해 보아라. 그러면 내가 무슨 권한으로 이런 일을 하는지를 너희에게 말하겠다.",
    Chn:"耶稣对他们说：「我要问你们一句话，你们回答我，我就告诉你们我仗着什么权柄做这些事。",
    Eng:"Jesus replied, \"I will ask you one question. Answer me, and I will tell you by what authority I am doing these things.",
    Ind:"Jawab Yesus kepada mereka: \"Aku akan mengajukan satu pertanyaan kepadamu. Berikanlah Aku jawabnya, maka Aku akan mengatakan kepadamu dengan kuasa manakah Aku melakukan hal-hal itu."
  },
  {Bible:"Mark", Chapter:11, Verse:30, Page:1,
    Kor:"요한의 j세례가 하늘에서 온 것이냐, 사람에게서 온 것이냐? 내게 대답해 보아라.\"(j 또는 '침례')",
    Chn:"约翰的洗礼是从天上来的？是从人间来的呢？你们可以回答我。」",
    Eng:"John's baptism--was it from heaven, or from men? Tell me!\"",
    Ind:"Baptisan Yohanes itu, dari sorga atau dari manusia? Berikanlah Aku jawabnya!\""
  },
  {Bible:"Mark", Chapter:11, Verse:31, Page:1,
    Kor:"그들은 자기들끼리 의논하며 말하였다. \"'하늘에서 왔다'고 말하면 '어찌하여 그를 믿지 않았느냐'고 할 것이다.",
    Chn:"他们彼此商议说：「我们若说『从天上来』，他必说：『这样，你们为什么不信他呢？』",
    Eng:"They discussed it among themselves and said, \"If we say, 'From heaven,' he will ask, 'Then why didn't you believe him?'",
    Ind:"Mereka memperbincangkannya di antara mereka, dan berkata: \"Jikalau kita katakan: Dari sorga, Ia akan berkata: Kalau begitu, mengapakah kamu tidak percaya kepadanya?"
  },
  {Bible:"Mark", Chapter:11, Verse:32, Page:1,
    Kor:"그렇다고 해서 '사람에게서 왔다'고 대답할 수도 없지 않은가?\" 그들은 무리를 무서워하고 있었다. 무리가 모두 요한을 참 예언자로 알고 있었기 때문이었다.",
    Chn:"若说『从人间来』，却又怕百姓，因为众人真以约翰为先知。」",
    Eng:"But if we say, 'From men'....\" (They feared the people, for everyone held that John really was a prophet.)",
    Ind:"Tetapi, masakan kita katakan: Dari manusia!\" Sebab mereka takut kepada orang banyak, karena semua orang menganggap bahwa Yohanes betul-betul seorang nabi."
  },
  {Bible:"Mark", Chapter:11, Verse:33, Page:1,
    Kor:"그래서 그들이 예수께 대답하였다. \"모르겠습니다.\" 예수께서 그들에게 말씀하셨다. \"나도 내가 무슨 권한으로 이런 일을 하는지를 너희에게 말하지 않겠다.\"",
    Chn:"于是回答耶稣说：「我们不知道。」耶稣说：「我也不告诉你们我仗着什么权柄做这些事。」",
    Eng:"So they answered Jesus, \"We don't know.\" Jesus said, \"Neither will I tell you by what authority I am doing these things.\"",
    Ind:"Lalu mereka menjawab Yesus: \"Kami tidak tahu.\" Maka kata Yesus kepada mereka: \"Jika demikian, Aku juga tidak mengatakan kepadamu dengan kuasa manakah Aku melakukan hal-hal itu.\""
  },
]);
