// 마가복음 13장 · Mark 13
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Mark",13,37);
BibleDB.add([
  {Bible:"Mark", Chapter:13, Verse:1, Page:1,
    Kor:"<성전이 무너질 것을 예언하시다(마 24:1-2; 눅 21:5-6)> 예수께서 성전을 떠나가실 때에, 제자들 가운데서 한 사람이 예수께 말하였다. \"선생님, 보십시오! 얼마나 굉장한 돌입니까! 얼마나 굉장한 건물들입니까!\"",
    Chn:"耶稣从殿里出来的时候，有一个门徒对他说：「夫子，请看，这是何等的石头！何等的殿宇！」",
    Eng:"As he was leaving the temple, one of his disciples said to him, \"Look, Teacher! What massive stones! What magnificent buildings!\"",
    Ind:"Ketika Yesus keluar dari Bait Allah, seorang murid-Nya berkata kepada-Nya: \"Guru, lihatlah betapa kokohnya batu-batu itu dan betapa megahnya gedung-gedung itu!\""
  },
  {Bible:"Mark", Chapter:13, Verse:2, Page:1,
    Kor:"예수께서 그에게 말씀하셨다. \"너는 이 큰 건물들을 보고 있느냐? 여기에 돌 하나도 돌 위에 남지 않고 다 무너질 것이다.\"",
    Chn:"耶稣对他说：「你看见这大殿宇吗？将来在这里没有一块石头留在石头上，不被拆毁了。」",
    Eng:"\"Do you see all these great buildings?\" replied Jesus. \"Not one stone here will be left on another; every one will be thrown down.\"",
    Ind:"Lalu Yesus berkata kepadanya: \"Kaulihat gedung-gedung yang hebat ini? Tidak satu batupun akan dibiarkan terletak di atas batu yang lain, semuanya akan diruntuhkan.\""
  },
  {Bible:"Mark", Chapter:13, Verse:3, Page:1,
    Kor:"<재난의 징조(마 24:3-14; 눅 21:7-19)> ○예수께서 올리브 산에서 성전을 마주 보고 앉아 계실 때에, 베드로와 야고보와 요한과 안드레가 따로 예수께 물었다.",
    Chn:"耶稣在橄榄山上对圣殿而坐。彼得、雅各、约翰，和安得烈暗暗地问他说：",
    Eng:"As Jesus was sitting on the Mount of Olives opposite the temple, Peter, James, John and Andrew asked him privately,",
    Ind:"Ketika Yesus duduk di atas Bukit Zaitun, berhadapan dengan Bait Allah, Petrus, Yakobus, Yohanes dan Andreas bertanya sendirian kepada-Nya:"
  },
  {Bible:"Mark", Chapter:13, Verse:4, Page:1,
    Kor:"\"우리에게 말씀해 주십시오. 이런 일이 언제 일어나겠습니까? 또 이런 일들이 이루어지려고 할 때에는, 무슨 징조가 있겠습니까?\"",
    Chn:"「请告诉我们，什么时候有这些事呢？这一切事将成的时候有什么预兆呢？」",
    Eng:"\"Tell us, when will these things happen? And what will be the sign that they are all about to be fulfilled?\"",
    Ind:"\"Katakanlah kepada kami, bilamanakah itu akan terjadi, dan apakah tandanya, kalau semuanya itu akan sampai kepada kesudahannya.\""
  },
  {Bible:"Mark", Chapter:13, Verse:5, Page:1,
    Kor:"예수께서 그들에게 말씀하셨다. \"누구에게도 속지 않도록 조심하여라.",
    Chn:"耶稣说：「你们要谨慎，免得有人迷惑你们。",
    Eng:"Jesus said to them: \"Watch out that no one deceives you.",
    Ind:"Maka mulailah Yesus berkata kepada mereka: \"Waspadalah supaya jangan ada orang yang menyesatkan kamu!"
  },
  {Bible:"Mark", Chapter:13, Verse:6, Page:1,
    Kor:"많은 사람이 내 이름으로 와서는 '내가 그리스도다' 하면서, 많은 사람을 속일 것이다.",
    Chn:"将来有好些人冒我的名来，说：『我是基督』，并且要迷惑许多人。",
    Eng:"Many will come in my name, claiming, 'I am he,' and will deceive many.",
    Ind:"Akan datang banyak orang dengan memakai nama-Ku dan berkata: Akulah dia, dan mereka akan menyesatkan banyak orang."
  },
  {Bible:"Mark", Chapter:13, Verse:7, Page:1,
    Kor:"또 너희는 여기저기에서 전쟁이 일어난 소식과 전쟁이 일어날 것이라는 소문을 듣게 되어도, 놀라지 말아라. 이런 일이 반드시 일어나야 한다. 그러나 아직 끝은 아니다.",
    Chn:"你们听见打仗和打仗的风声，不要惊慌。这些事是必须有的，只是末期还没有到。",
    Eng:"When you hear of wars and rumors of wars, do not be alarmed. Such things must happen, but the end is still to come.",
    Ind:"Dan apabila kamu mendengar deru perang atau kabar-kabar tentang perang, janganlah kamu gelisah. Semuanya itu harus terjadi, tetapi itu belum kesudahannya."
  },
  {Bible:"Mark", Chapter:13, Verse:8, Page:1,
    Kor:"민족과 민족이 맞서 일어나고, 나라와 나라가 맞서 일어날 것이며, 지진이 곳곳에서 일어나고, 기근이 들 것이다. 이런 일들은 진통의 시작이다.",
    Chn:"民要攻打民，国要攻打国；多处必有地震、饥荒。这都是灾难的起头。",
    Eng:"Nation will rise against nation, and kingdom against kingdom. There will be earthquakes in various places, and famines. These are the beginning of birth pains.",
    Ind:"Sebab bangsa akan bangkit melawan bangsa dan kerajaan melawan kerajaan. Akan terjadi gempa bumi di berbagai tempat, dan akan ada kelaparan. Semua itu barulah permulaan penderitaan menjelang zaman baru."
  },
  {Bible:"Mark", Chapter:13, Verse:9, Page:1,
    Kor:"○너희는 스스로 조심하여라. 사람들이 너희를 법정에 넘겨줄 것이며, 너희가 회당에서 매를 맞을 것이다. 또 너희는 나 때문에 총독들과 임금들 앞에 서게 되고, 그들에게 증언할 것이다.",
    Chn:"但你们要谨慎；因为人要把你们交给公会，并且你们在会堂里要受鞭打，又为我的缘故站在诸侯与君王面前，对他们作见证。",
    Eng:"\"You must be on your guard. You will be handed over to the local councils and flogged in the synagogues. On account of me you will stand before governors and kings as witnesses to them.",
    Ind:"Tetapi kamu ini, hati-hatilah! Kamu akan diserahkan kepada majelis agama dan kamu akan dipukul di rumah ibadat dan kamu akan dihadapkan ke muka penguasa-penguasa dan raja-raja karena Aku, sebagai kesaksian bagi mereka."
  },
  {Bible:"Mark", Chapter:13, Verse:10, Page:1,
    Kor:"먼저 a복음이 모든 민족에게 전파되어야 한다.(a 또는 '기쁜 소식')",
    Chn:"然而，福音必须先传给万民。",
    Eng:"And the gospel must first be preached to all nations.",
    Ind:"Tetapi Injil harus diberitakan dahulu kepada semua bangsa."
  },
  {Bible:"Mark", Chapter:13, Verse:11, Page:1,
    Kor:"사람들이 너희를 끌고 가서 넘겨줄 때에, 너희는 무슨 말을 할까 하고 미리 걱정하지 말아라. 무엇이든지 그 시각에 말할 것을 너희에게 지시하여 주시는 대로 말하여라. 말하는 이는 너희가 아니라 성령이시다.",
    Chn:"人把你们拉去交官的时候，不要预先思虑说什么；到那时候，赐给你们什么话，你们就说什么；因为说话的不是你们，乃是圣灵。",
    Eng:"Whenever you are arrested and brought to trial, do not worry beforehand about what to say. Just say whatever is given you at the time, for it is not you speaking, but the Holy Spirit.",
    Ind:"Dan jika kamu digiring dan diserahkan, janganlah kamu kuatir akan apa yang harus kamu katakan, tetapi katakanlah apa yang dikaruniakan kepadamu pada saat itu juga, sebab bukan kamu yang berkata-kata, melainkan Roh Kudus."
  },
  {Bible:"Mark", Chapter:13, Verse:12, Page:1,
    Kor:"형제가 형제를 죽음에 넘겨주고, 아버지가 자식을 또한 그렇게 하고, 자식이 부모를 거슬러 일어나서 부모를 죽일 것이다.",
    Chn:"弟兄要把弟兄，父亲要把儿子，送到死地；儿女要起来与父母为敌，害死他们；",
    Eng:"\"Brother will betray brother to death, and a father his child. Children will rebel against their parents and have them put to death.",
    Ind:"Seorang saudara akan menyerahkan saudaranya untuk dibunuh, demikian juga seorang ayah terhadap anaknya. Dan anak-anak akan memberontak terhadap orang tuanya dan akan membunuh mereka."
  },
  {Bible:"Mark", Chapter:13, Verse:13, Page:1,
    Kor:"너희는 내 이름 때문에 모든 사람에게서 미움을 받을 것이다. 그러나 끝까지 견디는 사람은 구원을 받을 것이다.\"",
    Chn:"并且你们要为我的名被众人恨恶。惟有忍耐到底的，必然得救。」",
    Eng:"All men will hate you because of me, but he who stands firm to the end will be saved.",
    Ind:"Kamu akan dibenci semua orang oleh karena nama-Ku. Tetapi orang yang bertahan sampai pada kesudahannya ia akan selamat.\""
  },
  {Bible:"Mark", Chapter:13, Verse:14, Page:1,
    Kor:"<가장 큰 재난(마 24:15-28; 눅 21:20-24)> ○\"b'황폐하게 하는 가증스러운 물건이 서지 못할 곳에 선 것'을 보거든, (읽는 사람은 깨달아라) 그 때에는 유대에 있는 사람들은 산으로 도망하여라.(b 단 9:27; 11:31; 12:11)",
    Chn:"「你们看见那行毁坏可憎的，站在不当站的地方（读这经的人须要会意）。那时，在犹太的，应当逃到山上；",
    Eng:"\"When you see 'the abomination that causes desolation' standing where it does not belong--let the reader understand--then let those who are in Judea flee to the mountains.",
    Ind:"\"Apabila kamu melihat Pembinasa keji berdiri di tempat yang tidak sepatutnya--para pembaca hendaklah memperhatikannya--maka orang-orang yang di Yudea haruslah melarikan diri ke pegunungan."
  },
  {Bible:"Mark", Chapter:13, Verse:15, Page:1,
    Kor:"지붕 위에 있는 사람은, 내려오지도 말고, 제 집 안에서 무엇을 꺼내려고 들어가지도 말아라.",
    Chn:"在房上的，不要下来，也不要进去拿家里的东西；",
    Eng:"Let no one on the roof of his house go down or enter the house to take anything out.",
    Ind:"Orang yang sedang di peranginan di atas rumah janganlah ia turun dan masuk untuk mengambil sesuatu dari rumahnya,"
  },
  {Bible:"Mark", Chapter:13, Verse:16, Page:1,
    Kor:"들에 있는 사람은 제 겉옷을 가지러 뒤로 돌아서지 말아라.",
    Chn:"在田里的，也不要回去取衣裳。",
    Eng:"Let no one in the field go back to get his cloak.",
    Ind:"dan orang yang sedang di ladang janganlah ia kembali untuk mengambil pakaiannya."
  },
  {Bible:"Mark", Chapter:13, Verse:17, Page:1,
    Kor:"그 날에는 아이 밴 여자들과 젖먹이가 딸린 여자들은 불행하다.",
    Chn:"当那些日子，怀孕的和奶孩子的有祸了！",
    Eng:"How dreadful it will be in those days for pregnant women and nursing mothers!",
    Ind:"Celakalah ibu-ibu yang sedang hamil atau yang menyusukan bayi pada masa itu."
  },
  {Bible:"Mark", Chapter:13, Verse:18, Page:1,
    Kor:"이 일이 겨울에 일어나지 않도록 기도하여라.",
    Chn:"你们应当祈求，叫这些事不在冬天临到。",
    Eng:"Pray that this will not take place in winter,",
    Ind:"Berdoalah, supaya semuanya itu jangan terjadi pada musim dingin."
  },
  {Bible:"Mark", Chapter:13, Verse:19, Page:1,
    Kor:"그 날에 환난이 닥칠 것인데, 그런 환난은 하나님께서 세상을 창조하신 이래로 지금까지 없었고, 앞으로도 없을 것이다.",
    Chn:"因为在那些日子必有灾难，自从　神创造万物直到如今，并没有这样的灾难，后来也必没有。",
    Eng:"because those will be days of distress unequaled from the beginning, when God created the world, until now--and never to be equaled again.",
    Ind:"Sebab pada masa itu akan terjadi siksaan seperti yang belum pernah terjadi sejak awal dunia, yang diciptakan Allah, sampai sekarang dan yang tidak akan terjadi lagi."
  },
  {Bible:"Mark", Chapter:13, Verse:20, Page:1,
    Kor:"주님께서 그 날들을 줄여 주지 않으셨다면, 구원받을 사람이 하나도 없을 것이다. 그러나 주님께서는, 주님이 뽑으신 선택받은 사람들을 위하여, 그 날들을 줄여 주셨다.",
    Chn:"若不是主减少那日子，凡有血气的，总没有一个得救的；只是为主的选民，他将那日子减少了。",
    Eng:"If the Lord had not cut short those days, no one would survive. But for the sake of the elect, whom he has chosen, he has shortened them.",
    Ind:"Dan sekiranya Tuhan tidak mempersingkat waktunya, maka dari segala yang hidup tidak akan ada yang selamat; akan tetapi oleh karena orang-orang pilihan yang telah dipilih-Nya, Tuhan mempersingkat waktunya."
  },
  {Bible:"Mark", Chapter:13, Verse:21, Page:1,
    Kor:"그 때에 누가 너희에게 '보아라, c그리스도가 여기에 있다. 보아라, 그리스도가 저기에 있다' 하더라도, 믿지 말아라.(c 또는 '메시아'. 그리스도는 그리스어이고, 메시아는 히브리어임. 둘 다 '기름부음 받은 사람'을 뜻함)",
    Chn:"那时若有人对你们说：『看哪，基督在这里』，或说：『基督在那里』，你们不要信！",
    Eng:"At that time if anyone says to you, 'Look, here is the Christ!' or, 'Look, there he is!' do not believe it.",
    Ind:"Pada waktu itu jika orang berkata kepada kamu: Lihat, Mesias ada di sini, atau: Lihat, Mesias ada di sana, jangan kamu percaya."
  },
  {Bible:"Mark", Chapter:13, Verse:22, Page:1,
    Kor:"거짓 d그리스도들과 거짓 예언자들이 일어나, 표징들과 기적들을 행하여 보여서, 할 수만 있으면 선택 받은 사람들을 홀리려 할 것이다.(d 또는 '메시아들')",
    Chn:"因为假基督、假先知将要起来，显神迹奇事，倘若能行，就把选民迷惑了。",
    Eng:"For false Christs and false prophets will appear and perform signs and miracles to deceive the elect--if that were possible.",
    Ind:"Sebab Mesias-mesias palsu dan nabi-nabi palsu akan muncul dan mereka akan mengadakan tanda-tanda dan mujizat-mujizat dengan maksud, sekiranya mungkin, menyesatkan orang-orang pilihan."
  },
  {Bible:"Mark", Chapter:13, Verse:23, Page:1,
    Kor:"그러므로 너희는 조심하여라. 내가 이 모든 일을 너희에게 미리 말하여 둔다.\"",
    Chn:"你们要谨慎。看哪，凡事我都预先告诉你们了。」",
    Eng:"So be on your guard; I have told you everything ahead of time.",
    Ind:"Hati-hatilah kamu! Aku sudah terlebih dahulu mengatakan semuanya ini kepada kamu.\""
  },
  {Bible:"Mark", Chapter:13, Verse:24, Page:1,
    Kor:"<인자가 오심(마 24:29-31; 눅 21:25-28)> \"그러나 그 환난이 지난 뒤에, e'그 날에는, 해가 어두워지고, 달이 빛을 내지 않고, (e 사 13:10; 34:4)",
    Chn:"「在那些日子，那灾难以后， 日头要变黑了， 月亮也不放光，",
    Eng:"\"But in those days, following that distress, \"'the sun will be darkened, and the moon will not give its light;",
    Ind:"\"Tetapi pada masa itu, sesudah siksaan itu, matahari akan menjadi gelap dan bulan tidak bercahaya"
  },
  {Bible:"Mark", Chapter:13, Verse:25, Page:1,
    Kor:"별들이 하늘에서 떨어지고, 하늘의 세력들이 흔들릴 것이다.'",
    Chn:"众星要从天上坠落， 天势都要震动。",
    Eng:"the stars will fall from the sky, and the heavenly bodies will be shaken.'",
    Ind:"dan bintang-bintang akan berjatuhan dari langit, dan kuasa-kuasa langit akan goncang."
  },
  {Bible:"Mark", Chapter:13, Verse:26, Page:1,
    Kor:"그 때에 사람들이, 인자가 큰 권능과 영광에 싸여 구름을 타고 오는 것을 볼 것이다.",
    Chn:"那时，他们要看见人子有大能力、大荣耀，驾云降临。",
    Eng:"\"At that time men will see the Son of Man coming in clouds with great power and glory.",
    Ind:"Pada waktu itu orang akan melihat Anak Manusia datang dalam awan-awan dengan segala kekuasaan dan kemuliaan-Nya."
  },
  {Bible:"Mark", Chapter:13, Verse:27, Page:1,
    Kor:"그 때에 그는 천사들을 보내어, 땅 끝에서 하늘 끝까지, 사방에서 선택된 사람들을 모을 것이다.\"",
    Chn:"他要差遣天使，把他的选民，从四方，从地极直到天边，都招聚了来。」",
    Eng:"And he will send his angels and gather his elect from the four winds, from the ends of the earth to the ends of the heavens.",
    Ind:"Dan pada waktu itupun Ia akan menyuruh keluar malaikat-malaikat-Nya dan akan mengumpulkan orang-orang pilihan-Nya dari keempat penjuru bumi, dari ujung bumi sampai ke ujung langit."
  },
  {Bible:"Mark", Chapter:13, Verse:28, Page:1,
    Kor:"<무화과나무에서 배울 교훈(마 24:32-35; 눅 21:29-33)> ○\"무화과나무에서 비유를 배워라. 그 가지가 연해지고 잎이 돋으면, 너희는 여름이 가까이 온 줄을 안다.",
    Chn:"「你们可以从无花果树学个比方：当树枝发嫩长叶的时候，你们就知道夏天近了。",
    Eng:"\"Now learn this lesson from the fig tree: As soon as its twigs get tender and its leaves come out, you know that summer is near.",
    Ind:"Tariklah pelajaran dari perumpamaan tentang pohon ara. Apabila ranting-rantingnya melembut dan mulai bertunas, kamu tahu, bahwa musim panas sudah dekat."
  },
  {Bible:"Mark", Chapter:13, Verse:29, Page:1,
    Kor:"이와 같이, 너희도 이런 일들이 일어나는 것을 보거든, 인자가 문 앞에 가까이 온 줄을 알아라.",
    Chn:"这样，你们几时看见这些事成就，也该知道人子近了，正在门口了。",
    Eng:"Even so, when you see these things happening, you know that it is near, right at the door.",
    Ind:"Demikian juga, jika kamu lihat hal-hal itu terjadi, ketahuilah bahwa waktunya sudah dekat, sudah di ambang pintu."
  },
  {Bible:"Mark", Chapter:13, Verse:30, Page:1,
    Kor:"내가 진정으로 너희에게 말한다. 이 세대가 끝나기 전에, 이 모든 일이 다 일어날 것이다.",
    Chn:"我实在告诉你们，这世代还没有过去，这些事都要成就。",
    Eng:"I tell you the truth, this generation will certainly not pass away until all these things have happened.",
    Ind:"Aku berkata kepadamu: Sesungguhnya angkatan ini tidak akan berlalu, sebelum semuanya itu terjadi."
  },
  {Bible:"Mark", Chapter:13, Verse:31, Page:1,
    Kor:"하늘과 땅은 없어질지라도, 나의 말은 절대로 없어지지 않을 것이다.\"",
    Chn:"天地要废去，我的话却不能废去。」",
    Eng:"Heaven and earth will pass away, but my words will never pass away.",
    Ind:"Langit dan bumi akan berlalu, tetapi perkataan-Ku tidak akan berlalu."
  },
  {Bible:"Mark", Chapter:13, Verse:32, Page:1,
    Kor:"<그 날과 그 때(마 24:36-44)> ○\"그러나 그 날과 그 때는 아무도 모른다. 하늘의 천사들도 모르고, 아들도 모르고, 오직 아버지만 아신다.",
    Chn:"「但那日子，那时辰，没有人知道，连天上的使者也不知道，子也不知道，惟有父知道。",
    Eng:"\"No one knows about that day or hour, not even the angels in heaven, nor the Son, but only the Father.",
    Ind:"Tetapi tentang hari atau saat itu tidak seorangpun yang tahu, malaikat-malaikat di sorga tidak, dan Anakpun tidak, hanya Bapa saja.\""
  },
  {Bible:"Mark", Chapter:13, Verse:33, Page:1,
    Kor:"조심하고, f깨어 있어라. 그 때가 언제인지를 너희가 모르기 때문이다.(f 다른 고대 사본들에는 '깨어서 기도하여라')",
    Chn:"你们要谨慎，警醒祈祷，因为你们不晓得那日期几时来到。",
    Eng:"Be on guard! Be alert! You do not know when that time will come.",
    Ind:"\"Hati-hatilah dan berjaga-jagalah! Sebab kamu tidak tahu bilamanakah waktunya tiba."
  },
  {Bible:"Mark", Chapter:13, Verse:34, Page:1,
    Kor:"사정은 여행하는 어떤 사람의 경우와 같은데, 그가 집을 떠날 때에, 자기 종들에게 권한을 주어서, 각 사람에게 할 일을 맡기고, 문지기에게는 깨어 있으라고 명령한다.",
    Chn:"这事正如一个人离开本家，寄居外邦，把权柄交给仆人，分派各人当做的工，又吩咐看门的警醒。",
    Eng:"It's like a man going away: He leaves his house and puts his servants in charge, each with his assigned task, and tells the one at the door to keep watch.",
    Ind:"Dan halnya sama seperti seorang yang bepergian, yang meninggalkan rumahnya dan menyerahkan tanggung jawab kepada hamba-hambanya, masing-masing dengan tugasnya, dan memerintahkan penunggu pintu supaya berjaga-jaga."
  },
  {Bible:"Mark", Chapter:13, Verse:35, Page:1,
    Kor:"그러므로 깨어 있어라. 집주인이 언제 올는지, 저녁녘일지, 한밤중일지, 닭이 울 무렵일지, 이른 아침녘일지, 너희가 알지 못하기 때문이다.",
    Chn:"所以，你们要警醒；因为你们不知道家主什么时候来，或晚上，或半夜，或鸡叫，或早晨；",
    Eng:"\"Therefore keep watch because you do not know when the owner of the house will come back--whether in the evening, or at midnight, or when the rooster crows, or at dawn.",
    Ind:"Karena itu berjaga-jagalah, sebab kamu tidak tahu bilamanakah tuan rumah itu pulang, menjelang malam, atau tengah malam, atau larut malam, atau pagi-pagi buta,"
  },
  {Bible:"Mark", Chapter:13, Verse:36, Page:1,
    Kor:"주인이 갑자기 와서 너희가 잠자고 있는 것을 보게 되는 일이 없도록 하여라.",
    Chn:"恐怕他忽然来到，看见你们睡着了。",
    Eng:"If he comes suddenly, do not let him find you sleeping.",
    Ind:"supaya kalau ia tiba-tiba datang jangan kamu didapatinya sedang tidur."
  },
  {Bible:"Mark", Chapter:13, Verse:37, Page:1,
    Kor:"내가 너희에게 하는 말은 모든 사람에게 하는 말이다. 깨어 있어라.\"",
    Chn:"我对你们所说的话，也是对众人说：要警醒！」",
    Eng:"What I say to you, I say to everyone: 'Watch!'\"",
    Ind:"Apa yang Kukatakan kepada kamu, Kukatakan kepada semua orang: berjaga-jagalah!\""
  },
]);
