// 레위기 22장 · Leviticus 22
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Leviticus",22,33);
BibleDB.add([
  {Bible:"Leviticus", Chapter:22, Verse:1, Page:1,
    Kor:"<제사음식을 먹는 규례> 주님께서 모세에게 말씀하셨다.",
    Chn:"耶和华对摩西说：",
    Eng:"The LORD said to Moses,",
    Ind:"TUHAN berfirman kepada Musa:"
  },
  {Bible:"Leviticus", Chapter:22, Verse:2, Page:1,
    Kor:"\"너는 아론과 그의 아들들에게 일러, 이스라엘 자손이 나에게 바친 거룩한 제사음식을 함부로 다루지 못하게 하여라. 제사음식을 함부로 다루는 것은 곧 나의 거룩한 이름을 욕되게 하는 것이다. 나는 주다.",
    Chn:"「你吩咐亚伦和他子孙说：要远离以色列人所分别为圣、归给我的圣物，免得亵渎我的圣名。我是耶和华。",
    Eng:"\"Tell Aaron and his sons to treat with respect the sacred offerings the Israelites consecrate to me, so they will not profane my holy name. I am the LORD.",
    Ind:"\"Katakanlah kepada Harun dan anak-anaknya, supaya mereka berlaku hati-hati terhadap persembahan-persembahan kudus yang dikuduskan orang Israel bagi-Ku, agar jangan mereka melanggar kekudusan nama-Ku yang kudus; Akulah TUHAN."
  },
  {Bible:"Leviticus", Chapter:22, Verse:3, Page:1,
    Kor:"너는 그들에게 다음과 같이 일러라. ○너희는 자손 대대로, 어느 누구든 몸이 부정할 때에는, 이스라엘 자손이 나 주에게 바친 거룩한 제사음식에 가까이해서는 안 된다. 이것을 어기는 사람은 다시는 내 앞에 서지 못할 것이다. 나는 주다.",
    Chn:"你要对他们说：你们世世代代的后裔，凡身上有污秽、亲近以色列人所分别为圣、归耶和华圣物的，那人必在我面前剪除。我是耶和华。",
    Eng:"\"Say to them: 'For the generations to come, if any of your descendants is ceremonially unclean and yet comes near the sacred offerings that the Israelites consecrate to the LORD, that person must be cut off from my presence. I am the LORD.",
    Ind:"Katakanlah kepada mereka: Setiap orang di antara kamu turun-temurun, yakni dari antara segala keturunanmu yang datang mendekat kepada persembahan-persembahan kudus yang dikuduskan orang Israel bagi TUHAN, sedang ia dalam keadaan najis, maka orang itu akan dilenyapkan dari hadapan-Ku; Akulah TUHAN."
  },
  {Bible:"Leviticus", Chapter:22, Verse:4, Page:1,
    Kor:"○아론의 자손 가운데서 a악성 피부병을 앓는 환자나 성기에서 고름을 흘리는 환자는, 그 병이 깨끗해질 때까지는 거룩한 제사음식을 먹지 못한다. 누구든지 죽은 것을 만지거나 정액을 흘린 남자와 몸이 닿거나 하여 부정하게 된 사람,(a 전통적으로 나병으로 알려져 왔으나, 히브리어로는 여러 03 22:가지 악성 피부병을 뜻함)",
    Chn:"亚伦的后裔，凡长大麻风的，或是有漏症的，不可吃圣物，直等他洁净了。无论谁摸那因死尸不洁净的物，或是遗精的人，",
    Eng:"\"'If a descendant of Aaron has an infectious skin disease or a bodily discharge, he may not eat the sacred offerings until he is cleansed. He will also be unclean if he touches something defiled by a corpse or by anyone who has an emission of semen,",
    Ind:"Seseorang dari keturunan Harun yang sakit kusta atau yang mengeluarkan lelehan, janganlah memakan persembahan-persembahan kudus, sebelum ia menjadi tahir; dan orang yang kena kepada sesuatu yang najis karena orang mati atau orang yang tertumpah maninya"
  },
  {Bible:"Leviticus", Chapter:22, Verse:5, Page:1,
    Kor:"또 어떤 길짐승에든지 닿아서 부정하게 된 사람, 또는 어떤 부정이든지 부정을 탄 사람,",
    Chn:"或是摸什么使他不洁净的爬物，或是摸那使他不洁净的人（不拘那人有什么不洁净），",
    Eng:"or if he touches any crawling thing that makes him unclean, or any person who makes him unclean, whatever the uncleanness may be.",
    Ind:"atau orang yang kena kepada seekor binatang yang merayap yang menajiskan dia atau kepada salah seorang manusia yang menajiskan dia, dengan kenajisan apapun ia menjadi najis,"
  },
  {Bible:"Leviticus", Chapter:22, Verse:6, Page:1,
    Kor:"곧 이런 부정한 것에 닿은 사람은 해가 질 때까지 부정하다. 해가 진 다음에라도, 물로 목욕을 하지 않으면, 그는 그 거룩한 제사음식을 먹지 못한다.",
    Chn:"摸了这些人、物的，必不洁净到晚上；若不用水洗身，就不可吃圣物。",
    Eng:"The one who touches any such thing will be unclean till evening. He must not eat any of the sacred offerings unless he has bathed himself with water.",
    Ind:"orang yang kena kepada yang demikian itu menjadi najis sampai matahari terbenam dan janganlah ia makan dari persembahan-persembahan kudus, sebelum ia membasuh tubuhnya dengan air."
  },
  {Bible:"Leviticus", Chapter:22, Verse:7, Page:1,
    Kor:"해가 지고 정결하게 된 뒤에는, 자기 몫으로 받은 그 거룩한 제사음식을 먹을 수 있다.",
    Chn:"日落的时候，他就洁净了，然后可以吃圣物，因为这是他的食物。",
    Eng:"When the sun goes down, he will be clean, and after that he may eat the sacred offerings, for they are his food.",
    Ind:"Sesudah matahari terbenam, barulah ia menjadi tahir dan sesudah itu bolehlah ia makan dari persembahan-persembahan kudus itu, karena itulah yang menjadi makanannya."
  },
  {Bible:"Leviticus", Chapter:22, Verse:8, Page:1,
    Kor:"저절로 죽었거나 짐승에게 물려 찢겨 죽은 것은 먹지 못한다. 그것을 먹었다가는, 그것 때문에 부정하게 된다. 나는 주다.",
    Chn:"自死的或是被野兽撕裂的，他不可吃，因此污秽自己。我是耶和华。",
    Eng:"He must not eat anything found dead or torn by wild animals, and so become unclean through it. I am the LORD.",
    Ind:"Janganlah ia makan bangkai atau sisa mangsa binatang buas, supaya jangan ia menjadi najis karenanya; Akulah TUHAN."
  },
  {Bible:"Leviticus", Chapter:22, Verse:9, Page:1,
    Kor:"그러므로 아론과 그의 아들들은 내가 지키라고 한 것을 그대로 지켜야 한다. 이것을 가볍게 생각하여 욕되게 하면, 그것은 곧 죄를 범하는 것이고, 그것 때문에 그들은 죽는다. 나는 제사장들을 거룩하게 하는 주다.",
    Chn:"所以他们要守我所吩咐的，免得轻忽了，因此担罪而死。我是叫他们成圣的耶和华。",
    Eng:"\"'The priests are to keep my requirements so that they do not become guilty and die for treating them with contempt. I am the LORD, who makes them holy.",
    Ind:"Dan mereka harus tetap berpegang pada kewajibannya terhadap Aku, supaya dalam hal itu jangan mereka mendatangkan dosa kepada dirinya dan mati oleh karenanya, karena mereka telah melanggar kekudusan kewajiban itu; Akulah TUHAN, yang menguduskan mereka."
  },
  {Bible:"Leviticus", Chapter:22, Verse:10, Page:1,
    Kor:"○제사장이 아닌 여느 사람은 아무도 그 거룩한 제사음식을 먹지 못한다. 제사장이 데리고 있는 나그네나 그가 쓰는 품꾼도, 그 거룩한 제사음식을 먹지 못한다.",
    Chn:"「凡外人不可吃圣物；寄居在祭司家的，或是雇工人，都不可吃圣物；",
    Eng:"\"'No one outside a priest's family may eat the sacred offering, nor may the guest of a priest or his hired worker eat it.",
    Ind:"Setiap orang awam janganlah memakan persembahan kudus; demikian juga pendatang yang tinggal pada imam ataupun orang upahan."
  },
  {Bible:"Leviticus", Chapter:22, Verse:11, Page:1,
    Kor:"그러나 제사장이 돈을 지불하고 자기 재산으로 사들인 종은, 그 음식을 먹을 수 있다. 제사장의 집에서 종의 자식으로 태어난 자들도, 자기 몫의 그 거룩한 제사음식을 먹을 수 있다.",
    Chn:"倘若祭司买人，是他的钱买的，那人就可以吃圣物；生在他家的人也可以吃。",
    Eng:"But if a priest buys a slave with money, or if a slave is born in his household, that slave may eat his food.",
    Ind:"Tetapi apabila seseorang telah dibeli oleh imam dengan uangnya menjadi budak beliannya, maka orang itu boleh turut memakannya, demikian juga mereka yang lahir di rumahnya."
  },
  {Bible:"Leviticus", Chapter:22, Verse:12, Page:1,
    Kor:"제사장의 딸이라도 여느 남자에게 시집갔다면, 그 딸은 제물로 바친 그 거룩한 제사음식을 먹을 수 없다.",
    Chn:"祭司的女儿若嫁外人，就不可吃举祭的圣物。",
    Eng:"If a priest's daughter marries anyone other than a priest, she may not eat any of the sacred contributions.",
    Ind:"Apabila anak perempuan imam bersuamikan orang awam, janganlah ia makan persembahan khusus dari persembahan-persembahan kudus."
  },
  {Bible:"Leviticus", Chapter:22, Verse:13, Page:1,
    Kor:"그러나 제사장의 딸이 과부가 되었거나 이혼하여, 자식도 없이 다시 아버지 집으로 돌아와, 시집가기 전처럼 아버지 집에서 살 때에는, 아버지가 먹는 제사음식을 먹을 수 있다. 그러나 여느 사람은 아무도 거룩한 제사음식을 먹지 못한다.",
    Chn:"但祭司的女儿若是寡妇，或是被休的，没有孩子，又归回父家，与她青年一样，就可以吃她父亲的食物；只是外人不可吃。",
    Eng:"But if a priest's daughter becomes a widow or is divorced, yet has no children, and she returns to live in her father's house as in her youth, she may eat of her father's food. No unauthorized person, however, may eat any of it.",
    Ind:"Tetapi apabila perempuan itu menjadi janda atau diceraikan, dan ia tidak mempunyai anak, dan telah kembali ke rumah ayahnya seperti waktu ia masih gadis, maka ia boleh makan dari makanan ayahnya; tetapi setiap orang awam janganlah memakannya."
  },
  {Bible:"Leviticus", Chapter:22, Verse:14, Page:1,
    Kor:"어떤 사람이 모르고 그 거룩한 제사음식을 먹으면, 그는 그 음식값의 오분의 일에 해당하는 값을 그 위에 더 보태어, 제사장에게 갚아야 한다.",
    Chn:"若有人误吃了圣物，要照圣物的原数加上五分之一交给祭司。",
    Eng:"\"'If anyone eats a sacred offering by mistake, he must make restitution to the priest for the offering and add a fifth of the value to it.",
    Ind:"Apabila seseorang dengan tidak sengaja memakan persembahan kudus, ia harus memberi gantinya kepada imam dengan menambah seperlima."
  },
  {Bible:"Leviticus", Chapter:22, Verse:15, Page:1,
    Kor:"제사장들은 이스라엘 자손이 바친 그 거룩한 제사음식 곧 그들이 주에게 바친 제물을 더럽혀서는 안 된다.",
    Chn:"祭司不可亵渎以色列人所献给耶和华的圣物，",
    Eng:"The priests must not desecrate the sacred offerings the Israelites present to the LORD",
    Ind:"Janganlah pada imam melanggar kekudusan persembahan-persembahan kudus orang Israel yang telah dikhususkan bagi TUHAN,"
  },
  {Bible:"Leviticus", Chapter:22, Verse:16, Page:1,
    Kor:"제사장은, 자기들이 먹을 제사음식을, 여느 사람들이 모르고 먹다가 죄를 지어 벌을 받는 일이 없도록 조심하여야 한다. 나는 그 음식을 거룩하게 하는 주다.\"",
    Chn:"免得他们在吃圣物上自取罪孽，因为我是叫他们成圣的耶和华。」",
    Eng:"by allowing them to eat the sacred offerings and so bring upon them guilt requiring payment. I am the LORD, who makes them holy.'\"",
    Ind:"karena dengan demikian mereka mendatangkan kepada orang Israel kesalahan yang harus ditebus, apabila mereka memakan persembahan-persembahan kudus mereka, sebab Akulah TUHAN, yang menguduskan mereka.\""
  },
  {Bible:"Leviticus", Chapter:22, Verse:17, Page:1,
    Kor:"<하나님이 받으시는 제물> ○주님께서 모세에게 말씀하셨다.",
    Chn:"耶和华对摩西说：",
    Eng:"The LORD said to Moses,",
    Ind:"TUHAN berfirman kepada Musa:"
  },
  {Bible:"Leviticus", Chapter:22, Verse:18, Page:1,
    Kor:"\"너는 아론과 그의 아들들과 온 이스라엘 자손에게 말하여라. 그들에게 다음과 같이 일러라. ○이스라엘 집안에 속한 사람이나 이스라엘 사람과 함께 사는 외국인 나그네가, 제물을 바치고자 할 때에는, 그것이, 서약한 것을 갚으려고 해서 바치는 것이거나, 자유로운 뜻에서 나 주에게 번제물로 바치려는 것이거나, 모두,",
    Chn:"「你晓谕亚伦和他子孙，并以色列众人说：以色列家中的人，或在以色列中寄居的，凡献供物，无论是所许的愿，是甘心献的，就是献给耶和华作燔祭的，",
    Eng:"\"Speak to Aaron and his sons and to all the Israelites and say to them: 'If any of you--either an Israelite or an alien living in Israel--presents a gift for a burnt offering to the LORD, either to fulfill a vow or as a freewill offering,",
    Ind:"\"Berbicaralah kepada Harun serta anak-anaknya dan kepada semua orang Israel dan katakan kepada mereka: Siapapun dari umat Israel dan dari orang asing di antara orang Israel yang mempersembahkan persembahannya, baik berupa sesuatu persembahan nazar maupun berupa sesuatu persembahan sukarela, yang hendak dipersembahkan mereka kepada TUHAN sebagai korban bakaran,"
  },
  {Bible:"Leviticus", Chapter:22, Verse:19, Page:1,
    Kor:"나 주가 즐거이 받도록, 소나 양이나 염소 가운데서 수컷으로, 흠이 없는 것을 바쳐야 한다.",
    Chn:"要将没有残疾的公牛，或是绵羊，或是山羊献上，如此方蒙悦纳。",
    Eng:"you must present a male without defect from the cattle, sheep or goats in order that it may be accepted on your behalf.",
    Ind:"maka supaya TUHAN berkenan akan kamu, haruslah persembahan itu tidak bercela dari lembu jantan, domba atau kambing."
  },
  {Bible:"Leviticus", Chapter:22, Verse:20, Page:1,
    Kor:"너희는 어떤 것이든지, 흠이 있는 것을 바쳐서는 안 된다. 그런 것을 바치면, 나 주가 너희를 반기지 않을 것이다.",
    Chn:"凡有残疾的，你们不可献上，因为这不蒙悦纳。",
    Eng:"Do not bring anything with a defect, because it will not be accepted on your behalf.",
    Ind:"Segala yang bercacat badannya janganlah kamu persembahkan, karena dengan itu TUHAN tidak berkenan akan kamu."
  },
  {Bible:"Leviticus", Chapter:22, Verse:21, Page:1,
    Kor:"○누구든지 서약한 것을 갚으려 하거나, 자유로운 뜻으로 제물을 바치려고 하여, 소 떼나 양 떼에서 제물을 골라 나 주에게 화목제물을 바칠 때에는, 나 주가 즐거이 받도록, 흠이 없는 것으로 골라서 바쳐야 한다. 제물로 바칠 짐승에 어떤 흠도 있어서는 안 된다.",
    Chn:"凡从牛群或是羊群中，将平安祭献给耶和华，为要还特许的愿，或是作甘心献的，所献的必纯全无残疾的才蒙悦纳。",
    Eng:"When anyone brings from the herd or flock a fellowship offering to the LORD to fulfill a special vow or as a freewill offering, it must be without defect or blemish to be acceptable.",
    Ind:"Juga apabila seseorang mempersembahkan kepada TUHAN korban keselamatan sebagai pembayar nazar khusus atau sebagai korban sukarela dari lembu atau kambing domba, maka korban itu haruslah yang tidak bercela, supaya TUHAN berkenan akan dia, janganlah badannya bercacat sedikitpun."
  },
  {Bible:"Leviticus", Chapter:22, Verse:22, Page:1,
    Kor:"눈이 먼 것이나, 다리를 저는 것이나, 어떤 부위가 잘린 것이나, 고름을 흘리는 것이나, 옴이 난 것이나, 종기가 난 것을 나 주에게 바쳐서는 안 된다. 그런 것들을 제단 위에다 놓고 불살라, 나 주에게 바치는 제물로 삼아서는 안 된다.",
    Chn:"瞎眼的、折伤的、残废的、有瘤子的、长癣的、长疥的都不可献给耶和华，也不可在坛上作为火祭献给耶和华。",
    Eng:"Do not offer to the LORD the blind, the injured or the maimed, or anything with warts or festering or running sores. Do not place any of these on the altar as an offering made to the LORD by fire.",
    Ind:"Binatang yang buta atau yang patah tulang, yang luka atau yang berbisul, yang berkedal atau yang berkurap, semuanya itu janganlah kamu persembahkan kepada TUHAN dan binatang yang demikian janganlah kamu taruh sebagai korban api-apian bagi TUHAN ke atas mezbah."
  },
  {Bible:"Leviticus", Chapter:22, Verse:23, Page:1,
    Kor:"자유로운 뜻에서 바치는 제물이면, 소나 양 가운데서 한쪽 다리는 길고 다른 한쪽은 짧은 것이라도 괜찮다. 그러나 서원한 것을 갚는 제사에서는, 나 주가 그런 것을 즐거이 받지 않는다.",
    Chn:"无论是公牛是绵羊羔，若肢体有余的，或是缺少的，只可作甘心祭献上；用以还愿，却不蒙悦纳。",
    Eng:"You may, however, present as a freewill offering an ox or a sheep that is deformed or stunted, but it will not be accepted in fulfillment of a vow.",
    Ind:"Tetapi seekor lembu atau domba yang terlalu panjang atau terlalu pendek anggotanya bolehlah kaupersembahkan sebagai korban sukarela, tetapi sebagai korban nazar TUHAN tidak akan berkenan akan binatang itu."
  },
  {Bible:"Leviticus", Chapter:22, Verse:24, Page:1,
    Kor:"짐승 가운데서 고환이 터졌거나 으스러졌거나 빠지거나 잘린 것은 나 주에게 바칠 수 없다. 너희가 사는 땅에서는, 너희가 이런 것들을 제물로 삼아서는 안 된다.",
    Chn:"肾子损伤的，或是压碎的，或是破裂的，或是骟了的，不可献给耶和华，在你们的地上也不可这样行。",
    Eng:"You must not offer to the LORD an animal whose testicles are bruised, crushed, torn or cut. You must not do this in your own land,",
    Ind:"Tetapi binatang yang buah pelirnya terjepit, ditumbuk, direnggut atau dikerat, janganlah kamu persembahkan kepada TUHAN; janganlah kamu berbuat demikian di negerimu."
  },
  {Bible:"Leviticus", Chapter:22, Verse:25, Page:1,
    Kor:"너희는 또한 외국인 자손에게서도 이런 불구나 병신이 된 짐승을 받아다가 너희가 섬기는 하나님에게 음식으로 바쳐서는 안 된다. 이런 불구나 병신인 것을 제물로 바치면, 나 주가 너희를 반기지 않을 것이다.\"",
    Chn:"这类的物，你们从外人的手，一样也不可接受作你们　神的食物献上；因为这些都有损坏，有残疾，不蒙悦纳。」",
    Eng:"and you must not accept such animals from the hand of a foreigner and offer them as the food of your God. They will not be accepted on your behalf, because they are deformed and have defects.'\"",
    Ind:"Juga dari tangan orang asing janganlah kamu persembahkan sesuatu dari semuanya itu sebagai santapan Allahmu, karena semuanya itu telah rusak dan bercacat badannya; TUHAN tidak akan berkenan akan kamu karena persembahan-persembahan itu.\""
  },
  {Bible:"Leviticus", Chapter:22, Verse:26, Page:1,
    Kor:"○주님께서 모세에게 말씀하셨다.",
    Chn:"耶和华晓谕摩西说：",
    Eng:"The LORD said to Moses,",
    Ind:"TUHAN berfirman kepada Musa:"
  },
  {Bible:"Leviticus", Chapter:22, Verse:27, Page:1,
    Kor:"\"소나 양이나 염소가 태어나면, 이레 동안은 그 어미 품에 그대로 두어야 한다. 여드레째 되는 날부터는 그것을 제물로 삼아 나 주에게 살라 바칠 수 있다. 나 주도 그것을 즐거이 받을 것이다.",
    Chn:"「才生的公牛，或是绵羊或是山羊，七天当跟着母；从第八天以后，可以当供物蒙悦纳，作为耶和华的火祭。",
    Eng:"\"When a calf, a lamb or a goat is born, it is to remain with its mother for seven days. From the eighth day on, it will be acceptable as an offering made to the LORD by fire.",
    Ind:"\"Apabila seekor anak lembu atau anak domba atau anak kambing dilahirkan, maka haruslah itu tinggal tujuh hari lamanya dengan induknya, tetapi sejak hari kedelapan dan seterusnya TUHAN berkenan akan binatang itu kalau dipersembahkan berupa korban api-apian bagi-Nya."
  },
  {Bible:"Leviticus", Chapter:22, Verse:28, Page:1,
    Kor:"그 어미가 암소거나 암양이거나 간에, 너희는 그 어미와 새끼를 같은 날에 죽여서는 안 된다.",
    Chn:"无论是母牛是母羊，不可同日宰母和子。",
    Eng:"Do not slaughter a cow or a sheep and its young on the same day.",
    Ind:"Seekor lembu atau kambing atau domba janganlah kamu sembelih bersama dengan anaknya pada satu hari juga."
  },
  {Bible:"Leviticus", Chapter:22, Verse:29, Page:1,
    Kor:"○너희가 나 주에게 감사의 제물을 바칠 때에, 너희가 바치는 그 제물을 나 주가 기쁨으로 받게 바쳐야 한다.",
    Chn:"你们献感谢祭给耶和华，要献得可蒙悦纳。",
    Eng:"\"When you sacrifice a thank offering to the LORD, sacrifice it in such a way that it will be accepted on your behalf.",
    Ind:"Dan apabila kamu menyembelih korban syukur bagi TUHAN, kamu harus menyembelihnya sedemikian, hingga TUHAN berkenan akan kamu."
  },
  {Bible:"Leviticus", Chapter:22, Verse:30, Page:1,
    Kor:"제물로 바친 것은 그 날로 너희가 다 먹고, 다음날 아침까지 남겨 두어서는 안 된다. 나는 주다.",
    Chn:"要当天吃，一点不可留到早晨。我是耶和华。",
    Eng:"It must be eaten that same day; leave none of it till morning. I am the LORD.",
    Ind:"Pada hari itu juga korban itu harus dimakan; janganlah kamu tinggalkan apa-apa dari padanya sampai pagi; Akulah TUHAN."
  },
  {Bible:"Leviticus", Chapter:22, Verse:31, Page:1,
    Kor:"○너희는 내가 명한 것을 지켜, 그대로 하여야 한다. 나는 주다.",
    Chn:"「你们要谨守遵行我的诫命。我是耶和华。",
    Eng:"\"Keep my commands and follow them. I am the LORD.",
    Ind:"Dengan demikian kamu harus berpegang pada perintah-Ku dan melakukannya; Akulah TUHAN."
  },
  {Bible:"Leviticus", Chapter:22, Verse:32, Page:1,
    Kor:"내가 이스라엘 자손 가운데서 나의 거룩함을 나타낼 것이니, 너희는 나의 거룩한 이름을 욕되게 해서는 안 된다. 나는 너희를 거룩하게 하는 주다.",
    Chn:"你们不可亵渎我的圣名；我在以色列人中，却要被尊为圣。我是叫你们成圣的耶和华，",
    Eng:"Do not profane my holy name. I must be acknowledged as holy by the Israelites. I am the LORD, who makes you holy",
    Ind:"Janganlah melanggar kekudusan nama-Ku yang kudus, supaya Aku dikuduskan di tengah-tengah orang Israel, sebab Akulah TUHAN, yang menguduskan kamu,"
  },
  {Bible:"Leviticus", Chapter:22, Verse:33, Page:1,
    Kor:"나는 너희의 하나님이 되려고, 너희를 이집트 땅에서 이끌어 내었다. 나는 주다.\"",
    Chn:"把你们从埃及地领出来，作你们的　神。我是耶和华。」",
    Eng:"and who brought you out of Egypt to be your God. I am the LORD.\"",
    Ind:"yang membawa kamu keluar dari tanah Mesir, supaya Aku menjadi Allahmu; Akulah TUHAN.\""
  },
]);
