// 레위기 26장 · Leviticus 26
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Leviticus",26,46);
BibleDB.add([
  {Bible:"Leviticus", Chapter:26, Verse:1, Page:1, Kor:"", Chn:"", Eng:""'Do not make idols or set up an image or a sacred stone for yourselves, and do not place a carved stone in your land to bow down before it. I am the LORD your God.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:2, Page:1, Kor:"", Chn:"", Eng:""'Observe my Sabbaths and have reverence for my sanctuary. I am the LORD.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:3, Page:1, Kor:"", Chn:"", Eng:""'If you follow my decrees and are careful to obey my commands,", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:4, Page:1, Kor:"", Chn:"", Eng:"I will send you rain in its season, and the ground will yield its crops and the trees of the field their fruit.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Your threshing will continue until grape harvest and the grape harvest will continue until planting, and you will eat all the food you want and live in safety in your land.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:6, Page:1, Kor:"", Chn:"", Eng:""'I will grant peace in the land, and you will lie down and no one will make you afraid. I will remove savage beasts from the land, and the sword will not pass through your country.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:7, Page:1, Kor:"", Chn:"", Eng:"You will pursue your enemies, and they will fall by the sword before you.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Five of you will chase a hundred, and a hundred of you will chase ten thousand, and your enemies will fall by the sword before you.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:9, Page:1, Kor:"", Chn:"", Eng:""'I will look on you with favor and make you fruitful and increase your numbers, and I will keep my covenant with you.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:10, Page:1, Kor:"", Chn:"", Eng:"You will still be eating last year's harvest when you will have to move it out to make room for the new.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:11, Page:1, Kor:"", Chn:"", Eng:"I will put my dwelling place among you, and I will not abhor you.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:12, Page:1, Kor:"", Chn:"", Eng:"I will walk among you and be your God, and you will be my people.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:13, Page:1, Kor:"", Chn:"", Eng:"I am the LORD your God, who brought you out of Egypt so that you would no longer be slaves to the Egyptians; I broke the bars of your yoke and enabled you to walk with heads held high.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:14, Page:1, Kor:"", Chn:"", Eng:""'But if you will not listen to me and carry out all these commands,", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:15, Page:1, Kor:"", Chn:"", Eng:"and if you reject my decrees and abhor my laws and fail to carry out all my commands and so violate my covenant,", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:16, Page:1, Kor:"", Chn:"", Eng:"then I will do this to you: I will bring upon you sudden terror, wasting diseases and fever that will destroy your sight and drain away your life. You will plant seed in vain, because your enemies will eat it.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:17, Page:1, Kor:"", Chn:"", Eng:"I will set my face against you so that you will be defeated by your enemies; those who hate you will rule over you, and you will flee even when no one is pursuing you.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:18, Page:1, Kor:"", Chn:"", Eng:""'If after all this you will not listen to me, I will punish you for your sins seven times over.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:19, Page:1, Kor:"", Chn:"", Eng:"I will break down your stubborn pride and make the sky above you like iron and the ground beneath you like bronze.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Your strength will be spent in vain, because your soil will not yield its crops, nor will the trees of the land yield their fruit.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:21, Page:1, Kor:"", Chn:"", Eng:""'If you remain hostile toward me and refuse to listen to me, I will multiply your afflictions seven times over, as your sins deserve.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:22, Page:1, Kor:"", Chn:"", Eng:"I will send wild animals against you, and they will rob you of your children, destroy your cattle and make you so few in number that your roads will be deserted.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:23, Page:1, Kor:"", Chn:"", Eng:""'If in spite of these things you do not accept my correction but continue to be hostile toward me,", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:24, Page:1, Kor:"", Chn:"", Eng:"I myself will be hostile toward you and will afflict you for your sins seven times over.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:25, Page:1, Kor:"", Chn:"", Eng:"And I will bring the sword upon you to avenge the breaking of the covenant. When you withdraw into your cities, I will send a plague among you, and you will be given into enemy hands.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:26, Page:1, Kor:"", Chn:"", Eng:"When I cut off your supply of bread, ten women will be able to bake your bread in one oven, and they will dole out the bread by weight. You will eat, but you will not be satisfied.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:27, Page:1, Kor:"", Chn:"", Eng:""'If in spite of this you still do not listen to me but continue to be hostile toward me,", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:28, Page:1, Kor:"", Chn:"", Eng:"then in my anger I will be hostile toward you, and I myself will punish you for your sins seven times over.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:29, Page:1, Kor:"", Chn:"", Eng:"You will eat the flesh of your sons and the flesh of your daughters.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:30, Page:1, Kor:"", Chn:"", Eng:"I will destroy your high places, cut down your incense altars and pile your dead bodies on the lifeless forms of your idols, and I will abhor you.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:31, Page:1, Kor:"", Chn:"", Eng:"I will turn your cities into ruins and lay waste your sanctuaries, and I will take no delight in the pleasing aroma of your offerings.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:32, Page:1, Kor:"", Chn:"", Eng:"I will lay waste the land, so that your enemies who live there will be appalled.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:33, Page:1, Kor:"", Chn:"", Eng:"I will scatter you among the nations and will draw out my sword and pursue you. Your land will be laid waste, and your cities will lie in ruins.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:34, Page:1, Kor:"", Chn:"", Eng:"Then the land will enjoy its sabbath years all the time that it lies desolate and you are in the country of your enemies; then the land will rest and enjoy its sabbaths.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:35, Page:1, Kor:"", Chn:"", Eng:"All the time that it lies desolate, the land will have the rest it did not have during the sabbaths you lived in it.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:36, Page:1, Kor:"", Chn:"", Eng:""'As for those of you who are left, I will make their hearts so fearful in the lands of their enemies that the sound of a windblown leaf will put them to flight. They will run as though fleeing from the sword, and they will fall, even though no one is pursuing them.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:37, Page:1, Kor:"", Chn:"", Eng:"They will stumble over one another as though fleeing from the sword, even though no one is pursuing them. So you will not be able to stand before your enemies.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:38, Page:1, Kor:"", Chn:"", Eng:"You will perish among the nations; the land of your enemies will devour you.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:39, Page:1, Kor:"", Chn:"", Eng:"Those of you who are left will waste away in the lands of their enemies because of their sins; also because of their fathers' sins they will waste away.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:40, Page:1, Kor:"", Chn:"", Eng:""'But if they will confess their sins and the sins of their fathers--their treachery against me and their hostility toward me,", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:41, Page:1, Kor:"", Chn:"", Eng:"which made me hostile toward them so that I sent them into the land of their enemies--then when their uncircumcised hearts are humbled and they pay for their sin,", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:42, Page:1, Kor:"", Chn:"", Eng:"I will remember my covenant with Jacob and my covenant with Isaac and my covenant with Abraham, and I will remember the land.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:43, Page:1, Kor:"", Chn:"", Eng:"For the land will be deserted by them and will enjoy its sabbaths while it lies desolate without them. They will pay for their sins because they rejected my laws and abhorred my decrees.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:44, Page:1, Kor:"", Chn:"", Eng:"Yet in spite of this, when they are in the land of their enemies, I will not reject them or abhor them so as to destroy them completely, breaking my covenant with them. I am the LORD their God.", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:45, Page:1, Kor:"", Chn:"", Eng:"But for their sake I will remember the covenant with their ancestors whom I brought out of Egypt in the sight of the nations to be their God. I am the LORD.'"", Ind:""},
  {Bible:"Leviticus", Chapter:26, Verse:46, Page:1, Kor:"", Chn:"", Eng:"These are the decrees, the laws and the regulations that the LORD established on Mount Sinai between himself and the Israelites through Moses.", Ind:""},
]);
