// 레위기 26장 · Leviticus 26
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Leviticus",26,46);
BibleDB.add([
  {Bible:"Leviticus", Chapter:26, Verse:1, Page:1,
    Kor:"너희는 우상을 만들거나 조각한 신상을 세우거나 돌기둥을 세워서는 안 된다. 또 너희가 사는 땅에 조각한 석상을 세우고 그것들에게 절해서는 안 된다. 나는 주 너희의 하나님이다.",
    Chn:"「你们不可做什么虚无的神像，不可立雕刻的偶像或是柱像，也不可在你们的地上安什么錾成的石像，向它跪拜，因为我是耶和华—你们的　神。",
    Eng:"\"'Do not make idols or set up an image or a sacred stone for yourselves, and do not place a carved stone in your land to bow down before it. I am the LORD your God.",
    Ind:"\"Janganlah kamu membuat berhala bagimu, dan patung atau tugu berhala janganlah kamu dirikan bagimu; juga batu berukir janganlah kamu tempatkan di negerimu untuk sujud menyembah kepadanya, sebab Akulah TUHAN, Allahmu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:2, Page:1,
    Kor:"너희는 내가 정하여 준 안식의 절기들을 지켜야 한다. 너희는 나에게 예배하는 성소를 속되게 해서는 안 된다. 나는 주다.\"",
    Chn:"你们要守我的安息日，敬我的圣所。我是耶和华。",
    Eng:"\"'Observe my Sabbaths and have reverence for my sanctuary. I am the LORD.",
    Ind:"Kamu harus memelihara hari-hari Sabat-Ku dan menghormati tempat kudus-Ku, Akulah TUHAN."
  },
  {Bible:"Leviticus", Chapter:26, Verse:3, Page:1,
    Kor:"<상과 벌> ○\"너희가, 내가 세운 규례를 따르고, 내가 명한 계명을 그대로 받들어 지키면,",
    Chn:"「你们若遵行我的律例，谨守我的诫命，",
    Eng:"\"'If you follow my decrees and are careful to obey my commands,",
    Ind:"Jikalau kamu hidup menurut ketetapan-Ku dan tetap berpegang pada perintah-Ku serta melakukannya,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:4, Page:1,
    Kor:"나는 철 따라 너희에게 비를 내리겠다. 땅은 소출을 내고, 들의 나무들은 열매를 맺을 것이다.",
    Chn:"我就给你们降下时雨，叫地生出土产，田野的树木结果子。",
    Eng:"I will send you rain in its season, and the ground will yield its crops and the trees of the field their fruit.",
    Ind:"maka Aku akan memberi kamu hujan pada masanya, sehingga tanah itu memberi hasilnya dan pohon-pohonan di ladangmu akan memberi buahnya."
  },
  {Bible:"Leviticus", Chapter:26, Verse:5, Page:1,
    Kor:"너희는, 거두어들인 곡식이 너무 많아서 포도를 딸 무렵에 가서야 타작을 겨우 끝낼 것이며, 포도도 너무 많이 달려서 씨앗을 뿌릴 때가 되어야 포도 따는 일을 겨우 끝낼 것이다. 너희는 배불리 먹고, 너희 땅에서 안전하게 살 것이다.",
    Chn:"你们打粮食要打到摘葡萄的时候，摘葡萄要摘到撒种的时候；并且要吃得饱足，在你们的地上安然居住。",
    Eng:"Your threshing will continue until grape harvest and the grape harvest will continue until planting, and you will eat all the food you want and live in safety in your land.",
    Ind:"Lamanya musim mengirik bagimu akan sampai kepada musim memetik buah anggur dan lamanya musim memetik buah anggur akan sampai kepada musim menabur. Kamu akan makan makananmu sampai kenyang dan diam di negerimu dengan aman tenteram."
  },
  {Bible:"Leviticus", Chapter:26, Verse:6, Page:1,
    Kor:"내가 땅을 평화롭게 하겠다. 너희는 두 다리를 쭉 뻗고 잘 것이며, 아무도 너희를 위협하지 못할 것이다. 나는 그 땅에서 사나운 짐승들을 없애고, 칼이 너희의 땅에서 설치지 못하게 하겠다.",
    Chn:"我要赐平安在你们的地上；你们躺卧，无人惊吓。我要叫恶兽从你们的地上息灭；刀剑也必不经过你们的地。",
    Eng:"\"'I will grant peace in the land, and you will lie down and no one will make you afraid. I will remove savage beasts from the land, and the sword will not pass through your country.",
    Ind:"Dan Aku akan memberi damai sejahtera di dalam negeri itu, sehingga kamu akan berbaring dengan tidak dikejutkan oleh apapun; Aku akan melenyapkan binatang buas dari negeri itu, dan pedang tidak akan melintas di negerimu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:7, Page:1,
    Kor:"너희의 원수들은 너희에게 쫓기다가, 너희가 보는 앞에서 칼에 맞아 쓰러지고 말 것이다.",
    Chn:"你们要追赶仇敌，他们必倒在你们刀下。",
    Eng:"You will pursue your enemies, and they will fall by the sword before you.",
    Ind:"Kamu akan mengejar musuhmu, dan mereka akan tewas di hadapanmu oleh pedang."
  },
  {Bible:"Leviticus", Chapter:26, Verse:8, Page:1,
    Kor:"그들 백 명이 너희 다섯 명에게 쫓기고, 그들 만 명이 너희 백 명에게 쫓길 것이다. 너희의 원수들이, 너희가 보는 앞에서 칼에 맞아 쓰러지고 말 것이다.",
    Chn:"你们五个人要追赶一百人，一百人要追赶一万人；仇敌必倒在你们刀下。",
    Eng:"Five of you will chase a hundred, and a hundred of you will chase ten thousand, and your enemies will fall by the sword before you.",
    Ind:"Lima orang dari antaramu akan mengejar seratus, dan seratus orang dari antaramu akan mengejar selaksa dan semua musuhmu akan tewas di hadapanmu oleh pedang."
  },
  {Bible:"Leviticus", Chapter:26, Verse:9, Page:1,
    Kor:"나는 너희를 보살펴, 자손을 낳게 하고, 자손이 많게 하겠다. 너희와 세운 언약을 나는 꼭 지킨다.",
    Chn:"我要眷顾你们，使你们生养众多，也要与你们坚定所立的约。",
    Eng:"\"'I will look on you with favor and make you fruitful and increase your numbers, and I will keep my covenant with you.",
    Ind:"Dan Aku akan berpaling kepadamu dan akan membuat kamu beranak cucu serta bertambah banyak dan Aku akan meneguhkan perjanjian-Ku dengan kamu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:10, Page:1,
    Kor:"너희는, 지난 해에 거두어들인 곡식을 미처 다 먹지도 못한 채, 햇곡식을 저장하려고, 해묵은 곡식을 바깥으로 퍼내야만 할 것이다.",
    Chn:"你们要吃陈粮，又因新粮挪开陈粮。",
    Eng:"You will still be eating last year's harvest when you will have to move it out to make room for the new.",
    Ind:"Kamu masih akan makan hasil lama dari panen yang lampau, dan hasil lama itu akan kamu keluarkan untuk menyimpan yang baru."
  },
  {Bible:"Leviticus", Chapter:26, Verse:11, Page:1,
    Kor:"너희가 사는 곳에서 나도 같이 살겠다. 나는 너희를 싫어하지 않는다.",
    Chn:"我要在你们中间立我的帐幕；我的心也不厌恶你们。",
    Eng:"I will put my dwelling place among you, and I will not abhor you.",
    Ind:"Aku akan menempatkan Kemah Suci-Ku di tengah-tengahmu dan hati-Ku tidak akan muak melihat kamu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:12, Page:1,
    Kor:"나는 너희 사이에서 거닐겠다. 나는 너희의 하나님이 되고, 너희는 나의 백성이 될 것이다.",
    Chn:"我要在你们中间行走；我要作你们的　神，你们要作我的子民。",
    Eng:"I will walk among you and be your God, and you will be my people.",
    Ind:"Tetapi Aku akan hadir di tengah-tengahmu dan Aku akan menjadi Allahmu dan kamu akan menjadi umat-Ku."
  },
  {Bible:"Leviticus", Chapter:26, Verse:13, Page:1,
    Kor:"내가 주 너희의 하나님이다. 나는 너희를 이집트 땅에서 이끌어 내어, 그들의 노예가 되지 않도록 하였다. 또, 나는 너희가 메고 있던 멍에의 가름대를 부수어서, 너희가 얼굴을 들고 다니게 하였다.",
    Chn:"我是耶和华—你们的　神，曾将你们从埃及地领出来，使你们不作埃及人的奴仆；我也折断你们所负的轭，叫你们挺身而走。」",
    Eng:"I am the LORD your God, who brought you out of Egypt so that you would no longer be slaves to the Egyptians; I broke the bars of your yoke and enabled you to walk with heads held high.",
    Ind:"Akulah TUHAN, Allahmu, yang membawa kamu keluar dari tanah Mesir, supaya kamu jangan lagi menjadi budak mereka. Aku telah mematahkan kayu kuk yang di atasmu dan membuat kamu berjalan tegak.\""
  },
  {Bible:"Leviticus", Chapter:26, Verse:14, Page:1,
    Kor:"○그러나 너희가, 내가 하는 말을 듣지 않고, 이 모든 명령을 지키지 않거나,",
    Chn:"「你们若不听从我，不遵行我的诫命，",
    Eng:"\"'But if you will not listen to me and carry out all these commands,",
    Ind:"\"Tetapi jikalau kamu tidak mendengarkan Daku, dan tidak melakukan segala perintah itu,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:15, Page:1,
    Kor:"내가 정하여 준 규례를 지키지 않고, 내가 세워 준 법도를 싫어하여, 나의 모든 계명을 그대로 실천하지 않고, 내가 세운 언약을 어기면,",
    Chn:"厌弃我的律例，厌恶我的典章，不遵行我一切的诫命，背弃我的约，",
    Eng:"and if you reject my decrees and abhor my laws and fail to carry out all my commands and so violate my covenant,",
    Ind:"jikalau kamu menolak ketetapan-Ku dan hatimu muak mendengar peraturan-Ku, sehingga kamu tidak melakukan segala perintah-Ku dan kamu mengingkari perjanjian-Ku,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:16, Page:1,
    Kor:"나는 너희에게 다음과 같이 보복하겠다. 갑작스런 재앙 곧 폐병과 열병을 너희에게 보내서, 너희의 눈을 어둡게 하고, 기운이 쏙 빠지게 하겠다. 너희가 씨를 뿌려도, 너희의 원수들이 와서 먹어 버릴 것이다.",
    Chn:"我待你们就要这样：我必命定惊惶，叫眼目干瘪、精神消耗的痨病热病辖制你们。你们也要白白地撒种，因为仇敌要吃你们所种的。",
    Eng:"then I will do this to you: I will bring upon you sudden terror, wasting diseases and fever that will destroy your sight and drain away your life. You will plant seed in vain, because your enemies will eat it.",
    Ind:"maka Akupun akan berbuat begini kepadamu, yakni Aku akan mendatangkan kekejutan atasmu, batuk kering serta demam, yang membuat mata rusak dan jiwa merana; kamu akan sia-sia menabur benihmu, karena hasilnya akan habis dimakan musuhmu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:17, Page:1,
    Kor:"내가 성난 얼굴로 너희를 쏘아보는 동안에, 너희는 원수들에게 얻어맞을 것이다. 너희를 미워하는 그자들이 너희를 다스릴 것이다. 너희는 쫓는 사람이 없어도 도망다니는 신세가 될 것이다.",
    Chn:"我要向你们变脸，你们就要败在仇敌面前。恨恶你们的，必辖管你们；无人追赶，你们却要逃跑。",
    Eng:"I will set my face against you so that you will be defeated by your enemies; those who hate you will rule over you, and you will flee even when no one is pursuing you.",
    Ind:"Aku sendiri akan menentang kamu, sehingga kamu akan dikalahkan oleh musuhmu, dan mereka yang membenci kamu akan menguasai kamu, dan kamu akan lari, sungguhpun tidak ada orang mengejar kamu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:18, Page:1,
    Kor:"너희가 이 지경이 되어도 나의 말을 듣지 않으면, 이번에는 너희가 지은 죄를 일곱 배로 벌하여,",
    Chn:"你们因这些事若还不听从我，我就要为你们的罪加七倍惩罚你们。",
    Eng:"\"'If after all this you will not listen to me, I will punish you for your sins seven times over.",
    Ind:"Dan jikalau kamu dalam keadaan yang demikianpun tidak mendengarkan Daku, maka Aku akan lebih keras menghajar kamu sampai tujuh kali lipat karena dosamu,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:19, Page:1,
    Kor:"너희가 자랑하는 그 힘을 꺾겠다. 너희의 하늘을 쇠처럼, 너희의 땅을 놋쇠처럼 단단하게 만들겠다.",
    Chn:"我必断绝你们因势力而有的骄傲，又要使覆你们的天如铁，载你们的地如铜。",
    Eng:"I will break down your stubborn pride and make the sky above you like iron and the ground beneath you like bronze.",
    Ind:"dan Aku akan mematahkan kekuasaanmu yang kaubanggakan dan akan membuat langit di atasmu sebagai besi dan tanahmu sebagai tembaga."
  },
  {Bible:"Leviticus", Chapter:26, Verse:20, Page:1,
    Kor:"그러면 너희가 아무리 힘을 써도, 너희의 땅은 소출을 내지 못할 것이며, 땅에 심은 나무도 열매를 맺지 못할 것이다.",
    Chn:"你们要白白地劳力；因为你们的地不出土产，其上的树木也不结果子。",
    Eng:"Your strength will be spent in vain, because your soil will not yield its crops, nor will the trees of the land yield their fruit.",
    Ind:"Maka tenagamu akan habis dengan sia-sia, tanahmu tidak akan memberi hasilnya dan pohon-pohonan di tanah itu tidak akan memberi buahnya."
  },
  {Bible:"Leviticus", Chapter:26, Verse:21, Page:1,
    Kor:"○너희가 나를 거역하여 나의 말에 순종하지 않으면, 나도 너희에게 너희가 지은 죄보다 일곱 배나 벌을 더 내리겠다.",
    Chn:"「你们行事若与我反对，不肯听从我，我就要按你们的罪加七倍降灾与你们。",
    Eng:"\"'If you remain hostile toward me and refuse to listen to me, I will multiply your afflictions seven times over, as your sins deserve.",
    Ind:"Jikalau hidupmu tetap bertentangan dengan Daku dan kamu tidak mau mendengarkan Daku, maka Aku akan makin menambah hukuman atasmu sampai tujuh kali lipat setimpal dengan dosamu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:22, Page:1,
    Kor:"들짐승을 보내서 너희에게 대들게 하겠다. 그 짐승들은 너희의 아이들을 움켜가고, 너희의 가축 떼를 죽일 것이며, 너희의 수가 줄어서 너희가 다니는 길도 한산할 것이다.",
    Chn:"我也要打发野地的走兽到你们中间，抢吃你们的儿女，吞灭你们的牲畜，使你们的人数减少，道路荒凉。",
    Eng:"I will send wild animals against you, and they will rob you of your children, destroy your cattle and make you so few in number that your roads will be deserted.",
    Ind:"Aku akan melepaskan kepadamu binatang liar yang akan memunahkan anak-anakmu dan yang akan melenyapkan ternakmu, serta membuat kamu menjadi sedikit, sehingga jalan-jalanmu menjadi sunyi."
  },
  {Bible:"Leviticus", Chapter:26, Verse:23, Page:1,
    Kor:"일이 이 지경이 될 때까지도, 너희가 나에게로 마음을 돌이키지 않고, 여전히 나를 거역하면,",
    Chn:"「你们因这些事若仍不改正归我，行事与我反对，",
    Eng:"\"'If in spite of these things you do not accept my correction but continue to be hostile toward me,",
    Ind:"Jikalau kamu dalam keadaan yang demikianpun tidak mau Kuajar, dan hidupmu tetap bertentangan dengan Daku,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:24, Page:1,
    Kor:"나도 너희를 거역할 수밖에 없다. 나 역시 너희가 지은 죄를 일곱 배로 보복하겠다.",
    Chn:"我就要行事与你们反对，因你们的罪击打你们七次。",
    Eng:"I myself will be hostile toward you and will afflict you for your sins seven times over.",
    Ind:"maka Akupun akan bertindak melawan kamu dan Aku sendiri akan menghukum kamu tujuh kali lipat karena dosamu,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:25, Page:1,
    Kor:"내가 너희에게 전쟁을 보내어서, 너희가 언약을 어긴 것을 보복하겠다. 너희가 여러 성읍으로 피하면, 너희에게 재앙을 뒤따라 보내서라도, 너희를 원수의 손에 넘겨 주겠다.",
    Chn:"我又要使刀剑临到你们，报复你们背约的仇；聚集你们在各城内，降瘟疫在你们中间，也必将你们交在仇敌的手中。",
    Eng:"And I will bring the sword upon you to avenge the breaking of the covenant. When you withdraw into your cities, I will send a plague among you, and you will be given into enemy hands.",
    Ind:"dan Aku akan mendatangkan ke atasmu suatu pedang, yang akan melakukan pembalasan oleh karena perjanjian itu; bila kamu berkumpul kelak di kota-kotamu, maka Aku akan melepas penyakit sampar ke tengah-tengahmu dan kamu akan diserahkan ke dalam tangan musuh."
  },
  {Bible:"Leviticus", Chapter:26, Verse:26, Page:1,
    Kor:"내가 먹거리를 끊어 버리면, 열 여인이 너희가 먹을 빵을 한 화덕에서 구울 것이며, 그 여인들은 빵을 저울에 달아 너희에게 줄 것이다. 그러면 너희는, 먹기는 먹어도 여전히 배가 고플 것이다.",
    Chn:"我要折断你们的杖，就是断绝你们的粮。那时，必有十个女人在一个炉子给你们烤饼，按分量秤给你们；你们要吃，也吃不饱。",
    Eng:"When I cut off your supply of bread, ten women will be able to bake your bread in one oven, and they will dole out the bread by weight. You will eat, but you will not be satisfied.",
    Ind:"Jika Aku memusnahkan persediaan makananmu, maka sepuluh perempuan akan membakar roti di dalam satu pembakaran. Mereka akan mengembalikan rotimu menurut timbangan tertentu, dan kamu akan makan, tetapi tidak menjadi kenyang."
  },
  {Bible:"Leviticus", Chapter:26, Verse:27, Page:1,
    Kor:"○이렇게까지 하여도, 너희가 나의 말을 듣지 않고, 여전히 나를 거역하면,",
    Chn:"「你们因这一切的事若不听从我，却行事与我反对，",
    Eng:"\"'If in spite of this you still do not listen to me but continue to be hostile toward me,",
    Ind:"Dan jikalau kamu dalam keadaan yang demikianpun tidak mendengarkan Daku, dan hidupmu tetap bertentangan dengan Daku,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:28, Page:1,
    Kor:"나는 더욱 노하여 너희를 거역할 것이며, 너희는 너희가 지은 죄보다 일곱 배나 더 벌을 받게 될 것이다.",
    Chn:"我就要发烈怒，行事与你们反对，又因你们的罪惩罚你们七次。",
    Eng:"then in my anger I will be hostile toward you, and I myself will punish you for your sins seven times over.",
    Ind:"maka Akupun akan bertindak keras melawan kamu dan Aku sendiri akan menghajar kamu tujuh kali lipat karena dosamu,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:29, Page:1,
    Kor:"그렇게 되면, 너희는 너희 아들의 살과 딸의 살이라도 먹을 것이다.",
    Chn:"并且你们要吃儿子的肉，也要吃女儿的肉。",
    Eng:"You will eat the flesh of your sons and the flesh of your daughters.",
    Ind:"dan kamu akan memakan daging anak-anakmu lelaki dan anak-anakmu perempuan."
  },
  {Bible:"Leviticus", Chapter:26, Verse:30, Page:1,
    Kor:"내가 높은 곳에 있는 너희의 산당들을 모조리 부수며, 분향단들을 다 헐고, 너희의 시체를 너희가 섬기는 그 우상들의 시체 위에다 쌓아 놓을 것이다. 나는 도저히 너희를 불쌍히 여길 수 없다.",
    Chn:"我又要毁坏你们的邱坛，砍下你们的日像，把你们的尸首扔在你们偶像的身上；我的心也必厌恶你们。",
    Eng:"I will destroy your high places, cut down your incense altars and pile your dead bodies on the lifeless forms of your idols, and I will abhor you.",
    Ind:"Dan bukit-bukit pengorbananmu akan Kupunahkan, dan segala pedupaanmu akan Kulenyapkan. Aku akan melemparkan bangkai-bangkaimu ke atas bangkai-bangkai berhalamu dan hati-Ku akan muak melihat kamu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:31, Page:1,
    Kor:"너희가 살던 마을들을 폐허로 만들고, 너희가 드나들던 성소들을 황량하게 만들 것이다. 너희가 바치는 향도 기쁘게 받지 않을 것이다.",
    Chn:"我要使你们的城邑变为荒凉，使你们的众圣所成为荒场；我也不闻你们馨香的香气。",
    Eng:"I will turn your cities into ruins and lay waste your sanctuaries, and I will take no delight in the pleasing aroma of your offerings.",
    Ind:"Kota-kotamu akan Kubuat menjadi reruntuhan dan tempat-tempat kudusmu akan Kurusakkan dan Aku tidak mau lagi menghirup bau persembahanmu yang menyenangkan."
  },
  {Bible:"Leviticus", Chapter:26, Verse:32, Page:1,
    Kor:"나는 또 땅을 황폐하게 할 것이다. 거기에서 사는 너희의 원수들은, 거칠고 못쓰게 된 그 땅을 보고 놀랄 것이다.",
    Chn:"我要使地成为荒场，住在其上的仇敌就因此诧异。",
    Eng:"I will lay waste the land, so that your enemies who live there will be appalled.",
    Ind:"Aku sendiri akan merusakkan negeri itu, sehingga musuhmu yang tinggal di situ akan tercengang karenanya."
  },
  {Bible:"Leviticus", Chapter:26, Verse:33, Page:1,
    Kor:"나는 너희를 여러 민족 사이로 흩어 버리고, 칼을 뽑아 너희 뒤를 쫓게 할 것이다. 너희가 살던 땅은 버려진 채, 거칠고 쓸모 없이 될 것이며, 너희가 살던 마을들은 폐허가 될 것이다.",
    Chn:"我要把你们散在列邦中；我也要拔刀追赶你们。你们的地要成为荒场；你们的城邑要变为荒凉。",
    Eng:"I will scatter you among the nations and will draw out my sword and pursue you. Your land will be laid waste, and your cities will lie in ruins.",
    Ind:"Tetapi kamu akan Kuserakkan di antara bangsa-bangsa lain dan Aku akan menghunus pedang di belakang kamu, dan tanahmu akan menjadi tempat tandus dan kota-kotamu akan menjadi reruntuhan."
  },
  {Bible:"Leviticus", Chapter:26, Verse:34, Page:1,
    Kor:"그 때에야 비로소, 땅은 안식을 누릴 것이다. 땅이 그렇게 폐허로 버려져 있는 동안, 곧 너희가 원수들의 나라로 잡혀가 있는 동안에, 비로소 땅은 쉴 것이며, 제 몫의 안식을 누릴 것이다.",
    Chn:"「你们在仇敌之地居住的时候，你们的地荒凉，要享受众安息；正在那时候，地要歇息，享受安息。",
    Eng:"Then the land will enjoy its sabbath years all the time that it lies desolate and you are in the country of your enemies; then the land will rest and enjoy its sabbaths.",
    Ind:"Pada waktu itulah tanah itu pulih dari dilalaikannya tahun-tahun sabatnya selama tanah itu tandus dan selama kamu tinggal di negeri musuh-musuhmu; pada waktu itulah tanah itu akan menjalani sabatnya dan dipulihkan tahun-tahun sabat yang belum didapatnya."
  },
  {Bible:"Leviticus", Chapter:26, Verse:35, Page:1,
    Kor:"너희가 그 땅에 사는 동안에는, 안식년이 되어도 땅이 쉬지 못하였지만, 폐허로 버려져 있는 동안에는, 땅이 쉴 것이다.",
    Chn:"地多时为荒场，就要多时歇息；地这样歇息，是你们住在其上的安息年所不能得的。",
    Eng:"All the time that it lies desolate, the land will have the rest it did not have during the sabbaths you lived in it.",
    Ind:"Selama ketandusannya tanah itu akan menjalani sabat yang belum dijalaninya pada tiap-tiap tahun sabatmu, ketika kamu masih diam di situ."
  },
  {Bible:"Leviticus", Chapter:26, Verse:36, Page:1,
    Kor:"○너희 가운데 살아 남은 사람들이 원수의 땅에 끌려가 사는 동안에, 내가 그들의 마음에 공포심을 일으켜, 바람에 나뭇잎 떨어지는 소리만 나도, 칼을 피해 도망가듯, 기겁하고 달아나게 하겠다. 그들은, 아무도 뒤쫓지 않아도 달아나다 넘어질 것이다.",
    Chn:"至于你们剩下的人，我要使他们在仇敌之地心惊胆怯。叶子被风吹的响声，要追赶他们；他们要逃避，像人逃避刀剑，无人追赶，却要跌倒。",
    Eng:"\"'As for those of you who are left, I will make their hearts so fearful in the lands of their enemies that the sound of a windblown leaf will put them to flight. They will run as though fleeing from the sword, and they will fall, even though no one is pursuing them.",
    Ind:"Dan mengenai mereka yang masih tinggal hidup dari antaramu, Aku akan mendatangkan kecemasan ke dalam hati mereka di dalam negeri-negeri musuh mereka, sehingga bunyi daun yang ditiupkan anginpun akan mengejar mereka, dan mereka akan lari seperti orang lari menjauhi pedang, dan mereka akan rebah, sungguhpun tidak ada orang yang mengejar."
  },
  {Bible:"Leviticus", Chapter:26, Verse:37, Page:1,
    Kor:"아무도 뒤쫓지 않아도, 칼날을 피하여 도망가듯, 서로 엎치락뒤치락 비틀거릴 것이다. 너희는 절대로 너희의 원수들과는 맞설 수 없다.",
    Chn:"无人追赶，他们要彼此撞跌，像在刀剑之前。你们在仇敌面前也必站立不住。",
    Eng:"They will stumble over one another as though fleeing from the sword, even though no one is pursuing them. So you will not be able to stand before your enemies.",
    Ind:"Dan mereka akan jatuh tersandung seorang kepada seorang seolah-olah hendak menjauhi pedang, sungguhpun yang mengejar tidak ada, dan kamu tidak akan dapat bertahan di hadapan musuh-musuhmu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:38, Page:1,
    Kor:"마침내 너희는 망하여, 다른 민족 사이에 흩어질 것이며, 원수들의 땅이 너희를 삼킬 것이다.",
    Chn:"你们要在列邦中灭亡；仇敌之地要吞吃你们。",
    Eng:"You will perish among the nations; the land of your enemies will devour you.",
    Ind:"Dan kamu akan binasa di antara bangsa-bangsa lain, dan negeri musuhmu akan memusnahkan kamu."
  },
  {Bible:"Leviticus", Chapter:26, Verse:39, Page:1,
    Kor:"너희 가운데 살아 남아 원수의 땅으로 끌려간 사람들은, 그 지은 죄 때문에 힘이 약해질 것이다. 조상들이 지은 죄 때문에도, 그들은 힘이 약해질 것이다.",
    Chn:"你们剩下的人必因自己的罪孽和祖宗的罪孽在仇敌之地消灭。",
    Eng:"Those of you who are left will waste away in the lands of their enemies because of their sins; also because of their fathers' sins they will waste away.",
    Ind:"Dan siapa yang masih tinggal hidup dari antaramu, mereka akan hancur lebur dalam hukumannya di negeri-negeri musuh mereka, dan karena kesalahan nenek moyang mereka juga mereka akan hancur lebur sama seperti nenek moyangnya."
  },
  {Bible:"Leviticus", Chapter:26, Verse:40, Page:1,
    Kor:"그러나 그들이, 자기들이 지은 죄와 조상들이 지은 죄, 곧 그들이 나를 배신하고 나에게 반항한 허물을 고백하면, 또 그들이 나를 거슬렀으므로,",
    Chn:"「他们要承认自己的罪和他们祖宗的罪，就是干犯我的那罪，并且承认自己行事与我反对，",
    Eng:"\"'But if they will confess their sins and the sins of their fathers--their treachery against me and their hostility toward me,",
    Ind:"Tetapi bila mereka mengakui kesalahan mereka dan kesalahan nenek moyang mereka dalam hal berubah setia yang dilakukan mereka terhadap Aku dan mengakui juga bahwa hidup mereka bertentangan dengan Daku"
  },
  {Bible:"Leviticus", Chapter:26, Verse:41, Page:1,
    Kor:"내가 그들을 거스르지 않을 수 없었다는 것과, 그래서 내가 그들을 원수가 사는 땅으로 보냈다는 것을 깨닫고, 할례 받지 못한 그들의 마음이 겸손해져서, 자기들이 지은 죄로 벌을 기꺼이 받으면,",
    Chn:"我所以行事与他们反对，把他们带到仇敌之地。那时，他们未受割礼的心若谦卑了，他们也服了罪孽的刑罚，",
    Eng:"which made me hostile toward them so that I sent them into the land of their enemies--then when their uncircumcised hearts are humbled and they pay for their sin,",
    Ind:"--Akupun bertindak melawan mereka dan membawa mereka ke negeri musuh mereka--atau bila kemudian hati mereka yang tidak bersunat itu telah tunduk dan mereka telah membayar pulih kesalahan mereka,"
  },
  {Bible:"Leviticus", Chapter:26, Verse:42, Page:1,
    Kor:"나는, 야곱과 맺은 언약과 이삭과 맺은 언약과 아브라함과 맺은 언약을 기억하고, 또 그 땅도 기억하겠다.",
    Chn:"我就要记念我与雅各所立的约，与以撒所立的约，与亚伯拉罕所立的约，并要记念这地。",
    Eng:"I will remember my covenant with Jacob and my covenant with Isaac and my covenant with Abraham, and I will remember the land.",
    Ind:"maka Aku akan mengingat perjanjian-Ku dengan Yakub; juga perjanjian dengan Ishak dan perjanjian-Ku dengan Abrahampun akan Kuingat dan negeri itu akan Kuingat juga."
  },
  {Bible:"Leviticus", Chapter:26, Verse:43, Page:1,
    Kor:"그들에게 버림받은 그 땅은, 오히려 그들이 없는 동안 폐허로 있으면서, 안식을 누릴 것이다. 그 기간에 그들은 내가 명한 법도를 거역한 죄값과 내가 세운 규례를 지키지 않은 죄값을 치를 것이다.",
    Chn:"他们离开这地，地在荒废无人的时候就要享受安息。并且他们要服罪孽的刑罚；因为他们厌弃了我的典章，心中厌恶了我的律例。",
    Eng:"For the land will be deserted by them and will enjoy its sabbaths while it lies desolate without them. They will pay for their sins because they rejected my laws and abhorred my decrees.",
    Ind:"Jadi tanah itu akan ditinggalkan mereka dan akan pulih dari akibat tahun-tahun sabat yang dilalaikan selama tanah itu tandus, oleh karena ditinggalkan mereka, dan mereka akan membayar pulih kesalahan mereka, tak lain dan tak bukan karena mereka menolak peraturan-Ku dan hati mereka muak mendengarkan ketetapan-Ku."
  },
  {Bible:"Leviticus", Chapter:26, Verse:44, Page:1,
    Kor:"비록 그들이 죄값을 치르고 있더라도, 그들이 원수의 땅에 잡혀가 있는 동안에, 나는 절대로 그들을 버리지 않겠다. 미워하지도 않고 멸망시키지도 않겠다. 그래서 그들과 세운 나의 언약을 깨뜨리지 않겠다. 내가 주 그들의 하나님이기 때문이다.",
    Chn:"虽是这样，他们在仇敌之地，我却不厌弃他们，也不厌恶他们，将他们尽行灭绝，也不背弃我与他们所立的约，因为我是耶和华—他们的　神。",
    Eng:"Yet in spite of this, when they are in the land of their enemies, I will not reject them or abhor them so as to destroy them completely, breaking my covenant with them. I am the LORD their God.",
    Ind:"Namun demikian, apabila mereka ada di negeri musuh mereka, Aku tidak akan menolak mereka dan tidak akan muak melihat mereka, sehingga Aku membinasakan mereka dan membatalkan perjanjian-Ku dengan mereka, sebab Akulah TUHAN, Allah mereka."
  },
  {Bible:"Leviticus", Chapter:26, Verse:45, Page:1,
    Kor:"그들을 돌보려고, 나는, 내가 이집트 땅에서 이끌어 낸 그 첫 세대와 맺은 언약을 기억할 것이다. 나는 그들의 하나님이 되려고, 뭇 민족이 보는 앞에서 그들을 이끌어 내었다. 나는 주다.\"",
    Chn:"我却要为他们的缘故记念我与他们先祖所立的约。他们的先祖是我在列邦人眼前、从埃及地领出来的，为要作他们的　神。我是耶和华。」",
    Eng:"But for their sake I will remember the covenant with their ancestors whom I brought out of Egypt in the sight of the nations to be their God. I am the LORD.'\"",
    Ind:"Untuk keselamatan mereka Aku akan mengingat perjanjian dengan orang-orang dahulu yang Kubawa keluar dari tanah Mesir di depan mata bangsa-bangsa lain, supaya Aku menjadi Allah mereka; Akulah TUHAN.\""
  },
  {Bible:"Leviticus", Chapter:26, Verse:46, Page:1,
    Kor:"○이상은 주님께서 시내 산에서 모세를 시켜, 주님과 이스라엘 자손 사이에 세우신 여러 가지 규례와 법도와 율법이다.",
    Chn:"这些律例、典章，和法度是耶和华与以色列人在西奈山借着摩西立的。",
    Eng:"These are the decrees, the laws and the regulations that the LORD established on Mount Sinai between himself and the Israelites through Moses.",
    Ind:"Itulah ketetapan-ketetapan dan peraturan-peraturan serta hukum-hukum yang diberikan TUHAN, berlaku di antara Dia dengan orang Israel, di gunung Sinai, dengan perantaraan Musa."
  },
]);
