// 레위기 10장 · Leviticus 10
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Leviticus",10,20);
BibleDB.add([
  {Bible:"Leviticus", Chapter:10, Verse:1, Page:1, Kor:"<나답과 아비후가 벌을 받아 죽다> 아론의 아들 가운데서, 나답과 아비후가 제각기 자기의 향로를 가져다가, 거기에 불을 담고 향을 피워서 주님께로 가져 갔다. 그러나 그 불은 주님께서 그들에게 명하신 것과는 다른 금지된 불이다.", Chn:"", Eng:"Aaron's sons Nadab and Abihu took their censers, put fire in them and added incense; and they offered unauthorized fire before the LORD, contrary to his command.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:2, Page:1, Kor:"주님 앞에서 불이 나와서 그들을 삼키니, 그들은 주님 앞에서 죽고 말았다.", Chn:"", Eng:"So fire came out from the presence of the LORD and consumed them, and they died before the LORD.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:3, Page:1, Kor:"모세가 아론에게 말하였다. \"주님께서 '내게 가까이 있는 이들에게 나의 거룩함을 보이겠고, 모든 백성에게 나의 위엄을 나타내리라' 하신 말씀은, 바로 이것을 두고 하신 말씀입니다.\" 아론은 아무 말도 못하였다.", Chn:"", Eng:"Moses then said to Aaron, \"This is what the LORD spoke of when he said: \"'Among those who approach me I will show myself holy; in the sight of all the people I will be honored.'\" Aaron remained silent.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:4, Page:1, Kor:"○모세는 미사엘과 엘사반을 불렀다. 그들은 아론의 삼촌 웃시엘의 아들들이다. 모세는 그들에게 그들의 조카들의 시체를 성소에서 진 바깥으로 옮기라고 하였다.", Chn:"", Eng:"Moses summoned Mishael and Elzaphan, sons of Aaron's uncle Uzziel, and said to them, \"Come here; carry your cousins outside the camp, away from the front of the sanctuary.\"", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:5, Page:1, Kor:"그들은 모세가 시킨 대로 가까이 가서, 조카들의 옷을 잡아 끌어 진 바깥으로 옮겼다.", Chn:"", Eng:"So they came and carried them, still in their tunics, outside the camp, as Moses ordered.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:6, Page:1, Kor:"○모세는 아론과 그의 아들들 곧 엘르아살과 이다말에게 말하였다. \"당신들은 머리를 풀거나 옷을 찢어 애도를 해서는 안 됩니다. 그렇게 하다가는 당신들마저 죽을 것입니다. 주님의 진노가 모든 회중에게까지 미치지 않도록 하십시오. 다만 당신들의 동족 곧 온 이스라엘 집안만이, 주님의 진노로 03 10:타 죽은 이들을 생각하며 애도할 것입니다.", Chn:"", Eng:"Then Moses said to Aaron and his sons Eleazar and Ithamar, \"Do not let your hair become unkempt, and do not tear your clothes, or you will die and the LORD will be angry with the whole community. But your relatives, all the house of Israel, may mourn for those the LORD has destroyed by fire.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:7, Page:1, Kor:"당신들은 회막 어귀 바깥으로 나가지 마십시오. 어기면, 당신들도 죽을 것입니다. 당신들은, 주님께서 기름부어 거룩하게 구별하신 사람들입니다.\" 그들은 모세가 시킨 대로 하였다.", Chn:"", Eng:"Do not leave the entrance to the Tent of Meeting or you will die, because the LORD'S anointing oil is on you.\" So they did as Moses said.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:8, Page:1, Kor:"<회막에 들어올 때에 지켜야 할 규례> ○주님께서 아론에게 말씀하셨다.", Chn:"", Eng:"Then the LORD said to Aaron,", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:9, Page:1, Kor:"\"너의 아들들이 너와 함께 회막으로 들어올 때에는 포도주나 독주를 마시지 말아라. 어기면 죽는다. 이것은 너희가 대대로 영원히 지켜야 할 규례이다.", Chn:"", Eng:"\"You and your sons are not to drink wine or other fermented drink whenever you go into the Tent of Meeting, or you will die. This is a lasting ordinance for the generations to come.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:10, Page:1, Kor:"너희는 거룩한 것과 속된 것을 구별하여야 하고, 부정한 것과 정한 것을 구별하여야 한다.", Chn:"", Eng:"You must distinguish between the holy and the common, between the unclean and the clean,", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:11, Page:1, Kor:"또 너희는 나 주가 모세를 시켜 말한 모든 규례를 이스라엘 자손에게 가르쳐야 할 사람들이다.\"", Chn:"", Eng:"and you must teach the Israelites all the decrees the LORD has given them through Moses.\"", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:12, Page:1, Kor:"<제사장이 성소에서 먹을 제물> ○모세는, 아론 및 살아 남은 아론의 두 아들 엘르아살과 이다말에게 말하였다. \"주님께 살라 바치는 제사를 드리고 남은 곡식제물은 형님과 형님의 아들들이 가지십시오. 누룩을 넣지 않고 만든 것은 제단 옆에서 먹도록 하십시오. 그것은 가장 거룩한 제물이므로,", Chn:"", Eng:"Moses said to Aaron and his remaining sons, Eleazar and Ithamar, \"Take the grain offering left over from the offerings made to the LORD by fire and eat it prepared without yeast beside the altar, for it is most holy.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:13, Page:1, Kor:"거룩한 곳에서만 먹어야 합니다. 그것은 주님께 살라 바치는 제물 가운데서, 형님과 형님의 아들들이 받은 몫이기 때문입니다. 주님께서 나에게 그렇게 명하셨습니다.", Chn:"", Eng:"Eat it in a holy place, because it is your share and your sons' share of the offerings made to the LORD by fire; for so I have been commanded.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:14, Page:1, Kor:"그러나 흔들어 바치는 가슴 고기와 높이 들어 바치는 넓적다리 고기는, 정결한 곳이면 어느 곳에서든지, 형님과 형님의 아들들과 형님의 딸들도 함께 먹을 수 있습니다. 그것들은 이스라엘 자손이 바친 화목제사의 제물 가운데서, 형님과 형님의 아들들의 몫으로 주신 것이기 때문입니다.", Chn:"", Eng:"But you and your sons and your daughters may eat the breast that was waved and the thigh that was presented. Eat them in a ceremonially clean place; they have been given to you and your children as your share of the Israelites' fellowship offerings.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:15, Page:1, Kor:"기름기를 불에 살라 바치면서, 함께 높이 들어 바치는 넓적다리 고기와 흔들어 바치는 가슴 고기는, 주님 앞에서 흔들어서 바치고 나면, 주님께서 명하신 대로, 영원히 형님과 형님의 아들들이 차지할 몫이 됩니다.\"", Chn:"", Eng:"The thigh that was presented and the breast that was waved must be brought with the fat portions of the offerings made by fire, to be waved before the LORD as a wave offering. This will be the regular share for you and your children, as the LORD has commanded.\"", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:16, Page:1, Kor:"○모세는 백성이 속죄제물로 바친 숫염소를 애써서 찾아 보았다. 그러나 그것은 이미 타 버리고 없었다. 모세는 아론의 남은 두 아들, 엘르아살과 이다말에게 화를 내면서 다그쳤다.", Chn:"", Eng:"When Moses inquired about the goat of the sin offering and found that it had been burned up, he was angry with Eleazar and Ithamar, Aaron's remaining sons, and asked,", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:17, Page:1, Kor:"\"어찌하여 너희는 성소에서 먹어야 할 그 속죄제물을 먹지 않고 불살랐느냐? 속죄제물은 가장 거룩한 것이 아니냐? 너희가 주님 앞에서 회중의 죄를 속하여 주어서 그들이 용서받게 하려고, 이 제물을 너희에게 먹으라고 주신 것이 아니냐?", Chn:"", Eng:"\"Why didn't you eat the sin offering in the sanctuary area? It is most holy; it was given to you to take away the guilt of the community by making atonement for them before the LORD.", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:18, Page:1, Kor:"그것은 성소 안에까지 피를 가지고 들어가는 제물이 아니므로, 너희는 내가 명령한 대로, 그 제물을 성소 안에서 먹었어야만 했다.\"", Chn:"", Eng:"Since its blood was not taken into the Holy Place, you should have eaten the goat in the sanctuary area, as I commanded.\"", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:19, Page:1, Kor:"이 말을 듣고, 아론이 모세에게 대답하였다. \"보십시오, 오늘 내 아들들이 속죄를 받으려고 주님 앞에 속죄제물과 번제물을 바쳤습니다. 그런데 이런 참혹한 일이 오늘 나에게 닥쳤습니다. 그러니 내가 무슨 염치로, 오늘 그들이 바친 속죄제물을 먹는단 말이오? 내가, 그들이 제물로 바친 고기를 먹으면, 주님께서 정말 좋게 보아 주시리라고 생각합니까?\"", Chn:"", Eng:"Aaron replied to Moses, \"Today they sacrificed their sin offering and their burnt offering before the LORD, but such things as this have happened to me. Would the LORD have been pleased if I had eaten the sin offering today?\"", Ind:""},
  {Bible:"Leviticus", Chapter:10, Verse:20, Page:1, Kor:"이 말을 듣고 보니, 모세도 그렇겠다는 생각이 들었다.", Chn:"", Eng:"When Moses heard this, he was satisfied.", Ind:""},
]);
