// 레위기 2장 · Leviticus 2
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Leviticus",2,16);
BibleDB.add([
  {Bible:"Leviticus", Chapter:2, Verse:1, Page:1, Kor:"<곡식제물> \"나 주에게 곡식제물을 바치는 사람은 누구든지 고운 밀가루를 제물로 바치는데, 거기에 기름을 붓고 향을 얹어서 바쳐야 한다.", Chn:"", Eng:"\"'When someone brings a grain offering to the LORD, his offering is to be of fine flour. He is to pour oil on it, put incense on it", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:2, Page:1, Kor:"그가 그 제물을 아론의 혈통을 이어받은 제사장들에게 가져 오면, 제사장은 기름으로 반죽한 밀가루에서는 가루 한 줌을 걷고, 향은 다 거두어서, 그 제물을 모두 바치는 정성의 표시로, 제단 위에 올려놓고 불살라야 한다. 이것이, 제물을 불에 태워서 그 향기로 나 주를 기쁘게 하는, 살라 바치는 03 2:제사이다.", Chn:"", Eng:"and take it to Aaron's sons the priests. The priest shall take a handful of the fine flour and oil, together with all the incense, and burn this as a memorial portion on the altar, an offering made by fire, an aroma pleasing to the LORD.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:3, Page:1, Kor:"곡식제물 가운데서 살라 바치고 남은 것은 아론과 그 아들들의 몫이다. 이것은 나 주에게 살라 바치는 제물에서 온 것이므로, 가장 거룩한 것이다.", Chn:"", Eng:"The rest of the grain offering belongs to Aaron and his sons; it is a most holy part of the offerings made to the LORD by fire.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:4, Page:1, Kor:"○네가 화덕에 구운 것으로 곡식제물을 바치려거든, 고운 밀가루에 기름을 넣어서 반죽하여, 누룩을 넣지 않고 만든 둥근 과자나, 누룩을 넣지 않고 기름만 발라서 만든 얇고 넓적한 과자를 바쳐야 한다.", Chn:"", Eng:"\"'If you bring a grain offering baked in an oven, it is to consist of fine flour: cakes made without yeast and mixed with oil, or wafers made without yeast and spread with oil.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:5, Page:1, Kor:"○네가 바치는 곡식제물이 빵 굽는 판에다 구운 것이면, 그것은 고운 밀가루에 기름을 넣어 반죽하여 만든 것으로서, 누룩을 넣지 않은 것이어야 한다.", Chn:"", Eng:"If your grain offering is prepared on a griddle, it is to be made of fine flour mixed with oil, and without yeast.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:6, Page:1, Kor:"너는 그것을 여러 조각으로 나누고, 그 위에 기름을 부어라. 이것이 곡식제물이다.", Chn:"", Eng:"Crumble it and pour oil on it; it is a grain offering.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:7, Page:1, Kor:"○네가 바치는 곡식제물이 냄비에다 구운 과자이면, 고운 밀가루에 기름을 넣어서 만든 것이어야 한다.", Chn:"", Eng:"If your grain offering is cooked in a pan, it is to be made of fine flour and oil.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:8, Page:1, Kor:"○이렇게 하여 곡식제물이 준비되면, 그것을 나 주에게 가지고 와서, 제사장에게 주어라. 제사장이 그것을 받아 제단으로 가져 갈 것이다.", Chn:"", Eng:"Bring the grain offering made of these things to the LORD; present it to the priest, who shall take it to the altar.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:9, Page:1, Kor:"제사장은 그 곡식제물에서 정성의 표시로 조금 떼어서, 그것을 제단 위에 올려놓고 불살라야 한다. 이렇게 하여 그 제물을 모두 바쳤다는 표시로 삼는다. 이것이, 제물을 불에 태워서 그 향기로 나 주를 기쁘게 하는, 살라 바치는 제사이다.", Chn:"", Eng:"He shall take out the memorial portion from the grain offering and burn it on the altar as an offering made by fire, an aroma pleasing to the LORD.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:10, Page:1, Kor:"곡식제물 가운데서 살라 바치고 남은 것은 아론과 그 아들들의 몫이다. 이것은 나 주에게 살라 바치는 제물에서 온 것이므로, 가장 거룩한 것이다.", Chn:"", Eng:"The rest of the grain offering belongs to Aaron and his sons; it is a most holy part of the offerings made to the LORD by fire.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:11, Page:1, Kor:"○너희가 나 주에게 바치는 곡식제물은, 어떤 것이든지, 누룩을 넣지 않은 것이어야 한다. 나 주에게 살라 바치는 제사에서, 어떤 누룩이나 꿀을 불살라서는 안 되기 때문이다.", Chn:"", Eng:"\"'Every grain offering you bring to the LORD must be made without yeast, for you are not to burn any yeast or honey in an offering made to the LORD by fire.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:12, Page:1, Kor:"너희가 맨 먼저 거둔 곡식을 제물로 바칠 때에는 나 주에게 누룩과 꿀을 가져 와도 되지만, 나 주를 기쁘게 하는 향기를 내려고 그것들을 제단 위에 올려놓아서는 안 된다.", Chn:"", Eng:"You may bring them to the LORD as an offering of the firstfruits, but they are not to be offered on the altar as a pleasing aroma.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:13, Page:1, Kor:"네가 바치는 모든 곡식제물에는 소금을 넣어야 한다. 네가 바치는 곡식제물에는 네 하나님과 언약을 세울 때에 넣는 그 소금을 빼놓지 말아라. 네가 바치는 모든 제물에는 소금을 넣도록 하여라.", Chn:"", Eng:"Season all your grain offerings with salt. Do not leave the salt of the covenant of your God out of your grain offerings; add salt to all your offerings.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:14, Page:1, Kor:"○네가 맨 먼저 거둔 것을 나 주에게 곡식제물로 바칠 때에는, 햇곡식을 불에 볶거나 찧은 것으로 곡식제물을 바쳐야 한다.", Chn:"", Eng:"\"'If you bring a grain offering of firstfruits to the LORD, offer crushed heads of new grain roasted in the fire.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:15, Page:1, Kor:"그 위에 기름과 향을 놓아라. 이것이 곡식제물이다.", Chn:"", Eng:"Put oil and incense on it; it is a grain offering.", Ind:""},
  {Bible:"Leviticus", Chapter:2, Verse:16, Page:1, Kor:"제사장은 제물을 모두 바치는 정성의 표시로, 곡식과 기름에서 조금 갈라 내어, 향 전부와 함께 불살라야 한다. 이것이 나 주에게 살라 바치는 제사이다.\"", Chn:"", Eng:"The priest shall burn the memorial portion of the crushed grain and the oil, together with all the incense, as an offering made to the LORD by fire.", Ind:""},
]);
