// 미가 2장 · Micah 2
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Micah",2,13);
BibleDB.add([
  {Bible:"Micah", Chapter:2, Verse:1, Page:1, Kor:"<가난한 이를 억누르는 사람이 받을 형벌> 악한 궁리나 하는 자들, 잠자리에 누워서도 음모를 꾸미는 자들은 망한다! 그들은 권력을 쥐었다고 해서, 날이 새자마자 음모대로 해치우고 마는 자들이다.", Chn:"", Eng:"Woe to those who plan iniquity, to those who plot evil on their beds! At morning's light they carry it out because it is in their power to do it.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:2, Page:1, Kor:"탐나는 밭을 빼앗고, 탐나는 집을 제 것으로 만든다. 집 임자를 속여서 집을 빼앗고, 주인에게 딸린 사람들과 유산으로 받은 밭을 제 것으로 만든다.", Chn:"", Eng:"They covet fields and seize them, and houses, and take them. They defraud a man of his home, a fellowman of his inheritance.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:3, Page:1, Kor:"\"그러므로 나 주가 말한다. 내가 이 백성에게 재앙을 내리기로 계획하였으니, 이 재앙을 a너희가 피할 수 없을 것이다. 너희가 거만하게 걸을 수도 없을 것이다. 그처럼 견디기 어려운 재앙의 때가 될 것이다. (a 히, '너희 목이')", Chn:"", Eng:"Therefore, the LORD says: \"I am planning disaster against this people, from which you cannot save yourselves. You will no longer walk proudly, for it will be a time of calamity.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:4, Page:1, Kor:"그 날이 오면, 사람들이 너희를 두고서 이러한 풍자시를 지어서 읊을 것이다. 슬픔에 사무친 애가를 지어서 부를 것이다. '우리는 알거지가 되었다. 주님께서 내 백성의 유산의 몫을 나누시고, 나에게서 빼앗은 땅을 반역자들의 몫으로 할당해 주셨다.'", Chn:"", Eng:"In that day men will ridicule you; they will taunt you with this mournful song: 'We are utterly ruined; my people's possession is divided up. He takes it from me! He assigns our fields to traitors.'\"", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:5, Page:1, Kor:"그러므로 주님의 총회에서 줄을 띄워 땅을 나누고 제비 뽑아 분배할 때에 너희의 몫은 없을 것이다.", Chn:"", Eng:"Therefore you will have no one in the assembly of the LORD to divide the land by lot.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:6, Page:1, Kor:"그들의 예언자들이 말한다. '너희는 우리에게 예언하지 말아라. 이 모든 재앙을 두고 예언하지 말아라. 하나님이 우리를 망신시키실 리가 없다.'", Chn:"", Eng:"\"Do not prophesy,\" their prophets say. \"Do not prophesy about these things; disgrace will not overtake us.\"", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:7, Page:1, Kor:"야곱 족속아, 너희가 어찌하여 '주님의 영도 분노하시느냐? 주님께서 정말 그런 일을 하시느냐?' 하고 말하느냐? 나의 말이 행위가 정직한 사람에게 유익하지 않으냐?", Chn:"", Eng:"Should it be said, O house of Jacob: \"Is the Spirit of the LORD angry? Does he do such things?\" \"Do not my words do good to him whose ways are upright?", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:8, Page:1, Kor:"요즈음에 내 백성이 대적처럼 일어났다. 전쟁터에서 고향으로 돌아가는 장정들처럼 안심하고 지나가는 사람들에게서, 너희는 그들의 옷을 벗겨 갔다.", Chn:"", Eng:"Lately my people have risen up like an enemy. You strip off the rich robe from those who pass by without a care, like men returning from battle.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:9, Page:1, Kor:"너희는 내 백성의 아내들을 그 정든 집에서 쫓아냈고, 그들의 자녀들에게서 내가 준 복을 너희가 영영 빼앗아 버렸다.", Chn:"", Eng:"You drive the women of my people from their pleasant homes. You take away my blessing from their children forever.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:10, Page:1, Kor:"썩 물러가거라. 여기는 너희의 안식처가 아니다. 이 곳은 더러워졌고, 끔찍한 멸망을 당할 수밖에 없다.", Chn:"", Eng:"Get up, go away! For this is not your resting place, because it is defiled, it is ruined, beyond all remedy.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:11, Page:1, Kor:"거짓말쟁이나 사기꾼이 와서 '너희에게 포도주와 독한 술이 철철 넘칠 것이다' 하고 예언하면, 그 사람이야말로 이 백성의 예언자가 될 것이다!", Chn:"", Eng:"If a liar and deceiver comes and says, 'I will prophesy for you plenty of wine and beer,' he would be just the prophet for this people!", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:12, Page:1, Kor:"야곱아, 내가 반드시 너희를 다 모으겠다. 남아 있는 이스라엘 백성을 다 모으겠다. 내가 너희를 b우리로 돌아오는 양 떼처럼 모으겠다. 양 떼로 가득 찬 초장과도 같이, 너희의 땅이 다시 백성으로 가득 찰 것이다. (b 히, '보스라')", Chn:"", Eng:"\"I will surely gather all of you, O Jacob; I will surely bring together the remnant of Israel. I will bring them together like sheep in a pen, like a flock in its pasture; the place will throng with people.", Ind:""},
  {Bible:"Micah", Chapter:2, Verse:13, Page:1, Kor:"길을 여는 자가 그들 앞서 올라가고 그들은 성문들을 부수고, 바깥으로 나갈 것이다. 그들의 왕이 앞장 서서 걸어가며 나 주가 선두에 서서 그들을 인도할 것이다.\"", Chn:"", Eng:"One who breaks open the way will go up before them; they will break through the gate and go out. Their king will pass through before them, the LORD at their head.\"", Ind:""},
]);
