// 미가 4장 · Micah 4
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Micah",4,13);
BibleDB.add([
  {Bible:"Micah", Chapter:4, Verse:1, Page:1, Kor:"<주님의 통치로 이룰 우주적 평화> 그 날이 오면, 주님의 성전이 서 있는 주님의 산이 산들 가운데서 가장 높이 솟아서, 모든 언덕을 아래로 내려다 보며, 우뚝 설 것이다. 민족들이 구름처럼 그리로 몰려올 것이다.", Chn:"", Eng:"In the last days the mountain of the LORD'S temple will be established as chief among the mountains; it will be raised above the hills, and peoples will stream to it.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:2, Page:1, Kor:"민족마다 오면서 이르기를 \"자, 가자. 우리 모두 주님의 산으로 올라가자. 야곱의 하나님이 계신 성전으로 어서 올라가자. 주님께서 우리에게 주님의 길을 가르치실 것이니, 주님께서 가르치시는 길을 따르자\" 할 것이다. 율법이 시온에서 나오며, 주님의 말씀이 예루살렘에서 나온다.", Chn:"", Eng:"Many nations will come and say, \"Come, let us go up to the mountain of the LORD, to the house of the God of Jacob. He will teach us his ways, so that we may walk in his paths.\" The law will go out from Zion, the word of the LORD from Jerusalem.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:3, Page:1, Kor:"주님께서 민족들 사이의 분쟁을 판결하시고, 원근 각처에 있는 열강 사이의 갈등을 해결하실 것이니, 나라마다 칼을 쳐서 보습을 만들고 창을 쳐서 낫을 만들 것이며, 나라와 나라가 칼을 들고 서로를 치지 않을 것이며, 다시는 군사 훈련도 하지 않을 것이다.", Chn:"", Eng:"He will judge between many peoples and will settle disputes for strong nations far and wide. They will beat their swords into plowshares and their spears into pruning hooks. Nation will not take up sword against nation, nor will they train for war anymore.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:4, Page:1, Kor:"사람마다 자기 포도나무와 무화과나무 아래 앉아서, 평화롭게 살 것이다. 사람마다 아무런 위협을 받지 않으면서 살 것이다. 이것은 만군의 주님께서 약속하신 것이다.", Chn:"", Eng:"Every man will sit under his own vine and under his own fig tree, and no one will make them afraid, for the LORD Almighty has spoken.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:5, Page:1, Kor:"다른 모든 민족은 각기 자기 신들을 섬기고 순종할 것이다. 그러나 우리는 언제까지나, 주 우리의 하나님만을 섬기고, 그분에게만 순종할 것이다.", Chn:"", Eng:"All the nations may walk in the name of their gods; we will walk in the name of the LORD our God for ever and ever.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:6, Page:1, Kor:"<이스라엘이 포로에서 돌아올 것이다> \"나 주가 선언한다. 그 날이 오면, 비틀거리며 사는 백성을 내가 다시 불러오고, 사로잡혀 가서 고생하던 나의 백성을 다시 불러모으겠다.", Chn:"", Eng:"\"In that day,\" declares the LORD, \"I will gather the lame; I will assemble the exiles and those I have brought to grief.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:7, Page:1, Kor:"그들이 이역만리 타향에서 비틀거리며 살고 있으나, 거기에서 살아 남은 백성이 강한 민족이 될 것이다. 그 때로부터 영원토록, 나 주가 그들을 시온 산에서 다스리겠다.", Chn:"", Eng:"I will make the lame a remnant, those driven away a strong nation. The LORD will rule over them in Mount Zion from that day and forever.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:8, Page:1, Kor:"너 양 떼의 망대야, 도성 시온의 산아, 너의 이전 통치가 회복되고 도성 예루살렘의 왕권이 네게로 돌아올 것이다.\"", Chn:"", Eng:"As for you, O watchtower of the flock, O stronghold of the Daughter of Zion, the former dominion will be restored to you; kingship will come to the Daughter of Jerusalem.\"", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:9, Page:1, Kor:"어찌하여 너는 그렇게 큰소리로 우느냐? 왕이 없기 때문이냐? 어찌하여 너는 아이를 낳는 여인처럼 진통하느냐? 자문관들이 죽었기 때문이냐?", Chn:"", Eng:"Why do you now cry aloud--have you no king? Has your counselor perished, that pain seizes you like that of a woman in labor?", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:10, Page:1, Kor:"도성 시온아, 이제 네가 이 도성을 떠나서, 빈 들로 가서 살아야 할 것이니, 아이를 낳는 여인처럼, 몸부림치면서 신음하여라. 너는 바빌론으로 가야 할 것이다. 거기에서 주님께서 너를 건지시고, 너의 원수에게서 너를 속량하실 것이다.", Chn:"", Eng:"Writhe in agony, O Daughter of Zion, like a woman in labor, for now you must leave the city to camp in the open field. You will go to Babylon; there you will be rescued. There the LORD will redeem you out of the hand of your enemies.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:11, Page:1, Kor:"그러나 이제 많은 민족이 연합하여 너를 칠 것이다. 그들은 이르기를 \"시온은 망해야 한다. 이제 곧 우리는 이 도성이 폐허가 되는 것을 보게 될 것이다\" 한다.", Chn:"", Eng:"But now many nations are gathered against you. They say, \"Let her be defiled, let our eyes gloat over Zion!\"", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:12, Page:1, Kor:"그러나 그들은, 나 주가 마음 속으로 무엇을 생각하고 있는지를 알지 못한다. 한꺼번에 같은 방법으로 벌을 주려고, 곡식을 타작 마당으로 모아서 쌓듯이, 그들을 한데 모았다는 것을 미처 깨닫지 못한다.", Chn:"", Eng:"But they do not know the thoughts of the LORD; they do not understand his plan, he who gathers them like sheaves to the threshing floor.", Ind:""},
  {Bible:"Micah", Chapter:4, Verse:13, Page:1, Kor:"도성 시온아, 네 원수에게 가서, 그들을 쳐라! 내가 네 뿔을 쇠 같게 하고, 네 굽을 놋쇠 같게 할 것이니, 너는 많은 민족을 짓밟고, 그들이 폭력을 써서 착취한 그 재물을 빼앗아다가, 온 세상의 주 곧 나에게 가져 올 것이다.", Chn:"", Eng:"\"Rise and thresh, O Daughter of Zion, for I will give you horns of iron; I will give you hoofs of bronze and you will break to pieces many nations.\" You will devote their ill-gotten gains to the LORD, their wealth to the Lord of all the earth.", Ind:""},
]);
