// 미가 5장 · Micah 5
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Micah",5,15);
BibleDB.add([
  {Bible:"Micah", Chapter:5, Verse:1, Page:1, Kor:"a군대의 도성아, 군대를 모아라! 우리가 포위되었다! 침략군들이 몽둥이로 이스라엘의 통치자의 뺨을 칠 것이다. (a 또는 '성벽으로 둘러싸인 성읍아, 네 성벽을 튼튼하게 하여라')", Chn:"", Eng:"Marshal your troops, O city of troops, for a siege is laid against us. They will strike Israel's ruler on the cheek with a rod.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:2, Page:1, Kor:"<베들레헴에서 통치자가 나올 것이다> \"그러나 너 베들레헴 에브라다야, 너는 유다의 여러 b족속 가운데서 작은 족속이지만, 이스라엘을 다스릴 자가 네게서 내게로 나올 것이다. 그의 기원은 아득한 옛날, 태초에까지 거슬러 올라간다.\" (b 히, '천 천' 또는 '통치자들')", Chn:"", Eng:"\"But you, Bethlehem Ephrathah, though you are small among the clans of Judah, out of you will come for me one who will be ruler over Israel, whose origins are from of old, from ancient times.\"", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:3, Page:1, Kor:"그러므로 주님께서는 해산하는 여인이 아이를 낳을 때까지, 당신의 백성을 원수들에게 그대로 맡겨 두실 것이다. 그 뒤에 그의 동포, 사로잡혀 가 있던 남은 백성이, 이스라엘 자손에게로 돌아올 것이다.", Chn:"", Eng:"Therefore Israel will be abandoned until the time when she who is in labor gives birth and the rest of his brothers return to join the Israelites.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:4, Page:1, Kor:"그가 주님께서 주신 능력을 가지고, 그의 하나님이신 주님의 이름이 지닌 그 위엄을 의지하고 서서 그의 떼를 먹일 것이다. 그러면 그의 위대함이 땅 끝까지 이를 것이므로, 그들은 안전하게 살아갈 수 있을 것이다.", Chn:"", Eng:"He will stand and shepherd his flock in the strength of the LORD, in the majesty of the name of the LORD his God. And they will live securely, for then his greatness will reach to the ends of the earth.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:5, Page:1, Kor:"그리고 그는 그들에게 '평화'를 가져다 줄 것이다.  <구원과 심판>  앗시리아 사람이 우리 땅을 침략하여, 우리의 방어망을 뚫고 들어올 때에, 우리는 일곱 목자, 여덟 장군들을 보내서, 침략자들과 싸우게 할 것이다.", Chn:"", Eng:"And he will be their peace. When the Assyrian invades our land and marches through our fortresses, we will raise against him seven shepherds, even eight leaders of men.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:6, Page:1, Kor:"그들은 칼로 앗시리아 땅을 정복하고, 뺀 칼로 c니므롯 땅을 황무지로 만들 것이다. 앗시리아의 군대가 우리의 땅을 침략하여, 우리의 국경선 너머로 들어올 때에 그가 우리를 앗시리아 군대의 손에서 구원하여 낼 것이다. (c 또는 '니므롯을 그 성문 어귀에서')", Chn:"", Eng:"They will rule the land of Assyria with the sword, the land of Nimrod with drawn sword. He will deliver us from the Assyrian when he invades our land and marches into our borders.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:7, Page:1, Kor:"많은 민족들 사이에 살아 남은 야곱 백성은, 주님께서 내려 주시는 아침 이슬과 같이 될 것이며, 푸성귀 위에 내리는 비와도 같게 되어서, 사람을 의지하거나 인생을 기다리지 않을 것이다.", Chn:"", Eng:"The remnant of Jacob will be in the midst of many peoples like dew from the LORD, like showers on the grass, which do not wait for man or linger for mankind.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:8, Page:1, Kor:"살아 남은 야곱 백성은 여러 민족과 백성 사이에 흩어져서 살 것이며, 숲 속 짐승들 가운데 서 있는 사자처럼, 양 떼의 한가운데 서 있는 사자처럼, 걸을 때마다, 먹이에게 달려들어 밟고 찢을 것이니, 그에게서는 아무도 그 짐승을 건져 낼 수 없을 것이다.", Chn:"", Eng:"The remnant of Jacob will be among the nations, in the midst of many peoples, like a lion among the beasts of the forest, like a young lion among flocks of sheep, which mauls and mangles as it goes, and no one can rescue.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:9, Page:1, Kor:"네가 네 대적 위에 손을 들고 네 원수를 모두 파멸시키기를 바란다.", Chn:"", Eng:"Your hand will be lifted up in triumph over your enemies, and all your foes will be destroyed.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:10, Page:1, Kor:"\"나 주가 선언한다. 그 날이 오면, 너희가 가진 군마를 없애 버리고 말이 끄는 병거를 부수어 버리겠다.", Chn:"", Eng:"\"In that day,\" declares the LORD, \"I will destroy your horses from among you and demolish your chariots.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:11, Page:1, Kor:"너희 땅에 세운 성곽들을 부수어 버리고, 요새들은 모두 파괴하여 버리겠다.", Chn:"", Eng:"I will destroy the cities of your land and tear down all your strongholds.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:12, Page:1, Kor:"너희가 쓰던 마법을 없앨 것이니, 너희가 다시는 점을 치지 않을 것이다.", Chn:"", Eng:"I will destroy your witchcraft and you will no longer cast spells.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:13, Page:1, Kor:"너희가 새긴 우상을 파괴하여 버리고, 신성하게 여긴 돌 기둥들도 부수어 버려서, 다시는 너희가 만든 그런 것들을 너희가 섬기지 못하게 하겠다.", Chn:"", Eng:"I will destroy your carved images and your sacred stones from among you; you will no longer bow down to the work of your hands.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:14, Page:1, Kor:"너희 가운데서 아세라 여신상을 모두 뽑아 버리고, 너희가 사는 성읍들을 파괴하겠다.", Chn:"", Eng:"I will uproot from among you your Asherah poles and demolish your cities.", Ind:""},
  {Bible:"Micah", Chapter:5, Verse:15, Page:1, Kor:"나에게 복종하지 않은 모든 민족에게, 화가 나는 대로, 분노를 참지 않고 보복하겠다.\"", Chn:"", Eng:"I will take vengeance in anger and wrath upon the nations that have not obeyed me.\"", Ind:""},
]);
