// 골로새서 3장 · Colossians 3
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Colossians",3,25);
BibleDB.add([
  {Bible:"Colossians", Chapter:3, Verse:1, Page:1,
    Kor:"그러므로 여러분이 그리스도와 함께 살려 주심을 받았으면, 위에 있는 것들을 추구하십시오. 거기에는, 그리스도께서 하나님의 오른쪽에 앉아 계십니다.",
    Chn:"所以，你们若真与基督一同复活，就当求在上面的事；那里有基督坐在　神的右边。",
    Eng:"Since, then, you have been raised with Christ, set your hearts on things above, where Christ is seated at the right hand of God.",
    Ind:"Karena itu, kalau kamu dibangkitkan bersama dengan Kristus, carilah perkara yang di atas, di mana Kristus ada, duduk di sebelah kanan Allah."
  },
  {Bible:"Colossians", Chapter:3, Verse:2, Page:1,
    Kor:"여러분은 땅에 있는 것들을 생각하지 말고, 위에 있는 것들을 생각하십시오.",
    Chn:"你们要思念上面的事，不要思念地上的事。",
    Eng:"Set your minds on things above, not on earthly things.",
    Ind:"Pikirkanlah perkara yang di atas, bukan yang di bumi."
  },
  {Bible:"Colossians", Chapter:3, Verse:3, Page:1,
    Kor:"여러분은 이미 죽었고, 여러분의 생명은 그리스도와 함께 하나님 안에 감추어져 있습니다.",
    Chn:"因为你们已经死了，你们的生命与基督一同藏在　神里面。",
    Eng:"For you died, and your life is now hidden with Christ in God.",
    Ind:"Sebab kamu telah mati dan hidupmu tersembunyi bersama dengan Kristus di dalam Allah."
  },
  {Bible:"Colossians", Chapter:3, Verse:4, Page:1,
    Kor:"a여러분의 생명이신 그리스도께서 나타나실 때에, 여러분도 그분과 함께 영광에 싸여 나타날 것입니다.(a 다른 고대 사본들에는 '우리의')",
    Chn:"基督是我们的生命，他显现的时候，你们也要与他一同显现在荣耀里。",
    Eng:"When Christ, who is your life, appears, then you also will appear with him in glory.",
    Ind:"Apabila Kristus, yang adalah hidup kita, menyatakan diri kelak, kamupun akan menyatakan diri bersama dengan Dia dalam kemuliaan."
  },
  {Bible:"Colossians", Chapter:3, Verse:5, Page:1,
    Kor:"○그러므로 땅에 속한 지체의 일들, 곧 음행과 더러움과 정욕과 악한 욕망과 탐욕을 죽이십시오. 탐욕은 우상숭배입니다.",
    Chn:"所以，要治死你们在地上的肢体，就如淫乱、污秽、邪情、恶欲，和贪婪（贪婪就与拜偶像一样）。",
    Eng:"Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry.",
    Ind:"Karena itu matikanlah dalam dirimu segala sesuatu yang duniawi, yaitu percabulan, kenajisan, hawa nafsu, nafsu jahat dan juga keserakahan, yang sama dengan penyembahan berhala,"
  },
  {Bible:"Colossians", Chapter:3, Verse:6, Page:1,
    Kor:"이런 것들 때문에, <순종하지 않는 자들에게> 하나님의 진노가 내립니다.",
    Chn:"因这些事，　神的忿怒必临到那悖逆之子。",
    Eng:"Because of these, the wrath of God is coming.",
    Ind:"semuanya itu mendatangkan murka Allah (atas orang-orang durhaka)."
  },
  {Bible:"Colossians", Chapter:3, Verse:7, Page:1,
    Kor:"여러분도 전에 b그런 것에 빠져서 살 때에는, 그렇게 행동하였습니다.(b 또는 '그런 삶을 살 때에는' 또는 '그런 사람들 가운데서 살 때에는')",
    Chn:"当你们在这些事中活着的时候，也曾这样行过。",
    Eng:"You used to walk in these ways, in the life you once lived.",
    Ind:"Dahulu kamu juga melakukan hal-hal itu ketika kamu hidup di dalamnya."
  },
  {Bible:"Colossians", Chapter:3, Verse:8, Page:1,
    Kor:"그러나 이제 여러분은 그 모든 것, 곧 분노와 격분과 악의와 훼방과 여러분의 입에서 나오는 부끄러운 말을 버리십시오.",
    Chn:"但现在你们要弃绝这一切的事，以及恼恨、忿怒、恶毒、毁谤，并口中污秽的言语。",
    Eng:"But now you must rid yourselves of all such things as these: anger, rage, malice, slander, and filthy language from your lips.",
    Ind:"Tetapi sekarang, buanglah semuanya ini, yaitu marah, geram, kejahatan, fitnah dan kata-kata kotor yang keluar dari mulutmu."
  },
  {Bible:"Colossians", Chapter:3, Verse:9, Page:1,
    Kor:"서로 거짓말을 하지 마십시오. 여러분은 옛 사람을 그 행실과 함께 벗어버리고,",
    Chn:"不要彼此说谎；因你们已经脱去旧人和旧人的行为，",
    Eng:"Do not lie to each other, since you have taken off your old self with its practices",
    Ind:"Jangan lagi kamu saling mendustai, karena kamu telah menanggalkan manusia lama serta kelakuannya,"
  },
  {Bible:"Colossians", Chapter:3, Verse:10, Page:1,
    Kor:"새 사람을 입으십시오. 이 새 사람은 자기를 창조하신 분의 형상을 따라 끊임없이 새로워져서, 참 지식에 이르게 됩니다.",
    Chn:"穿上了新人。这新人在知识上渐渐更新，正如造他主的形象。",
    Eng:"and have put on the new self, which is being renewed in knowledge in the image of its Creator.",
    Ind:"dan telah mengenakan manusia baru yang terus-menerus diperbaharui untuk memperoleh pengetahuan yang benar menurut gambar Khaliknya;"
  },
  {Bible:"Colossians", Chapter:3, Verse:11, Page:1,
    Kor:"거기에는 그리스인과 유대인도, 할례 받은 자와 할례받지 않은 자도, 야만인도 스구디아인도, 종도 자유인도 없습니다. 오직 그리스도만이 모든 것이며, 모든 것 안에 계십니다.",
    Chn:"在此并不分希腊人、犹太人，受割礼的、未受割礼的，化外人、西古提人，为奴的、自主的，惟有基督是包括一切，又住在各人之内。",
    Eng:"Here there is no Greek or Jew, circumcised or uncircumcised, barbarian, Scythian, slave or free, but Christ is all, and is in all.",
    Ind:"dalam hal ini tiada lagi orang Yunani atau orang Yahudi, orang bersunat atau orang tak bersunat, orang Barbar atau orang Skit, budak atau orang merdeka, tetapi Kristus adalah semua dan di dalam segala sesuatu."
  },
  {Bible:"Colossians", Chapter:3, Verse:12, Page:1,
    Kor:"○그러므로 여러분은 하나님의 택하심을 입은 사랑 받는 거룩한 사람답게, 동정심과 친절함과 겸손함과 온유함과 오래 참음을 옷 입듯이 입으십시오.",
    Chn:"所以，你们既是　神的选民，圣洁蒙爱的人，就要存怜悯、恩慈、谦虚、温柔、忍耐的心。",
    Eng:"Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.",
    Ind:"Karena itu, sebagai orang-orang pilihan Allah yang dikuduskan dan dikasihi-Nya, kenakanlah belas kasihan, kemurahan, kerendahan hati, kelemahlembutan dan kesabaran."
  },
  {Bible:"Colossians", Chapter:3, Verse:13, Page:1,
    Kor:"누가 누구에게 불평할 일이 있더라도, 서로 용납하여 주고, 서로 용서하여 주십시오. c주님께서 여러분을 용서하신 것과 같이, 여러분도 서로 용서하십시오.(c 다른 고대 사본들에는 '그리스도께서')",
    Chn:"倘若这人与那人有嫌隙，总要彼此包容，彼此饶恕；主怎样饶恕了你们，你们也要怎样饶恕人。",
    Eng:"Bear with each other and forgive whatever grievances you may have against one another. Forgive as the Lord forgave you.",
    Ind:"Sabarlah kamu seorang terhadap yang lain, dan ampunilah seorang akan yang lain apabila yang seorang menaruh dendam terhadap yang lain, sama seperti Tuhan telah mengampuni kamu, kamu perbuat jugalah demikian."
  },
  {Bible:"Colossians", Chapter:3, Verse:14, Page:1,
    Kor:"이 모든 것 위에 사랑을 더하십시오. 사랑은 완전하게 묶는 띠입니다.",
    Chn:"在这一切之外，要存着爱心，爱心就是联络全德的。",
    Eng:"And over all these virtues put on love, which binds them all together in perfect unity.",
    Ind:"Dan di atas semuanya itu: kenakanlah kasih, sebagai pengikat yang mempersatukan dan menyempurnakan."
  },
  {Bible:"Colossians", Chapter:3, Verse:15, Page:1,
    Kor:"그리스도의 평화가 여러분의 마음을 지배하게 하십시오. 이 평화를 누리도록 여러분은 부르심을 받아 한 몸이 되었습니다. 또 여러분은 감사하는 사람이 되십시오.",
    Chn:"又要叫基督的平安在你们心里作主；你们也为此蒙召，归为一体；且要存感谢的心。",
    Eng:"Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful.",
    Ind:"Hendaklah damai sejahtera Kristus memerintah dalam hatimu, karena untuk itulah kamu telah dipanggil menjadi satu tubuh. Dan bersyukurlah."
  },
  {Bible:"Colossians", Chapter:3, Verse:16, Page:1,
    Kor:"d그리스도의 말씀이 여러분 가운데 풍성히 살아 있게 하십시오. 온갖 지혜로 서로 가르치고 권고하십시오. 감사한 마음으로 시와 찬미와 신령한 노래로 여러분의 e하나님께 마음을 다하여 찬양하십시오.(d 다른 고대 사본들에는 '하나님의' 또는 '주님의' e 다른 고대 사본들에는 '주님께')",
    Chn:"当用各样的智慧，把基督的道理丰丰富富地存在心里，用诗章、颂词、灵歌，彼此教导，互相劝戒，心被恩感，歌颂　神。",
    Eng:"Let the word of Christ dwell in you richly as you teach and admonish one another with all wisdom, and as you sing psalms, hymns and spiritual songs with gratitude in your hearts to God.",
    Ind:"Hendaklah perkataan Kristus diam dengan segala kekayaannya di antara kamu, sehingga kamu dengan segala hikmat mengajar dan menegur seorang akan yang lain dan sambil menyanyikan mazmur, dan puji-pujian dan nyanyian rohani, kamu mengucap syukur kepada Allah di dalam hatimu."
  },
  {Bible:"Colossians", Chapter:3, Verse:17, Page:1,
    Kor:"그리고 말이든 행동이든 무엇을 하든지, 모든 것을 주 예수의 이름으로 하고, 그분에게서 힘을 얻어서, 하나님 아버지께 감사를 드리십시오.",
    Chn:"无论做什么，或说话或行事，都要奉主耶稣的名，借着他感谢父　神。",
    Eng:"And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.",
    Ind:"Dan segala sesuatu yang kamu lakukan dengan perkataan atau perbuatan, lakukanlah semuanya itu dalam nama Tuhan Yesus, sambil mengucap syukur oleh Dia kepada Allah, Bapa kita."
  },
  {Bible:"Colossians", Chapter:3, Verse:18, Page:1,
    Kor:"<가정 생활 지침> ○아내 된 이 여러분, 남편에게 순종하십시오. 이것이 주님 안에서 합당한 일입니다.",
    Chn:"你们作妻子的，当顺服自己的丈夫，这在主里面是相宜的。",
    Eng:"Wives, submit to your husbands, as is fitting in the Lord.",
    Ind:"Hai isteri-isteri, tunduklah kepada suamimu, sebagaimana seharusnya di dalam Tuhan."
  },
  {Bible:"Colossians", Chapter:3, Verse:19, Page:1,
    Kor:"남편 된 이 여러분, 아내를 사랑하십시오. 아내를 모질게 대하지 마십시오.",
    Chn:"你们作丈夫的，要爱你们的妻子，不可苦待她们。",
    Eng:"Husbands, love your wives and do not be harsh with them.",
    Ind:"Hai suami-suami, kasihilah isterimu dan janganlah berlaku kasar terhadap dia."
  },
  {Bible:"Colossians", Chapter:3, Verse:20, Page:1,
    Kor:"○자녀 된 이 여러분, 모든 일에 부모에게 복종하십시오. 이것이 주님을 기쁘게 해 드리는 일입니다.",
    Chn:"你们作儿女的，要凡事听从父母，因为这是主所喜悦的。",
    Eng:"Children, obey your parents in everything, for this pleases the Lord.",
    Ind:"Hai anak-anak, taatilah orang tuamu dalam segala hal, karena itulah yang indah di dalam Tuhan."
  },
  {Bible:"Colossians", Chapter:3, Verse:21, Page:1,
    Kor:"어버이 된 이 여러분, 여러분의 자녀들을 격분하게 하지 마십시오. 그들의 의기를 꺾지 않아야 합니다.",
    Chn:"你们作父亲的，不要惹儿女的气，恐怕他们失了志气。",
    Eng:"Fathers, do not embitter your children, or they will become discouraged.",
    Ind:"Hai bapa-bapa, janganlah sakiti hati anakmu, supaya jangan tawar hatinya."
  },
  {Bible:"Colossians", Chapter:3, Verse:22, Page:1,
    Kor:"○종으로 있는 이 여러분, 모든 일에 육신의 f주인에게 복종하십시오. 사람을 기쁘게 하는 자들처럼 눈가림으로 하지 말고, f주님을 두려워하면서, 성실한 마음으로 하십시오.(f 그리스어 '퀴리오스'는 '주인'에게도 쓰이고 '주님'에게도 쓰임)",
    Chn:"你们作仆人的，要凡事听从你们肉身的主人，不要只在眼前事奉，像是讨人喜欢的，总要存心诚实敬畏主。",
    Eng:"Slaves, obey your earthly masters in everything; and do it, not only when their eye is on you and to win their favor, but with sincerity of heart and reverence for the Lord.",
    Ind:"Hai hamba-hamba, taatilah tuanmu yang di dunia ini dalam segala hal, jangan hanya di hadapan mereka saja untuk menyenangkan mereka, melainkan dengan tulus hati karena takut akan Tuhan."
  },
  {Bible:"Colossians", Chapter:3, Verse:23, Page:1,
    Kor:"무슨 일을 하든지 사람에게 하듯이 하지 말고, 주님께 하듯이 진심으로 하십시오.",
    Chn:"无论做什么，都要从心里做，像是给主做的，不是给人做的，",
    Eng:"Whatever you do, work at it with all your heart, as working for the Lord, not for men,",
    Ind:"Apapun juga yang kamu perbuat, perbuatlah dengan segenap hatimu seperti untuk Tuhan dan bukan untuk manusia."
  },
  {Bible:"Colossians", Chapter:3, Verse:24, Page:1,
    Kor:"여러분은 주님께 유산을 상으로 받는다는 사실을 기억하십시오. 여러분이 섬기는 분은 주 그리스도이십니다.",
    Chn:"因你们知道从主那里必得着基业为赏赐；你们所事奉的乃是主基督。",
    Eng:"since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving.",
    Ind:"Kamu tahu, bahwa dari Tuhanlah kamu akan menerima bagian yang ditentukan bagimu sebagai upah. Kristus adalah tuan dan kamu hamba-Nya."
  },
  {Bible:"Colossians", Chapter:3, Verse:25, Page:1,
    Kor:"불의를 행하는 사람은, 자기가 행한 불의의 대가를 받을 것입니다. 거기에는 사람을 보고 차별을 하는 일이 없습니다.",
    Chn:"那行不义的必受不义的报应；主并不偏待人。",
    Eng:"Anyone who does wrong will be repaid for his wrong, and there is no favoritism.",
    Ind:"Barangsiapa berbuat kesalahan, ia akan menanggung kesalahannya itu, karena Tuhan tidak memandang orang."
  },
]);
