// 히브리서 8장 · Hebrews 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Hebrews",8,13);
BibleDB.add([
  {Bible:"Hebrews", Chapter:8, Verse:1, Page:1, Kor:"<새 언약의 대제사장> 지금 말한 것들의 요점은 이러합니다. 곧 우리에게는 이와 같은 대제사장이 한 분 계시다는 것입니다. 그는 하늘에서 지엄하신 분의 보좌 오른쪽에 앉으셨습니다.", Chn:"", Eng:"The point of what we are saying is this: We do have such a high priest, who sat down at the right hand of the throne of the Majesty in heaven,", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:2, Page:1, Kor:"그는 성소와 참 장막에서 섬기시는 분입니다. 이 장막은 주님께서 세우신 것이요, 사람이 세운 것이 아닙니다.", Chn:"", Eng:"and who serves in the sanctuary, the true tabernacle set up by the Lord, not by man.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:3, Page:1, Kor:"모든 대제사장은 예물과 제사를 드리는 일을 맡게 하려고 세우신 사람입니다. 그러므로 이 대제사장도 무엇인가 드릴 것을 가지고 있어야 합니다.", Chn:"", Eng:"Every high priest is appointed to offer both gifts and sacrifices, and so it was necessary for this one also to have something to offer.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:4, Page:1, Kor:"그런데 그가 땅에 계신다고 하면, 제사장이 되지는 못하실 것입니다. 땅에서는 율법을 따라 이미 예물을 드리는 사람들이 있기 때문입니다.", Chn:"", Eng:"If he were on earth, he would not be a priest, for there are already men who offer the gifts prescribed by the law.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:5, Page:1, Kor:"그러나 그들은 하늘에 있는 것들의 모형과 그림자에 지나지 않는, 땅에 있는 성전에서 섬깁니다. 모세가 장막을 세우려고 할 때에, a\"너는 명심하여 내가 산에서 네게 보여준 그 모형을 따라 모든 것을 만들어라\" 하고 말씀하신 하나님의 지시를 받은 것입니다.(a 출 25:40)", Chn:"", Eng:"They serve at a sanctuary that is a copy and shadow of what is in heaven. This is why Moses was warned when he was about to build the tabernacle: \"See to it that you make everything according to the pattern shown you on the mountain.\"", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:6, Page:1, Kor:"그러나 이제 b그리스도께서는 더욱 훌륭한 직무를 맡으셨습니다. 그가 더 좋은 약속을 바탕으로 하여 세운 더 좋은 언약의 중재자이시기 때문입니다.(b 또는 '예수'. 그, '그')", Chn:"", Eng:"But the ministry Jesus has received is as superior to theirs as the covenant of which he is mediator is superior to the old one, and it is founded on better promises.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:7, Page:1, Kor:"○그 첫 번째 언약에 결함이 없었더라면, 두 번째 언약이 생길 여지가 없었을 것입니다.", Chn:"", Eng:"For if there had been nothing wrong with that first covenant, no place would have been sought for another.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:8, Page:1, Kor:"그런데 하나님께서는 자기 백성을 나무라시면서 이렇게 말씀하셨습니다.  c\"주님께서 말씀하신다. '보아라, 날이 이를 것이다. 그 때에 내가 이스라엘 집과 유다 집과 더불어 새 언약을 맺을 것이다.' (c 렘 31:31-34(칠십인역))", Chn:"", Eng:"But God found fault with the people and said: \"The time is coming, declares the Lord, when I will make a new covenant with the house of Israel and with the house of Judah.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:9, Page:1, Kor:"또 주님께서 말씀하신다. '이 새 언약은, 내가 그들의 조상들의 손을 잡고, 이집트 땅에서 인도하여 내던 날에, 그 조상들과 맺은 언약과 같은 것이 아니다. 그들은 내 언약을 지키지 않았으므로, 나도 그들을 돌보지 않았다.'", Chn:"", Eng:"It will not be like the covenant I made with their forefathers when I took them by the hand to lead them out of Egypt, because they did not remain faithful to my covenant, and I turned away from them, declares the Lord.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:10, Page:1, Kor:"또 주님께서 말씀하신다. '그 날 뒤에, 내가 이스라엘 집과 맺을 언약은 이것이니, 나는 내 율법을 그들의 생각에 넣어 주고, 그들의 마음에다가 새겨 주겠다. 그리하여 나는 그들의 하나님이 되고, 그들은 내 백성이 될 것이다.", Chn:"", Eng:"This is the covenant I will make with the house of Israel after that time, declares the Lord. I will put my laws in their minds and write them on their hearts. I will be their God, and they will be my people.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:11, Page:1, Kor:"그리고 그들은 각각 자기 이웃과 자기 d동족을 가르치려고, 주님을 알라고 말하는 일이 없을 것이니, 작은 사람으로부터 큰 사람에 이르기까지, 모두 나를 알 것이기 때문이다. (d 그, '형제')", Chn:"", Eng:"No longer will a man teach his neighbor, or a man his brother, saying, 'Know the Lord,' because they will all know me, from the least of them to the greatest.", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:12, Page:1, Kor:"내가 그들의 불의함을 긍휼히 여기겠고, 더 이상 그들의 죄를 기억하지 않겠다.'\"", Chn:"", Eng:"For I will forgive their wickedness and will remember their sins no more.\"", Ind:""},
  {Bible:"Hebrews", Chapter:8, Verse:13, Page:1, Kor:"하나님께서 '새 언약'이라고 말씀하심으로써, 첫 번째 언약을 낡은 것으로 만드셨습니다. 낡고 오래된 것은 곧 사라집니다.", Chn:"", Eng:"By calling this covenant \"new,\" he has made the first one obsolete; and what is obsolete and aging will soon disappear.", Ind:""},
]);
