// 에스겔 1장 · Ezekiel 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요. 그 개수만큼만 절 드롭다운에 나와요.
BibleDB.ref("Ezekiel",1,28);
BibleDB.add([
  {Bible:"Ezekiel", Chapter:1, Verse:1, Page:1, Kor:"", Chn:"", Eng:"In the thirtieth year, in the fourth month on the fifth day, while I was among the exiles by the Kebar River, the heavens were opened and I saw visions of God.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:2, Page:1, Kor:"", Chn:"", Eng:"On the fifth of the month--it was the fifth year of the exile of King Jehoiachin--", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:3, Page:1, Kor:"", Chn:"", Eng:"the word of the LORD came to Ezekiel the priest, the son of Buzi, by the Kebar River in the land of the Babylonians. There the hand of the LORD was upon him.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:4, Page:1, Kor:"", Chn:"", Eng:"I looked, and I saw a windstorm coming out of the north--an immense cloud with flashing lightning and surrounded by brilliant light. The center of the fire looked like glowing metal,", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:5, Page:1, Kor:"", Chn:"", Eng:"and in the fire was what looked like four living creatures. In appearance their form was that of a man,", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:6, Page:1, Kor:"", Chn:"", Eng:"but each of them had four faces and four wings.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Their legs were straight; their feet were like those of a calf and gleamed like burnished bronze.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Under their wings on their four sides they had the hands of a man. All four of them had faces and wings,", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:9, Page:1, Kor:"", Chn:"", Eng:"and their wings touched one another. Each one went straight ahead; they did not turn as they moved.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Their faces looked like this: Each of the four had the face of a man, and on the right side each had the face of a lion, and on the left the face of an ox; each also had the face of an eagle.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Such were their faces. Their wings were spread out upward; each had two wings, one touching the wing of another creature on either side, and two wings covering its body.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:12, Page:1, Kor:"", Chn:"", Eng:"Each one went straight ahead. Wherever the spirit would go, they would go, without turning as they went.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:13, Page:1, Kor:"", Chn:"", Eng:"The appearance of the living creatures was like burning coals of fire or like torches. Fire moved back and forth among the creatures; it was bright, and lightning flashed out of it.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:14, Page:1, Kor:"", Chn:"", Eng:"The creatures sped back and forth like flashes of lightning.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:15, Page:1, Kor:"", Chn:"", Eng:"As I looked at the living creatures, I saw a wheel on the ground beside each creature with its four faces.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:16, Page:1, Kor:"", Chn:"", Eng:"This was the appearance and structure of the wheels: They sparkled like chrysolite, and all four looked alike. Each appeared to be made like a wheel intersecting a wheel.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:17, Page:1, Kor:"", Chn:"", Eng:"As they moved, they would go in any one of the four directions the creatures faced; the wheels did not turn about as the creatures went.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:18, Page:1, Kor:"", Chn:"", Eng:"Their rims were high and awesome, and all four rims were full of eyes all around.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:19, Page:1, Kor:"", Chn:"", Eng:"When the living creatures moved, the wheels beside them moved; and when the living creatures rose from the ground, the wheels also rose.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Wherever the spirit would go, they would go, and the wheels would rise along with them, because the spirit of the living creatures was in the wheels.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:21, Page:1, Kor:"", Chn:"", Eng:"When the creatures moved, they also moved; when the creatures stood still, they also stood still; and when the creatures rose from the ground, the wheels rose along with them, because the spirit of the living creatures was in the wheels.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:22, Page:1, Kor:"", Chn:"", Eng:"Spread out above the heads of the living creatures was what looked like an expanse, sparkling like ice, and awesome.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:23, Page:1, Kor:"", Chn:"", Eng:"Under the expanse their wings were stretched out one toward the other, and each had two wings covering its body.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:24, Page:1, Kor:"", Chn:"", Eng:"When the creatures moved, I heard the sound of their wings, like the roar of rushing waters, like the voice of the Almighty, like the tumult of an army. When they stood still, they lowered their wings.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Then there came a voice from above the expanse over their heads as they stood with lowered wings.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:26, Page:1, Kor:"", Chn:"", Eng:"Above the expanse over their heads was what looked like a throne of sapphire, and high above on the throne was a figure like that of a man.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:27, Page:1, Kor:"", Chn:"", Eng:"I saw that from what appeared to be his waist up he looked like glowing metal, as if full of fire, and that from there down he looked like fire; and brilliant light surrounded him.", Ind:""},
  {Bible:"Ezekiel", Chapter:1, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Like the appearance of a rainbow in the clouds on a rainy day, so was the radiance around him. This was the appearance of the likeness of the glory of the LORD. When I saw it, I fell facedown, and I heard the voice of one speaking.", Ind:""},
]);
