// 에스겔 32장 · Ezekiel 32
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Ezekiel",32,32);
BibleDB.add([
  {Bible:"Ezekiel", Chapter:32, Verse:1, Page:1,
    Kor:"<악어와 같았던 이집트> 제 십이년 열두째 달 초하루에, 주님께서 나에게 말씀하셨다.",
    Chn:"十二年十二月初一日，耶和华的话临到我说：",
    Eng:"In the twelfth year, in the twelfth month on the first day, the word of the LORD came to me:",
    Ind:"Pada tahun kedua belas, dalam bulan yang kedua belas, pada tanggal satu bulan itu, datanglah firman TUHAN kepadaku:"
  },
  {Bible:"Ezekiel", Chapter:32, Verse:2, Page:1,
    Kor:"○\"사람아, 너는 이집트 왕 바로를 두고 애가를 불러라. 너는 그에게 알려 주어라.  '너는 스스로 네가 만방의 사자라고 생각하지만, 너는 나일 강 속에 있는 악어이다. 뾰족한 코로 강물을 흩뿌리고 발로 강물을 휘저으면서 강물을 더럽혔다.",
    Chn:"「人子啊，你要为埃及王法老作哀歌，说： 从前你在列国中，如同少壮狮子； 现在你却像海中的大鱼。 你冲出江河， 用爪搅动诸水， 使江河浑浊。",
    Eng:"\"Son of man, take up a lament concerning Pharaoh king of Egypt and say to him: \"'You are like a lion among the nations; you are like a monster in the seas thrashing about in your streams, churning the water with your feet and muddying the streams.",
    Ind:"\"Hai anak manusia, ucapkanlah suatu ratapan mengenai Firaun, raja Mesir dan katakanlah kepadanya: Engkau menyamakan dirimu dengan singa muda di antara bangsa-bangsa. Tetapi engkau seperti buaya di laut; sungai-sungaimu kaubuat berbuih, engkau mengeruhkan airnya dengan kaki dan menggelompar dalam lumpur sungainya."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:3, Page:1,
    Kor:"그러므로 나 주 하나님이 말한다. 내가 많은 백성을 불러와서, 그들이 보는 앞에서 그물을 던져 너를 잡고, 예인망으로 너를 끌어올려서,",
    Chn:"主耶和华如此说： 我必用多国的人民， 将我的网撒在你身上， 把你拉上来。",
    Eng:"\"'This is what the Sovereign LORD says: \"'With a great throng of people I will cast my net over you, and they will haul you up in my net.",
    Ind:"Beginilah firman Tuhan ALLAH: Aku memasang jaringku menangkap engkau dengan sekumpulan bangsa-bangsa yang banyak, dan mengangkat engkau di dalam pukat-Ku."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:4, Page:1,
    Kor:"땅바닥에 내던지고 들판에 내동댕이치겠다. 공중의 새를 데려다가 네 몸 위에 내려앉게 하며, 온 땅의 들짐승들이 너를 뜯어먹고 배부르게 하겠다.",
    Chn:"我必将你丢在地上， 抛在田野， 使空中的飞鸟都落在你身上， 使遍地的野兽吃你得饱。",
    Eng:"I will throw you on the land and hurl you on the open field. I will let all the birds of the air settle on you and all the beasts of the earth gorge themselves on you.",
    Ind:"Kuhempaskan engkau ke tanah, Kulemparkan engkau ke padang. Dan ke atasmu Kusuruh hinggap segala burung di udara, dengan dagingmu Kukenyangkan binatang-binatang seluruh bumi."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:5, Page:1,
    Kor:"너의 살점을 이산 저산에 흩어 놓으면 골짜기마다 a네 시체로 가득 찰 것이다. (a 심마쿠스역과 시리아어역과 불가타를 따름. 히, '네 높은 키')",
    Chn:"我必将你的肉丢在山间， 用你高大的尸首填满山谷。",
    Eng:"I will spread your flesh on the mountains and fill the valleys with your remains.",
    Ind:"Dagingmu Kubiarkan berhamburan di atas pegunungan, lembah-lembah Aku penuhi dengan bangkai-bangkaimu."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:6, Page:1,
    Kor:"내가 네 피로 땅을 적시고, 산꼭대기까지 적실 것이니, 시내마다 네 피가 철철 넘쳐 흐를 것이다.",
    Chn:"我又必用你的血浇灌你所游泳之地， 漫过山顶； 河道都必充满。",
    Eng:"I will drench the land with your flowing blood all the way to the mountains, and the ravines will be filled with your flesh.",
    Ind:"Bumi Kuberi minum darahmu yang mengalir, ya, juga gunung-gunung; dan alur-alur sungai akan penuh dengannya."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:7, Page:1,
    Kor:"내가 네 빛을 꺼지게 할 때에, 하늘을 가려 별들을 어둡게 하고, 구름으로 태양을 가리고, 달도 빛을 내지 못하게 하겠다.",
    Chn:"我将你扑灭的时候， 要把天遮蔽， 使众星昏暗， 以密云遮掩太阳， 月亮也不放光。",
    Eng:"When I snuff you out, I will cover the heavens and darken their stars; I will cover the sun with a cloud, and the moon will not give its light.",
    Ind:"Waktu Aku membinasakan engkau, langit akan Kututup dan bintangnya Kubuat berkabut. Matahari Kututup dengan awan dan bulan, cahayanya tak disinarkan."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:8, Page:1,
    Kor:"하늘에서 빛나는 광채들을 모두 어둡게 하고, 네 땅을 어둠으로 뒤덮어 놓겠다. 나 주 하나님의 말이다.",
    Chn:"我必使天上的亮光都在你以上变为昏暗， 使你的地上黑暗。 这是主耶和华说的。",
    Eng:"All the shining lights in the heavens I will darken over you; I will bring darkness over your land, declares the Sovereign LORD.",
    Ind:"Semua yang bersinar di langit akan Kugelapkan demi engkau. Kegelapan Kudatangkan atas tanahmu, demikianlah firman Tuhan ALLAH."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:9, Page:1,
    Kor:"b네가 망했다는 소식을 내가 뭇 민족에게 알리면, 뭇 민족이 네가 알지도 못하던 그 나라들이 네가 망했다는 소식을 듣고, 불안에 떨 것이다. (b 칠십인역에는 '내가 너를 뭇 민족 가운데 포로로 잡혀가게 하면')",
    Chn:"「我使你败亡的风声传到你所不认识的各国。那时，我必使多民的心因你愁烦。",
    Eng:"I will trouble the hearts of many peoples when I bring about your destruction among the nations, among lands you have not known.",
    Ind:"Aku menggelisahkan hati banyak bangsa, kalau Aku membawa kamu sebagai tawanan di tengah bangsa-bangsa, ke negeri-negeri yang belum kamu kenal."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:10, Page:1,
    Kor:"많은 백성이 보는 앞에서 내가 칼을 휘둘러 너를 치면, 그들은 소스라쳐 놀라고, 또 내가 그들의 왕 앞에서 나의 칼을 휘둘러 너를 치면, 네가 받은 형벌을 보고 모두 벌벌 떨 것이며, 네가 쓰러지는 그 날에는, 왕들마다 목숨을 잃을까봐 떨 것이다.",
    Chn:"我在许多国民和君王面前向你抡我的刀，国民就必因你惊奇，君王也必因你极其恐慌。在你仆倒的日子，他们各人为自己的性命时刻战兢。」",
    Eng:"I will cause many peoples to be appalled at you, and their kings will shudder with horror because of you when I brandish my sword before them. On the day of your downfall each of them will tremble every moment for his life.",
    Ind:"Aku akan membuat banyak bangsa kaget melihat engkau, dan raja-rajanya akan menggigil melihatmu, kalau Aku menetak-netakkan pedang-Ku di hadapan mereka. Mereka akan gentar, terus-menerus, masing-masing demi hidupnya, pada hari kesudahanmu."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:11, Page:1,
    Kor:"나 주 하나님이 말한다. 바빌로니아 왕의 칼이 네게 미칠 것이다.",
    Chn:"主耶和华如此说：「巴比伦王的刀必临到你。",
    Eng:"\"'For this is what the Sovereign LORD says: \"'The sword of the king of Babylon will come against you.",
    Ind:"Sebab beginilah firman Tuhan ALLAH: Pedang raja Babel akan datang atasmu."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:12, Page:1,
    Kor:"내가 용사들의 칼로 너의 무리를 쓰러뜨리겠다. 그들은 뭇 민족 가운데서 가장 잔인한 사람들이다. 이집트가 자랑하던 것을 그들이 박살내며, 이집트의 온 무리를 그들이 멸망시킬 것이다.",
    Chn:"我必借勇士的刀使你的众民仆倒；这勇士都是列国中强暴的。 他们必使埃及的骄傲归于无有； 埃及的众民必被灭绝。",
    Eng:"I will cause your hordes to fall by the swords of mighty men--the most ruthless of all nations. They will shatter the pride of Egypt, and all her hordes will be overthrown.",
    Ind:"Aku akan membuat khalayak pengikutmu berebahan oleh pedang para pahlawan, semuanya yang terganas di antara bangsa-bangsa. Kecongkakan Mesir akan dipatahkan dan khalayak pengikutnya semua dipunahkan."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:13, Page:1,
    Kor:"내가 그 큰 물 가에서 모든 짐승을 없애 버리면, 다시는 사람의 발이 그 물을 흐리게 하지 못하고, 짐승의 발굽도 그 물을 흐리게 하지 못할 것이다.",
    Chn:"我必从埃及多水旁除灭所有的走兽； 人脚兽蹄必不再搅浑这水。",
    Eng:"I will destroy all her cattle from beside abundant waters no longer to be stirred by the foot of man or muddied by the hoofs of cattle.",
    Ind:"Semua binatangnya akan Kubinasakan dari tepi sungai-sungai besar; kaki manusia tidak lagi mengeruhkannya dan di dalamnya tiada hewan menggelompar."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:14, Page:1,
    Kor:"그리고 나서 내가 그 강물을 맑게 하여, 모든 강물이 기름처럼 흐르게 하겠다. 나 주 하나님의 말이다.",
    Chn:"那时，我必使埃及河澄清， 江河像油缓流。 这是主耶和华说的。",
    Eng:"Then I will let her waters settle and make her streams flow like oil, declares the Sovereign LORD.",
    Ind:"Maka airnya akan Kujernihkan, sungai-sungainya akan Kubuat mengalir seperti minyak, demikianlah firman Tuhan ALLAH."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:15, Page:1,
    Kor:"내가 이집트 땅을 황무지로 만들면, 그래서 그 땅에 가득 찬 풍요가 사라지면, 내가 그 땅에 사는 모든 사람을 치면, 그 때에야 비로소 그들이, 내가 주인 줄 알 것이다.",
    Chn:"我使埃及地变为荒废凄凉； 这地缺少从前所充满的， 又击杀其中一切的居民。 那时，他们就知道我是耶和华。",
    Eng:"When I make Egypt desolate and strip the land of everything in it, when I strike down all who live there, then they will know that I am the LORD.'",
    Ind:"Pada saat Mesir Kujadikan sunyi sepi, juga habis dilenyapkan segala isi negeri dan semua penduduknya habis Kumusnahkan, mereka akan tahu bahwa Akulah TUHAN."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:16, Page:1,
    Kor:"이것이 그들이 부를 애가다. 여러 민족의 딸들이 이것을 애가로 부를 것이다. 그들은 이것을 이집트와 그 나라의 온 무리를 애도하는 조가로 부를 것이다. 나 주 하나님의 말이다.'\"",
    Chn:"「人必用这哀歌去哀哭，列国的女子为埃及和她的群众也必以此悲哀。这是主耶和华说的。」",
    Eng:"\"This is the lament they will chant for her. The daughters of the nations will chant it; for Egypt and all her hordes they will chant it, declares the Sovereign LORD.\"",
    Ind:"Inilah ratapan yang seharusnya dinyanyikan; kaum perempuan bangsa-bangsa akan menyanyikannya; mereka akan menyanyikannya atas Mesir dan atas seluruh rakyatnya yang banyak, demikianlah firman Tuhan ALLAH.\""
  },
  {Bible:"Ezekiel", Chapter:32, Verse:17, Page:1,
    Kor:"<죽은 자들의 세계> ○제 십이년 c첫째 달 십오일에 주님께서 나에게 말씀하셨다.(c 칠십인역을 따름. 히브리어 본문에는 '첫째 달'이 없음)",
    Chn:"十二年十二月十五日，耶和华的话临到我说：",
    Eng:"In the twelfth year, on the fifteenth day of the month, the word of the LORD came to me:",
    Ind:"Pada tahun kedua belas, dalam bulan pertama, pada tanggal lima belas bulan itu, datanglah firman TUHAN kepadaku:"
  },
  {Bible:"Ezekiel", Chapter:32, Verse:18, Page:1,
    Kor:"\"사람아, 너는 이집트의 무리를 애도하여 슬피 울고, 이집트와 열강의 딸들을, 깊은 구덩이로 내려가는 사람들과 함께, 지하로 보내면서 일러라.",
    Chn:"「人子啊，你要为埃及群众哀号，又要将埃及和有名之国的女子，并下坑的人，一同扔到阴府去。",
    Eng:"\"Son of man, wail for the hordes of Egypt and consign to the earth below both her and the daughters of mighty nations, with those who go down to the pit.",
    Ind:"\"Hai anak manusia, perdengarkanlah suatu ratapan--engkau bersama kaum perempuan bangsa-bangsa yang hebat--mengenai khalayak ramai di Mesir dan turunkanlah mereka ke bumi yang paling bawah menjumpai mereka yang telah turun ke liang kubur."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:19, Page:1,
    Kor:"'도대체 네가 누구보다 더 아름답다는 거냐? 너는 아래로 내려가서 할례받지 못한 자들과 함께 누워라' 하여라.",
    Chn:"你埃及的美丽胜过谁呢？ 你下去与未受割礼的人一同躺卧吧！",
    Eng:"Say to them, 'Are you more favored than others? Go down and be laid among the uncircumcised.'",
    Ind:"Dari siapakah engkau lebih cantik? Turunlah dan berbaringlah bersama orang-orang yang tidak bersunat!"
  },
  {Bible:"Ezekiel", Chapter:32, Verse:20, Page:1,
    Kor:"○그들은 칼에 찔려 죽은 사람들 한가운데로 떨어질 것이다. 칼이 이미 이집트의 목을 겨누고 있으니, 이집트와 그의 온 군대를 지하로 내려보내라.",
    Chn:"他们必在被杀的人中仆到。她被交给刀剑，要把她和她的群众拉去。",
    Eng:"They will fall among those killed by the sword. The sword is drawn; let her be dragged off with all her hordes.",
    Ind:"Mereka akan rebah di tengah orang-orang yang mati terbunuh oleh pedang dan seluruh rakyatnya yang banyak akan telentang bersama dia."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:21, Page:1,
    Kor:"그러면 스올에 있는 강한 용사들이 부하들과 함께 바로의 무리에게 이르기를 '저 할례받지 못한 자들이, 저 칼에 찔려 죽은 자들이, 이 곳 아래로 떨어져 눕는다' 할 것이다.",
    Chn:"强盛的勇士要在阴间对埃及王和帮助他的说话；他们是未受割礼被杀的人，已经下去，躺卧不动。",
    Eng:"From within the grave the mighty leaders will say of Egypt and her allies, 'They have come down and they lie with the uncircumcised, with those killed by the sword.'",
    Ind:"Orang-orang berkuasa yang gagah perkasa beserta pembantu-pembantunya akan berbicara mengenai dia dari tengah dunia orang mati: Mereka telah turun dan telentang, orang-orang yang tidak bersunat itu, yang mati terbunuh oleh pedang."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:22, Page:1,
    Kor:"○그 곳에는 앗시리아가 묻혀 있고, 그의 군대가 함께 묻혀 있다. 사방에 그들의 무덤이 있다. 그들은 모두 칼에 찔려 죽은 전사자들이요, 칼에 쓰러진 자들이다.",
    Chn:"「亚述和她的众民都在那里，她民的坟墓在她四围；他们都是被杀倒在刀下的。",
    Eng:"\"Assyria is there with her whole army; she is surrounded by the graves of all her slain, all who have fallen by the sword.",
    Ind:"Di situ Asyur dengan semua sekutunya, sekelilingnya terdapat kuburnya; mereka semuanya mati terbunuh, rebah oleh pedang."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:23, Page:1,
    Kor:"앗시리아의 무덤은 구덩이의 가장 깊은 밑바닥에 마련되었고, 그 무덤의 둘레에는 앗시리아의 군대가 묻혀 있는데, 그들은 모두가 칼을 맞고 쓰러진 자들로서, 칼에 찔려 죽은 전사자들, 살아 있는 사람들의 세상에서 사람들에게 겁을 주던 자들이다.",
    Chn:"他们的坟墓在坑中极深之处。她的众民在她坟墓的四围，都是被杀倒在刀下的；他们曾在活人之地使人惊恐。",
    Eng:"Their graves are in the depths of the pit and her army lies around her grave. All who had spread terror in the land of the living are slain, fallen by the sword.",
    Ind:"Kuburnya ditentukan pada bagian yang terdalam dari liang dan kumpulan pengikutnya terdapat sekeliling kuburnya; mereka semuanya mati terbunuh, rebah oleh pedang, yaitu yang menimbulkan ketakutan di dunia orang-orang hidup."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:24, Page:1,
    Kor:"○그 곳에는 엘람이 묻혀 있고, 그 무덤 둘레에는 엘람의 온 군대가 묻혀 있다. 그들은 모두가 칼을 맞고 쓰러진 자들, 칼에 찔려 죽은 전사자들이다. 그들은 할례를 받지 못한 자들로서, 지하에 내려갔다. 그들은 살아 있는 사람들의 세상에서 사람들에게 겁을 주던 자들이었으나, 이제는 깊은 구덩이로 내려간 자들과 함께 자신들의 수치를 뒤집어쓰고 있다.",
    Chn:"「以拦也在那里，她的群众在她坟墓的四围，都是被杀倒在刀下、未受割礼而下阴府的；他们曾在活人之地使人惊恐，并且与下坑的人一同担当羞辱。",
    Eng:"\"Elam is there, with all her hordes around her grave. All of them are slain, fallen by the sword. All who had spread terror in the land of the living went down uncircumcised to the earth below. They bear their shame with those who go down to the pit.",
    Ind:"Di situ Elam dan sekeliling kuburnya seluruh rakyatnya yang banyak; mereka semuanya mati terbunuh, rebah oleh pedang, yaitu yang tanpa disunat turun ke bumi yang paling bawah, yang dari pihaknya menimbulkan ketakutan di dunia orang-orang hidup. Mereka menanggung nodanya bersama orang-orang yang turun ke liang kubur."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:25, Page:1,
    Kor:"엘람의 침상은 칼에 찔려 죽은 전사자들 한가운데 놓여 있고, 그 무덤의 둘레에는 엘람의 군대가 모두 묻혀 있다. 그들은 모두 할례를 받지 못한 자들이요, 칼에 찔려 죽은 전사자들이요, 살아 있는 사람들의 세상에서 사람들에게 겁을 주던 자들이었으나, 이제는 깊은 구덩이로 내려간 자들과 함께 자신들의 수치를 뒤집어쓰고 있다. 이제는 칼에 찔려 죽은 전사자들과 함께 누워 있다.",
    Chn:"人给她和她的群众在被杀的人中设立床榻。她民的坟墓在她四围，他们都是未受割礼被刀杀的；他们曾在活人之地使人惊恐，并且与下坑的人一同担当羞辱。以拦已经放在被杀的人中。",
    Eng:"A bed is made for her among the slain, with all her hordes around her grave. All of them are uncircumcised, killed by the sword. Because their terror had spread in the land of the living, they bear their shame with those who go down to the pit; they are laid among the slain.",
    Ind:"Di tengah orang-orang yang mati terbunuh disediakan tempat tidur baginya dengan seluruh rakyatnya yang banyak sekeliling kuburnya; mereka semuanya orang-orang yang tidak disunat, mati terbunuh oleh pedang. Oleh sebab ketakutan terhadap mereka sudah ditimbulkan di dunia orang-orang hidup, dan mereka menanggung nodanya bersama orang-orang yang turun ke liang kubur; mereka ditempatkan di tengah orang-orang yang mati terbunuh."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:26, Page:1,
    Kor:"○그 곳에는 메섹과 두발이 묻혀 있고, 그 무덤의 둘레에는 그들의 군대가 모두 묻혀 있다. 그들은 모두 할례를 받지 못한 자들이요, 칼에 찔려 죽은 전사자들이요, 살아 있는 사람들의 세상에서 사람들에게 겁을 주던 자들이었다.",
    Chn:"「米设、土巴，和她们的群众都在那里。她民的坟墓在她四围，他们都是未受割礼被刀杀的；他们曾在活人之地使人惊恐。",
    Eng:"\"Meshech and Tubal are there, with all their hordes around their graves. All of them are uncircumcised, killed by the sword because they spread their terror in the land of the living.",
    Ind:"Di situ Mesekh dan Tubal dengan seluruh rakyatnya yang banyak sekeliling kuburnya; mereka semuanya orang-orang yang tidak disunat, mati terbunuh oleh pedang, sebab mereka menimbulkan ketakutan di dunia orang-orang hidup."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:27, Page:1,
    Kor:"그러나 그들은, 전쟁 무기를 가지고 스올로 내려가 칼을 베개로 삼아 베고 d방패를 이불로 삼아 덮고 자는 고대의 전몰 용사들과 함께 눕지는 못하였다. 그들은 살아 있는 사람들의 세상에서는 사람들에게 겁을 주던 자들이었다.(d 히, '죄를')",
    Chn:"他们不得与那未受割礼仆倒的勇士一同躺卧；这些勇士带着兵器下阴间，头枕刀剑，骨头上有本身的罪孽；他们曾在活人之地使勇士惊恐。",
    Eng:"Do they not lie with the other uncircumcised warriors who have fallen, who went down to the grave with their weapons of war, whose swords were placed under their heads? The punishment for their sins rested on their bones, though the terror of these warriors had stalked through the land of the living.",
    Ind:"Mereka tidak dibaringkan bersama pahlawan-pahlawan yang mati rebah pada zaman dahulu, yang turun ke dunia orang mati bersama segala senjata perangnya dan yang pedang-pedangnya ditaruh orang di bawah kepalanya serta perisai-perisainya terletak di atas tulang-tulangnya; sebab ketakutan terhadap pahlawan-pahlawan itu meliputi dunia orang-orang hidup."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:28, Page:1,
    Kor:"○이제 너 이집트는 패망하여, 칼에 찔려 죽은 자들과 함께, 할례를 받지 못하고 죽은 자들과 함께 누울 것이다.",
    Chn:"「法老啊，你必在未受割礼的人中败坏，与那些被杀的人一同躺卧。",
    Eng:"\"You too, O Pharaoh, will be broken and will lie among the uncircumcised, with those killed by the sword.",
    Ind:"Engkau akan telentang di tengah orang-orang yang tidak bersunat bersama orang-orang yang mati terbunuh oleh pedang."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:29, Page:1,
    Kor:"○그 곳에는 에돔 곧 에돔의 왕들과 그 모든 지도자가 묻혀 있다. 그들은 용맹스러웠으나, 지금은 칼에 찔려 죽은 전사자들과 함께 누워 있고, 할례를 받지 못하고 무덤으로 내려간 자들과 함께 누워 있다.",
    Chn:"「以东也在那里。她君王和一切首领虽然仗着势力，还是放在被杀的人中；他们必与未受割礼的和下坑的人一同躺卧。",
    Eng:"\"Edom is there, her kings and all her princes; despite their power, they are laid with those killed by the sword. They lie with the uncircumcised, with those who go down to the pit.",
    Ind:"Di situ Edom, raja-rajanya dan semua pemimpinnya, yang ditempatkan dekat orang-orang yang mati terbunuh oleh pedang, walaupun mereka kuat; mereka dibaringkan dekat orang-orang yang tidak disunat dan dekat orang-orang yang turun ke liang kubur."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:30, Page:1,
    Kor:"그 곳에는 북쪽의 모든 우두머리와 모든 시돈 사람이 묻혀 있다. 그들은 칼에 찔려 죽은 전사자들과 함께 지하로 떨어졌다. 그들이 세상에서는 두려움을 떨치고 힘을 자랑하였으나, 이제는 수치를 당하게 되고, 할례를 받지 못하고 죽은 자들, 칼에 찔려 죽은 전사자들과 함께 누워 있고, 깊은 구덩이로 내려간 사람들과 함께 수치를 뒤집어쓰고 있다.",
    Chn:"「在那里有北方的众王子和一切西顿人，都与被杀的人下去。他们虽然仗着势力使人惊恐，还是蒙羞。他们未受割礼，和被刀杀的一同躺卧，与下坑的人一同担当羞辱。",
    Eng:"\"All the princes of the north and all the Sidonians are there; they went down with the slain in disgrace despite the terror caused by their power. They lie uncircumcised with those killed by the sword and bear their shame with those who go down to the pit.",
    Ind:"Di situ pemimpin-pemimpin dari utara, semuanya mereka, dan semua orang Sidon, yang dengan malu turun dekat orang-orang yang mati terbunuh, walaupun dengan kekuatannya mereka sudah menimbulkan ketakutan terhadap mereka; mereka dibaringkan tanpa disunat dekat orang-orang yang mati terbunuh oleh pedang dan mereka menanggung nodanya bersama orang-orang yang turun ke liang kubur."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:31, Page:1,
    Kor:"○바로와 그의 온 군대가 칼에 찔려 죽었지만, 지하에 내려가서, 이미 거기에 와 있는 군대를 모두 보고서는, 그들이 위로를 받을 것이다. 나 주 하나님의 말이다.",
    Chn:"「法老看见他们，便为他被杀的军队受安慰。这是主耶和华说的。",
    Eng:"\"Pharaoh--he and all his army--will see them and he will be consoled for all his hordes that were killed by the sword, declares the Sovereign LORD.",
    Ind:"Firaun akan melihat mereka semuanya dan ia akan merasa terhibur dengan nasib khalayak ramai yang mengikutinya. Firaun mati terbunuh oleh pedang dengan seluruh tentaranya, demikianlah firman Tuhan ALLAH."
  },
  {Bible:"Ezekiel", Chapter:32, Verse:32, Page:1,
    Kor:"○살아 있는 사람들의 세상에서 바로가 사람들에게 겁을 준 것은, 사실은, 내가 그렇게 하도록 시킨 것이다. 그러나 이제는 바로가 자기의 모든 군대와 함께 할례받지 못한 자들과 섞여, 칼에 찔려 죽은 전사자들과 함께 무덤에 눕게 될 것이다. 나 주 하나님의 말이다.\"",
    Chn:"我任凭法老在活人之地使人惊恐，法老和他的群众必放在未受割礼和被杀的人中。这是主耶和华说的。」",
    Eng:"Although I had him spread terror in the land of the living, Pharaoh and all his hordes will be laid among the uncircumcised, with those killed by the sword, declares the Sovereign LORD.\"",
    Ind:"Oleh karena ia menimbulkan ketakutan di dunia orang-orang hidup, maka ia dibaringkan di tengah orang-orang yang tidak disunat, dekat orang yang mati terbunuh oleh pedang. Firaun dengan seluruh khalayak ramai yang mengikutinya, demikianlah firman Tuhan ALLAH.\""
  },
]);
