// 에스겔 7장 · Ezekiel 7
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Ezekiel",7,27);
BibleDB.add([
  {Bible:"Ezekiel", Chapter:7, Verse:1, Page:1,
    Kor:"<이스라엘의 종말이 다가오다> 주님께서 나에게 말씀하셨다.",
    Chn:"耶和华的话又临到我说：",
    Eng:"The word of the LORD came to me:",
    Ind:"Kemudian datanglah firman TUHAN kepadaku:"
  },
  {Bible:"Ezekiel", Chapter:7, Verse:2, Page:1,
    Kor:"○\"너 사람아, 이스라엘에게 전하여라. 나 주 하나님이 이스라엘 땅을 두고 말한다.  끝이 왔다. 이 땅의 사방 구석구석에 끝이 왔다.",
    Chn:"「人子啊，主耶和华对以色列地如此说：结局到了，结局到了地的四境！",
    Eng:"\"Son of man, this is what the Sovereign LORD says to the land of Israel: The end! The end has come upon the four corners of the land.",
    Ind:"\"Engkau, anak manusia, katakanlah: Beginilah firman Tuhan ALLAH kepada tanah Israel: Berakhir! Berakhirlah keempat penjuru tanah itu."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:3, Page:1,
    Kor:"이스라엘아, 이제는 너희에게 끝이 왔다. 나는 이제 너희에게 내 분노를 쏟고, 너희 행실에 따라 너희를 심판하며, 너희의 역겨운 일들을 너희에게 보응하겠다.",
    Chn:"现在你的结局已经临到，我必使我的怒气归与你，也必按你的行为审判你，照你一切可憎的事刑罚你。",
    Eng:"The end is now upon you and I will unleash my anger against you. I will judge you according to your conduct and repay you for all your detestable practices.",
    Ind:"Kini kesudahanmu tiba dan Aku akan mencurahkan murka-Ku atasmu dan Aku akan menghakimi engkau selaras dengan tingkah lakumu dan Aku akan membalaskan kepadamu segala perbuatanmu yang keji."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:4, Page:1,
    Kor:"내가 너희를 아끼지도 않고, 불쌍히 여기지도 않겠다. 오히려 나는 너희의 모든 행실에 따라 너희를 벌하여, 역겨운 일들이 바로 너희의 한가운데서 벌어지게 하겠다. 그 때에야 비로소 내가 주인 줄 너희가 알게 될 것이다.\"",
    Chn:"我眼必不顾惜你，也不可怜你，却要按你所行的报应你，照你中间可憎的事刑罚你。你就知道我是耶和华。",
    Eng:"I will not look on you with pity or spare you; I will surely repay you for your conduct and the detestable practices among you. Then you will know that I am the LORD.",
    Ind:"Aku tidak akan merasa sayang kepadamu dan tidak akan kenal belas kasihan, tetapi Aku akan membalaskan kepadamu selaras dengan tingkah lakumu dan perbuatan-perbuatanmu yang keji akan tertimpa atasmu. Maka kamu akan mengetahui, bahwa Akulah TUHAN."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:5, Page:1,
    Kor:"주 하나님이 이렇게 말씀하신다. \"a재앙이다. 너희가 들어보지 못한 재앙이다. 이미 다가왔다. (a 몇몇 히브리어 사본과 시리아어역에는 '재앙에 재앙이 겹쳐 온다!')",
    Chn:"「主耶和华如此说：有一灾，独有一灾；看哪，临近了！",
    Eng:"\"This is what the Sovereign LORD says: Disaster! An unheard-of disaster is coming.",
    Ind:"Beginilah firman Tuhan ALLAH: Lihat, bencana demi bencana akan datang!"
  },
  {Bible:"Ezekiel", Chapter:7, Verse:6, Page:1,
    Kor:"끝이 왔다. 너희를 덮치려고 일어났다. 이미 다가왔다.",
    Chn:"结局来了，结局来了，向你兴起。看哪，来到了！",
    Eng:"The end has come! The end has come! It has roused itself against you. It has come!",
    Ind:"Kesudahan datang, kesudahanmu tiba, seakan-akan ia terbangun melawan engkau, lihat datangnya!"
  },
  {Bible:"Ezekiel", Chapter:7, Verse:7, Page:1,
    Kor:"이 땅에 사는 사람들아, 정해진 멸망이 너희에게 들이닥쳤다. 그 시각이 왔고, 그 날이 다가왔다. 산에서 즐겁게 환호하지 못할 당황할 날이 가까이 왔다.",
    Chn:"境内的居民哪，所定的灾临到你，时候到了，日子近了，乃是哄嚷并非在山上欢呼的日子。",
    Eng:"Doom has come upon you--you who dwell in the land. The time has come, the day is near; there is panic, not joy, upon the mountains.",
    Ind:"Malapetaka datang atasmu, hai penduduk negeri! Waktunya datang, saatnya tiba! Hari huru-hara, bukan tempik sorak di atas gunung-gunung."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:8, Page:1,
    Kor:"나는 이제 너희에게 내 분노를, 나의 분을 너희에게 쏟아서, 너희 행실에 따라 너희를 심판하며, 너희의 역겨운 일들을 너희에게 갚아주겠다.",
    Chn:"我快要将我的忿怒倾在你身上，向你成就我怒中所定的，按你的行为审判你，照你一切可憎的事刑罚你。",
    Eng:"I am about to pour out my wrath on you and spend my anger against you; I will judge you according to your conduct and repay you for all your detestable practices.",
    Ind:"Sekarang dengan segera Aku akan mencurahkan amarah-Ku atasmu dan melampiaskan murka-Ku kepadamu, Aku akan menghakimi engkau selaras dengan tingkah lakumu dan membalaskan kepadamu segala perbuatan-perbuat yang keji."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:9, Page:1,
    Kor:"내가 너희를 아끼지도 않고, 불쌍히 여기지도 않겠다. 오히려 나는 너희의 모든 행실에 따라 너희를 벌하여, 역겨운 일들이 바로 너희의 한가운데서 벌어지게 하겠다. 그 때에야 비로소 주가 이렇게 치는 것임을, 너희가 알게 될 것이다.",
    Chn:"我眼必不顾惜你，也不可怜你，必按你所行的报应你，照你中间可憎的事刑罚你。你就知道击打你的是我耶和华。",
    Eng:"I will not look on you with pity or spare you; I will repay you in accordance with your conduct and the detestable practices among you. Then you will know that it is I the LORD who strikes the blow.",
    Ind:"Aku tidak akan merasa sayang dan tidak akan kenal belas kasihan; selaras dengan tingkah lakumu akan Kubalaskan kepadamu dan perbuatan-perbuatanm yang keji akan tertimpa atasmu. Maka kamu akan mengetahui, bahwa Aku, Tuhanlah, yang memusnahkan."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:10, Page:1,
    Kor:"그 날이다. 보아라, 들이닥쳤다. 정해진 멸망이 시작되었다. 매질할 몽둥이가 꽃을 피우고 교만을 꺾을 채찍이 싹터 나왔다.",
    Chn:"「看哪，看哪，日子快到了；所定的灾已经发出！杖已经开花，骄傲已经发芽。",
    Eng:"\"The day is here! It has coma! Doom has burst forth, the rod has budded, arrogance has blossomed!",
    Ind:"Lihat, harinya sungguh datang: malapetaka akan menimpa, kelaliman bertunas, keangkuhan bertaruk."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:11, Page:1,
    Kor:"b폭력이 일어나서 죄악을 징벌하는 몽둥이가 되었다. 이 백성 가운데서 한 사람도 남지 않고, 이 백성의 무리들 가운데서도 더 이상 남을 사람이 없고, 그들의 재물이나 그들이 가진 것들 가운데서 눈에 띌 만한 것은 하나도 남아 있지 않을 것이다. (b 또는 '광포한 자가')",
    Chn:"强暴兴起，成了罚恶的杖。以色列人，或是他们的群众，或是他们的财宝，无一存留；他们中间也没有得尊荣的。",
    Eng:"Violence has grown into a rod to punish wickedness; none of the people will be left, none of that crowd--no wealth, nothing of value.",
    Ind:"Kekerasan bersimaharajalela, yang menjadi penopang segala kejahatan. Tidak ada dari mereka yang tertinggal, baik dari kelimpahan mereka maupun dari kemewahannya; kemolekannyapun akan terhapus."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:12, Page:1,
    Kor:"그 시각이 왔고, 그 날이 이르고야 말았다. 사는 사람도 기뻐하지 말고, 파는 사람도 슬퍼하지 말아라. 이 땅의 모든 무리에게 진노가 내릴 것이기 때문이다.",
    Chn:"时候到了，日子近了，买主不可欢喜，卖主不可愁烦，因为烈怒已经临到他们众人身上。",
    Eng:"The time has come, the day has arrived. Let not the buyer rejoice nor the seller grieve, for wrath is upon the whole crowd.",
    Ind:"Waktunya datang, harinya mendekat! Biarlah si pembeli jangan bergembira dan biarlah si penjual jangan berdukacita, karena kehangatan murka tertimpa atas segala kegemparan mereka."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:13, Page:1,
    Kor:"○판 사람이 아직 살아 있다 하여도, 팔린 것을 되찾으려고 돌아갈 수가 없을 것이니, 이 땅의 모든 무리에게 보여 준 묵시는 돌이킬 수가 없기 때문이다. 죄를 짓고서는, 어느 누구도 자기 목숨을 굳게 부지할 수가 없다.",
    Chn:"卖主虽然存活，却不能归回再得所卖的，因为这异象关乎他们众人。谁都不得归回，也没有人在他的罪孽中坚立自己。」",
    Eng:"The seller will not recover the land he has sold as long as both of them live, for the vision concerning the whole crowd will not be reversed. Because of their sins, not one of them will preserve his life.",
    Ind:"Sebab si penjual tidak akan kembali kepada jualannya, kalaupun mereka masih di tengah-tengah orang hidup, karena kehangatan murka tertimpa atas segala kegemparan mereka dan tidak dapat ditahan lagi, dan seorangpun tidak dapat mempertahankan hidupnya oleh karena kesalahannya."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:14, Page:1,
    Kor:"그들이 나팔을 불고 모든 장비를 갖춘다 하여도, 전쟁에 나갈 사람이 아무도 없는 것은, 내 진노가 이 땅의 모든 무리에게 미쳤기 때문이다.\"",
    Chn:"「他们已经吹角，预备齐全，却无一人出战，因为我的烈怒临到他们众人身上。",
    Eng:"Though they blow the trumpet and get everything ready, no one will go into battle, for my wrath is upon the whole crowd.",
    Ind:"Tiuplah sangkakala dan sediakanlah segala sesuatu! Tetapi seorangpun tidak maju berperang, sebab kehangatan murka-Ku tertimpa atas segala kegemparan mereka."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:15, Page:1,
    Kor:"<이스라엘이 받는 형벌> \"거리에는 전쟁이 있고, 집 안에는 전염병과 기근이 있다. 들녘에 있는 사람은 칼에 찔려 죽고, 성읍 안에 있는 사람은 기근과 전염병으로 죽는다.",
    Chn:"在外有刀剑；在内有瘟疫、饥荒。在田野的，必遭刀剑而死；在城中的，必有饥荒、瘟疫吞灭他。",
    Eng:"\"Outside is the sword, inside are plague and famine; those in the country will die by the sword, and those in the city will be devoured by famine and plague.",
    Ind:"Pedang ada di luar kota, sampar dan kelaparan ada di dalam. Barangsiapa yang di luar kota akan mati karena pedang, dan barangsiapa yang di dalam kota akan binasa oleh kelaparan dan sampar."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:16, Page:1,
    Kor:"더러는 살아 남아서, 계곡에서 놀란 비둘기처럼 산으로 피하겠지만, 저지른 죄를 생각하며 슬피 울 것이다.",
    Chn:"其中所逃脱的就必逃脱，各人因自己的罪孽在山上发出悲声，好像谷中的鸽子哀鸣。",
    Eng:"All who survive and escape will be in the mountains, moaning like doves of the valleys, each because of his sins.",
    Ind:"Dan kalaupun ada yang terluput dari antara mereka, mereka akan tinggal di gunung-gunung seperti burung perkutut di lembah-lembah, semuanya mengerang, masing-masing karena kesalahannya sendiri."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:17, Page:1,
    Kor:"사람들은 모두 손에 맥이 풀리고, 무릎을 떨 것이다.",
    Chn:"手都发软，膝弱如水。",
    Eng:"Every hand will go limp, and every knee will become as weak as water.",
    Ind:"Semua tangan terkulai dan semua orang terkencing ketakutan."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:18, Page:1,
    Kor:"굵은 베 옷을 입고, 두려워서 온 몸을 떨 것이다. 모든 얼굴에는 부끄러움이 가득할 것이요, 모든 머리는 대머리가 될 것이다.",
    Chn:"要用麻布束腰，被战兢所盖；各人脸上羞愧，头上光秃。",
    Eng:"They will put on sackcloth and be clothed with terror. Their faces will be covered with shame and their heads will be shaved.",
    Ind:"Mereka akan mengenakan kain kabung, kekejutan akan meliputi mereka, semuanya akan kehilangan muka dan semua kepala akan digundul sebagai tanda perkabungan."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:19, Page:1,
    Kor:"그들은 은을 길거리에 내던질 것이며, 금을 오물 보듯 할 것이다. 내가 진노하는 날에, 은과 금이 그들을 건져 줄 수 없을 것이다. 은과 금이 그들의 마음을 흡족하게 못하고, 허기진 배를 채워 주지 못할 것이다. 오히려 은과 금은 그들을 걸어서 넘어뜨려, 죄를 짓게 하였을 뿐이다.",
    Chn:"他们要将银子抛在街上，金子看如污秽之物。当耶和华发怒的日子，他们的金银不能救他们，不能使心里知足，也不能使肚腹饱满，因为这金银作了他们罪孽的绊脚石。",
    Eng:"They will throw their silver into the streets, and their gold will be an unclean thing. Their silver and gold will not be able to save them in the day of the LORD'S wrath. They will not satisfy their hunger or fill their stomachs with it, for it has made them stumble into sin.",
    Ind:"Perak mereka akan dicampakkan ke luar dan emas mereka akan dianggap cemar. Emas dan peraknya tidak akan dapat menyelamatkan mereka pada hari kemurkaan TUHAN. Mereka tidak akan kenyang karenanya dan perut mereka tidak akan terisi dengannya. Sebab hal itu menjadi batu sandungan, yang menjatuhkan mereka ke dalam kesalahan."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:20, Page:1,
    Kor:"그들이 자랑하던 아름다운 보석으로, 역겹고도 보기 싫은 우상들을 만들었으므로, 내가 보석을 오물이 되게 하겠다.",
    Chn:"论到耶和华妆饰华美的殿，他建立得威严，他们却在其中制造可憎可厌的偶像，所以这殿我使他们看如污秽之物。",
    Eng:"They were proud of their beautiful jewelry and used it to make their detestable idols and vile images. Therefore I will turn these into an unclean thing for them.",
    Ind:"Mereka menghiasi dirinya dengan emas dan peraknya dan kepermaian perhiasan ini membawa mereka dalam kecongkakan. Dari emas dan perak itu mereka membuat patung-patungnya yang keji dan dewa-dewanya yang menjijikkan; oleh sebab itu Aku akan menjadikan emas dan peraknya cemar bagi mereka."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:21, Page:1,
    Kor:"또 내가 그 보석을 외국 사람에게 넘겨 주어 약탈하게 하고, 세상의 악인들에게 넘겨 주어 약탈하고 더럽히게 하겠다.",
    Chn:"我必将这殿交付外邦人为掠物，交付地上的恶人为掳物；他们也必亵渎这殿。",
    Eng:"I will hand it all over as plunder to foreigners and as loot to the wicked of the earth, and they will defile it.",
    Ind:"Aku akan menyerahkannya menjadi rampasan di tangan orang-orang asing dan menjadi jarahan bagi orang-orang fasik di bumi ini, dan mereka ini akan menajiskannya."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:22, Page:1,
    Kor:"내가 간섭하지 않을 것이니, 외국 사람들이 나의 c은밀한 성소를 더럽히고, 도둑들이 그 곳에 들어가서 약탈할 것이다. (c 또는 '보물을 쌓아 둔 곳을')",
    Chn:"我必转脸不顾以色列人，他们亵渎我隐密之所，强盗也必进去亵渎。",
    Eng:"I will turn my face away from them, and they will desecrate my treasured place; robbers will enter it and desecrate it.",
    Ind:"Aku akan memalingkan wajah-Ku dari pada mereka dan perampok-perampok akan menajiskan rumah-Ku yang berharga; mereka akan masuk ke dalamnya dan menajiskannya,"
  },
  {Bible:"Ezekiel", Chapter:7, Verse:23, Page:1,
    Kor:"너는 쇠사슬을 만들어라. 이 땅에 살육이 가득 차 있고, 이 도성에는 폭력이 가득 차 있기 때문이다.",
    Chn:"「要制造锁链；因为这地遍满流血的罪，城邑充满强暴的事。",
    Eng:"\"Prepare chains, because the land is full of bloodshed and the city is full of violence.",
    Ind:"serta memusnahkannya. Sebab negeri itu penuh hutang darah dan kota itu penuh kekerasan."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:24, Page:1,
    Kor:"나는 세상에서 가장 악한 이방 사람들을 데려다가 그들의 집들을 차지하게 하겠다. 강한 사람들의 교만을 꺾고, 그들의 성소들이 모두 더럽혀지게 하겠다.",
    Chn:"所以，我必使列国中最恶的人来占据他们的房屋；我必使强暴人的骄傲止息，他们的圣所都要被亵渎。",
    Eng:"I will bring the most wicked of the nations to take possession of their houses; I will put an end to the pride of the mighty, and their sanctuaries will be desecrated.",
    Ind:"Aku akan membiarkan datang bangsa-bangsa yang paling kejam dan bangsa-bangsa ini akan mengambil rumah-rumah mereka menjadi miliknya; Aku akan mengakhiri kecongkakan mereka, yang ditimbulkan kekuatan mereka itu, dan tempat-tempat kudus mereka akan dinajiskan."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:25, Page:1,
    Kor:"파멸이 이미 이르렀다. 그들이 평안을 찾지만, 전혀 없을 것이다.",
    Chn:"毁灭临近了；他们要求平安，却无平安可得。",
    Eng:"When terror comes, they will seek peace, but there will be none.",
    Ind:"Ketakutan datang, dan mereka mencari keselamatan, tetapi tidak ada."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:26, Page:1,
    Kor:"재앙에 재앙이 겹치고, 불길한 기별이 꼬리를 물 것이다. 그 때에는 사람들이 예언자에게 묵시를 구하여도 얻지 못할 것이며, 제사장에게는 가르쳐 줄 율법이 없어질 것이고, 장로들에게서는 지혜가 사라질 것이다.",
    Chn:"灾害加上灾害，风声接连风声；他们必向先知求异象，但祭司讲的律法、长老设的谋略都必断绝。",
    Eng:"Calamity upon calamity will come, and rumor upon rumor. They will try to get a vision from the prophet; the teaching of the law by the priest will be lost, as will the counsel of the elders.",
    Ind:"Bencana demi bencana akan datang, kabar demi kabar akan tersiar. Mereka akan menginginkan suatu penglihatan dari nabi, pengajaran hilang lenyap dari imam, dan nasihat dari tua-tua."
  },
  {Bible:"Ezekiel", Chapter:7, Verse:27, Page:1,
    Kor:"왕은 통곡하고, 지도자들은 절망에 빠지고, 이 땅의 백성은 무서워서 벌벌 떨 것이다. 내가 그들의 행실대로 그들에게 갚아 주고, 그들이 심판받아야 하는 그대로 그들을 심판하겠다. 그 때에야 그들이 비로소 내가 주인 줄 알게 될 것이다.\"",
    Chn:"君要悲哀，王要披凄凉为衣，国民的手都发颤。我必照他们的行为待他们，按他们应得的审判他们，他们就知道我是耶和华。」",
    Eng:"The king will mourn, the prince will be clothed with despair, and the hands of the people of the land will tremble. I will deal with them according to their conduct, and by their own standards I will judge them. Then they will know that I am the LORD.\"",
    Ind:"Raja akan berkabung dan pemimpin akan diliputi kekagetan dan tangan seluruh penduduk negeri itu menjadi lemas ketakutan. Aku akan perbuat terhadap mereka selaras dengan tingkah lakunya dan Aku akan menghakimi mereka selaras dengan cara mereka menghakimi. Dan mereka akan mengetahui bahwa Akulah TUHAN.\""
  },
]);
