// 사도행전 7장 · Acts 7
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Acts",7,60);
BibleDB.add([
  {Bible:"Acts", Chapter:7, Verse:1, Page:1,
    Kor:"<스데반의 설교> 대제사장이 스데반에게 물었다. \"이것이 사실이오?\"",
    Chn:"大祭司就说：「这些事果然有吗？」",
    Eng:"Then the high priest asked him, \"Are these charges true?\"",
    Ind:"Kata Imam Besar: \"Benarkah demikian?\""
  },
  {Bible:"Acts", Chapter:7, Verse:2, Page:1,
    Kor:"스데반이 말하였다. \"부형 여러분, 내 말을 들어보십시오. 우리 조상 아브라함이 하란에 거주하기 전에, 아직 메소포타미아에 있을 때에, 영광의 하나님께서 그에게 나타나셔서 말씀하시기를",
    Chn:"司提反说：「诸位父兄请听！当日我们的祖宗亚伯拉罕在美索不达米亚还未住哈兰的时候，荣耀的　神向他显现，",
    Eng:"To this he replied: \"Brothers and fathers, listen to me! The God of glory appeared to our father Abraham while he was still in Mesopotamia, before he lived in Haran.",
    Ind:"Jawab Stefanus: \"Hai saudara-saudara dan bapa-bapa, dengarkanlah! Allah yang Mahamulia telah menampakkan diri-Nya kepada bapa leluhur kita Abraham, ketika ia masih di Mesopotamia, sebelum ia menetap di Haran,"
  },
  {Bible:"Acts", Chapter:7, Verse:3, Page:1,
    Kor:"a'너는 네 고향과 친척을 떠나서, 어디든지 내가 지시하는 땅으로 가거라' 하셨습니다.(a 창 12:1)",
    Chn:"对他说：『你要离开本地和亲族，往我所要指示你的地方去。』",
    Eng:"'Leave your country and your people,' God said, 'and go to the land I will show you.'",
    Ind:"dan berfirman kepadanya: Keluarlah dari negerimu dan dari sanak saudaramu dan pergilah ke negeri yang akan Kutunjukkan kepadamu."
  },
  {Bible:"Acts", Chapter:7, Verse:4, Page:1,
    Kor:"그래서 그는 갈대아 사람들의 땅을 떠나 하란으로 가서, 거기서 살았습니다. 그의 아버지가 죽은 뒤에, 하나님께서 그를 하란에서 지금 여러분이 사는 이 땅으로 옮기셨습니다.",
    Chn:"他就离开迦勒底人之地，住在哈兰。他父亲死了以后，　神使他从那里搬到你们现在所住之地。",
    Eng:"\"So he left the land of the Chaldeans and settled in Haran. After the death of his father, God sent him to this land where you are now living.",
    Ind:"Maka keluarlah ia dari negeri orang Kasdim, lalu menetap di Haran. Dan setelah ayahnya meninggal, Allah menyuruh dia pindah dari situ ke tanah ini, tempat kamu diam sekarang;"
  },
  {Bible:"Acts", Chapter:7, Verse:5, Page:1,
    Kor:"그러나 하나님께서는 여기에서 유산으로 물려줄 손바닥만한 땅도 그에게 주지 않으셨습니다. 아브라함에게 자식이 없는데도, 하나님께서는 그와 그의 후손들에게 이 땅을 소유로 주시겠다고 약속하셨습니다.",
    Chn:"在这地方，　神并没有给他产业，连立足之地也没有给他；但应许要将这地赐给他和他的后裔为业；那时他还没有儿子。",
    Eng:"He gave him no inheritance here, not even a foot of ground. But God promised him that he and his descendants after him would possess the land, even though at that time Abraham had no child.",
    Ind:"dan di situ Allah tidak memberikan milik pusaka kepadanya, bahkan setapak tanahpun tidak, tetapi Ia berjanji akan memberikan tanah itu kepadanya menjadi kepunyaannya dan kepunyaan keturunannya, walaupun pada waktu itu ia tidak mempunyai anak."
  },
  {Bible:"Acts", Chapter:7, Verse:6, Page:1,
    Kor:"그리고 하나님께서는 아브라함에게 이렇게 말씀하셨습니다. b'네 후손들은 외국 땅에서 나그네가 되어 사백 년 동안 종살이를 하고 학대를 받을 것이다.'(b 창 15:13, 14)",
    Chn:"神说：『他的后裔必寄居外邦，那里的人要叫他们作奴仆，苦待他们四百年。』",
    Eng:"God spoke to him in this way: 'Your descendants will be strangers in a country not their own, and they will be enslaved and mistreated four hundred years.",
    Ind:"Beginilah firman Allah, yaitu bahwa keturunannya akan menjadi pendatang di negeri asing dan bahwa mereka akan diperbudak dan dianiaya empat ratus tahun lamanya."
  },
  {Bible:"Acts", Chapter:7, Verse:7, Page:1,
    Kor:"또 하나님께서 말씀하시기를 '그러나 그들을 종으로 부리는 그 민족을 내가 심판하겠고, 그 뒤에 그들은 빠져 나와서, 이곳에서 나를 예배할 것이다' 하셨습니다.",
    Chn:"神又说：『使他们作奴仆的那国，我要惩罚。以后他们要出来，在这地方事奉我。』",
    Eng:"But I will punish the nation they serve as slaves,' God said, 'and afterward they will come out of that country and worship me in this place.'",
    Ind:"Tetapi bangsa yang akan memperbudak mereka itu akan Kuhukum, firman Allah, dan sesudah itu mereka akan keluar dari situ dan beribadah kepada-Ku di tempat ini."
  },
  {Bible:"Acts", Chapter:7, Verse:8, Page:1,
    Kor:"그리고 하나님께서는 아브라함에게 할례의 언약을 주셨습니다. 그래서 아브라함은 이삭을 낳고, 여드레째 되는 날에 그에게 할례를 행하고, 이삭은 야곱에게 또 야곱은 열두 족장에게 할례를 행하였습니다.",
    Chn:"神又赐他割礼的约。于是亚伯拉罕生了以撒，第八日给他行了割礼。以撒生雅各；雅各生十二位先祖。",
    Eng:"Then he gave Abraham the covenant of circumcision. And Abraham became the father of Isaac and circumcised him eight days after his birth. Later Isaac became the father of Jacob, and Jacob became the father of the twelve patriarchs.",
    Ind:"Lalu Allah memberikan kepadanya perjanjian sunat; dan demikianlah Abraham memperanakkan Ishak, lalu menyunatkannya pada hari yang kedelapan; dan Ishak memperanakkan Yakub, dan Yakub memperanakkan kedua belas bapa leluhur kita."
  },
  {Bible:"Acts", Chapter:7, Verse:9, Page:1,
    Kor:"○그런데 그 족장들은 요셉을 시기하여, 이집트에다 팔아 넘겼습니다. 그러나 하나님께서 그와 함께 하셔서,",
    Chn:"「先祖嫉妒约瑟，把他卖到埃及去；　神却与他同在，",
    Eng:"\"Because the patriarchs were jealous of Joseph, they sold him as a slave into Egypt. But God was with him",
    Ind:"Karena iri hati, bapa-bapa leluhur kita menjual Yusuf ke tanah Mesir, tetapi Allah menyertai dia,"
  },
  {Bible:"Acts", Chapter:7, Verse:10, Page:1,
    Kor:"모든 환난에서 그를 건져내시고, 그에게 은총과 지혜를 주셔서, 이집트의 바로 왕에게 총애를 받게 하셨습니다. 바로는 그를 총리로 세워서, 이집트와 자기 온 집을 다스리게 하였습니다.",
    Chn:"救他脱离一切苦难，又使他在埃及王法老面前得恩典，有智慧。法老就派他作埃及国的宰相兼管全家。",
    Eng:"and rescued him from all his troubles. He gave Joseph wisdom and enabled him to gain the goodwill of Pharaoh king of Egypt; so he made him ruler over Egypt and all his palace.",
    Ind:"dan melepaskannya dari segala penindasan serta menganugerahkan kepadanya kasih karunia dan hikmat, ketika ia menghadap Firaun, raja Mesir. Firaun mengangkatnya menjadi kuasa atas tanah Mesir dan atas seluruh istananya."
  },
  {Bible:"Acts", Chapter:7, Verse:11, Page:1,
    Kor:"그 때에 이집트와 가나안 온 지역에 흉년이 들어서 재난이 극심하였는데, 우리 조상들은 먹을거리를 구할 수 없었습니다.",
    Chn:"后来埃及和迦南全地遭遇饥荒，大受艰难，我们的祖宗就绝了粮。",
    Eng:"\"Then a famine struck all Egypt and Canaan, bringing great suffering, and our fathers could not find food.",
    Ind:"Maka datanglah bahaya kelaparan menimpa seluruh tanah Mesir dan tanah Kanaan serta penderitaan yang besar, sehingga nenek moyang kita tidak mendapat makanan."
  },
  {Bible:"Acts", Chapter:7, Verse:12, Page:1,
    Kor:"야곱이 이집트에 곡식이 있다는 소문을 듣고서, 우리 조상들을 처음으로 거기로 보냈습니다.",
    Chn:"雅各听见在埃及有粮，就打发我们的祖宗初次往那里去。",
    Eng:"When Jacob heard that there was grain in Egypt, he sent our fathers on their first visit.",
    Ind:"Tetapi ketika Yakub mendengar, bahwa di tanah Mesir ada gandum, ia menyuruh nenek moyang kita ke sana. Itulah kunjungan mereka yang pertama;"
  },
  {Bible:"Acts", Chapter:7, Verse:13, Page:1,
    Kor:"그들이 두 번째 갔을 때에, 요셉이 그의 형들에게 자기를 알리니, 이 일로 말미암아 요셉의 가족 관계가 바로에게 알려졌습니다.",
    Chn:"第二次约瑟与弟兄们相认，他的亲族也被法老知道了。",
    Eng:"On their second visit, Joseph told his brothers who he was, and Pharaoh learned about Joseph's family.",
    Ind:"pada kunjungan mereka yang kedua Yusuf memperkenalkan dirinya kepada saudara-saudaranya, lalu ketahuanlah asal-usul Yusuf kepada Firaun."
  },
  {Bible:"Acts", Chapter:7, Verse:14, Page:1,
    Kor:"요셉이 사람을 보내서, 그의 아버지 야곱과 모든 친족 일흔다섯 사람을 모셔 오게 하였습니다.",
    Chn:"约瑟就打发弟兄请父亲雅各和全家七十五个人都来。",
    Eng:"After this, Joseph sent for his father Jacob and his whole family, seventy-five in all.",
    Ind:"Kemudian Yusuf menyuruh menjemput Yakub, ayahnya, dan semua sanak saudaranya, tujuh puluh lima jiwa banyaknya."
  },
  {Bible:"Acts", Chapter:7, Verse:15, Page:1,
    Kor:"야곱이 이집트로 내려가서, 그도 거기서 살다가 죽고, 우리 조상들도 살다가 죽었습니다.",
    Chn:"于是雅各下了埃及，后来他和我们的祖宗都死在那里；",
    Eng:"Then Jacob went down to Egypt, where he and our fathers died.",
    Ind:"Lalu pergilah Yakub ke tanah Mesir. Di situ ia meninggal, ia dan nenek moyang kita;"
  },
  {Bible:"Acts", Chapter:7, Verse:16, Page:1,
    Kor:"그리고 그들의 유해는 나중에 세겜으로 옮겨서, 전에 아브라함이 세겜의 하몰 자손에게서 은을 주고 산 무덤에 묻었습니다.",
    Chn:"又被带到示剑，葬于亚伯拉罕在示剑用银子从哈抹子孙买来的坟墓里。",
    Eng:"Their bodies were brought back to Shechem and placed in the tomb that Abraham had bought from the sons of Hamor at Shechem for a certain sum of money.",
    Ind:"mayat mereka dipindahkan ke Sikhem dan diletakkan di dalam kuburan yang telah dibeli Abraham dengan sejumlah uang perak dari anak-anak Hemor di Sikhem."
  },
  {Bible:"Acts", Chapter:7, Verse:17, Page:1,
    Kor:"○하나님께서 아브라함에게 약속하신 때가 가까이 왔을 때에, 그 백성은 이집트에서 늘어나고 불어났습니다.",
    Chn:"「及至　神应许亚伯拉罕的日期将到，以色列民在埃及兴盛众多，",
    Eng:"\"As the time drew near for God to fulfill his promise to Abraham, the number of our people in Egypt greatly increased.",
    Ind:"Tetapi makin dekat genapnya janji yang diberikan Allah kepada Abraham, makin bertambah banyaklah bangsa itu di Mesir,"
  },
  {Bible:"Acts", Chapter:7, Verse:18, Page:1,
    Kor:"마침내, 요셉을 알지 못하는 다른 임금이 이집트의 왕위에 올랐습니다.",
    Chn:"直到有不晓得约瑟的新王兴起。",
    Eng:"Then another king, who knew nothing about Joseph, became ruler of Egypt.",
    Ind:"sampai bangkit seorang raja lain memerintah tanah Mesir, seorang yang tidak mengenal Yusuf."
  },
  {Bible:"Acts", Chapter:7, Verse:19, Page:1,
    Kor:"이 임금이 우리 겨레에게 교활한 정책을 써서, 우리 조상들을 학대하되, 갓난아기들을 내다 버리게 하여서, 살아남지 못하게 하였습니다.",
    Chn:"他用诡计待我们的宗族，苦害我们的祖宗，叫他们丢弃婴孩，使婴孩不能存活。",
    Eng:"He dealt treacherously with our people and oppressed our forefathers by forcing them to throw out their newborn babies so that they would die.",
    Ind:"Raja itu mempergunakan tipu daya terhadap bangsa kita dan menganiaya nenek moyang kita serta menyuruh membuang bayi mereka, supaya bangsa kita itu jangan berkembang."
  },
  {Bible:"Acts", Chapter:7, Verse:20, Page:1,
    Kor:"바로 이 때에 모세가 태어났습니다. 그는 용모가 아주 잘 생긴 아기였습니다. 그의 부모는 그를 석 달 동안 몰래 집에서 길렀습니다.",
    Chn:"那时，摩西生下来，俊美非凡，在他父亲家里抚养了三个月。",
    Eng:"\"At that time Moses was born, and he was no ordinary child. For three months he was cared for in his father's house.",
    Ind:"Pada waktu itulah Musa lahir dan ia elok di mata Allah. Tiga bulan lamanya ia diasuh di rumah ayahnya."
  },
  {Bible:"Acts", Chapter:7, Verse:21, Page:1,
    Kor:"그 뒤에 어쩔 수 없어서 내다 버렸는데, 바로의 딸이 데려다가 자기 아들로 삼아서 길렀습니다.",
    Chn:"他被丢弃的时候，法老的女儿拾了去，养为自己的儿子。",
    Eng:"When he was placed outside, Pharaoh's daughter took him and brought him up as her own son.",
    Ind:"Lalu ia dibuang, tetapi puteri Firaun memungutnya dan menyuruh mengasuhnya seperti anaknya sendiri."
  },
  {Bible:"Acts", Chapter:7, Verse:22, Page:1,
    Kor:"모세는 이집트 사람의 모든 지혜를 배워서, 그 하는 말과 하는 일에 능력이 있었습니다.",
    Chn:"摩西学了埃及人一切的学问，说话行事都有才能。",
    Eng:"Moses was educated in all the wisdom of the Egyptians and was powerful in speech and action.",
    Ind:"Dan Musa dididik dalam segala hikmat orang Mesir, dan ia berkuasa dalam perkataan dan perbuatannya."
  },
  {Bible:"Acts", Chapter:7, Verse:23, Page:1,
    Kor:"○모세가 마흔 살이 되었을 때에, 그의 마음에 c자기 동족인 이스라엘 사람의 사정을 살펴 볼 생각이 났습니다.(c 그, '그의 형제들인 이스라엘 자손')",
    Chn:"「他将到四十岁，心中起意去看望他的弟兄以色列人；",
    Eng:"\"When Moses was forty years old, he decided to visit his fellow Israelites.",
    Ind:"Pada waktu ia berumur empat puluh tahun, timbullah keinginan dalam hatinya untuk mengunjungi saudara-saudaranya, yaitu orang-orang Israel."
  },
  {Bible:"Acts", Chapter:7, Verse:24, Page:1,
    Kor:"어느 날 그는 자기 동족 한 사람이 억울한 일을 당하는 것을 보고, 그의 편을 들어, 이집트 사람을 때려 죽여서, 압박받는 사람의 원한을 풀어 주었습니다.",
    Chn:"到了那里，见他们一个人受冤屈，就护庇他，为那受欺压的人报仇，打死了那埃及人。",
    Eng:"He saw one of them being mistreated by an Egyptian, so he went to his defense and avenged him by killing the Egyptian.",
    Ind:"Ketika itu ia melihat seorang dianiaya oleh seorang Mesir, lalu ia menolong dan membela orang itu dengan membunuh orang Mesir itu."
  },
  {Bible:"Acts", Chapter:7, Verse:25, Page:1,
    Kor:"그는 <자기> d동포가 하나님이 자기 손을 빌어서 그들을 구원하여 주신다는 것을 깨달을 것으로 생각하였는데, 그들은 깨닫지 못하였습니다.(d 그, '형제들')",
    Chn:"他以为弟兄必明白　神是借他的手搭救他们；他们却不明白。",
    Eng:"Moses thought that his own people would realize that God was using him to rescue them, but they did not.",
    Ind:"Pada sangkanya saudara-saudaranya akan mengerti, bahwa Allah memakai dia untuk menyelamatkan mereka, tetapi mereka tidak mengerti."
  },
  {Bible:"Acts", Chapter:7, Verse:26, Page:1,
    Kor:"이튿날 모세는 동족들끼리 서로 싸우는 자리에 나타나서, 그들을 화해시키려고 하여 말하기를 '이 사람들아, 그대들은 한 형제가 아닌가? 그런데 어찌하여 서로 해하는가?' 하였습니다.",
    Chn:"第二天，遇见两个以色列人争斗，就劝他们和睦，说：『你们二位是弟兄，为什么彼此欺负呢？』",
    Eng:"The next day Moses came upon two Israelites who were fighting. He tried to reconcile them by saying, 'Men, you are brothers; why do you want to hurt each other?'",
    Ind:"Pada keesokan harinya ia muncul pula ketika dua orang Israel sedang berkelahi, lalu ia berusaha mendamaikan mereka, katanya: Saudara-saudara! Bukankah kamu ini bersaudara? Mengapakah kamu saling menganiaya?"
  },
  {Bible:"Acts", Chapter:7, Verse:27, Page:1,
    Kor:"그런데 동료에게 해를 입히던 사람이 모세를 떠밀고서 이렇게 말하였습니다. e'누가 너를 우리의 지도자와 재판관으로 세웠느냐?(e 출 2:14)",
    Chn:"那欺负邻舍的把他推开，说：『谁立你作我们的首领和审判官呢？",
    Eng:"\"But the man who was mistreating the other pushed Moses aside and said, 'Who made you ruler and judge over us?",
    Ind:"Tetapi orang yang berbuat salah kepada temannya itu menolak Musa dan berkata: Siapakah yang mengangkat engkau menjadi pemimpin dan hakim atas kami?"
  },
  {Bible:"Acts", Chapter:7, Verse:28, Page:1,
    Kor:"어제는 이집트 사람을 죽이더니, 오늘은 또 나를 그렇게 죽이려 하는가?'",
    Chn:"难道你要杀我，像昨天杀那埃及人吗？』",
    Eng:"Do you want to kill me as you killed the Egyptian yesterday?'",
    Ind:"Apakah engkau bermaksud membunuh aku, sama seperti kemarin engkau membunuh orang Mesir itu?"
  },
  {Bible:"Acts", Chapter:7, Verse:29, Page:1,
    Kor:"이 말을 듣고서, 모세는 도망하여, 미디안 땅에서 나그네가 되었습니다. 거기서 그는 아들 둘을 낳았습니다.",
    Chn:"摩西听见这话就逃走了，寄居于米甸；在那里生了两个儿子。",
    Eng:"When Moses heard this, he fled to Midian, where he settled as a foreigner and had two sons.",
    Ind:"Mendengar perkataan itu, larilah Musa dan hidup sebagai pendatang di tanah Midian. Di situ ia memperanakkan dua orang anak laki-laki."
  },
  {Bible:"Acts", Chapter:7, Verse:30, Page:1,
    Kor:"○사십 년이 지난 뒤에, 천사가 시내 산 광야에서 가시나무 떨기 불길 속에서 모세에게 나타났습니다.",
    Chn:"「过了四十年，在西奈山的旷野，有一位天使从荆棘火焰中向摩西显现。",
    Eng:"\"After forty years had passed, an angel appeared to Moses in the flames of a burning bush in the desert near Mount Sinai.",
    Ind:"Dan sesudah empat puluh tahun tampaklah kepadanya seorang malaikat di padang gurun gunung Sinai di dalam nyala api yang keluar dari semak duri."
  },
  {Bible:"Acts", Chapter:7, Verse:31, Page:1,
    Kor:"모세가 이 광경을 보고 기이하게 여겨서, 자세히 보려고 가까이 가는데, 주님의 음성이 들렸습니다.",
    Chn:"摩西见了那异象，便觉希奇，正进前观看的时候，有主的声音说：",
    Eng:"When he saw this, he was amazed at the sight. As he went over to look more closely, he heard the Lord's voice:",
    Ind:"Musa heran tentang penglihatan itu, dan ketika ia pergi ke situ untuk melihatnya dari dekat, datanglah suara Tuhan kepadanya:"
  },
  {Bible:"Acts", Chapter:7, Verse:32, Page:1,
    Kor:"f'나는 네 조상들의 하나님, 곧 아브라함의 하나님, 이삭의 하나님, 야곱의 하나님이다.' 모세는 두려워서 감히 바라보지 못하였습니다.(f 출 3:6)",
    Chn:"『我是你列祖的　神，就是亚伯拉罕的　神，以撒的　神，雅各的　神。』摩西战战兢兢，不敢观看。",
    Eng:"'I am the God of your fathers, the God of Abraham, Isaac and Jacob.' Moses trembled with fear and did not dare to look.",
    Ind:"Akulah Allah nenek moyangmu, Allah Abraham, Ishak dan Yakub. Maka gemetarlah Musa, dan ia tidak berani lagi melihatnya."
  },
  {Bible:"Acts", Chapter:7, Verse:33, Page:1,
    Kor:"그 때에 주님께서 모세에게 말씀하셨습니다. g'네 신발을 벗어라. 네가 서 있는 곳은 거룩한 땅이다.(g 출 3:5, 7, 8, 10)",
    Chn:"主对他说：『把你脚上的鞋脱下来，因为你所站之地是圣地。",
    Eng:"\"Then the Lord said to him, 'Take off your sandals; the place where you are standing is holy ground.",
    Ind:"Lalu firman Allah kepadanya: Tanggalkanlah kasutmu dari kakimu, sebab tempat, di mana engkau berdiri itu, adalah tanah yang kudus."
  },
  {Bible:"Acts", Chapter:7, Verse:34, Page:1,
    Kor:"나는 이집트에 있는 내 백성이 학대받는 것을 분명히 보았고, 또 그들이 신음하는 소리를 들었다. 그러므로 나는 그들을 구원하려고 내려왔다. 이제 내가 너를 이집트로 보내니, 너는 가거라.'",
    Chn:"我的百姓在埃及所受的困苦，我实在看见了，他们悲叹的声音，我也听见了。我下来要救他们。你来！我要差你往埃及去。』",
    Eng:"I have indeed seen the oppression of my people in Egypt. I have heard their groaning and have come down to set them free. Now come, I will send you back to Egypt.'",
    Ind:"Aku telah memperhatikan dengan sungguh kesengsaraan umat-Ku di tanah Mesir dan Aku telah mendengar keluh kesah mereka, dan Aku telah turun untuk melepaskan mereka; karena itu marilah, engkau akan Kuutus ke tanah Mesir."
  },
  {Bible:"Acts", Chapter:7, Verse:35, Page:1,
    Kor:"이 모세로 말하면, 이스라엘 백성이 '누가 너를 우리의 지도자와 재판관으로 세웠느냐?' 하고 배척한 사람인데, 하나님께서는 바로 이 모세를 가시나무 떨기 속에 나타난 천사의 능한 손길을 붙여 지도자와 해방자로 세워서 그들에게로 보내셨습니다.",
    Chn:"这摩西就是百姓弃绝说『谁立你作我们的首领和审判官』的；　神却借那在荆棘中显现之使者的手差派他作首领、作救赎的。",
    Eng:"\"This is the same Moses whom they had rejected with the words, 'Who made you ruler and judge?' He was sent to be their ruler and deliverer by God himself, through the angel who appeared to him in the bush.",
    Ind:"Musa ini, yang telah mereka tolak, dengan mengatakan: Siapakah yang mengangkat engkau menjadi pemimpin dan hakim? --Musa ini juga telah diutus oleh Allah sebagai pemimpin dan penyelamat oleh malaikat, yang telah menampakkan diri kepadanya di semak duri itu."
  },
  {Bible:"Acts", Chapter:7, Verse:36, Page:1,
    Kor:"이 사람이 이집트 땅과 홍해에서 놀라운 일과 표징을 행하여 그들을 이끌어냈으며, 사십 년 동안 광야에서도 그러한 일을 행하였습니다.",
    Chn:"这人领百姓出来，在埃及，在红海，在旷野，四十年间行了奇事神迹。",
    Eng:"He led them out of Egypt and did wonders and miraculous signs in Egypt, at the Red Sea and for forty years in the desert.",
    Ind:"Dialah yang membawa mereka keluar dengan mengadakan mujizat-mujizat dan tanda-tanda di tanah Mesir, di Laut Merah dan di padang gurun, empat puluh tahun lamanya."
  },
  {Bible:"Acts", Chapter:7, Verse:37, Page:1,
    Kor:"h'하나님께서는 i나를 세우신 것과 같이, 너희를 위하여 너희의 d동족 가운데서 한 예언자를 세워 주실 것이다' 하고 이스라엘 백성에게 말한 사람이 바로 이 모세입니다.(h 신 18:15 i '나와 같은'으로 번역해서 '한 예언자'에 연결할 수도 있음 d 그, '형제들')",
    Chn:"那曾对以色列人说『　神要从你们弟兄中间给你们兴起一位先知像我』的，就是这位摩西。",
    Eng:"\"This is that Moses who told the Israelites, 'God will send you a prophet like me from your own people.'",
    Ind:"Musa ini pulalah yang berkata kepada orang Israel: Seorang nabi seperti aku ini akan dibangkitkan Allah bagimu dari antara saudara-saudaramu."
  },
  {Bible:"Acts", Chapter:7, Verse:38, Page:1,
    Kor:"이 사람은, 이스라엘 백성이 광야에서 회중으로 모여 있을 때에, 시내 산에서 그에게 말하는 천사와 우리 조상들 사이에 중개자가 되어서, 산 말씀을 받아서 j우리에게 전해 준 사람입니다.(j 다른 고대 사본들에는 '여러분에게')",
    Chn:"这人曾在旷野会中和西奈山上，与那对他说话的天使同在，又与我们的祖宗同在，并且领受活泼的圣言传给我们。",
    Eng:"He was in the assembly in the desert, with the angel who spoke to him on Mount Sinai, and with our fathers; and he received living words to pass on to us.",
    Ind:"Musa inilah yang menjadi pengantara dalam sidang jemaah di padang gurun di antara malaikat yang berfirman kepadanya di gunung Sinai dan nenek moyang kita; dan dialah yang menerima firman-firman yang hidup untuk menyampaikannya kepada kamu."
  },
  {Bible:"Acts", Chapter:7, Verse:39, Page:1,
    Kor:"그러나 우리 조상들은 그의 말을 들으려고 하지 않았고, 그를 제쳐놓고서 이집트로 돌아가고 싶어하였습니다.",
    Chn:"我们的祖宗不肯听从，反弃绝他，心里归向埃及，",
    Eng:"\"But our fathers refused to obey him. Instead, they rejected him and in their hearts turned back to Egypt.",
    Ind:"Tetapi nenek moyang kita tidak mau taat kepadanya, malahan mereka menolaknya. Dalam hati mereka ingin kembali ke tanah Mesir."
  },
  {Bible:"Acts", Chapter:7, Verse:40, Page:1,
    Kor:"그래서 그들은 아론에게 말하였습니다. k'우리를 인도할 신들을 우리에게 만들어 주십시오. 이집트 땅에서 우리를 이끌어 내온 그 모세가 어떻게 되었는지, 우리는 도무지 모르겠습니다.'(k 출 32:1)",
    Chn:"对亚伦说：『你且为我们造些神像，在我们前面引路；因为领我们出埃及地的那个摩西，我们不知道他遭了什么事。』",
    Eng:"They told Aaron, 'Make us gods who will go before us. As for this fellow Moses who led us out of Egypt--we don't know what has happened to him!'",
    Ind:"Kepada Harun mereka berkata: Buatlah untuk kami beberapa allah yang akan berjalan di depan kami, sebab Musa ini yang telah memimpin kami keluar dari tanah Mesir--kami tidak tahu apa yang telah terjadi dengan dia."
  },
  {Bible:"Acts", Chapter:7, Verse:41, Page:1,
    Kor:"그 때에 그들은 송아지를 만들어 놓고서 그 우상에게 희생제물을 바치고, 자기들의 손으로 만든 것을 두고 즐거워하였습니다.",
    Chn:"那时，他们造了一个牛犊，又拿祭物献给那像，欢喜自己手中的工作。",
    Eng:"That was the time they made an idol in the form of a calf. They brought sacrifices to it and held a celebration in honor of what their hands had made.",
    Ind:"Lalu pada waktu itu mereka membuat sebuah anak lembu dan mempersembahkan persembahan kepada berhala itu dan mereka bersukacita tentang apa yang dibuat sendiri oleh mereka."
  },
  {Bible:"Acts", Chapter:7, Verse:42, Page:1,
    Kor:"그래서 하나님께서는 그들에게서 얼굴을 돌리시고, 그들을 내버려 두셔서, 하늘의 별들을 섬기게 하셨습니다. 이것은 예언자들의 책에 기록된 바와 같습니다.  l'이스라엘 가문아, 너희가 사십 년 동안 광야에 있을 때에, 희생물과 제물을 내게 바친 일이 있었느냐? (l 암 5:25-27(칠십인역))",
    Chn:"神就转脸不顾，任凭他们事奉天上的日月星辰，正如先知书上所写的说： 以色列家啊， 你们四十年间在旷野， 岂是将牺牲和祭物献给我吗？",
    Eng:"But God turned away and gave them over to the worship of the heavenly bodies. This agrees with what is written in the book of the prophets: \"'Did you bring me sacrifices and offerings forty years in the desert, O house of Israel?",
    Ind:"Maka berpalinglah Allah dari mereka dan membiarkan mereka beribadah kepada bala tentara langit, seperti yang tertulis dalam kitab nabi-nabi: Apakah kamu mempersembahkan kepada-Ku korban sembelihan dan persembahan selama empat puluh tahun di padang gurun itu, hai kaum Israel?"
  },
  {Bible:"Acts", Chapter:7, Verse:43, Page:1,
    Kor:"너희는 몰렉 신의 장막과 레판 신의 별을 받들었다. 그것들은 너희가 경배하려고 만든 형상들이 아니더냐? 그러므로 나는 너희를 바빌론 저쪽으로 옮겨 버리겠다.'",
    Chn:"你们抬着摩洛的帐幕和理番神的星， 就是你们所造为要敬拜的像。 因此，我要把你们迁到巴比伦外去。",
    Eng:"You have lifted up the shrine of Molech and the star of your god Rephan, the idols you made to worship. Therefore I will send you into exile' beyond Babylon.",
    Ind:"Tidak pernah, malahan kamu mengusung kemah Molokh dan bintang dewa Refan, patung-patung yang kamu buat itu untuk disembah. Maka Aku akan membawa kamu ke dalam pembuangan, sampai di seberang sana Babel."
  },
  {Bible:"Acts", Chapter:7, Verse:44, Page:1,
    Kor:"○우리 조상들이 광야에 살 때에, 그들에게 증거의 장막이 있었습니다. 그것은 모세에게 말씀하시는 분이 지시하신 대로 만든 것인데, 모세가 본 모형을 따라 만들었습니다.",
    Chn:"「我们的祖宗在旷野，有法柜的帐幕，是　神吩咐摩西叫他照所看见的样式做的。",
    Eng:"\"Our forefathers had the tabernacle of the Testimony with them in the desert. It had been made as God directed Moses, according to the pattern he had seen.",
    Ind:"Kemah Kesaksian ada pada nenek moyang kita di padang gurun, seperti yang diperintahkan Allah kepada Musa untuk membuatnya menurut contoh yang telah dilihatnya."
  },
  {Bible:"Acts", Chapter:7, Verse:45, Page:1,
    Kor:"우리 조상들은 이 장막을 물려받아서, 하나님께서 우리 조상들 앞에서 쫓아내신 이방 민족들의 땅을 차지할 때에, 여호수아와 함께 그것을 그 땅에 가지고 들어왔고, 다윗 시대까지 물려주었습니다.",
    Chn:"这帐幕，我们的祖宗相继承受。当　神在他们面前赶出外邦人去的时候，他们同约书亚把帐幕搬进承受为业之地，直存到大卫的日子。",
    Eng:"Having received the tabernacle, our fathers under Joshua brought it with them when they took the land from the nations God drove out before them. It remained in the land until the time of David,",
    Ind:"Kemah itu yang diterima nenek moyang kita dan yang dengan pimpinan Yosua dibawa masuk ke tanah ini, yaitu waktu tanah ini direbut dari bangsa-bangsa lain yang dihalau Allah dari depan nenek moyang kita; demikianlah sampai kepada zaman Daud."
  },
  {Bible:"Acts", Chapter:7, Verse:46, Page:1,
    Kor:"다윗은 하나님의 은총을 입은 사람이므로, m야곱의 집안을 위하여 하나님의 거처를 마련하게 해 달라고 간구하였습니다.(m 다른 고대 사본들에는 '야곱의 하나님을 위하여 그의 거처를')",
    Chn:"大卫在　神面前蒙恩，祈求为雅各的　神预备居所；",
    Eng:"who enjoyed God's favor and asked that he might provide a dwelling place for the God of Jacob.",
    Ind:"Daud telah mendapat kasih karunia di hadapan Allah dan ia memohon, supaya ia diperkenankan untuk mendirikan suatu tempat kediaman bagi Allah Yakub."
  },
  {Bible:"Acts", Chapter:7, Verse:47, Page:1,
    Kor:"그러나 야곱의 집안을 위하여 집을 지은 사람은 솔로몬이었습니다.",
    Chn:"却是所罗门为　神造成殿宇。",
    Eng:"But it was Solomon who built the house for him.",
    Ind:"Tetapi Salomolah yang mendirikan sebuah rumah untuk Allah."
  },
  {Bible:"Acts", Chapter:7, Verse:48, Page:1,
    Kor:"그런데 지극히 높으신 분께서는 사람의 손으로 지은 건물 안에 거하지 않으십니다. 그것은 예언자가 말하기를",
    Chn:"其实，至高者并不住人手所造的，就如先知所言：",
    Eng:"\"However, the Most High does not live in houses made by men. As the prophet says:",
    Ind:"Tetapi Yang Mahatinggi tidak diam di dalam apa yang dibuat oleh tangan manusia, seperti yang dikatakan oleh nabi:"
  },
  {Bible:"Acts", Chapter:7, Verse:49, Page:1,
    Kor:"n'주님께서 말씀하신다. 하늘은 나의 보좌요, 땅은 나의 발판이다. 너희가 나를 위해서 어떤 집을 지어 주겠으며 내가 쉴 만한 곳이 어디냐? (n 사 66:1, 2)",
    Chn:"主说：天是我的座位， 地是我的脚凳； 你们要为我造何等的殿宇？ 哪里是我安息的地方呢？",
    Eng:"\"'Heaven is my throne, and the earth is my footstool. What kind of house will you build for me? says the Lord. Or where will my resting place be?",
    Ind:"Langit adalah takhta-Ku, dan bumi adalah tumpuan kaki-Ku. Rumah apakah yang akan kamu dirikan bagi-Ku, demikian firman Tuhan, tempat apakah yang akan menjadi perhentian-Ku?"
  },
  {Bible:"Acts", Chapter:7, Verse:50, Page:1,
    Kor:"이 모든 것이 다 내 손으로 만든 것이 아니냐?' 한 것과 같습니다.",
    Chn:"这一切不都是我手所造的吗？",
    Eng:"Has not my hand made all these things?'",
    Ind:"Bukankah tangan-Ku sendiri yang membuat semuanya ini?"
  },
  {Bible:"Acts", Chapter:7, Verse:51, Page:1,
    Kor:"○목이 곧고 마음과 귀에 할례를 받지 못한 사람들이여, 당신들은 언제나 성령을 거역하고 있습니다. 당신네 조상들이 한 그대로 당신들도 하고 있습니다.",
    Chn:"「你们这硬着颈项、心与耳未受割礼的人，常时抗拒圣灵！你们的祖宗怎样，你们也怎样。",
    Eng:"\"You stiff-necked people, with uncircumcised hearts and ears! You are just like your fathers: You always resist the Holy Spirit!",
    Ind:"Hai orang-orang yang keras kepala dan yang tidak bersunat hati dan telinga, kamu selalu menentang Roh Kudus, sama seperti nenek moyangmu, demikian juga kamu."
  },
  {Bible:"Acts", Chapter:7, Verse:52, Page:1,
    Kor:"당신들의 조상들이 박해하지 않은 예언자가 한 사람이라도 있었습니까? 그들은 의인이 올 것을 예언한 사람들을 죽였고, 이제 당신들은 그 의인을 배반하고 죽였습니다.",
    Chn:"哪一个先知不是你们祖宗逼迫呢？他们也把预先传说那义者要来的人杀了；如今你们又把那义者卖了，杀了。",
    Eng:"Was there ever a prophet your fathers did not persecute? They even killed those who predicted the coming of the Righteous One. And now you have betrayed and murdered him--",
    Ind:"Siapakah dari nabi-nabi yang tidak dianiaya oleh nenek moyangmu? Bahkan mereka membunuh orang-orang yang lebih dahulu memberitakan tentang kedatangan Orang Benar, yang sekarang telah kamu khianati dan kamu bunuh."
  },
  {Bible:"Acts", Chapter:7, Verse:53, Page:1,
    Kor:"당신들은 천사들이 전하여 준 율법을 받기만 하고, 지키지는 않았습니다.\"",
    Chn:"你们受了天使所传的律法，竟不遵守。」",
    Eng:"you who have received the law that was put into effect through angels but have not obeyed it.\"",
    Ind:"Kamu telah menerima hukum Taurat yang disampaikan oleh malaikat-malaikat, akan tetapi kamu tidak menurutinya.\""
  },
  {Bible:"Acts", Chapter:7, Verse:54, Page:1,
    Kor:"<스데반의 순교> ○그들은 이 말을 듣고 격분해서, 스데반에게 이를 갈았다.",
    Chn:"众人听见这话就极其恼怒，向司提反咬牙切齿。",
    Eng:"When they heard this, they were furious and gnashed their teeth at him.",
    Ind:"Ketika anggota-anggota Mahkamah Agama itu mendengar semuanya itu, sangat tertusuk hati mereka. Maka mereka menyambutnya dengan gertakan gigi."
  },
  {Bible:"Acts", Chapter:7, Verse:55, Page:1,
    Kor:"그런데 스데반이 성령이 충만하여 하늘을 쳐다보니, 하나님의 영광이 보이고, 예수께서 하나님의 오른쪽에 서 계신 것이 보였다.",
    Chn:"但司提反被圣灵充满，定睛望天，看见　神的荣耀，又看见耶稣站在　神的右边，",
    Eng:"But Stephen, full of the Holy Spirit, looked up to heaven and saw the glory of God, and Jesus standing at the right hand of God.",
    Ind:"Tetapi Stefanus, yang penuh dengan Roh Kudus, menatap ke langit, lalu melihat kemuliaan Allah dan Yesus berdiri di sebelah kanan Allah."
  },
  {Bible:"Acts", Chapter:7, Verse:56, Page:1,
    Kor:"그래서 그는 \"보십시오, 하늘이 열려 있고, 하나님의 오른쪽에 o인자가 서 계신 것이 보입니다\" 하고 말하였다.(o '사람의 아들')",
    Chn:"就说：「我看见天开了，人子站在　神的右边。」",
    Eng:"\"Look,\" he said, \"I see heaven open and the Son of Man standing at the right hand of God.\"",
    Ind:"Lalu katanya: \"Sungguh, aku melihat langit terbuka dan Anak Manusia berdiri di sebelah kanan Allah.\""
  },
  {Bible:"Acts", Chapter:7, Verse:57, Page:1,
    Kor:"사람들은 귀를 막고, 큰 소리를 지르고서, 일제히 스데반에게 달려들어,",
    Chn:"众人大声喊叫，捂着耳朵，齐心拥上前去，",
    Eng:"At this they covered their ears and, yelling at the top of their voices, they all rushed at him,",
    Ind:"Maka berteriak-teriaklah mereka dan sambil menutup telinga serentak menyerbu dia."
  },
  {Bible:"Acts", Chapter:7, Verse:58, Page:1,
    Kor:"그를 성 바깥으로 끌어내서 돌로 쳤다. 증인들은 옷을 벗어서, 사울이라는 청년의 발 앞에 두었다.",
    Chn:"把他推到城外，用石头打他。作见证的人把衣裳放在一个少年人名叫扫罗的脚前。",
    Eng:"dragged him out of the city and began to stone him. Meanwhile, the witnesses laid their clothes at the feet of a young man named Saul.",
    Ind:"Mereka menyeret dia ke luar kota, lalu melemparinya. Dan saksi-saksi meletakkan jubah mereka di depan kaki seorang muda yang bernama Saulus."
  },
  {Bible:"Acts", Chapter:7, Verse:59, Page:1,
    Kor:"사람들이 스데반을 돌로 칠 때에, 스데반은 \"주 예수님, 내 영혼을 받아 주십시오\" 하고 부르짖었다.",
    Chn:"他们正用石头打的时候，司提反呼吁主说：「求主耶稣接收我的灵魂！」",
    Eng:"While they were stoning him, Stephen prayed, \"Lord Jesus, receive my spirit.\"",
    Ind:"Sedang mereka melemparinya Stefanus berdoa, katanya: \"Ya Tuhan Yesus, terimalah rohku.\""
  },
  {Bible:"Acts", Chapter:7, Verse:60, Page:1,
    Kor:"그리고 무릎을 꿇고서 큰 소리로 \"주님, 이 죄를 저 사람들에게 돌리지 마십시오\" 하고 외쳤다. 이 말을 하고 스데반은 p잠들었다.(p 또는 '죽었다')",
    Chn:"又跪下大声喊着说：「主啊，不要将这罪归于他们！」说了这话，就睡了。扫罗也喜悦他被害。",
    Eng:"Then he fell on his knees and cried out, \"Lord, do not hold this sin against them.\" When he had said this, he fell asleep.",
    Ind:"Sambil berlutut ia berseru dengan suara nyaring: \"Tuhan, janganlah tanggungkan dosa ini kepada mereka!\" Dan dengan perkataan itu meninggallah ia."
  },
]);
