// 사도행전 12장 · Acts 12
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Acts",12,25);
BibleDB.add([
  {Bible:"Acts", Chapter:12, Verse:1, Page:1,
    Kor:"<야고보의 순교와 베드로의 투옥> 이 무렵에 헤롯 왕이 손을 뻗쳐서, 교회에 속한 몇몇 사람을 해하였다.",
    Chn:"那时，希律王下手苦害教会中几个人，",
    Eng:"It was about this time that King Herod arrested some who belonged to the church, intending to persecute them.",
    Ind:"Kira-kira pada waktu itu raja Herodes mulai bertindak dengan keras terhadap beberapa orang dari jemaat."
  },
  {Bible:"Acts", Chapter:12, Verse:2, Page:1,
    Kor:"그는 먼저 요한과 형제간인 야고보를 칼로 죽였다.",
    Chn:"用刀杀了约翰的哥哥雅各。",
    Eng:"He had James, the brother of John, put to death with the sword.",
    Ind:"Ia menyuruh membunuh Yakobus, saudara Yohanes, dengan pedang."
  },
  {Bible:"Acts", Chapter:12, Verse:3, Page:1,
    Kor:"헤롯은 유대 사람들이 이 일을 기뻐하는 것을 보고, 이제는 베드로까지 잡으려고 하였다. 때는 a무교절 기간이었다.(a 출 12:15-20을 볼 것)",
    Chn:"他见犹太人喜欢这事，又去捉拿彼得。那时正是除酵的日子。",
    Eng:"When he saw that this pleased the Jews, he proceeded to seize Peter also. This happened during the Feast of Unleavened Bread.",
    Ind:"Ketika ia melihat, bahwa hal itu menyenangkan hati orang Yahudi, ia melanjutkan perbuatannya itu dan menyuruh menahan Petrus. Waktu itu hari raya Roti Tidak Beragi."
  },
  {Bible:"Acts", Chapter:12, Verse:4, Page:1,
    Kor:"그는 베드로도 잡아서 감옥에 가두고, 네 명으로 짠 경비병 네 패에게 맡겨서 지키게 하였다. b유월절이 지나면, 백성들 앞에 그를 끌어낼 속셈이었다.(b 출 12:13, 21-28을 볼 것)",
    Chn:"希律拿了彼得，收在监里，交付四班兵丁看守，每班四个人，意思要在逾越节后把他提出来，当着百姓办他。",
    Eng:"After arresting him, he put him in prison, handing him over to be guarded by four squads of four soldiers each. Herod intended to bring him out for public trial after the Passover.",
    Ind:"Setelah Petrus ditangkap, Herodes menyuruh memenjarakannya di bawah penjagaan empat regu, masing-masing terdiri dari empat prajurit. Maksudnya ialah, supaya sehabis Paskah ia menghadapkannya ke depan orang banyak."
  },
  {Bible:"Acts", Chapter:12, Verse:5, Page:1,
    Kor:"이렇게 되어서, 베드로가 감옥에 갇히고, 교회는 그를 위하여 하나님께 간절히 기도하였다.",
    Chn:"于是彼得被囚在监里；教会却为他切切地祷告　神。",
    Eng:"So Peter was kept in prison, but the church was earnestly praying to God for him.",
    Ind:"Demikianlah Petrus ditahan di dalam penjara. Tetapi jemaat dengan tekun mendoakannya kepada Allah."
  },
  {Bible:"Acts", Chapter:12, Verse:6, Page:1,
    Kor:"<베드로가 감옥에서 풀려나다> ○헤롯이 베드로를 백성들 앞에 끌어내기로 한 그 전날 밤이었다. 베드로는 두 쇠사슬에 묶여, 군인 두 사람 틈에서 잠들어 있었고, 문 앞에는 파수꾼들이 감옥을 지키고 있었다.",
    Chn:"希律将要提他出来的前一夜，彼得被两条铁链锁着，睡在两个兵丁当中；看守的人也在门外看守。",
    Eng:"The night before Herod was to bring him to trial, Peter was sleeping between two soldiers, bound with two chains, and sentries stood guard at the entrance.",
    Ind:"Pada malam sebelum Herodes hendak menghadapkannya kepada orang banyak, Petrus tidur di antara dua orang prajurit, terbelenggu dengan dua rantai. Selain itu prajurit-prajurit pengawal sedang berkawal di muka pintu."
  },
  {Bible:"Acts", Chapter:12, Verse:7, Page:1,
    Kor:"그런데 갑자기 주님의 천사가 나타나고, 감방에 빛이 환히 비치었다. 천사가 베드로의 옆구리를 쳐서 깨우고 말하기를 \"빨리 일어서라\" 하였다. 그러자 쇠사슬이 그의 두 손목에서 풀렸다.",
    Chn:"忽然，有主的一个使者站在旁边，屋里有光照耀，天使拍彼得的肋旁，拍醒了他，说：「快快起来！」那铁链就从他手上脱落下来。",
    Eng:"Suddenly an angel of the Lord appeared and a light shone in the cell. He struck Peter on the side and woke him up. \"Quick, get up!\" he said, and the chains fell off Peter's wrists.",
    Ind:"Tiba-tiba berdirilah seorang malaikat Tuhan dekat Petrus dan cahaya bersinar dalam ruang itu. Malaikat itu menepuk Petrus untuk membangunkannya, katanya: \"Bangunlah segera!\" Maka gugurlah rantai itu dari tangan Petrus."
  },
  {Bible:"Acts", Chapter:12, Verse:8, Page:1,
    Kor:"천사가 베드로에게 \"띠를 띠고, 신을 신어라\" 하고 말하니, 베드로가 그대로 하였다. 또 천사가 그에게 \"겉옷을 두르고, 나를 따라오너라\" 하니,",
    Chn:"天使对他说：「束上带子，穿上鞋。」他就那样做。天使又说：「披上外衣，跟着我来。」",
    Eng:"Then the angel said to him, \"Put on your clothes and sandals.\" And Peter did so. \"Wrap your cloak around you and follow me,\" the angel told him.",
    Ind:"Lalu kata malaikat itu kepadanya: \"Ikatlah pinggangmu dan kenakanlah sepatumu!\" Iapun berbuat demikian. Lalu malaikat itu berkata kepadanya: \"Kenakanlah jubahmu dan ikutlah aku!\""
  },
  {Bible:"Acts", Chapter:12, Verse:9, Page:1,
    Kor:"베드로가 감방에서 나와서, 천사를 따라갔다. 베드로는 천사가 하는 일이 참인 줄 모르고, 자기가 환상을 보고 있는 것이라고 생각하였다.",
    Chn:"彼得就出来跟着他，不知道天使所做是真的，只当见了异象。",
    Eng:"Peter followed him out of the prison, but he had no idea that what the angel was doing was really happening; he thought he was seeing a vision.",
    Ind:"Lalu ia mengikuti malaikat itu ke luar dan ia tidak tahu, bahwa apa yang dilakukan malaikat itu sungguh-sungguh terjadi, sangkanya ia melihat suatu penglihatan."
  },
  {Bible:"Acts", Chapter:12, Verse:10, Page:1,
    Kor:"그들이 첫째 초소와 둘째 초소를 지나서, 시내로 통하는 철문에 이르니, 문이 저절로 열렸다. 그래서 그들은 바깥으로 나와서, 거리를 하나 지났다. 그 때에 갑자기 천사가 떠나갔다.",
    Chn:"过了第一层第二层监牢，就来到临街的铁门，那门自己开了。他们出来，走过一条街，天使便离开他去了。",
    Eng:"They passed the first and second guards and came to the iron gate leading to the city. It opened for them by itself, and they went through it. When they had walked the length of one street, suddenly the angel left him.",
    Ind:"Setelah mereka melalui tempat kawal pertama dan tempat kawal kedua, sampailah mereka ke pintu gerbang besi yang menuju ke kota. Pintu itu terbuka dengan sendirinya bagi mereka. Sesudah tiba di luar, mereka berjalan sampai ke ujung jalan, dan tiba-tiba malaikat itu meninggalkan dia."
  },
  {Bible:"Acts", Chapter:12, Verse:11, Page:1,
    Kor:"그 때에야 베드로가 정신이 나서 말하였다. \"이제야 참으로 알겠다. 주님께서 주님의 천사를 보내셔서, 헤롯의 손에서, 그리고 유대 백성이 꾸민 모든 음모에서, 나를 건져 주셨다.\"",
    Chn:"彼得醒悟过来，说：「我现在真知道主差遣他的使者，救我脱离希律的手和犹太百姓一切所盼望的。」",
    Eng:"Then Peter came to himself and said, \"Now I know without a doubt that the Lord sent his angel and rescued me from Herod's clutches and from everything the Jewish people were anticipating.\"",
    Ind:"Dan setelah sadar akan dirinya, Petrus berkata: \"Sekarang tahulah aku benar-benar bahwa Tuhan telah menyuruh malaikat-Nya dan menyelamatkan aku dari tangan Herodes dan dari segala sesuatu yang diharapkan orang Yahudi.\""
  },
  {Bible:"Acts", Chapter:12, Verse:12, Page:1,
    Kor:"이런 사실을 깨닫고서, 베드로는, 마가라고도 하는 요한의 어머니 마리아의 집으로 갔다. 거기에는 많은 사람이 모여서 기도하고 있었다.",
    Chn:"想了一想，就往那称呼马可的约翰、他母亲马利亚家去，在那里有好些人聚集祷告。",
    Eng:"When this had dawned on him, he went to the house of Mary the mother of John, also called Mark, where many people had gathered and were praying.",
    Ind:"Dan setelah berpikir sebentar, pergilah ia ke rumah Maria, ibu Yohanes yang disebut juga Markus. Di situ banyak orang berkumpul dan berdoa."
  },
  {Bible:"Acts", Chapter:12, Verse:13, Page:1,
    Kor:"베드로가 대문을 두드리니, 로데라는 어린 여종이 맞으러 나왔다.",
    Chn:"彼得敲外门，有一个使女，名叫罗大，出来探听，",
    Eng:"Peter knocked at the outer entrance, and a servant girl named Rhoda came to answer the door.",
    Ind:"Dan ketika ia mengetuk pintu gerbang, datanglah seorang hamba perempuan bernama Rode untuk mengetahui siapa yang mengetuk itu."
  },
  {Bible:"Acts", Chapter:12, Verse:14, Page:1,
    Kor:"그 여종은 베드로의 목소리를 알아듣고, 너무 기뻐서, 문을 열지도 않고 도로 달려들어가서, 대문 앞에 베드로가 서 있다고 알렸다.",
    Chn:"听得是彼得的声音，就欢喜的顾不得开门，跑进去告诉众人说：「彼得站在门外。」",
    Eng:"When she recognized Peter's voice, she was so overjoyed she ran back without opening it and exclaimed, \"Peter is at the door!\"",
    Ind:"Ia terus mengenal suara Petrus, tetapi karena girangnya ia tidak membuka pintu gerbang itu dan segera masuk ke dalam untuk memberitahukan, bahwa Petrus ada di depan pintu gerbang."
  },
  {Bible:"Acts", Chapter:12, Verse:15, Page:1,
    Kor:"사람들이 여종에게 \"네가 미쳤구나\" 하고 말하자, 여종은 참말이라고 우겼다. 그러자 그들은 \"베드로의 천사일거야\" 하고 말하였다.",
    Chn:"他们说：「你是疯了！」使女极力地说：「真是他！」他们说：「必是他的天使！」",
    Eng:"\"You're out of your mind,\" they told her. When she kept insisting that it was so, they said, \"It must be his angel.\"",
    Ind:"Kata mereka kepada perempuan itu: \"Engkau mengigau.\" Akan tetapi ia tetap mengatakan, bahwa benar-benar demikian. Kata mereka: \"Itu malaikatnya.\""
  },
  {Bible:"Acts", Chapter:12, Verse:16, Page:1,
    Kor:"그 동안에 베드로가 줄곧 문을 두드리니, 사람들이 문을 열어서 베드로를 보고, 깜짝 놀랐다.",
    Chn:"彼得不住地敲门。他们开了门，看见他，就甚惊奇。",
    Eng:"But Peter kept on knocking, and when they opened the door and saw him, they were astonished.",
    Ind:"Tetapi Petrus terus-menerus mengetuk dan ketika mereka membuka pintu dan melihat dia, mereka tercengang-cengang."
  },
  {Bible:"Acts", Chapter:12, Verse:17, Page:1,
    Kor:"베드로는 손을 흔들어서 그들을 조용하게 하고, 주님께서 자기를 감옥에서 인도하여 내신 일을 이야기하였다. 그리고 그는 \"이 사실을 야고보와 다른 c신도들에게 알리시오\" 하고 말하고는, 거기에서 떠나 다른 곳으로 갔다.(c 그, '형제들')",
    Chn:"彼得摆手，不要他们作声，就告诉他们主怎样领他出监；又说：「你们把这事告诉雅各和众弟兄。」于是出去，往别处去了。",
    Eng:"Peter motioned with his hand for them to be quiet and described how the Lord had brought him out of prison. \"Tell James and the brothers about this,\" he said, and then he left for another place.",
    Ind:"Tetapi Petrus memberi isyarat dengan tangannya, supaya mereka diam, lalu ia menceriterakan bagaimana Tuhan menuntunnya ke luar dari penjara. Katanya: \"Beritahukanlah hal ini kepada Yakobus dan saudara-saudara kita.\" Lalu ia keluar dan pergi ke tempat lain."
  },
  {Bible:"Acts", Chapter:12, Verse:18, Page:1,
    Kor:"○날이 새니, 군인들 사이에서는 베드로가 없어진 일로 작지 않은 소동이 일어났다.",
    Chn:"到了天亮，兵丁扰乱得很，不知道彼得往哪里去了。",
    Eng:"In the morning, there was no small commotion among the soldiers as to what had become of Peter.",
    Ind:"Pada keesokan harinya gemparlah prajurit-prajurit itu. Mereka bertanya-tanya apakah yang telah terjadi dengan Petrus."
  },
  {Bible:"Acts", Chapter:12, Verse:19, Page:1,
    Kor:"헤롯은 샅샅이 찾아보았으나, 베드로를 찾지 못하고, 경비병들을 문초한 뒤에, 명령을 내려서 그들을 사형에 처하였다. 그런 다음에, d헤롯은 유대를 떠나 가이사랴로 내려가서, 거기에서 한동안 지냈다.(d 그, '그는'. '그'의 실명사를 '베드로'로 보는 견해도 있음)",
    Chn:"希律找他，找不着，就审问看守的人，吩咐把他们拉去杀了。后来希律离开犹太，下凯撒利亚去，住在那里。",
    Eng:"After Herod had a thorough search made for him and did not find him, he cross-examined the guards and ordered that they be executed. Then Herod went from Judea to Caesarea and stayed there a while.",
    Ind:"Herodes menyuruh mencari Petrus, tetapi ia tidak ditemukan. Lalu Herodes menyuruh memeriksa pengawal-pengawal itu dan membunuh mereka. Kemudian ia berangkat dari Yudea ke Kaisarea dan tinggal di situ."
  },
  {Bible:"Acts", Chapter:12, Verse:20, Page:1,
    Kor:"<헤롯의 죽음> ○그런데 두로와 시돈 사람들은 헤롯에게 몹시 노여움을 사고 있었다. 그래서 그들은 뜻을 모아서, 왕을 찾아갔다. 그들은 왕의 침실 시종 블라스도를 설득하여, 그를 통해서 헤롯에게 화평을 청하였다. 그들의 지방이 왕의 영토에서 식량을 공급받고 있었으므로, 이렇게 할 수밖에 없었다.",
    Chn:"希律恼怒泰尔、西顿的人。他们那一带地方是从王的地土得粮，因此就托了王的内侍臣伯拉斯都的情，一心来求和。",
    Eng:"He had been quarreling with the people of Tyre and Sidon; they now joined together and sought an audience with him. Having secured the support of Blastus, a trusted personal servant of the king, they asked for peace, because they depended on the king's country for their food supply.",
    Ind:"Herodes sangat marah terhadap orang Tirus dan Sidon. Atas persetujuan bersama mereka pergi menghadap dia. Mereka berhasil membujuk Blastus, pegawai istana raja, ke pihak mereka, lalu mereka memohonkan perdamaian, karena negeri mereka beroleh bahan makanan dari wilayah raja."
  },
  {Bible:"Acts", Chapter:12, Verse:21, Page:1,
    Kor:"지정된 날에, 헤롯이 용포를 걸쳐 입고, 왕좌에 좌정하여 그들에게 연설하였다.",
    Chn:"希律在所定的日子，穿上朝服，坐在位上，对他们讲论一番。",
    Eng:"On the appointed day Herod, wearing his royal robes, sat on his throne and delivered a public address to the people.",
    Ind:"Dan pada suatu hari yang ditentukan, Herodes mengenakan pakaian kerajaan, lalu duduk di atas takhta dan berpidato kepada mereka."
  },
  {Bible:"Acts", Chapter:12, Verse:22, Page:1,
    Kor:"그 때에 군중이 \"신의 소리다. 사람의 소리가 아니다\" 하고 외쳤다.",
    Chn:"百姓喊着说：「这是神的声音，不是人的声音。」",
    Eng:"They shouted, \"This is the voice of a god, not of a man.\"",
    Ind:"Dan rakyatnya bersorak membalasnya: \"Ini suara allah dan bukan suara manusia!\""
  },
  {Bible:"Acts", Chapter:12, Verse:23, Page:1,
    Kor:"그러자 즉시로 주님의 천사가 헤롯을 내리쳤다. 헤롯이 하나님께 영광을 돌리지 않았기 때문이다. 그는 벌레에게 먹혀서 죽고 말았다.",
    Chn:"希律不归荣耀给　神，所以主的使者立刻罚他，他被虫所咬，气就绝了。",
    Eng:"Immediately, because Herod did not give praise to God, an angel of the Lord struck him down, and he was eaten by worms and died.",
    Ind:"Dan seketika itu juga ia ditampar malaikat Tuhan karena ia tidak memberi hormat kepada Allah; ia mati dimakan cacing-cacing."
  },
  {Bible:"Acts", Chapter:12, Verse:24, Page:1,
    Kor:"○하나님의 말씀이 점점 더 널리 퍼지고, 믿는 사람이 많아졌다.",
    Chn:"神的道日见兴旺，越发广传。",
    Eng:"But the word of God continued to increase and spread.",
    Ind:"Maka firman Tuhan makin tersebar dan makin banyak didengar orang."
  },
  {Bible:"Acts", Chapter:12, Verse:25, Page:1,
    Kor:"바나바와 사울은 그들의 사명을 마치고, 마가라고도 하는 요한을 데리고 e예루살렘에서 돌아왔다.(e 다른 고대 사본들에는 '예루살렘으로 돌아갔다')",
    Chn:"巴拿巴和扫罗办完了他们供给的事，就从耶路撒冷回来，带着称呼马可的约翰同去。",
    Eng:"When Barnabas and Saul had finished their mission, they returned from Jerusalem, taking with them John, also called Mark.",
    Ind:"Barnabas dan Saulus kembali dari Yerusalem, setelah mereka menyelesaikan tugas pelayanan mereka. Mereka membawa Yohanes, yang disebut juga Markus."
  },
]);
