// 사도행전 14장 · Acts 14
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Acts",14,28);
BibleDB.add([
  {Bible:"Acts", Chapter:14, Verse:1, Page:1,
    Kor:"<바울과 바나바가 이고니온에서 전도하다> a바울과 바나바는 이고니온에서도 이전과 마찬가지로, 유대 사람의 회당에 들어가서 말하였다. 그래서 유대 사람과 그리스 사람이 많이 믿게 되었다.(a 그, '그들은')",
    Chn:"二人在以哥念同进犹太人的会堂，在那里讲的，叫犹太人和希腊人信的很多。",
    Eng:"At Iconium Paul and Barnabas went as usual into the Jewish synagogue. There they spoke so effectively that a great number of Jews and Gentiles believed.",
    Ind:"Di Ikoniumpun kedua rasul itu masuk ke rumah ibadat orang Yahudi, lalu mengajar sedemikian rupa, sehingga sejumlah besar orang Yahudi dan orang Yunani menjadi percaya."
  },
  {Bible:"Acts", Chapter:14, Verse:2, Page:1,
    Kor:"그러나 마음을 돌이키지 않은 유대 사람들이 이방 사람들을 선동해서, 믿는 형제들에게 나쁜 감정을 품게 하였다.",
    Chn:"但那不顺从的犹太人耸动外邦人，叫他们心里恼恨弟兄。",
    Eng:"But the Jews who refused to believe stirred up the Gentiles and poisoned their minds against the brothers.",
    Ind:"Tetapi orang-orang Yahudi, yang menolak pemberitaan mereka, memanaskan hati orang-orang yang tidak mengenal Allah dan membuat mereka gusar terhadap saudara-saudara itu."
  },
  {Bible:"Acts", Chapter:14, Verse:3, Page:1,
    Kor:"두 사도는 오랫동안 거기에 머물면서, 주님을 의지하여 담대하게 말하였다. 주님께서는 그들의 손으로 표징과 놀라운 일을 행하게 하셔서, 그들이 전하는 은혜의 말씀을 확증하여 주셨다.",
    Chn:"二人在那里住了多日，倚靠主放胆讲道，主借他们的手施行神迹奇事，证明他的恩道。",
    Eng:"So Paul and Barnabas spent considerable time there, speaking boldly for the Lord, who confirmed the message of his grace by enabling them to do miraculous signs and wonders.",
    Ind:"Paulus dan Barnabas tinggal beberapa waktu lamanya di situ. Mereka mengajar dengan berani, karena mereka percaya kepada Tuhan. Dan Tuhan menguatkan berita tentang kasih karunia-Nya dengan mengaruniakan kepada mereka kuasa untuk mengadakan tanda-tanda dan mujizat-mujizat."
  },
  {Bible:"Acts", Chapter:14, Verse:4, Page:1,
    Kor:"그 도시 사람들은 두 편으로 나뉘어서, 더러는 유대 사람의 편을 들고, 더러는 사도의 편을 들었다.",
    Chn:"城里的众人就分了党，有附从犹太人的，有附从使徒的。",
    Eng:"The people of the city were divided; some sided with the Jews, others with the apostles.",
    Ind:"Tetapi orang banyak di kota itu terbelah menjadi dua: ada yang memihak kepada orang Yahudi, ada pula yang memihak kepada kedua rasul itu."
  },
  {Bible:"Acts", Chapter:14, Verse:5, Page:1,
    Kor:"그런데 이방 사람들과 유대 사람들이 그들의 관원들과 합세해서, 바울과 바나바를 모욕하고 돌로 쳐죽이려고 했다.",
    Chn:"那时，外邦人和犹太人，并他们的官长，一齐拥上来，要凌辱使徒，用石头打他们。",
    Eng:"There was a plot afoot among the Gentiles and Jews, together with their leaders, to mistreat them and stone them.",
    Ind:"Maka mulailah orang-orang yang tidak mengenal Allah dan orang-orang Yahudi bersama-sama dengan pemimpin-pemimpin mereka menimbulkan suatu gerakan untuk menyiksa dan melempari kedua rasul itu dengan batu."
  },
  {Bible:"Acts", Chapter:14, Verse:6, Page:1,
    Kor:"a사도들은 그것을 알고, 루가오니아 지방에 있는 두 도시 루스드라와 더베와 그 근방으로 피하였다.(a 그, '그들은')",
    Chn:"使徒知道了，就逃往吕高尼的路司得、特庇两个城和周围地方去，",
    Eng:"But they found out about it and fled to the Lycaonian cities of Lystra and Derbe and to the surrounding country,",
    Ind:"Setelah rasul-rasul itu mengetahuinya, menyingkirlah mereka ke kota-kota di Likaonia, yaitu Listra dan Derbe dan daerah sekitarnya."
  },
  {Bible:"Acts", Chapter:14, Verse:7, Page:1,
    Kor:"그들은 거기에서도 줄곧 복음을 전하였다.",
    Chn:"在那里传福音。",
    Eng:"where they continued to preach the good news.",
    Ind:"Di situ mereka memberitakan Injil."
  },
  {Bible:"Acts", Chapter:14, Verse:8, Page:1,
    Kor:"<바울과 바나바가 루스드라에서 전도하다> ○루스드라에 발을 쓰지 못하는 지체장애인 한 사람이 앉아 있었다. 그는 나면서부터 못 걷는 사람이 되어서, 걸어본 적이 없었다.",
    Chn:"路司得城里坐着一个两脚无力的人，生来是瘸腿的，从来没有走过。",
    Eng:"In Lystra there sat a man crippled in his feet, who was lame from birth and had never walked.",
    Ind:"Di Listra ada seorang yang duduk saja, karena lemah kakinya dan lumpuh sejak ia dilahirkan dan belum pernah dapat berjalan."
  },
  {Bible:"Acts", Chapter:14, Verse:9, Page:1,
    Kor:"이 사람이 바울이 말하는 것을 들었다. 바울은 그를 똑바로 바라보고, 고침을 받을 만한 믿음이 그에게 있는 것을 알고는,",
    Chn:"他听保罗讲道，保罗定睛看他，见他有信心，可得痊愈，",
    Eng:"He listened to Paul as he was speaking. Paul looked directly at him, saw that he had faith to be healed",
    Ind:"Ia duduk mendengarkan, ketika Paulus berbicara. Dan Paulus menatap dia dan melihat, bahwa ia beriman dan dapat disembuhkan."
  },
  {Bible:"Acts", Chapter:14, Verse:10, Page:1,
    Kor:"큰 소리로 \"그대의 발로 똑바로 일어서시오\" 하고 말하였다. 그러자 그는 벌떡 일어나서, 걷기 시작하였다.",
    Chn:"就大声说：「你起来，两脚站直！」那人就跳起来，而且行走。",
    Eng:"and called out, \"Stand up on your feet!\" At that, the man jumped up and began to walk.",
    Ind:"Lalu kata Paulus dengan suara nyaring: \"Berdirilah tegak di atas kakimu!\" Dan orang itu melonjak berdiri, lalu berjalan kian ke mari."
  },
  {Bible:"Acts", Chapter:14, Verse:11, Page:1,
    Kor:"무리가 바울이 행한 일을 보고서, 루가오니아 말로 \"신들이 사람의 모습으로 우리에게 내려왔다\" 하고 소리 질렀다.",
    Chn:"众人看见保罗所做的事，就用吕高尼的话大声说：「有神借着人形降临在我们中间了。」",
    Eng:"When the crowd saw what Paul had done, they shouted in the Lycaonian language, \"The gods have come down to us in human form!\"",
    Ind:"Ketika orang banyak melihat apa yang telah diperbuat Paulus, mereka itu berseru dalam bahasa Likaonia: \"Dewa-dewa telah turun ke tengah-tengah kita dalam rupa manusia.\""
  },
  {Bible:"Acts", Chapter:14, Verse:12, Page:1,
    Kor:"그리고 그들은 바나바를 제우스라고 부르고, 바울을 헤르메스라고 불렀는데, 그것은 바울이 말하는 역할을 주로 맡았기 때문이다.",
    Chn:"于是称巴拿巴为宙斯，称保罗为希耳米，因为他说话领首。",
    Eng:"Barnabas they called Zeus, and Paul they called Hermes because he was the chief speaker.",
    Ind:"Barnabas mereka sebut Zeus dan Paulus mereka sebut Hermes, karena ia yang berbicara."
  },
  {Bible:"Acts", Chapter:14, Verse:13, Page:1,
    Kor:"성 바깥에 있는 제우스 신당의 제사장이 황소 몇 마리와 화환을 성문 앞에 가지고 와서, 군중과 함께 두 사람에게 제사를 드리려고 하였다.",
    Chn:"有城外宙斯庙的祭司牵着牛，拿着花圈，来到门前，要同众人向使徒献祭。",
    Eng:"The priest of Zeus, whose temple was just outside the city, brought bulls and wreaths to the city gates because he and the crowd wanted to offer sacrifices to them.",
    Ind:"Maka datanglah imam dewa Zeus, yang kuilnya terletak di luar kota, membawa lembu-lembu jantan dan karangan-karangan bunga ke pintu gerbang kota untuk mempersembahkan korban bersama-sama dengan orang banyak kepada rasul-rasul itu."
  },
  {Bible:"Acts", Chapter:14, Verse:14, Page:1,
    Kor:"이 말을 듣고서, 바나바와 바울 두 사도는 자기들의 옷을 찢고, 군중 가운데로 뛰어 들어가서 외치면서,",
    Chn:"巴拿巴、保罗二使徒听见，就撕开衣裳，跳进众人中间，喊着说：",
    Eng:"But when the apostles Barnabas and Paul heard of this, they tore their clothes and rushed out into the crowd, shouting:",
    Ind:"Mendengar itu Barnabas dan Paulus mengoyakkan pakaian mereka, lalu terjun ke tengah-tengah orang banyak itu sambil berseru:"
  },
  {Bible:"Acts", Chapter:14, Verse:15, Page:1,
    Kor:"이렇게 말하였다. \"b여러분, 어찌하여 이런 일들을 하십니까? 우리도 여러분과 똑같은 성정을 가진 사람입니다. 우리가 여러분에게 복음을 전하는 것은, 여러분이 이런 헛된 일을 버리고, 하늘과 땅과 바다와 그 안에 있는 모든 것을 만드신, 살아 계신 하나님께로 돌아오게 하려는 것입니다.(b 그, '사람들')",
    Chn:"「诸君，为什么做这事呢？我们也是人，性情和你们一样。我们传福音给你们，是叫你们离弃这些虚妄，归向那创造天、地、海，和其中万物的永生　神。",
    Eng:"\"Men, why are you doing this? We too are only men, human like you. We are bringing you good news, telling you to turn from these worthless things to the living God, who made heaven and earth and sea and everything in them.",
    Ind:"\"Hai kamu sekalian, mengapa kamu berbuat demikian? Kami ini adalah manusia biasa sama seperti kamu. Kami ada di sini untuk memberitakan Injil kepada kamu, supaya kamu meninggalkan perbuatan sia-sia ini dan berbalik kepada Allah yang hidup, yang telah menjadikan langit dan bumi, laut dan segala isinya."
  },
  {Bible:"Acts", Chapter:14, Verse:16, Page:1,
    Kor:"하나님께서는 지나간 세대에는 이방 민족들이 자기네 방식대로 살아가게 내버려 두셨습니다.",
    Chn:"他在从前的世代，任凭万国各行其道；",
    Eng:"In the past, he let all nations go their own way.",
    Ind:"Dalam zaman yang lampau Allah membiarkan semua bangsa menuruti jalannya masing-masing,"
  },
  {Bible:"Acts", Chapter:14, Verse:17, Page:1,
    Kor:"그렇지만 하나님께서 자기를 드러내지 않으신 것은 아닙니다. 곧 하늘에서 비를 내려 주시고, 철을 따라 열매를 맺게 하시고, 먹을거리를 주셔서, 여러분의 마음을 기쁨으로 가득 채워 주셨습니다.\"",
    Chn:"然而为自己未尝不显出证据来，就如常施恩惠，从天降雨，赏赐丰年，叫你们饮食饱足，满心喜乐。」",
    Eng:"Yet he has not left himself without testimony: He has shown kindness by giving you rain from heaven and crops in their seasons; he provides you with plenty of food and fills your hearts with joy.\"",
    Ind:"namun Ia bukan tidak menyatakan diri-Nya dengan berbagai-bagai kebajikan, yaitu dengan menurunkan hujan dari langit dan dengan memberikan musim-musim subur bagi kamu. Ia memuaskan hatimu dengan makanan dan kegembiraan.\""
  },
  {Bible:"Acts", Chapter:14, Verse:18, Page:1,
    Kor:"두 사도는 이렇게 말하면서, 군중이 자기들에게 제사하지 못하게 겨우 말렸다.",
    Chn:"二人说了这些话，仅仅地拦住众人不献祭与他们。",
    Eng:"Even with these words, they had difficulty keeping the crowd from sacrificing to them.",
    Ind:"Walaupun rasul-rasul itu berkata demikian, namun hampir-hampir tidak dapat mereka mencegah orang banyak mempersembahkan korban kepada mereka."
  },
  {Bible:"Acts", Chapter:14, Verse:19, Page:1,
    Kor:"○그런데 유대 사람들이 안디옥과 이고니온에서 거기로 몰려와서 군중을 설득하고, 바울을 돌로 쳤다. 그들은 바울이 죽은 줄 알고, 그를 성 밖으로 끌어냈다.",
    Chn:"但有些犹太人从安提阿和以哥念来，挑唆众人，就用石头打保罗，以为他是死了，便拖到城外。",
    Eng:"Then some Jews came from Antioch and Iconium and won the crowd over. They stoned Paul and dragged him outside the city, thinking he was dead.",
    Ind:"Tetapi datanglah orang-orang Yahudi dari Antiokhia dan Ikonium dan mereka membujuk orang banyak itu memihak mereka. Lalu mereka melempari Paulus dengan batu dan menyeretnya ke luar kota, karena mereka menyangka, bahwa ia telah mati."
  },
  {Bible:"Acts", Chapter:14, Verse:20, Page:1,
    Kor:"그러나 제자들이 바울을 둘러섰을 때에, 그는 일어나서 성 안으로 들어갔다. 이튿날 그는 바나바와 함께 더베로 떠났다.",
    Chn:"门徒正围着他，他就起来，走进城去。 第二天，同巴拿巴往特庇去，",
    Eng:"But after the disciples had gathered around him, he got up and went back into the city. The next day he and Barnabas left for Derbe.",
    Ind:"Akan tetapi ketika murid-murid itu berdiri mengelilingi dia, bangkitlah ia lalu masuk ke dalam kota. Keesokan harinya berangkatlah ia bersama-sama dengan Barnabas ke Derbe."
  },
  {Bible:"Acts", Chapter:14, Verse:21, Page:1,
    Kor:"<바울과 바나바가 수리아의 안디옥으로 돌아오다> ○바울과 바나바는 그 성에서 복음을 전하여 많은 제자를 얻은 뒤에, 루스드라와 이고니온과 안디옥으로 되돌아갔다.",
    Chn:"对那城里的人传了福音，使好些人作门徒，就回路司得、以哥念、安提阿去，",
    Eng:"They preached the good news in that city and won a large number of disciples. Then they returned to Lystra, Iconium and Antioch,",
    Ind:"Paulus dan Barnabas memberitakan Injil di kota itu dan memperoleh banyak murid. Lalu kembalilah mereka ke Listra, Ikonium dan Antiokhia."
  },
  {Bible:"Acts", Chapter:14, Verse:22, Page:1,
    Kor:"그들은 제자들의 마음을 굳세게 해주고, 믿음을 지키라고 권하였다. 그리고 또 이렇게 말하였다. \"우리가 하나님 나라에 들어가려면, 반드시 많은 환난을 겪어야 합니다.\"",
    Chn:"坚固门徒的心，劝他们恒守所信的道；又说：「我们进入　神的国，必须经历许多艰难。」",
    Eng:"strengthening the disciples and encouraging them to remain true to the faith. \"We must go through many hardships to enter the kingdom of God,\" they said.",
    Ind:"Di tempat itu mereka menguatkan hati murid-murid itu dan menasihati mereka supaya mereka bertekun di dalam iman, dan mengatakan, bahwa untuk masuk ke dalam Kerajaan Allah kita harus mengalami banyak sengsara."
  },
  {Bible:"Acts", Chapter:14, Verse:23, Page:1,
    Kor:"그리고 그들을 위해서 각 교회에서 장로들을 임명한 뒤에, 금식을 하면서 기도하고, 그들이 믿게 된 주님께 그들을 맡겼다.",
    Chn:"二人在各教会中选立了长老，又禁食祷告，就把他们交托所信的主。",
    Eng:"Paul and Barnabas appointed elders for them in each church and, with prayer and fasting, committed them to the Lord, in whom they had put their trust.",
    Ind:"Di tiap-tiap jemaat rasul-rasul itu menetapkan penatua-penatua bagi jemaat itu dan setelah berdoa dan berpuasa, mereka menyerahkan penatua-penatua itu kepada Tuhan, yang adalah sumber kepercayaan mereka."
  },
  {Bible:"Acts", Chapter:14, Verse:24, Page:1,
    Kor:"그리고 그 두 사람은 비시디아 지방을 거쳐서 밤빌리아 지방에 이르렀다.",
    Chn:"二人经过彼西底，来到旁非利亚。",
    Eng:"After going through Pisidia, they came into Pamphylia,",
    Ind:"Mereka menjelajah seluruh Pisidia dan tiba di Pamfilia."
  },
  {Bible:"Acts", Chapter:14, Verse:25, Page:1,
    Kor:"그들은 버가에서 말씀을 전한 뒤에, 앗달리아로 내려가서,",
    Chn:"在别加讲了道，就下亚大利去，",
    Eng:"and when they had preached the word in Perga, they went down to Attalia.",
    Ind:"Di situ mereka memberitakan firman di Perga, lalu pergi ke Atalia, di pantai."
  },
  {Bible:"Acts", Chapter:14, Verse:26, Page:1,
    Kor:"거기에서 배를 타고 안디옥으로 향하여 갔다. 이 안디옥은, 그들이 선교 활동을 하려고, 하나님의 은혜에 몸을 내맡기고 나선 곳이다. 이제 그들은 그 일을 다 이루었다.",
    Chn:"从那里坐船，往安提阿去。当初，他们被众人所托、蒙　神之恩、要办现在所做之工，就是在这地方。",
    Eng:"From Attalia they sailed back to Antioch, where they had been committed to the grace of God for the work they had now completed.",
    Ind:"Dari situ berlayarlah mereka ke Antiokhia; di tempat itulah mereka dahulu diserahkan kepada kasih karunia Allah untuk memulai pekerjaan, yang telah mereka selesaikan."
  },
  {Bible:"Acts", Chapter:14, Verse:27, Page:1,
    Kor:"그 곳에 이르러서 그들은 교회 회중을 불러모으고서, 하나님께서 자기들과 함께 행하신 모든 일과, 하나님께서 이방 사람들에게 믿음의 문을 열어 주신 것을 보고하였다.",
    Chn:"到了那里，聚集了会众，就述说　神借他们所行的一切事，并　神怎样为外邦人开了信道的门。",
    Eng:"On arriving there, they gathered the church together and reported all that God had done through them and how he had opened the door of faith to the Gentiles.",
    Ind:"Setibanya di situ mereka memanggil jemaat berkumpul, lalu mereka menceriterakan segala sesuatu yang Allah lakukan dengan perantaraan mereka, dan bahwa Ia telah membuka pintu bagi bangsa-bangsa lain kepada iman."
  },
  {Bible:"Acts", Chapter:14, Verse:28, Page:1,
    Kor:"그들은 제자들과 함께 오랫동안 지냈다.",
    Chn:"二人就在那里同门徒住了多日。",
    Eng:"And they stayed there a long time with the disciples.",
    Ind:"Di situ mereka lama tinggal bersama-sama dengan murid-murid itu."
  },
]);
