// 사도행전 19장 · Acts 19
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Acts",19,41);
BibleDB.add([
  {Bible:"Acts", Chapter:19, Verse:1, Page:1,
    Kor:"<바울의 에베소 전도활동> 아볼로가 고린도에 있는 동안에, 바울은 a높은 지역들을 거쳐서, 에베소에 이르렀다. 거기서 그는 몇몇 제자를 만나서,(a 갈라디아 지방과 부르기아 지방을 가리킴)",
    Chn:"亚波罗在哥林多的时候，保罗经过了上边一带地方，就来到以弗所；在那里遇见几个门徒，",
    Eng:"While Apollos was at Corinth, Paul took the road through the interior and arrived at Ephesus. There he found some disciples",
    Ind:"Ketika Apolos masih di Korintus, Paulus sudah menjelajah daerah-daerah pedalaman dan tiba di Efesus. Di situ didapatinya beberapa orang murid."
  },
  {Bible:"Acts", Chapter:19, Verse:2, Page:1,
    Kor:"\"여러분은 믿을 때에, 성령을 받았습니까?\" 하고 물었다. 그들은 \"우리는 성령이 있다는 말을 들어보지도 못하였습니다\" 하고 대답하였다.",
    Chn:"问他们说：「你们信的时候受了圣灵没有？」他们回答说：「没有，也未曾听见有圣灵赐下来。」",
    Eng:"and asked them, \"Did you receive the Holy Spirit when you believed?\" They answered, \"No, we have not even heard that there is a Holy Spirit.\"",
    Ind:"Katanya kepada mereka: \"Sudahkah kamu menerima Roh Kudus, ketika kamu menjadi percaya?\" Akan tetapi mereka menjawab dia: \"Belum, bahkan kami belum pernah mendengar, bahwa ada Roh Kudus.\""
  },
  {Bible:"Acts", Chapter:19, Verse:3, Page:1,
    Kor:"바울이 다시 물었다. \"그러면 여러분은 무슨 b세례를 받았습니까?\" 그들이 \"요한의 b세례를 받았습니다\" 하고 대답하니(b 또는 '침례')",
    Chn:"保罗说：「这样，你们受的是什么洗呢？」他们说：「是约翰的洗。」",
    Eng:"So Paul asked, \"Then what baptism did you receive?\" \"John's baptism,\" they replied.",
    Ind:"Lalu kata Paulus kepada mereka: \"Kalau begitu dengan baptisan manakah kamu telah dibaptis?\" Jawab mereka: \"Dengan baptisan Yohanes.\""
  },
  {Bible:"Acts", Chapter:19, Verse:4, Page:1,
    Kor:"바울이 말하였다. \"요한은 백성들에게 자기 뒤에 오시는 이 곧 예수를 믿으라고 말하면서, 회개의 b세례를 주었습니다.\"(b 또는 '침례')",
    Chn:"保罗说：「约翰所行的是悔改的洗，告诉百姓当信那在他以后要来的，就是耶稣。」",
    Eng:"Paul said, \"John's baptism was a baptism of repentance. He told the people to believe in the one coming after him, that is, in Jesus.\"",
    Ind:"Kata Paulus: \"Baptisan Yohanes adalah pembaptisan orang yang telah bertobat, dan ia berkata kepada orang banyak, bahwa mereka harus percaya kepada Dia yang datang kemudian dari padanya, yaitu Yesus.\""
  },
  {Bible:"Acts", Chapter:19, Verse:5, Page:1,
    Kor:"이 말을 듣고, 그들은 주 예수의 이름으로 b세례를 받았다.(b 또는 '침례')",
    Chn:"他们听见这话，就奉主耶稣的名受洗。",
    Eng:"On hearing this, they were baptized into the name of the Lord Jesus.",
    Ind:"Ketika mereka mendengar hal itu, mereka memberi diri mereka dibaptis dalam nama Tuhan Yesus."
  },
  {Bible:"Acts", Chapter:19, Verse:6, Page:1,
    Kor:"그리고 바울이 그들에게 손을 얹으니, 성령이 그들에게 내리셨다. 그래서 그들은 c방언으로 말하고 예언을 했는데,(c 입신 상태에서 하는 알 수 없는 말)",
    Chn:"保罗按手在他们头上，圣灵便降在他们身上，他们就说方言，又说预言。",
    Eng:"When Paul placed his hands on them, the Holy Spirit came on them, and they spoke in tongues and prophesied.",
    Ind:"Dan ketika Paulus menumpangkan tangan di atas mereka, turunlah Roh Kudus ke atas mereka, dan mulailah mereka berkata-kata dalam bahasa roh dan bernubuat."
  },
  {Bible:"Acts", Chapter:19, Verse:7, Page:1,
    Kor:"모두 열두 사람쯤 되었다.",
    Chn:"一共约有十二个人。",
    Eng:"There were about twelve men in all.",
    Ind:"Jumlah mereka adalah kira-kira dua belas orang."
  },
  {Bible:"Acts", Chapter:19, Verse:8, Page:1,
    Kor:"○바울은 회당에 들어가서, 석 달 동안 하나님 나라의 일을 강론하고 권면하면서, 담대하게 말하였다.",
    Chn:"保罗进会堂，放胆讲道，一连三个月，辩论　神国的事，劝化众人。",
    Eng:"Paul entered the synagogue and spoke boldly there for three months, arguing persuasively about the kingdom of God.",
    Ind:"Selama tiga bulan Paulus mengunjungi rumah ibadat di situ dan mengajar dengan berani. Oleh pemberitaannya ia berusaha meyakinkan mereka tentang Kerajaan Allah."
  },
  {Bible:"Acts", Chapter:19, Verse:9, Page:1,
    Kor:"그러나 몇몇 사람은, 마음이 완고하게 되어서 믿으려 하지 않고, 온 회중 앞에서 이 '도'를 비난하므로, 바울은 그들을 떠나, 제자들을 따로 데리고 나가서, 날마다 두란노 학당에서 d강론하였다.(d 다른 고대 사본들에는 '오전 열한 시부터 오후 네 시까지 강론하였다')",
    Chn:"后来，有些人心里刚硬不信，在众人面前毁谤这道，保罗就离开他们，也叫门徒与他们分离，便在推喇奴的学房天天辩论。",
    Eng:"But some of them became obstinate; they refused to believe and publicly maligned the Way. So Paul left them. He took the disciples with him and had discussions daily in the lecture hall of Tyrannus.",
    Ind:"Tetapi ada beberapa orang yang tegar hatinya. Mereka tidak mau diyakinkan, malahan mengumpat Jalan Tuhan di depan orang banyak. Karena itu Paulus meninggalkan mereka dan memisahkan murid-muridnya dari mereka, dan setiap hari berbicara di ruang kuliah Tiranus."
  },
  {Bible:"Acts", Chapter:19, Verse:10, Page:1,
    Kor:"이런 일을 이태 동안 하였다. 아시아에 사는 사람들은, 유대 사람이나 그리스 사람이나, 모두 주님의 말씀을 듣게 되었다.",
    Chn:"这样有两年之久，叫一切住在亚细亚的，无论是犹太人，是希腊人，都听见主的道。",
    Eng:"This went on for two years, so that all the Jews and Greeks who lived in the province of Asia heard the word of the Lord.",
    Ind:"Hal ini dilakukannya dua tahun lamanya, sehingga semua penduduk Asia mendengar firman Tuhan, baik orang Yahudi maupun orang Yunani."
  },
  {Bible:"Acts", Chapter:19, Verse:11, Page:1,
    Kor:"<스게와의 아들들> ○하나님께서 바울의 손을 빌어서 비상한 기적들을 행하셨다.",
    Chn:"神借保罗的手行了些非常的奇事；",
    Eng:"God did extraordinary miracles through Paul,",
    Ind:"Oleh Paulus Allah mengadakan mujizat-mujizat yang luar biasa,"
  },
  {Bible:"Acts", Chapter:19, Verse:12, Page:1,
    Kor:"심지어 사람들이, 바울이 몸에 지니고 있는 손수건이나 두르고 있는 앞치마를 그에게서 가져다가, 앓는 사람 위에 얹기만 해도 병이 물러가고, 악한 귀신이 쫓겨 나갔다.",
    Chn:"甚至有人从保罗身上拿手巾或围裙放在病人身上，病就退了，恶鬼也出去了。",
    Eng:"so that even handkerchiefs and aprons that had touched him were taken to the sick, and their illnesses were cured and the evil spirits left them.",
    Ind:"bahkan orang membawa saputangan atau kain yang pernah dipakai oleh Paulus dan meletakkannya atas orang-orang sakit, maka lenyaplah penyakit mereka dan keluarlah roh-roh jahat."
  },
  {Bible:"Acts", Chapter:19, Verse:13, Page:1,
    Kor:"그런데 귀신 축출가로 행세하며 떠돌아다니는 몇몇 유대 사람조차도 \"바울이 전파하는 예수를 힘입어서 내가 너희에게 명령한다\" 하고 말하면서, 악귀 들린 사람들에게 주 예수의 이름을 이용하여 귀신을 내쫓으려고 시도하였다.",
    Chn:"那时，有几个游行各处、念咒赶鬼的犹太人，向那被恶鬼附的人擅自称主耶稣的名，说：「我奉保罗所传的耶稣敕令你们出来！」",
    Eng:"Some Jews who went around driving out evil spirits tried to invoke the name of the Lord Jesus over those who were demon-possessed. They would say, \"In the name of Jesus, whom Paul preaches, I command you to come out.\"",
    Ind:"Juga beberapa tukang jampi Yahudi, yang berjalan keliling di negeri itu, mencoba menyebut nama Tuhan Yesus atas mereka yang kerasukan roh jahat dengan berseru, katanya: \"Aku menyumpahi kamu demi nama Yesus yang diberitakan oleh Paulus.\""
  },
  {Bible:"Acts", Chapter:19, Verse:14, Page:1,
    Kor:"스게와라는 유대인 제사장의 일곱 아들도 이런 일을 하였는데,",
    Chn:"做这事的，有犹太祭司长士基瓦的七个儿子。",
    Eng:"Seven sons of Sceva, a Jewish chief priest, were doing this.",
    Ind:"Mereka yang melakukan hal itu ialah tujuh orang anak dari seorang imam kepala Yahudi yang bernama Skewa."
  },
  {Bible:"Acts", Chapter:19, Verse:15, Page:1,
    Kor:"귀신이 그들에게 \"나는 예수도 알고, 바울도 알지만, 당신들은 도대체 누구요?\" 하고 말하였다.",
    Chn:"恶鬼回答他们说：「耶稣我认识，保罗我也知道。你们却是谁呢？」",
    Eng:"One day the evil spirit answered them, \"Jesus I know, and I know about Paul, but who are you?\"",
    Ind:"Tetapi roh jahat itu menjawab: \"Yesus aku kenal, dan Paulus aku ketahui, tetapi kamu, siapakah kamu?\""
  },
  {Bible:"Acts", Chapter:19, Verse:16, Page:1,
    Kor:"그리고서 악귀 들린 사람이 그들에게 달려들어, 그들을 짓눌러 이기니, 그들은 몸에 상처를 입고서, 벗은 몸으로 그 집에서 도망하였다.",
    Chn:"恶鬼所附的人就跳在他们身上，胜了其中二人，制伏他们，叫他们赤着身子受了伤，从那房子里逃出去了。",
    Eng:"Then the man who had the evil spirit jumped on them and overpowered them all. He gave them such a beating that they ran out of the house naked and bleeding.",
    Ind:"Dan orang yang dirasuk roh jahat itu menerpa mereka dan menggagahi mereka semua dan mengalahkannya, sehingga mereka lari dari rumah orang itu dengan telanjang dan luka-luka."
  },
  {Bible:"Acts", Chapter:19, Verse:17, Page:1,
    Kor:"이 일이 에베소에 사는 모든 유대 사람과 그리스 사람에게 알려지니, 그들은 모두 두려워하고, 주 예수의 이름을 찬양하였다.",
    Chn:"凡住在以弗所的，无论是犹太人，是希腊人，都知道这事，也都惧怕；主耶稣的名从此就尊大了。",
    Eng:"When this became known to the Jews and Greeks living in Ephesus, they were all seized with fear, and the name of the Lord Jesus was held in high honor.",
    Ind:"Hal itu diketahui oleh seluruh penduduk Efesus, baik orang Yahudi maupun orang Yunani, maka ketakutanlah mereka semua dan makin masyhurlah nama Tuhan Yesus."
  },
  {Bible:"Acts", Chapter:19, Verse:18, Page:1,
    Kor:"그리고 신도가 된 많은 사람이 와서, 자기들이 한 일을 자백하고 공개하였다.",
    Chn:"那已经信的，多有人来承认诉说自己所行的事。",
    Eng:"Many of those who believed now came and openly confessed their evil deeds.",
    Ind:"Banyak di antara mereka yang telah menjadi percaya, datang dan mengaku di muka umum, bahwa mereka pernah turut melakukan perbuatan-perbuata seperti itu."
  },
  {Bible:"Acts", Chapter:19, Verse:19, Page:1,
    Kor:"또 마술을 부리던 많은 사람이 그들의 책을 모아서, 모든 사람 앞에서 불살랐다. 책값을 계산하여 보니, 은돈 오만 닢에 맞먹었다.",
    Chn:"平素行邪术的，也有许多人把书拿来，堆积在众人面前焚烧。他们算计书价，便知道共合五万块钱。",
    Eng:"A number who had practiced sorcery brought their scrolls together and burned them publicly. When they calculated the value of the scrolls, the total came to fifty thousand drachmas.",
    Ind:"Banyak juga di antara mereka, yang pernah melakukan sihir, mengumpulkan kitab-kitabnya lalu membakarnya di depan mata semua orang. Nilai kitab-kitab itu ditaksir lima puluh ribu uang perak."
  },
  {Bible:"Acts", Chapter:19, Verse:20, Page:1,
    Kor:"이렇게 하여 주님의 말씀이 능력 있게 퍼져 나가고, 점점 힘을 떨쳤다.",
    Chn:"主的道大大兴旺，而且得胜，就是这样。",
    Eng:"In this way the word of the Lord spread widely and grew in power.",
    Ind:"Dengan jalan ini makin tersiarlah firman Tuhan dan makin berkuasa."
  },
  {Bible:"Acts", Chapter:19, Verse:21, Page:1,
    Kor:"<에베소에서 일어난 소동> ○이런 일이 있은 뒤에, 바울은 마케도니아와 아가야를 거쳐 예루살렘으로 가기로 마음에 작정하고 \"나는 거기에 갔다가, 로마에도 꼭 가 보아야 하겠습니다\" 하고 말하였다.",
    Chn:"这些事完了，保罗心里定意经过了马其顿、亚该亚，就往耶路撒冷去；又说：「我到了那里以后，也必须往罗马去看看。」",
    Eng:"After all this had happened, Paul decided to go to Jerusalem, passing through Macedonia and Achaia. \"After I have been there,\" he said, \"I must visit Rome also.\"",
    Ind:"Kemudian dari pada semuanya itu Paulus bermaksud pergi ke Yerusalem melalui Makedonia dan Akhaya. Katanya: \"Sesudah berkunjung ke situ aku harus melihat Roma juga.\""
  },
  {Bible:"Acts", Chapter:19, Verse:22, Page:1,
    Kor:"그래서 자기를 돕는 사람들 가운데서 디모데와 에라스도 두 사람을 마케도니아로 보내고, 자기는 얼마 동안 e아시아에 더 머물러 있었다.(e 오늘날의 소아시아의 서남부에 위치한 로마의 행정 구역인 아시아 주를 가리킴)",
    Chn:"于是从帮助他的人中打发提摩太、以拉都二人往马其顿去，自己暂时等在亚细亚。",
    Eng:"He sent two of his helpers, Timothy and Erastus, to Macedonia, while he stayed in the province of Asia a little longer.",
    Ind:"Lalu ia menyuruh dua orang pembantunya, yaitu Timotius dan Erastus, mendahuluinya ke Makedonia, tetapi ia sendiri tinggal beberapa lama lagi di Asia."
  },
  {Bible:"Acts", Chapter:19, Verse:23, Page:1,
    Kor:"○그 무렵에 주님의 '도' 때문에 적지 않은 소동이 일어났다.",
    Chn:"那时，因为这道起的扰乱不小。",
    Eng:"About that time there arose a great disturbance about the Way.",
    Ind:"Kira-kira pada waktu itu timbul huru-hara besar mengenai Jalan Tuhan."
  },
  {Bible:"Acts", Chapter:19, Verse:24, Page:1,
    Kor:"데메드리오라고 하는 은장이가 은으로 아데미 여신의 모형 신전들을 만들어서, 직공들에게 적지 않은 돈벌이를 시켜주었다.",
    Chn:"有一个银匠，名叫底米丢，是制造亚底米神银龛的，他使这样手艺人生意发达。",
    Eng:"A silversmith named Demetrius, who made silver shrines of Artemis, brought in no little business for the craftsmen.",
    Ind:"Sebab ada seorang bernama Demetrius, seorang tukang perak, yang membuat kuil-kuilan dewi Artemis dari perak. Usahanya itu mendatangkan penghasilan yang tidak sedikit bagi tukang-tukangnya."
  },
  {Bible:"Acts", Chapter:19, Verse:25, Page:1,
    Kor:"그가 직공들과 이런 일에 종사하는 사람들을 모아 놓고 말하였다. \"여러분, 여러분이 아시는 바와 같이, 우리는 이 사업으로 잘 살고 있습니다.",
    Chn:"他聚集他们和同行的工人，说：「众位，你们知道我们是倚靠这生意发财。",
    Eng:"He called them together, along with the workmen in related trades, and said: \"Men, you know we receive a good income from this business.",
    Ind:"Ia mengumpulkan mereka bersama-sama dengan pekerja-pekerja lain dalam perusahaan itu dan berkata: \"Saudara-saudara, kamu tahu, bahwa kemakmuran kita adalah hasil perusahaan ini!"
  },
  {Bible:"Acts", Chapter:19, Verse:26, Page:1,
    Kor:"그런데 여러분이 보고 듣는 대로, 바울이라는 이 사람이 에베소에서뿐만 아니라, 거의 온 e아시아에 걸쳐서, 사람의 손으로 만든 신은 신이 아니라고 말하면서, 많은 사람을 설득해서 마음을 돌려놓았습니다.(e 오늘날의 소아시아의 서남부에 위치한 로마의 행정 구역인 아시아 주를 가리킴)",
    Chn:"这保罗不但在以弗所，也几乎在亚细亚全地，引诱迷惑许多人，说：『人手所做的，不是神。』这是你们所看见所听见的。",
    Eng:"And you see and hear how this fellow Paul has convinced and led astray large numbers of people here in Ephesus and in practically the whole province of Asia. He says that man-made gods are no gods at all.",
    Ind:"Sekarang kamu sendiri melihat dan mendengar, bagaimana Paulus, bukan saja di Efesus, tetapi juga hampir di seluruh Asia telah membujuk dan menyesatkan banyak orang dengan mengatakan, bahwa apa yang dibuat oleh tangan manusia bukanlah dewa."
  },
  {Bible:"Acts", Chapter:19, Verse:27, Page:1,
    Kor:"그러니 우리의 이 사업이 명성을 잃을 위험이 있을 뿐만 아니라, 위대한 아데미 여신의 신전도 무시당하고, 또 나아가서는 온 e아시아와 온 세계가 숭배하는 이 여신의 위신이 땅에 떨어지고 말 위험이 있습니다.\"(e 오늘날의 소아시아의 서남부에 위치한 로마의 행정 구역인 아시아 주를 가리킴)",
    Chn:"这样，不独我们这事业被人藐视，就是大女神亚底米的庙也要被人轻忽，连亚细亚全地和普天下所敬拜的大女神之威荣也要消灭了。」",
    Eng:"There is danger not only that our trade will lose its good name, but also that the temple of the great goddess Artemis will be discredited, and the goddess herself, who is worshiped throughout the province of Asia and the world, will be robbed of her divine majesty.\"",
    Ind:"Dengan jalan demikian bukan saja perusahaan kita berada dalam bahaya untuk dihina orang, tetapi juga kuil Artemis, dewi besar itu, berada dalam bahaya akan kehilangan artinya. Dan Artemis sendiri, Artemis yang disembah oleh seluruh Asia dan seluruh dunia yang beradab, akan kehilangan kebesarannya.\""
  },
  {Bible:"Acts", Chapter:19, Verse:28, Page:1,
    Kor:"○거기에 서 있는 사람들이 이 말을 듣고 격분해서 \"에베소 사람의 아데미 여신은 위대하다!\" 하고 소리를 질렀다.",
    Chn:"众人听见，就怒气填胸，喊着说：「大哉，以弗所人的亚底米啊！」",
    Eng:"When they heard this, they were furious and began shouting: \"Great is Artemis of the Ephesians!\"",
    Ind:"Mendengar itu meluaplah amarah mereka, lalu mereka berteriak-teriak, katanya: \"Besarlah Artemis dewi orang Efesus!\""
  },
  {Bible:"Acts", Chapter:19, Verse:29, Page:1,
    Kor:"그래서 온 도시는 큰 혼란에 빠졌고, 군중이 바울의 동행자들인 마케도니아 사람 가이오와 아리스다고를 붙잡아서 한꺼번에 극장으로 몰려 들어갔다.",
    Chn:"满城都轰动起来。众人拿住与保罗同行的马其顿人该犹和亚里达古，齐心拥进戏园里去。",
    Eng:"Soon the whole city was in an uproar. The people seized Gaius Aristarchus, Paul's traveling companions from Macedonia, and rushed as one man into the theater.",
    Ind:"Seluruh kota menjadi kacau dan mereka ramai-ramai membanjiri gedung kesenian serta menyeret Gayus dan Aristarkhus, keduanya orang Makedonia dan teman seperjalanan Paulus."
  },
  {Bible:"Acts", Chapter:19, Verse:30, Page:1,
    Kor:"바울이 군중 속에 들어가려고 하였으나, 제자들이 그것을 말렸다.",
    Chn:"保罗想要进去，到百姓那里，门徒却不许他去。",
    Eng:"Paul wanted to appear before the crowd, but the disciples would not let him.",
    Ind:"Paulus mau pergi ke tengah-tengah rakyat itu, tetapi murid-muridnya tidak mengizinkannya."
  },
  {Bible:"Acts", Chapter:19, Verse:31, Page:1,
    Kor:"바울에게 호감을 가진 f아시아의 몇몇 고관들도 사람을 보내서, 바울에게 극장에 들어가지 말라고 권하였다.(f 아시아의 제의 동맹의 대제관들인 듯함)",
    Chn:"还有亚细亚几位首领，是保罗的朋友，打发人来劝他，不要冒险到戏园里去。",
    Eng:"Even some of the officials of the province, friends of Paul, sent him a message begging him not to venture into the theater.",
    Ind:"Bahkan beberapa pembesar yang berasal dari Asia yang bersahabat dengan Paulus, mengirim peringatan kepadanya, supaya ia jangan masuk ke gedung kesenian itu."
  },
  {Bible:"Acts", Chapter:19, Verse:32, Page:1,
    Kor:"극장 안에서는, 더러는 이렇게 외치고, 더러는 저렇게 외치는 바람에, 모임은 혼란에 빠지고, 무엇 때문에 자기들이 모여들었는지조차 알지 못하는 사람이 많았다.",
    Chn:"聚集的人纷纷乱乱，有喊叫这个的，有喊叫那个的；大半不知道是为什么聚集。",
    Eng:"The assembly was in confusion: Some were shouting one thing, some another. Most of the people did not even know why they were there.",
    Ind:"Sementara itu orang yang berkumpul di dalam gedung itu berteriak-teriak; yang seorang mengatakan ini dan yang lain mengatakan itu, sebab kumpulan itu kacau-balau dan kebanyakan dari mereka tidak tahu untuk apa mereka berkumpul."
  },
  {Bible:"Acts", Chapter:19, Verse:33, Page:1,
    Kor:"유대 사람들이 알렉산더를 앞으로 밀어내니, 군중 가운데서 몇 사람이 그를 다그쳤다. 알렉산더가 조용히 해 달라고 손짓을 하고서, 군중에게 변명하려고 하였다.",
    Chn:"有人把亚历山大从众人中带出来，犹太人推他往前，亚历山大就摆手，要向百姓分诉；",
    Eng:"The Jews pushed Alexander to the front, and some of the crowd shouted instructions to him. He motioned for silence in order to make a defense before the people.",
    Ind:"Lalu seorang bernama Aleksander didorong ke depan oleh orang-orang Yahudi. Ia mendapat keterangan dari orang banyak tentang apa yang terjadi. Segera ia memberi isyarat dengan tangannya dan mau memberi penjelasan sebagai pembelaan di depan rakyat itu."
  },
  {Bible:"Acts", Chapter:19, Verse:34, Page:1,
    Kor:"그러나 군중은 알렉산더가 유대 사람인 것을 알고는, 모두 한 목소리로 거의 두 시간 동안이나 \"에베소 사람의 아데미 여신은 위대하다!\" 하고 외쳤다.",
    Chn:"只因他们认出他是犹太人，就大家同声喊着说：「大哉！以弗所人的亚底米啊。」如此约有两小时。",
    Eng:"But when they realized he was a Jew, they all shouted in unison for about two hours: \"Great is Artemis of the Ephesians!\"",
    Ind:"Tetapi ketika mereka tahu, bahwa ia adalah orang Yahudi, berteriaklah mereka bersama-sama kira-kira dua jam lamanya: \"Besarlah Artemis dewi orang Efesus!\""
  },
  {Bible:"Acts", Chapter:19, Verse:35, Page:1,
    Kor:"드디어 시청 서기관이 무리를 진정시키고 나서 말하였다. \"에베소 시민 여러분, 우리의 도시 에베소가 위대한 아데미 여신과 하늘에서 내린 그 신상을 모신 신전 수호자임을 모르는 사람이 어디 있습니까?",
    Chn:"那城里的书记安抚了众人，就说：「以弗所人哪，谁不知道以弗所人的城是看守大亚底米的庙和从宙斯那里落下来的像呢？",
    Eng:"The city clerk quieted the crowd and said: \"Men of Ephesus, doesn't all the world know that the city of Ephesus is the guardian of the temple of the great Artemis and of her image, which fell from heaven?",
    Ind:"Akan tetapi panitera kota menenangkan orang banyak itu dan berkata: \"Hai orang Efesus! Siapakah di dunia ini yang tidak tahu, bahwa kota Efesuslah yang memelihara baik kuil dewi Artemis, yang mahabesar, maupun patungnya yang turun dari langit?"
  },
  {Bible:"Acts", Chapter:19, Verse:36, Page:1,
    Kor:"이것은 부인할 수 없는 사실이니, 여러분은 마땅히 진정하고, 절대로 경솔한 행동을 해서는 안됩니다.",
    Chn:"这事既是驳不倒的，你们就当安静，不可造次。",
    Eng:"Therefore, since these facts are undeniable, you ought to be quiet and not do anything rash.",
    Ind:"Hal itu tidak dapat dibantah, karena itu hendaklah kamu tenang dan janganlah terburu-buru bertindak."
  },
  {Bible:"Acts", Chapter:19, Verse:37, Page:1,
    Kor:"신전 물건을 도둑질한 사람도 아니요 g우리 여신을 모독한 사람도 아닌 이 사람들을, 여러분은 여기에 끌고 왔습니다.(g 다른 고대 사본들에는 '너희의')",
    Chn:"你们把这些人带来，他们并没有偷窃庙中之物，也没有谤 我们的女神。",
    Eng:"You have brought these men here, though they have neither robbed temples nor blasphemed our goddess.",
    Ind:"Sebab kamu telah membawa orang-orang ini ke sini, walaupun mereka tidak merampok kuil dewi kita dan tidak menghujat namanya."
  },
  {Bible:"Acts", Chapter:19, Verse:38, Page:1,
    Kor:"그러므로 데메드리오와 그와 함께 있는 직공들이 누구를 걸어서 송사할 일이 있으면, 재판정도 열려 있고, 총독들도 있으니, 당사자들이 서로 고소도 하고, 맞고소도 해야 할 것입니다.",
    Chn:"若是底米丢和他同行的人有控告人的事，自有放告的日子，也有方伯可以彼此对告。",
    Eng:"If, then, Demetrius and his fellow craftsmen have a grievance against anybody, the courts are open and there are proconsuls. They can press charges.",
    Ind:"Jadi jika Demetrius dan tukang-tukangnya ada pengaduannya terhadap seseorang, bukankah ada sidang-sidang pengadilan dan ada gubernur, jadi hendaklah kedua belah pihak mengajukan dakwaannya ke situ."
  },
  {Bible:"Acts", Chapter:19, Verse:39, Page:1,
    Kor:"여러분이 이 이상으로 해결하고자 하는 어떤 문제가 있으면, 그것은 정식 집회에서 처리되어야 할 것입니다.",
    Chn:"你们若问别的事，就可以照常例聚集断定。",
    Eng:"If there is anything further you want to bring up, it must be settled in a legal assembly.",
    Ind:"Dan jika ada sesuatu yang lain yang kamu kehendaki, baiklah kehendakmu itu diselesaikan dalam sidang rakyat yang sah."
  },
  {Bible:"Acts", Chapter:19, Verse:40, Page:1,
    Kor:"우리는 오늘 일어난 이 일 때문에, 소요죄로 문책을 받을 위험이 있습니다. 우리는 이 소요를 정당화할 수 있는 아무런 명분이 없습니다.\"",
    Chn:"今日的扰乱本是无缘无故，我们难免被查问。论到这样聚众，我们也说不出所以然来。」",
    Eng:"As it is, we are in danger of being charged with rioting because of today's events. In that case we would not be able to account for this commotion, since there is no reason for it.\"",
    Ind:"Sebab kita berada dalam bahaya akan dituduh, bahwa kita menimbulkan huru-hara pada hari ini, karena tidak ada alasan yang dapat kita kemukakan untuk membenarkan kumpulan yang kacau-balau ini.\""
  },
  {Bible:"Acts", Chapter:19, Verse:41, Page:1,
    Kor:"이렇게 말하고서, 그는 모임을 해산시켰다.h(h 원문에는 41절이 없다)",
    Chn:"说了这话，便叫众人散去。",
    Eng:"After he had said this, he dismissed the assembly.",
    Ind:"(19-40b) Dan dengan kata-kata itu ia membubarkan kumpulan rakyat itu."
  },
]);
