// 사도행전 17장 · Acts 17
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Acts",17,34);
BibleDB.add([
  {Bible:"Acts", Chapter:17, Verse:1, Page:1,
    Kor:"<바울이 데살로니가에서 전도하다> a바울 일행은 암비볼리와 아볼로니아를 거쳐서, 데살로니가에 이르렀다. 거기에는, 유대 사람의 회당이 있었다.(a 그, '그들은')",
    Chn:"保罗和西拉经过暗妃坡里、亚波罗尼亚，来到帖撒罗尼迦，在那里有犹太人的会堂。",
    Eng:"When they had passed through Amphipolis and Apollonia, they came to Thessalonica, where there was a Jewish synagogue.",
    Ind:"Paulus dan Silas mengambil jalan melalui Amfipolis dan Apolonia dan tiba di Tesalonika. Di situ ada sebuah rumah ibadat orang Yahudi."
  },
  {Bible:"Acts", Chapter:17, Verse:2, Page:1,
    Kor:"바울은 자기 관례대로 회당으로 그들을 찾아가서, 세 안식일에 걸쳐 성경을 가지고 그들과 토론하였다.",
    Chn:"保罗照他素常的规矩进去，一连三个安息日，本着圣经与他们辩论，",
    Eng:"As his custom was, Paul went into the synagogue, and on three Sabbath days he reasoned with them from the Scriptures,",
    Ind:"Seperti biasa Paulus masuk ke rumah ibadat itu. Tiga hari Sabat berturut-turut ia membicarakan dengan mereka bagian-bagian dari Kitab Suci."
  },
  {Bible:"Acts", Chapter:17, Verse:3, Page:1,
    Kor:"그는, b그리스도께서 반드시 고난을 당하시고 죽은 사람들 가운데서 살아나셔야 한다는 것을 해석하고 증명하면서 \"내가 여러분에게 전하고 있는 예수가 바로 그 b그리스도이십니다\" 하고 말하였다.(b 또는 '메시아')",
    Chn:"讲解陈明基督必须受害，从死里复活；又说：「我所传与你们的这位耶稣就是基督。」",
    Eng:"explaining and proving that the Christ had to suffer and rise from the dead. \"This Jesus I am proclaiming to you is the Christ,\" he said.",
    Ind:"Ia menerangkannya kepada mereka dan menunjukkan, bahwa Mesias harus menderita dan bangkit dari antara orang mati, lalu ia berkata: \"Inilah Mesias, yaitu Yesus, yang kuberitakan kepadamu.\""
  },
  {Bible:"Acts", Chapter:17, Verse:4, Page:1,
    Kor:"그들 가운데 몇몇 사람이 승복하여 바울과 실라를 따르고, 또 많은 경건한 그리스 사람들과 적지 않은 귀부인들이 그렇게 하였다.",
    Chn:"他们中间有些人听了劝，就附从保罗和西拉，并有许多虔敬的希腊人，尊贵的妇女也不少。",
    Eng:"Some of the Jews were persuaded and joined Paul and Silas, as did a large number of God-fearing Greeks and not a few prominent women.",
    Ind:"Beberapa orang dari mereka menjadi yakin dan menggabungkan diri dengan Paulus dan Silas dan juga sejumlah besar orang Yunani yang takut kepada Allah, dan tidak sedikit perempuan-perempuan terkemuka."
  },
  {Bible:"Acts", Chapter:17, Verse:5, Page:1,
    Kor:"그러나 유대 사람들은 시기하여, 거리의 불량배들을 끌어 모아다가 패거리를 지어서 시내에 소요를 일으키고 야손의 집을 습격하였다. 그리고 바울 일행을 끌어다가 군중 앞에 세우려고 찾았다.",
    Chn:"但那不信的犹太人心里嫉妒，招聚了些市井匪类，搭伙成群，耸动合城的人闯进耶孙的家，要将保罗、西拉带到百姓那里。",
    Eng:"But the Jews were jealous; so they rounded up some bad characters from the marketplace, formed a mob and started a riot in the city. They rushed to Jason's house in search of Paul and Silas in order to bring them out to the crowd.",
    Ind:"Tetapi orang-orang Yahudi menjadi iri hati dan dengan dibantu oleh beberapa penjahat dari antara petualang-petualang di pasar, mereka mengadakan keributan dan mengacau kota itu. Mereka menyerbu rumah Yason dengan maksud untuk menghadapkan Paulus dan Silas kepada sidang rakyat."
  },
  {Bible:"Acts", Chapter:17, Verse:6, Page:1,
    Kor:"그러나 그들을 찾지 못하고, 야손과 c신도 몇 사람을 d시청 관원들에게 끌고 가서, 큰 소리로 외쳤다. \"세상을 소란하게 한 그 사람들이 여기에도 나타났습니다.(c 그, '형제들' d 그, '폴리트아르케스')",
    Chn:"找不着他们，就把耶孙和几个弟兄拉到地方官那里，喊叫说：「那搅乱天下的也到这里来了，",
    Eng:"But when they did not find them, they dragged Jason and some other brothers before the city officials, shouting: \"These men who have caused trouble all over the world have now come here,",
    Ind:"Tetapi ketika mereka tidak menemukan keduanya, mereka menyeret Yason dan beberapa saudara ke hadapan pembesar-pembesar kota, sambil berteriak, katanya: \"Orang-orang yang mengacaukan seluruh dunia telah datang juga ke mari,"
  },
  {Bible:"Acts", Chapter:17, Verse:7, Page:1,
    Kor:"그런데 야손이 그들을 영접하였습니다. 그 사람들은 모두 예수라는 또 다른 왕이 있다고 말하면서, e황제의 명령을 거슬러 행동을 합니다.\"(e 그, '가이사', 라틴어의 그리스어 음역. 로마 황제의 칭호)",
    Chn:"耶孙收留他们。这些人都违背凯撒的命令，说另有一个王耶稣。」",
    Eng:"and Jason has welcomed them into his house. They are all defying Caesar's decrees, saying that there is another king, one called Jesus.\"",
    Ind:"dan Yason menerima mereka menumpang di rumahnya. Mereka semua bertindak melawan ketetapan-ketetapan Kaisar dengan mengatakan, bahwa ada seorang raja lain, yaitu Yesus.\""
  },
  {Bible:"Acts", Chapter:17, Verse:8, Page:1,
    Kor:"군중과 시청 관원들이 이 말을 듣고 소동하였다.",
    Chn:"众人和地方官听见这话，就惊慌了；",
    Eng:"When they heard this, the crowd and the city officials were thrown into turmoil.",
    Ind:"Ketika orang banyak dan pembesar-pembesar kota mendengar semuanya itu, mereka menjadi gelisah."
  },
  {Bible:"Acts", Chapter:17, Verse:9, Page:1,
    Kor:"그러나 시청 관원들은 야손과 그 밖의 사람들에게서 보석금을 받고 놓아주었다.",
    Chn:"于是取了耶孙和其余之人的保状，就释放了他们。",
    Eng:"Then they made Jason and the others post bond and let them go.",
    Ind:"Tetapi setelah mereka mendapat jaminan dari Yason dan dari saudara-saudara lain, merekapun dilepaskan."
  },
  {Bible:"Acts", Chapter:17, Verse:10, Page:1,
    Kor:"<바울이 베뢰아에서 전도하다> ○c신도들은 곧 바로 그날 밤으로 바울과 실라를 베뢰아로 보냈다. 두 사람은 거기에 이르러서, 유대 사람의 회당으로 들어갔다.(c 그, '형제들')",
    Chn:"弟兄们随即在夜间打发保罗和西拉往庇哩亚去。二人到了，就进入犹太人的会堂。",
    Eng:"As soon as it was night, the brothers sent Paul and Silas away to Berea. On arriving there, they went to the Jewish synagogue.",
    Ind:"Tetapi pada malam itu juga segera saudara-saudara di situ menyuruh Paulus dan Silas berangkat ke Berea. Setibanya di situ pergilah mereka ke rumah ibadat orang Yahudi."
  },
  {Bible:"Acts", Chapter:17, Verse:11, Page:1,
    Kor:"베뢰아의 유대 사람들은 데살로니가의 유대 사람들보다 더 고상한 사람들이어서, 아주 기꺼이 말씀을 받아들이고, 그것이 사실인지 알아보려고, 날마다 성경을 상고하였다.",
    Chn:"这地方的人贤于帖撒罗尼迦的人，甘心领受这道，天天考查圣经，要晓得这道是与不是。",
    Eng:"Now the Bereans were of more noble character than the Thessalonians, for they received the message with great eagerness and examined the Scriptures every day to see if what Paul said was true.",
    Ind:"Orang-orang Yahudi di kota itu lebih baik hatinya dari pada orang-orang Yahudi di Tesalonika, karena mereka menerima firman itu dengan segala kerelaan hati dan setiap hari mereka menyelidiki Kitab Suci untuk mengetahui, apakah semuanya itu benar demikian."
  },
  {Bible:"Acts", Chapter:17, Verse:12, Page:1,
    Kor:"따라서, 그들 가운데서 믿게 된 사람이 많이 생겼다. 또 지체가 높은 그리스 여자들과 남자들 가운데서도 믿게 된 사람이 적지 않았다.",
    Chn:"所以他们中间多有相信的，又有希腊尊贵的妇女，男子也不少。",
    Eng:"Many of the Jews believed, as did also a number of prominent Greek women and many Greek men.",
    Ind:"Banyak di antara mereka yang menjadi percaya; juga tidak sedikit di antara perempuan-perempuan terkemuka dan laki-laki Yunani."
  },
  {Bible:"Acts", Chapter:17, Verse:13, Page:1,
    Kor:"데살로니가의 유대 사람들은, 바울이 베뢰아에서도 하나님의 말씀을 전하는 것을 알고서, 거기에도 가서, 무리를 선동하여 소동을 벌였다.",
    Chn:"但帖撒罗尼迦的犹太人知道保罗又在庇哩亚传　神的道，也就往那里去，耸动搅扰众人。",
    Eng:"When the Jews in Thessalonica learned that Paul was preaching the word of God at Berea, they went there too, agitating the crowds and stirring them up.",
    Ind:"Tetapi ketika orang-orang Yahudi dari Tesalonika tahu, bahwa juga di Berea telah diberitakan firman Allah oleh Paulus, datang jugalah mereka ke sana menghasut dan menggelisahkan hati orang banyak."
  },
  {Bible:"Acts", Chapter:17, Verse:14, Page:1,
    Kor:"그 때에 c신도들이 곧바로 바울을 바닷가로 떠나보냈다. 그러나 실라와 디모데는 거기에 그대로 남아 있었다.(c 그, '형제들')",
    Chn:"当时弟兄们便打发保罗往海边去，西拉和提摩太仍住在庇哩亚。",
    Eng:"The brothers immediately sent Paul to the coast, but Silas and Timothy stayed at Berea.",
    Ind:"Tetapi saudara-saudara menyuruh Paulus segera berangkat menuju ke pantai laut, tetapi Silas dan Timotius masih tinggal di Berea."
  },
  {Bible:"Acts", Chapter:17, Verse:15, Page:1,
    Kor:"바울을 안내하는 사람들이 바울을 아테네까지 인도하였다. 그들은 바울에게서, 실라와 디모데가 할 수 있는 대로 빨리 그에게로 와야 한다는 지시를 받아 가지고, 베뢰아로 떠나갔다.",
    Chn:"送保罗的人带他到了雅典，既领了保罗的命，叫西拉和提摩太速速到他这里来，就回去了。",
    Eng:"The men who escorted Paul brought him to Athens and then left with instructions for Silas and Timothy to join him as soon as possible.",
    Ind:"Orang-orang yang mengiringi Paulus menemaninya sampai di Atena, lalu kembali dengan pesan kepada Silas dan Timotius, supaya mereka selekas mungkin datang kepadanya."
  },
  {Bible:"Acts", Chapter:17, Verse:16, Page:1,
    Kor:"<바울이 아테네에서 전도하다> ○바울은, 아테네에서 그들을 기다리고 있는 동안에, 온 도시가 우상으로 가득 차 있는 것을 보고 격분하였다.",
    Chn:"保罗在雅典等候他们的时候，看见满城都是偶像，就心里着急；",
    Eng:"While Paul was waiting for them in Athens, he was greatly distressed to see that the city was full of idols.",
    Ind:"Sementara Paulus menantikan mereka di Atena, sangat sedih hatinya karena ia melihat, bahwa kota itu penuh dengan patung-patung berhala."
  },
  {Bible:"Acts", Chapter:17, Verse:17, Page:1,
    Kor:"그래서 바울은 회당에서는 유대 사람들과 이방 사람 예배자들과 더불어 토론을 벌였고, 또한 f광장에서는 만나는 사람들과 날마다 토론하였다.(f 그, '아고라(시의 중심지)')",
    Chn:"于是在会堂里与犹太人和虔敬的人，并每日在市上所遇见的人，辩论。",
    Eng:"So he reasoned in the synagogue with the Jews and the God-fearing Greeks, as well as in the marketplace day by day with those who happened to be there.",
    Ind:"Karena itu di rumah ibadat ia bertukar pikiran dengan orang-orang Yahudi dan orang-orang yang takut akan Allah, dan di pasar setiap hari dengan orang-orang yang dijumpainya di situ."
  },
  {Bible:"Acts", Chapter:17, Verse:18, Page:1,
    Kor:"그리고 몇몇 에피쿠로스 철학자와 스토아 철학자도 바울과 논쟁하였는데, 그 가운데서 몇몇 사람은 \"이 말쟁이가 도대체 무슨 소리를 하려는 것인가?\" 하고 말하는가 하면, 또 몇몇 사람은 \"그는 외국 신들을 선전하는 사람인 것 같다\" 하고 말하기도 하였다. 그것은 바울이 예수를 전하고 부활을 전하기 때문이었다.",
    Chn:"还有伊壁鸠鲁和斯多亚两门的学士，与他争论。有的说：「这胡言乱语的要说什么？」有的说：「他似乎是传说外邦鬼神的。」这话是因保罗传讲耶稣与复活的道。",
    Eng:"A group of Epicurean and Stoic philosophers began to dispute with him. Some of them asked, \"What is this babbler trying to say?\" Others remarked, \"He seems to be advocating foreign gods.\" They said this because Paul was preaching the good news about Jesus and the resurrection.",
    Ind:"Dan juga beberapa ahli pikir dari golongan Epikuros dan Stoa bersoal jawab dengan dia dan ada yang berkata: \"Apakah yang hendak dikatakan si peleter ini?\" Tetapi yang lain berkata: \"Rupa-rupanya ia adalah pemberita ajaran dewa-dewa asing.\" Sebab ia memberitakan Injil tentang Yesus dan tentang kebangkitan-Nya."
  },
  {Bible:"Acts", Chapter:17, Verse:19, Page:1,
    Kor:"그들은 바울을 붙들어, 아레오바고 법정으로 데리고 가서 \"당신이 말하는 이 새로운 교훈이 무엇인지 우리가 알 수 있겠소?",
    Chn:"他们就把他带到亚略·巴古，说：「你所讲的这新道，我们也可以知道吗？",
    Eng:"Then they took him and brought him to a meeting of the Areopagus, where they said to him, \"May we know what this new teaching is that you are presenting?",
    Ind:"Lalu mereka membawanya menghadap sidang Areopagus dan mengatakan: \"Bolehkah kami tahu ajaran baru mana yang kauajarkan ini?"
  },
  {Bible:"Acts", Chapter:17, Verse:20, Page:1,
    Kor:"당신은 우리 귀에 생소한 것을 소개하고 있는데, 도대체 그것이 무엇인지 알고 싶소\" 하고 말하였다.",
    Chn:"因为你有些奇怪的事传到我们耳中，我们愿意知道这些事是什么意思。」（",
    Eng:"You are bringing some strange ideas to our ears, and we want to know what they mean.\"",
    Ind:"Sebab engkau memperdengarkan kepada kami perkara-perkara yang aneh. Karena itu kami ingin tahu, apakah artinya semua itu.\""
  },
  {Bible:"Acts", Chapter:17, Verse:21, Page:1,
    Kor:"모든 아테네 사람과 거기에 살고 있는 외국 사람들은, 무엇이나 새로운 것을 말하고 듣는 일로만 세월을 보내는 사람들이었다.",
    Chn:"雅典人和住在那里的客人都不顾别的事，只将新闻说说听听。）",
    Eng:"(All the Athenians and the foreigners who lived there spent their time doing nothing but talking about and listening to the latest ideas.)",
    Ind:"Adapun orang-orang Atena dan orang-orang asing yang tinggal di situ tidak mempunyai waktu untuk sesuatu selain untuk mengatakan atau mendengar segala sesuatu yang baru."
  },
  {Bible:"Acts", Chapter:17, Verse:22, Page:1,
    Kor:"○바울이 아레오바고 법정 가운데 서서, 이렇게 말하였다. \"아테네 시민 여러분, 내가 보기에, 여러분은 모든 면에서 종교심이 많습니다.",
    Chn:"保罗站在亚略·巴古当中，说：「众位雅典人哪，我看你们凡事很敬畏鬼神。",
    Eng:"Paul then stood up in the meeting of the Areopagus and said: \"Men of Athens! I see that in every way you are very religious.",
    Ind:"Paulus pergi berdiri di atas Areopagus dan berkata: \"Hai orang-orang Atena, aku lihat, bahwa dalam segala hal kamu sangat beribadah kepada dewa-dewa."
  },
  {Bible:"Acts", Chapter:17, Verse:23, Page:1,
    Kor:"내가 다니면서, 여러분이 예배하는 대상들을 살펴보는 가운데, '알지 못하는 신에게'라고 새긴 제단도 보았습니다. 그러므로 나는 여러분이 알지 못하고 예배하는 그 대상을 여러분에게 알려 드리겠습니다.",
    Chn:"我游行的时候，观看你们所敬拜的，遇见一座坛，上面写着『未识之神』。你们所不认识而敬拜的，我现在告诉你们。",
    Eng:"For as I walked around and looked carefully at your objects of worship, I even found an altar with this inscription: TO AN UNKNOWN GOD. Now what you worship as something unknown I am going to proclaim to you.",
    Ind:"Sebab ketika aku berjalan-jalan di kotamu dan melihat-lihat barang-barang pujaanmu, aku menjumpai juga sebuah mezbah dengan tulisan: Kepada Allah yang tidak dikenal. Apa yang kamu sembah tanpa mengenalnya, itulah yang kuberitakan kepada kamu."
  },
  {Bible:"Acts", Chapter:17, Verse:24, Page:1,
    Kor:"우주와 그 안에 있는 모든 것을 창조하신 하나님께서는 하늘과 땅의 주님이시므로, 사람의 손으로 지은 신전에 거하지 않으십니다.",
    Chn:"创造宇宙和其中万物的　神，既是天地的主，就不住人手所造的殿，",
    Eng:"\"The God who made the world and everything in it is the Lord of heaven and earth and does not live in temples built by hands.",
    Ind:"Allah yang telah menjadikan bumi dan segala isinya, Ia, yang adalah Tuhan atas langit dan bumi, tidak diam dalam kuil-kuil buatan tangan manusia,"
  },
  {Bible:"Acts", Chapter:17, Verse:25, Page:1,
    Kor:"또 하나님께서는, 무슨 부족한 것이라도 있어서 사람의 손으로 섬김을 받으시는 것이 아닙니다. 그분은 모든 사람에게 생명과 호흡과 모든 것을 주시는 분이십니다.",
    Chn:"也不用人手服事，好像缺少什么；自己倒将生命、气息、万物，赐给万人。",
    Eng:"And he is not served by human hands, as if he needed anything, because he himself gives all men life and breath and everything else.",
    Ind:"dan juga tidak dilayani oleh tangan manusia, seolah-olah Ia kekurangan apa-apa, karena Dialah yang memberikan hidup dan nafas dan segala sesuatu kepada semua orang."
  },
  {Bible:"Acts", Chapter:17, Verse:26, Page:1,
    Kor:"그분은 인류의 모든 족속을 한 혈통으로 만드셔서, 온 땅 위에 살게 하셨으며, 그들이 살 시기와 거주할 지역의 경계를 정해 놓으셨습니다.",
    Chn:"他从一本造出万族的人，住在全地上，并且预先定准他们的年限和所住的疆界，",
    Eng:"From one man he made every nation of men, that they should inhabit the whole earth; and he determined the times set for them and the exact places where they should live.",
    Ind:"Dari satu orang saja Ia telah menjadikan semua bangsa dan umat manusia untuk mendiami seluruh muka bumi dan Ia telah menentukan musim-musim bagi mereka dan batas-batas kediaman mereka,"
  },
  {Bible:"Acts", Chapter:17, Verse:27, Page:1,
    Kor:"이렇게 하신 것은, 사람으로 하여금 g하나님을 찾게 하시려는 것입니다. 사람이 하나님을 더듬어 찾기만 하면, 만날 수 있을 것입니다. 사실, 하나님은 우리 각 사람에게서 멀리 떨어져 계시지 않습니다.(g 다른 고대 사본들에는 '주님을')",
    Chn:"要叫他们寻求　神，或者可以揣摩而得，其实他离我们各人不远；",
    Eng:"God did this so that men would seek him and perhaps reach out for him and find him, though he is not far from each one of us.",
    Ind:"supaya mereka mencari Dia dan mudah-mudahan menjamah dan menemukan Dia, walaupun Ia tidak jauh dari kita masing-masing."
  },
  {Bible:"Acts", Chapter:17, Verse:28, Page:1,
    Kor:"○여러분의 시인 가운데 어떤 이들도  '우리도 하나님의 자녀이다' 하고 말한 바와 같이, 우리는 하나님 안에서 살고, 움직이고, 존재하고 있습니다.",
    Chn:"我们生活、动作、存留，都在乎他。就如你们作诗的，有人说：『我们也是他所生的。』",
    Eng:"'For in him we live and move and have our being.' As some of your own poets have said, 'We are his offspring.'",
    Ind:"Sebab di dalam Dia kita hidup, kita bergerak, kita ada, seperti yang telah juga dikatakan oleh pujangga-pujanggamu: Sebab kita ini dari keturunan Allah juga."
  },
  {Bible:"Acts", Chapter:17, Verse:29, Page:1,
    Kor:"그러므로 하나님의 자녀인 우리는 신을, 사람의 기술과 고안으로 금이나 은이나 돌에다가 새겨서 만든 것과 같다고 생각해서는 안됩니다.",
    Chn:"我们既是　神所生的，就不当以为　神的神性像人用手艺、心思所雕刻的金、银、石。",
    Eng:"\"Therefore since we are God's offspring, we should not think that the divine being is like gold or silver or stone--an image made by man's design and skill.",
    Ind:"Karena kita berasal dari keturunan Allah, kita tidak boleh berpikir, bahwa keadaan ilahi sama seperti emas atau perak atau batu, ciptaan kesenian dan keahlian manusia."
  },
  {Bible:"Acts", Chapter:17, Verse:30, Page:1,
    Kor:"하나님께서는 무지했던 시대에는 눈감아 주셨지만, 이제는 어디에서나 모든 사람에게 회개하라고 명하십니다.",
    Chn:"世人蒙昧无知的时候，　神并不监察，如今却吩咐各处的人都要悔改。",
    Eng:"In the past God overlooked such ignorance, but now he commands all people everywhere to repent.",
    Ind:"Dengan tidak memandang lagi zaman kebodohan, maka sekarang Allah memberitakan kepada manusia, bahwa di mana-mana semua mereka harus bertobat."
  },
  {Bible:"Acts", Chapter:17, Verse:31, Page:1,
    Kor:"그것은, 하나님께서 세계를 정의로 심판하실 날을 정해 놓으셨기 때문입니다. 하나님께서는 자기가 정하신 사람을 내세워서 심판하실 터인데, 그를 죽은 사람들 가운데서 살리심으로, 모든 사람에게 확신을 주셨습니다.\"",
    Chn:"因为他已经定了日子，要借着他所设立的人按公义审判天下，并且叫他从死里复活，给万人作可信的凭据。」",
    Eng:"For he has set a day when he will judge the world with justice by the man he has appointed. He has given proof of this to all men by raising him from the dead.\"",
    Ind:"Karena Ia telah menetapkan suatu hari, pada waktu mana Ia dengan adil akan menghakimi dunia oleh seorang yang telah ditentukan-Nya, sesudah Ia memberikan kepada semua orang suatu bukti tentang hal itu dengan membangkitkan Dia dari antara orang mati.\""
  },
  {Bible:"Acts", Chapter:17, Verse:32, Page:1,
    Kor:"○그들이 죽은 사람들의 부활에 대해서 들었을 때에, 더러는 비웃었으나, 더러는 \"이 일에 관해서 당신의 말을 다시 듣고 싶소\" 하고 말하였다.",
    Chn:"众人听见从死里复活的话，就有讥诮他的；又有人说：「我们再听你讲这个吧！」",
    Eng:"When they heard about the resurrection of the dead, some of them sneered, but others said, \"We want to hear you again on this subject.\"",
    Ind:"Ketika mereka mendengar tentang kebangkitan orang mati, maka ada yang mengejek, dan yang lain berkata: \"Lain kali saja kami mendengar engkau berbicara tentang hal itu.\""
  },
  {Bible:"Acts", Chapter:17, Verse:33, Page:1,
    Kor:"이렇게 바울은 그들을 떠났다.",
    Chn:"于是保罗从他们当中出去了。",
    Eng:"At that, Paul left the Council.",
    Ind:"Lalu Paulus pergi meninggalkan mereka."
  },
  {Bible:"Acts", Chapter:17, Verse:34, Page:1,
    Kor:"그러나 몇몇 사람은 바울 편에 가담하여 신자가 되었다. 그 가운데는 아레오바고 법정의 판사인 디오누시오도 있었고, 다마리라는 부인도 있었고, 그 밖에 다른 사람들도 있었다.",
    Chn:"但有几个人贴近他，信了主，其中有亚略·巴古的官丢尼修，并一个妇人，名叫大马哩，还有别人一同信从。",
    Eng:"A few men became followers of Paul and believed. Among them was Dionysius, a member of the Areopagus, also a woman named Damaris, and a number of others.",
    Ind:"Tetapi beberapa orang laki-laki menggabungkan diri dengan dia dan menjadi percaya, di antaranya juga Dionisius, anggota majelis Areopagus, dan seorang perempuan bernama Damaris, dan juga orang-orang lain bersama-sama dengan mereka."
  },
]);
