// 창세기 49장 · Genesis 49
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Genesis",49,33);
BibleDB.add([
  {Bible:"Genesis", Chapter:49, Verse:1, Page:1, Kor:"", Chn:"", Eng:"Then Jacob called for his sons and said: \"Gather around so I can tell you what will happen  to you in days to come.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:2, Page:1, Kor:"", Chn:"", Eng:"\"Assemble and listen, sons of Jacob; listen to your father Israel.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:3, Page:1, Kor:"", Chn:"", Eng:"\"Reuben, you are my firstborn, my might, the first sign of my strength, excelling in honor,  excelling in power.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Turbulent as the waters, you will no longer excel, for you went up onto your father's bed,  onto my couch and defiled it.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:5, Page:1, Kor:"", Chn:"", Eng:"\"Simeon and Levi are brothers--their swords are weapons of violence.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:6, Page:1, Kor:"", Chn:"", Eng:"Let me not enter their council, let me not join their assembly, for they have killed men in  their anger and hamstrung oxen as they pleased.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Cursed be their anger, so fierce, and their fury, so cruel! I will scatter them in Jacob and  disperse them in Israel.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:8, Page:1, Kor:"", Chn:"", Eng:"\"Judah, your brothers will praise you; your hand will be on the neck of your enemies; your  father's sons will bow down to you.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:9, Page:1, Kor:"", Chn:"", Eng:"You are a lion's cub, O Judah; you return from the prey, my son. Like a lion he crouches and  lies down, like a lioness--who dares to rouse him?", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:10, Page:1, Kor:"", Chn:"", Eng:"The scepter will not depart from Judah, nor the ruler's staff from between his feet, until  he comes to whom it belongs and the obedience of the nations is his.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:11, Page:1, Kor:"", Chn:"", Eng:"He will tether his donkey to a vine, his colt to the choicest branch; he will wash his  garments in wine, his robes in the blood of grapes.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:12, Page:1, Kor:"", Chn:"", Eng:"His eyes will be darker than wine, his teeth whiter than milk.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:13, Page:1, Kor:"", Chn:"", Eng:"\"Zebulun will live by the seashore and become a haven for ships; his border will extend  toward Sidon.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:14, Page:1, Kor:"", Chn:"", Eng:"\"Issachar is a rawboned donkey lying down between two saddlebags.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:15, Page:1, Kor:"", Chn:"", Eng:"When he sees how good is his resting place and how pleasant is his land, he will bend his  shoulder to the burden and submit to forced labor.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:16, Page:1, Kor:"", Chn:"", Eng:"\"Dan will provide justice for his people as one of the tribes of Israel.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Dan will be a serpent by the roadside, a viper along the path, that bites the horse's heels  so that its rider tumbles backward.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:18, Page:1, Kor:"", Chn:"", Eng:"\"I look for your deliverance, O LORD.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:19, Page:1, Kor:"", Chn:"", Eng:"\"Gad will be attacked by a band of raiders, but he will attack them at their heels.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:20, Page:1, Kor:"", Chn:"", Eng:"\"Asher's food will be rich; he will provide delicacies fit for a king.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:21, Page:1, Kor:"", Chn:"", Eng:"\"Naphtali is a doe set free that bears beautiful fawns.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:22, Page:1, Kor:"", Chn:"", Eng:"\"Joseph is a fruitful vine, a fruitful vine near a spring, whose branches climb over a  wall.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:23, Page:1, Kor:"", Chn:"", Eng:"With bitterness archers attacked him; they shot at him with hostility.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:24, Page:1, Kor:"", Chn:"", Eng:"But his bow remained steady, his strong arms stayed limber, because of the hand of the  Mighty One of Jacob, because of the Shepherd, the Rock of Israel,", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:25, Page:1, Kor:"", Chn:"", Eng:"because of your father's God, who helps you, because of the Almighty, who blesses you with  blessings of the heavens above, blessings of the deep that lies below, blessings of the breast  and womb.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:26, Page:1, Kor:"", Chn:"", Eng:"Your father's blessings are greater than the blessings of the ancient mountains, than the  bounty of the age-old hills. Let all these rest on the head of Joseph, on the brow of the prince  among his brothers.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:27, Page:1, Kor:"", Chn:"", Eng:"\"Benjamin is a ravenous wolf; in the morning he devours the prey, in the evening he divides  the plunder.\"", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:28, Page:1, Kor:"", Chn:"", Eng:"All these are the twelve tribes of Israel, and this is what their father said to them when  he blessed them, giving each the blessing appropriate to him.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Then he gave them these instructions: \"I am about to be gathered to my people. Bury me with  my fathers in the cave in the field of Ephron the Hittite,", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:30, Page:1, Kor:"", Chn:"", Eng:"the cave in the field of Machpelah, near Mamre in Canaan, which Abraham bought as a burial  place from Ephron the Hittite, along with the field.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:31, Page:1, Kor:"", Chn:"", Eng:"There Abraham and his wife Sarah were buried, there Isaac and his wife Rebekah were buried,  and there I buried Leah.", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:32, Page:1, Kor:"", Chn:"", Eng:"The field and the cave in it were bought from the Hittites.\"", Ind:""},
  {Bible:"Genesis", Chapter:49, Verse:33, Page:1, Kor:"", Chn:"", Eng:"When Jacob had finished giving instructions to his sons, he drew his feet up into the bed,  breathed his last and was gathered to his people.", Ind:""},
]);
