// 창세기 18장 · Genesis 18
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Genesis",18,33);
BibleDB.add([
  {Bible:"Genesis", Chapter:18, Verse:1, Page:1, Kor:"", Chn:"", Eng:"The LORD appeared to Abraham near the great trees of Mamre while he was sitting at the  entrance to his tent in the heat of the day.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:2, Page:1, Kor:"", Chn:"", Eng:"Abraham looked up and saw three men standing nearby. When he saw them, he hurried from the  entrance of his tent to meet them and bowed low to the ground.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:3, Page:1, Kor:"", Chn:"", Eng:"He said, \"If I have found favor in your eyes, my lord, do not pass your servant by.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Let a little water be brought, and then you may all wash your feet and rest under this tree.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Let me get you something to eat, so you can be refreshed and then go on your way--now that  you have come to your servant.\" \"Very well,\" they answered, \"do as you say.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:6, Page:1, Kor:"", Chn:"", Eng:"So Abraham hurried into the tent to Sarah. \"Quick,\" he said, \"get three seahs of fine flour  and knead it and bake some bread.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:7, Page:1, Kor:"", Chn:"", Eng:"Then he ran to the herd and selected a choice, tender calf and gave it to a servant, who  hurried to prepare it.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:8, Page:1, Kor:"", Chn:"", Eng:"He then brought some curds and milk and the calf that had been prepared, and set these  before them. While they ate, he stood near them under a tree.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:9, Page:1, Kor:"", Chn:"", Eng:"\"Where is your wife Sarah?\" they asked him. \"There, in the tent,\" he said.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said, \"I will surely return to you about this time next year, and Sarah your  wife will have a son.\" Now Sarah was listening at the entrance to the tent, which was behind him.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Abraham and Sarah were already old and well advanced in years, and Sarah was past the age  of childbearing.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:12, Page:1, Kor:"", Chn:"", Eng:"So Sarah laughed to herself as she thought, \"After I am worn out and my master is old, will  I now have this pleasure?\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said to Abraham, \"Why did Sarah laugh and say, 'Will I really have a child,  now that I am old?'", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:14, Page:1, Kor:"", Chn:"", Eng:"Is anything too hard for the LORD? I will return to you at the appointed time next year and  Sarah will have a son.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:15, Page:1, Kor:"", Chn:"", Eng:"Sarah was afraid, so she lied and said, \"I did not laugh.\" But he said, \"Yes, you did  laugh.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:16, Page:1, Kor:"", Chn:"", Eng:"When the men got up to leave, they looked down toward Sodom, and Abraham walked along with  them to see them on their way.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:17, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said, \"Shall I hide from Abraham what I am about to do?", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:18, Page:1, Kor:"", Chn:"", Eng:"Abraham will surely become a great and powerful nation, and all nations on earth will be  blessed through him.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:19, Page:1, Kor:"", Chn:"", Eng:"For I have chosen him, so that he will direct his children and his household after him to  keep the way of the LORD by doing what is right and just, so that the LORD will bring about for  Abraham what he has promised him.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said, \"The outcry against Sodom and Gomorrah is so great and their sin so  grievous", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:21, Page:1, Kor:"", Chn:"", Eng:"that I will go down and see if what they have done is as bad as the outcry that has reached  me. If not, I will know.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:22, Page:1, Kor:"", Chn:"", Eng:"The men turned away and went toward Sodom, but Abraham remained standing before the LORD.", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:23, Page:1, Kor:"", Chn:"", Eng:"Then Abraham approached him and said: \"Will you sweep away the righteous with the wicked?", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:24, Page:1, Kor:"", Chn:"", Eng:"What if there are fifty righteous people in the city? Will you really sweep it away and not  spare the place for the sake of the fifty righteous people in it?", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:25, Page:1, Kor:"", Chn:"", Eng:"Far be it from you to do such a thing--to kill the righteous with the wicked, treating the  righteous and the wicked alike. Far be it from you! Will not the Judge of all the earth do  right?\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:26, Page:1, Kor:"", Chn:"", Eng:"The LORD said, \"If I find fifty righteous people in the city of Sodom, I will spare the  whole place for their sake.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:27, Page:1, Kor:"", Chn:"", Eng:"Then Abraham spoke up again: \"Now that I have been so bold as to speak to the Lord, though  I am nothing but dust and ashes,", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:28, Page:1, Kor:"", Chn:"", Eng:"what if the number of the righteous is five less than fifty? Will you destroy the whole  city because of five people?\" \"If I find forty-five there,\" he said, \"I will not destroy it.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:29, Page:1, Kor:"", Chn:"", Eng:"Once again he spoke to him, \"What if only forty are found there?\" He said, \"For the sake of  forty, I will not do it.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:30, Page:1, Kor:"", Chn:"", Eng:"Then he said, \"May the Lord not be angry, but let me speak. What if only thirty can be  found there?\" He answered, \"I will not do it if I find thirty there.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:31, Page:1, Kor:"", Chn:"", Eng:"Abraham said, \"Now that I have been so bold as to speak to the Lord, what if only twenty  can be found there?\" He said, \"For the sake of twenty, I will not destroy it.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:32, Page:1, Kor:"", Chn:"", Eng:"Then he said, \"May the Lord not be angry, but let me speak just once more. What if only ten  can be found there?\" He answered, \"For the sake of ten, I will not destroy it.\"", Ind:""},
  {Bible:"Genesis", Chapter:18, Verse:33, Page:1, Kor:"", Chn:"", Eng:"When the LORD had finished speaking with Abraham, he left, and Abraham returned home.", Ind:""},
]);
