// 창세기 21장 · Genesis 21
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Genesis",21,34);
BibleDB.add([
  {Bible:"Genesis", Chapter:21, Verse:1, Page:1,
    Kor:"<이삭이 태어나다> 주님께서는 말씀하신 대로 사라를 돌보셨다. 사라에게 약속하신 것을 주님께서 그대로 이루시니,",
    Chn:"耶和华按着先前的话眷顾撒拉，便照他所说的给撒拉成就。",
    Eng:"Now the LORD was gracious to Sarah as he had said, and the LORD did for Sarah what he had  promised.",
    Ind:"TUHAN memperhatikan Sara, seperti yang difirmankan-Nya, dan TUHAN melakukan kepada Sara seperti yang dijanjikan-Nya."
  },
  {Bible:"Genesis", Chapter:21, Verse:2, Page:1,
    Kor:"사라가 임신하였고, 하나님이 아브라함에게 약속하신 바로 그 때가 되니, 사라와 늙은 아브라함 사이에서 아들이 태어났다.",
    Chn:"当亚伯拉罕年老的时候，撒拉怀了孕；到　神所说的日期，就给亚伯拉罕生了一个儿子。",
    Eng:"Sarah became pregnant and bore a son to Abraham in his old age, at the very time God had  promised him.",
    Ind:"Maka mengandunglah Sara, lalu ia melahirkan seorang anak laki-laki bagi Abraham dalam masa tuanya, pada waktu yang telah ditetapkan, sesuai dengan firman Allah kepadanya."
  },
  {Bible:"Genesis", Chapter:21, Verse:3, Page:1,
    Kor:"아브라함은 사라가 낳아 준 아들에게 a이삭이라는 이름을 지어 주었다.(a '그가 웃다')",
    Chn:"亚伯拉罕给撒拉所生的儿子起名叫以撒。",
    Eng:"Abraham gave the name Isaac to the son Sarah bore him.",
    Ind:"Abraham menamai anaknya yang baru lahir itu Ishak, yang dilahirkan Sara baginya."
  },
  {Bible:"Genesis", Chapter:21, Verse:4, Page:1,
    Kor:"이삭이 태어난 지 여드레 만에, 아브라함은, 하나님이 분부하신 대로, 그 아기에게 할례를 베풀었다.",
    Chn:"以撒生下来第八日，亚伯拉罕照着　神所吩咐的，给以撒行了割礼。",
    Eng:"When his son Isaac was eight days old, Abraham circumcised him, as God commanded him.",
    Ind:"Kemudian Abraham menyunat Ishak, anaknya itu, ketika berumur delapan hari, seperti yang diperintahkan Allah kepadanya."
  },
  {Bible:"Genesis", Chapter:21, Verse:5, Page:1,
    Kor:"아브라함이 아들 이삭을 보았을 때에, 그의 나이는 백 살이었다.",
    Chn:"他儿子以撒生的时候，亚伯拉罕年一百岁。",
    Eng:"Abraham was a hundred years old when his son Isaac was born to him.",
    Ind:"Adapun Abraham berumur seratus tahun, ketika Ishak, anaknya, lahir baginya."
  },
  {Bible:"Genesis", Chapter:21, Verse:6, Page:1,
    Kor:"사라가 혼자서 말하였다. \"하나님이 나에게 웃음을 주셨구나. 나와 같은 늙은이가 아들을 낳았다고 하면, 듣는 사람마다 나처럼 웃지 않을 수 없겠지.\"",
    Chn:"撒拉说：「　神使我喜笑，凡听见的必与我一同喜笑」；",
    Eng:"Sarah said, \"God has brought me laughter, and everyone who hears about this will laugh with  me.\"",
    Ind:"Berkatalah Sara: \"Allah telah membuat aku tertawa; setiap orang yang mendengarnya akan tertawa karena aku.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:7, Page:1,
    Kor:"그는 말을 계속하였다. \"사라가 자식들에게 젖을 물리게 될 것이라고, 누가 아브라함에게 말할 엄두를 내었으랴? 그러나 내가 지금, 늙은 아브라함에게 아들을 낳아 주지 않았는가!\"",
    Chn:"又说：「谁能预先对亚伯拉罕说『撒拉要乳养婴孩』呢？因为在他年老的时候，我给他生了一个儿子。」",
    Eng:"And she added, \"Who would have said to Abraham that Sarah would nurse children? Yet I have  borne him a son in his old age.\"",
    Ind:"Lagi katanya: \"Siapakah tadinya yang dapat mengatakan kepada Abraham: Sara menyusui anak? Namun aku telah melahirkan seorang anak laki-laki baginya pada masa tuanya.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:8, Page:1,
    Kor:"<하갈과 이스마엘이 쫓겨나다> ○아기가 자라서, 젖을 떼게 되었다. 이삭이 젖을 떼는 날에, 아브라함이 큰 잔치를 벌였다.",
    Chn:"孩子渐长，就断了奶。以撒断奶的日子，亚伯拉罕设摆丰盛的筵席。",
    Eng:"The child grew and was weaned, and on the day Isaac was weaned Abraham held a great feast.",
    Ind:"Bertambah besarlah anak itu dan ia disapih, lalu Abraham mengadakan perjamuan besar pada hari Ishak disapih itu."
  },
  {Bible:"Genesis", Chapter:21, Verse:9, Page:1,
    Kor:"그런데 사라가 보니, 이집트 여인 하갈과 아브라함 사이에서 태어난 아들이 이삭을 놀리고 있었다.",
    Chn:"当时，撒拉看见埃及人夏甲给亚伯拉罕所生的儿子戏笑，",
    Eng:"But Sarah saw that the son whom Hagar the Egyptian had borne to Abraham was mocking,",
    Ind:"Pada waktu itu Sara melihat, bahwa anak yang dilahirkan Hagar, perempuan Mesir itu bagi Abraham, sedang main dengan Ishak, anaknya sendiri."
  },
  {Bible:"Genesis", Chapter:21, Verse:10, Page:1,
    Kor:"사라가 아브라함에게 말하였다. \"저 여종과 그 아들을 내보내십시오. 저 여종의 아들은 나의 아들 이삭과 유산을 나누어 가질 수 없습니다.\"",
    Chn:"就对亚伯拉罕说：「你把这使女和她儿子赶出去！因为这使女的儿子不可与我的儿子以撒一同承受产业。」",
    Eng:"and she said to Abraham, \"Get rid of that slave woman and her son, for that slave woman's  son will never share in the inheritance with my son Isaac.\"",
    Ind:"Berkatalah Sara kepada Abraham: \"Usirlah hamba perempuan itu beserta anaknya, sebab anak hamba ini tidak akan menjadi ahli waris bersama-sama dengan anakku Ishak.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:11, Page:1,
    Kor:"그러나 아브라함은, 그 아들도 자기 아들이므로, 이 일로 마음이 몹시 괴로웠다.",
    Chn:"亚伯拉罕因他儿子的缘故很忧愁。",
    Eng:"The matter distressed Abraham greatly because it concerned his son.",
    Ind:"Hal ini sangat menyebalkan Abraham oleh karena anaknya itu."
  },
  {Bible:"Genesis", Chapter:21, Verse:12, Page:1,
    Kor:"하나님이 그에게 말씀하셨다. \"그 아들과 그 어머니인 여종의 일로 너무 걱정하지 말아라. 이삭에게서 태어나는 사람이 너의 씨가 될 것이니, 사라가 너에게 말한 대로 다 들어 주어라.",
    Chn:"神对亚伯拉罕说：「你不必为这童子和你的使女忧愁。凡撒拉对你说的话，你都该听从；因为从以撒生的，才要称为你的后裔。",
    Eng:"But God said to him, \"Do not be so distressed about the boy and your maidservant. Listen to  whatever Sarah tells you, because it is through Isaac that your offspring will be reckoned.",
    Ind:"Tetapi Allah berfirman kepada Abraham: \"Janganlah sebal hatimu karena hal anak dan budakmu itu; dalam segala yang dikatakan Sara kepadamu, haruslah engkau mendengarkannya, sebab yang akan disebut keturunanmu ialah yang berasal dari Ishak."
  },
  {Bible:"Genesis", Chapter:21, Verse:13, Page:1,
    Kor:"그러나 여종에게서 난 아들도 너의 씨니, 그 아들은 그 아들대로, 내가 한 민족이 되게 하겠다.\"",
    Chn:"至于使女的儿子，我也必使他的后裔成立一国，因为他是你所生的。」",
    Eng:"I will make the son of the maidservant into a nation also, because he is your offspring.\"",
    Ind:"Tetapi keturunan dari hambamu itu juga akan Kubuat menjadi suatu bangsa, karena iapun anakmu.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:14, Page:1,
    Kor:"다음날 아침에 일찍, 아브라함은 먹거리 얼마와 물 한 가죽부대를 가져다가, 하갈에게 주었다. 그는 먹거리와 마실 물을 하갈의 어깨에 메워 주고서, 그를 아이와 함께 내보냈다. 하갈은 길을 나서서, 브엘세바 빈 들에서 정처없이 헤매고 다녔다.",
    Chn:"亚伯拉罕清早起来，拿饼和一皮袋水，给了夏甲，搭在她的肩上，又把孩子交给她，打发她走。夏甲就走了，在别是巴的旷野走迷了路。",
    Eng:"Early the next morning Abraham took some food and a skin of water and gave them to Hagar.  He set them on her shoulders and then sent her off with the boy. She went on her way and wandered  in the desert of Beersheba.",
    Ind:"Keesokan harinya pagi-pagi Abraham mengambil roti serta sekirbat air dan memberikannya kepada Hagar. Ia meletakkan itu beserta anaknya di atas bahu Hagar, kemudian disuruhnyalah perempuan itu pergi. Maka pergilah Hagar dan mengembara di padang gurun Bersyeba."
  },
  {Bible:"Genesis", Chapter:21, Verse:15, Page:1,
    Kor:"○가죽부대에 담아 온 물이 다 떨어지니, 하갈은 아이를 덤불 아래에 뉘어 놓고서",
    Chn:"皮袋的水用尽了，夏甲就把孩子撇在小树底下，",
    Eng:"When the water in the skin was gone, she put the boy under one of the bushes.",
    Ind:"Ketika air yang dikirbat itu habis, dibuangnyalah anak itu ke bawah semak-semak,"
  },
  {Bible:"Genesis", Chapter:21, Verse:16, Page:1,
    Kor:"\"아이가 죽어 가는 꼴을 차마 볼 수가 없구나!\" 하면서, 화살 한 바탕 거리만큼 떨어져서, 주저앉았다. 그 여인은 아이 쪽을 바라보고 앉아서, 소리를 내어 울었다.",
    Chn:"自己走开约有一箭之远，相对而坐，说：「我不忍见孩子死」，就相对而坐，放声大哭。",
    Eng:"Then she went off and sat down nearby, about a bowshot away, for she thought, \"I cannot  watch the boy die.\" And as she sat there nearby, she began to sob.",
    Ind:"dan ia duduk agak jauh, kira-kira sepemanah jauhnya, sebab katanya: \"Tidak tahan aku melihat anak itu mati.\" Sedang ia duduk di situ, menangislah ia dengan suara nyaring."
  },
  {Bible:"Genesis", Chapter:21, Verse:17, Page:1,
    Kor:"하나님이 그 아이가 우는 소리를 들으셨다. 하늘에서 하나님의 천사가 하갈을 부르며 말하였다. \"하갈아, 어찌 된 일이냐? 무서워하지 말아라. 아이가 저기에 누워서 우는 저 소리를 하나님이 들으셨다.",
    Chn:"神听见童子的声音；　神的使者从天上呼叫夏甲说：「夏甲，你为何这样呢？不要害怕，　神已经听见童子的声音了。",
    Eng:"God heard the boy crying, and the angel of God called to Hagar from heaven and said to her,  \"What is the matter, Hagar? Do not be afraid; God has heard the boy crying as he lies there.",
    Ind:"Allah mendengar suara anak itu, lalu Malaikat Allah berseru dari langit kepada Hagar, kata-Nya kepadanya: \"Apakah yang engkau susahkan, Hagar? Janganlah takut, sebab Allah telah mendengar suara anak itu dari tempat ia terbaring."
  },
  {Bible:"Genesis", Chapter:21, Verse:18, Page:1,
    Kor:"아이를 안아 일으키고, 달래어라. 내가 저 아이에게서 큰 민족이 나오게 하겠다.\"",
    Chn:"起来！把童子抱在怀中，我必使他的后裔成为大国。」",
    Eng:"Lift the boy up and take him by the hand, for I will make him into a great nation.\"",
    Ind:"Bangunlah, angkatlah anak itu, dan bimbinglah dia, sebab Aku akan membuat dia menjadi bangsa yang besar.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:19, Page:1,
    Kor:"하나님이 하갈의 눈을 밝히시니, 하갈이 샘을 발견하고, 가서, 가죽부대에 물을 담아다가 아이에게 먹였다.",
    Chn:"神使夏甲的眼睛明亮，她就看见一口水井，便去将皮袋盛满了水，给童子喝。",
    Eng:"Then God opened her eyes and she saw a well of water. So she went and filled the skin with  water and gave the boy a drink.",
    Ind:"Lalu Allah membuka mata Hagar, sehingga ia melihat sebuah sumur; ia pergi mengisi kirbatnya dengan air, kemudian diberinya anak itu minum."
  },
  {Bible:"Genesis", Chapter:21, Verse:20, Page:1,
    Kor:"○그 아이가 자라는 동안에, 하나님이 그 아이와 늘 함께 계시면서 돌보셨다. 그는 광야에 살면서, 활을 쏘는 사람이 되었다.",
    Chn:"神保佑童子，他就渐长，住在旷野，成了弓箭手。",
    Eng:"God was with the boy as he grew up. He lived in the desert and became an archer.",
    Ind:"Allah menyertai anak itu, sehingga ia bertambah besar; ia menetap di padang gurun dan menjadi seorang pemanah."
  },
  {Bible:"Genesis", Chapter:21, Verse:21, Page:1,
    Kor:"그가 바란 광야에서 살 때에, 그의 어머니가 그에게 이집트 땅에 사는 여인을 데려가서, 아내로 삼게 하였다.",
    Chn:"他住在巴兰的旷野；他母亲从埃及地给他娶了一个妻子。",
    Eng:"While he was living in the Desert of Paran, his mother got a wife for him from Egypt.",
    Ind:"Maka tinggallah ia di padang gurun Paran, dan ibunya mengambil seorang isteri baginya dari tanah Mesir."
  },
  {Bible:"Genesis", Chapter:21, Verse:22, Page:1,
    Kor:"<아브라함과 아비멜렉의 협약> ○그 무렵에 아비멜렉과 그의 군사령관 비골이 아브라함에게 말하였다. \"하나님은, 당신이 무슨 일을 하든지, 당신을 도우십니다.",
    Chn:"当那时候，亚比米勒同他军长非各对亚伯拉罕说：「凡你所行的事都有　神的保佑。",
    Eng:"At that time Abimelech and Phicol the commander of his forces said to Abraham, \"God is with  you in everything you do.",
    Ind:"Pada waktu itu Abimelekh, beserta Pikhol, panglima tentaranya, berkata kepada Abraham: \"Allah menyertai engkau dalam segala sesuatu yang engkau lakukan."
  },
  {Bible:"Genesis", Chapter:21, Verse:23, Page:1,
    Kor:"이제 여기 하나님 앞에서, 당신이 나와 나의 아이들과 나의 자손을 속이지 않겠다고 맹세하십시오. 당신이 나그네살이를 하는 우리 땅에서, 내가 당신에게 한 것처럼, 당신도 나와 이 땅 사람들에게 친절을 베풀어 주시기 바랍니다.\"",
    Chn:"我愿你如今在这里指着　神对我起誓，不要欺负我与我的儿子，并我的子孙。我怎样厚待了你，你也要照样厚待我与你所寄居这地的民。」",
    Eng:"Now swear to me here before God that you will not deal falsely with me or my children or my  descendants. Show to me and the country where you are living as an alien the same kindness I have  shown to you.\"",
    Ind:"Oleh sebab itu, bersumpahlah kepadaku di sini demi Allah, bahwa engkau tidak akan berlaku curang kepadaku, atau kepada anak-anakku, atau kepada cucu cicitku; sesuai dengan persahabatan yang kulakukan kepadamu, demikianlah harus engkau berlaku kepadaku dan kepada negeri yang kautinggali sebagai orang asing.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:24, Page:1,
    Kor:"아브라함이 말하였다. \"맹세합니다.\"",
    Chn:"亚伯拉罕说：「我情愿起誓。」",
    Eng:"Abraham said, \"I swear it.\"",
    Ind:"Lalu kata Abraham: \"Aku bersumpah!\""
  },
  {Bible:"Genesis", Chapter:21, Verse:25, Page:1,
    Kor:"○이렇게 말하고 나서, 아브라함은, 아비멜렉의 종들이 우물을 빼앗은 것을 아비멜렉에게 항의하였다.",
    Chn:"从前，亚比米勒的仆人霸占了一口水井，亚伯拉罕为这事指责亚比米勒。",
    Eng:"Then Abraham complained to Abimelech about a well of water that Abimelech's servants had  seized.",
    Ind:"Tetapi Abraham menyesali Abimelekh tentang sebuah sumur yang telah dirampas oleh hamba-hamba Abimelekh."
  },
  {Bible:"Genesis", Chapter:21, Verse:26, Page:1,
    Kor:"그러나 아비멜렉은 이렇게 말하였다. \"누가 그런 일을 저질렀는지, 나는 모릅니다. 당신도 그런 말을 여태까지 나에게 하지 않았습니다. 나는 그 일을 겨우 오늘에 와서야 들었습니다.\"",
    Chn:"亚比米勒说：「谁做这事，我不知道，你也没有告诉我，今日我才听见了。」",
    Eng:"But Abimelech said, \"I don't know who has done this. You did not tell me, and I heard about  it only today.\"",
    Ind:"Jawab Abimelekh: \"Aku tidak tahu, siapa yang melakukan hal itu; lagi tidak kauberitahukan kepadaku, dan sampai hari ini belum pula kudengar.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:27, Page:1,
    Kor:"아브라함이 양과 소를 끌고 와서, 아비멜렉에게 주고, 두 사람이 서로 언약을 세웠다.",
    Chn:"亚伯拉罕把羊和牛给了亚比米勒，二人就彼此立约。",
    Eng:"So Abraham brought sheep and cattle and gave them to Abimelech, and the two men made a  treaty.",
    Ind:"Lalu Abraham mengambil domba dan lembu dan memberikan semuanya itu kepada Abimelekh, kemudian kedua orang itu mengadakan perjanjian."
  },
  {Bible:"Genesis", Chapter:21, Verse:28, Page:1,
    Kor:"아브라함이 양 떼에서 새끼 암양 일곱 마리를 따로 떼어 놓으니,",
    Chn:"亚伯拉罕把七只母羊羔另放在一处。",
    Eng:"Abraham set apart seven ewe lambs from the flock,",
    Ind:"Tetapi Abraham memisahkan tujuh anak domba betina dari domba-domba itu."
  },
  {Bible:"Genesis", Chapter:21, Verse:29, Page:1,
    Kor:"아비멜렉이 아브라함에게 물었다. \"새끼 암양 일곱 마리를 따로 떼어 놓은 까닭이 무엇입니까?\"",
    Chn:"亚比米勒问亚伯拉罕说：「你把这七只母羊羔另放在一处，是什么意思呢？」",
    Eng:"and Abimelech asked Abraham, \"What is the meaning of these seven ewe lambs you have set  apart by themselves?\"",
    Ind:"Lalu kata Abimelekh kepada Abraham: \"Untuk apakah ketujuh anak domba yang kaupisahkan ini?\""
  },
  {Bible:"Genesis", Chapter:21, Verse:30, Page:1,
    Kor:"아브라함이 대답하였다. \"내가 이 우물을 파 놓은 증거로, 이 새끼 암양 일곱 마리를 드리려고 합니다.\"",
    Chn:"他说：「你要从我手里受这七只母羊羔，作我挖这口井的证据。」",
    Eng:"He replied, \"Accept these seven lambs from my hand as a witness that I dug this well.\"",
    Ind:"Jawabnya: \"Ketujuh anak domba ini harus kauterima dari tanganku untuk menjadi tanda bukti bagiku, bahwa akulah yang menggali sumur ini.\""
  },
  {Bible:"Genesis", Chapter:21, Verse:31, Page:1,
    Kor:"이 두 사람이 여기에서 이렇게 맹세를 하였으므로, 그 곳을 b브엘세바라고 한다.(b '맹세의 우물' 또는 '일곱 우물')",
    Chn:"所以他给那地方起名叫别是巴，因为他们二人在那里起了誓。",
    Eng:"So that place was called Beersheba, because the two men swore an oath there.",
    Ind:"Sebab itu orang menyebutkan tempat itu Bersyeba, karena kedua orang itu telah bersumpah di sana."
  },
  {Bible:"Genesis", Chapter:21, Verse:32, Page:1,
    Kor:"아브라함과 아비멜렉이 브엘세바에서 언약을 세운 다음에, 아비멜렉과 그의 군사령관 비골은 블레셋 사람의 땅으로 돌아갔다.",
    Chn:"他们在别是巴立了约，亚比米勒就同他军长非各起身回非利士地去了。",
    Eng:"After the treaty had been made at Beersheba, Abimelech and Phicol the commander of his  forces returned to the land of the Philistines.",
    Ind:"Setelah mereka mengadakan perjanjian di Bersyeba, pulanglah Abimelekh beserta Pikhol, panglima tentaranya, ke negeri orang Filistin."
  },
  {Bible:"Genesis", Chapter:21, Verse:33, Page:1,
    Kor:"아브라함은 브엘세바에 에셀 나무를 심고, 거기에서, 영생하시는 주 하나님의 이름을 부르며 예배를 드렸다.",
    Chn:"亚伯拉罕在别是巴栽上一棵垂丝柳树，又在那里求告耶和华—永生　神的名。",
    Eng:"Abraham planted a tamarisk tree in Beersheba, and there he called upon the name of the  LORD, the Eternal God.",
    Ind:"Lalu Abraham menanam sebatang pohon tamariska di Bersyeba, dan memanggil di sana nama TUHAN, Allah yang kekal."
  },
  {Bible:"Genesis", Chapter:21, Verse:34, Page:1,
    Kor:"아브라함은 오랫동안 블레셋 족속의 땅에 머물러 있었다.",
    Chn:"亚伯拉罕在非利士人的地寄居了多日。",
    Eng:"And Abraham stayed in the land of the Philistines for a long time.",
    Ind:"Dan masih lama Abraham tinggal sebagai orang asing di negeri orang Filistin."
  },
]);
