// 창세기 27장 · Genesis 27
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Genesis",27,46);
BibleDB.add([
  {Bible:"Genesis", Chapter:27, Verse:1, Page:1,
    Kor:"<이삭이 야곱을 축복하다> 이삭이 늙어서, 눈이 어두워 잘 볼 수 없게 된 어느 날, 맏아들 에서를 불렀다. \"나의 아들아.\" 에서가 대답하였다. \"예, 제가 여기에 있습니다.\"",
    Chn:"以撒年老，眼睛昏花，不能看见，就叫了他大儿子以扫来，说：「我儿。」以扫说：「我在这里。」",
    Eng:"When Isaac was old and his eyes were so weak that he could no longer see, he called for Esau  his older son and said to him, \"My son.\" \"Here I am,\" he answered.",
    Ind:"Ketika Ishak sudah tua, dan matanya telah kabur, sehingga ia tidak dapat melihat lagi, dipanggilnyalah Esau, anak sulungnya, serta berkata kepadanya: \"Anakku.\" Sahut Esau: \"Ya, bapa.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:2, Page:1,
    Kor:"이삭이 말하였다. \"얘야, 보아라, 너의 아버지가 이제는 늙어서, 언제 죽을지 모르겠구나.",
    Chn:"他说：「我如今老了，不知道哪一天死。",
    Eng:"Isaac said, \"I am now an old man and don't know the day of my death.",
    Ind:"Berkatalah Ishak: \"Lihat, aku sudah tua, aku tidak tahu bila hari kematianku."
  },
  {Bible:"Genesis", Chapter:27, Verse:3, Page:1,
    Kor:"그러니 이제 너는 나를 생각해서, 사냥할 때에 쓰는 기구들 곧 화살통과 활을 메고 들로 나가서, 사냥을 해다가,",
    Chn:"现在拿你的器械，就是箭囊和弓，往田野去为我打猎，",
    Eng:"Now then, get your weapons--your quiver and bow--and go out to the open country to hunt some  wild game for me.",
    Ind:"Maka sekarang, ambillah senjatamu, tabung panah dan busurmu, pergilah ke padang dan burulah bagiku seekor binatang;"
  },
  {Bible:"Genesis", Chapter:27, Verse:4, Page:1,
    Kor:"내가 좋아하는 별미를 만들어서, 나에게 가져 오너라. 내가 그것을 먹고, 죽기 전에 너에게 마음껏 축복하겠다.\"",
    Chn:"照我所爱的做成美味，拿来给我吃，使我在未死之先给你祝福。」",
    Eng:"Prepare me the kind of tasty food I like and bring it to me to eat, so that I may give you  my blessing before I die.\"",
    Ind:"olahlah bagiku makanan yang enak, seperti yang kugemari, sesudah itu bawalah kepadaku, supaya kumakan, agar aku memberkati engkau, sebelum aku mati.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:5, Page:1,
    Kor:"○이삭이 자기 아들 에서에게 이렇게 말하는 것을 리브가가 엿들었다. 에서가 무엇인가를 잡아오려고 들로 사냥을 나가자,",
    Chn:"以撒对他儿子以扫说话，利百加也听见了。以扫往田野去打猎，要得野味带来。",
    Eng:"Now Rebekah was listening as Isaac spoke to his son Esau. When Esau left for the open  country to hunt game and bring it back,",
    Ind:"Tetapi Ribka mendengarkannya, ketika Ishak berkata kepada Esau, anaknya. Setelah Esau pergi ke padang memburu seekor binatang untuk dibawanya kepada ayahnya,"
  },
  {Bible:"Genesis", Chapter:27, Verse:6, Page:1,
    Kor:"리브가는 아들 야곱에게 말하였다. \"얘야, 나 좀 보자. 너의 아버지가 너의 형에게 하는 말을 내가 들었다.",
    Chn:"利百加就对她儿子雅各说：「我听见你父亲对你哥哥以扫说：",
    Eng:"Rebekah said to her son Jacob, \"Look, I overheard your father say to your brother Esau,",
    Ind:"berkatalah Ribka kepada Yakub, anaknya: \"Telah kudengar ayahmu berkata kepada Esau, kakakmu:"
  },
  {Bible:"Genesis", Chapter:27, Verse:7, Page:1,
    Kor:"사냥을 해다가, 별미를 만들어서 아버지께 가져 오라고 하시면서, 그것을 잡수시고, 돌아가시기 전에, 주님 앞에서 너의 형에게 축복하겠다고 하시더라.",
    Chn:"『你去把野兽带来，做成美味给我吃，我好在未死之先，在耶和华面前给你祝福。』",
    Eng:"'Bring me some game and prepare me some tasty food to eat, so that I may give you my  blessing in the presence of the LORD before I die.'",
    Ind:"Bawalah bagiku seekor binatang buruan dan olahlah bagiku makanan yang enak, supaya kumakan, dan supaya aku memberkati engkau di hadapan TUHAN, sebelum aku mati."
  },
  {Bible:"Genesis", Chapter:27, Verse:8, Page:1,
    Kor:"그러니 얘야, 너의 어머니가 하는 말을 잘 듣고, 시키는 대로 하여라.",
    Chn:"现在，我儿，你要照着我所吩咐你的，听从我的话。",
    Eng:"Now, my son, listen carefully and do what I tell you:",
    Ind:"Maka sekarang, anakku, dengarkanlah perkataanku seperti yang kuperintahkan kepadamu."
  },
  {Bible:"Genesis", Chapter:27, Verse:9, Page:1,
    Kor:"염소가 있는 데로 가서, 어린 것으로 통통한 놈 두 마리만 나에게 끌고 오너라. 너의 아버지가 어떤 것을 좋아하시는지 내가 잘 아니까, 아버지가 잡수실 별미를 만들어 줄 터이니,",
    Chn:"你到羊群里去，给我拿两只肥山羊羔来，我便照你父亲所爱的给他做成美味。",
    Eng:"Go out to the flock and bring me two choice young goats, so I can prepare some tasty food  for your father, just the way he likes it.",
    Ind:"Pergilah ke tempat kambing domba kita, ambillah dari sana dua anak kambing yang baik, maka aku akan mengolahnya menjadi makanan yang enak bagi ayahmu, seperti yang digemarinya."
  },
  {Bible:"Genesis", Chapter:27, Verse:10, Page:1,
    Kor:"너는 그것을 아버지께 가져다 드려라. 그러면 아버지가 그것을 잡수시고서, 돌아가시기 전에 너에게 축복하여 주실 것이다.\"",
    Chn:"你拿到你父亲那里给他吃，使他在未死之先给你祝福。」",
    Eng:"Then take it to your father to eat, so that he may give you his blessing before he dies.\"",
    Ind:"Bawalah itu kepada ayahmu, supaya dimakannya, agar dia memberkati engkau, sebelum ia mati.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:11, Page:1,
    Kor:"야곱이 어머니 리브가에게 말하였다. \"형 에서는 털이 많은 사람이고, 나는 이렇게 피부가 매끈한 사람인데,",
    Chn:"雅各对他母亲利百加说：「我哥哥以扫浑身是有毛的，我身上是光滑的；",
    Eng:"Jacob said to Rebekah his mother, \"But my brother Esau is a hairy man, and I'm a man with  smooth skin.",
    Ind:"Lalu kata Yakub kepada Ribka, ibunya: \"Tetapi Esau, kakakku, adalah seorang yang berbulu badannya, sedang aku ini kulitku licin."
  },
  {Bible:"Genesis", Chapter:27, Verse:12, Page:1,
    Kor:"아버지께서 만져 보시면 어떻게 되겠습니까? 아버지를 속인 죄로, 축복은커녕 오히려 저주를 받을 것이 아닙니까?\"",
    Chn:"倘若我父亲摸着我，必以我为欺哄人的，我就招咒诅，不得祝福。」",
    Eng:"What if my father touches me? I would appear to be tricking him and would bring down a  curse on myself rather than a blessing.\"",
    Ind:"Mungkin ayahku akan meraba aku; maka nanti ia akan menyangka bahwa aku mau memperolok-olokkan dia; dengan demikian aku akan mendatangkan kutuk atas diriku dan bukan berkat.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:13, Page:1,
    Kor:"어머니가 아들에게 말하였다. \"아들아, 저주는 이 어미가 받으마. 내가 시키는 대로 하여라. 가서, 두 마리를 끌고 오너라.\"",
    Chn:"他母亲对他说：「我儿，你招的咒诅归到我身上；你只管听我的话，去把羊羔给我拿来。」",
    Eng:"His mother said to him, \"My son, let the curse fall on me. Just do what I say; go and get  them for me.\"",
    Ind:"Tetapi ibunya berkata kepadanya: \"Akulah yang menanggung kutuk itu, anakku; dengarkan saja perkataanku, pergilah ambil kambing-kambing itu.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:14, Page:1,
    Kor:"그가 가서, 두 마리를 붙잡아서 어머니에게 끌고 오니, 그의 어머니가 그것으로 아버지의 입맛에 맞게 별미를 만들었다.",
    Chn:"他便去拿来，交给他母亲；他母亲就照他父亲所爱的做成美味。",
    Eng:"So he went and got them and brought them to his mother, and she prepared some tasty food,  just the way his father liked it.",
    Ind:"Lalu ia pergi mengambil kambing-kambing itu dan membawanya kepada ibunya; sesudah itu ibunya mengolah makanan yang enak, seperti yang digemari ayahnya."
  },
  {Bible:"Genesis", Chapter:27, Verse:15, Page:1,
    Kor:"그런 다음에 리브가는, 자기가 집에 잘 간직하여 둔 맏아들 에서의 옷 가운데 가장 좋은 것을 꺼내어, 작은 아들 야곱에게 입혔다.",
    Chn:"利百加又把家里所存大儿子以扫上好的衣服给她小儿子雅各穿上，",
    Eng:"Then Rebekah took the best clothes of Esau her older son, which she had in the house, and  put them on her younger son Jacob.",
    Ind:"Kemudian Ribka mengambil pakaian yang indah kepunyaan Esau, anak sulungnya, pakaian yang disimpannya di rumah, lalu disuruhnyalah dikenakan oleh Yakub, anak bungsunya."
  },
  {Bible:"Genesis", Chapter:27, Verse:16, Page:1,
    Kor:"리브가는 염소 새끼 가죽을 야곱의 매끈한 손과 목덜미에 둘러 주고 나서,",
    Chn:"又用山羊羔皮包在雅各的手上和颈项的光滑处，",
    Eng:"She also covered his hands and the smooth part of his neck with the goatskins.",
    Ind:"Dan kulit anak kambing itu dipalutkannya pada kedua tangan Yakub dan pada lehernya yang licin itu."
  },
  {Bible:"Genesis", Chapter:27, Verse:17, Page:1,
    Kor:"자기가 마련한 별미와 빵을 아들 야곱에게 들려 주었다.",
    Chn:"就把所做的美味和饼交在她儿子雅各的手里。",
    Eng:"Then she handed to her son Jacob the tasty food and the bread she had made.",
    Ind:"Lalu ia memberikan makanan yang enak dan roti yang telah diolahnya itu kepada Yakub, anaknya."
  },
  {Bible:"Genesis", Chapter:27, Verse:18, Page:1,
    Kor:"○야곱이 아버지에게 가서 \"아버지!\" 하고 불렀다. 그러자 이삭이 \"나 여기 있다. 아들아, 너는 누구냐?\" 하고 물었다.",
    Chn:"雅各到他父亲那里说：「我父亲！」他说：「我在这里。我儿，你是谁？」",
    Eng:"He went to his father and said, \"My father.\" \"Yes, my son,\" he answered. \"Who is it?\"",
    Ind:"Demikianlah Yakub masuk ke tempat ayahnya serta berkata: \"Bapa!\" Sahut ayahnya: \"Ya, anakku; siapakah engkau?\""
  },
  {Bible:"Genesis", Chapter:27, Verse:19, Page:1,
    Kor:"야곱이 아버지에게 말하였다. \"저는 아버지의 맏아들 에서입니다. 아버지께서 말씀하신 그대로 하였습니다. 이제 일어나 앉으셔서, 제가 사냥하여 온 고기를 잡수시고, 저에게 마음껏 축복하여 주시기 바랍니다.\"",
    Chn:"雅各对他父亲说：「我是你的长子以扫；我已照你所吩咐我的行了。请起来坐着，吃我的野味，好给我祝福。」",
    Eng:"Jacob said to his father, \"I am Esau your firstborn. I have done as you told me. Please sit  up and eat some of my game so that you may give me your blessing.\"",
    Ind:"Kata Yakub kepada ayahnya: \"Akulah Esau, anak sulungmu. Telah kulakukan, seperti yang bapa katakan kepadaku. Bangunlah, duduklah dan makanlah daging buruan masakanku ini, agar bapa memberkati aku.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:20, Page:1,
    Kor:"이삭이 아들에게 물었다. \"얘야, 어떻게 그렇게 빨리 사냥거리를 찾았느냐?\" 야곱이 대답하였다. \"아버지께서 섬기시는 주 하나님이, 일이 잘 되게 저를 도와 주셨습니다.\"",
    Chn:"以撒对他儿子说：「我儿，你如何找得这么快呢？」他说：「因为耶和华—你的　神使我遇见好机会得着的。」",
    Eng:"Isaac asked his son, \"How did you find it so quickly, my son?\" \"The LORD your God gave me  success,\" he replied.",
    Ind:"Lalu Ishak berkata kepada anaknya itu: \"Lekas juga engkau mendapatnya, anakku!\" Jawabnya: \"Karena TUHAN, Allahmu, membuat aku mencapai tujuanku.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:21, Page:1,
    Kor:"이삭이 야곱에게 말하였다. \"얘야, 내가 너를 좀 만져 볼 수 있게, 이리 가까이 오너라. 네가 정말로 나의 아들 에서인지, 좀 알아보아야겠다.\"",
    Chn:"以撒对雅各说：「我儿，你近前来，我摸摸你，知道你真是我的儿子以扫不是。」",
    Eng:"Then Isaac said to Jacob, \"Come near so I can touch you, my son, to know whether you really  are my son Esau or not.\"",
    Ind:"Lalu kata Ishak kepada Yakub: \"Datanglah mendekat, anakku, supaya aku meraba engkau, apakah engkau ini anakku Esau atau bukan.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:22, Page:1,
    Kor:"야곱이 아버지 이삭에게 가까이 가니, 이삭이 아들을 만져 보고서 중얼거렸다. \"목소리는 야곱의 목소리인데, 손은 에서의 손이로구나.\"",
    Chn:"雅各就挨近他父亲以撒。以撒摸着他，说：「声音是雅各的声音，手却是以扫的手。」",
    Eng:"Jacob went close to his father Isaac, who touched him and said, \"The voice is the voice of  Jacob, but the hands are the hands of Esau.\"",
    Ind:"Maka Yakub mendekati Ishak, ayahnya, dan ayahnya itu merabanya serta berkata: \"Kalau suara, suara Yakub; kalau tangan, tangan Esau.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:23, Page:1,
    Kor:"이삭은, 야곱의 두 손이 저의 형 에서의 손처럼 털이 나 있으므로, 그가 야곱인 줄을 모르고, 그에게 축복하여 주기로 하였다.",
    Chn:"以撒就辨不出他来；因为他手上有毛，像他哥哥以扫的手一样，就给他祝福；",
    Eng:"He did not recognize him, for his hands were hairy like those of his brother Esau; so he  blessed him.",
    Ind:"Jadi Ishak tidak mengenal dia, karena tangannya berbulu seperti tangan Esau, kakaknya. Ishak hendak memberkati dia,"
  },
  {Bible:"Genesis", Chapter:27, Verse:24, Page:1,
    Kor:"이삭은 다짐하였다. \"네가 정말로 나의 아들 에서냐?\" 야곱이 대답하였다. \"예, 그렇습니다.\"",
    Chn:"又说：「你真是我儿子以扫吗？」他说：「我是。」",
    Eng:"\"Are you really my son Esau?\" he asked. \"I am,\" he replied.",
    Ind:"tetapi ia masih bertanya: \"Benarkah engkau ini anakku Esau?\" Jawabnya: \"Ya!\""
  },
  {Bible:"Genesis", Chapter:27, Verse:25, Page:1,
    Kor:"이삭이 말하였다. \"나의 아들아, 네가 사냥하여 온 것을 나에게 가져 오너라. 내가 그것을 먹고서, 너에게 마음껏 복을 빌어 주겠다.\" 야곱이 이삭에게 그 요리한 것을 가져다가 주니, 이삭이 그것을 먹었다. 야곱이 또 포도주를 가져다가 따르니, 이삭이 그것을 마셨다.",
    Chn:"以撒说：「你递给我，我好吃我儿子的野味，给你祝福。」雅各就递给他，他便吃了，又拿酒给他，他也喝了。",
    Eng:"Then he said, \"My son, bring me some of your game to eat, so that I may give you my  blessing.\" Jacob brought it to him and he ate; and he brought some wine and he drank.",
    Ind:"Lalu berkatalah Ishak: \"Dekatkanlah makanan itu kepadaku, supaya kumakan daging buruan masakan anakku, agar aku memberkati engkau.\" Jadi didekatkannyalah makanan itu kepada ayahnya, lalu ia makan, dibawanya juga anggur kepadanya, lalu ia minum."
  },
  {Bible:"Genesis", Chapter:27, Verse:26, Page:1,
    Kor:"그의 아버지 이삭이 그에게 말하였다. \"나의 아들아, 이리 와서, 나에게 입을 맞추어 다오.\"",
    Chn:"他父亲以撒对他说：「我儿，你上前来与我亲嘴。」",
    Eng:"Then his father Isaac said to him, \"Come here, my son, and kiss me.\"",
    Ind:"Berkatalah Ishak, ayahnya, kepadanya: \"Datanglah dekat-dekat dan ciumlah aku, anakku.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:27, Page:1,
    Kor:"야곱이 가까이 가서, 그에게 입을 맞추었다. 이삭이 야곱의 옷에서 나는 냄새를 맡고서, 그에게 복을 빌어 주었다.  \"나의 아들에게서 나는 냄새는 주님께 복받은 밭의 냄새로구나.",
    Chn:"他就上前与父亲亲嘴。他父亲一闻他衣服上的香气，就给他祝福，说： 我儿的香气 如同耶和华赐福之田地的香气一样。",
    Eng:"So he went to him and kissed him. When Isaac caught the smell of his clothes, he blessed  him and said, \"Ah, the smell of my son is like the smell of a field that the LORD has blessed.",
    Ind:"Lalu datanglah Yakub dekat-dekat dan diciumnyalah ayahnya. Ketika Ishak mencium bau pakaian Yakub, diberkatinyalah dia, katanya: \"Sesungguhnya bau anakku adalah sebagai bau padang yang diberkati TUHAN."
  },
  {Bible:"Genesis", Chapter:27, Verse:28, Page:1,
    Kor:"하나님은 하늘에서 이슬을 내려 주시고, 땅을 기름지게 하시고, 곡식과 새 포도주가 너에게 넉넉하게 하실 것이다.",
    Chn:"愿　神赐你天上的甘露， 地上的肥土， 并许多五谷新酒。",
    Eng:"May God give you of heaven's dew and of earth's richness--an abundance of grain and new  wine.",
    Ind:"Allah akan memberikan kepadamu embun yang dari langit dan tanah-tanah gemuk di bumi dan gandum serta anggur berlimpah-limpah."
  },
  {Bible:"Genesis", Chapter:27, Verse:29, Page:1,
    Kor:"여러 민족이 너를 섬기고, 백성들이 너에게 무릎을 꿇을 것이다. 너는 너의 친척들을 다스리고, 너의 어머니의 자손들이 너에게 무릎을 꿇을 것이다. 너를 저주하는 사람마다 저주를 받고, 너를 축복하는 사람마다 복을 받을 것이다.\"",
    Chn:"愿多民事奉你， 多国跪拜你。 愿你作你弟兄的主； 你母亲的儿子向你跪拜。 凡咒诅你的，愿他受咒诅； 为你祝福的，愿他蒙福。",
    Eng:"May nations serve you and peoples bow down to you. Be lord over your brothers, and may the  sons of your mother bow down to you. May those who curse you be cursed and those who bless you be  blessed.\"",
    Ind:"Bangsa-bangsa akan takluk kepadamu, dan suku-suku bangsa akan sujud kepadamu; jadilah tuan atas saudara-saudaramu, dan anak-anak ibumu akan sujud kepadamu. Siapa yang mengutuk engkau, terkutuklah ia, dan siapa yang memberkati engkau, diberkatilah ia.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:30, Page:1,
    Kor:"<에서가 축복받기를 간청하다> ○이삭은 이렇게 야곱에게 축복하여 주었다. 야곱이 아버지 앞에서 막 물러나오는데, 사냥하러 나갔던 그의 형 에서가 돌아왔다.",
    Chn:"以撒为雅各祝福已毕，雅各从他父亲那里才出来，他哥哥以扫正打猎回来，",
    Eng:"After Isaac finished blessing him and Jacob had scarcely left his father's presence, his  brother Esau came in from hunting.",
    Ind:"Setelah Ishak selesai memberkati Yakub, dan baru saja Yakub keluar meninggalkan Ishak, ayahnya, pulanglah Esau, kakaknya, dari berburu."
  },
  {Bible:"Genesis", Chapter:27, Verse:31, Page:1,
    Kor:"에서도 역시 별미를 만들어서, 그것을 들고 자기 아버지 앞에 가서 말하였다. \"아버지, 일어나셔서, 이 아들이 사냥하여 온 고기를 잡수시고, 저에게 마음껏 축복하여 주시기 바랍니다.\"",
    Chn:"也做了美味，拿来给他父亲，说：「请父亲起来，吃你儿子的野味，好给我祝福。」",
    Eng:"He too prepared some tasty food and brought it to his father. Then he said to him, \"My  father, sit up and eat some of my game, so that you may give me your blessing.\"",
    Ind:"Ia juga menyediakan makanan yang enak, lalu membawanya kepada ayahnya. Katanya kepada ayahnya: \"Bapa, bangunlah dan makan daging buruan masakan anakmu, agar engkau memberkati aku.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:32, Page:1,
    Kor:"그의 아버지 이삭이 그에게 물었다. \"너는 누구냐?\" 에서가 대답하였다. \"저는 아버지의 아들, 아버지의 맏아들 에서입니다.\"",
    Chn:"他父亲以撒对他说：「你是谁？」他说：「我是你的长子以扫。」",
    Eng:"His father Isaac asked him, \"Who are you?\" \"I am your son,\" he answered, \"your firstborn,  Esau.\"",
    Ind:"Tetapi kata Ishak, ayahnya, kepadanya: \"Siapakah engkau ini?\" Sahutnya: \"Akulah anakmu, anak sulungmu, Esau.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:33, Page:1,
    Kor:"이삭이 크게 충격을 받고서, 부들부들 떨면서 말을 더듬거렸다. \"그렇다면, 네가 오기 전에 나에게 사냥한 고기를 가져 온 게 누구란 말이냐? 네가 오기 전에, 내가 그것을 이미 다 먹고, 그에게 축복하였으니, 바로 그가 복을 받을 것이다.\"",
    Chn:"以撒就大大地战兢，说：「你未来之先，是谁得了野味拿来给我呢？我已经吃了，为他祝福；他将来也必蒙福。」",
    Eng:"Isaac trembled violently and said, \"Who was it, then, that hunted game and brought it to  me? I ate it just before you came and I blessed him--and indeed he will be blessed!\"",
    Ind:"Lalu terkejutlah Ishak dengan sangat serta berkata: \"Siapakah gerangan dia, yang memburu binatang itu dan yang telah membawanya kepadaku? Aku telah memakan semuanya, sebelum engkau datang, dan telah memberkati dia; dan dia akan tetap orang yang diberkati.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:34, Page:1,
    Kor:"아버지의 말을 들은 에서는 소리치며 울면서, 아버지에게 애원하였다. \"저에게 축복하여 주십시오. 아버지, 저에게도 똑같이 복을 빌어 주십시오.\"",
    Chn:"以扫听了他父亲的话，就放声痛哭，说：「我父啊，求你也为我祝福！」",
    Eng:"When Esau heard his father's words, he burst out with a loud and bitter cry and said to his  father, \"Bless me--me too, my father!\"",
    Ind:"Sesudah Esau mendengar perkataan ayahnya itu, meraung-raunglah ia dengan sangat keras dalam kepedihan hatinya serta berkata kepada ayahnya: \"Berkatilah aku ini juga, ya bapa!\""
  },
  {Bible:"Genesis", Chapter:27, Verse:35, Page:1,
    Kor:"그러나 이삭이 말하였다. \"너의 동생이 와서 나를 속이고, 네가 받을 복을 가로챘구나.\"",
    Chn:"以撒说：「你兄弟已经用诡计来将你的福分夺去了。」",
    Eng:"But he said, \"Your brother came deceitfully and took your blessing.\"",
    Ind:"Jawab ayahnya: \"Adikmu telah datang dengan tipu daya dan telah merampas berkat yang untukmu itu.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:36, Page:1,
    Kor:"에서가 말하였다. \"그 녀석의 이름이 왜 a야곱인지, 이제야 알 것 같습니다. 그 녀석이 이번까지 두 번이나 저를 속였습니다. 지난번에는 맏아들의 권리를 저에게서 빼앗았고, 이번에는 제가 받을 복까지 빼앗아갔습니다.\" 에서가 아버지에게 물었다. \"저에게 주실 복을 하나도 남겨 두지 않으셨습니까?\"(a '발뒤꿈치를 잡다' 즉 '속이다')",
    Chn:"以扫说：「他名雅各，岂不是正对吗？因为他欺骗了我两次：他从前夺了我长子的名分，你看，他现在又夺了我的福分。」以扫又说：「你没有留下为我可祝的福吗？」",
    Eng:"Esau said, \"Isn't he rightly named Jacob? He has deceived me these two times: He took my  birthright, and now he's taken my blessing!\" Then he asked, \"Haven't you reserved any blessing  for me?\"",
    Ind:"Kata Esau: \"Bukankah tepat namanya Yakub, karena ia telah dua kali menipu aku. Hak kesulunganku telah dirampasnya, dan sekarang dirampasnya pula berkat yang untukku.\" Lalu katanya: \"Apakah bapa tidak mempunyai berkat lain bagiku?\""
  },
  {Bible:"Genesis", Chapter:27, Verse:37, Page:1,
    Kor:"이삭이 에서에게 대답하였다. \"나는, 그가 너를 다스리도록 하였고, 그의 모든 친척을 그에게 종으로 주었고, 곡식과 새 포도주가 그에게서 떨어지지 않도록 하였다. 그러니, 나의 아들아, 내가 너에게 무엇을 해줄 수 있겠느냐?\"",
    Chn:"以撒回答以扫说：「我已立他为你的主，使他的弟兄都给他作仆人，并赐他五谷新酒可以养生。我儿，现在我还能为你做什么呢？」",
    Eng:"Isaac answered Esau, \"I have made him lord over you and have made all his relatives his  servants, and I have sustained him with grain and new wine. So what can I possibly do for you, my  son?\"",
    Ind:"Lalu Ishak menjawab Esau, katanya: \"Sesungguhnya telah kuangkat dia menjadi tuan atas engkau, dan segala saudaranya telah kuberikan kepadanya menjadi hambanya, dan telah kubekali dia dengan gandum dan anggur; maka kepadamu, apa lagi yang dapat kuperbuat, ya anakku?\""
  },
  {Bible:"Genesis", Chapter:27, Verse:38, Page:1,
    Kor:"에서가 그의 아버지에게 말하였다. \"아버지, 아버지께서 비실 수 있는 복이 어디 그 하나뿐입니까? 저에게도 복을 빌어 주십시오, 아버지!\" 이 말을 하면서, 에서는 큰소리로 울었다.",
    Chn:"以扫对他父亲说：「父啊，你只有一样可祝的福吗？我父啊，求你也为我祝福！」以扫就放声而哭。",
    Eng:"Esau said to his father, \"Do you have only one blessing, my father? Bless me too, my  father!\" Then Esau wept aloud.",
    Ind:"Kata Esau kepada ayahnya: \"Hanya berkat yang satu itukah ada padamu, ya bapa? Berkatilah aku ini juga, ya bapa!\" Dan dengan suara keras menangislah Esau."
  },
  {Bible:"Genesis", Chapter:27, Verse:39, Page:1,
    Kor:"○그의 아버지 이삭이 그에게 대답하였다.  \"네가 살 곳은 땅이 기름지지 않고, 하늘에서 이슬도 내리지 않는 곳이다.",
    Chn:"他父亲以撒说： 地上的肥土必为你所住； 天上的甘露必为你所得。",
    Eng:"His father Isaac answered him, \"Your dwelling will be away from the earth's richness, away  from the dew of heaven above.",
    Ind:"Lalu Ishak, ayahnya, menjawabnya: \"Sesungguhnya tempat kediamanmu akan jauh dari tanah-tanah gemuk di bumi dan jauh dari embun dari langit di atas."
  },
  {Bible:"Genesis", Chapter:27, Verse:40, Page:1,
    Kor:"너는 칼을 의지하고 살 것이며, 너의 아우를 섬길 것이다. 그러나 애써 힘을 기르면, 너는, 그가 네 목에 씌운 멍에를 부술 것이다.\"",
    Chn:"你必倚靠刀剑度日， 又必事奉你的兄弟； 到你强盛的时候， 必从你颈项上挣开他的轭。",
    Eng:"You will live by the sword and you will serve your brother. But when you grow restless, you  will throw his yoke from off your neck.\"",
    Ind:"Engkau akan hidup dari pedangmu dan engkau akan menjadi hamba adikmu. Tetapi akan terjadi kelak, apabila engkau berusaha sungguh-sungguh, maka engkau akan melemparkan kuk itu dari tengkukmu.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:41, Page:1,
    Kor:"○에서는 아버지에게서 받을 축복을 야곱에게 빼앗긴 것 때문에 야곱에게 원한이 깊어갔다. 그는 혼자서 '아버지를 곡할 날이 머지 않았으니, 그 때가 되면, 동생 야곱을 죽이겠다' 하고 마음을 먹었다.",
    Chn:"以扫因他父亲给雅各祝的福，就怨恨雅各，心里说：「为我父亲居丧的日子近了，到那时候，我要杀我的兄弟雅各。」",
    Eng:"Esau held a grudge against Jacob because of the blessing his father had given him. He said  to himself, \"The days of mourning for my father are near; then I will kill my brother Jacob.\"",
    Ind:"Esau menaruh dendam kepada Yakub karena berkat yang telah diberikan oleh ayahnya kepadanya, lalu ia berkata kepada dirinya sendiri: \"Hari-hari berkabung karena kematian ayahku itu tidak akan lama lagi; pada waktu itulah Yakub, adikku, akan kubunuh.\""
  },
  {Bible:"Genesis", Chapter:27, Verse:42, Page:1,
    Kor:"리브가는 맏아들 에서가 하고 다니는 말을 전해 듣고는, 작은 아들을 불러다 놓고서 말하였다. \"너의 형 에서가 너를 죽여서, 한을 풀려고 한다.",
    Chn:"有人把利百加大儿子以扫的话告诉利百加，她就打发人去，叫了她小儿子雅各来，对他说：「你哥哥以扫想要杀你，报仇雪恨。",
    Eng:"When Rebekah was told what her older son Esau had said, she sent for her younger son Jacob  and said to him, \"Your brother Esau is consoling himself with the thought of killing you.",
    Ind:"Ketika diberitahukan perkataan Esau, anak sulungnya itu kepada Ribka, maka disuruhnyalah memanggil Yakub, anak bungsunya, lalu berkata kepadanya: \"Esau, kakakmu, bermaksud membalas dendam membunuh engkau."
  },
  {Bible:"Genesis", Chapter:27, Verse:43, Page:1,
    Kor:"그러니 나의 아들아, 내가 시키는 대로 하여라. 이제 곧 하란에 계시는 라반 외삼촌에게로 가거라.",
    Chn:"现在，我儿，你要听我的话：起来，逃往哈兰、我哥哥拉班那里去，",
    Eng:"Now then, my son, do what I say: Flee at once to my brother Laban in Haran.",
    Ind:"Jadi sekarang, anakku, dengarkanlah perkataanku, bersiaplah engkau dan larilah kepada Laban, saudaraku, ke Haran,"
  },
  {Bible:"Genesis", Chapter:27, Verse:44, Page:1,
    Kor:"네 형의 분노가 풀릴 때까지, 너는 얼마 동안 외삼촌 집에 머물러라.",
    Chn:"同他住些日子，直等你哥哥的怒气消了。",
    Eng:"Stay with him for a while until your brother's fury subsides.",
    Ind:"dan tinggallah padanya beberapa waktu lamanya, sampai kegeraman"
  },
  {Bible:"Genesis", Chapter:27, Verse:45, Page:1,
    Kor:"네 형의 분노가 풀리고, 네가 형에게 한 일을 너의 형이 잊으면, 거기를 떠나서 돌아오라고 전갈을 보내마. 내가 어찌 하루에 자식 둘을 다 잃겠느냐!\"",
    Chn:"你哥哥向你消了怒气，忘了你向他所做的事，我便打发人去把你从那里带回来。为什么一日丧你们二人呢？」",
    Eng:"When your brother is no longer angry with you and forgets what you did to him, I'll send  word for you to come back from there. Why should I lose both of you in one day?\"",
    Ind:"dan kemarahan kakakmu itu surut dari padamu, dan ia lupa apa yang telah engkau perbuat kepadanya; kemudian aku akan menyuruh orang menjemput engkau dari situ. Mengapa aku akan kehilangan kamu berdua pada satu hari juga?\""
  },
  {Bible:"Genesis", Chapter:27, Verse:46, Page:1,
    Kor:"<이삭이 야곱을 라반에게 보내다> ○리브가가 이삭에게 말하였다. \"나는, 헷 사람의 딸들 때문에, 사는 게 아주 넌더리가 납니다. 야곱이 이 땅에 사는 사람들의 딸들 곧 헷 사람의 딸들 가운데서 아내를 맞아들인다고 하면, 내가 살아 있다고는 하지만, 나에게 무슨 사는 재미가 있겠습니까?\"",
    Chn:"利百加对以撒说：「我因这赫人的女子连性命都厌烦了；倘若雅各也娶赫人的女子为妻，像这些一样，我活着还有什么益处呢？」",
    Eng:"Then Rebekah said to Isaac, \"I'm disgusted with living because of these Hittite women. If  Jacob takes a wife from among the women of this land, from Hittite women like these, my life will  not be worth living.\"",
    Ind:"Kemudian Ribka berkata kepada Ishak: \"Aku telah jemu hidup karena perempuan-perempuan Het itu; jikalau Yakub juga mengambil seorang isteri dari antara perempuan negeri ini, semacam perempuan Het itu, apa gunanya aku hidup lagi?\""
  },
]);
