// 창세기 43장 · Genesis 43
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Genesis",43,34);
BibleDB.add([
  {Bible:"Genesis", Chapter:43, Verse:1, Page:1, Kor:"", Chn:"", Eng:"Now the famine was still severe in the land.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:2, Page:1, Kor:"", Chn:"", Eng:"So when they had eaten all the grain they had brought from Egypt, their father said to them,  \"Go back and buy us a little more food.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:3, Page:1, Kor:"", Chn:"", Eng:"But Judah said to him, \"The man warned us solemnly, 'You will not see my face again unless  your brother is with you.'", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:4, Page:1, Kor:"", Chn:"", Eng:"If you will send our brother along with us, we will go down and buy food for you.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:5, Page:1, Kor:"", Chn:"", Eng:"But if you will not send him, we will not go down, because the man said to us, 'You will not  see my face again unless your brother is with you.'\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:6, Page:1, Kor:"", Chn:"", Eng:"Israel asked, \"Why did you bring this trouble on me by telling the man you had another  brother?\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:7, Page:1, Kor:"", Chn:"", Eng:"They replied, \"The man questioned us closely about ourselves and our family. 'Is your father  still living?' he asked us. 'Do you have another brother?' We simply answered his questions. How  were we to know he would say, 'Bring your brother down here'?\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:8, Page:1, Kor:"", Chn:"", Eng:"Then Judah said to Israel his father, \"Send the boy along with me and we will go at once, so  that we and you and our children may live and not die.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:9, Page:1, Kor:"", Chn:"", Eng:"I myself will guarantee his safety; you can hold me personally responsible for him. If I do  not bring him back to you and set him here before you, I will bear the blame before you all my  life.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:10, Page:1, Kor:"", Chn:"", Eng:"As it is, if we had not delayed, we could have gone and returned twice.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Then their father Israel said to them, \"If it must be, then do this: Put some of the best  products of the land in your bags and take them down to the man as a gift--a little balm and a  little honey, some spices and myrrh, some pistachio nuts and almonds.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:12, Page:1, Kor:"", Chn:"", Eng:"Take double the amount of silver with you, for you must return the silver that was put back  into the mouths of your sacks. Perhaps it was a mistake.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Take your brother also and go back to the man at once.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:14, Page:1, Kor:"", Chn:"", Eng:"And may God Almighty grant you mercy before the man so that he will let your other brother  and Benjamin come back with you. As for me, if I am bereaved, I am bereaved.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:15, Page:1, Kor:"", Chn:"", Eng:"So the men took the gifts and double the amount of silver, and Benjamin also. They hurried  down to Egypt and presented themselves to Joseph.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:16, Page:1, Kor:"", Chn:"", Eng:"When Joseph saw Benjamin with them, he said to the steward of his house, \"Take these men to  my house, slaughter an animal and prepare dinner; they are to eat with me at noon.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:17, Page:1, Kor:"", Chn:"", Eng:"The man did as Joseph told him and took the men to Joseph's house.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:18, Page:1, Kor:"", Chn:"", Eng:"Now the men were frightened when they were taken to his house. They thought, \"We were  brought here because of the silver that was put back into our sacks the first time. He wants to  attack us and overpower us and seize us as slaves and take our donkeys.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:19, Page:1, Kor:"", Chn:"", Eng:"So they went up to Joseph's steward and spoke to him at the entrance to the house.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:20, Page:1, Kor:"", Chn:"", Eng:"\"Please, sir,\" they said, \"we came down here the first time to buy food.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:21, Page:1, Kor:"", Chn:"", Eng:"But at the place where we stopped for the night we opened our sacks and each of us found  his silver--the exact weight--in the mouth of his sack. So we have brought it back with us.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:22, Page:1, Kor:"", Chn:"", Eng:"We have also brought additional silver with us to buy food. We don't know who put our  silver in our sacks.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:23, Page:1, Kor:"", Chn:"", Eng:"\"It's all right,\" he said. \"Don't be afraid. Your God, the God of your father, has given  you treasure in your sacks; I received your silver.\" Then he brought Simeon out to them.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:24, Page:1, Kor:"", Chn:"", Eng:"The steward took the men into Joseph's house, gave them water to wash their feet and  provided fodder for their donkeys.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:25, Page:1, Kor:"", Chn:"", Eng:"They prepared their gifts for Joseph's arrival at noon, because they had heard that they  were to eat there.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:26, Page:1, Kor:"", Chn:"", Eng:"When Joseph came home, they presented to him the gifts they had brought into the house, and  they bowed down before him to the ground.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:27, Page:1, Kor:"", Chn:"", Eng:"He asked them how they were, and then he said, \"How is your aged father you told me about?  Is he still living?\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:28, Page:1, Kor:"", Chn:"", Eng:"They replied, \"Your servant our father is still alive and well.\" And they bowed low to pay  him honor.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:29, Page:1, Kor:"", Chn:"", Eng:"As he looked about and saw his brother Benjamin, his own mother's son, he asked, \"Is this  your youngest brother, the one you told me about?\" And he said, \"God be gracious to you, my son.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:30, Page:1, Kor:"", Chn:"", Eng:"Deeply moved at the sight of his brother, Joseph hurried out and looked for a place to  weep. He went into his private room and wept there.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:31, Page:1, Kor:"", Chn:"", Eng:"After he had washed his face, he came out and, controlling himself, said, \"Serve the food.\"", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:32, Page:1, Kor:"", Chn:"", Eng:"They served him by himself, the brothers by themselves, and the Egyptians who ate with him  by themselves, because Egyptians could not eat with Hebrews, for that is detestable to Egyptians.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:33, Page:1, Kor:"", Chn:"", Eng:"The men had been seated before him in the order of their ages, from the firstborn to the  youngest; and they looked at each other in astonishment.", Ind:""},
  {Bible:"Genesis", Chapter:43, Verse:34, Page:1, Kor:"", Chn:"", Eng:"When portions were served to them from Joseph's table, Benjamin's portion was five times as  much as anyone else's. So they feasted and drank freely with him.", Ind:""},
]);
