// 창세기 34장 · Genesis 34
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Genesis",34,31);
BibleDB.add([
  {Bible:"Genesis", Chapter:34, Verse:1, Page:1,
    Kor:"<디나가 폭행을 당하다> 레아와 야곱 사이에서 태어난 딸 디나가 그 지방 여자들을 보러 나갔다.",
    Chn:"利亚给雅各所生的女儿底拿出去，要见那地的女子们。",
    Eng:"Now Dinah, the daughter Leah had borne to Jacob, went out to visit the women of the land.",
    Ind:"Pada suatu kali pergilah Dina, anak perempuan Lea yang dilahirkannya bagi Yakub, mengunjungi perempuan-perempuan di negeri itu."
  },
  {Bible:"Genesis", Chapter:34, Verse:2, Page:1,
    Kor:"히위 사람 하몰에게는 세겜이라는 아들이 있는데, 세겜은 그 지역의 통치자였다. 세겜이 디나를 보자, 데리고 가서 욕을 보였다.",
    Chn:"那地的主—希未人、哈抹的儿子示剑看见她，就拉住她，与她行淫，玷辱她。",
    Eng:"When Shechem son of Hamor the Hivite, the ruler of that area, saw her, he took her and  violated her.",
    Ind:"Ketika itu terlihatlah ia oleh Sikhem, anak Hemor, orang Hewi, raja negeri itu, lalu Dina itu dilarikannya dan diperkosanya."
  },
  {Bible:"Genesis", Chapter:34, Verse:3, Page:1,
    Kor:"그는 야곱의 딸 디나에게 마음을 빼앗겼다. 그는 디나를 사랑하기 때문에, 디나에게 사랑을 고백하였다.",
    Chn:"示剑的心系恋雅各的女儿底拿，喜爱这女子，甜言蜜语地安慰她。",
    Eng:"His heart was drawn to Dinah daughter of Jacob, and he loved the girl and spoke tenderly to  her.",
    Ind:"Tetapi terikatlah hatinya kepada Dina, anak Yakub; ia cinta kepada gadis itu, lalu menenangkan hati gadis itu."
  },
  {Bible:"Genesis", Chapter:34, Verse:4, Page:1,
    Kor:"세겜은 자기 아버지 하몰에게 말하였다. \"이 처녀를 아내로 삼게 해주십시오.\"",
    Chn:"示剑对他父亲哈抹说：「求你为我聘这女子为妻。」",
    Eng:"And Shechem said to his father Hamor, \"Get me this girl as my wife.\"",
    Ind:"Sebab itu berkatalah Sikhem kepada Hemor, ayahnya: \"Ambillah bagiku gadis ini untuk menjadi isteriku.\""
  },
  {Bible:"Genesis", Chapter:34, Verse:5, Page:1,
    Kor:"○야곱이 자기의 딸 디나의 몸을 세겜이 더럽혔다는 말을 들을 때에, 그의 아들들은 가축 떼와 함께 들에 있었다. 야곱은 아들들이 돌아올 때까지 이 일을 입 밖에 내지 않았다.",
    Chn:"雅各听见示剑玷污了他的女儿底拿。那时他的儿子们正和群畜在田野，雅各就闭口不言，等他们回来。",
    Eng:"When Jacob heard that his daughter Dinah had been defiled, his sons were in the fields with  his livestock; so he kept quiet about it until they came home.",
    Ind:"Kedengaranlah kepada Yakub, bahwa Sikhem mencemari Dina. Tetapi anak-anaknya ada di padang menjaga ternaknya, jadi Yakub mendiamkan soal itu sampai mereka pulang."
  },
  {Bible:"Genesis", Chapter:34, Verse:6, Page:1,
    Kor:"세겜의 아버지 하몰이 청혼을 하려고, 야곱을 만나러 왔다.",
    Chn:"示剑的父亲哈抹出来见雅各，要和他商议。",
    Eng:"Then Shechem's father Hamor went out to talk with Jacob.",
    Ind:"Lalu Hemor ayah Sikhem, pergi mendapatkan Yakub untuk berbicara dengan dia."
  },
  {Bible:"Genesis", Chapter:34, Verse:7, Page:1,
    Kor:"와서 보니, 야곱의 아들들이 이미 디나에게 일어난 일을 듣고, 들에서 돌아와 있었다. 세겜이 야곱의 딸을 욕보여서, 이스라엘 사람에게 부끄러운 일 곧 해서는 안 될 일을 하였으므로, 야곱의 아들들은 슬픔과 분노를 억누르지 못하고 있었다.",
    Chn:"雅各的儿子们听见这事，就从田野回来，人人忿恨，十分恼怒；因示剑在以色列家做了丑事，与雅各的女儿行淫，这本是不该做的事。",
    Eng:"Now Jacob's sons had come in from the fields as soon as they heard what had happened. They  were filled with grief and fury, because Shechem had done a disgraceful thing in Israel by lying  with Jacob's daughter--a thing that should not be done.",
    Ind:"Sementara itu anak-anak Yakub pulang dari padang, dan sesudah mendengar peristiwa itu orang-orang ini sakit hati dan sangat marah karena Sikhem telah berbuat noda di antara orang Israel dengan memperkosa anak perempuan Yakub, sebab yang demikian itu tidak patut dilakukan."
  },
  {Bible:"Genesis", Chapter:34, Verse:8, Page:1,
    Kor:"○하몰이 그들에게 말하였다. \"나의 아들 세겜이 댁의 따님에게 반했습니다. 댁의 따님과 나의 아들을 맺어 주시기 바랍니다.",
    Chn:"哈抹和他们商议说：「我儿子示剑的心恋慕这女子，求你们将她给我的儿子为妻。",
    Eng:"But Hamor said to them, \"My son Shechem has his heart set on your daughter. Please give her  to him as his wife.",
    Ind:"Berbicaralah Hemor kepada mereka itu: \"Hati Sikhem anakku mengingini anakmu; kiranya kamu memberikan dia kepadanya menjadi isterinya"
  },
  {Bible:"Genesis", Chapter:34, Verse:9, Page:1,
    Kor:"우리 사이에 서로 통혼할 것을 제의합니다. 따님들을 우리 쪽으로 시집보내어 주시고, 우리의 딸들도 며느리로 데려가시기 바랍니다.",
    Chn:"你们与我们彼此结亲；你们可以把女儿给我们，也可以娶我们的女儿。",
    Eng:"Intermarry with us; give us your daughters and take our daughters for yourselves.",
    Ind:"dan biarlah kita ambil-mengambil: berikanlah gadis-gadis kamu kepada kami dan ambillah gadis-gadis kami."
  },
  {Bible:"Genesis", Chapter:34, Verse:10, Page:1,
    Kor:"그리고 우리와 함께 섞여서, 여기에서 같이 살기를 바랍니다. 땅이 여러분 앞에 있습니다. 이 땅에서 자리를 잡고, 여기에서 장사도 하고, 여기에서 재산을 늘리십시오.\"",
    Chn:"你们与我们同住吧！这地都在你们面前，只管在此居住，做买卖，置产业。」",
    Eng:"You can settle among us; the land is open to you. Live in it, trade in it, and acquire  property in it.\"",
    Ind:"Tinggallah pada kami: negeri ini terbuka untuk kamu; tinggallah di sini, jalanilah negeri ini dengan bebas, dan menetaplah di sini.\""
  },
  {Bible:"Genesis", Chapter:34, Verse:11, Page:1,
    Kor:"세겜도 디나의 아버지와 오라버니들에게 간청하였다. \"저를 너그러이 보아 주시기 바랍니다. 원하시는 것은 무엇이든지 드리겠습니다.",
    Chn:"示剑对女儿的父亲和弟兄们说：「但愿我在你们眼前蒙恩，你们向我要什么，我必给你们。",
    Eng:"Then Shechem said to Dinah's father and brothers, \"Let me find favor in your eyes, and I  will give you whatever you ask.",
    Ind:"Lalu Sikhem berkata kepada ayah anak itu dan kepada kakak-kakaknya: \"Biarlah kiranya aku mendapat kasihmu, aku akan memberikan kepadamu apa yang kamu minta;"
  },
  {Bible:"Genesis", Chapter:34, Verse:12, Page:1,
    Kor:"신부를 데려오는 데 치러야 할 값을 정해 주시고, 제가 가져 와야 할 예물의 값도 정해 주시기 바랍니다. 아무리 많이 요구하셔도, 요구하시는 만큼 제가 치르겠습니다. 다만 제가 바라는 것은, 디나를 저의 아내로 주시기를 바라는 것뿐입니다.\"",
    Chn:"任凭向我要多重的聘金和礼物，我必照你们所说的给你们；只要把女子给我为妻。」",
    Eng:"Make the price for the bride and the gift I am to bring as great as you like, and I'll pay  whatever you ask me. Only give me the girl as my wife.\"",
    Ind:"walaupun kamu bebankan kepadaku uang jujuran dan uang mahar seberapa banyakpun, aku akan memberikan apa yang kamu minta; tetapi berilah gadis itu kepadaku menjadi isteriku.\""
  },
  {Bible:"Genesis", Chapter:34, Verse:13, Page:1,
    Kor:"○야곱의 아들들은, 세겜이 그들의 누이 디나를 욕보였으므로, 세겜과 그의 아버지 하몰에게 짐짓 속임수를 썼다.",
    Chn:"雅各的儿子们因为示剑玷污了他们的妹子底拿，就用诡诈的话回答示剑和他父亲哈抹，",
    Eng:"Because their sister Dinah had been defiled, Jacob's sons replied deceitfully as they spoke  to Shechem and his father Hamor.",
    Ind:"Lalu anak-anak Yakub menjawab Sikhem dan Hemor, ayahnya, dengan tipu muslihat. Karena Sikhem telah mencemari Dina, adik mereka itu,"
  },
  {Bible:"Genesis", Chapter:34, Verse:14, Page:1,
    Kor:"그들은 세겜과 하몰에게 이렇게 말하였다. \"우리는 그렇게 할 수 없습니다. 할례를 받지 않은 남자에게 우리의 누이를 줄 수 없습니다. 그렇게 하는 것은 우리에게 부끄러운 일입니다.",
    Chn:"对他们说：「我们不能把我们的妹子给没有受割礼的人为妻，因为那是我们的羞辱。",
    Eng:"They said to them, \"We can't do such a thing; we can't give our sister to a man who is not  circumcised. That would be a disgrace to us.",
    Ind:"berkatalah mereka kepada kedua orang itu: \"Kami tidak dapat berbuat demikian, memberikan adik kami kepada seorang laki-laki yang tidak bersunat, sebab hal itu aib bagi kami."
  },
  {Bible:"Genesis", Chapter:34, Verse:15, Page:1,
    Kor:"조건이 하나 있습니다. 당신들 쪽에서 남자들이 우리처럼 모두 할례를 받겠다고 하면, 그 청혼을 받아들이겠습니다.",
    Chn:"惟有一件才可以应允：若你们所有的男丁都受割礼，和我们一样，",
    Eng:"We will give our consent to you on one condition only: that you become like us by  circumcising all your males.",
    Ind:"Hanyalah dengan syarat ini kami dapat menyetujui permintaanmu: kamu harus sama seperti kami, yaitu setiap laki-laki di antara kamu harus disunat,"
  },
  {Bible:"Genesis", Chapter:34, Verse:16, Page:1,
    Kor:"그렇게 하면, 우리가 딸들을 당신들에게로 시집도 보내고, 당신네 딸들을 우리가 며느리로 삼으며, 당신들과 함께 여기에서 살고, 더불어 한 겨레가 되겠습니다.",
    Chn:"我们就把女儿给你们，也娶你们的女儿；我们便与你们同住，两下成为一样的人民。",
    Eng:"Then we will give you our daughters and take your daughters for ourselves. We'll settle  among you and become one people with you.",
    Ind:"barulah kami akan memberikan gadis-gadis kami kepada kamu dan mengambil gadis-gadis kamu; maka kami akan tinggal padamu, dan kita akan menjadi satu bangsa."
  },
  {Bible:"Genesis", Chapter:34, Verse:17, Page:1,
    Kor:"그러나 당신들 쪽에서 할례 받기를 거절하면, 우리는 우리의 누이를 데리고 여기에서 떠나겠습니다.\"",
    Chn:"倘若你们不听从我们受割礼，我们就带着妹子走了。」",
    Eng:"But if you will not agree to be circumcised, we'll take our sister and go.\"",
    Ind:"Tetapi jika kamu tidak mendengarkan perkataan kami dan kamu tidak disunat, maka kami akan mengambil kembali anak itu, lalu pergi.\""
  },
  {Bible:"Genesis", Chapter:34, Verse:18, Page:1,
    Kor:"○하몰과 그의 아들 세겜은, 야곱의 아들들이 내놓은 제안을 좋게 여겼다.",
    Chn:"哈抹和他的儿子示剑喜欢这话。",
    Eng:"Their proposal seemed good to Hamor and his son Shechem.",
    Ind:"Lalu Hemor dan Sikhem, anak Hemor, menyetujui usul mereka."
  },
  {Bible:"Genesis", Chapter:34, Verse:19, Page:1,
    Kor:"그래서 그 젊은이는 시간을 지체하지 않고, 그들이 제안한 것을 실천으로 옮겼다. 그만큼 그는 야곱의 딸을 좋아하였다. 세겜은 자기 아버지의 집안에서 가장 존귀한 인물이었다.",
    Chn:"那少年人做这事并不迟延，因为他喜爱雅各的女儿；他在他父亲家中也是人最尊重的。",
    Eng:"The young man, who was the most honored of all his father's household, lost no time in  doing what they said, because he was delighted with Jacob's daughter.",
    Ind:"Dan orang muda itu tidak bertangguh melakukannya, sebab ia suka kepada anak Yakub, lagipula ia seorang yang paling dihormati di antara seluruh kaum keluarganya."
  },
  {Bible:"Genesis", Chapter:34, Verse:20, Page:1,
    Kor:"하몰과 그의 아들 세겜이 성문께로 가서, 그들의 성읍 사람들에게 말하였다.",
    Chn:"哈抹和他儿子示剑到本城的门口，对本城的人说：",
    Eng:"So Hamor and his son Shechem went to the gate of their city to speak to their fellow  townsmen.",
    Ind:"Lalu pergilah Hemor dan Sikhem, anaknya itu, ke pintu gerbang kota mereka dan mereka berbicara kepada penduduk kota itu:"
  },
  {Bible:"Genesis", Chapter:34, Verse:21, Page:1,
    Kor:"\"이 사람들이 우리에게 우호적입니다. 그러니 그들이 우리 땅에서 살면서, 우리와 함께 물건을 서로 사고팔게 합시다. 이 땅은 그들을 받아들일 수 있을 만큼 넓습니다. 우리가 그들의 딸들과 결혼할 수 있게 하고, 그들은 우리의 딸들과 결혼할 수 있게 합시다.",
    Chn:"「这些人与我们和睦，不如许他们在这地居住，做买卖；这地也宽阔，足可容下他们。我们可以娶他们的女儿为妻，也可以把我们的女儿嫁给他们。",
    Eng:"\"These men are friendly toward us,\" they said. \"Let them live in our land and trade in it;  the land has plenty of room for them. We can marry their daughters and they can marry ours.",
    Ind:"\"Orang-orang itu mau hidup damai dengan kita, biarlah mereka tinggal di negeri ini dan menjalaninya dengan bebas; bukankah negeri ini cukup luas untuk mereka? Maka kita dapat mengambil gadis-gadis mereka menjadi isteri kita dan kita dapat memberikan gadis-gadis kita kepada mereka."
  },
  {Bible:"Genesis", Chapter:34, Verse:22, Page:1,
    Kor:"그러나 이 사람들이 기꺼이 우리와 한 겨레가 되어서, 우리와 함께 사는 데는, 조건이 하나 있습니다. 그들이 할례를 받는 것처럼, 우리쪽 남자들이 모두 할례를 받아야 한다는 것입니다.",
    Chn:"惟有一件事我们必须做，他们才肯应允和我们同住，成为一样的人民：就是我们中间所有的男丁都要受割礼，和他们一样。",
    Eng:"But the men will consent to live with us as one people only on the condition that our males  be circumcised, as they themselves are.",
    Ind:"Namun hanya dengan syarat ini orang-orang itu setuju tinggal bersama-sama dengan kita, sehingga kita menjadi satu bangsa, yaitu setiap laki-laki di antara kita harus disunat seperti mereka bersunat."
  },
  {Bible:"Genesis", Chapter:34, Verse:23, Page:1,
    Kor:"그렇게 하면, 그들의 양 떼와 재산과 집짐승이 모두 우리의 것이 되지 않겠습니까? 다만, 그들이 우리에게 요구하는 것은 그대로 합시다. 우리가 그렇게 할례를 받으면, 그들이 우리와 함께 살 것입니다.\"",
    Chn:"他们的群畜、货财，和一切的牲口岂不都归我们吗？只要依从他们，他们就与我们同住。」",
    Eng:"Won't their livestock, their property and all their other animals become ours? So let us  give our consent to them, and they will settle among us.\"",
    Ind:"Ternak mereka, harta benda mereka dan segala hewan mereka, bukankah semuanya itu akan menjadi milik kita? Hanya biarlah kita menyetujui permintaan mereka, sehingga mereka tetap tinggal pada kita.\""
  },
  {Bible:"Genesis", Chapter:34, Verse:24, Page:1,
    Kor:"그 성읍의 모든 장정이, 하몰과 그의 아들 세겜이 제안한 것을 좋게 여겼다. 그래서 그 장정들은 모두 할례를 받았다.",
    Chn:"凡从城门出入的人就都听从哈抹和他儿子示剑的话；于是凡从城门出入的男丁都受了割礼。",
    Eng:"All the men who went out of the city gate agreed with Hamor and his son Shechem, and every  male in the city was circumcised.",
    Ind:"Maka usul Hemor dan Sikhem, anaknya itu, didengarkan oleh semua orang yang datang berkumpul di pintu gerbang kota itu, lalu disunatlah setiap laki-laki, yakni setiap orang dewasa di kota itu."
  },
  {Bible:"Genesis", Chapter:34, Verse:25, Page:1,
    Kor:"○사흘 뒤에, 장정 모두가 아직 상처가 아물지 않아서 아파하고 있을 때에, 야곱의 아들들 곧 디나의 친오라버니들인 시므온과 레위가, 칼을 들고 성읍으로 쳐들어가서, 순식간에 남자들을 모조리 죽였다.",
    Chn:"到第三天，众人正在疼痛的时候，雅各的两个儿子，就是底拿的哥哥西缅和利未，各拿刀剑，趁着众人想不到的时候来到城中，把一切男丁都杀了，",
    Eng:"Three days later, while all of them were still in pain, two of Jacob's sons, Simeon and  Levi, Dinah's brothers, took their swords and attacked the unsuspecting city, killing every male.",
    Ind:"Pada hari ketiga, ketika mereka sedang menderita kesakitan, datanglah dua orang anak Yakub, yaitu Simeon dan Lewi, kakak-kakak Dina, setelah masing-masing mengambil pedangnya, menyerang kota itu dengan tidak takut-takut serta membunuh setiap laki-laki."
  },
  {Bible:"Genesis", Chapter:34, Verse:26, Page:1,
    Kor:"그들은 하몰과 그의 아들 세겜도 칼로 쳐서 죽이고, 세겜의 집에 있는 디나를 데려왔다.",
    Chn:"又用刀杀了哈抹和他儿子示剑，把底拿从示剑家里带出来就走了。",
    Eng:"They put Hamor and his son Shechem to the sword and took Dinah from Shechem's house and  left.",
    Ind:"Juga Hemor dan Sikhem, anaknya, dibunuh mereka dengan mata pedang, dan mereka mengambil Dina dari rumah Sikhem, lalu pergi."
  },
  {Bible:"Genesis", Chapter:34, Verse:27, Page:1,
    Kor:"야곱의 다른 아들들은, 죽은 시체에 달려들어서 털고, 그들의 누이가 욕을 본 그 성읍을 약탈하였다.",
    Chn:"雅各的儿子们因为他们的妹子受了玷污，就来到被杀的人那里，掳掠那城，",
    Eng:"The sons of Jacob came upon the dead bodies and looted the city where their sister had been  defiled.",
    Ind:"Kemudian datanglah anak-anak Yakub merampasi orang-orang yang terbunuh itu, lalu menjarah kota itu, karena adik mereka telah dicemari."
  },
  {Bible:"Genesis", Chapter:34, Verse:28, Page:1,
    Kor:"그들은, 양과 소와 나귀와 성 안에 있는 것과 성 바깥들에 있는 것과",
    Chn:"夺了他们的羊群、牛群，和驴，并城里田间所有的；",
    Eng:"They seized their flocks and herds and donkeys and everything else of theirs in the city  and out in the fields.",
    Ind:"Kambing dombanya dan lembu sapinya, keledainya dan segala yang di dalam dan di luar kota itu dibawa mereka;"
  },
  {Bible:"Genesis", Chapter:34, Verse:29, Page:1,
    Kor:"모든 재산을 빼앗고, 어린 것들과 아낙네들을 사로잡고, 집 안에 있는 물건을 다 약탈하였다.",
    Chn:"又把他们一切货财、孩子、妇女，并各房中所有的，都掳掠去了。",
    Eng:"They carried off all their wealth and all their women and children, taking as plunder  everything in the houses.",
    Ind:"segala kekayaannya, semua anaknya dan perempuannya ditawan dan dijarah mereka, juga seluruhnya yang ada di rumah-rumah."
  },
  {Bible:"Genesis", Chapter:34, Verse:30, Page:1,
    Kor:"일이 이쯤 되니, 야곱이 시므온과 레위를 나무랐다. \"너희는 나를 오히려 더 어렵게 만들었다. 이제 가나안 사람이나, 브리스 사람이나, 이 땅에 사는 모든 사람이, 나를 사귀지도 못할 추한 인간이라고 여길 게 아니냐? 우리는 수가 적은데, 그들이 합세해서, 나를 치고, 나를 죽이면, 나와 나의 01 34:집안이 다 몰살당할 수밖에 없지 않느냐?\"",
    Chn:"雅各对西缅和利未说：「你们连累我，使我在这地的居民中，就是在迦南人和比利洗人中，有了臭名。我的人丁既然稀少，他们必聚集来击杀我，我和全家的人都必灭绝。」",
    Eng:"Then Jacob said to Simeon and Levi, \"You have brought trouble on me by making me a stench  to the Canaanites and Perizzites, the people living in this land. We are few in number, and if  they join forces against me and attack me, I and my household will be destroyed.\"",
    Ind:"Yakub berkata kepada Simeon dan Lewi: \"Kamu telah mencelakakan aku dengan membusukkan namaku kepada penduduk negeri ini, kepada orang Kanaan dan orang Feris, padahal kita ini hanya sedikit jumlahnya; apabila mereka bersekutu melawan kita, tentulah mereka akan memukul kita kalah, dan kita akan dipunahkan, aku beserta seisi rumahku.\""
  },
  {Bible:"Genesis", Chapter:34, Verse:31, Page:1,
    Kor:"그들이 대답하였다. \"그가 우리 누이를 창녀 다루듯이 하는 데도, 그대로 두라는 말입니까?\"",
    Chn:"他们说：「他岂可待我们的妹子如同妓女吗？」",
    Eng:"But they replied, \"Should he have treated our sister like a prostitute?\"",
    Ind:"Tetapi jawab mereka: \"Mengapa adik kita diperlakukannya sebagai seorang perempuan sundal!\""
  },
]);
