// 창세기 1장 · Genesis 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Genesis",1,31);
BibleDB.add([
  {Bible:"Genesis", Chapter:1, Verse:1, Page:1,
    Kor:"<천지창조> a태초에 하나님이 천지를 창조하셨다.(a 또는 '태초에 하나님이 천지를 창조하실 때에' 또는 '하나님이 천지를 창조하기 시작하셨을 때에')",
    Chn:"起初，　神创造天地。",
    Eng:"In the beginning God created the heavens and the earth.",
    Ind:"Pada mulanya Allah menciptakan langit dan bumi."
  },
  {Bible:"Genesis", Chapter:1, Verse:2, Page:1,
    Kor:"땅이 혼돈하고 공허하며, 어둠이 깊음 위에 있고, b하나님의 영은 물 위에 움직이고 계셨다.(b 또는 '하나님의 바람' 또는 '강한 바람')",
    Chn:"地是空虚混沌，渊面黑暗；　神的灵运行在水面上。",
    Eng:"Now the earth was formless and empty, darkness was over the surface of the deep, and the  Spirit of God was hovering over the waters.",
    Ind:"Bumi belum berbentuk dan kosong; gelap gulita menutupi samudera raya, dan Roh Allah melayang-layang di atas permukaan air."
  },
  {Bible:"Genesis", Chapter:1, Verse:3, Page:1,
    Kor:"○하나님이 말씀하시기를 \"빛이 생겨라\" 하시니, 빛이 생겼다.",
    Chn:"神说：「要有光」，就有了光。",
    Eng:"And God said, \"Let there be light,\" and there was light.",
    Ind:"Berfirmanlah Allah: \"Jadilah terang.\" Lalu terang itu jadi."
  },
  {Bible:"Genesis", Chapter:1, Verse:4, Page:1,
    Kor:"그 빛이 하나님 보시기에 좋았다. 하나님이 빛과 어둠을 나누셔서,",
    Chn:"神看光是好的，就把光暗分开了。",
    Eng:"God saw that the light was good, and he separated the light from the darkness.",
    Ind:"Allah melihat bahwa terang itu baik, lalu dipisahkan-Nyalah terang itu dari gelap."
  },
  {Bible:"Genesis", Chapter:1, Verse:5, Page:1,
    Kor:"빛을 낮이라고 하시고, 어둠을 밤이라고 하셨다. 저녁이 되고 아침이 되니, 하루가 지났다.",
    Chn:"神称光为「昼」，称暗为「夜」。有晚上，有早晨，这是头一日。",
    Eng:"God called the light \"day,\" and the darkness he called \"night.\" And there was evening, and  there was morning--the first day.",
    Ind:"Dan Allah menamai terang itu siang, dan gelap itu malam. Jadilah petang dan jadilah pagi, itulah hari pertama."
  },
  {Bible:"Genesis", Chapter:1, Verse:6, Page:1,
    Kor:"○하나님이 말씀하시기를 \"물 한가운데 창공이 생겨, 물과 물 사이가 갈라져라\" 하셨다.",
    Chn:"神说：「诸水之间要有空气，将水分为上下。」",
    Eng:"And God said, \"Let there be an expanse between the waters to separate water from water.\"",
    Ind:"Berfirmanlah Allah: \"Jadilah cakrawala di tengah segala air untuk memisahkan air dari air.\""
  },
  {Bible:"Genesis", Chapter:1, Verse:7, Page:1,
    Kor:"하나님이 이처럼 창공을 만드시고서, 물을 창공 아래에 있는 물과 창공 위에 있는 물로 나누시니, 그대로 되었다.",
    Chn:"神就造出空气，将空气以下的水、空气以上的水分开了。事就这样成了。",
    Eng:"So God made the expanse and separated the water under the expanse from the water above it.  And it was so.",
    Ind:"Maka Allah menjadikan cakrawala dan Ia memisahkan air yang ada di bawah cakrawala itu dari air yang ada di atasnya. Dan jadilah demikian."
  },
  {Bible:"Genesis", Chapter:1, Verse:8, Page:1,
    Kor:"하나님이 창공을 하늘이라고 하셨다. 저녁이 되고 아침이 되니, 이튿날이 지났다.",
    Chn:"神称空气为「天」。有晚上，有早晨，是第二日。",
    Eng:"God called the expanse \"sky.\" And there was evening, and there was morning--the second day.",
    Ind:"Lalu Allah menamai cakrawala itu langit. Jadilah petang dan jadilah pagi, itulah hari kedua."
  },
  {Bible:"Genesis", Chapter:1, Verse:9, Page:1,
    Kor:"○하나님이 말씀하시기를 \"하늘 아래에 있는 물은 한 곳으로 모이고, 뭍은 드러나거라\" 하시니, 그대로 되었다.",
    Chn:"神说：「天下的水要聚在一处，使旱地露出来。」事就这样成了。",
    Eng:"And God said, \"Let the water under the sky be gathered to one place, and let dry ground  appear.\" And it was so.",
    Ind:"Berfirmanlah Allah: \"Hendaklah segala air yang di bawah langit berkumpul pada satu tempat, sehingga kelihatan yang kering.\" Dan jadilah demikian."
  },
  {Bible:"Genesis", Chapter:1, Verse:10, Page:1,
    Kor:"하나님이 뭍을 땅이라고 하시고, 모인 물을 바다라고 하셨다. 하나님 보시기에 좋았다.",
    Chn:"神称旱地为「地」，称水的聚处为「海」。　神看着是好的。",
    Eng:"God called the dry ground \"land,\" and the gathered waters he called \"seas.\" And God saw that  it was good.",
    Ind:"Lalu Allah menamai yang kering itu darat, dan kumpulan air itu dinamai-Nya laut. Allah melihat bahwa semuanya itu baik."
  },
  {Bible:"Genesis", Chapter:1, Verse:11, Page:1,
    Kor:"하나님이 말씀하시기를 \"땅은 푸른 움을 돋아나게 하여라. 씨를 맺는 식물과 씨 있는 열매를 맺는 나무가 그 종류대로 땅 위에서 돋아나게 하여라\" 하시니, 그대로 되었다.",
    Chn:"神说：「地要发生青草和结种子的菜蔬，并结果子的树木，各从其类，果子都包着核。」事就这样成了。",
    Eng:"Then God said, \"Let the land produce vegetation: seed-bearing plants and trees on the land  that bear fruit with seed in it, according to their various kinds.\" And it was so.",
    Ind:"Berfirmanlah Allah: \"Hendaklah tanah menumbuhkan tunas-tunas muda, tumbuh-tumbuhan yang berbiji, segala jenis pohon buah-buahan yang menghasilkan buah yang berbiji, supaya ada tumbuh-tumbuhan di bumi.\" Dan jadilah demikian."
  },
  {Bible:"Genesis", Chapter:1, Verse:12, Page:1,
    Kor:"땅은 푸른 움을 돋아나게 하고, 씨를 맺는 식물을 그 종류대로 나게 하고, 씨 있는 열매를 맺는 나무를 그 종류대로 돋아나게 하였다. 하나님 보시기에 좋았다.",
    Chn:"于是地发生了青草和结种子的菜蔬，各从其类；并结果子的树木，各从其类；果子都包着核。　神看着是好的。",
    Eng:"The land produced vegetation: plants bearing seed according to their kinds and trees bearing  fruit with seed in it according to their kinds. And God saw that it was good.",
    Ind:"Tanah itu menumbuhkan tunas-tunas muda, segala jenis tumbuh-tumbuhan yang berbiji dan segala jenis pohon-pohonan yang menghasilkan buah yang berbiji. Allah melihat bahwa semuanya itu baik."
  },
  {Bible:"Genesis", Chapter:1, Verse:13, Page:1,
    Kor:"저녁이 되고 아침이 되니, 사흗날이 지났다.",
    Chn:"有晚上，有早晨，是第三日。",
    Eng:"And there was evening, and there was morning--the third day.",
    Ind:"Jadilah petang dan jadilah pagi, itulah hari ketiga."
  },
  {Bible:"Genesis", Chapter:1, Verse:14, Page:1,
    Kor:"○하나님이 말씀하시기를 \"하늘 창공에 빛나는 것들이 생겨서, 낮과 밤을 가르고, 계절과 날과 해를 나타내는 표가 되어라.",
    Chn:"神说：「天上要有光体，可以分昼夜，作记号，定节令、日子、年岁，",
    Eng:"And God said, \"Let there be lights in the expanse of the sky to separate the day from the  night, and let them serve as signs to mark seasons and days and years,",
    Ind:"Berfirmanlah Allah: \"Jadilah benda-benda penerang pada cakrawala untuk memisahkan siang dari malam. Biarlah benda-benda penerang itu menjadi tanda yang menunjukkan masa-masa yang tetap dan hari-hari dan tahun-tahun,"
  },
  {Bible:"Genesis", Chapter:1, Verse:15, Page:1,
    Kor:"또 하늘 창공에 있는 빛나는 것들은 땅을 환히 비추어라\" 하시니, 그대로 되었다.",
    Chn:"并要发光在天空，普照在地上。」事就这样成了。",
    Eng:"and let them be lights in the expanse of the sky to give light on the earth.\" And it was so.",
    Ind:"dan sebagai penerang pada cakrawala biarlah benda-benda itu menerangi bumi.\" Dan jadilah demikian."
  },
  {Bible:"Genesis", Chapter:1, Verse:16, Page:1,
    Kor:"하나님이 두 큰 빛을 만드시고, 둘 가운데서 큰 빛으로는 낮을 다스리게 하시고, 작은 빛으로는 밤을 다스리게 하셨다. 또 별들도 만드셨다.",
    Chn:"于是　神造了两个大光，大的管昼，小的管夜，又造众星，",
    Eng:"God made two great lights--the greater light to govern the day and the lesser light to  govern the night. He also made the stars.",
    Ind:"Maka Allah menjadikan kedua benda penerang yang besar itu, yakni yang lebih besar untuk menguasai siang dan yang lebih kecil untuk menguasai malam, dan menjadikan juga bintang-bintang."
  },
  {Bible:"Genesis", Chapter:1, Verse:17, Page:1,
    Kor:"하나님이 빛나는 것들을 하늘 창공에 두시고 땅을 비추게 하시고,",
    Chn:"就把这些光摆列在天空，普照在地上，",
    Eng:"God set them in the expanse of the sky to give light on the earth,",
    Ind:"Allah menaruh semuanya itu di cakrawala untuk menerangi bumi,"
  },
  {Bible:"Genesis", Chapter:1, Verse:18, Page:1,
    Kor:"낮과 밤을 다스리게 하시며, 빛과 어둠을 가르게 하셨다. 하나님 보시기에 좋았다.",
    Chn:"管理昼夜，分别明暗。　神看着是好的。",
    Eng:"to govern the day and the night, and to separate light from darkness. And God saw that it  was good.",
    Ind:"dan untuk menguasai siang dan malam, dan untuk memisahkan terang dari gelap. Allah melihat bahwa semuanya itu baik."
  },
  {Bible:"Genesis", Chapter:1, Verse:19, Page:1,
    Kor:"저녁이 되고 아침이 되니, 나흗날이 지났다.",
    Chn:"有晚上，有早晨，是第四日。",
    Eng:"And there was evening, and there was morning--the fourth day.",
    Ind:"Jadilah petang dan jadilah pagi, itulah hari keempat."
  },
  {Bible:"Genesis", Chapter:1, Verse:20, Page:1,
    Kor:"○하나님이 말씀하시기를 \"물은 생물을 번성하게 하고, 새들은 땅 위 하늘 창공으로 날아다녀라\" 하셨다.",
    Chn:"神说：「水要多多滋生有生命的物；要有雀鸟飞在地面以上，天空之中。」",
    Eng:"And God said, \"Let the water teem with living creatures, and let birds fly above the earth  across the expanse of the sky.\"",
    Ind:"Berfirmanlah Allah: \"Hendaklah dalam air berkeriapan makhluk yang hidup, dan hendaklah burung beterbangan di atas bumi melintasi cakrawala.\""
  },
  {Bible:"Genesis", Chapter:1, Verse:21, Page:1,
    Kor:"하나님이 커다란 바다 짐승들과 물에서 번성하는 움직이는 모든 생물을 그 종류대로 창조하시고, 날개 달린 모든 새를 그 종류대로 창조하셨다. 하나님 보시기에 좋았다.",
    Chn:"神就造出大鱼和水中所滋生各样有生命的动物，各从其类；又造出各样飞鸟，各从其类。　神看着是好的。",
    Eng:"So God created the great creatures of the sea and every living and moving thing with which  the water teems, according to their kinds, and every winged bird according to its kind. And God  saw that it was good.",
    Ind:"Maka Allah menciptakan binatang-binatang laut yang besar dan segala jenis makhluk hidup yang bergerak, yang berkeriapan dalam air, dan segala jenis burung yang bersayap. Allah melihat bahwa semuanya itu baik."
  },
  {Bible:"Genesis", Chapter:1, Verse:22, Page:1,
    Kor:"하나님이 이것들에게 복을 베푸시면서 말씀하시기를 \"생육하고 번성하여 여러 바닷물에 충만하여라. 새들도 땅 위에서 번성하여라\" 하셨다.",
    Chn:"神就赐福给这一切，说：「滋生繁多，充满海中的水；雀鸟也要多生在地上。」",
    Eng:"God blessed them and said, \"Be fruitful and increase in number and fill the water in the  seas, and let the birds increase on the earth.\"",
    Ind:"Lalu Allah memberkati semuanya itu, firman-Nya: \"Berkembangbiaklah dan bertambah banyaklah serta penuhilah air dalam laut, dan hendaklah burung-burung di bumi bertambah banyak.\""
  },
  {Bible:"Genesis", Chapter:1, Verse:23, Page:1,
    Kor:"저녁이 되고 아침이 되니, 닷샛날이 지났다.",
    Chn:"有晚上，有早晨，是第五日。",
    Eng:"And there was evening, and there was morning--the fifth day.",
    Ind:"Jadilah petang dan jadilah pagi, itulah hari kelima."
  },
  {Bible:"Genesis", Chapter:1, Verse:24, Page:1,
    Kor:"○하나님이 말씀하시기를 \"땅은 생물을 그 종류대로 내어라. 집짐승과 기어다니는 것과 들짐승을 그 종류대로 내어라\" 하시니, 그대로 되었다.",
    Chn:"神说：「地要生出活物来，各从其类；牲畜、昆虫、野兽，各从其类。」事就这样成了。",
    Eng:"And God said, \"Let the land produce living creatures according to their kinds: livestock,  creatures that move along the ground, and wild animals, each according to its kind.\" And it was  so.",
    Ind:"Berfirmanlah Allah: \"Hendaklah bumi mengeluarkan segala jenis makhluk yang hidup, ternak dan binatang melata dan segala jenis binatang liar.\" Dan jadilah demikian."
  },
  {Bible:"Genesis", Chapter:1, Verse:25, Page:1,
    Kor:"하나님이 들짐승을 그 종류대로, 집짐승도 그 종류대로, 들에 사는 모든 길짐승도 그 종류대로 만드셨다. 하나님 보시기에 좋았다.",
    Chn:"于是　神造出野兽，各从其类；牲畜，各从其类；地上一切昆虫，各从其类。　神看着是好的。",
    Eng:"God made the wild animals according to their kinds, the livestock according to their kinds,  and all the creatures that move along the ground according to their kinds. And God saw that it  was good.",
    Ind:"Allah menjadikan segala jenis binatang liar dan segala jenis ternak dan segala jenis binatang melata di muka bumi. Allah melihat bahwa semuanya itu baik."
  },
  {Bible:"Genesis", Chapter:1, Verse:26, Page:1,
    Kor:"○하나님이 말씀하시기를 \"우리가 우리의 형상을 따라서, 우리의 모양대로 c사람을 만들자. 그리고 그가, 바다의 고기와 공중의 새와 땅 위에 사는 온갖 들짐승과 땅 위를 기어다니는 모든 길짐승을 다스리게 하자\" 하시고,(c 히, '아담')",
    Chn:"神说：「我们要照着我们的形象、按着我们的样式造人，使他们管理海里的鱼、空中的鸟、地上的牲畜，和全地，并地上所爬的一切昆虫。」",
    Eng:"Then God said, \"Let us make man in our image, in our likeness, and let them rule over the  fish of the sea and the birds of the air, over the livestock, over all the earth, and over all  the creatures that move along the ground.\"",
    Ind:"Berfirmanlah Allah: \"Baiklah Kita menjadikan manusia menurut gambar dan rupa Kita, supaya mereka berkuasa atas ikan-ikan di laut dan burung-burung di udara dan atas ternak dan atas seluruh bumi dan atas segala binatang melata yang merayap di bumi.\""
  },
  {Bible:"Genesis", Chapter:1, Verse:27, Page:1,
    Kor:"하나님이 당신의 형상대로 c사람을 창조하셨으니, 곧 하나님의 형상대로 사람을 창조하셨다. 하나님이 그들을 남자와 여자로 창조하셨다.",
    Chn:"神就照着自己的形象造人，乃是照着他的形象造男造女。",
    Eng:"So God created man in his own image, in the image of God he created him; male and female he  created them.",
    Ind:"Maka Allah menciptakan manusia itu menurut gambar-Nya, menurut gambar Allah diciptakan-Nya dia; laki-laki dan perempuan diciptakan-Nya mereka."
  },
  {Bible:"Genesis", Chapter:1, Verse:28, Page:1,
    Kor:"하나님이 그들에게 복을 베푸셨다. 하나님이 그들에게 말씀하시기를 \"생육하고 번성하여 땅에 충만하여라. 땅을 정복하여라. 바다의 고기와 공중의 새와 땅 위에서 살아 움직이는 모든 생물을 다스려라\" 하셨다.",
    Chn:"神就赐福给他们，又对他们说：「要生养众多，遍满地面，治理这地，也要管理海里的鱼、空中的鸟，和地上各样行动的活物。」",
    Eng:"God blessed them and said to them, \"Be fruitful and increase in number; fill the earth and  subdue it. Rule over the fish of the sea and the birds of the air and over every living creature  that moves on the ground.\"",
    Ind:"Allah memberkati mereka, lalu Allah berfirman kepada mereka: \"Beranakcuculah dan bertambah banyak; penuhilah bumi dan taklukkanlah itu, berkuasalah atas ikan-ikan di laut dan burung-burung di udara dan atas segala binatang yang merayap di bumi.\""
  },
  {Bible:"Genesis", Chapter:1, Verse:29, Page:1,
    Kor:"하나님이 말씀하시기를 \"내가 온 땅 위에 있는 씨 맺는 모든 채소와 씨 있는 열매를 맺는 모든 나무를 너희에게 준다. 이것들이 너희의 먹거리가 될 것이다.",
    Chn:"神说：「看哪，我将遍地上一切结种子的菜蔬和一切树上所结有核的果子全赐给你们作食物。",
    Eng:"Then God said, \"I give you every seed-bearing plant on the face of the whole earth and every  tree that has fruit with seed in it. They will be yours for food.",
    Ind:"Berfirmanlah Allah: \"Lihatlah, Aku memberikan kepadamu segala tumbuh-tumbuhan yang berbiji di seluruh bumi dan segala pohon-pohonan yang buahnya berbiji; itulah akan menjadi makananmu."
  },
  {Bible:"Genesis", Chapter:1, Verse:30, Page:1,
    Kor:"또 땅의 모든 짐승과 공중의 모든 새와 땅 위에 사는 모든 것, 곧 생명을 지닌 모든 것에게도 모든 푸른 풀을 먹거리로 준다\" 하시니, 그대로 되었다.",
    Chn:"至于地上的走兽和空中的飞鸟，并各样爬在地上有生命的物，我将青草赐给它们作食物。」事就这样成了。",
    Eng:"And to all the beasts of the earth and all the birds of the air and all the creatures that  move on the ground--everything that has the breath of life in it--I give every green plant for  food.\" And it was so.",
    Ind:"Tetapi kepada segala binatang di bumi dan segala burung di udara dan segala yang merayap di bumi, yang bernyawa, Kuberikan segala tumbuh-tumbuhan hijau menjadi makanannya.\" Dan jadilah demikian."
  },
  {Bible:"Genesis", Chapter:1, Verse:31, Page:1,
    Kor:"하나님이 손수 만드신 모든 것을 보시니, 보시기에 참 좋았다. 저녁이 되고 아침이 되니, 엿샛날이 지났다.",
    Chn:"神看着一切所造的都甚好。有晚上，有早晨，是第六日。",
    Eng:"God saw all that he had made, and it was very good. And there was evening, and there was  morning--the sixth day.",
    Ind:"Maka Allah melihat segala yang dijadikan-Nya itu, sungguh amat baik. Jadilah petang dan jadilah pagi, itulah hari keenam."
  },
]);
