// 예레미야 15장 · Jeremiah 15
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",15,21);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:15, Verse:1, Page:1, Kor:"<유다 백성의 심판> 그 때에 주님께서는 나에게 말씀하셨다. \"비록 모세와 사무엘이 내 앞에 나와 빈다고 해도, 내가 이 백성에게 마음을 기울이지 않을 것이다. 이 백성을 내 앞에서 쫓아내라!", Chn:"", Eng:"Then the LORD said to me: \"Even if Moses and Samuel were to stand before me, my heart would not go out to this people. Send them away from my presence! Let them go!", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:2, Page:1, Kor:"그들이 너에게 '어디로 가야 하느냐' 하고 묻거든, 너는 그들에게 이렇게 대답하여라. 나 주가 말한다.  '어디를 가든지, 염병에 걸려 죽을 자는 염병에 걸려 죽고, 칼에 맞아 죽을 자는 칼에 맞아 죽고, 굶어 죽을 자는 굶어 죽고, 포로로 끌려갈 자는 포로로 끌려갈 것이다.'", Chn:"", Eng:"And if they ask you, 'Where shall we go?' tell them, 'This is what the LORD says: \"'Those destined for death, to death; those for the sword, to the sword; those for starvation, to starvation; those for captivity, to captivity.'", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:3, Page:1, Kor:"나는 이렇게 네 가지로 그들을 벌할 것이다. 그들을 칼에 맞아 죽게 하며, 개가 그들을 뜯어먹게 하며, 공중의 새가 그들의 시체를 쪼아먹게 하며, 들짐승이 그들을 먹어 치우게 할 것이다. 나 주의 말이다.", Chn:"", Eng:"\"I will send four kinds of destroyers against them,\" declares the LORD, \"the sword to kill and the dogs to drag away and the birds of the air and the beasts of the earth to devour and destroy.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:4, Page:1, Kor:"내가 이렇게 하여 a그들로 세상 만국을 놀라게 할 것이니, 이는 히스기야의 아들 므낫세가 유다 왕으로서 예루살렘에서 죄를 지었기 때문이다.\" (a 또는 '그들을 세상 만국에 흩을 것이니')", Chn:"", Eng:"I will make them abhorrent to all the kingdoms of the earth because of what Manasseh son of Hezekiah king of Judah did in Jarusalem.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:5, Page:1, Kor:"\"예루살렘아, 누가 너를 불쌍히 여기겠느냐? 누가 너를 생각하여 위로의 눈물을 흘리며, 누가 네 안부라도 물으려고 들러 보겠느냐?", Chn:"", Eng:"\"Who will have pity on you, O Jerusalem? Who will mourn for you? Who will stop to ask how you are?", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:6, Page:1, Kor:"네가 바로 나를 버린 자다. 나 주의 말이다. 너는 늘 나에게 등을 돌리고 떠나갔다. 나는 이제 너를 불쌍히 여기기에도 지쳤다. 너를 멸망시키려고 내가 손을 들었다.\"", Chn:"", Eng:"You have rejected me,\" declares the LORD. \"You keep on backsliding. So I will lay hands on you and destroy you; I can no longer show compassion.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:7, Page:1, Kor:"\"내가 이 땅의 모든 성문 앞에서, 내 백성들을 키질하여 흩어 버리겠다. 모두들 자식을 잃고 망할 것이다. 그들이 그릇된 길에서 돌이키지 않으려 하기 때문이다.", Chn:"", Eng:"I will winnow them with a winnowing fork at the city gates of the land. I will bring bereavement and destruction on my people, for they have not changed their ways.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:8, Page:1, Kor:"내가 이 백성 가운데서 과부를 바닷가의 모래보다도 더 많게 하겠다. 내가 대낮에 침략군을 끌어들여 갑자기 그들을 치게 하고, 젊은이들과 그들의 어머니들을 치게 하고, 모두들 놀라고 두려워하며 떨게 하겠다.", Chn:"", Eng:"I will make their widows more numerous than the sand of the sea. At midday I will bring a destroyer against the mothers of their young men; suddenly I will bring down on them anguish and terror.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:9, Page:1, Kor:"아들을 일곱이나 둔 여인도 아들을 잃고 기절할 것이다. 그 여인에게 대낮은 이미 칠흑 같은 밤이다. 그 여인은 비천한 신세가 될 것이다. 살아 남은 자식들은, 원수들이 보는 앞에서 칼에 맞아 죽게 하겠다. 나 주의 말이다.\"", Chn:"", Eng:"The mother of seven will grow faint and breathe her last. Her sun will set while it is still day; she will be disgraced and humiliated. I will put the survivors to the sword before their enemies,\" declares the LORD.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:10, Page:1, Kor:"<예레미야의 탄식과 주님의 응답> 아! 어머니 원통합니다. 왜 나를 낳으셨습니까? 온 세상이 다 나에게 시비를 걸어오고, 싸움을 걸어옵니다. 나는 아무에게도 빚을 진 일도 없고, 빚을 준 일도 없는데, 모든 사람이 다 나를 저주합니다.", Chn:"", Eng:"Alas, my mother, that you gave me birth, a man with whom the whole land strives and contends! I have neither lent nor borrowed, yet everyone curses me.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:11, Page:1, Kor:"주님께서 말씀하셨다. \"내가 분명히 너를 강하게 해주고, 네가 복을 누리게 하겠다. 네 원수가 재앙을 당하여 궁지에 빠질 때에, 그가 너를 찾아와서 간청하게 하겠다.\"", Chn:"", Eng:"The LORD said, \"Surely I will deliver you for a good purpose; surely I will make your enemies plead with you in times of disaster and times of distress.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:12, Page:1, Kor:"<노예가 될 백성> \"누가 쇠 곧 북녘에서 오는 쇠와 놋쇠를 부술 수 있겠느냐?", Chn:"", Eng:"\"Can a man break iron--iron from the north--or bronze?", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:13, Page:1, Kor:"유다 백성아, 너희가 나라 구석구석에서 지은 모든 죄 값으로, 너희의 재산과 보물을 아무런 값도 못받는 약탈품으로 원수에게 내주겠다.", Chn:"", Eng:"Your wealth and your treasures I will give as plunder, without charge, because of all your sins throughout your country.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:14, Page:1, Kor:"b나는 너희를, 너희가 알지도 못하는 땅으로 끌고가서, 너희 원수들을 섬기게 하겠다. 내 분노가 불처럼 타올라 너희를 사를 것이다.\" (b 몇몇 히브리어 사본과 칠십인역과 시리아어역을 따름.(17:4 참조) 대다수의 히브리어 사본들은 '내가 너희 원수들을 시켜 너희를 너희가 알지 못하는 땅으로 끌고 가게 하겠다')", Chn:"", Eng:"I will enslave you to your enemies in a land you do not know, for my anger will kindle a fire that will burn against you.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:15, Page:1, Kor:"<예레미야의 탄식> 주님, 주님께서는 저를 아시니, 저를 잊지 말고 돌보아 주십시오. 저를 핍박하는 사람들에게 원수를 갚아 주십시오! 주님께서 진노를 오래 참으시다가 그만, 저를 잡혀 죽게 하시는 일은 없게 하여 주십시오. 제가 주님 때문에 이렇게 수모를 당하는 줄을, 주님께서 알아 주십시오.", Chn:"", Eng:"You understand, O LORD; remember me and care for me. Avenge me on my persecutors. You are long-suffering--do not take me away; think of how I suffer reproach for your sake.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:16, Page:1, Kor:"만군의 주 하나님, 저는 주님의 이름으로 불리는 사람입니다. 주님께서 저에게 말씀을 주셨을 때에, 저는 그 말씀을 받아먹었습니다. 주님의 말씀은 저에게 기쁨이 되었고, 제 마음에 즐거움이 되었습니다.", Chn:"", Eng:"When your words came, I ate them; they were my joy and my heart's delight, for I bear your name, O LORD God Almighty.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:17, Page:1, Kor:"저는, 웃으며 떠들어대는 사람들과 함께 어울려 즐거워하지도 않습니다. 주님께서 채우신  분노를 가득 안은 채로, 주님의 손에 붙들려 외롭게 앉아 있습니다.", Chn:"", Eng:"I never sat in the company of revelers, never made merry with them; I sat alone because your hand was on me and you had filled me with indignation.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:18, Page:1, Kor:"어찌하여 저의 고통은 그치지 않습니까? 어찌하여 저의 상처는 낫지 않습니까? 주님께서는, 흐르다가도 마르고 마르다가도 흐르는 여름철의 시냇물처럼, 도무지 믿을 수 없는 분이 되셨습니다.", Chn:"", Eng:"Why is my pain unending and my wound grievous and incurable? Will you be to me like a deceptive brook, like a spring that fails?", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:19, Page:1, Kor:"<주님의 대답> \"나 주가 말한다. 네가 돌아오면, 내가 너를 다시 맞아들여 나를 섬기게 하겠다. 또 네가 천박한 것을 말하지 않고, 귀한 말을 선포하면, 너는 다시 나의 대변자가 될 것이다. 너에게로 돌아와야 할 사람들은 그들이다. 네가 그들에게 돌아가서는 안 된다.", Chn:"", Eng:"Therefore this is what the LORD says: \"If you repent, I will restore you that you may serve me; if you utter worthy, not worthless, words, you will be my spokesman. Let this people turn to you, but you must not turn to them.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:20, Page:1, Kor:"내가 너를 튼튼한 놋쇠 성벽으로 만들어서 이 백성과 맞서게 하겠다. 그들이 너에게 맞서서 덤벼들겠지만, 너를 이기지는 못할 것이다. 내가 반드시 너와 함께 있어서, 너를 도와주고, 너를 구원하여 주겠다. 나 주의 말이다.", Chn:"", Eng:"I will make you a wall to this people, a fortified wall of bronze; they will fight against you but will not overcome you, for I am with you to rescue and save you,\" declares the LORD.", Ind:""},
  {Bible:"Jeremiah", Chapter:15, Verse:21, Page:1, Kor:"내가 너를  악인들의 손에서도 건져내고, 잔악한 사람들의 손에서도 구하여 내겠다.\"", Chn:"", Eng:"\"I will save you from the hands of the wicked and redeem you from the grasp of the cruel.\"", Ind:""},
]);
