// 예레미야 43장 · Jeremiah 43
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",43,13);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:43, Verse:1, Page:1, Kor:"<예레미야가 이집트로 가다> 하나님께서 그의 백성에게 지시하신 모든 말씀, 곧 그들의 하나님이신 주님께서 예레미야를 보내셔서 그들에게 이르게 하신 이 모든 말씀을, 예레미야가 온 백성에게 다 일러주었을 때에,", Chn:"", Eng:"When Jeremiah finished telling the people all the words of the LORD their God--everything the LORD had sent him to tell them--", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:2, Page:1, Kor:"호사야의 아들 아사랴와 가레아의 아들 요하난과 고집이 센 모든 사람이, 예레미야에게 말하였다. \"당신은 거짓말을 하고 있소. 주 우리의 하나님께서 당신에게, 우리가 이집트로 가서 머무르게 해서는 안 된다는 말씀을 전하게 하셨을 리가 없소.", Chn:"", Eng:"Azariah son of Hoshaiah and Johanan son of Kareah and all the arrogant men said to Jeremiah, \"You are lying! The LORD our God has not sent you to say, 'You must not go to Egypt to settle there.'", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:3, Page:1, Kor:"이것은 틀림없이, 네리야의 아들 바룩이 우리를 바빌로니아 사람의 손에 넘겨 주어서 그들이 우리를 죽이거나 바빌로니아로 잡아가도록 하려고, 당신을 꾄 것이오.\"", Chn:"", Eng:"But Baruch son of Neriah is inciting you against us to hand us over to the Babylonians, so they may kill us or carry us into exile to Babylon.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:4, Page:1, Kor:"○가레아의 아들 요하난과 모든 군지휘관과 온 백성은, 유다 땅에 머물러 살라는 주님의 말씀을 듣지 않았다.", Chn:"", Eng:"So Johanan son of Kareah and all the army officers and all the people disobeyed the LORD'S command to stay in the land of Judah.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:5, Page:1, Kor:"마침내 가레아의 아들 요하난과 모든 군지휘관은 여러 나라에 흩어져 살다가 유다 땅에서 살려고 돌아온 유다의 살아 남은 사람들을 모두 데리고,", Chn:"", Eng:"Instead, Johanan son of Kareah and all the army officers led away all the remnant of Judah who had come back to live in the land of Judah from all the nations where they had been scattered.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:6, Page:1, Kor:"남자와 여자와 어린 아이들과 공주들과, 근위대장 느부사라단이 사반의 손자요 아히감의 아들인 그달리야에게 맡겨 놓은 모든 사람과, 예언자 예레미야와 네리야의 아들 바룩까지 데리고서,", Chn:"", Eng:"They also led away all the men, women and children and the king's daughters whom Nebuzaradan commander of the imperial guard had left with Gedaliah son of Ahikam, the son of Shaphan, and Jeremiah the prophet and Baruch son of Neriah.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:7, Page:1, Kor:"이집트 땅으로 들어갔다. 이처럼 그들은 주님께 순종하지 않았다. ○그들이 다바네스에 이르렀을 때에,", Chn:"", Eng:"So they entered Egypt in disobedience to the LORD and went as far as Tahpanhes.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:8, Page:1, Kor:"주님께서 예레미야에게 말씀하셨다.", Chn:"", Eng:"In Tahpanhes the word of the LORD came to Jeremiah:", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:9, Page:1, Kor:"\"너는 너의 손으로 큰 돌들을 날라다가, 다바네스에 있는 바로의 궁 대문 앞 포장된 광장을 파고, 유다 사람들이 보는 앞에서 그 돌들을 묻어라.", Chn:"", Eng:"\"While the Jews are watching, take some large stones with you and bury them in clay in the brick pavement at the entrance to Pharaoh's palace in Tahpanhes.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:10, Page:1, Kor:"그런 다음에 너는 유다 사람들에게 이렇게 전하여라. '나 만군의 주, 이스라엘의 하나님이 말한다. 내가 사람을 보내어, 나의 종 바빌로니아 왕 느부갓네살을 데려오겠다. 그러면 그는 내가 묻어 놓은 이 돌들 위에 자기의 보좌를 차려 놓고, 그 위에 차일을 칠 것이다.", Chn:"", Eng:"Then say to them, 'This is what the LORD Almighty, the God of Israel, says: I will send for my servant Nebuchadnezzar king of Babylon, and I will set his throne over these stones I have buried here; he will spread his royal canopy above them.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:11, Page:1, Kor:"그가 와서 이집트 땅을 치면, 염병에 걸려 죽을 자는 염병에 걸려 죽고, 포로로 끌려갈 자는 포로로 끌려가고, 칼에 맞아 죽을 자는 칼에 맞아 죽을 것이다.", Chn:"", Eng:"He will come and attack Egypt, bringing death to those destined for death, captivity to those destined for captivity, and the sword to those destined for the sword.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:12, Page:1, Kor:"○그리고 a그는 이집트의 신전들에 불을 놓아서 신상들을 태우거나 전리품으로 가져 갈 것이다. 그는 마치, 목동이 자기 옷에서 벌레를 잡아내듯이 이집트 땅을 말끔히 털고, 아무런 저항도 받지 않고, 그 곳에서 평안히 떠나갈 것이다.(a 칠십인역과 시리아어역과 불가타를 따름. 히, '나는')", Chn:"", Eng:"He will set fire to the temples of the gods of Egypt; he will burn their temples and take their gods captive. As a shepherd wraps his garment around him, so will he wrap Egypt around himself and depart from there unscathed.", Ind:""},
  {Bible:"Jeremiah", Chapter:43, Verse:13, Page:1, Kor:"그는 이집트 땅에 있는 b태양 신전의 돌기둥들을 부수고, 이집트의 신전들을 불살라 버릴 것이다.'\"(b 또는 '헬리오폴리스에 있는 돌기둥들을')", Chn:"", Eng:"There in the temple of the sun in Egypt he will demolish the sacred pillars and will burn down the temples of the gods of Egypt.'\"", Ind:""},
]);
