// 예레미야 12장 · Jeremiah 12
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",12,17);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:12, Verse:1, Page:1, Kor:"<예레미야의 질문> 주님, 제가 주님과 변론할 때마다, 언제나 주님이 옳으셨습니다. 그러므로 주님께 공정성 문제 한 가지를 여쭙겠습니다. 어찌하여 악인들이 형통하며, 배신자들이 모두 잘 되기만 합니까?", Chn:"", Eng:"You are always righteous, O LORD, when I bring a case before you. Yet I would speak with you about your justice: Why does the way of the wicked prosper? Why do all the faithless live at ease?", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:2, Page:1, Kor:"주님께서 그들을, 나무를 심듯이 심으셨으므로, 뿌리를 내리고 자라며, 열매도 맺으나, 말로만 주님과 가까울 뿐, 속으로는 주님과 멀리 떨어져 있습니다.", Chn:"", Eng:"You have planted them, and they have taken root; they grow and bear fruit. You are always on their lips but far from their hearts.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:3, Page:1, Kor:"그러나 주님, 주님께서는 저를 아십니다. 주님은 저의 속을 들여다보시고, 저의 마음이 주님과 함께 있음을 감찰하여 알고 계십니다. 그러므로 그들을 도살할 양처럼 끌어내시고, 죽일 날을 정하셔서 따로 갈라내 두십시오.", Chn:"", Eng:"Yet you know me, O LORD; you see me and test my thoughts about you. Drag them off like sheep to be butchered! Set them apart for the day of slaughter!", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:4, Page:1, Kor:"이 땅이 언제까지 a슬퍼하며, 들녘의 모든 풀이 말라 죽어야 합니까? 이 땅에 사는 사람의 죄악 때문에, 짐승과 새도 씨가 마르게 되었습니다. 사람들은 자기들이 무슨 일을 하든지, 하나님께서 내려다보시지 않는다고 말하고 있습니다. (a 또는 '마르며')", Chn:"", Eng:"How long will the land lie parched and the grass in every field be withered? Because those who live in it are wicked, the animals and birds have perished. Moreover, the people are saying, \"He will not see what happens to us.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:5, Page:1, Kor:"<주님의 대답> \"네가 사람과 달리기를 해도 피곤하면, 어떻게 말과 달리기를 하겠느냐? b네가 조용한 땅에서만 안전하게 살 수 있다면, 요단 강의 창일한 물 속에서는 어찌하겠느냐? (b 또는 '네가 안전한 땅에서도 비틀거린다면')", Chn:"", Eng:"\"If you have raced with men on foot and they have worn you out, how can you compete with horses? If you stumble in safe country, how will you manage in the thickets by the Jordan?", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:6, Page:1, Kor:"그렇다. 바로 네 친척, 네 집안 식구가 너를 배신하고, 바로 그들이 네 뒤에서 소리를 질러 너를 욕한다. 그러므로 그들이 너에게 다정하게 말을 걸어와도, 너는 그들을 믿지 말아라.\"", Chn:"", Eng:"Your brothers, your own family--even they have betrayed you; they have raised a loud cry against you. Do not trust them, though they speak well of you.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:7, Page:1, Kor:"<주님의 슬픔> \"나는 내 집을 버렸다. 내 소유로 택한 내 백성을 포기하였다. 내가 진정으로 사랑한 백성을 바로 그들의 원수에게 넘겨 주었다.", Chn:"", Eng:"\"I will forsake my house, abandon my inheritance; I will give the one I love into the hands of her enemies.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:8, Page:1, Kor:"내 소유로 택한 내 백성이 내게 반항하였다. 숲 속의 사자처럼, 내게 으르렁거리며 덤벼들었다.", Chn:"", Eng:"My inheritance has become to me like a lion in the forest. She roars at me; therefore I hate her.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:9, Page:1, Kor:"내 소유로 택한 내 백성은 사나운 매들에게 둘러싸인 새와 같다. 모든 들짐승아, 어서 모여라. 몰려와서, 이 새를 뜯어먹어라.\"", Chn:"", Eng:"Has not my inheritance become to me like a speckled bird of prey that other birds of prey surround and attack? Go and gather all the wild beasts; bring them to devour.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:10, Page:1, Kor:"\"이방 통치자들이 내 포도원을 망쳐 놓았고, 내 농장을 짓밟아 버렸다. 그들은 내가 아끼는 밭을 사막으로 만들어 버렸다.", Chn:"", Eng:"Many shepherds will ruin my vineyard and trample down my field; they will turn my pleasant field into a desolate wasteland.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:11, Page:1, Kor:"그들이 내 땅을 황무지로 바꾸어 놓았다. 황무지가 된 이 땅이 나를 보고 통곡한다. 온 땅이 이렇게 황무지가 되었는데도, 걱정하는 사람이 하나도 없구나.", Chn:"", Eng:"It will be made a wasteland, parched and desolate before me; the whole land will be laid waste because there is no one who cares.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:12, Page:1, Kor:"강도 떼가 사막의 모든 언덕을 넘어서 몰려왔다. 내가, 땅 이 끝에서 저 끝까지 칼로 휩쓸어, 어느 누구도 평온하게 살 수 없게 하였다.", Chn:"", Eng:"Over all the barren heights in the desert destroyers will swarm, for the sword of the LORD will devour from one end of the land to the other; no one will be safe.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:13, Page:1, Kor:"사람들이 밀을 심어도 가시만을 거두었고, 그들이 수고해도 아무런 소득이 없었다. 그들은 나의 맹렬한 분노 때문에, 아무런 소출도 없이 수치만 당하였다.\"", Chn:"", Eng:"They will sow wheat but reap thorns; they will wear themselves out but gain nothing. So bear the shame of your harvest because of the LORD'S fierce anger.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:14, Page:1, Kor:"<주님께서 유다의 이웃 백성에게 하신 약속> ○\"나 주가 말한다. 내가 내 백성 이스라엘에게 유산으로 준 땅을 침범한, 모든 악한 이웃 백성을 두고 말한다. 내가 그 악한 백성들을 그들의 고향 땅에서 쫓아내고, 유다 백성을 그들 가운데서 구하여 내겠다.", Chn:"", Eng:"This is what the LORD says: \"As for all my wicked neighbors who seize the inheritance I gave my people Israel, I will uproot them from their lands and I will uproot the house of Judah from among them.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:15, Page:1, Kor:"그러나 내가 그들을 쫓아낸 다음에는, 다시 그들을 불쌍히 여겨서, 제 땅, 제 고향으로 되돌려 보내겠다.", Chn:"", Eng:"But after I uproot them, I will again have compassion and will bring each of them back to his own inheritance and his own country.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:16, Page:1, Kor:"비록 그들이 내 백성에게, 바알의 이름을 부르며 맹세하도록 가르쳤지만, 그들이 내 백성의 도를 확실하게 배우고, 내 이름을 부르며 '주님의 살아 계심을 두고' 맹세하면, 그들도 내 백성 가운데 들게 될 것이다.", Chn:"", Eng:"And if they learn well the ways of my people and swear by my name, saying, 'As surely as the LORD lives'--even as they once taught my people to swear by Baal--then they will be established among my people.", Ind:""},
  {Bible:"Jeremiah", Chapter:12, Verse:17, Page:1, Kor:"그러나 그들이 복종하지 않으면, 내가 그 민족을 완전히 뿌리째 뽑아 멸망시키겠다. 나 주의 말이다.\"", Chn:"", Eng:"But if any nation does not listen, I will completely uproot and destroy it,\" declares the LORD.", Ind:""},
]);
