// 예레미야 49장 · Jeremiah 49
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",49,39);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:49, Verse:1, Page:1,
    Kor:"<암몬 심판의 예언> 이것은 암몬 백성을 두고 하신 주님의 말씀이다.  \"나 주가 말한다. 이스라엘은 자식도 두지 못하고, 상속자도 두지 못하였느냐? 어찌하여 a몰렉 신이 갓을 차지하고, 몰렉의 백성이 갓의 성읍들에서 자리잡고 사느냐? (a 또는 '그들의 왕이'. 히, '말감')",
    Chn:"论亚扪人。耶和华如此说： 以色列没有儿子吗？ 没有后嗣吗？ 玛勒堪为何得迦得之地为业呢？ 属他的民为何住其中的城邑呢？",
    Eng:"Concerning the Ammonites: This is what the LORD says: \"Has Israel no sons? Has she no heirs? Why then has Molech taken possession of Gad? Why do his people live in its towns?",
    Ind:"Mengenai bani Amon. Beginilah firman TUHAN: \"Tidak adakah anak Israel, tidak adakah ahli warisnya? Mengapakah dewa Milkom memiliki Gad, dan bangsanya mendiami kota-kotanya?"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:2, Page:1,
    Kor:"보아라, 그 날이 온다. 나 주의 말이다. 그 때에는 내가 암몬 백성이 사는 랍바에 전쟁의 함성이 들리게 하겠다. 그러면 랍바가 폐허 더미로 변하고, 그에 딸린 성읍들은 불에 타버리고, 이스라엘은 빼앗겼던 자기 땅을 다시 돌려 받게 될 것이다. 나 주의 말이다.\"",
    Chn:"耶和华说： 日子将到，我必使人听见打仗的喊声， 是攻击亚扪人拉巴的喊声。 拉巴要成为乱堆； 属她的乡村要被火焚烧。 先前得以色列地为业的， 此时以色列倒要得他们的地为业。 这是耶和华说的。",
    Eng:"But the days are coming,\" declares the LORD, \"when I will sound the battle cry against Rabbah of the Ammonites; it will become a mound of ruins, and its surrounding villages will be set on fire. Then Israel will drive out those who drove her out,\" says the LORD.",
    Ind:"Sebab itu, sesungguhnya, waktunya akan datang, demikianlah firman TUHAN, bahwa Aku akan memperdengarkan tempik sorak peperangan terhadap Raba bani Amon. Kota itu akan menjadi anak bukit yang tandus, dan kota-kota jajahannya akan dibakar dengan api; maka Israel akan memiliki orang-orang yang dahulu memilikinya, firman TUHAN."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:3, Page:1,
    Kor:"\"아이 성이 멸망하였으니, 헤스본아, 통곡하여라. 랍바의 딸들아, 울부짖어라. 굵은 베 옷을 몸에 걸치고 애곡하여라. 이리 뛰고 저리 뛰며 몸부림 쳐라. 너희의 신 a몰렉이 포로로 끌려가고, 몰렉을 섬기던 제사장들과 고관들도 다 함께 포로로 끌려갈 것이다.\" (a 또는 '그들의 왕이'. 히, '말감')",
    Chn:"希实本哪，你要哀号， 因为爱地变为荒场。 拉巴的居民哪，要呼喊， 以麻布束腰； 要哭号，在篱笆中跑来跑去； 因玛勒堪和属他的祭司、 首领要一同被掳去。",
    Eng:"\"Wail, O Heshbon, for Ai is destroyed! Cry out, O inhabitants of Rabbah! Put on sackcloth and mourn; rush here and there inside the walls, for Molech will go into exile, together with his priests and officials.",
    Ind:"Merataplah, hai Hesybon, sebab pembinasa telah maju menyerbu, berteriaklah, hai puteri-puteri Raba, kenakanlah kain kabung, berkabunglah, berjalan kelilinglah dengan luka toreh-torehan, sebab Milkom akan pergi ke dalam pembuangan bersama-sama dengan para imam dan pemuka-pemukanya."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:4, Page:1,
    Kor:"\"너 방종한 딸 암몬아, 네가 어찌하여 너의 비옥한 골짜기들을 자랑하느냐? 너의 골짜기들은 이미 고갈되었다. 네가 어찌하여 재물을 의지하며 '누가 나를 치러 올 수가 있느냐?' 하고 뽐내었느냐?",
    Chn:"背道的民哪， 你们为何因有山谷， 就是水流的山谷夸张呢？ 为何倚靠财宝说： 谁能来到我们这里呢？",
    Eng:"Why do you boast of your valleys, boast of your valleys so fruitful? O unfaithful daughter, you trust in your riches and say, 'Who will attack me?'",
    Ind:"Betapa engkau memegahkan dirimu dengan lembahmu, hai puteri yang congkak, yang percaya akan harta bendanya dan yang berkata: Siapakah yang berani datang menyerang aku?"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:5, Page:1,
    Kor:"보아라, 내가 너의 사방에서 무서운 적들을 데려다가, 너를 치겠다! 나 만군의 주 하나님의 말이다. 그러면 너의 백성이 제각기 흩어져 도망할 것이고, 아무도 도주하는 사람들을 모을 수 없을 것이다.",
    Chn:"主—万军之耶和华说： 我要使恐吓从四围的人中临到你们； 你们必被赶出， 各人一直前往， 没有人收聚逃民。",
    Eng:"I will bring terror on you from all those around you,\" declares the Lord, the LORD Almighty. \"Every one of you will be driven away, and no one will gather the fugitives.",
    Ind:"Sesungguhnya, Aku mendatangkan kekejutan atasmu demikianlah firman Tuhan ALLAH semesta alam, dari segala tempat di sekitarmu, sehingga kamu bersorak-sorak, masing-masing ke arahnya sendiri, dan tidak ada yang mengumpulkan orang-orang yang mengembara itu."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:6, Page:1,
    Kor:"그러나 그렇게 한 뒤에는, 내가 사로잡혀 간 암몬의 포로를 돌아오게 하겠다. 나 주의 말이다.\"",
    Chn:"后来我还要使被掳的亚扪人归回。 这是耶和华说的。",
    Eng:"\"Yet afterward, I will restore the fortunes of the Ammonites,\" declares the LORD.",
    Ind:"Tetapi sesudah itu Aku akan memulihkan keadaan bani Amon itu, demikianlah firman TUHAN.\""
  },
  {Bible:"Jeremiah", Chapter:49, Verse:7, Page:1,
    Kor:"<에돔 심판의 예언> ○ 이것은 에돔을 두고 하신 주님의 말씀이다. \"나 만군의 주가 말한다. 이제 데만에 더 이상 지혜가 없느냐? 명철한 사람들에게서 좋은 생각이 다 사라져 버렸느냐? 그들의 슬기가 끝이 났느냐?",
    Chn:"论以东。万军之耶和华如此说： 提幔中再没有智慧吗？ 明哲人不再有谋略吗？ 他们的智慧尽归无有吗？",
    Eng:"Concerning Edom: This is what the LORD Almighty says: \"Is there no longer wisdom in Teman? Has counsel perished from the prudent? Has their wisdom decayed?",
    Ind:"Mengenai Edom. Beginilah firman TUHAN semesta alam: \"Tidak adakah lagi kebijaksanaan di Teman? Sudah hilangkah pertimbangan dari orang-orang yang berakal budi, sudah busukkah kebijaksanaan mereka?"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:8, Page:1,
    Kor:"드단의 주민아, 너희는 어서 도피하여라. 너희는 거기에서 떠나서, 깊은 은신처로 들어가서 숨어라. 내가 에서에게 재앙을 내려 그를 벌할 때가 되었다.",
    Chn:"底但的居民哪，要转身逃跑， 住在深密处； 因为我向以扫追讨的时候， 必使灾殃临到他。",
    Eng:"Turn and flee, hide in deep caves, you who live in Dedan, for I will bring disaster on Esau at the time I punish him.",
    Ind:"Larilah cepat, bersembunyilah dalam liang-liang, hai penduduk Dedan! Sebab malapetaka akan Kudatangkan atas Esau, pada waktu Aku menghukum dia."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:9, Page:1,
    Kor:"포도 서리를 하는 사람들이 들이닥쳐도 남기는 것이 더러 있으며, 밤에 도둑이 들어도 마음에 드는 것만 가져 간다.",
    Chn:"摘葡萄的若来到他那里， 岂不剩下些葡萄呢？ 盗贼若夜间而来， 岂不毁坏直到够了呢？",
    Eng:"If grape pickers came to you, would they not leave a few grapes? If thieves came during the night, would they not steal only as much as they wanted?",
    Ind:"Jika pemetik buah anggur datang kepadamu, mereka tidak akan meninggalkan sisa-sisa pemetikannya! Jika malam-malam pencuri datang kepadamu, mereka akan merusakkan sepuas-puasnya!"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:10, Page:1,
    Kor:"그러나, 나는 에서를 샅샅이 뒤지고, 그가 숨을 수 있는 곳들을 다 들추어내었으니, 그는 숨을 곳이 없다. 그의 자손이 다 망하고, 그의 친족이 모두 망하고, 그의 이웃이 모두 망하고, 에돔마저도 살아 남지 못할 것이다.",
    Chn:"我却使以扫赤露， 显出他的隐密处； 他不能自藏。 他的后裔、弟兄、邻舍尽都灭绝； 他也归于无有。",
    Eng:"But I will strip Esau bare; I will uncover his hiding places, so that he cannot conceal himself. His children, relatives and neighbors will perish, and he will be no more.",
    Ind:"Tetapi Aku ini telah menelanjangi Esau, telah menyingkapkan tempat-tempat persembunyiannya, sehingga ia tidak dapat menyembunyikan diri lagi. Keturunannya telah binasa dan saudara-saudaranya dan bangsa-bangsa tetangganya tidak ada lagi."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:11, Page:1,
    Kor:"네 고아들은 내게 남겨 두어라. 내가 그들을 돌보아 주겠다. 네 과부들도 나를 의지하고 살 수가 있을 것이다.",
    Chn:"你撇下孤儿，我必保全他们的命； 你的寡妇可以倚靠我。",
    Eng:"Leave your orphans; I will protect their lives. Your widows too can trust in me.\"",
    Ind:"Tinggalkanlah anak-anak yatimmu, aku akan menghidupi mereka; biarlah janda-jandamu menaruh kepercayaan padaku!\""
  },
  {Bible:"Jeremiah", Chapter:49, Verse:12, Page:1,
    Kor:"○진실로 나 주가 말한다. 보아라, 이 잔을 마시도록 판결을 받지 않은 백성도 꼼짝없이 이 잔을 마셨는데, 하물며 너 에돔이 벌을 받지 않고 벗어나려고 하느냐? 너는 절대로 벌을 면할 수가 없다. 너는 그 잔을 마셔야만 한다.",
    Chn:"耶和华如此说：「原不该喝那杯的一定要喝。你能尽免刑罚吗？你必不能免，一定要喝！」",
    Eng:"This is what the LORD says: \"If those who do not deserve to drink the cup must drink it, why should you go unpunished? You will not go unpunished, but must drink it.",
    Ind:"Sebab beginilah firman TUHAN: \"Sedangkan orang-orang yang tidak selayaknya meminum isi piala itu telah terpaksa meminumnya, masakan engkau ini akan bebas dari hukuman? Engkau tidak akan bebas dari hukuman, tetapi mesti meminumnya!"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:13, Page:1,
    Kor:"참으로 내가 나를 두고 맹세한다. 나 주의 말이다. 보스라는 폐허가 되어, 놀라움과 조소와 저주의 대상이 되며, 거기에 딸린 모든 성읍도 영원히 폐허로 남을 것이다.\"",
    Chn:"耶和华说：「我指着自己起誓，波斯拉必令人惊骇、羞辱、咒诅，并且荒凉。她的一切城邑必变为永远的荒场。」",
    Eng:"I swear by myself,\" declares the LORD, \"that Bozrah will become a ruin and an object of horror, of reproach and of cursing; and all its towns will be in ruins forever.\"",
    Ind:"Sebab Aku telah bersumpah demi diri-Ku, demikianlah firman TUHAN, bahwa Bozra akan menjadi ketandusan, cela, keruntuhan dan kutuk, dan segala kotanya akan menjadi reruntuhan yang kekal.\""
  },
  {Bible:"Jeremiah", Chapter:49, Verse:14, Page:1,
    Kor:"주님께서 세계 만민에게 특사를 파견하시면서 하시는 말씀을 내가 들었다. '너희는 모여서 에돔으로 몰려가서 그를 쳐라. 너희는 일어나서 싸워라' 하셨다.",
    Chn:"我从耶和华那里听见信息， 并有使者被差往列国去，说： 你们聚集来攻击以东， 要起来争战。",
    Eng:"I have heard a message from the LORD: An envoy was sent to the nations to say, \"Assemble yourselves to attack it! Rise up for battle!\"",
    Ind:"Suatu kabar telah kudengar dari TUHAN, seorang utusan telah disuruh ke tengah-tengah bangsa-bangsa: \"Berkumpullah, pergilah menyerangnya, bersiaplah untuk bertempur!"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:15, Page:1,
    Kor:"\"에돔아, 보아라, 이제 내가 너를 세계 만민 가운데서 가장 하찮은 자로 만들어서, 사람들에게서 멸시를 받게 하겠다.",
    Chn:"我使你在列国中为最小， 在世人中被藐视。",
    Eng:"\"Now I will make you small among the nations, despised among men.",
    Ind:"Sebab sesungguhnya, Aku membuat engkau kecil di antara bangsa-bangsa, dihinakan di antara manusia."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:16, Page:1,
    Kor:"네가 바위 틈 속에 자리잡고 살며, 산꼭대기를 차지하고 산다고, 누구나 너를 무서워한다고 생각하지 말아라. 그러한 너의 교만은 너 스스로를 속일 뿐이다. 네가 아무리 독수리처럼 높은 곳에 네 보금자리를 만들어 놓아도, 내가 너를 거기에서 끌어내리겠다. 나 주의 말이다.\"",
    Chn:"住在山穴中据守山顶的啊， 论到你的威吓， 你因心中的狂傲自欺； 你虽如大鹰高高搭窝， 我却从那里拉下你来。 这是耶和华说的。",
    Eng:"The terror you inspire and the pride of your heart have deceived you, you who live in the clefts of the rocks, who occupy the heights of the hill. Though you build your nest as high as the eagle's, from there I will bring you down,\" declares the LORD.",
    Ind:"Sikapmu yang menggemetarkan orang memperdayakan engkau, dan keangkuhan hatimu, ya engkau yang tinggal di liang-liang batu, yang menduduki tempat tinggi bukit! Sekalipun engkau membuat sarangmu tinggi seperti burung rajawali, Aku akan menurunkan engkau dari sana, demikianlah firman TUHAN."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:17, Page:1,
    Kor:"\"에돔이 참혹하게 파괴되어, 그 곳을 지나는 사람마다 그 곳에 내린 모든 재앙을 보고 놀라며, 비웃을 것이다.",
    Chn:"「以东必令人惊骇；凡经过的人就受惊骇，又因她一切的灾祸嗤笑。",
    Eng:"\"Edom will become an object of horror; all who pass by will be appalled and will scoff because of all its wounds.",
    Ind:"Edom akan menjadi ketandusan; setiap orang yang melewatinya akan merasa ngeri dan bersuit karena segala pukulan yang dideritanya."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:18, Page:1,
    Kor:"소돔과 고모라와 그 이웃 성읍들이 멸망하였을 때와 마찬가지로, 더 이상 그 땅에 자리잡고 사는 사람이 없을 것이며, 그 땅에 머무르는 사람도 없을 것이다. 나 주가 말한다.",
    Chn:"耶和华说：必无人住在那里，也无人在其中寄居，要像所多玛、蛾摩拉，和邻近的城邑倾覆的时候一样。",
    Eng:"As Sodom and Gomorrah were overthrown, along with their neighboring towns,\" says the LORD, \"so no one will live there; no man will dwell in it.",
    Ind:"Seperti pada waktu ditunggangbalikkannya Sodom dan Gomora dan kota-kota tetangganya--firman TUHAN--maka seorangpun tidak akan diam lagi di sana dan seorang manusiapun tidak akan tinggal lagi di dalamnya."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:19, Page:1,
    Kor:"보아라, 사자가 요단 강 가의 깊은 숲 속에서 뛰어나와서, 푸른 목장으로 달려들듯이, 나도 갑자기 에돔으로 달려들어서, 그 주민을 몰아내고, 내가 택한 지도자를 그 곳에 세우겠다. 누가 나와 같다는 말이냐? 감히 나에게 따지며 대들 수 있는 자가 누구이며, 나에게 맞설 수 있는 목자가 누구냐?",
    Chn:"仇敌必像狮子从约旦河边的丛林上来，攻击坚固的居所。转眼之间，我要使以东人逃跑，离开这地。谁蒙拣选，我就派谁治理这地。谁能比我呢？谁能给我定规日期呢？有何牧人能在我面前站立得住呢？",
    Eng:"\"Like a lion coming up from Jordan's thickets to a rich pastureland, I will chase Edom from its land in an instant. Who is the chosen one I will appoint for this? Who is like me and who can challenge me? And what shepherd can stand against me?\"",
    Ind:"Sesungguhnya, seperti singa yang bangkit keluar dari hutan belukar sungai Yordan mendatangi padang rumput tempat kawanan domba, demikianlah Aku akan membuat mereka lari dengan tiba-tiba dari negeri itu dan mengangkat di dalamnya dia yang Kupilih. Sebab siapakah yang seperti Aku? Siapakah yang berani mendakwa Aku? Siapakah gerangan gembala yang tahan menghadapi Aku?"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:20, Page:1,
    Kor:"그러므로 너희는 나, 주가 에돔을 두고 세운 계획을 듣고, 데만 주민에 대한 나의 생각을 들어 보아라.\" \"양 떼 가운데서 아주 어린 것들까지 끌려갈 것이니, 온 목장이 황무지가 될 것이다.",
    Chn:"你们要听耶和华攻击以东所说的谋略和他攻击提幔居民所定的旨意。仇敌定要将他们群众微弱的拉去，定要使他们的居所荒凉。",
    Eng:"Therefore, hear what the LORD has planned against Edom, what he has purposed against those who live in Teman: The young of the flock will be dragged away; he will completely destroy their pasture because of them.",
    Ind:"Sebab itu dengarlah putusan yang telah diambil TUHAN terhadap Edom dan rancangan-rancangan yang telah dibuat-Nya terhadap penduduk Teman: Bahwa sesungguhnya, yang paling lemahpun di antara kawanan domba akan diseret. Bahwa sesungguhnya, padang rumput mereka sendiri akan merasa ngeri terhadap mereka."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:21, Page:1,
    Kor:"에돔이 쓰러지는 소리가 땅을 흔들고, 그들의 울부짖는 소리가 b홍해에까지 들릴 것이다. (b 히, '얌 쑤프')",
    Chn:"因他们仆倒的声音，地就震动。人在红海那里必听见呼喊的声音。",
    Eng:"At the sound of their fall the earth will tremble; their cry will resound to the Red Sea.",
    Ind:"Bumi akan goncang karena bunyi jatuhnya mereka; teriakan mereka akan terdengar bunyinya di Laut Teberau."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:22, Page:1,
    Kor:"보아라, 적이 독수리처럼 날아와서, 보스라 위에 두 날개를 펼칠 것이니, 그 날에는 에돔 용사들의 마음이 해산하는 여인의 마음과 같이 공포에 사로잡힐 것이다.\"",
    Chn:"仇敌必如大鹰飞起，展开翅膀攻击波斯拉。到那日，以东的勇士心中疼痛如临产的妇人。」",
    Eng:"Look! An eagle will soar and swoop down, spreading its wings over Bozrah. In that day the hearts of Edom's warriors will be like the heart of a woman in labor.",
    Ind:"Sesungguhnya, ia naik terbang seperti burung rajawali, melayang dan mengembangkan sayapnya ke atas Bozra. Hati para pahlawan Edom pada waktu itu akan seperti hati perempuan yang sakit beranak.\""
  },
  {Bible:"Jeremiah", Chapter:49, Verse:23, Page:1,
    Kor:"<다마스쿠스 심판의 예언> 이것은 다마스쿠스를 두고 하신 주님의 말씀이다. \"하맛과 아르밧이 불길한 소식을 듣고, 어쩔 줄 몰라 한다. 그들이 낙담하였고, 걱정이 파도처럼 몰아치니, 평안을 잃었다.",
    Chn:"论大马士革。 哈马和亚珥拔蒙羞， 因他们听见凶恶的信息就消化了。 海上有忧愁，不得平静。",
    Eng:"Concerning Damascus: \"Hamath and Arpad are dismayed, for they have heard bad news. They are disheartened, troubled like the restless sea.",
    Ind:"Mengenai Damsyik. \"Hamat dan Arpad telah menjadi malu, sebab mereka mendengar kabar buruk; hati mereka gemetar karena kecemasan, tidak dapat menjadi tenang."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:24, Page:1,
    Kor:"다마스쿠스가 용기를 잃고 몸을 돌이켜 달아나려 하지만, 공포가 그를 사로잡고 해산하는 여인의 고통과 슬픔처럼 그를 사로잡았다.",
    Chn:"大马士革发软，转身逃跑。 战兢将她捉住； 痛苦忧愁将她抓住， 如产难的妇人一样。",
    Eng:"Damascus has become feeble, she has turned to flee and panic has gripped her; anguish and pain have seized her, pain like that of a woman in labor.",
    Ind:"Damsyik telah menjadi lemah semangat, berpaling untuk lari, kegemparan telah mencekam dia, kesesakan dan sakit beranak telah menggenggam dia seperti seorang perempuan yang sedang melahirkan."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:25, Page:1,
    Kor:"칭찬을 받던 도성, 나의 기쁨이었던 성읍이, 이처럼 버림을 받게 되었다.",
    Chn:"我所喜乐可称赞的城， 为何被撇弃了呢？",
    Eng:"Why has the city of renown not been abandoned, the town in which I delight?",
    Ind:"Sungguh, kota yang terpuji itu sudah ditinggalkan, kota kegirangan itu!"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:26, Page:1,
    Kor:"그러므로 그 날에는 그 도성의 젊은이들이 광장에서 쓰러져 죽고, 모든 군인이 전멸을 당할 것이다. 나 만군의 주의 말이다.",
    Chn:"她的少年人必仆倒在街上； 当那日，一切兵丁必默默无声。 这是万军之耶和华说的。",
    Eng:"Surely, her young men will fall in the streets; all her soldiers will be silenced in that day,\" declares the LORD Almighty.",
    Ind:"Sebab itu teruna-terunanya akan rebah di tanah-tanah lapangnya dan semua prajuritnya akan menjadi bungkam pada waktu itu, demikianlah firman TUHAN semesta alam."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:27, Page:1,
    Kor:"그 때에 내가 다마스쿠스의 성벽에 불을 질러 벤하닷의 궁궐을 태워 버릴 것이다.\"",
    Chn:"我必在大马士革城中使火着起， 烧灭便·哈达的宫殿。",
    Eng:"\"I will set fire to the walls of Damascus; it will consume the fortresses of Ben-Hadad.\"",
    Ind:"Aku akan menyalakan api di tembok Damsyik, yang menghanguskan puri Benhadad.\""
  },
  {Bible:"Jeremiah", Chapter:49, Verse:28, Page:1,
    Kor:"<게달과 하솔 심판의 예언> ○바빌로니아 왕 느부갓네살이 멸망시킨 게달과 하솔 왕국을 두고, 주님께서 하신 말씀이다.  \"나 주가 말한다. 너희는 일어나 게달로 쳐올라가서, 저 동방의 백성을 멸망시켜라.",
    Chn:"论巴比伦王尼布甲尼撒所攻打的基达和夏琐的诸国。耶和华如此说： 迦勒底人哪，起来上基达去， 毁灭东方人。",
    Eng:"Concerning Kedar and the kingdoms of Hazor, which Nebuchadnezzar king of Babylon attacked: This is what the LORD says: \"Arise, and attack Kedar and destroy the people of the East.",
    Ind:"Mengenai Kedar dan mengenai kerajaan-kerajaan Hazor yang dipukul kalah oleh Nebukadnezar, raja Babel. Beginilah firman TUHAN: \"Bersiaplah, majulah melawan Kedar, binasakanlah orang-orang di sebelah timur!"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:29, Page:1,
    Kor:"그들의 장막과 양 떼를 빼앗고, 그들의 휘장과 세간도 모조리 빼앗아라. 그들에게서 낙타도 빼앗아라. 그리고 그들에게 이르기를 '너희 사방에는 무서운 적들만 있다' 하여라.\"",
    Chn:"他们的帐棚和羊群都要夺去， 将幔子和一切器皿，并骆驼为自己掠去。 人向他们喊着说： 四围都有惊吓。",
    Eng:"Their tents and their flocks will be taken; their shelters will be carried off with all their goods and camels. Men will shout to them, 'Terror on every side!'",
    Ind:"Hendaklah kemah-kemah mereka dan kawanan domba mereka dirampas sampai bersih, tenda-tenda mereka dan segala perabot mereka; hendaklah unta-unta mereka habis dibawa serta, dan hendaklah berteriak-teriak kepada mereka: Kegentaran dari segala jurusan!"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:30, Page:1,
    Kor:"\"하솔 주민아, 너희는 어서 도피하고 도주하여, 깊은 곳에 들어가 숨어 살아라. 나 주의 말이다. 바빌로니아 왕 느부갓네살이 너희를 칠 계획을 세웠고, 너희를 칠 뜻을 굳혔다.\"",
    Chn:"耶和华说： 夏琐的居民哪，要逃奔远方， 住在深密处； 因为巴比伦王尼布甲尼撒设计谋害你们， 起意攻击你们。",
    Eng:"\"Flee quickly away! Stay in deep caves, you who live in Hazor,\" declares the LORD. \"Nebuchadnezzar king of Babylon has plotted against you; he has devised a plan against you.",
    Ind:"Larilah, mengungsilah cepat-cepat, bersembunyilah dalam liang-liang, hai penduduk Hazor! demikianlah firman TUHAN. Sebab Nebukadnezar, raja Babel, telah mengambil putusan terhadap kamu dan telah membuat rancangan terhadap kamu."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:31, Page:1,
    Kor:"\"바빌로니아야, 저렇게 마음을 놓고 태평하게 살아가는 민족에게 어서 쳐올라가거라. 그들은 성문도 없고 빗장도 없이 멀리 떨어져 홀로 살고 있다. 나 주의 말이다.\"",
    Chn:"耶和华说： 迦勒底人哪，起来！ 上安逸无虑的居民那里去； 他们是无门无闩、独自居住的。",
    Eng:"\"Arise and attack a nation at ease, which lives in confidence,\" declares the LORD, \"a nation that has neither gates nor bars; its people live alone.",
    Ind:"Bersiaplah, majulah melawan bangsa yang hidup sentosa, yang diam dengan aman tenteram, demikianlah firman TUHAN, dan yang tidak punya pintu gerbang atau palang, dan yang tinggal tersendiri!"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:32, Page:1,
    Kor:"\"그들의 낙타 떼가 노략을 당하고, 가축 떼가 전리품이 될 것이다. c관자놀이의 머리카락을 짧게 깎고 사는 이 백성을, 내가 사방으로 흩어 버리겠다. 나 주의 말이다.\" (c 또는 '먼 곳에서 사는')",
    Chn:"他们的骆驼必成为掠物； 他们众多的牲畜必成为掳物。 我必将剃周围头发的人分散四方， 使灾殃从四围临到他们。 这是耶和华说的。",
    Eng:"Their camels will become plunder, and their large herds will be booty. I will scatter to the winds those who are in distant places and will bring disaster on them from every side,\" declares the LORD.",
    Ind:"Unta-unta mereka akan menjadi jarahan, dan ternak mereka yang banyak itu menjadi rampasan! Aku akan menyerakkan ke segala mata angin mereka yang berpotong tepi rambutnya berkeliling, dan dari segala penjuru Aku akan mendatangkan bencana atas mereka, demikianlah firman TUHAN."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:33, Page:1,
    Kor:"\"하솔은 영영 황폐한 곳이 되어 이리 떼의 소굴로 변할 것이며, 그 곳에 다시는 정착하는 사람이 없을 것이며, 그 곳에 머무르는 사람도 없을 것이다.\"",
    Chn:"夏琐必成为野狗的住处， 永远凄凉； 必无人住在那里， 也无人在其中寄居。",
    Eng:"\"Hazor will become a haunt of jackals, a desolate place forever. No one will live there; no man will dwell in it.\"",
    Ind:"Hazor akan menjadi tempat persembunyian bagi serigala, menjadi tempat tandus sampai selama-lamanya; seorangpun tidak akan diam lagi di sana dan seorang manusiapun tidak akan tinggal lagi di dalamnya.\""
  },
  {Bible:"Jeremiah", Chapter:49, Verse:34, Page:1,
    Kor:"<엘람 심판의 예언> ○이것은 시드기야가 유다 왕이 되어 다스리기 시작할 무렵에, 엘람을 두고 주님께서 예언자 예레미야에게 하신 말씀이다.",
    Chn:"犹大王西底家登基的时候，耶和华论以拦的话临到先知耶利米说：",
    Eng:"This is the word of the LORD that came to Jeremiah the prophet concerning Elam, early in the reign of Zedekiah king of Judah:",
    Ind:"Firman TUHAN yang datang kepada nabi Yeremia mengenai Elam, pada permulaan pemerintahan Zedekia, raja Yehuda:"
  },
  {Bible:"Jeremiah", Chapter:49, Verse:35, Page:1,
    Kor:"\"나 만군의 주가 말한다. 엘람의 주력 무기인 활을 꺾어 버리겠다.",
    Chn:"「万军之耶和华如此说：我必折断以拦人的弓，就是他们为首的权力。",
    Eng:"This is what the LORD Almighty says: \"See, I will break the bow of Elam, the mainstay of their might.",
    Ind:"Beginilah firman TUHAN semesta alam: \"Sesungguhnya, Aku mematahkan busur Elam, yakni inti kekuatannya."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:36, Page:1,
    Kor:"하늘의 네 끝에서 나온 사방의 바람을 엘람으로 몰아다가, 그들을 사방으로 흩어 버리겠다. 그러면 엘람에서 쫓겨난 사람들이 여러 나라로 유배되어 갈 것이다.",
    Chn:"我要使四风从天的四方刮来，临到以拦人，将他们分散四方。这被赶散的人没有一国不到的。」",
    Eng:"I will bring against Elam the four winds from the four quarters of the heavens; I will scatter them to the four winds, and there will not be a nation where Elam's exiles do not go.",
    Ind:"Aku akan mendatangkan atas Elam keempat angin dari keempat penjuru langit dan akan menyerakkan mereka ke segala mata angin ini, sehingga tidak ada bangsa yang tidak kedatangan orang-orang yang berserakan dari Elam."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:37, Page:1,
    Kor:"나는 엘람 사람들을, 그들의 원수들, 곧 그들의 목숨을 노리는 자들 앞에서 두려워 떨게 하겠다. 내가 이렇게 타오르는 분노로 그들에게 재앙을 내리고, 군대를 보내어서 그들을 뒤쫓게 하겠다. 나 주의 말이다.",
    Chn:"耶和华说：「我必使以拦人在仇敌和寻索其命的人面前惊惶；我也必使灾祸，就是我的烈怒临到他们，又必使刀剑追杀他们，直到将他们灭尽。",
    Eng:"I will shatter Elam before their foes, before those who seek their lives; I will bring disaster upon them, even my fierce anger,\" declares the LORD. \"I will pursue them with the sword until I have made an end of them.",
    Ind:"Aku akan membuat Elam terkejut di depan para musuhnya dan di depan orang-orang yang berusaha mencabut nyawanya. Aku akan mendatangkan atasnya malapetaka, yakni murka-Ku yang menyala-nyala, demikianlah firman TUHAN. Aku akan menyuruh pedang mengejar mereka sampai mereka Kuhabiskan."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:38, Page:1,
    Kor:"나는 엘람 왕과 고관들을 그 땅에서 멸절시키고, 엘람에 나의 보좌를 놓겠다. 나 주의 말이다.",
    Chn:"我要在以拦设立我的宝座，从那里除灭君王和首领。这是耶和华说的。",
    Eng:"I will set my throne in Elam and destroy her king and officials,\" declares the LORD.",
    Ind:"Aku akan menaruh takhta-Ku di Elam, dan Aku akan membinasakan dari sana raja dan pemuka-pemuka, demikianlah firman TUHAN."
  },
  {Bible:"Jeremiah", Chapter:49, Verse:39, Page:1,
    Kor:"그러나 훗날에는 내가 사로잡혀 간 엘람의 포로를 돌아오게 할 것이다. 나 주의 말이다.\"",
    Chn:"「到末后，我还要使被掳的以拦人归回。这是耶和华说的。」",
    Eng:"\"Yet I will restore the fortunes of Elam in days to come,\" declares the LORD.",
    Ind:"Tetapi di kemudian hari Aku akan memulihkan keadaan Elam, demikianlah firman TUHAN.\""
  },
]);
