// 예레미야 52장 · Jeremiah 52
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",52,34);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:52, Verse:1, Page:1,
    Kor:"<예루살렘의 함락(왕하 24:18-25:7)> 시드기야가 왕이 되었을 때에, 그는 스물한 살이었다. 그는 예루살렘에서 열한 해 동안 다스렸다. 그의 어머니 하무달은 리블라 출신으로 예레미야의 딸이다.",
    Chn:"西底家登基的时候年二十一岁，在耶路撒冷作王十一年。他母亲名叫哈慕她，是立拿人耶利米的女儿。",
    Eng:"Zedekiah was twenty-one years old when he became king, and he reigned in Jerusalem eleven years. His mother's name was Hamutal daughter of Jeremiah; she was from Libnah.",
    Ind:"Zedekia berumur dua puluh satu tahun pada waktu ia menjadi raja dan sebelas tahun lamanya ia memerintah di Yerusalem. Nama ibunya ialah Hamutal binti Yeremia, dari Libna."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:2, Page:1,
    Kor:"그는 여호야김이 하였던 것과 똑같이, 주님께서 보시기에 악한 일을 하였다.",
    Chn:"西底家行耶和华眼中看为恶的事，是照约雅敬一切所行的。",
    Eng:"He did evil in the eyes of the LORD, just as Jehoiakim had done.",
    Ind:"Ia melakukan apa yang jahat di mata TUHAN tepat seperti yang telah dilakukan Yoyakim."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:3, Page:1,
    Kor:"예루살렘과 유다가 주님을 그토록 진노하시게 하였기 때문에, 주님께서는 마침내 그들을 주님 앞에서 쫓아내셨다. ○시드기야가 바빌로니아 왕에게 반기를 들었으므로,",
    Chn:"因此耶和华的怒气在耶路撒冷和犹大发作，以致将人民从自己的面前赶出。",
    Eng:"It was because of the LORD'S anger that all this happened to Jerusalem and Judah, and in the end he thrust them from his presence. Now Zedekiah rebelled against the king of Babylon.",
    Ind:"Sebab oleh karena murka Tuhanlah hal itu terjadi terhadap Yerusalem dan Yehuda, yakni bahwa Ia sampai membuang mereka dari hadapan-Nya. Zedekia memberontak terhadap raja Babel."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:4, Page:1,
    Kor:"시드기야 왕 제 구년 열째 달 십일에 바빌로니아 왕 느부갓네살이 그의 모든 군대를 거느리고 예루살렘을 치러 올라와서, 도성을 포위하고, 도성 안을 공격하려고 성벽 바깥 사방에 흙 언덕을 쌓았다.",
    Chn:"西底家背叛巴比伦王。他作王第九年十月初十日，巴比伦王尼布甲尼撒率领全军来攻击耶路撒冷，对城安营，四围筑垒攻城。",
    Eng:"So in the ninth year of Zedekiah's reign, on the tenth day of the tenth month, Nebuchadnezzar king of Babylon marched against Jerusalem with his whole army. They camped outside the city and built siege works all around it.",
    Ind:"Maka pada tahun kesembilan dari pemerintahannya, dalam bulan yang kesepuluh, pada tanggal sepuluh bulan itu, datanglah Nebukadnezar, raja Babel, dengan segala tentaranya menyerang Yerusalem. Berkemahlah mereka mengepungnya dan didirikan merekalah tembok pengepungan sekelilingnya."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:5, Page:1,
    Kor:"그리하여 이 도성은 시드기야 왕 제 십일년까지 포위되어 있었다.",
    Chn:"于是城被围困直到西底家王十一年。",
    Eng:"The city was kept under siege until the eleventh year of King Zedekiah.",
    Ind:"Demikianlah kota itu terkepung sampai tahun yang kesebelas pemerintahan raja Zedekia."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:6, Page:1,
    Kor:"그 해 넷째 달 구일이 되었을 때에, 도성 안에 기근이 심해져서, 그 땅 백성이 먹을 양식이 다 떨어지고 말았다.",
    Chn:"四月初九日，城里有大饥荒，甚至百姓都没有粮食。",
    Eng:"By the ninth day of the fourth month the famine in the city had become so severe that there was no food for the people to eat.",
    Ind:"Pada tanggal sembilan bulan yang keempat, ketika kelaparan sudah merajalela di kota itu dan tidak ada lagi makanan pada rakyat negeri itu,"
  },
  {Bible:"Jeremiah", Chapter:52, Verse:7, Page:1,
    Kor:"○드디어 성벽이 뚫리니, 이것을 본 왕은, a바빌로니아 군대가 도성을 포위하고 있는데도, 밤을 틈타서 모든 군사를 거느리고, 왕의 정원 근처, 두 성벽을 잇는 통로를 지나 도성 바깥으로 빠져 나와 아라바 쪽으로 도망하였다.(a 또는 '갈대아')",
    Chn:"城被攻破，一切兵丁就在夜间从靠近王园两城中间的门，出城逃跑；迦勒底人正在四围攻城。他们就往亚拉巴逃去。",
    Eng:"Then the city wall was broken through, and the whole army fled. They left the city at night through the gate between the two walls near the king's garden, though the Babylonians were surrounding the city. They fled toward the Arabah,",
    Ind:"maka dibelah oranglah tembok kota itu. Melihat hal itu maka melarikan dirilah raja dengan semua tentara, meninggalkan kota itu pada waktu malam melalui pintu gerbang antara kedua tembok yang ada di dekat taman raja, sekalipun orang Kasdim mengepung kota itu sekeliling. Mereka lari menuju ke Araba-Yordan."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:8, Page:1,
    Kor:"그러나 바빌로니아 군대가 시드기야 왕을 추격하여, 여리고 평원에서 그를 사로잡으니, 시드기야의 군사들은 모두 그를 버리고 흩어졌다.",
    Chn:"迦勒底的军队追赶西底家王，在耶利哥的平原追上他。他的全军都离开他四散了。",
    Eng:"but the Babylonian army pursued King Zedekiah and overtook him in the plains of Jericho. All his soldiers were separated from him and scattered,",
    Ind:"Tetapi tentara Kasdim itu mengejar raja dari belakang dan mencapai Zedekia di dataran Yerikho; segala tentaranya telah berserak-serak meninggalkan dia."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:9, Page:1,
    Kor:"바빌로니아 군대가 시드기야 왕을 체포해서, 하맛 땅의 리블라에 있는 바빌로니아 왕에게 끌고 가니, 그가 시드기야를 신문하고,",
    Chn:"迦勒底人就拿住王，带他到在哈马地利比拉的巴比伦王那里；巴比伦王便审判他。",
    Eng:"and he was captured. He was taken to the king of Babylon at Riblah in the land of Hamath, where he pronounced sentence on him.",
    Ind:"Mereka menangkap raja dan membawa dia ke Ribla di tanah Hamat, kepada raja Babel, yang menjatuhkan hukuman atas dia."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:10, Page:1,
    Kor:"또 바빌로니아 왕은 시드기야의 아들들을 그가 보는 앞에서 처형하고, 역시 리블라에서 유다의 고관들도 모두 처형하였다.",
    Chn:"巴比伦王在西底家眼前杀了他的众子，又在利比拉杀了犹大的一切首领，",
    Eng:"There at Riblah the king of Babylon slaughtered the sons of Zedekiah before his eyes; he also killed all the officials of Judah.",
    Ind:"Raja Babel menyuruh menyembelih anak-anak Zedekia di depan matanya; juga semua pemuka Yehuda disembelihnya di Ribla."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:11, Page:1,
    Kor:"그리고 바빌로니아 왕은 시드기야의 두 눈을 뺀 다음에, 쇠사슬로 묶어서, 바빌론으로 끌고 가서, 그가 죽는 날까지 감옥에 가두어 두었다.",
    Chn:"并且剜了西底家的眼睛，用铜链锁着他，带到巴比伦去，将他囚在监里，直到他死的日子。",
    Eng:"Then he put out Zedekiah's eyes, bound him with bronze shackles and took him to Babylon, where he put him in prison till the day of his death.",
    Ind:"Kemudian mata Zedekia dibutakannya, lalu ia dibelenggu dengan rantai tembaga. Kemudian raja Babel membawa dia ke Babel dan menaruhnya dalam rumah hukuman sampai kepada hari matinya."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:12, Page:1,
    Kor:"<성전 붕괴(왕하 25:8-17)> ○바빌로니아 왕 느부갓네살 제 십구년 다섯째 달 십일에, 바빌로니아 왕의 부하인 근위대장 느부사라단이 예루살렘으로 왔다.",
    Chn:"巴比伦王尼布甲尼撒十九年五月初十日，在巴比伦王面前侍立的护卫长尼布撒拉旦进入耶路撒冷，",
    Eng:"On the tenth day of the fifth month, in the nineteenth year of Nebuchadnezzar king of Babylon, Nebuzaradan commander of the imperial guard, who served the king of Babylon, came to Jerusalem.",
    Ind:"Dalam bulan yang kelima, pada tanggal sepuluh bulan itu--itulah tahun kesembilan belas pemerintahan Nebukadnezar, raja Babel--datanglah Nebuzaradan, kepala pasukan pengawal, yang melayani raja Babel, ke Yerusalem."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:13, Page:1,
    Kor:"그는 주님의 성전과 왕궁과 예루살렘의 모든 건물 곧 큰 건물은 모두 불태워 버렸다.",
    Chn:"用火焚烧耶和华的殿和王宫，又焚烧耶路撒冷的房屋，就是各大户家的房屋。",
    Eng:"He set fire to the temple of the LORD, the royal palace and all the houses of Jerusalem. Every important building he burned down.",
    Ind:"Ia membakar rumah TUHAN, rumah raja dan segala rumah di Yerusalem; segala rumah orang-orang besar dibakarnya dengan api."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:14, Page:1,
    Kor:"근위대장이 지휘하는 바빌로니아의 모든 군대가 예루살렘의 사면 성벽을 모두 헐어 버렸다.",
    Chn:"跟从护卫长迦勒底的全军就拆毁耶路撒冷四围的城墙。",
    Eng:"The whole Babylonian army under the commander of the imperial guard broke down all the walls around Jerusalem.",
    Ind:"Segala tembok sekeliling kota Yerusalem dirobohkan oleh tentara Kasdim yang ada bersama-sama dengan kepala pasukan pengawal itu."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:15, Page:1,
    Kor:"근위대장 느부사라단은 백성 가운데서 가장 가난한 사람들과, 도성 안에 남은 나머지 사람들과, 바빌로니아 왕에게 투항한 사람들과, 나머지 기술자들을 모두 포로로 잡아갔다.",
    Chn:"那时护卫长尼布撒拉旦将民中最穷的和城里所剩下的百姓，并已经投降巴比伦王的人，以及大众所剩下的人，都掳去了。",
    Eng:"Nebuzaradan the commander of the guard carried into exile some of the poorest people and those who remained in the city, along with the rest of the craftsmen and those who had gone over to the king of Babylon.",
    Ind:"Sebagian dari orang-orang yang paling lemah dan sisa-sisa rakyat yang masih tinggal di kota itu dan pembelot-pembelot yang menyeberang ke pihak raja Babel dan sisa-sisa para pekerja tangan diangkut ke dalam pembuangan oleh Nebuzaradan, kepala pasukan pengawal itu."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:16, Page:1,
    Kor:"그러나 근위대장 느부사라단은, 그 땅에서 가장 가난한 백성 가운데 일부를 남겨 두어서, 포도원을 가꾸고 농사를 짓게 하였다.",
    Chn:"但护卫长尼布撒拉旦留下些民中最穷的，使他们修理葡萄园，耕种田地。",
    Eng:"But Nebuzaradan left behind the rest of the poorest people of the land to work the vineyards and fields.",
    Ind:"Hanya beberapa orang miskin dari negeri itu ditinggalkan oleh Nebuzaradan, kepala pasukan pengawal itu, untuk menjadi tukang-tukang kebun anggur dan peladang-peladang."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:17, Page:1,
    Kor:"○바빌로니아 군대는 주님의 성전에 있는 놋쇠 기둥과 받침대, 또 주님의 성전에 있는 놋바다를 부수어서, 모든 놋쇠를 바빌론으로 가져 갔다.",
    Chn:"耶和华殿的铜柱并殿内的盆座和铜海，迦勒底人都打碎了，将那铜运到巴比伦去了，",
    Eng:"The Babylonians broke up the bronze pillars, the movable stands and the bronze Sea that were at the temple of the LORD and they carried all the bronze to Babylon.",
    Ind:"Juga tiang-tiang tembaga yang ada di rumah TUHAN dan kereta penopang dan laut tembaga yang ada di rumah TUHAN dipecahkan oleh orang Kasdim dan seluruh tembaganya diangkut mereka ke Babel."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:18, Page:1,
    Kor:"또 솥과 부삽과 부집게와, 대야와 향 접시와 제사를 드릴 때에 쓰는 놋쇠 기구를 모두 가져 갔다.",
    Chn:"又带去锅、铲子、蜡剪、盘子、调羹，并所用的一切铜器、",
    Eng:"They also took away the pots, shovels, wick trimmers, sprinkling bowls, dishes and all the bronze articles used in the temple service.",
    Ind:"Kuali-kuali, penyodok-penyodok, pisau-pisau, bokor-bokor penyiraman dan cawan-cawan dan segala perkakas tembaga yang dipakai untuk menyelenggarakan kebaktian diambil mereka,"
  },
  {Bible:"Jeremiah", Chapter:52, Verse:19, Page:1,
    Kor:"근위대장은 잔과 화로와 대야와 솥과 등잔대와 향 접시와 부어 드리는 제사 때 쓰는 잔을 모두 가져 갔다. 금으로 만든 것은 금이라고 하여 가져 갔고, 은으로 만든 것은 은이라고 하여 가져 갔다.",
    Chn:"杯、火鼎、碗、盆、灯台、调羹、爵，无论金的银的，护卫长也都带去了。",
    Eng:"The commander of the imperial guard took away the basins, censers, sprinkling bowls, pots, lampstands, dishes and bowls used for drink offerings--all that were made of pure gold or silver.",
    Ind:"juga pasu-pasu, perbaraan-perbaraan, bokor-bokor penyiraman, kuali-kuali, kandil-kandil, cawan-cawan dan piala-piala, baik segala yang dari emas maupun segala yang dari perak, diambil oleh kepala pasukan pengawal itu."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:20, Page:1,
    Kor:"솔로몬 왕이 주님의 성전에 만들어 놓은 놋쇠로 만든 두 기둥과, 놋바다 하나와, 놋받침대 밑에 있는 놋쇠로 만든 소 모형 열둘을 모두 가져 갔다. 그가 가져 간 이 모든 기구의 놋쇠는, 그 무게를 달아 볼 수 없을 정도로 많았다.",
    Chn:"所罗门为耶和华殿所造的两根铜柱、一个铜海，并座下的十二只铜牛，这一切的铜多得无法可称。",
    Eng:"The bronze from the two pillars, the Sea and the twelve bronze bulls under it, and the movable stands, which King Solomon had made for the temple of the LORD, was more than could be weighed.",
    Ind:"Adapun kedua tiang, laut yang satu itu dan kedua belas lembu tembaga yang ada di bawah kereta penopang, yang dibuat oleh raja Salomo untuk rumah TUHAN, tiada tertimbang tembaga segala perkakas ini."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:21, Page:1,
    Kor:"기둥 한 개의 높이는 열여덟 자이고, 둘레가 열두 자이고, 기둥 속은 비었지만, 놋쇠 두께는 손가락 네 개의 너비이다.",
    Chn:"这一根柱子高十八肘，厚四指，是空的，围十二肘。",
    Eng:"Each of the pillars was eighteen cubits high and twelve cubits in circumference; each was four fingers thick, and hollow.",
    Ind:"Adapun tiang-tiang itu, satu tiang delapan belas hasta tingginya dan dapat dililit oleh tali yang dua belas hasta panjangnya; tebalnya empat jari dan geronggang dari dalam."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:22, Page:1,
    Kor:"그 위에는 놋쇠로 된 기둥머리가 있고, 각 기둥머리의 높이는 다섯 자이다. 그리고 놋쇠로 된 기둥머리 위 사방에는 그물과 석류 모양의 장식이 얹혀 있다. 다른 기둥도 석류 모양을 하고 있어서, 똑같이 장식되어 있다.",
    Chn:"柱上有铜顶，高五肘；铜顶的周围有网子和石榴，都是铜的。那一根柱子照此一样，也有石榴。",
    Eng:"The bronze capital on top of the one pillar was five cubits high and was decorated with a network and pomegranates of bronze all around. The other pillar, with its pomegranates, was similar.",
    Ind:"Di atasnya ada ganja dari tembaga; tinggi ganja yang satu itu lima hasta, dan jala-jala dan buah-buah delima ada di atas ganja itu sekeliling, semuanya dari tembaga. Dan tiang yang kedua seperti itu juga. Mengenai buah delima,"
  },
  {Bible:"Jeremiah", Chapter:52, Verse:23, Page:1,
    Kor:"그물에 사방으로 매달린 석류는 모두 백 개인데, 밖에서 보이는 것은 아흔여섯 개이다.",
    Chn:"柱子四面有九十六个石榴，在网子周围，共有一百石榴。",
    Eng:"There were ninety-six pomegranates on the sides; the total number of pomegranates above the surrounding network was a hundred.",
    Ind:"ada sembilan puluh enam buah delima yang merupakan gambar timbul; seluruhnya buah-buah delima itu ada seratus pada jala-jala itu berkeliling."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:24, Page:1,
    Kor:"<유다 백성이 바빌로니아로 잡혀 가다(왕하 25:18-21, 27-30)> ○근위대장은 대제사장 스라야와 부제사장 스바냐와 세 명의 성전 문지기를 체포하였다.",
    Chn:"护卫长拿住大祭司西莱雅、副祭司西番亚，和三个把门的，",
    Eng:"The commander of the guard took as prisoners Seraiah the chief priest, Zephaniah the priest next in rank and the three doorkeepers.",
    Ind:"Lalu kepala pasukan pengawal itu menangkap Seraya, imam kepala, dan Zefanya, imam tingkat dua, dan ketiga orang penjaga pintu."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:25, Page:1,
    Kor:"이 밖에도 그가 도성 안에서 체포한 사람은, 군대를 통솔하는 내시 한 사람과, 도성 안에 그대로 남은 왕의 시종 일곱 사람과, 그 땅의 백성을 군인으로 징집하는 권한을 가진 군대 참모장과, 도성 안에 남은 그 땅의 백성 예순 명이다.",
    Chn:"又从城中拿住一个管理兵丁的官，并在城里所遇常见王面的七个人和检点国民军长的书记，以及城里所遇见的国民六十个人。",
    Eng:"Of those still in the city, he took the officer in charge of the fighting men, and seven royal advisers. He also took the secretary who was chief officer in charge of conscripting the people of the land and sixty of his men who were found in the city.",
    Ind:"Dari kota itu ditangkapnya seorang pegawai istana yang diangkat mengepalai prajurit-prajurit dan tujuh orang pelayan pribadi raja yang terdapat di kota itu, dan panitera panglima tentara yang mengerahkan rakyat negeri menjadi tentara, dan enam puluh orang dari rakyat negeri yang terdapat di tengah-tengah kota itu."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:26, Page:1,
    Kor:"근위대장 느부사라단은 그들을 체포하여, 리블라에 머물고 있는 바빌로니아 왕에게 데리고 갔다.",
    Chn:"护卫长尼布撒拉旦将这些人带到利比拉的巴比伦王那里。",
    Eng:"Nebuzaradan the commander took them all and brought them to the king of Babylon at Riblah.",
    Ind:"Nebuzaradan, kepala pasukan pengawal, menangkap mereka dan membawa mereka kepada raja Babel, di Ribla."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:27, Page:1,
    Kor:"바빌로니아 왕은 하맛 땅 리블라에서 그들을 처형하였다. ○이렇게 유다 백성은 포로가 되어서 그들의 땅에서 쫓겨났다.",
    Chn:"巴比伦王就把他们击杀在哈马地的利比拉。这样，犹大人被掳去离开本地。",
    Eng:"There at Riblah, in the land of Hamath, the king had them executed. So Judah went into captivity, away from her land.",
    Ind:"Lalu raja Babel menyuruh membunuh mereka di Ribla, di tanah Hamat. Demikianlah orang Yehuda diangkut ke dalam pembuangan dari tanahnya."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:28, Page:1,
    Kor:"느부갓네살이 포로로 끌고 간 유다 백성의 수는 이러하다. 그의 통치 제 칠년에는 삼천이십삼 명이었다.",
    Chn:"尼布甲尼撒所掳的民数记在下面：在他第七年掳去犹大人三千零二十三名；",
    Eng:"This is the number of the people Nebuchadnezzar carried into exile: in the seventh year,",
    Ind:"Inilah jumlah rakyat yang diangkut ke dalam pembuangan oleh Nebuzaradan: dalam tahun ketujuh, tiga ribu dua puluh tiga orang Yehuda;"
  },
  {Bible:"Jeremiah", Chapter:52, Verse:29, Page:1,
    Kor:"느부갓네살의 통치 제 십팔년에는 예루살렘에서 팔백삼십이 명을 포로로 잡아갔다.",
    Chn:"尼布甲尼撒十八年从耶路撒冷掳去八百三十二人；",
    Eng:"in Nebuchadnezzar's eighteenth year, 832 people from Jerusalem;",
    Ind:"dalam tahun kedelapan belas zaman Nebukadnezar, delapan ratus tiga puluh dua jiwa dari Yerusalem;"
  },
  {Bible:"Jeremiah", Chapter:52, Verse:30, Page:1,
    Kor:"느부갓네살의 통치 제 이십삼년에는 근위대장 느부사라단이 유다 사람 칠백사십오 명을 포로로 잡아 갔다. 잡혀 간 포로의 수는 모두 사천육백 명이다.",
    Chn:"尼布甲尼撒二十三年，护卫长尼布撒拉旦掳去犹大人七百四十五名；共有四千六百人。",
    Eng:"in his twenty-third year, 745 Jews taken into exile by Nebuzaradan the commander of the imperial guard. There were 4,600 people in all.",
    Ind:"dalam tahun kedua puluh tiga zaman Nebukadnezar, diangkut ke dalam pembuangan oleh Nebuzaradan, kepala pasukan pengawal, tujuh ratus empat puluh lima jiwa orang Yehuda; seluruhnya berjumlah empat ribu enam ratus jiwa."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:31, Page:1,
    Kor:"○유다 왕 여호야긴이 포로로 잡혀 간 지 서른일곱 해가 되는 해 곧 바빌로니아 왕 에윌므로닥이 왕위에 오른 그 해 열두째 달 이십오일에, 그가 유다 왕 여호야긴에게 특사를 베풀어서, 그를 옥에서 석방하였다.",
    Chn:"犹大王约雅斤被掳后三十七年，巴比伦王以未·米罗达元年十二月二十五日，使犹大王约雅斤抬头，提他出监，",
    Eng:"In the thirty-seventh year of the exile of Jehoiachin king of Judah, in the year Evil-Merodach became king of Babylon, he released Jehoiachin king of Judah and freed him from prison on the twenty-fifth day of the twelfth month.",
    Ind:"Kemudian dalam tahun ketiga puluh tujuh sesudah Yoyakhin, raja Yehuda, dibuang, dalam bulan yang kedua belas, pada tanggal dua puluh lima bulan itu, maka Ewil-Merodakh, raja Babel, dalam tahun ia menjadi raja, menunjukkan belas kasihannya kepada Yoyakhin, raja Yehuda, dengan melepaskannya dari penjara."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:32, Page:1,
    Kor:"그는 여호야긴에게 친절하게 대접하여 주면서, 그와 함께 바빌로니아에 있는 다른 왕들의 자리보다 더 높은 자리를 그에게 주었다.",
    Chn:"又对他说恩言，使他的位高过与他一同在巴比伦众王的位，",
    Eng:"He spoke kindly to him and gave him a seat of honor higher than those of the other kings who were with him in Babylon.",
    Ind:"Ewil-Merodakh berbicara baik-baik dengan dia dan memberikan kedudukan kepadanya lebih tinggi dari pada kedudukan raja-raja yang bersama-sama dengan dia di Babel."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:33, Page:1,
    Kor:"그래서 여호야긴은 죄수복을 벗고, 남은 생애 동안 늘 왕과 한 상에서 먹었다.",
    Chn:"给他脱了囚服。他终身在巴比伦王面前吃饭。",
    Eng:"So Jehoiachin put aside his prison clothes and for the rest of his life ate regularly at the king's table.",
    Ind:"Yoyakhin boleh mengganti pakaian penjaranya dan boleh selalu makan roti di hadapan raja selama hidupnya."
  },
  {Bible:"Jeremiah", Chapter:52, Verse:34, Page:1,
    Kor:"여호야긴의 생계비는, 그가 죽을 때까지 매일 일정하게, 그의 일생 동안 끊이지 않고, 바빌로니아 왕이 그에게 대주었다.",
    Chn:"巴比伦王赐他所需用的食物，日日赐他一分，终身是这样，直到他死的日子。",
    Eng:"",
    Ind:"Dan tentang belanjanya, raja Babel selalu memberikannya kepadanya, sekadar yang perlu tiap-tiap hari, selama hidupnya, sampai hari matinya."
  },
]);
