// 예레미야 24장 · Jeremiah 24
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",24,10);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:24, Verse:1, Page:1, Kor:"<무화과 두 광주리> 주님께서 나에게 이런 것을 보여 주셨다. 내가 보니, 주님의 성전 앞에 무화과 광주리 두 개가 놓여 있었다. 이것은 바빌로니아 왕 느부갓네살이 여호야김의 아들 유다 왕 a여고냐와 유다의 고관들을 비롯하여 기술자들과 대장장이들을 함께 예루살렘에서 포로로 사로잡아 바빌로니아로 데려간 뒤에 있었던 일이다.(a 일명 '여호야긴')", Chn:"", Eng:"After Jehoiachin son of Jehoiakim king of Judah and the officials, the craftsmen and the artisans of Judah were carried into exile from Jerusalem to Babylon by Nebuchadnezzar king of Babylon, the LORD showed me two baskets of figs placed in front of the temple of the LORD.", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:2, Page:1, Kor:"그런데 한 광주리에는 맏물 무화과처럼 아주 좋은 무화과가 담겨 있었고, 다른 한 광주리에는 너무 나빠서 먹을 수도 없는 아주 나쁜 무화과가 담겨 있었다.", Chn:"", Eng:"One basket had very good figs, like those that ripen early; the other basket had very poor figs, so bad they could not be eaten.", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:3, Page:1, Kor:"○그 때에 주님께서 나에게 물으셨다. \"예레미야야, 네가 무엇을 보느냐?\" 내가 대답하였다. \"무화과입니다. 좋은 무화과는 아주 좋고, 나쁜 무화과는 아주 나빠서, 먹을 수가 없습니다.\"", Chn:"", Eng:"Then the LORD asked me, \"What do you see, Jeremiah?\" \"Figs,\" I answered. \"The good ones are very good, but the poor ones are so bad they cannot be eaten.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:4, Page:1, Kor:"○그러자 주님께서 나에게 이렇게 일러주셨다.", Chn:"", Eng:"Then the word of the LORD came to me:", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:5, Page:1, Kor:"○\"나 주 이스라엘의 하나님이 말한다. 내가 이 곳에서 b바빌로니아 사람의 땅으로 내쫓은 유다의 포로들을 이 좋은 무화과처럼 잘 돌보아 주겠다.(b 또는 '갈대아')", Chn:"", Eng:"\"This is what the LORD, the God of Israel, says: 'Like these good figs, I regard as good the exiles from Judah, whom I sent away from this place to the land of the Babylonians.", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:6, Page:1, Kor:"내가 그들을 지켜 보면서 잘 되게 하고, 다시 이 땅으로 데려오겠다. 내가 그들을 세우고 헐지 않겠으며, 내가 그들을 심고 뽑지 않겠다.", Chn:"", Eng:"My eyes will watch over them for their good, and I will bring them back to this land. I will build them up and not tear them down; I will plant them and not uproot them.", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:7, Page:1, Kor:"이제는 내가 그들에게 나를 그들의 주로 알아볼 수 있는 마음을 주겠다. 그러면 그들이 온전한 마음으로 나에게 돌아와서 나의 백성이 되고, 나는 그들의 하나님이 될 것이다.", Chn:"", Eng:"I will give them a heart to know me, that I am the LORD. They will be my people, and I will be their God, for they will return to me with all their heart.", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:8, Page:1, Kor:"○그러나, 유다 왕 시드기야와 그의 대신들을 비롯하여, 예루살렘에 남은 사람들과 이 땅에 남은 사람들과 이집트 땅으로 간 사람들은, 아주 나빠서 먹을 수가 없는, 나쁜 무화과처럼 만들어 버리겠다. 나 주가 분명히 말한다.", Chn:"", Eng:"\"'But like the poor figs, which are so bad they cannot be eaten,' says the LORD, 'so will I deal with Zedekiah king of Judah, his officials and the survivors from Jerusalem, whether they remain in this land or live in Egypt.", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:9, Page:1, Kor:"내가 c그들을 세계 만국으로 흩어 놓아, 혐오의 대상이 되게 하겠다. 그러면 내가 쫓아 보낸 그 모든 곳에서, 그들이 수치와 조롱을 당하고, 비웃음과 저주를 받게 될 것이다.(c 또는 '그들로 세계 만국에 두려움이 되게 하여')", Chn:"", Eng:"I will make them abhorrent and an offense to all the kingdoms of the earth, a reproach and a byword, an object of ridicule and cursing, wherever I banish them.", Ind:""},
  {Bible:"Jeremiah", Chapter:24, Verse:10, Page:1, Kor:"그리고 내가 그들과 그들의 조상에게 준 땅에서 그들이 멸절될 때까지, 나는 계속 그들에게 전쟁과 기근과 염병을 보내겠다.\"", Chn:"", Eng:"I will send the sword, famine and plague against them until they are destroyed from the land I gave to them and their fathers.'\"", Ind:""},
]);
