// 예레미야 18장 · Jeremiah 18
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",18,23);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:18, Verse:1, Page:1, Kor:"<토기장이의 비유> 이것은 주님께서 예레미야에게 하신 말씀이다.", Chn:"", Eng:"This is the word that came to Jeremiah from the LORD:", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:2, Page:1, Kor:"\"너는 어서 토기장이의 집으로 내려가거라. 거기에서 내가 너에게 나의 말을 선포하겠다.\"", Chn:"", Eng:"\"Go down to the potter's house, and there I will give you my message.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:3, Page:1, Kor:"○그래서 내가 토기장이의 집으로 내려갔더니, 토기장이가 마침 물레를 돌리며 일을 하고 있었다.", Chn:"", Eng:"So I went down to the potter's house, and I saw him working at the wheel.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:4, Page:1, Kor:"그런데 그 토기장이는 진흙으로 그릇을 빚다가 잘 되지 않으면, 그 흙으로 다른 그릇을 빚었다.", Chn:"", Eng:"But the pot he was shaping from the clay was marred in his hands; so the potter formed it into another pot, shaping it as seemed best to him.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:5, Page:1, Kor:"○그 때에 주님께서 나에게 이렇게 말씀하셨다.", Chn:"", Eng:"Then the word of the LORD came to me:", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:6, Page:1, Kor:"○\"'이스라엘 백성아, 내가 이 토기장이와 같이 너희를 다룰 수가 없겠느냐? 나 주의 말이다. 이스라엘 백성아, 진흙이 토기장이의 손 안에 있듯이, 너희도 내 손 안에 있다.", Chn:"", Eng:"\"O house of Israel, can I not do with you as this potter does?\" declares the LORD. \"Like clay in the hand of the potter, so are you in my hand, O house of Israel.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:7, Page:1, Kor:"내가 어떤 민족이나 나라의 뿌리를 뽑아내거나, 그들을 부수거나 멸망시키겠다고 말을 하였더라도,", Chn:"", Eng:"If at any time I announce that a nation or kingdom is to be uprooted, torn down and destroyed,", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:8, Page:1, Kor:"그 민족이 내가 경고한 죄악에서 돌이키기만 하면 나는 그들에게 내리려고 생각한 재앙을 거둔다.", Chn:"", Eng:"and if that nation I warned repents of its evil, then I will relent and not inflict on it the disaster I had planned.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:9, Page:1, Kor:"○그러나 내가 어떤 민족이나 나라를 세우고 심겠다고 말을 하였더라도,", Chn:"", Eng:"And if at another time I announce that a nation or kingdom is to be built up and planted,", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:10, Page:1, Kor:"그 백성이 나의 말을 순종하지 않고, 내가 보기에 악한 일을 하기만 하면, 나는 그들에게 내리기로 약속한 복을 거둔다.'", Chn:"", Eng:"and if it does evil in my sight and does not obey me, then I will reconsider the good I had intended to do for it.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:11, Page:1, Kor:"○그러므로 너는 이제 유다 사람과 예루살렘 주민에게 전하여라. '나 주가 말한다. 내가 너희에게 내릴 재앙을 마련하고 있으며, 너희를 칠 계획도 세우고 있다. 그러므로 너희는 어서, 각기 자신의 사악한 길에서 돌이키고, 너희의 행동과 행실을 고쳐라.'", Chn:"", Eng:"\"Now therefore say to the people of Judah and those living in Jerusalem, 'This is what the LORD says: Look! I am preparing a disaster for you and devising a plan against you. So turn from your evil ways, each one of you, and reform your ways and your actions.'", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:12, Page:1, Kor:"○네가 이렇게 말하면, 그들은 이르기를 '그럴 필요 없다. 우리는 우리 생각대로 살아가겠다. 우리는 각자 자신의 악한 마음에서 나오는 고집대로 행동하겠다' 할 것이다.\"", Chn:"", Eng:"But they will reply, 'It's no use. We will continue with our own plans; each of us will follow the stubbornness of his evil heart.'\"", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:13, Page:1, Kor:"<이스라엘 백성이 주님을 거역하다> \"그러므로 나 주가 말한다. 누가 이와 같은 말을 들어 보았는지, 세상 만민에게 물어 보아라. 처녀 이스라엘은 너무 역겨운 일을 저질렀다.", Chn:"", Eng:"Therefore this is what the LORD says: \"Inquire among the nations: Who has ever heard anything like this? A most horrible thing has been done by Virgin Israel.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:14, Page:1, Kor:"레바논 산의 험준한 바위 봉우리에 눈이 없는 때가 있더냐? 거기에서 흘러 내리는 시원한 물줄기가 마르는 일이 있더냐?", Chn:"", Eng:"Does the snow of Lebanon ever vanish from its rocky slopes? Do its cool waters from distant sources ever cease to flow?", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:15, Page:1, Kor:"그러나 내 백성은 나를 잊어버리고, 헛된 우상들에게 분향을 한다. 옛부터 걸어온 바른길을 벗어나서, 이정표도 없는 길로 들어섰다.", Chn:"", Eng:"Yet my people have forgotten me; they burn incense to worthless idols, which made them stumble in their ways and in the ancient paths. They made them walk in bypaths and on roads not built up.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:16, Page:1, Kor:"그들이 사는 땅을 황폐하게 만들어 영영 비웃음거리가 되게 하니, 그 곳을 지나가는 사람마다 놀라서 머리를 흔들며 비웃는다.", Chn:"", Eng:"Their land will be laid waste, an object of lasting scorn; all who pass by will be appalled and will shake their heads.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:17, Page:1, Kor:"내가 그들을 원수 앞에서 흩어 버리기를 동풍으로 흩어 버리듯 할 것이며, 그들이 재난을 당하는 날, 내가 그들에게 등을 돌리고, 내 얼굴을 보이지 않을 것이다.\"", Chn:"", Eng:"Like a wind from the east, I will scatter them before their enemies; I will show them my back and not my face in the day of their disaster.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:18, Page:1, Kor:"<예레미야의 암살 음모> ○백성이 나를 두고 이르기를 \"이제 예레미야를 죽일 계획을 세우자. 이 사람이 없어도 우리에게는 율법을 가르쳐 줄 제사장이 있고, 지혜를 가르쳐 줄 현자가 있으며, 말씀을 전하여 줄 예언자가 있다. 그러니 어서 우리의 혀로 그를 헐뜯자. 그가 하는 모든 말을 무시하여 버리자\" 합니다.", Chn:"", Eng:"They said, \"Come, let's make plans against Jeremiah; for the teaching of the law by the priest will not be lost, nor will counsel from the wise, nor the word from the prophets. So come, let's attack him with our tongues and pay no attention to anything he says.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:19, Page:1, Kor:"<예레미야의 기도> 주님, 저의 호소를 들어주십시오. 원수들이 저를 두고 하는 말을 들어 보십시오!", Chn:"", Eng:"Listen to me, O LORD; hear what my accusers are saying!", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:20, Page:1, Kor:"선을 악으로 갚아도 되는 겁니까? 그런데도 그들은 제 목숨을 노려서 함정을 팠습니다. 제가 주님 앞에 나서서 그들을 변호한 것, 주님께서 그들을 보시고 진노하셨지만, 주님의 진노를 풀어드리려고 그들을 생각하면서, 주님의 은혜를 간구한 것을, 기억하여 주십시오.", Chn:"", Eng:"Should good be repaid with evil? Yet they have dug a pit for me. Remember that I stood before you and spoke in their behalf to turn your wrath away from them.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:21, Page:1, Kor:"그들이 이렇게 배은망덕하니, 그들의 아들딸들이 굶어 죽거나 전쟁에서 죽게 하여 주십시오. 그들의 아내들이 아들딸들을 잃게 하시고, 남편들을 잃어 과부가 되게 하여 주십시오. 장정들은 전쟁터에서 칼에 찔려 죽게 하여 주십시오.", Chn:"", Eng:"So give their children over to famine; hand them over to the power of the sword. Let their wives be made childless an` widows; let their men be put to death, their young men slain by the sword in battle.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:22, Page:1, Kor:"그들이 저를 잡으려고 함정을 팠고, 제 발을 걸리게 하려고 올가미들을 숨겨 놓았으니, 주님께서 그들에게 약탈하는 자들을 졸지에 보내 주셔서, 그들의 집집마다 울부짖는 소리가 터져 나오게 하여 주십시오.", Chn:"", Eng:"Let a cry be heard from their houses when you suddenly bring invaders against them, for they have dug a pit to capture me and have hidden snares for my feet.", Ind:""},
  {Bible:"Jeremiah", Chapter:18, Verse:23, Page:1, Kor:"주님, 저를 죽이려는 그들의 모든 흉계를 주님께서는 다 아시니, 그들의 죄악을 용서하지 마시고, 그들의 허물을 가볍게 다루지도 마십시오. 주님께서 진노하시는 날에, 그들이 주님 앞에서 거꾸러져 죽게 하여 주십시오.", Chn:"", Eng:"But you know, O LORD, all their plots to kill me. Do not forgive their crimes or blot out their sins from your sight. Let them be overthrown before you; deal with them in the time of your anger.", Ind:""},
]);
