// 예레미야 11장 · Jeremiah 11
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",11,23);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:11, Verse:1, Page:1, Kor:"", Chn:"", Eng:"This is the word that came to Jeremiah from the LORD:", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:2, Page:1, Kor:"", Chn:"", Eng:"\"Listen to the terms of this covenant and tell them to the people of Judah and to those who live in Jerusalem.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:3, Page:1, Kor:"", Chn:"", Eng:"Tell them that this is what the LORD, the God of Israel, says: 'Cursed is the man who does not obey the terms of this covenant--", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:4, Page:1, Kor:"", Chn:"", Eng:"the terms I commanded your forefathers when I brought them out of Egypt, out of the iron-smelting furnace.' I said, 'Obey me and do everything I command you, and you will be my people, and I will be your God.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:5, Page:1, Kor:"", Chn:"", Eng:"Then I will fulfill the oath I swore to your forefathers, to give them a land flowing with milk and honey'--the land you possess today.\" I answered, \"Amen, LORD.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:6, Page:1, Kor:"", Chn:"", Eng:"The LORD said to me, \"Proclaim all these words in the towns of Judah and in the streets of Jerusalem: 'Listen to the terms of this covenant and follow them.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:7, Page:1, Kor:"", Chn:"", Eng:"From the time I brought your forefathers up from Egypt until today, I warned them again and again, saying, \"Obey me.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:8, Page:1, Kor:"", Chn:"", Eng:"But they did not listen or pay attention; instead, they followed the stubbornness of their evil hearts. So I brought on them all the curses of the covenant I had commanded them to follow but that they did not keep.'\"", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:9, Page:1, Kor:"", Chn:"", Eng:"Then the LORD said to me, \"There is a conspiracy among the people of Judah and those who live in Jerusalem.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:10, Page:1, Kor:"", Chn:"", Eng:"They have returned to the sins of their forefathers, who refused to listen to my words. They have followed other gods to serve them. Both the house of Israel and the house of Judah have broken the covenant I made with their forefathers.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:11, Page:1, Kor:"", Chn:"", Eng:"Therefore this is what the LORD says: 'I will bring on them a disaster they cannot escape. Although they cry out to me, I will not listen to them.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:12, Page:1, Kor:"", Chn:"", Eng:"The towns of Judah and the people of Jerusalem will go and cry out to the gods to whom they burn incense, but they will not help them at all when disaster strikes.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:13, Page:1, Kor:"", Chn:"", Eng:"You have as many gods as you have towns, O Judah; and the altars you have set up to burn incense to that shameful god Baal are as many as the streets of Jerusalem.'", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:14, Page:1, Kor:"", Chn:"", Eng:"\"Do not pray for this people nor offer any plea or petition for them, because I will not listen when they call to me in the time of their distress.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:15, Page:1, Kor:"", Chn:"", Eng:"\"What is my beloved doing in my temple as she works out her evil schemes with many? Can consecrated meat avert your punishment? When you engage in your wickedness, then you rejoice.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:16, Page:1, Kor:"", Chn:"", Eng:"The LORD called you a thriving olive tree with fruit beautiful in form. But with the roar of a mighty storm he will set it on fire, and its branches will be broken.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:17, Page:1, Kor:"", Chn:"", Eng:"The LORD Almighty, who planted you, has decreed disaster for you, because the house of Israel and the house of Judah have done evil and provoked me to anger by burning incense to Baal.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:18, Page:1, Kor:"", Chn:"", Eng:"Because the LORD revealed their plot to me, I knew it, for at that time he showed me what they were doing.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:19, Page:1, Kor:"", Chn:"", Eng:"I had been like a gentle lamb led to the slaughter; I did not realize that they had plotted against me, saying, \"Let us destroy the tree and its fruit; let us cut him off from the land of the living, that his jame be remembered no more.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:20, Page:1, Kor:"", Chn:"", Eng:"But, O LORD Almighty, you who judge righteously and test the heart and mind, let me see your vengeance upon them, for to you I have committed my cause.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:21, Page:1, Kor:"", Chn:"", Eng:"\"Therefore this is what the LORD says about the men of Anathoth who are seeking your life and saying, 'Do not prophesy in the name of the LORD or you will die by our hands'--", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:22, Page:1, Kor:"", Chn:"", Eng:"therefore this is what the LORD Almighty says: 'I will punish them. Their young men will die by the sword, their sons and daughters by famine.", Ind:""},
  {Bible:"Jeremiah", Chapter:11, Verse:23, Page:1, Kor:"", Chn:"", Eng:"Not even a remnant will be left to them, because I will bring disaster on the men of Anathoth in the year of their punishment.'\"", Ind:""},
]);
