// 예레미야 4장 · Jeremiah 4
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",4,31);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:4, Verse:1, Page:1, Kor:"", Chn:"", Eng:"\"If you will return, O Israel, return to me,\" declares the LORD. \"If you put your detestable idols out of my sight and no longer go astray,", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:2, Page:1, Kor:"", Chn:"", Eng:"and if in a truthful, just and righteous way you swear, 'As surely as the LORD lives,' then the nations will be blessed by him and in him they will glory.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:3, Page:1, Kor:"", Chn:"", Eng:"This is what the LORD says to the men of Judah and to Jerusalem: \"Break up your unplowed ground and do not sow among thorns.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:4, Page:1, Kor:"", Chn:"", Eng:"Circumcise yourselves to the LORD, circumcise your hearts, you men of Judah and people of Jerusalem, or my wrath will break out and burn like fire because of the evil you have done--burn with no one to quench it.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:5, Page:1, Kor:"", Chn:"", Eng:"\"Announce in Judah and proclaim in Jerusalem and say: 'Sound the trumpet throughout the land!' Cry aloud and say: 'Gather together! Let us flee to the fortified cities!'", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:6, Page:1, Kor:"", Chn:"", Eng:"Raise the signal to go to Zion! Flee for safety without delay! For I am bringing disaster from the north, even terrible destruction.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:7, Page:1, Kor:"", Chn:"", Eng:"A lion has come out of his lair; a destroyer of nations has set out. He has left his place to lay waste your land. Your towns will lie in ruins without inhabitant.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:8, Page:1, Kor:"", Chn:"", Eng:"So put on sackcloth, lament and wail, for the fierce anger of the LORD has not turned away from us.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:9, Page:1, Kor:"", Chn:"", Eng:"\"In that day,\" declares the LORD, \"the king and the officials will lose heart, the priests will be horrified, and the prophets will be appalled.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:10, Page:1, Kor:"", Chn:"", Eng:"Then I said, \"Ah, Skvereign LORD, how completely you have deceived this people and Jerusalem by saying, 'You will have peace,' when the sword is at our throats.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:11, Page:1, Kor:"", Chn:"", Eng:"At that time this people and Jerusalem will be told, \"A scorching wind from the barren heights in the desert blows toward my people, but not to winnow or cleanse;", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:12, Page:1, Kor:"", Chn:"", Eng:"a wind too strong for that comes from me. Now I pronounce my judgments against them.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:13, Page:1, Kor:"", Chn:"", Eng:"Look! He advances like the clouds, his chariots come like a whirlwind, his horses are swifter than eagles. Woe to us! We are ruined!", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:14, Page:1, Kor:"", Chn:"", Eng:"O Jerusalem, wash the evil from your heart and be saved. How long will you harbor wicked thoughts?", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:15, Page:1, Kor:"", Chn:"", Eng:"A voice is announcing from Dan, proclaiming disaster from the hills of Ephraim.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:16, Page:1, Kor:"", Chn:"", Eng:"\"Tell this to the nations, proclaim it to Jerusalem: 'A besieging army is coming from a distant land, raising a war cry against the cities of Judah.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:17, Page:1, Kor:"", Chn:"", Eng:"They surround her like men guarding a field, because she has rebelled against me,'\" declares the LORD.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:18, Page:1, Kor:"", Chn:"", Eng:"\"Your own conduct and actions have brought this upon you. This is your punishment. How bitter it is! How it pierces to the heart!\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:19, Page:1, Kor:"", Chn:"", Eng:"Oh, my anguish, my anguish! I writhe in pain. Oh, the agony of my heart! My heart pounds within me, I cannot keep silent. For I have heard the sound of the trumpet; I have heard the battle cry.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:20, Page:1, Kor:"", Chn:"", Eng:"Disaster follows disaster; the whole land lies in ruins. In an instant my tents are destroyed, my shelter in a moment.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:21, Page:1, Kor:"", Chn:"", Eng:"How long must I see the battle standard and hear the sound of the trumpet?", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:22, Page:1, Kor:"", Chn:"", Eng:"\"My people are fools; they do not know me. They are senseless children; they have no understanding. They are skilled in doing evil; they know not how to do good.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:23, Page:1, Kor:"", Chn:"", Eng:"I looked at the earth, and it was formless and empty; and at the heavens, and their light was gone.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:24, Page:1, Kor:"", Chn:"", Eng:"I looked at the mountains, and they were quaking; all the hills were swaying.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:25, Page:1, Kor:"", Chn:"", Eng:"I looked, and there were no people; every bird in the sky had flown away.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:26, Page:1, Kor:"", Chn:"", Eng:"I looked, and the fruitful land was a desert; all its towns lay in ruins before the LORD, before his fierce anger.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:27, Page:1, Kor:"", Chn:"", Eng:"This is what the LORD says: \"The whole land will be ruined, though I will not destroy it completely.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:28, Page:1, Kor:"", Chn:"", Eng:"Therefore the earth will mourn and the heavens above grow dark, because I have spoken and will not relent, I have decided and will not turn back.\"", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:29, Page:1, Kor:"", Chn:"", Eng:"At the sound of horsemen and archers every town takes to flight. Some go into the thickets; some climb up among the rocks. All the towns are deserted; no one lives in them.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:30, Page:1, Kor:"", Chn:"", Eng:"What are you doing, O devastated one? Why dress yourself in scarlet and put on jewels of gold? Why shade your eyes with paint? You adorn yourself in vain. Your lovers despise you; they seek your life.", Ind:""},
  {Bible:"Jeremiah", Chapter:4, Verse:31, Page:1, Kor:"", Chn:"", Eng:"I hear a cry as of a woman in labor, a groan as of one bearing her first child--the cry of the Daughter of Zion gasping for breath, stretching out her hands and saying, \"Alas! I am fainting; my life is given over to murderers.\"", Ind:""},
]);
