// 예레미야 13장 · Jeremiah 13
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Jeremiah",13,27);
BibleDB.add([
  {Bible:"Jeremiah", Chapter:13, Verse:1, Page:1,
    Kor:"<허리띠> 주님께서 나에게 이렇게 말씀하셨다. \"너는 가서 베로 만든 띠를 사서 너의 허리에 띠고, 물에 적시는 일이 없도록 하여라.\"",
    Chn:"耶和华对我如此说：「你去买一根麻布带子束腰，不可放在水中。」",
    Eng:"This is what the LORD said to me: \"Go and buy a linen belt and put it around your waist, but do not let it touch water.\"",
    Ind:"Beginilah firman TUHAN kepadaku: \"Pergilah membeli ikat pinggang lenan, ikatkanlah itu pada pinggangmu, tetapi jangan kaucelupkan ke dalam air!\""
  },
  {Bible:"Jeremiah", Chapter:13, Verse:2, Page:1,
    Kor:"그래서 나는 주님의 말씀대로, 베 띠를 사서 허리에 띠었다.",
    Chn:"我就照着耶和华的话，买了一根带子束腰。",
    Eng:"So I bought a belt, as the LORD directed, and put it around my waist.",
    Ind:"Maka aku membeli ikat pinggang seperti yang difirmankan TUHAN, lalu mengikatkannya pada pinggangku."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:3, Page:1,
    Kor:"○주님께서 다시 나에게 말씀하셨다.",
    Chn:"耶和华的话第二次临到我说：",
    Eng:"Then the word of the LORD came to me a second time:",
    Ind:"Sesudah itu datanglah firman TUHAN kepadaku untuk kedua kalinya, bunyinya:"
  },
  {Bible:"Jeremiah", Chapter:13, Verse:4, Page:1,
    Kor:"\"네가 사서 허리에 띤 그 띠를 들고 일어나, 유프라테스 강 가로 가서, 그 곳의 바위 틈에 그 띠를 숨겨 두어라.\"",
    Chn:"「要拿着你所买的腰带，就是你腰上的带子，起来往幼发拉底河去，将腰带藏在那里的磐石穴中。」",
    Eng:"\"Take the belt you bought and are wearing around your waist, and go now to Perath and hide it there in a crevice in the rocks.\"",
    Ind:"\"Ambillah ikat pinggang yang telah kaubeli dan yang sekarang pada pinggangmu itu! Pergilah segera ke sungai Efrat untuk menyembunyikannya di sana di celah-celah bukit batu!\""
  },
  {Bible:"Jeremiah", Chapter:13, Verse:5, Page:1,
    Kor:"그래서 나는 주님께서 명하신 대로, 가서 유프라테스 강 가에 그것을 숨겨 두었다.",
    Chn:"我就去，照着耶和华所吩咐我的，将腰带藏在幼发拉底河边。",
    Eng:"So I went and hid it at Perath, as the LORD told me.",
    Ind:"Maka pergilah aku, lalu menyembunyikannya di pinggir sungai Efrat seperti yang diperintahkan TUHAN kepadaku."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:6, Page:1,
    Kor:"○또 여러 날이 지난 다음에, 주님께서 나에게 말씀하셨다. \"너는 일어나서 유프라테스 강 가로 가서, 내가 그 곳에 숨겨 두라고 너에게 명한 그 띠를, 그 곳에서 가져 오너라.\"",
    Chn:"过了多日，耶和华对我说：「你起来往幼发拉底河去，将我吩咐你藏在那里的腰带取出来。」",
    Eng:"Many days later the LORD said to me, \"Go now to Perath and get the belt I told you to hide there.\"",
    Ind:"Sesudah beberapa waktu lamanya, berfirmanlah TUHAN kepadaku: \"Pergilah segera ke sungai Efrat mengambil dari sana ikat pinggang yang Kuperintahkan kausembunyikan di sana!\""
  },
  {Bible:"Jeremiah", Chapter:13, Verse:7, Page:1,
    Kor:"그래서 내가 유프라테스 강 가로 가서, 띠를 숨겨 둔 곳을 파고, 거기에서 그 띠를 꺼내 보니, 그 띠는 썩어서 전혀 쓸모가 없게 되었다.",
    Chn:"我就往幼发拉底河去，将腰带从我所藏的地方刨出来，见腰带已经变坏，毫无用了。",
    Eng:"So I went to Perath and dug up the belt and took it from the place where I had hidden it, but now it was ruined and completely useless.",
    Ind:"Maka pergilah aku ke sungai Efrat, lalu aku menggali dan mengambil ikat pinggang itu dari tempat aku menyembunyikannya, tetapi ternyata ikat pinggang itu sudah lapuk, tidak berguna untuk apapun."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:8, Page:1,
    Kor:"○그 때에 주님께서 나에게 말씀하셨다.",
    Chn:"耶和华的话临到我说：",
    Eng:"Then the word of the LORD came to me:",
    Ind:"Lalu datanglah firman TUHAN kepadaku:"
  },
  {Bible:"Jeremiah", Chapter:13, Verse:9, Page:1,
    Kor:"\"나 주가 말한다. 내가 유다의 교만과 예루살렘의 큰 교만을 이렇게 썩게 하겠다.",
    Chn:"「耶和华如此说：我必照样败坏犹大的骄傲和耶路撒冷的大骄傲。",
    Eng:"\"This is what the LORD says: 'In the same way I will ruin the pride of Judah and the great pride of Jerusalem.",
    Ind:"\"Beginilah firman TUHAN: Demikianlah Aku akan menghapuskan kecongkakbongakan Yehuda dan Yerusalem."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:10, Page:1,
    Kor:"이 악한 백성은 나의 말 듣는 것을 거부하고, 자기들의 마음에서 나오는 고집대로 살아가고, 다른 신들을 쫓아가서 그것들을 섬기며 경배하므로, 이제 이 백성은 전혀 쓸모가 없는 이 띠와 같이 되고 말 것이다.",
    Chn:"这恶民不肯听我的话，按自己顽梗的心而行，随从别神，事奉敬拜，他们也必像这腰带变为无用。」",
    Eng:"These wicked people, who refuse to listen to my words, who follow the stubbornness of their hearts and go after other gods to serve and worship them, will be like this belt--completely useless!",
    Ind:"Bangsa yang jahat ini, yang enggan mendengarkan perkataan-perkataan-Ku, yang mengikuti kedegilan hatinya dan mengikuti allah lain untuk beribadah dan sujud menyembah kepada mereka, akan menjadi seperti ikat pinggang ini yang tidak berguna untuk apapun."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:11, Page:1,
    Kor:"띠가 사람의 허리에 동여지듯이, 내가 이스라엘의 온 백성과 유다의 온 백성을 나에게 단단히 동여매어서, 그들이 내 백성이 되게 하고, 내 이름을 빛내게 하고, 나를 찬양하게 하고, 나에게 영광을 돌릴 수 있게 하였으나, 그들은 듣지 않았다. 나 주의 말이다.\"",
    Chn:"耶和华说：「腰带怎样紧贴人腰，照样，我也使以色列全家和犹大全家紧贴我，好叫他们属我为子民，使我得名声，得颂赞，得荣耀；他们却不肯听。」",
    Eng:"For as a belt is bound around a man's waist, so I bound the whole house of Israel and the whole house of Judah to me,' declares the LORD, 'to be my people for my renown and praise and honor. But they have not listened.'",
    Ind:"Sebab seperti ikat pinggang melekat pada pinggang seseorang, demikianlah tadinya segenap kaum Israel dan segenap kaum Yehuda Kulekatkan kepada-Ku, demikianlah firman TUHAN, supaya mereka itu menjadi umat, menjadi ternama, terpuji dan terhormat bagi-Ku. Tetapi mereka itu tidak mau mendengar.\""
  },
  {Bible:"Jeremiah", Chapter:13, Verse:12, Page:1,
    Kor:"<포도주 항아리> ○\"그러므로 너는 그들에게 이 말을 전하여라. '나 주 이스라엘의 하나님이 말한다. 항아리마다 포도주로 가득 찰 것이다!' 하면 그들이 너에게 묻기를 '항아리에 포도주가 담긴다는 것을 우리가 어찌 모르겠느냐?' 할 것이다.",
    Chn:"「所以你要对他们说：『耶和华—以色列的　神如此说：各坛都要盛满了酒。』他们必对你说：『我们岂不确知各坛都要盛满了酒呢？』",
    Eng:"\"Say to them: 'This is what the LORD, the God of Israel, says: Every wineskin should be filled with wine.' And if they say to you, 'Don't we know that every wineskin should be filled with wine?'",
    Ind:"\"Katakanlah kepada mereka firman ini: Beginilah firman TUHAN, Allah Israel: Setiap buyung harus dipenuhi dengan anggur! Dan jika mereka berkata kepadamu: Masakan kami tidak tahu betul, bahwa setiap buyung harus dipenuhi dengan anggur?,"
  },
  {Bible:"Jeremiah", Chapter:13, Verse:13, Page:1,
    Kor:"그러면 너는 그들에게 이렇게 대답하여라. '나 주가 말한다. 내가, 이 땅의 모든 주민과, 다윗의 왕위에 앉은 왕들과, 제사장들과, 예언자들과, 예루살렘의 모든 주민을, 술에 잔뜩 취하게 하여,",
    Chn:"你就要对他们说：『耶和华如此说：我必使这地的一切居民，就是坐大卫宝座的君王和祭司，与先知，并耶路撒冷的一切居民，都酩酊大醉。』」",
    Eng:"then tell them, 'This is what the LORD says: I am going to fill with drunkenness all who live in this land, including the kings who sit on David's throne, the priests, the prophets and all those living in Jerusalem.",
    Ind:"maka katakanlah kepada mereka: Beginilah firman TUHAN: Sesungguhnya, seluruh penduduk negeri ini akan Kupenuhi dengan kemabukan: para raja yang duduk di atas takhta Daud, para imam, para nabi dan seluruh penduduk Yerusalem."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:14, Page:1,
    Kor:"그들이 서로 부딪쳐서 깨지게 하고, 아버지와 자녀 사이에도 서로 부딪쳐서 깨지게 하겠다. 나는 그들을 불쌍히 여기지도 않으며, 동정도 하지 않으며, 사정없이 멸망시킬 것이다. 나 주의 말이다.'\"",
    Chn:"耶和华说：「我要使他们彼此相碰，就是父与子彼此相碰；我必不可怜，不顾惜，不怜悯，以致灭绝他们。」",
    Eng:"I will smash them one against the other, fathers and sons alike, declares the LORD. I will allow no pity or mercy or compassion to keep me from destroying them.'\"",
    Ind:"Aku akan membantingkan seorang kepada yang lain sampai mereka hancur, bapa-bapa dengan anak-anaknya, demikianlah firman TUHAN. Aku akan membinasakan mereka tanpa belas kasihan, tanpa merasa sayang dan tanpa ampun.\""
  },
  {Bible:"Jeremiah", Chapter:13, Verse:15, Page:1,
    Kor:"<교만에 대한 최후의 경고> 주님께서 말씀하셨으니, 너희는 들어라. 그리고 귀를 기울여라. 교만하지 말아라.",
    Chn:"你们当听，当侧耳而听。 不要骄傲，因为耶和华已经说了。",
    Eng:"Hear and pay attention, do not be arrogant, for the LORD has spoken.",
    Ind:"Dengarlah, pasanglah telingamu, janganlah kamu tinggi hati, sebab TUHAN telah berfirman."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:16, Page:1,
    Kor:"너희는 주님께서 날을 어두워지게 하시기 전에, 너희가 어두운 산 속에서 실족하기 전에, 주 너희 하나님께 영광을 돌려라. 그 때에는 너희가 빛을 고대해도, 주님은 빛을 어둠과 흑암으로 바꾸어 놓으실 것이다.",
    Chn:"耶和华—你们的　神未使黑暗来到， 你们的脚未在昏暗山上绊跌之先， 当将荣耀归给他； 免得你们盼望光明， 他使光明变为死荫， 成为幽暗。",
    Eng:"Give glory to the LORD your God before he brings the darkness, before your feet stumble on the darkening hills. You hope for light, but he will turn it to thick darkness and change it to deep gloom.",
    Ind:"Permuliakanlah TUHAN, Allahmu, sebelum Ia membuat hari menjadi gelap, sebelum kakimu tersandung di atas bukit-bukit yang diliputi senja, sementara kamu menanti-nantikan terang, tetapi Ia menjadikan hari kelam pekat dan mengubahnya menjadi gelap gulita."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:17, Page:1,
    Kor:"너희가 이 말을 듣지 않으면, 너희의 교만 때문에 내 심령은 숨어서 울고, 끝없이 눈물을 흘릴 것이다. 주님의 양 떼가 포로로 끌려갈 것이므로, 내 눈에서 하염없이 눈물이 흐를 것이다.",
    Chn:"你们若不听这话， 我必因你们的骄傲在暗地哭泣； 我眼必痛哭流泪， 因为耶和华的群众被掳去了。",
    Eng:"But if you do not listen, I will weep in secret because of your pride; my eyes will weep bitterly, overflowing with tears, because the LORD'S flock will be taken captive.",
    Ind:"Jika kamu tidak mau mendengarkannya, aku akan menangis di tempat yang tersembunyi oleh karena kesombonganmu, air mataku akan berlinang-linang, bahkan akan bercucuran, oleh sebab kawanan domba TUHAN diangkut tertawan."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:18, Page:1,
    Kor:"\"너는 저 왕과 왕후에게 전하여라. 왕의 자리에서 내려와서 낮은 곳에 앉으라고 하여라. 그들의 영광스러운 면류관이 머리에서 벗겨져 떨어졌기 때문이라고 하여라.",
    Chn:"你要对君王和太后说： 你们当自卑，坐在下边； 因你们的头巾， 就是你们的华冠，已经脱落了。",
    Eng:"Say to the king and to the queen mother, \"Come down from your thrones, for your glorious crowns will fall from your heads.\"",
    Ind:"Katakanlah kepada raja dan kepada ibu suri: \"Duduklah di tempat yang rendah sekali, sebab mahkota kemuliaanmu sudah turun dari kepalamu!\""
  },
  {Bible:"Jeremiah", Chapter:13, Verse:19, Page:1,
    Kor:"유다의 남쪽 성읍들이 포위되었으나, 그 포위망을 뚫어 주는 사람이 아무도 없어서, 온 유다가 포로로 끌려가되, 남김없이 모두 잡혀 가고 말았다.\"",
    Chn:"南方的城尽都关闭， 无人开放； 犹大全被掳掠， 且掳掠净尽。",
    Eng:"The cities in the Negev will be shut up, and there will be no one to open them. All Judah will be carried into exile, carried completely away.",
    Ind:"Kota-kota tanah Negeb sudah ditutup gerbangnya, dan tidak ada seorangpun yang membukanya. Segenap Yehuda sudah diangkut ke dalam pembuangan, diangkut ke dalam pembuangan seluruhnya."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:20, Page:1,
    Kor:"\"예루살렘아, 눈을 뜨고, 북녘에서 오는 적들을 보아라. 네가 돌보던 양 떼, 네가 그처럼 자랑하던 네 백성이, 지금은 어디에 있느냐?",
    Chn:"你们要举目观看从北方来的人。 先前赐给你的群众， 就是你佳美的群众， 如今在哪里呢？",
    Eng:"Lift up your eyes and see those who are coming from the north. Where is the flock that was entrusted to you, the sheep of which you boasted?",
    Ind:"Layangkanlah matamu, hai Yerusalem, dan lihatlah, ada orang-orang datang dari utara! Di manakah kawanan ternak yang diberikan kepadamu, kambing domba yang menjadi kemuliaanmu?"
  },
  {Bible:"Jeremiah", Chapter:13, Verse:21, Page:1,
    Kor:"네가 손수 기른 자들이 너를 공격하고 지배하면, 네 심정이 어떠하겠느냐? 너는 해산하는 여인처럼, 온갖 진통에 사로잡히지 않겠느냐?",
    Chn:"耶和华立你自己所交的朋友为首，辖制你， 那时你还有什么话说呢？ 痛苦岂不将你抓住像产难的妇人吗？",
    Eng:"What will you say when the LORD sets over you those you cultivated as your special allies? Will not pain grip you like that of a woman in labor?",
    Ind:"Apakah yang kaukatakan, apabila diangkat menjadi kepalamu orang-orang yang kauperlakukan sebagai pacar? Bukankah kesakitan akan menyergap engkau seperti halnya seorang perempuan yang melahirkan?"
  },
  {Bible:"Jeremiah", Chapter:13, Verse:22, Page:1,
    Kor:"그 때에 너는 '어찌하여 내가 이런 신세가 되었는가?' 하고 물을 것이다. 내가 대답하마. 네 치마가 벗겨지고 네 몸이 폭행을 당한 것은, 바로 네가 저지른 많은 죄악 때문이다.\"",
    Chn:"你若心里说：这一切事为何临到我呢？ 你的衣襟揭起， 你的脚跟受伤， 是因你的罪孽甚多。",
    Eng:"And if you ask yourself, \"Why has this happened to me?\"--it is because of your many sins that your skirts have been torn off and your body mistreated.",
    Ind:"Dan apabila engkau bertanya dalam hatimu: \"Mengapakah semuanya ini menimpa aku?\" Karena banyaknya kesalahanmulah maka disingkapkan ujung kainmu dan engkau diperkosa!"
  },
  {Bible:"Jeremiah", Chapter:13, Verse:23, Page:1,
    Kor:"\"a에티오피아 사람이 자기의 피부 색깔을 바꿀 수 있느냐? 표범이 자기의 반점들을 다르게 바꿀 수 있느냐? 만약 그렇게 할 수만 있다면, 죄악에 익숙해진 너희도 선을 행할 수가 있을 것이다. (a 히, '구스 사람'. 나일 강 상류지역 사람)",
    Chn:"古实人岂能改变皮肤呢？ 豹岂能改变斑点呢？ 若能，你们这习惯行恶的便能行善了。",
    Eng:"Can the Ethiopian change his skin or the leopard its spots? Neither can you do good who are accustomed to doing evil.",
    Ind:"Dapatkah orang Etiopia mengganti kulitnya atau macan tutul mengubah belangnya? Masakan kamu dapat berbuat baik, hai orang-orang yang membiasakan diri berbuat jahat?"
  },
  {Bible:"Jeremiah", Chapter:13, Verse:24, Page:1,
    Kor:"그러므로 내가 너희를 사막의 바람에 나부끼는 검불처럼, 산산이 흩어 놓겠다.",
    Chn:"所以我必用旷野的风吹散他们， 像吹过的碎秸一样。",
    Eng:"\"I will scatter you like chaff driven by the desert wind.",
    Ind:"Aku akan menghamburkan mereka seperti sekam yang diterbangkan angin padang gurun."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:25, Page:1,
    Kor:"이것은 너의 몫이며, 내가 너에게 정하여 준 배당이다. 나 주의 말이다. 너는 나를 잊어버리고, 헛된 것을 믿었다.",
    Chn:"耶和华说：这是你所当得的， 是我量给你的分； 因为你忘记我， 倚靠虚假。",
    Eng:"This is your lot, the portion I have decreed for you,\" declares the LORD, \"because you have forgotten me and trusted in false gods.",
    Ind:"Itulah nasibmu, bagianmu yang telah Kuukur untukmu, demikianlah firman TUHAN, karena engkau melupakan Aku, dan mempercayai dusta."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:26, Page:1,
    Kor:"그래서 내가 너의 치마를 얼굴까지 들어 올려서, 너의 수치가 드러나게 하겠다.",
    Chn:"所以我要揭起你的衣襟， 蒙在你脸上， 显出你的丑陋。",
    Eng:"I will pull up your skirts over your face that your shame may be seen--",
    Ind:"Akupun juga akan mengangkat ujung kainmu sampai kepada mukamu, sehingga kelihatan auratmu."
  },
  {Bible:"Jeremiah", Chapter:13, Verse:27, Page:1,
    Kor:"너는 음란하게 소리를 지르며 간음하고, 부끄러운 일들을 하였다. 나는 언덕과 들녘에서, 네가 저지른 역겨운 일들을 보았다. 부정한 예루살렘아, 너에게 화가 미칠 것이다. 언제까지 네가 그렇게 지내려느냐?\"",
    Chn:"你那些可憎恶之事— 就是在田野的山上行奸淫， 发嘶声，做淫乱的事— 我都看见了。 耶路撒冷啊，你有祸了！ 你不肯洁净，还要到几时呢？",
    Eng:"your adulteries and lustful neighings, your shameless prostitution! I have seen your detestable acts on the hills and in the fields. Woe to you, O Jerusalem! How long will you be unclean?\"",
    Ind:"Zinahmu dan ringkikmu, persundalanmu yang mesum di atas bukit-bukit dan di padang-padang, Aku sudah melihat perbuatanmu yang keji itu. Celakalah engkau, hai Yerusalem, berapa lama lagi hingga engkau menjadi tahir?"
  },
]);
