// 하박국 1장 · Habakkuk 1
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Habakkuk",1,17);
BibleDB.add([
  {Bible:"Habakkuk", Chapter:1, Verse:1, Page:1, Kor:"이것은 예언자 하박국이 묵시로 받은 말씀이다.", Chn:"", Eng:"The oracle that Habakkuk the prophet received.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:2, Page:1, Kor:"<하박국의 호소> 살려 달라고 부르짖어도 듣지 않으시고, \"폭력이다!\" 하고 외쳐도 구해 주지 않으시니, 주님, 언제까지 그러실 겁니까?", Chn:"", Eng:"How long, O LORD, must I call for help, but you do not listen? Or cry out to you, \"Violence!\" but you do not save?", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:3, Page:1, Kor:"어찌하여 나로 불의를 보게 하십니까? 어찌하여 악을 그대로 보기만 하십니까? 약탈과 폭력이 제 앞에서 벌어지고, 다툼과 시비가 그칠 사이가 없습니다.", Chn:"", Eng:"Why do you make me look at injustice? Why do you tolerate wrong? Destruction and violence are before me; there is strife, and conflict abounds.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:4, Page:1, Kor:"율법이 해이하고, 공의가 아주 시행되지 못합니다. 악인이 의인을 협박하니, 공의가 왜곡되고 말았습니다.", Chn:"", Eng:"Therefore the law is paralyzed, and justice never prevails. The wicked hem in the righteous, so that justice is perverted.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:5, Page:1, Kor:"<주님의 대답> \"너희는 민족들을 눈여겨 보아라. 놀라고 질겁할 일이 벌어질 것이다. 너희가 살아 있는 동안에, 내가 그 일을 벌이겠다. 너희가 듣고도, 도저히 믿지 못할 일을 벌이겠다.", Chn:"", Eng:"\"Look at the nations and watch--and be utterly amazed. For I am going to do something in your days that you would not believe, even if you were told.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:6, Page:1, Kor:"이제 내가 a바빌로니아 사람을 일으키겠다. 그들은 사납고 성급한 민족이어서, 천하를 주름 잡고 돌아다니며, 남들이 사는 곳을 제 것처럼 차지할 것이다. (a 또는 '갈대아')", Chn:"", Eng:"I am raising up the Babylonians, that ruthless and impetuous people, who sweep across the whole earth to seize dwelling places not their own.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:7, Page:1, Kor:"그들은 두렵고 무서운 백성이다. 자기들이 하는 것만이 정의라고 생각하고, 자기들의 권위만을 내세우는 자들이다.", Chn:"", Eng:"They are a feared and dreaded people; they are a law to themselves and promote their own honor.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:8, Page:1, Kor:"그들이 부리는 말은 표범보다 날쌔고, 해거름에 나타나는 굶주린 늑대보다도 사납다. 그들의 기병은 쏜살같이 달린다. 먼 곳에서 그렇게 달려온다. 먹이를 덮치는 독수리처럼 날쌔게 날아온다.", Chn:"", Eng:"Their horses are swifter than leopards, fiercer than wolves at dusk. Their cavalry gallops headlong; their horsemen come from afar. They fly like a vulture swooping to devour;", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:9, Page:1, Kor:"그들은 폭력을 휘두르러 오는데, 폭력을 앞세우고 와서, 포로를 모래알처럼 많이 사로잡아 갈 것이다.", Chn:"", Eng:"they all come bent on violence. Their hordes advance like a desert wind and gather prisoners like sand.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:10, Page:1, Kor:"그들은 왕들을 업신여기고, 통치자들을 비웃을 것이다. 견고한 성도 모두 우습게 여기고, 흙언덕을 쌓아서 그 성들을 점령할 것이다.", Chn:"", Eng:"They deride kings and scoff at rulers. They laugh at all fortified cities; they build earthen ramps and capture them.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:11, Page:1, Kor:"그러나 제 힘이 곧 하나님이라고 여기는 이 죄인들도 마침내 바람처럼 사라져서 없어질 것이다.\"", Chn:"", Eng:"Then they sweep past like the wind and go on--guilty men, whose own strength is their god.\"", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:12, Page:1, Kor:"<하박국이 다시 호소하다> 주님, 주님께서는 옛날부터 계시지 않으셨습니까? 나의 하나님, 나의 거룩하신 주님, b우리는 죽지 않을 것입니다. 주님, 주님께서는 우리를 심판하시려고 c그를 일으키셨습니다. 반석이신 주님께서는 우리를 벌하시려고 그를 채찍으로 삼으셨습니다. (b 고대 히브리 전통에서는 '주님은 영원히 살아계시는 분이십니다' c 바빌로니아)", Chn:"", Eng:"O LORD, are you not from everlasting? My God, my Holy One, we will not die. O LORD, you have appointed them to execute judgment; O Rock, you have ordained them to punish.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:13, Page:1, Kor:"주님께서는 눈이 맑으시므로, 악을 보시고 참지 못하시며, 패역을 보고 그냥 계시지 못하시는 분입니다. 그런데 어찌하여 배신자들을 보고만 계십니까? 악한 민족이 착한 백성을 삼키어도, 조용히만 계십니까?", Chn:"", Eng:"Your eyes are too pure to look on evil; you cannot tolerate wrong. Why then do you tolerate the treacherous? Why are you silent while the wicked swallow up those more righteous than themselves?", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:14, Page:1, Kor:"주님께서 백성들을 바다의 고기처럼 만드시고 다스리는 자가 없는 바다 피조물처럼 만드시니,", Chn:"", Eng:"You have made men like fish in the sea, like sea creatures that have no ruler.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:15, Page:1, Kor:"d악한 대적이 낚시로 백성을 모두 낚아 올리며, 그물로 백성을 사로잡아 올리며, 좽이로 끌어 모으고는, 좋아서 날뜁니다. (d 바빌로니아 사람)", Chn:"", Eng:"The wicked foe pulls all of them up with hooks, he catches them in his net, he gathers them up in his dragnet; and so he rejoices and is glad.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:16, Page:1, Kor:"그러므로 d그는 그 그물 덕분에 넉넉하게 살게 되고 기름진 것을 먹게 되었다고 하면서, 그물에다가 고사를 지내고, 좽이에다가 향을 살라 바칩니다. (d 바빌로니아 사람)", Chn:"", Eng:"Therefore he sacrifices to his net and burns incense to his dragnet, for by his net he lives in luxury and enjoys the choicest food.", Ind:""},
  {Bible:"Habakkuk", Chapter:1, Verse:17, Page:1, Kor:"그가 그물을 떨고 나서, 곧 이어 무자비하게 뭇 백성을 죽이는데, 그가 이렇게 해도 되는 것입니까?", Chn:"", Eng:"Is he to keep on emptying his net, destroying nations without mercy?", Ind:""},
]);
