// 사사기 8장 · Judges 8
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Judges",8,35);
BibleDB.add([
  {Bible:"Judges", Chapter:8, Verse:1, Page:1,
    Kor:"<기드온이 죽인 미디안 왕들> 그 때에 에브라임 사람들이 기드온에게 말하였다. \"장군께서는 미디안과 싸우러 나가실 때에 우리를 부르지 않으셨는데, 어떻게 우리에게 이렇게 하실 수 있습니까?\" 그들이 기드온에게 거세게 항의하니,",
    Chn:"以法莲人对基甸说：「你去与米甸人争战，没有招我们同去，为什么这样待我们呢？」他们就与基甸大大地争吵。",
    Eng:"Now the Ephraimites asked Gideon, \"Why have you treated us like this? Why didn't you call us when you went to fight Midian?\" And they criticized him sharply.",
    Ind:"Lalu berkatalah orang-orang Efraim kepada Gideon: \"Apa macam perbuatanmu ini terhadap kami! Mengapa engkau tidak memanggil kami, ketika engkau pergi berperang melawan orang Midian?\" Lalu mereka menyesali dia dengan sangat."
  },
  {Bible:"Judges", Chapter:8, Verse:2, Page:1,
    Kor:"그가 그들에게 말하였다. \"이번에 내가 한 일이 당신들이 한 일에 비교나 되겠습니까? 에브라임이 떨어진 포도를 주운 것이 아비에셀이 추수한 것 전부보다 낫지 않습니까?",
    Chn:"基甸对他们说：「我所行的岂能比你们所行的呢？以法莲拾取剩下的葡萄不强过亚比以谢所摘的葡萄吗？",
    Eng:"But he answered them, \"What have I accomplished compared to you? Aren't the gleanings of Ephraim's grapes better than the full grape harvest of Abiezer?",
    Ind:"Jawabnya kepada mereka: \"Apa perbuatanku dalam hal ini, jika dibandingkan dengan kamu? Bukankah pemetikan susulan oleh suku Efraim lebih baik hasilnya dari panen buah anggur kaum Abiezer?"
  },
  {Bible:"Judges", Chapter:8, Verse:3, Page:1,
    Kor:"하나님이 미디안의 우두머리 오렙과 스엡을 당신들의 손에 넘겨 주셨습니다. 그러니 내가 한 일이 어찌 당신들이 한 일에 비교나 되겠습니까?\" 기드온이 이 말을 하니, 그들의 노여움이 풀렸다.",
    Chn:"神已将米甸人的两个首领俄立和西伊伯交在你们手中；我所行的岂能比你们所行的呢？」基甸说了这话，以法莲人的怒气就消了。",
    Eng:"God gave Oreb and Zeeb, the Midianite leaders, into your hands. What was I able to do compared to you?\" At this, their resentment against him subsided.",
    Ind:"Allah telah menyerahkan kedua raja Midian itu, yakni Oreb dan Zeeb, ke dalam tanganmu; apa yang telah dapat kucapai, jika dibandingkan dengan kamu?\" Setelah ia berkata demikian, maka redalah marah mereka terhadap dia."
  },
  {Bible:"Judges", Chapter:8, Verse:4, Page:1,
    Kor:"○기드온이 그가 거느리는 군사 삼백 명과 함께 요단 강을 건너, 지친 몸이지만 계속 적들을 추격하였다.",
    Chn:"基甸和跟随他的三百人到约旦河过渡，虽然疲乏，还是追赶。",
    Eng:"Gideon and his three hundred men, exhausted yet keeping up the pursuit, came to the Jordan and crossed it.",
    Ind:"Ketika Gideon sampai ke sungai Yordan, menyeberanglah ia dan ketiga ratus orang yang bersama-sama dengan dia, meskipun masih lelah, namun mengejar juga."
  },
  {Bible:"Judges", Chapter:8, Verse:5, Page:1,
    Kor:"기드온은 숙곳에 이르렀을 때에 그 곳 사람들에게 사정하였다. \"나를 따르는 군인들이 지쳤으니, 그들에게 빵 덩어리를 좀 주십시오. 나는 미디안의 두 왕 세바와 살문나를 추격하고 있습니다.\"",
    Chn:"基甸对疏割人说：「求你们拿饼来给跟随我的人吃，因为他们疲乏了；我们追赶米甸人的两个王西巴和撒慕拿。」",
    Eng:"He said to the men of Succoth, \"Give my troops some bread; they are worn out, and I am still pursuing Zebah and Zalmunna, the kings of Midian.\"",
    Ind:"Dan berkatalah ia kepada orang-orang Sukot: \"Tolong berikan beberapa roti untuk rakyat yang mengikuti aku ini, sebab mereka telah lelah, dan aku sedang mengejar Zebah dan Salmuna, raja-raja Midian.\""
  },
  {Bible:"Judges", Chapter:8, Verse:6, Page:1,
    Kor:"이 말을 들은 숙곳의 지도자들은 \"우리를 보고 당신의 군대에게 빵을 주라니, 세바와 살문나가 당신의 손아귀에 들기라도 하였다는 말이오?\" 하고 비아냥거렸다.",
    Chn:"疏割人的首领回答说：「西巴和撒慕拿已经在你手里，你使我们将饼给你的军兵吗？」",
    Eng:"But the officials of Succoth said, \"Do you already have the hands of Zebah and Zalmunna in your possession? Why should we give bread to your troops?\"",
    Ind:"Tetapi jawab para pemuka di Sukot itu: \"Sudahkah Zebah dan Salmuna itu ada dalam tanganmu, sehingga kami harus memberikan roti kepada tentaramu?\""
  },
  {Bible:"Judges", Chapter:8, Verse:7, Page:1,
    Kor:"그러자 기드온이 대답하였다. \"좋소! 주님께서 세바와 살문나를 나의 손에 넘겨 주신 뒤에, 내가 들가시와 찔레로 당신들의 살을 찌르고야 말겠소.\"",
    Chn:"基甸说：「耶和华将西巴和撒慕拿交在我手之后，我就用野地的荆条和枳棘打伤你们。」",
    Eng:"Then Gideon replied, \"Just for that, when the LORD has given Zebah and Zalmunna into my hand, I will tear your flesh with desert thorns and briers.\"",
    Ind:"Lalu kata Gideon: \"Kalau begitu, apabila TUHAN menyerahkan Zebah dan Salmuna ke dalam tanganku, aku akan menggaruk tubuhmu dengan duri padang gurun dan onak.\""
  },
  {Bible:"Judges", Chapter:8, Verse:8, Page:1,
    Kor:"거기에서 기드온이 브누엘로 올라가, 그 곳 사람들에게도 같은 사정을 해보았지만, 브누엘 사람들의 대답도 숙곳 사람들의 대답과 같았다.",
    Chn:"基甸从那里上到毗努伊勒，对那里的人也是这样说；毗努伊勒人也与疏割人回答他的话一样。",
    Eng:"From there he went up to Peniel and made the same request of them, but they answered as the men of Succoth had.",
    Ind:"Maka berjalanlah ia dari sana ke Pnuel, dan berkata demikian juga kepada orang-orang Pnuel, tetapi orang-orang inipun menjawabnya seperti orang-orang Sukot."
  },
  {Bible:"Judges", Chapter:8, Verse:9, Page:1,
    Kor:"그래서 그는 브누엘 사람들에게도 \"내가 안전하게 성한 몸으로 돌아오는 날, 이 망대를 헐어 버리고 말겠소\" 하고 말하였다.",
    Chn:"他向毗努伊勒人说：「我平平安安回来的时候，我必拆毁这楼。」",
    Eng:"So he said to the men of Peniel, \"When I return in triumph, I will tear down this tower.\"",
    Ind:"Lalu berkatalah ia juga kepada orang-orang Pnuel: \"Apabila aku kembali dengan selamat, maka aku akan merobohkan menara ini.\""
  },
  {Bible:"Judges", Chapter:8, Verse:10, Page:1,
    Kor:"○그 때에 세바와 살문나는 겨우 만 오천 명의 군대를 데리고, 갈골에 진을 치고 있었다. 이들은 모두 사막 부족의 군대 가운데서 살아 남은 자들인데, 이미 칼 쓰는 군인 십이만 명이 전사하였다.",
    Chn:"那时西巴和撒慕拿，并跟随他们的军队都在加各，约有一万五千人，就是东方人全军所剩下的；已经被杀约有十二万拿刀的。",
    Eng:"Now Zebah and Zalmunna were in Karkor with a force of about fifteen thousand men, all that were left of the armies of the eastern peoples; a hundred and twenty thousand swordsmen had fallen.",
    Ind:"Sementara itu Zebah dan Salmuna ada di Karkor bersama-sama dengan tentara mereka, kira-kira lima belas ribu orang banyaknya, yakni semua orang yang masih tinggal hidup dari seluruh tentara orang-orang dari sebelah timur; banyaknya yang tewas ada seratus dua puluh ribu orang yang bersenjatakan pedang."
  },
  {Bible:"Judges", Chapter:8, Verse:11, Page:1,
    Kor:"기드온은, 장막에 사는 사람들이 다니는 길을 따라 동쪽으로 노바와 욕브하까지 올라가서, 방심하고 있던 적군을 기습하였다.",
    Chn:"基甸就由挪巴和约比哈东边，从住帐棚人的路上去，杀败了米甸人的军兵，因为他们坦然无惧。",
    Eng:"Gideon went up by the route of the nomads east of Nobah and Jogbehah and fell upon the unsuspecting army.",
    Ind:"Gideon maju melalui jalan orang-orang yang diam di dalam kemah di sebelah timur Nobah dan Yogbeha, lalu memukul kalah tentara itu, ketika tentara itu menyangka dirinya aman."
  },
  {Bible:"Judges", Chapter:8, Verse:12, Page:1,
    Kor:"미디안의 두 왕 세바와 살문나가 또 도망치니, 기드온이 그들을 추격하여 세바와 살문나를 사로잡고, 온 군대를 전멸시켰다.",
    Chn:"西巴和撒慕拿逃跑；基甸追赶他们，捉住米甸的二王西巴和撒慕拿，惊散全军。",
    Eng:"Zebah and Zalmunna, the two kings of Midian, fled, but he pursued them and captured them, routing their entire army.",
    Ind:"Zebah dan Salmuna melarikan diri, tetapi Gideon mengejar mereka dan menawan kedua raja Midian itu, yakni Zebah dan Salmuna, sedang seluruh tentara itu diceraiberaikannya."
  },
  {Bible:"Judges", Chapter:8, Verse:13, Page:1,
    Kor:"○요아스의 아들 기드온이 헤레스 비탈길에서 전쟁을 마치고 오다가,",
    Chn:"约阿施的儿子基甸由希列斯坡从阵上回来，",
    Eng:"Gideon son of Joash then returned from the battle by the Pass of Heres.",
    Ind:"Kemudian kembalilah Gideon bin Yoas dari peperangan dengan melalui pendakian Heres;"
  },
  {Bible:"Judges", Chapter:8, Verse:14, Page:1,
    Kor:"숙곳 사람 젊은이 한 명을 포로로 잡아서 캐물으니, 그 젊은이가 일흔일곱 명이나 되는 숙곳의 지도자들과 장로들의 명단을 적어 주었다.",
    Chn:"捉住疏割的一个少年人，问他：「疏割的首领长老是谁？」他就将首领长老七十七个人的名字写出来。",
    Eng:"He caught a young man of Succoth and questioned him, and the young man wrote down for him the names of the seventy-seven officials of Succoth, the elders of the town.",
    Ind:"ditangkapnyalah seorang muda dari penduduk Sukot. Setelah ditanyai, orang itu menuliskan nama para pemuka dan para tua-tua di Sukot untuk Gideon, tujuh puluh tujuh orang banyaknya."
  },
  {Bible:"Judges", Chapter:8, Verse:15, Page:1,
    Kor:"기드온은 숙곳에 이르러 그 곳 사람들에게 말하였다. \"여기 세바와 살문나가 있다. 너희는 나에게 '우리를 보고 당신의 지친 군대에게 빵을 주라니, 세바와 살문나가 당신의 손아귀에 들기라도 하였다는 말이오?' 하면서 나를 조롱하였다.\"",
    Chn:"基甸到了疏割，对那里的人说：「你们从前讥诮我说：『西巴和撒慕拿已经在你手里，你使我们将饼给跟随你的疲乏人吗？』现在西巴和撒慕拿在这里。」",
    Eng:"Then Gideon came and said to the men of Succoth, \"Here are Zebah and Zalmunna, about whom you taunted me by saying, 'Do you already have the hands of Zebah and Zalmunna in your possession? Why should we give bread to your exhausted men?'\"",
    Ind:"Lalu pergilah Gideon kepada orang-orang Sukot sambil berkata: \"Inilah Zebah dan Salmuna yang karenanya kamu telah mencela aku dengan berkata: Sudahkah Zebah dan Salmuna itu ada dalam tanganmu, sehingga kami harus memberikan roti kepada orang-orangmu yang lelah itu?\""
  },
  {Bible:"Judges", Chapter:8, Verse:16, Page:1,
    Kor:"기드온은 그 성읍의 장로들을 체포한 다음에, 들가시와 찔레를 가져다가, 숙곳 사람들을 응징하였다.",
    Chn:"于是捉住那城内的长老，用野地的荆条和枳棘责打疏割人；",
    Eng:"He took the elders of the town and taught the men of Succoth a lesson by punishing them with desert thorns and briers.",
    Ind:"Lalu ia mengumpulkan para tua-tua kota itu, ia mengambil duri padang gurun dan onak, dan menghajar orang-orang Sukot dengan itu."
  },
  {Bible:"Judges", Chapter:8, Verse:17, Page:1,
    Kor:"그리고 그는 브누엘의 망대도 헐고, 그 성읍 사람들을 죽였다.",
    Chn:"又拆了毗努伊勒的楼，杀了那城里的人。",
    Eng:"He also pulled down the tower of Peniel and killed the men of the town.",
    Ind:"Juga menara Pnuel dirobohkannya dan dibunuhnya orang-orang kota itu."
  },
  {Bible:"Judges", Chapter:8, Verse:18, Page:1,
    Kor:"○그런 다음에 그는 세바와 살문나에게 물었다. \"너희가 다볼에서 죽인 사람들은 어떻게 생겼더냐?\" 그들이 대답하였다. \"그들은 당신처럼 하나 하나가 왕자와 같았습니다.\"",
    Chn:"基甸问西巴和撒慕拿说：「你们在他泊山所杀的人是什么样式？」回答说：「他们好像你，各人都有王子的样式。」",
    Eng:"Then he asked Zebah and Zalmunna, \"What kind of men did you kill at Tabor?\" \"Men like you,\" they answered, \"each one with the bearing of a prince.\"",
    Ind:"Kemudian bertanyalah ia kepada Zebah dan Salmuna: \"Di manakah orang-orang yang telah kamu bunuh di Tabor itu?\" Jawab mereka: \"Mereka itu serupa dengan engkau, sikap mereka masing-masing seperti anak raja.\""
  },
  {Bible:"Judges", Chapter:8, Verse:19, Page:1,
    Kor:"기드온이 말하였다. \"그들은 나의 어머니에게서 난 형제들이다. 주님의 살아 계심을 두고 맹세하지만, 너희가 그들을 살려 주기만 하였더라도 내가 너희를 죽이지는 않을 것이다.\"",
    Chn:"基甸说：「他们是我同母的弟兄，我指着永生的耶和华起誓，你们从前若存留他们的性命，我如今就不杀你们了。」",
    Eng:"Gideon replied, \"Those were my brothers, the sons of my own mother. As surely as the LORD lives, if you had spared their lives, I would not kill you.\"",
    Ind:"Lalu kata Gideon: \"Saudara-saudarakulah itu, anak-anak ibuku! Demi TUHAN yang hidup, seandainya kamu membiarkan mereka hidup, aku tidak akan membunuh kamu.\""
  },
  {Bible:"Judges", Chapter:8, Verse:20, Page:1,
    Kor:"기드온은 맏아들 예델에게, 어서 그들을 죽이라고 명하였다. 그러나 그는 아직 어리고 두려워서 칼을 뽑지 못하였다.",
    Chn:"于是对他的长子益帖说：「你起来杀他们。」但益帖因为是童子，害怕，不敢拔刀。",
    Eng:"Turning to Jether, his oldest son, he said, \"Kill them!\" But Jether did not draw his sword, because he was only a boy and was afraid.",
    Ind:"Katanya kepada Yeter, anak sulungnya: \"Bangunlah, bunuhlah mereka.\" Tetapi orang muda itu tidak menghunus pedangnya, karena ia takut, sebab ia masih muda."
  },
  {Bible:"Judges", Chapter:8, Verse:21, Page:1,
    Kor:"그러자 세바와 살문나가 기드온에게 말하였다. \"사내 대장부답게 네가 직접 우리를 쳐라.\" 기드온이 일어나 세바와 살문나를 쳐서 죽이고, 그들이 타던 낙타의 목에서 초승달 모양의 장식을 떼어 가졌다.",
    Chn:"西巴和撒慕拿说：「你自己起来杀我们吧！因为人如何，力量也是如何。」基甸就起来，杀了西巴和撒慕拿，夺获他们骆驼项上戴的月牙圈。",
    Eng:"Zebah and Zalmunna said, \"Come, do it yourself. 'As is the man, so is his strength.'\" So Gideon stepped forward and killed them, and took the ornaments off their camels' necks.",
    Ind:"Lalu kata Zebah dan Salmuna: \"Bangunlah engkau sendiri dan paranglah kami, sebab seperti orangnya, demikian pula kekuatannya.\" Maka bangunlah Gideon, dibunuhnya Zebah dan Salmuna, kemudian diambilnya bulan-bulanan yang ada pada leher unta mereka."
  },
  {Bible:"Judges", Chapter:8, Verse:22, Page:1,
    Kor:"○그 뒤에 이스라엘 사람들이 기드온에게 말하였다. \"장군께서 우리를 미디안의 손에서 구하여 주셨으니, 장군께서 우리를 다스리시고, 대를 이어 아들과 손자가 우리를 다스리게 하여 주십시오.\"",
    Chn:"以色列人对基甸说：「你既救我们脱离米甸人的手，愿你和你的儿孙管理我们。」",
    Eng:"The Israelites said to Gideon, \"Rule over us--you, your son and your grandson--because you have saved us out of the hand of Midian.\"",
    Ind:"Kemudian berkatalah orang Israel kepada Gideon: \"Biarlah engkau memerintah kami, baik engkau baik anakmu maupun cucumu, sebab engkaulah yang telah menyelamatkan kami dari tangan orang Midian.\""
  },
  {Bible:"Judges", Chapter:8, Verse:23, Page:1,
    Kor:"그러나 기드온은 그들에게 말하였다. \"나는 여러분을 다스리지 않을 것입니다. 나의 아들도 여러분을 다스리지 않을 것입니다. 오직 주님께서 여러분을 다스리실 것입니다.\"",
    Chn:"基甸说：「我不管理你们，我的儿子也不管理你们，惟有耶和华管理你们。」",
    Eng:"But Gideon told them, \"I will not rule over you, nor will my son rule over you. The LORD will rule over you.\"",
    Ind:"Jawab Gideon kepada mereka: \"Aku tidak akan memerintah kamu dan juga anakku tidak akan memerintah kamu tetapi TUHAN yang memerintah kamu.\""
  },
  {Bible:"Judges", Chapter:8, Verse:24, Page:1,
    Kor:"기드온은 말을 계속하였다. \"여러분에게 한 가지 청이 있습니다. 각 사람이 얻은 전리품 가운데서 귀고리 하나씩을 나에게 주십시오.\" 미디안 군은 이스마엘 사람들이므로, 모두 금 귀고리를 달고 있었다.",
    Chn:"基甸又对他们说：「我有一件事求你们：请你们各人将所夺的耳环给我。」（原来仇敌是以实玛利人，都是戴金耳环的。）",
    Eng:"And he said, \"I do have one request, that each of you give me an earring from your share of the plunder.\" (It was the custom of the Ishmaelites to wear gold earrings.)",
    Ind:"Selanjutnya kata Gideon kepada mereka: \"Satu hal saja yang kuminta kepadamu: Baiklah kamu masing-masing memberikan anting-anting dari jarahannya.\" --Karena musuh itu beranting-anting mas, sebab mereka orang Ismael."
  },
  {Bible:"Judges", Chapter:8, Verse:25, Page:1,
    Kor:"그들은 \"기꺼이 드리겠습니다\" 하고 말하면서, 겉옷을 펴고, 저마다 전리품 가운데서 귀고리 하나씩을 거기에 던졌다.",
    Chn:"他们说：「我们情愿给你」，就铺开一件外衣，各人将所夺的耳环丢在其上。",
    Eng:"They answered, \"We'll be glad to give them.\" So they spread out a garment, and each man threw a ring from his plunder onto it.",
    Ind:"Jawab mereka: \"Kami mau memberikannya dengan suka hati.\" Dan setelah dihamparkan sehelai kain, maka masing-masing melemparkan anting-anting dari jarahannya ke atas kain itu."
  },
  {Bible:"Judges", Chapter:8, Verse:26, Page:1,
    Kor:"그의 요청으로 들어온 금 귀고리의 무게가 금 천칠백 세겔이나 되었다. 그 밖에도 초승달 모양의 장식품과 패물들, 미디안 왕들이 입었던 자주색 옷과 낙타 목에 둘렀던 사슬이 있었다.",
    Chn:"基甸所要出来的金耳环重一千七百舍客勒金子。此外还有米甸王所戴的月环、耳坠，和所穿的紫色衣服，并骆驼项上的金链子。",
    Eng:"The weight of the gold rings he asked for came to seventeen hundred shekels, not counting the ornaments, the pendants and the purple garments worn by the kings of Midian or the chains that were on their camels' necks.",
    Ind:"Adapun berat anting-anting emas yang dimintanya itu ada seribu tujuh ratus syikal emas, belum terhitung bulan-bulanan, perhiasan telinga dan pakaian kain ungu muda yang dipakai oleh raja-raja Midian, dan belum terhitung kalung rantai yang ada pada leher unta mereka."
  },
  {Bible:"Judges", Chapter:8, Verse:27, Page:1,
    Kor:"기드온은 이것들을 가지고 에봇 하나를 만들어, 자기가 사는 오브라 성읍에 두었다. 그러자 온 이스라엘이 그 곳에서 그것을 음란하게 섬겨서, 그것이 기드온과 그 집안에 올가미가 되었다.",
    Chn:"基甸以此制造了一个以弗得，设立在本城俄弗拉。后来以色列人拜那以弗得行了邪淫；这就作了基甸和他全家的网罗。",
    Eng:"Gideon made the gold into an ephod, which he placed in Ophrah, his town. All Israel prostituted themselves by worshiping it there, and it became a snare to Gideon and his family.",
    Ind:"Kemudian Gideon membuat efod dari semuanya itu dan menempatkannya di kotanya, di Ofra. Di sanalah orang Israel berlaku serong dengan menyembah efod itu; inilah yang menjadi jerat bagi Gideon dan seisi rumahnya."
  },
  {Bible:"Judges", Chapter:8, Verse:28, Page:1,
    Kor:"○이와 같이 하여 미디안은 이스라엘 사람에게 복종하게 되었고, 다시는 고개를 들지 못하였다. 기드온이 사는 사십 년 동안, 그 땅은 전쟁이 없이 평온하였다.",
    Chn:"这样，米甸人被以色列人制伏了，不敢再抬头。基甸还在的日子，国中太平四十年。",
    Eng:"Thus Midian was subdued before the Israelites and did not raise its head again. During Gideon's lifetime, the land enjoyed peace forty years.",
    Ind:"Demikianlah orang Midian tunduk kepada orang Israel dan tidak dapat menegakkan kepalanya lagi; maka amanlah negeri itu empat puluh tahun lamanya pada zaman Gideon."
  },
  {Bible:"Judges", Chapter:8, Verse:29, Page:1,
    Kor:"<기드온이 죽다> ○요아스의 아들 여룹바알은 자기 집으로 돌아가서 살았다.",
    Chn:"约阿施的儿子耶路·巴力回去，住在自己家里。",
    Eng:"Jerub-Baal son of Joash went back home to live.",
    Ind:"Lalu Yerubaal bin Yoas pergilah dan diam di rumahnya sendiri."
  },
  {Bible:"Judges", Chapter:8, Verse:30, Page:1,
    Kor:"그런데 기드온은 아내가 많아, 친아들이 일흔 명이나 되었다.",
    Chn:"基甸有七十个亲生的儿子，因为他有许多的妻。",
    Eng:"He had seventy sons of his own, for he had many wives.",
    Ind:"Gideon mempunyai tujuh puluh anak laki-laki, semuanya anak kandungnya, sebab ia beristeri banyak;"
  },
  {Bible:"Judges", Chapter:8, Verse:31, Page:1,
    Kor:"또 세겜에 있는 첩과의 사이에서 아들이 하나 태어났는데, 그 아들에게는 아비멜렉이라는 이름을 지어 주었다.",
    Chn:"他的妾住在示剑，也给他生了一个儿子。基甸与他起名叫亚比米勒。",
    Eng:"His concubine, who lived in Shechem, also bore him a son, whom he named Abimelech.",
    Ind:"juga gundiknya yang tinggal di Sikhem melahirkan seorang anak laki-laki baginya, lalu ia memberikan nama Abimelekh kepada anak itu."
  },
  {Bible:"Judges", Chapter:8, Verse:32, Page:1,
    Kor:"요아스의 아들 기드온은 나이가 많을 때까지 잘 살다가, 죽어서 아비에셀 사람의 땅 오브라에 있는 그의 아버지 요아스의 무덤에 묻혔다.",
    Chn:"约阿施的儿子基甸，年纪老迈而死，葬在亚比以谢族的俄弗拉，在他父亲约阿施的坟墓里。",
    Eng:"Gideon son of Joash died at a good old age and was buried in the tomb of his father Joash in Ophrah of the Abiezrites.",
    Ind:"Gideon bin Yoas mati pada waktu rambutnya telah putih, lalu dikuburkan dalam kubur Yoas, ayahnya, di Ofra kota orang Abiezer."
  },
  {Bible:"Judges", Chapter:8, Verse:33, Page:1,
    Kor:"기드온이 죽으니, 이스라엘 자손이 다시 바알들을 음란하게 섬기고, 바알브릿을 자기들의 신으로 삼았다.",
    Chn:"基甸死后，以色列人又去随从诸巴力行邪淫，以巴力·比利土为他们的神。",
    Eng:"No sooner had Gideon died than the Israelites again prostituted themselves to the Baals. They set up Baal-Berith as their god and",
    Ind:"Setelah Gideon mati, kembalilah orang Israel berjalan serong dengan mengikuti para Baal dan membuat Baal-Berit menjadi allah mereka;"
  },
  {Bible:"Judges", Chapter:8, Verse:34, Page:1,
    Kor:"이스라엘 자손은 주위의 모든 적으로부터 자기들을 건져 내신 주 하나님을 기억하지 않았다.",
    Chn:"以色列人不记念耶和华—他们的　神，就是拯救他们脱离四围仇敌之手的，",
    Eng:"did not remember the LORD their God, who had rescued them from the hands of all their enemies on every side.",
    Ind:"orang Israel tidak ingat kepada TUHAN, Allah mereka, yang telah melepaskan mereka dari tangan semua musuhnya di sekelilingnya,"
  },
  {Bible:"Judges", Chapter:8, Verse:35, Page:1,
    Kor:"또 여룹바알이라고도 하는 기드온이 이스라엘에게 선을 베풀었지만, 아무도 그 가족에게 은혜를 갚지 않았다.",
    Chn:"也不照着耶路·巴力，就是基甸向他们所施的恩惠厚待他的家。",
    Eng:"They also failed to show kindness to the family of Jerub-Baal (that is, Gideon) for all the good things he had done for them.",
    Ind:"juga tidak menunjukkan terima kasihnya kepada keturunan Yerubaal-Gideon seimbang dengan segala yang baik yang telah dilakukannya kepada orang Israel."
  },
]);
