// 사사기 17장 · Judges 17
// [절 수] 아래 숫자를 이 장의 마지막 절 번호로 고치세요.
BibleDB.ref("Judges",17,13);
BibleDB.add([
  {Bible:"Judges", Chapter:17, Verse:1, Page:1, Kor:"<미가 집의 제사장> 에브라임 산간지방에 미가라는 사람이 있었다.", Chn:"", Eng:"Now a man named Micah from the hill country of Ephraim", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:2, Page:1, Kor:"그가 어머니에게 말하였다. \"누군가가 은돈 천백 냥을 훔쳐 갔을 때에, 어머니는 그 훔친 사람을 저주하셨습니다. 나도 이 귀로 직접 들었습니다. 보십시오, 그 은돈이 여기 있습니다. 바로 내가 그것을 가져 갔습니다.\" 그러자 그의 어머니는 도리어 이렇게 말하였다. \"얘야, 주님께서 너에게 복 주시기를 바란다.\"", Chn:"", Eng:"said to his mother, \"The eleven hundred shekels of silver that were taken from you and about which I heard you utter a curse--I have that silver with me; I took it.\" Then his mother said, \"The LORD bless you, my son!\"", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:3, Page:1, Kor:"그는 은돈 천백 냥을 어머니에게 내놓았다. 그러자 그의 어머니가 말하였다. \"나의 아들이 저주를 받지 않도록, 이 은돈을 주님께 거룩하게 구별하여 바치겠다. 이 돈은 은을 입힌 목상을 만드는 데 쓰도록 하겠다. 그러니 이 은돈을 너에게 다시 돌려 주마.\"", Chn:"", Eng:"When he returned the eleven hundred shekels of silver to his mother, she said, \"I solemnly consecrate my silver to the LORD for my son to make a carved image and a cast idol. I will give it back to you.\"", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:4, Page:1, Kor:"그러나 미가는 그 돈을 어머니에게 돌려 주었다. 그의 어머니가 은돈 이백 냥을 은장이에게 주어, 조각한 목상에 은을 입힌 우상을 만들게 하였는데, 그것을 미가의 집에 놓아 두었다.", Chn:"", Eng:"So he returned the silver to his mother, and she took two hundred shekels of silver and gave them to a silversmith, who made them into the image and the idol. And they were put in Micah's house.", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:5, Page:1, Kor:"○미가라는 이 사람은 개인 신당을 가지고 있었다. 에봇과 드라빔 신상도 만들고, 자기 아들 가운데서 하나를 제사장으로 삼았다.", Chn:"", Eng:"Now this man Micah had a shrine, and he made an ephod and some idols and installed one of his sons as his priest.", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:6, Page:1, Kor:"그 때에는 이스라엘에 왕이 없었으므로, 사람들은 저마다 자기의 뜻에 맞는 대로 하였다.", Chn:"", Eng:"In those days Israel had no king; everyone did as he saw fit.", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:7, Page:1, Kor:"○유다 지파에 속한 유다 땅 베들레헴에 한 젊은이가 있었는데, 그는 레위 사람으로서 그 곳에서 잠시 살고 있었다.", Chn:"", Eng:"A young Levite from Bethlehem in Judah, who had been living within the clan of Judah,", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:8, Page:1, Kor:"그 사람이 자기가 살던 유다 땅 베들레헴을 떠나서 있을 곳을 찾다가, 에브라임 산간지방까지 와서, 미가의 집에 이르렀다.", Chn:"", Eng:"left that town in search of some other place to stay. On his way he came to Micah's house in the hill country of Ephraim.", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:9, Page:1, Kor:"미가가 그에게 물었다. \"젊은이는 어디서 오시는 길이오?\" 그가 대답하였다. \"나는 유다 땅 베들레헴에 사는 레위 사람인데, 있을 곳을 찾아다니고 있습니다.\"", Chn:"", Eng:"Micah asked him, \"Where are you from?\" \"I'm a Levite from Bethlehem in Judah,\" he said, \"and I'm looking for a place to stay.\"", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:10, Page:1, Kor:"미가가 그에게 말하였다. \"우리 집에 살면서, 어른이 되어 주시고, 제사장이 되어 주십시오. 일 년에 은돈 열 냥을 드리고, 옷과 먹거리를 드리겠습니다.\" 이 말을 듣고 그 젊은 레위 사람은 안으로 들어갔다.", Chn:"", Eng:"Then Micah said to him, \"Live with me and be my father and priest, and I'll give you ten shekels of silver a year, your clothes and your food.\"", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:11, Page:1, Kor:"그 젊은 레위 사람은 미가와 함께 살기로 하고, 미가의 친아들 가운데 하나처럼 되었다.", Chn:"", Eng:"So the Levite agreed to live with him, and the young man was to him like one of his sons.", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:12, Page:1, Kor:"미가가 그 레위 사람을 거룩하게 구별하여 세우니, 그 젊은이는 미가 집안의 제사장이 되어, 그의 집에서 살았다.", Chn:"", Eng:"Then Micah installed the Levite, and the young man became his priest and lived in his house.", Ind:""},
  {Bible:"Judges", Chapter:17, Verse:13, Page:1, Kor:"그래서 미가는, 자기가 이제 레위 사람을 제사장으로 삼았으니, 주님께서 틀림없이 자기에게 복을 주실 것이라고 생각하였다.", Chn:"", Eng:"And Micah said, \"Now I know that the LORD will be good to me, since this Levite has become my priest.\"", Ind:""},
]);
